add AIX mounts information
ansible/ansible pull request #10431
Opened 2015-03-11 16:07 UTC by bmanojlovic

example snippet what it now can return
```
        "ansible_mounts": [                                                                                   
            {                                                                                                 
                "device": "/dev/hd4",
                "fstype": "jfs2",                                                                                    
                "mount": "/",                                                                                    
                "options": "rw,log=/dev/hd8",                                                                        
                "time": "Sep 30 13:00"
            }, 
....  
           {
                "device": "/dev/fslv01",
                "fstype": "jfs2",
                "mount": "/var/xxx",
                "options": "rw,log=/dev/loglv00",
                "time": "Sep 30 13:00"
            },
            {
                "device": "10.10.10.33:/install/exported",
                "fstype": "nfs3",
                "mount": "/testmount",
                "options": "",
                "time": "Mar 11 15:22"
            }
```

2015-07-29 16:16 UTC, amenonsen commented
Well, this seems reasonable enough. Of course I have no way to test it. Just a couple of very minor nits: (a) the code runs mount but ignores ``rc`` and ``err``. I notice that a lot of other places in ``facts.py`` do the same thing, though. Sometimes they check ``rc``, and sometimes the whole thing is wrapped in ``try``. So I suppose I can't really blame this patch for followig existing precedent, but I don't like it; (b) ``startswith('/')`` is more straightforward than ``re.match('^/', …)``, but that also hardly matters.

(Aside: am I the only one who would like to see an example in the source comments of the kind of output that's being parsed by code such as this? I know it would bloat facts.py further to do this in more than a handful of cases, but it would make it so much easier to review code/fix bugs.)

2015-07-29 18:01 UTC, bmanojlovic commented
regarding comment in code i can push it if there is need, but this is output i had to parse
```
  node       mounted        mounted over    vfs       date        options      
-------- ---------------  ---------------  ------ ------------ --------------- 
         /dev/hd4         /                jfs2   May 21 10:40 rw,log=/dev/hd8 
         /dev/hd2         /usr             jfs2   May 21 10:40 rw,log=/dev/hd8 
         /dev/hd9var      /var             jfs2   May 21 10:40 rw,log=/dev/hd8 
         /dev/hd3         /tmp             jfs2   May 21 10:40 rw,log=/dev/hd8 
         /dev/hd1         /home            jfs2   May 21 10:40 rw,log=/dev/hd8 
         /dev/hd11admin   /admin           jfs2   May 21 10:40 rw,log=/dev/hd8 
         /proc            /proc            procfs May 21 10:40 rw              
         /dev/hd10opt     /opt             jfs2   May 21 10:40 rw,log=/dev/hd8 
         /dev/livedump    /var/adm/ras/livedump jfs2   May 21 10:40 rw,log=/dev/hd8 
         /dev/homedb2     /db2/home        jfs2   May 21 10:40 rw,log=/dev/loghome
         /dev/bckpdb2     /db2/backup      jfs2   May 21 10:40 rw,log=/dev/loghome
         /dev/logmdb2     /db2/logmirror   jfs2   May 21 10:40 rw,log=/dev/loghome
         /dev/path        /db2/dbpath      jfs2   May 21 10:40 rw,log=/dev/logpath
         /dev/loglv       /db2/log         jfs2   May 21 10:40 rw,log=/dev/loglog
         /dev/dataalv     /db2/dataa1      jfs2   May 21 10:40 rw,log=/dev/logdvg
         /dev/datablv     /db2/datab1      jfs2   May 21 10:40 rw,log=/dev/logdvg
         /dev/dataclv     /db2/datac1      jfs2   May 21 10:40 rw,log=/dev/logdvg
         /dev/datadlv     /db2/datad1      jfs2   May 21 10:40 rw,log=/dev/logdvg
         /dev/fslv00      /db2/export      jfs2   May 21 10:40 rw,log=/dev/loglv01
10.222.22.2 /db2/import      /db2/linux-nfs   nfs3   May 22 14:22                 
10.222.22.22 /db2/import      /db2/sdx-nfs     nfs3   Jun 25 10:50                 
10.222.22.222 /db2/import      /db2/sdx         nfs3   Jul 13 14:00                 
```

2017-01-06 20:08 UTC, bmanojlovic commented
!needs_rebase

2017-01-10 12:32 UTC, molekuul commented
please re-adjust the code for nfs and cifs filesystems, while there can be mount options on these filesystems as shown below:
```$ mount
  node       mounted        mounted over    vfs       date        options
-------- ---------------  ---------------  ------ ------------ ---------------
         /dev/hd4         /                jfs2   Dec 10 15:23 rw,log=/dev/hd8
         /dev/hd2         /usr             jfs2   Dec 10 15:23 rw,log=/dev/hd8
         /dev/hd9var      /var             jfs2   Dec 10 15:23 rw,log=/dev/hd8
         /dev/hd3         /tmp             jfs2   Dec 10 15:23 rw,log=/dev/hd8
         /proc            /proc            procfs Dec 10 15:24 rw
         /dev/hd1         /home            jfs2   Dec 10 15:24 rw,log=/dev/hd8
         /dev/hd10opt     /opt             jfs2   Dec 10 15:24 rw,log=/dev/hd8
         /dev/hd11admin   /admin           jfs2   Dec 10 15:24 rw,log=/dev/hd8
         /dev/livedump    /var/adm/ras/livedump jfs2   Dec 10 15:24 rw,log=/dev/hd8
         /dev/aixcaplv01  /appl/aixcap     jfs2   Dec 10 15:24 rw,log=/dev/midware_l2
         /dev/NIMDATA_lv01 /export/nim      jfs2   Dec 10 15:24 rw,log=/dev/NIMDATA_loglv
         /dev/NIMIMAG_lv02 /export/nim/appliances jfs2   Dec 10 15:24 rw,log=/dev/NIMIMAG_loglv
         /dev/fix2010-02_lv /export/nim/fix2010-02 jfs2   Dec 10 15:24 rw,log=INLINE
         /dev/NIMIMAG_lv01 /export/nim/images jfs2   Dec 10 15:24 rw,log=/dev/NIMIMAG_loglv
         /dev/NIMDRDCR_lv02 /export/nim/mksysb/DCR/DTA jfs2   Dec 10 15:24 rw,log=/dev/NIMDRDCR_loglv
         /dev/NIMDRDCR_lv01 /export/nim/mksysb/DCR/P jfs2   Dec 10 15:24 rw,log=/dev/NIMDRDCR_loglv
         /dev/NIMLOG_lv01 /export/nim/mksysb/log jfs2   Dec 10 15:24 rw,log=/dev/NIMDRDCR_loglv
         /dev/NIMTO_lv01  /opt/nimtools    jfs2   Dec 10 15:24 rw,log=/dev/midware_l2
         /dev/REPOSP_lv02 /release_management/hardware jfs2   Dec 10 15:24 rw,log=/dev/REPOSP_loglv
         /dev/REPOSP_lv01 /release_management/repository jfs2   Dec 10 15:24 rw,log=/dev/REPOSP_loglv
         /dev/REPOSP_lv03 /release_management/special jfs2   Dec 10 15:24 rw,log=/dev/REPOSP_loglv
         /dev/REPOSP_lv04 /release_management/wia jfs2   Dec 10 15:24 rw,log=/dev/REPOSP_loglv
         /dev/rhome_lv    /root            jfs2   Dec 10 15:24 rw,log=/dev/hd8
         /dev/tftp_lv     /tftpboot        jfs2   Dec 10 15:24 rw,log=/dev/hd8
         /dev/ecc_lv      /usr/ecc         jfs2   Dec 10 15:24 rw,log=/dev/hd8
         /dev/ulocal_lv   /usr/local       jfs2   Dec 10 15:24 rw,log=/dev/hd8
         /dev/tiv_lcf_lv  /usr/local/Tivoli/lcf jfs2   Dec 10 15:24 rw,log=/dev/hd8
         /dev/uuc_acct_lv01 /uuc_accept/2013_1 jfs2   Dec 10 15:24 rw,log=INLINE
         /dev/uuc_repos_lv01 /uuc_repos/2013_1 jfs2   Dec 10 15:24 rw,log=INLINE
         /dev/nmon_lv     /var/adm/nmon    jfs2   Dec 10 15:24 rw,log=/dev/hd8
         /dev/core_lv     /var/core        jfs2   Dec 10 15:24 rw,log=/dev/hd8
         /dev/vlocal_lv   /var/local       jfs2   Dec 10 15:24 rw,log=/dev/hd8
         /dev/NIMDATA_lv22 /export/nim/aix6109-04 jfs2   Dec 10 15:24 rw,log=INLINE
         /dev/REPOSP_lv05 /release_management/quality_assurance jfs2   Dec 10 15:24 rw,log=/dev/REPOSP_loglv
         /dev/NIMDATA_lv24 /export/nim/vio2234 jfs2   Dec 10 15:24 rw,log=/dev/NIMDATA_loglv
         /dev/usr_tsm_lv  /usr/tivoli/tsm  jfs2   Dec 10 15:24 rw,log=INLINE
         /dev/log_tsm_lv  /var/log/tsm     jfs2   Dec 10 15:24 rw,log=INLINE
         /dev/aix6109-06_lv01 /export/nim/aix6109-06 jfs2   Dec 10 15:24 rw,log=/dev/NIMDATA_loglv
         /dev/uuc_arc_lv  /uuc_arc/2013_1  jfs2   Dec 10 15:24 rw,log=/dev/REPOSP_loglv
         /dev/opt_tem     /opt/BESClient   jfs2   Dec 10 15:24 rw,log=INLINE
         /dev/var_tem     /var/opt/BESClient jfs2   Dec 10 15:24 rw,log=INLINE
         /dev/aix7104-03_lv01 /export/nim/aix7104-03 jfs2   Dec 10 15:24 rw,log=/dev/NIMDATA_loglv
         /dev/vios22370_lv01 /export/nim/vio22370 jfs2   Dec 10 15:24 rw,log=/dev/NIMDATA_loglv
         /dev/opt_itm     /opt/IBM/ITM     jfs2   Dec 15 10:16 rw,log=INLINE
nfsserv  /nfsexport     /mnt               nfs3   Jan 10 13:09 ro
```

2017-01-10 14:32 UTC, molekuul requested changes
nfs or cifs filesystems can have mount options

2017-01-12 18:15 UTC, merged