Adding lookup plugin for postgresql database
ansible/ansible pull request #11315
Opened 2015-06-18 15:46 UTC by gshivani

lookup plugin for querying postgresql

2015-06-28 19:55 UTC, msabramo commented
Maybe even more useful would be a more general plugin that uses SQLAlchemy to query the database. Then you could use it with any of the database engines supported by SQLAlchemy. 

Instead of taking username, password, etc., it could take a SQLAlchemy database URL (which probably a lot of people would keep in variables and encrypt with vault).

2015-07-29 05:56 UTC, amenonsen commented
A few quick thoughts: (a) this definitely needs documentation, (b) "connection failed or something's wrong" is a complete non-starter, this is something that may well not work right the first time, and that error would drive me nuts while debugging and not help *at all*.

@msabramo's suggestion to use SQLAlchemy is… well, it's probably the Right Thing To Do™, though I personally don't want to have to install and learn SQLAlchemy and don't need anything but Postgres support. Being able to encrypt and store database connection information is certainly nice, but it's also possible to encrypt and store the ``conninfo`` string for Postgres with this PR already.

2017-07-17 15:13 UTC, bcoca requested changes
I know this has been open a long time, but since previous comments were not addressed we have not returned to it. Now we are trying to close these old issues and if we don't get any response to this review either we'll end up just closing the PR.

2017-07-17 15:13 UTC, bcoca commented on lib/ansible/plugins/lookup/postgresql.py
> +import psycopg2
this needs to be guarded and return an ansible error in the init  (see consul_kv lookup and HAS_CONSUL)

2017-07-17 15:13 UTC, bcoca commented on lib/ansible/plugins/lookup/postgresql.py
> +             raise AnsibleError("Connection Failed or something's wrong")
Adding the exception string to the error would help the user narrow down what the issue is.

2017-07-17 15:13 UTC, bcoca commented on lib/ansible/plugins/lookup/postgresql.py
> +        #Connection to postgresql
lacking parameter validation, user should be notified if the minimal requirements for lookup to work are not met

2018-09-13 21:02 UTC, jstoja commented
@bcoca No answer after +1y, you can probably close it.

2018-10-09 18:33 UTC, ryanmerolle commented
What is required here to make this shippable?  I am interested in this becoming a standard lookup plugin in ansible.

2018-10-09 19:05 UTC, ryanmerolle commented on lib/ansible/plugins/lookup/postgresql.py
> +        }
It likely makes sense to add the remaining psycopg2 parameters including host and port.

2018-10-10 17:51 UTC, gundalow commented
@ryanmerolle PR needs rebasing https://docs.ansible.com/ansible/devel/dev_guide/developing_rebasing.html

It maybe worth you creating a new branch and copying across the new file into that branch

2018-10-11 19:01 UTC, gshivani commented
@ryanmerolle Glad that you are interested in this becoming a standard plugin! I'm not sure if I can get to this soon. Please feel free to create new branch and reuse the code!

2019-03-29 13:28 UTC, Andersson007 commented
needs_info

2019-06-01 18:25 UTC, closed without merging