Integrate EUI64 SLAAC into ipaddr() Jinja2 filter
ansible/ansible pull request #11658
Opened 2015-07-20 15:35 UTC by vctgross

usage: {{ 2db8::/64 | ipaddr(l2addr) }}

- Enforce RFC 4862 5.5.3 and ignore networks with a prefixlen other than 64
- does not require a separate keyword, acts as if l2addr was an index in the
  subnet
- does not work with bare hwaddr (such as "001122334455") to keep templates
  like {{ 2db8::/32 | ipaddr(32) }} working. Better force hwaddr format as in
  {{ 2db8::/64 | ipaddr(l2addr|hwaddr('eui48')) }} when unsure.

2015-07-29 07:00 UTC, amenonsen commented
For such a relatively small change, this took me *ages* to understand. I'm still not sure I understand how the last part, i.e. ``{{ 2db8::/64 | ipaddr(l2addr|hwaddr('eui48')) }}`` works. I think this change is sensible and correct, but it definitely does need documentation somewhere in ``playbooks_filters_ipaddr.rst``.

2017-05-17 14:45 UTC, calfonso commented
@ganeshrn would you mind taking a look at this bug and find out if it's ok to merge?

2017-05-17 15:24 UTC, ganeshrn commented
@calfonso Ack, will take a look.

2017-07-24 07:42 UTC, ganeshrn commented on lib/ansible/plugins/filter/ipaddr.py
> +    v_ip = netaddr.IPAddress(str(v.ip))
this variable is not used anywhere, is it required?

2017-07-24 07:42 UTC, ganeshrn commented on lib/ansible/plugins/filter/ipaddr.py
> +    hw = netaddr.EUI(value);
Semicolon after statement not required

2017-07-24 07:47 UTC, ganeshrn commented on lib/ansible/plugins/filter/ipaddr.py
> +            if hwaddr(query):
The first argument of `hwaddr` is value, however instead `query` is passed.

2017-07-24 07:54 UTC, ganeshrn requested changes
Patch doesn't work on latest devel branch. It is giving below stacktrace.
```
  File "/Users/ansible/lib/ansible/plugins/filter/ipaddr.py", line 985, in hwaddr
    return query_func_map[query](v, *extras)
UnboundLocalError: local variable 'v' referenced before assignment
```
Can you please re-test on latest devel and check if it is working. Also, this PR needs to have relevant documentation in `playbooks_filters_ipaddr.rst` and unit test.

2017-07-31 14:51 UTC, gundalow commented
Closing & reopening to trigger CI

2017-07-31 14:51 UTC, gundalow commented
@vctgross Rebase needed

2017-08-01 17:08 UTC, calfonso commented
Hi!

Thanks very much for your submission to Ansible. It sincerely means a lot to us that you've taken time to contribute.

Unfortunately, we're not sure if we want this feature in the program, and I don't want this to seem confrontational. Our reasons for this are:

Closing due to contributor inactivity.

However, we're absolutely always up for discussion. Since this is a really busy project, we don't always see comments on closed tickets, but want to encourage open dialog. You can stop by the development list, and we'd be glad to talk about it - and we might even be persuaded otherwise!

https://groups.google.com/forum/#!forum/ansible-devel
In the future, sometimes starting a discussion on the development list prior to implementing a feature can make getting things included a little easier, but it's not always necessary.

Thank you once again for this and your interest in Ansible!

2017-08-01 17:08 UTC, closed without merging