Make ModuleArgsParser more understandable
ansible/ansible pull request #13974
Opened 2016-01-19 01:55 UTC by willthames

Both comments and method names for handling new/old
style parameters were switched around

Made comments and method names reflect actual code paths
taken.

2016-01-19 01:56 UTC, bcoca commented on lib/ansible/modules/extras
> +Subproject commit b20cb4dd71425a48e68e0af06039afd2a410cb13
someone snuck in submodule ref changes ?

2016-01-19 02:00 UTC, willthames commented
@bcoca, oops, I updated my commit and it pulled those in. I've removed them now. 'snuck in' is probably an ungenerous term.

2016-01-19 02:07 UTC, bcoca commented
sorry, i get cranky after a full day of triage

2017-01-06 00:57 UTC, willthames commented
ready_for_review

2017-01-06 16:24 UTC, mattclay requested changes
I spotted two other corrections that should be made to the comments.

2017-01-06 16:24 UTC, mattclay commented on lib/ansible/parsing/mod_args.py
>          returns tuple of (module_name, dictionary_args)
The return comment doesn't match the return value. Not a new problem, but should be fixed.

2017-01-06 16:24 UTC, mattclay commented on lib/ansible/parsing/mod_args.py
>              ( 'command', { _raw_params: 'echo hi', _uses_shell: True }
This output comment is incorrect. Also not a new problem, but fix it while you're in the area.

2017-01-13 01:15 UTC, willthames commented
!needs_revision

2017-01-13 01:16 UTC, willthames commented
ready_for_review

2017-01-13 01:16 UTC, willthames commented
@mattclay I fixed your review points and also went a bit further

2017-01-13 02:22 UTC, mattclay approved these changes

2017-01-13 02:22 UTC, merged

2017-01-13 02:23 UTC, mattclay commented
@willthames Merged! Thanks for cleaning this up.