Pass boto_profile to get_route53_records
ansible/ansible pull request #14354
Opened 2016-02-07 02:42 UTC by Jonnymcc

2017-01-27 19:45 UTC, ryansb requested changes

2017-01-27 19:45 UTC, ryansb commented on contrib/inventory/ec2.py
> +        r53_conn = route53.Route53Connection(profile_name=self.boto_profile)
Can you add a conditional so this only gets passed if the boto_profile is set?

2017-02-15 23:22 UTC, willthames commented
shipit - I wish `boto3_conn` (or `connect_to_aws`) worked for route53 (I believe it's one of the few that doesn't, because both rely on the underlying service having a `connect_to_region` type call, and route53 is region agnostic).

2017-02-16 13:49 UTC, ryansb approved these changes

2017-02-16 13:49 UTC, merged