IAM role support for EC2 dynamic inventory
ansible/ansible pull request #15196
Opened 2016-03-29 13:12 UTC by areian

##### ISSUE TYPE
 - Feature Pull Request

##### ANSIBLE VERSION
```
ansible 2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
Tested on both `2.1.0` and `1.9.4`

##### SUMMARY
This change allows the EC2 dynamic inventory to assume an IAM role prior to connecting to the AWS modules.
We needed this functionality at my company due to how we have structured our AWS setup, and I thought others might find it useful.

2016-05-20 13:27 UTC, defionscode commented
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;UPYq68tv&#x2F;6-iam-role-support-for-ec2-dynamic-inventory"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> IAM role support for EC2 dynamic inventory</a>

2016-05-20 16:49 UTC, MichaelBaydoun commented
It would be great if we could do this for the entire playbook, and not just for ec2 dynamic inventory.

2016-05-20 18:03 UTC, ryansb commented
Looks good to me. 

@MichaelBaydoun do you mean for all the other AWS modules? IMO ec2.py is at least a little separate so I wouldn't block this pending IAM support for all other modules.

2016-05-20 20:06 UTC, MichaelBaydoun commented
@ryansb Agreed, I'm not suggesting holding this merge up, it's a good improvement.  Just floating the idea that down the road, it would be great if we had iam role assumption capability in the core, for all the modules.

2016-12-16 16:59 UTC, ryansb requested changes
Tweak on the `if` check, other than that looks good.

2016-12-16 16:59 UTC, ryansb commented on contrib/inventory/ec2.py
> +        if self.iam_role:
This needs a guard, since `self.iam_role` will be unset if the option isn't specified.

2016-12-23 12:28 UTC, areian commented on contrib/inventory/ec2.py
> +        if self.iam_role:
It seemed more in line with the rest of the code to define the variable with a default value in `read_settings`.

2017-02-16 14:52 UTC, ryansb approved these changes

2017-02-16 14:52 UTC, ryansb commented
shipit

2017-02-16 23:20 UTC, willthames commented
shipit

2017-02-17 20:43 UTC, nethershaw commented
-1

This merge would cause regression of https://github.com/ansible/ansible/pull/15890.

2017-02-19 23:08 UTC, willthames commented
@nethershaw it doesn't seem to relate to the change in #15890, so might need some more detail as to how you identified that it would cause such a regression.

2017-02-24 14:37 UTC, HontoNoRoger commented
I tried your changes with current Ansible 2.2.0 with the dynamic inventory from the docs. Works as intended!

The only thing missing was
```python
from boto import sts
```
at the top of `ec2.py` script. Did I overlook that or is it still missing in the PR?

2017-03-10 13:29 UTC, areian commented
@HontoNoRoger You are absolutely correct. An oversight on my part when creating the PR. It has been fixed.

Will fix rebase later today

2017-03-20 21:19 UTC, ryansb approved these changes

2017-03-20 21:19 UTC, merged