Lastpass lookup plugin
ansible/ansible pull request #16285
Opened 2016-06-14 21:10 UTC by azenk

##### ISSUE TYPE
 - New Module Pull Request

##### ANSIBLE VERSION
```
ansible 2.0.2.0
  config file = /home/azenk/ansible/pgc-application-playbooks/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY
This plugin can be used with the lpass cli interface for lastpass.
[lastpass-cli](https://github.com/lastpass/lastpass-cli)

Example:
Add a lookup to your playbooks/variables somewhere:
```
some_variable: "{{ lookup('lpass','Some Lastpass entry name or ID', field='username') }}"
```
Start a lpass session prior to using ansible, run ansible, logout when finished:
```
lpass login user@domain.com
ansible-playbook foo.yml
lpass logout
```

2016-06-14 22:05 UTC, jhawkesworth commented
Interesting idea. I wonder if it would be possible/uaeful to implement as a callback plugin.

2016-06-15 12:48 UTC, azenk commented
I'm not quite sure what the potential benefits to implementing this as a callback plugin rather than a lookup plugin would be.  Can you expand on the thought?

2016-06-15 15:03 UTC, jhawkesworth commented
Probably not many, on reflection, it was just an idle though.  

I created a callback plugin to acquire kerberos credentials for passwordless connection to windows hosts and just thought maybe the same thing could be done for lastpass logins.  But I guess the difference is you might well have lots of lastpass logins for different hosts/services, whereas on windows you typically have a domain login that lets you do whatever you are allowed to do on lots of machines.

2016-06-15 15:32 UTC, bcoca commented
a lookup makes more sense as you can do: 

```
ansible_password: "{{lookup('lastpass' ....
```

the kerberos case is 'special' as it was not really a password but a ticket/token you maintain for the whole communication AFTER having authenticated

2016-06-15 18:54 UTC, jhawkesworth commented
Yeah, lookup makes sense. Callbacks really meant for reporting anyway, so it's bending things to use for Kerberos tickets. Forget that I commented!

2016-06-16 19:49 UTC, azenk commented
While reading the comment from @bcoca it occurred to me that lastpass would be a better name for this plugin, so I'll make that change and clean up some white space issues.

2016-06-18 01:58 UTC, azenk commented
I added some tests and refactored things a little.  It looks like all the tests are passing now.  I think it's ready to go.  I'm happy to make further improvements if requested though.

2016-09-07 19:22 UTC, DebbieGillespie commented
We would really like this feature. Could this pull request be merged?

2016-09-07 19:42 UTC, sivel commented
My 2 cents here.  I would much rather see this use the lastpass API, potentially through something like `lastpass-python` or even just direct API calls instead of shelling out to lastpass-cli.

2016-09-07 19:58 UTC, azenk commented
Are there docs available on that?  I looked for API docs prior to writing this and did not find any mention of anything other than the provisioning API.  This plugin has been working fine for us.  One nice benefit of using the cli, is that the lastpass vault session management is handled outside of ansible.   

Provided the session management could be dealt with properly (not using ansible vault to store my lastpass credentials) I'd be happy to modify this to use the API, if you can point me towards docs.

2016-09-11 14:00 UTC, azenk commented
As far as I can tell, lastpass-python cannot be used without providing your username and password at runtime, which would make the plugin useless for me.  So, I won't be using that.  Apart from shelling out to the cli, are there any other objections to merging this?

2016-09-11 14:30 UTC, georgepsarakis commented
@azenk there is a function for executing shell commands named [run_cmd](https://github.com/ansible/ansible/blob/devel/lib/ansible/utils/cmd_functions.py#L27).

Perhaps it would be preferrable to use this function, instead of using `subprocess.Popen` directly?

2016-09-11 14:43 UTC, georgepsarakis commented
@azenk regarding the API, if I understand correctly from the code, both the CLI and the
`lastpass-python` library make certain HTTP requests that return XML.

I think it should be also noted that `lastpass-python` is not officially supported whereas the CLI is.

2016-09-12 01:30 UTC, azenk commented
@georgepsarakis I could swap run_cmd in, but I'm not sure I see an advantage other than maintaining consistency with other ansible code.

2016-09-12 04:21 UTC, georgepsarakis commented
@azenk yes that is the main reason. Reusing well-tested code in large projects is beneficial, don't you think?

2016-09-12 15:29 UTC, azenk commented
@georgepsarakis Yes, absolutely.  In this case it's slightly problematic since I'd have to build an escaped command string just to have shlex.split return the same list of args that I started with (is there a good way to do this in python 2.x?  3.3 has shlex.quote).  While this is possible, I think the advantages of skipping all that and using Popen directly outweigh the negatives.  It's certainly doable though.

2016-09-26 04:39 UTC, azenk commented
What's the status of this?  I'm not planning to make any revisions to this unless someone offers concrete feedback about changes that are required prior to merging.

2016-11-03 16:08 UTC, azenk commented
Is there any chance this could be merged for 2.3?

2016-12-21 20:21 UTC, Dispader commented
Very excited to have this new feature— anyone have any more thoughts, here?

2016-12-22 07:43 UTC, mattclay requested changes
@azenk Looks good overall. Just one change to how unit tests are implemented should be made.

2016-12-22 07:43 UTC, mattclay commented on lib/ansible/plugins/lookup/lastpass.py
> +        lp = kwargs.get('__mock_lpass_obj', LPass())
Instead of making the plugin aware of the tests, use `mock.patch` to mock the `LPass` class in the tests.

2016-12-22 18:24 UTC, azenk commented
@mattclay I think I've addressed the issue.  I'm a bit of a novice with mock.patch, so please forgive any rookie mistakes, etc.

2016-12-22 20:05 UTC, mattclay requested changes
Could you amend your last commit message to remove the @ mention of me. That should help cut down on spurious notifications on GitHub.

Other than that, and the one requested change, it looks good. Thanks for the quick response to feedback!

2016-12-22 20:05 UTC, mattclay commented on test/units/plugins/lookup/test_lastpass.py
> +from mock import patch
Sorry, I should have mentioned this in my original feedback. Import `patch` using:

```python
from ansible.compat.tests.mock import patch
```

2016-12-22 22:08 UTC, azenk commented
@mattclay  So amended.  I also rolled the import change into the amended commit.

2016-12-22 22:46 UTC, mattclay approved these changes

2016-12-22 22:47 UTC, merged

2016-12-22 22:47 UTC, mattclay commented
@azenk Thanks for the new lookup plugin!