More tolerant unit parsing
ansible/ansible pull request #16748
Opened 2016-07-18 15:51 UTC by Christoph-D

##### ISSUE TYPE
 - Bugfix Pull Request

##### SUMMARY

Issue #16526 shows that there is confusion about the valid units for memory sizes in docker.  This is a proposal to parse the units in a more tolerant way by accepting all of "4MB", "4M", and "4m".  This is backwards-compatible because it accepts strictly more than before.

Also add a test case for the unit parser.

2017-05-31 14:39 UTC, calfonso commented
@Christoph-D This needs to be rebased, then use the basic.py functions. Once that is done and you've verified everything, please close this PR, thanks!

2018-07-01 18:39 UTC, Christoph-D commented
I rebased the PR, it is now much easier and mostly a documentation update. PTAL?

2018-08-05 11:43 UTC, felixfontein commented
@Christoph-D I just found your PR; I did something very similar three weeks ago: #42789

Both our PRs fix #42692, so definitely one of them should be merged. I think yours is better, as it also documents some more valid units :) Except that you should not use backticks, you should use `C(...)` instead to get the documentation formatted correctly.

@kassiansun Can you also take a look? You seem to be the only active `docker_container` maintainer currently...

2018-08-06 00:19 UTC, kassiansun approved these changes

2018-08-06 00:19 UTC, kassiansun commented
shipit

2018-08-10 06:13 UTC, felixfontein requested changes
Except some minimal changes (backticks -> `C(...)` and some more unification), this is great.

2018-08-10 06:13 UTC, felixfontein commented on lib/ansible/modules/cloud/docker/docker_container.py
> +        Unit can be `B` (byte), `K` (kibibyte, 1024B), `M` (mebibyte), `G` (gibibyte),
Please use `C(...)` instead of backticks.

2018-08-10 06:13 UTC, felixfontein commented on lib/ansible/modules/cloud/docker/docker_container.py
> +        `T` (tebibyte), or `P` (pebibyte)."
Same here.

2018-08-10 06:13 UTC, felixfontein commented on lib/ansible/modules/cloud/docker/docker_container.py
> +        `M` (mebibyte), `G` (gibibyte), `T` (tebibyte), or `P` (pebibyte)."
Same here.

2018-08-10 06:13 UTC, felixfontein commented on lib/ansible/modules/cloud/docker/docker_container.py
> +        `T` (tebibyte), or `P` (pebibyte)."
Same here.

2018-08-10 06:13 UTC, felixfontein commented on lib/ansible/modules/cloud/docker/docker_container.py
>        - "Kernel memory limit (format: <number>[<unit>]). Number is a positive integer.
`<number>[<unit>]` should be formatted with `C(...)` as well (everywhere). Currently, backticks are only used for `shm_size` (which should be converted to `C(...)` too).

2018-08-18 11:44 UTC, Christoph-D commented
I changed the backticks to C(...).

2018-08-18 12:13 UTC, felixfontein approved these changes
Assuming you removed the executable attribute, looks good to me! :)

shipit

2018-08-18 12:33 UTC, felixfontein commented
bot_status

2018-08-18 12:59 UTC, felixfontein commented
@kassiansun I guess you have to re-shipit this one.

2018-08-20 00:46 UTC, kassiansun commented
shipit

2018-08-20 19:48 UTC, felixfontein commented
bot_status

2018-08-22 16:54 UTC, felixfontein commented
shipit

2018-08-22 16:54 UTC, felixfontein commented
bot_status

2018-08-22 17:02 UTC, felixfontein commented
yay, progress :tada:

2018-08-22 17:05 UTC, merged

2018-08-22 17:06 UTC, felixfontein commented
@Christoph-D Thank you very much for your contribution! And sorry that it took this long!