add vars_dirs parameter like vars_files
ansible/ansible pull request #17967
Opened 2016-10-11 06:37 UTC by nohi

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
core

##### SUMMARY
add vars_dirs parameter in playbook.
If you specific vars_dirs, all vars files in dirs is included and appended to vars_files.
It helps to manage many vars_files and referrence from many playbook.

##### EXAMPLE

###### dir tree
```
<PLAYBOOK_DIR>
    └── vars_dir
        ├── foo.yml
        ├── bar.yml
        └── hoge.yml
```

###### playbook

_normaly_
```
- hosts: hoge
  vars_files:
    - "vars_dir/foo.yml"
    - "vars_dir/bar.yml"
    - "vars_dir/hoge.yml"
```

_after_
```
- hosts: hoge
  vars_dirs:
    - "vars_dir"
```

2016-10-18 23:27 UTC, jeffwidman commented
You can already accomplish similar things with Roles and also group_vars support folders so anything in those folders get picked up by the group. Using Roles also generally results in more composable/compartmentalized code.

Curious what particular use cases this solves that those don't?

2016-10-19 07:23 UTC, nohi commented
My environment (playbook directory layout, ansible.cfg and command) are as follows.

Directory Layout
```
$CWD/
├── group_vars/
│   └── all/
│       ├── common_foo.yml
│       ├── common_bar.yml
│       └── common_hoge.vault
│
├── inventories/
│   ├── inventory_A/
│   │  ├── group_vars/
│   │  │   ├── db/
│   │  │   ├── web/
│   │  │   └── all/
│   │  │        ├── A_group_var1.yml
│   │  │        └── A_group_var2.yml
│   │  └── inventory
│   │
│   └── inventory_B/
│       ├── group_vars/
│       │   ├── web/
│       │   ├── db/
│       │   └── all/
│       │        ├── B_group_var1.yml
│       │        └── B_group_var2.yml
│       └── inventory
│
├── playbooks
│   ├── hoge
│   │  ├── playbook_A.yml
│   │  └── playbook_B.yml
│   └── .../
│
└── roles/
```


ansible.cfg
```
roles_path    = ./roles:/etc/ansible/roles
```

Commands
```shell
ansible-playbook -i inventories/inventory_A/ playbooks/hoge/playbook_A.yml
ansible-playbook -i inventories/inventory_B/ playbooks/hoge/playbook_B.yml
```

I stored common variables in $CWD/group_vars/* (ex: common firewall rules and yum repository)
and overwrite variables in inventories/HOGE/group_vars/ .

it worked on ansivle v2.1.1.0 or earlier.
but after fixed #16953 , $CWD/group_vars/* files and dir does not workd.

so, I implimented var_dirs take the place of $CWD/group_vars.

2016-10-20 03:45 UTC, bcoca commented
Instead of a new directive, why not make vars_files work with directories?

2016-10-20 05:56 UTC, nohi commented
If you ask me, It was implemented so as not to affect vars_files.
Shoud I change vars_files work with directory?

2016-11-01 03:11 UTC, nohi commented
usage
```
- hosts: hoge
  vars_files:
    - "path/to/vars_dir"
```

2017-07-25 18:28 UTC, calfonso commented
@nohi are you interested in rebasing this feature? We'd also like some documentation around this feature, and tests are always welcome. Please notify us in IRC when this is updated so we are sure to see your update!

2017-07-26 09:31 UTC, nohi commented
@calfonso sorry for my long silence
I rebased and updated doc about this feature.

2017-07-26 13:20 UTC, bcoca commented
FYI, `include_vars` already supports directories with the added feature of filtering for specific files.

2017-08-04 07:37 UTC, nohi commented
@bcoca Thank you for your information.
maybe, is ```vars_files```  not often used?
I've thought that ```include_vars``` is often used in specific task, and ```vars_files``` is used as common variables for each task.

2017-08-04 19:06 UTC, bcoca commented
no, but it works NOW

2017-08-04 19:11 UTC, bcoca requested changes

2017-08-04 19:11 UTC, bcoca commented on lib/ansible/vars/manager.py
> +                # if 'vars_files' is directory, all files in dir are appended to vars_file_list.
the code does not filter out 'forgein' files and assumes all files in the directory are 'yaml', i would instead refactor the host_group_vars plugin and/or include_vars code to a common source and use that.

2017-08-14 03:07 UTC, nohi commented
>  i would instead refactor the host_group_vars plugin and/or include_vars code to a common source and use that.

I got it.
I will close this PR and open new PR if I try to refactor.
Thank you for your advice and your review :-)

2017-08-14 03:07 UTC, closed without merging