Build debs with pbuilder
ansible/ansible pull request #18165
Opened 2016-10-24 14:35 UTC by shanemcd

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

Debian packaging

##### ANSIBLE VERSION

N/A

##### SUMMARY

We started seeing failures related to build dependencies when building 16.04 debs on our 14.04 Jenkins node. `pbuilder` ensures a clean-room environment inside a chroot.

2016-10-24 15:39 UTC, jlaska commented
Thanks for updating the README's too, this is a welcome change to use `pbuilder`!

2016-10-25 01:00 UTC, bcoca commented
So i would not eliminate the old way of building it, just add a new one. some users are stuck in older versions of debian and/or do not use pbuilder. It is easy enough to have this 'in addition to'

2016-10-25 13:21 UTC, jlaska commented
@bcoca normally I would agree, however the old way of building the DEBs produces DEBs *only* for the platform you are building on.  In addition, there was logic in there that resulted in failed builds depending on the state of packages installed on the system.  Chroot builds is much preferred to provide consistent builds and accurately test `BuildRequires`.

2016-10-25 14:50 UTC, ghjm commented
`DEB_DIST='precise trusty xenial' make deb` worked on my Ubuntu 14.04 box with pbuilder and build deps installed. Looks good to me.

2016-10-25 15:28 UTC, shanemcd commented
@bcoca Great suggestion. I've added a `local_deb` target to allow for building outside of a chroot.

2016-10-25 18:26 UTC, mattclay requested changes
I've successfully tested this using the provided instructions for docker.

However, I'm unable to produce a deb package running in a fresh Ubuntu 16.04 VM. The build process finishes without errors, but no deb package is produced.

2016-10-25 18:26 UTC, mattclay commented on packaging/debian/README.md
> +cd ansible
Add `git submodule update --init` here.

2016-10-25 18:26 UTC, mattclay commented on packaging/debian/README.md
> +cd ansible
Add `git submodule update --init` here.

2016-10-25 18:26 UTC, mattclay commented on packaging/debian/README.md
> +apt-get install cdbs debootstrap devscripts make pbuilder python-setuptools
Additional packages needed on a fresh install of Ubuntu 16.04:

- git
- asciidoc

2016-10-25 18:26 UTC, mattclay commented on packaging/debian/README.md
>  To create an Ansible DEB package:
It should be noted that running as root is required.

2016-10-25 18:42 UTC, mattclay commented on packaging/debian/Dockerfile
> +    cdbs \
The `asciidoc` package is needed.

2016-10-25 19:40 UTC, shanemcd commented
@mattclay Thanks for the review. I've implemented your feedback, and am currently debugging on a fresh 16.04 VM to diagnose:

> The build process finishes without errors, but no deb package is produced.

For some reason, it is placing the deb in a top-level directory at `/deb-build` when running with sudo, but works when running directly as root. It works fine when running on a 14.04 box. ¯\_(ツ)_/¯ Will report back when I find something.

2016-10-25 20:28 UTC, shanemcd commented
@mattclay I've pushed a fix that works on a fresh 16.04 box. It works when using GNU Make's `CURDIR` variable instead of `PWD`. Also tested with the Docker based approach.

2016-10-26 02:46 UTC, mattclay approved these changes

2016-10-26 02:56 UTC, mattclay commented on packaging/debian/README.md
> +__Note__: You must either run as root or have write access to `/var/cache/pbuilder`
@shanemcd Write access to `/var/cache/pbuilder` isn't enough. The build process fails with this error when not running as root:

```
E: debootstrap can only run as root
```

2016-10-26 19:45 UTC, bcoca commented
IIRC pbuilder should be doing fakeroot by default

2016-10-26 21:24 UTC, merged