Validate apache2 mpm module switching for bug #5328
ansible/ansible pull request #18371
Opened 2016-11-04 20:15 UTC by michaelgugino

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
web_infrastructure/apache2_module

##### ANSIBLE VERSION

```
  lib/ansible/modules/core: (detached HEAD 55b1813ebd) last updated 2016/11/01 14:02:20 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD cf524673e1) last updated 2016/11/01 12:39:51 (GMT -400)
  config file = 
  configured module search path = Default w/o overrides
```

##### SUMMARY

This patchset updates module integration testing to
validate the changes in PR #5454

This patchset instructs apache2_module to disable all
mpm modules, enable mpm_event, then disable mpm_event
and enable mpm_worker.

Fixes: #5328

2016-11-05 19:29 UTC, robinro requested changes
Please also add a test that tries to remove all mpm modules with `check_mode: True` and then fails.

Use `failed_when: False` and then check `result|failed`.

2016-11-05 19:29 UTC, robinro commented on test/integration/targets/apache2_module/tasks/actualtest.yml
> +  apache2_module: name={{ item }} state=absent
Ansible now recommends yaml format:
```
apache2_module:
  name: "{{item}}"
  state: absent

2016-11-05 19:29 UTC, robinro commented on test/integration/targets/apache2_module/tasks/actualtest.yml
> +  apache2_module: name=mpm_event state=present check_config=1
Use `True` or `False` for boolean values.

2016-11-05 19:29 UTC, robinro commented on test/integration/targets/apache2_module/tasks/actualtest.yml
> +  apache2_module: name={{ item }} state=absent
Needs `check_config: False`

2016-11-16 09:26 UTC, robinro commented
I'd suggest to add a test for the current behavior that fails to remove all modules. See also https://github.com/ansible/ansible-modules-core/pull/5454
```
- name: try to disable all mpm modules with configcheck
  apache2_module:
    name: "{{item}}"
    state: absent
  with_items:
    - mpm_event
    - mpm_worker
    - mpm_prefork
  failed_when: False
  register: remove_with_configcheck

- name: ensure configcheck fails task
  assert:
    that:
      - "remove_with_configcheck.failed"

- name: try to disable all mpm modules without configcheck
  apache2_module:
    name: "{{item}}"
    state: absent
    ignore_configcheck: True
  with_items:
    - mpm_event
    - mpm_worker
    - mpm_prefork
  failed_when: False
  register: remove_without_configcheck

- name: ensure without configcheck task succeeds
  assert:
    that:
      - "not remove_with_configcheck.failed"
```

2016-11-16 09:27 UTC, robinro commented
Also test `switch between mpm_event and mpm_worker` both ways, once first remove then add, once first add then remove. a2{en/dis}mod fails for different reasons in those cases.

2017-05-31 15:26 UTC, jctanner commented
@michaelgugino does this test work on redhat/centos/fedora?

needs_info

2017-05-31 15:31 UTC, michaelgugino commented
Yes, I believe it should work against all supported distros.  I cannot recall if I tested it against RH.

2017-05-31 15:39 UTC, robinro commented
@jctanner The apache2_module module only supports debian and suse type distros.

@michaelgugino  I had some some more suggestions for tests, can you implement them or comment on them?

2017-05-31 15:44 UTC, michaelgugino commented
@robinro I think the suggestions are good.  I will get an updated patch out later this week.

2017-06-08 09:57 UTC, gundalow commented
Closing & reopening to trigger CI

2017-06-08 15:24 UTC, gundalow commented
Module needs updating to support opensuse, see failing integration tests

2017-06-08 16:47 UTC, michaelgugino commented
I cannot recall if the mpm specific portions are actually applicable to OpenSUSE.  I seem to remember apache only shipping with one mpm module in that distro.  Thoughts?

2017-06-12 10:07 UTC, gundalow commented
1) Update module so it works on OpenSUSE - preferred
2) Update tests so they skip on OpenSUSE (conditional on OS)

2017-06-15 14:00 UTC, gundalow commented
Failing on OpenSuse still
https://app.shippable.com/github/ansible/ansible/runs/24887/17/tests

2017-07-05 18:46 UTC, michaelgugino commented
@robinro 
I have confirmed locally with OpenSuSe 42.2 that apache2 does not ship with mpm_event or mpm_worker.  The only available module is mpm_prefork.  Thus, the checks are failing as expected because the desired module mpm_event is never present in the stdout of apache2ctl -M.

Please let me know your thoughts.

2017-07-06 23:07 UTC, mattclay commented
@michaelgugino Are you planning on making any additional changes? I see that @robinro requested testing with check mode, which would be good to have, but I don't see that included in the tests.

2017-07-06 23:14 UTC, michaelgugino commented
@mattclay I'm not sure that's what was suggested.  A new feature was added to this module called 'ignore_configcheck' to allow disabling validation of the apache configs during a run.  This feature was developed as a fix to bug-5328, and this bug seems to really only impact Debian based distros.

I'm happy to add more to the tests, but I personally don't feel that check-mode testing is 100% necessary here.

2017-07-06 23:39 UTC, mattclay commented
@michaelgugino The first [comment](https://github.com/ansible/ansible/pull/18371#pullrequestreview-7320347) from @robinro requested testing check mode.

Having check mode tests is important for making sure it actually works. There have been issues where check mode is reported by a module as supported, yet it either fails or actually makes changes.

With that being said, I don't think we should block this PR due to lack of testing check mode. Those tests can be added in a follow-up PR if anyone is interested.

2018-01-12 00:59 UTC, merged

2018-01-12 01:00 UTC, mattclay commented
@michaelgugino Thanks for the additional tests.