fix datacenter value in case where the datacenter is defined in the conf file
ansible/ansible pull request #18583
Opened 2016-11-22 15:42 UTC by jkhelil

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

contrib/inventory/consul_io.py

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```

##### SUMMARY

When datacenter is defined in the consul.ini conf file, kv groups are not retrieved for nodes, we should set self.current_dc with the right value to fix it

2016-11-23 15:36 UTC, jctanner commented
@sgargan can you review please?

2016-11-28 20:39 UTC, jctanner commented
@johnnycarlin @maguec are either of you able to review this?

2016-11-28 21:29 UTC, sgargan commented
looks good shipit

2017-01-30 09:16 UTC, mliljedahl requested changes
Think it is enough to set self.current_dc on line 227:

if config.has_config('datacenter'):
  self.current_dc = config.datacenter
  if  config.has_config('host'):
......

But your implementation works, so shipit :)

2017-07-05 14:49 UTC, calfonso commented
@jkhelil would you mind rebasing and we'll get this merged, thanks!

2018-05-13 18:06 UTC, Akasurde commented
@jkhelil Can you please rebase ?

2019-09-03 16:10 UTC, gundalow commented
@jkhelil  Thank you for your PR.
As part of reviewing the backlog of PRs we are looking at PRs older PRs that haven't been update

Given that:
* Last commits were a long time ago
* Rebase hasn't been done

I'm going to close this.
If you, or anyone else wants to continue with this work then please do feel free to create a fresh PR and `@mention` the previous reviewers in here.

2019-09-03 16:10 UTC, closed without merging