etcd.py module improved . added posibility to configure from playbook…
ansible/ansible pull request #18580
Opened 2016-11-22 12:48 UTC by MihaiMoldovanu

##### ISSUE TYPE

 - Feature Pull Request
 - New Module Pull Request
 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME

##### ANSIBLE VERSION

```

```

##### SUMMARY

```

```

… etcd server to query

2016-11-22 13:47 UTC, gundalow requested changes

2016-11-22 13:47 UTC, gundalow commented on docsite/rst/playbooks_lookups.rst
> +# query localhost etcd ( v1 )
If you indent this sample block, like in "Here are some examples" under "More Lookups" that should fix the formatting

2016-11-22 13:47 UTC, gundalow commented on docsite/rst/playbooks_lookups.rst
> +
# Note "url" option is new in Ansible 2.3

2016-11-22 13:49 UTC, gundalow commented
Do you think the parameters should be in a table, like "The CSV File Lookup"

2016-11-22 14:43 UTC, gundalow commented on docsite/rst/playbooks_lookups.rst
> +version          Default 'v1'. If ANSIBLE_ETCD_VERSION is set will override default
". Added in 2.3"

2016-11-22 14:43 UTC, gundalow commented on docsite/rst/playbooks_lookups.rst
> +url              Default 'http://127.0.0.1:4001'. If ANSIBLE_ETCD_URL is set will override
". Added in 2.3"

2016-11-23 12:39 UTC, gundalow approved these changes
shipit

2016-11-23 12:39 UTC, gundalow commented
Once merged we should add this to `CHANGELOG`

2017-07-27 18:28 UTC, calfonso commented
@MihaiMoldovanu could you rebase this and resolve any conflicts, and then we'll get it reviewed/merged. Thanks!

2017-07-28 09:55 UTC, MihaiMoldovanu commented
Ok :) Done :) @calfonso anything else i should do ?

2017-10-05 08:57 UTC, MihaiMoldovanu commented
Fixed the conflict

2017-10-05 09:46 UTC, MihaiMoldovanu commented
Everything in green . Can you merge it  ?

2017-10-05 10:08 UTC, gundalow commented
@MihaiMoldovanu Rebase needed, see the details in the previous `ansibot` comment

2017-10-05 11:06 UTC, MihaiMoldovanu commented
Rebased .

2017-10-05 12:09 UTC, MihaiMoldovanu commented
@gundalow  now it's ok ?

2017-10-10 15:00 UTC, gundalow commented on docs/docsite/rst/playbooks_lookups.rst
> +
Multiline please

```
- debug:
    msg: "{{ lookup('etcd', 'foo') }} is a value from a locally running etcd"
```

2017-10-10 15:00 UTC, gundalow commented on docs/docsite/rst/playbooks_lookups.rst
> +       - debug: msg={{lookup('etcd','/tfm/network/config', url='http://192.168.1.21:2379' , version='v2')}}
Multiline format please

2017-10-10 16:16 UTC, gundalow approved these changes

2017-10-10 20:26 UTC, dharmabumstead approved these changes
Approved with some edits. Thanks @MihaiMoldovanu!

2017-10-10 23:01 UTC, MihaiMoldovanu commented
Erm ... playbook_lookups changed a lot . lookup options / examples were removed from playbook_lookups.rst .

2017-10-10 23:44 UTC, bcoca commented
@MihaiMoldovanu lookup docs now live in the lookup itself

2017-10-12 05:40 UTC, MihaiMoldovanu commented
fixed conflict

2017-10-12 14:55 UTC, merged

2017-10-12 14:56 UTC, gundalow commented
Merged into `devel`, will be released in `2.5.0`