Add a code-smell test for iterkeys
ansible/ansible pull request #18589
Opened 2016-11-22 19:47 UTC by abadger

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME
tests/sanity/code-smell/no-iterkeys.sh

##### ANSIBLE VERSION

```
devel
```

##### SUMMARY
code-smell test to look for iterkeys().  (Calls to iterkeys should all be replaced with something else to work on python3)

2016-11-22 19:48 UTC, abadger commented
Now that @Shaps has cleaned up the code to not have iterkeys, this is the last thing to do to make sure we don't regress https://github.com/ansible/ansible/issues/18507

2016-11-22 21:37 UTC, mattclay requested changes
You'll need to add `no-iterkeys.sh` to `test/utils/shippable/code-smell.sh` so it's executed by Shippable.

This won't be necessary once `ansible-test` is deployed, as it runs code-smell scripts automatically.

2016-11-22 21:37 UTC, mattclay commented on test/sanity/code-smell/no-iterkeys.sh
> +ITERKEYS_USERS=$(grep -r iterkeys . \
Add the `-I` option to ignore binary files.

2016-11-22 21:37 UTC, mattclay commented on test/sanity/code-smell/no-iterkeys.sh
> +    -e no-iterkeys.sh \
Include the path to `no-iterkeys.sh` for completeness.

2016-11-22 21:37 UTC, mattclay commented on test/sanity/code-smell/no-iterkeys.sh
> +    echo "${ITERKEYS_USERS}"
Include a brief message explaining what the failure is, along with the corrective action.

2016-12-13 12:37 UTC, gundalow commented
From `#ansible-devel` on 2016-12-13

Would be good for this to also check for iteritems, May want to rename the script if that's the case.

2016-12-13 13:09 UTC, abadger commented
Okay, changes made (minus the addition of the test to code-smell.sh as I've waited long enough that we're now using ansible-test  @mattclay, does this look good now?

2016-12-13 14:13 UTC, gundalow commented
Is this enough to prove that the script is being executed by `ansible-test`:
```
2016-12-13 13:12:04 Detected changes in 1 file(s).
2016-12-13 13:12:04 test/sanity/code-smell/no-iterkeys.sh
2016-12-13 13:12:04 Mapping 1 changed file(s) to tests.
2016-12-13 13:12:04 test/sanity/code-smell/no-iterkeys.sh -> compile: none
2016-12-13 13:12:04 WARNING: No tests found for detected changes.
2016-12-13 13:12:04 + ansible-test sanity --color -v --tox --skip-test ansible-doc --python 2.7
2016-12-13 13:12:04 Shippable detected, collecting parameters from environment.
2016-12-13 13:12:04 Run command: git diff --name-only --no-renames -z devel
2016-12-13 13:12:04 Processing pull request for branch devel commit f377cd72ca5b685527164fe4c40771b9f1ec231f
2016-12-13 13:12:04 Detected changes in 1 file(s).
2016-12-13 13:12:04 test/sanity/code-smell/no-iterkeys.sh
2016-12-13 13:12:04 Mapping 1 changed file(s) to tests.
2016-12-13 13:12:04 test/sanity/code-smell/no-iterkeys.sh -> sanity: all
2016-12-13 13:12:05 Run command: tox -c test/runner/tox.ini -e py27 -- /root/src/github.com/ansible/ansible/test/runner/test.py sanity -v --skip-test ansible-doc --python 2.7 --color yes --requirements
```

2016-12-14 00:37 UTC, mattclay approved these changes

2016-12-14 00:39 UTC, merged