updates the network shared docs to include the timeout parameter
ansible/ansible pull request #18635
Opened 2016-11-26 04:11 UTC by privateip

The network shared doc fragment was missing the timeout parameter from
the docstring.  This commit adds the timeout parameter back to the
doc fragment

2016-11-26 07:56 UTC, gundalow requested changes
needs_revision

2016-11-26 07:56 UTC, gundalow commented on lib/ansible/utils/module_docs_fragments/eos.py
> +    require: false
`version_added: 2.3`

2016-11-26 07:56 UTC, gundalow commented on lib/ansible/utils/module_docs_fragments/eos.py
> +      - Specifies the timeout for communicating with the network device
Specifies the timeout (in seconds) for...

2016-11-26 16:16 UTC, privateip commented on lib/ansible/utils/module_docs_fragments/eos.py
> +    require: false
This was actually added in 2.2 it was just missing the docstring

2016-11-28 12:13 UTC, gundalow approved these changes
shipit

2016-11-28 12:13 UTC, merged