Pamd Module
ansible/ansible pull request #18808
Opened 2016-12-07 01:24 UTC by kevensen

##### ISSUE TYPE

- New Module Pull Request
##### COMPONENT NAME

pamd
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### SUMMARY

While lineinfile and replace are very useful, I felt that a module specific to updating pam.d services was necessary.

2016-12-07 01:24 UTC, kevensen commented
Migrated from https://github.com/ansible/ansible-modules-extras/pull/2640

2016-12-07 01:44 UTC, kevensen commented
I know this request is old, but I really would like it incorporated.

2016-12-07 01:51 UTC, gundalow requested changes
needs_revision

2016-12-07 01:51 UTC, gundalow commented on lib/ansible/modules/system/pamd.py
> +version_added: "2.2"
2.3

2016-12-07 01:51 UTC, gundalow commented on lib/ansible/modules/system/pamd.py
> +    type=auth
For examples we are standardizing on
`key: value`
Rather than key=value

2016-12-07 15:16 UTC, kevensen commented
@gundalow I've made the changes you requested.  At your convenience, could you please take another look?

2016-12-08 22:23 UTC, gundalow commented
Thank you for being very proactive in your efforts to migrate your PR, however it appears that there was a window of time when ansible/ansible:devel was broken and it appears, unfortunately, that your PR was migrated during that window.

Due to this you will need to follow a hopefully very simple process to fix this. Please see https://groups.google.com/forum/#!topic/ansible-devel/0eRSpiGkios

As a thank you for being pioneers, we will actively review your PRs as a priority. Once you've migrated your PR please add it to the Core Agenda https://github.com/ansible/community/issues/147

2016-12-08 22:23 UTC, closed without merging