[WIP] Vyos 2.3
ansible/ansible pull request #18994
Opened 2016-12-08 14:51 UTC by Qalthos

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
vyos_system

##### ANSIBLE VERSION

```
2.3
```

##### SUMMARY
New module vyos_system, roughly corresponds to `set system *` commands

2016-12-09 11:04 UTC, gundalow commented
I recently found out there is a better view of failing tests in shippable

https://app.shippable.com/runs/5849bea0c42d210f009d89d6/2/tests

2017-01-07 19:28 UTC, gundalow commented on lib/ansible/modules/network/vyos/vyos_system.py
> +    domain_name: eng.ansible.com
foo.example.com

2017-01-07 19:28 UTC, gundalow commented on lib/ansible/modules/network/vyos/vyos_system.py
> +    - set system domain-name eng.ansible.com
foo.example.com

2017-01-20 23:19 UTC, gundalow reviewed
I know this is WIP, the the bot pinged me about it so I thought I'd cast my eye over it

2017-01-20 23:19 UTC, gundalow commented on lib/ansible/modules/network/vyos/vyos_config.py
> +    result['commands'] = updates
@privateip did we make a decision on returning `updates` vs `commands`?

2017-01-20 23:19 UTC, gundalow commented on lib/ansible/module_utils/vyos.py
> -    TERMINAL_LENGTH = os.getenv('ANSIBLE_VYOS_TERMINAL_LENGTH', 10000)
Where has this moved to?

2017-01-23 15:13 UTC, Qalthos commented on lib/ansible/module_utils/vyos.py
> -    TERMINAL_LENGTH = os.getenv('ANSIBLE_VYOS_TERMINAL_LENGTH', 10000)
evidently plugins/terminal/vyos.py, will restore there.

2017-01-23 18:46 UTC, gundalow requested changes
needs_revision

2017-01-23 18:46 UTC, gundalow commented on lib/ansible/module_utils/vyos2.py
> +# Copyright (c) 2015 Peter Sprygada, <psprygada@ansible.com>
Should we put a Red Hat copyright notice here

2017-01-23 18:46 UTC, gundalow commented on lib/ansible/modules/network/vyos/vyos_command.py
>  - vyos_command:
For examples we are standardising on 

```
- name: describe
  module:
    arg1:
    arg2
```

2017-01-23 18:46 UTC, gundalow commented on lib/ansible/plugins/terminal/vyos.py
> +    terminal_length = os.getenv('ANSIBLE_VYOS_TERMINAL_LENGTH', 10000)
Thinking about this a bit more, should this be moved to `lib/ansible/constants.py`

2017-01-23 18:48 UTC, gundalow commented on lib/ansible/plugins/terminal/vyos.py
> +    terminal_length = os.getenv('ANSIBLE_VYOS_TERMINAL_LENGTH', 10000)
It's correct where it is

2017-01-23 20:28 UTC, gundalow approved these changes
shipit

2017-01-23 20:30 UTC, merged