2 modules for Packet Host: packet_device and packet_sshkey
ansible/ansible pull request #19005
Opened 2016-12-08 20:33 UTC by t0mk

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
- cloud/packet/packet_device
- cloud/packet/packet_sshkey

##### ANSIBLE VERSION

```
ansible 2.3.0 (packet-modules 8babd1fdda) last updated 2016/12/08 22:27:03 (GMT +300)
  config file = 
  configured module search path = Default w/o overrides
```

##### SUMMARY
This PR adds 2 modules for the Packet host (https://www.packet.net). Packet offers bare metal infrastructure.

- packet_device: for managing devices (servers)
- packet_sshkey: for adding and removing public SSH keys

2016-12-11 13:35 UTC, t0mk commented
@crunchywelch @baldwinSPC
This the active PR with the modules for Packet host. I made it a single commit.

2016-12-13 16:03 UTC, baldwinSPC commented
+1 from this end.

2016-12-13 16:37 UTC, t0mk commented
@baldwinSPC thanks!

I tried to fix some things that people pinpointed in your previous PR https://github.com/ansible/ansible-modules-extras/pull/1673:
- idempotent behavious for "present" devices (e.g. new device is not created if one with given specs already exists)
- it's possible to wait for more spawned devices at once (one use-case of this is in examples)

2016-12-22 14:49 UTC, mmlb commented on lib/ansible/modules/cloud/packet/packet_device.py
> +def listify_string_name_or_id(s):
both callers of `listify_string_name_or_id` go on to call `.strip()` on list elements, so maybe you should get rid of that from here?

2016-12-22 14:49 UTC, mmlb commented on lib/ansible/modules/cloud/packet/packet_device.py
> +    if ',' is s:
typo?: `is` -> `in`

2016-12-22 14:49 UTC, mmlb commented on lib/ansible/modules/cloud/packet/packet_device.py
> +    # Also include each IPs as a key for easier lookup in roles.
typo: IPs -> IP

2016-12-22 14:49 UTC, mmlb commented on lib/ansible/modules/cloud/packet/packet_device.py
> +- name: Create 3 coreos devices with userdata, wait till they get IPs and then wait for SSH
grammar: `till` -> `until`

2016-12-22 14:49 UTC, mmlb commented on lib/ansible/modules/cloud/packet/packet_device.py
> +      - Userdata blob made available to the machine
missing a `.` at the end

2016-12-22 14:49 UTC, mmlb commented on lib/ansible/modules/cloud/packet/packet_device.py
> +      - Alias of I(name)
missing `.` at end of sentence

2016-12-22 14:49 UTC, mmlb commented on lib/ansible/modules/cloud/packet/packet_device.py
> +      - Facility slug for device creation. As of 2016, it should be one of [ewr1, sjc1. ams1].
nrt1 is currently available
also typo after sjc1: `.` -> `,`

2016-12-22 14:49 UTC, mmlb commented on lib/ansible/modules/cloud/packet/packet_device.py
> +      - The number of devices to create. Count number can he included in hostname via the %d string formatter.
typo: can he -> can be

2016-12-22 14:49 UTC, mmlb commented on lib/ansible/modules/cloud/packet/packet_device.py
> +            break
unnecessary break

2016-12-22 14:49 UTC, mmlb commented on lib/ansible/modules/cloud/packet/packet_sshkey.py
> +     - File with the public key
missing `.` at end

2016-12-22 14:49 UTC, mmlb commented on lib/ansible/modules/cloud/packet/packet_sshkey.py
> +     - Public Key string ({type} {base64 encoded key} {description})
missing `.` at end

2016-12-24 09:03 UTC, t0mk commented
Thanks for the comments! I will fix them after Chistmas.

2016-12-29 19:19 UTC, HyperBaton commented
Ran a simple playbook with these modules and it worked nicely for me.

2017-01-01 09:31 UTC, gundalow requested changes
needs_revision 

Please also update the CHANGELOG.md in the root to list these new modules.

2017-01-01 09:31 UTC, gundalow commented on lib/ansible/modules/cloud/packet/packet_sshkey.py
> +            auth_token=dict(default=os.environ.get(PACKET_API_TOKEN_ENV_VAR)),
For secret things please add
`, no_log=True,`

2017-01-01 09:31 UTC, gundalow commented on lib/ansible/modules/cloud/packet/packet_device.py
> +      - Packet api token. You can also supply it in env var PACKET_API_TOKEN.
Environment variables should be formatted in a constant width font:
`C(PACKET_API_TOKEN)`

2017-01-01 09:31 UTC, gundalow commented on lib/ansible/modules/cloud/packet/packet_device.py
> +      - Alias of I(name)
Please delete this line. 
Any aliases get documented via the `aliases:` option.

2017-01-01 09:31 UTC, gundalow commented on lib/ansible/modules/cloud/packet/packet_device.py
> +    type: bool
There isn't a `type:` option in the documentation block, please remove.

2017-01-01 09:31 UTC, gundalow commented on lib/ansible/modules/cloud/packet/packet_sshkey.py
> +from ansible.module_utils.basic import * # noqa: F403
Please only import what you need.

2017-01-01 17:36 UTC, t0mk commented
@gundalow: thanks for your comments, I will fix them on Tuesday.

2017-01-03 13:17 UTC, gundalow requested changes
needs_revision

2017-01-03 13:17 UTC, gundalow commented on lib/ansible/modules/cloud/packet/packet_device.py
> +      - Packet api token. You can also supply it in env var c(PACKET_API_TOKEN).
Capital `C`, apologies if I told you the wrong thing before.

2017-01-03 13:17 UTC, gundalow commented on lib/ansible/modules/cloud/packet/packet_device.py
> +# All the examples assume that you have your Packet api token in env var c(PACKET_API_TOKEN).
No need for `C(...)` here as the whole `EXAMPLES` block is already formatted correctly.

2017-01-03 13:17 UTC, gundalow commented on lib/ansible/modules/cloud/packet/packet_sshkey.py
> +     - Packet api token. You can also supply it in env var c(PACKET_API_TOKEN).
Capital `C`.

2017-01-03 13:17 UTC, gundalow commented on lib/ansible/modules/cloud/packet/packet_sshkey.py
> +# All the examples assume that you have your Packet API token in env var c(PACKET_API_TOKEN).
Remove the `c(...)` here

2017-01-03 14:02 UTC, t0mk commented
ready_for_review

2017-01-03 16:09 UTC, gundalow approved these changes

2017-01-03 16:10 UTC, gundalow commented
Looks like everyone is happy, so merging.

Thanks for the reviews

2017-01-03 16:10 UTC, merged