Allow kerberos_auth in URL requests
ansible/ansible pull request #19032
Opened 2016-12-09 03:27 UTC by willthames

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
module_utils/urls

##### ANSIBLE VERSION

```
ansible 2.3.0 (kerberos_auth_uri a6c870d62c) last updated 2016/12/09 13:22:30 (GMT +1000)
  config file = 
  configured module search path = Default w/o overrides
```

##### SUMMARY

Enable kerberos authentication for URLs.

Makes use of very recent urllib_kerberos module available on pypi.

2017-07-27 18:47 UTC, calfonso commented
@willthames could you rebase and resolve any conflicts? Then we'll finish up the review, thanks!

2017-11-27 04:41 UTC, bgsanthosh commented
Any update on this PR ?

2017-11-27 19:47 UTC, calfonso commented
@bgsanthosh waiting on the contributor to fixed the conflicts.

2017-11-28 01:55 UTC, willthames commented
Rebased, looks good but untested.

2018-02-06 00:07 UTC, puiterwijk requested changes
I think there's some fixes that should be made to the underlying library, and there should probably be documentation or clear notes that the kerberos negotiation is initiated from the *ansible target*, meaning that the credentials (keytab or active credential cache) needs to be available there.

2018-02-06 00:07 UTC, puiterwijk commented on lib/ansible/module_utils/urls.py
> +            handlers.append(urllib_kerberos.HTTPKerberosAuthHandler())
This looks really opinionated to me, not allowing specifying the Service Principal Name (neither service, hardcoded to "HTTP" or hostname), keytab or ccache location.
Especially given that this runs on the ansible target, I highly doubt most servers would have a current credential in their credential cache at any point in time.
So basically, this code would require someone to have a manual `kinit` play before *any* play that uses `kerberos_auth=yes`.

2018-02-06 00:07 UTC, puiterwijk commented on lib/ansible/module_utils/urls.py
> +    import urllib_kerberos
I see a few problems with using this library:
- If you have `urllib_kerberos` installed but not `kerberos` (which is allowed since `setup.py` does not require it), any run of `ansible` with this patch in that situation will return SystemExit (https://github.com/willthames/urllib_kerberos/blob/fdd0d2954905aa82ff9940d350c0ee8787d379b3/lib/urllib_kerberos/__init__.py#L39)
- It does not actually have a way to enforce mutual authentication, which is marked as TODO and should be configurable, defaulting to enforced (https://github.com/willthames/urllib_kerberos/blob/fdd0d2954905aa82ff9940d350c0ee8787d379b3/lib/urllib_kerberos/__init__.py#L127)

2018-02-06 00:07 UTC, puiterwijk commented on lib/ansible/module_utils/urls.py
> +        module.fail_json(msg="kerberos or urllib_kerberos is not installed. Please install from pip")
I am not sure we should advice people to install this from pip.

2018-02-06 00:20 UTC, willthames commented
Thanks for the review @puiterwijk - this fix was enough to get kerberos working for URL requests for my needs but probably not suitable for production release.

I'll just close this off - I have no need for this fix any longer, and better fixes are likely possible - using a better implementation of urllib combined with kerberos would probably be a good goal, but not one that I'm interested in implementing or maintaining.

2018-02-06 00:20 UTC, closed without merging