swdepot.py : filter swlist result header
ansible/ansible pull request #19047
Opened 2016-12-09 08:12 UTC by melankh

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
packaging/os/swdepot.py 

##### ANSIBLE VERSION
```
ansible 2.2.0.0
```

##### SUMMARY
swlist add a header that could match package name.
Real example : "tar" that match "target"

```
$swlist -a revision -l product tar | grep tar
# Contacting target "yrvm08"...
  tar   1.29
```

So filtering it via "grep -v \#"
```
$ swlist -a revision -l product tar | grep -v \# |  grep tar
  tar   1.29
```

2016-12-09 08:12 UTC, melankh commented
Migrated from https://github.com/melankh/ansible-modules-extras/pull/1

2017-06-28 15:54 UTC, jctanner commented
@melankh do you intend to rebase this?

needs_info

2017-06-28 15:54 UTC, bcoca requested changes

2017-06-28 15:54 UTC, bcoca commented on lib/ansible/modules/packaging/os/swdepot.py
> +        rc, stdout, stderr = module.run_command("%s %s | grep -v \# | grep %s" % (cmd_list, pipes.quote(name), pipes.quote(name)), use_unsafe_shell=True)
the grep seems too generic and will remove any line with a #, you probably only want lines beginning with #

2017-06-29 08:21 UTC, melankh commented on lib/ansible/modules/packaging/os/swdepot.py
> +        rc, stdout, stderr = module.run_command("%s %s | grep -v \# | grep %s" % (cmd_list, pipes.quote(name), pipes.quote(name)), use_unsafe_shell=True)
There's no # in the results of swinstall (or swcopy/swverify/...) except in the beginning of the lines.

But, if you prefer, the grep command can be replaced by :   **`egrep -v \^\#`**

2017-06-30 13:22 UTC, bcoca commented on lib/ansible/modules/packaging/os/swdepot.py
> +        rc, stdout, stderr = module.run_command("%s %s | grep -v \# | grep %s" % (cmd_list, pipes.quote(name), pipes.quote(name)), use_unsafe_shell=True)
no need, if the tools enforce that already

2018-04-14 12:06 UTC, closed without merging