Source Mage GNU/Linux package manager support
ansible/ansible pull request #19072
Opened 2016-12-09 14:09 UTC by vaygr

I'm glad to present the 'sorcery' module for Ansible.

[Sorcery](http://sourcemage.org/Sorcery) is a package management system for some super-flexible source-based Linux distro called [Source Mage GNU/Linux](http://sourcemage.org). It is one of the [oldest](http://sourcemage.org/linux-timeline.png) distros available, and even while being not so popular, it still takes [its niche](http://sourcemage.org/About) quite well.

The module provides wide-range functionality for controlling SMGL (so we call them) systems the way you want them to be (pretty minimal and up-to-date), including dependencies management, full/partial system rebuild, updating of the components (package manager, collections of software, packages), so we could provide a universal alternative to our outdated [Cabal command](http://sourcemage.org/Sorcery/Commands/Cabal), used to be a multi-system control tool.

[Intro page](http://sourcemage.org/Intro) is there if you need some more information on how our system works.
You can also find us lurking on #sourcemage at Freenode IRC network and ask a question!

Thanks!

2016-12-09 14:09 UTC, vaygr commented
Migrated from https://github.com/ansible/ansible-modules-extras/pull/1040

2016-12-10 14:44 UTC, gundalow requested changes
Just a few minor tweaks needed. Nice to see a module with decent documentation. 

I see @bcoca has a few comments on the previous PR which may be outstanding, so we should get his mark of approval before merging as well.

2016-12-10 14:44 UTC, gundalow commented on lib/ansible/modules/packaging/os/sorcery.py
> +EXAMPLES = '''
Can you please rewrite the examples with a 
`name:` and multi line statements using `key: value`
We are in the process of standardising all the modules to use that format.

2016-12-10 14:44 UTC, gundalow commented on lib/ansible/modules/packaging/os/sorcery.py
> +main()
To enable the module to work with debuggers can you please rewrite this as:
```
if __name__ == '__main__':
    main()
```

2016-12-10 14:44 UTC, gundalow commented on lib/ansible/modules/packaging/os/sorcery.py
> +from ansible.module_utils.basic import *
Could you just import the specific things you need?

2016-12-10 15:24 UTC, vaygr commented on lib/ansible/modules/packaging/os/sorcery.py
> +main()
absolutely, was thinking about it.

2016-12-10 15:52 UTC, vaygr commented on lib/ansible/modules/packaging/os/sorcery.py
> +EXAMPLES = '''
Yeah, I see, done.

2016-12-10 16:53 UTC, vaygr commented on lib/ansible/modules/packaging/os/sorcery.py
> +from ansible.module_utils.basic import *
done,

btw, is there any value in making this module more portable so it'd work with older branches of Ansible, e.g. `1.9`?

2016-12-10 21:38 UTC, gundalow approved these changes

2016-12-10 21:38 UTC, merged

2016-12-10 21:40 UTC, gundalow commented
Ansible 1.9 will be going out of support very soon. Ansible 2.2 was released recently and I'd strongly suggest upgrading. 

As a general rule we don't backport new modules. However if you include this file in `./library/` directory along side `roles` if will be available to you.

2016-12-10 21:41 UTC, gundalow commented
@vaygr if @bcoca has any feedback please include that in a follow up PR.

Thanks for the new module.

2016-12-11 10:28 UTC, vaygr commented
will do, thank you.