win_file: fix error when creating an existing dir
ansible/ansible pull request #19070
Opened 2016-12-09 12:28 UTC by ilpianista

##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

win_file
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

Fix error when creating an existing dir.

If something else created the dir New-Item will throw an exception and the task will fail. Check the existing file and as long as it's a dir, we don't need to error out.

2016-12-09 12:28 UTC, ilpianista commented
Migrated from https://github.com/ansible/ansible-modules-core/pull/4823

2016-12-10 14:47 UTC, gundalow commented
Following on from @jhawkesworth comment in the original PR, as the modules have now moved into the main repo it would be great if a test  was added to defend this fix. Tests are in `test/integration/targets/`

2016-12-12 22:23 UTC, abadger commented
\cc @nitzmahone

2017-01-24 14:14 UTC, ilpianista commented
@gundalow looking in the tests folder, I cannot find an example of a tests that runs the same task **in parallel**. Any help?

2017-01-24 18:47 UTC, gundalow commented
I'm not aware of any, @mattclay any ideas?

2017-01-24 19:24 UTC, mattclay commented
We don't have integration tests for race conditions, as there's typically no way to guarantee that the race condition is actually encountered during the test. That kind of testing is usually more suited for unit testing, where we can use mocking to trigger the necessary code paths. However, we only have unit testing for python code currently.

2017-01-24 20:55 UTC, gundalow commented
Also I think we are on diminishing returns for that. If you have some spare cycles reviewing the existing `win_file` tests in https://github.com/ansible/ansible/tree/devel/test/integration/targets/win_file would be cool, though that would be a separate PR

2017-02-09 14:55 UTC, gundalow commented
Rebase needed

2017-02-09 18:14 UTC, ilpianista commented
Thank you @gundalow I missed the notification.

2017-02-13 12:02 UTC, jhawkesworth commented
@ilpianista if you need help rebasing please see this
https://docs.ansible.com/ansible/dev_guide/developing_rebasing.html
if you need further help please ask in #ansible-devel irc channel.

2017-02-13 19:49 UTC, ilpianista commented
@jhawkesworth what's wrong with my rebase?

2017-02-14 09:04 UTC, jhawkesworth commented
Sorry @ilpianista I must have been looking at an outdated version of the page - there is nothing wrong with your rebase.

2017-02-14 09:08 UTC, jhawkesworth commented
The integration tests are still passing and this does add better exception handling so I see no reason not to include this

shipit

2017-02-14 09:09 UTC, jhawkesworth commented
bot_status

2017-02-28 18:55 UTC, gundalow commented
Rebase needed

2017-03-14 12:25 UTC, dagwieers requested changes

2017-03-14 12:25 UTC, dagwieers commented on lib/ansible/modules/windows/win_file.ps1
> +                        Fail-Json (New-Object psobject) "path is not a directory"
Make this:
```powershell
Fail-Json $result "Existing path $path is not a directory"
```

2017-03-14 12:25 UTC, dagwieers commented on lib/ansible/modules/windows/win_file.ps1
> +                    Fail-Json (New-Object psobject) $_.Exception.Message
Make this:
```powershell
Fail-Json $result $_.Exception.Message
```

2017-03-14 18:56 UTC, ilpianista commented
@dagwieers thanks, done

2017-03-14 21:06 UTC, dagwieers commented on lib/ansible/modules/windows/win_file.ps1
> +        Fail-Json $result "Failed to delete $file.FullName: $_.Exception.Message"
Does this work ? I though it had to be "$($file.FileName)".

2017-03-14 21:09 UTC, dagwieers requested changes

2017-03-14 21:09 UTC, dagwieers commented on lib/ansible/modules/windows/win_file.ps1
> +        if (-not $check_mode) {
This is not needed because we already do `-WhatIf:$check_mode`.
And the failure paths should be tested in check-mode to.

2017-03-14 22:17 UTC, ilpianista commented on lib/ansible/modules/windows/win_file.ps1
> +        Fail-Json $result "Failed to delete $file.FullName: $_.Exception.Message"
This is how it's done at line 66, so I thought this is the same case

2017-03-14 22:20 UTC, dagwieers commented on lib/ansible/modules/windows/win_file.ps1
> +        Fail-Json $result "Failed to delete $file.FullName: $_.Exception.Message"
Please test it, I am petty sure it does not work in a string.

2017-03-14 22:53 UTC, ilpianista commented on lib/ansible/modules/windows/win_file.ps1
> +        Fail-Json $result "Failed to delete $file.FullName: $_.Exception.Message"
I can't test it at the moment, so I reverted it.

2017-03-17 16:33 UTC, nitzmahone approved these changes

2017-03-17 16:33 UTC, merged