[GCE] regex support for gce_tag. Integration, unit tests to support instance_pattern
ansible/ansible pull request #19087
Opened 2016-12-09 18:26 UTC by supertom

##### ISSUE TYPE

- Feature Pull Request
 - Test Pull Request

##### COMPONENT NAME

gce_tag

##### ANSIBLE VERSION

```
ansible 2.3.0 (int-gce-tag e35b362df8) last updated 2016/11/18 00:23:21 (GMT +000)
  lib/ansible/modules/core: (devel 48cd199871) last updated 2016/10/27 16:05:05 (GMT +000)
  lib/ansible/modules/extras: (gce_tag_regex f1cf3901a7) last updated 2016/11/08 04:25:30 (GMT +000)
  config file = /home/supertom/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY

The gce_tag module can support updating tags on multiple instances via an instance_pattern field.

 'instance_pattern' and 'instance_name' are mutually exclusive and one must be specified.

The integration test for the gce_tag module has been updated to support the instance_pattern parameter.  Unit tests have been added to test the list-manipulation functionality.

Run the integration test with:

`TEST_FLAGS='--tags "test_gce_tag"' make gce`

Run the unit tests with:

`python test/units/modules/cloud/google/test_gce_tag.py`

/cc @ryansb

2016-12-09 18:26 UTC, supertom commented
Migrated from https://github.com/ansible/ansible/pull/18536

2016-12-09 19:31 UTC, ryansb requested changes

2016-12-09 19:31 UTC, ryansb commented on lib/ansible/modules/test/units/modules/cloud/google/test_gce_tag.py
> +import unittest
You need to add `#!/usr/bin/python` to the first line here, and that should fix up your tests on shippable.

2016-12-09 19:31 UTC, ryansb commented on lib/ansible/modules/cloud/google/gce_tag.py
> +        module.fail_json(msg='libcloud with GCE support is required.')
Is there a min version for the tag support?

2016-12-09 19:31 UTC, ryansb commented on lib/ansible/modules/cloud/google/gce_tag.py
> +      - The pattern of GCE instance names to match for adding/removing tags.  Required if instance_name is not specified.
Can you add here that patterns support full Python regex? I see that you straight `re.compile` them later.

2016-12-09 19:31 UTC, ryansb commented on lib/ansible/modules/cloud/google/gce_tag.py
> +            p = re.compile(instance_pattern)
Can you add a try/except here so bad regexes are pointed to as the source of the failure?

2016-12-09 19:31 UTC, ryansb commented on lib/ansible/modules/cloud/google/gce_tag.py
> +            p = re.compile(instance_pattern)
Bonus points for a link to the `re` man page 😉

2016-12-09 19:31 UTC, ryansb commented on lib/ansible/modules/cloud/google/gce_tag.py
> +       module.fail_json(msg=str(e), changed=False)
Can you add `exception=traceback.format_exc()` to the failure here?

2016-12-09 23:49 UTC, supertom commented on lib/ansible/modules/test/units/modules/cloud/google/test_gce_tag.py
> +import unittest
Done

2016-12-09 23:49 UTC, supertom commented on lib/ansible/modules/cloud/google/gce_tag.py
> +      - The pattern of GCE instance names to match for adding/removing tags.  Required if instance_name is not specified.
Done

2016-12-09 23:50 UTC, supertom commented on lib/ansible/modules/cloud/google/gce_tag.py
> +        module.fail_json(msg='libcloud with GCE support is required.')
I put in 0.17.0, which we use for gce.py.  They both rely on the same API.

2016-12-09 23:50 UTC, supertom commented on lib/ansible/modules/cloud/google/gce_tag.py
> +        module.fail_json(msg='libcloud with GCE support is required.')
Done

2016-12-09 23:50 UTC, supertom commented on lib/ansible/modules/test/units/modules/cloud/google/test_gce_tag.py
> +import unittest
Done

2016-12-09 23:51 UTC, supertom commented on lib/ansible/modules/cloud/google/gce_tag.py
> +      - The pattern of GCE instance names to match for adding/removing tags.  Required if instance_name is not specified.
Done

2016-12-09 23:51 UTC, supertom commented on lib/ansible/modules/cloud/google/gce_tag.py
> +            p = re.compile(instance_pattern)
Done

2016-12-09 23:51 UTC, supertom commented on lib/ansible/modules/cloud/google/gce_tag.py
> +       module.fail_json(msg=str(e), changed=False)
Done

2016-12-10 01:25 UTC, supertom commented
@ryansb Thanks for the review - made the changes requested.  PTAL!

2016-12-14 16:15 UTC, ryansb approved these changes

2016-12-29 13:45 UTC, merged