Added new module gitlab_tag
ansible/ansible pull request #19089
Opened 2016-12-09 18:50 UTC by dj-wasabi

##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

gitlab_tag
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

This module will create a git tag in Gitlab on a project. The group and project should exists, otherwise this module will complain that either one of these does not exists. This module can only create or delete a tag, not update a tag.

2016-12-09 18:50 UTC, dj-wasabi commented
Migrated from https://github.com/ansible/ansible-modules-extras/pull/3283

2017-02-01 08:53 UTC, djmattyg007 requested changes

2017-02-01 08:53 UTC, djmattyg007 commented on lib/ansible/modules/source_control/gitlab_tag.py
> +    server_url="http://gitlab.dj-wasabi.local"
Examples should use HTTPS

2017-02-01 08:53 UTC, djmattyg007 commented on lib/ansible/modules/source_control/gitlab_tag.py
> +    server_url="http://gitlab.dj-wasabi.local"
Examples should use HTTPS

2017-02-01 08:53 UTC, djmattyg007 commented on lib/ansible/modules/source_control/gitlab_tag.py
> +from ansible.module_utils.basic import *
I believe importing all symbols from `ansible.modules_utils.basic` is now considered bad practice. You should import only what you need.

2017-02-01 08:53 UTC, djmattyg007 commented on lib/ansible/modules/source_control/gitlab_tag.py
> +            state=dict(default="present", choices=["present", 'absent']),
This list would be easier to grok if it was in alphabetical order.

2017-02-01 08:53 UTC, djmattyg007 commented on lib/ansible/modules/source_control/gitlab_tag.py
> +            git = gitlab.Gitlab(server_url, email=login_user, password=login_password, ssl_verify=verify_ssl)
I think `gitlab` would be a better name for this variable than `git`.

2017-02-01 08:53 UTC, djmattyg007 commented on lib/ansible/modules/source_control/gitlab_tag.py
> +    use_credentials = None
A lot of this code is duplicated between this `gitlab_tag` module and the `gitlab_hook` module that you've also submitted: https://github.com/ansible/ansible/pull/19093

I think you should extract the common code into a class that goes into `ansible.module_utils`.

2017-02-01 08:53 UTC, djmattyg007 commented on lib/ansible/modules/source_control/gitlab_tag.py
> +                module.exit_json(changed=True, result="Tag should have been deleted.")
Change `should` to `would`.

2017-02-01 08:53 UTC, djmattyg007 commented on lib/ansible/modules/source_control/gitlab_tag.py
> +                module.exit_json(changed=False, result="Something went wrong deleting the tag.")
I would use `module.fail_json` here to properly indicate failure.

2017-02-01 08:53 UTC, djmattyg007 commented on lib/ansible/modules/source_control/gitlab_tag.py
> +                module.exit_json(changed=True, result="Tag should have been created.")
Change `should` to `would`.

2017-02-01 08:53 UTC, djmattyg007 commented on lib/ansible/modules/source_control/gitlab_tag.py
> +                module.exit_json(changed=False, result="Something went wrong creating the tag.")
As above, use `module.fail_json` to properly indicate failure.

2017-02-01 08:53 UTC, djmattyg007 commented on lib/ansible/modules/source_control/gitlab_tag.py
> +        project = self.projectObject
If something calls `existsTag` before `getProject` is called, `project` will hold `None`, and will then cause problems. I think there should be a `GitLabProject` class (which should also go into the `ansible.module_utils` namespace) which should be passed in to this class through the constructor.

2017-02-03 05:58 UTC, adrianmoisey commented on lib/ansible/modules/source_control/gitlab_tag.py
> +short_description: Creates/deletes tags on Gitlab projects
This is a nitpick, I'm not 100% sure if it's right, but it looks like GitLab like to go by "GitLab" and not "Gitlab"

2017-08-15 17:11 UTC, closed without merging