Add new OpenStack module for managing cinder volume snapshots
ansible/ansible pull request #19122
Opened 2016-12-09 21:24 UTC by ruizink

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME

lib/ansible/modules/cloud/openstack/os_volume_snapshot.py
##### ANSIBLE VERSION

```
ansible 2.3.0.0
```
##### SUMMARY

This change adds a new OpenStack module to allow the creation/deletion of snapshots on cinder volumes.

2017-07-06 10:53 UTC, ruizink commented
Any updates regarding this MR?

2018-02-07 19:39 UTC, maxamillion requested changes

2018-02-07 19:39 UTC, maxamillion commented on lib/ansible/modules/cloud/openstack/os_volume_snapshot.py
> +
Needs an `ANSIBLE_METADATA` entry as per https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_documenting.html

2018-02-07 19:39 UTC, maxamillion commented on lib/ansible/modules/cloud/openstack/os_volume_snapshot.py
> +version_added: "2.3"
Just a note, we'll need to bump this to the correct version at the time this gets included.

2018-02-07 19:39 UTC, maxamillion commented
As a general note, any desire to support `check_mode`?

2018-02-07 19:39 UTC, maxamillion commented
needs_info needs_revision

2018-02-14 14:24 UTC, ruizink commented
* Rebased with from `devel`
* Bumped the Ansible version in `version_added`
* Added `ANSIBLE_METADATA` section
* Added support for `check_mode`

2018-05-03 05:28 UTC, Akasurde commented
@maxamillion Could you please revisit changes ?

2018-05-03 13:47 UTC, maxamillion approved these changes

2018-05-03 14:15 UTC, maxamillion commented
I'd like to note that I should have encouraged adding integration tests previously, but I won't block on it. The code looks good.

2018-05-03 14:15 UTC, merged

2018-05-03 14:31 UTC, ruizink commented
@maxamillion I will work on adding those. Thanks

2018-05-03 14:41 UTC, maxamillion commented
@ruizink much appreciated!