Win service rewrite
ansible/ansible pull request #19143
Opened 2016-12-10 11:40 UTC by jborean93

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
win_service

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```

##### SUMMARY
Rewrite the win_service module to support the below features
* Allow it to return existance info instead of just failing outright
* Return a lot more info on the service such as username, dependencies, description, etc
* Allow setting of the service username and password
* Allow setting of dependencies
* Allow creation/removal of services
* Allow setting description, display name and path to executable of service

2016-12-20 02:30 UTC, nitzmahone commented
@jborean93 This looks pretty good- I'm going to do some more testing this week, but I think this is the way we'll go. I *might* want to do the default status behavior by setting state to default to `state: status` (or something less lame than that), but otherwise, I think it's pretty much good (I'll let you know after playing with it some more). Hoping I won't be cursing myself a year or two from now that we let this thing get too big/complicated, but it's not too bad yet (see the EC2 module for anti-patterns). 

Thanks for adding test coverage for new features. You also checked a couple more things off my personal TODO list by creating a surrogate service for this to test against (always bugged me that we're dinking around with a real system service). :)

2016-12-20 05:30 UTC, jborean93 commented
@nitzmahone Thanks for the update, I will be on holiday's for the coming weeks but feel free to make any changes to the code if you wish otherwise I may be a bit slow to reply to some messages and requests.

2017-01-30 20:59 UTC, jborean93 commented
@nitzmahone sorry if I am spamming you but were you able to test this change?

2017-02-10 23:15 UTC, nitzmahone commented
There's a couple weeks after the main feature freeze where I'll spend some time poking at this more- should be merged soon after Feb. 15.

2017-02-12 23:40 UTC, jborean93 commented
No worries thanks for the update.

2017-02-20 12:18 UTC, dagwieers commented
@jborean93 Can you integrate #20509 and #20539 ?

Especially regarding `-Force`, you seem to be forceing by default.
Is that on purpose ?

2017-02-20 12:20 UTC, dagwieers commented
BTW Because of your rewrite, the module no longer is easy to understand/straightforward as it was in https://github.com/dagwieers/ansible/blob/df3ae0787f369850d0a734db56d00ae507957090/lib/ansible/modules/windows/win_service.ps1

So I don't know if it is still a good candidate as a reference module :-/

2017-02-20 12:28 UTC, jborean93 commented
Hey @dagwieers, I didn't have a reasoning behind it apart from if you state to Ansible you want to stop a service it should stop. After looking at the docs it might be relevant to set another parameter like @nitzmahone suggested. I am feeling that `ignore_dependent_services` as that is really what the -Force parameter does.

2017-02-20 12:30 UTC, dagwieers commented
Ok. I trust you more than my Windows experience :-)

2017-02-20 12:30 UTC, dagwieers requested changes

2017-02-20 12:30 UTC, dagwieers commented on lib/ansible/modules/windows/win_service.ps1
> +$username = Get-AnsibleParam -obj $params -name 'username' -failifempty $false -default $null
Most of these do not have a strict -type used. I would make the following modifications:
- Add `-type "str"` to all of them, add `-type "path"` to the path parameter.
- Remove `-default $null` because that is the default for unset parameters.
- Remove `-failifempty $false` because that is the default for parameters.
- I prefer to use `-validateset` (all lowercase) since we don't do it for anything else (not -Name, not -failIfEmpty, etc.)
- I prefer to have lists comma-seperated (no space) so it parses easier for humans (just a preference, do as you like)

2017-02-20 12:30 UTC, dagwieers commented on lib/ansible/modules/windows/win_service.ps1
> +    warnings = @()
No longer need to add an empty `warnings` entry.
Use `Add-Warning()` instead !

2017-02-20 12:30 UTC, dagwieers commented on lib/ansible/modules/windows/win_service.ps1
> +}
Would be nice to do this for `-type list` automatically !
Could you add this and make this module use it too ?

2017-02-20 12:30 UTC, dagwieers commented on lib/ansible/modules/windows/win_service.ps1
> +                    Set-ItemProperty -Path $delayed_key -Name "DelayedAutostart" -Value 0 -Type DWORD -WhatIf
I started doing `-WhatIf:$check_mode` which avoids most of the duplicated code.

2017-02-20 12:30 UTC, dagwieers commented on lib/ansible/modules/windows/win_service.ps1
> +                $svc | Set-Service -DisplayName $display_name -WhatIf
Same here, try using `-WhatIf:$check_mode` instead.

2017-02-20 12:30 UTC, dagwieers commented on lib/ansible/modules/windows/win_service.ps1
> +                $svc | Set-Service -Description $description -WhatIf
Same here, try using `-WhatIf:$check_mode` instead.

2017-02-20 12:30 UTC, dagwieers commented on lib/ansible/modules/windows/win_service.ps1
> +                Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Services\$name" -Name ImagePath -Value $path -WhatIf
Same here, try using `-WhatIf:$check_mode` instead.

2017-02-20 12:30 UTC, dagwieers commented on lib/ansible/modules/windows/win_service.ps1
> +                Start-Service -Name $svc.Name -WhatIf
Same here, try using `-WhatIf:$check_mode` instead.

2017-02-20 12:30 UTC, dagwieers commented on lib/ansible/modules/windows/win_service.ps1
> +                Stop-Service -Name $svc.Name -Force -WhatIf
Same here, try using -WhatIf:$check_mode instead.

2017-02-20 12:30 UTC, dagwieers commented on lib/ansible/modules/windows/win_service.ps1
> +                Restart-Service -Name $svc.Name -Force -WhatIf
Same here, try using `-WhatIf:$check_mode` instead.

2017-02-20 12:30 UTC, dagwieers commented on lib/ansible/modules/windows/win_service.ps1
> +                Stop-Service -Name $svc.Name -Force -WhatIf
Same here, try using `-WhatIf:$check_mode` instead.

2017-02-20 12:30 UTC, dagwieers commented on lib/ansible/modules/windows/win_service.ps1
> +                    New-Service -Name $name -BinaryPathname $path -WhatIf
Same here, try using `-WhatIf:$check_mode` instead.

2017-02-20 12:30 UTC, dagwieers commented on lib/ansible/modules/windows/win_service.ps1
> +        exists = $false
This is a bit weird to me. Must be easier to do :-)

2017-02-20 12:30 UTC, dagwieers commented on lib/ansible/modules/windows/win_service.py
> +    required: False
If it is not required, you don't need to state `required: False`. That's implicit.
It is easier to see which parameters are required if those only have `required: True`.

2017-02-20 12:32 UTC, jborean93 commented on lib/ansible/modules/windows/win_service.ps1
> +$username = Get-AnsibleParam -obj $params -name 'username' -failifempty $false -default $null
will make the changes, at the time it didn't have your work on this.

2017-02-20 12:32 UTC, jborean93 commented on lib/ansible/modules/windows/win_service.ps1
> +    warnings = @()
same as above :)

2017-02-20 12:34 UTC, dagwieers commented on lib/ansible/modules/windows/win_service.ps1
> +$username = Get-AnsibleParam -obj $params -name 'username' -failifempty $false -default $null
No, indeed, I ditched my work over yours ;-)

2017-02-20 12:54 UTC, jborean93 commented on lib/ansible/modules/windows/win_service.ps1
> +        exists = $false
I'm not sure if there is an easier way, all it is doing is recreating an empty result again, do you have another suggestion?

2017-02-20 13:18 UTC, jborean93 commented
I've made the changes locally but an issue with the devel branch is stopping me from committing. I need to spend some time to test out the pipelining stuff recently merged in as it seems to not pass in the values set when calling the task.

2017-02-20 13:37 UTC, dagwieers commented on lib/ansible/modules/windows/win_service.ps1
> +        exists = $false
Well, I wouldn't be expecting that at this point, when removing a service (which appears to be only stopping the service ??) the $result dictionary would have anything except the initialized data.

But I am not in favor of the current structure of the code where we seem to run a lot of stuff even when state -eq "absent". I'd rather see a large if-then-elseif-elseif-elseif structure for each of the possible states.

Also, I am a bit confused as this module seems to be able to create services, as well as change their state. Which is different from the Unix **service** module, where you can only do started, stopped or restarted, and reloaded. And you can enable/disable them on boot. But not create or remove them. I think that is confusing somehow (present/absent vs started/stopped/restarted/reloaded and enabled/disabled).

2017-02-20 20:53 UTC, jborean93 commented
After having a think about it overnight from your comments and just a general vibe I feel that maybe this module should be split up into different modules and `win_service` changed like the below

`win_service`: Allows you to set the description, path of a service. Could allow you to create a basic service as well as remove one
`win_service_dependencies`: Allows you to set, add, remove services that are dependencies for this service
`win_service_log_on`: Allows you to configure the Log on as account for a service
`win_service_stat`: Get's the details of a service (whether it exists) and all the return values in this current PR.
`win_service_status`: could be `win_service_state` to keep consistent but I feel this is close to `stat` and it is called Status in Windows. This allows you to stop, start or restart a service.
`win_service_startup`: Allows you to set the startup type of a service

The only question I have is whether to change the functionality of `win_service` to the above or deprecate that module and add in that functionality to something like `win_service_details` or `win_service_config` I'm not sure on.

While I am happy to push ahead with this PR I feel it might be necessary at the currently level of complexity in the code as well as testing this might start to turn into the `ec2` module of Windows.

Thoughts @dagwieers @jhawkesworth @nitzmahone @trondhindenes @JimFicarra

2017-02-20 21:04 UTC, dagwieers commented
@jborean93 I hope that won't be necessary, but I don't know what the right interface is either.

2017-03-02 06:17 UTC, nitzmahone commented
I like "right-sized" modules- this one's getting a *little* big, but it also seems unlikely that it'd need to get much bigger over time, since we've pretty well covered the SCM surface area (unlike EC2, which is a constantly moving target). I'd prefer this to a bunch of super-tiny modules.

I'm going to merge as-is to ensure we make the module cutoff- we can diddle with some of the internals over the next couple weeks, but I'm pretty happy with the UI, docs, and tests. Thanks @jborean93, and thanks to @dagwieers for the thorough review.

2017-03-02 06:17 UTC, merged