Add module for managing boot environments on FreeBSD/Solaris/illumos …
ansible/ansible pull request #19180
Opened 2016-12-10 20:55 UTC by xen0l

##### ISSUE TYPE

- New Module Pull Request
##### COMPONENT NAME

beadm.py
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

This module enables management of ZFS boot environments on FreeBSD/illumos systems (Solaris should be supported as well, but it wasn't tested).

2016-12-10 20:55 UTC, xen0l commented
Migrated from https://github.com/ansible/ansible-modules-extras/pull/3076

2016-12-10 22:13 UTC, xen0l commented
@ansible, I got this reviewed. Can this be merged?

2017-01-02 20:58 UTC, xen0l commented
@sivel you closed ansible/ansible-modules-extras#3076, which was reviewed there. This was reviewed by @jurajlutter there. Any chance to get this merged?

2017-01-02 22:17 UTC, gundalow requested changes
needs_revision 
1) please update CHANGELOG.md in the root if the future repo so the new module is listed under 2.3

2) please add the ANSIBLE_META data before the DOCUMENTION block, see other modules for examples

2017-01-02 22:17 UTC, gundalow commented on lib/ansible/modules/system/beadm.py
> +version_added: "2.2"
2.3

2017-01-02 22:17 UTC, gundalow commented on lib/ansible/modules/system/beadm.py
> +# Create ZFS boot environment
Please write examples in multi-line YAML with `key: value`
Also  use `name: ...` rather than a comment to describe what the task is doing.

2017-01-02 22:17 UTC, gundalow commented on lib/ansible/modules/system/beadm.py
> +from ansible.module_utils.basic import *
Please only import what you need, rather than `*`

2017-01-02 22:17 UTC, gundalow commented on lib/ansible/modules/system/beadm.py
> +RETURN = '''
It looks like this module will return data, if that's correct please document. See other modules for an example

2017-01-09 07:52 UTC, gundalow approved these changes

2017-01-09 07:52 UTC, merged