new module: ssm_parameter_store
ansible/ansible pull request #19196
Opened 2016-12-11 10:57 UTC by SydOps

ISSUE TYPE

New Module Pull Request
COMPONENT NAME

cloud/amazon/ssm_parameter_store.py

ANSIBLE VERSION

ansible 2.2.0.0
config file = /etc/ansible/ansible.cfg
configured module search path = Default w/o overrides

SUMMARY

This module is used to create, update, show and delete parameter in AWS parameter store.

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/sysman-paramstore-walk.html

2016-12-11 10:57 UTC, SydOps commented
Migrated from https://github.com/ansible/ansible-modules-extras/pull/3691

2017-02-01 01:24 UTC, willthames requested changes

2017-02-01 01:24 UTC, willthames commented on lib/ansible/modules/cloud/amazon/ssm_parameter_store.py
> +short_description: Manage key-vaule pairs in aws parameter store.
typo: value

2017-02-01 01:24 UTC, willthames commented on lib/ansible/modules/cloud/amazon/ssm_parameter_store.py
> +version_added: "2.2"
Should be 2.3 now

2017-02-01 01:24 UTC, willthames commented on lib/ansible/modules/cloud/amazon/ssm_parameter_store.py
> +      changed = True
This needs to go through flake8, two character indents are very weird.

2017-02-01 01:24 UTC, willthames commented on lib/ansible/modules/cloud/amazon/ssm_parameter_store.py
> +        description = dict(required=False),
required=False is default, so this can just be `dict()`

2017-02-01 01:24 UTC, willthames commented
needs_revision

2017-02-01 09:18 UTC, zimbatm commented
Please remove me from the bot mentions. The linked help page doesn't give me a way to do it myself.

2017-04-10 00:12 UTC, gkrizek commented
@SydOps Any idea on when the revisions will be added? Would love to see this module added.

2017-04-10 00:18 UTC, SydOps commented
@gkrizek 

I lost the way to submit my updates. 

With the normal way, I committed my changes in my fork repo, it will appear in PR directly. But ansible used a different way to manage PRs. 

For example, my fork is from `ansible/ansible-modules-extras`, but PR has to be raised in `ansible/ansible`. Seems there are something broken.

2017-04-10 00:35 UTC, gkrizek commented
@SydOps Hmm, strange. 

@willthames Any guidance on the above? Should there just be a new PR from the Ansibe repo?

2017-04-10 00:41 UTC, simplesteph requested changes
@SydOps I think you have to create a new PR based on the `ansible/ansible` repo. Shouldn't be too hard as it's a new module.

It's an awesome module, I can't wait to use it to push my vault variables into SSM using this module. Going to make my deploys way more secure

2017-04-10 00:41 UTC, simplesteph commented on lib/ansible/modules/cloud/amazon/ssm_parameter_store.py
> +    value: "World"
aren't you supposed to add a reference to a key there to store a SecureString?

2017-04-10 00:45 UTC, gkrizek commented on lib/ansible/modules/cloud/amazon/ssm_parameter_store.py
> +    value: "World"
I think so too. Such as the `state: show` on line 105.

2017-04-10 00:56 UTC, jersten commented on lib/ansible/modules/cloud/amazon/ssm_parameter_store.py
> +    value: "World"
:+1:

2017-04-10 01:56 UTC, wimnat commented on lib/ansible/modules/cloud/amazon/ssm_parameter_store.py
> +        state =       dict(default='present', choices=['present', 'absent', 'show']),
`show` state would probably be better as a separate '_facts' module.

2017-04-10 03:13 UTC, simplesteph commented on lib/ansible/modules/cloud/amazon/ssm_parameter_store.py
> +        state =       dict(default='present', choices=['present', 'absent', 'show']),
Although I would normally agree, SSM is so simple and the API so streamlined, that I feel it would be overhead more than anything.

2017-04-10 03:19 UTC, SydOps commented on lib/ansible/modules/cloud/amazon/ssm_parameter_store.py
> +    value: "World"
@simplesteph 

Do you mean I have to close the current PR and raise a new one every time, if I need to update and add commits?

2017-04-10 04:14 UTC, simplesteph commented on lib/ansible/modules/cloud/amazon/ssm_parameter_store.py
> +    value: "World"
@SydOps unsure... but that's how I would do it. Just linked back to this one for discussion points

2017-04-10 12:51 UTC, gkrizek commented on lib/ansible/modules/cloud/amazon/ssm_parameter_store.py
> +        state =       dict(default='present', choices=['present', 'absent', 'show']),
I agree with @simplesteph

2017-04-10 12:59 UTC, wimnat commented on lib/ansible/modules/cloud/amazon/ssm_parameter_store.py
> +        state =       dict(default='present', choices=['present', 'absent', 'show']),
Well I would at least enable check mode in the module so people can 'show' in check mode.

2017-04-10 14:50 UTC, SydOps commented
new PR has been raised: 

#23460

2017-04-10 14:50 UTC, closed without merging

2017-04-10 14:51 UTC, SydOps commented on lib/ansible/modules/cloud/amazon/ssm_parameter_store.py
> +version_added: "2.2"
fixed in new PR #23460

2017-04-10 14:51 UTC, SydOps commented on lib/ansible/modules/cloud/amazon/ssm_parameter_store.py
> +      changed = True
fixed in new PR #23460

2017-04-10 14:51 UTC, SydOps commented on lib/ansible/modules/cloud/amazon/ssm_parameter_store.py
> +short_description: Manage key-vaule pairs in aws parameter store.
fixed in new PR #23460

2017-04-10 14:51 UTC, SydOps commented on lib/ansible/modules/cloud/amazon/ssm_parameter_store.py
> +        description = dict(required=False),
fixed in new PR #23460