add option for path to pear executable
ansible/ansible pull request #19200
Opened 2016-12-11 16:07 UTC by mmckinst

ref https://github.com/ansible/ansible-modules-extras/pull/3365

this PR adds the feature @resmo suggested at https://github.com/ansible/ansible-modules-extras/pull/3365#issuecomment-262194091

---

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME
pear

##### ANSIBLE VERSION
```
ansible 2.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY
This allows you to specify a path to the pear executable or a directory where the pear executable is located. This is useful if you have multiple versions of PHP installed at once and need to install pecl modules for them. I've included a playbook showing its usefulness on a CentOS 7 machine using SCL RPMs but there are other methods.

```yaml
- hosts: localhost
  tasks:
    - name: install prereqs
      package: name={{ item }}
      with_items:
        - epel-release
        - centos-release-scl
        - centos-release-scl-rh
    - name: install packages 
      package: name={{ item }}
      with_items:
        - gcc-c++
        - libssh2-devel
        - php-pear
        - php-devel
        - php55-php-devel
        - php55-php-pear
        - rh-php56-php-pear
        - rh-php56-php-devel
    - name: create symlink to give non-standard name for SCL php55 pear
      file:
        state: link
        src: /opt/rh/php55/root/usr/bin/pear
        dest: /usr/bin/php55-pear
    - name: install pecl-ssh2 for default PHP
      pear:
        name: pecl/ssh2
    - name: install pecl-ssh2 for SCL php55 using explicit path
      pear:
        name: pecl/ssh2
        executable: /usr/bin/php55-pear
    - name: install pecl-ssh2 for SCL php56 using directory where pear executable is located
      pear:
        name: pecl/ssh2
        executable: /opt/rh/rh-php56/root/usr/bin/
```

2017-02-15 02:30 UTC, mmckinst commented
@gentledevil can you take a look at this? Its the same PR you approved at https://github.com/ansible/ansible-modules-extras/pull/3365 but someone requested a feature be added before it was to be merged. I have added that feature. It needs your approval again to move forward.

2017-02-15 16:14 UTC, gentledevil commented
> The explicit executable or path to find the pear executable

Maybe the description could be reworded ? Sounds weird/not clear to me, but maybe it's just me.

shipit

2017-02-24 21:31 UTC, franckcuny commented
Agree with @gentledevil this could be reworded differently, maybe 

    Path to the pear executable

Won't block the review for this though.

Shipit.

2017-08-03 06:06 UTC, resmo requested changes
could you please correct the version added and ping me afterwards, so this get merged into 2.4? 

Thanks!

2017-08-03 06:06 UTC, resmo commented on lib/ansible/modules/packaging/language/pear.py
> +      version_added: "2.3"
please change version_added to "2.4"

2017-08-03 14:37 UTC, resmo approved these changes

2017-08-03 15:08 UTC, merged

2017-08-03 15:08 UTC, resmo commented
Thanks!