Avi Networks Ansible modules.
ansible/ansible pull request #19248
Opened 2016-12-12 18:49 UTC by grastogi23

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

network/avi

##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = /home/grastogi/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY

New Avi Ansible modules. They provide full configuration and API support for Avi Vantage Solution. The modules honor impotency and depend on pip package avisdk.

Dependencies: avisdk, requests
Avi Version: 16.3.2

```

```

2016-12-12 18:50 UTC, grastogi23 commented
Re-submitting the Avi modules pull request which was originally submitted for ansible modules extras
https://github.com/ansible/ansible-modules-extras/pull/3062

2016-12-12 19:45 UTC, gundalow commented
Hi
1) Does the Avi lib that these modules depend on work on Python 2.4?
If so this code needs to work on py2.4
If not then please remove the check by editing https://github.com/ansible/ansible/blob/devel/test/compile/python2.4-skip.txt

2) We've found it best to raise a single PR with with a single module (and any associated `module_utils` or `docs_fragments`), getting that fully reviewed and integrated.
Only then raise one PR per module to get the rest reviewed.


So with the above in mind

3) There are a lot of duplicated options here.
Any options that are used in all modules should be defined in `module_utils`
https://github.com/ansible/ansible/tree/devel/lib/ansible/module_utils
See 
https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/f5.py#L39
And the documentation for those options should be documented https://github.com/ansible/ansible/blob/devel/lib/ansible/utils/module_docs_fragments/f5.py

And the following added into the module
`extends_documentation_fragment: avi`

4) Similarly any common code should be pushed into `lib/ansible/module_utils/avi.py`

2016-12-12 20:23 UTC, gundalow requested changes
I've only done a partial review of the first module

Please review that and http://docs.ansible.com/ansible/dev_guide/developing_modules.html#module-checklist before resubmitting.

I believe this is autogenerated, if so a single PR is OK.

The main issue is there is a lot of common code/docs that's duplicated.

2016-12-12 20:23 UTC, gundalow commented on lib/ansible/modules/network/avi/avi_actiongroupconfig.py
> +- code: 'avi_actiongroupconfig controller=10.10.25.42 username=admin '
Please rewrite in this form:
```
EXAMPLES = '''
- name: Example git checkout from Ansible Playbooks
  git:
    repo: git://foosball.example.org/path/to/repo.git
    dest: /srv/checkout
    version: release-0.22

- name: Example read-write git checkout from github
  git:
    repo: ssh://git@github.com/mylogin/hello.git
    dest: /home/mylogin/hello
```


Also the order is

DOCUMENTATION
EXAMPLES
RETURNS

2016-12-12 20:23 UTC, gundalow commented on lib/ansible/modules/network/avi/avi_actiongroupconfig.py
> +# Comment: import * is to make the modules work in ansible 2.0 environments
We only put modules into the latest release, e.g. 2.3
I'll need to dig out the official End Of Life date for Ansible 2.0, though we strongly recommend that you (and your users) move to Ansible 2.2

2016-12-12 20:23 UTC, gundalow commented on lib/ansible/modules/network/avi/avi_actiongroupconfig.py
> +from ansible.module_utils.basic import *
If this is for Ansible 2.3+ please change this to only import the specific needed utils rather than `*`

2016-12-12 20:23 UTC, gundalow commented on lib/ansible/modules/network/avi/avi_actiongroupconfig.py
> +            - location of the controller. Environment variable AVI_CONTROLLER is default
All descriptions should be full sentences, e.g. Capital letters and full stops.

Variables such as AVI_CONTROLLER should be written as `C(AVI_CONTROLLER)` so they are formatted correctly.

2016-12-12 20:23 UTC, gundalow commented on lib/ansible/modules/network/avi/avi_actiongroupconfig.py
> +            - Not present.
Is this needed?

2016-12-12 20:23 UTC, gundalow commented on lib/ansible/modules/network/avi/avi_actiongroupconfig.py
> +            - Not present.
Is this needed?

2016-12-12 20:23 UTC, gundalow commented on lib/ansible/modules/network/avi/avi_actiongroupconfig.py
> +            - Not present. object ref Tenant.
Is this needed?

2016-12-12 20:23 UTC, gundalow commented on lib/ansible/modules/network/avi/avi_actiongroupconfig.py
> +            - url
URl of what?

2016-12-12 20:23 UTC, gundalow commented on lib/ansible/modules/network/avi/avi_actiongroupconfig.py
> +        argument_spec=dict(
1) Common arguments (which you should document in a `docs_fragment` should be pulled out of here, see
https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/f5/bigip_device_dns.py#L374

And corresponding code in https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/f5.py#L39

2) Please reformat so each option is on a singleline, and fix indentation.

3) Secret items, such as `password` should have ` no_log=True`

2016-12-12 20:23 UTC, gundalow commented on lib/ansible/modules/network/avi/avi_actiongroupconfig.py
> +    main()
Please add the missing newline

2016-12-12 22:45 UTC, grastogi23 commented on lib/ansible/modules/network/avi/avi_actiongroupconfig.py
> +# Comment: import * is to make the modules work in ansible 2.0 environments
We are forced to be compatible as our customers are not yet moved beyond 2.0. Actually, I did not have this line before but had to put it in due to one of the very large Ansible customer is using Ansible 2.0

2016-12-12 22:46 UTC, grastogi23 commented on lib/ansible/modules/network/avi/avi_actiongroupconfig.py
> +from ansible.module_utils.basic import *
Current version of avi module works with the ansible 2.0. I request to allow this for greater compatibility.

2016-12-12 22:46 UTC, grastogi23 commented on lib/ansible/modules/network/avi/avi_actiongroupconfig.py
> +            - location of the controller. Environment variable AVI_CONTROLLER is default
ok

2016-12-12 23:33 UTC, grastogi23 commented
Regarding the module_docs_fragment comment. It would break our ability to package avi modules in roles as roles eg. 
https://github.com/avinetworks/ansible-role-avisdk

Can you pl. provide some information / documentation on how we can package the additional module_utils and modules_doc_fragments.

thanks

2016-12-13 12:40 UTC, gundalow commented
The documentation process always builds from `devel`, so it's easy to submit a PR to update to update a docs_fragment and get that reflected on `docs.ansible.com`. That update process is out-of-band to the usual release cycle, i.e. we can update the docs at any time.

@grastogi23 I see there is an email thread about this now. Let me chat to some of the rest of the Core Team to see how we can avoid the issues you've highlighted.

2016-12-14 23:32 UTC, grastogi23 commented on lib/ansible/modules/network/avi/avi_actiongroupconfig.py
> +    main()
fixed

2016-12-14 23:35 UTC, grastogi23 commented
I have committed a new version addressing most of the review comments except
from ansible.module_utils.basic import *

2016-12-15 12:16 UTC, gundalow requested changes
1) In the `short_description:` 

More examples at U(https://github.com/avinetworks/avi-ansible-samples)

2) There are various options defined that you've not provided any documentation for. Everything defined in `argument_specs` needs documenting in the module.

2016-12-15 12:16 UTC, gundalow commented on lib/ansible/modules/network/avi/avi_actiongroupconfig.py
>      name:
The examples show `name:` is needed, if that's correct then this needs documenting

2016-12-15 12:16 UTC, gundalow commented on lib/ansible/modules/network/avi/avi_actiongroupconfig.py
>      uuid:
uuid needs documenting as it's `argument_specs`.

2016-12-15 12:16 UTC, gundalow commented on lib/ansible/modules/network/avi/avi_actiongroupconfig.py
>      description:
description needs documenting as it's `argument_specs`.

2016-12-15 12:16 UTC, gundalow commented on lib/ansible/modules/network/avi/avi_actiongroupconfig.py
> +            - reference of the action script configuration to be used. It is reference to an object of type AlertScriptConfig.
reference -> Reference

2016-12-15 21:40 UTC, grastogi23 commented
Updated modules ensuring descriptions for every option.

2016-12-19 16:58 UTC, gundalow commented
You're last change has added a load of trailing whitespace in, that needs removing.

2016-12-20 12:21 UTC, gundalow requested changes
1) Should `url` be added to module_utils/avi.py and docs_fragment

2) Ensure any options defined in avi_common_argument_spec aren't repeated in module documentation

3) Ensure all `documentation:` lines are full sentences, (capital letters & fullstop), acronyms have capital letters (API, not api), and are not placeholders

2016-12-20 12:21 UTC, gundalow commented on lib/ansible/modules/network/avi/avi_api_session.py
> +    username:
Duplicated documentation here (username, password)

2016-12-20 12:21 UTC, gundalow commented on lib/ansible/modules/network/avi/avi_api_session.py
> +            - get, put, post, delete
The list should be in `choices:` and add a meaningful `descriptions:`

Also missing `post`

2016-12-20 12:21 UTC, gundalow commented on lib/ansible/modules/network/avi/avi_api_session.py
> +    tenant:
I believe `tenant:` is defined in the docs_fragment.

2016-12-20 12:21 UTC, gundalow commented on lib/ansible/modules/network/avi/avi_api_session.py
> +    password:
I believe this is defined in the docs_fragment.

2016-12-20 12:21 UTC, gundalow commented on lib/ansible/modules/network/avi/avi_controllerproperties.py
> +            - Placeholder for description of property allow_unauthenticated_nodes.
Placeholder docs, this applies to multiple modules

2016-12-20 12:21 UTC, gundalow commented on lib/ansible/modules/network/avi/avi_controllerproperties.py
> +        type: bool
We don't define the `type:` in the `DOCUMENTATION` block, only in `RETURNS`, so these can be removed from all modules.

2016-12-20 15:49 UTC, grastogi23 commented
URL is not desired to be in the common as there are a few modules we will be adding which don't have url. Eg. Analytics. URLs are only valid for the objects.

2017-01-18 18:54 UTC, grastogi23 commented
Please add @grastogi23, @khaltore and @ericsysmin as reviewers

2017-01-18 18:54 UTC, closed without merging