Added in bullet of Python 2.4+ support discontinuation
ansible/ansible pull request #19264
Opened 2016-12-12 22:53 UTC by thaumos

##### ISSUE TYPE
 - Docs Pull Request

##### SUMMARY
Added in bullet point about Python 2.4 support.

2016-12-13 08:57 UTC, gundalow requested changes
Needs to clarify if this is the controller or the remote end (also what are the official terms we use for the machine running ansible-playbook and the remote side?)

2017-01-31 17:37 UTC, gundalow commented
Python 2.4 will no longer be supported for modules. This means from Ansible 2.4 (and forward) only Python 2.6+ will be supported.

2017-01-31 17:40 UTC, bcoca commented
we skip 2.5?

2017-01-31 17:43 UTC, bcoca commented on docsite/rst/roadmap/ROADMAP_2_4.rst
> +  - Python 2.4 will no longer be supported. Going forward, Python 2.6+ will be supported.
bikeshedding:
"Python 2.4 will no longer be supported on target machines (controller already required >=2.6), from now on Ansible will require >=Python2.6"

2017-01-31 18:39 UTC, gundalow commented
Thanks Brian, that's clearer.

For the record we *are* dropping Module support for py2.4 and py2.5

2017-01-31 19:57 UTC, bcoca commented
then heading should also include 2.5

2017-02-08 04:02 UTC, thaumos commented
shipit

2017-02-08 07:16 UTC, gundalow approved these changes

2017-02-09 15:56 UTC, gundalow commented
[15:56] <@bcoca> i'm happy, abadger2000 is ecstatic

2017-02-09 15:57 UTC, merged