authorized_key: support --diff
ansible/ansible pull request #19277
Opened 2016-12-13 08:47 UTC by mgedmin

### Test plan

``` yml
# test.yml

---
- hosts: localhost
  gather_facts: no
  vars:
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    user: "{{ ansible_user }}"
  tasks:
    - authorized_key: path=./auth_keys key="{{ key }}" user="{{ user }}"
```

```
$ ansible-playbook -i localhost, test.yml -CD
$ ansible-playbook -i localhost, test.yml -D
```
### Expected output

```
PLAY [localhost] ***************************************************************

TASK [authorized_key] **********************************************************
--- before: ./auth_keys
+++ after: ./auth_keys
@@ -0,0 +1 @@
+ssh-rsa AAAA.....

changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0   
```

2016-12-13 08:47 UTC, mgedmin commented
Migrated from https://github.com/ansible/ansible-modules-core/pull/3026

2016-12-13 10:33 UTC, edgarsj commented
+1. Was really expecting this to work already when using authorized_keys module.

2016-12-14 15:31 UTC, robinro commented
This is maybe a good occasion to also add a testcase for checkmode and the diff?

Something like 
```
authorized_key: key={{foo}} ...
check_mode: True
register: add_key

assert: 
  that: 
    - 'add_key|changed'
    - '"part-of-key" in add_key.diff...'```

2016-12-16 08:11 UTC, mgedmin commented
Rebased on devel and added an integration test.

2016-12-27 08:26 UTC, gundalow requested changes
needs_revision

2016-12-27 08:26 UTC, gundalow commented on lib/ansible/modules/system/authorized_key.py
>      return (key, key_type, options, comment, rank)
The file mode has changed, please change it back to 644

2016-12-27 08:27 UTC, mgedmin commented on lib/ansible/modules/system/authorized_key.py
>      return (key, key_type, options, comment, rank)
Whoops, vim autocommand magic strikes again!

2016-12-27 08:29 UTC, mgedmin commented
Rebased and force-pushed to fix the accidental chmod.

2016-12-27 08:36 UTC, gundalow approved these changes
shipit 

Bonus points for test case. I'd like someone else to look at this before merging.

2016-12-27 09:13 UTC, robinro approved these changes
LGTM

2017-01-03 14:32 UTC, merged