new AWS KMS module
ansible/ansible pull request #19309
Opened 2016-12-13 18:11 UTC by tedder

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
`kms`

##### ANSIBLE VERSION
```
ansible 2.3.0

```

##### SUMMARY
- adds/removes user/role from a KMS key. Nothing else. Good start for a KMS administration module. Needed because it can't really be done in Cloudformation.

2016-12-13 18:33 UTC, tedder commented
Need a rerun on Shippable.

2016-12-30 17:20 UTC, ryansb requested changes

2016-12-30 17:20 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/kms.py
> +module: kms
Can you rename this as `aws_kms` please? Three-letter acronyms have enough risk for overlap that it's probably worth doing.

2016-12-30 17:20 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/kms.py
> +short_description: Perform various KMS management tasks.
Maybe `Manage role/user access to a KMS key` would be more descriptive.

2016-12-30 17:20 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/kms.py
> +    - Role to allow/deny access. One of C(role_name) or C(role_arn) are required.
Please also add `role_arn` as a doc param.

2016-12-30 17:20 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/kms.py
> +    haz = {}
Not everyone on the codebase is aware that has==haz, or even has English-as-a-first-language. Can you rename this to be clearer?

2016-12-30 17:20 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/kms.py
> +            module.fail_json(msg=error_msg, traceback=traceback.format_exc().splitlines())
When using fail_json, please include `exception=traceback.format_exc()` as a kwarg.

2016-12-30 17:20 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/kms.py
> +        module.fail_json(msg=str(e))
When using fail_json, please include `exception=traceback.format_exc()` as a kwarg.

2017-01-03 02:19 UTC, tedder commented on lib/ansible/modules/cloud/amazon/kms.py
> +module: kms
done. it's the only `aws_` module, fwiw. But I agree on the likely overlap.

2017-01-03 02:23 UTC, tedder commented on lib/ansible/modules/cloud/amazon/kms.py
> +        module.fail_json(msg=str(e))
okay. Looks like usage of this for the "create boto conn" exception is all over the map, fwiw.,

2017-01-03 04:41 UTC, tedder commented
Changes are in. Added "arn cleanup" from my own testing.

2017-01-03 21:40 UTC, ryansb requested changes
Should be set to go after this set of changes.

2017-01-03 21:40 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/aws_kms.py
> +                    if clean_invalid_entries and len(list(filter(lambda x: not x.startswith('arn:aws:iam::'), statement['Principal']['AWS']))):
Can you make this into a couple statements for easier readability? Something like:

```
invalid_entries = [x for x in statement['Principal']['AWS'] 
    if not x.startswith('arn:aws:iam::)]
if clean_invalid_entries and len(invalid_entries):
    for entry in invalid_entries:
        statement['Principal']['AWS'].remove(entry)
```

Or there's always:

```
original_size = len(statement['Principal']['AWS'])
statement['Principal']['AWS'] = [x for x in statement['Principal']['AWS'] 
    if x.startswith('arn:aws:iam::)]
have_invalid_entries = (original_size == len(statement['Principal']['AWS']))
```

2017-01-03 21:40 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/aws_kms.py
> +have_invalid_entries:
`s/have/had/`

2017-01-03 21:40 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/aws_kms.py
> +    if mode == 'grant' or mode == 'deny':
You don't need this conditional, since Ansible enforces that these are the only choices.

2017-01-03 21:40 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/aws_kms.py
> +                module.fail_json(msg='KMS ARN is required to {}'.format(mode))
Add here that the `key_alias` or `key_arn` are both ways to provide it.

2017-01-03 21:40 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/aws_kms.py
> +            #policy_json_string = json.dumps({'Policy': policy})
Please remove this comment since it's not needed.

2017-01-03 21:54 UTC, tedder commented on lib/ansible/modules/cloud/amazon/aws_kms.py
> +                    if clean_invalid_entries and len(list(filter(lambda x: not x.startswith('arn:aws:iam::'), statement['Principal']['AWS']))):
yeah, I iterated through this in a few ways. See if you like the latest.. or do you really dislike the filter()?

2017-01-05 14:38 UTC, ryansb approved these changes

2017-01-05 14:43 UTC, merged

2017-01-05 14:43 UTC, ryansb commented
![](https://www.prlog.org/10422244-youre-approved.jpg)