Add new module for elasticache parameter group.
ansible/ansible pull request #19375
Opened 2016-12-15 10:24 UTC by akurniawan

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
elasticache_parameter_group

##### ANSIBLE VERSION
```
2.2.0
```

##### SUMMARY
This is new module to create parameter group for elasticache in AWS

2017-02-01 00:42 UTC, willthames commented on lib/ansible/modules/cloud/amazon/elasticache_parameter_group.py
> +    if changed:
you can just `module.exit_json(changed=changed, parameter_groups=response)`

2017-02-01 01:09 UTC, willthames commented on lib/ansible/modules/cloud/amazon/elasticache_parameter_group.py
> +    session = boto3.Session(aws_access_key_id=params["aws_access_key"],
we should be using boto3_conn for all connections. For example, security_token is missing here. boto3_conn avoids you having to worry about that.

2017-02-01 01:09 UTC, willthames commented on lib/ansible/modules/cloud/amazon/elasticache_parameter_group.py
> +    HAS_BOTO = True
should be HAS_BOTO3

2017-02-01 09:18 UTC, zimbatm commented
Please remove me from the bot mentions. The linked help page doesn't give me a way to do it myself.

2017-02-01 11:08 UTC, akurniawan commented
Hi @zimbatm, how exactly can I do that?

2017-02-01 23:52 UTC, willthames requested changes

2017-02-01 23:52 UTC, willthames commented on lib/ansible/modules/cloud/amazon/elasticache_parameter_group.py
> +version_added: "2.2"
Should be 2.3

2017-02-01 23:52 UTC, willthames commented on lib/ansible/modules/cloud/amazon/elasticache_parameter_group.py
> +    result = []
This method can be simplified to:

```
return [{"ParameterName": str(k), "ParameterValue": str(v)} for (k,v) in params.items]
```

2017-02-01 23:52 UTC, willthames commented on lib/ansible/modules/cloud/amazon/elasticache_parameter_group.py
> +from ansible.module_utils.basic import *
Should be changed to new style module imports nearer the top of the file:

```
from ansible.module_utils.basic import AnsibleModule
from ansible.module_utils.ec2 import ec2_argument_spec, get_aws_connection_info, boto3_conn
```

2017-02-02 04:36 UTC, willthames commented on lib/ansible/modules/cloud/amazon/elasticache_parameter_group.py
> +from ansible.module_utils.basic import *
This is still outstanding

2017-02-02 04:36 UTC, willthames commented on lib/ansible/modules/cloud/amazon/elasticache_parameter_group.py
> +    result = []
This is a suggestion, not a blocker.

2017-02-02 05:14 UTC, akurniawan commented on lib/ansible/modules/cloud/amazon/elasticache_parameter_group.py
> +from ansible.module_utils.basic import *
should I put the imports to the very beginning of the file or above DOCUMENTATION variable?

2017-02-02 05:19 UTC, willthames commented on lib/ansible/modules/cloud/amazon/elasticache_parameter_group.py
> +from ansible.module_utils.basic import *
I put mine after the comments just above the documentation variable as then it passes pep8.

2017-02-02 05:54 UTC, willthames commented on lib/ansible/modules/cloud/amazon/elasticache_parameter_group.py
> +try:
flake8 will moan about this - and apologies for not being clearer. Leave this section where it was, and then everything should be fine. One thing to note while I'm in the area,but it's not a blocker, is that flake8 will complain less if you add HAS_BOTO3 to the list of imports and don't import boto3 (in the `except ImportError` part, just `pass`, as you'll handle that  using HAS_BOTO3 later)

2017-02-02 08:58 UTC, akurniawan commented on lib/ansible/modules/cloud/amazon/elasticache_parameter_group.py
> +try:
I don't quite follow this part 
> add HAS_BOTO3 to the list of imports and don't import boto3. 

Is this what you mean?
try:
    import botocore
    HAS_BOTO3 = True
except ImportError:
    pass

How can I tell if boto3 is really installed?

2017-02-03 03:48 UTC, willthames commented on lib/ansible/modules/cloud/amazon/elasticache_parameter_group.py
> +try:
```
from ansible.module_utils.ec2 import HAS_BOTO3

try:
    import botocore
except ImportError:
    pass  # will be caught by imported HAS_BOTO3
```

2017-02-03 03:50 UTC, willthames commented
I'm sorry, I've given bad advice - ansible/proposals#50 now means that, in contradiction to what standard flake8 says, the imports should be after all the documentation. This has been a little bit of a moving target during my reviews of this PR, but I still apologise for the misinformation. Should be an easy fix though.

2017-02-28 20:38 UTC, s-hertel commented
Closing because pr #21023 was merged. If you think there is missing functionality, please let me know.

2017-02-28 20:38 UTC, closed without merging