Env vars
ansible/ansible pull request #19385
Opened 2016-12-15 16:13 UTC by machacekondra

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

lib/ansible/module_utils/ovirt.py

##### ANSIBLE VERSION

```
2.3.0
```

##### SUMMARY

This patch adds support to enter authentication parameters via environment variables,
instead of passing it via module parameters.

2016-12-15 16:13 UTC, machacekondra commented
@mwperina @ryansb

2016-12-16 14:58 UTC, ryansb requested changes

2016-12-16 14:58 UTC, ryansb commented on lib/ansible/utils/module_docs_fragments/ovirt.py
> +            - "C(password)[I(required)] - The password of the user. Could be also specified by I(OVIRT_PASSWORD) environment variable."
Can you specify in these docs which takes precedence?

2016-12-16 20:17 UTC, machacekondra commented on lib/ansible/utils/module_docs_fragments/ovirt.py
> +            - "C(password)[I(required)] - The password of the user. Could be also specified by I(OVIRT_PASSWORD) environment variable."
I've written there, that environment variables are the default one.

2016-12-30 17:23 UTC, ryansb approved these changes

2016-12-30 17:24 UTC, merged