added vmware_add_nic module
ansible/ansible pull request #19394
Opened 2016-12-15 19:20 UTC by mholiv

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME
vmware_add_nic

##### ANSIBLE VERSION

```
ansible --version
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```

##### SUMMARY

A module that allows the user to add nics to virtual hosts to VMware

2016-12-15 22:19 UTC, mholiv commented
All checks now passed yay!

2017-02-01 00:27 UTC, dagwieers commented
The module name should be something like **vmware_guest_nic** as it manages the nic (not just add them, that would not be idempotent). The other concern I have is that this functionality is currently taken care of by vmware_guest (or at least there is overlapping functionality.

My preference would be that any change to the vmware_guest call for a given VM would automatically modify that VM to the requested form. So in this case hot-add/hot-remove NICs. Not sure if that is currently possible or wanted.

2017-07-18 11:31 UTC, jctanner commented
@mholiv is this something you still want to work on?

needs_info

2017-07-18 13:07 UTC, dagwieers commented
+label new_module

2017-07-25 11:59 UTC, cdelgehier commented
ahah, VMWare talk to me in french :s But it doesn't work 

```python
>>> vm = content.searchIndex.FindByUuid(None, '4218eab0-a5a9-b98a-8d42-ec846d22fe0b', True)
>>> for device in vm.config.hardware.device:
...     device.deviceInfo.label
... 
'IDE 0'
'IDE 1'
'Contrôleur PS2 0'
'Contrôleur PCI 0'
'Contrôleur SIO 0'
'Clavier '
'Périphérique de pointage'
'Carte vidéo '
'Périphérique VMCI'
'Contrôleur SCSI 0'
'Disque dur 1'
'Adaptateur réseau 1'
```

```
ok: [testvm -> localhost] => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "datacenter": "Blue", 
            "dvs": false, 
            "hostname": "172.16.17.2", 
            "label": "Adaptateur réseau 1", 
            "network_name": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "state": "absent", 
            "type": "vmxnet3", 
            "username": "vmware", 
            "validate_certs": false, 
            "vm_path": "/DEV/TEST/testvm"
        }
    }, 
    "msg": "No NIC with the name: Adaptateur réseau 1 was found"
}
```

2017-07-27 04:57 UTC, Akasurde requested changes

2017-07-27 04:57 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_add_nic.py
> +module: vmware_nic
Could you please match the name of module - `vmware_add_nic` ?

2017-07-27 04:57 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_add_nic.py
> +     - Allows non-idempotent creation of VMs. Updates and removals are idempotent.
Do you mean `Allows non-idempotent creation of NIC for VMs` ?

2017-07-27 04:57 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_add_nic.py
> +  vm_path:
Could you please change this to `folder` to match other VMware modules?

2017-07-27 04:57 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_add_nic.py
> +def get_vm_object(module, conn, path, datacenter):
Could you please use `find_vm_by_id` from vmware module_utils ?

2017-07-27 04:57 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_add_nic.py
> +        pg_obj = get_obj_by_name(conn, [vim.dvs.DistributedVirtualPortgroup], desired_nic['network'])
Could you please use `find_dvs_by_name` from vmware module_utils ?

2017-07-27 04:57 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_add_nic.py
> +                vm_path=dict(required=True, type='str'),
Can you please include `uuid` as parameter for finding VM ? you can use `find_by_vm_id` API for finding VM using uuid just like other VMware modules do.

2017-07-27 04:57 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_add_nic.py
> +from ansible.module_utils.basic import *
Please use particular import from these modules.

2017-07-27 04:57 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_add_nic.py
> +
Could you please add integration tests for this module ? Please take a look at various VMware related tests in `test/integration` directory.

2017-07-27 19:10 UTC, cdelgehier commented
Adding a card to a vswitch works.
But when you pass the `dvs` to `true` for an existing DVSwitch, we get an error
```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_m6fqrU/ansible_module_vmware_nic.py", line 433, in <module>
    main()
  File "/tmp/ansible_m6fqrU/ansible_module_vmware_nic.py", line 402, in main
    results = create_nic(module, conn, proper_vm, desired_nic)
  File "/tmp/ansible_m6fqrU/ansible_module_vmware_nic.py", line 202, in create_nic
    nic_spec.device.backing.deviceName = desired_nic['network']
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/VmomiSupport.py", line 537, in __setattr__
    CheckField(self._GetPropertyInfo(name), val)
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/VmomiSupport.py", line 342, in GetPropertyInfo
    raise AttributeError(name)
AttributeError: deviceName
```

Otherwise I have to bypass the language problem by changing the conditions:

```if nic['nic_obj'].deviceInfo.label == desired_nic['label']:```
to 
```if nic['nic_obj'].deviceInfo.label.rsplit(None, 1)[-1] == desired_nic['label']:```

So the `label` parameter changes from `Network adapter 1` to `1`

2017-08-08 14:25 UTC, dagwieers commented
So the module freeze deadline for v2.4 is getting closer (2017-08-31). Now is the time to finish up, get it reviewed and merged with no delay.

2018-02-19 11:27 UTC, Akasurde commented
@mholiv Are you still working on this ?

2018-02-19 18:13 UTC, mholiv commented
No. This should be encompassed in the general VMware module set anyways.

2018-04-02 08:56 UTC, Akasurde commented
Closing this due to inactivity of contributor.

2018-04-02 08:56 UTC, closed without merging