Improve YAML examples - windows/win_package.py
ansible/ansible pull request #19407
Opened 2016-12-15 20:47 UTC by Fale

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
lib/ansible/modules/windows

##### ANSIBLE VERSION
```
2.2
```

##### SUMMARY
Improve examples

@gundalow
@nitzmahone

2016-12-15 23:04 UTC, nitzmahone requested changes

2016-12-15 23:04 UTC, nitzmahone commented on lib/ansible/modules/windows/win_package.py
> +    Product_Id: {CF2BEA3C-26EA-32F8-AA9B-331F7E34BA97}
These will need to remain quoted (either kind)- naked `{` at the beginning of a YAML value will be interpreted as a dictionary.

2016-12-15 23:04 UTC, nitzmahone commented on lib/ansible/modules/windows/win_package.py
> +    product_id: {0240359E-6A4C-4884-9E94-B397A02D893C}
Quote

2016-12-15 23:04 UTC, nitzmahone commented on lib/ansible/modules/windows/win_package.py
> +    product_id: {0240359E-6A4C-4884-9E94-B397A02D893C}
Quote

2016-12-15 23:04 UTC, nitzmahone commented on lib/ansible/modules/windows/win_package.py
> +- name: Install the vVisual C thingy
s/vVisual/Visual/

2016-12-16 09:20 UTC, Fale commented on lib/ansible/modules/windows/win_package.py
> +- name: Install the vVisual C thingy
Thanks, fixed

2016-12-16 09:20 UTC, Fale commented on lib/ansible/modules/windows/win_package.py
> +    Product_Id: {CF2BEA3C-26EA-32F8-AA9B-331F7E34BA97}
True, sorry about that

2016-12-16 09:20 UTC, Fale commented on lib/ansible/modules/windows/win_package.py
> +    product_id: {0240359E-6A4C-4884-9E94-B397A02D893C}
True, sorry about that

2016-12-16 09:20 UTC, Fale commented on lib/ansible/modules/windows/win_package.py
> +    product_id: {0240359E-6A4C-4884-9E94-B397A02D893C}
True, sorry about that

2016-12-19 21:58 UTC, merged