Add ipadm_addrprop module
ansible/ansible pull request #19415
Opened 2016-12-15 21:36 UTC by xen0l

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME
ipadm_addrprop

##### ANSIBLE VERSION
latest

##### SUMMARY
Module for managing IP address properties on illumos/Solaris systems.

2017-01-03 16:15 UTC, privateip requested changes
* missing metadata which is required for 2.3 modules
* please consider adding unit tests

2017-01-03 16:15 UTC, privateip commented on lib/ansible/modules/network/illumos/ipadm_addrprop.py
> +RETURN = '''
return keys must be documented

2017-01-03 16:15 UTC, privateip commented on lib/ansible/modules/network/illumos/ipadm_addrprop.py
> +from ansible.module_utils.basic import *
please use explicit imports `from ansible.module_utils.basic import AnsibleModule`

2017-01-03 16:15 UTC, privateip commented on lib/ansible/modules/network/illumos/ipadm_addrprop.py
> +main()
please wrap in block

```
if __name__ == '__main__':
   main()
```

2017-01-08 18:39 UTC, xen0l commented
@privateip I addressed you comments. As for unit tests, they will be shared among all modules to a certain degree (I am also speaking about modules, which are already included with Ansible). For that reason, I would like to add them in the next round if possible.

2017-01-08 18:39 UTC, xen0l commented
ready_for_review

2017-01-09 17:29 UTC, merged