Add ipadm_ifprop module
ansible/ansible pull request #19416
Opened 2016-12-15 21:37 UTC by xen0l

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

##### ANSIBLE VERSION

Latest

##### SUMMARY
Module for managing IP interface properties on illumos/Solaris systems.

2017-01-03 16:13 UTC, privateip requested changes
* Missing metadata.  Metadata is now required for 2.3 modules
* please consider adding unit tests to the test folder as well.  this will be a required element soon

2017-01-03 16:13 UTC, privateip commented on lib/ansible/modules/network/illumos/ipadm_ifprop.py
> +RETURN = '''
return data must be documented

2017-01-03 16:13 UTC, privateip commented on lib/ansible/modules/network/illumos/ipadm_ifprop.py
> +from ansible.module_utils.basic import *
please use explicit imports .... `from ansible.module_utils.basic import AnsibleModule` ... etc

2017-01-03 16:13 UTC, privateip commented on lib/ansible/modules/network/illumos/ipadm_ifprop.py
> +main()
please wrap in block

```
if __name__ == '__main__':
   main()
```

2017-01-08 18:28 UTC, xen0l commented
ready_for_review

2017-01-08 18:31 UTC, xen0l commented
@privateip I addressed you comments. As for unit tests, they will be shared among all modules to a certain degree (I am also speaking about modules, which are already included with Ansible). For that reason, I would like to add them in the next round if possible.

2017-01-09 17:29 UTC, privateip approved these changes

2017-01-09 17:29 UTC, merged