Add dladm_linkprop module
ansible/ansible pull request #19413
Opened 2016-12-15 21:35 UTC by xen0l

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME
dladm_linkprop

##### ANSIBLE VERSION
latest

##### SUMMARY

Module to manage network link interface properties on illumos/Solaris systems.

2017-01-03 16:18 UTC, privateip requested changes
* missing METADATA
* please consider adding unit tests

2017-01-03 16:18 UTC, privateip commented on lib/ansible/modules/network/illumos/dladm_linkprop.py
> +RETURN = '''
RETURN doc string is required

2017-01-03 16:18 UTC, privateip commented on lib/ansible/modules/network/illumos/dladm_linkprop.py
> +from ansible.module_utils.basic import *
please use explicit imports

2017-01-03 16:18 UTC, privateip commented on lib/ansible/modules/network/illumos/dladm_linkprop.py
> +main()
please wrap in `IF` block

2017-01-08 21:54 UTC, xen0l commented
ready_for_review

2017-01-08 21:54 UTC, xen0l commented
@privateip I addressed you comments. As for unit tests, they will be shared among all modules to a certain degree (I am also speaking about modules, which are already included with Ansible). For that reason, I would like to add them in the next round if possible.

2017-01-09 17:31 UTC, privateip approved these changes

2017-01-09 17:31 UTC, merged