Add ipadm_addr module
ansible/ansible pull request #19411
Opened 2016-12-15 21:33 UTC by xen0l

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME
ipadm_addr

##### ANSIBLE VERSION
latest

##### SUMMARY
Module for managing IP address configuration on illumos/Solaris systems.

2017-01-03 16:22 UTC, privateip requested changes
* missing RETURN doc string
* missing METADATA
* please consider adding unit test cases

2017-01-03 16:22 UTC, privateip commented on lib/ansible/modules/network/illumos/ipadm_addr.py
> +from ansible.module_utils.basic import *
please use explicit imports

2017-01-03 16:22 UTC, privateip commented on lib/ansible/modules/network/illumos/ipadm_addr.py
> +main()
please wrap in `if` block

2017-01-08 21:44 UTC, xen0l commented
ready_for_review

2017-01-08 21:44 UTC, xen0l commented
@privateip I addressed you comments. As for unit tests, they will be shared among all modules to a certain degree (I am also speaking about modules, which are already included with Ansible). For that reason, I would like to add them in the next round if possible.

2017-01-09 17:33 UTC, privateip requested changes

2017-01-09 17:33 UTC, privateip commented on lib/ansible/modules/network/illumos/ipadm_addr.py
> +version_added: "2.1"
VERSION_ADDED should be "2.3"

2017-01-09 18:45 UTC, xen0l commented
@privateip I bumped version to 2.3

2017-01-09 19:32 UTC, merged