Add dladm_vlan module
ansible/ansible pull request #19412
Opened 2016-12-15 21:34 UTC by xen0l

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME
dladm_vlan

##### ANSIBLE VERSION
latest

##### SUMMARY
Module to manage VLAN interfaces on illumos/Solaris systems.

2017-01-03 16:20 UTC, privateip requested changes
* missing RETURN doc string
* missing METADATA
* please consider adding unit test cases

2017-01-03 16:20 UTC, privateip commented on lib/ansible/modules/network/illumos/dladm_vlan.py
> +from ansible.module_utils.basic import *
please use explicit import statements

2017-01-03 16:20 UTC, privateip commented on lib/ansible/modules/network/illumos/dladm_vlan.py
> +main()
please wrap in `if` block

2017-01-08 21:50 UTC, xen0l commented
@privateip I addressed you comments. As for unit tests, they will be shared among all modules to a certain degree (I am also speaking about modules, which are already included with Ansible). For that reason, I would like to add them in the next round if possible.

2017-01-08 21:50 UTC, xen0l commented
ready_for_review

2017-01-09 17:32 UTC, merged