Initial Commit for Infinidat Ansible Modules
ansible/ansible pull request #19429
Opened 2016-12-16 12:04 UTC by GR360RY

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

- infini_export
- infini_export_client
- infini_fs
- infini_host
- infini_pool
- infini_vol

##### ANSIBLE VERSION

```
ansible 2.3.0 (devel 57a1283b33) last updated 2016/12/16 14:01:18 (GMT +300)
  config file =
  configured module search path = Default w/o overrides
```

##### SUMMARY

Modules for managing Infinidat Infinibox storage. Separate modules to create/delete/modify pools, volumes, filesystems, hosts and exports.

```

```

2016-12-16 13:07 UTC, gundalow requested changes
needs_revision.
I've only reviewed the first module, though a lot of that feedback would apply to the other modules.

As mentioned on `#ansible-devel`, it may be worth pushing the common code & arguments into `module_utils`, as well as creating a `docs_fragment` for the documenting common arguments.

2016-12-16 13:07 UTC, gundalow commented on lib/ansible/modules/storage/infinidat/infini_export.py
> +short_description: Create, Delete or Modify NFS Export on Infinibox
Should that me exports (plural)?

2016-12-16 13:07 UTC, gundalow commented on lib/ansible/modules/storage/infinidat/infini_export.py
> +      - Export name. Should always start with \"/\". (ex. name=/data)
You can use `C()` for constant width which doesn't require escaping, which also gives better formatting.

2016-12-16 13:07 UTC, gundalow commented on lib/ansible/modules/storage/infinidat/infini_export.py
> +      - Creates/Modifies export when present and removes when absent
Missing full stop. All `descriptions:` must be full sentences. This applies to a few other `descriptions:` in these modules.

2016-12-16 13:07 UTC, gundalow commented on lib/ansible/modules/storage/infinidat/infini_export.py
> +      - Infinibox hostname or IP address
Do you support IPv6, if not then this should say IPv4 address.

2016-12-16 13:07 UTC, gundalow commented on lib/ansible/modules/storage/infinidat/infini_export.py
> +      - Infinibox User username
As there different levels of user permissions on Infinibox, if so it's worth saying "Infinibox User username with FOO permissions"

Also say, if not specified C(INFINIBOX_USER) will be used, or C(~/.infinidat/infinisdk.ini).

2016-12-16 13:07 UTC, gundalow commented on lib/ansible/modules/storage/infinidat/infini_export.py
> +    See http://infinisdk.readthedocs.io/en/latest/getting_started.html
U(http://infinisdk.readthedocs.io/en/latest/getting_started.html)

2016-12-16 13:07 UTC, gundalow commented on lib/ansible/modules/storage/infinidat/infini_export.py
> +      - Infinibox User password
Also say, if not specified C(INFINIBOX_PASSWORD) will be used, or C(~/.infinidat/infinisdk.ini).

2016-12-16 13:07 UTC, gundalow commented on lib/ansible/modules/storage/infinidat/infini_export.py
> +EXAMPLES = '''
In all the examples rather than specifying a `# comment` please set that as the `- name:`, remember you will need to remove the `-` from before the module.

2016-12-16 13:07 UTC, gundalow commented on lib/ansible/modules/storage/infinidat/infini_export.py
> +            user        = dict(no_log=True),
We generally don't mask the usernames, just passwords.

2016-12-16 13:07 UTC, gundalow commented on lib/ansible/modules/storage/infinidat/infini_export.py
> +        supports_check_mode=False
What would be required for this to be idempotent, e.g. support check mode.
http://docs.ansible.com/ansible/playbooks_checkmode.html

2016-12-16 13:07 UTC, gundalow commented on lib/ansible/modules/storage/infinidat/infini_export.py
> +from ansible.module_utils.basic import *
Could you please rewrite to just import what you need.

2016-12-16 13:07 UTC, gundalow commented on lib/ansible/modules/storage/infinidat/infini_export.py
> +# Export and specify client list explictly
explicitly

2016-12-16 13:07 UTC, gundalow commented on lib/ansible/modules/storage/infinidat/infini_vol.py
> +      - Volume size in MB, GB or TB units. See examples.
The example uses `1T`, 

However later on you have
`module.fail_json(msg='size (Physical Capacity) should be defined in MB, GB, TB or PB units')`

2016-12-16 13:07 UTC, gundalow commented on lib/ansible/modules/storage/infinidat/infini_export.py
> +author: Gregory Shulov
`author: Gregory Shulov (@GR360RY)"`

2016-12-18 17:37 UTC, GR360RY commented
All points should be addressed now. Commits are squashed to a single commit that incorporates all the changes:

* Cleanup documentation
* Move Shared documentations to fragments
* Move shared common code to modules_utils
* All modules are idempotent and check mode is enabled for all modules.

The only thing that brakes now is the Shippable with uninformative error:
![screen shot 2016-12-18 at 19 31 20](https://cloud.githubusercontent.com/assets/828309/21295236/5f646584-c559-11e6-8451-ab549b461d89.png)

@gundalow , can you please review and comment ?

2016-12-19 04:48 UTC, willthames commented
The test failures were introduced by: 884b5291

2016-12-19 11:10 UTC, willthames commented
If you rebase this on latest devel branch it should pass tests (as failing test was fixed in #19506)

2016-12-19 13:20 UTC, gundalow requested changes

2016-12-19 13:20 UTC, gundalow commented on lib/ansible/module_utils/infinibox.py
> +    return [['user', 'password']]
Missing newline

2016-12-19 13:20 UTC, gundalow commented on lib/ansible/modules/storage/infinidat/infini_export.py
> +  infini_export: name=/data01 filesystem=foo user=admin password=secret system=ibox001
We are standerdising on multiline YAMl examples, please rewrite in the same form as your `Export and specify client list explicitly` example.

This comment may apply to other examples in your new modules as well.

2016-12-19 13:20 UTC, gundalow commented on lib/ansible/utils/module_docs_fragments/infinibox.py
> +      - Infinibox Hostname or IPv4 Address
Missing full stop.

2016-12-19 13:20 UTC, gundalow commented on lib/ansible/utils/module_docs_fragments/infinibox.py
> +      - Infinibox User password
Missing full stop.

2016-12-19 13:20 UTC, gundalow commented on lib/ansible/utils/module_docs_fragments/infinibox.py
> +'''
Missing newline

2016-12-19 13:20 UTC, gundalow commented on lib/ansible/utils/module_docs_fragments/infinibox.py
> +author: Gregory Shulov (@GR360RY)
Please remove `author`. It's possible that in the future someone else may develop a module that uses this docs fragment.

2016-12-19 19:17 UTC, GR360RY commented
Ready for review. All requested changes are made:

* All examples are rewritten in multiline format.
* New lines and description fields are fixed.
* Author added to each individual module and removed from fragments part

@gundalow , tell me if need to rebase and squash in case everything is intact.
Should I also update the CHANGELOG.md **New Modules** section ?

2016-12-19 20:23 UTC, gundalow commented
@GR360RY Updating CHANGELOG.md is a good idea, see the 2.2 list for how to fornat that.

No need to squash, I'll do that when I merge

2016-12-19 21:07 UTC, GR360RY commented
Updated CHANGELOG.md and added ANSIBLE_METADATA in format proposed by ( https://github.com/ansible/proposals/issues/30 )

2016-12-21 04:47 UTC, GR360RY commented
@gundalow , anything else I should do to move this PR forward ?

2016-12-22 13:17 UTC, gundalow approved these changes

2016-12-22 13:18 UTC, merged

2016-12-22 13:41 UTC, gundalow commented
Merged, thanks

Please see https://github.com/ansible/ansibullbot/pull/231 about maintainers