Add comment option to authorized_key
ansible/ansible pull request #19424
Opened 2016-12-16 06:29 UTC by cao

##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

authorized_key - Adds or removes an SSH authorized key
##### ANSIBLE VERSION

```
2.1.0.0
```
##### SUMMARY

The patch adds the comment option to the authorized_key module.

The comment option can be used to overwrite the comment for an SSH key before writing it to disk. It is useful when fetching the keys from a source that does not carry a meaningful comment, such as Gitlab or Github.

2016-12-16 06:29 UTC, cao commented
Migrated from https://github.com/ansible/ansible-modules-core/pull/4094

2016-12-16 08:48 UTC, xen0l requested changes

2016-12-16 08:48 UTC, xen0l commented on lib/ansible/modules/system/authorized_key.py
> +    default: null
You want to state default: None instead of default: null for consistency. Otherwise, LGTM.

2016-12-16 18:12 UTC, cao commented on lib/ansible/modules/system/authorized_key.py
> +    default: null
It appears that None and null are mixed throughout the codebase. Is there some documentation that describes the preferred/canonical way?

2016-12-16 18:37 UTC, xen0l commented on lib/ansible/modules/system/authorized_key.py
> +    default: null
None, that I am aware of. I am always using the same value as default in argument_spec.

2016-12-20 11:42 UTC, cao commented on lib/ansible/modules/system/authorized_key.py
> +    default: null
I am using `null` as the default argument for `description` because it is the default for `key_options` also.

2017-01-22 00:51 UTC, cao commented
Is anything blocking the pull request?

2017-08-04 17:48 UTC, samdoran commented on lib/ansible/modules/system/authorized_key.py
> +            parsed_new_key = (parsed_new_key[0], parsed_new_key[1], parsed_new_key[2], comment)
Need to add the original index to the end of this tuple, otherwise an out of bounds error will be thrown on line 608.

2017-08-04 17:50 UTC, samdoran requested changes
I have addressed issues in a new branch. Will submit a new PR shortly.

2017-08-04 18:09 UTC, samdoran commented
Thank you for your submission. I made a few changes to your PR but had to do it in a new branch and submit a new PR (#27781). You can [allow changes to your PR](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) to make it easier for us to make changes and get things merged.

Thanks again for contributing to Ansible!

2017-08-04 18:09 UTC, closed without merging