Add Ability to Exlude Paths from Archive
ansible/ansible pull request #19453
Opened 2016-12-16 19:54 UTC by rjsabatini

##### ISSUE TYPE

- Feature Pull Request
##### COMPONENT NAME

files/archive.
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

The archive module allows you to pass a glob to the path argument.
This feature allows end users to continue to pass a glob to the path argument,
but enables a new argument to exclude specific dirs, or a glob of dirs in order to prevent
unwanted paths from being archived. The idea is to enable similar functionality as the
`--exclude=PATTERN` option for the `tar` command.

2016-12-16 19:54 UTC, rjsabatini commented
Migrated from https://github.com/ansible/ansible-modules-extras/pull/3069

2016-12-19 16:28 UTC, bendoh requested changes
Looks good to me! There are a couple of minor typos that should be cleaned up.

2016-12-19 16:28 UTC, bendoh commented on lib/ansible/modules/files/archive.py
> +# Create a bz2 archive of a globbed path, while exluding specific dirnames
Typo: `exluding` should be `excluding`

2016-12-19 16:28 UTC, bendoh commented on lib/ansible/modules/files/archive.py
> +    description: The list of matching exlude paths from the exclude_path argument.
Typo: `exlude` -> `exclude`

2016-12-22 02:10 UTC, rjsabatini commented
I have corrected the typos, thank you for catching them!

2017-03-30 12:37 UTC, rjsabatini commented
Is there something more that needs to be done to have this merged?

2017-06-22 09:40 UTC, abadyan-vonage commented
@bendoh Is this expected to be merged into ansible? We also need this functionality.

2017-07-12 21:24 UTC, rjsabatini commented
I've rebased with devel to fix the merge conflict. Let me know if there is more that you would like to see added in order to move the PR forward. I'd love to get this merged and closed off since it's been open for so long.

2017-07-13 01:01 UTC, bendoh commented
shipit

2017-07-13 01:04 UTC, bendoh commented
bot_status

2017-07-13 01:07 UTC, bendoh commented
!needs_revision

I'm only marked as a contributor to this, so I don't believe I have any influence on the bot.

2017-07-13 01:13 UTC, bendoh commented
!needs_revision

2017-07-13 01:20 UTC, rjsabatini commented
@bendoh Does it need revision or are you trying to get the bot to remove the flag?

2017-07-13 01:22 UTC, bendoh commented
AFAICT it doesn't need any revision, just trying to get the bot to undo the flag –– It LGTM tho!

2017-07-13 13:39 UTC, rjsabatini commented
ready_for_review

2017-07-19 18:02 UTC, rjsabatini commented
bot_broken

2017-07-24 01:47 UTC, mattclay commented
Removing broken label to permit the bot to continue processing this PR. This PR appears to be waiting on approval from a second maintainer as documented here:

https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#existing-modules

2017-07-24 02:28 UTC, rjsabatini commented
@mattclay Who would the second maintainer be? I only know of @bendoh. I added the bot broken label because it wasn't properly removing the needs revision tag.

2017-07-24 03:05 UTC, mattclay commented
A second approval from either a maintainer in the same namespace (files) or from a core maintainer should be adequate. @jctanner Is that correct?

2017-07-31 18:46 UTC, abadger commented
+1 from me too.  WIll merge to devel

2017-07-31 18:46 UTC, merged

2017-07-31 18:49 UTC, abadger commented
Merged to devel for the 2.4.0 release.  Thanks @rjsabatini for the code and @bendoh for the review!

2018-01-23 09:13 UTC, mkrizek commented
@bendoh Your `!needs_revision` command didn't work because your review still says that you requested changes, you'd need to approve the PR via gihub UI to get rid of that label.