Allow setting ipv4.dhcp-client-id parameter
ansible/ansible pull request #19471
Opened 2016-12-17 17:56 UTC by opoplawski

##### Issue Type:
- Feature Pull Request
##### Plugin Name:

nmcli
##### Summary:

Allow setting ipv4.dhcp-client-id parameter for an interface.  Fixes #1523
##### Example:

```
- name: Configure dhcp-client-id for CORA network
  nmcli: state=present type=ethernet conn_name=CORA dhcp_client_id={{ ansible_fqdn }}
  tags: network
```

2016-12-17 17:56 UTC, opoplawski commented
Migrated from https://github.com/ansible/ansible-modules-extras/pull/1840

2016-12-19 13:40 UTC, gundalow commented
@alcamie101 I believe you are the current maintainer of this module, could you please review. Thanks

2016-12-19 13:40 UTC, gundalow requested changes
needs_revision

2016-12-19 13:40 UTC, gundalow commented on lib/ansible/modules/network/nmcli.py
> +        version_added: "2.2"
2.3

2016-12-22 18:48 UTC, opoplawski commented
Updated version.

2016-12-22 18:56 UTC, gundalow approved these changes
Still need the maintainer to look at this

2017-01-25 13:51 UTC, gundalow commented
@alcamie101 Could you please have a look at this PR. Thanks

2017-04-27 17:25 UTC, gundalow commented
Hi,
A number of files have been git moved from `modules/network` to `modules/net_tools`, which has effected this PR. Please rebase this PR to pull in that change.

2017-06-29 11:21 UTC, gundalow commented
@opoplawski Could you please rebase this, which will move it to `modules/net_tools` thanks in advance.

2017-07-31 18:47 UTC, calfonso commented
@opoplawski still waiting on this one to be rebased and moved into net_tools. Also waiting for the maintainer to respond to the review request. cc alcamie101

2017-07-31 18:50 UTC, abadger commented
CC @alcamie101 (ping for review of a parameter addition to the nmcli ansible module)

2017-12-27 12:00 UTC, Akasurde commented
@opoplawski Are you still working on this ? If not, let me know, I will take over this ?

2017-12-27 20:42 UTC, opoplawski commented
@Akasurde - If you could take this over, that would be great.  Thanks.

2017-12-28 05:13 UTC, Akasurde commented
@opoplawski Thanks.

Superseded by #34268

2017-12-28 05:13 UTC, closed without merging