Add new parameters to taskdefinition module - network_mode and task_r…
ansible/ansible pull request #19493
Opened 2016-12-18 17:45 UTC by wimnat

##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

ecs_taskdefinition
##### ANSIBLE VERSION

2.2
##### SUMMARY

Resolves #3015 

Adds two new parameters to the module:

task_role_arn 
network_mode

These are new features in AWS

2016-12-18 17:45 UTC, wimnat commented
Migrated from https://github.com/ansible/ansible-modules-extras/pull/3016

2016-12-19 15:57 UTC, Java1Guy approved these changes

2016-12-19 15:58 UTC, Java1Guy approved these changes

2016-12-19 16:05 UTC, gundalow commented
You appear to have made this file executable, please revert that

2016-12-19 16:06 UTC, gundalow requested changes
needs_revision

2016-12-19 16:06 UTC, gundalow commented on lib/ansible/modules/cloud/amazon/ecs_taskdefinition.py
> +        version_added: 2.2
This needs to be a string: `"2.3"`

2016-12-19 16:06 UTC, gundalow commented on lib/ansible/modules/cloud/amazon/ecs_taskdefinition.py
> +        version_added: 2.2
This needs to be a string: `"2.3"`

2016-12-19 18:12 UTC, wimnat commented
ready_for_review

2016-12-19 18:16 UTC, gundalow approved these changes

2016-12-19 18:16 UTC, gundalow commented
Given maintainer @Java1Guy has approved this I'll merge

2016-12-19 18:16 UTC, merged

2016-12-20 12:26 UTC, kkarimi commented
@wimnat I think there is a bug here but not sure, when I try with this definition:
 ```
 - name: Registrator - Create Task Definition
  ecs_taskdefinition:
    state: present
    family: "registrator"
    network_mode: host
    containers:
      - name: registrator
        image: "gliderlabs/registrator:master"
        memory: 10
        portMappings:
          - containerPort: 9998
            hostPort: 9998
            protocol: tcp
        mountPoints:
          - sourceVolume: docker-sock
            containerPath: /var/run/docker.sock
            readOnly: true
 ```

I get:
 ```
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_name": "ecs_taskdefinition"
    }, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/9c/3f5ffpbx6p977jwgv3lj3d8c0000gn/T/ansible_sq3saL/ansible_module_ecs_taskdefinition.py\", line 383, in <module>\n    main()\n  File \"/var/folders/9c/3f5ffpbx6p977jwgv3lj3d8c0000gn/T/ansible_sq3saL/ansible_module_ecs_taskdefinition.py\", line 352, in main\n    volumes)\n  File \"/var/folders/9c/3f5ffpbx6p977jwgv3lj3d8c0000gn/T/ansible_sq3saL/ansible_module_ecs_taskdefinition.py\", line 176, in register_task\n    self.module.fail_json(msg=e.message, **camel_dict_to_snake_dict(e.response))\nNameError: global name 'camel_dict_to_snake_dict' is not defined\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
```

2016-12-20 13:58 UTC, wimnat commented
Hmm what version of ansible are you using? That function has been in since
2.1 I think

On 20 Dec. 2016 12:27, "Kash" <notifications@github.com> wrote:

@wimnat <https://github.com/wimnat> I think there is a bug here but not
sure, when I try with this definition:

- name: Registrator - Create Task Definition
 ecs_taskdefinition:
   state: present
   family: "registrator"
   network_mode: host
   containers:
     - name: registrator
       image: "gliderlabs/registrator:master"
       memory: 10
       portMappings:
         - containerPort: 9998
           hostPort: 9998
           protocol: tcp
       mountPoints:
         - sourceVolume: docker-sock
           containerPath: /var/run/docker.sock
           readOnly: true

I get:

fatal: [localhost]: FAILED! => {
   "changed": false,
   "failed": true,
   "invocation": {
       "module_name": "ecs_taskdefinition"
   },
   "module_stderr": "Traceback (most recent call last):\n  File
\"/var/folders/9c/3f5ffpbx6p977jwgv3lj3d8c0000gn/T/ansible_sq3saL/ansible_module_ecs_taskdefinition.py\",
line 383, in <module>\n    main()\n  File
\"/var/folders/9c/3f5ffpbx6p977jwgv3lj3d8c0000gn/T/ansible_sq3saL/ansible_module_ecs_taskdefinition.py\",
line 352, in main\n    volumes)\n  File
\"/var/folders/9c/3f5ffpbx6p977jwgv3lj3d8c0000gn/T/ansible_sq3saL/ansible_module_ecs_taskdefinition.py\",
line 176, in register_task\n    self.module.fail_json(msg=e.message,
**camel_dict_to_snake_dict(e.response))\nNameError: global name
'camel_dict_to_snake_dict' is not defined\n",
   "module_stdout": "",
   "msg": "MODULE FAILURE",
   "rc": 0
}

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/ansible/ansible/pull/19493#issuecomment-268231076>, or mute
the thread
<https://github.com/notifications/unsubscribe-auth/AHFORlwSMakqN_XJybb7WyPvwmdekeDWks5rJ8msgaJpZM4LQL2b>
.

2016-12-20 14:01 UTC, wimnat commented
Actually I see the problem. The import statement doesn't include the function. I'll submit a PR tonight. Not sure how this passed my testing :/

2016-12-20 14:03 UTC, kkarimi commented
@wimnat I am running against develop branch, so that must be it, thanks 👍