Add ignore_time_wait option
ansible/ansible pull request #19505
Opened 2016-12-19 08:08 UTC by sorenk

##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

wait_for
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

This adds a "ignore_time_wait" option for the wait_for module. 
When using the wait_for module for waiting for all connections to be drained on a loadbalanced node,  it can take very long time (in my expirience more than 10 minutes - I haven't had the patience to wait much longer than that, before my ansible task would timeout). 
I have seen this behaviour on all kinds of linux systems which were running java application servers. 
My understanding is, that time_wait state connections actually are closed, but are waiting to be "recycled". 
I have added as a option to be backwards compatible, but maybe it would even make more sense to completely ignore time_wait connections completely.

Before change:

```
TASK [loadbalancer : Wait for connections to be drained] ********
Friday 07 October 2016  21:15:02 +0200 (0:00:01.261)       0:00:04.732 ******** 
failed: [appserver] (item={u'port': 8080, u'pool': u'appserver-8080'}) => {"elapsed": 900, "failed": true, "item": {"pool": "appserver-8080", "port": 8080}, "msg": "Timeout when waiting for 192.168.1.2:8080 to drain"}
```

After change:

```
TASK [loadbalancer : Wait for connections to be drained] ********
Friday 07 October 2016  22:46:47 +0200 (0:00:01.005)       0:00:04.392 ******** 
ok: [appserver] => (item={u'port': 8080, u'pool': u'appserver-8080'})
```

2016-12-19 08:08 UTC, sorenk commented
Migrated from https://github.com/ansible/ansible-modules-core/pull/5195

2016-12-19 16:10 UTC, gundalow requested changes
needs_revision

2016-12-19 16:10 UTC, gundalow commented on lib/ansible/modules/utilities/logic/wait_for.py
> +    required: false
Options added after a module has been released need version data. Please add
`version_added: "2.3"` in this section

2016-12-19 16:14 UTC, sorenk commented on lib/ansible/modules/utilities/logic/wait_for.py
> +    required: false
Done!

2016-12-19 16:47 UTC, gundalow approved these changes

2016-12-19 17:06 UTC, bcoca commented on lib/ansible/modules/utilities/logic/wait_for.py
> +    required: false
instead of having specific options, a general 'ignore' and being able to feed 'statuses' would be more useful

2016-12-19 19:47 UTC, sorenk commented on lib/ansible/modules/utilities/logic/wait_for.py
> +    required: false
Makes sense...  Something like an "active_connection_states" option which takes a list and has the following default:
[ 'ESTABLISHED', 'SYN_SENT', 'SYN_RECV', 'FIN_WAIT1', 'FIN_WAIT2', 'TIME_WAIT' ]
?

2016-12-19 20:20 UTC, bcoca commented on lib/ansible/modules/utilities/logic/wait_for.py
> +    required: false
sounds good

2017-01-02 12:41 UTC, sorenk commented
I created a new pull request which adds the active_connection_states option. 
https://github.com/ansible/ansible/pull/19775

2017-01-02 12:42 UTC, closed without merging