fix #19487
ansible/ansible pull request #19515
Opened 2016-12-19 13:55 UTC by DavidVentura

this PR fixes #19487

2016-12-19 16:13 UTC, gundalow commented on lib/ansible/modules/cloud/misc/proxmox.py
> +      - Public key to add to /root/.ssh/authorized_keys
`Public key to add to .ssh/authorized_keys.`
Missing full stop
May not be run as root

2016-12-19 16:14 UTC, gundalow commented on lib/ansible/modules/cloud/misc/proxmox.py
> +    description:
Generally we put the `description:` first to make the file more readable.

2016-12-19 16:14 UTC, gundalow requested changes
needs_revision

2016-12-19 16:40 UTC, UnderGreen commented
Will fail on ProxmoxVE < 4.2. You have to add backport compatibility.

2016-12-19 16:48 UTC, DavidVentura commented
@UnderGreen It will only fail **only** if the options are specified and proxmox does not support it. You get an api response saying that the option is not supported. Is this behavior not ok?

2016-12-19 16:49 UTC, DavidVentura commented on lib/ansible/modules/cloud/misc/proxmox.py
> +      - Public key to add to /root/.ssh/authorized_keys
Why can't it be run as root?

2016-12-19 16:51 UTC, gundalow commented on lib/ansible/modules/cloud/misc/proxmox.py
> +      - Public key to add to /root/.ssh/authorized_keys
Apologies, my comment wasn't clear.
I assume this module could be ran as root *or* another user. Therefore the `description:` should be something closer to
`Public key to add to users .ssh/authorized_keys.

2016-12-19 17:01 UTC, DavidVentura commented
Proxmox adds the key to the root user upon creation

On December 19, 2016 1:52:17 PM GMT-03:00, John R Barker <notifications@github.com> wrote:
>gundalow commented on this pull request.
>
>
>
>> @@ -175,6 +175,14 @@
>      - Indicate desired state of the instance
>     choices: ['present', 'started', 'absent', 'stopped', 'restarted']
>     default: present
>+  pubkey:
>+    version_added: "2.3"
>+    description:
>+      - Public key to add to /root/.ssh/authorized_keys
>
>Apologies, my comment wasn't clear.
>I assume this module could be ran as root *or* another user. Therefore
>the `description:` should be something closer to
>`Public key to add to users .ssh/authorized_keys.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ansible/ansible/pull/19515

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

2016-12-19 17:07 UTC, UnderGreen commented
@DavidVentura if Proxmox doesn't support something it will response with 500x :cry:

2016-12-19 17:21 UTC, DavidVentura commented on lib/ansible/modules/cloud/misc/proxmox.py
> +      - Public key to add to /root/.ssh/authorized_keys
Proxmox adds the specified public key to the root user upon container creation.

2016-12-19 17:36 UTC, DavidVentura commented on lib/ansible/modules/cloud/misc/proxmox.py
> +    description:
Swapped in the last commit

2016-12-19 17:37 UTC, DavidVentura commented
@UnderGreen Just pushed the version check

2017-02-07 23:31 UTC, DavidVentura commented
I totally forgot about this. What do we do now? Do you want me to rebase this ?

2017-02-08 07:21 UTC, gundalow commented
Please rebase

2017-02-08 07:25 UTC, gundalow commented on lib/ansible/modules/cloud/misc/proxmox.py
> +      - Public key to add to /root/.ssh/authorized_keys.
If I'm reading the code correct, does this only work on proxmox 4.2+? If so may be worth stating that here.

2017-02-08 07:25 UTC, gundalow commented on lib/ansible/modules/cloud/misc/proxmox.py
> +    type: string
No need to document `type:`, please remove.

2017-02-08 13:55 UTC, DavidVentura commented
I seem to have broken my merge beyond human ability. I'll clean this up and open a new PR with a clean branch.

2017-02-08 13:55 UTC, closed without merging