New AWS module for managing RDS instance using newer boto3 API
ansible/ansible pull request #19523
Opened 2016-12-19 16:56 UTC by aioue

##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

rds_v2
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel e396d5d508) last updated 2016/08/24 12:13:10 (GMT +1000)
  lib/ansible/modules/core: (detached HEAD 368ca738fa) last updated 2016/08/24 12:13:21 (GMT +1000)
  lib/ansible/modules/extras: (detached HEAD 0749ce6faa) last updated 2016/08/24 12:13:30 (GMT +1000)
```
##### SUMMARY

This module manages the creation, modification, deletion, snapshot, restore, reboot, replicate and promote of RDS Instances in AWS.

Note: Technically this is a rewrite of the existing core RDS module and while I believe rewrites using older API's aren't being included until 2.3 I thought people could still use this in the meantime, especially if support for Aurora is required. 

```
TASK [print new RDS instance] **************************************************
ok: [localhost] => {
    "msg": {
        "changed": true, 
        "rds": {
            "DBInstances": [
                {
                    "AllocatedStorage": 10, 
                    "AutoMinorVersionUpgrade": true, 
                    "AvailabilityZone": "ap-southeast-2a", 
                    "BackupRetentionPeriod": 10, 
                    "CACertificateIdentifier": "rds-ca-2015", 
                    "CopyTagsToSnapshot": false, 
                    "DBInstanceClass": "db.t2.medium", 
                    "DBInstanceIdentifier": "test-instance", 
                    "DBInstanceStatus": "available", 
                    "DBParameterGroups": [
                        {
                            "DBParameterGroupName": "test-param-group", 
                            "ParameterApplyStatus": "in-sync"
                        }
                    ], 
                    "DBSecurityGroups": [], 
                    "DBSubnetGroup": {
                        "DBSubnetGroupDescription": "test subnet group", 
                        "DBSubnetGroupName": "test-subnet-group", 
                        "SubnetGroupStatus": "Complete", 
                        "Subnets": [
                            {
                                "SubnetAvailabilityZone": {
                                    "Name": "ap-southeast-2a"
                                }, 
                                "SubnetIdentifier": "subnet-75ed1123", 
                                "SubnetStatus": "Active"
                            }, 
                            {
                                "SubnetAvailabilityZone": {
                                    "Name": "ap-southeast-2b"
                                }, 
                                "SubnetIdentifier": "subnet-6ae33123", 
                                "SubnetStatus": "Active"
                            }
                        ], 
                        "VpcId": "vpc-aad24acf"
                    }, 
                    "DbInstancePort": 0, 
                    "DbiResourceId": "db-7ZINBVLFLHNOT5ROFK76T4XXXX", 
                    "Endpoint": {
                        "Address": "test-instance2.c4nb0jta2bug.ap-southeast-2.rds.amazonaws.com", 
                        "HostedZoneId": "Z32T0VRHXEXXXX", 
                        "Port": 3306
                    }, 
                    "Engine": "mysql", 
                    "EngineVersion": "5.6.27", 
                    "InstanceCreateTime": "2016-09-03T07:36:28.832000+00:00", 
                    "LatestRestorableTime": "2016-09-03T07:40:00+00:00", 
                    "LicenseModel": "general-public-license", 
                    "MasterUsername": "testuser", 
                    "MonitoringInterval": 0, 
                    "MultiAZ": false, 
                    "OptionGroupMemberships": [
                        {
                            "OptionGroupName": "test-option-group", 
                            "Status": "in-sync"
                        }
                    ], 
                    "PendingModifiedValues": {}, 
                    "PreferredBackupWindow": "17:54-18:24", 
                    "PreferredMaintenanceWindow": "fri:12:54-fri:13:24", 
                    "PubliclyAccessible": false, 
                    "ReadReplicaDBInstanceIdentifiers": [], 
                    "StorageEncrypted": false, 
                    "StorageType": "standard", 
                    "VpcSecurityGroups": [
                        {
                            "Status": "active", 
                            "VpcSecurityGroupId": "sg-d188c123"
                        }
                    ]
                }
            ], 
            "ResponseMetadata": {
                "HTTPStatusCode": 200, 
                "RequestId": "022114a4-71aa-11e6-8a7d-bd9007adb1d5"
            }
        }
    }
}
```

2016-12-19 16:56 UTC, aioue commented
Migrated from https://github.com/ansible/ansible-modules-extras/pull/2845 by aioue (not original author)

2016-12-19 17:52 UTC, aioue commented on lib/ansible/modules/cloud/amazon/rds_v2.py
> +        backup_retention_period=dict(type=int, required=False),
Should be `type='int'`.

2016-12-19 17:54 UTC, aioue commented
After that minor change on line 1087, I was able to successfully use this module to create a storage encrypted postrgesql DB. @naslanidis

2016-12-19 18:26 UTC, wimnat requested changes

2016-12-19 18:26 UTC, wimnat commented on lib/ansible/modules/cloud/amazon/rds_v2.py
> +  region:
Not required - added by doc fragement

2016-12-19 18:26 UTC, wimnat commented on lib/ansible/modules/cloud/amazon/rds_v2.py
> +            module.fail_json(msg=str(e))
Handle boto3 exceptions as per the guidelines.

E.g.
```module.fail_json(msg=e.message, **camel_dict_to_snake_dict(e.response))```

2016-12-19 18:26 UTC, wimnat commented on lib/ansible/modules/cloud/amazon/rds_v2.py
> +            module.fail_json(msg=str(e))
As comment above - handle as per the guidelines

2016-12-19 18:26 UTC, wimnat commented on lib/ansible/modules/cloud/amazon/rds_v2.py
> +            status_achieved, response = wait_for_status(client, module, 'available')
There's a new AWS Retry generic handler that you can use here.  Check out the ec2 shared code in module_utils

2016-12-19 18:26 UTC, wimnat commented on lib/ansible/modules/cloud/amazon/rds_v2.py
> +        module.fail_json(msg=str(e))
As comment above - handle as per the guidelines

2016-12-19 18:26 UTC, wimnat commented on lib/ansible/modules/cloud/amazon/rds_v2.py
> +            module.fail_json(msg=str(e))
As comment above - handle as per the guidelines

2016-12-19 18:26 UTC, wimnat commented on lib/ansible/modules/cloud/amazon/rds_v2.py
> +                module.fail_json(msg=str(e))
As comment above - handle as per the guidelines

2016-12-19 18:26 UTC, wimnat commented on lib/ansible/modules/cloud/amazon/rds_v2.py
> +                module.fail_json(msg=str(e))
As comment above - handle as per the guidelines

2016-12-19 18:26 UTC, wimnat commented on lib/ansible/modules/cloud/amazon/rds_v2.py
> +            module.fail_json(msg=str(e))
As comment above - handle as per the guidelines

2016-12-19 18:26 UTC, wimnat commented on lib/ansible/modules/cloud/amazon/rds_v2.py
> +            module.fail_json(msg=str(e))
As comment above - handle as per the guidelines

2016-12-19 18:26 UTC, wimnat commented on lib/ansible/modules/cloud/amazon/rds_v2.py
> +            module.fail_json(msg=str(e))
As comment above - handle as per the guidelines

2016-12-19 18:26 UTC, wimnat commented on lib/ansible/modules/cloud/amazon/rds_v2.py
> +            module.fail_json(msg=str(e))
As comment above - handle as per the guidelines

2016-12-19 18:26 UTC, wimnat commented on lib/ansible/modules/cloud/amazon/rds_v2.py
> +    if module.params.get('tags'):
Use the ec2 helper function `ansible_dict_to_boto3_tag_list`

2016-12-19 18:26 UTC, wimnat commented on lib/ansible/modules/cloud/amazon/rds_v2.py
> +    if not HAS_BOTO3:
Define separate checks for json and boto3

2016-12-19 18:26 UTC, wimnat commented on lib/ansible/modules/cloud/amazon/rds_v2.py
> +    module.exit_json(changed=changed, rds=results)
Use the ec2 helper function `camel_dict_to_snake_dict` to ensure the results are returned in snake_case format

2016-12-30 15:47 UTC, ryansb reviewed
How hard would it be to be param-compatible with the existing RDS module? It would be preferable not to have a whole second module out for boto3 support. A rewrite to handle boto3 is fine, since the old modules are very boto2-dependent.

2016-12-30 15:47 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/rds_v2.py
> +    choices: [ 'mariadb', 'MySQL', 'oracle-se1', 'oracle-se', 'oracle-ee', 'sqlserver-ee', 'sqlserver-se', 'sqlserver-ex', 'sqlserver-web', 'postgres', 'aurora']
Is there a way to find this out by introspecting in boto3 instead? Manually updating this is kind of a pain.

2017-01-06 07:39 UTC, aioue commented
Closing in favour of original author's prmove. https://github.com/ansible/ansible/pull/19783

2017-01-06 07:39 UTC, closed without merging