Stacki host module
ansible/ansible pull request #19532
Opened 2016-12-19 20:29 UTC by bbyhuy

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME
stacki_host

##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = /home/vagrant/automata_modules/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY

Module for managing stacki hosts (add, remove, force-install).

Referencing Revisions: [Previous PR# 19518](https://github.com/ansible/ansible/pull/19518)

```
$ ansible local -i 'localhost,' -c local -m stacki_host -a 'name=test-1 stacki_user=usr stacki_password=pwd stacki_endpoint=url prim_intf_mac=mac_addr prim_intf_ip=x.x.x.x prim_intf=eth0' 

changed: [127.0.0.1] => {"changed": true, "rc": 0, "stderr": "{}", "stdout": "api call successful", "stdout_lines": ["api call successful"]}

```

2016-12-19 20:29 UTC, bbyhuy commented
@gundalow @bsanders

2016-12-20 13:58 UTC, gundalow commented on lib/ansible/modules/infrastructure/stacki/stacki_host.py
> +            stacki_password=dict(required=True, no_log=True, type='str', default=os.environ.get('stacki_password')),
You should mention these these env variables in the `description:`, e.g.

"If not specified the environment variable C(stacki_password) is used instead."

2016-12-20 13:59 UTC, gundalow commented on lib/ansible/modules/infrastructure/stacki/stacki_host.py
> +        module.fail_json(msg='requests is required for this module')
Mention version of requests here as well

2016-12-20 13:59 UTC, gundalow commented on lib/ansible/modules/infrastructure/stacki/stacki_host.py
> + - requests==2.2.1
Exactly 2.2.1 or 2.2.1 or higher?

2016-12-20 14:00 UTC, gundalow requested changes
needs_revision

Shippable is failing due to the use of requests, you'll need to add this to the skip file for that test.

2016-12-20 18:35 UTC, bsanders commented
There's also a 'chdir' option that doesn't appear to be used anymore.

2016-12-20 21:12 UTC, mattclay commented
@bbyhuy Tests are failing because there's no `__init__.py` in the `infrastructure` directory. That directory was recently [removed](https://github.com/ansible/ansible/commit/9816addcdc8e62ba3c2a64223fd4653bbac08250) for being too generic.

You'll need to pick a more appropriate directory for the module.

2016-12-20 21:13 UTC, bsanders commented
This is a +1 Stacki, at least from a Stacki perspective.

@bbyhuy Do you think you'll add other stack commands, or with these two PRs are you pretty much adding what you guys will need?

2016-12-20 21:19 UTC, bsanders commented
@bbyhuy @mattclay very recently removed, heh.  It looks like Foreman and Katello were moved to "remote_management", so Stacki modules should probably go there, too.

2016-12-20 21:42 UTC, bbyhuy commented
@bsanders definitely will be updating it in the near future as we start adding the raiding features and network bonding.

2016-12-21 10:24 UTC, gundalow approved these changes

2016-12-21 10:31 UTC, gundalow commented
If everyone is happy please respond with "ship_it" and I'll get it merged. Looks like you are, just want to check.

@bsanders Are you from Stacki? 

We define a list of module maintainers so we know who should review, I wonder if that should be you and @bbyhuy 

FYI, if in the future you start adding more modules you can pull out common code, arguments and docs into `lib/ansible/module_utils` and `docs_fragments`

2016-12-21 20:08 UTC, bsanders commented
@gundalow Yeah, I'm one of the developers for Stacki so I suppose I should be the maintainer.  @bbyhuy is one of our power users ;)

Sorry, one more thing @bbyhuy: It looks like you implement but did not document the "force_install" option.

2016-12-22 04:55 UTC, bbyhuy commented
@gundalow I do not mind joining @bsanders as a maintainer :-)

2016-12-22 13:53 UTC, gundalow commented
I can see the docsstrings for force_install has been updated so I'll merge this now

Maintainers added in https://github.com/ansible/ansibullbot/pull/232

Thanks!

2016-12-22 13:53 UTC, merged