Updated the gitlab_project module with usage of other python module
ansible/ansible pull request #19530
Opened 2016-12-19 19:51 UTC by dj-wasabi

##### ISSUE TYPE

- Feature Pull Request
##### COMPONENT NAME

gitlab_project
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = /git/ansible/environment/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

The python module used in the previous version seems not alive anymore. Suggestion from #2159 was to use other python module, one that is alive. This PR make use of this suggested module and added some new options. Other modules will be updated soon.

2017-01-04 13:43 UTC, gundalow requested changes
needs_revision

2017-01-04 13:43 UTC, gundalow commented on lib/ansible/modules/source_control/gitlab_project.py
> +            - Will only work if "builds_enabled" is set to True.
Will only work when C(builds_enabled=True).

2017-01-04 13:43 UTC, gundalow commented on lib/ansible/modules/source_control/gitlab_project.py
> +            - Will only work if "builds_enabled" is set to True.
Will only work when C(builds_enabled=True).

2017-01-04 13:43 UTC, gundalow commented on lib/ansible/modules/source_control/gitlab_project.py
> +        choices: ["true", "false"]
Will only work when C(builds_enabled=True).

2017-01-04 14:23 UTC, dj-wasabi commented on lib/ansible/modules/source_control/gitlab_project.py
> +            - Will only work if "builds_enabled" is set to True.
What the purpose of the C? (Just out of curiosity)

2017-01-04 14:47 UTC, gundalow commented on lib/ansible/modules/source_control/gitlab_project.py
> +            - Will only work if "builds_enabled" is set to True.
Code formatting. e.g.
http://docs.ansible.com/ansible/eos_command_module.html

> Configures the transport to use SSL if set to true only when the transport=eapi. If the transport argument is not eapi, this value is ignored.

2017-01-06 11:50 UTC, gundalow approved these changes
Looks good, thanks

2017-03-09 18:22 UTC, mainderay commented
Tried to use this and discovered that python-gitlab parameters like namespace-id and import-url are written using an underscore and thus fail. In my case it was line 272:

`                project = self._gitlab.projects.create({'name': name, 'namespace_id': group_id})
`

should be:

`                project = self._gitlab.projects.create({'name': name, 'namespace-id': group_id})
`

I believe it may be the case for any python-gitlab parameter that uses a dash for separating words.

I hope this helps and thank you for the great module!

2017-03-09 19:23 UTC, dj-wasabi commented
Hi @mainderay 

According to this page http://python-gitlab.readthedocs.io/en/stable/gl_objects/projects.html, it should be used with underscores.

2017-03-09 20:13 UTC, mainderay commented
@dj-wasabi Darn. You're right. I thought of using a dash because I was having trouble with the module and so I tried the CLI version of python-gitlab. In the help they show the parameter `namespace_id` with a dash. So their docs are out of date. I'm let them know.

To be more specific I'm using the latest version of python-gitlab (0.19) and I kept getting a namespace error. I finally dug into the gitlab_project module code and first I removed the namespace_id from the code and it worked. Then I figured out python-gitlab 0.19 wanted namespace-id instead. That also works.

My task in Ansible looks like this so you can reproduce the issue:

`    - name: 'Gitlab create and local creat, commit and push with .gitignore file.'
      gitlab_project:
        server_url: https://gitlab.com
        validate_certs: True
        login_token: 9YmtcDSuFDo11A6DWxB7
        name: '{{longname}}' 
        state: present
        issues_enabled: True
        wiki_enabled: True
        snippets_enabled: False
      delegate_to: localhost`

I hope this helps. Can you reproduce the issue on your end?

-raymond

2017-06-02 21:42 UTC, resmo commented
needs_info

2017-08-14 13:42 UTC, jxn commented
I assume that all the gitlab modules will break with the current python lib used?  AFAIK, the next gitlab release removes the old version of the gitlab API.  Anyone know?  Any prayer of getting this merged?

2017-08-15 17:09 UTC, closed without merging

2018-05-14 12:36 UTC, gpchelkin commented
Any ETA for this?

2018-05-14 20:34 UTC, jxn commented
@gpchelkin I don't think this will be done as this issue is closed and it looks like @dj-wasabi has withdrawn the PR. My guess is this will only be done if someone else decides to do the work, as Ansible / RedHat don't seem to be the ones maintaining the gitlab modules.

2018-05-15 12:44 UTC, resmo commented
I am willing to work on it but ETA Ansible ~2.7

2018-05-15 15:15 UTC, dj-wasabi commented
@jxn @gpchelkin I'll try another run with some PR's somewhere next few weeks.