Add omapi_host module
ansible/ansible pull request #19602
Opened 2016-12-21 15:17 UTC by nerzhul

This module managed DHCPd hosts using OMAPI protocol

Features:
* Add a host
* Remove a host
* Modify host IP (it's impossible to modify only mac or only hostname, this doesn't have any effect)
* Add custom DHCP attributes (at creation only)

##### ISSUE TYPE

 - Feature Pull Request
 - New Module Pull Request
 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME

##### ANSIBLE VERSION

```

```

##### SUMMARY

```

```

2016-12-29 18:38 UTC, nerzhul commented
rebased + documentation fixes

2016-12-29 19:33 UTC, nerzhul commented
i don't really understand the problem with shippable on this PR

2016-12-30 10:29 UTC, gundalow commented
The Shippable failure is from Py2.4
```
2016-12-29 18:35:10 Compile with Python 2.4
2016-12-29 18:35:10 Run command: python2.4 -m compileall -fq ./lib/ansible/modules/network/omapi_host.py
2016-12-29 18:35:10 Compiling ./lib/ansible/modules/network/omapi_host.py ...
2016-12-29 18:35:10   File "./lib/ansible/modules/network/omapi_host.py", line 154
2016-12-29 18:35:10     msg = OmapiMessage.open(b"host")
2016-12-29 18:35:10                                   ^
2016-12-29 18:35:10 SyntaxError: invalid syntax
```

2016-12-30 10:30 UTC, gundalow commented on lib/ansible/modules/network/omapi_host.py
> +        description:
All `description:` must be full sentences, e.g. capital letter and full stop.

2016-12-30 10:47 UTC, gundalow requested changes
needs_revision

Please also update `CHANGELOG.md` in the root of Ansible to add it to the list of new modules in 2.3

2016-12-30 10:47 UTC, gundalow commented on lib/ansible/modules/network/omapi_host.py
> +from ansible.module_utils.basic import *
Please only import what you need, rather than `*`

2016-12-30 10:47 UTC, gundalow commented on lib/ansible/modules/network/omapi_host.py
> +
Please document the requirements
```
requirements:
  - pypureomapi
```

2016-12-30 10:47 UTC, gundalow commented on lib/ansible/modules/network/omapi_host.py
> +            - hostname (mandatory if state=present)
I don't see this being checked in `main()`

2016-12-30 10:47 UTC, gundalow commented on lib/ansible/modules/network/omapi_host.py
> +    - Create, update and remove omapi hosts into compatible DHCPd servers
s/omapi/OMAPI/

2016-12-30 10:47 UTC, gundalow commented on lib/ansible/modules/network/omapi_host.py
> +short_description: Setup omapi hosts
s/omapi/OMAPI/

2016-12-30 11:43 UTC, nerzhul commented
Thanks for the extended review, i will improve this soon

2016-12-30 15:58 UTC, nerzhul commented on lib/ansible/modules/network/omapi_host.py
> +            - hostname (mandatory if state=present)
it's checked in setup_host function

2016-12-30 16:03 UTC, nerzhul commented
All points are now fixed

2016-12-31 19:09 UTC, gundalow approved these changes

2016-12-31 19:09 UTC, gundalow commented
Great, thanks

2016-12-31 19:09 UTC, merged

2017-01-01 09:48 UTC, nerzhul commented
great thanks :)