Add modules for SolidFire storage system.
ansible/ansible pull request #19631
Opened 2016-12-22 04:15 UTC by timuster

##### ISSUE TYPE

- New Module Pull Request
##### COMPONENT NAME

- SolidFire storage platform
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

The change adds modules that enable the management of a NetApp SolidFire storage platform. The modules were based on a design/approach similar to the existing NetApp E-Series (SANtricity) storage platform.

2016-12-22 04:15 UTC, timuster commented
Migrated from https://github.com/ansible/ansible-modules-extras/pull/3259

2016-12-22 16:53 UTC, thaumos requested changes
Hi @timuster, 

Thanks again for this submission as well!

Same as other PR.  Remove README file, as it is not needed.  Add in module utils and doc fragments for the modules.

Make changes to suggested lines (not comprehensive).

2016-12-22 16:53 UTC, thaumos commented on lib/ansible/modules/storage/netapp/sf_account_manager.py
> +    action:
Parameter of **action** is against best practices for module dev.  Please use **state** in place of this.

2016-12-22 16:53 UTC, thaumos commented on lib/ansible/modules/storage/netapp/sf_account_manager.py
> +from ansible.module_utils.basic import *
import specific functions, not *

2016-12-22 16:53 UTC, thaumos commented on lib/ansible/modules/storage/netapp/sf_account_manager.py
> +from solidfire.factory import ElementFactory
Import custom packages in try/except and handled with fail_json() in main() e.g.::

    try:
        import foo
        HAS_LIB=True
    except:
        HAS_LIB=False

2016-12-25 16:29 UTC, timuster commented
Thank you for the review, @thaumos ! I'll push the suggested changes by January 16th.

2017-01-20 03:15 UTC, closed without merging

2017-01-20 03:28 UTC, timuster commented
https://github.com/ansible/ansible/pull/19607