FIX issue 18461 : docker_container fact filtered by data parser
ansible/ansible pull request #19660
Opened 2016-12-23 10:18 UTC by bathizte

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
docker_container

##### ANSIBLE VERSION

```
ansible 2.3.0
```

##### SUMMARY

Fixes #18461 : docker_container return fact is filtered by the data parser. 
So I just changed the name of the dictionnary returned by the module. 
was: ansible_docker_container 
becomes : docker_container. 

Before
```
TASK [starting container] ******************************************************
changed: [localhost] => {"ansible_facts": {}, "changed": true}

TASK [inventory addendum] ******************************************************
ok: [localhost] => {
    "docker_cont": {
        "ansible_facts": {}, 
        "changed": true
    }
}
```
After :
```
TASK [starting container] **************************************************************
changed: [localhost] => {"ansible_facts": {"docker_container": {"AppArmorProfile": "", "Args": [" 
```
[...]

2017-01-04 23:33 UTC, abadger commented
/cc @bcoca @chouseknecht @ryansb @jimi-c to see if this is the way we want to do it, if we need to adjust the regex, or if we need to come up with a different namespace for returned facts.

2017-02-20 10:36 UTC, kasabov commented
This change is not backwards compatible according to https://docs.ansible.com/ansible/docker_container_module.html, why not fix the regex instead.

2017-02-20 11:48 UTC, bathizte commented
As [stated by @jctanner](https://github.com/ansible/ansible/issues/18461#issuecomment-259971370) in #18461 : 

> The regex is by design to prevent certain security problems described in #15925
> The fix should probably be to have the module not return facts prefixed with ansible_*

For the backward compatibility, I believe it is not for now a major issue since the [module page mentions](https://docs.ansible.com/ansible/docker_container_module.html#status) : "This module is flagged as preview which means that it is not guaranteed to have a backwards compatible interface."

2017-05-24 22:49 UTC, dorianpula requested changes

2017-05-24 22:49 UTC, dorianpula commented on lib/ansible/modules/cloud/docker/docker_container.py
> +docker_container:
Please document the reason for the change: https://github.com/ansible/ansible/issues/18461

2017-05-29 11:40 UTC, bathizte commented on lib/ansible/modules/cloud/docker/docker_container.py
> +docker_container:
Hmm, like this : https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/docker/docker_container.py#L630 ? 

apparently suggested change has already been commited : 
https://github.com/ansible/ansible/commit/20bf02f6b96356ab5fe68578a3af9462b4ca42a5#diff-ff29a0f2b632e64441519bf4d9c578d3

2017-07-24 20:29 UTC, theyough commented
+1

2018-03-19 14:48 UTC, pts-dorianpula approved these changes

2018-03-19 15:22 UTC, dorianpula approved these changes

2018-08-22 21:13 UTC, felixfontein commented
This PR can be closed, as #22324 was already merged.

2018-08-23 12:19 UTC, felixfontein commented
Duplicate of #22324.

close_me

2018-08-23 12:24 UTC, closed without merging