Add support for local repositories (file://).
ansible/ansible pull request #19726
Opened 2016-12-29 00:39 UTC by grilo

##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

maven_artifact
##### ANSIBLE VERSION

ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
##### SUMMARY

Reduced code base in approximately 30%, (removed dead code, simplified some logic), using ansible's own error checking to catch the glaring ones (such as absence of required parameters).
Added ignore_checksum option, enabling artifact download without forcing remote checksum validation.
Added aliases to repository, username and password parameters for better consistency.
Fixed (unreported) issue where http credentials weren't being propagated correctly.
Module initialization parameters are mandatory according to the documentation but not in the code.
Add support for local .m2 repositories (allowing a simple 'mvn install' to work without requiring a full fledged repository).
##### TESTING

I've been using this in production on my company for a few months now (a few thousand downloads so far, very heterogeneous parameters), no issues found.

2016-12-29 09:48 UTC, gundalow requested changes
needs_revision

2016-12-29 09:48 UTC, gundalow commented on lib/ansible/modules/packaging/language/maven_artifact.py
> +            - The maven artifactId coordinate.
Descriptions should be full sentences,  eg with capital letter and full stop.

2016-12-29 09:48 UTC, gundalow commented on lib/ansible/modules/packaging/language/maven_artifact.py
> +        version_added: 2.3
version_added should be a string, as specified in the module checklist

2016-12-29 09:48 UTC, gundalow commented on lib/ansible/modules/packaging/language/maven_artifact.py
> +        version_added: 2.3
String

2016-12-29 09:48 UTC, gundalow commented on lib/ansible/modules/packaging/language/maven_artifact.py
> +- maven_artifact: group_id=junit artifact_id=junit dest=/tmp/junit-latest.jar
Examples should be in multi-line with `key: value`

2016-12-29 10:13 UTC, grilo commented
ready_for_review

2016-12-29 11:12 UTC, grilo commented on lib/ansible/modules/packaging/language/maven_artifact.py
> +            - The maven artifactId coordinate.
The diff looks good, but this isn't picking up the changes properly. Is this something I can fix?

2016-12-31 19:10 UTC, gundalow commented on lib/ansible/modules/packaging/language/maven_artifact.py
> +    group_id=junit
`key: value` (with a space between), e.g.

`group_id: junit`

2016-12-31 19:11 UTC, gundalow requested changes
needs_revision just the examples that need work

2016-12-31 19:31 UTC, grilo commented
ready_for_review

@gundalow Thank you for your assistance.

2017-01-01 09:36 UTC, gundalow approved these changes

2017-01-25 20:01 UTC, gundalow commented
Hi,

Looks like this branch needs updating to fix some issues, please see this guide on how to do that cleanly.

http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

2017-01-30 22:29 UTC, grilo commented
ready_for_review

2017-02-21 22:58 UTC, grilo commented
ready_for_review

2017-02-23 01:51 UTC, dharmabumstead approved these changes

2017-03-02 13:43 UTC, paulstapleton commented
Hi,
I've really wanted to be able to download from `file://` locations for some time, and have tried out your changes by copying the code locally and overwriting the existing module. I encountered a few issues which I would like to report.
I am running ansible 2.2.1.0 on CentOS 7.3.1611

Running the maven_artifact module gave me an error immediately:

```python
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_tStxC7/ansible_module_maven_artifact.py", line 374, in <module>
    main()
  File "/tmp/ansible_tStxC7/ansible_module_maven_artifact.py", line 310, in main
    parsed_url = urlparse(url_repository)
NameError: global name 'url_repository' is not defined
```

This occurs due to a problem in the main method:

```python
    try:
        parsed_url = urlparse(url_repository)
    except AttributeError as e:
        module.fail_json(msg='url parsing went wrong %s' % e)
```

where the variable `url_repository` has not been defined yet. Changing this to the following fixed the problem.
```python
        parsed_url = urlparse(module.params["url_repository"])
```

After fixing this I had issues with the checksum logic when downloading from the file system with a `file://` URL.

In the `main()` method is the following logic:

```python
# Does the local file already exist and match the remote md5?
    if client.checksum(artifact, dest):
        module.exit_json(dest=dest, state=state, version=artifact.version, changed=False)

    try:
        client.download(artifact, dest)
    except Exception as e:
        module.fail_json(msg=e.args[0])

    if ignore_checksum and not client.checksum(artifact, dest):
        module.fail_json(msg="I was able to download the artifact (%s), but the checksum doesn't match (%s)." % (artifact.url, dest))

```

Here we check the checksum once before and then again after downloading the artifact. However due to the implementation of the `FileSystemMavenClient` checksum function this always results in a failure:

```python
class FileSystemMavenClient:
...
    def checksum(self, artifact, dest):
        self.module.fail_json(msg=artifact.url)
        return True # There is nothing to check if the artifact is local
```
So downloading from the `file://` location always fails. I fixed this locally by doing a similar checksum calculation as for the `HttpMavenClient`.
```python
class FileSystemMavenClient:
...
    def download(self, artifact, destination):
        try:
            src = create_artifact_location(artifact)
            return shutil.copy2(src, destination)
        except (IOError, os.error) as why:
            self.module.fail_json(msg='Copy failed. %s' % (':'.join([artifact.group_id, artifact.artifact_id, artifact.classifier, artifact.extension, artifact.url, destination, str(why)])))

    def create_artifact_location(artifact):
      return posixpath.join(self.repo, artifact.url).replace('file:/', '').replace('//', '/')

    def checksum(self, artifact, dest):
        if not os.path.isfile(dest):
            return False
        with open(create_artifact_location(artifact), 'rb') as file:
            remote_md5 = hashlib.md5(file.read()).hexdigest()
        with open(dest, 'rb') as file:
            local_md5 = hashlib.md5(file.read()).hexdigest()
        return remote_md5 == local_md5
```

I hope you find my comments helpful.

2017-03-02 23:02 UTC, grilo commented
@paulstapleton Thank you for your input, those were definitely glaring mistakes. The fixes and your checksum proposal have been incorporated.

2017-03-03 06:36 UTC, paulstapleton commented on lib/ansible/modules/packaging/language/maven_artifact.py
> +        with open(create_artifact_location(artifact), 'rb') as file:
Hi,
The method `create_artifact_location` doesn't actually yet. Sorry that I wasn't explicit in my comment (https://github.com/ansible/ansible/pull/19726#issuecomment-283656479).
I extracted the file path generation code from the `download` method into a new function:

```python
def create_artifact_location(artifact):
      return posixpath.join(self.repo, artifact.url).replace('file:/', '').replace('//', '/')
```

2017-03-03 06:37 UTC, paulstapleton commented on lib/ansible/modules/packaging/language/maven_artifact.py
> +        with open(create_artifact_location(artifact), 'rb') as file:
Hi,
The method `create_artifact_location` doesn't actually yet. Sorry that I wasn't explicit in my comment (https://github.com/ansible/ansible/pull/19726#issuecomment-283656479).
I extracted the file path generation code from the `download` method into a new function:

```python
def create_artifact_location(artifact):
      return posixpath.join(self.repo, artifact.url).replace('file:/', '').replace('//', '/')
```

2017-03-03 21:05 UTC, grilo commented
@paulstapleton Fixed, thank you for having my back covered. Feel free to report any further issues.

2017-04-20 00:45 UTC, grilo commented
@chrisisbeef @gundalow I've been using this version for quite some time in my company and we're doing several hundred deployments per day. Let me know if there are any pending issues.

2017-04-21 17:32 UTC, gundalow requested changes

2017-04-21 17:32 UTC, gundalow commented on lib/ansible/modules/packaging/language/maven_artifact.py
> +        version_added: "2.3"
`"2.4"`

2017-04-21 17:32 UTC, gundalow commented on lib/ansible/modules/packaging/language/maven_artifact.py
> +import urlparse # Override urlparse from module_utils
Please import what you need rather than `*` 

https://docs.ansible.com/ansible/dev_guide/developing_modules_documenting.html#python-imports

2017-04-21 17:32 UTC, gundalow commented on lib/ansible/modules/packaging/language/maven_artifact.py
> +            url_repository = dict(default='http://repo1.maven.org/maven2', aliases=['repository_url', 'repository']),
Should the default be https, if so update docs

2017-04-21 17:32 UTC, gundalow commented on lib/ansible/modules/packaging/language/maven_artifact.py
> +        aliases: [ username, user, uname, aws_secret_key ]
Are these common aliases with maven?
Generally with modules we just use `user:` and `password`

2017-04-21 17:32 UTC, gundalow commented on lib/ansible/modules/packaging/language/maven_artifact.py
> +        aliases: [ password, pwd, passwd, aws_secret_access_key ]
Are these common aliases with maven?
Generally with modules we just use `user:` and `password`

2017-04-21 17:33 UTC, gundalow commented
Closing and re-opening the PR to rerun CI

2017-04-21 23:49 UTC, grilo commented
ready_for_review

@gundalow Changes incorporated. Thank you for your feedback.

2017-04-24 17:40 UTC, gundalow approved these changes

2017-08-22 01:11 UTC, grilo commented
@tumbl3w33d I believe the behaviour introduced with #28295 is already by default in this one. The same would apply to #27103 and #24518.

2017-08-22 18:30 UTC, tumbl3w33d commented
First and foremost, I want to thank you for the effort you put into this PR. I see a lot of improvement for the module here, not only functionality-wise but you also did some nice refactorings and cleanups. 👍 

Now here comes the downside. This PR is quite a chunk to chew on. You wanted to extend the module by some certain functionality but did an entire overhaul of the module. While I'd also do that with my private/work code to which I have direct access, I find it quite difficult in this scope here in which it's quite hard to get follow-up bugfixes in quickly.
This module has 0 test coverage so far and you changed major parts of its logic. The change is also too big for my simple mind to evaluate just from looking at it. So the only option left for me would be intensive manual testing which means reproducing all of the different possible use cases.

Let's assume I'd find time and power to do so - how likely is it that:
* I will not forget some of the use cases
* some other (core) reviewer will spend the same effort

To sum it up - I'm really struggling with this one. On the one hand I really like most of your improvements (some are just a matter of taste). I would have preferred to get this proposed as several PRs, each one concise and focused on a certain topic. Like this I don't feel like taking exclusive responsibility for it. Maybe a core dev or @chrisisbeef could state their opinion on this.

2017-08-22 19:12 UTC, grilo commented
It'll take me a few days, but I'm happy to do both (multiple PRs and automated tests).

Is it OK if the first one is just a big chunk of tests (no new functionality)?

2017-08-22 19:17 UTC, tumbl3w33d commented
Nice you don't give up :)
Tests would be highly appreciated, of course! I've been thinking about adding some as well, I just didn't find the time yet to find my way into how unit/integration tests are done here (e.g., if it would be possible to spin up a dummy registry container).

In the long run I'd also like to get this module PEP8 compliant. It's listed as exception at the moment, but for future developments we should strive for it, I think.

Looking forward to your next PRs then! 👍

2017-11-22 22:15 UTC, dharmabumstead commented
Closing due to inactivity. Please feel free to reopen and rebase if it's still applicable. Thanks.

2017-11-22 22:15 UTC, closed without merging