New AWS module rds_option_group.py
ansible/ansible pull request #19786
Opened 2017-01-02 23:42 UTC by naslanidis

##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

rds_option_group
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel e396d5d508) last updated 2016/08/24 12:13:10 (GMT +1000)
  lib/ansible/modules/core: (detached HEAD 368ca738fa) last updated 2016/08/24 12:13:21 (GMT +1000)
  lib/ansible/modules/extras: (detached HEAD 0749ce6faa) last updated 2016/08/24 12:13:30 (GMT +1000)
```
##### SUMMARY

This module manages the creation, modification, deletion of RDS Option groups and the associated options applied to those groups. 

Note: Some of the options list output has been removed for the sake of brevity. 

```
TASK [print new option group] **************************************************
ok: [localhost] => {
    "msg": {
        "changed": true, 
        "option_group": {
            "OptionGroupsList": [
                {
                    "AllowsVpcAndNonVpcInstanceMemberships": false, 
                    "EngineName": "mysql", 
                    "MajorEngineVersion": "5.6", 
                    "OptionGroupDescription": "test mysql option group", 
                    "OptionGroupName": "test-mysql-option-group", 
                    "Options": [
                        {
                            "DBSecurityGroupMemberships": [], 
                            "OptionDescription": "Innodb Memcached for MySQL", 
                            "OptionName": "MEMCACHED", 
                            "OptionSettings": [
                                {
                                    "AllowedValues": "1-2", 
                                    "ApplyType": "STATIC", 
                                    "DataType": "FLOAT", 
                                    "DefaultValue": "1.25", 
                                    "Description": "Chunk size growth factor that controls the size of each successive chunk with each chunk growing times this amount larger than the previous chunk.", 
                                    "IsCollection": false, 
                                    "IsModifiable": true, 
                                    "Name": "CHUNK_SIZE_GROWTH_FACTOR", 
                                    "Value": "1.35"
                                }, 
                                {
                                    "AllowedValues": "10-1024", 
                                    "ApplyType": "STATIC", 
                                    "DataType": "INTEGER", 
                                    "DefaultValue": "1024", 
                                    "Description": "Maximum number of concurrent connections. Setting this value to anything less than 10 prevents MySQL from starting.", 
                                    "IsCollection": false, 
                                    "IsModifiable": true, 
                                    "Name": "MAX_SIMULTANEOUS_CONNECTIONS", 
                                    "Value": "20"
                                }
                            ], 
                            "Permanent": false, 
                            "Persistent": false, 
                            "Port": 11211, 
                            "VpcSecurityGroupMemberships": [
                                {
                                    "Status": "active", 
                                    "VpcSecurityGroupId": "sg-d188c123"
                                }
                            ]
                        }
                    ], 
                    "VpcId": "vpc-aad24123"
                }
            ], 
            "ResponseMetadata": {
                "HTTPStatusCode": 200, 
                "RequestId": "cb9bf613-7027-11e6-8515-d3586c4629c2"
            }
        }
    }
}
```

2017-01-02 23:42 UTC, naslanidis commented
Migrated from https://github.com/ansible/ansible-modules-extras/pull/2826

2017-01-09 00:24 UTC, willthames commented
Once tests pass this is good to go.

2017-01-15 07:28 UTC, willthames commented on lib/ansible/modules/cloud/amazon/rds_option_group.py
> +    main()
There should be a newline at the end of the file

2017-01-15 07:29 UTC, willthames commented on lib/ansible/modules/cloud/amazon/rds_option_group.py
> +    state = module.params.get('state').lower()
no need for `lower()` here

2017-01-15 07:31 UTC, willthames commented on lib/ansible/modules/cloud/amazon/rds_option_group.py
> +                changed, new_option_group_options =  create_option_group_options(client, module)
Shouldn't this take `to_be_added` ?

2017-01-15 07:36 UTC, willthames commented on lib/ansible/modules/cloud/amazon/rds_option_group.py
> +        if cmp(sorted(old_settings),sorted(new_settings)) != 0:
This whole section would be much simpler if you started with `set`s and continued with them

```
new_settings = set([item['OptionName'] for item in new_options])
old_settings = set([item['OptionName'] for item in current_option['OptionName'])
if new_settings != old_settings:
    to_be_added = list(new_settings - old_settings)
    to_be_removed = list(old_settings - new_settings)
```

2017-01-15 07:38 UTC, willthames commented
Other than the final newline, all my review comments are more suggestions than requirements.

2017-01-24 10:19 UTC, naslanidis commented
@willthames 

Your suggestions were good and I've added all but one. I just retested and the to_be_added doesn't get passed to the create_option_group_function as if there are any new ones at all it just gets them from the original params. The to_be_removed gets passed to the remove function as we only want to remove specific options.

2017-02-01 00:13 UTC, willthames commented on lib/ansible/modules/cloud/amazon/rds_option_group.py
> +                changed, new_option_group_options =  create_option_group_options(client, module)
You inadvertently added a third blank line. Probably worth running flake8 and removing what issues you can

2017-02-01 00:13 UTC, willthames commented on lib/ansible/modules/cloud/amazon/rds_option_group.py
> +
You inadvertently added a third blank line. Probably worth running flake8 and removing what issues you can

2017-02-01 00:14 UTC, willthames commented on lib/ansible/modules/cloud/amazon/rds_option_group.py
> +
If that's too much of a headache, even just removing the accidental line would be good.

2017-02-14 10:29 UTC, willthames commented
shipit

Extra blank line is not a big deal in the grand scheme of things

2017-04-05 17:07 UTC, s-hertel requested changes
After these things get addressed this gets a shipit from me too. Looks good!

2017-04-05 17:07 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/rds_option_group.py
> +version_added: "2.3"
Should be 2.4 now.

2017-04-05 17:07 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/rds_option_group.py
> +from ansible.module_utils.basic import *
Import just the specific things used and move these to the top, please!

2017-04-05 17:07 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/rds_option_group.py
> +    (changed, results) = invocations[state](client, module)
Parentheses aren't needed here.

2017-04-05 17:07 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/rds_option_group.py
> +                                if cmp(setting_name[name], option[name]) != 0:
No cmp with python3.

2017-04-05 17:07 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/rds_option_group.py
> +                                        if cmp(new_option_setting['Value'], current_option_setting['Value']) != 0:
Here too.

2017-06-02 03:28 UTC, willthames commented
In the absence of further updates from @naslanidis I've implemented the fixes for this PR in #25290.

2017-08-01 18:27 UTC, jctanner commented
duplicate_of https://github.com/ansible/ansible/pull/25290

2017-08-01 18:27 UTC, closed without merging