ec2_group: description property is immutable
ansible/ansible pull request #19790
Opened 2017-01-03 02:02 UTC by alexlo03

Fixes https://github.com/ansible/ansible/issues/19789

The three commits in this PR fix three issues (two are test suite updates)

2017-01-03 02:17 UTC, alexlo03 commented
For anyone interested I wrote up ["the making of" story](https://alexlo03.wordpress.com/2017/01/02/steps-for-making-a-change-to-the-ansible-aws-security-group-module/)

2017-02-14 11:22 UTC, willthames commented on lib/ansible/modules/cloud/amazon/ec2_group.py
> +            '''existing group'''
Should this be a comment rather than a docstring?

2017-02-14 11:22 UTC, willthames commented
shipit

2017-02-14 16:00 UTC, alexlo03 commented on lib/ansible/modules/cloud/amazon/ec2_group.py
> +            '''existing group'''
I'll try to change tonight.  comment/docstring standards seem a bit haphazard.

2017-02-20 05:10 UTC, willthames commented
bot_status

2017-02-20 05:22 UTC, willthames commented
shipit

2017-03-07 21:11 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/ec2_group.py
> +    except Exception as e:
Instead of Exception you could use boto.exception.EC2ResponseError

2017-03-08 17:38 UTC, alexlo03 commented on lib/ansible/modules/cloud/amazon/ec2_group.py
> +    except Exception as e:
@s-hertel I'm happy to catch a more specific exception.  Question: I have gotten timeouts on this call before, I'm not sure that boto will wrap those in EC2ResponseError.  The documentation is kind of sparse and looking around I see others handling both EC2ResponseError and other exceptions.  LMK what you think? Thanks!

2017-03-08 20:02 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/ec2_group.py
> +    except Exception as e:
Hm, good point. Maybe making exceptions more specific will be a pr for the future since it's used elsewhere in the module anyway.

2017-03-08 20:03 UTC, s-hertel approved these changes

2017-03-08 20:03 UTC, s-hertel commented
shipit

2017-03-08 23:58 UTC, willthames commented on lib/ansible/modules/cloud/amazon/ec2_group.py
> +    except Exception as e:
We do have guidelines on boto3 exception handling
https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/GUIDELINES.md#boto3-2

`botocore.exceptions.ClientError` covers most needs, and is a little better than just catching `Exception`

2017-03-09 12:46 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/ec2_group.py
> +    except Exception as e:
+1

2017-03-09 12:56 UTC, s-hertel requested changes
Great, so it looks like a ClientError will catch timeout as well. Could you fix the other Exception in this module as well and import traceback to use with the fail json for debugging? Something like module.fail_json(msg="Failure getting security groups.", exception=traceback.format_exc())

2017-03-09 13:00 UTC, willthames commented
@s-hertel my standard exception handling these days is

```
except botocore.exceptions.ClientError as e:
    module.fail_json(msg="nice friendly message here", exception=traceback.format_exc(),
                     **camel_dict_to_snake_dict(e.response))
```
I think that covers both @wimnat and @ryansb's preferences

2017-03-09 15:16 UTC, s-hertel commented
@willthames Good to know! I'll make sure I'm implementing it like that in the future too.

2017-03-09 16:05 UTC, alexlo03 commented on lib/ansible/modules/cloud/amazon/ec2_group.py
> +    except Exception as e:
@willthames @s-hertel is this a request to upgrade boto to boto3 for ec2_group?  happy to take a crack at that (trying now), but a bit larger than the original scope of this PR

2017-03-10 00:09 UTC, willthames commented on lib/ansible/modules/cloud/amazon/ec2_group.py
> +    except Exception as e:
@alexlo03 only inadvertently, I somehow switched from thinking about boto to boto3 exceptions. The same guidelines have boto exception handling - not sure if `boto.exceptions.BotoServerError` will suffice for timeouts or not.

http://boto.cloudhackers.com/en/latest/ref/boto.html#module-boto.exception

Given that we use BotoClientError with boto3, chances are same will work with boto

2017-03-13 19:51 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/ec2_group.py
> +    except Exception as e:
Sorry about that, alexlo03. Had my head in the uh clouds. :/ Not a request for boto3! I'd prefer to see the bugfixes make it into 2.3 and fix make the exceptions better in another PR if willthames's suggestion above doesn't catch timeouts.

2017-03-20 17:00 UTC, alexlo03 commented
@willthames @s-hertel 
I brought exception handling up to spec per https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/GUIDELINES.md#boto-2

I did not include the traceback / dict response (ex below) as it wasn't in that guidelines doc.
```except botocore.exceptions.ClientError as e:
    module.fail_json(msg="nice friendly message here", exception=traceback.format_exc(),
                     **camel_dict_to_snake_dict(e.response))```

Please LMK if you'd like me to update further.  Thanks

2017-03-23 18:18 UTC, s-hertel commented
@alexlo03 I have updated the [amazon guidelines](1ca4a42 ) to reflect expectations!

2017-03-23 22:30 UTC, willthames commented
shipit

2017-03-24 20:11 UTC, s-hertel approved these changes

2017-03-25 12:17 UTC, alexlo03 commented
@s-hertel sorry for the delay was going to get that this weekend - thanks for the changes and the review!

2017-03-26 13:33 UTC, merged

2017-03-27 20:38 UTC, alexlo03 commented
@s-hertel @willthames Thanks again for all your help - this makes our production security group ansible job 2.7x faster 
https://alexlo03.wordpress.com/2017/03/27/making-ansible-network-security-2-3x-faster/

2017-04-13 14:19 UTC, s-hertel commented
Thoughts from mikedlr (here @michael-dev2rights) on irc:
```
<mikedlr> Michael afternoon.  so interesting change;  I was relying on ec2_group to verify but not create a security group.  Recent changes mean that 
09:14 it went from passing green to failing in the case where the group description doesn't match..
09:18 the change is from https://github.com/ansible/ansible/pull/19790 
09:19 I guess the final behaviour is sort of correct.  the module can't update the ec2_group without deleting it and recreating so it might be 
09:19 best to just warn, but the overall effect is nasty.  
09:19 a) is there a better way to do this 
09:19 b) should there be some kind of deprecation process? 
09:20 c) what's wrong with at least trying to delete and recreate the security group? 
```

```
<mikedlr> Michael reproducer:  create security group "abc" with description "def"   ; now tell ansible to create "abc" with description "ghi"    try on 2.2. - no complaint;  try on 2.3 fails. 
```

Should we add a warning for this?