cloud: ovirt: add kernel boot parameters to vms module
ansible/ansible pull request #19832
Opened 2017-01-03 21:08 UTC by machacekondra

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

ovirt_vms

##### ANSIBLE VERSION

```
ansible 2.3.0
```

##### SUMMARY

This patch adds three new parameters to `ovirt_vms` modules, and it's following:

 - kernel_path
 - initrd_path
 - kernel_params

2017-01-04 06:56 UTC, machacekondra commented
@mwperina @ryansb

2017-01-04 06:57 UTC, machacekondra commented
shipit

2017-01-04 09:29 UTC, mwperina requested changes

2017-01-04 09:29 UTC, mwperina commented on lib/ansible/modules/cloud/ovirt/ovirt_vms.py
> +            - "Path to kernel image to boot the virtual machine."
I'd rephrase to: "Path to a kernel image used to boot the virtual machine"

2017-01-04 09:29 UTC, mwperina commented on lib/ansible/modules/cloud/ovirt/ovirt_vms.py
> +            - "Kernel command line parameter strings to be used with the defined kernel on boot."
I'd rephrase: "Kernel command line parameters (formatted as string) to be used with the kernel specified by `kernel_path` option."

2017-01-04 09:29 UTC, mwperina commented on lib/ansible/modules/cloud/ovirt/ovirt_vms.py
> +            - "Path to a ramdisk to be used with the kernel."
I'd rephrase: "Path to an initial ramdisk to be used with the kernel specified by `kernel_path` option".

2017-01-04 21:08 UTC, machacekondra commented on lib/ansible/modules/cloud/ovirt/ovirt_vms.py
> +            - "Path to kernel image to boot the virtual machine."
done

2017-01-04 21:08 UTC, machacekondra commented on lib/ansible/modules/cloud/ovirt/ovirt_vms.py
> +            - "Path to a ramdisk to be used with the kernel."
done

2017-01-04 21:08 UTC, machacekondra commented on lib/ansible/modules/cloud/ovirt/ovirt_vms.py
> +            - "Kernel command line parameter strings to be used with the defined kernel on boot."
done

2017-01-05 01:11 UTC, merged

2017-01-05 01:11 UTC, abadger commented
Merged to devel.  thanks @machacekondra and @mwperina !