Panos check module to test FW readiness to accept new configuration(s)
ansible/ansible pull request #19882
Opened 2017-01-04 18:45 UTC by ivanbojer

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
panos_check

##### ANSIBLE VERSION

```
ansible 2.1.0.0 
config file = 
configured module search path = Default w/o overrides
```

##### SUMMARY
Whenever FW starts/reboots it goes through a set of checks/commits. Before these are done there is no way to manipulate FW configurations. This module will repeatedly query FW in order to determine if FW is in the ready state.

2017-01-06 21:32 UTC, privateip requested changes
consider adding unit test cases

2017-01-06 21:32 UTC, privateip commented on lib/ansible/modules/network/panos/panos_check.py
> +RETURN = '''
return value does not match RETURN doc string

2017-01-06 21:32 UTC, privateip commented on lib/ansible/modules/network/panos/panos_check.py
> +    if not ip_address:
not needed

2017-01-06 21:32 UTC, privateip commented on lib/ansible/modules/network/panos/panos_check.py
> +    if not password:
not needed

2017-01-10 21:47 UTC, ivanbojer commented on lib/ansible/modules/network/panos/panos_check.py
> +RETURN = '''
There is no returned value so I copied return from wakeonlan.py sample

2017-01-10 21:47 UTC, ivanbojer commented on lib/ansible/modules/network/panos/panos_check.py
> +    if not ip_address:
ok

2017-01-10 21:47 UTC, ivanbojer commented on lib/ansible/modules/network/panos/panos_check.py
> +    if not password:
ok

2017-01-10 21:47 UTC, ivanbojer commented
Thank you for the review. I've incorporated all the changes as requested.

2017-01-10 21:47 UTC, ivanbojer commented
ready_for_review

2017-01-13 03:26 UTC, merged