new module to manipulate DAG table
ansible/ansible pull request #19885
Opened 2017-01-04 18:53 UTC by ivanbojer

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
panos_dag

##### ANSIBLE VERSION

```
ansible 2.1.0.0 
config file = 
configured module search path = Default w/o overrides
```

##### SUMMARY
New panos module that allows for Dynamic Address Group generation. DAG's are dynamic run-time objects that are used in FW policies. The typical example would be a white-list of IP's that is updated every 5 minutes.

2017-01-06 21:31 UTC, privateip requested changes
consider adding unit tests

2017-01-06 21:31 UTC, privateip commented on lib/ansible/modules/network/panos/panos_dag.py
> +try:
shared module?

2017-01-06 21:31 UTC, privateip commented on lib/ansible/modules/network/panos/panos_dag.py
> +RETURN = '''
return value does not match RETURN doc string

2017-01-06 21:31 UTC, privateip commented on lib/ansible/modules/network/panos/panos_dag.py
> +    if not ip_address:
not needed

2017-01-06 21:31 UTC, privateip commented on lib/ansible/modules/network/panos/panos_dag.py
> +    if not password:
not needed

2017-01-06 21:31 UTC, privateip commented on lib/ansible/modules/network/panos/panos_dag.py
> +    if not dag_filter:
not needed

2017-01-06 21:31 UTC, privateip commented on lib/ansible/modules/network/panos/panos_dag.py
> +    if not dag_name:
not needed

2017-01-10 21:50 UTC, ivanbojer commented on lib/ansible/modules/network/panos/panos_dag.py
> +RETURN = '''
no return so I copied default return string from wakeonlan.py

2017-01-10 21:50 UTC, ivanbojer commented on lib/ansible/modules/network/panos/panos_dag.py
> +try:
no

2017-01-10 21:50 UTC, ivanbojer commented on lib/ansible/modules/network/panos/panos_dag.py
> +    if not ip_address:
ok

2017-01-10 21:50 UTC, ivanbojer commented on lib/ansible/modules/network/panos/panos_dag.py
> +    if not password:
ok

2017-01-10 21:50 UTC, ivanbojer commented on lib/ansible/modules/network/panos/panos_dag.py
> +    if not dag_name:
ok

2017-01-10 21:50 UTC, ivanbojer commented on lib/ansible/modules/network/panos/panos_dag.py
> +    if not dag_filter:
ok

2017-01-10 21:51 UTC, ivanbojer commented
Thank you for the review. I've incorporated all the changes requested.

2017-01-10 21:51 UTC, ivanbojer commented
ready_for_review

2017-01-13 03:27 UTC, merged