module for certificate generation
ansible/ansible pull request #19881
Opened 2017-01-04 18:02 UTC by ivanbojer

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
panos_cert_gen_ssh

##### ANSIBLE VERSION

```
ansible 2.1.0.0 
config file = 
configured module search path = Default w/o overrides
```

##### SUMMARY
New panos module that allows for admin user to generate self-signed certificate on the device. This is mainly used for private VPN connections and global protect integrations.

2017-01-06 21:34 UTC, privateip requested changes
consider adding unit test cases

2017-01-06 21:34 UTC, privateip commented on lib/ansible/modules/network/panos/panos_cert_gen_ssh.py
> +status:
return value does not match RETURN doc string

2017-01-06 21:34 UTC, privateip commented on lib/ansible/modules/network/panos/panos_cert_gen_ssh.py
> +    if not ip_address:
not needed

2017-01-06 21:34 UTC, privateip commented on lib/ansible/modules/network/panos/panos_cert_gen_ssh.py
> +    if not key_filename:
use `required_one_if` kwarg in AnsbileModule instance

2017-01-06 21:34 UTC, privateip commented on lib/ansible/modules/network/panos/panos_cert_gen_ssh.py
> +    if not cert_cn:
not needed

2017-01-06 21:34 UTC, privateip commented on lib/ansible/modules/network/panos/panos_cert_gen_ssh.py
> +    if not cert_friendly_name:
not needed

2017-01-06 21:34 UTC, privateip commented on lib/ansible/modules/network/panos/panos_cert_gen_ssh.py
> +    if not signed_by:
not needed

2017-01-07 00:07 UTC, ivanbojer commented on lib/ansible/modules/network/panos/panos_cert_gen_ssh.py
> +status:
no return VARS, copied empty clause from wakeonlan.py

2017-01-07 00:07 UTC, ivanbojer commented on lib/ansible/modules/network/panos/panos_cert_gen_ssh.py
> +    if not ip_address:
ok

2017-01-07 00:07 UTC, ivanbojer commented on lib/ansible/modules/network/panos/panos_cert_gen_ssh.py
> +    if not key_filename:
ok, I was not aware of it.

2017-01-07 00:08 UTC, ivanbojer commented on lib/ansible/modules/network/panos/panos_cert_gen_ssh.py
> +    if not cert_cn:
ok

2017-01-07 00:08 UTC, ivanbojer commented on lib/ansible/modules/network/panos/panos_cert_gen_ssh.py
> +    if not cert_friendly_name:
ok

2017-01-07 00:08 UTC, ivanbojer commented on lib/ansible/modules/network/panos/panos_cert_gen_ssh.py
> +    if not signed_by:
ok

2017-01-07 00:08 UTC, ivanbojer commented
Thank you for the review. I've changed code based on the comments. Also, I added an additional exception handling that was missing.

2017-01-10 21:36 UTC, ivanbojer commented
ready_for_review

2017-01-19 22:46 UTC, ivanbojer commented
Can someone provide a hint on why are checks failing here?

2017-01-24 18:19 UTC, ivanbojer commented
ready_for_review

2017-01-25 14:26 UTC, gundalow requested changes
needs_revision

Please also update `CHANGELOG.md` in the root of the repo to include this in the list of new modules in 2.3

2017-01-25 14:26 UTC, gundalow commented on lib/ansible/modules/network/panos/panos_cert_gen_ssh.py
> +short_description: generates a self-signed certificate - NOT A CA -- using SSH with SSH key
Could this be rewritten as
`generates a self-signed certificate for using SSH with SSH key`

2017-01-25 14:26 UTC, gundalow commented on lib/ansible/modules/network/panos/panos_cert_gen_ssh.py
> +    - generates a self-signed certificate that can be used by GlobalProtect client. root-ca must be preset on the system first. This module depends on paramiko for ssh.
All `description:` must be full sentences, start with a capital letter and end with a full stop.

2017-01-25 14:35 UTC, gundalow commented on lib/ansible/modules/network/panos/panos_cert_gen_ssh.py
> +    ip_address:
Should this option be called `host`, rather than ip_address?

You would want to make the came change in the other panosmodule

2017-01-25 14:36 UTC, gundalow requested changes
needs_revision

2017-01-25 21:25 UTC, ivanbojer commented on lib/ansible/modules/network/panos/panos_cert_gen_ssh.py
> +short_description: generates a self-signed certificate - NOT A CA -- using SSH with SSH key
Certificates are not only for panos device but they have other usages (for example, GPClient IPsec tunnels)

2017-01-25 21:30 UTC, ivanbojer commented on lib/ansible/modules/network/panos/panos_cert_gen_ssh.py
> +    - generates a self-signed certificate that can be used by GlobalProtect client. root-ca must be preset on the system first. This module depends on paramiko for ssh.
OK

2017-01-25 21:30 UTC, ivanbojer commented on lib/ansible/modules/network/panos/panos_cert_gen_ssh.py
> +    ip_address:
We have already integrations with legacy modules that use ip_address as a parameter. We need to keep it the same in order not to break the integrations.

2017-01-25 22:21 UTC, gundalow commented on lib/ansible/modules/network/panos/panos_cert_gen_ssh.py
> +    ip_address:
Sure, that makes sense.

2017-01-27 22:21 UTC, ivanbojer commented on lib/ansible/modules/network/panos/panos_cert_gen_ssh.py
> +    ip_address:
I've updated CHANGELOG.md as requested.

2017-01-27 22:21 UTC, ivanbojer commented
ready_for_review

2017-01-31 22:29 UTC, ivanbojer commented
I have to abandon this pull in lieu to https://github.com/ansible/ansible/pull/20889 because of git rebase issues. The new request is identical to this one.

2017-01-31 22:29 UTC, closed without merging