Panos mgtconfig
ansible/ansible pull request #19897
Opened 2017-01-04 22:39 UTC by ivanbojer

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
panos_mgtconfig

##### ANSIBLE VERSION

```
ansible 2.1.0.0 
config file = 
configured module search path = Default w/o overrides
```

##### SUMMARY
New panos module that allows for rudimentary management interface configuration.

2017-01-05 04:50 UTC, privateip requested changes

2017-01-05 04:50 UTC, privateip commented on lib/ansible/modules/network/panos/panos_mgtconfig.py
> +RETURN = '''
doc string doesn't match actual return value

2017-01-05 04:50 UTC, privateip commented on lib/ansible/modules/network/panos/panos_mgtconfig.py
> +    if not ip_address:
not needed

2017-01-05 04:50 UTC, privateip commented on lib/ansible/modules/network/panos/panos_mgtconfig.py
> +    if not password:
not needed

2017-01-05 04:50 UTC, privateip commented on lib/ansible/modules/network/panos/panos_mgtconfig.py
> +        import sys
use `get_exception()` instead

2017-01-05 04:50 UTC, privateip commented on lib/ansible/modules/network/panos/panos_mgtconfig.py
> +    xapi = pan.xapi.PanXapi(
shared function?

2017-01-06 23:27 UTC, ivanbojer commented on lib/ansible/modules/network/panos/panos_mgtconfig.py
> +RETURN = '''
mimicked wakeonlan.py given there is no return var

2017-01-06 23:27 UTC, ivanbojer commented on lib/ansible/modules/network/panos/panos_mgtconfig.py
> +    if not ip_address:
ok

2017-01-06 23:27 UTC, ivanbojer commented on lib/ansible/modules/network/panos/panos_mgtconfig.py
> +    if not password:
ok

2017-01-06 23:27 UTC, ivanbojer commented on lib/ansible/modules/network/panos/panos_mgtconfig.py
> +    xapi = pan.xapi.PanXapi(
nope, just a class instantiation

2017-01-06 23:27 UTC, ivanbojer commented on lib/ansible/modules/network/panos/panos_mgtconfig.py
> +        import sys
ok

2017-01-06 23:27 UTC, ivanbojer commented
ready_for_review

2017-01-10 04:50 UTC, merged