new module for profile groups
ansible/ansible pull request #19904
Opened 2017-01-04 23:18 UTC by ivanbojer

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
panos_pg

##### ANSIBLE VERSION

```
ansible 2.1.0.0 
config file = 
configured module search path = Default w/o overrides
```

##### SUMMARY
New panos module that allows for creation of security profile groups.

2017-01-05 04:14 UTC, privateip requested changes
Consider pulling common functions across all panos_* modules into a shared lib in ansible/module_utils.  Then you can import in each module using standard Python imports.

2017-01-05 04:14 UTC, privateip commented on lib/ansible/modules/network/panos/panos_pg.py
> +    if not ip_address:
not needed.  setting `required=True` in the argument_spec will automatically generate an failed message if the argument is not specified.

2017-01-05 04:14 UTC, privateip commented on lib/ansible/modules/network/panos/panos_pg.py
> +    if not password:
same as with`ip_address`

2017-01-05 04:14 UTC, privateip commented on lib/ansible/modules/network/panos/panos_pg.py
> +    if not pg_name:
same as `ip_address`

2017-01-05 04:14 UTC, privateip commented on lib/ansible/modules/network/panos/panos_pg.py
> +        import sys
use the `get_exception` function in ansible.module_utils.basic instead

```
from ansible.module_utils.basic import get_exception

.....

except PanXapiError:
   exc = get_exception()
   module.fail_json(msg=exc.message)
```

2017-01-05 04:14 UTC, privateip commented on lib/ansible/modules/network/panos/panos_pg.py
> +RETURN = '''
doesn't match actual return string

2017-01-06 23:13 UTC, ivanbojer commented
Thank you for the review. I've incorporated all the changes as request and will follow these in the further modules. The one thing I was not sure about was RETURN documentation and I followed what was done in 'wakeonlan.py' given that this module has no return value.

2017-01-06 23:15 UTC, ivanbojer commented on lib/ansible/modules/network/panos/panos_pg.py
> +RETURN = '''
ok, I followed what was done in 'wakeonlan.py' given that this module has no return variables either.

2017-01-06 23:15 UTC, ivanbojer commented on lib/ansible/modules/network/panos/panos_pg.py
> +    if not ip_address:
OK

2017-01-06 23:15 UTC, ivanbojer commented on lib/ansible/modules/network/panos/panos_pg.py
> +    if not password:
OK

2017-01-06 23:15 UTC, ivanbojer commented on lib/ansible/modules/network/panos/panos_pg.py
> +    if not pg_name:
OK

2017-01-06 23:15 UTC, ivanbojer commented on lib/ansible/modules/network/panos/panos_pg.py
> +        import sys
OK

2017-01-06 23:15 UTC, ivanbojer commented
ready_for_review

2017-01-10 04:48 UTC, merged