new module to load configuration file
ansible/ansible pull request #19902
Opened 2017-01-04 23:04 UTC by ivanbojer

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
panos_loadcfg

##### ANSIBLE VERSION

```
ansible 2.1.0.0 
config file = 
configured module search path = Default w/o overrides
```

##### SUMMARY
New panos module that allows admin to apply and load new configuration into the firewall. The file has to be imported first using panos_import module.

2017-01-05 04:21 UTC, privateip requested changes

2017-01-05 04:21 UTC, privateip commented on lib/ansible/modules/network/panos/panos_loadcfg.py
> +RETURN = '''
does not match actual return dict

2017-01-05 04:21 UTC, privateip commented on lib/ansible/modules/network/panos/panos_loadcfg.py
> +    if not ip_address:
not needed when `required=True` is specified

2017-01-05 04:21 UTC, privateip commented on lib/ansible/modules/network/panos/panos_loadcfg.py
> +    if not password:
not needed when `required=True` is specified

2017-01-05 04:21 UTC, privateip commented on lib/ansible/modules/network/panos/panos_loadcfg.py
> +    if file_ is None:
not needed when `required=True` is specified

2017-01-05 04:21 UTC, privateip commented on lib/ansible/modules/network/panos/panos_loadcfg.py
> +    xapi = pan.xapi.PanXapi(
common function?

2017-01-06 23:21 UTC, ivanbojer commented on lib/ansible/modules/network/panos/panos_loadcfg.py
> +RETURN = '''
There is no return value so I mimicked what was done in wakeonlan.py

2017-01-06 23:21 UTC, ivanbojer commented on lib/ansible/modules/network/panos/panos_loadcfg.py
> +    if not ip_address:
ok

2017-01-06 23:21 UTC, ivanbojer commented on lib/ansible/modules/network/panos/panos_loadcfg.py
> +    if not password:
ok

2017-01-06 23:22 UTC, ivanbojer commented on lib/ansible/modules/network/panos/panos_loadcfg.py
> +    xapi = pan.xapi.PanXapi(
nope, just class instantiation.

2017-01-06 23:22 UTC, ivanbojer commented on lib/ansible/modules/network/panos/panos_loadcfg.py
> +    if file_ is None:
ok

2017-01-06 23:22 UTC, ivanbojer commented
ready_for_review

2017-01-10 04:49 UTC, merged