(docs) Remove/update mentions of `git submodule` in docs and error me…
ansible/ansible pull request #19941
Opened 2017-01-05 16:36 UTC by ryansb

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME

##### SUMMARY

Per core-meeting today, this change removes submodule instructions from error messages and Arch linux packaging script.

2017-01-05 16:54 UTC, gundalow approved these changes
Looks good.
Simplified instructions for the win

2017-01-05 16:58 UTC, bcoca commented
not sure we should remove it as people might still be using 2.2 git checkouts, we need 2 sections (from now on: and for those using 2.0-2.2:)

2017-01-05 20:16 UTC, dharmabumstead requested changes
Please remove the "not the same kind of modules, alas" bit and it looks good to go.

2017-01-05 20:39 UTC, alikins commented
code changes in the pr LGTM, but may be useful to add more detail to those error messages as well (ala https://github.com/ansible/ansible/compare/devel...alikins:recursive)

2017-01-06 21:58 UTC, dharmabumstead approved these changes

2017-01-07 19:24 UTC, gundalow approved these changes

2017-01-07 19:25 UTC, gundalow commented
Rebase needed, `./docsite/rst/` is now `./docs/docsite/rst/`

2017-01-09 13:04 UTC, ryansb commented
@gundalow done!

2017-01-09 14:06 UTC, gundalow commented
SHIPIT!

2017-01-09 17:11 UTC, merged