Increase wait_for_vm_ip poll time
ansible/ansible pull request #19947
Opened 2017-01-05 19:59 UTC by neilhwatson

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
vmware_guest.py

##### SUMMARY
Sometimes the wait_for_vm_ip in the guest_vmware module will not return an IP address. Increasing this poll number allows more time for the mdoule to get the new guest's IP from Vsphere.

2017-01-05 21:02 UTC, jctanner commented
@neilhwatson it might make more sense to add this as a configurable parameter to the module. 200 seconds may not be enough for some VMs/infras either.

@nerzhul @dav1x thoughts?

2017-01-05 21:17 UTC, neilhwatson commented
The Vsphere env I have is pretty wonky; If it works here I don't think further configuration would be needed, but an in play option is a nicer solution.

2017-01-05 21:37 UTC, nerzhul commented
@jctanner i agree timeout should be configurable, it's a far better approach

2017-01-05 22:00 UTC, dav1x commented
@jctanner I also like the idea of a configurable parameter. 

But, I think that a base number should still be applied as the default. Some networks are faster than others but, if vmtoolsd doesn't properly start it could make for a long wait before the module is finished.

2017-01-06 04:34 UTC, jctanner requested changes
Please convert this into an argument on the module with a default setting of 200.

2017-01-08 18:36 UTC, dagwieers commented
I was convinced that `wait_for_ip_address` was useful, and also was contemplating a `wait_for_customization` option, but after testing and experimenting it does not bring me anything.

The reason is that you are waiting for the system to be available so you can continue to work on it, however the availability of the IP address does not help in any way for this. Usually you'd wait for the system to be joined to the domain, run some additional task (i.e. adding a key, or running SysPrep runonce to enable WinRM). And even a `wait_for_customization` is not sufficient (see #20011 )

So for me the solution is not inside vmware_guest, but rather in functionality in Ansible, like `wait_for_connection`. Which does exactly what is needed (although not feature-complete yet) and does it correctly, as it tests if WinRM/SSH is actually working ! And reports a proper error if it fails (e.g. WinRM 500 error, or SSH key problems).

BTW there are other issues with `wait_for_ip_address`, in the sense that it does not differentiate between a DHCP address, local link addresses (169.254.* or fe80) or even IPv4 or IPv6. Ideally you would provide it with an address to check for (maybe the one from customizations).

So why do this as part of vmware_guest when we have the means to do it better.

I would actively vote for removing the `wait_for_ip_address` because it leads to implementing the wrong solution in almost every case.

2017-01-08 19:35 UTC, dagwieers commented
So, as @jctanner correctly mentioned on IRC, there is the use-case where people get an IP address and need this address in order to continue (e.g. with waiting_for_connection). So we need to wait until an IP address is assigned.

So why don't we simply make vmware_guest end at the end of the customization process by default, so that any address that is assigned will be part of the facts returned. I will have to look at what is possible here (even if people don't explicitly add customization maybe we can have an empty customization part just in order to detect the end).

PS When I *was* using wait_for_ip_address, I had the case once that my IPv4 address was not added, but I did have an IPv6 local link address. vmware_guest did come back, but the playbook would bail out eventually. That's why I think the current implementation will not cut if for whatever people's use cases until we have something that covers everything. I hate to see: wait_for_ipv4_address, wait_for_ipv6_address, wait_for_customization, wait_for_address: x.y.z.a, wait_for_address_in: x.y.z.a/d, ...

2017-01-08 20:48 UTC, nerzhul commented
@dagwieers wait_for_ip_address is required if you create a VM and wait for guest to have an IP to do some modifications, but not required if you just do idempotence on guest, stopped or not.

2017-01-09 22:33 UTC, dav1x commented
@dagwieers  

I can definitely see your point. But, my openshift ansible on vmware playbooks actually use a

```
until:  actual_production_hosts.ansible_facts.hw_eth0.ipaddresses[0] is defined
```

While I can see the problematic nature of waiting for an ip_address (docker container private network, openshift SDN, vxlan overlay network, etc, etc, etc), I think to some degree if you are cloning from a template you have some responsibility when that template was initially created.

2017-01-10 09:49 UTC, dagwieers commented
Right, there's always the possibility to run the (not-yet-existing) vmware_guest_facts to query the ip-address(es) and match them with a network or whatever condition you prefer. In fact, we could do the same thing for waiting for customizations or other conditions (e.g. power state, etc.).

That said, since it is an option that is already released with v2.2 there is no chance of removing `wait_for_ip_address:` either. (*"between wish and deed there are laws and practical objections" -- Willem Elsschot*). But I am very reluctant to add additional options to vmware_guest and for non-core functionality (like waiting for an ip address) even more. I don't object increasing the time, and to something even higher than what is proposed by default. If people want to have more control over this an until-loop seems the best suggestion. Thanks @dav1x !

/me makes a note to add such example to the documentation once we have vmware_guest_facts.

2017-01-10 14:00 UTC, neilhwatson commented
A quick update. Further testing showed that this increased timeout do not fix the underlying problem sometimes no ipv4 address was returned. I resorted to pausing the play then using vmware_vm_facts to find the IP address. So I don't think this PR will accomplish anything. The problem is more subtle.

2017-02-21 13:57 UTC, jctanner commented
@neilhwatson should we close this PR?

2017-02-21 14:05 UTC, closed without merging