win_reboot: display message before rebooting
ansible/ansible pull request #19986
Opened 2017-01-06 20:06 UTC by dagwieers

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

win_reboot

##### ANSIBLE VERSION

v2.3

##### SUMMARY

Show a message to users when rebooting the system.

TODO: Look if this message is logged in the EventLog properly, if not,
fix that :-)

2017-01-06 20:40 UTC, dagwieers commented
Shippable fails due to:
```
2017-01-06 20:08:23 WARNING: Failed to pull docker image "ansible/ansible:fedora24". Waiting a few seconds before trying again.
2017-01-06 20:08:26 ERROR: Failed to pull docker image "ansible/ansible:fedora24".
```

2017-01-10 10:59 UTC, dagwieers commented
@nitzmahone I think this deserves your attention as well ;-)

2017-01-10 16:22 UTC, nitzmahone requested changes
Need to ditch the int cast.

2017-01-10 16:22 UTC, nitzmahone commented on lib/ansible/plugins/action/win_reboot.py
> +        msg = int(self._task.args.get('msg', self.DEFAULT_REBOOT_MESSAGE))
`int()`? Guessing bad copy/paste and no testing- this results in `ValueError: invalid literal for int() with base 10: 'hey d00d gonna reboot'`

2017-01-10 21:09 UTC, dagwieers commented on lib/ansible/plugins/action/win_reboot.py
> +        msg = int(self._task.args.get('msg', self.DEFAULT_REBOOT_MESSAGE))
That's weird, I thought I did that and my branch has it fixed.
I just force-pushed it again.

2017-01-10 21:12 UTC, dagwieers commented
I have been using this for the last 4 days, and I even increased the delay so people can view my nice messages ;-) 2 seconds is too fast to even have a glimpse.

If Ansible had a way to get to the task's name, it would be nice to use that as a default. Or allow people to use that instead (because I always put the reason in the task's name).

2017-01-10 21:58 UTC, nitzmahone commented
Nice- that looks better. :) Sadly, no way for a module to get at the task name ATM...

2017-01-10 21:59 UTC, merged