vmware_guest: New features
ansible/ansible pull request #20018
Opened 2017-01-08 16:47 UTC by aperigault

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
```
2.2.0
```

##### SUMMARY
- Add capability to mark an existing VM as template
- Add capability to rename an existing VM

2017-01-09 09:21 UTC, nerzhul requested changes

2017-01-09 09:21 UTC, nerzhul commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +
can you remove this empty line ?

2017-01-09 09:21 UTC, nerzhul commented
Except the empty line it's good for me

2017-01-09 09:25 UTC, gundalow commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +        required: False
Please add the following line, at the same indentation level as `required: False`
`version_added: "2.3`

2017-01-09 09:26 UTC, gundalow requested changes
needs_revision

2017-01-09 09:33 UTC, aperigault commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +        required: False
Fixed!

2017-01-09 09:33 UTC, aperigault commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +
Fixed!

2017-01-09 09:36 UTC, nerzhul approved these changes
Okay now, thanks

2017-01-09 09:36 UTC, nerzhul commented
shipit

2017-01-09 09:37 UTC, gundalow approved these changes

2017-01-09 09:37 UTC, merged

2017-01-09 09:37 UTC, gundalow commented
Merged, thanks

2017-01-09 09:40 UTC, dagwieers commented
Hmm, that's not a good interface for doing an operation IMO.
What happens if you run this task twice ?

2017-01-09 09:50 UTC, aperigault commented
@dagwieers What is your proposal ?
If I extend checks it will ok for you ?

2017-01-09 09:52 UTC, nerzhul commented
@dagwieers if you run twice you will not found original VM then changed = False, it's lgtm

2017-01-09 09:54 UTC, nerzhul commented
@aperigault can you add a bugfix to check if vm exists when new_name is provided ? If not you should fail

2017-01-09 09:56 UTC, aperigault commented
@nerzhul Yes I'm writing this check right now. I also add an idempotent check if template is already one.

2017-01-09 09:58 UTC, nerzhul commented
good point

2017-01-09 09:59 UTC, dagwieers commented
Again, I think it is a bad design to mix states like absent/present, with operations like moving just because there is another parameter new_name. If you add more parameters for other operations (just like the snapshotting) it becomes a big problem IMO.

And adding more checks internally is hell. Because you will have to explain the user the different scenarios and what can work together and what not.

2017-01-09 10:00 UTC, dagwieers commented
That's the reason why I would like to move facts gathering and snapshot operations out of vmware_guest. Not adding more things.

2017-01-09 10:03 UTC, aperigault commented
Your proposal is to do a new module only to rename a VM ? And an other one to Mark Vm as template ?

2017-01-09 10:15 UTC, nerzhul commented
@aperigault doesn't make sense to vm name and vm is_template as they are attribute of the VM, but it make sense for snapshot (which is an object itself) and for facts gathering (like ec2_facts)

2017-01-09 10:18 UTC, aperigault commented
@nerzhul I'm agree. I'm waiting for @dagwieers proposal.

2017-01-09 10:22 UTC, dagwieers commented
No, what I am saying is that the existence of parameters is not a good way to indicate operations.
That will become a big mess quickly. We have `state:` for operations.

That said, I do think that some operations do not belong in vmware_guest. I would like to see how other modules do the same thing (and even if they use the existence of `new_name:`  as an operation, that's bad.

2017-01-09 11:23 UTC, aperigault commented
@dagwieers Is not exactly the same thing but there is another rename function here : https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/lxd/lxd_profile.py#L153 implemented exactly in the same way. This does not mean that it is good...
For now I do a new commit to add checks : https://github.com/aperigault/ansible/commit/d600d5af8f297cdb41bdf0eff66dc88a50fb8da3 I'm waiting for your opinion before do a new PR.
@bcoca Have you an opinion about this ?

2017-01-10 09:27 UTC, dagwieers commented
BTW the reason why I am pedantic about this is because when we create something new the interface is more important than the code. The code we can change and fix afterwards, the interface not so easily.

That's why I am always very concerned when new things are added to the interface (we will have to support it from release onwards despite improved insights/understanding)

2017-01-10 17:56 UTC, bcoca commented
@dagwieers  +10

2017-01-10 17:58 UTC, bcoca commented
since name is not unique identifier i would overload name: and if it is different for the uiid: provided (actual unique identifier), change it.

If you don't know the uuid a previous task that looks it up should be added.

2017-01-10 19:09 UTC, dagwieers commented
Ok, I like that. So something like this:

```yaml
- name: Move the VM
  vmware_guest:
    uuid: 1234-....-abcd
    name: new-name
    state: rename
```
That would be idempotent on consecutive runs, and uses `state:` for operations.

2017-01-10 19:25 UTC, aperigault commented
I understand the problem but nobody use the uuid of a VM. If you think it's difficult to explain how to use the module with actual implementation. I think it would be more complicated to explain why you need to do this to rename a VM.
Instead of fail in renaming task your job will fail in previous task.
Can we use new_name only when state is rename for example ?

2017-01-10 19:34 UTC, bcoca commented
i would even do it on 'state: present' as having a name not matching uuid would imply that imo, 'state=rename' just seems wrong.

@aperigault I think that having it as a 2 step process is fine, if you really dont like this approach i would suggest a dedicated module.

2017-01-10 21:01 UTC, dagwieers commented
bcoca: I considered a rename a special operation that you wouldn't put in your normal (reran) playbooks. (Hence the idea of having it in special purpose module)

But what you suggest is even better if you consider a change in the playbook would automatically cause a rename. (the name would be just another property, which it actually is) It does mean that people initially make the right mapping (e.g. when moving van name-based to uuid-based handling in order to work with renames). Or they use a 2-step approach as you suggested.

It also makes uuid-based handling a preferred way of working, which is not bad either. I can live with this and feels much more in line with what @jctanner wanted too.