cloud: ovirt: add affinity groups module
ansible/ansible pull request #20047
Opened 2017-01-09 15:12 UTC by machacekondra

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

lib/ansible/modules/cloud/ovirt/ovirt_affinity_groups.py

##### ANSIBLE VERSION

```
ansible 2.3.0
```

##### SUMMARY

This PR adds new module which handle managing of affinity groups in oVirt.

2017-01-09 16:31 UTC, machacekondra commented
@mwperina @ryansb

2017-01-11 09:22 UTC, machacekondra commented
shipit

2017-01-23 07:22 UTC, mwperina requested changes

2017-01-23 07:22 UTC, mwperina commented on lib/ansible/modules/cloud/ovirt/ovirt_affinity_groups.py
> +            - "If I(true) vm cannot start on host if it does not satisfy the C(host_rule)."
vm -> VM

2017-01-23 07:22 UTC, mwperina commented on lib/ansible/modules/cloud/ovirt/ovirt_affinity_groups.py
> +            - "If I(positive) I(all) vms in this group should run on the this host."
vms -> VMs

2017-01-23 07:22 UTC, mwperina commented on lib/ansible/modules/cloud/ovirt/ovirt_affinity_groups.py
> +            - "If I(negative) I(no) vms in this group should run on the this host."
vms -> VMs

2017-01-24 17:35 UTC, machacekondra commented
@ryansb shipit

2017-01-24 21:42 UTC, mwperina requested changes

2017-01-24 21:42 UTC, mwperina commented on lib/ansible/modules/cloud/ovirt/ovirt_affinity_groups.py
> +            - "If I(true) vm cannot start on host if it does not satisfy the C(host_rule)."
Above comment is still valid :-)

2017-01-25 14:17 UTC, merged