added ability to modify nova flavor metadata in os_nova_flavor module
ansible/ansible pull request #20091
Opened 2017-01-10 14:27 UTC by kuboj

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
os_nova_flavor

##### ANSIBLE VERSION
```
ansible 2.2.0.0
```

##### SUMMARY
This PR adds ability to specify metadata (aka extra_specs) for nova flavors using shade API.

2017-02-13 15:35 UTC, gundalow requested changes
Have a look at docs.ansible.com/ansible/dev_guide/developing_modules_documenting.html for details on how to document modules

2017-02-13 15:35 UTC, gundalow commented on lib/ansible/modules/cloud/openstack/os_nova_flavor.py
> +     default: None
Please add `version_added: "2.3"` to this section

2017-02-13 15:35 UTC, gundalow commented on lib/ansible/modules/cloud/openstack/os_nova_flavor.py
> +# Create flavor with metadata
Please use `- name: Create flavor with metadata` (and remove `-` from in front of `os_nova_flavor:`

2017-02-16 09:43 UTC, kuboj commented
Documentation fixed according to comments by @gundalow

2017-02-16 09:44 UTC, kuboj commented
ready_for_review

2017-02-16 11:19 UTC, rcarrillocruz commented on lib/ansible/modules/cloud/openstack/os_nova_flavor.py
> +     default: None
Along with the doc change, please force the version requirement in the code itself too.
We use StrictVersion for that, have a look at https://github.com/ansible/ansible/blob/829c0b8f6284ec37e36f1454d7d3640415239cb2/lib/ansible/modules/cloud/openstack/os_network.py#L186 .

2017-02-16 11:25 UTC, rcarrillocruz commented
shipit

2017-02-16 19:18 UTC, gundalow approved these changes

2017-02-23 11:58 UTC, merged