cloud: ovirt: add ability to override luns
ansible/ansible pull request #20144
Opened 2017-01-11 17:17 UTC by tareqalayan

Add the ability to wipe used luns when adding new iscsi storage

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY

```

```

2017-01-11 17:24 UTC, tareqalayan commented
@machacekondra  please review

2017-01-11 18:12 UTC, machacekondra commented
Looks good to me, thank you.

2017-01-11 18:12 UTC, machacekondra commented
@ryansb shipit

2017-01-11 18:16 UTC, machacekondra requested changes

2017-01-11 18:16 UTC, machacekondra commented on lib/ansible/modules/cloud/ovirt/ovirt_storage_domains.py
> +        override_luns=dict(type='bool', default=False),
Please remove this line, `override_luns` are part of `iscsi` dictinary

2017-01-11 18:16 UTC, machacekondra commented on lib/ansible/modules/cloud/ovirt/ovirt_storage_domains.py
> +            - "C(override_luns) - If I(True) storage domain will be formatted before adding it."
Maybe it would be nice to say, something like:
If `True` ISCSI storage domain luns will be overriden before adding.
What do you think?

2017-01-11 20:55 UTC, tareqalayan commented on lib/ansible/modules/cloud/ovirt/ovirt_storage_domains.py
> +            - "C(override_luns) - If I(True) storage domain will be formatted before adding it."
done

2017-01-11 20:56 UTC, tareqalayan commented on lib/ansible/modules/cloud/ovirt/ovirt_storage_domains.py
> +        override_luns=dict(type='bool', default=False),
done

2017-01-11 21:29 UTC, tareqalayan commented
@machacekondra  done and tested

2017-01-11 22:26 UTC, ryansb approved these changes

2017-01-12 14:12 UTC, tareqalayan commented
@machacekondra please take a look and approve, 

Thanks

2017-01-12 18:12 UTC, machacekondra commented
Looks good to me, thanks.

2017-01-12 18:13 UTC, machacekondra commented
shipt

2017-01-12 19:13 UTC, merged