Empty string is not valid path
ansible/ansible pull request #20153
Opened 2017-01-11 21:18 UTC by jtyr

##### ISSUE TYPE

Bugfix Pull Request

##### COMPONENT NAME

AnsibleModule class.

##### ANSIBLE VERSION

```
ansible 2.3.0 (jtyr-path_type 86a9b6c569) last updated 2017/01/11 21:09:42 (GMT +100)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY

This patch is checking for empty string passed to a module parameter of type `path`. Python is treating empty string is an invalid path:

```
In [1]: open('', 'r')
---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
<ipython-input-1-edeadb16a11b> in <module>()
----> 1 open('', 'r')

IOError: [Errno 2] No such file or directory: ''
```

This patch will cause the `_check_type_path()` fail with a message which is then displayed in the `details` as shown below:

```
failed: [test-soe] (item={u'user_id': 1000, u'user_comment': u'My user', u'user_password': u'$6$fAknMdY5$VuAzbn3N52r7kSPN2ALSVArJJP/83NeApvsotA/fA5EIuhUB274q.6czfKWPuXbHrP0GVJuiKR8pG1F2Ybe/g3', u'group_name': u'myuser', u'group_id': 1000, u'user_name': u'myuser'}) => {
    "details": "Path can not be an empty string.", 
    "failed": true, 
    "invocation": {
        "module_args": {
            "append": "no", 
            "comment": "", 
            "createhome": "yes", 
            "force": false, 
            "group": "myuser", 
            "home": "", 
            "move_home": "no", 
            "name": "myuser", 
            "non_unique": false, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "remove": "no", 
            "ssh_key_bits": 0, 
            "ssh_key_comment": "ansible-generated on localhost.localdomain", 
            "ssh_key_type": "rsa", 
            "state": "present", 
            "system": "no", 
            "uid": "1000", 
            "update_password": "always"
        }, 
        "module_name": "user"
    }, 
    "item": {
        "group_id": 1000, 
        "group_name": "myuser", 
        "user_comment": "My user", 
        "user_id": 1000, 
        "user_name": "myuser", 
        "user_password": "$6$fAknMdY5$VuAzbn3N52r7kSPN2ALSVArJJP/83NeApvsotA/fA5EIuhUB274q.6czfKWPuXbHrP0GVJuiKR8pG1F2Ybe/g3"
    }, 
    "msg": "argument home is of type <type 'str'> and we were unable to convert to path"
}
```

2017-01-11 21:30 UTC, jtyr commented
@bcoca please review.

2017-01-11 22:44 UTC, bcoca commented on lib/ansible/module_utils/basic.py
> +                    details=str(e))
use 'exception' key which is already there for this kind of thing, 'details' is not something ansible recognizes.

2017-01-11 22:46 UTC, bcoca requested changes

2017-01-11 22:46 UTC, bcoca commented on lib/ansible/module_utils/basic.py
> +        if valid_path == '':
i'm still not sure we should do this for all modules

2017-01-11 22:46 UTC, bcoca commented on lib/ansible/module_utils/basic.py
> +        if valid_path == '':
what if valid_path is None?

2017-01-11 23:15 UTC, jtyr commented on lib/ansible/module_utils/basic.py
> +        if valid_path == '':
If an empty string is invalid path then it should be fixed for all modules.

Any of the os.path functions used in this case return `None` so no need to test it. If `None` is passed to any of the functions, the function rises `TypeError: argument of type 'NoneType' is not iterable` error.

2017-01-11 23:19 UTC, bcoca commented on lib/ansible/module_utils/basic.py
> +        if valid_path == '':
And that 'if' is what im having issues with, I'm not sure it is invalid.

In any case, if it is None it doesn't even hit this function, None is a valid value for paths in many modules (most of the file modules check for this specifically).

2017-01-11 23:22 UTC, jtyr commented on lib/ansible/module_utils/basic.py
> +        if valid_path == '':
I have proven in the PR description that it is in deed invalid.

If it doesn't hit this function with `None` value then we don't need to test the `None` here at all.

2017-01-11 23:28 UTC, jtyr commented on lib/ansible/module_utils/basic.py
> +                    details=str(e))
There is quite few `details=` in `modules` and `modules_utils`. But it's true that there is much more occurrences of `exception=`. So I will change it to `exception=` here (and in all my modules ;o)).

2017-06-28 16:28 UTC, jimi-c commented
@jtyr I agree with @bcoca here, I don't think an empty path is always invalid. To me, in pretty much every language I've used, an empty path == the current working directory. It is true that it's not a valid _file_ name, however this may not always be used for a path to a file by every module. If this were `_check_type_file`, I would be more inclined to your argument.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

2017-06-28 16:28 UTC, closed without merging