New AWS VPC Endpoint module for creating and deleting VPC endpoints
ansible/ansible pull request #20212
Opened 2017-01-13 05:06 UTC by willthames

Create and delete AWS VPC Endpoints. Requires Boto3.
- Creates AWS VPC endpoints.
- Deletes AWS VPC endpoints.
- This module support check mode.

2017-01-13 05:06 UTC, willthames commented
Migrated from https://github.com/ansible/ansible-modules-extras/pull/1430 by willthames (not original author)

2017-02-01 00:08 UTC, willthames commented
!needs_revision

2017-02-02 15:03 UTC, ryansb submitted a review, later dismissed

2017-02-02 15:03 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/ec2_vpc_endpoint.py
> +        module.fail_json(msg='botocore and boto3 are required for removal')
I think this message should just be `botocore and boto3 are required for this module`.

2017-02-02 15:03 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/ec2_vpc_endpoint.py
> +        module.fail_json(msg=str(e))
Please add a message like "Failed to connect to AWS due to wrong or missing credentials" rather than just `str(e)`

2017-02-02 15:03 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/ec2_vpc_endpoint.py
> +            policy=dict(),
To match style in other AWS modules, can you please use `policy` to take a "json" typed argument and a mutually exclusive `policy_file` argument to take a file path? That way users can specify a JSON string, a regular YAML dictionary, or a file from another source so they have the maximum flexibility.

2017-02-02 15:03 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/ec2_vpc_endpoint.py
> +                    json_data.close()
This `.close()` isn't needed, the context manager closes the file automatically.

2017-02-02 15:03 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/ec2_vpc_endpoint.py
> +                module.fail_json(msg=str(e))
For exceptions, include `exception=traceback.format_exc()` so the full error is preserved.

2017-02-02 15:03 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/ec2_vpc_endpoint.py
> +result:
Please document return values w/ example.

2017-02-02 15:03 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/ec2_vpc_endpoint.py
> +        result = client.create_vpc_endpoint(**params)['VpcEndpoint']
When returning output from boto3 calls, remember to use `camel_dict_to_snake_dict` to make capitalization consistent.

2017-02-20 05:39 UTC, willthames commented
@ryansb your concerns should now have been addressed.

2017-02-20 10:00 UTC, wimnat commented on lib/ansible/modules/cloud/amazon/ec2_vpc_endpoint.py
> +            policy=dict(),
I think that is unnecessary.  If you want a file just jinja it with lookup('file', 'path/to/file').  Providing more examples is preferred over a possibly confusing second parameter IMO.

2017-02-20 10:17 UTC, wimnat requested changes

2017-02-20 10:17 UTC, wimnat commented on lib/ansible/modules/cloud/amazon/ec2_vpc_endpoint.py
> +extends_documentation_fragment: aws
Should also extend ec2

2017-02-20 10:17 UTC, wimnat commented on lib/ansible/modules/cloud/amazon/ec2_vpc_endpoint.py
> +EXAMPLES = '''
I would add the 'standard' AWS examples comment:

`# Note: These examples do not set authentication details, see the AWS Guide for details.`

2017-02-20 10:17 UTC, wimnat commented on lib/ansible/modules/cloud/amazon/ec2_vpc_endpoint.py
> +    import botocore
I would look for boto3 specifically.  You can have botocore without boto3 but not vice versa

2017-02-20 10:17 UTC, wimnat commented on lib/ansible/modules/cloud/amazon/ec2_vpc_endpoint.py
> +            vpc_id=dict(),
You should specify required=True here.

If this is only required when state=present then use `required_if`

2017-02-20 10:17 UTC, wimnat commented on lib/ansible/modules/cloud/amazon/ec2_vpc_endpoint.py
> +        module.fail_json(msg='vpc_id is a required paramater')
Do this in the module parameters rather than here

2017-02-20 10:17 UTC, wimnat commented on lib/ansible/modules/cloud/amazon/ec2_vpc_endpoint.py
> +        module.fail_json(msg='a valid service is a required paramater')
As above

2017-02-20 10:17 UTC, wimnat commented on lib/ansible/modules/cloud/amazon/ec2_vpc_endpoint.py
> +            service=dict(),
As above

2017-02-20 10:17 UTC, wimnat commented on lib/ansible/modules/cloud/amazon/ec2_vpc_endpoint.py
> +    except botocore.exceptions.NoCredentialsError as e:
Handle all AWS exceptions as per guidelines https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/GUIDELINES.md#boto3-2

2017-02-20 10:17 UTC, wimnat commented on lib/ansible/modules/cloud/amazon/ec2_vpc_endpoint.py
> +            module.fail_json(msg=str(e), exception=traceback.format_exc())
Handle exception as per guidelines https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/GUIDELINES.md#boto3-2

2017-02-20 10:17 UTC, wimnat commented on lib/ansible/modules/cloud/amazon/ec2_vpc_endpoint.py
> +        if "DryRunOperation" in e.message:
For all below - Handle exception as per guidelines https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/GUIDELINES.md#boto3-2

2017-02-20 20:14 UTC, mattclay commented
CI failure due to module validation error:

```
2017-02-20 05:42:07 ============================================================================
2017-02-20 05:42:07 lib/ansible/modules/cloud/amazon/ec2_vpc_endpoint.py
2017-02-20 05:42:07 ============================================================================
2017-02-20 05:42:07 ERROR: No ANSIBLE_METADATA provided
2017-02-20 05:42:07 ERROR: Import found before documentation variables. All imports must appear below DOCUMENTATION/EXAMPLES/RETURN/ANSIBLE_METADATA. line 17
2017-02-20 05:42:07 ERROR: Import found before documentation variables. All imports must appear below DOCUMENTATION/EXAMPLES/RETURN/ANSIBLE_METADATA. line 18
2017-02-20 05:42:07 ERROR: Import found before documentation variables. All imports must appear below DOCUMENTATION/EXAMPLES/RETURN/ANSIBLE_METADATA. line 19
2017-02-20 05:42:07 ERROR: Import found before documentation variables. All imports must appear below DOCUMENTATION/EXAMPLES/RETURN/ANSIBLE_METADATA. line 20
2017-02-20 05:42:07 ERROR: Import found before documentation variables. All imports must appear below DOCUMENTATION/EXAMPLES/RETURN/ANSIBLE_METADATA. line 22
2017-02-20 05:42:07 ERROR: Import found before documentation variables. All imports must appear below DOCUMENTATION/EXAMPLES/RETURN/ANSIBLE_METADATA. line 23
2017-02-20 05:42:07 ERROR: Import found before documentation variables. All imports must appear below DOCUMENTATION/EXAMPLES/RETURN/ANSIBLE_METADATA. line 24
```

2017-02-20 23:25 UTC, willthames commented on lib/ansible/modules/cloud/amazon/ec2_vpc_endpoint.py
> +    import botocore
You don't need to

I import HAS_BOTO3 from module_utils.ec2, and the module itself doesn't directly rely on boto3 (it does rely on botocore)

2017-02-20 23:26 UTC, willthames commented on lib/ansible/modules/cloud/amazon/ec2_vpc_endpoint.py
> +            policy=dict(),
Grrr, that's how it was before I changed it. @ryansb and @wimnat can you agree on this because this is just annoying.

2017-02-20 23:28 UTC, willthames commented on lib/ansible/modules/cloud/amazon/ec2_vpc_endpoint.py
> +            vpc_id=dict(),
required_if is completely undocumented. The module developer guidelines really need an update.

2017-02-20 23:47 UTC, willthames commented on lib/ansible/modules/cloud/amazon/ec2_vpc_endpoint.py
> +            module.fail_json(msg=str(e), exception=traceback.format_exc())
Guidelines need update to reflect what to do with traceback as this was updated based on feedback in this PR.

2017-02-27 05:56 UTC, willthames commented
ready_for_review

I've addressed all @wimnat's comments other than the `policy`/`policy_file` debate.

2017-02-28 01:38 UTC, willthames commented
!needs_revision

2017-04-05 11:22 UTC, ryansb approved these changes

2017-04-05 12:28 UTC, ryansb commented
heh, thanks @willthames was just about to push the same thing :1st_place_medal:

2017-04-05 12:28 UTC, merged