cloud/ovirt: set storage domain when creating vm
ansible/ansible pull request #20310
Opened 2017-01-16 17:45 UTC by tareqalayan

##### ISSUE TYPE

 - Feature Pull Request
 - New Module Pull Request
 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME

##### ANSIBLE VERSION

```

```

##### SUMMARY

```

```

2017-01-16 17:45 UTC, tareqalayan commented
@machacekondra please review thanks

2017-01-17 09:12 UTC, machacekondra commented on lib/ansible/modules/cloud/ovirt/ovirt_vms.py
> +    def __get_storage_domain(self):
You may use `search_by_name()' method:

```
search_by_name(
    self._connection.system_service().storage_domains_service(),
    self._module.params['storage_domain']
)
```

https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/ovirt.py#L221

2017-01-17 09:14 UTC, machacekondra commented on lib/ansible/modules/cloud/ovirt/ovirt_vms.py
> +        disk = disk_attachments[0].disk
Hmm, what if the template will have more disks. We have to somehow distinguish which one should go where...

2017-01-18 06:32 UTC, tareqalayan commented
@machacekondra please review 

thanks,

2017-01-20 12:05 UTC, machacekondra commented
We need to think about the possibility of specification of specific storage of specific disk.

2017-01-23 21:03 UTC, machacekondra commented
Maybe we can do following:

Specific disk to specific SD:
```yaml
ovirt_vms:
  name: myvm
  template: mytemplate
  cluster: mycluster
  disks:
    -  id: 123
       storage_domain: nfs_0
```

All disks to one SD:
```yaml
ovirt_vms:
  name: myvm
  template: mytemplate
  cluster: mycluster
  disks:
    - storage_domain: nfs_0
```
What do you think?

2017-01-24 10:30 UTC, tareqalayan commented
@machacekondra 
OK sounds good, 
I will do the change during the week or beginning of next week.

2017-01-26 04:47 UTC, mattclay commented
Closing and re-opening to trigger CI.

2017-02-06 15:01 UTC, jctanner commented
bot_status

2017-03-21 12:14 UTC, tareqalayan commented
@machacekondra 

i think if there is template in the module we don't have to specify disk_id or name we just need to copy all disks attached to template to the specified storage domain? 

i am just thinking loud here ... what do you think?

2017-03-21 15:15 UTC, tareqalayan commented
@machacekondra 
Ondra can you please review?

2017-03-22 09:58 UTC, myakove commented on lib/ansible/modules/cloud/ovirt/ovirt_vms.py
> +
disks = self._module.params.get('disks', list())

2017-03-22 09:58 UTC, myakove commented on lib/ansible/modules/cloud/ovirt/ovirt_vms.py
> +            for disk in self._module.params['disks']:
for disk in disks:

2017-03-22 09:58 UTC, myakove commented on lib/ansible/modules/cloud/ovirt/ovirt_vms.py
> +        # if self.__get_storage_domain() is None:
remove comments please

2017-03-22 09:58 UTC, myakove commented on lib/ansible/modules/cloud/ovirt/ovirt_vms.py
> +            disk_attachments=disks if disks else None,
disks or None

2017-03-27 11:21 UTC, machacekondra commented on lib/ansible/modules/cloud/ovirt/ovirt_vms.py
> +        )
No need to re-fetch the template, you can just write:
```python
disk_attachments = self._connection.follow_link(template.disk_attachments)
```

2017-03-27 11:22 UTC, machacekondra commented on lib/ansible/modules/cloud/ovirt/ovirt_vms.py
> +                        format=otypes.DiskFormat.COW,
What about 'raw'?

2017-03-27 11:26 UTC, machacekondra commented on lib/ansible/modules/cloud/ovirt/ovirt_vms.py
> +                storage_domain = search_by_name(
Better to use ```get_id_by_name``` it get proper error message if storage is not found

2017-03-27 11:30 UTC, machacekondra commented on lib/ansible/modules/cloud/ovirt/ovirt_vms.py
> +            disk_attachments=disks if disks else None,
I wonder what should happen when disks is [].

2017-03-27 11:32 UTC, machacekondra commented on lib/ansible/modules/cloud/ovirt/ovirt_vms.py
> +        if self.param('template'):
What if we want to create VM from template, and attach some other disks?

2017-03-27 11:37 UTC, machacekondra commented on lib/ansible/modules/cloud/ovirt/ovirt_vms.py
> +            if disk_id == disk.get('id'):
Can we somehow implement behavior of specify storage_domain for all disks? If I understand the code correctly, it not currently.

2017-03-27 11:38 UTC, machacekondra requested changes
Can you also verify the beahvior of copy/move disks?

2017-03-27 12:48 UTC, tareqalayan commented on lib/ansible/modules/cloud/ovirt/ovirt_vms.py
> +        disk = disk_attachments[0].disk
I think they all should go there, no?

2017-03-27 12:48 UTC, tareqalayan commented on lib/ansible/modules/cloud/ovirt/ovirt_vms.py
> +    def __get_storage_domain(self):
ok will change this

2017-03-27 12:48 UTC, tareqalayan commented on lib/ansible/modules/cloud/ovirt/ovirt_vms.py
> +        disk = disk_attachments[0].disk
done

2017-03-27 12:48 UTC, tareqalayan commented on lib/ansible/modules/cloud/ovirt/ovirt_vms.py
> +
done

2017-03-27 12:48 UTC, tareqalayan commented on lib/ansible/modules/cloud/ovirt/ovirt_vms.py
> +            for disk in self._module.params['disks']:
done

2017-03-27 12:48 UTC, tareqalayan commented on lib/ansible/modules/cloud/ovirt/ovirt_vms.py
> +        # if self.__get_storage_domain() is None:
done

2017-03-27 12:48 UTC, tareqalayan commented on lib/ansible/modules/cloud/ovirt/ovirt_vms.py
> +            disk_attachments=disks if disks else None,
I will leave this as is to be like the lines above.

2017-03-27 12:48 UTC, tareqalayan commented on lib/ansible/modules/cloud/ovirt/ovirt_vms.py
> +            if disk_id == disk.get('id'):
The idea here is to specify which disk go where see example:
  ovirt_vms:
    name: vm_test
    cluster: clu1
    template: template01
    operating_system: other_linux
    type: server
    cpu_cores: 1
    cpu_sockets: 1
    state: stopped
    clone: True
    timeout: 600
    disks:
      - id: disk_id1
        storage_domain: my_nfs_1
     -  id: disk_id1
        storage_domains: my_nfs_3

i would prefer not to decalre any disk and only storage domain so all disks related to template will go to spesfic storage domain ... 
but you said there is a use case to split disks of templates on multiple storage domains .... 

please tell me what you suggest... and i will implement it ...

2017-03-27 12:48 UTC, tareqalayan commented on lib/ansible/modules/cloud/ovirt/ovirt_vms.py
> +                storage_domain = search_by_name(
ack

2017-03-27 12:48 UTC, tareqalayan commented on lib/ansible/modules/cloud/ovirt/ovirt_vms.py
> +        )
ack

2017-03-27 12:48 UTC, tareqalayan commented on lib/ansible/modules/cloud/ovirt/ovirt_vms.py
> +                        format=otypes.DiskFormat.COW,
I didn't put much thinking here ... what it should it be?

2017-03-27 12:48 UTC, tareqalayan commented on lib/ansible/modules/cloud/ovirt/ovirt_vms.py
> +            disk_attachments=disks if disks else None,
nothing should happen it put the disk on the first storage storage domain on the list ... in my case it always choose nfs_0 ....

2017-03-27 12:48 UTC, tareqalayan commented on lib/ansible/modules/cloud/ovirt/ovirt_vms.py
> +        if self.param('template'):
i am not familiar with this use case. 

do we want to support that ? 

should i  grab all template disks + disks stated in the module?

2017-04-25 11:01 UTC, tareqalayan commented on lib/ansible/modules/cloud/ovirt/ovirt_vms.py
> +            if disk_id == disk.get('id'):
the plan now is: 
1. if there is a template specified and a storage domain: all disks related to that template will go into the storage domain
2. if there is a template specifeid and disks is specified each disk will go to the specified storage domain:
template: my_template
disks:
  - id_of_disk
  - storage domain 


@machacekondra please ack

2017-06-08 09:31 UTC, closed without merging