Fixing Issue #20315 - win_msi shows changed even when msi not found
ansible/ansible pull request #20358
Opened 2017-01-17 17:41 UTC by JimFicarra

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

win_msi
##### ANSIBLE VERSION

```
ansible 2.3.0 (devel 06e30485ea) last updated 2017/01/16 20:03:34 (GMT +000)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/custom_modules']

This has existed in this module in previous 2.x releases as well.  I confirmed that this is an issue in the latest devel branch as of this writing.

```

##### SUMMARY

Fixes Issue #20315 - win_msi shows as 'changed' when the msi specified in the path attribute is missing.  This is misleading to the user.  

The fix is simple - just checks if the path exists for the specified MSI and if it does not, it will fail with an appropriate message through the Fail-JSON helper function

Sample Task

 name: Install bogus win_msi
 win_msi:
   path: 'd:\build\bogus_installer.msi

```
Before:

server1.mycompany.com | SUCCESS => {
    "changed": true,
    "invocation": {
        "module_name": "win_msi"
    },
    "log": ""
}

After:
fatal: [server1.mycompany.com]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_name": "win_msi"
    },
    "msg": "Cannot find d:\\build\\bogus_installer.msi."
}

```

2017-01-30 16:09 UTC, JimFicarra commented
@sivel are there any blockers to moving this to the next step?

2017-01-30 21:42 UTC, JimFicarra commented
Rebased and ready for review

2017-02-02 21:52 UTC, jborean93 requested changes
win_msi is in a deprecated status (to be replaced with win_package) so I'm not sure what the go is with making changes but there is only a tiny thing I would change. @nitzmahone or @jhawkesworth are you able to advise what we are doing with deprecated modules?

2017-02-02 21:52 UTC, jborean93 commented on lib/ansible/modules/windows/win_msi.ps1
> +{
Sorry to nitpick but are you able to put the braces in the same line as the if statement to keep the same as the rest of the file?

2017-02-02 22:12 UTC, JimFicarra commented on lib/ansible/modules/windows/win_msi.ps1
> +{
@jborean93 I can.  I'll update it in a little bit and push the changes.

2017-02-03 14:36 UTC, JimFicarra commented on lib/ansible/modules/windows/win_msi.ps1
> +{
@jborean93 the requested change has been pushed.

2017-02-03 14:43 UTC, jhawkesworth commented
@jborean93 - I think this would be first windows module to be deprecated.  There is an open PR for adding warnings to modules, so it could produce a warning once that has been merged, otherwise I guess its a change to the module docs to deprecate it.

That said, I think this change is benign.

shipit

2017-02-03 20:27 UTC, jborean93 commented
@JimFicarra looks good, if you have some time it would be appreciated if you could look at some of my pull requests.

shipit

2017-02-04 00:37 UTC, dagwieers commented
shipit

2017-02-04 00:38 UTC, dagwieers commented
@gundalow This one is available to be merged !

2017-02-04 08:32 UTC, merged

2017-02-04 08:33 UTC, gundalow commented
Since this is a simple bug fix I've merged it, even though this is a deprecated module. 

Can someone please confirm that win_package doesn't have this issue, thanks.

2017-02-05 17:13 UTC, jhawkesworth commented
@gundalow - confirmed that win_package does *not* do this - example run below (against latest devel):

```
$ ansible 12 -m win_package -a 'path=C:\Ansible_testing\MadeUp.msi product_id=1'
WIN-KGJARAQCNLQ | FAILED! => {
    "changed": false, 
    "failed": true, 
    "msg": "The given Path (C:\\Ansible_testing\\MadeUp.msi) could not be found", 
    "name": "C:\\Ansible_testing\\MadeUp.msi"
}
```