Fix win_unzip module hang on error
ansible/ansible pull request #20364
Opened 2017-01-17 19:56 UTC by camradal

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
win_unzip

##### ANSIBLE VERSION
```
ansible 2.3.0 (devel 37f0cee2da) last updated 2017/01/17 11:47:59 (GMT -700)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY
During extracting a zip file on Windows, if there's any error (such as not enough disk space), Ansible will hang indefinitely.
The only way to unblock it is to kill the powershell process.
This fix adds an extra flag to not show UI on errors.
From [MSDN documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/bb787866(v=vs.85).aspx)

2017-01-17 20:02 UTC, schwartzmx commented
untested, but seems fine to me 👍

2017-01-18 12:48 UTC, dagwieers commented
Looking good, maybe add the documentation URL as a comment too ?
shipit

2017-01-18 12:49 UTC, dagwieers commented
And I guess 16 overrides 512 anyway ?

2017-01-18 12:49 UTC, gundalow requested changes
needs_revision

Might be worth including the MSDN link in here as well.

2017-01-18 18:54 UTC, dagwieers commented
shipit

2017-01-18 20:44 UTC, gundalow approved these changes

2017-01-18 20:44 UTC, merged

2017-01-18 20:44 UTC, gundalow commented
Merged, thanks

2017-01-18 21:32 UTC, camradal commented
Great, thank you.