Adding benchmark stress module
ansible/ansible pull request #20367
Opened 2017-01-17 21:20 UTC by bbyhuy

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME
stress

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY

Benchmarking is a field which automation is often sought after. By wrapping these benchmark tools (more to come) as Ansible modules, it enables people to quickly launch benchmarks remotely and at scale. Each benchmark module is formatted with essentially the same boilerplate with specific changes to just the parsing and execution portions. As much of the code is kept the same as possible as to allow adding new benchmarks to be quick and painless.

stress is a deliberately simple workload generator for POSIX systems. It imposes a configurable amount of CPU, memory, I/O, and disk stress on the system.

```
$: ansible all -i 'x.x.x.x,' -m stress -a 'cpu=1 timeout=10'

x.x.x.x | SUCCESS => {
    "bench_config": {
        "cpu": 1,
        "timeout": 10
    },
    "changed": true,
    "exec_cmd": "/usr/local/bin/stress --cpu 1 --timeout 10",
    "rc": 0,
    "stderr": "",
    "stdout": "stress: info: [4553] dispatching hogs: 1 cpu, 0 io, 0 vm, 0 hdd\nstress: info: [4553] successful run completed in 10s",
    "stdout_lines": [
        "stress: info: [4553] dispatching hogs: 1 cpu, 0 io, 0 vm, 0 hdd",
        "stress: info: [4553] successful run completed in 10s"
    ]
}
```

2017-01-17 21:21 UTC, bbyhuy commented
referencing [#19457](https://github.com/ansible/ansible/pull/19457)

2017-01-18 13:18 UTC, gundalow commented
@haad I believe you reviewed the original PR https://github.com/ansible/ansible-modules-extras/pull/3107 Do you have any extra thoughts on this?

2017-01-18 13:24 UTC, gundalow requested changes
needs_revision

If this module gets run multiple times against a system will multiple stress tests be invoked? That feels like something that at a minimum needs making very clear in the documentation, or better yet detected in code

2017-01-18 13:24 UTC, gundalow commented on lib/ansible/modules/benchmarks/stress.py
> +    required: true
Please add the following so the documentation will list the acceptable choices.
`choices: ['benchmark', 'parse']`

2017-01-18 13:24 UTC, gundalow commented on lib/ansible/modules/benchmarks/stress.py
> +     - Total time to run stress for.
Please document units, eg:
`Total time, in seconds, to run stress for`

2017-01-19 17:34 UTC, bbyhuy commented
Added a function to check ps or psgrep for process name. Though, unless a similar function already exists, may be worthwhile adding it as a helper function for AnsibleModules? seems like something that would be useful in other cases.

2017-02-07 13:31 UTC, gundalow approved these changes

2017-06-18 10:11 UTC, krzysztof-magosa approved these changes

2018-02-08 04:11 UTC, maxamillion commented
I think this seems like a better candidate for a reusable role in Galaxy than a module, please help me understand what the module provides that a role would not.

2018-12-17 21:35 UTC, maxamillion commented
needs_info

2019-02-19 23:33 UTC, closed without merging