Add oVirt modules notes to CHANGELOG
ansible/ansible pull request #20401
Opened 2017-01-18 14:17 UTC by machacekondra

##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

CHANGELOG.md

##### ANSIBLE VERSION

```
2.3.0
```

##### SUMMARY

This patch specify new features of oVirt in CHANGELOG

2017-01-18 14:17 UTC, machacekondra commented
@mwperina

2017-01-18 14:23 UTC, mwperina reviewed
We would like emphasize changes in oVirt modules, so that's we have added a new section "Modules Notes". Just listing new modules doesn't provide any higher level overview of changes.

2017-01-18 14:23 UTC, gundalow requested changes
needs_revision

2017-01-18 14:23 UTC, gundalow commented on CHANGELOG.md
> +###Modules Notes:
I like the idea of "Module Notes:` though I wonder if it should go *after* the list of new modules

2017-01-18 14:23 UTC, gundalow commented on CHANGELOG.md
> +  * Add support for data centers, clusters, hosts, storages and networks management.
"storages" doesn't seem right, 
storage locations, storage types?

2017-01-18 14:28 UTC, mykaul reviewed
Did inventory get in for Ansible 2.2, or is it part of the work for 2.3?

2017-01-18 14:28 UTC, mykaul commented on CHANGELOG.md
> +  * Add support for oVirt 4.1 features.
oVirt -> oVirt/RHV

2017-01-18 14:28 UTC, mykaul commented on CHANGELOG.md
> +  * Add support for data centers, clusters, hosts, storages and networks management.
Indeed - storage domains is the correct term.

2017-01-18 14:29 UTC, mwperina commented on CHANGELOG.md
> +###Modules Notes:
I'm not sure if most users don't stop reading at potentially huge list of new modules and will ever get to "Modules notes" section if it's after "New modules" section

2017-01-18 15:30 UTC, gundalow commented on CHANGELOG.md
> +###Modules Notes:
That's a fair point. You can drop my issue.

2017-01-18 19:26 UTC, mwperina commented on CHANGELOG.md
> +  * Add dynamic inventory.
I'd change to "Add dynamic inventories for oVirt resources"

2017-01-18 20:41 UTC, gundalow commented
If once you are app happy please reply with "shipit" and I'll merge this

2017-01-20 12:03 UTC, machacekondra commented on CHANGELOG.md
> +  * Add dynamic inventory.
It's just one. What you mean are Anisble facts modules for most of the resources.

2017-01-23 07:18 UTC, mwperina commented on CHANGELOG.md
> +  * Add dynamic inventory.
Ahh, OK, thanks for explanation

2017-01-23 07:18 UTC, mwperina commented
shipit

2017-01-23 10:58 UTC, gundalow approved these changes

2017-01-23 10:58 UTC, merged

2017-01-23 10:58 UTC, gundalow commented
Merged, thanks