win_msi: Add -type "path" to path parameters
ansible/ansible pull request #20402
Opened 2017-01-18 14:29 UTC by dagwieers

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

win_msi

##### ANSIBLE VERSION

v2.3

##### SUMMARY

I intended to update the documentation, but it appears the website docs
are behind the actual documentation (as the website doesn't show the
default values for booleans).

So I ended up adding the missing -type "path" and use the default $null
value for undefined parameters.

2017-01-26 04:44 UTC, mattclay commented
Closing and re-opening to trigger CI.

2017-01-26 12:23 UTC, dagwieers commented
@nitzmahone @gundalow @dav1x @jhawkesworth @jctanner Can we please get this one merged ?

2017-01-26 13:28 UTC, gundalow requested changes
needs_revision

I've not reviewed the `.ps1` file

2017-01-26 13:28 UTC, gundalow commented on lib/ansible/modules/windows/win_msi.py
> +- Please look into C(win_package) instead, this package will be deprecated in Ansible v2.3.
`M(win_package)` for Module links.

Please update deprecation section of `CHANGELOG.md` for 2.3.

2017-01-27 14:36 UTC, dagwieers commented on lib/ansible/modules/windows/win_msi.py
> +- Please look into C(win_package) instead, this package will be deprecated in Ansible v2.3.
Done.

2017-01-27 14:40 UTC, gundalow approved these changes

2017-01-27 14:41 UTC, gundalow commented
It should be noted my approval is only on the docs, not the code

2017-01-27 23:11 UTC, nitzmahone approved these changes

2017-01-27 23:11 UTC, merged