improve doc for 'lineinfile'
ansible/ansible pull request #20466
Opened 2017-01-19 15:37 UTC by computersalat

especially for 'regexp:' and 'insertafter:'

2017-03-09 03:52 UTC, dharmabumstead requested changes

2017-03-09 03:52 UTC, dharmabumstead commented on lib/ansible/modules/files/lineinfile.py
> +        or insertbefore); only the last line found will be replaced.
This wording is confusing. Did you mean to say "even if you use insertbefore or insertafter, only the last line found will be replaced"? If so, please remove the parenthesis. Thanks.

2017-03-09 13:39 UTC, computersalat commented on lib/ansible/modules/files/lineinfile.py
> +        or insertbefore); only the last line found will be replaced.
If I would meant it this way I would have written it this way ... perhaps ``` even ``` should be replaced with ``` also ```.
Sorry I am not a native English speaker ...

2017-04-11 17:31 UTC, computersalat commented
all-in-all it is somehow awesome how fast this issue is handled  ...

2017-08-16 01:43 UTC, dharmabumstead approved these changes

2018-08-16 17:37 UTC, acozine commented
Hi @computersalat - thanks for contributing back to Ansible via this PR. My apologies for the long wait and thank you for your patience! 

I tested the `lineinfile` module today. You're right, the current documentation doesn't describe the interaction of the  `insertbefore` and `insertafter` parameters with the `regexp` parameter. But your suggested changes to the docs don't quite capture the behavior either. The `regexp` parameter takes priority. For example, if you start with this file: 

```
First line
Second line
Third line
```

and run this task against it:

```
    - name: finds match to regexp, replaces it in current location, ignores insertafter
      lineinfile:
        path: /path/to/file
        state: present
        insertafter: ^Second
        regexp: ^First
        line: "First line replaced"
```

you'll get:

```
First line replaced
Second line
Third line
```

if you run this task instead:

```
    - name: finds no match to regexp, finds match to insertafter, adds line after insertafter match
      lineinfile:
        path: /path/to/file
        state: present
        insertafter: ^Second
        regexp: ^New
        line: "New line after Second line"
```

you'll get:

```
First line
Second line
New line after Second line
Third line
```

I've opened a new PR to update the module docs. Take a look at #44277 and let me know if it addresses your concerns. Thanks!

2018-08-17 10:31 UTC, computersalat commented
@acozine 
sorry, but this is too long ago to remember how this `lineinfile` is working ...
I just tried to improve the docs in the way I found out how it is working ...
... currently I have no time to check this again, sorry
You seem to know this module better than me ... please update the docs (examples) in a way that a noob (like me) is able to understand how it works ... with life examples and meaningful comments.
Thank you

2018-08-17 14:20 UTC, samdoran commented
Superseded by #44277

2018-08-17 14:20 UTC, closed without merging