fixes for redhat_subscription module
ansible/ansible pull request #20548
Opened 2017-01-22 10:25 UTC by evgeni

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
redhat_subscription

##### ANSIBLE VERSION
```
ansible 2.3.0 (devel 61e6e7868c) last updated 2017/01/21 22:31:04 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY
* Fail cleanly when a system does not have subscription-manager installed (like a CentOS machine)
* Document and enforce the need to pass `org_id` when one wants to use an activation key (Fixes: #20542)

before 1:
```
fatal: [vm]: FAILED! => {"changed": false, "cmd": "subscription-manager identity", "failed": true, "msg": "[Errno 2] No such file or directory", "rc": 2}
```

after 1:
```
fatal: [vm]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find subscription-manager. Please ensure it is installed."}
```

before 2:
```
fatal: [vm]: FAILED! => {"changed": false, "cmd": "subscription-manager register --activationkey ak-egolov-test1", "failed": true, "msg": "Error: Must provide --org with activation keys.", "rc": 64, "stderr": "Error: Must provide --org with activation keys.\n", "stdout": "", "stdout_lines": []}
```

after 2:
```
fatal: [vm]: FAILED! => {"changed": false, "failed": true, "msg": "Missing arguments, If registering with an activationkey, must supply Organization ID"}
```

2017-01-25 10:24 UTC, gundalow requested changes
needs_revision

2017-01-25 10:24 UTC, gundalow commented on lib/ansible/modules/packaging/os/redhat_subscription.py
> +        if not (activationkey or org_id or username or password):
You may be able to simplify this buy using the helper functions
`required_one_of`
`mutually_exclusive`
`required_together`

Have a look at existing modules for examples

2017-01-25 10:24 UTC, gundalow commented on lib/ansible/modules/packaging/os/redhat_subscription.py
> +    SUBMAN_CMD = module.get_bin_path('subscription-manager', False)
If you do
`module.get_bin_path('subscription-manager', True)`
then `get_bin_path` will call `self.fail_json` directly, do you can delete the lines
```
if not SUBMAN_CMD:
    module.fail_json(msg="Could not find subscription-manager. Please ensure it is installed.")
```

2017-01-25 10:32 UTC, evgeni commented on lib/ansible/modules/packaging/os/redhat_subscription.py
> +    SUBMAN_CMD = module.get_bin_path('subscription-manager', False)
ack, thanks

2017-01-25 10:53 UTC, gundalow commented
shipit

2017-01-25 10:53 UTC, gundalow approved these changes

2017-01-25 10:54 UTC, gundalow commented
@alikins Can you please review & merge if/when you are happy. Thanks

2017-01-26 04:34 UTC, mattclay commented
Closing and re-opening to trigger CI.

2017-01-26 18:22 UTC, merged