WIP Refactor iosxr_config to make use of network_connection plugin
ansible/ansible pull request #20559
Opened 2017-01-23 09:46 UTC by rcarrillocruz

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

iosxr_config

##### ANSIBLE VERSION

```
ansible 2.3.0 (refactor_ios_config_network_connection 784bd58c4a) last updated 2017/01/23 10:44:35 (GMT +200)
```

##### SUMMARY

Refactor iosxr_config to make use of network_connection plugin

2017-01-23 18:01 UTC, privateip requested changes

2017-01-23 18:01 UTC, privateip commented on lib/ansible/modules/network/iosxr/iosxr_config.py
>  from ansible.module_utils.basic import get_exception
not needed

2017-01-23 18:01 UTC, privateip commented on lib/ansible/modules/network/iosxr/iosxr_config.py
> +        result['changed'] = not module.check_mode
Shouldn't the `changed` flag be based on the return.  If `diff` is empy `changed=False` else `changed=True`?

2017-01-23 18:01 UTC, privateip commented on lib/ansible/modules/network/iosxr/iosxr_config.py
> +        result['changed'] = not module.check_mode
Also, if result should return the diff key with the diff in it to support calling `ansible-playbook` with the `--diff` option

2017-01-23 18:01 UTC, privateip commented on lib/ansible/modules/network/iosxr/iosxr_config.py
> +        load_config(module, commands, not module.check_mode)
`load_config` needs to support the `comment` argument

2017-01-24 14:43 UTC, rcarrillocruz commented on lib/ansible/modules/network/iosxr/iosxr_config.py
>  from ansible.module_utils.basic import get_exception
done

2017-01-24 14:44 UTC, rcarrillocruz commented on lib/ansible/modules/network/iosxr/iosxr_config.py
> +        load_config(module, commands, not module.check_mode)
yep, cargo-culted from module_utils/ios.py which didn't have 'comment', will push a patch to fix it as well.

2017-01-24 22:38 UTC, rcarrillocruz commented on lib/ansible/modules/network/iosxr/iosxr_config.py
> +        result['changed'] = not module.check_mode
done

2017-01-24 22:56 UTC, privateip commented
ship_it

2017-01-25 12:23 UTC, privateip approved these changes

2017-01-25 12:26 UTC, merged