vmware_guest - Add graceful guest shutdown/reboot support
ansible/ansible pull request #20564
Opened 2017-01-23 14:00 UTC by Abdul-Anshad-A

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
devel

##### SUMMARY
Add support for graceful guest shutdown/reboot operations.
fixes issue #3491

2017-01-23 14:00 UTC, Abdul-Anshad-A commented
Migrated from https://github.com/ansible/ansible-modules-extras/pull/3507

2017-01-23 14:07 UTC, nerzhul requested changes

2017-01-23 14:07 UTC, nerzhul commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +                            result = {'changed': True, 'failed': False}
please verify result to ensure it was changed or failed

2017-01-23 15:08 UTC, Abdul-Anshad-A commented
@nerzhul Corrected. I have no idea for the failing check.

2017-01-23 15:58 UTC, Abdul-Anshad-A commented
ready_for_review

2017-01-23 16:21 UTC, nerzhul commented
shipit

2017-01-24 16:49 UTC, dav1x commented
shipit

2017-01-26 18:41 UTC, jctanner commented
bot_status

2017-01-26 19:30 UTC, Abdul-Anshad-A commented
Is there anything else required from my end to merge this change?

2017-01-26 20:56 UTC, jctanner commented
@Abdul-Anshad-A you have a merge commit https://github.com/ansible/ansible/pull/20564/commits/d67c53f7f5e6250f0726fe7deb4d61dff2de3a69

Please rebase your branch: http://docs.ansible.com/ansible/dev_guide/developing_rebasing.html

2017-01-27 07:00 UTC, Abdul-Anshad-A commented
I've re-based my branch.

2017-02-07 08:46 UTC, nerzhul commented
needs_rebase

2017-02-07 15:05 UTC, Abdul-Anshad-A commented
Re-based my branch again.

2017-02-07 15:17 UTC, nerzhul approved these changes
shipit

2017-02-07 15:18 UTC, jctanner commented
bot_status

2017-02-07 15:26 UTC, dav1x commented
shipit

2017-02-07 15:26 UTC, jctanner commented
shipit

2017-02-07 15:33 UTC, merged

2017-02-07 15:33 UTC, jctanner commented
@Abdul-Anshad-A thank you!