Add "clean" option support for pkgng module
ansible/ansible pull request #20575
Opened 2017-01-23 20:16 UTC by dgeo

##### ISSUE TYPE
  - Feature Pull Request

##### COMPONENT NAME
pkgng module

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = /home/dgeo/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY
Runs `pkg clean` which removes cached package files. Possible values:
  * `none` (do not clean, default)
  * `obsolete` (clean only obsolete package files (e.g. old versions))
  * `all` (clean all package files)

Note this is a pure copy of @AMDmi3's original PR to
ansible-modules-extras#2339, adding @bcoca's suggestion : they should be credited here, I just act for this work not to be lost :)

2017-01-24 12:59 UTC, nerzhul requested changes
Nice addition, just a little thing to fix

2017-01-24 12:59 UTC, nerzhul commented on lib/ansible/modules/packaging/os/pkgng.py
> +        version_added: "2.2"
please set it to 2.3

2017-01-24 14:27 UTC, nerzhul commented
needs_revision

2017-02-28 12:31 UTC, dgeo commented
This time it should pass, removed `@`'s and version to 2.3.

2017-07-20 17:37 UTC, AMDmi3 commented
This is obsoleted by #27126, which fixes the conflicts and issue with incorrect default value for clean option.

2018-03-26 09:17 UTC, dgeo commented
I'll let @AMDmi3 manage this in #27126 as he seems more up-to-date :)

2018-03-26 09:17 UTC, closed without merging