Added AIX LV module
ansible/ansible pull request #20574
Opened 2017-01-23 19:23 UTC by adejoux

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME
aix_lvol.py

##### ANSIBLE VERSION

```
ansible 2.3.0 (devel 9958b215d7) last updated 2017/01/23 17:32:04 (GMT +200)
  config file = 
  configured module search path = Default w/o overrides
```

##### SUMMARY

This module is adding support to create, change and delete AIX logical volumes. I started from **lvol** module but AIX LVM management is really different. 

Here a simple playbook using it: 

```
- hosts: adxlpar2
  gather_facts: False
  tasks:
    - name: Create a logical volume of 512M.
      aix_lvol: vg=testvg lv=testlv size=512M
    - name: Create a logical volume of 512M with disks hdisk1 and hdisk2
      aix_lvol: vg=testvg lv=test2lv size=512M pvs="hdisk1,hdisk2"
    - name: Create a logical volume of 512M mirrored.
      aix_lvol: vg=testvg lv=test3lv size=512M copies=2
    - name: Create a logical volume of 1G with a minimum placement policy.
      aix_lvol: vg=testvg lv=test4lv size=1G policy=minimum
    - name: Change logical volume size to 1200 MB.
      aix_lvol: vg=testvg lv=test4lv size=1200M
    - name: delete logical volumes
      aix_lvol: vg=testvg lv={{ item }} state="absent"
      with_items:
        - "testlv"
        - "test2lv"
        - "test3lv"
        - "test4lv"
```

And the output:

```
ansible-playbook  -i hosts playbook.yml

PLAY [adxlpar2] ************************************************************************************************************************************************************

TASK [Create a logical volume of 512M.] ************************************************************************************************************************************
changed: [adxlpar2]

TASK [Create a logical volume of 512M with disks hdisk1 and hdisk2] ********************************************************************************************************
changed: [adxlpar2]

TASK [Create a logical volume of 512M mirrored.] ***************************************************************************************************************************
changed: [adxlpar2]

TASK [Create a logical volume of 1G with a minimum placement policy.] ******************************************************************************************************
changed: [adxlpar2]

TASK [Change logical volume size to 1200 MB.] ******************************************************************************************************************************
changed: [adxlpar2]

TASK [delete logical volumes] **********************************************************************************************************************************************
changed: [adxlpar2] => (item=testlv)
changed: [adxlpar2] => (item=test2lv)
changed: [adxlpar2] => (item=test3lv)
changed: [adxlpar2] => (item=test4lv)

PLAY RECAP *****************************************************************************************************************************************************************
adxlpar2                   : ok=6    changed=6    unreachable=0    failed=0  
```

2017-01-24 16:33 UTC, ryansb requested changes

2017-01-24 16:33 UTC, ryansb commented on lib/ansible/modules/system/aix_lvol.py
> +        test_opt = 'echo '
This doesn't seem to add `--test`, is the above comment out of date, or is this option name wrong?

2017-01-24 16:33 UTC, ryansb commented on lib/ansible/modules/system/aix_lvol.py
> +    msg=''
Instead of setting this out here and doing the `exit_json` out of scope, can you please use `exit_json` right in the various `rc==0` blocks?

2017-01-24 16:33 UTC, ryansb commented on lib/ansible/modules/system/aix_lvol.py
> +
These docs should also include a `RETURNS` section so users can see examples of what the module outputs in different scenarios.

2017-01-24 16:46 UTC, adejoux commented on lib/ansible/modules/system/aix_lvol.py
> +        test_opt = 'echo '
The comment is out of date. I will update.

2017-01-24 17:00 UTC, adejoux commented on lib/ansible/modules/system/aix_lvol.py
> +    msg=''
Ok. I will update.

2017-01-27 13:59 UTC, molekuul commented
I have a question on your code:
In the function "convert_size "
you have two times the
```
if  match.group(1) == "G":
```
but 1 time with the size_factor = 1024
and 1 time with size_factor = 1024*1024
see snippet below 
this doesn't seem right to me?

```
def convert_size(size):
    base_size = None
    size_factor = None

    match = re.search("(\d+)", size)
    if match is not None:
        base_size = int(match.group(1))

    match = re.search("(\w)", size)
    if match is not None:

        if match.group(1) == "G":
            size_factor=1024
        if match.group(1) == "G":
            size_factor=1024*1024

    if base_size is None:
```

kind regards,

Joris Weijters

2017-01-27 16:12 UTC, adejoux commented
@molekuul, thanks it was a mistake on my side. It's for terabytes sizing. I didn't tetsed this one. I fixed it.

2017-01-27 16:21 UTC, ryansb approved these changes

2017-02-01 09:06 UTC, molekuul commented
shipit

2017-02-01 09:37 UTC, tmshn requested changes

2017-02-01 09:37 UTC, tmshn commented on lib/ansible/modules/system/aix_lvol.py
> +        if match.group(1) == "T":
IMO, adding `.upper()` make the parse more robust.
```python
 if match.group(1).upper() == "T":
```

2017-02-01 09:37 UTC, tmshn commented on lib/ansible/modules/system/aix_lvol.py
> +            pvs=dict(type='str')
You can use `type='list'` with `default=list()`.
Later, you can use it like `' '.join(pvs)`.

https://github.com/natefoo/ansible/blob/599eb6115e53fd6fd15770a4c7ef292177d5b888/lib/ansible/module_utils/basic.py#L1525

2017-02-01 09:37 UTC, tmshn commented on lib/ansible/modules/system/aix_lvol.py
> +            copies=dict(type='str'),
Why not using `type='int' default=1`?

2017-02-01 09:37 UTC, tmshn commented on lib/ansible/modules/system/aix_lvol.py
> +            copies=dict(type='str'),
Also, you can do
```python
lv_type=dict(default='jfs2'),
# ...snip...
opts=dict(default=''),
```

2017-02-01 09:37 UTC, tmshn commented on lib/ansible/modules/system/aix_lvol.py
> +                pass
What are these 2 lines doing??

2017-02-01 09:37 UTC, tmshn commented on lib/ansible/modules/system/aix_lvol.py
> +                cmd = "%s %s %sM" % (extendlv_cmd, lv, lv_size - this_lv['size'])
You don't need `test_opt` here?

2017-02-01 11:23 UTC, adejoux commented
@tmshn thanks for your comments. I will implement your recommendations tonight.

2017-02-02 03:00 UTC, tmshn approved these changes

2017-02-02 03:01 UTC, tmshn commented
Looks good, shipit.

2017-02-14 15:25 UTC, mscherer commented on lib/ansible/modules/system/aix_lvol.py
> +            copies=dict(default='1'),
type should be a 'int'

2017-02-14 15:26 UTC, mscherer commented on lib/ansible/modules/system/aix_lvol.py
> +    lslv_cmd = module.get_bin_path("lslv", required=True)
It would IMHO make more sense to move that near the other command, so we can verify both command at the same time.

2017-02-14 20:58 UTC, adejoux commented on lib/ansible/modules/system/aix_lvol.py
> +            copies=dict(default='1'),
Hello, Thanks for the comment.
 If you are talking about the "size" attribute, I made it a string to be able to take in parameter "100m", "100g" or "1T". I think it's making it easier to use for the end user.

2017-02-14 21:12 UTC, adejoux commented on lib/ansible/modules/system/aix_lvol.py
> +    lslv_cmd = module.get_bin_path("lslv", required=True)
I moved lslv_cmd. I was thinking about moving the others "_cmd" commands but deletion and creation commands will never be run together in the same run so I am not sure. Let me know if you want me to move them too.

2017-02-15 14:25 UTC, tmshn commented on lib/ansible/modules/system/aix_lvol.py
> +            copies=dict(default='1'),
No, maybe @mscherer is talking about `copies`.

Do
```
copies=dict(default=1, type='int')
```
rather than
```
copies=dict(default='1')
```

2017-02-15 16:58 UTC, adejoux commented on lib/ansible/modules/system/aix_lvol.py
> +            copies=dict(default='1'),
Thanks. I modified it. :)

2017-02-22 21:46 UTC, adejoux commented
Hello,

I am not familiar with the process. Should I do something to be merged ?

Regards,

Alain

2017-02-23 02:18 UTC, tmshn commented
bot_status

2017-02-23 05:42 UTC, adejoux commented
ready_for_review

2017-02-23 08:03 UTC, adejoux commented
@tmshn thanks again :)

2017-02-23 08:39 UTC, dagwieers commented on lib/ansible/modules/system/aix_lvol.py
> +def convert_size(size):
One way to do this is something like:

```yaml
    unit = size[-1]
    units = list('b', 'k', 'M', 'G', 'T', 'P', 'E', 'Z', 'Y')
    try:
        multiplier = 1024**units.index(unit)
    except ValueError::
        e = get_exception()
        module.fail_json(msg="No valid size unit specified. %s" % e)
```

2017-02-23 08:53 UTC, dagwieers commented on lib/ansible/modules/system/aix_lvol.py
> +    required: false
If parameters are not required, you do not have to add `required: false`. This is the implied value, so it is easier to see what is required if only the required parameters have this option.

2017-02-23 08:55 UTC, dagwieers commented on lib/ansible/modules/system/aix_lvol.py
> +from ansible.module_utils.basic import *
Please put all imports together at the top, and include only the stuff you are using, i.e.
```python
from ansible.module_utils.basic import AnsibleModule
```

2017-02-23 08:56 UTC, dagwieers commented on lib/ansible/modules/system/aix_lvol.py
> +            copies=dict(default='1', type='int'),
If it is an integer, don't add the quotes because that would make it a string.

2017-02-23 08:57 UTC, dagwieers commented on lib/ansible/modules/system/aix_lvol.py
> +            lv_type=dict(default='jfs2'),
Please add `type="str"`, and maybe list the possibilities as `choices=`.

2017-02-23 08:57 UTC, dagwieers commented on lib/ansible/modules/system/aix_lvol.py
> +            vg=dict(required=True),
Please add `type='str'`

2017-02-23 09:01 UTC, dagwieers requested changes

2017-02-23 09:01 UTC, dagwieers commented on lib/ansible/modules/system/aix_lvol.py
> +            size=dict(type='str'),
Please add `type="str"`

2017-02-23 09:01 UTC, dagwieers commented on lib/ansible/modules/system/aix_lvol.py
> +            opts=dict(default=''),
Please add `type="str"`

2017-02-23 09:01 UTC, dagwieers commented on lib/ansible/modules/system/aix_lvol.py
> +                rc, _, err = module.run_command("%s %s -e %s %s" % (test_opt, chlv_cmd, lv_policy, this_lv['name']))
We are not doing anything with stdout and stderr, but on failures it may be the only clue to why it failed.

2017-02-23 09:01 UTC, dagwieers commented on lib/ansible/modules/system/aix_lvol.py
> +            rc, _, err = module.run_command("%s %s -f %s" % (test_opt, rmlv_cmd, this_lv['name']))
We are not doing anything with stdout and stderr, but on failures it may be the only clue to why it failed.

2017-02-23 16:26 UTC, adejoux commented on lib/ansible/modules/system/aix_lvol.py
> +def convert_size(size):
Like it :) I will implement something like that along your others recommendations. thanks

2017-02-27 13:11 UTC, adejoux commented
bot_status

2017-03-10 09:41 UTC, adejoux commented
Hello @dagwieers , Are you waiting on something from me?

Thanks

2017-03-10 13:22 UTC, dagwieers approved these changes

2017-03-13 21:14 UTC, adejoux commented
bot_status

2017-04-04 07:57 UTC, adejoux commented
Hello @dagwieers ,@tmshn, @mscherer,

Not sure what is blocking for the merge now. Could you help me ?

Thanks,

Alain

2017-04-04 10:41 UTC, tmshn commented
It looks every time someone request changes, the `maintainer_shipits` will be reset to 0, and maintainers should approve it by `shipit` comment every time `needs_revision` changed to `False`.
It's a bad behavior of ansibot 😥 ...though I don't know if it's a bug or intended.

Now it looks all green ✅ ; so you can ask for the `shipit` comment again for formerly commented maintainers.

2017-04-04 10:41 UTC, tmshn commented
shipit

2017-04-04 12:11 UTC, dagwieers commented
@tmshn The idea is that changes after a review/shipit needs to be re-reviewed. Because a shipit on old code may not be relevant to the latest changes. So this is to be expected. Obviously, if the changes are rather small, this is a nuisance...

2017-04-04 12:12 UTC, dagwieers commented on lib/ansible/modules/system/aix_lvol.py
> +# (c) 2016, Alain Dejoux ²adejoux@djouxtech.net>
Just noticed a typo in the email-address.

2017-04-04 12:14 UTC, dagwieers commented
I personally don't like the check_mode implementation, but confirm it's hard to do right in this case.

shipit

2017-04-04 13:10 UTC, jctanner commented
@tmshn the count resets after a new commit. If someone requests changes, the "needs revision" label is set, but the "ship it" is not changed.

2017-04-04 13:20 UTC, tmshn commented
@jctanner Ah I see. Actually I see it in action just now! lol
And that sounds appropriate; if something has changed, the changes must pass reviews.
Thanks for the info!

2017-04-04 13:20 UTC, tmshn commented
shipit, finally.

2017-04-10 09:01 UTC, adejoux commented
Hello @dagwieers ,@tmshn, 

I didn't expect than fixing a small typo  in the email address would make me do so many small fixes but at least I think it's ready now. And cleaner ;)

So could you approve it a last time. :)

Thanks,

Alain

2017-04-10 10:00 UTC, dagwieers approved these changes
shipit

2017-04-10 10:01 UTC, dagwieers commented
bot_status

2017-04-10 10:56 UTC, dagwieers commented
shipit

@jctanner Maybe a nice feature for ansibot: accept shipit statements from approved review process.

2017-04-11 01:20 UTC, tmshn commented
shipit

2017-04-18 13:05 UTC, merged