Add bigmon policy module
ansible/ansible pull request #20584
Opened 2017-01-23 22:27 UTC by tedelhourani

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

##### ANSIBLE VERSION

```
ansible 2.1.2.0
```

##### SUMMARY

```

```

2017-01-25 11:30 UTC, gundalow requested changes
needs_revision

1) Please update `CHANGELOG.md` in the root of the repo to add this now module under the 2.3 section

2) You seen to have a number of Dockerfiles in this PR which I don't seem to belong here.

2017-01-25 11:30 UTC, gundalow commented on lib/ansible/modules/network/bigswitch/bigmon_policy.py
> +    choices: ['forward', 'drop', 'flow-gen', 'flow-gen']
"flow-gen" listed twice

2017-01-25 11:30 UTC, gundalow commented on lib/ansible/modules/network/bigswitch/bigmon_policy.py
> +   - name: policy to aggregate filter and deliver data center (DC) 1 traffic
Looks like you've got 3 characters of whitespace before all the examples, please remove.

2017-01-25 20:25 UTC, tedelhourani commented
Changes made as requested, Thank you!

2017-01-25 22:33 UTC, gundalow requested changes
needs_revision

2017-01-25 22:33 UTC, gundalow commented on CHANGELOG.md
> +- bigswitch:
Alphabetical order please :)

2017-01-25 22:33 UTC, gundalow commented on lib/ansible/modules/network/bigswitch/bigmon_policy.py
> +            access_token=dict(aliases=['BIGSWITCH_ACCESS_TOKEN'], no_log=True)
You've not specified this alias in the documentation. 

If you meant to read from the environment then you need to read from the the standard python environment object.

2017-01-25 23:04 UTC, tedelhourani commented on lib/ansible/modules/network/bigswitch/bigmon_policy.py
> +            access_token=dict(aliases=['BIGSWITCH_ACCESS_TOKEN'], no_log=True)
I added the alias to the doc.

Yes I am giving the option to either give the access_token as input or to read it from the environment with:
    try:
        access_token = module.params['access_token'] or os.environ['BIGSWITCH_ACCESS_TOKEN']
    except KeyError:
        e = get_exception()
        module.fail_json(msg='Unable to load %s' % e.message)

2017-01-26 19:10 UTC, tedelhourani commented
Rebase done!

2017-01-27 14:47 UTC, gundalow commented on lib/ansible/modules/network/bigswitch/bigmon_policy.py
> +            access_token=dict(aliases=['BIGSWITCH_ACCESS_TOKEN'], no_log=True)
That code looks similar to `./bigswitch/bigmon_chain.py`, so that should be fine

2017-01-27 14:52 UTC, gundalow requested changes
No need to specify the alias
I realise that the other bigswitch modules will need these changes. Once you've updated here and tested them could you please apply them in a separate PR to the existing modules?

2017-01-27 14:52 UTC, gundalow commented on lib/ansible/modules/network/bigswitch/bigmon_policy.py
> +    aliases: ['BIGSWITCH_ACCESS_TOKEN']
Please remove this line

2017-01-27 14:52 UTC, gundalow commented on lib/ansible/modules/network/bigswitch/bigmon_policy.py
> +     - Bigmon access token.
`Bigmon access token. If this isn't set the the environment variable C(BIGSWITCH_ACCESS_TOKEN) is used.`

2017-01-27 14:52 UTC, gundalow commented on lib/ansible/modules/network/bigswitch/bigmon_policy.py
> +            access_token=dict(aliases=['BIGSWITCH_ACCESS_TOKEN'], no_log=True)
`access_token=dict(type='str', no_log=True)`

2017-01-27 16:57 UTC, tedelhourani commented
Thanks for the comments! all makes sense. 
Changes are made and will open a new PR later for the other module, to similarly fix the access_token.

2017-01-28 18:06 UTC, gundalow requested changes
Just two minor things then I think we are good

2017-01-28 18:06 UTC, gundalow commented on lib/ansible/modules/network/bigswitch/bigmon_policy.py
> +     - description of policy.
`Description` (capital letter)

2017-01-28 18:06 UTC, gundalow commented on lib/ansible/modules/network/bigswitch/bigmon_policy.py
> +  - An environment variable can be used, BIGSWITCH_ACCESS_TOKEN.
You can delete this `notes:` section as you've documented it under "access_token:"

2017-01-28 18:06 UTC, gundalow commented on lib/ansible/modules/network/bigswitch/bigmon_policy.py
> +            validate_certs=dict(type='bool', default='False'),
` default='True'`

2017-01-29 06:23 UTC, tedelhourani commented
Made the changes, tks!

2017-01-29 15:31 UTC, gundalow approved these changes

2017-01-29 15:31 UTC, merged