Ovirt hosts
ansible/ansible pull request #20607
Opened 2017-01-24 17:06 UTC by machacekondra

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

ovirt_hosts

##### ANSIBLE VERSION

```
2.3.0
```

##### SUMMARY

This PR  primarly fixes issue https://github.com/ansible/ansible/issues/20549.
In addition, it add ```reinstall``` state to ```ovirt_hosts``` module, so users can easily reinstall after boot parameters change. Also adds ```override_display``` and making sure we are waiting before running a first poll request to entity state.

2017-01-24 17:10 UTC, machacekondra commented
@mwperina

2017-01-24 17:30 UTC, machacekondra commented
@ryansb

2017-01-24 17:30 UTC, machacekondra commented
shipit

2017-01-24 21:44 UTC, mwperina requested changes

2017-01-24 21:44 UTC, mwperina commented on lib/ansible/modules/cloud/ovirt/ovirt_hosts.py
> +            - "Override the display address of all VMs on this host by specified address."
by specified -> with specified

2017-01-25 11:55 UTC, mykaul commented on lib/ansible/module_utils/ovirt.py
> +            # Sleep for `poll_interval` seconds if nor of the conditions apply:
nor -> none

2017-01-25 14:17 UTC, ryansb approved these changes

2017-01-25 14:17 UTC, merged