Add domain_id parameter to openstack os_group
ansible/ansible pull request #20609
Opened 2017-01-24 18:03 UTC by cmurphy

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
cloud/openstack/os_group

##### ANSIBLE VERSION
```
ansible 2.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible']
```

##### SUMMARY
Previously, the os_group module did not have any way to specify under
which domain a group should be created. This meant that a group could
only be created for the default domain. The keystone API supports the
domain_id parameter for group creation[1] as does the shade library[2]
so this patch adds the support in the ansible module.

[1] http://developer.openstack.org/api-ref/identity/v3/index.html?expanded=create-group-detail#create-group
[2] http://docs.openstack.org/infra/shade/usage.html#shade.OperatorCloud.create_group

2017-02-22 22:29 UTC, rcarrillocruz requested changes

2017-02-22 22:29 UTC, rcarrillocruz commented on lib/ansible/modules/cloud/openstack/os_group.py
> +     default: None
please add the  version added:

version_added: "2.3"

Something like https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/openstack/os_subnet.py#L77 as an example.

Other than that, change lgtm, I will merge when amended.

2017-02-23 08:29 UTC, cmurphy commented on lib/ansible/modules/cloud/openstack/os_group.py
> +     default: None
Thanks, done

2017-02-23 09:56 UTC, rcarrillocruz approved these changes

2017-02-23 09:57 UTC, merged