Feature #2731: added postgres import and dump
ansible/ansible pull request #20627
Opened 2017-01-25 07:48 UTC by joshmoore

Originally filed as gh-2752 by @autotune. 

---

Ended up just recreating the branch with the specific modified file on there per #2751. The issue template has been re-posted below as well:

Issue Type:

Can you help us out in labelling this by telling us what kind of ticket this this? You can say:
Feature Pull Request

Ansible Version: 2.1.0

Ansible Configuration:

Standard config.

Environment:

[autotune@ansibledev ansible-modules-core]$ cat /etc/redhat-release
CentOS Linux release 7.1.1503 (Core)

Summary:

This module adds an import and dump state to the core postgresql_db Module that supports .tar, .gz, .xz, .bz, and a standard .sql file:

```

---
- hosts: local
  tasks:
- name:
  2731_postgresql_db: name=ansitest login_user=postgres state=dump login_host=127.0.0.1 target=~/dev/features/2731/ansitest.sql.xz
```

Steps To Reproduce:

Run the above playbook with a database that exists in postgres called "ansitest" and do a dump. Run the same playbook with "state=import" and change name to an new, empty database, and import.

Expected Results:

Either a new dump created in the form of a compressed file or an imported database.

Actual Results:

See above.

2017-01-25 07:48 UTC, joshmoore commented
Migrated from https://github.com/ansible/ansible-modules-core/pull/4614

2017-01-25 08:46 UTC, nerzhul requested changes

2017-01-25 08:46 UTC, nerzhul commented on lib/ansible/modules/database/postgresql/postgresql_db.py
> +    version_added: "2.2"
please fix version_added to 2.3

2017-01-25 10:12 UTC, gundalow requested changes
needs_revision

You seem to alternate between the terms backup, import and restore. Picking two will make this easier for people to follow.

2017-01-25 10:12 UTC, gundalow commented on lib/ansible/modules/database/postgresql/postgresql_db.py
>        - The database state
Please add a comment on the `description` to say dump and import where added in 2.3

Also is it import or restore?

2017-01-25 10:12 UTC, gundalow commented on lib/ansible/modules/database/postgresql/postgresql_db.py
> +    version_added: "2.2"
`"2.3"`

2017-01-25 10:12 UTC, gundalow commented on lib/ansible/modules/database/postgresql/postgresql_db.py
> +    choices: [ "present", "absent", "dump", "restore" ]
Is it import or restore?

2017-01-25 10:12 UTC, gundalow commented on lib/ansible/modules/database/postgresql/postgresql_db.py
> +    backup:
What are these three lines for?
I don't see any `backup` option, also the formatting is wrong.

2017-01-25 10:12 UTC, gundalow commented on lib/ansible/modules/database/postgresql/postgresql_db.py
> +      - Restore from a destination. See backup for supported options
I don't see a backup option in the code

2017-01-25 10:12 UTC, gundalow commented on lib/ansible/modules/database/postgresql/postgresql_db.py
> +      - File to back up or restore from.
You seem to alternate between the terms backup, import and restore. Picking two will make this easier for people to follow.

2017-01-25 10:15 UTC, gundalow commented
@autotune Could you please give this a look. Thanks in advance.

2017-01-31 16:00 UTC, joshmoore commented on lib/ansible/modules/database/postgresql/postgresql_db.py
> +      - File to back up or restore from.
Agreed. I didn't even realize the discrepancy when taking over https://github.com/ansible/ansible-modules-core/pull/2752

2017-01-31 16:02 UTC, joshmoore commented on lib/ansible/modules/database/postgresql/postgresql_db.py
> +      - Restore from a destination. See backup for supported options
I'm inclined to think these were originally intended as part of the description. I'll migrate.

2017-01-31 16:07 UTC, joshmoore commented
I think the latest push addresses all the comments made. Thanks, all.

2017-01-31 19:22 UTC, gundalow approved these changes
shipit

2017-01-31 19:24 UTC, gundalow commented
Looks like there are some pep8 tidiups needed (reported by Shippable)

```
2017-01-31 16:45:00 Run command: pep8 --max-line-length 160 --config /dev/null --ignore E123,E124,E127,E128,E201,E202,E203,E211,E221,E222,E225,E226,E227,E228,E231,E241,E251,E261,E262,E265,E266,E301,E302,E303,E402,E502,E713,E731,W391,W503 lib/ansible/modules/database/postgresql/postgresql_db.py
2017-01-31 16:45:00 ERROR: PEP 8: lib/ansible/modules/database/postgresql/postgresql_db.py:262:13: E121 continuation line under-indented for hanging indent (legacy)
2017-01-31 16:45:00 ERROR: PEP 8: lib/ansible/modules/database/postgresql/postgresql_db.py:308:13: E121 continuation line under-indented for hanging indent (legacy)
2017-01-31 16:45:00 PEP 8: There were 3 different legacy issues found (32 total):
2017-01-31 16:45:00 PEP 8: Count Code Message
2017-01-31 16:45:00 PEP 8:    27 E111 indentation is not a multiple of four
2017-01-31 16:45:00 PEP 8:     2 E129 visually indented line with same indent as next logical line
2017-01-31 16:45:00 PEP 8:     3 E501 line too long (NNN > NNN characters)
2017-01-31 16:45:00 ERROR: PEP 8: There are 2 issues which need to be resolved.
```

2017-02-01 06:39 UTC, nerzhul reviewed
please fix the last pep8 reports

2017-02-14 16:47 UTC, joshmoore commented
Rebase removed & pep8 fixed.

2017-02-14 18:46 UTC, joshmoore commented
ready_for_review

2017-02-20 16:40 UTC, joshmoore commented
ready_for_review

2017-02-27 13:49 UTC, joshmoore commented
bot_status

2017-02-27 14:01 UTC, joshmoore commented
(I'm unclear why `needs_revision` was added)

2017-03-06 10:43 UTC, joshmoore commented
@gundalow @nerzhul, sorry for the ping, but could either of you clarify? Cheers.

2017-03-06 11:04 UTC, nerzhul commented
@joshmoore CI is happy it's good for me

2017-03-13 12:17 UTC, joshmoore commented
@gundalow: any thoughts?

2017-03-13 13:50 UTC, gundalow commented
Maybe add another ready_for_review

After that @nerzhul needs to give change his review

2017-03-13 13:51 UTC, gundalow commented
Also this is a feature request, We've hit feature freeze on 2.3, so this will have to wait till we've hit RC1 (Friday) before it gets merged into `devel` which will be `2.4` at that point

2017-03-14 07:10 UTC, joshmoore commented
ready_for_review

2017-03-21 14:58 UTC, joshmoore commented
@nerzhul : you ok to give a green review based on https://github.com/ansible/ansible/pull/20627#issuecomment-284366643 ? (Think it's a GitHub bug since the commits that you commented on have now been force pushed away)

2017-03-21 15:01 UTC, nerzhul approved these changes

2017-03-21 15:02 UTC, nerzhul commented
It's okay for me but your change cannot be merged for 2.3, maybe it should be changed to 2.4 @gundalow ?

2017-03-31 20:12 UTC, gundalow commented on lib/ansible/modules/database/postgresql/postgresql_db.py
> +    version_added: "2.3"
`"2.4"`

2017-04-07 11:14 UTC, joshmoore commented
ready_for_review

2017-04-07 16:19 UTC, mattclay commented
Closing and re-opening to trigger CI.

2017-04-24 06:51 UTC, joshmoore commented
ready_for_review

2017-04-24 07:38 UTC, gundalow approved these changes

2017-04-24 07:59 UTC, nerzhul commented
shipit

2017-05-08 16:33 UTC, pchauncey commented
Might just be me/user error, but I'm getting this on both ansible 2.3 and ansible 2.4: 

`fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "db": "foo", 
            "encoding": "", 
            "lc_collate": "", 
            "lc_ctype": "", 
            "login_host": "127.0.0.1", 
            "login_password": "", 
            "login_unix_socket": "", 
            "login_user": "postgres", 
            "name": "foo", 
            "owner": "", 
            "port": 5432, 
            "ssl_mode": "prefer", 
            "ssl_rootcert": null, 
            "state": "dump", 
            "target": "/tmp/foo.sql.gz", 
            "template": ""
        }
    }, 
    "msg": "db_dump() got an unexpected keyword argument 'sslmode'"
}


ansible 2.4.0 (testing_PR20627 b4bffa6d8a) last updated 2017/05/08 10:23:49 (GMT -500)
postgresql-9.5.6-1.fc25.x86_64
`
I've tried with ssl_mode=disable with the same results

2017-05-09 06:49 UTC, joshmoore commented
I've reproduced in an integration test:

```
TASK [postgresql : Dump the db] ************************************************
fatal: [testhost]: FAILED! => {"changed": false, "failed": true, "msg": "db_dump() got an unexpected keyword argument 'sslmode'"}
	to retry, use: --limit @/root/ansible/test/integration/postgresql-y_LlPW.retry

```

I'll push a fix shortly.

2017-05-09 19:42 UTC, joshmoore commented
ready_for_review

Note: there are a couple of changes that I could see adding on top of this even for 2.4 but would prefer to get this in first since it's been something of a struggle with the repo migration and both the 2.2 and 2.3 releases. Features to follow include:

 * `-Fd` and `-j $CPUS` to allow saving a database in parallel
 * support for `login_password`

2017-05-09 20:16 UTC, pchauncey commented
Now it appears that the dump and restore actions aren't honoring login_user:

The "present" action works:
```
ansible localhost -m postgresql_db -a "name=foo login_host=127.0.0.1 login_user=postgres state=present" 
localhost | SUCCESS => {
    "changed": false, 
    "db": "foo"
}
```

But the "dump" action doesn't, and it's trying to use my UID instead of postgres:
```
ansible localhost -m postgresql_db -a "name=foo target=/tmp/foo.sql login_host=127.0.0.1 login_user=postgres state=dump" -vvv
localhost | FAILED! => {
    "changed": false, 
    "cmd": "/usr/bin/psql --dbname=foo < /tmp/foo.sql", 
    "failed": true, 
    "invocation": {
        "module_args": {
            "db": "foo", 
            "encoding": "", 
            "lc_collate": "", 
            "lc_ctype": "", 
            "login_host": "127.0.0.1", 
            "login_password": "", 
            "login_unix_socket": "", 
            "login_user": "postgres", 
            "name": "foo", 
            "owner": "", 
            "port": 5432, 
            "ssl_mode": "prefer", 
            "ssl_rootcert": null, 
            "state": "restore", 
            "target": "/tmp/foo.sql", 
            "template": ""
        }
    }, 
    "msg": "psql: FATAL:  role \"patrick\" does not exist\n", 
    "rc": 2, 
    "stdout": "", 
    "stdout_lines": []
}

```

2017-05-10 09:28 UTC, joshmoore commented
Thanks for the testing @pchauncey. Good you give https://github.com/ansible/ansible/pull/20627/commits/0939ccab45a96422a5f328110d253ebd4900f22a a try?

2017-05-10 13:34 UTC, pchauncey commented
Hi @joshmoore, thanks for the quick updates, it is using the postgres user now, but:  Still getting an error here from the same ansible command.  I tried a playbook as well, but both result in the error below:

```
$ ansible localhost -m postgresql_db -a "name=foo target=/tmp/foo.sql login_host=127.0.0.1 login_user=postgres state=dump" -vvv
localhost | FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "db": "foo", 
            "encoding": "", 
            "lc_collate": "", 
            "lc_ctype": "", 
            "login_host": "127.0.0.1", 
            "login_password": "", 
            "login_unix_socket": "", 
            "login_user": "postgres", 
            "name": "foo", 
            "owner": "", 
            "port": 5432, 
            "ssl_mode": "prefer", 
            "ssl_rootcert": null, 
            "state": "dump", 
            "target": "/tmp/foo.sql", 
            "template": ""
        }
    }, 
    "msg": "Database query failed: putenv() argument 2 must be string, not None"
}
$ ansible --version
ansible 2.4.0 (pr20627 f4c49664f0) last updated 2017/05/10 08:17:28 (GMT -500)
```

2017-05-10 16:02 UTC, joshmoore commented
Hi @pchauncey. What this really needs is a number of tests per each combination of user/password, etc. In lieu of that, thanks again for hammering on it!

2017-05-10 17:01 UTC, pchauncey commented
Here are a couple of quick fixes:

1. In db_dump() Host wasn't being passed to pg_dump if db name was supplied (elif should be if)
2. Quotes around host and port were breaking things for pg_dump if specified
3. In db_restore() cmd was only getting the first flag passed (flag[0])

How do these look to you?

```diff
--- a/lib/ansible/modules/database/postgresql/postgresql_db.py
+++ b/lib/ansible/modules/database/postgresql/postgresql_db.py
@@ -241,12 +241,12 @@ def db_dump(module, target,
     flags = ''
     if db:
         flags += ' {0}'.format(pipes.quote(db))
-    elif host:
-        flags += ' --host={0}'.format(pipes.quote(host))
-        if port:
-            flags += ' --port={0}'.format(pipes.quote(port))
+    if host:
+        flags += ' --host={0}'.format(host)
+    if port:
+        flags += ' --port={0}'.format(port)
     if user:
-        flags += ' --username={0}'.format(pipes.quote(user))
+        flags += ' --username={0}'.format(user)
 
     cmd = module.get_bin_path('pg_dump', True)
     comp_prog_path = None
@@ -311,7 +311,8 @@ def db_restore(module, target,
     elif os.path.splitext(target)[-1] == '.xz':
         comp_prog_path = module.get_bin_path('xzcat', True)
 
-    cmd += flags[0]
+    for flag in flags:
+        cmd += flag
 
     if comp_prog_path:
         p1 = subprocess.Popen([comp_prog_path, target], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
```

2017-05-11 08:17 UTC, joshmoore commented
Thanks for the fixes, @pchauncey. They certainly pointed to further issues (both in the code and in the tests). I've applied the patch with your info and have pusedh a few commits on top of it. Looking forward to more feedback.

2017-05-11 13:06 UTC, pchauncey approved these changes
shipit

2017-05-11 13:06 UTC, pchauncey commented
Looks great.  Thanks for all of the additional changes!

2017-05-11 16:13 UTC, joshmoore commented
Gladly! :) Eventually I could use some info on the minimum supported postgres version and similar or perhaps just on how to scope a feature to a given version in order to introduce the `-j` option. But definitely looking forward to calling this PR done first.

2017-05-19 06:32 UTC, joshmoore commented
Anything else need from me here?

2017-05-19 11:47 UTC, pchauncey commented
bot_status

2017-05-22 07:09 UTC, joshmoore commented
Should I close & re-open or will that put us back at square one?

2017-05-22 10:03 UTC, gundalow commented
I've clicked "rebuild" on shippable, which should remove the `stale_ci` label.

If people are happy after than I think we can merge.

2017-06-05 18:58 UTC, joshmoore commented
bot_status

2017-06-12 05:57 UTC, joshmoore commented
Sorry, @gundalow, but how do I go about making sure everyone is happy?

2017-06-17 07:59 UTC, gundalow commented
Closing and reopening to trigger CI

2017-06-17 08:02 UTC, gundalow approved these changes

2017-06-17 08:03 UTC, gundalow commented
@matburt @pchaunceyn are you happy with this?

2017-06-17 08:04 UTC, gundalow commented
I'll merge this next week if I don't hear anything otherwise.

2017-07-04 11:51 UTC, joshmoore commented
Friendly reminder.

2017-07-04 11:56 UTC, pchauncey commented
Looks good to me

2017-07-10 07:05 UTC, gundalow approved these changes

2017-07-10 07:05 UTC, merged

2017-07-10 07:06 UTC, gundalow commented
Thanks for the PR and reviews.
As this is new functionality this has been merged into `devel` and will be released in `2.4.0`

2017-08-21 17:05 UTC, autotune commented
@joshmoore additional thanks from me as well for helping drive this through to completion.