Allow iam_cert to be renamed or moved without needing to specify cert…
ansible/ansible pull request #20622
Opened 2017-01-25 04:34 UTC by ProjectRice

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
iam_cert

##### ANSIBLE VERSION
```
ansible 2.2.0.0
```

##### SUMMARY
Currently although cert and key data are not actually used in renaming/moving iam_certs, they are still required.  Otherwise the module will fail when trying to read the cert data that defaults to None.

This change means that if new_name and/or new_path are specified, cert, key and cert_chain arguments will be ignored.

2017-01-25 11:56 UTC, gundalow requested changes
needs_revision

2017-01-25 11:56 UTC, gundalow commented on lib/ansible/modules/cloud/amazon/iam_cert.py
> +	  - When present, cert, key and cert_chain values will be ignored.
Indentation doesn't look right here.

2017-01-25 11:56 UTC, gundalow commented on lib/ansible/modules/cloud/amazon/iam_cert.py
> +	  - When present, cert, key and cert_chain values will be ignored.
Indentation doesn't look right here.

2017-01-30 04:19 UTC, ProjectRice commented
Sorry guys.. I had to run due to wife's impending child birth and submitted rather quickly.

2017-01-30 04:46 UTC, ProjectRice commented
needs_review

2017-01-30 09:09 UTC, ProjectRice commented
Hopefully all is in order now...

2017-01-30 09:21 UTC, ProjectRice commented on lib/ansible/modules/cloud/amazon/iam_cert.py
> +	  - When present, cert, key and cert_chain values will be ignored.
Fixed and rebased

2017-01-30 09:21 UTC, ProjectRice commented on lib/ansible/modules/cloud/amazon/iam_cert.py
> +	  - When present, cert, key and cert_chain values will be ignored.
Thanks. Fixed and rebased

2017-01-30 12:09 UTC, gundalow approved these changes

2017-01-30 12:10 UTC, gundalow commented
@defionscode @Etherdaemon Could you please take a look at this PR?
Thanks in advance.

2017-03-01 05:36 UTC, willthames commented
I don't really like silently ignoring parameters.

Can we make `new_path` and `new_name` mutually exclusive with `key` and `cert` - there's already an empty `mutually_exclusive` array, it would just need to be:

```
mutually_exclusive = [
  [ 'new_path', 'key'],
  [ 'new_name', 'cert'],
  [ 'new_path', 'key'],
  [ 'new_name', 'cert'],
]
```

2017-03-01 21:29 UTC, ProjectRice commented
Thanks Will.  Did you mean to reverse the `new_path` and `new_name` or `key` and `cert` values in the 2nd instance?

eg.
```
mutually_exclusive = [
  [ 'new_path', 'key'],
  [ 'new_path', 'cert'],
  [ 'new_name', 'key'],
  [ 'new_name', 'cert'],
]
```

or
```
mutually_exclusive = [
  [ 'new_path', 'key'],
  [ 'new_name', 'cert'],
  [ 'new_path', 'cert'],
  [ 'new_name', 'key'],
]
```

2017-03-01 23:21 UTC, willthames commented
@ProjectRice good catch - the first of your two alternatives looks best to me

2017-03-02 00:51 UTC, ProjectRice commented
Ah crap..  that's what I get for testing the github desktop client to do this after a rebase...

2017-03-02 01:03 UTC, ProjectRice commented
Take 2

2017-03-02 01:11 UTC, ProjectRice commented
I'm guessing all the incidental c:* tags need to be removed manually given the dodgy merge I reverted.

2017-03-06 21:21 UTC, s-hertel commented
shipit

2017-03-06 22:56 UTC, ProjectRice commented
Is it too late to push a couple of other changes for a few things I noticed last night that are unrelated to my original PR?

eg..   chain is assigned as a variable but never used.
key=cert=chain=None

If this was changed to cert_chain the reading of the cert_chain value could be moved inside the if statement.  Something like below, and cert_chain could also be added to the mutually exclusive definition.
```
if state == 'present' and not new_name and not new_path:
        cert = open(module.params.get('cert'), 'r').read().rstrip()
        key = open(module.params.get('key'), 'r').read().rstrip()
        cert_chain = module.params.get('cert_chain')
        if cert_chain is not None:
            cert_chain = open(module.params.get('cert_chain'), 'r').read()
    else:
        key=cert=cert_chain=None
```

2017-03-07 13:41 UTC, s-hertel commented
Go ahead! I'll re-shipit when you're done.

2017-03-08 14:05 UTC, gundalow commented on lib/ansible/modules/cloud/amazon/iam_cert.py
>      aliases: []
Please remove the empty `aliases: []` lines and the `required: false`

2017-03-08 20:32 UTC, ProjectRice commented on lib/ansible/modules/cloud/amazon/iam_cert.py
>      aliases: []
Will do.. although I didn't add them :)

2017-03-08 21:06 UTC, ProjectRice commented on lib/ansible/modules/cloud/amazon/iam_cert.py
>      aliases: []
Doneski...  Also cleaned up the Defaults that were not required.

2017-05-09 13:09 UTC, s-hertel commented
@ProjectRice Can you rebase? Sorry for not getting back to this sooner.

2017-05-09 20:52 UTC, ProjectRice commented
Hi @s-hertel that should be done however I had to it via the gui so couldn't squash/amend the commit sorry.  I won't be able to do this until later or tomorrow.

Can I ask what the current thoughts are re pep8 and other standards when you're making a PR like mine?  If they're existing issues are we best to fix them in order to help speed up the process?

2017-05-09 21:31 UTC, ProjectRice commented
Is it possible to revert a commit or avoid the merge issues (eg only commit the 1 file) via the online editor/merge conflict resolution pages.

2017-05-10 07:17 UTC, ProjectRice commented on lib/ansible/modules/cloud/amazon/iam_cert.py
>      aliases: []
Unfortunately I had to re-add one of the "required: false" lines to fix a merge conflict.

2017-06-22 21:32 UTC, ProjectRice commented
Hi @s-hertel and co.

While we're making minor changes to get this ready.... We've also just discovered a small issue with dup_chek.

I believe cert names are not case sensitive, however the comparison in dup_check will cause certs with differing cases to be treated as unique.  https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_iam-limits.html

I'm looking at this now and will try to update shortly.

2017-06-23 01:34 UTC, willthames commented on lib/ansible/modules/cloud/amazon/iam_cert.py
> +                        certificate_body \
most of these line continuations aren't necessary - should probably run flake8 over this.

2017-06-23 01:34 UTC, willthames commented on lib/ansible/modules/cloud/amazon/iam_cert.py
> +    orig_cert_names = [ctb['server_certificate_name'] for ctb in \
This is nicer wrapped without line continuation markers:

```
orig_cert_names = [ctb['server_certificate_name'] for ctb in 
                   iam.get_all_server_certs().list_server_certificates_result.server_certificate_metadata_list]
```

2017-06-23 01:36 UTC, willthames commented on lib/ansible/modules/cloud/amazon/iam_cert.py
> +        state=dict(default=None, required=True, choices=['present', 'absent']),
`default=None` is the default (can be removed from the others too, along with `required=False`, if desired)

2017-06-23 01:37 UTC, ProjectRice commented on lib/ansible/modules/cloud/amazon/iam_cert.py
> +                        certificate_body \
Lol.  I actually changed some of this stuff but didn't push it since it was already there because and I thought less change was better.

2017-06-23 01:37 UTC, ProjectRice commented on lib/ansible/modules/cloud/amazon/iam_cert.py
> +    orig_cert_names = [ctb['server_certificate_name'] for ctb in \
See my other comment 👍   Happy to fix while I'm here though

2017-06-23 01:37 UTC, willthames reviewed
This seems mostly fine to me. The key thing is to fix the pep8 check, but there is some horrible line breaking going on too, which we might as well eliminate while in the area.

2017-06-23 02:37 UTC, ProjectRice commented on lib/ansible/modules/cloud/amazon/iam_cert.py
> +        state=dict(default=None, required=True, choices=['present', 'absent']),
I'm assuming type='str' is possibly also a default?

Is it preferred to have at least something defined in the parameter dict?  Or just leave it empty if there is nothing required?

2017-06-23 04:19 UTC, ProjectRice commented
Hi @s-hertel, @willthames @gundalow  and @ryansb,
I think this should be ready to go 👍

2017-06-23 04:45 UTC, willthames commented on lib/ansible/modules/cloud/amazon/iam_cert.py
> +    opath = iam.get_server_certificate(name).get_server_certificate_result.\
We're making a lot of unnecessary API calls and having a lot of horribly long lines - we can cure both at once:

```
    certificate =  iam.get_server_certificate(name).get_server_certificate_result.server_certificate
    ocert = certificate.certificate_body
    ocert_id = certificate.server_certificate_metadata.server_certificate_id
    ...
```

2017-06-23 04:46 UTC, willthames commented
Sorry, your pep8 fixes exposed some more horrible line wrapping. I know you didn't introduce them, but it's an easy win to fix it.

2017-06-23 04:48 UTC, willthames commented on lib/ansible/modules/cloud/amazon/iam_cert.py
> +from ansible.module_utils.basic import *
should probably address this to at some point. But I can always fix this after.

Usually 

```
from ansible.module_utils.basic import AnsibleModule
from ansible.module_utils.ec2 import ec2_argument_spec, get_aws_connection_info, connect_to_aws
```
suffices but flake8 will tell you if you've missed anything.

2017-06-23 05:02 UTC, ProjectRice commented on lib/ansible/modules/cloud/amazon/iam_cert.py
> +from ansible.module_utils.basic import *
I've updated since I'm here.

2017-06-23 05:07 UTC, ProjectRice commented on lib/ansible/modules/cloud/amazon/iam_cert.py
> +    opath = iam.get_server_certificate(name).get_server_certificate_result.\
Doneski

2017-06-23 05:32 UTC, merged

2017-06-23 05:32 UTC, willthames commented
Merged, thanks for all the tweaks.

2017-06-26 11:07 UTC, ProjectRice commented
Unfortunately I realised today that this had introduced a bug.

Fix PR here.. https://github.com/ansible/ansible/pull/26087