Reminder that lookup(‘file’) can be used
ansible/ansible pull request #20649
Opened 2017-01-25 16:39 UTC by craigfrancis

Sometimes the block of text does not easily fit into a playbook, so this acts as a reminder (or a prompt for anyone who hasn't used this before) that the content could be stored in an separate file.

I've also included `backup: yes` as I think this is a good example of where a backup might be needed.

##### ISSUE TYPE

 - Feature Pull Request
 - New Module Pull Request
 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME

##### ANSIBLE VERSION

```

```

##### SUMMARY

```

```

2017-01-25 17:12 UTC, gundalow commented on lib/ansible/modules/files/blockinfile.py
> +    block: "{{ lookup(‘file’, ‘./local/ssh_config’) }}"
I think you've got an dodgy quote in that line, I think you need:
`block: "{{ lookup(‘file', './local/ssh_config') }}"`

That should fix the Shippable error

2017-01-25 17:13 UTC, gundalow requested changes
needs_revision

2017-01-25 17:29 UTC, craigfrancis commented
Good point, thanks @gundalow ... hopefully that change will fix it.

2017-01-26 18:02 UTC, mattclay commented on lib/ansible/modules/files/blockinfile.py
> +– name: insert/update configuration using a local file
The `–` isn't an ASCII `-`, which is causing CI failures.

2017-01-26 18:28 UTC, craigfrancis commented
Thanks @mattclay... not sure why I decided to copy/paste from a WordPress comment, should have just kept with the original source code.

2017-02-07 13:57 UTC, gundalow approved these changes

2017-02-07 13:57 UTC, merged

2017-02-07 13:57 UTC, gundalow commented
Merged, thanks