Panos interface
ansible/ansible pull request #20659
Opened 2017-01-25 19:43 UTC by ivanbojer

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
panos_interface

##### ANSIBLE VERSION

```
ansible 2.1.0.0 
config file = 
configured module search path = Default w/o overrides
```

##### SUMMARY
New panos module that allows Firewall interface configuration. Configure data-port (DP) network interface for DHCP.

2017-01-30 23:14 UTC, ivanbojer commented
ready_for_review

2017-02-11 16:03 UTC, gundalow requested changes

2017-02-11 16:03 UTC, gundalow commented on lib/ansible/modules/network/panos/panos_interface.py
> +            - IP address (or hostname) of PAN-OS device
Capital letters & full stops please

2017-02-11 16:03 UTC, gundalow commented on lib/ansible/modules/network/panos/panos_interface.py
> +# enable DHCP client on ethernet1/1 in zone public
This comment should be part of the `- name:`

2017-02-13 18:30 UTC, ivanbojer commented on lib/ansible/modules/network/panos/panos_interface.py
> +            - IP address (or hostname) of PAN-OS device
OK

2017-02-13 18:30 UTC, ivanbojer commented on lib/ansible/modules/network/panos/panos_interface.py
> +# enable DHCP client on ethernet1/1 in zone public
OK

2017-02-13 18:35 UTC, ivanbojer commented
@gundalow Thank you for the review. I've incorporated all the changes requested. In addition I incorporated changes from the previous comments too (like ANSIBLE_METADATA coming before DOCUMENTATION).

2017-02-13 18:35 UTC, ivanbojer commented
ready_for_review

2017-02-13 18:56 UTC, gundalow approved these changes

2017-02-21 03:22 UTC, merged