New Network Module: facts module for HUAWEI cloudengine switch.
ansible/ansible pull request #20679
Opened 2017-01-26 07:50 UTC by JackyGao2016

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
ce_facts

##### ANSIBLE VERSION

```
# ansible --version
ansible 2.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr1/wangdz/ansible-iSource/lib/ansible/modules/core/network/cloudengine']
```

##### SUMMARY

This module returns HUAWEI cloudengine(CE) switch facts

```
[BEGIN] 2017/1/26 15:44:26
root@SZV1000189197:/usr1/wangdz# ansible -m ce_facts -a 'host=10.135.182.157 port=12347 username=rootDC password=Admin@123 gather_subset=default' localhost --connection local
localhost | SUCCESS => {
    "ansible_facts": {
        "BIOS Version": "365", 
        "Board Type": "CE7850-32Q-EI", 
        "CPLD1 Version": "100", 
        "CPLD2 Version": "100", 
        "MAB Version": "1", 
        "PCB Version": "CEM32QP01", 
        "gather_subset": [
            "default"
        ], 
        "hostname": "test1.com"
    }, 
    "changed": false
}
```

2017-02-11 15:58 UTC, gundalow requested changes

2017-02-11 15:58 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_facts.py
> +# Collect only the config facts
Please use `- name: ` rather than comments

http://docs.ansible.com/ansible/dev_guide/developing_modules_documenting.html#examples-block

2017-02-11 15:58 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_facts.py
> +# default
FYI, all these RETURN items will end up as rows in a table and will not be grouped by default, hardware, etc.

I can't think of a better way of doing this, no action, just so you are aware.

2017-02-13 12:36 UTC, numone213 commented on lib/ansible/modules/network/cloudengine/ce_facts.py
> +# Collect only the config facts
I've corrected it.

2017-02-13 13:33 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_facts.py
> +# default
ok, I know it, thanks.

2017-02-13 13:49 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_facts.py
> +# Collect only the config facts
Thanks, if you push those changes I can re-review

2017-05-09 14:39 UTC, gundalow requested changes

2017-05-09 14:39 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_facts.py
> +version_added: "2.3"
`version_added: "2.4"`

2017-05-09 14:39 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_facts.py
> +# Collect only the config facts
Doesn't seem to have been done

2017-05-12 15:37 UTC, calfonso commented
@JackyGao2016 just checking in here, are you planning on making the rest of the changes so we can get this PR merged?

2017-05-14 10:47 UTC, QijunPan commented
@calfonso  @JackyGao2016  The RP no longer valid. Please close it directly, thanks.

2017-05-14 14:00 UTC, closed without merging