New ec2_az_facts module to be able to get facts from EC2 availability zones
ansible/ansible pull request #20690
Opened 2017-01-26 12:19 UTC by Sodki

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

ec2_az_facts

##### ANSIBLE VERSION

```
ansible 2.3.0 (devel 28e39ca42f) last updated 2017/01/25 16:44:10 (GMT +100)
  config file = 
  configured module search path = Default w/o overrides
```

##### SUMMARY

This is a new module that allows to query EC2 and obtain a a list of availability zones. It's useful if you want to iterate through the availability zones in search of something specific. I wrote this module because it was something I needed to do.

This implementation uses the same skeleton as `ec2_group_facts`.

2017-01-27 16:54 UTC, tedder commented
Regions (#20689) and zones seem similar. Perhaps these should be rolled together, maybe even with some other facts?

2017-01-27 17:13 UTC, jjshoe requested changes

2017-01-27 17:13 UTC, jjshoe commented on lib/ansible/modules/cloud/amazon/ec2_az_facts.py
> +    sample:
Where's the sample?

2017-01-27 17:13 UTC, jjshoe commented on lib/ansible/modules/cloud/amazon/ec2_az_facts.py
> +    region, ec2_url, aws_connect_params = get_aws_connection_info(module, boto3=True)
I could be wrong, but this doesn't appear to be using the aws connection stuff that's in https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/ec2.py

2017-01-27 17:13 UTC, jjshoe commented on lib/ansible/modules/cloud/amazon/ec2_az_facts.py
> +    sanitized_filters = module.params.get("filters")
https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/ec2.py#L379

2017-01-27 17:13 UTC, jjshoe commented on lib/ansible/modules/cloud/amazon/ec2_az_facts.py
> +    snaked_availability_zones = []
also a function in the module utils that does this

2017-01-27 17:23 UTC, jjshoe commented
Also, you don't have to, but you can add yourself as an author into the file, look at other modules for an example

2017-01-27 19:49 UTC, j-carl commented on lib/ansible/modules/cloud/amazon/ec2_az_facts.py
> +from ansible.module_utils.ec2 import *
Please change module imports to the new style. Take a look at [vmware_guest.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest.py) for an example.

2017-01-28 00:44 UTC, wimnat requested changes

2017-01-28 00:44 UTC, wimnat commented on lib/ansible/modules/cloud/amazon/ec2_az_facts.py
> +        module.fail_json(msg=e.message, exception=traceback.format_exc(e))
Handle exceptions as per the guidelines... https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/GUIDELINES.md#boto3-2

2017-01-28 08:58 UTC, willthames commented
This should probably be renamed aws_az_facts (same for the regions facts). Most of my comments in the regions PR apply here.

2017-02-16 17:30 UTC, Sodki commented on lib/ansible/modules/cloud/amazon/ec2_az_facts.py
> +    sample:
You're right, I missed that one. Added.

2017-02-16 17:31 UTC, Sodki commented on lib/ansible/modules/cloud/amazon/ec2_az_facts.py
> +    region, ec2_url, aws_connect_params = get_aws_connection_info(module, boto3=True)
It does use it.

2017-02-16 17:32 UTC, Sodki commented on lib/ansible/modules/cloud/amazon/ec2_az_facts.py
> +    sanitized_filters = module.params.get("filters")
I don't understand. I use that function a couple of lines below, but I still need to to the dash/underscore switch first.

2017-02-16 17:32 UTC, Sodki commented on lib/ansible/modules/cloud/amazon/ec2_az_facts.py
> +    snaked_availability_zones = []
I use that function a couple of lines below. But I've changed the code to make it explicit and smaller. Thanks!

2017-02-16 17:40 UTC, Sodki commented on lib/ansible/modules/cloud/amazon/ec2_az_facts.py
> +from ansible.module_utils.ec2 import *
Thank you, I've changed it.

2017-02-16 23:55 UTC, Sodki commented
@jjshoe I'm declaring myself as the author:
```
 +author: "Henrique Rodrigues (github.com/Sodki)"
```
Or is it something else that I'm missing?

2017-02-17 00:03 UTC, Sodki commented
@willthames I agree with the name change, it makes total sense. I've renamed this to aws_az_facts.

2017-02-17 00:50 UTC, Sodki commented
@willthames I've also taken your other comments into account. flake8 is now happy.

2017-02-17 00:52 UTC, Sodki commented
ready_for_review

2017-02-17 01:28 UTC, Sodki commented
@tedder `aws_region_facts` and `aws_az_facts` serve different purposes, that's why I implemented them as different modules. But if there is a consensus that they should be merged, I'll happily do it.

2017-02-17 03:50 UTC, willthames commented
shipit

subjective style comments that apply to #20689 apply here too

2017-02-17 15:18 UTC, Sodki commented
@willthames I've applies the changes you mentioned, thank you for them.

ready_for_review

2017-02-17 19:39 UTC, mattclay commented on lib/ansible/modules/cloud/amazon/aws_az_facts.py
> +    sanitized_filters = {k.replace('_', '-'):v for k,v in module.params.get('filters').items()}
CI failure due to use of dict comprehensions, which aren't supported on python 2.6:

```
2017-02-17 15:34:06 Compiling ./lib/ansible/modules/cloud/amazon/aws_az_facts.py ...
2017-02-17 15:34:06 SyntaxError: ('invalid syntax', ('./lib/ansible/modules/cloud/amazon/aws_az_facts.py', 116, 50, "    sanitized_filters = {k.replace('_', '-'):v for k,v in module.params.get('filters').items()}\n"))
```

See here for an alternative: http://stackoverflow.com/questions/21069668/alternative-to-dict-comprehension-prior-to-python-2-7

2017-02-17 21:06 UTC, Sodki commented on lib/ansible/modules/cloud/amazon/aws_az_facts.py
> +    sanitized_filters = {k.replace('_', '-'):v for k,v in module.params.get('filters').items()}
Thank you so much, I've fixed it now.

2017-02-17 21:06 UTC, Sodki commented
ready_for_review

2017-03-18 13:53 UTC, Sodki commented
ready_for_review

2018-01-25 19:31 UTC, s-hertel commented
Closing and reopening to trigger CI.

2018-01-25 19:32 UTC, s-hertel approved these changes

2018-01-25 20:12 UTC, simplesteph commented
@s-hertel I tried emailing ansible but got no answer. How do I remove myself from the list of module mainteners please?

2018-01-26 18:56 UTC, s-hertel commented
@simplesteph I've opened #35407. Do you want to be removed from all of them? If you're listed as an author for any of them an 'ignore' will also need to be added (I did so for ecs_service, but it was the only one I saw).

2018-01-26 19:52 UTC, ryansb approved these changes

2018-01-26 19:52 UTC, merged