rename setup to gather_facts, setup still an alias
ansible/ansible pull request #20717
Opened 2017-01-26 20:49 UTC by bcoca

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

setup

##### ANSIBLE VERSION

```
2.3
```

##### SUMMARY

rename setup to gather_facts as it is both a more intuitive name and not a conflict with python tools.

2017-01-26 21:27 UTC, dagwieers commented
I'd go for "facts" instead. Easier to type, less awkward for non-native English speakers.

2017-01-26 21:43 UTC, abadger commented on lib/ansible/executor/action_write_locks.py
> +    mods.update(('copy', 'file', 'setup', 'slurp', 'stat', 'gather_facts'))
You can remove setup here if it no longer gets called directly from an action plugin

2017-01-26 22:00 UTC, bcoca commented on lib/ansible/executor/action_write_locks.py
> +    mods.update(('copy', 'file', 'setup', 'slurp', 'stat', 'gather_facts'))
done

2017-01-27 08:03 UTC, jhawkesworth commented
I would have gone for get_facts to save typing those 3 extra characters.  Or perhaps I spent too much time looking at java beans with their getters and setters.  :-)

2017-01-27 21:42 UTC, bdowling commented
I saw @gundalow comment on #20702 that this might take 4 releases to deprecate the alias ...

I understand why the filesystem symlink alias support is there for module renaming/deprecation.  But in this instance, in order to address the issue impacting people today, is there any reason a workaround  in the loader couldn't be made?  We have aliases for parameters, why not implement aliases for modules in code?  e.g.

```diff
--- a/lib/ansible/plugins/__init__.py
+++ b/lib/ansible/plugins/__init__.py
@@ -224,6 +224,11 @@ class PluginLoader:
     def find_plugin(self, name, mod_type='', ignore_deprecated=False):
         ''' Find a plugin named name '''
 
+        # Handle module aliases, could be done in a more generic method, but just
+        # to test this works --BD
+        if name == 'setup':
+            name = 'gather_facts'
+
```

I tested this both with the adhoc -m setup and playbook and worked just fine with other setup.py files in the path.

2017-01-31 05:18 UTC, jctanner commented
bot_status

2017-01-31 14:10 UTC, bcoca commented
@bdowling we cannot do that as it will break local overrides

2017-01-31 21:50 UTC, bdowling commented
Should the examples and other docs be changed to "-m gather_facts" ?

https://github.com/bcoca/ansible/blob/3e6a984b97fa75cd7a48d610c75f93489fb10106/lib/ansible/modules/system/gather_facts.py#L96

2017-01-31 22:51 UTC, bcoca commented
if/when we decide to merge this, yep, we should start changing docs

2017-02-02 15:41 UTC, dagwieers commented
Can we postpone this change and do this together with modularizing setup ?

Because I would like to have the concept of facts-plugins, where the setup module includes specific facts (either on request or by default) in the gather_facts stage.

At various customers they have the need for specific custom facts (not something worth upstreaming because specific to their systems/applications/processes) and currently we have custom modules that updates the fact-cache and are included by the inventory-script). That's a very ugly two-step inventory scheme, to avoid having the inventory-script gathering those facts as well.

The solution to this are facts-plugins that setup runs for you.

2017-02-02 17:21 UTC, bcoca commented
@dagwieers several of us have talked about that, if you want to start the proposals (i think we never got one out) we'll look at making that part of 2.4

In any case, I think this change is unrelated.

2017-02-03 12:01 UTC, dagwieers commented
It's related if we are planning to call that phase "facts" and the plugins "facts plugins" rather than "gather_facts" and "gather_facts" plugins. I.e. the remote directory is called */etc/facts.d/* not */etc/gather_facts.d/*

I would rather propose to rename the gather_facts-parameter to simply facts: (and keep gather_facts for backward-compatibility). And rename the "setup" module to "facts" instead.

    ansible -m facts system1

rather than

    ansible -m gather_facts system1

And
```yaml
- hosts: all
  facts: no
  tasks:
  - vmware_guest:
    connection: local

  - wait_for_connection:

  - facts:
```

It is going to be confusing since we have so many *_facts modules now, that gather_facts in a listing seems related to some subsystem called "gather", rather than the default facts-mechanism.

2017-03-14 05:00 UTC, mattclay commented
I reran CI for this PR to test the new message sorting. This triggered the additional bot notification.

2017-03-16 02:33 UTC, mattclay requested changes

2017-03-16 02:33 UTC, mattclay commented on lib/ansible/modules/system/gather_facts.py
> +version_added: 2.4
The value for `version_added` should remain `historical` since we're only renaming the module.

2017-03-16 02:33 UTC, mattclay commented on lib/ansible/modules/system/gather_facts.py
> +    - the module used to be named 'setup', changed in version 2.4.
Capitalize the first letter of this sentence. Use `I(setup)` instead of `'setup'`.

2017-03-16 02:33 UTC, mattclay commented on test/sanity/validate-modules/validate-modules
> +        'gather_facts.ps1'
This line should replace the previous line. Include a comma at the end of the line.

2017-03-16 02:33 UTC, mattclay commented on lib/ansible/executor/action_write_locks.py
> +    mods.update(('copy', 'file', 'gather_facts', 'slurp', 'stat' ))
Remove the added trailing space at the end of the set.

2017-03-16 02:35 UTC, mattclay commented
@bcoca Do you know if the doc generation handles module aliases?

2017-03-16 13:34 UTC, bcoca commented on lib/ansible/modules/system/gather_facts.py
> +version_added: 2.4
that would mislead users to think gather_facts was always available

2017-03-16 16:02 UTC, bcoca commented
well, aliases in anisble-doc will point you to the 'main' doc, have not checked the html site.

2017-03-16 19:21 UTC, mattclay approved these changes

2017-03-16 19:23 UTC, mattclay commented
It's the HTML site I was thinking about. We don't want the existing setup page to disappear, at least not without a redirect.

2017-03-16 19:24 UTC, mattclay commented on lib/ansible/modules/system/gather_facts.py
> +version_added: 2.4
It's too bad we don't have a way (aside from the description) to indicate a different version_added for the new and old names.

2017-06-14 16:10 UTC, itdependsnetworks commented
@bcoca Is this still on target for 2.4?

2017-06-16 16:13 UTC, gundalow commented on test/sanity/validate-modules/validate-modules
> -main.py
Why has this changed?

2017-07-11 19:16 UTC, alikins commented
I'm +1 for renaming lib/ansible/modules/system/setup.py to lib/ansible/modules/system/facts.py with an alias for 'setup'

2017-07-13 15:54 UTC, bcoca commented
closing due to bikeshed mobious strip

2017-07-13 15:54 UTC, closed without merging

2018-07-17 20:02 UTC, dagwieers commented
From the meeting notes on 2018-01-09: https://meetbot.fedoraproject.org/ansible-meeting/2018-01-09/ansible_core.2018-01-09-19.00.log.html

There are references to earlier discussions (I was not involved in).
```
19:20:59 <abadger1999> gundalow: change the name there from gather_facts to facts and I think we had agreement from alikins and i that it would be okay.
-snip-
19:22:05 <abadger1999> I'm okay with it happening.
19:22:15 <abadger1999> As loing as we can agree on name.
19:22:23 <abadger1999> that's where we got stuck last time.
-snip-
19:22:38 <abadger1999> I think everyone except bcoca agreed on the name but bcoca had been the one writing the PR?
```

From those meeting logs we can count people's preferences:
- **gather_facts:** bcoca, jimi, maximilion
- **facts:** dag, alikins, abadger, nitzmahone
- *no change*: jimi, sivel

Where thaumos and sivel didn't clearly state a preference, and maximilian was fine with both (but preferred gather_facts).

There's also the possibility to make 'setup' work without calling the module **setup.py**.