include upgraded packages in pacman upgrade action
ansible/ansible pull request #20713
Opened 2017-01-26 20:20 UTC by yithian

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

pacman module

##### ANSIBLE VERSION

```
ansible 2.3.0 (devel d4449d082e) last updated 2017/01/26 11:34:53 (GMT -400)
  config file = /home/<username>/code/<playbooks repo>/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY

Include a list of packages that were upgraded when performing a pacman upgrade task (or would be, if running in check mode). The upgraded packages are returned as a new key in the interest of not breaking backwards compatibility. Also this way there's less risk of flooding the user's screen with a huge list of packages.

I envision this being useful for registering the return of an upgrade so that handlers could selectively restart services after being upgraded.

Before:
```
ok: [<hostname>] => {
    "updates": {
        "changed": true, 
        "msg": "System upgraded"
    }
}
```
After:
```
ok: [<hostname>] => {
    "updates": {
        "changed": true, 
        "msg": "System upgraded", 
        "packages": [
            "gnupg", 
            "python2-parsedatetime", 
            "python2-requests"
        ]
    }
}
```

2017-01-26 20:28 UTC, indrajitr commented
shipit

2017-01-26 21:35 UTC, jctanner commented
bot_status

2017-01-26 21:39 UTC, bcoca commented
I would use the 'diff' facility to show packages added/removed.

2017-01-26 21:43 UTC, indrajitr commented
Yes, that's on my todo-list. Will get back to this in a week.

2017-01-27 00:52 UTC, indrajitr commented
needs_revision
If @yithian can take care of this per the recommendation of @bcoca (which is definitely a better way forward), great. Else I'll take care of this in a week.

2017-01-27 01:12 UTC, yithian commented
I'll make that revision and update the pull request with the new commit

2017-01-27 03:52 UTC, yithian commented
--check --diff output now looks like this:

```
TASK [system updates] ***********************************************************************************************************
--- before
+++ after: upgraded
@@ -0,0 +1,3 @@
+gnupg
+python2-parsedatetime
+python2-requests

changed: [<hostname>]

TASK [display output] ***********************************************************************************************************
ok: [<hostname>] => {
    "pacman_result": {
        "changed": true,
        "diff": {
            "after": "gnupg\npython2-parsedatetime\npython2-requests\n",
            "after_header": "upgraded",
            "before": ""
        },
        "msg": "3 package(s) would be upgraded",
        "packages": [
            "gnupg",
            "python2-parsedatetime",
            "python2-requests"
        ]
    }
}
```

using just --diff (without --check) now looks like this (probably redundant, but for completion's sake):

```
TASK [system updates] ***********************************************************************************************************
--- before
+++ after: upgraded
@@ -0,0 +1,3 @@
+gnupg
+python2-parsedatetime
+python2-requests

changed: [<hostname>]

TASK [display output] ***********************************************************************************************************
ok: [<hostname>] => {
    "pacman_result": {
        "changed": true,
        "diff": {
            "after": "gnupg\npython2-parsedatetime\npython2-requests\n",
            "after_header": "upgraded",
            "before": ""
        },
        "msg": "System upgraded",
        "packages": [
            "gnupg",
            "python2-parsedatetime",
            "python2-requests"
        ]
    }
}
```

Running without --diff will have output like from before but with a skeleton diff key. I left the packages key because I figured it would be easier to parse

2017-01-27 03:54 UTC, yithian commented
That was an accidental click of the close button, sorry for the noise

2017-01-27 11:24 UTC, jtyr requested changes

2017-01-27 11:24 UTC, jtyr commented on lib/ansible/modules/packaging/os/pacman.py
> +        module.exit_json(changed=False, msg='Nothing to upgrade', packages=data)
Any non-standard exit keywords should be [documented](http://docs.ansible.com/ansible/dev_guide/developing_modules.html#example) in the `RETURN` block.

2017-01-30 21:33 UTC, yithian commented
I've also got a patch that would add --diff support to the install_packages, remove_packages and check_packages functions, if that should be included here.

If not, I can submit it as a separate pull request.

2017-01-30 21:36 UTC, indrajitr commented
@yithian, yes please! That would be very awesome. I'll just take your PR instead of submitting the one I was working on.

2017-01-30 21:44 UTC, yithian commented
output used to look like:
```
TASK [install packages] ********************************************************
changed: [<hostname>] => (item=[u'cowsay', u'ponysay'])

TASK [remove packages] *********************************************************
changed: [<hostname>] => (item=[u'cowsay', u'ponysay'])
```

output now looks like:
```
TASK [install packages] *********************************************************************************************************************************************************************************************
--- before
+++ after: installed
@@ -0,0 +1,2 @@
+cowsay
+ponysay

changed: [<hostname>] => (item=[u'cowsay', u'ponysay'])

TASK [remove packages] **********************************************************************************************************************************************************************************************
--- before: removed
+++ after
@@ -1,2 +0,0 @@
-cowsay
-ponysay

changed: [<hostname>] => (item=[u'cowsay', u'ponysay'])
```

2017-02-08 14:48 UTC, yithian commented
any other changes i should make for this?

2017-02-16 14:39 UTC, yithian commented
ready_for_review

2017-02-16 16:09 UTC, yithian commented
bot_status

2017-02-16 18:20 UTC, yithian commented
bot_broken

2017-02-23 21:54 UTC, yithian commented
upgrade output (with -D) now looks like:
```
--- before
+++ after
@@ -1,8 +1,8 @@
-bash-4.4.005-1
-libssh-0.7.4-1
-mesa-17.0.0-1.1
-libgl-17.0.0-1.1
-libwww-6.15-1
-appdirs-1.4.0-5
-utils-1.10.1-1
-wget-1.19.1-1
+bash-4.4.012-2
+libssh-0.7.4-2
+mesa-17.0.0-2
+libgl-17.0.0-2
+libwww-6.19-2
+appdirs-1.4.1-1
+utils-1.12.3-1
+wget-1.19.1-2

changed: [<hostname>] => {
    "changed": true, 
    "diff": {
        "after": "bash-4.4.012-2\nlibssh-0.7.4-2\nmesa-17.0.0-2\nlibgl-17.0.0-2\nlibwww-6.19-2\nappdirs-1.4.1-1\nutils-1.12.3-1\nwget-1.19.1-2\n", 
        "before": "bash-4.4.005-1\nlibssh-0.7.4-1\nmesa-17.0.0-1.1\nlibgl-17.0.0-1.1\nlibwww-6.15-1\nappdirs-1.4.0-5\nutils-1.10.1-1\nwget-1.19.1-1\n"
    }, 
    "invocation": {
        "module_args": {
            "force": false, 
            "name": null, 
            "recurse": false, 
            "state": "present", 
            "update_cache": true, 
            "upgrade": true
        }, 
        "module_name": "pacman"
    }, 
    "msg": "System upgraded", 
    "packages": [
        "bash", 
        "libssh", 
        "mesa", 
        "libgl", 
        "libwww", 
        "appdirs", 
        "utils", 
        "wget"
    ]
}
```

package install output (with -D) now looks like:
```
--- before
+++ after
@@ -0,0 +1,3 @@
+cowsay-3.03-9
+ponysay-3.0.2-1
+sl-5.02-4

changed: [<hostname>] => (item=[u'cowsay', u'ponysay', u'sl']) => {
    "changed": true, 
    "diff": {
        "after": "cowsay-3.03-9\nponysay-3.0.2-1\nsl-5.02-4\n", 
        "before": ""
    }, 
    "invocation": {
        "module_args": {
            "force": false, 
            "name": [
                "cowsay", 
                "ponysay", 
                "sl"
            ], 
            "recurse": false, 
            "state": "present", 
            "update_cache": false, 
            "upgrade": false
        }, 
        "module_name": "pacman"
    }, 
    "item": [
        "cowsay", 
        "ponysay", 
        "sl"
    ], 
    "msg": "installed 3 package(s). "
}
```

package removal output (with -D) now looks like:
```
--- before
+++ after
@@ -1,3 +0,0 @@
-cowsay-3.03-9
-ponysay-3.0.2-1
-sl-5.02-4

changed: [<hostname>] => (item=[u'cowsay', u'ponysay', u'sl']) => {
    "changed": true, 
    "diff": {
        "after": "", 
        "before": "cowsay-3.03-9\nponysay-3.0.2-1\nsl-5.02-4\n"
    }, 
    "invocation": {
        "module_args": {
            "force": false, 
            "name": [
                "cowsay", 
                "ponysay", 
                "sl"
            ], 
            "recurse": false, 
            "state": "absent", 
            "update_cache": false, 
            "upgrade": false
        }, 
        "module_name": "pacman"
    }, 
    "item": [
        "cowsay", 
        "ponysay", 
        "sl"
    ], 
    "msg": "removed 3 package(s)"
}
```

2017-03-02 16:01 UTC, yithian commented
ready_for_review

2017-03-08 15:22 UTC, yithian commented
@indrajitr @bcoca Is there anything left you'd like me to do for this?

It doesn't look like the ansibot commands are working to remove the needs_revision label...

2017-03-08 15:32 UTC, merged

2017-03-08 22:25 UTC, jctanner commented
@yithian the needs_revision label was set because @jtyr needed to approve or dismiss his change request. The bot status command wasn't working because of https://github.com/ansible/ansibullbot/pull/408