Add NetApp SolidFire snapshot schedule module
ansible/ansible pull request #20734
Opened 2017-01-27 00:48 UTC by timuster

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

NetApp SolidFire snapshot schedule manager module

##### ANSIBLE VERSION

```
ansible 2.3.0
  config file = 
  configured module search path = Default w/o overrides
```

##### SUMMARY

Adding sf_snapshot_schedule_manager.py, a module to manage NetApp SolidFire snapshot schedules. The design was based on the existing NetApp E-Series modules.

```

```

2017-01-31 19:58 UTC, hulquest commented
All of the general comments made in #20732 have been applied here.  
The module is sound from a SF API point of view. 
shipit

2017-02-03 06:55 UTC, resmo commented on lib/ansible/modules/storage/netapp/sf_snapshot_schedule_manager.py
> +            supports_check_mode=False
To me it looks the module does handle check mode (https://github.com/ansible/ansible/pull/20734/files#diff-672a20e0686da08f7554286ee4283346R423). So in my opinion `supports_check_mode` an be set to true

2017-02-04 00:40 UTC, timuster commented on lib/ansible/modules/storage/netapp/sf_snapshot_schedule_manager.py
> +            supports_check_mode=False
@resmo You're right. This is remnant of an older code commit. Fixing it now.

2017-02-04 01:38 UTC, mattclay commented on lib/ansible/modules/storage/netapp/sf_snapshot_schedule_manager.py
> +        - Please use two '-' in the above format, or you may see the following error: TypeError: datetime.datetime(2016, 12, 1, 0, 0) is not JSON serializable description.
CI failure due to PEP 8 issue:

```
2017-02-04 01:35:47 ERROR: PEP 8: lib/ansible/modules/storage/netapp/sf_snapshot_schedule_manager.py:114:161: E501 line too long (171 > 160 characters) (current)
```

2017-02-06 19:03 UTC, timuster commented
ready_for_review

2017-02-06 19:11 UTC, jctanner commented
bot_status

2017-02-06 22:44 UTC, resmo commented
shipit

2017-02-07 20:55 UTC, hulquest commented
shipit

2017-02-07 23:56 UTC, mattclay commented
bot_status

2017-02-08 15:07 UTC, bcoca commented on lib/ansible/modules/storage/netapp/sf_snapshot_schedule_manager.py
> +    pause:
not blocker: `paused` is more declarative, `pause` is imperative, we prefer the former

2017-02-08 15:14 UTC, bcoca requested changes

2017-02-08 15:14 UTC, bcoca commented on lib/ansible/modules/storage/netapp/sf_snapshot_schedule_manager.py
> +logger.setLevel(logging.DEBUG)
modules already have logging  and debug facilities, do not create alternates as you bypass things like `no_log`

2017-02-08 15:14 UTC, bcoca commented on lib/ansible/modules/storage/netapp/sf_snapshot_schedule_manager.py
> +    new_name:
since schedule_id is the unique identifier i do not use new_name, if the name does not match update it.

2017-02-08 15:14 UTC, bcoca commented on lib/ansible/modules/storage/netapp/sf_snapshot_schedule_manager.py
> +        logger.debug("Exception in apply(): \n%s" % format_exc(err))
catchall exception, does not give us good idea of exact action that was being attempted on the module's side, unless the underlying API is very friendly/precise we normally prefer to do specific exception catching closer to the source of the exception so we can tell module user what was being attempted i.e `failed to change name of schedule: %s' % e`

2017-02-08 15:22 UTC, bcoca commented on lib/ansible/modules/storage/netapp/sf_snapshot_schedule_manager.py
> +        raise
ending module execution in  an exception is a bug

use fail_json, if you want to pass back traceback information use the 'exception' key in the returned json

2017-02-08 15:32 UTC, resmo commented on lib/ansible/modules/storage/netapp/sf_snapshot_schedule_manager.py
> +import logging
@gundalow probably a pattern to trigger for the sanity tests. logging should be avoided due security reasons

2017-02-08 16:32 UTC, sivel commented
@timuster I've fixed the module that was causing tests to fail in this PR.  Please rebase against current devel, and tests should not fail on that module.

2017-02-08 17:06 UTC, timuster commented
ready_for_review

2017-02-08 18:14 UTC, bcoca commented on lib/ansible/modules/storage/netapp/sf_snapshot_schedule_manager.py
> +            pause=dict(required=False, type='bool'),
does not match docs

2017-02-08 18:15 UTC, bcoca commented on lib/ansible/modules/storage/netapp/sf_snapshot_schedule_manager.py
> +
not a blocker, but returning schedule information would be 'nice', schedule_id at the least when creating.

2017-02-08 18:39 UTC, bcoca approved these changes

2017-02-09 06:49 UTC, resmo commented
shipit

2017-02-09 10:11 UTC, gundalow commented on lib/ansible/modules/storage/netapp/sf_snapshot_schedule_manager.py
> +        type: bool
Please remove the `type:` lines from `DOCUMENTATION` block, they are not required.

2017-02-09 19:39 UTC, gundalow approved these changes

2017-02-09 19:39 UTC, merged

2017-02-09 19:45 UTC, gundalow commented
Merged, thanks
If you could please update https://github.com/ansible/ansible/pull/2073 and confirm that your docs_fragment change goes away that would be great (and then repeat for the other PRs)

Added to CHANGELOG.md https://github.com/ansible/ansible/pull/21212/files

At the moment we have `storage/netapp/: hulquest` defined in the maintainers list, should that be changed to hulquest + timuster? Anyone else need adding??