Add NetApp SolidFire volume access group module
ansible/ansible pull request #20733
Opened 2017-01-27 00:37 UTC by timuster

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

NetApp SolidFire volume access group module

##### ANSIBLE VERSION

```
ansible 2.3.0
  config file = 
  configured module search path = Default w/o overrides
```

##### SUMMARY

Adding sf_volume_access_group_manager.py, a module to manage NetApp SolidFire volume access groups. The design was based on the existing NetApp E-Series modules.

```

```

2017-01-31 19:59 UTC, hulquest commented
All of the general comments made in #20732 have been applied here.  
The module is sound from a SF API point of view. 
shipit

2017-02-01 20:25 UTC, resmo commented on lib/ansible/modules/storage/netapp/sf_volume_access_group_manager.py
> +    - auth_basic
is this a left over?

2017-02-01 20:25 UTC, resmo commented on lib/ansible/modules/storage/netapp/sf_volume_access_group_manager.py
> +        required: true
many modules have the default of `state=present`. consider this as a default if you feel it make sense.

2017-02-01 20:25 UTC, resmo commented on lib/ansible/modules/storage/netapp/sf_volume_access_group_manager.py
> +       volumes: 7,8
I would prefer the syntax `[7, 8]` comma separated can be confusing

2017-02-01 20:25 UTC, resmo commented on lib/ansible/modules/storage/netapp/sf_volume_access_group_manager.py
> +msg:
changed: true is a common return, no need to document that. but you have `msg` several times, which does not make much sense. if the module does not return anything other than the common returns, just leave it empty

2017-02-01 20:25 UTC, resmo commented on lib/ansible/modules/storage/netapp/sf_volume_access_group_manager.py
> +    attributes:
would be good to have an example for this as it is free form

2017-02-02 00:29 UTC, timuster commented on lib/ansible/modules/storage/netapp/sf_volume_access_group_manager.py
> +    attributes:
I've provided an example in the "EXAMPLES" section.

2017-02-02 00:30 UTC, timuster commented on lib/ansible/modules/storage/netapp/sf_volume_access_group_manager.py
> +        required: true
That's a good suggestion! However, for the sake of consistency with the other existing NetApp modules, I think it's a good idea to leave it as it is. We can update all of our modules later.

2017-02-02 20:27 UTC, timuster commented
ready_for_review

2017-02-06 21:14 UTC, mattclay commented on lib/ansible/modules/storage/netapp/sf_volume_access_group_manager.py
> +DOCUMENTATION = '''
CI failure due to missing module metadata:

```
2017-02-06 20:39:27 ============================================================================
2017-02-06 20:39:27 lib/ansible/modules/storage/netapp/sf_volume_access_group_manager.py
2017-02-06 20:39:27 ============================================================================
2017-02-06 20:39:27 ERROR: No ANSIBLE_METADATA provided
```

2017-02-06 22:06 UTC, resmo commented
shipit

(note for the merger, add metadata after the merge)

2017-02-06 23:18 UTC, resmo commented
shipit

2017-02-07 05:54 UTC, resmo commented
shipit

2017-02-07 20:55 UTC, hulquest commented
shipit

2017-02-08 16:24 UTC, resmo requested changes

2017-02-08 16:24 UTC, resmo commented on lib/ansible/modules/storage/netapp/sf_volume_access_group_manager.py
> +import logging
please remove logging due security concerns

2017-02-08 16:24 UTC, resmo commented on lib/ansible/modules/storage/netapp/sf_volume_access_group_manager.py
> +        raise
replace with fail_json() to show a user friendly error message

2017-02-08 23:56 UTC, timuster commented
ready_for_review

2017-02-10 12:47 UTC, resmo approved these changes

2017-02-10 18:52 UTC, merged