adds netconf shared module
ansible/ansible pull request #20743
Opened 2017-01-27 04:07 UTC by privateip

New netconf shared lib added to module_utils for sending netconf
messages to remote devices over netconf connection plugin

2017-01-27 09:35 UTC, gundalow requested changes
I believe we agreed that all new files would start `network_`

You'd previously said:
> agreed, we are standardizing on network_ .... will need to move the rest through a deprecation process

2017-01-27 09:37 UTC, gundalow commented on lib/ansible/module_utils/netconf.py
> +        yield
This doesn't seem to be py2.4 compliant

```
2017-01-27 04:09:40 Compiling ./lib/ansible/module_utils/netconf.py ...
2017-01-27 04:09:40   File "./lib/ansible/module_utils/netconf.py", line 79
2017-01-27 04:09:40     yield
2017-01-27 04:09:40          ^
2017-01-27 04:09:40 SyntaxError: invalid syntax
```

2017-01-27 12:50 UTC, privateip commented
Modules that are common libs for all networking will start with `network_`.  This one is specific to netconf (same as say eos or nxos or ios... etc)

2017-01-28 07:28 UTC, mattclay commented
@privateip CI failure due to python 2.4 syntax error:

```
2017-01-27 04:09:40 Compiling ./lib/ansible/module_utils/netconf.py ...
2017-01-27 04:09:40   File "./lib/ansible/module_utils/netconf.py", line 79
2017-01-27 04:09:40     yield
2017-01-27 04:09:40          ^
2017-01-27 04:09:40 SyntaxError: invalid syntax
```

2017-02-04 14:40 UTC, merged