module docker_image: print output on failure
ansible/ansible pull request #20757
Opened 2017-01-27 15:44 UTC by TomasTomecek

Signed-off-by: Tomas Tomecek <ttomecek@redhat.com>

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
module `docker_image`

##### ANSIBLE VERSION

```
2.2.1
```

##### SUMMARY

The module now gathers all build logs and prints them upon failure.

Fixes https://github.com/ansible/ansible-modules-core/issues/5161

before
```
$ PYTHONPATH="lib/" ./bin/ansible-playbook ./asd.yml
 [WARNING]: provided hosts list is empty, only localhost is available

PLAY [a] ******************************************************************************************************************************************

TASK [b] ******************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error building asd - code: 1 message: The command '/bin/sh -c false' returned a non-zero code: 1"}
        to retry, use: --limit @/home/tt/g/ansible/asd.retry

PLAY RECAP ****************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1

```

after
```
 PYTHONPATH="lib/" ./bin/ansible-playbook ./asd.yml
 [WARNING]: provided hosts list is empty, only localhost is available

PLAY [a] ******************************************************************************************************************************************

TASK [b] ******************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error building asd - logs: [u'Step 1 : FROM fedora:25\\n', u' ---> a1e614
f0f30e\\n', u'Step 2 : LABEL a b\\n', u' ---> Using cache\\n', u' ---> 1fa7d53567a0\\n', u'Step 3 : RUN false\\n', u' ---> Running in 5472c265b599\
\n', u'Removing intermediate container 5472c265b599\\n'], code: 1 message: The command '/bin/sh -c false' returned a non-zero code: 1"}
        to retry, use: --limit @/home/tt/g/ansible/asd.retry

PLAY RECAP ****************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1
```

2017-01-30 20:51 UTC, ryansb requested changes

2017-01-30 20:51 UTC, ryansb commented on lib/ansible/modules/cloud/docker/docker_image.py
> +                            "Error building %s - logs: %s, code: %s message: %s" % (
I'd prefer to have logs last in the error message, since they're going to be by far the most verbose.

2017-01-31 13:29 UTC, TomasTomecek commented on lib/ansible/modules/cloud/docker/docker_image.py
> +                            "Error building %s - logs: %s, code: %s message: %s" % (
done

2017-01-31 16:56 UTC, ryansb approved these changes

2017-01-31 16:57 UTC, ryansb requested changes

2017-01-31 16:57 UTC, ryansb commented on lib/ansible/modules/cloud/docker/docker_image.py
> +                            self.name,
Please fix the PEP8 errors here https://app.shippable.com/runs/589091484862ac1000f7f0a0/1/console

2017-02-01 14:39 UTC, TomasTomecek commented on lib/ansible/modules/cloud/docker/docker_image.py
> +                            self.name,
Oh, I didn't notice. Thanks for headsup, should be fixed now.

2017-02-01 14:51 UTC, ryansb approved these changes

2017-02-01 14:51 UTC, ryansb commented
shipit

2017-02-16 10:42 UTC, TomasTomecek commented
Still not merged :/

2017-02-16 14:47 UTC, merged