Add min_count and max_count options to ec2 module
ansible/ansible pull request #20788
Opened 2017-01-28 04:48 UTC by wrouesnel

These two options fulfill the same purpose as the exact_count option, but allow
for loosely specifying the number of instances or bounding it.

min_count ensures at least a certain number of instances are running, max_count
ensures no more then a certain number are running.

min_count and max_count can be used together, but are mutually exclusive to
exact_count (which is functionally identical to setting both values to the same
number).

These options make performing non Amazon autoscaling much easier, and
in particular allow idempotent deploy and bootstrapping ("ensure at least 1
production machine exists" can now be written into a play.)

2017-01-28 04:48 UTC, wrouesnel commented
Migrated from https://github.com/ansible/ansible-modules-core/pull/2240

2017-01-28 07:30 UTC, mattclay commented on lib/ansible/modules/cloud/amazon/ec2.py
> +
@wrouesnel CI failure due to PEP 8 issue:

```
2017-01-28 07:26:38 ERROR: PEP 8: lib/ansible/modules/cloud/amazon/ec2.py:930:1: W293 blank line contains whitespace (legacy)
```

2017-03-08 16:04 UTC, wrouesnel commented
Rebased and updated.

2017-06-17 02:11 UTC, wrouesnel commented
Rebased and updated again.

2017-06-18 04:14 UTC, wrouesnel commented
@mattclay Any chance of getting this looked at again? AFAIK the functionality here is still not available in the ec2 module and I believe valuable. It'd be good to get it merged.

2017-06-19 17:27 UTC, mattclay commented
/cc @s-hertel

2017-06-19 18:53 UTC, s-hertel requested changes

2017-06-19 18:53 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/ec2.py
> +from ansible.module_utils.basic import *
Can you remove these and only import specifically what is needed with the other imports?

2017-06-19 18:53 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/ec2.py
> +from ansible.module_utils.six import iteritems
I don't see this being used, can you remove it?

2017-06-19 18:53 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/ec2.py
> -from ansible.module_utils.basic import AnsibleModule
Can you put that back rather than importing everything from ansible.module_utils.basic?

2017-06-19 18:53 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/ec2.py
> +import time
Can delete this line

2017-06-19 18:54 UTC, s-hertel commented
@wrouesnel I'll test this more thoroughly within a few days. This was just a cursory review.

2017-06-20 12:32 UTC, wrouesnel commented on lib/ansible/modules/cloud/amazon/ec2.py
> +import time
Looks like a bad rebase at some point. Fixed.

2017-06-20 12:32 UTC, wrouesnel commented on lib/ansible/modules/cloud/amazon/ec2.py
> +from ansible.module_utils.basic import *
This one crept in because at some point a whole bunch of modules were doing it and I was attempting to follow the style. Fixed.

2017-06-20 12:33 UTC, wrouesnel commented on lib/ansible/modules/cloud/amazon/ec2.py
> +from ansible.module_utils.six import iteritems
Me neither - another one which I believe I inherited from a rebase at some point. Fixed.

2017-06-20 12:33 UTC, wrouesnel commented on lib/ansible/modules/cloud/amazon/ec2.py
> -from ansible.module_utils.basic import AnsibleModule
Fixed.

2017-06-20 18:50 UTC, s-hertel requested changes

2017-06-20 18:50 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/ec2.py
> +    max_count = module.params.get('min_count')
min_count =

2017-06-20 18:50 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/ec2.py
> +    if max_count <= len(instances) <= max_count:
if min_count <=

2017-06-20 18:50 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/ec2.py
> +            ['exact_count', 'max_count'],
Could you add a check somewhere that min_count < max_count?

2017-06-20 18:50 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/ec2.py
> -
Can you put the whitespace back, please?

2017-06-20 18:50 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/ec2.py
> +        if module.params.get('exact_count') is None and \
You could change this to `if not (module.params.get('exact_count') and module.params.get('min_count') and module.params.get('max_count')):`

2017-06-20 18:50 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/ec2.py
> +  max_count:
Can you add an example using these?

2017-06-20 21:57 UTC, wrouesnel commented on lib/ansible/modules/cloud/amazon/ec2.py
> +    max_count = module.params.get('min_count')
Embarrassing ...

2017-06-20 22:05 UTC, wrouesnel commented on lib/ansible/modules/cloud/amazon/ec2.py
> +    if max_count <= len(instances) <= max_count:
Fixed.

2017-06-20 22:13 UTC, wrouesnel commented on lib/ansible/modules/cloud/amazon/ec2.py
> +        if module.params.get('exact_count') is None and \
I'd somewhat prefer not to because while it's terser, IMO it's harder to read what's going on in.

2017-06-20 22:13 UTC, wrouesnel commented on lib/ansible/modules/cloud/amazon/ec2.py
> -
Fixed.

2017-06-21 11:07 UTC, s-hertel approved these changes

2017-06-21 11:08 UTC, s-hertel commented
shipit

2017-08-09 03:06 UTC, wrouesnel commented
Any progress on merging this ?

2017-08-09 12:30 UTC, s-hertel commented
@ryansb @willthames @michael-dev2rights Can I get another review on this, please, before merging?

2017-08-09 13:17 UTC, willthames approved these changes

2017-08-09 13:18 UTC, willthames commented
lgtm @s-hertel

2017-08-29 17:46 UTC, ryansb commented
I feel like this is drifting out of the intended scope for this module: for cases where you need "between X and Y instances" I'd think an autoscaling group would be the way to go, since it offers termination policies and other niceties the ec2 module will never be able to match.

2020-08-17 14:50 UTC, closed without merging