ec2_group: add ports keyword (#19888).
ansible/ansible pull request #20806
Opened 2017-01-29 16:39 UTC by anryko

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

ec2_group

##### ANSIBLE VERSION

```
ansible 2.3.0 (ec2_group_ports 460d8f34a9) last updated 2017/01/29 17:29:54 (GMT +200)
```

##### SUMMARY

Added 'ports' rule keyword. It accepts a single port value or a list of values including ranges (from_port-to_port). This will reduce verbosity of rules definition, increase maintenance convenience and readability of complex ec2 security groups. 

```
- name: example2 ec2 group
  ec2_group:
    name: example2
    description: an example2 EC2 group
    vpc_id: 12345
    region: eu-west-1a
    rules:
      - proto: tcp
        ports: 22
        group_name: example-vpn
      - proto: tcp
        ports:
          - 80
          - 443
          - 8080-8099
        cidr_ip: 0.0.0.0/0
```

2017-01-30 03:08 UTC, jbscare commented
I haven't looked at the code, but I like the YAML side.

2017-01-30 09:05 UTC, willthames commented on lib/ansible/modules/cloud/amazon/ec2_group.py
> +    rules_expanded = []
If `ports_expand` took a rule rather than the value of its `ports` key this entire function could be replaced with

```
return [ports_expand(rule) for rule in rules]
```

Edit: of course `ports_expand` returns a list, so you need to flatten the result:

```
return [rule for expansion in ports_expand(rule) for rule in expansion]
```

2017-01-30 09:05 UTC, willthames commented on lib/ansible/modules/cloud/amazon/ec2_group.py
> +    # takes a sting or list and returns a list of (port_from, port_to)
typo: string

2017-01-31 20:05 UTC, willthames commented
Thanks for the fixes - I will test this today.

2017-02-01 03:57 UTC, willthames commented
shipit

2017-02-13 11:54 UTC, willthames commented on lib/ansible/modules/cloud/amazon/ec2_group.py
> +        cidr_ip: 172.16.1.0/24
This is great, I really like this.

Can you make it clearer that all source types are now supported (group_name, group_id and cidr_ip) - it's clear to me from reading the source code, but wasn't when I looked at this example (might be worth having separate examples for different source types?)

2017-02-13 12:05 UTC, willthames requested changes

2017-02-13 12:05 UTC, willthames commented on lib/ansible/modules/cloud/amazon/ec2_group.py
> +import re
imports should all be just after the documentation sections (effectively at the top of the actual non-doc code)

2017-02-13 12:07 UTC, willthames commented
I've removed my earlier shipit comment as more functional changes have been made - I'll retest with the new features.

2017-02-16 19:07 UTC, anryko commented
@willthames is there anything else I can improve?

2017-02-16 23:25 UTC, willthames commented
@anryko I don't think so - I just need to find some time to test the most recent enhancements - they look good at first glance.

2017-02-20 16:45 UTC, alexlo03 commented
Consider adding an integration test at https://github.com/ansible/ansible/blob/devel/test/integration/roles/test_ec2_group/tasks/main.yml ?

2017-02-20 23:15 UTC, willthames commented
shipit

Have tested this in our environment (which has SGs that very much benefit from this change) and it appears to work perfectly.

@alexlo03's suggestion about adding tests is a good one, but I'm not going to block this on that.

2017-02-22 23:23 UTC, anryko commented
@alexlo03 as I understand tests are done against AWS API responses and nothing was changed in this regard. Ansible task syntax was enriched, but underneath it is expanded to meet the same API as before.
Thanks for pointing this out, I will make sure to check integration tests while working on future commits.

2017-03-06 00:38 UTC, willthames commented
!needs_revision

2017-03-06 00:39 UTC, willthames commented
bot_status

2017-03-06 03:44 UTC, jctanner commented
@willthames you need to dismiss or approve your review to get this out of needs revision.

2017-03-06 04:09 UTC, willthames approved these changes

2017-04-02 15:21 UTC, s-hertel approved these changes

2017-04-02 15:21 UTC, s-hertel commented
shipit

2017-04-04 18:09 UTC, merged