Added prefix attribute to rabbitmq modules
ansible/ansible pull request #20822
Opened 2017-01-30 15:05 UTC by ColOfAbRiX

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
rabbitmq_parameter
rabbitmq_policy
rabbitmq_user
rabbitmq_vhost

##### ANSIBLE VERSION
```
ansible 2.3.0 (feature/rabbitmq 9494c5c44b) last updated 2017/01/30 14:58:14 (GMT +000)
  config file = 
  configured module search path = Default w/o overrides
```

##### SUMMARY
Added support for RabbitMQ installation on a custom location.
The change adds a prefix attribute, like the one in the module rabbitmq_plugin, to the plugins that use the command rabbitmqctl.

**NOTE:** This is the same pull request as https://github.com/ansible/ansible-modules-extras/pull/3079 that has been closed after the repository merge and https://github.com/ansible/ansible/pull/19843 that lost the reference to my repository.

2017-03-07 12:19 UTC, ColOfAbRiX commented
Hi @manuel-sousa @chrishoffman @romanek-adam. It took me a bit to fix the merge conflict but now it's good to go.

2017-05-30 13:00 UTC, gundalow requested changes

2017-05-30 13:00 UTC, gundalow commented on lib/ansible/modules/messaging/rabbitmq_parameter.py
> +    version_added: "2.3"
`version_added: "2.4"`

2017-05-30 13:00 UTC, gundalow commented on lib/ansible/modules/messaging/rabbitmq_policy.py
> +    version_added: "2.3"
`version_added: "2.4"`

2017-05-30 13:00 UTC, gundalow commented on lib/ansible/modules/messaging/rabbitmq_user.py
> +    version_added: "2.3"
`version_added: "2.4"`

2017-05-30 13:00 UTC, gundalow commented on lib/ansible/modules/messaging/rabbitmq_vhost.py
> +    version_added: "2.3"
`version_added: "2.4"`

2017-05-31 13:10 UTC, ColOfAbRiX commented
ready_for_review

2017-06-18 07:32 UTC, gundalow commented on CHANGELOG.md
> +* The AWS Lambda module previously ignored changes that only affected one parameter. Existing deployments may have outstanding changes that this bugfix will apply.
This doesn't look related

2018-05-13 19:41 UTC, Akasurde commented
@ColOfAbRiX Could you please rebase this  ? needs_info

2018-07-16 23:31 UTC, closed without merging