oracle: initial commit
ansible/ansible pull request #20848
Opened 2017-01-31 07:45 UTC by Nosmoht

##### ISSUE TYPE

New Module Pull Request

##### COMPONENT NAME

Oracle modules

##### ANSIBLE VERSION

```
ansible 2.3.0 (oracle 44e92fa095) last updated 2017/01/31 08:37:28 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY

Add modules to support Oracle Database technology. The modules provide support to
- Manage Oracle Database Instance parameters
- Manage Oracle Database tablespaces
- Manage Oracle Database accounts
- Manage Oracle Database directotries

```
```

2017-01-31 15:25 UTC, ryansb commented
For reviews of new modules, it helps significantly to do a PR with a single module (and any needed module_utils code) before submitting all the modules. It both makes the code faster to review, and avoids situations where the same change needs to be made to all modules.

2017-01-31 15:26 UTC, ryansb commented
Also, for work-in-progress pull requests, you may choose to title the PR "[WIP] new module xyz to help foo the bars" to let reviewers know the code isn't yet ready.

2017-01-31 15:30 UTC, bcoca commented
also please review http://docs.ansible.com/ansible/dev_guide/developing_modules.html

hint: shebang should be `#!/usr/bin/python`, using env breaks interpreter configurations in Ansible.

2017-01-31 15:46 UTC, Nosmoht commented
Thanks @ryansb and @bcoca for your comments. I'll follow them next time.

In regards to the interpreter i was quite suprised that the sanity check for module_utils/oracle.py requires 
```
#!/usr/bin/env python
```
whereas all modules required 
```
#!/usr/bin/python
```
Is that expected?

2017-01-31 15:50 UTC, bcoca commented
actually that is wrong, module_utils should NOT have shebang (its probably leaking from bin/ansible)

2017-01-31 15:57 UTC, Nosmoht commented
Nice to know. But how can i pass the sanity check if i remove shebang?

I got the following result before i changed shebang with https://github.com/ansible/ansible/pull/20848/commits/811f72778b37ab0cdce0a93aabaf0ae39d99ae43
```
2017-01-31 13:42:42 ./lib/ansible/module_utils/oracle.py:#!/usr/bin/python
2017-01-31 13:42:42 One or more file(s) listed above have an unexpected shebang.
2017-01-31 13:42:42 See test/sanity/code-smell/shebang.sh for the list of acceptable values.
2017-01-31 13:42:42 ERROR: Command "test/sanity/code-smell/shebang.sh" returned exit status 1.
```

After the change the check was passed.

2017-01-31 16:04 UTC, bcoca commented
check is wrong @mattclay

2017-01-31 17:53 UTC, mattclay commented
@Nosmoht Sorry about the confusion on the shebang. The current script verifies that a shebang is on the approved list. However, it doesn't yet indicate when a file should have no shebang. If you remove the shebang, tests will pass.

2017-02-01 07:42 UTC, Nosmoht commented
@mattclay Thanks for the hint. Shebang and removed and test passed.

_ready_for_review_

2017-02-01 10:37 UTC, oswalya commented
Nice module, works really great for my standard setup. So from my point of view we should _shipit_

2017-04-25 16:35 UTC, gundalow commented
https://docs.ansible.com/ansible/dev_guide/developing_modules_in_groups.html

2017-04-25 22:07 UTC, gundalow commented
This page should help with the errors in the above comment https://docs.ansible.com/ansible/dev_guide/developing_modules_documenting.html

2017-04-27 11:46 UTC, gundalow requested changes
Looks good. Please be aware that in the future it's one module per PR.

Would be good to get some other people to test this and report back.

2017-04-27 11:46 UTC, gundalow commented on lib/ansible/modules/database/oracle/oracle_directory.py
> +- name: Ensure directory
The name seems to be incomplete
`- name: Ensure directory exists`?

2017-04-27 11:46 UTC, gundalow commented on lib/ansible/utils/module_docs_fragments/oracle.py
> +    - Can be omitted if environment variable ORACLE_PASS is set.
`C(ORACLE_PASS)`
http://docs.ansible.com/ansible/dev_guide/developing_modules_documenting.html#formatting-options

2017-04-27 11:46 UTC, gundalow commented on lib/ansible/utils/module_docs_fragments/oracle.py
> +    - Can be SYSDBA or SYSOPER.
Please remove this line, it repeats whats in `choices:`.

2017-04-27 11:46 UTC, gundalow commented on lib/ansible/modules/database/oracle/oracle_role.py
> +      - If an empty list ([]) is specified all granted roles will be revoked.
`If an empty list C([]) is specified`

2017-04-27 11:46 UTC, gundalow commented on lib/ansible/modules/database/oracle/oracle_role.py
> +      - If an empty list ([]) is specified all granted system privileges will be revoked.
`If an empty list C([]) is specified`

2017-04-27 11:46 UTC, gundalow commented on lib/ansible/modules/database/oracle/oracle_role.py
> +  description: Role and attributes as it currently exists within the databsae
databsae -> database

2017-04-27 11:46 UTC, gundalow commented on lib/ansible/modules/database/oracle/oracle_system_parameter.py
> +    - Can be omitted if environment variable ORACLE_PASS is set.
`C(ORACLE_PASS)`

2017-04-27 11:46 UTC, gundalow commented on lib/ansible/modules/database/oracle/oracle_system_parameter.py
> +    - Can be either of SYSASM, SYSDBA or SYSOPER.
Please remove this line.

2017-04-27 11:46 UTC, gundalow commented on lib/ansible/modules/database/oracle/oracle_tablespace.py
> +    default: false
Please add `type: bool` (this is the only `type:` that's supported in DOCUMENTATION.

http://docs.ansible.com/ansible/dev_guide/developing_modules_documenting.html#documentation-block

2017-04-27 11:46 UTC, gundalow commented on lib/ansible/modules/database/oracle/oracle_tablespace.py
> +    - Size of the next extend of each datafile if autoextend is enabled.
Do you need to specify units (MB, GB, etc)?

2017-04-27 11:46 UTC, gundalow commented on lib/ansible/modules/database/oracle/oracle_tablespace.py
> +    - Values must by specified as bytes or have one of ['K','M','G','T','P','E'] as suffix.
Does this line need adding to `init_size` and `next_size`?

2017-04-27 11:46 UTC, gundalow commented on lib/ansible/modules/database/oracle/oracle_user.py
> +    default: false
please add `type: bool`

2017-04-27 11:46 UTC, gundalow commented on lib/ansible/modules/database/oracle/oracle_user.py
> +            password=dict(type='str', required=False),
`, no_log = True`

2017-04-27 16:04 UTC, Nosmoht commented on lib/ansible/modules/database/oracle/oracle_user.py
> +    default: false
Done with https://github.com/ansible/ansible/pull/20848/commits/d0226d5788ebce965ce1b803de529f11d1066d6e

2017-04-27 16:04 UTC, Nosmoht commented on lib/ansible/modules/database/oracle/oracle_tablespace.py
> +    - Values must by specified as bytes or have one of ['K','M','G','T','P','E'] as suffix.
Done with https://github.com/ansible/ansible/pull/20848/commits/d0226d5788ebce965ce1b803de529f11d1066d6e

2017-04-27 16:04 UTC, Nosmoht commented on lib/ansible/modules/database/oracle/oracle_tablespace.py
> +    - Size of the next extend of each datafile if autoextend is enabled.
Done with https://github.com/ansible/ansible/pull/20848/commits/d0226d5788ebce965ce1b803de529f11d1066d6e

2017-04-27 16:04 UTC, Nosmoht commented on lib/ansible/modules/database/oracle/oracle_tablespace.py
> +    default: false
Done with https://github.com/ansible/ansible/pull/20848/commits/d0226d5788ebce965ce1b803de529f11d1066d6e

2017-04-27 16:37 UTC, Nosmoht commented
@gundalow could you please help me with the following issue? I'm pretty sure i'm not allowed to fix it.
```
test/units/modules/system/test_systemd.py:36:161: E501 line too long (165 > 160 characters)
```

2017-04-27 23:43 UTC, mattclay commented
@Nosmoht CI failure was unrelated to this PR. The issue has been resolved and CI is now passing.

2017-04-28 08:24 UTC, Nosmoht commented
Hi Guys,

as all checks have been passed which additional changes are required to remove "Changes requested"?

2017-04-28 11:37 UTC, gundalow commented
@Nosmoht Add a comment `ready_for_review`

see https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#for-pullrequest-submitters for more info

2017-04-28 11:37 UTC, gundalow approved these changes

2017-05-29 08:30 UTC, Nosmoht commented
_ready_for_review_

2018-04-13 00:35 UTC, mattclay commented on lib/ansible/modules/database/oracle/.gitignore
> +.idea
This shouldn't be needed as it already exists in the top-level .gitignore file.

2018-11-20 06:01 UTC, Akasurde commented
@Nosmoht Are you still working on this ? Thanks

needs_info

2019-01-02 10:24 UTC, Nosmoht commented
I'm currently not working on the modules as the PR is now 2 years old. Sorry.

2019-09-03 19:45 UTC, gundalow commented
Given above comment,closing

2019-09-03 19:45 UTC, closed without merging