ec2: `assign_public_ip` should be `None` field
ansible/ansible pull request #20856
Opened 2017-01-31 14:01 UTC by sourabhtk37

This issue was addressed in the `ansible-modules-core` but wasn't reflected here.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
ec2

##### SUMMARY

`assign_public_ip` should be a None type field as default. This issue was addressed in `ansible-modules-core` but change wasn't reflected here.

```

```

2017-01-31 14:15 UTC, sourabhtk37 commented
Sorry,for the flake8 test failure. :) 
forgot about that.

2017-01-31 15:48 UTC, ryansb requested changes

2017-01-31 15:48 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/ec2_lc.py
> +        assign_public_ip = None
The `bool` type handles more cases than just `yes`. To assign the public_ip variable here to be true/false when provided or None by default, all you should need is to set the default to `None` as below, then assign the variable using:

```
module.params.get('assign_public_ip')
```

2017-01-31 15:48 UTC, ryansb commented
Can you please link to where this issue was addressed previously and describe why the change was made?

2017-01-31 15:57 UTC, sourabhtk37 commented
https://github.com/ansible/ansible-modules-core/issues/273/

2017-01-31 20:29 UTC, mattclay commented on lib/ansible/modules/cloud/amazon/ec2_lc.py
> +
CI failure due to:

```
2017-01-31 16:18:54 ERROR: PEP 8: lib/ansible/modules/cloud/amazon/ec2_lc.py:190:1: W293 blank line contains whitespace (legacy)
```

2017-02-01 15:03 UTC, ryansb commented
I think this change is a no-op. The default for `bool` arguments in ansible is `None` , so manually setting it as None doesn't change the behavior. Is there a bug that the current behavior causes?

2017-02-01 15:44 UTC, sourabhtk37 commented
http://stackoverflow.com/questions/41958015/assign-public-ip-no-still-creating-public-ips-ansible-and-ec2/41958738?noredirect=1#comment71098366_41958738

2017-02-01 18:15 UTC, ryansb commented
That issue doesn't provide enough information for me to reproduce this bug. It looks like this is being launched in EC2 classic, and the behavior of the public IP option differs in VPC vs. EC2 Classic environments. 

Your change does not alter the default for the option, because the default value for an unfilled `bool` field is already `None`.

2017-02-03 13:33 UTC, sourabhtk37 commented
Yes, I suppose the error can't be reproduced pertaining to the behaviour of Classic and VPC instance.
Please close this PR if no follow up is there.

2017-02-14 23:12 UTC, closed without merging