Add count attribute to os_server for launching  multiple instances
ansible/ansible pull request #20874
Opened 2017-01-31 17:51 UTC by samvarankashyap

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

os_server

##### ANSIBLE VERSION

```
ansible 2.2.1.0
```

##### SUMMARY

Currently Ansible os_server module does not have support to provision servers based on count.
However , We can observe that rackspace( rax.py ) and AWS EC2 ( ec2.py) modules have support to provision multiple instances based on count. With few tweaks to existing module, it is highly possible to incorporate this feature into os_server module.
In the current PR  following functions are added, such that it would not effect the existing functionality of the os_server module.
- _create_server_count : This function is written in order not to disrupt the existing functionality of _create server. It checks for the existence of the server and creates it if it does not exist else fetches the data and appends it to a list. Finally , the list is returned through the _exit_host_vars_count.
- _delete_server_count : Works similarly to create , checks for existence of the server if it exists deletes the server.  
- _exit_host_vars_count: its a replacement to existing _exit_host_vars as there are multiple server_ids and multiple servers involved.

Fixes #20864 
The updated module supports a count attribute. When given an appropriate integer value, it launches servers on openstack cloud appending the count to the name of sever. Likewise, It also performs the delete operation. 
usage in playbook changes is as follows:
```yaml
---
- name: Launching two instances on openstack using count
  hosts: localhost
  tasks:
    os_server:
      state: "present"
      name: "testvm"
      image: "centos7"
      key_name: "test_keypair"
      flavor: "m1.small"
      network:  "test_network"
      count: 2
```

2017-01-31 19:51 UTC, mattclay commented
Closing and re-opening to trigger CI.

2017-01-31 20:33 UTC, samvarankashyap commented
Though PR https://github.com/ansible/ansible-modules-core/pull/4105 
addresses it to certain extent , it did not consider the idempotent provisioning and deletion of the multiple servers. Further , the output rendered did not contain all list of provisioned server details. 
Current PR addresses the above issues too . 
Further , usage of count feature in the module happen to be almost 30 % faster provisioning time than using Ansible loop construct. ( tested by provisioning and teardown of two instances )

2017-02-28 13:05 UTC, rcarrillocruz requested changes
This needs documentation on the new 'count' param.
Please add it, along with the version it is being added (at the time of this comment should be 2.3)

2017-03-01 17:40 UTC, samvarankashyap commented
@rcarrillocruz : changes requested have been made. Further , I also squashed multiple commits into one single commit. 
Please let me know if you need anything else to be done. 
Thanks.

2017-03-01 20:44 UTC, samvarankashyap commented
@rcarrillocruz : re based and updated.

2017-03-31 12:04 UTC, rcarrillocruz commented
Sorry, I just realized min_count/max_count is already available in Shade.
Therefore, there's no need to add logic into the Ansible module itself.

Closing.

2017-03-31 12:04 UTC, closed without merging

2017-08-31 15:44 UTC, samvarankashyap commented
@rcarrillocruz 
shade min_count , max_count do not return the data specific to each server provisioned . 
Moreover, There is a bug in assigning the floating ips to provisioned servers. 
I feel the above approach much feasible in order multiple instances in a single run.
please see.
https://storyboard.openstack.org/#!/story/2001178