new module for private cert generation
ansible/ansible pull request #20889
Opened 2017-01-31 22:23 UTC by ivanbojer

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
panos_cert_gen_ssh

##### ANSIBLE VERSION

```
ansible 2.1.0.0 
config file = 
configured module search path = Default w/o overrides
```

##### SUMMARY
New panos module that allows for admin user to generate self-signed certificate on the device. This is mainly used for private VPN connections and global protect integrations.

2017-01-31 22:29 UTC, ivanbojer commented
This is the same as https://github.com/ansible/ansible/pull/19881 that I had to abandon due to rebase going wrong.

2017-02-01 01:49 UTC, ivanbojer commented
ready_for_review

2017-02-01 23:05 UTC, abadger commented
@gundalow If you want to continue where the last review left off.

2017-02-07 13:28 UTC, gundalow requested changes
needs_revision

2017-02-07 13:28 UTC, gundalow commented on lib/ansible/modules/network/panos/panos_cert_gen_ssh.py
> +            - IP address (or hostname) of PAN-OS device
All `description:` should be full sentences, ie. start with a capital letter and end with a full stop.

2017-02-07 13:28 UTC, gundalow commented on lib/ansible/modules/network/panos/panos_cert_gen_ssh.py
> +            - filename of the SSH Key to use for authentication (either key or password is required)
`Filename of the SSH Key to use for authentication. Either I(key_filename) or I(password) is required.`

Similar for `password` field.

2017-02-07 13:28 UTC, gundalow commented on lib/ansible/modules/network/panos/panos_cert_gen_ssh.py
> +    module = AnsibleModule(argument_spec=argument_spec, supports_check_mode=False,
What would be needed to support `check_mode`?

2017-02-07 13:28 UTC, gundalow commented on lib/ansible/modules/network/panos/panos_cert_gen_ssh.py
> +        password=dict(),
`no_log=True`

2017-02-07 13:28 UTC, gundalow commented on lib/ansible/modules/network/panos/panos_cert_gen_ssh.py
> +        rsa_nbits=dict(default='2048'),
Default option doesn't match docs

2017-02-07 20:18 UTC, ivanbojer commented on lib/ansible/modules/network/panos/panos_cert_gen_ssh.py
> +            - IP address (or hostname) of PAN-OS device
OK

2017-02-07 20:21 UTC, ivanbojer commented on lib/ansible/modules/network/panos/panos_cert_gen_ssh.py
> +            - filename of the SSH Key to use for authentication (either key or password is required)
Thank you I was not aware of italics mode. Changed!

2017-02-07 20:21 UTC, ivanbojer commented on lib/ansible/modules/network/panos/panos_cert_gen_ssh.py
> +        password=dict(),
OK

2017-02-07 20:21 UTC, ivanbojer commented on lib/ansible/modules/network/panos/panos_cert_gen_ssh.py
> +        rsa_nbits=dict(default='2048'),
Fixed!

2017-02-07 20:23 UTC, ivanbojer commented on lib/ansible/modules/network/panos/panos_cert_gen_ssh.py
> +    module = AnsibleModule(argument_spec=argument_spec, supports_check_mode=False,
I've been thinking about that and what we need to do is implement a functionality that will un-roll the last transaction on the device. If we do this we have to do it across all modules. This is something I plan to do for V2.0.

2017-02-07 20:24 UTC, ivanbojer commented
@gundalow Thank you for the review. I've incorporated all of the changes except check_mode per my comments.

2017-02-07 20:24 UTC, ivanbojer commented
ready_for_review

2017-02-08 08:31 UTC, gundalow approved these changes

2017-02-08 08:35 UTC, gundalow commented
On Ansibot's maintainers list we currently have:
`network/panos/: ivanbojer`

The above sets who should be notified when PRs or issues are raised against the panos modules. Is there anyone else we can add to that list?

2017-02-08 21:47 UTC, ivanbojer commented
@gundalow Lets add @jtschichold two but I might have to revise that later on:

2017-02-09 09:40 UTC, gundalow commented on lib/ansible/modules/network/panos/panos_cert_gen_ssh.py
> +requirements:
Can you please add a `note:` section to say that checkmode isn't supported. Then I think we will be good to merge

2017-02-09 21:20 UTC, ivanbojer commented on lib/ansible/modules/network/panos/panos_cert_gen_ssh.py
> +requirements:
OK, done!

2017-02-11 15:34 UTC, gundalow approved these changes

2017-02-11 15:34 UTC, merged

2017-02-11 15:34 UTC, gundalow commented
Merged, thanks

2017-02-11 15:39 UTC, gundalow commented
Added to changelog: https://github.com/ansible/ansible/pull/21286
Added to Ansibullbot: https://github.com/ansible/ansibullbot/pull/343
Change `note:` to `notes:` https://github.com/ansible/ansible/pull/21287 - Spotted during final review, easier for me to fix post merging

Thanks for the new module, it's been merged into `devel` and therefore will be included in 2.3