Lambda policy module
ansible/ansible pull request #20890
Opened 2017-01-31 22:33 UTC by michael-dev2rights

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME
lambda_policy 

##### ANSIBLE VERSION

```
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY

This is a proposal to submit [pjodouin's lambda_policy module](https://github.com/pjodouin/ansible-lambda/blob/master/modules/lambda_policy.py) from his [ansible lambda collection](https://github.com/pjodouin/ansible-lambda) as discused [in this ticket](https://github.com/pjodouin/ansible-lambda/issues/10) and irc.

```
ansible  localhost -m lambda_policy -a 'function_name=fred statement_id=fred principal=apigateway.amazonaws.com action=lambda:InvokeFunction region=eu-west-1'
```

output before 
```
 [WARNING]: provided hosts list is empty, only localhost is available

localhost | FAILED! => {
    "failed": true, 
    "msg": "The module lambda_policy was not found in configured module paths. Additionally, core modules are missing. If this is a checkout, run 'git pull --rebase' to correct this problem."
}
```

output after
```
 [WARNING]: provided hosts list is empty, only localhost is available

localhost | SUCCESS => {
    "ansible_facts": {
        "lambda_policy_action": "none"
    }, 
    "changed": false
}
```

2017-02-02 07:16 UTC, willthames requested changes

2017-02-02 07:16 UTC, willthames commented on lib/ansible/modules/cloud/amazon/lambda_policy.py
> +from ansible.module_utils.basic import *
Should be changed to new style imports. Also then no need to set HAS_BOTO3, you can import it.

2017-02-02 07:16 UTC, willthames commented on lib/ansible/modules/cloud/amazon/lambda_policy.py
> +            alias=dict(required=False, default=None),
required=False, default=None is default for an argument

2017-02-02 07:16 UTC, willthames commented on lib/ansible/modules/cloud/amazon/lambda_policy.py
> +    api_params = set_api_params(module, params)
I believe this is equivalent to  `api_params = snake_dict_to_camel_dict(module.params)` - `pc` and `set_api_params` should not be required.

2017-02-02 07:16 UTC, willthames commented on lib/ansible/modules/cloud/amazon/lambda_policy.py
> +        required_together=[]
get rid of this if it's empty

2017-02-09 20:05 UTC, ryansb commented
needs_revision

2017-04-06 05:50 UTC, willthames commented
Do you have much time to work on this at the moment or shall I just submit a PR on your fork?

2017-04-07 13:37 UTC, michael-dev2rights commented
@willthar I'm working on it today and will merge your pull request shortly one I get tests running without it.

2017-05-16 20:41 UTC, ryansb commented
Is this still waiting on @willthames PR?

2017-05-20 07:48 UTC, michael-dev2rights commented
@ryansb this is in a sense really waiting for the merge of https://github.com/ansible/ansible/pull/24722 because I want some integration tests for lambda_policy when I merge it and those integration tests would really want to use the lambda module.  I'll then merge in Willthames work and add integration tests to this.

2017-05-20 08:26 UTC, michael-dev2rights commented
@ryansb actually; review that a bit;  Lambda policy integration tests really make sense once we have a policy limited event source in the modules.  This means API Gateway so really I'd also like to see https://github.com/ansible/ansible/pull/20230 merged ASAP so that then lambda policy can be demonstrated to be actually doing something valuable in the integration tests.  In both cases I believe the pull requests are ready to merge.

2017-05-25 06:24 UTC, willthames commented
shipit - `pc` shouldn't be required but this code is good enough.

2017-05-25 06:26 UTC, willthames requested changes

2017-05-25 06:26 UTC, willthames commented on lib/ansible/modules/cloud/amazon/lambda_policy.py
> +        if module_param:
This might do weird things for module parameters set `False` - this should probably be `if module_param is not None`

2017-08-08 17:32 UTC, michael-dev2rights commented on lib/ansible/modules/cloud/amazon/lambda_policy.py
> +        if module_param:
fixed in https://github.com/ansible/ansible/pull/24951

2017-08-08 17:34 UTC, michael-dev2rights commented
This PR can now be replaced with https://github.com/ansible/ansible/pull/24951 since a) we have all the other pre-requisites for the test cases merged in and b) we should have the test permissions set up to be able to include all tests in CI.  Closing it and moving future work to that PR.

2017-08-08 17:34 UTC, closed without merging