Windows: Add Warn mechanism for modules
ansible/ansible pull request #20903
Opened 2017-01-31 23:34 UTC by dagwieers

Similar to what already exists for python modules.

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

module_utils/powershell.ps1

##### ANSIBLE VERSION

v2.3

##### SUMMARY

Added a Warn function to assist modules in managing warnings. This functions ensures that if there is not warnings-attribute (or if it isn't a list) the attribute is added correctly and the message is appended to the list.

2017-02-01 11:01 UTC, jhawkesworth commented
This is great, but just wondering if we should stick with powershell naming convention i.e. Verb-Noun so instead of Warn you'd probably have something like Write-Warning or perhaps Write-AnsibleWarning?

Personally its not something I'm particularly keen on but worth considering, because as soon as its out there its going to get used (has been already in your other PRs) - its effectively adding to the ansible module (powershell) API.  Its a tricky balance as your function names would be more familiar to python module authors.

2017-02-01 11:09 UTC, dagwieers commented
The whole Windows module infrastructure is going to be rewritten by @nitzmahone anyhow, but in this case I wanted to stay close to the python modules. I try to do the same for the option to Set-AnsibleParam for instance, I hate the `--failifempty` (should have been `-required`) or `-ValidateSet` (should have been `-choices`).

So I understand that the Windows/Powershell world has their own way of doing things, but I wouldn't deviate from what Ansible is doing. IMO it is going to be much easier to document this if we stick to common practices as much as possible and doesn't alienate one group from the other.

I would have preferred warn() instead, but that's less an issue because Powershell doesn't care anyhow :-)

2017-02-01 17:41 UTC, bcoca commented
@nitzmahone is on PTO right now, but I believe he'll agree that we keep the API as close as possible.

2017-02-07 10:42 UTC, jhawkesworth commented
Wouldn't want to hold up this going in, just wanted to flag up concern.  More important to have the api capability than to make it instantly recognisable to those familiar with powershell.

shipit

2017-02-07 10:46 UTC, dagwieers commented
@jhawkesworth No worries, we can wait on @nitzmahone 's return to decide. I know some of the interfaces will be changed in the future, but since we don't know whether this will hit v2.3 or later I prefer we don't focus too much on that right now and add as much functionality to make it on-par with Python modules.

It is going to be much easier to replace A with B once it is needed, then to have to revisit the code and refactor such support into it after the fact.

2017-02-09 02:15 UTC, nitzmahone commented
My only issue with adding new global functions to to the API surface area at this point is that anything we add will have to get dragged around for at least two releases before we could remove it (since we can't know what private modules are using). OTOH, since the new wrapper supports arbitrary module_utils inclusions (and powershell.ps1 is not strictly required anymore), anything new won't be defined in powershell.ps1 anyway, so we can pretty much consider that file "legacy" already. 

As far as naming goes, I think @jhawkesworth is on the right track- I'd vote for `Add-Warning`/`Add-DeprecationWarning` (since we're not "writing" it per-se like Write-Output/Error/etc). 

I'm OK to merge this with that name change (or feel free to suggest others)...

2017-02-09 09:55 UTC, dagwieers commented
@nitzmahone Thanks for the feedback. Implemented as requested.

2017-02-09 11:02 UTC, jhawkesworth commented
Nice.

shipit

2017-02-09 16:49 UTC, nitzmahone requested changes

2017-02-09 16:49 UTC, nitzmahone commented on lib/ansible/modules/windows/win_regedit.ps1
> +    Warn $result "Please use path: HKCC:\... instead of path: $path"
Needs rename :)

2017-02-09 16:49 UTC, nitzmahone commented on lib/ansible/modules/windows/win_command.ps1
> +$result = @{
I don't really have a problem with this placement, but this seems like an arbitrary and completely unrelated change.

2017-02-09 16:49 UTC, nitzmahone commented on lib/ansible/modules/windows/win_shell.ps1
> +$result = @{
Ditto

2017-02-09 18:41 UTC, nitzmahone approved these changes

2017-02-09 18:41 UTC, merged

2017-02-09 18:42 UTC, dagwieers commented on lib/ansible/modules/windows/win_regedit.ps1
> +    Warn $result "Please use path: HKCC:\... instead of path: $path"
I didn't realize these changes were in this PR too.

2017-02-09 18:42 UTC, dagwieers commented on lib/ansible/modules/windows/win_command.ps1
> +$result = @{
I didn't realize these changes were in this PR too.

2017-02-09 18:42 UTC, dagwieers commented on lib/ansible/modules/windows/win_shell.ps1
> +$result = @{
I didn't realize these changes were in this PR too.