add gce_template.py
ansible/ansible pull request #20918
Opened 2017-02-01 09:43 UTC by GwenaelPellenArkeup

gce template manage GCE Instance Templates in Google Cloud Plateform.

ISSUE TYPE

New Module Pull Request

COMPONENT NAME

gce_template

ANSIBLE VERSION

ansible 2.3

SUMMARY

Module can create and detroy Intance Templates.

2017-02-01 09:51 UTC, GwenaelPellenArkeup commented
sorry everybody, i make a cleaner pull-request.

2017-02-02 01:05 UTC, supertom requested changes
Thanks for the PR.  Just some changes based on style/formatting.

2017-02-02 01:05 UTC, supertom commented on lib/ansible/modules/cloud/google/gce_template.py
> +    """Retrieves instance template informations
No 's' on information.

2017-02-02 01:05 UTC, supertom commented on lib/ansible/modules/cloud/google/gce_template.py
> +    """Create on instance template
"an instance template", not "on instance template".

2017-02-02 01:05 UTC, supertom commented on lib/ansible/modules/cloud/google/gce_template.py
> +
delete blank line here.

2017-02-02 01:05 UTC, supertom commented on lib/ansible/modules/cloud/google/gce_template.py
> +
Please delete blank line

2017-02-02 01:05 UTC, supertom commented on lib/ansible/modules/cloud/google/gce_template.py
> +    gce_template:
please pull gce_template to the left margin.

2017-02-02 01:05 UTC, supertom commented on lib/ansible/modules/cloud/google/gce_template.py
> +      "monitoring", "sql", "sql-admin", "storage-full", "storage-ro",
remove 'sql' from the choices list.  It will be removed from gce.py soon.

2017-02-02 01:05 UTC, supertom commented on lib/ansible/modules/cloud/google/gce_template.py
> +
please delete blank line here.

2017-02-02 01:05 UTC, supertom commented on lib/ansible/modules/cloud/google/gce_template.py
> +        module.fail_json(msg="no instance template !")
delete space between template and '!'

2017-02-02 01:05 UTC, supertom commented on lib/ansible/modules/cloud/google/gce_template.py
> +author: "Gwenael Pellen <gwenael.pellen@arkeup.com>"
Please include your github ID in the author line, in between your name and email address.  For example:

`"my name (@my-github) <my-email@example.com>"`

2017-02-02 01:08 UTC, supertom commented
@GwenaelPellenArkeup thanks for submitting.  I tested it out and it works as expected.  I'm OK with letting it in as-is provided the style/formatting changes are made.  Going forward, someone will need to consolidate the duplicated code between [gce.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/google/gce.py) and this one, but, I don't want to keep the functionality from being included due to housekeeping.

2017-02-02 10:49 UTC, GwenaelPellenArkeup commented on lib/ansible/modules/cloud/google/gce_template.py
> +      "monitoring", "sql", "sql-admin", "storage-full", "storage-ro",
remove 'sql-admin' too ?

2017-02-07 18:27 UTC, supertom commented
@GwenaelPellenArkeup thanks for the changes.  re-tested and LGTM!  @ryansb I'm OK with merging this.

2017-02-08 21:07 UTC, supertom commented
Hi @GwenaelPellenArkeup, in talking with @ryansb, we should rename this gce_instance_template to be more specific.  Sound good?

2017-02-10 02:06 UTC, supertom requested changes
Thanks for the rename.  Would you please update the DOCUMENTATION and EXAMPLE blocks as well?  I see a few references to gce_template rather than gce_instance_template.

Thanks!

2017-02-10 18:44 UTC, ryansb requested changes

2017-02-10 18:44 UTC, ryansb commented on lib/ansible/modules/cloud/google/gce_instance_template.py
> +       of Compte Engine of Google Cloud Plateform.
s/Compte/Compute/

s/Plateform/Platform/

2017-02-10 18:44 UTC, ryansb commented on lib/ansible/modules/cloud/google/gce_instance_template.py
> +            source=dict(),
In the docs you mention that source and image cannot both be applied. Can you enforce this by adding an argument like this: `mutually_exclusive=[['source', 'image']],` around line 555?

2017-02-10 18:44 UTC, ryansb commented on lib/ansible/modules/cloud/google/gce_instance_template.py
> +        Cannot specify both 'image' and 'source'.
So image_family and image_source are required together, but neither can be specified if source is specified? Is that right?

2017-02-10 18:44 UTC, ryansb commented on lib/ansible/modules/cloud/google/gce_instance_template.py
> +            disk_type=dict(default='pd-standard'),
Use an option type here, to allow only valid disk types (I guess `pd-ssd` and `pd-standard`?). @supertom are there more options?

2017-02-10 18:44 UTC, ryansb commented on lib/ansible/modules/cloud/google/gce_instance_template.py
> +      - The Subnetwork resource for this instance.
What is the format for this field? Is it an ID, name, or something else?

2017-02-10 18:44 UTC, ryansb commented on lib/ansible/modules/cloud/google/gce_instance_template.py
> +  can_ip_forword:
s/forword/forward/

2017-02-13 12:15 UTC, GwenaelPellenArkeup commented on lib/ansible/modules/cloud/google/gce_instance_template.py
> +        Cannot specify both 'image' and 'source'.
If the souce is specified neither image nor image_family should be used.
Otherwise image or image_family must be specified.

2017-02-13 14:38 UTC, ryansb approved these changes

2017-02-13 14:39 UTC, ryansb commented
shipit

2017-02-20 13:24 UTC, bjolivot commented
ok after test
shipit

2017-02-20 13:38 UTC, gundalow requested changes

2017-02-20 13:38 UTC, gundalow commented on lib/ansible/modules/cloud/google/gce_instance_template.py
> +      - desired state of instance template
Descriptions need to be full sentences, Capital letters & full stops

Please see docs.ansible.com/ansible/dev_guide/developing_modules_documenting.html for more detail

2017-02-20 13:38 UTC, gundalow commented on lib/ansible/modules/cloud/google/gce_instance_template.py
> +      - instance template size to use, use 'f1-micro' by default
Don't document default, that's what the `default:` field is for docs.ansible.com/ansible/dev_guide/developing_modules_documenting.html

2017-02-20 13:38 UTC, gundalow commented on lib/ansible/modules/cloud/google/gce_instance_template.py
> +    required: false
`required: false` files can be removed, see docs.ansible.com/ansible/dev_guide/developing_modules_documenting.html for more info

2017-02-20 13:38 UTC, gundalow commented on lib/ansible/modules/cloud/google/gce_instance_template.py
> +        Cannot specify both 'image' and 'source'.
`Cannot specify both I(image) and I(source).`
http://docs.ansible.com/ansible/dev_guide/developing_modules_documenting.html#formatting-options

2017-02-20 13:38 UTC, gundalow commented on lib/ansible/modules/cloud/google/gce_instance_template.py
> +        Cannot specify both 'image' and 'source'.
`Cannot specify both I(image) and I(source).`
http://docs.ansible.com/ansible/dev_guide/developing_modules_documenting.html#formatting-options

2017-02-20 13:38 UTC, gundalow commented on lib/ansible/modules/cloud/google/gce_instance_template.py
> +        Cannot specify both 'image' and 'source'.
The doesn't appear to match the code
```
 +        mutually_exclusive=[['source', 'image']],
 +        required_one_of=[['image', 'image_family']],
 +        supports_check_mode=True
```

Please also use `I(...)` for option names

2017-02-20 13:38 UTC, gundalow commented on lib/ansible/modules/cloud/google/gce_instance_template.py
> +        True by default.
Remove default from `description:`

2017-02-20 13:38 UTC, gundalow commented on lib/ansible/modules/cloud/google/gce_instance_template.py
> +        If 'ephemeral' (default), a new non-static address will be
I(ephemeral)

2017-02-20 13:38 UTC, gundalow commented on lib/ansible/modules/cloud/google/gce_instance_template.py
> +        used.  If 'None', then no external address will
I(None)

2017-02-20 13:38 UTC, gundalow commented on lib/ansible/modules/cloud/google/gce_instance_template.py
> +      - a comma-separated list of tags to associate with the instance
Might be better to define this as `type='list'`

2017-02-20 13:38 UTC, gundalow commented on lib/ansible/modules/cloud/google/gce_instance_template.py
> +  name: my-test-instance-template
Missing `-` before `name:`

2017-02-20 13:38 UTC, gundalow commented on lib/ansible/modules/cloud/google/gce_instance_template.py
> +EXAMPLES = '''
Please review http://docs.ansible.com/ansible/dev_guide/developing_modules_documenting.html#examples-block

2017-02-21 12:13 UTC, gundalow approved these changes

2017-02-21 12:36 UTC, GwenaelPellenArkeup commented
bot_status

2017-02-21 13:01 UTC, GwenaelPellenArkeup commented
shipit

2017-02-21 21:36 UTC, ryansb submitted a review, later dismissed

2017-02-21 21:36 UTC, ryansb commented on lib/ansible/modules/cloud/google/gce_instance_template.py
> +RETURN = '''
Please add docs on what this module returns.

2017-02-24 20:17 UTC, GwenaelPellenArkeup commented on lib/ansible/modules/cloud/google/gce_instance_template.py
> +RETURN = '''
Is empty because no new return variable returned.
Only standard return variable used.

2017-02-24 20:31 UTC, ryansb commented on lib/ansible/modules/cloud/google/gce_instance_template.py
> +        module.fail_json(
This `else` is not needed, Ansible will verify that only present/absent are passed as the state.

2017-03-01 21:50 UTC, merged