cloud: ovirt: add snapshots module
ansible/ansible pull request #20936
Opened 2017-02-01 19:17 UTC by machacekondra

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

ovirt_snapshots

##### ANSIBLE VERSION

```
2.3.0
```

##### SUMMARY

This PR adds one new module for managing oVirt snaphosts and one new module to retrive snapshots facts.

```

```

2017-02-01 19:18 UTC, machacekondra commented
shipit

2017-02-01 19:18 UTC, machacekondra commented
@ryansb

2017-02-01 19:57 UTC, mattclay commented
CI failure due to missing docs fragment:

```
2017-02-01 19:27:21 ============================================================================
2017-02-01 19:27:21 lib/ansible/modules/cloud/ovirt/ovirt_snapshots_facts.py
2017-02-01 19:27:21 ============================================================================
2017-02-01 19:27:21 ERROR: DOCUMENTATION fragment missing: ovirt_snapshots
```

2017-02-01 20:33 UTC, machacekondra commented
Thanks, fixed.

2017-02-02 18:52 UTC, ryansb requested changes

2017-02-02 18:52 UTC, ryansb commented on lib/ansible/modules/cloud/ovirt/ovirt_snapshots.py
> +EXAMPLES = '''
In addition to examples, can you add docs on `RETURN` like what's in the `snapshot_facts` module below?

2017-02-02 21:25 UTC, ryansb approved these changes

2017-02-02 21:28 UTC, ryansb commented
Looks good, just made some tiny changes to pass style checks. Once CI passes proper I can merge. 😄

2017-02-02 21:34 UTC, merged