wait_for: change file check to handle directories and sockets
ansible/ansible pull request #20979
Opened 2017-02-02 16:24 UTC by Ferroin

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
wait_for

##### ANSIBLE VERSION
Based on: 8d5f4dda06d876a380f25afc2958f951544ff4ca
Originally discovered with:
```
ansible 2.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY
open(path) throws an error when called on a directory or UNIX socket,
and therefore a check to ensure that the path is absent will always
succeed when there is a directory or file located there.

This updates the check to use os.access(path, os.F_OK) instead, which
instead just checks that the path exists instead of trying to open it as
a file, and therefore properly handles directories and sockets.

This causes a slight semantic change in how permissions are handled.
The existing code will fail to work correctly if the user running the
module on the managed host has no read access to the path specified.
The new code will work correctly in that situation.
Both versions fail if the user can't traverse the parent directory.

Fixes: #20870 

I've also added a check to the try block to catch OSError.  I've seen this call fail with an OSError on rare occasion in the face of odd extended permissions (usually MAC configuration) in cases where it should technically return False.  In such cases, the file is functionally inaccessible to the user making the call, so it's essentially not there, but it can't be created by them either.  This particular issue also technically affected the original code too, and should probably be documented somewhere.  I can make a pull request to add this to the documentation if desired.

2017-02-02 16:40 UTC, gregswift commented
nice and simple fix. 👍 

If you want to update the doc in the module with that information that would be good. that shoud fit inside the scope of this PR.

2017-02-02 18:13 UTC, Ferroin commented
OK, I'll look at getting that done before the weekend.  Would you prefer two separate commits or would you like me to just squash that into the existing commit?

2017-02-03 13:07 UTC, Ferroin commented
I just updated after rebasing and adding the documentation.  I've got it listing version 2.4 as the first that fixes this because I assume that will be the next release, if I'm wrong about it feel free to change it.

I also added a note about this module following symbolic links when checking paths.  This caught me by surprise when I was testing (most of the other modules seem to not follow symbolic links), so I figured it should probably be documented too.

2017-02-07 17:03 UTC, gregswift commented
shipit

2017-02-07 17:03 UTC, gregswift commented
shipit

2017-02-15 15:46 UTC, Ferroin commented
Bumping this since it hasn't gone anywhere in a week.

2017-02-16 20:46 UTC, gregswift commented
bot_status

2017-02-16 21:34 UTC, gregswift commented
@Ferroin needs more shipits because its supported by core.

```core: Members of the Ansible organization typically do all the maintainence on this module, so only they can approve changes. Expect reviews to take longer than most other modules because of the volume the core team has on a daily basis.```

2017-02-17 13:12 UTC, Ferroin commented
Ah, I had forgotten that this was part of the core modules.

2017-03-22 11:56 UTC, Ferroin commented
Bumping this again in the hope that I won't have to continue running a locally patched version for the foreseeable future...

2017-06-06 02:44 UTC, gregswift commented
@bcoca (who else should i prod?) can we check this out? i already shipit'd it but with the merge of the git repos and this being a core module i'm not special enough anymore :D

2017-06-08 09:57 UTC, gundalow commented
Rebase needed

2017-06-09 14:58 UTC, Ferroin commented
And of course I forgot to fix the PEP8 errors when rebasing...

2017-06-09 16:13 UTC, gregswift requested changes

2017-06-09 16:13 UTC, gregswift commented on lib/ansible/modules/utilities/logic/wait_for.py
> +import os
Youll want to rebase again i think some changes where just made around this.

2017-06-09 16:44 UTC, Ferroin commented on lib/ansible/modules/utilities/logic/wait_for.py
> +import os
Thanks for the heads up about that.

2017-06-12 14:05 UTC, Ferroin commented
ready_for_review

2017-06-12 21:25 UTC, gregswift commented
ship_it

2017-07-19 13:14 UTC, AnderEnder commented
@Ferroin, there is a merge conflict

2017-07-19 13:22 UTC, Ferroin commented
Just rebased and fixed the conflict.

2017-09-15 14:37 UTC, Ferroin commented
Poking this yet again, no merge conflicts and all checks are passing...

2017-09-19 04:23 UTC, gregswift commented
@Ferroin so wednesdays are meeting day for ansible community. maybe if you can make the 2pn (CDT) working group meeting you could get some more traction? #ansible-meeting on freenode.

2017-10-11 01:47 UTC, lae commented
I just happened to hit the bug this fixes. Any chance of getting this merged soon?

2017-11-22 21:15 UTC, hvhaugwitz commented
I'm also affected by this issue. Please consider to merge this pull request.

2017-11-27 14:01 UTC, Ferroin commented
@hvhaugwitz @lae  If you can confirm here that the PR fixes things for you, it might help finally get the attention of the core team members again so that it could finally get merged.

2017-11-27 14:04 UTC, Ferroin commented
bot_broken

The needs_revision tag from 2017-06-09 never got removed despite multiple revisions occurring since then.

2017-11-27 18:26 UTC, lae commented
This PR fixes the immediate issue I was facing regarding ensuring directories were absent (the builds in ansible-role-proxmox above failed because of a different underlying issue).

2017-11-28 17:30 UTC, hvhaugwitz commented
@Ferroin The PR fixes my issue regarding watching for the absence of files the user cannot open (due to file permissions) but see (due to directory permissions).

2017-12-07 00:09 UTC, mattclay commented
bot_status

2017-12-13 17:09 UTC, maxamillion approved these changes

2017-12-13 17:10 UTC, merged