Adding modules to manage Cloudera Manager cluster.  http://www.cloudera.com/
ansible/ansible pull request #20996
Opened 2017-02-03 01:30 UTC by sanicheev

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
module_utils/cloudera.py
modules/clustering/cloudera/cloudera_cluster.py
modules/clustering/cloudera/cloudera_hdfs_ha.py
modules/clustering/cloudera/cloudera_host.py
modules/clustering/cloudera/cloudera_kerberos.py
modules/clustering/cloudera/cloudera_license.py
modules/clustering/cloudera/cloudera_misc.py
modules/clustering/cloudera/cloudera_oozie_ha.py
modules/clustering/cloudera/cloudera_parcel.py
modules/clustering/cloudera/cloudera_role.py
modules/clustering/cloudera/cloudera_service.py
modules/clustering/cloudera/cloudera_yarn_ha.py

##### ANSIBLE VERSION
```
2.1.2.0
```

##### SUMMARY
```
Ansible changes were made by a http://www.contexti.com
Added library helper in module_utils : cloudera.py
Added cloudera_cluster.py in clustering module section to manage cloudera cluster
Added cloudera_hdfs_ha.py in clustering module section to enable HDFS HA
Added cloudera_host.py in clustering module section to provision and add hosts into cloudera cluster
Added cloudera_kerberos.py in clustering module section to configure services for kerberos
Added cloudera_license.py in clustering module section to manage cloudera license
Added cloudera_misc.py in clustering module section to perform misc actions such as: start,restart, deploy service configuration and etc.
Added cloudera_oozie_ha.py in clustering module section to enable HA for OOZIE
Added cloudera_parcel.py in clustering module section to install and activate parcel in cluster
Added cloudera_role.py in clustering module section to manage cloudera service
Added cloudera_service.py in clustering module section to manage cloudera role
Added cloudera_yarn_ha.py in clustering module section to enable HA for YARN

Modules are using cm_api client package built by http://www.cloudera.com/.
Link to its repo : https://github.com/cloudera/cm_api
```

2017-02-03 01:59 UTC, mattclay commented on lib/ansible/module_utils/cloudera.py
> +        dictionary = { value:key for key,value in dictionary.items() }
CI failure due to python 2.4 syntax error:

```
2017-02-03 01:32:20 Compiling ./lib/ansible/module_utils/cloudera.py ...
2017-02-03 01:32:20   File "./lib/ansible/module_utils/cloudera.py", line 149
2017-02-03 01:32:20     dictionary = { value:key for key,value in dictionary.items() }
2017-02-03 01:32:20                                ^
2017-02-03 01:32:20 SyntaxError: invalid syntax
```

2017-02-04 08:04 UTC, gundalow commented
Hi, can you please split this into multiple PRs. 

The first PR should have
* A single module 
* __init__.py
* module_utils

Once that has been reviewed and merged you can raise one PR per module for the remaining ones. 

Thanks

2017-02-04 08:10 UTC, gundalow requested changes
I've done a quick review of the first module only. Once you've updated this or so there is only a single module I will review again.

2017-02-04 08:10 UTC, gundalow commented on lib/ansible/modules/clustering/cloudera/cloudera_cluster.py
> +version_added: '2.2.0.2'
`"2.3"`

2017-02-04 08:10 UTC, gundalow commented on lib/ansible/modules/clustering/cloudera/cloudera_hdfs_ha.py
> +short_description: Cloudera Manager enable HA for HDFS.
No full stop needed on short description

2017-02-04 08:10 UTC, gundalow commented on lib/ansible/modules/clustering/cloudera/cloudera_hdfs_ha.py
> +    - This module will enable HA for HDFS. Please take in consideration that ZOOKEEPER service should be up and running!
Delete "This module", so it reads
"Enable HA for HDFS.... '

2017-02-04 08:10 UTC, gundalow commented on lib/ansible/modules/clustering/cloudera/cloudera_hdfs_ha.py
> +    from ansible.module_utils.basic import *
Generally the imports go before the "if main" 
Only import what you need, rather than `*`

2017-02-04 09:41 UTC, sanicheev commented
Created another PR in order to have clean history : https://github.com/ansible/ansible/pull/21036

2017-02-04 09:41 UTC, closed without merging