Add Check Mode capability to kernel_blacklist module
ansible/ansible pull request #21007
Opened 2017-02-03 13:30 UTC by imranh2

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
modules/system/kernel_blacklist

##### ANSIBLE VERSION
```
ansible 2.3.0
```

##### SUMMARY

Added the ability for the kernel_blacklist module to run under Check Mode.

Simply redirect writes to /dev/null

Module will not make any changes to the local system but will report changes if there are any that it would have made.

```

```

2017-02-03 17:12 UTC, matze commented
Great, thanks :+1: shipit

2017-02-03 17:18 UTC, ovcharenko commented
shipit

2017-02-04 03:38 UTC, tmshn requested changes

2017-02-04 03:38 UTC, tmshn commented on lib/ansible/modules/system/kernel_blacklist.py
> +        filename = '/dev/null'
Using `os.devnull` might be better.

https://docs.python.org/2/library/os.html#os.devnull

2017-02-04 03:42 UTC, tmshn commented
IMHO, it would be nicer if it
- read from `blacklist_file`
- but write to nothing (`/dev/null`).

Current implementation (both reading from and writing to `/dev/null`) always gives `changed=True`.

2017-02-04 11:42 UTC, imranh2 commented
@tmshn yeah, I'll swap in `os.devnull`.

@tmshn and @matze the current module will always make a change to your system if 'filename' doesn't exist even if you specify a module to be 'absent' (weird edge case but you got to think about these things), I'd certainly count making an empty file a change, if the file doesn't already exist. So this would go back to me making changes to the 'Blacklist' constructor again like with my previous PR. So my next patch will:

* Pass a bool into 'Blacklist' that'll just be 'module.check_mode'
* Move detection and creation of a file to a separate function within 'Blacklist'
* If there's no file on the system, set 'self.filename' to `os.devnull` AND mark a change, as the module would have created an empty file.
* Whenever a 'self.filename' is being opened in a mode where changes can be made, replace with an if statement that check 'self.checkmode' and if true then open up 'os.devnull' instead

I think I'll create a completely separate PR for making the module not always initially creating/opening `blacklist_file` if it doesn't have to. And maybe another for the module to do cleanup if it removes the last module from the blacklist file.

2017-02-04 11:58 UTC, imranh2 commented
ready_for_review

2017-02-05 05:50 UTC, tmshn approved these changes

2017-02-05 05:50 UTC, tmshn commented
Looks OK, shipit :shipit:

2017-02-05 10:18 UTC, matze commented
shipit

2017-02-06 17:48 UTC, jctanner commented
this PR lost sync with shippable, so I need to re-open it.

2017-02-06 18:00 UTC, merged