New dynamic inventory for Apstra AOS
ansible/ansible pull request #21045
Opened 2017-02-05 03:39 UTC by dgarros

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
It' s a dynamic inventory, not a module per say. 
I put it under `contrib/inventory`

##### ANSIBLE VERSION
```
ansible 2.3.0 (aos_ip_pool 058e112d07) last updated 2017/02/03 18:14:02 (GMT -700)
  config file =
  configured module search path = Default w/o overrides
```

##### SUMMARY
I'm working for Apstra, we are making to automate Datacenter Networks and we are developed a dozen of Ansible module and one dynamic inventory to control our product with Ansible.

This PR is regarding the Dynamic Inventory and I also opened a PR for our first module #21044 

This dynamic inventory will get the list of devices managed by AOS and construct a dynamic inventory for it. It will also collect facts and information about the devices and populate variables for each device. Also, devices are assigned to several groups dynamically based on their type.  

Looking forward to your feedback

2017-02-06 19:42 UTC, alikins requested changes

2017-02-06 19:42 UTC, alikins commented on contrib/inventory/apstra_aos.py
> +import xmlrpclib
This import is not used.

2017-02-06 19:42 UTC, alikins commented on contrib/inventory/apstra_aos.py
> +    from apstra.aosom.exc import SessionError, SessionRqstError, LoginError
contrib/inventory/apstra_aos.py:47:5: F401 'apstra.aosom.exc.SessionRqstError' imported but unused
contrib/inventory/apstra_aos.py:47:5: F401 'apstra.aosom.exc.LoginError' imported but unused
contrib/inventory/apstra_aos.py:47:5: F401 'apstra.aosom.exc.SessionError' imported but unused

None of those imports appear to be used.

2017-02-06 19:42 UTC, alikins commented on contrib/inventory/apstra_aos.py
> +class AosInventory(object):
pep8 warning:
contrib/inventory/apstra_aos.py:268:1: E302 expected 2 blank lines, found 0

2017-02-06 19:42 UTC, alikins commented on contrib/inventory/apstra_aos.py
> +AosInventory()
pep8 warning:
E305 expected 2 blank lines after class or function definition, found 1

2017-02-06 19:42 UTC, alikins commented on contrib/inventory/apstra_aos.py
> +            ##   if it's create a new group
pep8/flake8 doesnt really like the '##' comments. Minor, but it keeps pep8 happy:
contrib/inventory/apstra_aos.py:286:9: E265 block comment should start with '# '
contrib/inventory/apstra_aos.py:288:9: E265 block comment should start with '# '
contrib/inventory/apstra_aos.py:298:9: E265 block comment should start with '# '
contrib/inventory/apstra_aos.py:300:9: E265 block comment should start with '# '
contrib/inventory/apstra_aos.py:316:13: E266 too many leading '#' for block comment
contrib/inventory/apstra_aos.py:333:13: E266 too many leading '#' for block comment
contrib/inventory/apstra_aos.py:334:13: E266 too many leading '#' for block comment
contrib/inventory/apstra_aos.py:342:9: E265 block comment should start with '# '
contrib/inventory/apstra_aos.py:344:9: E265 block comment should start with '# '

2017-02-06 19:42 UTC, alikins commented on contrib/inventory/apstra_aos.py
> +AosInventory()
I'd recommend adding a main() and a 'if __name__ == __main__: main()' here, but thats optional.

2017-02-08 01:35 UTC, dgarros commented
@alikins thanks for your feedback. 

I made some changes to address your points, I think it covers all of them.

2017-02-09 17:32 UTC, alikins commented on contrib/inventory/apstra_aos.py
> +import ConfigParser
May want to use the configparser in 'ansible.compat.six.moves.configparser' here. Otherwise there are py2/py3 compat issues.

2017-02-09 17:41 UTC, dgarros commented
@alikins, I changed the library as suggested, thanks

2017-02-09 17:43 UTC, alikins approved these changes

2017-02-09 18:10 UTC, merged