New Module : aos_ip_pool as part of network/apstra
ansible/ansible pull request #21044
Opened 2017-02-05 03:29 UTC by dgarros

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
network/apstra/aos_ip_pool

##### ANSIBLE VERSION
```
ansible 2.3.0 (aos_ip_pool 058e112d07) last updated 2017/02/03 18:14:02 (GMT -700)
  config file =
  configured module search path = Default w/o overrides
```

##### SUMMARY
I'm working for [Apstra](http://www.apstra.com/), we are making to automate Datacenter Networks and we are developed a dozen of Ansible module and one dynamic inventory to control our product with Ansible.   
We have tried to follow Ansible's best practices as much as possible, all our modules are idempotent and support the mode `--check`. 

This pull request is the first one, once a got feedback on this one I will open other PR for the other modules.

The module `aos_ip_pool` is used to manage IP Pool on our solutions.  

Looking forward to your feedback

2017-02-06 19:24 UTC, gundalow requested changes

2017-02-06 19:24 UTC, gundalow commented on lib/ansible/module_utils/aos.py
> +# it under the terms of the GNU General Public License as published by
`module_utils` should be BSD. You can copy the text from another library in this module

2017-02-06 19:24 UTC, gundalow commented on lib/ansible/modules/network/aos/aos_ip_pool.py
> +description:
All `description:` (apart from `short_description:`) must be full sentences, ie start with a capital letter and end with a full stop.

2017-02-06 19:24 UTC, gundalow commented on lib/ansible/modules/network/aos/aos_ip_pool.py
> +      - Name of the IP Pool to manage
Name of the IP Pool to manage. Only one of I(name), I(id) or I(src) can be set.

This apply to a few option descriptions.

2017-02-06 19:24 UTC, gundalow commented on lib/ansible/modules/network/aos/aos_ip_pool.py
> +      - Indicate
A little more detail here would be good.

2017-02-06 19:24 UTC, gundalow commented on lib/ansible/modules/network/aos/aos_ip_pool.py
> +    default: []
You can delete this line.

2017-02-06 19:24 UTC, gundalow commented on lib/ansible/modules/network/aos/aos_ip_pool.py
> +    - name: "Create IP Pool"
- name: "Create an IP Pool with one subnet"

2017-02-06 19:24 UTC, gundalow commented on lib/ansible/modules/network/aos/aos_ip_pool.py
> +# Create an IP Pool with one subnet
Delete the comments, and set them as `- name: ` instead

Then fix the indentation `- name: ` shouldn't have any spaces before it. This is to allow people to copy & paste the examples straight into their playbooks.

2017-02-06 19:24 UTC, gundalow commented on lib/ansible/modules/network/aos/aos_ip_pool.py
> +from ansible.module_utils.aos import *
Import only what you need and not `*`

2017-02-06 19:24 UTC, gundalow commented on lib/ansible/modules/network/aos/aos_ip_pool.py
> +    # TODO add Exception handling for login error
TODO add Exception handling for login error

2017-02-06 19:24 UTC, gundalow commented on lib/ansible/modules/network/aos/aos_ip_pool.py
> +      - An existing AOS session as obtained by aos_login module
Once aos_login has been merged you can change this to `M(aos_login)` to generate a hyperlink to the Module docs for aos_login.

2017-02-06 23:18 UTC, dgarros commented
@gundalow Thanks for reviewing this module, appreciate your feedback.
 I made all changes you requested. Please let me know if you see more things that needs to be change.

2017-02-07 11:50 UTC, gundalow approved these changes
Looks good, thanks

2017-02-07 14:07 UTC, privateip requested changes

2017-02-07 14:07 UTC, privateip commented on lib/ansible/modules/network/aos/aos_ip_pool.py
> +            src=dict(required=False),
should be `type='path'`

2017-02-07 14:07 UTC, privateip commented on lib/ansible/modules/network/aos/aos_ip_pool.py
> +        item_name = get_display_name_from_file(module, margs['src'])
This will fail if the playbook task uses `delegate_to`.   Consider instead of accepting the file contents instead of a source file name

2017-02-07 14:07 UTC, privateip commented on lib/ansible/module_utils/aos.py
> +    except SessionRqstError:
I think this will fail a `NameError`

2017-02-07 17:56 UTC, dgarros commented on lib/ansible/modules/network/aos/aos_ip_pool.py
> +        item_name = get_display_name_from_file(module, margs['src'])
I'm not familiar with `delegate_to`, would you have an example that is doing what you propose ?
thks

2017-02-07 22:34 UTC, dgarros commented
@privateip, I made few changes to this module following your review, the main one is that I replaced `src` with `content` to allow more options. 
 It's now possible to pass a JSON string, a Yaml string or a variable directly. I also added a parameter `content_format` to indicate in which format the content is provided.

```
- name: "Load IP Pool from a JSON file"
  aos_ip_pool:
    session: "{{ session_ok }}"
    content: "{{ lookup('file', 'resources/ip_pool_saved.json') }}"
    state: present

- name: "Load IP Pool from a YAML file"
  aos_ip_pool:
    session: "{{ session_ok }}"
    content: "{{ lookup('file', 'resources/ip_pool_saved.yaml') }}"
    content_format: yaml
    state: present

- name: "Load IP Pool from a Variable"
  aos_ip_pool:
    session: "{{ session_ok }}"
    content:
      display_name: my-ip-pool
      id: 4276738d-6f86-4034-9656-4bff94a34ea7
      subnets:
        - network: 172.10.0.0/16
        - network: 172.12.0.0/16
    content_format: var
    state: present
```

I also made couple of minor changes: 
- Add a minimum version check for the library aos-pyez
- Change the authentication format to match with latest version of aos-pyez
- I made the exception handling more generic in `do_load_resource` following your comment


Please let me know if you see something else that needs to be changed.
thanks

2017-02-08 00:29 UTC, dgarros commented
I see some errors in shippable related to `test/units/modules/network/vyos/`, not sure how these arrived here.
I don't think the errors reported are related to the aos module

2017-02-08 01:35 UTC, dgarros commented
I rebased from `devel` and tests are passing now

2017-02-08 16:11 UTC, bcoca commented on lib/ansible/module_utils/aos.py
> +import yaml
yaml is not required on target machines, even if this module is expected to run with `connection: local` you might be run on 'delegated' machine which does not have Ansible installed

2017-02-08 16:15 UTC, bcoca commented
aside from the initial connection there is no exception handling, it is a bug if a module returns an exception instead of a JSON document.

2017-02-08 17:33 UTC, dgarros commented
@bcoca, thanks for your feedback. I made some changes to address your comments.
I added a `try/except` block in several places on the main function or code block.

Please let me know if you have more comments.

@privateip, did my changes addressed your comments as well ? I refactor the parameter `src` to be more friendly with `deletegate_to`

Also I added a mention of `module_utils/aos.py` into the documentation as suggested.

Looking forward to your inputs.

2017-02-08 17:38 UTC, bcoca commented
@dgarros the yaml import is still an issue

for content, FYI, JSON is a subset of YAML so yaml can normally parse both transparently. Also you can use detection (see our type=json implementation) to allow all 3 formats transparently w/o need of a content_format option.

2017-02-08 18:22 UTC, alikins requested changes

2017-02-08 18:22 UTC, alikins commented on lib/ansible/modules/network/aos/aos_ip_pool.py
> +def create_new_ip_pool(ip_pool, name, subnets=[]):
lib/ansible/modules/network/aos/aos_ip_pool.py:191:1: M511 - mutable default arg of type List

There is only one caller of create_new_ip_pool() and it provides all three args, so subnets doesnt need to be keyword arg or optional.

2017-02-08 18:22 UTC, alikins commented on lib/ansible/module_utils/aos.py
> +    import apstra.aosom.exc as aosExc
This import doesn't appear to be used.

2017-02-08 18:25 UTC, alikins commented on lib/ansible/modules/network/aos/aos_ip_pool.py
> +            in_use = True
As far as I can tell, the 'in_use' is never used.

2017-02-08 18:49 UTC, dgarros commented
@bcoca, I removed `content_format` as suggested and i updated the documentation accordingly. Now the format of the input is automatically detected. 
Please let me know if you see something else

@alikins thanks for your feedback, I made the changes to address your comments. Very good catches. Please let me know if you see something else.

2017-02-09 00:32 UTC, dgarros commented
I pushed some wrong commits in my branch, this is why @ansibot  requested a rebase.
I removed cleaned up everything, sorry for the noise.

2017-02-09 10:04 UTC, gundalow commented on lib/ansible/modules/network/aos/aos_ip_pool.py
> +  - aos-pyez
I'm not sure how old aos-pyez 0.6.0 is, though you may wish to detail that here.
`- "aos-pyez >= 0.6.0"`

2017-02-09 17:18 UTC, dgarros commented
@gundalow Very good point, I made the change 

@privateip @alikins Is there anything else you would like to change on this PR ? 
it would be great to get this one merged. I have more PR to open for additional modules before the 2.3 deadline next week
Please let me know if you have more comments or questions

2017-02-09 17:41 UTC, alikins approved these changes

2017-02-09 21:12 UTC, privateip approved these changes

2017-02-09 22:22 UTC, merged

2017-02-09 22:26 UTC, gundalow commented
Merged, thanks for the prompt updates, the rest should go faster. 

So you are now free to raise 5 PRs, each containing a single module. Feel free to `@gundalow` in the PRs so I'll get notified.

2017-02-09 22:48 UTC, dgarros commented
thanks a lot for your help