Added option validate_certs to the jenkins_job module
ansible/ansible pull request #21097
Opened 2017-02-07 15:57 UTC by samyray

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
Option to disable SSL verification for jenkins_job module

##### ANSIBLE VERSION
```
ansible 2.2.1.0 (detached HEAD 5362910000) last updated 2017/01/21 16:09:44 (GMT +100)
  lib/ansible/modules/core: (detached HEAD 7e8bb413b7) last updated 2017/01/21 16:10:55 (GMT +100)
  lib/ansible/modules/extras: (detached HEAD c501e006ea) last updated 2017/01/21 16:11:38 (GMT +100)
  config file =
  configured module search path = Default w/o overrides
```

##### SUMMARY
Many companies using self-sign SSL certificates in their estate for Jenkins masters and as a result, if you're trying to use "jenkins_job" module it fails with following error:

```
ansible-playbook -i localhost site.yml -e jenkins_url="https://jenkins-internal.test.com" -e jenkins_token="XXXXXXXXX"
 [WARNING]: Host file not found: localhost

 [WARNING]: provided hosts list is empty, only localhost is available

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Load variables] **********************************************************
ok: [localhost]

TASK [Add jenkins job] *********************************************************
failed: [localhost] (item=({u'name': u'Test job'], "msg": "Unable to validate if job exists, Error in request: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) for https://jenkins-internal.test.com"}
```

I've added additional option to this module:

```
  validate_certs:
    description:
      - If set to C(False), the SSL certificates will not be validated.
        This should only set to C(False) used on personally controlled sites
        using self-signed certificates as it avoids verifying the source site.
    required: False
    default: True
```

And now with this option it ignores SSL errors:

```
ansible-playbook -i localhost site.yml -e jenkins_url="https://jenkins-internal.test.com" -e jenkins_token="09e518c813a040a701404174ecb7b855"
 [WARNING]: Host file not found: localhost

 [WARNING]: provided hosts list is empty, only localhost is available

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Load variables] **********************************************************
ok: [localhost]

TASK [Add jenkins job] *********************************************************
ok: [localhost] => (item=({u'name': u'Test job'}))

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0
```

2017-02-08 01:11 UTC, mattclay commented on lib/ansible/modules/web_infrastructure/jenkins_job.py
> +            # Handle target environment that doesn't support HTTPS verification
CI failure due to PEP 8 issues:

```
2017-02-07 16:03:50 ERROR: PEP 8: lib/ansible/modules/web_infrastructure/jenkins_job.py:225:13: E115 expected an indented block (comment) (legacy)
2017-02-07 16:03:50 ERROR: PEP 8: lib/ansible/modules/web_infrastructure/jenkins_job.py:228:13: E115 expected an indented block (comment) (legacy)
```

2017-02-09 13:23 UTC, sermilrod requested changes
Apart from the small refactor suggestion, I like the new feature.

2017-02-09 13:23 UTC, sermilrod commented on lib/ansible/modules/web_infrastructure/jenkins_job.py
> +        if self.validate_certs == False:
can you extract this into a separated method? 

So get_jenkins_connection before returning the server object it calls something like:
`self.set_https_context()`

Naming really up to you, but I think it makes sense extracting it into a method.

2017-02-18 12:18 UTC, sermilrod commented
Hi @samyray I have ready some extra enhancements for this but I don't have permissions to push my commits to your branch. Do you mind setting me as a collaborator please?

2017-02-20 16:46 UTC, samyray commented
Hi @sermilrod 
> Do you mind setting me as a collaborator please?
I've added you as a collaborator to my fork, please check and let me know if it is working for you

2017-02-20 19:54 UTC, sermilrod commented
Hi @samyray all good, I was able to push my commits. However the CI seems to be failing with an error apparently unrelated 

```
2017-02-20 19:40:27     from ansible.module_utils.six import iteritems ; for KEY, VALUE in iteritems(DICT):
2017-02-20 19:40:27     from ansible.compat.six import iteritems ; for KEY, VALUE in iteritems(DICT):
2017-02-20 19:40:27 ./contrib/inventory/nagios_livestatus.py:            for key,value in section_values.iteritems():
2017-02-20 19:40:27 ./contrib/inventory/nagios_livestatus.py:            for key, value in section_values.iteritems():
2017-02-20 19:40:27 ERROR: Command "test/sanity/code-smell/no-dict-iteritems.sh" returned exit status 1.
2017-02-20 19:40:27 ERROR: InvocationError: '/root/src/github.com/ansible/ansible/test/runner/test.py sanity -v --skip-test ansible-doc --python 2.7 --require lib/ansible/modules/web_infrastructure/jenkins_job.py --color yes --requirements'
2017-02-20 19:40:27 ___________________________________ summary ____________________________________
2017-02-20 19:40:27 ERROR:   py27: commands failed
2017-02-20 19:40:27 ERROR: Command "tox -c test/runner/tox.ini -e py27 -- /root/src/github.com/ansible/ansible/test/runner/test.py sanity -v --skip-test ansible-doc --python 2.7 --require lib/ansible/modules/web_infrastructure/jenkins_job.py --color yes --requirements" returned exit status 1.
```

Any other reviewer have any clue on this?

2017-02-20 20:05 UTC, mattclay commented
@sermilrod Unrelated failure which has been fixed. I'll restart CI.

2017-02-20 20:21 UTC, sermilrod commented
@mattclay Thank you very much! 

For me this new feature looks good now. I give my 'shipit' and waiting for another OK.

2017-03-08 20:12 UTC, sermilrod commented
Any updates on this? 

I am not sure if we need 2 OK as I am actively contributing to the PR as module author and maintainer.

2017-04-10 13:29 UTC, samyray commented
@sermilrod Your changes looks good and was tested in Jenkins V1 and V2, do we need to do anything to merger this branch?

2017-04-11 14:49 UTC, sermilrod commented
We need a second member of the community to give us the OK to proceed. Apparently mine as the author and unique maintainer of the module is not enough...

2017-08-03 18:32 UTC, calfonso commented
@samyray could you rebase and resolve conflicts and we'll finish the review? Thanks!

2017-08-03 18:41 UTC, abadger commented
this code doesn't look compatible with python-2.6 (and I believe, also not compatible with python-2.7 < 2.7.8.  Note that some distros backport these changes to older pythons (RHEL-7) whereas other do not (Ubuntu and Debian))  Ideally, the jenkins client library would add support for this and we could just pass the right parameter to the client API to do this.  Doing it correctly in our code may prove to be very difficult.

* Versions of python are an issue
* Testing whether the module fails correctly when validate_certs=True will probably show that this code is not sufficient.

2018-05-13 19:30 UTC, Akasurde commented
@samyray Could you please rebase ? needs_info

2018-07-16 23:30 UTC, closed without merging