New Networking Module: NCLU
ansible/ansible pull request #21101
Opened 2017-02-07 17:06 UTC by isharacomix

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

nclu

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /home/cumulus/cldemo-nclu-ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible']
```

##### SUMMARY

This PR introduces an ansible module for NCLU, a new command-line interface for configuring networks on Cumulus Linux. This module is designed to be easier to use for individuals who are new to Cumulus Linux and/or network automation in general by exposing the NCLU interface in an automatable way.

https://docs.cumulusnetworks.com/display/DOCS/Network+Command+Line+Utility

```

```

2017-02-07 19:34 UTC, isharacomix commented
All the tests are passing - am I failing to hit minimum coverage?

2017-02-08 15:35 UTC, isharacomix commented
ready_for_review

2017-02-11 15:32 UTC, gundalow requested changes

2017-02-11 15:32 UTC, gundalow commented on lib/ansible/modules/network/cumulus/nclu.py
> +version_added: "2.2.3"
`version_added: "2.3"`

2017-02-11 15:32 UTC, gundalow commented on lib/ansible/modules/network/cumulus/nclu.py
> +      https://docs.cumulusnetworks.com/display/DOCS/Network+Command+Line+Utility
To get a URL use the following:
`U(https://docs.cumulusnetworks.com/display/DOCS/Network+Command+Line+Utility)`

See http://docs.ansible.com/ansible/dev_guide/developing_modules_documenting.html for details

2017-02-11 15:32 UTC, gundalow commented on lib/ansible/modules/network/cumulus/nclu.py
> +
Examples should include a ` - name:`, see http://docs.ansible.com/ansible/dev_guide/developing_modules_documenting.html#examples-block for details.

2017-02-11 15:32 UTC, gundalow commented on lib/ansible/modules/network/cumulus/nclu.py
> +## Add 48 interfaces and commit the change.
Use `- name:` rather than a comment

2017-02-11 15:32 UTC, gundalow commented on lib/ansible/modules/network/cumulus/nclu.py
> +## Atomically add an interface
Use `- name:` rather than a comment

2017-02-11 15:32 UTC, gundalow commented on lib/ansible/modules/network/cumulus/nclu.py
> +        mutually_exclusive=[('commands', 'template'),
The docs should state this

"Mutually exclusive options must be documented as the final sentence on each of the options."

http://docs.ansible.com/ansible/dev_guide/developing_modules_documenting.html#examples-block

2017-02-11 15:32 UTC, gundalow commented on lib/ansible/modules/network/cumulus/nclu.py
> +from ansible.module_utils.basic import *
Only import what you need, rather than `*`

2017-02-11 15:32 UTC, gundalow commented on lib/ansible/modules/network/cumulus/nclu.py
> +            - A list of strings containing the net commands to run.
Mutually exclusive with `I(template)`.

2017-02-11 15:32 UTC, gundalow commented on lib/ansible/modules/network/cumulus/nclu.py
> +              Mutually exclusive with 'commands'.
Mutually exclusive with `I(commands)`.

http://docs.ansible.com/ansible/dev_guide/developing_modules_documenting.html#formatting-options

2017-02-11 15:32 UTC, gundalow commented on lib/ansible/modules/network/cumulus/nclu.py
> +        description = dict(required=False, type='str', default="Ansible-originated commit"),
Default needs adding to docs

2017-02-13 17:29 UTC, gundalow approved these changes

2017-02-15 12:03 UTC, gundalow commented
Looks good thanks.

I see in the `MAINTAINER.txt` file we have `network/cumulus/: CumulusNetworks`

Should I update that to be all the people listed in https://github.com/orgs/CumulusNetworks/people

At the moment `Ansibot` doesn't know that you are part of CumulusNetworks?

2017-02-15 15:24 UTC, isharacomix commented
Adding everyone under @CumulusNetworks is probably not worth it. Set it to @isharacomix and @jrrivers - do you want us to PR Maintainers.txt ourselves going forward?

I'm not sure how to convince Ansibot who I belong to. :)

2017-02-15 15:53 UTC, gundalow commented
I've updated the bot so it knows who you are now https://github.com/ansible/ansibullbot/pull/373

2017-02-15 15:55 UTC, gundalow commented
If in the future you wish to update the MAINTAINERS.txt list (as people join/leave) feel free to raise a PR to do so, like I did in https://github.com/ansible/ansibullbot/pull/373

2017-02-21 03:21 UTC, merged