Vmware resource pool first add
ansible/ansible pull request #21116
Opened 2017-02-07 23:40 UTC by dav1x

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

new module for vmware_guest.py sweet

##### ANSIBLE VERSION

```
-> ansible --version
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY

This adds the ability to create resource pools in vmware in vCenter.

```
changed: [localhost] => {
    "changed": true, 
    "invocation": {
        "module_args": {
            "cluster": "devel", 
            "cpu_expandable_reservations": true, 
            "cpu_limit": -1, 
            "cpu_reservation": 0, 
            "cpu_shares": "normal", 
            "datacenter": "Boston", 
            "hostname": "10.x.x.25", 
            "mem_expandable_reservations": true, 
            "mem_limit": -1, 
            "mem_reservation": 0, 
            "mem_shares": "normal", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "resource_pool": "testrp-final2", 
            "state": "present", 
            "username": "administrator@vsphere.local", 
            "validate_certs": false
        }, 
        "module_name": "vmware_resource_pool"
    }
}

```

2017-02-08 01:17 UTC, mattclay commented
CI failure due to PEP 8 issues:

```
2017-02-08 00:01:28 ERROR: PEP 8: lib/ansible/modules/cloud/vmware/vmware_resource_pool.py:65:161: E501 line too long (190 > 160 characters) (current)
2017-02-08 00:01:28 ERROR: PEP 8: lib/ansible/modules/cloud/vmware/vmware_resource_pool.py:86:161: E501 line too long (190 > 160 characters) (current)
2017-02-08 00:01:28 ERROR: PEP 8: lib/ansible/modules/cloud/vmware/vmware_resource_pool.py:247:11: E111 indentation is not a multiple of four (current)
2017-02-08 00:01:28 ERROR: PEP 8: lib/ansible/modules/cloud/vmware/vmware_resource_pool.py:248:11: E111 indentation is not a multiple of four (current)
2017-02-08 00:01:28 ERROR: PEP 8: lib/ansible/modules/cloud/vmware/vmware_resource_pool.py:251:11: E111 indentation is not a multiple of four (current)
```

2017-02-08 06:58 UTC, nerzhul commented
Seems very nice

2017-02-08 16:14 UTC, angystardust commented
@dav1x very nice! Any plans to implement a `vmware_datastore.py` module?

2017-02-08 16:24 UTC, dav1x commented
@angystardust thanks! What functionality were you thinking for vmware_datastore? I'm planning on doing a vmware_folder next I think.

2017-02-08 16:32 UTC, nerzhul commented
it seems there is no idempotency in the module and a fix on vmware_guest from another pr, can you add idempotency ?

2017-02-08 17:35 UTC, dav1x commented
I can work on those features next week. My daughter is having surgery today and I'll be at the hospital for the next 5-7 days

2017-02-08 18:20 UTC, angystardust commented
@dav1x Thanks for paying attention to my comment. I'm thinking of some basic CRUD operations like "create an nfs or vmfs datastore", "destroy a datastore". You can take some inspiration from the govm tool:
https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#datastorecreate
Do you want me to open a feature-request issue for this? 

P.s.: good luck to you and your daughter for the surgery. Hope it isn't something too serious...

2017-02-20 18:15 UTC, dav1x commented
rebased and remove the previous change. @nerzhul I tested the module and it seems to have functional idempotency. You can submit the same play run and it will not repeat nor mark as changed. 

Can you elaborate further as to what is missing?

2017-02-20 20:19 UTC, mattclay commented
CI failure due to module docs validation error:

```
2017-02-20 20:17:01 ============================================================================
2017-02-20 20:17:01 lib/ansible/modules/cloud/vmware/vmware_resource_pool.py
2017-02-20 20:17:01 ============================================================================
2017-02-20 20:17:01 TRACE:
2017-02-20 20:17:01     mapping values are not allowed here
2017-02-20 20:17:01       in "vmware_resource_pool.EXAMPLES", line 117, column 11:
2017-02-20 20:17:01             - name: Add resource pool to vCenter
2017-02-20 20:17:01                   ^
2017-02-20 20:17:01 ERROR: EXAMPLES is not valid YAML. Line 117 column 11
```

2017-02-21 10:41 UTC, nerzhul commented on lib/ansible/modules/cloud/vmware/vmware_resource_pool.py
> +        cpu_alloc.limit=int(self.cpu_limit)
why not add spaces around equal ?

2017-02-21 10:42 UTC, nerzhul commented on lib/ansible/modules/cloud/vmware/vmware_resource_pool.py
> +from ansible.module_utils.basic import *
too wide imports, please only import the needed parts or @gundalow will bite you :)

2017-02-21 10:42 UTC, nerzhul requested changes
Some changes are required

2017-02-21 14:48 UTC, dav1x commented
Hey @nerzhul will add changes today. Thanks for the review!

2017-02-21 14:57 UTC, gundalow commented on lib/ansible/modules/cloud/vmware/vmware_resource_pool.py
> +from ansible.module_utils.basic import *
Hehe,
We will be getting this enforced by CI at somepoint as well, so it's good to get in the habit now :)

2017-02-21 21:47 UTC, mattclay commented on lib/ansible/modules/cloud/vmware/vmware_resource_pool.py
> +     find_cluster_by_name_datacenter, wait_for_task
CI failure due to PEP 8 issue:

```
2017-02-21 20:33:25 ERROR: PEP 8: lib/ansible/modules/cloud/vmware/vmware_resource_pool.py:322:6: E126 continuation line over-indented for hanging indent (current)
```

You can run the PEP 8 tests locally with `make pep8`.

2017-02-23 09:03 UTC, nerzhul requested changes
Except the code style it seems goods

2017-02-23 09:03 UTC, nerzhul commented on lib/ansible/modules/cloud/vmware/vmware_resource_pool.py
> +                              cpu_shares=dict(type='str', default="normal", choices=['high','custom','normal', 'low']),
can you make the space consisten in your lists ? same for same list above

2017-02-27 16:40 UTC, dav1x commented on lib/ansible/modules/cloud/vmware/vmware_resource_pool.py
> +                              cpu_shares=dict(type='str', default="normal", choices=['high','custom','normal', 'low']),
@nerzhul do you mean the spacing by the =?

2017-02-28 12:43 UTC, nerzhul commented on lib/ansible/modules/cloud/vmware/vmware_resource_pool.py
> +                              cpu_shares=dict(type='str', default="normal", choices=['high','custom','normal', 'low']),
@dav1x yeah

2017-02-28 17:29 UTC, dav1x commented on lib/ansible/modules/cloud/vmware/vmware_resource_pool.py
> +                              cpu_shares=dict(type='str', default="normal", choices=['high','custom','normal', 'low']),
@nerzhul done!

2017-03-01 02:23 UTC, mattclay commented
CI failure due to module validation errors:

```
2017-02-28 17:36:10 ============================================================================
2017-02-28 17:36:10 lib/ansible/modules/cloud/vmware/vmware_resource_pool.py
2017-02-28 17:36:10 ============================================================================
2017-02-28 17:36:10 ERROR:107:Imports should be directly below DOCUMENTATION/EXAMPLES/RETURN/ANSIBLE_METADATA. line 326
2017-02-28 17:36:10 ERROR:107:Imports should be directly below DOCUMENTATION/EXAMPLES/RETURN/ANSIBLE_METADATA. line 328
```

2017-03-08 21:42 UTC, dav1x commented
any updates to this? can we take about a merge?

@jctanner @nerzhul

2017-03-08 21:44 UTC, dav1x commented
@angystardust I'm going to work on vmware_datastore next. We got the dynamic provisioning in kubernetes 1.5.3 working on vsphere. Programmatically creating datastores would be a great addition to my OpenShift playbooks!

2017-03-08 22:23 UTC, jctanner commented
@dav1x were in a feature freeze for 2.3, but this is also waiting on @nerzhul to approve or dismiss his change request.

2017-03-08 22:24 UTC, nerzhul reviewed
Code is okay for me, i just need to test it, but as said we are in FF

2017-03-08 22:25 UTC, nerzhul commented
I cannot dismiss my review as i'm not marked as an official maintainer for github :(

2017-03-08 22:26 UTC, jctanner commented
bot_status

2017-03-24 20:12 UTC, dav1x commented
@jctanner @nerzhul any thing we can do for this? Should I remove the PR and re-request it? I've got vmware_folder.py written and ready to contribute now as well.

2017-03-24 23:02 UTC, nerzhul approved these changes
It's okay for me

shipit

2017-03-27 14:35 UTC, merged