add nice approximation of the shippable/testrunner pep8 spec
ansible/ansible pull request #21120
Opened 2017-02-08 01:08 UTC by tedder

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
testing/shippable/pep8

##### ANSIBLE VERSION
2.3.0 devel

##### SUMMARY
I needed to short-circuit the pep8 testing so I could fix things and iterate. Passing on, because The More You Know.

2017-02-08 01:28 UTC, sivel commented
The test runner can be run directly to perform the pep8 test 

```
./test/runner/ansible-test sanity -v --test pep8
```

That would be the preferred command to execute as it is sure to be in sync with the way we are running pep8.

2017-02-08 03:46 UTC, tedder commented
Perfect. I've updated it, @sivel. I find these type of breadcrumbs are handy for those of us who aren't in the code every day.

2017-02-08 23:42 UTC, abadger commented
@mattclay I know you were working on test documentation but if that's a ways off maybe we want this as a short-term hint until the new docs can be merged?

2017-02-10 08:43 UTC, dharmabumstead approved these changes
Looks OK from a docs standpoint. Thanks @tedder!

2017-02-13 17:24 UTC, mattclay commented
The PEP 8 tests can now be run with `make pep8` from the git root.

2017-02-13 17:34 UTC, tedder commented
@mattclay is there support for only running against one file/directory?

2017-02-13 17:38 UTC, mattclay requested changes

2017-02-13 17:38 UTC, mattclay commented on test/sanity/pep8/README.md
> +## Running locally
Capitalize `locally` for consistency with other headings.

2017-02-13 17:38 UTC, mattclay commented on test/sanity/pep8/README.md
> +You can do a quick pep8 spotcheck by approximating `command_sanity_pep8` in `test/runner/lib/executor.py` like this:
No need to reference the internals of `ansible-test` here. A simpler explanation should suffice:

```
The PEP 8 check can be run locally with:
```

2017-02-13 17:38 UTC, mattclay commented on test/sanity/pep8/README.md
> +    ./test/runner/ansible-test sanity -v --test pep8 <files to sanity-check>
I'd revise the example a little. Verbose output is probably not needed in most cases:

```
test/runner/ansible-test sanity --test pep8 [file-or-directory-path-to-check] ...
```

2017-02-13 17:41 UTC, mattclay commented
@tedder For that, I recommend running `ansible-test` directly, so you can take advantage of tab completion provided by `argcomplete`. However, if you do want to use `make`, you can pass extra arguments using the `TEST_FLAGS` environment variable.

The `pep8` target was already present, I just recently updated it to use `ansible-test`.

2017-02-13 17:46 UTC, tedder commented
Made those corrections. Originally the "approximating command_sanity_pep8" text was because.. I was running a custom command to approximate it. Yay for built-in methods to do so.

2017-02-13 17:47 UTC, mattclay commented
@tedder Please remove the '@' mention from the commit message to avoid spurious notifications from GitHub.

2017-02-13 17:51 UTC, tedder commented
done (and force-pushed)

2017-02-13 17:54 UTC, mattclay requested changes

2017-02-13 17:54 UTC, mattclay commented on test/sanity/pep8/README.md
> +    ./test/runner/ansible-test sanity --test pep8 <files to sanity-check>
The example in my previous review comment probably explains usage better:

```
test/runner/ansible-test sanity --test pep8 [file-or-directory-path-to-check] ...
```

It makes it more clear that paths given are:

- optional
- can be files or directories
- can be specified more than once

2017-02-13 18:25 UTC, mattclay requested changes

2017-02-13 18:25 UTC, mattclay commented on test/sanity/pep8/README.md
> +    ./test/runner/ansible-test sanity --test pep8 [file-or-directory-path-to-check]
Missing `...` at the end to indicate multiple files can be specified.

2017-02-13 18:33 UTC, mattclay approved these changes

2017-02-13 19:09 UTC, merged