New Module : aos_external_router as part of network/aos (clean)
ansible/ansible pull request #21221
Opened 2017-02-09 23:12 UTC by dgarros

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
network/aos/aos_external_router

##### ANSIBLE VERSION
```
ansible 2.3.0 (aos_login_clean e06132a1fb) last updated 2017/02/09 14:56:31 (GMT -700)
  config file =
  configured module search path = Default w/o overrides
```

##### SUMMARY
I'm working for [Apstra](http://www.apstra.com/), we are making a product to automate Datacenter Networks and we are developed a dozen of Ansible modules and one dynamic inventory to control our product with Ansible.
We have tried to follow Ansible's best practices as much as possible, all our modules are idempotent and support the mode `--check`.

This is the second batch of module that I'm submitting for review, the first `aos_ip_pool` #21044 has been recently approved

@gundalow, please can you take a look and let me know if I need to make some changes 

> I opened a similar PR yesterday for this module but it included the first PR #21044 so I closed it and opened a clean one #21179. Somehow git was not able to rebase properly  ...

2017-02-10 17:32 UTC, jeremyschulman approved these changes
shipit

2017-02-10 19:06 UTC, gundalow requested changes
Just remove  `required: false`, everything else looks good

2017-02-10 19:33 UTC, dgarros commented
@gundalow Done, thanks

2017-02-10 19:53 UTC, gundalow approved these changes

2017-02-11 13:30 UTC, gundalow requested changes

2017-02-11 13:30 UTC, gundalow commented on lib/ansible/modules/network/aos/aos_external_router.py
> +            loopback=dict(required=False),
Missing from docs

2017-02-11 13:30 UTC, gundalow commented on lib/ansible/modules/network/aos/aos_external_router.py
> +            asn=dict(required=False)
Missing from docs

2017-02-13 03:00 UTC, dgarros commented
@gundalow good catch, I documented those 2.
it's incredibly hard to check everything manually, it would be great to automate these tests :)

2017-02-13 12:35 UTC, gundalow commented
So, apparently their is a "beta" function to validate arg-spec
```
source hacking/env-setup
./test/sanity/validate-modules/validate-modules --arg-spec --warnings  lib/ansible/modules/network/aos/
```

There are some ongoing discussions regarding moving the documentation for options into `argspec` itself, so we've not looked at fully automating this. I'll updated docs.ansible.com/ansible/dev_guide/developing_modules_documenting.html to mention that people can use the above tool locally.

2017-02-13 12:35 UTC, gundalow approved these changes

2017-02-13 23:25 UTC, dgarros commented
ready_for_review

2017-02-14 09:49 UTC, gundalow commented
shipit

2017-02-18 01:25 UTC, merged