resolve #21056 - Add support for full cloning a Qemu VM. Fix some issues. Update doc
ansible/ansible pull request #21225
Opened 2017-02-09 23:56 UTC by helldorado

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

modules/cloud/misc/proxmox_kvm.py

##### ANSIBLE VERSION

```yaml
ansible --version
ansible 2.2.0.0
  config file = /usr/local/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY

Fixes #21056
Add new feature
  - Clone

```yaml
---
- hosts: orchestrator
  remote_user: root
  gather_facts: False
  vars:
    instance:
      - name: spynal
        proxmox:
          api_host  : labhyp.helldorado.info
          node      : labhyp1
          cores     : 2
          vcpus     : 1
          net       : '{"net0":"virtio,bridge=vmbr0"}'
          virtio    : '{"virtio0":"VMs:50,format=qcow2"}'
```

```yaml
- name: CLONE
  local_action:
    module: proxmox_kvm
    api_user     : "{{ item.proxmox.api_user|default('root@pam') }}"
    api_password : "{{ item.proxmox.api_password|default(omit) }}"
    api_host     : "{{ item.proxmox.api_host }}"
    node         : "{{ item.proxmox.node }}"
    name         :  "{{ item.name }}"
    clone        : zavala
    storage      : 'VMs'
    timeout      : 300
  with_items: "{{ instance }}"
```

> ℹ️  Some output has truncated

```yaml
ansible@spynal-orchestrator:/usr/local/ansible/orchestrator (master)$ ansible-playbook playbooks/servers.yml -vvvv
PLAYBOOK: servers.yml **********************************************************
1 plays in playbooks/servers.yml

PLAY [orchestrator] ************************************************************

TASK [deploy : Include virtual] ************************************************
task path: /usr/local/ansible/orchestrator/roles/deploy/tasks/main.yml:4
included: /usr/local/ansible/orchestrator/roles/deploy/tasks/virtual.yml for spynal-orchestrator

TASK [deploy : CLONE] **********************************************************
task path: /usr/local/ansible/orchestrator/roles/deploy/tasks/virtual.yml:32
Using module file /usr/local/ansible/orchestrator/roles/deploy/library/proxmox_kvm.py
changed: [spynal-orchestrator -> localhost] => (item={{
        },
        "module_name": "proxmox_kvm"
    },
    "item": {
        "cores" : 2,
        "delete": "cpuunits",
        "name": "spynal",
        "net": "{\"net0\":\"virtio,bridge=vmbr0\"}",
        "proxmox": {
            "api_host": "labhyp.helldorado.info",
            "node": "labhyp1"
        },
        "vcpus": 1,
        "virtio": "{\"virtio0\":\"VMs:50,format=qcow2\"}"
    },
    "msg": "VM spynal with newid 136 cloned from vm with vmid 108"
}

PLAY RECAP *********************************************************************
spynal-orchestrator        : ok=2    changed=1    unreachable=0    failed=0
```

Issue #21056

##### Update/Delete/Revert VM parameters

###### Update
```yaml
---
- hosts: orchestrator
  remote_user: root
  gather_facts: False
  vars:
    instance:
      - name: spynal
        proxmox:
          api_host : labhyp.helldorado.info
          node     : labhyp1
          cores    : 4
          vcpus    : 1
          net      : '{"net0":"virtio,bridge=vmbr0"}'
          virtio   : '{"virtio0":"VMs:50,format=qcow2"}'
          update   : yes
```

```yaml
- name: CREATE/UPDATE VM
  local_action:
    module: proxmox_kvm
    api_user      : "{{ item.proxmox.api_user|default('root@pam') }}"
    api_password  : "{{ item.proxmox.api_password|default(omit) }}"
    api_host      : "{{ item.proxmox.api_host }}"
    node          : "{{ item.proxmox.node }}"
    name          : "{{ item.name }}"
    kvm           : "{{ item.kvm|default('yes') }}"
    net           : '{"net0":"virtio,bridge={{ vlan|default(pxe.vlan) }}"}'
    virtio        : "{{ item.virtio }}"
    cores         : "{{ item.cores|default('4') }}"
    sockets       : "{{ item.sockets|default('1') }}"
    vcpus         : "{{ item.vcpus|default(omit) }}"
    memory        : "{{ item.memory|default('2048') }}"
    balloon       : "{{ item.ballon|default(omit) }}"
    hotplug       : "{{ item.hotplug|default('memory,cpu,disk,network') }}"
    numa_enabled  : "{{ item.numa_enabled|default('yes') }}"
    keyboard      : "{{ item.keyboard|default('fr') }}"
    state         : "{{ item.state|default('present') }}"
    update        : "{{ item.update|default('yes') }}"
    delete        : "{{ item.delete|default(omit) }}"
    cpuunits      : "{{ item.cpuunits|default(omit) }}"
    revert        : "{{ item.revert|default(omit) }}"
  register: qemu
  with_items: "{{ instance }}"
```

###### Delete

> Param `delete: 'template'` added in instance dict per example

```yaml
ansible@spynal-orchestrator:/usr/local/ansible/orchestrator (master)$ ansible-playbook playbooks/servers.yml -vvvvvvvvv
PLAYBOOK: servers.yml **********************************************************
1 plays in playbooks/servers.yml

PLAY [orchestrator] ************************************************************

TASK [deploy : Include virtual] ************************************************
task path: /usr/local/ansible/orchestrator/roles/deploy/tasks/main.yml:4
included: /usr/local/ansible/orchestrator/roles/deploy/tasks/virtual.yml for spynal-orchestrator

TASK [deploy : CREATE/UPDATE VM] ******************************************************
task path: /usr/local/ansible/orchestrator/roles/deploy/tasks/virtual.yml:4
Using module file /usr/local/ansible/orchestrator/roles/deploy/library/proxmox_kvm.py
changed: [spynal-orchestrator -> localhost] => (item={}) => {
    "changed": true,
    "invocation": {
        "module_args": {
        },
        "module_name": "proxmox_kvm"
    },
    "item": {
        "cores": 2,
        "cpuunits": 50000,
        "delete": "template",
        "name": "combo",
        "net": "{\"net0\":\"virtio,bridge=vmbr0\"}",
        "proxmox": {
            "api_host": "labhyp.helldorado.info",
            "node": "labhyp1"
        },
        "tag": 1488514,
        "update": true,
        "vcpus": 1,
        "virtio": "{\"virtio0\":\"VMs:50,format=qcow2\"}"
    },
    "msg": "Settings has deleted on VM combo with vmid 108"
}

PLAY RECAP *********************************************************************
spynal-orchestrator        : ok=2    changed=1    unreachable=0    failed=0
```

###### Revert

> Param `revert: 'cpuunits'` added in instance dict per example

```yaml
ansible@spynal-abah-orchestrator:/usr/local/ansible/orchestrator (master)$ ansible-playbook playbooks/servers.yml -vvvvvvvvv

PLAYBOOK: servers.yml **********************************************************
1 plays in playbooks/servers.yml

PLAY [orchestrator] ************************************************************

TASK [deploy : Include virtual] ************************************************
task path: /usr/local/ansible/orchestrator/roles/deploy/tasks/main.yml:4
included: /usr/local/ansible/orchestrator/roles/deploy/tasks/virtual.yml for spynal-orchestrator

TASK [deploy : CREATE/UPDATE VM] ******************************************************
task path: /usr/local/ansible/orchestrator/roles/deploy/tasks/virtual.yml:4
Using module file /usr/local/ansible/orchestrator/roles/deploy/library/proxmox_kvm.py
changed: [spynal-orchestrator -> localhost] => (item={}) => {
    "changed": true,
    "invocation": {
        "module_args": {
            },
        },
        "module_name": "proxmox_kvm"
    },
    "item": {
        "cores": 2,
        "cpuunits": 50000,
        "name": "combo",
        "net": "{\"net0\":\"virtio,bridge=vmbr0\"}",
        "proxmox": {
            "api_host": "labhyp.helldorado.info",
            "node": "labhyp1"
        },
        "revert": "cpuunits",
        "tag": 1488514,
        "update": true,
        "vcpus": 1,
        "virtio": "{\"virtio0\":\"VMs:50,format=qcow2\"}"
    },
    "msg": "Settings has reverted on VM combo with vmid 108"
}

PLAY RECAP *********************************************************************
spynal-orchestrator        : ok=2    changed=1    unreachable=0    failed=0
```

2017-02-10 11:14 UTC, gundalow requested changes

2017-02-10 11:14 UTC, gundalow commented on lib/ansible/modules/cloud/misc/proxmox_kvm.py
> -                    'version': '1.0'}
This is the version of the metadata, not your file. So no need to change that. 

It's on my to do list to document ANSIBLE_METADATA so I'll add a note about this.

2017-02-10 11:14 UTC, gundalow commented on lib/ansible/modules/cloud/misc/proxmox_kvm.py
> +    type: string
No need to document `type:` in the DOCUMENTION block.

2017-02-10 11:14 UTC, gundalow commented on lib/ansible/modules/cloud/misc/proxmox_kvm.py
> +  if module.params['delete'] is not None and module.params['revert'] is not None:
Their are built in helpers for argspec  for the this, have a look in other modules for "exclusive"

2017-02-13 10:23 UTC, helldorado commented
ready_for_review

2017-02-13 12:08 UTC, gundalow approved these changes

2017-02-13 19:04 UTC, mattclay commented
CI failure due to PEP 8 issues:

```
2017-02-13 18:55:47 ERROR: PEP 8: lib/ansible/modules/cloud/misc/proxmox_kvm.py:900:5: E121 continuation line under-indented for hanging indent (legacy)
2017-02-13 18:55:47 ERROR: PEP 8: lib/ansible/modules/cloud/misc/proxmox_kvm.py:901:7: E121 continuation line under-indented for hanging indent (legacy)
```

I recommend running the PEP 8 checks locally with `make pep8` to easily see what needs changes.

2017-02-14 09:56 UTC, helldorado commented
ready_for_review

2017-02-15 22:51 UTC, merged