New Module : aos_login as part of network/aos (clean)
ansible/ansible pull request #21220
Opened 2017-02-09 23:07 UTC by dgarros

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
network/aos/aos_login

##### ANSIBLE VERSION
```
ansible 2.3.0 (aos_login_clean e06132a1fb) last updated 2017/02/09 14:56:31 (GMT -700)
  config file =
  configured module search path = Default w/o overrides
```

##### SUMMARY
I'm working for [Apstra](http://www.apstra.com/), we are making a product to automate Datacenter Networks and we are developed a dozen of Ansible modules and one dynamic inventory to control our product with Ansible.
We have tried to follow Ansible's best practices as much as possible, all our modules are idempotent and support the mode `--check`.

This is the second batch of module that I'm submitting for review, the first `aos_ip_pool` #21044 has been recently approved

@gundalow, please can you take a look and let me know if I need to make some changes 

> I opened a similar PR yesterday for this module but it included the first PR #21044 so I closed it and opened a clean one #21174. Somehow git was not able to rebase properly  ...

2017-02-10 17:32 UTC, jeremyschulman approved these changes
shipit

2017-02-10 19:15 UTC, gundalow requested changes

2017-02-10 19:15 UTC, gundalow commented on lib/ansible/modules/network/aos/aos_login.py
> +    This module is not idempotent and do not support chech mode.
Typo of "check mode".

2017-02-10 19:15 UTC, gundalow commented on lib/ansible/modules/network/aos/aos_login.py
> +    required: false
Please remove `required: false`

2017-02-10 19:15 UTC, gundalow commented on lib/ansible/modules/network/aos/aos_login.py
> +  port:
Please document default port

2017-02-10 19:15 UTC, gundalow commented on lib/ansible/modules/network/aos/aos_login.py
> +            passwd=dict(default='admin', no_log=True)))
Just an FYI.
I believe the way `no_log` works is my replacing any occurrence of that string in output displayed to the users. Therefore  if `admin` is both username and password then we wouldn't see the username if it was returned in a message.

2017-02-10 19:31 UTC, dgarros commented on lib/ansible/modules/network/aos/aos_login.py
> +            passwd=dict(default='admin', no_log=True)))
got it thanks, I think we are good

2017-02-10 19:31 UTC, dgarros commented
@gundalow thanks for your review, I made the changes you suggested.

2017-02-10 19:34 UTC, gundalow approved these changes

2017-02-13 23:21 UTC, dgarros commented
ready_for_review

2017-02-14 09:50 UTC, gundalow commented
shipit

2017-02-18 01:25 UTC, merged