Add new module aos_logical_device
ansible/ansible pull request #21226
Opened 2017-02-10 00:02 UTC by dgarros

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
network/aos/aos_logical_device

##### ANSIBLE VERSION
```
ansible 2.3.0 (aos_logical_device b4396d1217) last updated 2017/02/09 16:00:06 (GMT -700)
  config file =
  configured module search path = Default w/o overrides
```

##### SUMMARY
I'm working for [Apstra](http://www.apstra.com/), we are making a product to automate Datacenter Networks and we are developed a dozen of Ansible modules and one dynamic inventory to control our product with Ansible.
We have tried to follow Ansible's best practices as much as possible, all our modules are idempotent and support the mode `--check`.

This is the second batch of module that I'm submitting for review, the first `aos_ip_pool` #21044 has been recently approved

@gundalow, please can you take a look and let me know if I need to make some changes

2017-02-10 17:30 UTC, jeremyschulman approved these changes
shipit

2017-02-10 19:00 UTC, gundalow requested changes

2017-02-10 19:00 UTC, gundalow commented on lib/ansible/modules/network/aos/aos_logical_device.py
> +            time.sleep(1)
Might be worth adding a comment to say why this is needed

2017-02-10 19:00 UTC, gundalow commented on lib/ansible/modules/network/aos/aos_logical_device.py
> +    required: false
You can remove the `required: false` lines, it's implicit

2017-02-10 19:14 UTC, dgarros commented
@gundalow I made the changes you requested, thanks for your review

2017-02-10 19:16 UTC, gundalow approved these changes

2017-02-11 12:16 UTC, gundalow commented
shipit

2017-02-13 23:23 UTC, dgarros commented
ready_for_review

2017-02-14 09:49 UTC, gundalow commented
shipit

2017-02-18 01:26 UTC, merged