New Module : aos_asn_pool as part of network/aos (clean)
ansible/ansible pull request #21224
Opened 2017-02-09 23:21 UTC by dgarros

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
network/aos/aos_asn_pool

##### ANSIBLE VERSION
```
ansible 2.3.0 (aos_asn_pool_clean e06132a1fb) last updated 2017/02/09 14:56:31 (GMT -700)
  config file =
  configured module search path = Default w/o overrides
```

##### SUMMARY
I'm working for [Apstra](http://www.apstra.com/), we are making a product to automate Datacenter Networks and we are developed a dozen of Ansible modules and one dynamic inventory to control our product with Ansible.
We have tried to follow Ansible's best practices as much as possible, all our modules are idempotent and support the mode `--check`.

This is the second batch of module that I'm submitting for review, the first `aos_ip_pool` #21044 has been recently approved

@gundalow, please can you take a look and let me know if I need to make some changes 

> I opened a similar PR yesterday for this module but it included the first PR #21044 so I closed it and opened a clean one #21178 . Somehow git was not able to rebase properly  ...

2017-02-10 17:30 UTC, jeremyschulman approved these changes
shipit

2017-02-10 17:54 UTC, gundalow requested changes

2017-02-10 17:54 UTC, gundalow commented on lib/ansible/modules/network/aos/aos_asn_pool.py
> +            module.fail_json(msg="Unable to delete this Asn Pool is currently in use")
Could the error return which Asn Pool is in use?

Also Asn or ASN - This comment applies to a few lines in the modules?

2017-02-10 17:54 UTC, gundalow commented on lib/ansible/modules/network/aos/aos_asn_pool.py
> +    is idempotent and support the I(check) mode. It's using the AOS REST API
Missing full stop.

2017-02-10 17:54 UTC, gundalow commented on lib/ansible/modules/network/aos/aos_asn_pool.py
> +      - An existing AOS session as obtained by aos_login module
Missing full stop.

One all the modules are updates you could raise a single PR to update any reference to another module with the `M(aos_login)`  which will insert a link to the online docs for that module.

e.g.

2017-02-10 17:54 UTC, gundalow commented on lib/ansible/modules/network/aos/aos_asn_pool.py
> +    is idempotent and support the I(check) mode. It's using the AOS REST API
support -> supports

2017-02-10 17:54 UTC, gundalow commented on lib/ansible/modules/network/aos/aos_asn_pool.py
> +        on success in I(value).
From the examples is seems like `content` can also be a key when uses with `state: absent`.

2017-02-10 17:54 UTC, gundalow commented on lib/ansible/modules/network/aos/aos_asn_pool.py
> +      - Indicate what is the expected state of the ASN Pool (present or not)
Missing full stop.

2017-02-10 17:54 UTC, gundalow commented on lib/ansible/modules/network/aos/aos_asn_pool.py
> +      - List of ASNs ranges to add to the ASN Pool
Missing full stop.

2017-02-10 17:54 UTC, gundalow commented on lib/ansible/modules/network/aos/aos_asn_pool.py
> +    required: false
You can removed all the `required: false` it's implicit

2017-02-10 17:54 UTC, gundalow commented on lib/ansible/modules/network/aos/aos_asn_pool.py
> +        module.exit_json(changed=False, name=margs['name'], id='', value={})
Could you please add an example (in reply to his comment) of what this error would look like.

2017-02-10 19:24 UTC, dgarros commented on lib/ansible/modules/network/aos/aos_asn_pool.py
> +        module.exit_json(changed=False, name=margs['name'], id='', value={})
Not sure to understand your question here, if `state: absent` is defined and the pool do not exist, we just return `changed: false` but it's not an error.

2017-02-10 19:26 UTC, gundalow commented on lib/ansible/modules/network/aos/aos_asn_pool.py
> +        module.exit_json(changed=False, name=margs['name'], id='', value={})
Ah, yes, I miss read the code. Nothing to change here.

2017-02-10 19:26 UTC, dgarros commented
@gundalow, thanks for your review
I made the necessary changes to address your comments, except for one that I'm not sure to understand.
Please let me know if you see something else

2017-02-10 19:33 UTC, gundalow approved these changes

2017-02-13 23:22 UTC, dgarros commented
ready_for_review

2017-02-14 09:50 UTC, gundalow commented
shipit

2017-02-18 01:24 UTC, merged