New module for setting up Avi SSL Key and Certificates for Virtual Se…
ansible/ansible pull request #21242
Opened 2017-02-10 12:45 UTC by grastogi23

…rvices

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

avi.avi_sslkeyandcertificate
##### ANSIBLE VERSION

```
ansible 2.3.0
  config file = /home/grastogi/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY

New module for setting up Avi SSL Key and Certificates.

```

```

2017-02-10 20:00 UTC, khaltore approved these changes
+label shipit

2017-02-11 14:55 UTC, gundalow requested changes

2017-02-11 14:55 UTC, gundalow commented on lib/ansible/modules/network/avi/avi_sslkeyandcertificate.py
> +            - Name of the encrypted private key (e.
I think this should be a single line, rather than three

2017-02-11 14:55 UTC, gundalow commented on lib/ansible/modules/network/avi/avi_sslkeyandcertificate.py
> +        default: 1
Default not set in argspec.

2017-02-11 14:55 UTC, gundalow commented on lib/ansible/modules/network/avi/avi_sslkeyandcertificate.py
> +        default: 0
Default not set in argspec.

2017-02-11 21:39 UTC, grastogi23 commented
Fixed all the inconsistencies.

2017-02-14 09:57 UTC, gundalow approved these changes

2017-02-18 00:00 UTC, ericsysmin commented
shipit

2017-02-23 16:49 UTC, ericsysmin commented
+shipit

2017-02-23 17:16 UTC, khaltore commented
shipit

2017-02-23 17:16 UTC, ericsysmin commented
shipit

2017-02-24 02:30 UTC, ericsysmin commented
shipit

2017-02-24 16:37 UTC, merged