New module for setting up Avi Pool
ansible/ansible pull request #21241
Opened 2017-02-10 12:19 UTC by grastogi23

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

avi.avi_pool
##### ANSIBLE VERSION

```
ansible 2.3.0
  config file = /home/grastogi/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY

New module for setting up Avi Pool. 

```

```

2017-02-10 17:07 UTC, khaltore approved these changes
+label shipit

2017-02-11 14:59 UTC, gundalow requested changes
I've not been through everything, though please ensure if in the documentation you specifuy:
* a default
* required: True

That this is also reflected in `argspec`

2017-02-11 14:59 UTC, gundalow commented on lib/ansible/modules/network/avi/avi_pool.py
> +        default: 0
Default not set in argspec.

2017-02-11 14:59 UTC, gundalow commented on lib/ansible/modules/network/avi/avi_pool.py
> +        default: 10
Default not set in argspec.

2017-02-11 14:59 UTC, gundalow commented on lib/ansible/modules/network/avi/avi_pool.py
> +        default: 80
Default not set in argspec.

2017-02-11 14:59 UTC, gundalow commented on lib/ansible/modules/network/avi/avi_pool.py
> +        default: True
Default not set in argspec.

2017-02-11 14:59 UTC, gundalow commented on lib/ansible/modules/network/avi/avi_pool.py
> +        default: 10
Default not set in argspec.

2017-02-11 14:59 UTC, gundalow commented on lib/ansible/modules/network/avi/avi_pool.py
> +        default: 1
Default not set in argspec.

2017-02-11 14:59 UTC, gundalow commented on lib/ansible/modules/network/avi/avi_pool.py
> +        default: False
Default not set in argspec.

2017-02-11 14:59 UTC, gundalow commented on lib/ansible/modules/network/avi/avi_pool.py
> +        default: 1
Default not set in argspec.

2017-02-11 14:59 UTC, gundalow commented on lib/ansible/modules/network/avi/avi_pool.py
> +        default: 1
Default not set in argspec.

2017-02-11 14:59 UTC, gundalow commented on lib/ansible/modules/network/avi/avi_pool.py
> +        default: 0
Default not set in argspec.

2017-02-11 14:59 UTC, gundalow commented on lib/ansible/modules/network/avi/avi_pool.py
> +        required: true
Required not set in argspec

2017-02-11 14:59 UTC, gundalow commented on lib/ansible/modules/network/avi/avi_pool.py
> +            - (internal-use) networks designated as containing servers for this pool.
If this is for internal use does it need to be in the module?

2017-02-11 14:59 UTC, gundalow commented on lib/ansible/modules/network/avi/avi_pool.py
> +        default: 128
Default not set in argspec.

2017-02-11 21:39 UTC, grastogi23 commented on lib/ansible/modules/network/avi/avi_pool.py
> +        required: true
fixed

2017-02-11 21:40 UTC, grastogi23 commented on lib/ansible/modules/network/avi/avi_pool.py
> +            - (internal-use) networks designated as containing servers for this pool.
This information is still returned in the API. It is just not editable. In next version of Avi we will clean it up then I would be updating it to deprecated. However, till our next release happens we need to keep it in the object.

2017-02-11 21:40 UTC, grastogi23 commented
Fixed all other items.

2017-02-14 09:55 UTC, gundalow approved these changes

2017-02-18 00:01 UTC, ericsysmin commented
shipit

2017-02-23 16:49 UTC, ericsysmin commented
+shipit

2017-02-23 17:16 UTC, khaltore commented
shipit

2017-02-23 17:17 UTC, ericsysmin commented
shipit

2017-02-24 01:12 UTC, ericsysmin commented
shipit

2017-02-24 16:38 UTC, merged