New Module : aos_blueprint as part of network/aos
ansible/ansible pull request #21278
Opened 2017-02-11 00:33 UTC by dgarros

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
network/aos/aos_blueprint

##### ANSIBLE VERSION
```
ansible 2.3.0 (aos_blueprint de9d90c9e6) last updated 2017/02/10 15:59:02 (GMT -700)
  config file =
  configured module search path = Default w/o overrides
```

##### SUMMARY
I'm working for [Apstra](http://www.apstra.com/), we are making a product to automate Datacenter Networks and we are developed a dozen of Ansible modules and one dynamic inventory to control our product with Ansible.
We have tried to follow Ansible's best practices as much as possible, all our modules are idempotent and support the mode `--check`.

This is the third batch of module that I'm submitting for review, the first `aos_ip_pool` #21044 has been recently approved.

2017-02-11 00:34 UTC, dgarros commented
@gundalow please can you review this module, thanks

2017-02-11 01:08 UTC, mattclay commented on lib/ansible/modules/network/aos/aos_blueprint.py
> +        msg = 'likely missing dependencies' if 'UNPROCESSABLE ENTITY' in exc.message \
CI failure due to python 2.4 syntax error:

```
2017-02-11 00:37:22 Compiling ./lib/ansible/modules/network/aos/aos_blueprint.py ...
2017-02-11 00:37:22   File "./lib/ansible/modules/network/aos/aos_blueprint.py", line 151
2017-02-11 00:37:22     msg = 'likely missing dependencies' if 'UNPROCESSABLE ENTITY' in exc.message \
2017-02-11 00:37:22                                          ^
2017-02-11 00:37:22 SyntaxError: invalid syntax
```

2017-02-11 13:17 UTC, gundalow requested changes

2017-02-11 13:17 UTC, gundalow commented on lib/ansible/modules/network/aos/aos_blueprint.py
> +      - An existing AOS session as obtained by aos_login module
Missing full stop.

2017-02-11 13:17 UTC, gundalow commented on lib/ansible/modules/network/aos/aos_blueprint.py
> +          architecture value. I(Refer to AOS-server documentation for available values)
Missing full stop.

2017-02-11 13:17 UTC, gundalow commented on lib/ansible/modules/network/aos/aos_blueprint.py
> +          architecture value. I(Refer to AOS-server documentation for available values)
You can embed URLS to external documentation if you wish, e.g.
`See U(http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeRouteTables.html) for possible filters.`

2017-02-11 13:17 UTC, gundalow commented on lib/ansible/modules/network/aos/aos_blueprint.py
> +      - When state='build-ready', this timeout identifies timeout in seconds to wait before
`When I(state=build-ready), this ...`

See http://docs.ansible.com/ansible/dev_guide/developing_modules_documenting.html#formatting-options for othereamples

2017-02-11 13:17 UTC, gundalow commented on lib/ansible/modules/network/aos/aos_blueprint.py
> +  timeout:
Please document default timeout.

2017-02-11 13:17 UTC, gundalow commented on lib/ansible/modules/network/aos/aos_blueprint.py
> +      - AOS Id of the IP Pool to manage (can't be used to create a new IP Pool),
Full stop, rather than comma at the end.

2017-02-11 13:17 UTC, gundalow commented on lib/ansible/modules/network/aos/aos_blueprint.py
> +      - When creating a blueprint, this value identifies, by user-name, an existing engineering
I assume to users of this module "by user-name" will make sense, or should be be "by name"?

2017-02-13 02:54 UTC, dgarros commented on lib/ansible/modules/network/aos/aos_blueprint.py
> +          architecture value. I(Refer to AOS-server documentation for available values)
Thanks, unfortunately the doc mentioned is not public currently

2017-02-13 02:55 UTC, dgarros commented
@gundalow I made all changes based on your feedback, thanks.
I keep missing these full stop ... :(

2017-02-13 12:29 UTC, gundalow approved these changes

2017-02-13 23:08 UTC, jeremyschulman commented
shipit

2017-02-13 23:20 UTC, dgarros commented
ready_for_review

2017-02-14 09:51 UTC, gundalow commented
shipit

2017-02-18 01:24 UTC, merged