New Module : aos_logical_device_map as part of network/aos
ansible/ansible pull request #21277
Opened 2017-02-11 00:13 UTC by dgarros

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
network/aos/aos_device

##### ANSIBLE VERSION
```
ansible 2.3.0 (aos_logical_device_map de9d90c9e6) last updated 2017/02/10 15:59:02 (GMT -700)
  config file =
  configured module search path = Default w/o overrides
```

##### SUMMARY
I'm working for [Apstra](http://www.apstra.com/), we are making a product to automate Datacenter Networks and we are developed a dozen of Ansible modules and one dynamic inventory to control our product with Ansible.
We have tried to follow Ansible's best practices as much as possible, all our modules are idempotent and support the mode `--check`.

This is the third batch of module that I'm submitting for review, the first `aos_ip_pool` #21044 has been recently approved.

2017-02-11 00:34 UTC, dgarros commented
@gundalow please can you review this module, thanks

2017-02-11 13:28 UTC, gundalow requested changes

2017-02-11 13:28 UTC, gundalow commented on lib/ansible/modules/network/aos/aos_logical_device_map.py
> +        on success in I(value).
+ `Only one of I(name), I(id) or I(content) can be set.`

2017-02-11 13:28 UTC, gundalow commented on lib/ansible/modules/network/aos/aos_logical_device_map.py
> +      - Indicate what is the expected state of the Logical Device Map (present or not)
Missing full stop.

2017-02-11 13:43 UTC, gundalow commented on lib/ansible/modules/network/aos/aos_logical_device_map.py
> +            module.fail_json(msg="An error occured, while trying to delete the Logical Device Map")
occurred

2017-02-13 02:40 UTC, dgarros commented
@gundalow thanks for your review, I made the changes you suggested

2017-02-13 12:31 UTC, gundalow approved these changes

2017-02-18 01:26 UTC, merged