New Module : aos_device as part of network/aos
ansible/ansible pull request #21276
Opened 2017-02-11 00:03 UTC by dgarros

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
network/aos/aos_device

##### ANSIBLE VERSION
```
ansible 2.3.0 (aos_device_clean de9d90c9e6) last updated 2017/02/10 15:59:02 (GMT -700)
  config file =
  configured module search path = Default w/o overrides
```

##### SUMMARY
I'm working for [Apstra](http://www.apstra.com/), we are making a product to automate Datacenter Networks and we are developed a dozen of Ansible modules and one dynamic inventory to control our product with Ansible.
We have tried to follow Ansible's best practices as much as possible, all our modules are idempotent and support the mode `--check`.

Currently, this module has limited features but the few it has are very useful :).
We have implemented the parameter `state` even if it only supports 1 state right because we know that we will add more very soon, unfortunately it won't be ready for the 2.3 deadline.

This is the third batch of modules that I'm submitting for review, the first `aos_ip_pool` #21044 has been recently approved.

2017-02-11 00:03 UTC, dgarros commented
@gundalow if you have a moment please can you review this one as well, thanks

2017-02-11 13:24 UTC, gundalow requested changes

2017-02-11 13:24 UTC, gundalow commented on lib/ansible/modules/network/aos/aos_device.py
> +      - An existing AOS session as obtained by aos_login module
Missing full stop.

2017-02-11 13:24 UTC, gundalow commented on lib/ansible/modules/network/aos/aos_device.py
> +      - When approving a device using the I(approve) argument, it's possible
In `argspec` you could use `required_if` to enforce this. Assuming you want to throw an error if `location` is set and `approve` isn't

2017-02-11 13:24 UTC, gundalow commented on lib/ansible/modules/network/aos/aos_device.py
> +            approve=dict( required=False ),
Should this be `type='bool'`, or is it more complex?

If it's more complex then it might be worth expanding the description for this option.

2017-02-11 13:24 UTC, gundalow commented on lib/ansible/modules/network/aos/aos_device.py
> +            module.fail_json(msg="Device is not in 'normal' state")
Would it be worth updating the message to "Device is in '%s' rather than 'normal' state"?

2017-02-13 02:41 UTC, dgarros commented on lib/ansible/modules/network/aos/aos_device.py
> +      - When approving a device using the I(approve) argument, it's possible
Location is not mandatory when using `approve`, thanks for the tips

2017-02-13 02:45 UTC, dgarros commented on lib/ansible/modules/network/aos/aos_device.py
> +            approve=dict( required=False ),
Good point, i changed it to `type='bool'`, thanks

2017-02-13 02:47 UTC, dgarros commented
@gundalow thanks for the review, i made the changes

2017-02-13 12:30 UTC, gundalow approved these changes

2017-02-13 23:20 UTC, dgarros commented
ready_for_review

2017-02-14 09:50 UTC, gundalow commented
shipit

2017-02-18 01:23 UTC, merged