ec2.py: Better error messages for OptInRequired
ansible/ansible pull request #21292
Opened 2017-02-11 18:02 UTC by lorin

For ec2 dynamic inventory plugin, improve error messages for RDS and ElastiCache failures for code OptInRequired.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
ec2.py inventory plugin

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file =
  configured module search path = Default w/o overrides
```

##### SUMMARY

This change improves the error messages shown for ec2.py inventory plugin when it fails connecting to either rds or elasticache with the OptInRequired error code.

Fixes #10840

Before change:

```
$ ./ec2.py --list
ERROR: "Forbidden", while: getting RDS instances

$ ./ec2.py --list
ERROR: "Forbidden", while: getting ElastiCache clusters
```

After change:

```
$  ./ec2.py --list
ERROR: "RDS hasn't been enabled for this account yet. You must either log in to the RDS service through the AWS console to enable it, or set 'rds = False' in ec2.ini", while: getting RDS instances

$ ./ec2.py --list
ERROR: "ElastiCache hasn't been enabled for this account yet. You must either log in to the ElastiCache service through the AWS console to enable it, or set 'elasticache = False' in ec2.ini", while: getting ElastiCache cluster

```

2017-02-13 12:11 UTC, willthames commented
shipit

2017-02-13 14:53 UTC, bcoca requested changes

2017-02-13 14:53 UTC, bcoca commented on contrib/inventory/ec2.py
> +            if e.error_code == "OptInRequired":
use elif, its a minor optimization but will avoid overwriting errors. Same below.

2017-07-05 15:02 UTC, merged

2017-07-05 15:02 UTC, calfonso commented
@lorin Are you planning to update this PR, if so please do so and we'll get it merged. Thanks!

2017-07-05 15:57 UTC, lorin commented
@calfonso Somehow I missed the notifications about @bococa's requested changes to the PR, but it looks like @bcoca merged it as-is.