passwordstore (pass) lookup module
ansible/ansible pull request #21314
Opened 2017-02-12 19:39 UTC by morphje

##### ISSUE TYPE
 - New Lookup Plugin Pull Request
This closes PR #16672

##### COMPONENT NAME
passwordstore.py

##### ANSIBLE VERSION
ansible 2.3.0.0

##### SUMMARY
Adding a 'password-store' lookup plugin, which allows one to query passwords in an password store (passwordstore.org). Includes options to create passwords, insert passwords, update passwords and retreive KV values as arbritrary data.

##### EXAMPLES# Basic lookups
- name: create a new random password
  debug: msg="{{ lookup('pass', 'testpass/example1 create=true') }}"
- name: create a longer random password
  debug: msg="{{ lookup('pass', 'testpass/example2 create=true length=42') }}"
- name: update password entry with new random password
  debug: msg="{{ lookup('pass', 'testpass/example1 overwrite=true') }}"
- name: read example1 from the store, does not update
  debug: msg="{{ lookup('pass', 'testpass/example1 create=true') }}"
- name: read non-existent example0 (and fail)
  debug: msg="{{ lookup('pass', 'testpass/example0') }}"
  ignore_errors: true
# user defined password examples
- name: create example3 with a userdefined password
  debug: msg="{{ lookup('pass', 'testpass/example3 create=true userpass=r4nd0mPwd') }}"
- name: read example3 with the same statement. No overwrite
  debug: msg="{{ lookup('pass', 'testpass/example3 create=true userpass=somethingelse') }}"
- name: update example3 with a bad userdefined password
  debug: msg="{{ lookup('pass', 'testpass/example3 create=true userpass=Welcome01') }}"
# interacting with other data in the password store
- name: read entire password file
  debug: msg="{{ lookup('pass', 'testpass/example2 returnall=true').split('\n') }}"
- name: read a kv value from the password store
  debug: msg="{{ lookup('pass', 'testpass/example2 subkey=lookup_pass') }}"

2017-02-13 14:32 UTC, ryansb requested changes

2017-02-13 14:32 UTC, ryansb commented on lib/ansible/plugins/lookup/passwordstore.py
> +#!/usr/bin/python
This shebang isn't needed, since the module isn't run standalone.

2017-02-13 14:32 UTC, ryansb commented on lib/ansible/plugins/lookup/passwordstore.py
> +# Name:        passwordstore.py
The licensing should match the rest of Ansible, see [this example](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/lookup/dig.py#L1-L16)

2017-02-14 10:51 UTC, morphje commented
implemented changes as requested

2017-02-14 15:30 UTC, ryansb approved these changes

2017-02-14 15:33 UTC, bcoca commented
@morphje can you make sure the original commit keeps attribution to @sigio ?

2017-02-14 16:03 UTC, morphje commented
@bcoca actually i am the original author of the plugin. In his previous pull request he referred his import request to my repo. You can check the development history at https://github.com/morphje/ansible_pass_lookup. He attributed himself as "bugging morphje to develop the plugin".

I plan to deprecate my repo as soon as this lookup is integrated into ansible.
sigio doesn't have a fork of my repo any more.

2017-02-14 16:12 UTC, merged

2017-02-14 16:23 UTC, sigio commented
nice :) good to see this merged