Ensure that s3_bucket versioning is correctly enabled
ansible/ansible pull request #21320
Opened 2017-02-13 00:42 UTC by willthames

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
s3_bucket

##### ANSIBLE VERSION
```
ansible 2.3.0 (devel a6cb377420) last updated 2017/02/13 10:23:20 (GMT +1000)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY
If versioning is not enabled, then `get_bucket_versioning`
can return an empty dict.

If that happens, the code to enable versioning should still
run!

The logic for suspending versioning was also incorrect, so
have updated that too.

Fixes #20491

Tested with:
```
hacking/test-module -m lib/ansible/modules/cloud/amazon/s3_bucket.py -a "profile=sandbox name=test-2017-02-13-1039 versioning=no"
 hacking/test-module -m lib/ansible/modules/cloud/amazon/s3_bucket.py -a "profile=sandbox name=test-2017-02-13-1039 versioning=yes"
 hacking/test-module -m lib/ansible/modules/cloud/amazon/s3_bucket.py -a "profile=sandbox name=test-2017-02-13-1039 versioning=no"
```

and results now as expected

2017-02-13 18:33 UTC, s-hertel approved these changes

2017-02-13 20:03 UTC, ryansb requested changes

2017-02-13 20:03 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/s3_bucket.py
> +                module.fail_json(msg=e.message)
Please add the traceback to this message with `exception=traceback.format_exc()`

2017-02-13 23:19 UTC, willthames commented on lib/ansible/modules/cloud/amazon/s3_bucket.py
> +                module.fail_json(msg=e.message)
This code isn't actually changing (apart from the change to indentation)

There is no documentation that exceptions should be returned when calling `fail_json`.

I can do this, but it's a surprise that I should need to.

2017-02-14 23:52 UTC, willthames commented
@ryansb traceback added to exceptions and various pep8 issues resolved

2017-02-16 01:37 UTC, willthames commented
!needs_revision

2017-02-16 14:43 UTC, ryansb approved these changes

2017-02-16 14:45 UTC, merged