Improving of nxos_ip_interface module
ansible/ansible pull request #21353
Opened 2017-02-13 19:33 UTC by Drey

Added features:

  * Route tags for an IP address at interface level with 'tag' option
  * Support of IPv4 secondary addresses if option `allow_secondary` is
true (false by default). If option `allow_secondary` is true primary
IPv4 address will be replaced

All features support NXAPI and CLI transport, but only with text/raw
output. Currently not possible to get route tags for secondary IPv4/IPv6
addresses from JSON output.

Other changes:
  * Module return state 'changed' only when configuration commands were
executed
  * Module result includes multiple prefixes if IPv4 addresses were
found

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
ansible/modules/network/nxos/nxos_ip_interface

##### ANSIBLE VERSION
```
ansible --version
ansible 2.2.1.0 (stable-2.2 6176c95838) last updated 2017/02/13 16:48:05 (GMT +300)
  lib/ansible/modules/core: (feature-nxos-ip-interface 2c1f374da0) last updated 2017/02/13 21:58:33 (GMT +300)
  lib/ansible/modules/extras: (detached HEAD 994349b647) last updated 2017/02/13 16:58:44 (GMT +300)
  config file = /Users/idrey/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY
I have tested this commit with playbook that can be downloaded by [link](https://gist.github.com/Drey/fa7360f9746c6269f17598b96cb95d82) and Ansible version from branch stable-2.2.

Thanks!

2017-02-13 20:02 UTC, mattclay commented
CI failure due to PEP 8 issues:

```
2017-02-13 19:37:16 ERROR: PEP 8: lib/ansible/modules/network/nxos/nxos_ip_interface.py:164:6: E111 indentation is not a multiple of four (current)
2017-02-13 19:37:16 ERROR: PEP 8: lib/ansible/modules/network/nxos/nxos_ip_interface.py:165:10: E111 indentation is not a multiple of four (current)
2017-02-13 19:37:16 ERROR: PEP 8: lib/ansible/modules/network/nxos/nxos_ip_interface.py:166:6: E111 indentation is not a multiple of four (current)
2017-02-13 19:37:16 ERROR: PEP 8: lib/ansible/modules/network/nxos/nxos_ip_interface.py:167:10: E111 indentation is not a multiple of four (current)
2017-02-13 19:37:16 ERROR: PEP 8: lib/ansible/modules/network/nxos/nxos_ip_interface.py:168:6: E111 indentation is not a multiple of four (current)
2017-02-13 19:37:16 ERROR: PEP 8: lib/ansible/modules/network/nxos/nxos_ip_interface.py:169:10: E111 indentation is not a multiple of four (current)
2017-02-13 19:37:16 ERROR: PEP 8: lib/ansible/modules/network/nxos/nxos_ip_interface.py:541:33: E126 continuation line over-indented for hanging indent (current)
2017-02-13 19:37:16 ERROR: PEP 8: lib/ansible/modules/network/nxos/nxos_ip_interface.py:560:161: E501 line too long (185 > 160 characters) (current)
2017-02-13 19:37:16 ERROR: PEP 8: lib/ansible/modules/network/nxos/nxos_ip_interface.py:627:6: W291 trailing whitespace (current)
2017-02-13 19:37:16 ERROR: PEP 8: lib/ansible/modules/network/nxos/nxos_ip_interface.py:717:13: E126 continuation line over-indented for hanging indent (current)
```

2017-02-14 02:11 UTC, privateip requested changes

2017-02-14 02:11 UTC, privateip commented on lib/ansible/modules/network/nxos/nxos_ip_interface.py
> +version_added: "2.2"
`version_added` should not be changed

2017-02-14 02:11 UTC, privateip commented on lib/ansible/modules/network/nxos/nxos_ip_interface.py
> +import ipaddress
`ipaddress` doesn't exist in py2... need to wrap this in a try ... except

2017-02-14 02:12 UTC, privateip commented
/cc @GGabriele

2017-02-14 08:16 UTC, Drey commented on lib/ansible/modules/network/nxos/nxos_ip_interface.py
> +import ipaddress
Fixed the same way as in other modules. Thanks.

2017-02-14 08:16 UTC, Drey commented on lib/ansible/modules/network/nxos/nxos_ip_interface.py
> +version_added: "2.2"
Fixed. Thanks!

2017-02-14 08:39 UTC, gundalow requested changes

2017-02-14 08:39 UTC, gundalow commented on lib/ansible/modules/network/nxos/nxos_ip_interface.py
> +        default: 0
Please add:
`version_added: "2.3"`

2017-02-14 08:39 UTC, gundalow commented on lib/ansible/modules/network/nxos/nxos_ip_interface.py
> +        required: false
Please add:
`version_added: "2.3"`

2017-02-14 08:39 UTC, gundalow commented on lib/ansible/modules/network/nxos/nxos_ip_interface.py
> +    HAS_IPADDRESS = True
Please docent this in the `requirements:` block
See http://docs.ansible.com/ansible/dev_guide/developing_modules_documenting.html#documentation-block for details.

2017-02-14 09:14 UTC, Drey commented on lib/ansible/modules/network/nxos/nxos_ip_interface.py
> +    HAS_IPADDRESS = True
I did it. Thanks for introduction!

2017-02-14 09:45 UTC, gundalow approved these changes
I'm happy with the docs, not reviewed the code

2017-02-16 08:30 UTC, Drey commented
Hello, maybe I need to provide some additional information about changes in the commit? Or improve something? Let me know if I can help.

2017-02-16 14:52 UTC, Drey commented
I have tried to resolve conflicts but could you describe for me how I can keep that module working for both `devel` and `stable-2.2` branches? I think that the only way to do it is a duplication of some code inside nxos_ip_interfaces. Is it the excellent idea?

I have tested all my commits with the branch `stable-2.2` and all features work properly.

2017-03-25 12:04 UTC, privateip commented
@Drey in order to merge the PR it must be rebased against the devel branch.

needs_rebase

2017-03-26 21:11 UTC, Drey commented
@privateip Hi! I have done rebase. Thanks.

2017-03-27 11:06 UTC, gundalow approved these changes

2017-03-30 14:51 UTC, Drey commented
@privateip Hi! What do you think about my latest commit? Maybe I need to improve something?

2017-03-31 18:35 UTC, gundalow commented
@Drey Thanks for this PR (and rebasing it).
We are currently busy working through the final touches for Ansible 2.3.

I've added the Milestone 2.4 marker to this so we will review once 2.3 is complete.

Thanks again

2017-04-27 15:46 UTC, Qalthos commented on lib/ansible/modules/network/nxos/nxos_ip_interface.py
> +            - Route tag for IPv4 ot IPv6 Address in integer format.
IPv4 *or* IPv6, presumably

2017-05-04 11:09 UTC, gundalow requested changes

2017-05-04 11:09 UTC, gundalow commented on lib/ansible/modules/network/nxos/nxos_ip_interface.py
> +                             choices=[True, False], type='bool'),
Please remove choices for `type='bool'`, as `bool` accepts yes,1,true, etc.

2017-05-10 09:11 UTC, Drey commented on lib/ansible/modules/network/nxos/nxos_ip_interface.py
> +                             choices=[True, False], type='bool'),
Thanks, done

2017-05-12 15:45 UTC, merged