refactors junos modules to support persistent socket connections
ansible/ansible pull request #21365
Opened 2017-02-13 21:43 UTC by privateip

* updates junos_netconf module
* updates junos_command module
* updates junos_config module
* updates _junos_template module
* adds junos_rpc module
* adds junos_user module

2017-02-14 00:35 UTC, mattclay commented
CI failure due to python 2.4 syntax errors:

```
2017-02-13 23:28:10 Compiling ./lib/ansible/module_utils/junos_compat.py ...
2017-02-13 23:28:10   File "./lib/ansible/module_utils/junos_compat.py", line 1
2017-02-13 23:28:10     2015 Peter Sprygada, <psprygada@ansible.com>
2017-02-13 23:28:10     ^
2017-02-13 23:28:10 SyntaxError: invalid syntax
2017-02-13 23:28:10 
2017-02-13 23:28:10 Compiling ./lib/ansible/modules/network/junos/junos_config.py ...
2017-02-13 23:28:10   File "./lib/ansible/modules/network/junos/junos_config.py", line 280
2017-02-13 23:28:10     with locked_config:
2017-02-13 23:28:10                      ^
2017-02-13 23:28:10 SyntaxError: invalid syntax
2017-02-13 23:28:10 
2017-02-13 23:28:10 Compiling ./lib/ansible/modules/network/junos/junos_netconf.py ...
2017-02-13 23:28:10   File "./lib/ansible/modules/network/junos/junos_netconf.py", line 153
2017-02-13 23:28:10     result = {'changed': False, warnings=warnings}
2017-02-13 23:28:10                                         ^
2017-02-13 23:28:10 SyntaxError: invalid syntax
```

2017-02-15 18:06 UTC, Qalthos commented on lib/ansible/modules/network/junos/_junos_template.py
> +    confirm
This looks unnecessary?

2017-02-15 18:06 UTC, Qalthos commented on lib/ansible/modules/network/junos/junos_config.py
> +        #'comment': module.params['comment'],
Should these be removed entirely?

2017-02-15 19:56 UTC, privateip commented on lib/ansible/modules/network/junos/junos_config.py
> +        #'comment': module.params['comment'],
argh... good catch, those need to be implemented

2017-02-15 19:57 UTC, privateip commented on lib/ansible/modules/network/junos/_junos_template.py
> +    confirm
hey whats that doing there ?!?!?!?!? .... new PR coming shortly

2017-02-15 20:41 UTC, Qalthos requested changes

2017-02-15 20:41 UTC, Qalthos commented on lib/ansible/module_utils/junos.py
> +def load(module, candidate, action='merge', commit=False, format='xml')
Need a colon at the end here

2017-02-16 14:36 UTC, Qalthos requested changes

2017-02-16 14:36 UTC, Qalthos commented on lib/ansible/modules/network/junos/junos_user.py
> +ROLES = ['operator', 'read-onYly', 'super-user', 'unauthorized']
`read-onYly` should probably be `read-only`

2017-02-16 15:53 UTC, merged