win_timezone: Clean up and check-mode support
ansible/ansible pull request #21387
Opened 2017-02-14 02:47 UTC by dagwieers

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

win_timezone

##### ANSIBLE VERSION

v2.3

##### SUMMARY

Changes include:
- Use Get-AnsibleParam with -type support
- Replace $result PSObject with normal hash
- Add check-mode support

2017-02-16 12:31 UTC, dagwieers commented
ready_for_review

2017-02-16 15:51 UTC, schwartzmx commented
lgtm

shipit

2017-02-20 21:03 UTC, jborean93 requested changes

2017-02-20 21:03 UTC, jborean93 commented on lib/ansible/modules/windows/win_timezone.ps1
> +$timezone = Get-AnsibleParam -obj $params -name "timezone" -failifempty $true -resultobj $result
Do we want to change this and remove the -resultobj to keep in line with the rest of the modules?

2017-02-20 21:03 UTC, jborean93 commented on lib/ansible/modules/windows/win_timezone.ps1
> +$result = @{
$ErrorActionPreference = "Stop" like other modules?

2017-02-20 21:03 UTC, jborean93 commented on lib/ansible/modules/windows/win_timezone.ps1
>          Exit-Json $result "$timezone is already set on this machine"
Do we need this here or should we just remove this if branch and just exit at the end of the code like normal

2017-02-20 21:03 UTC, jborean93 commented on lib/ansible/modules/windows/win_timezone.ps1
>      Fail-Json $result "Error setting timezone to: $timezone."
Add in $($_.Error.Message) to the end for better error handling.

2017-02-20 21:04 UTC, jborean93 commented
Hey @dagwieers just requested some changes to keep this more in line with the other work you have done, let me know your thoughts.

2017-02-20 21:14 UTC, dagwieers commented on lib/ansible/modules/windows/win_timezone.ps1
> +$result = @{
Well, I didn't want to change the module in other ways then just the things I now changed.
Things like this we have to discuss with the Windows working group.

2017-02-20 21:20 UTC, dagwieers commented on lib/ansible/modules/windows/win_timezone.ps1
> +$timezone = Get-AnsibleParam -obj $params -name "timezone" -failifempty $true -resultobj $result
To be honest, the -resultobj does not seem to do anything except be used for error-handling within the AnsibleParam function. So I would remove them myself, but I don't think I am smarter than the person who added it, so I restricted myself to the stuff I do know and are safe to change.

2017-02-20 21:23 UTC, dagwieers commented
@jborean93 In general I wanted to restrict myself to AnsibleParam, $result hash and maybe $check_mode. Not a complete rewrite. In some cases I did modify the indentation/syntax, but mostly when that wasn't consistent within the file. I know it is frowned upon to change cosmetics.

2017-02-20 22:43 UTC, jborean93 approved these changes

2017-02-20 22:43 UTC, jborean93 commented
@dagwieers no worries I was unsure what the scope of your changes were, looks good.

shipit

2017-02-21 06:01 UTC, jhawkesworth commented
Looks good to me and has 2 shipits, 1 from the maintainer, so I'm merging this in.

2017-02-21 06:01 UTC, merged