Use with statement when doing rw on files
ansible/ansible pull request #21390
Opened 2017-02-14 03:27 UTC by AlejandroTrev

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
contrib/inventory/ec2.py

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = 
  configured module search path = Default w/o overrides
```

##### SUMMARY
Small bug fix to make sure files are closed when they're opened. Uses python's `with` statement. Compatible with python 2.5 and above.
```
./ec2.py --list
# printed huge list, took a while to display

./ec2.py --list
# second time around was much faster, since results were cached
# (confirms my change works as expected)
```

2017-02-14 03:40 UTC, willthames commented
shipit

2017-02-14 19:47 UTC, ryansb requested changes

2017-02-14 19:47 UTC, ryansb commented on contrib/inventory/ec2.py
> +            self.index = json.loads(json_index)
Instead, please set `self.index = json.load(f)`. The JSON library uses the `.load` function to stream straight from files without needing to `.read()` first. This also avoids pesky encoding issues with Python2/3.

2017-02-15 01:46 UTC, AlejandroTrev commented on contrib/inventory/ec2.py
> +            self.index = json.loads(json_index)
Done! Updated the PR.

2017-02-16 01:04 UTC, willthames commented
shipit

2017-02-16 01:04 UTC, willthames commented
!needs_revision

2017-02-16 14:41 UTC, ryansb approved these changes

2017-02-16 14:41 UTC, merged