cloud/vmware/vmware_vmotion: added storage vmotion capabilities.
ansible/ansible pull request #21421
Opened 2017-02-14 18:40 UTC by gdepuille

##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

vmware_vmotion.py
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

Added "Storage vMotion" capabilities to vmware_vmotion module.
Now enables the virtual machine storage migration to another datastore, simultaneously (or not, up the the module invocation) with the virtual machine host migration.
Doesn't break compatibility with the previous version of the module.

**Needs ansible/ansible#17538 to be merged for this change to work**

output before:

```
{
    "changed": true, 
    "invocation": {
        "module_args": {
            "destination_host": "esx2", 
            "hostname": "myvcenter", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "username": "administrator@myvspheredomain.com", 
            "vm_name": "myVM"
        }
    }, 
    "running_host": "esx2"
}

```

output after:

```
{
    "changed": true, 
    "datastores": [
        "datastore2"
    ], 
    "invocation": {
        "module_args": {
            "destination_datastore": "datastore2", 
            "destination_host": "esx2", 
            "hostname": "myvcenter", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "username": "administrator@myvspheredomain.com", 
            "vm_name": "myVM"
        }
    }, 
    "running_host": "esx2"
}

```

2017-02-14 18:57 UTC, gdepuille commented
@mattclay I seen your comment after the CI failure in the previous PR. I will solve this tomorrow.

2017-06-02 07:53 UTC, gdepuille commented
Hi, 
I realized a rebase for this PR.
Can you explain to me if I've missed a step in the process for validate this one ?

2017-06-15 08:48 UTC, MKPhil commented
I'm interested in storage vMotion functionality too, to the point of writing my own variant of vmware_vmotion, which turned out to be virtually identical to this PR! (great minds think alike!)  However, whilst it can do vMotion / storage vMotion _within_ a Cluster, I get an error moving the VM to another Cluster:
`A specified parameter was not correct:`
I'm not sure if it's my environment or not - I've only got one vCenter I can test with that has multiple Clusters.  Using the GUI or PowerCLI command Move-VM works OK.
Any thoughts on how to get this working between Clusters?

2017-10-08 15:38 UTC, Akasurde commented
@gdepuille Could you please rebase this PR?

2017-10-08 15:40 UTC, Akasurde requested changes

2017-10-08 15:40 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_vmotion.py
> +author: "Bede Carroll (@bedecarroll) / Olivier Boukili (@oboukili)"
Author should be list

```yaml
author:
   - Bede...
   - Oliver...
```

2017-10-08 15:40 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_vmotion.py
> +        required: False
required is by-default false so no need to specify.

2017-10-09 09:29 UTC, gdepuille commented
@Akasurde I've done the rebase and I changed documentation like your last comment suggestion.

2017-10-09 09:39 UTC, Akasurde commented
@gdepuille Could you please add integration test for this change as well ? you can start by looking at [vmware guest test](https://github.com/ansible/ansible/tree/devel/test/integration/targets/vmware_guest)

2017-10-09 13:45 UTC, gdepuille commented
@Akasurde I will check your link to add integration test, probably, this week.

2017-10-09 13:46 UTC, gdepuille commented
@Akasurde The rebase and CI is OK.

2018-01-06 11:33 UTC, Akasurde commented
@gdepuille Are you still working on this ? Let me know if not, I will take over this PR.

2018-01-12 09:31 UTC, gdepuille commented
@Akasurde I will try to complete your requested features (add integration test, rebase, etc...). I'm sorry, but now I've some business developments must be completed in my company before finish this one.

2018-05-12 06:23 UTC, Akasurde approved these changes

2018-05-12 06:23 UTC, Akasurde commented
cc @pdellaert @gdepuille @dericcrago Could you please review latest changes ?

2018-05-26 21:27 UTC, Alex5252 commented
I am check this merge and code work, as expected, except this example:
destination_host (old (current))
destination_datastore  (new)
If destination_host select as current esxi host and destination_datastore select as new datastore, when virtual machine to new destination_datastore not vmotion'ed.

2018-07-07 05:23 UTC, Alex5252 commented
I am check this merge and code work, as expected, regardless of order destination_host (current/new)) and destination_datastore (current/new)
If destination_host select as current esxi host and destination_datastore select as new datastore, when virtual machine to new destination_datastore not vmotion'ed.
@Akasurde, many thanks!

2018-07-17 08:44 UTC, Akasurde commented
@dericcrago @jctanner @pdellaert Could you please review this ?

2018-07-17 13:10 UTC, jctanner approved these changes
I am unable to test, but the code looks okay.

2018-07-17 13:36 UTC, Akasurde commented
rebuild_merge

2018-07-17 15:13 UTC, merged

2018-07-17 15:14 UTC, Akasurde commented
@gdepuille Thanks for the contribution. @Alex5252 @jctanner Thanks for the reviews.