New Module : aos_blueprint_virtnet as part of network/aos
ansible/ansible pull request #21432
Opened 2017-02-14 22:20 UTC by dgarros

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
network/aos/aos_blueprint_virtnet

##### ANSIBLE VERSION
```
ansible 2.3.0 (aos_blueprint de9d90c9e6) last updated 2017/02/10 15:59:02 (GMT -700)
  config file =
  configured module search path = Default w/o overrides
```

##### SUMMARY
I'm working for [Apstra](http://www.apstra.com/), we are making a product to automate Datacenter Networks and we are developed a dozen of Ansible modules and one dynamic inventory to control our product with Ansible.
We have tried to follow Ansible's best practices as much as possible, all our modules are idempotent and support the mode `--check`.

This is the third batch of module that I'm submitting for review, the first `aos_ip_pool` #21044 has been recently approved.

2017-02-14 22:21 UTC, dgarros commented
@gundalow Please could you review this module, it's the last one we would like to contribute for Ansible 2.3
Thanks for all your help so far .

2017-02-14 22:25 UTC, gundalow requested changes

2017-02-14 22:25 UTC, gundalow commented on lib/ansible/modules/network/aos/aos_blueprint_virtnet.py
> +    aos_blueprint_virtnet:
Indentation looks wrong here

2017-02-14 22:29 UTC, dgarros commented
@gundalow thanks for your quick review and good catch I fixed it.    
ready_for_review

2017-02-14 23:17 UTC, gundalow approved these changes

2017-02-15 11:13 UTC, gundalow approved these changes

2017-02-18 01:22 UTC, merged