Remove the end of the task_data.path which causes #21461
ansible/ansible pull request #21463
Opened 2017-02-15 14:26 UTC by hogarthj

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
junit

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY
Fixes #21461 

This just jumps off the \.yml:[0-9]+ from task_data.path so that python-junit_xml does not see that in the classname passed in. 

As a result parsing the results and displaying them in Jenkins or similar is far more readable and much easier to compare and follow.

I've tested this against our internal ansible role testing and it behaves as the sed workaround in the issue does.

2017-02-15 14:53 UTC, gundalow commented
@mattclay I believe you wrote the original script

2017-02-15 21:00 UTC, mattclay commented
Having the full file path to the playbook and the line number of the task is an intentional feature. I'm open to having an option to drop those from the output though.

2017-02-15 21:01 UTC, mattclay commented
needs_revision

2017-02-15 21:05 UTC, mattclay requested changes
Add a `JUNIT_` prefixed environment variable to control the behavior of the class naming, so the existing behavior can be maintained as the default.

2017-02-15 22:00 UTC, hogarthj commented
@mattclay as requested a new environment variable to tune behaviour.

It defaults to the current behaviour so as not to break anyone's workflow or scripting or visualization tools but setting JUNIT_TASK_CLASS="True" will switch it to one class per yaml file in tasks instead.

2017-02-15 22:19 UTC, mattclay commented on lib/ansible/plugins/callback/junit.py
> +        self._task_class = os.getenv('JUNIT_TASK_CLASS', 'False').to_lower()
CI failure due to:

```
2017-02-15 21:58:57 Traceback (most recent call last):
2017-02-15 21:58:57   File "/root/ansible/bin/ansible-playbook", line 103, in <module>
2017-02-15 21:58:57     exit_code = cli.run()
2017-02-15 21:58:57   File "/root/ansible/lib/ansible/cli/playbook.py", line 156, in run
2017-02-15 21:58:57     results = pbex.run()
2017-02-15 21:58:57   File "/root/ansible/lib/ansible/executor/playbook_executor.py", line 89, in run
2017-02-15 21:58:57     self._tqm.load_callbacks()
2017-02-15 21:58:57   File "/root/ansible/lib/ansible/executor/task_queue_manager.py", line 196, in load_callbacks
2017-02-15 21:58:57     self._callback_plugins.append(callback_plugin())
2017-02-15 21:58:57   File "/root/ansible/lib/ansible/plugins/callback/junit.py", line 76, in __init__
2017-02-15 21:58:57     self._task_class = os.getenv('JUNIT_TASK_CLASS', 'False').to_lower()
2017-02-15 21:58:57 AttributeError: 'str' object has no attribute 'to_lower'
```

2017-02-15 22:20 UTC, mattclay commented on lib/ansible/plugins/callback/junit.py
> +        self._task_class = os.getenv('JUNIT_TASK_CLASS', 'False').to_lower()
This should be `lower` instead of `to_lower`.

2017-02-15 22:29 UTC, hogarthj commented
Urgh how embarrassing ... that's what I get for between multitasking between different languages ...

2017-02-15 23:43 UTC, hogarthj commented
@mattclay there that's corrected

2017-02-15 23:59 UTC, mattclay requested changes
One minor style fix requested. The rest looks good.

2017-02-15 23:59 UTC, mattclay commented on lib/ansible/plugins/callback/junit.py
> +        if (self._task_class == 'true'):
Remove the redundant parenthesis.

2017-02-16 00:28 UTC, hogarthj commented
@mattclay style tweak made and rebased to a single clean commit

2017-02-16 00:35 UTC, mattclay commented
@hogarthj Thanks. For future reference, there's no need to squash commits, as that will be done when the PR is merged. It's actually easier to review if you just add additional commits. Performing a rebase when there are merge conflicts is fine -- but that can be done without squashing commits.

2017-02-16 00:54 UTC, hogarthj commented
@mattclay oh sorry - didn't realise that one ... I'll keep that in mind for future PRs here :)

2017-02-16 01:32 UTC, mattclay approved these changes

2017-02-16 01:35 UTC, merged

2017-02-16 01:35 UTC, mattclay commented
Merged. Thanks!