Introduce module.warn() in all modules
ansible/ansible pull request #21572
Opened 2017-02-17 12:44 UTC by dagwieers

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

Various modules, incl cloudformation, ec2_eip, assemble, git, mount, asa_command, ce_command,  dellos10_command, dellos6_command, dellos9_command, eos_command, ios_command, iosxr_command, junos_command, ops_command, sros_command, vyos_command,

##### ANSIBLE VERSION

v2.3

##### SUMMARY

This is a small rewrite of all warnings to use module.warn()
We kept compatibility with check_args() in the various common network
libraries in module_utils so that out-of-tree modules keep on working.

2017-02-17 13:15 UTC, willthames commented
@dagwieers is there an associated PR reflecting the introduction of `module.warn()` ?

2017-02-17 13:19 UTC, dagwieers commented
@willthames I don't think so, looking for this functionality through `git blame` brought me to https://github.com/ansible/ansible/commit/7e6758873c41699cf1447e91f778452bf49969e9

2017-02-17 13:23 UTC, willthames commented on lib/ansible/modules/files/assemble.py
> +            module.warn('Unable to remove temp file (%s): %s' % (path, str(e))])
Looks like test failures are due to extra `]` just before the end of this line

2017-02-17 13:24 UTC, willthames commented
Happy with this once tests pass (will upgrade this comment to shipit at that point)

2017-02-17 18:50 UTC, bcoca requested changes

2017-02-17 18:50 UTC, bcoca commented on lib/ansible/modules/files/assemble.py
> -def cleanup(path, result=None):
unrelated change

2017-02-17 18:50 UTC, bcoca commented on lib/ansible/modules/network/eos/_eos_template.py
deprecated module, no need to change

2017-02-17 18:50 UTC, bcoca commented on lib/ansible/modules/network/ios/_ios_template.py
> +    check_args(module)
also deprecated

2017-02-17 18:50 UTC, bcoca commented on lib/ansible/modules/network/junos/junos_command.py
> +def check_args(module):
to make change backwards compatible with modules not in repo, make `warnings=None`

2017-02-18 11:01 UTC, dagwieers commented on lib/ansible/modules/files/assemble.py
> -def cleanup(path, result=None):
In order to let the cleanup function use `module.warn()`, I need to expose module to that function, and `result` is no longer needed. So this is pretty much needed as part of making everything use `module.warn()`.

2017-02-18 11:02 UTC, dagwieers commented on lib/ansible/modules/network/eos/_eos_template.py
Well, since I already did and it is deprecated, I'll let the change be.

2017-02-18 11:02 UTC, dagwieers commented on lib/ansible/modules/network/ios/_ios_template.py
> +    check_args(module)
No problem then.

2017-02-18 11:04 UTC, dagwieers commented on lib/ansible/modules/network/junos/junos_command.py
> +def check_args(module):
Hmm, I forgot this one apparently. I did it for all the others.

2017-02-18 11:06 UTC, dagwieers commented on lib/ansible/modules/network/junos/junos_command.py
> +def check_args(module):
Ah, I see, this function is only exposed to this module, so it doesn't really matter, there's no incompatibility here.
I did modify all of the mod_utils functions correctly.

2017-02-18 11:08 UTC, dagwieers commented
So the weird thing now is that I don't think I have to make any changes, but I have no means of closing the review comments. And ansibot will be stuck in this state.
bot_status

2017-02-18 11:08 UTC, dagwieers commented
ready_for_review

2017-02-18 20:16 UTC, dagwieers commented
@jctanner Please advise :-)

2017-02-19 23:15 UTC, willthames commented
@dagwieers you can use !needs_revision to remove that label, but this now needs_rebase

2017-02-20 10:39 UTC, dagwieers commented
!needs_revision

2017-02-20 14:21 UTC, bcoca commented on lib/ansible/modules/network/eos/_eos_template.py
no, really, remove the deprecated files from your commit

2017-02-20 14:25 UTC, dagwieers commented on lib/ansible/modules/network/ios/_ios_template.py
> +    check_args(module)
@bcoca The reason for me to update the deprecated files is that we don't want people to use those as a reference of how to do it. If we don't have any bad examples, people can't copy them either.

2017-02-20 14:25 UTC, dagwieers commented on lib/ansible/modules/network/eos/_eos_template.py
@bcoca The reason for me to update the deprecated files is that we don't want people to use those as a reference of how to do it. If we don't have any bad examples, people can't copy them either.

2017-02-20 14:27 UTC, bcoca commented on lib/ansible/modules/network/ios/_ios_template.py
> +    check_args(module)
i cannot imagine people look at deprecated files first for examples ...., but they do see changes to them and then try to use those to justify subsequent changes.

2017-02-20 14:49 UTC, dagwieers commented on lib/ansible/modules/network/ios/_ios_template.py
> +    check_args(module)
You cannot imagine, but people do this all the time. I often grep for strings to get quick examples (i.e. warning in this case). And you don't know a module is deprecated unless you are specifically looking for it. So to me it is still important and relevant to make these changes to deprecated modules.

2017-02-23 09:23 UTC, closed without merging