win_nssm: Clean up parameter handling + docs
ansible/ansible pull request #21625
Opened 2017-02-18 22:36 UTC by dagwieers

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

win_nssm

##### ANSIBLE VERSION

v2.3

##### SUMMARY

Changes include:
- Use Get-AnsibleParam with -type
- Replace $result PSObject with normal hash
- Clean up documentation

2017-02-20 21:10 UTC, jborean93 commented on lib/ansible/modules/windows/win_nssm.ps1
> +$state = Get-AnsibleParam -obj $params -name "state" -type "str" -default "present" -validateset "present","absent","started","stopped","restarted" -resultobj $result
Is the -resultobj required?

2017-02-20 21:11 UTC, jborean93 commented on lib/ansible/modules/windows/win_nssm.ps1
> +$startMode = Get-AnsibleParam -obj $params -name "start_mode" -type "str" -default "auto" -validateset "auto","manual","disabled" -resultobj $result
-resultobj again?

2017-02-20 21:13 UTC, jborean93 requested changes

2017-02-20 21:13 UTC, jborean93 commented on lib/ansible/modules/windows/win_nssm.ps1
> +$state = Get-AnsibleParam -obj $params -name "state" -type "str" -default "present" -validateset "present","absent","started","stopped","restarted" -resultobj $result
Is the -resultobj required?

2017-02-20 21:13 UTC, jborean93 commented on lib/ansible/modules/windows/win_nssm.ps1
> +$startMode = Get-AnsibleParam -obj $params -name "start_mode" -type "str" -default "auto" -validateset "auto","manual","disabled" -resultobj $result
-resultobj again?

2017-02-20 21:13 UTC, jborean93 commented on lib/ansible/modules/windows/win_nssm.ps1
> +
Random newline?

2017-02-20 22:07 UTC, dagwieers commented on lib/ansible/modules/windows/win_nssm.ps1
> +
Nope, just a cleanup of trailing whitespaces. My editor makes them quite obvious, so I remove them.

2017-02-20 22:07 UTC, dagwieers commented on lib/ansible/modules/windows/win_nssm.ps1
> +$state = Get-AnsibleParam -obj $params -name "state" -type "str" -default "present" -validateset "present","absent","started","stopped","restarted" -resultobj $result
Yup, prefer to not touch those until we have decided what to do with them.

2017-02-20 22:07 UTC, dagwieers commented on lib/ansible/modules/windows/win_nssm.ps1
> +$startMode = Get-AnsibleParam -obj $params -name "start_mode" -type "str" -default "auto" -validateset "auto","manual","disabled" -resultobj $result
Yup, prefer to not touch those until we have decided what to do with them.

2017-02-20 22:08 UTC, dagwieers commented
!needs_revision

2017-02-20 22:44 UTC, jborean93 approved these changes

2017-02-20 22:45 UTC, jborean93 commented
shipit

2017-02-24 07:13 UTC, nitzmahone approved these changes

2017-02-24 07:14 UTC, merged