Contributing new lib/ansible/modules/network/cloudengine/ce_config.py module to manage HUAWEI data center CloudEngine switch
ansible/ansible pull request #21667
Opened 2017-02-20 11:51 UTC by QijunPan

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

ce_config
##### ANSIBLE VERSION

```
ansible 2.3.0
config file = /etc/ansible/ansible.cfg
configured module search path = ['/home/ansible-2.1.1.0/lib/ansible/modules/core/network/cloudengine', '/home/ansible-2.1.1.0/lib/ansible/module_utils', '/home/ansible-2.1.1.0/lib/ansible/modules', '/home/ansible-2.1.1.0', '/home/ansible-2.1.1.0/lib/ansible/utils/']
```

##### SUMMARY

```
TASK [configure top level configuration and save it] ***************************
task path: /usr1/code/OpenNESS/code/current/KVM/intg/test/testcases/test-ce_config.yml:18
Using module file /usr/local/lib/python2.7/site-packages/ansible-2.3.0-py2.7.egg/ansible/modules/core/network/cloudengine/ce_config.py
<ce_6850> ESTABLISH LOCAL CONNECTION FOR USER: root
<ce_6850> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1487042776.85-243958543444735 `" && echo ansible-tmp-1487042776.85-243958543444735="` echo $HOME/.ansible/tmp/ansible-tmp-1487042776.85-243958543444735 `" ) && sleep 0'
<ce_6850> PUT /tmp/tmpcpw7_S TO /root/.ansible/tmp/ansible-tmp-1487042776.85-243958543444735/ce_config.py
<ce_6850> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1487042776.85-243958543444735/ /root/.ansible/tmp/ansible-tmp-1487042776.85-243958543444735/ce_config.py && sleep 0'
<ce_6850> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1487042776.85-243958543444735/ce_config.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1487042776.85-243958543444735/" > /dev/null 2>&1 && sleep 0'
changed: [ce_6850] => {
    "changed": true, 
    "invocation": {
        "module_args": {
            "after": null, 
            "auth_pass": null, 
            "authorize": false, 
            "backup": false, 
            "before": null, 
            "config": null, 
            "defaults": false, 
            "host": "ce_6850", 
            "lines": [
                "sysname boardleaf1"
            ], 
            "match": "line", 
            "parents": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 12345, 
            "provider": null, 
            "replace": "line", 
            "save": false, 
            "src": null, 
            "ssh_keyfile": null, 
            "timeout": 10, 
            "transport": null, 
            "use_ssl": false, 
            "username": "rootDC", 
            "validate_certs": true
        }
    }, 
    "updates": [
        "sysname boardleaf1"
    ], 
    "warnings": []
}
```

2017-05-12 15:45 UTC, calfonso commented
@QijunPan are you planning on making the pep8 fixes so we can get this PR merged?

2017-05-13 08:17 UTC, QijunPan commented
@calfonso Yes, we are dealing with these problems and will finish it as soon as possible, thanks.

2017-05-19 15:21 UTC, gundalow requested changes

2017-05-19 15:21 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_config.py
> +        force=dict(default=False, type='bool'),
Please remove this + from docs. No point releasing something that we will deprecate soon.

2017-05-19 15:21 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_config.py
> +  force:
Delete `force:`

2017-05-19 15:21 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_config.py
> +    choices: ['yes', 'no']
Please use `type: bool` instead of `choices`

2017-05-19 15:21 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_config.py
> +    required: false
Please add `type: bool`.

2017-05-19 15:21 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_config.py
> +    required: false
Please use add `type: bool`

2017-05-23 12:57 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_config.py
> +    required: false
OK I fixed it.

2017-05-23 12:57 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_config.py
> +    required: false
OK,thanks

2017-05-23 12:57 UTC, QijunPan commented
@gundalow  can this PR merged?

2017-05-23 13:30 UTC, QijunPan commented
@gundalow  I've dealt with these PRs, and I expect them can be merged, thank you.
[https://github.com/ansible/ansible/pull/22344](url)
[https://github.com/ansible/ansible/pull/22054](url)
[https://github.com/ansible/ansible/pull/22053](url)
[https://github.com/ansible/ansible/pull/22052](url)
[https://github.com/ansible/ansible/pull/22051](url)
[https://github.com/ansible/ansible/pull/22050](url)
[https://github.com/ansible/ansible/pull/22048](url)
[https://github.com/ansible/ansible/pull/22047](url)
[https://github.com/ansible/ansible/pull/22046](url)
[https://github.com/ansible/ansible/pull/22045](url)
[https://github.com/ansible/ansible/pull/22038](url)
[https://github.com/ansible/ansible/pull/22036](url)
[https://github.com/ansible/ansible/pull/22033](url)
[https://github.com/ansible/ansible/pull/22032](url)
[https://github.com/ansible/ansible/pull/22031](url)
[https://github.com/ansible/ansible/pull/22030](url)
[https://github.com/ansible/ansible/pull/21881](url)
[https://github.com/ansible/ansible/pull/21879](url)
[https://github.com/ansible/ansible/pull/21877](url)
[https://github.com/ansible/ansible/pull/21818](url)
[https://github.com/ansible/ansible/pull/21667](url)
[https://github.com/ansible/ansible/pull/21645](url)

2017-05-23 20:14 UTC, gundalow commented
Hi, 
Thanks for the updates, I'll get these merged by the end of next week.

2017-05-25 13:01 UTC, gundalow approved these changes

2017-05-25 13:01 UTC, merged