Improve error output with undefined values in dicts
ansible/ansible pull request #21672
Opened 2017-02-20 13:41 UTC by dagwieers

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

debug

##### ANSIBLE VERSION

v2.3

##### SUMMARY

With an older change https://github.com/ansible/ansible/commit/d73562902b289e7fd7e2e5a37e82b00c83a16369 undefined values inside a dictionary make the whole dictionary undefined, and as a result one cannot easily determine what caused the dict to be undefined.

Using this playbook:
```yaml
---
- name: test
  hosts: localhost
  gather_facts: no                                                                                                                         
  vars:
    some:
      complex:
        struct:
          problem: '{{ unknown_var }}'
  tasks:
  - debug: var=some
```

Before:

```
fatal: [localhost]: FAILED! => {"failed": true, "msg": "'some' is undefined"}
```

After:
```
fatal: [localhost]: FAILED! => {"failed": true, "msg": "'unknown_var' is undefined"}
```

This fixes #15722

2017-02-20 14:00 UTC, nerzhul commented
please shipit

2017-02-20 14:03 UTC, dagwieers commented
@nerzhul We first have to agree if this behaviour is correct, because CI is now failing expecting the old beahviour.

```
2017-02-20 13:47:54 TASK [test_var_blending : check debug variable output when variable is undefined] ***
2017-02-20 13:47:54 task path: /root/ansible/test/integration/targets/var_blending/roles/test_var_blending/tasks/main.yml:41
2017-02-20 13:47:54 fatal: [testhost]: FAILED! => {
2017-02-20 13:47:54     "failed": true, 
2017-02-20 13:47:54     "msg": "'undefined_variable' is undefined"
2017-02-20 13:47:54 }
```

2017-02-20 14:05 UTC, nerzhul commented
@dagwieers the unit test should be fixed i think

2017-02-20 14:58 UTC, pilou- commented
Bonus: this PR allows to avoid an exception when `ansible host -m debug -a var=ansible_facts` is used :)

In order to keep a consistent behavior, `debug` module should fail when multiple variables are used (or multiple variables shouldn't be allowed). The current behavior is:
<pre>
ansible -i hosts localhost -m debug -a var=ansible_host,test2,test3
localhost | SUCCESS => {
    "ansible_host,test2,test3": "('127.0.0.1', Undefined, Undefined)", 
    "changed": false
}
</pre>

2017-02-20 17:23 UTC, pilou- commented
Some notes:

1. I really don't understand the following this [line](https://github.com/dagwieers/ansible/blob/84d886e24a6834cd00e9dfb216fcd01c0fcf21da/lib/ansible/plugins/action/debug.py#L60):
<pre>
results = self._templar.template("{{" + results + "}}", convert_bare=True, fail_on_undefined=True)
</pre>
why the brackets **and** `convert_bare=True` ? The [documentation](https://github.com/dagwieers/ansible/blob/84d886e24a6834cd00e9dfb216fcd01c0fcf21da/lib/ansible/template/__init__.py#L336) states that `If convert_bare is set to True, the given data will be wrapped as a jinja2 variable ('{{foo}}')`.
2. it seems the lookup tests ([here](https://github.com/dagwieers/ansible/blob/84d886e24a6834cd00e9dfb216fcd01c0fcf21da/test/integration/targets/lookups/tasks/main.yml#L265) and [here](https://github.com/dagwieers/ansible/blob/84d886e24a6834cd00e9dfb216fcd01c0fcf21da/test/integration/targets/lookup_properties/test_lookup_properties.yml#L12)) should use `var=item` or `msg={{item}}` but not `var={{item}}` ?
3. `var={{item}}` should raise an error when the value of item isn't the name of variable

2017-02-21 21:49 UTC, mattclay commented
CI failure in integration tests due to:

```
2017-02-21 02:05:30 TASK [test_var_blending : assert] **********************************************
2017-02-21 02:05:30 task path: /root/ansible/test/integration/targets/var_blending/roles/test_var_blending/tasks/main.yml:45
2017-02-21 02:05:30 fatal: [testhost]: FAILED! => {
2017-02-21 02:05:30     "assertion": "var_undefined.undefined_variable == 'VARIABLE IS NOT DEFINED!'", 
2017-02-21 02:05:30     "changed": false, 
2017-02-21 02:05:30     "evaluated_to": false, 
2017-02-21 02:05:30     "failed": true
2017-02-21 02:05:30 }
```

2017-02-22 00:13 UTC, pilou- commented
@dagwieers could you append 393c7ea3d1f6766d868fa8613b89a65bacd8f616 here ?

2017-02-24 01:36 UTC, dagwieers commented
@pilou- Thanks !

2017-02-24 01:37 UTC, dagwieers commented
CI seems to be stuck again. Closing and re-opening for fun and profit !

2017-02-24 15:34 UTC, pilou- commented
@dagwieers `convert_bare=True` parameter of method `Templar.template` does nothing when the variable isn't defined.
I propose to detect bare variable instead of calling `Templar.template` twice.

Could you append ?
- 0d5c0977c6bd74726e940dd00a70b8a7b6645c62 _debug: handle undefined bare variables_
- f9e415e5b132cf6d606871a6e9981d7bba6fd50b _debug: test undefined variable (using full jinja2 syntax)_
- 38f6f7ffb3080d9328b791bde0197397ba8c44d8 _doc: debug task may fail_
- 99045ff2084108c0b880f971cd43c7e5e186bbcf: _doc: use full variable syntax instead of bare variables_
By the way, I fail to see the usefulness of the `var` parameter of the `debug` module. It seems msg could be always used instead.

2017-03-17 19:21 UTC, bcoca requested changes

2017-03-17 19:21 UTC, bcoca commented on test/integration/targets/lookup_properties/test_lookup_properties.yml
> +    - debug: var=item
this is relying on double interpolation to test dispay of test2, test_dot, not of item

2017-03-17 20:45 UTC, nerzhul commented
thanks for your review @bcoca this change is really needed

2017-06-19 21:27 UTC, closed without merging