AWS Elasticache module check mode, replication group, and security group names
ansible/ansible pull request #21922
Opened 2017-02-24 21:27 UTC by calvinli723

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME

AWS elasticache module

##### ANSIBLE VERSION

```
ansible 1.9.1
  configured module search path = None
```

##### SUMMARY

The module previously had not supported check mode, so this pull request was partly made to address that by only making API calls when check mode is not activated. Also, there was no support for managing replication groups for elasticache clusters, so this pull request also attempts to address that. Also, it may be useful to pass in security group names instead of ids, since you might not want to hardcode security group ids in your configuration management, so the module can query for the ids using these names.

2017-02-24 21:27 UTC, calvinli723 commented
Migrated from https://github.com/ansible/ansible-modules-core/pull/5613

2017-09-18 04:22 UTC, willthames requested changes

2017-09-18 04:22 UTC, willthames commented on lib/ansible/modules/cloud/amazon/elasticache.py
> +    if security_group_names:
Use `get_ec2_security_group_ids_from_names`

2017-09-18 04:22 UTC, willthames commented on lib/ansible/modules/cloud/amazon/elasticache.py
> +        conn = boto.connect_ec2()
Don't use `boto.connect_ec2` directly - use `connect_to_aws` - otherwise things like profiles, security tokens etc. don't get properly passed.

2017-09-18 04:22 UTC, willthames commented on lib/ansible/modules/cloud/amazon/elasticache.py
> +                                                      num_cache_nodes=self.num_nodes,
This wasn't aligned correctly before but we may as well fix it up now we're changing it.

2018-01-30 14:13 UTC, s-hertel requested changes

2018-01-30 14:13 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/elasticache.py
> +        replication_group=dict(),
It doesn't look like this option is used in any boto call.

2018-01-30 14:13 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/elasticache.py
>          self.engine = engine.lower()
This fails now if replication_group is specified because engine and node_type are set to None in main and you can't .lower() None.

2020-04-29 23:47 UTC, closed without merging