Added new Avi module to setup User Roles.
ansible/ansible pull request #21935
Opened 2017-02-25 00:42 UTC by grastogi23

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

network.avi.avi_role

##### ANSIBLE VERSION

```
ansible 2.3.0
  config file = /home/grastogi/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY

New module to setup user roles.

```

```

2017-02-25 01:12 UTC, khaltore commented
shipit

2017-02-25 01:33 UTC, ericsysmin commented
shipit

2017-02-26 20:01 UTC, gundalow requested changes

2017-02-26 20:01 UTC, gundalow commented on lib/ansible/modules/network/avi/avi_role.py
> +- name: Example Adds/Deletes Role configuration from Avi Controller
This appears to add, rather than delete

2017-02-28 15:27 UTC, ericsysmin commented
shipit

2017-03-01 13:12 UTC, gundalow approved these changes

2017-03-01 13:12 UTC, merged