Added new Avi module to setup SSL profile.
ansible/ansible pull request #21934
Opened 2017-02-25 00:40 UTC by grastogi23

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

network.avi.avi_sslprofile

##### ANSIBLE VERSION

```
ansible 2.3.0
  config file = /home/grastogi/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY

New module for setting to setup SSL Profile.

```

```

2017-02-25 00:47 UTC, khaltore commented
shipit

2017-02-25 01:33 UTC, ericsysmin commented
shipit

2017-02-26 19:58 UTC, gundalow requested changes

2017-02-26 19:58 UTC, gundalow commented on lib/ansible/modules/network/avi/avi_sslprofile.py
> +            - Ciphers suites represented as defined by http //www.openssl.org/docs/apps/ciphers.html.
`U(http://www.openssl.org/docs/apps/ciphers.html)`

2017-02-28 15:27 UTC, ericsysmin commented
shipit

2017-03-01 13:12 UTC, gundalow approved these changes

2017-03-01 13:12 UTC, merged