Added new Avi module to setup PKI profile.
ansible/ansible pull request #21936
Opened 2017-02-25 00:43 UTC by grastogi23

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

network.avi.pkiprofile

##### ANSIBLE VERSION

```
ansible 2.3.0
  config file = /home/grastogi/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY

New module to setup PKI profile.

```

```

2017-02-25 01:06 UTC, khaltore commented
shipit

2017-02-25 01:33 UTC, ericsysmin commented
shipit

2017-02-26 20:03 UTC, gundalow requested changes

2017-02-26 20:03 UTC, gundalow commented on lib/ansible/modules/network/avi/avi_pkiprofile.py
> +- name: Example Adds/Deletes PKIProfile configuration from Avi Controller
Example appears to add, rather than delete.

2017-02-28 15:27 UTC, ericsysmin commented
shipit

2017-03-01 13:13 UTC, gundalow approved these changes

2017-03-01 13:13 UTC, merged