Added new Avi module to setup Certificate Management Profile.
ansible/ansible pull request #21938
Opened 2017-02-25 00:45 UTC by grastogi23

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

network.avi.avi_certificatemanagementprofile

##### ANSIBLE VERSION

```
ansible 2.3.0
  config file = /home/grastogi/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY

New module to setup Avi CertificateManagementProfile.

```

```

2017-02-25 01:14 UTC, khaltore commented
shipit

2017-02-25 01:33 UTC, ericsysmin commented
shipit

2017-02-26 20:04 UTC, gundalow requested changes

2017-02-26 20:04 UTC, gundalow commented on lib/ansible/modules/network/avi/avi_certificatemanagementprofile.py
> +- name: Example Adds/Deletes CertificateManagementProfile configuration from Avi Controller
Example appears to add, rather than delete.

2017-03-01 13:14 UTC, gundalow approved these changes

2017-03-01 13:14 UTC, merged