Proposed new notification module: BearyChat
ansible/ansible pull request #21947
Opened 2017-02-25 09:33 UTC by tonyseek

BearyChat (https://bearychat.com) is a Slack alternative service.

CC @loddit @bearyinnovative

2017-02-25 09:33 UTC, tonyseek commented
Migrated from https://github.com/ansible/ansible-modules-extras/pull/1448

2017-02-26 03:25 UTC, shonenada commented
shipit

2017-02-26 04:08 UTC, bcho commented
shipit

2017-02-26 19:49 UTC, bjolivot requested changes
missclic

2017-02-26 20:08 UTC, bjolivot requested changes
Hello
Thank you for your module could you make some changes ?
Thank you

2017-02-26 20:08 UTC, bjolivot commented on lib/ansible/modules/notification/bearychat.py
> +    default: None
required: false and default: None are implicit, you can remove both

2017-02-26 20:08 UTC, bjolivot commented on lib/ansible/modules/notification/bearychat.py
> +    response, info = fetch_url(module, url, data=payload)
Why do you wait to fail ? I think you must fail in "main"

2017-02-26 20:08 UTC, bjolivot commented on lib/ansible/modules/notification/bearychat.py
> +    })
Required=false are implicit could you remove them ?
Default=None too in case of string

2017-03-06 10:03 UTC, tonyseek commented
@bjolivot Thanks for your review. The changes have been revised.

2017-03-22 14:07 UTC, bjolivot commented
shipit

2017-04-12 11:00 UTC, tonyseek commented
ready_for_review

2017-04-13 04:43 UTC, yuanbohan commented
shipit

2017-04-13 08:11 UTC, tonyseek commented
bot_status

2017-04-13 10:44 UTC, tonyseek commented
Why waiting on me... I have revised the description of pull request.

2017-04-13 11:35 UTC, bcho commented
bot_broken

2017-04-13 12:35 UTC, gundalow commented
`changes_requested_by: bjolivot` I believe @bjolivot needs to accept their GitHub review

2017-04-13 12:37 UTC, bjolivot approved these changes

2017-04-13 12:39 UTC, bjolivot commented
bot_status

2017-04-13 13:25 UTC, bcho commented
shipit

2017-04-13 13:25 UTC, bcho commented
bot_status

2017-04-13 13:28 UTC, bcho commented
OK, waiting another maintainer to shipit :shipit:

2017-05-06 16:30 UTC, willybarro commented
shipit :shipit:

2017-06-09 04:42 UTC, tonyseek commented
ready_for_review

2017-07-24 04:02 UTC, tonyseek commented
bot_status

2017-08-01 10:53 UTC, gundalow commented
closing/reopenign to trigger CI then I think we can get this merged

2017-08-01 11:21 UTC, tonyseek commented
ready_for_review

2017-08-01 11:47 UTC, gundalow approved these changes

2017-08-01 11:47 UTC, merged

2017-08-01 11:48 UTC, gundalow commented
Merged into `devel` so this will be released in Ansible 2.4.0
Thanks for the PR and the reviews :)