ec2_group: cidr_ip validation (#21871).
ansible/ansible pull request #21956
Opened 2017-02-26 01:23 UTC by anryko

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

ec2_group

##### ANSIBLE VERSION

```
ansible 2.3.0 (ec2_group_ip_fix f6805870e9) last updated 2017/02/26 01:55:45 (GMT +200)
```

##### SUMMARY

Fixes #21871.
Added validation of ec2 group cidr_ip before submitting it to boto. Change results in:
 - Cleaner error message on invalid IP.
 - Automatically adjusts CIDR IP in case when interface IP was provided (e.g. 10.0.0.28/29 will be adjusted to 10.0.0.24/29). Before the change boto was doing the same thing internally and rule was set, but would fail on second run.
 - /32 is automatically appended to IP if netmask is not set.

##### DETAILS
Rule:
```
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 10.0.0.28/29
```

Before the change:
First run:
```
changed: [localhost] => {                                                                                             [60/216]
    "changed": true,
    "group_id": "sg-xxxxxxxx",
    "invocation": {
        "module_args": {
            "aws_access_key": null,
            "aws_secret_key": null,
            "description": "edge-test",
            "ec2_url": null,
            "name": "edge-test",
            "profile": null,
            "purge_rules": true,
            "purge_rules_egress": true,
            "region": "eu-central-1",
            "rules": [
                {
                    "cidr_ip": "10.0.0.28/29",
                    "from_port": 22,
                    "proto": "tcp",
                    "to_port": 22
                }
            ],
            "rules_egress": null,
            "security_token": null,
            "state": "present",
            "validate_certs": true,
            "vpc_id": "vpc-xxxxxxxx"
        },
        "module_name": "ec2_group"
    }
}
```
Secind run:
```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_ayE3Gh/ansible_module_ec2_group.py", line 483, in <module>
    main()
  File "/tmp/ansible_ayE3Gh/ansible_module_ec2_group.py", line 377, in main
    group.authorize(rule['proto'], rule['from_port'], rule['to_port'], thisip, grantGroup)
  File "/usr/local/lib/python2.7/dist-packages/boto/ec2/securitygroup.py", line 203, in authorize
    dry_run=dry_run)
  File "/usr/local/lib/python2.7/dist-packages/boto/ec2/connection.py", line 3207, in authorize_security_group
    params, verb='POST')
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1227, in get_status
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidPermission.Duplicate</Code><Message>the specified rule "peer: 10.0.0.24/29, TCP, from p$
rt: 22, to port: 22, ALLOW" already exists</Message></Error></Errors><RequestID>8ad2ecaa-a82c-4618-910f-277b0f15c009</Request$
D></Response>

fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_name": "ec2_group"
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_ayE3Gh/ansible_module_ec2_group.py\", line 48$
, in <module>\n    main()\n  File \"/tmp/ansible_ayE3Gh/ansible_module_ec2_group.py\", line 377, in main\n    group.authorize$
rule['proto'], rule['from_port'], rule['to_port'], thisip, grantGroup)\n  File \"/usr/local/lib/python2.7/dist-packages/boto/$
c2/securitygroup.py\", line 203, in authorize\n    dry_run=dry_run)\n  File \"/usr/local/lib/python2.7/dist-packages/boto/ec2$
connection.py\", line 3207, in authorize_security_group\n    params, verb='POST')\n  File \"/usr/local/lib/python2.7/dist-pack
ages/boto/connection.py\", line 1227, in get_status\n    raise self.ResponseError(response.status, response.reason, body)\nbot
o.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Response><Errors
><Error><Code>InvalidPermission.Duplicate</Code><Message>the specified rule \"peer: 10.0.0.24/29, TCP, from port: 22, to port:
 22, ALLOW\" already exists</Message></Error></Errors><RequestID>8ad2ecaa-a82c-4618-910f-277b0f15c009</RequestID></Response>\n
",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}
```

After the change:
First run:
```
changed: [localhost] => {                                                                                             [4/9395]
    "changed": true,
    "group_id": "sg-xxxxxxxx",
    "invocation": {
        "module_args": {
            "aws_access_key": null,
            "aws_secret_key": null,
            "description": "edge-test",
            "ec2_url": null,
            "name": "edge-test",
            "profile": null,
            "purge_rules": true,
            "purge_rules_egress": true,
            "region": "eu-central-1",
            "rules": [
                {
                    "cidr_ip": "10.0.0.24/29",
                    "from_port": 22,
                    "proto": "tcp",
                    "to_port": 22
                }
            ],
            "rules_egress": null,
            "security_token": null,
            "state": "present",
            "validate_certs": true,
            "vpc_id": "vpc-xxxxxxxx"
        },
        "module_name": "ec2_group"
    }
}
```
Second run:
```
ok: [localhost] => {                                                                                                  [4/9446]
    "changed": false,
    "group_id": "sg-xxxxxxxx",
    "invocation": {
        "module_args": {
            "aws_access_key": null,
            "aws_secret_key": null,
            "description": "edge-test",
            "ec2_url": null,
            "name": "edge-test",
            "profile": null,
            "purge_rules": true,
            "purge_rules_egress": true,
            "region": "eu-central-1",
            "rules": [
                {
                    "cidr_ip": "10.0.0.24/29",
                    "from_port": 22,
                    "proto": "tcp",
                    "to_port": 22
                }
            ],
            "rules_egress": null,
            "security_token": null,
            "state": "present",
            "validate_certs": true,
            "vpc_id": "vpc-xxxxxxxx"
        },
        "module_name": "ec2_group"
    }
}
```
Notice that before the change "incorrect" IP is in the output and we can see the IP that was actually set in error message on the second run.

2017-02-26 23:19 UTC, willthames commented
I wonder if a `cidr` parameter type would be a better approach that could be more widely applied, similar to how the `path` type expands `~` in filenames (see https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/basic.py#L1659 for how that happens).

2017-02-27 19:54 UTC, anryko commented
@willthames that's a good idea for a new feature. However, it is not applicable to this particular case. As far as I encountered in ansible sources, validation is done only on top level, like:
```python
argument_spec.update(dict(
   rules=dict(type='list')
))
```
In this case we would need "deep" validation of list of dicts of rules, which can contain cidr_ip (or not). This might be another nice feature to have, but I think it is out of scope of this small fix.

2017-02-27 20:00 UTC, sivel commented
Some of that discussion is ongoing, such as in:

https://github.com/ansible/ansible/pull/17731
https://github.com/ansible/ansible/pull/21171

However the implementation in #17731 isn't what we want.

For now, I'd probably just leave it implemented the way it is here, and look for this in the future.

My biggest concern is that this is an additional dependency that could break backwards compatibility.

You should like wrap the import and define a `HAS_IPADDRESS` and if `HAS_IPADDRESS` is false, don't validate it, but instead maybe add a warning to the return, saying it couldn't be validated due to missing the `ipaddress` python module.

Also, I might recommend updating to utilize `netaddr` since that is already the library that the `ipaddr` filters are based off of, and what is more likely to be available.

2017-02-27 21:42 UTC, anryko commented
@sivel thanks for your review and links. Will come back with recommended changes.

2017-03-03 18:41 UTC, ryansb requested changes

2017-03-03 18:41 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/ec2_group.py
> +import ipaddress
I believe this module is only available in 2.7 and 3.3+, for modules using boto we support back to 2.6. How is boto doing this validation on Python 2.6? Can you copy them?

2017-03-05 12:07 UTC, anryko commented on lib/ansible/modules/cloud/amazon/ec2_group.py
> +import ipaddress
@ryansb checked it out and boto doesn't do cidr_ip validation. So this validation is done on AWS backend.

2017-03-05 12:09 UTC, anryko commented
@sivel will use any of those libs if available and display warning while skipping validation if not. What do you think?

2018-01-29 16:10 UTC, s-hertel commented
Thanks for working on this @anryko. Rather than depend on external libraries, this was added in d877c146ab750c0f1505b4180e4170163d854fb5 using module_utils/network/common/utils.py.

2018-01-29 16:10 UTC, closed without merging