iptables module: match=conntrack with ctstate not working
ansible/ansible pull request #21976
Opened 2017-02-26 22:54 UTC by snowsky

##### ISSUE TYPE

 - Feature Pull Request
 - New Module Pull Request
 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME

##### ANSIBLE VERSION

```

```

##### SUMMARY

```

```

2017-02-27 15:21 UTC, bcoca requested changes

2017-02-27 15:21 UTC, bcoca commented on lib/ansible/modules/system/iptables.py
> +    if params['ctstate']:
sadly we are overloading the param here, in many cases it should be used as `--state`

2017-02-27 18:54 UTC, bcoca commented on lib/ansible/modules/system/iptables.py
> +    if params['ctstate']:
i'm thinking that it should be state/--state unless conntrack is explicitly loaded

2017-02-27 19:31 UTC, snowsky commented on lib/ansible/modules/system/iptables.py
> +    if params['ctstate']:
The -m state should be using --state xxxx,xxxx parameter, but not sure if it can work with --ctstate. I'll verify tonight to see if it is the case.

2017-02-27 20:53 UTC, snowsky commented on lib/ansible/modules/system/iptables.py
> +    if params['ctstate']:
see here, http://unix.stackexchange.com/questions/108169/what-is-the-difference-between-m-conntrack-ctstate-and-m-state-state. The --state parameter is being replaced by conntrack.

2017-02-27 21:33 UTC, bcoca commented on lib/ansible/modules/system/iptables.py
> +    if params['ctstate']:
I understand the difference, mostly my concern is that existing plays are relying on it translating into `-m state --state` even though its kind of incorrectly named and `--ctstate` makes more sense, but I would make it conditional to the loading of conntrack itself (which needs to be loaded in both but explicitly for the command line matching --ctstate)

2017-02-27 21:53 UTC, snowsky commented on lib/ansible/modules/system/iptables.py
> +    if params['ctstate']:
sure, that would be an easy fix. Will put it up soon.

2017-02-27 22:40 UTC, snowsky commented on lib/ansible/modules/system/iptables.py
> +    if params['ctstate']:
I just remember that it is not possible to use --state here, for "state" is reserved:
"msg": "value of state must be one of: present,absent, got: ESTABLISHED,RELATED"

2017-02-27 22:52 UTC, snowsky commented on lib/ansible/modules/system/iptables.py
> +    if params['ctstate']:
I am using this yaml file:
>- hosts: localhost
  tasks:
     - iptables:
         chain: INPUT
         match: state
         state: ESTABLISHED,RELATED
         jump: ACCEPT

2017-03-01 00:53 UTC, snowsky commented
@bcoca please review the new change.

2017-03-08 16:01 UTC, bcoca approved these changes

2017-03-08 16:01 UTC, merged