Vault cleanups
ansible/ansible pull request #21978
Opened 2017-02-27 04:22 UTC by nbraud

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
parsing/vault

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY
Not really a bugfix, simply some cleanups for things I noticed while reading vault's code.

This should not cause any behaviour change.

2017-02-27 04:59 UTC, nbraud commented
The 2 failed CI runs are Fedora-related isssues, and seem completely unrelated to my patches.

2017-02-27 10:34 UTC, resmo commented
@nbraud I kicked the build again. passed

2017-03-08 20:08 UTC, alikins requested changes

2017-03-08 20:08 UTC, alikins commented on lib/ansible/parsing/vault/__init__.py
> -        vaulttext = file_obj.read(count)
The count here is important.

Without it any file loaded by dataloader will be loaded entirely and entire contents ran through a to_bytes(to_text())

2017-03-08 20:10 UTC, alikins commented on lib/ansible/parsing/vault/__init__.py
> -        vaulttext = file_obj.read(count)
Actually, that is plumbed through already.

Should be okay.

2017-03-08 20:10 UTC, alikins approved these changes

2017-03-08 20:14 UTC, merged

2017-03-08 20:17 UTC, alikins commented on lib/ansible/parsing/vault/__init__.py
> -        vaulttext = file_obj.read(count)
I don't remember why the options to the inner to_text()  here different or if it is significant.

``` python
vaulttext, encoding='ascii', errors='strict'```

vs

``` python
data, encoding='ascii', errors='strict', nonstring='strict'
```