Add win_msg module
ansible/ansible pull request #22008
Opened 2017-02-27 17:37 UTC by jhawkesworth

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

win_msg

##### ANSIBLE VERSION

```
ansible 2.3.0 (win_msg_new ad7cb10fc6) last updated 2017/02/27 17:15:23 (GMT +100)
  config file =
  configured module search path = Default w/o overrides
```

##### SUMMARY

In keeping with the current zeitgeist of reviving all things nineties https://www.theregister.co.uk/2017/02/14/hmd_nokia_nostalgia/, this module adds the ability to irritate windows users just like you used to using pop up messages.

No tests at this time, but easy enough to test using ad-hoc ansible.

Due to the curious and ancient nature of the msg.exe messages are sent in turn to logged on users, which can result in long run times if you set the 'wait' parameter to 'true'.  For this reason I have added module runtime info to the module return output.

This change fixes nothing.

```

```

2017-02-27 17:39 UTC, jhawkesworth commented
@dagwieers - please review if you have a moment.
@jborean93 - I tweaked this a little from the old version in modules-extra which you reviewed.  Would you mind having another go with this version?

2017-02-27 17:50 UTC, dagwieers requested changes

2017-02-27 17:50 UTC, dagwieers commented on lib/ansible/modules/windows/win_msg.ps1
> +$params = Parse-Args $args
Enable check-mode support !

2017-02-27 17:50 UTC, dagwieers commented on lib/ansible/modules/windows/win_msg.ps1
> +$result = New-Object PSObject
Use a normal hashtable.

2017-02-27 17:50 UTC, dagwieers commented on lib/ansible/modules/windows/win_msg.ps1
> +$msg = Get-Attr -obj $params -name msg -failifempty $True -resultobj $result
Use Get-AnsibleParam for all of these :-)

2017-02-27 17:50 UTC, dagwieers commented on lib/ansible/modules/windows/win_msg.ps1
> +}
I would set a standard message by default. (Just like debug and fail also do)

2017-02-27 17:50 UTC, dagwieers commented on lib/ansible/modules/windows/win_msg.py
> +    required: false
Don't add `required: false`. It is implicit.

2017-02-27 17:50 UTC, dagwieers commented on lib/ansible/modules/windows/win_msg.py
> +    required: false
Don't add `required: false`. It is implicit.

2017-02-27 17:50 UTC, dagwieers commented on lib/ansible/modules/windows/win_msg.py
> +    default: all logged in users on the windows target.
This doesn't seem right. Default states the default value, not some documentation string.

2017-02-27 17:50 UTC, dagwieers commented on lib/ansible/modules/windows/win_msg.py
> +    required: false
Don't add `required: false`. It is implicit.

2017-02-27 17:50 UTC, dagwieers commented on lib/ansible/modules/windows/win_msg.py
> +    default: no default
Remove this line. If it is required, there is no default (not  "no default").
But I would add a default message.

2017-02-27 22:11 UTC, jhawkesworth commented
Thanks for the review @dagwieers - I think I have fixed all the issues you mention now.

ready_for_review

2017-02-27 22:18 UTC, jhawkesworth commented
Ok jumped the gun a bit there, latest push should keep pep8 checks happy.

ready_for_review

2017-02-27 22:22 UTC, jhawkesworth commented
.. only kidding.  3rd time lucky

ready_for_review

2017-02-27 22:35 UTC, jhawkesworth commented
.. and this time I remembered to update the changelog

ready_for_review

2017-02-28 11:41 UTC, dagwieers commented
shipit

2017-02-28 15:32 UTC, jhawkesworth commented
bot_status

2017-02-28 20:14 UTC, jhawkesworth commented
Hmm, just one ship it short ...

2017-02-28 22:02 UTC, jborean93 commented
Sorry @jhawkesworth I will try and get to this later today for me but a lot of my spare time has been taken up by another project I am working on right now.

2017-03-01 08:18 UTC, jborean93 requested changes
Just some style changes to keep conformity. Only have one question around the -resultobj when getting ansible parameters, what does this do exactly?

2017-03-01 08:18 UTC, jborean93 commented on lib/ansible/modules/windows/win_msg.ps1
> +{
Are we able to keep the braces the same as the rest of the windows modules?

2017-03-01 08:18 UTC, jborean93 commented on lib/ansible/modules/windows/win_msg.ps1
> +If (-not $result.rc -eq 0 )
If braces again like normal.

2017-03-01 11:23 UTC, dagwieers commented on lib/ansible/modules/windows/win_msg.ps1
> +{
@jborean93 There's no consensus, and there's no standard way of doing things in Powershell (cfr. PEP8 in Python). For that reason I removed all the formatting changes in my refactoring of most Windows modules on request of @nitzmahone 

I'd prefer a standard way of writing modules in absence of a higher authoritative source for clarity and conformance. But then again, I have no prior experience with Powershell and will have it easier to adapt to the "new normal" than others. (I do have preferences that are closer to the way C and Python does things :-))

2017-03-01 13:55 UTC, jhawkesworth commented
Ok @jborean93 - I fixed up the brackets so that they are at least in the same style within this file.

IIRC you used to have to set the -resultobj $results if you used -failifempty true although I'm not sure that is still true any more.

Hope there's enough time to get this in to 2.3.

ready_for_review

2017-03-01 13:55 UTC, jhawkesworth commented
bot_status

2017-03-01 13:56 UTC, dagwieers commented
shipit

2017-03-01 13:58 UTC, dagwieers commented
As mentioned earlier in a discussion, it seems the `-resultobj` is only used for when `Add-AnsibleParam` is bailing out with `Fail-Json`. To be honest, in almost all cases this will be an empty $result because we have not done anything yet. So I would drop this (in python this functionality does not exist either...)

2017-03-01 14:00 UTC, jborean93 approved these changes

2017-03-01 14:01 UTC, jborean93 commented
Looks good to me.

shipit

2017-03-01 14:02 UTC, gundalow commented on lib/ansible/modules/windows/win_msg.py
> +      - How long to wait for receiver to acknowledge message.
in seconds?

2017-03-01 14:03 UTC, jhawkesworth commented
I think maybe the idea was so that you could output multiple warnings/errors if there were >1 things wrong with modules params.  Maybe @trondhindenes would recall

2017-03-01 14:04 UTC, jhawkesworth commented on lib/ansible/modules/windows/win_msg.py
> +      - How long to wait for receiver to acknowledge message.
Yes, I guess it could be clearer although calling it 'display_seconds' would help.  Do you want me to change the description?

2017-03-01 14:09 UTC, dagwieers approved these changes

2017-03-01 14:10 UTC, jborean93 commented
In case my shipit was invalidated with the commit.
shipit

2017-03-01 14:10 UTC, dagwieers commented
shipit

2017-03-01 14:10 UTC, jhawkesworth commented
Added 'in seconds' to display_seconds parameter description as suggested by @gundalow

2017-03-01 14:11 UTC, jhawkesworth commented
bot_status

2017-03-01 14:14 UTC, gundalow approved these changes

2017-03-01 14:16 UTC, merged

2017-03-01 14:16 UTC, gundalow commented
Three shipits = merge
Thanks

2017-03-01 14:17 UTC, jhawkesworth commented
Yay!  Thank you @dagwieers @jborean93 and @gundalow for keeping an eye out for changes on this one today.