Contributing lib/ansible/modules/network/cloudengine/ce_netconf.py module to manage HUAWEI data center CloudEngine
ansible/ansible pull request #22056
Opened 2017-02-28 07:43 UTC by QijunPan

add ce_netconf

##### ISSUE TYPE

 - New Module Pull Request
##### COMPONENT NAME

ce_netconf.py
##### ANSIBLE VERSION

```
ansible 2.3.0
config file = /etc/ansible/ansible.cfg
configured module search path = ['/home/ansible-2.1.1.0/lib/ansible/modules/core/network/cloudengine', '/home/ansible-2.1.1.0/lib/ansible/module_utils', '/home/ansible-2.1.1.0/lib/ansible/modules', '/home/ansible-2.1.1.0', '/home/ansible-2.1.1.0/lib/ansible/utils/']
```

##### SUMMARY

```
TASK [edit-config operation] ***************************************************
task path: /usr1/code/OpenNESS/code/current/KVM/intg/test/testcases/test-ce_netconf.yml:34
Using module file /usr/local/lib/python2.7/site-packages/ansible-2.3.0-py2.7.egg/ansible/modules/core/network/cloudengine/ce_netconf.py
<ce_6850> ESTABLISH LOCAL CONNECTION FOR USER: root
<ce_6850> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1487043783.51-104602864594431 `" && echo ansible-tmp-1487043783.51-104602864594431="` echo $HOME/.ansible/tmp/ansible-tmp-1487043783.51-104602864594431 `" ) && sleep 0'
<ce_6850> PUT /tmp/tmpMgRxvr TO /root/.ansible/tmp/ansible-tmp-1487043783.51-104602864594431/ce_netconf.py
<ce_6850> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1487043783.51-104602864594431/ /root/.ansible/tmp/ansible-tmp-1487043783.51-104602864594431/ce_netconf.py && sleep 0'
<ce_6850> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1487043783.51-104602864594431/ce_netconf.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1487043783.51-104602864594431/" > /dev/null 2>&1 && sleep 0'
changed: [ce_6850] => {
    "changed": true, 
    "end_state": {
        "result": "ok"
    }, 
    "invocation": {
        "module_args": {
            "auth_pass": null, 
            "authorize": false, 
            "cfg_xml": "<config><aaa xmlns=\"http://www.huawei.com/netconf/vrp\" content-version=\"1.0\" format-version=\"1.0\"><authenticationSchemes><authenticationScheme  operation=\"create\"><authenSchemeName>default_wdz</authenSchemeName><firstAuthenMode>local</firstAuthenMode><secondAuthenMode>invalid</secondAuthenMode></authenticationScheme></authenticationSchemes></aaa></config>", 
            "host": "ce_6850", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 12345, 
            "provider": null, 
            "rpc": "edit-config", 
            "ssh_keyfile": null, 
            "timeout": 10, 
            "transport": null, 
            "use_ssl": false, 
            "username": "rootDC", 
            "validate_certs": true
        }, 
        "module_name": "ce_netconf"
    }
}
```

2017-05-03 11:26 UTC, gundalow requested changes

2017-05-03 11:26 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_netconf.py
> +short_description: Run arbitrary netconf command on cloudengine devices.
CloudEngine

Singular: `Run an arbitrary netconf command on CloudEngine devices.`
Plural: `Run arbitrary netconf commands on CloudEngine devices.`

2017-05-03 11:26 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_netconf.py
> +notes:
You can delete this note and instead use `required: true` under `rpc:`

2017-05-03 11:26 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_netconf.py
> +        rpc=dict(choices=['get', 'edit-config',
required=True?

2017-05-03 11:26 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_netconf.py
> +        required: false
Should this be required: true?

2017-05-03 11:26 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_netconf.py
> +    if not rpc or not cfg_xml:
You shouldn't need this if you have `required=True` on both options.

2017-05-03 11:26 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_netconf.py
> +version_added: "2.3"
`version_added: "2.4"`

2017-05-03 11:26 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_netconf.py
> +    - Sends an arbitrary netconf command to a cloudengine node and returns the results read from the device.
Same review comment as `short_description`

2017-05-08 11:54 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_netconf.py
> +        rpc=dict(choices=['get', 'edit-config',
YES

2017-05-08 11:55 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_netconf.py
> +    if not rpc or not cfg_xml:
OK,thanks

2017-05-08 11:57 UTC, QijunPan commented
These issues have been fixed, thank you very much.

2017-05-16 21:43 UTC, gundalow approved these changes

2017-05-16 21:43 UTC, merged