Contributing lib/ansible/modules/network/cloudengine/ce_ntp.py module to manage HUAWEI data center CloudEngine
ansible/ansible pull request #22057
Opened 2017-02-28 08:02 UTC by QijunPan

add ce_ntp

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

ce_ntp.py
##### ANSIBLE VERSION

```
ansible 2.3.0
config file = /etc/ansible/ansible.cfg
configured module search path = ['/home/ansible-2.1.1.0/lib/ansible/modules/core/network/cloudengine', '/home/ansible-2.1.1.0/lib/ansible/module_utils', '/home/ansible-2.1.1.0/lib/ansible/modules', '/home/ansible-2.1.1.0', '/home/ansible-2.1.1.0/lib/ansible/utils/']
```

##### SUMMARY

```
TASK [config ntp server] *******************************************************
task path: /usr1/code/OpenNESS/code/current/KVM/intg/test/testcases/test-ce_ntp.yml:20
Using module file /usr/local/lib/python2.7/site-packages/ansible-2.3.0-py2.7.egg/ansible/modules/core/network/cloudengine/ce_ntp.py
<ce_6850> ESTABLISH LOCAL CONNECTION FOR USER: root
<ce_6850> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1487051882.19-225076900404633 `" && echo ansible-tmp-1487051882.19-225076900404633="` echo $HOME/.ansible/tmp/ansible-tmp-1487051882.19-225076900404633 `" ) && sleep 0'
<ce_6850> PUT /tmp/tmpvLHcf6 TO /root/.ansible/tmp/ansible-tmp-1487051882.19-225076900404633/ce_ntp.py
<ce_6850> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1487051882.19-225076900404633/ /root/.ansible/tmp/ansible-tmp-1487051882.19-225076900404633/ce_ntp.py && sleep 0'
<ce_6850> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1487051882.19-225076900404633/ce_ntp.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1487051882.19-225076900404633/" > /dev/null 2>&1 && sleep 0'
changed: [ce_6850] => {
    "changed": true, 
    "end_state": [
        {
            "is_preferred": "false", 
            "key_id": null, 
            "server": "192.8.5.6", 
            "source_int": null, 
            "vpn_name": null
        }
    ], 
    "execute_time": "0:00:03.144494", 
    "existing": [], 
    "invocation": {
        "module_args": {
            "auth_pass": null, 
            "authorize": false, 
            "host": "ce_6850", 
            "is_preferred": null, 
            "key_id": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "peer": null, 
            "port": 12345, 
            "provider": null, 
            "server": "192.8.5.6", 
            "source_int": null, 
            "ssh_keyfile": null, 
            "state": "present", 
            "timeout": 10, 
            "transport": null, 
            "use_ssl": false, 
            "username": "rootDC", 
            "validate_certs": true, 
            "vpn_name": "_public_"
        }, 
        "module_name": "ce_ntp"
    }, 
    "proposed": {
        "is_preferred": "false", 
        "key_id": null, 
        "server": "192.8.5.6", 
        "source_int": null, 
        "state": "present", 
        "vpn_name": null
    }, 
    "updates": [
        "ntp unicast-server 192.8.5.6"
    ]
}
```

2017-05-03 10:05 UTC, gundalow requested changes

2017-05-03 10:05 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_ntp.py
> +version_added: "2.3"
`version_added: "2.4"`

2017-05-03 10:05 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_ntp.py
> +              Must be fully qualified interface name, i.e. 40GE1/0/22, vlanif10.
`C(40GE1/0/22), C(vlanif10).` will make it a little easier to read.

2017-05-03 10:05 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_ntp.py
> +        if not self.server and not self.peer:
There are some options to `AnsibleModule` which you may be able to use to validate options passed in.
Look at existing modules for examples:
```
required_one_of
```

2017-05-03 10:05 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_ntp.py
> +        key_id=dict(type='str'),
Should this be an int?

2017-05-08 11:45 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_ntp.py
> +        key_id=dict(type='str'),
Because the device side configuration is all type ```string```, avoid repeated conversion, Let's keep it.

2017-05-08 11:46 UTC, QijunPan commented
These issues have been fixed, thank you.

2017-05-10 17:08 UTC, mattclay commented
Updating the issue to wake up the bot.

2017-05-16 21:51 UTC, gundalow approved these changes

2017-05-16 21:51 UTC, merged