Contributing lib/ansible/modules/network/cloudengine/ce_ospf.py module to manage HUAWEI data center CloudEngine
ansible/ansible pull request #22059
Opened 2017-02-28 08:12 UTC by QijunPan

add ce_ospf

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

ce_ospf.py
##### ANSIBLE VERSION

```
ansible 2.3.0
config file = /etc/ansible/ansible.cfg
configured module search path = ['/home/ansible-2.1.1.0/lib/ansible/modules/core/network/cloudengine', '/home/ansible-2.1.1.0/lib/ansible/module_utils', '/home/ansible-2.1.1.0/lib/ansible/modules', '/home/ansible-2.1.1.0', '/home/ansible-2.1.1.0/lib/ansible/utils/']
```

##### SUMMARY

```
TASK [Ensure ospf process exist] ***********************************************
task path: /usr1/code/OpenNESS/code/current/KVM/intg/test/testcases/test-ce_ospf.yml:23
Using module file /usr/local/lib/python2.7/site-packages/ansible-2.3.0-py2.7.egg/ansible/modules/core/network/cloudengine/ce_ospf.py
<ce_6850> ESTABLISH LOCAL CONNECTION FOR USER: root
<ce_6850> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1487052112.24-816461415048 `" && echo ansible-tmp-1487052112.24-816461415048="` echo $HOME/.ansible/tmp/ansible-tmp-1487052112.24-816461415048 `" ) && sleep 0'
<ce_6850> PUT /tmp/tmpkH3QN3 TO /root/.ansible/tmp/ansible-tmp-1487052112.24-816461415048/ce_ospf.py
<ce_6850> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1487052112.24-816461415048/ /root/.ansible/tmp/ansible-tmp-1487052112.24-816461415048/ce_ospf.py && sleep 0'
<ce_6850> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1487052112.24-816461415048/ce_ospf.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1487052112.24-816461415048/" > /dev/null 2>&1 && sleep 0'
changed: [ce_6850] => {
    "changed": true, 
    "end_state": {
        "areas": [], 
        "max_load_balance": "32", 
        "nexthops": [], 
        "process_id": "100"
    }, 
    "existing": {}, 
    "invocation": {
        "module_args": {
            "addr": null, 
            "area": null, 
            "auth_key_id": null, 
            "auth_mode": null, 
            "auth_pass": null, 
            "auth_text_md5": null, 
            "auth_text_simple": null, 
            "authorize": false, 
            "host": "ce_6850", 
            "mask": null, 
            "max_load_balance": null, 
            "nexthop_addr": null, 
            "nexthop_weight": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 12345, 
            "process_id": "100", 
            "provider": null, 
            "ssh_keyfile": null, 
            "state": "present", 
            "timeout": 10, 
            "transport": null, 
            "use_ssl": false, 
            "username": "rootDC", 
            "validate_certs": true
        }, 
        "module_name": "ce_ospf"
    }, 
    "proposed": {
        "area": null, 
        "max_load_balance": null, 
        "process_id": "100", 
        "state": "present"
    }, 
    "updates": [
        "ospf 100"
    ]
}
```

2017-05-03 09:33 UTC, gundalow requested changes

2017-05-03 09:33 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_ospf.py
> +version_added: "2.3"
`version_added: "2.4"`

2017-05-03 09:33 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_ospf.py
> +        process_id=dict(required=True, type='str'),
For integers please:
use `type='int'`
remove the `isdigit` check from `check_params`

2017-05-03 09:33 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_ospf.py
> +        area=dict(required=False, type='str'),
For integers please:
use `type='int'`
remove the `isdigit` check from `check_params`

2017-05-03 09:33 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_ospf.py
> +        mask=dict(required=False, type='str'),
For integers please:
use `type='int'`
remove the `isdigit` check from `check_params`

2017-05-03 09:33 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_ospf.py
> +        auth_key_id=dict(required=False, type='str'),
For integers please:
use `type='int'`
remove the `isdigit` check from `check_params`

2017-05-03 09:33 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_ospf.py
> +        nexthop_weight=dict(required=False, type='str'),
For integers please:
use `type='int'`
remove the `isdigit` check from `check_params`

2017-05-03 09:33 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_ospf.py
> +        max_load_balance=dict(required=False, type='str'),
For integers please:
use `type='int'`
remove the `isdigit` check from `check_params`

2017-05-03 09:33 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_ospf.py
> +            if self.addr:
Does `mask` require `addr`, and does `addr` require `mask`, if so you may wish to add:
```
required_together
```

2017-05-03 09:33 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_ospf.py
> +                        self.module.fail_json(
There are some options to `AnsibleModule` which you may be able to use to validate options passed in.
Look at existing modules for examples:
```
required_together
```

2017-05-03 09:33 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_ospf.py
> +                            msg='Error: auth_key_id and auth_text_md5 should be set at the same time.')
There are some options to `AnsibleModule` which you may be able to use to validate options passed in.
Look at existing modules for examples:
```
required_together
```

2017-05-03 09:33 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_ospf.py
> +                    msg='Error: nexthop_addr and nexthop_weight should be set at the same time.')
There are some options to `AnsibleModule` which you may be able to use to validate options passed in.
Look at existing modules for examples:
```
required_together
```

2017-05-05 04:02 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_ospf.py
> +            if self.addr:
Yes,   I'll fix it.

2017-05-05 06:35 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_ospf.py
> +        process_id=dict(required=True, type='str'),
Because the device side configuration is all type ```string```, avoid repeated conversion, Let's keep it.

2017-05-05 06:35 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_ospf.py
> +        area=dict(required=False, type='str'),
Because the device side configuration is all type ```string```, avoid repeated conversion, Let's keep it.

2017-05-05 06:35 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_ospf.py
> +        mask=dict(required=False, type='str'),
Because the device side configuration is all type ```string```, avoid repeated conversion, Let's keep it.

2017-05-05 06:38 UTC, QijunPan commented
These issues have been fixed, thank you very much.

2017-05-19 07:24 UTC, gundalow approved these changes

2017-05-19 07:24 UTC, merged