Contributing lib/ansible/modules/network/cloudengine/ce_ntp_auth.py module to manage HUAWEI data center CloudEngine
ansible/ansible pull request #22058
Opened 2017-02-28 08:08 UTC by QijunPan

add ce_ntp_auth

##### ISSUE TYPE

 - New Module Pull Request
##### COMPONENT NAME

ce_ntp_auth.py
##### ANSIBLE VERSION

```
ansible 2.3.0
config file = /etc/ansible/ansible.cfg
configured module search path = ['/home/ansible-2.1.1.0/lib/ansible/modules/core/network/cloudengine', '/home/ansible-2.1.1.0/lib/ansible/module_utils', '/home/ansible-2.1.1.0/lib/ansible/modules', '/home/ansible-2.1.1.0', '/home/ansible-2.1.1.0/lib/ansible/utils/']
```

##### SUMMARY

```
TASK [config ntp authentication key-id] ****************************************
task path: /usr1/code/OpenNESS/code/current/KVM/intg/test/testcases/test-ce_ntp_auth.yml:21
Using module file /usr/local/lib/python2.7/site-packages/ansible-2.3.0-py2.7.egg/ansible/modules/core/network/cloudengine/ce_ntp_auth.py
<ce_6850> ESTABLISH LOCAL CONNECTION FOR USER: root
<ce_6850> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1487051833.38-266845643224957 `" && echo ansible-tmp-1487051833.38-266845643224957="` echo $HOME/.ansible/tmp/ansible-tmp-1487051833.38-266845643224957 `" ) && sleep 0'
<ce_6850> PUT /tmp/tmpHgpqGi TO /root/.ansible/tmp/ansible-tmp-1487051833.38-266845643224957/ce_ntp_auth.py
<ce_6850> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1487051833.38-266845643224957/ /root/.ansible/tmp/ansible-tmp-1487051833.38-266845643224957/ce_ntp_auth.py && sleep 0'
<ce_6850> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1487051833.38-266845643224957/ce_ntp_auth.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1487051833.38-266845643224957/" > /dev/null 2>&1 && sleep 0'
changed: [ce_6850] => {
    "changed": true, 
    "end_state": {
        "authentication": "disable", 
        "authentication-keyid": [
            {
                "auth_mode": "md5", 
                "key_id": "2526", 
                "trusted_key": "false"
            }
        ]
    }, 
    "execute_time": "0:00:03.540156", 
    "existing": {
        "authentication": "disable", 
        "authentication-keyid": "None"
    }, 
    "invocation": {
        "module_args": {
            "auth_mode": "md5", 
            "auth_pass": null, 
            "auth_pwd": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "auth_type": "encrypt", 
            "authentication": null, 
            "authorize": false, 
            "host": "ce_6850", 
            "key_id": "2526", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 12345, 
            "provider": null, 
            "ssh_keyfile": null, 
            "state": "present", 
            "timeout": 10, 
            "transport": null, 
            "trusted_key": "false", 
            "use_ssl": false, 
            "username": "rootDC", 
            "validate_certs": true
        }, 
        "module_name": "ce_ntp_auth"
    }, 
    "proposed": {
        "auth_mode": "md5", 
        "auth_pwd": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
        "auth_type": "encrypt", 
        "authentication": null, 
        "key_id": "2526", 
        "state": "present", 
        "trusted_key": "false"
    }, 
    "updates": [
        "ntp authentication-keyid 2526 authentication-mode md5  cipher ********"
    ]
}
```

2017-05-03 09:57 UTC, gundalow requested changes

2017-05-03 09:57 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_ntp_auth.py
> +version_added: "2.3"
`version_added: "2.4"`

2017-05-03 09:57 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_ntp_auth.py
> +            - Specify authentication algorithm md5 or hmac-sha256.
`Specify authentication algorithm.`

No need to repeat what's in `choices:`

2017-05-03 09:57 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_ntp_auth.py
> +        key_id=dict(required=True, type='str'),
For integers please:
use `type='int'`
remove the `isdigit` check from `check_params`

2017-05-03 09:57 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_ntp_auth.py
> +                    msg='Error: Please input password and auth_mode.')
There are some options to `AnsibleModule` which you may be able to use to validate options passed in.
Look at existing modules for examples:
```
required_together
```

2017-05-08 11:28 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_ntp_auth.py
> +        key_id=dict(required=True, type='str'),
Because the device side configuration is all type ```string```, avoid repeated conversion, Let's keep it.

2017-05-08 11:33 UTC, QijunPan commented
These issues have been fixed, thanks.

2017-05-19 07:24 UTC, gundalow approved these changes

2017-05-19 07:24 UTC, merged