Contributing lib/ansible/modules/network/cloudengine/ce_snmp_target_host.py module to manage HUAWEI data center CloudEngine
ansible/ansible pull request #22066
Opened 2017-02-28 09:03 UTC by QijunPan

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

ce_snmp_target_host.py
##### ANSIBLE VERSION

```
ansible 2.3.0
config file = /etc/ansible/ansible.cfg
configured module search path = ['/home/ansible-2.1.1.0/lib/ansible/modules/core/network/cloudengine', '/home/ansible-2.1.1.0/lib/ansible/module_utils', '/home/ansible-2.1.1.0/lib/ansible/modules', '/home/ansible-2.1.1.0', '/home/ansible-2.1.1.0/lib/ansible/utils/']
```

##### SUMMARY

```
TASK [change snmp target host version] *****************************************
task path: /usr1/code/OpenNESS/code/current/KVM/intg/test/testcases/test-ce_snmp_target_host.yml:31
Using module file /usr/local/lib/python2.7/site-packages/ansible-2.3.0-py2.7.egg/ansible/modules/core/network/cloudengine/ce_snmp_target_host.py
<ce_6850> ESTABLISH LOCAL CONNECTION FOR USER: root
<ce_6850> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1487053689.97-5279664452771 `" && echo ansible-tmp-1487053689.97-5279664452771="` echo $HOME/.ansible/tmp/ansible-tmp-1487053689.97-5279664452771 `" ) && sleep 0'
<ce_6850> PUT /tmp/tmpMAwtn5 TO /root/.ansible/tmp/ansible-tmp-1487053689.97-5279664452771/ce_snmp_target_host.py
<ce_6850> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1487053689.97-5279664452771/ /root/.ansible/tmp/ansible-tmp-1487053689.97-5279664452771/ce_snmp_target_host.py && sleep 0'
<ce_6850> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1487053689.97-5279664452771/ce_snmp_target_host.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1487053689.97-5279664452771/" > /dev/null 2>&1 && sleep 0'
changed: [ce_6850] => {
    "changed": true, 
    "end_state": {
        "version": "v3"
    }, 
    "existing": {
        "version": "v2c"
    }, 
    "invocation": {
        "module_args": {
            "address": null, 
            "auth_pass": null, 
            "authorize": false, 
            "connect_port": null, 
            "host": "ce_6850", 
            "host_name": null, 
            "interface_name": null, 
            "is_public_net": null, 
            "notify_type": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 12345, 
            "provider": null, 
            "recv_port": null, 
            "security_level": null, 
            "security_model": null, 
            "security_name": null, 
            "security_name_v3": null, 
            "ssh_keyfile": null, 
            "state": "present", 
            "timeout": 10, 
            "transport": null, 
            "use_ssl": false, 
            "username": "rootDC", 
            "validate_certs": true, 
            "version": "v3", 
            "vpn_name": null
        }, 
        "module_name": "ce_snmp_target_host"
    }, 
    "proposed": {
        "state": "present", 
        "version": "v3"
    }, 
    "updates": [
        "snmp-agent sys-info version v3"
    ]
}
```

2017-05-02 13:12 UTC, gundalow requested changes

2017-05-02 13:12 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_snmp_target_host.py
> +            if self.state == "present":
There are some options to `AnsibleModule` which you may be able to use to validate options passed in.
Look at existing modules for examples:
```
required_together
```

2017-05-02 13:12 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_snmp_target_host.py
> +                if not self.address or not self.notify_type:
There are some options to `AnsibleModule` which you may be able to use to validate options passed in.
Look at existing modules for examples:
```
required_together
```

2017-05-02 13:12 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_snmp_target_host.py
> +            if self.security_model and self.security_model in ["v1", "v2c"]:
There are some options to `AnsibleModule` which you may be able to use to validate options passed in.
Look at existing modules for examples:
```
required_if
```

2017-05-02 13:12 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_snmp_target_host.py
> +            if self.security_model and self.security_model in ["v3"]:
There are some options to `AnsibleModule` which you may be able to use to validate options passed in.
Look at existing modules for examples:
```
required_if
```

2017-05-04 14:00 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_snmp_target_host.py
> +            if self.security_model and self.security_model in ["v3"]:
thank you, The problem has been fixed.

2017-05-04 14:01 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_snmp_target_host.py
> +            if self.security_model and self.security_model in ["v1", "v2c"]:
thank you, The problem has been fixed.

2017-05-04 14:01 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_snmp_target_host.py
> +                if not self.address or not self.notify_type:
thank you, The problem has been fixed.

2017-05-04 14:01 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_snmp_target_host.py
> +            if self.state == "present":
thank you, The problem has been fixed.

2017-05-18 11:54 UTC, QijunPan commented
@gundalow   These problems have been fixed， can  this PR merged?

2017-05-19 07:22 UTC, gundalow approved these changes

2017-05-19 07:22 UTC, merged