Contributing lib/ansible/modules/network/cloudengine/ce_snmp_user.py module to manage HUAWEI data center CloudEngine
ansible/ansible pull request #22069
Opened 2017-02-28 10:52 UTC by QijunPan

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

ce_snmp_user.py
##### ANSIBLE VERSION

```
ansible 2.3.0
config file = /etc/ansible/ansible.cfg
configured module search path = ['/home/ansible-2.1.1.0/lib/ansible/modules/core/network/cloudengine', '/home/ansible-2.1.1.0/lib/ansible/module_utils', '/home/ansible-2.1.1.0/lib/ansible/modules', '/home/ansible-2.1.1.0', '/home/ansible-2.1.1.0/lib/ansible/utils/']
```

##### SUMMARY

```
TASK [config snmp user] ********************************************************
task path: /usr1/code/OpenNESS/code/current/KVM/intg/test/testcases/test-ce_snmp_user.yml:27
Using module file /usr/local/lib/python2.7/site-packages/ansible-2.3.0-py2.7.egg/ansible/modules/core/network/cloudengine/ce_snmp_user.py
<ce_6850> ESTABLISH LOCAL CONNECTION FOR USER: root
<ce_6850> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1487053788.71-134455651982378 `" && echo ansible-tmp-1487053788.71-134455651982378="` echo $HOME/.ansible/tmp/ansible-tmp-1487053788.71-134455651982378 `" ) && sleep 0'
<ce_6850> PUT /tmp/tmpgWgzQ_ TO /root/.ansible/tmp/ansible-tmp-1487053788.71-134455651982378/ce_snmp_user.py
<ce_6850> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1487053788.71-134455651982378/ /root/.ansible/tmp/ansible-tmp-1487053788.71-134455651982378/ce_snmp_user.py && sleep 0'
<ce_6850> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1487053788.71-134455651982378/ce_snmp_user.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1487053788.71-134455651982378/" > /dev/null 2>&1 && sleep 0'
changed: [ce_6850] => {
    "changed": true, 
    "end_state": {
        "snmp local user": {
            "local_user_info": []
        }, 
        "snmp usm user": {
            "usm_user_info": [
                {
                    "aclNumber": "2000", 
                    "engineID": "800007DB03FCE33CA7D461", 
                    "remoteEngineID": "false", 
                    "userName": "wdz_snmp"
                }
            ]
        }
    }, 
    "existing": {
        "snmp local user": {
            "local_user_info": []
        }, 
        "snmp usm user": {
            "usm_user_info": []
        }
    }, 
    "invocation": {
        "module_args": {
            "aaa_local_user": null, 
            "acl_number": "2000", 
            "auth_key": null, 
            "auth_pass": null, 
            "auth_protocol": null, 
            "authorize": false, 
            "host": "ce_6850", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 12345, 
            "priv_key": null, 
            "priv_protocol": null, 
            "provider": null, 
            "remote_engine_id": null, 
            "ssh_keyfile": null, 
            "state": "present", 
            "timeout": 10, 
            "transport": null, 
            "use_ssl": false, 
            "user_group": null, 
            "username": "rootDC", 
            "usm_user_name": "wdz_snmp", 
            "validate_certs": true
        }, 
        "module_name": "ce_snmp_user"
    }, 
    "proposed": {
        "acl_number": "2000", 
        "state": "present", 
        "usm_user_name": "wdz_snmp"
    }, 
    "updates": [
        [
            "snmp-agent usm-user v3 wdz_snmp acl 2000", 
            "snmp-agent usm-user v3 wdz_snmp", 
            "snmp-agent usm-user v3 wdz_snmp"
        ]
    ]
}
```

2017-05-02 12:54 UTC, gundalow requested changes

2017-05-02 12:54 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_snmp_user.py
> +version_added: "2.3"
`version_added: "2.4"`

2017-05-02 12:54 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_snmp_user.py
> +                    'version': '1.0'}
`metadata_version`

2017-05-02 12:54 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_snmp_user.py
> +            - Authentication protocol ( md5 | sha ).
`Authentication protocol.`

No need to repeat `choices:`

2017-05-02 12:54 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_snmp_user.py
> +            - The authentication password. Simple password length <8-255>. Field max.
Suggestion: `The authentication password. Password length, 8-255 characters.`

2017-05-02 12:54 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_snmp_user.py
> +            - The encryption password. Simple password length <8-255>. Field max.
Suggestion: `The encryption password. Password length 8-255 characters.`

2017-05-02 12:54 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_snmp_user.py
> +            if local_user_name:
There are some options to `AnsibleModule` which you may be able to use to validate options passed in.
Look at existing modules for examples:
```
mutually_exclusive
```

2017-05-02 12:54 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_snmp_user.py
> +                if not auth_protocol:
There are some options to `AnsibleModule` which you may be able to use to validate options passed in.
Look at existing modules for examples:
```
required_together
require_if
```

2017-05-04 10:45 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_snmp_user.py
> +                    'version': '1.0'}
OK, I'll fix it. thanks.

2017-05-04 10:45 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_snmp_user.py
> +            - Authentication protocol ( md5 | sha ).
OK, I'll fix it. thanks.

2017-05-04 10:45 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_snmp_user.py
> +            - The encryption password. Simple password length <8-255>. Field max.
Good suggestion, I'll fix it. thanks.

2017-05-04 10:52 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_snmp_user.py
> +                if not auth_protocol:
I'm trying, but it doesn't work.

2017-05-04 10:53 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_snmp_user.py
> +            if local_user_name:
OK, I'll fix it, thanks.

2017-05-04 11:06 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_snmp_user.py
> +                if not auth_protocol:
I'm currently working on some documentation for `AnsibleModule`, the following shows the different validation options:
```
def main():
    module = AnsibleModule(
        argument_spec=dict(
            state=dict(default='present', choices=['present', 'absent']),
            username=dict(type='str'),
            password=dict(no_log=True),
            token=dict(no_log=True),
            src=dict(type='path'),
            priority=dict(type='int'),
        ),
        mutually_exclusive=(['password', 'token'],),
        required_together=(['username', 'password'],),
        required_one_of=[['password', 'token']],
        required_if=[('state', 'present', ['src', 'priority'])],
        supports_check_mode=True
   )
```

2017-05-04 11:41 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_snmp_user.py
> +                if not auth_protocol:
@gundalow I need your help. when I deal this logic:
```
if A:
    if not B:
        print something errror
```
B is not dependent on A, but A dependent on B， They don't need to be config at the same time， it's not use ```required_together```, so I'll try:
```
required_if=[('B', not None, ['A'])]
```
but it is not work well.
I think ```required_if``` needs to be improved, This condition is not enough to judge when the condition is ```not None```,  How do you think about?

2017-05-18 11:53 UTC, QijunPan commented
@gundalow   These problems have been fixed， can  this PR merged?

2017-05-19 07:21 UTC, gundalow approved these changes

2017-05-19 07:21 UTC, merged