Contributing lib/ansible/modules/network/cloudengine/ce_snmp_contact.py module to manage HUAWEI data center CloudEngine
ansible/ansible pull request #22064
Opened 2017-02-28 08:49 UTC by QijunPan

add ce_snmp_connect

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

ce_snmp_contact.py
##### ANSIBLE VERSION

```
ansible 2.3.0
config file = /etc/ansible/ansible.cfg
configured module search path = ['/home/ansible-2.1.1.0/lib/ansible/modules/core/network/cloudengine', '/home/ansible-2.1.1.0/lib/ansible/module_utils', '/home/ansible-2.1.1.0/lib/ansible/modules', '/home/ansible-2.1.1.0', '/home/ansible-2.1.1.0/lib/ansible/utils/']
```

##### SUMMARY

```
TASK [config snmp contact] *****************************************************
task path: /usr1/code/OpenNESS/code/current/KVM/intg/test/testcases/test-ce_snmp_contact.yml:22
Using module file /usr/local/lib/python2.7/site-packages/ansible-2.3.0-py2.7.egg/ansible/modules/core/network/cloudengine/ce_snmp_contact.py
<ce_6850> ESTABLISH LOCAL CONNECTION FOR USER: root
<ce_6850> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1487053602.44-179342278832205 `" && echo ansible-tmp-1487053602.44-179342278832205="` echo $HOME/.ansible/tmp/ansible-tmp-1487053602.44-179342278832205 `" ) && sleep 0'
<ce_6850> PUT /tmp/tmpF8rr5q TO /root/.ansible/tmp/ansible-tmp-1487053602.44-179342278832205/ce_snmp_contact.py
<ce_6850> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1487053602.44-179342278832205/ /root/.ansible/tmp/ansible-tmp-1487053602.44-179342278832205/ce_snmp_contact.py && sleep 0'
<ce_6850> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1487053602.44-179342278832205/ce_snmp_contact.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1487053602.44-179342278832205/" > /dev/null 2>&1 && sleep 0'
changed: [ce_6850] => {
    "changed": true, 
    "end_state": {
        "contact": "call Operator at 010-99999999"
    }, 
    "existing": {}, 
    "invocation": {
        "module_args": {
            "auth_pass": null, 
            "authorize": false, 
            "contact": "call Operator at 010-99999999", 
            "host": "ce_6850", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 12345, 
            "provider": null, 
            "ssh_keyfile": null, 
            "state": "present", 
            "timeout": 10, 
            "transport": null, 
            "use_ssl": false, 
            "username": "rootDC", 
            "validate_certs": true
        }, 
        "module_name": "ce_snmp_contact"
    }, 
    "proposed": {
        "contact": "call Operator at 010-99999999", 
        "state": "present"
    }, 
    "updates": [
        "snmp-agent sys-info contact call Operator at 010-99999999"
    ]
}
```

2017-05-02 13:21 UTC, gundalow requested changes

2017-05-02 13:21 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_snmp_contact.py
> +options:
Missing `state:`

2017-05-05 02:20 UTC, QijunPan commented
These issues have been fixed, thank you very much.

2017-05-18 11:55 UTC, QijunPan commented
@gundalow   These problems have been fixed， can  this PR merged?

2017-05-18 18:47 UTC, gundalow approved these changes

2017-05-18 22:07 UTC, gundalow approved these changes

2017-05-18 22:08 UTC, merged