Contributing lib/ansible/modules/network/cloudengine/ce_reboot.py module to manage HUAWEI data center CloudEngine
ansible/ansible pull request #22060
Opened 2017-02-28 08:18 UTC by QijunPan

add ce_reboot

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

ce_reboot.py
##### ANSIBLE VERSION

```
ansible 2.3.0
config file = /etc/ansible/ansible.cfg
configured module search path = ['/home/ansible-2.1.1.0/lib/ansible/modules/core/network/cloudengine', '/home/ansible-2.1.1.0/lib/ansible/module_utils', '/home/ansible-2.1.1.0/lib/ansible/modules', '/home/ansible-2.1.1.0', '/home/ansible-2.1.1.0/lib/ansible/utils/']
```

##### SUMMARY

```
ansible -vvv -m ce_reboot -a 'host=10.135.182.157 port=12347 username=rootDC password=Admin@123 confirm=true save_config=true' localhost --connection local
Using /etc/ansible/ansible.cfg as config file
Using module file /usr1/wangdz/ansible-iSource/lib/ansible/modules/core/network/cloudengine/ce_reboot.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1487054756.28-94911482560641 `" && echo ansible-tmp-1487054756.28-94911482560641="` echo $HOME/.ansible/tmp/ansible-tmp-1487054756.28-94911482560641 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmp4aUB3k TO /root/.ansible/tmp/ansible-tmp-1487054756.28-94911482560641/ce_reboot.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1487054756.28-94911482560641/ /root/.ansible/tmp/ansible-tmp-1487054756.28-94911482560641/ce_reboot.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1487054756.28-94911482560641/ce_reboot.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1487054756.28-94911482560641/" > /dev/null 2>&1 && sleep 0'
localhost | SUCCESS => {
    "changed": true, 
    "invocation": {
        "module_args": {
            "auth_pass": null, 
            "authorize": false, 
            "confirm": true, 
            "host": "10.135.182.157", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 12347, 
            "provider": null, 
            "save_config": "true", 
            "ssh_keyfile": null, 
            "timeout": 10, 
            "transport": null, 
            "use_ssl": false, 
            "username": "rootDC", 
            "validate_certs": true
        }, 
        "module_name": "ce_reboot"
    }, 
    "rebooted": true
}

```

2017-05-03 09:23 UTC, gundalow requested changes

2017-05-03 09:23 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_reboot.py
> +version_added: 2.3
`version_added: "2.4"`

2017-05-03 09:23 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_reboot.py
> +        save_config=dict(required=False, default='false',
`save_config=dict(required=True,default=False, type='bool'),`

Then ensure the code works with Booleans

2017-05-03 09:23 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_reboot.py
> +        required: true
Please add `type: bool`

2017-05-03 09:23 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_reboot.py
> +        required: false
Please add `type: bool`

2017-05-03 09:23 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_reboot.py
> +short_description: Reboot a network device.
`Reboot a CloudEngine network device`

2017-05-03 09:23 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_reboot.py
> +        confirm=dict(required=True, type='bool'),
default=False

2017-05-03 09:23 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_reboot.py
> +        module.network_module.fail_json(msg='Error: The ncclient library is required.')
Please add this to the `DOCUMENTATION` block, e.g.
`requirements: ncclient`

http://docs.ansible.com/ansible/dev_guide/developing_modules_documenting.html#documentation-block

2017-05-05 03:20 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_reboot.py
> +        required: true
OK, It has been fixed.  thanks.

2017-05-05 03:21 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_reboot.py
> +        module.network_module.fail_json(msg='Error: The ncclient library is required.')
OK, It has been fixed. thanks.

2017-05-05 03:58 UTC, QijunPan commented
These issues have been fixed, thank you very much!

2017-05-19 07:23 UTC, gundalow approved these changes

2017-05-19 07:23 UTC, merged