Contributing lib/ansible/modules/network/cloudengine/ce_snmp_traps.py module to manage HUAWEI data center CloudEngine
ansible/ansible pull request #22067
Opened 2017-02-28 09:05 UTC by QijunPan

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

ce_snmp_traps.py
##### ANSIBLE VERSION

```
ansible 2.3.0
config file = /etc/ansible/ansible.cfg
configured module search path = ['/home/ansible-2.1.1.0/lib/ansible/modules/core/network/cloudengine', '/home/ansible-2.1.1.0/lib/ansible/module_utils', '/home/ansible-2.1.1.0/lib/ansible/modules', '/home/ansible-2.1.1.0', '/home/ansible-2.1.1.0/lib/ansible/utils/']
```

##### SUMMARY

```
TASK [config snmp traps] *******************************************************
task path: /usr1/code/OpenNESS/code/current/KVM/intg/test/testcases/test-ce_snmp_traps.yml:18
Using module file /usr/local/lib/python2.7/site-packages/ansible-2.3.0-py2.7.egg/ansible/modules/core/network/cloudengine/ce_snmp_traps.py
<ce_6850> ESTABLISH LOCAL CONNECTION FOR USER: root
<ce_6850> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1487053737.44-173263156287693 `" && echo ansible-tmp-1487053737.44-173263156287693="` echo $HOME/.ansible/tmp/ansible-tmp-1487053737.44-173263156287693 `" ) && sleep 0'
<ce_6850> PUT /tmp/tmpzUPYUK TO /root/.ansible/tmp/ansible-tmp-1487053737.44-173263156287693/ce_snmp_traps.py
<ce_6850> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1487053737.44-173263156287693/ /root/.ansible/tmp/ansible-tmp-1487053737.44-173263156287693/ce_snmp_traps.py && sleep 0'
<ce_6850> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1487053737.44-173263156287693/ce_snmp_traps.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1487053737.44-173263156287693/" > /dev/null 2>&1 && sleep 0'
changed: [ce_6850] => {
    "changed": true, 
    "end_state": {
        "snmp-agent trap": [
            "enable"
        ], 
        "undo snmp-agent trap": []
    }, 
    "existing": {
        "snmp-agent trap": [], 
        "undo snmp-agent trap": []
    }, 
    "invocation": {
        "module_args": {
            "auth_pass": null, 
            "authorize": false, 
            "feature_name": "all", 
            "host": "ce_6850", 
            "interface_number": null, 
            "interface_type": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 12345, 
            "port_number": null, 
            "provider": null, 
            "ssh_keyfile": null, 
            "state": "present", 
            "timeout": 10, 
            "transport": null, 
            "trap_name": null, 
            "use_ssl": false, 
            "username": "rootDC", 
            "validate_certs": true
        }, 
        "module_name": "ce_snmp_traps"
    }, 
    "proposed": {
        "feature_name": "all", 
        "state": "present"
    }, 
    "updates": [
        "snmp-agent trap enable"
    ]
}
```

2017-05-02 13:01 UTC, gundalow requested changes

2017-05-02 13:01 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_snmp_traps.py
> +        port_number=dict(type='str')
For integers please:
use `type='int`
remove the `isdigit` check from `check_params

2017-05-02 13:01 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_snmp_traps.py
> +        if self.interface_type:
There are some options to `AnsibleModule` which you may be able to use to validate options passed in.
Look at existing modules for examples:
```
required_together
```

2017-05-02 13:01 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_snmp_traps.py
> +        if self.interface_number:
There are some options to `AnsibleModule` which you may be able to use to validate options passed in.
Look at existing modules for examples:
```
required_together
```

2017-05-04 11:54 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_snmp_traps.py
> +        if self.interface_type:
I'll fix it. thank you.

2017-05-04 11:54 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_snmp_traps.py
> +        if self.interface_number:
I'll fix it. thank you.

2017-05-04 11:59 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_snmp_traps.py
> +        port_number=dict(type='str')
Because the device side is string, avoid repeated conversion,  retain it， thanks.

2017-05-18 11:53 UTC, QijunPan commented
@gundalow   These problems have been fixed， can  this PR merged?

2017-05-19 07:22 UTC, gundalow approved these changes

2017-05-19 07:22 UTC, merged