Contributing lib/ansible/modules/network/cloudengine/ce_rollback.py module to manage HUAWEI data center CloudEngine
ansible/ansible pull request #22061
Opened 2017-02-28 08:20 UTC by QijunPan

add ce_rollback

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

ce_rollback.py
##### ANSIBLE VERSION

```
ansible 2.3.0
config file = /etc/ansible/ansible.cfg
configured module search path = ['/home/ansible-2.1.1.0/lib/ansible/modules/core/network/cloudengine', '/home/ansible-2.1.1.0/lib/ansible/module_utils', '/home/ansible-2.1.1.0/lib/ansible/modules', '/home/ansible-2.1.1.0', '/home/ansible-2.1.1.0/lib/ansible/utils/']
```

##### SUMMARY

```
TASK [Set the user label of a specified configuration checkpoint 1] ************
task path: /usr1/code/OpenNESS/code/current/KVM/intg/test/testcases/test-ce_rollback.yml:29
Using module file /usr/local/lib/python2.7/site-packages/ansible-2.3.0-py2.7.egg/ansible/modules/core/network/cloudengine/ce_rollback.py
<ce_6850> ESTABLISH LOCAL CONNECTION FOR USER: root
<ce_6850> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1487053443.04-35796149118741 `" && echo ansible-tmp-1487053443.04-35796149118741="` echo $HOME/.ansible/tmp/ansible-tmp-1487053443.04-35796149118741 `" ) && sleep 0'
<ce_6850> PUT /tmp/tmpg7dSlJ TO /root/.ansible/tmp/ansible-tmp-1487053443.04-35796149118741/ce_rollback.py
<ce_6850> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1487053443.04-35796149118741/ /root/.ansible/tmp/ansible-tmp-1487053443.04-35796149118741/ce_rollback.py && sleep 0'
<ce_6850> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1487053443.04-35796149118741/ce_rollback.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1487053443.04-35796149118741/" > /dev/null 2>&1 && sleep 0'
changed: [ce_6850] => {
    "changed": true, 
    "end_state": null, 
    "existing": {}, 
    "invocation": {
        "module_args": {
            "action": "set", 
            "auth_pass": null, 
            "authorize": false, 
            "commit_id": "1000096276", 
            "filename": null, 
            "host": "ce_6850", 
            "label": "user1", 
            "last": null, 
            "oldest": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 12345, 
            "provider": null, 
            "ssh_keyfile": null, 
            "timeout": 10, 
            "transport": null, 
            "use_ssl": false, 
            "username": "rootDC", 
            "validate_certs": true
        }, 
        "module_name": "ce_rollback"
    }, 
    "proposed": {
        "commit_id": "1000096276", 
        "label": "user1"
    }, 
    "updates": [
        "set configuration commit 1000096276 label user1"
    ]
}
```

2017-05-02 13:44 UTC, gundalow requested changes

2017-05-02 13:44 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_rollback.py
> +version_added: "2.3"
`+version_added: "2.4"`

2017-05-02 13:44 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_rollback.py
> +        last=dict(required=False, type='str'),
For integers please:
use `type='int`
remove the `isdigit` check from `check_params`

2017-05-02 13:44 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_rollback.py
> +        oldest=dict(required=False, type='str'),
For integers please:
use `type='int`
remove the `isdigit` check from `check_params`

2017-05-02 13:44 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_rollback.py
> +        commit_id=dict(required=False),
For integers please:
use `type='int`
remove the `isdigit` check from `check_params`

2017-05-05 02:53 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_rollback.py
> +        oldest=dict(required=False, type='str'),
Because the device side configuration is all type ```string```, avoid repeated conversion, Let's keep it.

2017-05-05 02:53 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_rollback.py
> +        last=dict(required=False, type='str'),
Because the device side configuration is all type ```string```, avoid repeated conversion, Let's keep it.

2017-05-05 02:53 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_rollback.py
> +        commit_id=dict(required=False),
Because the device side configuration is all type ```string```, avoid repeated conversion, Let's keep it.

2017-05-05 02:53 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_rollback.py
> +version_added: "2.3"
OK I'll fix it.

2017-05-05 02:53 UTC, QijunPan commented
These issues have been fixed, thank you very much.

2017-05-19 07:23 UTC, gundalow approved these changes

2017-05-19 07:23 UTC, merged