Contributing lib/ansible/modules/network/cloudengine/ce_startup.py module to manage HUAWEI data center CloudEngine
ansible/ansible pull request #22070
Opened 2017-02-28 10:55 UTC by QijunPan

add ce_startup

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

ce_startup.py
##### ANSIBLE VERSION

```
ansible 2.3.0
config file = /etc/ansible/ansible.cfg
configured module search path = ['/home/ansible-2.1.1.0/lib/ansible/modules/core/network/cloudengine', '/home/ansible-2.1.1.0/lib/ansible/module_utils', '/home/ansible-2.1.1.0/lib/ansible/modules', '/home/ansible-2.1.1.0', '/home/ansible-2.1.1.0/lib/ansible/utils/']
```

##### SUMMARY

```
TASK [display startup information] *********************************************************************************************************************************************************************************************************
task path: /usr1/wangdz/ansible-iSource/ansible/test/testcases/test-ce_startup.yml:23
Using module file /usr/local/lib/python2.7/dist-packages/ansible-2.3.0-py2.7.egg/ansible/modules/network/cloudengine/ce_startup.py
<10.135.182.157> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.135.182.157> EXEC /bin/sh -c 'echo ~ && sleep 0'
<10.135.182.157> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1488193097.69-278676106367016 `" && echo ansible-tmp-1488193097.69-278676106367016="` echo /root/.ansible/tmp/ansible-tmp-1488193097.69-278676106367016 `" ) && sleep 0'
<10.135.182.157> PUT /tmp/tmpr_6nEE TO /root/.ansible/tmp/ansible-tmp-1488193097.69-278676106367016/ce_startup.py
<10.135.182.157> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1488193097.69-278676106367016/ /root/.ansible/tmp/ansible-tmp-1488193097.69-278676106367016/ce_startup.py && sleep 0'
<10.135.182.157> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1488193097.69-278676106367016/ce_startup.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1488193097.69-278676106367016/" > /dev/null 2>&1 && sleep 0'
ok: [10.135.182.157] => {
    "changed": false, 
    "end_state": {
        "StartupInfos": null
    }, 
    "existing": {
        "StartupInfos": [
            {
                "configSysSoft": "flash:/CE6850UHI-V200R001C00SPC700.cc", 
                "curentPatchFile": "NULL", 
                "curentStartupFile": "flash:/fcoe_vm.cfg", 
                "curentSysSoft": "flash:/CE6850UHI-V200R001C00SPC700.cc", 
                "nextPatchFile": "NULL", 
                "nextStartupFile": "flash:/fcoe_vm.cfg", 
                "nextSysSoft": "flash:/CE6850UHI-V200R001C00SPC700.cc", 
                "position": "slot1"
            }
        ]
    }, 
    "invocation": {
        "module_args": {
            "action": "display", 
            "cfg_file": null, 
            "host": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "patch_file": null, 
            "port": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "provider": {
                "host": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "port": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "timeout": null, 
                "transport": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "use_ssl": null, 
                "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "validate_certs": null
            }, 
            "slot": null, 
            "software_file": null, 
            "timeout": null, 
            "transport": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "use_ssl": null, 
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "validate_certs": null
        }
    }, 
    "proposed": {}, 
    "updates": []
}
```

2017-05-02 12:45 UTC, gundalow requested changes

2017-05-02 12:45 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_startup.py
> +        slot=dict(type='str'),
For integers please:
use `type='int`
remove the `isdigit` check from `check_params`

2017-05-04 10:36 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_startup.py
> +        slot=dict(type='str'),
Let's keep this type, avoid conversion

2017-05-18 11:52 UTC, QijunPan commented
@gundalow   These problems have been fixed， can  this PR merged?

2017-05-18 22:07 UTC, gundalow approved these changes

2017-05-18 22:07 UTC, merged