Contributing lib/ansible/modules/network/cloudengine/ce_switchport.py module to manage HUAWEI data center CloudEngine
ansible/ansible pull request #22075
Opened 2017-02-28 11:12 UTC by QijunPan

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

ce_switchport.py
##### ANSIBLE VERSION

```
ansible 2.3.0
config file = /etc/ansible/ansible.cfg
configured module search path = ['/home/ansible-2.1.1.0/lib/ansible/modules/core/network/cloudengine', '/home/ansible-2.1.1.0/lib/ansible/module_utils', '/home/ansible-2.1.1.0/lib/ansible/modules', '/home/ansible-2.1.1.0', '/home/ansible-2.1.1.0/lib/ansible/utils/']
```

##### SUMMARY

```
TASK [ENSURE 40GE1/0/4 is configured for access vlan 20] ***********************
task path: /usr1/code/OpenNESS/code/current/KVM/intg/test/testcases/test-ce_switchport.yml:30
Using module file /usr/local/lib/python2.7/site-packages/ansible-2.3.0-py2.7.egg/ansible/modules/core/network/cloudengine/ce_switchport.py
<ce_6850> ESTABLISH LOCAL CONNECTION FOR USER: root
<ce_6850> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1487053951.32-122707423167147 `" && echo ansible-tmp-1487053951.32-122707423167147="` echo $HOME/.ansible/tmp/ansible-tmp-1487053951.32-122707423167147 `" ) && sleep 0'
<ce_6850> PUT /tmp/tmpaG50mq TO /root/.ansible/tmp/ansible-tmp-1487053951.32-122707423167147/ce_switchport.py
<ce_6850> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1487053951.32-122707423167147/ /root/.ansible/tmp/ansible-tmp-1487053951.32-122707423167147/ce_switchport.py && sleep 0'
<ce_6850> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1487053951.32-122707423167147/ce_switchport.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1487053951.32-122707423167147/" > /dev/null 2>&1 && sleep 0'
changed: [ce_6850] => {
    "changed": true, 
    "end_state": {
        "access_vlan": "20", 
        "interface": "40GE1/0/4", 
        "mode": "access", 
        "native_vlan": "20", 
        "switchport": "enable", 
        "trunk_vlans": ""
    }, 
    "existing": {
        "access_vlan": "1", 
        "interface": "40GE1/0/4", 
        "mode": "access", 
        "native_vlan": "1", 
        "switchport": "enable", 
        "trunk_vlans": ""
    }, 
    "invocation": {
        "module_args": {
            "access_vlan": "20", 
            "auth_pass": null, 
            "authorize": false, 
            "host": "ce_6850", 
            "interface": "40GE1/0/4", 
            "mode": "access", 
            "native_vlan": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 12345, 
            "provider": null, 
            "ssh_keyfile": null, 
            "state": "present", 
            "timeout": 10, 
            "transport": null, 
            "trunk_vlans": null, 
            "use_ssl": false, 
            "username": "rootDC", 
            "validate_certs": true
        }, 
        "module_name": "ce_switchport"
    }, 
    "proposed": {
        "access_vlan": "20", 
        "interface": "40GE1/0/4", 
        "mode": "access", 
        "native_vlan": null, 
        "state": "present", 
        "trunk_vlans": null
    }, 
    "updates": [
        "interface 40GE1/0/4", 
        "port default vlan 20"
    ]
}
```

2017-05-02 12:14 UTC, gundalow requested changes

2017-05-02 12:14 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_switchport.py
> +      in the `port trunk allow-pass vlan` command. Use verbose mode to see
`C(port trunk allow-pass vlan)`

2017-05-02 12:14 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_switchport.py
> +        if not self.interface:
If you have `required=True` this isn't needed

2017-05-02 12:14 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_switchport.py
> +def is_portswitch_enalbe(iftype):
is_portswitch_enalbe -> is_portswitch_enabled

2017-05-02 12:14 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_switchport.py
> +        if not self.intf_type or not is_portswitch_enalbe(self.intf_type):
is_portswitch_enalbe -> is_portswitch_enabled

2017-05-02 12:14 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_switchport.py
> +            if not self.access_vlan.isdigit():
Not needed if you do `type='int'`

2017-05-02 12:14 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_switchport.py
> +            if not self.native_vlan.isdigit():
Not needed if you do `type='int'`

2017-05-02 12:14 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_switchport.py
> +        if self.state == "present" or self.state == "absent":
Not needed if you have `required=True`

2017-05-02 12:14 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_switchport.py
> +                self.module.fail_json(msg='Error: Interface mode must be set.')
There are some options to `AnsibleModule` which you may be able to use to validate options passed in.
Look at existing modules for examples:
```
mutually_exclusive
required_together
required_one_of
require_if
```

2017-05-04 08:09 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_switchport.py
> +            if not self.native_vlan.isdigit():
Let's keep this type, avoid conversion

2017-05-04 08:09 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_switchport.py
> +            if not self.access_vlan.isdigit():
Let's keep this type, avoid conversion

2017-05-04 08:09 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_switchport.py
> +        if not self.intf_type or not is_portswitch_enalbe(self.intf_type):
OK，thank you.

2017-05-04 08:11 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_switchport.py
> +                self.module.fail_json(msg='Error: Interface mode must be set.')
good idea,  thank you.

2017-05-18 11:52 UTC, QijunPan commented
@gundalow   These problems have been fixed， can  this PR merged?

2017-05-18 22:09 UTC, merged