Contributing lib/ansible/modules/network/cloudengine/ce_stp.py module to manage HUAWEI data center CloudEngine
ansible/ansible pull request #22073
Opened 2017-02-28 11:08 UTC by QijunPan

##### ISSUE TYPE

 - New Module Pull Request
##### COMPONENT NAME

ce_stp.py
##### ANSIBLE VERSION

```
ansible 2.3.0
config file = /etc/ansible/ansible.cfg
configured module search path = ['/home/ansible-2.1.1.0/lib/ansible/modules/core/network/cloudengine', '/home/ansible-2.1.1.0/lib/ansible/module_utils', '/home/ansible-2.1.1.0/lib/ansible/modules', '/home/ansible-2.1.1.0', '/home/ansible-2.1.1.0/lib/ansible/utils/']
```

##### SUMMARY

```
TASK [config stp mode] *********************************************************
task path: /usr1/code/OpenNESS/code/current/KVM/intg/test/testcases/test-ce_stp.yml:23
Using module file /usr/local/lib/python2.7/site-packages/ansible-2.3.0-py2.7.egg/ansible/modules/core/network/cloudengine/ce_stp.py
<ce_6850> ESTABLISH LOCAL CONNECTION FOR USER: root
<ce_6850> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1487053900.0-25983287206973 `" && echo ansible-tmp-1487053900.0-25983287206973="` echo $HOME/.ansible/tmp/ansible-tmp-1487053900.0-25983287206973 `" ) && sleep 0'
<ce_6850> PUT /tmp/tmp1At8OQ TO /root/.ansible/tmp/ansible-tmp-1487053900.0-25983287206973/ce_stp.py
<ce_6850> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1487053900.0-25983287206973/ /root/.ansible/tmp/ansible-tmp-1487053900.0-25983287206973/ce_stp.py && sleep 0'
<ce_6850> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1487053900.0-25983287206973/ce_stp.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1487053900.0-25983287206973/" > /dev/null 2>&1 && sleep 0'
changed: [ce_6850] => {
    "changed": true, 
    "end_state": {
        "stp_mode": "stp"
    }, 
    "existing": {
        "stp_mode": "mstp"
    }, 
    "invocation": {
        "module_args": {
            "auth_pass": null, 
            "authorize": false, 
            "bpdu_filter": null, 
            "bpdu_protection": null, 
            "cost": null, 
            "edged_port": null, 
            "host": "ce_6850", 
            "interface": null, 
            "loop_protection": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 12345, 
            "provider": null, 
            "root_protection": null, 
            "ssh_keyfile": null, 
            "state": "present", 
            "stp_converge": null, 
            "stp_enable": null, 
            "stp_mode": "stp", 
            "tc_protection": null, 
            "tc_protection_interval": null, 
            "tc_protection_threshold": null, 
            "timeout": 10, 
            "transport": null, 
            "use_ssl": false, 
            "username": "rootDC", 
            "validate_certs": true
        }, 
        "module_name": "ce_stp"
    }, 
    "proposed": {
        "state": "present", 
        "stp_mode": "stp"
    }, 
    "updates": [
        "stp mode stp"
    ]
}

```

2017-05-02 12:25 UTC, gundalow requested changes

2017-05-02 12:25 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_stp.py
> +        tc_protection_interval=dict(type='str'),
For integers please:
use `type='int`
remove the `isdigit` check from `check_params`

2017-05-02 12:25 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_stp.py
> +        tc_protection_threshold=dict(type='str'),
For integers please:
use `type='int`
remove the `isdigit` check from `check_params`

2017-05-02 12:25 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_stp.py
> +        cost=dict(type='str'),
For integers please:
use `type='int`
remove the `isdigit` check from `check_params`

2017-05-02 12:25 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_stp.py
> +    def check_args(self):
You've named this check_params in other modules. Not a major issue.

2017-05-02 12:25 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_stp.py
> +        if self.cost:
Can be simplified if you do `type='int'`.

2017-05-02 12:25 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_stp.py
> +        if self.tc_protection_interval:
Can be simplified if you do `type='int'`.

2017-05-02 12:25 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_stp.py
> +        if self.tc_protection_threshold:
Can be simplified if you do `type='int'`.

2017-05-02 12:25 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_stp.py
> +            if not self.interface:
There are some options to `AnsibleModule` which you may be able to use to validate options passed in.
Look at existing modules for examples:
```
required_together
required_one_of
require_if
```

2017-05-02 12:25 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_stp.py
> +            elif self.interface == "all":
There are some options to `AnsibleModule` which you may be able to use to validate options passed in.
Look at existing modules for examples:
```
mutually_exclusive
```

2017-05-02 12:25 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_stp.py
> +        if self.root_protection and self.root_protection == "enable":
There are some options to `AnsibleModule` which you may be able to use to validate options passed in.
Look at existing modules for examples:
```
mutually_exclusive
required_together
required_one_of
require_if
```

2017-05-02 12:25 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_stp.py
> +        if self.edged_port or self.bpdu_filter:
There are some options to `AnsibleModule` which you may be able to use to validate options passed in.
Look at existing modules for examples:
```
required_together
require_if
```

2017-05-02 12:25 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_stp.py
> +              The value is an integer ranging from 1 to 255. The default value is 1.
I don't see `default=1` in the argspec, or in the documentation. Is this the default on the switch?

If so then this comment may need updating

2017-05-02 12:25 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_stp.py
> +              If the value is all, will apply configuration to all interfaces.
`If the value is C(all), apply configuration to all interfaces.`

2017-05-04 08:49 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_stp.py
> +        if self.tc_protection_threshold:
Let's keep this type, avoid conversion

2017-05-04 08:49 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_stp.py
> +        if self.tc_protection_interval:
Let's keep this type, avoid conversion

2017-05-04 08:55 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_stp.py
> +        cost=dict(type='str'),
Let's keep this type, avoid conversion

2017-05-04 08:55 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_stp.py
> +        tc_protection_threshold=dict(type='str'),
Let's keep this type, avoid conversion

2017-05-04 08:55 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_stp.py
> +        tc_protection_interval=dict(type='str'),
Let's keep this type, avoid conversion

2017-05-04 09:00 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_stp.py
> +        if self.edged_port or self.bpdu_filter:
I'm trying, but it doesn't work.

2017-05-04 09:01 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_stp.py
> +            if not self.interface:
I'm trying, but it doesn't work.

2017-05-04 09:01 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_stp.py
> +        if self.root_protection and self.root_protection == "enable":
I'm trying, but it doesn't work.

2017-05-04 09:01 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_stp.py
> +            elif self.interface == "all":
I'm trying, but it doesn't work.

2017-05-18 11:52 UTC, QijunPan commented
@gundalow   These problems have been fixed， can  this PR merged?

2017-05-18 22:09 UTC, gundalow approved these changes

2017-05-18 22:09 UTC, merged