Contributing lib/ansible/modules/network/cloudengine/ce_vrf_interface.py module to manage HUAWEI data center CloudEngine
ansible/ansible pull request #22079
Opened 2017-02-28 11:36 UTC by QijunPan

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

ce_vrf_interface.py
##### ANSIBLE VERSION

```
ansible 2.3.0
config file = /etc/ansible/ansible.cfg
configured module search path = ['/home/ansible-2.1.1.0/lib/ansible/modules/core/network/cloudengine', '/home/ansible-2.1.1.0/lib/ansible/module_utils', '/home/ansible-2.1.1.0/lib/ansible/modules', '/home/ansible-2.1.1.0', '/home/ansible-2.1.1.0/lib/ansible/utils/']
```

##### SUMMARY

```

TASK [Configure a VPN instance on the interface] *******************************
task path: /usr1/code/OpenNESS/code/current/KVM/intg/test/testcases/test-ce_vrf_interface.yml:27
Using module file /usr/local/lib/python2.7/site-packages/ansible-2.3.0-py2.7.egg/ansible/modules/core/network/cloudengine/ce_vrf_interface.py
<ce_6850> ESTABLISH LOCAL CONNECTION FOR USER: root
<ce_6850> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1487054117.49-224243640103190 `" && echo ansible-tmp-1487054117.49-224243640103190="` echo $HOME/.ansible/tmp/ansible-tmp-1487054117.49-224243640103190 `" ) && sleep 0'
<ce_6850> PUT /tmp/tmpTdtehD TO /root/.ansible/tmp/ansible-tmp-1487054117.49-224243640103190/ce_vrf_interface.py
<ce_6850> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1487054117.49-224243640103190/ /root/.ansible/tmp/ansible-tmp-1487054117.49-224243640103190/ce_vrf_interface.py && sleep 0'
<ce_6850> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1487054117.49-224243640103190/ce_vrf_interface.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1487054117.49-224243640103190/" > /dev/null 2>&1 && sleep 0'
changed: [ce_6850] => {
    "changed": true, 
    "end_state": {
        "vpn_interface": "40GE1/0/5", 
        "vrf": "jss"
    }, 
    "existing": {
        "vpn_interface": "40GE1/0/5", 
        "vrf": null
    }, 
    "invocation": {
        "module_args": {
            "auth_pass": null, 
            "authorize": false, 
            "host": "ce_6850", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 12345, 
            "provider": null, 
            "ssh_keyfile": null, 
            "state": "present", 
            "timeout": 10, 
            "transport": null, 
            "use_ssl": false, 
            "username": "rootDC", 
            "validate_certs": true, 
            "vpn_interface": "40GE1/0/5", 
            "vrf": "jss"
        }, 
        "module_name": "ce_vrf_interface"
    }, 
    "proposed": {
        "state": "present", 
        "vpn_interface": "40GE1/0/5", 
        "vrf": "jss"
    }, 
    "updates": [
        "ip binding vpn-instance jss"
    ]
}
```

2017-05-02 11:26 UTC, gundalow requested changes

2017-05-02 11:26 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_vrf_interface.py
> +            - VPN instance, the length of vrf name is 1 ~ 31,i.e. "test", but can not be _public_.
`VPN instance, the length of vrf name is 1 ~ 31, i.e. "test", but can not be C(_public_.)`

2017-05-02 11:26 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_vrf_interface.py
> +def get_interface_type(interface):
If this is needed by other modules it may be useful to move this into `module_utils`.

2017-05-02 11:26 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_vrf_interface.py
> +        if not self.vrf or not self.vpn_interface:
There are some options to `AnsibleModule` which you may be able to use to validate options passed in.
Look at existing modules for examples:
```
mutually_exclusive
required_together
required_one_of
require_if
```

2017-05-03 14:12 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_vrf_interface.py
> +            - VPN instance, the length of vrf name is 1 ~ 31,i.e. "test", but can not be _public_.
thank you. I'll fix it.

2017-05-03 14:18 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_vrf_interface.py
> +def get_interface_type(interface):
This is a good idea, and this will be refactored in the future.

2017-05-18 11:51 UTC, QijunPan commented
@gundalow   These problems have been fixed， can  this PR merged?

2017-05-18 22:11 UTC, merged