Contributing lib/ansible/modules/network/cloudengine/ce_vlan.py module to manage HUAWEI data center CloudEngine
ansible/ansible pull request #22076
Opened 2017-02-28 11:24 UTC by QijunPan

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

ce_vlan.py
##### ANSIBLE VERSION

```
ansible 2.3.0
config file = /etc/ansible/ansible.cfg
configured module search path = ['/home/ansible-2.1.1.0/lib/ansible/modules/core/network/cloudengine', '/home/ansible-2.1.1.0/lib/ansible/module_utils', '/home/ansible-2.1.1.0/lib/ansible/modules', '/home/ansible-2.1.1.0', '/home/ansible-2.1.1.0/lib/ansible/utils/']
```

##### SUMMARY

```
TASK [Ensure a range of VLANs are not present on the switch] *******************
task path: /usr1/code/OpenNESS/code/current/KVM/intg/test/testcases/test-ce_vlan.yml:18
Using module file /usr/local/lib/python2.7/site-packages/ansible-2.3.0-py2.7.egg/ansible/modules/core/network/cloudengine/ce_vlan.py
<ce_6850> ESTABLISH LOCAL CONNECTION FOR USER: root
<ce_6850> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1487053996.61-725734869023 `" && echo ansible-tmp-1487053996.61-725734869023="` echo $HOME/.ansible/tmp/ansible-tmp-1487053996.61-725734869023 `" ) && sleep 0'
<ce_6850> PUT /tmp/tmpHC0oJF TO /root/.ansible/tmp/ansible-tmp-1487053996.61-725734869023/ce_vlan.py
<ce_6850> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1487053996.61-725734869023/ /root/.ansible/tmp/ansible-tmp-1487053996.61-725734869023/ce_vlan.py && sleep 0'
<ce_6850> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1487053996.61-725734869023/ce_vlan.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1487053996.61-725734869023/" > /dev/null 2>&1 && sleep 0'
changed: [ce_6850] => {
    "changed": true, 
    "end_state": null, 
    "end_state_vlans_list": [
        "1", 
        "20", 
        "21"
    ], 
    "existing": null, 
    "existing_vlans_list": [
        "1"
    ], 
    "invocation": {
        "module_args": {
            "auth_pass": null, 
            "authorize": false, 
            "description": null, 
            "host": "ce_6850", 
            "name": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 12345, 
            "provider": null, 
            "ssh_keyfile": null, 
            "state": "present", 
            "timeout": 10, 
            "transport": null, 
            "use_ssl": false, 
            "username": "rootDC", 
            "validate_certs": true, 
            "vlan_id": null, 
            "vlan_range": "20-21"
        }, 
        "module_name": "ce_vlan"
    }, 
    "proposed": null, 
    "proposed_vlans_list": [
        "1", 
        "20", 
        "21"
    ], 
    "updates": [
        "vlan batch 20 to 21"
    ]
}
```

2017-05-02 11:50 UTC, gundalow requested changes

2017-05-02 11:50 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_vlan.py
> +        if not self.vlan_id and not self.vlan_range:
There are some options to `AnsibleModule` which you may be able to use to validate options passed in.
Look at existing modules for examples:
```
mutually_exclusive
required_together
required_one_of
require_if
```

2017-05-02 11:50 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_vlan.py
> +        elif self.vlan_id and self.vlan_range:
There are some options to `AnsibleModule` which you may be able to use to validate options passed in.
Look at existing modules for examples:
```
mutually_exclusive
```

2017-05-02 11:50 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_vlan.py
> +        if not self.vlan_id and self.description:
There are some options to `AnsibleModule` which you may be able to use to validate options passed in.
Look at existing modules for examples:
```
mutually_exclusive
required_together
required_one_of
require_if
```

2017-05-02 11:50 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_vlan.py
> +        if not self.vlan_id and self.name:
There are some options to `AnsibleModule` which you may be able to use to validate options passed in.
Look at existing modules for examples:
```
mutually_exclusive
required_together
required_one_of
require_if
```

2017-05-02 11:50 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_vlan.py
> +        vlan_id=dict(required=False),
For integers please:
use `type='int`
remove the `isdigit` check from `check_params`

2017-05-02 11:50 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_vlan.py
> +            - Range of VLANs such as 2-10 or 2,5,10-15, etc.
`Range of VLANs such as C(2-10) or C(2,5,10-15), etc.`

2017-05-04 04:06 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_vlan.py
> +        vlan_id=dict(required=False),
Let's keep use type='str' to avoid conversion。

2017-05-04 07:29 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_vlan.py
> +        if not self.vlan_id and self.description:
@gundalow 
I'm try to use required_if,  like ```lib/ansible/modules/network/ovs/openvswitch_bridge.py```:
```
required_if = [('description', not None, ('vlan_id',)), ('name', not None, ('vlan_id',))]
```
But it is not work well?  How can i use ```required_if``` option to check: 
```if not self.vlan_id and self.description:```

2017-05-04 13:07 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_vlan.py
> +        if not self.vlan_id and self.description:
```
        module = AnsibleModule(
            argument_spec=dict(
                state=dict(default='present', choices=['present', 'absent']),
                username=dict(type='str'),
                password=dict(no_log=True),
                token=dict(no_log=True),
                src=dict(type='path'),
                priority=dict(type='int'),
            ),
            mutually_exclusive=(['password', 'token'],),
            required_together=(['username', 'password'],),
            required_one_of=[['password', 'token']],
            required_if=[('state', 'present', ['src', 'priority'])],
            supports_check_mode=True
        )```

`required_together` looks like it should work

2017-05-04 13:26 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_vlan.py
> +        if not self.vlan_id and self.description:
```
if not self.vlan_id and self.description:
```
mean ```description``` is  dependent on ```vlan_id```， but ```vlan_id``` is not dependent on ```description```. 
```required_together``` mean ```description``` and ```vlan_id``` always required at the same time, Actually ```description``` is not always required.

2017-05-18 11:52 UTC, QijunPan commented
@gundalow   These problems have been fixed， can  this PR merged?

2017-05-18 22:10 UTC, merged