Contributing lib/ansible/modules/network/cloudengine/ce_vrf.py module to manage HUAWEI data center CloudEngine
ansible/ansible pull request #22077
Opened 2017-02-28 11:26 UTC by QijunPan

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

ce_vrf.py
##### ANSIBLE VERSION

```
ansible 2.3.0
config file = /etc/ansible/ansible.cfg
configured module search path = ['/home/ansible-2.1.1.0/lib/ansible/modules/core/network/cloudengine', '/home/ansible-2.1.1.0/lib/ansible/module_utils', '/home/ansible-2.1.1.0/lib/ansible/modules', '/home/ansible-2.1.1.0', '/home/ansible-2.1.1.0/lib/ansible/utils/']
```

##### SUMMARY

```
TASK [Config a vpn named vpna, description is test] ****************************
task path: /usr1/code/OpenNESS/code/current/KVM/intg/test/testcases/test-ce_vrf.yml:15
Using module file /usr/local/lib/python2.7/site-packages/ansible-2.3.0-py2.7.egg/ansible/modules/core/network/cloudengine/ce_vrf.py
<ce_6850> ESTABLISH LOCAL CONNECTION FOR USER: root
<ce_6850> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1487054159.22-62399001042523 `" && echo ansible-tmp-1487054159.22-62399001042523="` echo $HOME/.ansible/tmp/ansible-tmp-1487054159.22-62399001042523 `" ) && sleep 0'
<ce_6850> PUT /tmp/tmpDHp21I TO /root/.ansible/tmp/ansible-tmp-1487054159.22-62399001042523/ce_vrf.py
<ce_6850> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1487054159.22-62399001042523/ /root/.ansible/tmp/ansible-tmp-1487054159.22-62399001042523/ce_vrf.py && sleep 0'
<ce_6850> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1487054159.22-62399001042523/ce_vrf.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1487054159.22-62399001042523/" > /dev/null 2>&1 && sleep 0'
changed: [ce_6850] => {
    "changed": true, 
    "end_state": {
        "description": "test", 
        "vrf": "vpna"
    }, 
    "existing": {}, 
    "invocation": {
        "module_args": {
            "auth_pass": null, 
            "authorize": false, 
            "description": "test", 
            "host": "ce_6850", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 12345, 
            "provider": null, 
            "ssh_keyfile": null, 
            "state": "present", 
            "timeout": 10, 
            "transport": null, 
            "use_ssl": false, 
            "username": "rootDC", 
            "validate_certs": true, 
            "vrf": "vpna"
        }, 
        "module_name": "ce_vrf"
    }, 
    "proposed": {
        "description": "test", 
        "state": "present", 
        "vrf": "vpna"
    }, 
    "updates": [
        "ip vpn-instance vpna", 
        "description test"
    ]
}
```

2017-05-02 11:43 UTC, gundalow requested changes

2017-05-02 11:43 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_vrf.py
> +            - VPN instance,the length of vrf name is 1 - 31,i.e. "test",but can not be _public_.
`VPN instance, the length of vrf name is 1 - 31, i.e. "test",but can not be C(_public_).`

2017-05-02 11:43 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_vrf.py
> +            - Description of the vrf,the string length is 1 - 242 .
Missing space between `vrf,` and `the`.

2017-05-02 11:43 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_vrf.py
> +        if not self.vrf:
Not needed as you have `required=True`

2017-05-02 11:43 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_vrf.py
> +    - If no vrf is supplied, vrf is set to default.
vtf has `required=True`, so they Playbook writer will always have to specify a vrf, so I'm not sure what this note means.

2017-05-02 11:43 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_vrf.py
> +      If state==absent, the route will be removed, regardless of the
`I(state=absent)`

2017-05-02 11:43 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_vrf.py
> +      non-required parameters.
`non-required options.`

2017-05-04 03:41 UTC, QijunPan commented
@gundalow  I had fix those issues, thanks.

2017-05-16 21:48 UTC, gundalow approved these changes

2017-05-16 21:48 UTC, merged