Contributing lib/ansible/modules/network/cloudengine/ce_vxlan_tunnel.py module to manage HUAWEI data center CloudEngine
ansible/ansible pull request #22083
Opened 2017-02-28 11:50 UTC by QijunPan

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

ce_vxlan_tunnel.py
##### ANSIBLE VERSION

```
ansible 2.3.0
config file = /etc/ansible/ansible.cfg
configured module search path = ['/home/ansible-2.1.1.0/lib/ansible/modules/core/network/cloudengine', '/home/ansible-2.1.1.0/lib/ansible/module_utils', '/home/ansible-2.1.1.0/lib/ansible/modules', '/home/ansible-2.1.1.0', '/home/ansible-2.1.1.0/lib/ansible/utils/']
```

##### SUMMARY

```
TASK [add vni_id and bridge_domain_id] *****************************************
task path: /usr1/code/OpenNESS/code/current/KVM/intg/test/testcases/test-ce_vxlan_tunnel.yml:36
Using module file /usr/local/lib/python2.7/site-packages/ansible-2.3.0-py2.7.egg/ansible/modules/core/network/cloudengine/ce_vxlan_tunnel.py
<ce_12800> ESTABLISH LOCAL CONNECTION FOR USER: root
<ce_12800> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1487054649.63-132024260408253 `" && echo ansible-tmp-1487054649.63-132024260408253="` echo $HOME/.ansible/tmp/ansible-tmp-1487054649.63-132024260408253 `" ) && sleep 0'
<ce_12800> PUT /tmp/tmpz_zEwe TO /root/.ansible/tmp/ansible-tmp-1487054649.63-132024260408253/ce_vxlan_tunnel.py
<ce_12800> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1487054649.63-132024260408253/ /root/.ansible/tmp/ansible-tmp-1487054649.63-132024260408253/ce_vxlan_tunnel.py && sleep 0'
<ce_12800> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1487054649.63-132024260408253/ce_vxlan_tunnel.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1487054649.63-132024260408253/" > /dev/null 2>&1 && sleep 0'
changed: [ce_12800] => {
    "changed": true, 
    "end_state": {
        "vni_to_bridge_domain": [
            {
                "bdId": "20", 
                "vniId": "1"
            }
        ]
    }, 
    "existing": {}, 
    "invocation": {
        "module_args": {
            "auth_pass": null, 
            "authorize": false, 
            "bridge_domain_id": "20", 
            "host": "ce_12800", 
            "nve_mode": null, 
            "nve_name": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "peer_list_ip": null, 
            "port": 12346, 
            "protocol_type": null, 
            "provider": null, 
            "source_ip": null, 
            "ssh_keyfile": null, 
            "state": "present", 
            "timeout": 10, 
            "transport": null, 
            "use_ssl": false, 
            "username": "root123", 
            "validate_certs": true, 
            "vni_id": "1"
        }, 
        "module_name": "ce_vxlan_tunnel"
    }, 
    "proposed": {
        "bridge_domain_id": "20", 
        "state": "present", 
        "vni_id": "1"
    }, 
    "updates": [
        "bridge-domain 20", 
        "vxlan vni 1"
    ]
}

```

2017-05-02 07:42 UTC, gundalow requested changes
I've added a note of the Core Team Agenda to see if we can add built in validation of int ranges and IP addresses as part of `argument_spec`

https://github.com/ansible/community/issues/159#issuecomment-298523500

2017-05-02 07:42 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_vxlan_tunnel.py
> +        bridge_domain_id=dict(required=False),
`type='int'`

2017-05-02 07:42 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_vxlan_tunnel.py
> +        vni_id=dict(required=False, type='str'),
`type='int'`

2017-05-02 07:42 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_vxlan_tunnel.py
> +        nve_name=dict(required=False, type='str'),
`type='int'`

2017-05-02 07:42 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_vxlan_tunnel.py
> +            if not self.bridge_domain_id.isdigit():
specifying `type='int'` removes the need for this, so you only need to check the range.

2017-05-02 07:42 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_vxlan_tunnel.py
> +            if not self.vni_id.isdigit():
specifying `type='int'` removes the need for this, so you only need to check the range.

2017-05-02 07:42 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_vxlan_tunnel.py
> +            mode = "mode-l2"
I'm not familiar with CE, though is this correct?
```
if mode == "mode-l3":
   ...
   mode = "mode-l2"
   ...
   self.updates_cmd.append("undo mode l3")
```

2017-05-02 07:42 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_vxlan_tunnel.py
> +                self.module.fail_json(msg='Error: The %s is not exist' % peer_ip)
Perhaps say `does not exist`?

2017-05-02 07:42 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_vxlan_tunnel.py
> +                    msg='Error: Error: Nve interface is invalid.')
Perhaps include the name of the NVE interface in the error message?
Also `Nve` or `NVE`?

2017-05-02 07:42 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_vxlan_tunnel.py
> +                        msg='Error: The %s exist invalid ip address' % self.peer_list_ip)
Perhaps: `Error: The %s exist, and is an invalid IP address`?

2017-05-03 13:00 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_vxlan_tunnel.py
> +            mode = "mode-l2"
Keep the string type and avoid the repeated conversion, thanks!

2017-05-03 13:00 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_vxlan_tunnel.py
> +            if not self.bridge_domain_id.isdigit():
Keep the string type and avoid the repeated conversion, thanks!

2017-05-03 13:00 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_vxlan_tunnel.py
> +            if not self.vni_id.isdigit():
Keep the string type and avoid the repeated conversion, thanks!

2017-05-03 13:05 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_vxlan_tunnel.py
> +                self.module.fail_json(msg='Error: The %s is not exist' % peer_ip)
yes, thank you. I'll fix it.

2017-05-03 13:06 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_vxlan_tunnel.py
> +        bridge_domain_id=dict(required=False),
Keep the string type and avoid the repeated conversion, thanks!

2017-05-03 13:06 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_vxlan_tunnel.py
> +        vni_id=dict(required=False, type='str'),
Keep the string type and avoid the repeated conversion, thanks!

2017-05-03 13:06 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_vxlan_tunnel.py
> +        nve_name=dict(required=False, type='str'),
Keep the string type and avoid the repeated conversion, thanks!

2017-05-03 13:24 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_vxlan_tunnel.py
> +            mode = "mode-l2"
This is correct, but easy to cause misunderstanding, I'll fix it. thank you.

2017-05-18 11:49 UTC, QijunPan commented
@gundalow   These problems have been fixed， can get this PR merged?

2017-05-19 07:21 UTC, gundalow approved these changes

2017-05-19 07:21 UTC, merged