Contributing lib/ansible/modules/network/cloudengine/ce_vxlan_global.py module to manage HUAWEI data center CloudEngine
ansible/ansible pull request #22082
Opened 2017-02-28 11:46 UTC by QijunPan

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

ce_vxlan_global.py
##### ANSIBLE VERSION

```
ansible 2.3.0
config file = /etc/ansible/ansible.cfg
configured module search path = ['/home/ansible-2.1.1.0/lib/ansible/modules/core/network/cloudengine', '/home/ansible-2.1.1.0/lib/ansible/module_utils', '/home/ansible-2.1.1.0/lib/ansible/modules', '/home/ansible-2.1.1.0', '/home/ansible-2.1.1.0/lib/ansible/utils/']
```

##### SUMMARY

```
TASK [create bd bdid1] *********************************************************
task path: /usr1/code/OpenNESS/code/current/KVM/intg/test/testcases/test-ce_vxlan_global.yml:27
Using module file /usr/local/lib/python2.7/site-packages/ansible-2.3.0-py2.7.egg/ansible/modules/core/network/cloudengine/ce_vxlan_global.py
<ce_12800> ESTABLISH LOCAL CONNECTION FOR USER: root
<ce_12800> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1487054580.59-270941695611808 `" && echo ansible-tmp-1487054580.59-270941695611808="` echo $HOME/.ansible/tmp/ansible-tmp-1487054580.59-270941695611808 `" ) && sleep 0'
<ce_12800> PUT /tmp/tmp8eYR9F TO /root/.ansible/tmp/ansible-tmp-1487054580.59-270941695611808/ce_vxlan_global.py
<ce_12800> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1487054580.59-270941695611808/ /root/.ansible/tmp/ansible-tmp-1487054580.59-270941695611808/ce_vxlan_global.py && sleep 0'
<ce_12800> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1487054580.59-270941695611808/ce_vxlan_global.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1487054580.59-270941695611808/" > /dev/null 2>&1 && sleep 0'
changed: [ce_12800] => {
    "changed": true, 
    "end_state": {
        "bridge_domain": [
            "1"
        ], 
        "nvo3_acl_extend": "enable", 
        "nvo3_ecmp_hash": "disable", 
        "nvo3_eth_trunk_hash": "disable", 
        "nvo3_gw_enhanced": null, 
        "nvo3_prevent_loops": "disable", 
        "nvo3_service_extend": "disable", 
        "tunnel_mode_vxlan": "enable"
    }, 
    "existing": {
        "bridge_domain": [], 
        "nvo3_acl_extend": "enable", 
        "nvo3_ecmp_hash": "disable", 
        "nvo3_eth_trunk_hash": "disable", 
        "nvo3_gw_enhanced": null, 
        "nvo3_prevent_loops": "disable", 
        "nvo3_service_extend": "disable", 
        "tunnel_mode_vxlan": "enable"
    }, 
    "invocation": {
        "module_args": {
            "auth_pass": null, 
            "authorize": false, 
            "bridge_domain_id": "1", 
            "host": "ce_12800", 
            "nvo3_acl_extend": null, 
            "nvo3_ecmp_hash": null, 
            "nvo3_eth_trunk_hash": null, 
            "nvo3_gw_enhanced": null, 
            "nvo3_prevent_loops": null, 
            "nvo3_service_extend": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 12346, 
            "provider": null, 
            "ssh_keyfile": null, 
            "state": "present", 
            "timeout": 10, 
            "transport": null, 
            "tunnel_mode_vxlan": null, 
            "use_ssl": false, 
            "username": "root123", 
            "validate_certs": true
        }, 
        "module_name": "ce_vxlan_global"
    }, 
    "proposed": {
        "bridge_domain_id": "1", 
        "state": "present"
    }, 
    "updates": [
        "bridge-domain 1"
    ]
}
```

2017-05-02 08:06 UTC, gundalow requested changes

2017-05-02 08:06 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_vxlan_global.py
> +    argument_spec = dict(
For integers please:
use `type='int`
remove the `isdigit` check from `check_params`

2017-05-03 13:33 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_vxlan_global.py
> +    argument_spec = dict(
Keep the string type to avoid the repeated conversion, thanks!

2017-05-18 11:50 UTC, QijunPan commented
@gundalow   These problems have been fixed， can  this PR merged?

2017-05-19 07:21 UTC, gundalow approved these changes

2017-05-19 07:21 UTC, merged