Contributing lib/ansible/modules/network/cloudengine/ce_vxlan_arp.py module to manage HUAWEI data center CloudEngine
ansible/ansible pull request #22080
Opened 2017-02-28 11:39 UTC by QijunPan

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

ce_vxlan_arp.py
##### ANSIBLE VERSION

```
ansible 2.3.0
config file = /etc/ansible/ansible.cfg
configured module search path = ['/home/ansible-2.1.1.0/lib/ansible/modules/core/network/cloudengine', '/home/ansible-2.1.1.0/lib/ansible/module_utils', '/home/ansible-2.1.1.0/lib/ansible/modules', '/home/ansible-2.1.1.0', '/home/ansible-2.1.1.0/lib/ansible/utils/']
```

##### SUMMARY

```

TASK [set evn bgp enable] ******************************************************
task path: /usr1/code/OpenNESS/code/current/KVM/intg/test/testcases/test-ce_vxlan_arp.yml:39
Using module file /usr/local/lib/python2.7/site-packages/ansible-2.3.0-py2.7.egg/ansible/modules/core/network/cloudengine/ce_vxlan_arp.py
<ce_12800> ESTABLISH LOCAL CONNECTION FOR USER: root
<ce_12800> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1487054230.86-225202508677991 `" && echo ansible-tmp-1487054230.86-225202508677991="` echo $HOME/.ansible/tmp/ansible-tmp-1487054230.86-225202508677991 `" ) && sleep 0'
<ce_12800> PUT /tmp/tmppGxPZU TO /root/.ansible/tmp/ansible-tmp-1487054230.86-225202508677991/ce_vxlan_arp.py
<ce_12800> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1487054230.86-225202508677991/ /root/.ansible/tmp/ansible-tmp-1487054230.86-225202508677991/ce_vxlan_arp.py && sleep 0'
<ce_12800> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1487054230.86-225202508677991/ce_vxlan_arp.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1487054230.86-225202508677991/" > /dev/null 2>&1 && sleep 0'
changed: [ce_12800] => {
    "changed": true, 
    "end_state": {
        "arp_suppress": "disable", 
        "evn_bgp": "enable", 
        "evn_peer_ip": null, 
        "evn_reflect_client": null, 
        "evn_server": "disable", 
        "evn_source_ip": null, 
        "host_collect_protocol": null
    }, 
    "existing": {
        "arp_suppress": "disable", 
        "evn_bgp": "disable", 
        "host_collect_protocol": null
    }, 
    "invocation": {
        "module_args": {
            "arp_collect_host": null, 
            "arp_suppress": null, 
            "auth_pass": null, 
            "authorize": false, 
            "bridge_domain_id": null, 
            "evn_bgp": "enable", 
            "evn_peer_ip": null, 
            "evn_reflect_client": null, 
            "evn_server": null, 
            "evn_source_ip": null, 
            "host": "ce_12800", 
            "host_collect_protocol": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 12346, 
            "provider": null, 
            "ssh_keyfile": null, 
            "state": "present", 
            "timeout": 10, 
            "transport": null, 
            "use_ssl": false, 
            "username": "root123", 
            "validate_certs": true, 
            "vbdif_name": null
        }, 
        "module_name": "ce_vxlan_arp"
    }, 
    "proposed": {
        "evn_bgp": "enable", 
        "state": "present"
    }, 
    "updates": [
        "evn bgp"
    ]
}
```

2017-05-02 08:12 UTC, gundalow requested changes

2017-05-02 08:12 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_vxlan_arp.py
> +    argument_spec = dict(
For integers please:
use `type='int`
remove the `isdigit` check from `check_params`

2017-05-02 08:12 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_vxlan_arp.py
> +            self.module.fail_json(msg="Error: Bridge domain is not exist.")
It might be worth including the bridgename in the error message.

2017-05-02 08:12 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_vxlan_arp.py
> +        # vbdif_name and arp_collect_host must set at the same time
There are some options to `AnsibleModule` which you may be able to use to validate options passed in.
Look at existing modules for examples:
```
mutually_exclusive
required_together
required_one_of
require_if
```

2017-05-03 13:46 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_vxlan_arp.py
> +    argument_spec = dict(
Let's keep the string type to avoid the repeated conversion, thanks!

2017-05-03 13:53 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_vxlan_arp.py
> +            self.module.fail_json(msg="Error: Bridge domain is not exist.")
yes,  I'll ifx it.

2017-05-03 14:02 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_vxlan_arp.py
> +        # vbdif_name and arp_collect_host must set at the same time
OK, thank you.

2017-05-18 11:51 UTC, QijunPan commented
@gundalow   These problems have been fixed， can  this PR merged?

2017-05-18 22:11 UTC, merged