Contributing lib/ansible/modules/network/cloudengine/ce_vxlan_gateway.py module to manage HUAWEI data center CloudEngine
ansible/ansible pull request #22081
Opened 2017-02-28 11:42 UTC by QijunPan

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

ce_vxlan_gateway.py
##### ANSIBLE VERSION

```
ansible 2.3.0
config file = /etc/ansible/ansible.cfg
configured module search path = ['/home/ansible-2.1.1.0/lib/ansible/modules/core/network/cloudengine', '/home/ansible-2.1.1.0/lib/ansible/module_utils', '/home/ansible-2.1.1.0/lib/ansible/modules', '/home/ansible-2.1.1.0', '/home/ansible-2.1.1.0/lib/ansible/utils/']
```

##### SUMMARY

```
TASK [create dfs-group] ********************************************************
task path: /usr1/code/OpenNESS/code/current/KVM/intg/test/testcases/test-ce_vxlan_gateway.yml:50
Using module file /usr/local/lib/python2.7/site-packages/ansible-2.3.0-py2.7.egg/ansible/modules/core/network/cloudengine/ce_vxlan_gateway.py
<ce_12800> ESTABLISH LOCAL CONNECTION FOR USER: root
<ce_12800> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1487054527.58-93814235766625 `" && echo ansible-tmp-1487054527.58-93814235766625="` echo $HOME/.ansible/tmp/ansible-tmp-1487054527.58-93814235766625 `" ) && sleep 0'
<ce_12800> PUT /tmp/tmpN1Vu8M TO /root/.ansible/tmp/ansible-tmp-1487054527.58-93814235766625/ce_vxlan_gateway.py
<ce_12800> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1487054527.58-93814235766625/ /root/.ansible/tmp/ansible-tmp-1487054527.58-93814235766625/ce_vxlan_gateway.py && sleep 0'
<ce_12800> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1487054527.58-93814235766625/ce_vxlan_gateway.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1487054527.58-93814235766625/" > /dev/null 2>&1 && sleep 0'
changed: [ce_12800] => {
    "changed": true, 
    "end_state": {
        "dfs_all_active": "disable", 
        "dfs_id": "1", 
        "dfs_source_ip": null, 
        "dfs_source_vpn": null, 
        "dfs_udp_port": null
    }, 
    "existing": {}, 
    "invocation": {
        "module_args": {
            "arp_direct_route": null, 
            "arp_distribute_gateway": null, 
            "auth_pass": null, 
            "authorize": false, 
            "dfs_all_active": null, 
            "dfs_id": "1", 
            "dfs_peer_ip": null, 
            "dfs_peer_vpn": null, 
            "dfs_source_ip": null, 
            "dfs_source_vpn": null, 
            "dfs_udp_port": null, 
            "host": "ce_12800", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 12346, 
            "provider": null, 
            "ssh_keyfile": null, 
            "state": "present", 
            "timeout": 10, 
            "transport": null, 
            "use_ssl": false, 
            "username": "root123", 
            "validate_certs": true, 
            "vbdif_bind_vpn": null, 
            "vbdif_mac": null, 
            "vbdif_name": null, 
            "vpn_instance": null, 
            "vpn_vni": null
        }, 
        "module_name": "ce_vxlan_gateway"
    }, 
    "proposed": {
        "dfs_all_active": null, 
        "dfs_id": "1", 
        "dfs_peer_ip": null, 
        "dfs_peer_vpn": null, 
        "dfs_source_ip": null, 
        "dfs_source_vpn": null, 
        "dfs_udp_port": null, 
        "state": "present"
    }, 
    "updates": [
        "dfs-group 1"
    ]
}
```

2017-05-02 08:10 UTC, gundalow requested changes

2017-05-02 08:10 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_vxlan_gateway.py
> +    argument_spec = dict(
For integers please:
use `type='int`
remove the `isdigit` check from `check_params`

2017-05-02 08:10 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_vxlan_gateway.py
> +              The value _public_ is reserved and cannot be used as the VPN instance name.
`The value C( _public_) is...`

2017-05-02 08:10 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_vxlan_gateway.py
> +              The value _public_ is reserved and cannot be used as the VPN instance name.
`The value C( _public_) is...`

2017-05-02 08:10 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_vxlan_gateway.py
> +              The value _public_ is reserved and cannot be used as the VPN instance name.
`The value C( _public_) is...`

2017-05-02 08:10 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_vxlan_gateway.py
> +              The value _public_ is reserved and cannot be used as the VPN instance name.
`The value C( _public_) is...`

2017-05-02 08:10 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_vxlan_gateway.py
> +              The value is in the format of H-H-H. Each H is a 4-digit hexadecimal number, such as 00e0 or fc01.
`C(00e0) or C(fc01).`

2017-05-02 08:10 UTC, gundalow commented on lib/ansible/modules/network/cloudengine/ce_vxlan_gateway.py
> +              If an H contains less than four digits, 0s are added ahead. For example, e0 is equal to 00e0.
`C(e0) is equal to C(00e0)`

2017-05-03 13:42 UTC, QijunPan commented on lib/ansible/modules/network/cloudengine/ce_vxlan_gateway.py
> +    argument_spec = dict(
Keep the string type to avoid the repeated conversion, thanks!

2017-05-18 11:51 UTC, QijunPan commented
@gundalow   These problems have been fixed， can  this PR merged?

2017-05-18 22:12 UTC, merged