Add update_only parameter for yum module
ansible/ansible pull request #22206
Opened 2017-03-02 17:06 UTC by SteveHNH

When using latest, `update_only: yes` will ensure that only existing
packages are updated and no additional packages are installed.

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

`ansible/lib/ansible/modules/packaging/os/yum.py`

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/sadams/code/ansible/lib/ansible/modules']
```

##### SUMMARY

Adding an `update_only` boolean parameter to the yum module. Affects the module only when using `state: latest.`  
The idea being that if you run across systems where you do not want the package installed, you can specify that the package should only be updated if it already exists.
```
yum:
  name: httpd
  state: latest
  update_only: yes
```

Both tests performed with httpd NOT installed on the machine.  
**Before**
```
➔ ansible -m yum -a "name=httpd state=latest" rhel7 --become 
192.168.33.10 | SUCCESS => {
    "changed": true, 
    "msg": "", 
    "rc": 0, 
    "results": [
        "Loaded plugins: product-id, search-disabled-repos, subscription-manager\nResolving Dependencies\n--> Running transaction check\n---> Package httpd.x86_64 0:2.4.6-45.el7 will be installed\n--> Processing Dependency: httpd-tools = 2.4.6-45.el7 for package: httpd-2.4.6-45.el7.x86_64\n--> Running transaction check\n---> Package httpd-tools.x86_64 0:2.4.6-45.el7 will be installed\n--> Finished Dependency Resolution\n\nDependencies Resolved\n\n================================================================================\n Package          Arch        Version             Repository               Size\n================================================================================\nInstalling:\n httpd            x86_64      2.4.6-45.el7        rhel-7-server-rpms      1.2 M\nInstalling for dependencies:\n httpd-tools      x86_64      2.4.6-45.el7        rhel-7-server-rpms       84 k\n\nTransaction Summary\n================================================================================\nInstall  1 Package (+1 Dependent package)\n\nTotal download size: 1.3 M\nInstalled size: 3.9 M\nDownloading packages:\n--------------------------------------------------------------------------------\nTotal                                              1.7 MB/s | 1.3 MB  00:00     \nRunning transaction check\nRunning transaction test\nTransaction test succeeded\nRunning transaction\n  Installing : httpd-tools-2.4.6-45.el7.x86_64                              1/2 \n  Installing : httpd-2.4.6-45.el7.x86_64                                    2/2 \n  Verifying  : httpd-tools-2.4.6-45.el7.x86_64                              1/2 \n  Verifying  : httpd-2.4.6-45.el7.x86_64                                    2/2 \n\nInstalled:\n  httpd.x86_64 0:2.4.6-45.el7                                                   \n\nDependency Installed:\n  httpd-tools.x86_64 0:2.4.6-45.el7                                             \n\nComplete!\n"
    ]
}
```  
**After**
```
➔ ansible -m yum -a "name=httpd state=latest update_only=yes" rhel7 --become
192.168.33.10 | SUCCESS => {
    "changed": false, 
    "msg": "", 
    "rc": 0, 
    "results": [
        "Packages providing httpd not installed due to update_only specified", 
        ""
    ]
}
```

2017-09-25 16:43 UTC, mkrizek requested changes

2017-09-25 16:43 UTC, mkrizek commented on lib/ansible/modules/packaging/os/yum.py
> +    version_added: "2.4"
Can you change this to `2.5`?

2017-09-25 18:07 UTC, SteveHNH commented
@mkrizek Version_added updated. Thanks!

2017-09-25 19:22 UTC, mkrizek commented
@SteveHNH Actually, would you mind adding a couple of integration tests for this feature? I think that adding the task you mentioned in the PR description would do.

2017-10-02 17:26 UTC, SteveHNH commented
@mkrizek I can take care of it! Will push update this PR soon

2017-10-03 15:45 UTC, SteveHNH commented
@mkrizek added the requested tests.  Let me know if there is anything else I need to do

2017-10-04 08:24 UTC, mkrizek approved these changes

2017-10-04 08:25 UTC, merged

2017-10-04 08:25 UTC, mkrizek commented
Thanks @SteveHNH!