New module to setup cloud connector properties
ansible/ansible pull request #22225
Opened 2017-03-03 02:25 UTC by grastogi23

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

avi.avi_cloudconnectoruser

##### ANSIBLE VERSION

```
ansible 2.3.0
  config file = /home/grastogi/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY

New module to setup cloud connector properties.

```

```

2017-03-03 03:24 UTC, khaltore commented
shipit

2017-03-07 18:26 UTC, ericsysmin commented
shipit

2017-05-03 21:07 UTC, ericsysmin commented
shipit

2017-05-03 21:24 UTC, khaltore commented
shipit

2017-05-04 11:26 UTC, gundalow commented
Closing and reopening to retrigger CI as we've extended module validation rules.

2017-05-04 12:26 UTC, gundalow requested changes

2017-05-04 12:26 UTC, gundalow commented on lib/ansible/modules/network/avi/avi_cloudconnectoruser.py
> +        private_key=dict(type='str',),
I wonder if this (and any other instance of `private_key`) should have `no_log=true`

I might have missed this in some other PRs, so feel free to raise one PR that updates all the modules.

2017-05-04 18:02 UTC, grastogi23 commented
Sure, let me scrub all of them. I did take care of those in sslkeycertificate before.

2017-05-08 06:40 UTC, merged

2017-05-08 06:44 UTC, gundalow commented
I believe that's all the Avi modules merged. You are now free to raise a single PR that updates all modules for any improvements, such as:
* Use of `no_log`correct private keys 
* Formatting in DOCUMENTION block