wildfly module for domain mode deployment
ansible/ansible pull request #22294
Opened 2017-03-05 08:45 UTC by adityacs

##### ISSUE TYPE

 New Module Pull Request

##### COMPONENT NAME
web_infrastructure/wildfly

##### ANSIBLE VERSION

```
2.1.0
```

##### SUMMARY
This is a wildfly module with domain deployment capability developed by using HTTP Management API.

2017-03-07 19:39 UTC, bcoca commented
we are currently in freeze, so this will probably wait until 2.4

2017-03-07 20:03 UTC, adityacs commented
@bcoca sure

2017-04-14 09:41 UTC, adityacs commented
@bcoca Can this be merged for 2.4 release?

2017-04-17 19:09 UTC, bcoca commented
it can, you just need 2 "shipit's" from maintainers

2017-04-17 19:49 UTC, adityacs commented
@Slezhuk @inetfuture @jhoekx @jtyr @lekum @mattupstate @mgruener @n0trax @oboukili @ramondelafuente @robinro @scottanderson42 @sermilrod @tarka @tastychutney

Requesting to review this PR and approve.

2017-04-18 07:20 UTC, Slezhuk commented
@adityacs , can you rebase your PR to 1 commit, to keep history clean?

2017-04-18 09:28 UTC, jtyr requested changes
I went through the code and pointed out just few major issues. I have also noticed that this module has no `check_mode`. Every module should have it unless you have a very good reason why not.

2017-04-18 09:28 UTC, jtyr commented on lib/ansible/modules/web_infrastructure/wildfly.py
> +DOCUMENTATION = \
The `DOCUMENTATION` block should start like this:

```
DOCUMENTATION = """
---
module: wildfly
...
```

2017-04-18 09:28 UTC, jtyr commented on lib/ansible/modules/web_infrastructure/wildfly.py
> +ANSIBLE_METADATA = {'status': ['preview'], 'supported_by': 'community',
I would format this like this:

```
ANSIBLE_METADATA = {
  'status': ['preview'],
  'supported_by': 'community',
  'metadata_version': '1.0'
}
```

2017-04-18 09:28 UTC, jtyr commented on lib/ansible/modules/web_infrastructure/wildfly.py
> +    default: "present"
The value should not be quoted.

2017-04-18 09:28 UTC, jtyr commented on lib/ansible/modules/web_infrastructure/wildfly.py
> +notes:
You can remove this line if there are no notes.

2017-04-18 09:28 UTC, jtyr commented on lib/ansible/modules/web_infrastructure/wildfly.py
> +EXAMPLES = \
The same like in the case of `DOCUMENTATION` block.

2017-04-18 09:28 UTC, jtyr commented on lib/ansible/modules/web_infrastructure/wildfly.py
> +# Deploy a hello world application
What about to turn comments into the task names?

```
- name: Deploy a hello world application
  wildfly:
    src: /tmp/hello-1.0-SNAPSHOT.war
    ...
```

2017-04-18 09:28 UTC, jtyr commented on lib/ansible/modules/web_infrastructure/wildfly.py
> +RETURN = \
The same like in the case of `DOCUMENTATION` block.

2017-04-18 09:28 UTC, jtyr commented on lib/ansible/modules/web_infrastructure/wildfly.py
> +    global module, mode, changed, username, password, controller_address
I don't like this. You should pass the `module.params` to the functions instead of making variables global.

2017-04-18 09:28 UTC, jtyr commented on lib/ansible/modules/web_infrastructure/wildfly.py
> +        # Let snippet from module_utils/basic.py return a proper error in this
You should use something like this:

```
HAS_JSON = True

try:
    import json
except ImportError:
    try:
        import simplejson as json
    except ImportError:
      HAS_JSON = False
```

And then in the `main()` display proper message if the package wasn't found:

```
if not HAS_JSON:
  module.fail_json(msg='Cannot import JSON package.')
```

2017-04-18 09:28 UTC, jtyr commented on lib/ansible/modules/web_infrastructure/wildfly.py
> +    else:
This is never evaluated as the `state` is always set.

2017-04-18 09:28 UTC, jtyr commented on lib/ansible/modules/web_infrastructure/wildfly.py
> +        module.fail_json(msg='Missing Configurations', stdout='',
You should not use `stdout` and `stderror` if you use `msg`.

2017-04-18 09:28 UTC, jtyr commented on lib/ansible/modules/web_infrastructure/wildfly.py
> +    deployment = '{}'.format(deployment)
Why are you formatting the variable? The same in many places in the code below. Is the reason that you want to have it as `string`? In that case, you can define `type='str'` in the `argument_spec` to enforce that type.

2017-04-18 09:28 UTC, jtyr commented on lib/ansible/modules/web_infrastructure/wildfly.py
> +        response = open_url(
You should use [`fetch_url`](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/urls.py#L993) instead which encapsulates the `open_url`. That gives you the ability to use other standard parameters like `url_username`, `url_password`, `force_basic_auth`, ... without the need to define it in your code.

2017-04-18 09:28 UTC, jtyr commented on lib/ansible/modules/web_infrastructure/wildfly.py
> +            deploy_enable(result, deployment, server_groups, src)
Functions should return the `changed` value:

```
changed = deploy_enable(...)
```

2017-04-18 09:28 UTC, jtyr commented on lib/ansible/modules/web_infrastructure/wildfly.py
> +        if 'outcome' in result:
What if there is no `outcome` in the results? You show no error message?

2017-04-18 09:28 UTC, jtyr commented on lib/ansible/modules/web_infrastructure/wildfly.py
> +                module.exit_json(changed=True, stdout='deployed',
I would rather use the `exit_json` in the `main()` function.

2017-04-18 09:28 UTC, jtyr commented on lib/ansible/modules/web_infrastructure/wildfly.py
> +      - The http api management address
`http` should be `HTTP` and `api` should be `API`. The sentence should end with a period. The same in any other `description` in the `DOCUMENTATION` block.

2017-04-18 09:28 UTC, jtyr commented on lib/ansible/modules/web_infrastructure/wildfly.py
> +short_description: deploy applications to Wildfly
First letter should be capital and the sentence should end with a period.

2017-04-18 09:28 UTC, jtyr commented on lib/ansible/modules/web_infrastructure/wildfly.py
> +# (c) 2016, Aditya C S <aditya.gnu@gmail.com>
Your full name should be used.

2017-04-18 09:28 UTC, jtyr commented on lib/ansible/modules/web_infrastructure/wildfly.py
> +author: "Aditya C S"
Your full name should be used.

2017-04-18 12:04 UTC, adityacs commented
@jtyr Thanks for the review. I will make the changes and commit again. 
Also, how to enable` check_mode`? Could you please give me some code reference to this? so that I can refer and implement.

2017-04-18 12:36 UTC, jtyr commented
Search for `check_mode` in any module (e.g. [yum_repository](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/os/yum_repository.py) or [jenkins_plugin](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/web_infrastructure/jenkins_plugin.py))

2017-04-20 09:16 UTC, jtyr requested changes

2017-04-20 09:16 UTC, jtyr commented on lib/ansible/modules/web_infrastructure/wildfly.py
> +  'status': ['preview'],
This should be indented by 4 spaces as it's Python code not YAML.

2017-04-20 09:16 UTC, jtyr commented on lib/ansible/modules/web_infrastructure/wildfly.py
> +from ansible.module_utils.urls import *
I would prefer explicit imports.

2017-04-20 09:16 UTC, jtyr commented on lib/ansible/modules/web_infrastructure/wildfly.py
> +    remove_content = \
Format this like this:

```
remove_content = {
    'operation': 'remove',
    'address': [
        {'deployment': deployment}
    ],
    'json.pretty': 1
}
```

The same anywhere else where you are using ` = \`.

2017-04-20 09:16 UTC, jtyr commented on lib/ansible/modules/web_infrastructure/wildfly.py
> +            if info['status'] != 200:
This is never evaluated because you are already in the branch which matches `info['status'] == 200` only.

2017-04-20 09:16 UTC, jtyr commented on lib/ansible/modules/web_infrastructure/wildfly.py
> +            else:
This is never evaluated because you are already in the branch which matches `info['status'] == 200` only.

2017-04-20 09:16 UTC, jtyr commented on lib/ansible/modules/web_infrastructure/wildfly.py
> +            response_add_content_server_group, info = \
Format this like this:

```
response_add_content_server_group, info = get_response(
    add_content_server_group)
```

2017-04-20 09:16 UTC, jtyr commented on lib/ansible/modules/web_infrastructure/wildfly.py
> +        module.fail_json(msg='Error while performing wildfly operation',
Format this like this:

```
module.fail_json(
    msg='Error while performing wildfly operation', details=info['msg'])
```

The same anywhere else in the code.

2017-04-20 09:16 UTC, jtyr commented on lib/ansible/modules/web_infrastructure/wildfly.py
> +                else:
This is never evaluated. The same reason like I mentioned above.

2017-04-20 09:16 UTC, jtyr commented on lib/ansible/modules/web_infrastructure/wildfly.py
> +    global module
If possible, do not use global variables. Pass the module to the function as a parameter if needed.

2017-04-20 09:16 UTC, jtyr commented on lib/ansible/modules/web_infrastructure/wildfly.py
> +                module.exit_json(changed=changed, state='Nothing to undeploy',
`Nothing to undeploy` nor `undeployed` are not valid states. You should use only `state` here.

2017-04-20 12:37 UTC, adityacs commented on lib/ansible/modules/web_infrastructure/wildfly.py
> +            if info['status'] != 200:
info get new value here

2017-04-20 12:52 UTC, adityacs commented on lib/ansible/modules/web_infrastructure/wildfly.py
> +                else:
info gets new value

2017-04-20 13:38 UTC, jtyr requested changes

2017-04-20 13:38 UTC, jtyr commented on lib/ansible/modules/web_infrastructure/wildfly.py
> +# Deploy a hello world application
Do we still need these comments here? Isn't the task name enough?

2017-04-20 13:38 UTC, jtyr commented on lib/ansible/modules/web_infrastructure/wildfly.py
> +
You can delete this empty line.

2017-04-20 13:38 UTC, jtyr commented on lib/ansible/modules/web_infrastructure/wildfly.py
> +        module.fail_json(msg='Wildfly operation failed', details=info['body'])
There should be period at the end of the `msg`. Check the other occurrences.

2017-04-20 13:38 UTC, jtyr commented on lib/ansible/modules/web_infrastructure/wildfly.py
> +RETURN = '''
Use `"""` to unify it with the other blocks above.

2017-04-20 13:50 UTC, jtyr requested changes

2017-04-20 13:50 UTC, jtyr commented on lib/ansible/modules/web_infrastructure/wildfly.py
> +author: "Aditya Cheelangi Sreedharamurthy"
This should not be quoted.

2017-04-20 13:50 UTC, jtyr commented on lib/ansible/modules/web_infrastructure/wildfly.py
> +    description: Domain mode or standalone mode
Missing period.

2017-04-20 13:50 UTC, jtyr commented on lib/ansible/modules/web_infrastructure/wildfly.py
> +    description: Server groups to deploy the war.
The value should be as list like in all cases above.

2017-04-20 13:50 UTC, jtyr commented on lib/ansible/modules/web_infrastructure/wildfly.py
> +                changed=changed, status='deployed', name=deployment)
You are not returning `state` in any of the `exit_json`. You should drop the `status` as that can be determined from the `state` and the `changed` values.

2017-04-20 14:21 UTC, jtyr commented on lib/ansible/modules/web_infrastructure/wildfly.py
> +                    changed=changed, name=deployment)
Is the `state` added automatically that you did not add it here?

2017-04-20 14:21 UTC, adityacs commented on lib/ansible/modules/web_infrastructure/wildfly.py
> +                    changed=changed, name=deployment)
I am not returning state anymore.

2017-04-20 14:22 UTC, adityacs commented on lib/ansible/modules/web_infrastructure/wildfly.py
> +                    changed=changed, name=deployment)
"changed" should tell about the state

2017-04-20 14:27 UTC, jtyr commented on lib/ansible/modules/web_infrastructure/wildfly.py
> +                    changed=changed, name=deployment)
Well, how do you determine which action was just run if you only return `changed`? The `state` is standard key which is expected to be return by any module. Please add it (`state=state`).

2017-04-20 14:31 UTC, adityacs commented on lib/ansible/modules/web_infrastructure/wildfly.py
> +                    changed=changed, name=deployment)
Sure.

2017-04-20 14:57 UTC, adityacs commented
@jtyr Hope the code looks good now. Thanks for the review. Learnt a lot from this review.
Requesting you to approve for merge.

2017-04-20 15:00 UTC, jtyr commented on lib/ansible/modules/web_infrastructure/wildfly.py
> +- name: Undeploy an application in domain mode
I would insert an empty line in front of every example to separate it a bit.

2017-04-20 15:01 UTC, jtyr commented
The code looks OK now but I did not test it. If you provide a playbook, I'm willing to test it.

2017-04-20 15:08 UTC, adityacs commented
@jtyr Here is the sample playbook

```
---
 - hosts: localhost
   become: true
   tasks:
    - name: Deploy sample.war
      wildfly: deployment="sample.war" src="/home/aditya/Downloads/sample.war" state=absent username="admin" password="admin" mode=domain controller_address=http://localhost:9990 server_groups=all-relevant-server-groups
      register: deployment
      check_mode: false

    - name: debug
      debug: msg="{{ deployment.state }}"

```

2017-04-20 15:11 UTC, adityacs commented
@jtyr You can test both domain and standalone modes.
Start wildfly with.
"./domains.sh" for domain mode
"./standalone.sh" for standalone mode

2017-04-20 15:21 UTC, jtyr commented
I meant a playbook which will install Wildfly as well ;o)

2017-04-20 15:35 UTC, adityacs commented
@jtyr This should work
[https://github.com/inkatze/wildfly](url)

2017-04-21 09:41 UTC, adityacs commented
@jtyr Were you able to test this?

2017-04-21 17:18 UTC, adityacs commented
@jtyr Let me know if you need any help. I am waiting for you on this.

2017-04-25 09:07 UTC, adityacs commented
@jtyr Waiting for your update.

2017-05-03 16:24 UTC, adityacs commented
@jtyr @Slezhuk Any updates?

2017-05-13 20:21 UTC, adityacs commented
@Slezhuk @inetfuture @jhoekx @jtyr @lekum @mattupstate @mgruener @n0trax @oboukili @ramondelafuente @robinro @scottanderson42 @sermilrod @tarka @tastychutney

Kindly requesting for update.

2017-06-25 18:55 UTC, adityacs commented
@Slezhuk @inetfuture @jhoekx @jtyr @lekum @mattupstate @mgruener @n0trax @oboukili @ramondelafuente @robinro @scottanderson42 @sermilrod @tarka @tastychutney

Kindly update on this PR.

2017-10-20 13:59 UTC, angystardust commented
i'm wondering if it will be possible to modify this module so it can also work for deploying webapps on a tomcat instance...

2018-06-29 17:37 UTC, closed without merging