[WIP Stricter module documentation validation
ansible/ansible pull request #22353
Opened 2017-03-07 10:11 UTC by gundalow

##### ISSUE TYPE
 - Bugfix Pull Request

##### SUMMARY
Updated Validation and docs
Used to find https://github.com/ansible/ansible/pull/22297/files

Todo
* Recursive subspec
* Update docs
* Other fixme's as defined in code

2017-03-12 20:14 UTC, gundalow commented
ready_for_review

2017-03-13 18:18 UTC, mattclay requested changes
Looks good overall. Just one suggested change for adding deprecation notices.

2017-03-13 18:18 UTC, mattclay commented on docs/docsite/rst/dev_guide/developing_modules_checklist.rst
> +3) Add the deprecation to CHANGELOG.md
Specify where the deprecation notice goes. We have a `###Deprecations:` section in `CHANGELOG.md` for this.

2017-03-13 19:26 UTC, gundalow commented on docs/docsite/rst/dev_guide/developing_modules_checklist.rst
> +3) Add the deprecation to CHANGELOG.md
Good idea, done

2017-03-13 19:26 UTC, gundalow commented
ready_for_review

2017-03-13 19:31 UTC, mattclay approved these changes

2017-03-13 19:49 UTC, merged