ec2_elb_facts: Handle AWS throttling when requesting ELB information
ansible/ansible pull request #22383
Opened 2017-03-07 22:42 UTC by bobobox

##### SUMMARY
Fixes issue where module would fail immediately upon encountering AWS API throttling.
Also makes minor changes to error handling.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
ec2_elb_facts.py

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file =
  configured module search path = Default w/o overrides
```

##### ADDITIONAL INFORMATION
Uses the `AWSRetry.backoff` method both as a decorator and, where more efficient, directly as a wrapper function to  handle AWS API throttling for boto methods invoked in the module. 

Various instances of `BotoServerError` exceptions being caught and handled simply by invoking the  `fail_json` method have been removed, and replaced with a similar try/catch block in the `main` function. I'm not sure that that exception handling was particularly useful in the first place (and I'd be open to removing it completely), but  moving it into `main` at least provides pretty much the same behavior without interfering with use of the `AWSRetry` decorator, which catches specific cases of `BotoServerError`.

Also, removes questionable 'catch-all' clause on line 111 which would return an empty dict for tags.

2017-03-08 13:29 UTC, gundalow requested changes

2017-03-08 13:29 UTC, gundalow commented on lib/ansible/modules/cloud/amazon/ec2_elb_facts.py
> +from ansible.module_utils.basic import *
Please import what you need rather than `*`

http://docs.ansible.com/ansible/dev_guide/developing_modules_documenting.html#python-imports

2017-03-08 13:30 UTC, gundalow commented
If this can get reviewed by the maintainers within the week we can look at getting this into the 2.3 release.

2017-03-08 13:31 UTC, gundalow commented on lib/ansible/modules/cloud/amazon/ec2_elb_facts.py
> +from ansible.module_utils.basic import *
Ah, I see you've just moved the code to satisfy CI, rather than these been new imports. If you could fix this it would be great.

2017-03-08 14:45 UTC, mjschultz commented
shipit

2017-03-08 15:29 UTC, mjschultz commented on lib/ansible/modules/cloud/amazon/ec2_elb_facts.py
> +from ansible.module_utils.basic import *
I fixed them in https://github.com/ansible/ansible/pull/22415 which I can fix up once this is merged in.

2017-03-08 16:53 UTC, bobobox commented
I merged @mjschultz's fixes to address @gundalow's request.

2017-03-08 17:02 UTC, bobobox commented on lib/ansible/modules/cloud/amazon/ec2_elb_facts.py
> +from ansible.module_utils.basic import *
I merged @mjschultz's fixes to address @gundalow's request.

2017-03-08 19:31 UTC, s-hertel commented
shipit

2017-03-09 00:34 UTC, willthames requested changes

2017-03-09 00:34 UTC, willthames commented on lib/ansible/modules/cloud/amazon/ec2_elb_facts.py
> +        self.module.fail_json(msg="{}: {}".format(err.error_code, err.error_message),
This will fail on python 2.6

2017-03-09 00:34 UTC, willthames commented on lib/ansible/modules/cloud/amazon/ec2_elb_facts.py
> +from ansible.module_utils.ec2 import (
Just put this on one line (or two if needed for line lengths)
```
from a.b.c import x, y, z
from a.b.c import u, v, w
```

2017-03-09 16:46 UTC, bobobox commented on lib/ansible/modules/cloud/amazon/ec2_elb_facts.py
> +from ansible.module_utils.ec2 import (
Is there an established Ansible style that says this should be kept on one line? (honest question, I am new to the codebase)
In general I prefer putting things like this into multiple lines as it's a lot clearer later on in diffs when elements are added or removed, and overall just easier (IMO) to read.

2017-03-09 16:49 UTC, bobobox commented on lib/ansible/modules/cloud/amazon/ec2_elb_facts.py
> +        self.module.fail_json(msg="{}: {}".format(err.error_code, err.error_message),
Thanks. Fixed in 189eb0f42

2017-03-09 18:23 UTC, bobobox commented
@gundalow - could you approve your requested changes? Thanks :)

2017-03-10 02:02 UTC, willthames commented on lib/ansible/modules/cloud/amazon/ec2_elb_facts.py
> +from ansible.module_utils.ec2 import (
I'd suggest it's an undocumented preference

But it's a fairly standard way of doing things, at least in the amazon modules:

```
$ git grep  'import [^(]*,' | wc -l
75
$ git grep 'import (' | wc -l
5
```

2017-03-13 14:29 UTC, gundalow commented on lib/ansible/modules/cloud/amazon/ec2_elb_facts.py
> +from ansible.module_utils.basic import *
Sounds good

2017-03-13 14:30 UTC, gundalow approved these changes

2017-03-13 19:58 UTC, ryansb approved these changes

2017-03-13 20:01 UTC, ryansb commented
Merged as https://github.com/ansible/ansible/commit/6d8edfc35ff469fbc39c52a0b5ec391aa290ae4a

2017-03-13 20:01 UTC, closed without merging