Autoscaling Groups Lifecycle Hooks module
ansible/ansible pull request #22412
Opened 2017-03-08 15:09 UTC by tsiganenok

##### SUMMARY
New module which allows managing ASG Lifecycle hooks.

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
ec2_asg_lifecycle_hook

##### ANSIBLE VERSION
[root@localhost playbooks]# ansible --version
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

##### ADDITIONAL INFORMATION
There is no module allowing Lifecycle Hooks management for AWS Autoscaling Groups for now.
More about Lifecycle Hooks: http://docs.aws.amazon.com/autoscaling/latest/userguide/lifecycle-hooks.html
It uses boto3 and there is no separate documentation for hooks, but only in autoscaling section: 
http://boto3.readthedocs.io/en/latest/reference/services/autoscaling.html

2017-03-10 20:23 UTC, mattclay commented
@tsiganenok I restarted CI for this PR since the bot didn't pick up all the errors the first time.

2017-03-13 05:29 UTC, willthames commented on lib/ansible/modules/cloud/amazon/ec2_asg_lifecycle_hook.py
> +            heartbeat_timeout=dict(type='str'),
If this is set to type='int' this should avoid the later type conversion

2017-03-20 09:27 UTC, yuval-almog commented
+1

2017-03-20 09:27 UTC, shayisrael commented
+1 
Will be very useful for me

2017-03-20 09:28 UTC, classx commented
+1 very useful

2017-05-10 02:35 UTC, stevenbaker commented
Hope this makes it into 2.4.0.  Looks super useful.

2017-06-15 20:18 UTC, s-hertel requested changes
This looks like a helpful module to have. Thanks for the time and effort you've spent on it!

2017-06-15 20:18 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/ec2_asg_lifecycle_hook.py
> +  - Can create, delete or update Lifecycle Hooks for AWS Autoscaling Groups.
Can you add a more thorough description?

2017-06-15 20:18 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/ec2_asg_lifecycle_hook.py
> +    HAS_BOTO3 = True
You could import this from ansible.module_utils.ec2 instead of manually setting it here and in the except ImportError.

2017-06-15 20:18 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/ec2_asg_lifecycle_hook.py
> +
~Can you document what the returns look like?~
I think this is fine since there isn't any helpful data returned by the boto3 calls. Maybe a facts module would be nice later.

2017-06-15 20:18 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/ec2_asg_lifecycle_hook.py
> +        except Exception as e:
It would better to catch botocore.exceptions.ClientError instead of Exception.

2017-06-15 20:18 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/ec2_asg_lifecycle_hook.py
> +    existing_hook = connection.describe_lifecycle_hooks(
It would be good to have a try/except around this call.

2017-06-15 20:18 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/ec2_asg_lifecycle_hook.py
> +    all_hooks = connection.describe_lifecycle_hooks(
It would be good to have a try/except around this call.

2017-06-15 20:18 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/ec2_asg_lifecycle_hook.py
> +            except Exception as e:
Catch botocore.exceptions.ClientError instead of Exception here too.

2017-06-15 20:18 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/ec2_asg_lifecycle_hook.py
> +    except boto.exception.NoAuthHandlerFound as e:
This should be botocore.exceptions.NoCredentialsError.

2017-07-27 18:46 UTC, tsiganenok commented
@s-hertel Sorry for the time it took, but finally I fixed everything you asked.
What should I do about the RETURN?

2017-08-16 13:38 UTC, tsiganenok commented on lib/ansible/modules/cloud/amazon/ec2_asg_lifecycle_hook.py
> +
So I'm leaving it as is?

2017-11-26 15:24 UTC, tsiganenok commented
@ryansb Hi, is this going to be merged or do I need to fix / change anything?

2017-12-26 09:50 UTC, tsiganenok commented
@s-hertel @ryansb Hi, do I need to fix / edit anything else in order to get it merged?

2018-01-03 00:30 UTC, merged

2018-01-03 00:30 UTC, willthames commented
Merged, thanks for this @tsiganenok. This will indeed be very useful.

2018-01-03 00:33 UTC, willthames commented
Didn't spot the stale_ci, oops. Should have reran the tests. I'll push a new PR shortly for the fixes.

2018-01-03 00:44 UTC, willthames commented
#34379 added to fix some of the problems that would have occurred had tests been rerun.