Fix the eos_banner idempotency
ansible/ansible pull request #22413
Opened 2017-03-08 15:21 UTC by rcarrillocruz

##### SUMMARY

The map_config_to_obj calls the run_commands  helper function,
which returns a list of results.
However, the map_params_to_obj return a single string.
Therefore, the comparison between the two datasets could never be equal,
breaking idempotency.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

eos_banner

##### ANSIBLE VERSION

```
ansible 2.3.0 (fix_eos_banner_idempotency af8f28bdf5) last updated 2017/03/08 16:19:33 (GMT +200)
```

2017-03-08 16:42 UTC, gundalow requested changes
https://app.shippable.com/runs/58c022a9e4b9a205009e04f7/2/tests

2017-03-08 19:24 UTC, gundalow commented
Looks like there may still be an issues with *removing* the banner

```yaml
- name: Setup
  eos_banner:
    banner: login
    text: |
      Junk login banner
      over multiple lines
    state: present
    authorize: yes 

- name: remove login
  eos_banner:
    banner: login
    state: absent
    authorize: yes 
  register: result


- debug:
    msg: "{{ result }}"

- assert:
    that:
      - "result.changed == true"
      - "'no banner login' in result.commands" # does this break due to "contains?"
      # Ensure sessions contains epoc. Will fail after 18th May 2033
      - "'ansible_1' in result.session_name"

- name: remove login (idempotent)
  eos_banner:
    banner: login
    state: absent
    authorize: yes 
  register: result

- assert:
    that:
      - "result.changed == false"
```

2017-03-08 19:31 UTC, mattclay commented
CI failure due to unit test failure: https://app.shippable.com/runs/58c022a9e4b9a205009e04f7/2/tests

2017-03-09 12:43 UTC, gundalow approved these changes

2017-03-09 12:43 UTC, gundalow commented
Tests pass

2017-03-09 12:43 UTC, merged