Added example of removing the standard website and port 80 binding
ansible/ansible pull request #22457
Opened 2017-03-09 19:50 UTC by andmos

##### SUMMARY

By default a "clean" install of IIS contains the Default Web Site, occupying port 80. 
Added example on usage of absent to remove the site and the binding so it can be used by custom sites. 

##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

win_iis_website
##### ANSIBLE VERSION

```
2.2.2.0
```

##### ADDITIONAL INFORMATION

```

```

2017-03-10 13:51 UTC, jctanner commented
cc @nitzmahone @jhawkesworth this module used to be maintained by whenrik, but he/she is no longer on github.

2017-03-15 13:51 UTC, dagwieers commented on lib/ansible/modules/windows/win_iis_website.py
> +# Remove Defaut Web Site and the standard port 80 binding
Typo.

2017-03-15 13:52 UTC, dagwieers requested changes

2017-03-15 13:52 UTC, dagwieers commented on lib/ansible/modules/windows/win_iis_website.py
> +
Please remove the empty line.

2017-03-15 17:34 UTC, jhawkesworth commented
as per @dagwieers comments above

needs_revision

2017-03-15 21:45 UTC, andmos commented
@dagwieers looks good now?

2017-03-16 08:09 UTC, dagwieers commented
@andmos LGTM BTW did you know that strings don't need to be quoted (unless it contains a colon followed by a space, or it is a template) ?

shipit

2017-03-16 21:47 UTC, jborean93 commented
shipit

2017-03-16 21:52 UTC, nitzmahone approved these changes

2017-03-16 21:52 UTC, merged