add osquery_facts module; closes #14066
ansible/ansible pull request #22467
Opened 2017-03-09 23:20 UTC by rmetzler

##### SUMMARY

This module adds basic support for [osquery](https://osquery.io/).

The queries are run via the `osqueryi` cli with the `--json` flag to enable easy parsing.
I wasn't sure whether to use `set_facts` or return the resulting array of dicts and let the user register the variable. I went with the second option mainly because I think the design is simpler.

This is my first module and I didn't wrote any python for a couple of years. Please let me know what I can improve. 

There is a feature request #14066, which I hope to close.

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

osquery_facts

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /usr/local/etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### ADDITIONAL INFORMATION

```

```

2017-03-09 23:41 UTC, sivel requested changes
Facts modules need to return the facts in an `ansible_facts` key.

Additionally due to this they likely need to be namespaces into a `osquery` key.

2017-03-09 23:41 UTC, sivel commented on lib/ansible/modules/system/osquery_facts.py
> +from module_utils.basic import AnsibleModule
This needs to be `from ansible.module_utils...`

2017-03-10 02:10 UTC, rmetzler commented on lib/ansible/modules/system/osquery_facts.py
> +from module_utils.basic import AnsibleModule
done

2017-03-10 07:16 UTC, rmetzler commented
ready_for_review

didn't see the bot's help text

2017-03-10 16:38 UTC, rmetzler commented
ready_for_review

2017-11-29 00:09 UTC, agaffney commented on lib/ansible/modules/system/osquery_facts.py
> +version_added: "2.3"
This should probably be `2.5`

2017-12-05 02:19 UTC, sivel approved these changes

2017-12-07 09:09 UTC, rmetzler commented on lib/ansible/modules/system/osquery_facts.py
> +version_added: "2.3"
fixed

2017-12-13 18:57 UTC, rmetzler commented
@ansibot bot_broken ? I thought the label ci_verified would mean, the PR passed all CI tests. But it seems it rather means the opposite.

2017-12-13 19:07 UTC, sivel commented
Per the documentation, `ci_verified` means:

> Identify pull requests for which CI failed. A pull request must successfully pass CI in order to be merged.

2017-12-15 00:09 UTC, mattclay commented
I've removed the broken label as the bot is functioning correctly.

@sivel Before removing the label, the comment that caused the label to be applied must be removed or edited to no longer contain the command. Otherwise the bot will re-apply the label.

2018-02-13 00:27 UTC, mattclay commented
bot_status

2019-09-18 17:05 UTC, rmetzler commented
:)

```
# install dependencies
pip3 install pep8 pycodestyle voluptuous

# run tests
python3 ./bin/ansible-test sanity --test pep8 lib/ansible/modules/system/
python3 ./bin/ansible-test sanity --test validate-modules lib/ansible/modules/system/

# fix problems
# there is no type `string` in Python, it's `str`
```

2019-09-22 17:34 UTC, rmetzler commented
ready_for_review

2019-09-22 17:40 UTC, rmetzler commented
@ansibot ready_for_review

2019-09-22 17:41 UTC, rmetzler commented
bot_status

2019-11-05 21:28 UTC, rmetzler commented
bot_status

2020-08-17 03:39 UTC, closed without merging