refactor s3_bucket and implement update for ceph
ansible/ansible pull request #22475
Opened 2017-03-10 01:45 UTC by jrandall

##### SUMMARY
Refactors s3_bucket and fixes it to work with ceph (including updates)

Fixes #22464 

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
s3_bucket module

##### ANSIBLE VERSION
```
ansible 2.3.0
  config file =
  configured module search path = Default w/o overrides
  python version = 3.5.2 (default, Sep 19 2016, 11:45:55) [GCC 4.9.1]
```

2017-03-10 16:53 UTC, s-hertel commented
Can you separate the bugfix and refactoring into two PRs? Since we are in feature freeze right now only taking bugfixes are being accepted for 2.3.

2017-05-16 13:48 UTC, ryansb commented
@jrandall can you rebase this now that the bugfix was merged?

2017-05-16 14:08 UTC, colin-nolan commented
Rebased (by member of Josh's team).

2017-05-17 19:45 UTC, colin-nolan commented
@ansibot ready_for_review

2017-08-02 18:00 UTC, ryansb requested changes

2017-08-02 18:00 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/s3_bucket.py
> +            module.fail_json(msg="Failed to get S3 bucket: %s" % e)
While editing this, please also add the traceback via the keyword arg "exception" as in `exception=traceback.format_exc()`

2017-08-02 18:00 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/s3_bucket.py
> +            module.fail_json(msg='Failed to empty S3 bucket: %s' % e)
Same here

2017-08-02 18:00 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/s3_bucket.py
> +        module.fail_json(msg='Failed to delete S3 bucket: %s' % e)
Same here

2017-08-02 18:00 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/s3_bucket.py
> +    if module.params["tags"] is not None and flavour == 'ceph':
Maybe make this an `elif module.params["tags"] is not None:` since the `== 'ceph'` is the inverse of above?

2017-08-02 18:00 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/s3_bucket.py
> +    current_tags_dict=None
Need a space here for PEP8

2017-08-02 18:00 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/s3_bucket.py
> +            payer='Requester'
Need a space here

2017-08-02 18:00 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/s3_bucket.py
> +            payer='BucketOwner'
Need a space here

2017-08-02 18:00 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/s3_bucket.py
> +    if versioning is not None:
How about:

```
if versioning is None:
    pass
elif versioning and versioning_status.get('Versioning') != "Enabled":
    ...
elif not versioning and versioning_status.get('Versioning') == "Enabled":
    ...
```

To reduce the nesting level a little bit.

2017-08-03 09:30 UTC, colin-nolan commented on lib/ansible/modules/cloud/amazon/s3_bucket.py
> +    if versioning is not None:
I'll refactor around here to remove the duplication.

2017-08-03 09:38 UTC, colin-nolan commented
Completed changes on behalf of @jrandall to address the issues raised by @ryansb.

2018-11-30 19:19 UTC, nitzmahone commented
This should be brought to an AWS Working Group meeting if it's still desired behavior...

2018-11-30 21:43 UTC, s-hertel commented
The bugfix was merged, and what is left here appears to just be refactoring. This module was ported to boto3 and had tests added in 2.6. I'm not sure if the refactor is warranted anymore, but would probably need to be done from scratch since trying to rebase this would be very messy. I'm closing since it will not rebase. On the plus side, now there are tests to help ensure refactoring won't break things if you still see a need for that. Feel free to reach out to the AWS working group if I've overlooked something.

2018-11-30 21:43 UTC, closed without merging