adds connection established message to ansible-connection
ansible/ansible pull request #22492
Opened 2017-03-10 14:05 UTC by privateip

This will now print a log message that displays how long the ssh
connection took to establish to the remote device.  If the connection
established time is exceed it will also print a message to the log file
that the connection attempts have exceed.

fixes #22319

2017-03-10 14:40 UTC, jctanner commented
shipit

2017-03-10 15:39 UTC, gundalow commented
So with this in I get (out the box defaults):

```
2017-03-10 15:31:55,735 p=19669 u=johnb |  TASK [prepare_eos_tests : enable cli on remote device] *******************************************************************************************************************************************************************************************
2017-03-10 15:31:55,735 p=19669 u=johnb |  task path: /home/johnb/git/ansible-inc/ansible-workspace-2/test/integration/targets/prepare_eos_tests/tasks/main.yml:1
<veos01> starting new persistent socket with path /home/johnb/.ansible/pc/ca5960d27a
<veos01> using connection plugin network_cli
<veos01> ESTABLISH CONNECTION FOR USER: admin on PORT 22 TO veos01
2017-03-10 15:32:06,173 p=19677 u=johnb |  number of connection attempts exceeded, unable to connect to control socket
2017-03-10 15:32:06,174 p=19677 u=johnb |  persistent_connect_interval=1, persistent_connect_retries=10
2017-03-10 15:32:06,222 p=19669 u=johnb |  fatal: [veos01]: FAILED! => {
```

Wait for socket to fully timeout

Setting `ANSIBLE_PERSISTENT_CONNECT_INTERVAL=10 `
```
2017-03-10 15:37:20,220 p=19901 u=johnb |  META: ran handlers
2017-03-10 15:37:20,261 p=19901 u=johnb |  TASK [prepare_eos_tests : enable cli on remote device] *******************************************************************************************************************************************************************************************
2017-03-10 15:37:20,261 p=19901 u=johnb |  task path: /home/johnb/git/ansible-inc/ansible-workspace-2/test/integration/targets/prepare_eos_tests/tasks/main.yml:1
<veos01> starting new persistent socket with path /home/johnb/.ansible/pc/ca5960d27a
<veos01> using connection plugin network_cli
<veos01> ESTABLISH CONNECTION FOR USER: admin on PORT 22 TO veos01
<veos01> ssh connection done, setting terminal
<veos01> ssh connection has completed successfully
<veos01> connection established in 0:00:22.297563
<veos01> incoming request accepted on persistent socket
```

2017-03-10 15:53 UTC, gundalow requested changes
1)  Would be worth increasing the constant in here

2) So for the other connection issues we can do
`grep  -e "^<" $ANSIBLE_LOG_PATH

Can we get some marker in here we can grep for, maybe `ansible-connection` that will make documenting debug steps easier

2017-03-13 14:34 UTC, gundalow commented
As discussed in Team meeting:
* Please increase the timeout, then this can be merged

In a future PR:
* Prefix the messages that makes it clear what comes from ansible vs ansible-connection
* Once network debug docs is live gundalow will update the messages to point to docs.ansible.com

2017-03-14 14:31 UTC, merged