Support setting a relative log_path without a leading directory
ansible/ansible pull request #22506
Opened 2017-03-10 18:32 UTC by jdufresne

Use more Pythonic pattern "Easier to ask for forgiveness than permission". As
Python already does the error checking, simply catch the exception instead of
reproducing the same checks.

https://docs.python.org/3/glossary.html#term-eafp

Fixes #22500

##### ISSUE TYPE
 - Bugfix Pull Request

##### ANSIBLE VERSION

```
$ $ansible --version
ansible 2.3.0 (devel 4ca7726e75) last updated 2017/03/10 10:16:35 (GMT -700)
```

2017-03-10 19:52 UTC, jctanner commented
@jdufresne I think the try/except should be around the code that actually throws the exception, rather than around a whole block like that. Please revise.

needs_revision

2017-03-10 21:17 UTC, jdufresne commented
I agree with your suggestion. I have revised the PR, please review.

The shippable failure has something to do with a cURL failure and I believe it is unrelated to this change.

Thanks.

2017-03-10 22:39 UTC, jdufresne commented
ready_for_review

2017-07-14 14:43 UTC, bcoca requested changes

2017-07-14 14:43 UTC, bcoca commented on lib/ansible/utils/display.py
> +        print("[WARNING]: log file at %s is not writeable and we cannot create it, aborting\n" % path, file=sys.stderr)
the error is misleading, as the problem is either that you cannot write to or cannot create a logfile in the directory, this seems to imply both. 

note:yes, error is prexisting ... need to append exception if we are going to change from `if` to `try`

2017-07-14 14:43 UTC, bcoca commented on lib/ansible/utils/display.py
> +        print("[WARNING]: log file at %s is not writeable and we cannot create it, aborting\n" % path, file=sys.stderr)
probably a simpler fix is setting `expand_relative_paths=True` for this config item in constants.py

2017-07-14 14:45 UTC, calfonso commented
Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you. If you could, please re-test using our devel branch and let us know if you still see the issue.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code
Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

2017-07-14 14:48 UTC, abadger commented
Reopened because we aren't sure that this is fixed.  If you could retest and then, if it isn't fixed, implement bcoca's suggestions, we would be most happy to see if this should be merged.  Thanks!

2017-07-15 03:11 UTC, jdufresne commented
ready_for_review

2017-07-15 03:23 UTC, jdufresne commented
Thanks. I tested the latest devel and the log is working for me! Closing my PR.

2017-07-15 03:23 UTC, closed without merging