Fixes bug https://github.com/ansible/ansible/issues/22455 - Git reset…
ansible/ansible pull request #22502
Opened 2017-03-10 16:58 UTC by Miyurz

##### SUMMARY

Fixes bug https://github.com/ansible/ansible/issues/22455, Git reset fails when file with the name 'origin' is present in the repository. With this change one can update its origin even when there exists a file named origin in its code base. This fix has been tested with the user provided inputs. Snapshots attached.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

ansible/modules/source_control/git.py
##### ANSIBLE VERSION

```
ansible 2.3.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 18 2016, 07:03:39) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### ADDITIONAL INFORMATION

```

```

2017-03-10 18:58 UTC, jctanner commented
cc @robinro

2017-03-12 13:31 UTC, robinro approved these changes
LGTM

Thanks @silwol for reporting and @Miyurz for this fix.

You could add an integration test to prevent future regressions.

2017-03-14 11:07 UTC, Miyurz commented
Fixed the yamlint issue. Sorry for the noise!

2017-03-14 12:54 UTC, robinro commented
@Miyurz you rebased/merged too much stuff and now have 37 unrelated commits in here.

Regarding the integration test: 
* Please add this to the existing git tests, there is no need for a new target
* Instead of using a remote repo, please create a local test repo inside the tests and clone that, see in `test/integration/targets/git/tasks` see `setup-local-repos.yml`, `depth.yml`.

2017-03-14 15:52 UTC, gundalow commented
See http://docs.ansible.com/ansible/dev_guide/developing_rebasing.html for how to rebase

2017-03-21 10:47 UTC, Miyurz commented
Thats a false failure. I checked above and the test(s) failed to pull the docker image and hence the error.

2017-03-21 10:54 UTC, Miyurz commented
How do I rebuild this branch in CI ?

2017-03-21 12:48 UTC, Miyurz commented
@robinro Not sure what target is building git tasks/playbooks in integration/targets/git

2017-03-21 13:22 UTC, Miyurz commented
Awesome, all tests are now passing!

2017-03-21 16:06 UTC, robinro commented
@Miyurz The new tests are not in the right place don't run as far as I see.

Put the repo setup in `test/integration/targets/git/tasks/setup-local-repos.yml` and the test in `test/integration/targets/git/tasks/formats.yml`.
Or if you want a seperate file, create one in the same folder and include it from `test/integration/targets/git/tasks/main.yml`.

The code of the tests looks good to me. Thanks for implementing those.

2017-03-21 17:18 UTC, Miyurz commented
@robinro Incorporated your review comments.

2017-03-21 17:30 UTC, Miyurz commented
@robinro Incorporated your review comments

2017-03-21 17:35 UTC, robinro requested changes

2017-03-21 17:35 UTC, robinro commented on test/integration/git.yml
> +---
This file is not needed.

2017-03-21 17:35 UTC, robinro commented on test/integration/targets/git/tasks/reset-origin.yml
> +- hosts: localhost
This is a `tasks` file, remove lines 2-5.

2017-03-21 17:35 UTC, robinro commented on test/integration/targets/git/vars/main.yml
> +source_dir:  "{{ output_dir }}/source"
`msg` is only used once, so you can hardcode it there.

I would also not define variables for source_dir and destination_dir, but put the values directly.
Following the convention in `setup-local-repos.yml` I'd recommend to use `{{repo_dir}}/origin` for the "source" and `{{checkout_dir}}` for the "destination".

2017-03-21 18:00 UTC, Miyurz commented on test/integration/git.yml
> +---
Yeah, its removed already. Check the latest commit.

2017-03-21 18:00 UTC, Miyurz commented on test/integration/targets/git/vars/main.yml
> +source_dir:  "{{ output_dir }}/source"
`msg` is used twice and since its quite a long line, it has been added as a var.
other vars have not been taken care of.

2017-03-21 18:12 UTC, Miyurz commented
@robinro Replied to your comments and removed the variables.

2017-03-22 07:42 UTC, robinro commented
@Miyurz The `msg` var is still not needed imo. I would put the reference to the issue in the test name, such that it is also visible to people running the test. There is no need to put that URL in the file or commit message.

The vars section is long already and we should keep it compact to ease refactoring.

2017-03-22 09:08 UTC, Miyurz commented
@robinro I got your pint now. Indeed, `msg` var doesn't make sense in the vars file. Done with the changes!

2017-03-22 09:27 UTC, robinro commented
Thanks @Miyurz for the fixes. Looks good now! Tests run and pass.

shipit
@jctanner @gundalow

2017-03-23 03:18 UTC, Miyurz commented
@gundalow @jctanner Is this merged yet ?

2017-03-27 04:11 UTC, Miyurz commented
@robinro @gundalow @jctanner When do we merge this and close the PR ?

2017-03-27 06:32 UTC, robinro commented
@Miyurz I don't have commit rights on the repo. @jctanner @gundalow do and either they or someone else will probably soon (within the next days) merge this.
If you want to speed it up, you can go to ansible-devel in IRC and ask someone to review/merge it.

2017-03-27 14:00 UTC, jctanner commented
@robinro you have a pending requestion for change. Please dismiss or approve it.

2017-03-27 14:17 UTC, robinro approved these changes

2017-03-27 14:17 UTC, robinro commented
@jctanner done

2017-03-28 12:41 UTC, merged