Doc directives
ansible/ansible pull request #22524
Opened 2017-03-11 04:02 UTC by bcoca

##### SUMMARY

actually document directives page

##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

docs
##### ANSIBLE VERSION

```
2.3
```

2017-03-13 19:00 UTC, gundalow requested changes
Looks good, thanks for documenting this. Just a few suggestions of wording, though I'll let Scott have the final say.

2017-03-13 19:00 UTC, gundalow commented on docs/docsite/directive_desc.yml
> +become_flags: A string of flag(s) to pass to the privilege escalation program when ``become`` is True.
`A string of flag(s) (white space separated)...

2017-03-13 19:00 UTC, gundalow commented on docs/docsite/directive_desc.yml
> +become_user: User that you 'become' after using privilege escalation, the remote/login user must have permissions to become this user.
User that you 'become' after using privilege escalation on the remote system, the ``remote_user`` user must have permissions to become this user.

2017-03-13 19:00 UTC, gundalow commented on docs/docsite/directive_desc.yml
> +ignore_errors: Boolean that allows you to ignore task failures and continue with play. It does not affect connection errors.
s/It does not affect connection errors./Connection errors will always cause an error and stop the playbook run for the  machine./


Not sure what the best wording for "stop the playbook run for the  machine", feel free to change

2017-03-13 19:00 UTC, gundalow commented on docs/docsite/directive_desc.yml
> +name: It's a name, works mostly for documentation, in the case of tasks/handlers it can be an identifier.
Allows tasks to have a human readable name, which is best practice. The name can be used as an identified when uses with ``--start-at-task` or for `handlers:`.

2017-03-13 19:00 UTC, gundalow commented on docs/docsite/directive_desc.yml
> +remote_user: User used to log into the target via the connection plugin. AKA login user.
Also referred to as the "login user".

2017-03-13 19:00 UTC, gundalow commented on docs/docsite/directive_desc.yml
> +always_run: DEPRECATED, forces a task to run even in check mode, use check_mode directive instead.
``check_mode``

2017-03-13 19:03 UTC, bcoca commented
once merged, changing the docs is just editing the yaml file, so i'm going to leave as is for now,  you guys can modify to perfection afterwards.

2017-03-13 19:46 UTC, gundalow commented
> once merged, changing the docs is just editing the yaml file, so i'm going to leave as is for now, you guys can modify to perfection afterwards.

Sounds good idea.

2017-03-15 15:24 UTC, dharmabumstead requested changes

2017-03-15 15:24 UTC, dharmabumstead commented on docs/docsite/directive_desc.yml
> +ignore_errors: Boolean that allows you to ignore task failures and continue with play. It does not affect connection errors.
Suggest using 'Boolean that indicates..." rather than "Boolean that controls..."

2017-03-15 15:24 UTC, dharmabumstead commented on docs/docsite/directive_desc.yml
> +name: It's a name, works mostly for documentation, in the case of tasks/handlers it can be an identifier.
+1 @gundalow

2017-03-15 15:24 UTC, dharmabumstead commented on docs/docsite/directive_desc.yml
> +always_run: DEPRECATED, forces a task to run even in check mode, use check_mode directive instead.
s/Boolean that controls/Boolean that indicates...

Example: 
Boolean that indicates whether or not a log is create.

2017-03-15 15:29 UTC, merged