vmware_guest: Fix "KeyError: 'changed'"
ansible/ansible pull request #22564
Opened 2017-03-13 13:48 UTC by dagwieers

##### SUMMARY

Due to how the result-dictionary is being used, in some codepaths it would have an empty dictionary.
This then is problematic if the code expects the 'changed' key later on.

I also improved the docs a bit, by clearly marking the parameter names and URL in the documentation.

##### ISSUE TYPE

 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

v2.3

2017-03-13 14:32 UTC, nerzhul requested changes
Except some spaces it's good for me

2017-03-13 14:32 UTC, nerzhul commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +            changed = False,
please remove spaces

2017-03-13 14:32 UTC, nerzhul commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +            failed= False,
same here

2017-03-13 23:22 UTC, dagwieers commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +            changed = False,
Why ? We have automatic PEP testing now, this was considered fine.

2017-03-13 23:27 UTC, nerzhul commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +            changed = False,
just for being consistent with other dicts in the module

2017-03-13 23:31 UTC, dagwieers commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +            changed = False,
I don't think it improves readability, especially not for multi-line dicts. But you're the boss.

2017-03-14 11:40 UTC, dagwieers commented
!needs_revision

2017-03-16 13:34 UTC, dagwieers commented
@nerzhul Can you please merge this ? And backport to v2.3 ?

2017-03-16 14:16 UTC, nerzhul commented
i cannot merge, but 

shipit

2017-03-16 14:48 UTC, nerzhul approved these changes
approving for bot

2017-03-16 14:55 UTC, merged