New metadata 1.0
ansible/ansible pull request #22587
Opened 2017-03-13 23:47 UTC by abadger

##### SUMMARY
A new metadata format was approved here: https://github.com/ansible/proposals/issues/54

* Update documentation to the new metadata format
* Changes to metadata-tool to account for new metadata  
    * Add GPL license header
    * Add upgrade subcommand to upgrade metadata version
    * Change default metadata to the new format
    * Fix exclusion of non-modules from the metadata report
* Update the metadata in all modules to the new version

##### ISSUE TYPE
 - Feature Pull Request
 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME
metadata of all modules.

##### ANSIBLE VERSION

```
2.3
```

2017-03-14 00:14 UTC, dharmabumstead approved these changes

2017-03-14 03:59 UTC, mattclay requested changes
A few minor docs changes requested.

2017-03-14 03:59 UTC, mattclay commented on docs/docsite/rst/dev_guide/developing_modules_checklist.rst
> +The complete module metadata specification is here: http://docs.ansible.com/ansible/dev_guide/developing_modules_documenting.html#ansible-metadata-block
Use `https` for docs links.

2017-03-14 03:59 UTC, mattclay commented on docs/docsite/rst/dev_guide/developing_modules_documenting.rst
> +   * Promoting a module's ``status`` or ``supported_by`` status should only be done by members of the Ansible Core Team.
The note about `status` and `supported_by` doesn't make sense under the "metadata_version field" heading. Perhaps the heading should just be a general warning instead?

2017-03-14 14:05 UTC, abadger commented
Addressed mattclay's requests.  Waiting on shippable and then will merge.

2017-03-14 15:56 UTC, mattclay approved these changes

2017-03-14 16:07 UTC, merged

2019-02-28 12:59 UTC, gherrin commented
To whom it may concern, this module misses views when granting table-level privs and/or ALL_IN_SCHEMA privs.  This section of code needs to select relkind of 'r' and 'v':

    def get_table_acls(self, schema, tables):
        query = """SELECT relacl
                   FROM pg_catalog.pg_class c
                   JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
                   WHERE nspname = %s AND relkind = 'r' AND relname = ANY (%s)
                   ORDER BY relname"""
        self.cursor.execute(query, (schema, tables))
        return [t[0] for t in self.cursor.fetchall()]