win_service Added -Force option and minor cleanup
ansible/ansible pull request #22598
Opened 2017-03-14 08:10 UTC by jborean93

##### SUMMARY
As per the discussion in the Windows user group this cleans up win_service so that it matches general standard and adds the optional parameter around whether to force a service to stop.

##### ISSUE TYPE
 - Feature Pull Request
 - Bugfix Pull Request

##### COMPONENT NAME
win_service

##### ANSIBLE VERSION
```
ansible 2.3.0 (devel 771b14acb2) last updated 2017/03/14 17:33:12 (GMT +1000)
  config file = /mnt/c/dev/test/role/ansible.cfg
  configured module search path = [u'/mnc/c/dev/test/role/library']
  python version = 2.7.12 (default, Dec 14 2016, 21:05:07) [GCC 4.8.4]
```

2017-03-14 08:10 UTC, jborean93 commented
@nitzmahone @dagwieers @jhawkesworth

2017-03-14 11:37 UTC, dagwieers commented
So you basically reimplemented #20539 and #22311 too :-)
I think it is unfortunate that effort is duplicated like this (because our time could be spend better) and I hope we can prevent this in the future.

shipit

2017-03-14 11:39 UTC, dagwieers approved these changes

2017-03-14 11:43 UTC, jborean93 commented
this change was from an action in today's meeting, I thought you wanted me to incorporate your changes into the one but I must have misinterpreted it.

2017-03-14 11:45 UTC, dagwieers commented
@jborean93 Yeah, I have no problem with this. Fact is that if PRs would be merged quicker, you didn't have to do this as it would already be reviewed and merged using the normal process.

2017-03-15 00:42 UTC, nitzmahone requested changes
Hmm, wondering if there's a better name than `ignore_dependencies`, since we're not really "ignoring" them... We're stopping/restarting "dependent" services, not this service's dependencies- trying to figure out a concise way to name that... 

`allow_dependent_service_state_change` would be correct, but awfully long. Microsoft rarely trades brevity for clarity in Powershell, but in this case the terse `force` arg on `Stop-Service`/`Restart-Service` is not a name I want to emulate. `manage_dependent_services` maybe? Dunno, I'm open to suggestions, and if you're busy, I can do the rename if you like. Thoughts?

2017-03-15 00:54 UTC, jborean93 commented
Maybe `change_dependent_services`  as we are changing the state of the dependent services?

2017-03-15 00:56 UTC, nitzmahone commented
Trying to find a word about twiddling their state...

2017-03-15 01:00 UTC, nitzmahone commented
`X_dependent_services`, where X is:

manage
state_change
manipulate
modify

`state_change_dependent_services` is the most accurate of those, but funky English, which is why I kinda landed on `manage_dependent_services`, but I still don't *love* that either.

2017-03-15 01:02 UTC, nitzmahone commented
I don't really want to split it into separate args for stop/restart, but if we *did*, `stop_dependent_services` and `restart_dependent_services` would be exactly correct... :(

2017-03-15 01:02 UTC, nitzmahone commented
Which brings me back to `manage_dependent_services` as the best compromise.

2017-03-15 01:02 UTC, jborean93 commented
`allow_twiddling_of_dependent_services` :)

Could we put `force_dependent_services` as it matches the -Force side of the command, still not the best.

2017-03-15 01:03 UTC, nitzmahone commented
Actually I don't hate `force_dependent_services`... That'll do- you want to make the change, or shall I?

2017-03-15 01:04 UTC, jborean93 commented
I'll make the change, there are some other typos I've found in the WMI error codes I want to fix up as well.

2017-03-15 01:04 UTC, nitzmahone commented
OK, if you're doing typos, I saw a couple others too- go ahead and do the other stuff and I'll mark those up real quick.

2017-03-15 01:10 UTC, nitzmahone commented on lib/ansible/modules/windows/win_service.py
> +    - When stopping or restarting a service this will Force the service to stop
How about "If `true`, stopping or restarting a service with dependent services will force the dependent services to stop or restart also. If `false`, stopping or restarting a service with dependent services may fail.

2017-03-15 01:34 UTC, nitzmahone approved these changes

2017-03-15 01:35 UTC, jborean93 commented on lib/ansible/modules/windows/win_service.py
> +    - When stopping or restarting a service this will Force the service to stop
Have made the change, I wasn't fully aware of this behaviour but am now

2017-03-15 01:35 UTC, nitzmahone commented
Noice, will wait for green from shippable and merge. Thanks!

2017-03-15 01:53 UTC, merged