Bcf
ansible/ansible pull request #22594
Opened 2017-03-14 03:47 UTC by tedelhourani

##### SUMMARY

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

bcf_switch

##### ANSIBLE VERSION

```
ansible 2.3.0 (bcf 69f17bb39c) last updated 2017/03/13 19:08:53 (GMT -700)
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### ADDITIONAL INFORMATION

```

```

2017-03-16 19:05 UTC, jayakody commented
ACK

2017-03-16 20:41 UTC, jayakody commented
LGTM. 
shipit

2017-03-17 16:55 UTC, vuile commented
ship

2017-04-24 12:55 UTC, jctanner commented
bot_status

2017-04-27 16:56 UTC, gundalow requested changes

2017-04-27 16:56 UTC, gundalow commented on lib/ansible/modules/network/bigswitch/bcf_switch.py
> +version_added: "2.3"
`version_added: "2.4"`

2017-04-27 16:56 UTC, gundalow commented
Closing and reopening to rerun CI

2017-05-02 06:04 UTC, gundalow requested changes

2017-05-02 06:04 UTC, gundalow commented on lib/ansible/modules/network/bigswitch/bigmon_chain.py
>  # -*- coding: utf-8 -*-
Modules should have permission 644 (not 775), could you please check this.

2017-05-02 06:04 UTC, gundalow commented on lib/ansible/modules/network/bigswitch/bcf_switch.py
> +short_description: Create and remove a bcf switch.
One bit of feed back we've recently had fun the community is to put the vendor and/or product name in the `short_description` so a more searchable string will appear in http://docs.ansible.com/ansible/list_of_network_modules.html

So I think bigmon needs adding to this.

2017-05-02 06:04 UTC, gundalow commented on lib/ansible/modules/network/bigswitch/bcf_switch.py
> +    )
What would it take for the module to support "check mode", ie be idempotent?

2017-05-03 05:37 UTC, tedelhourani commented on lib/ansible/modules/network/bigswitch/bcf_switch.py
> +short_description: Create and remove a bcf switch.
This is a bcf (big cloud fabric), not a big mon module.

2017-05-03 06:29 UTC, tedelhourani commented on lib/ansible/modules/network/bigswitch/bcf_switch.py
> +    )
Can be implemented now as the module is already idempotent.

But before, what does this mean?

lib/ansible/modules/network/bigswitch/bcf_switch.py:0:0: E319 RETURN.changed.: expected a dictionary
lib/ansible/modules/network/bigswitch/bcf_switch.py:0:0: E319 RETURN.invocation.description: required key not provided @ data['description']. Got None
lib/ansible/modules/network/bigswitch/bcf_switch.py:0:0: E319 RETURN.invocation.module_args: extra keys not allowed @ data['module_args']. Got {'validate_certs': False, 'fabric_role': 'leaf', 'controller': '192.168.86.230', 'mac': '00:00:00:02:00:02', 'name': 'Rack1Leaf1', 'state': 'present', 'access_token': None, 'leaf_group': 'R1'}
lib/ansible/modules/network/bigswitch/bcf_switch.py:0:0: E319 RETURN.invocation.returned: required key not provided @ data['returned']. Got None
lib/ansible/modules/network/bigswitch/bcf_switch.py:0:0: E319 RETURN.invocation.type: required key not provided @ data['type']. Got None
click here for bot help

2017-05-03 15:03 UTC, tedelhourani commented
Closing this one starting from scratch.

2017-05-03 15:03 UTC, closed without merging