New module redshift_facts
ansible/ansible pull request #22615
Opened 2017-03-14 16:14 UTC by j-carl

Gather facts about Redshift Cluster(s).

##### SUMMARY

Gather facts about Redshift Cluster(s) either by:

- Get all cluster(s)
- Get cluster(s) by name (uses a regular expression)
- Get cluster(s) by tags

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

`lib/ansible/modules/cloud/amazon/redshift_facts.py`

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file =
  configured module search path = Default w/o overrides
```

2017-03-15 17:11 UTC, gundalow commented on lib/ansible/modules/cloud/amazon/redshift_facts.py
> +version_added: "2.3"
`"2.4"`

2017-06-19 18:23 UTC, s-hertel requested changes

2017-06-19 18:23 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/redshift_facts.py
> +    for key, value in tags_to_match.item():
I think this was a typo- should be tags_to_match.items():

2017-06-19 18:23 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/redshift_facts.py
> +    module = AnsibleModule(argument_spec=argument_spec)
you could add supports_check_mode=True to AnsibleModule

2017-06-19 18:23 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/redshift_facts.py
> +            matched_tags = matched_tags(tags, cluster)
Another typo - should be match_tags(tags, cluster)

2017-06-21 18:40 UTC, j-carl commented on lib/ansible/modules/cloud/amazon/redshift_facts.py
> +    for key, value in tags_to_match.item():
Thx and I fixed it

2017-06-21 18:40 UTC, j-carl commented on lib/ansible/modules/cloud/amazon/redshift_facts.py
> +            matched_tags = matched_tags(tags, cluster)
Thx

2017-06-21 18:41 UTC, j-carl commented on lib/ansible/modules/cloud/amazon/redshift_facts.py
> +    module = AnsibleModule(argument_spec=argument_spec)
I added the feature

2017-06-23 13:42 UTC, s-hertel approved these changes

2017-06-23 13:42 UTC, s-hertel commented
shipit

2017-08-01 18:09 UTC, merged

2017-08-01 18:10 UTC, abadger commented
Merged to devel for 2.4.0 release.