win_scheduled_task: Added frequency: once and check_mode support
ansible/ansible pull request #22611
Opened 2017-03-14 15:04 UTC by dagwieers

##### SUMMARY

This patch includes:
- Renamed `execute:` parameter to `executable:`
- Renamed `argument:` parameter to `arguments:`
- Implemented `frequency: once` support
- Implemented check_mode support

##### ISSUE TYPE

 - Feature Pull Request
 - Bugfix Pull Request

##### COMPONENT NAME

win_scheduled_task

##### ANSIBLE VERSION

v2.3

##### ADDITIONAL INFORMATION

This fixes #22485

2017-03-14 16:58 UTC, dagwieers commented
@nitzmahone @jborean93 @jhawkesworth Obviously I am biased, but after testing and fixing this module I think we need to ship this with v2.3 RC1 too. There is an idempotency bugfix, now supports check-mode and finally has integration tests that fail with the original module.

2017-03-14 22:28 UTC, jborean93 commented
I like the way you have done the tests, will probably pinch it for the future.

shipit

2017-03-15 01:52 UTC, nitzmahone requested changes
Couple minor things (mainly removing the debug cruft)- the test stuff is just suggestions that we can deal with later if you'd rather.

2017-03-15 01:52 UTC, nitzmahone commented on lib/ansible/modules/windows/win_scheduled_task.ps1
> +        $result.foobar = "($($task.Description) vs $description) -- ($($task.TaskName) vs $name) -- ($($task.TaskPath) vs $path) -- ($($task.Actions.Execute) vs $executable) -- ($taskState vs $enable
Debug cruft?

2017-03-15 01:52 UTC, nitzmahone commented on test/integration/targets/win_scheduled_task/tasks/main.yml
> +- name: Test in normal mode (only run on Win2012+)
This only works for current shippable config- should use feature sniff instead, something like `raw: Get-Command New-ScheduledTask -ErrorAction SilentlyContinue; $?` with `failed_when: False` then skip the tests if the rc != 0. I guess we could use the OS version facts too...

2017-03-15 01:52 UTC, nitzmahone commented on test/integration/targets/win_scheduled_task/tasks/main.yml
> +      - add_scheduled_task.changed == true
Should run a `state: absent` first sans registered output to assert the right starting state (eg, test stopped in the middle and left the test task there).

2017-03-15 09:34 UTC, dagwieers commented on lib/ansible/modules/windows/win_scheduled_task.ps1
> +        $result.foobar = "($($task.Description) vs $description) -- ($($task.TaskName) vs $name) -- ($($task.TaskPath) vs $path) -- ($($task.Actions.Execute) vs $executable) -- ($taskState vs $enable
Ouch, indeed :)

2017-03-15 09:46 UTC, dagwieers commented on test/integration/targets/win_scheduled_task/tasks/main.yml
> +- name: Test in normal mode (only run on Win2012+)
That is clever. I now test for capabilities this way...

2017-03-15 09:47 UTC, dagwieers commented on test/integration/targets/win_scheduled_task/tasks/main.yml
> +      - add_scheduled_task.changed == true
Good catch. I included that as well.

2017-03-15 10:08 UTC, dagwieers commented
!needs_revision

2017-03-15 10:08 UTC, dagwieers commented
ready_for_review

2017-03-15 10:09 UTC, dagwieers commented
bot_status

2017-03-15 13:40 UTC, dagwieers commented
@nitzmahone I need you to flag the review process as finished ! Or re-review.

2017-03-15 14:11 UTC, nitzmahone approved these changes

2017-03-15 14:11 UTC, merged

2017-03-15 14:11 UTC, nitzmahone commented
woot- thanks!