openstack: remove default egress security rules
ansible/ansible pull request #22628
Opened 2017-03-15 00:50 UTC by nhicher

With this change, it's possible for a user to remove
the default egress security rules during the
security group creation.

It's not possible to match these rules using
os_security_group_rule module without adding a specific
condition in _find_matching_rule function (with None
values for remote_ip_prefix, protocol and ethertype).

This solution looks easier to maintain.

##### SUMMARY

##### ISSUE TYPE

 - Feature Pull Request
 - New Module Pull Request
 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME

##### ANSIBLE VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

2017-04-25 16:31 UTC, emonty requested changes
Seems like a fine approach to the problem - the name of the parameter confused me at first though.

2017-04-25 16:31 UTC, emonty commented on lib/ansible/modules/cloud/openstack/os_security_group.py
> +                if egress_default_rules == 'absent':
Maybe I'm missing something, but it looks to me like setting egress_default_rules to absent will remove _all_ rules from the group that was just created (the default set of rules could be different things on different clouds iirc) Perhaps we should just make this a bool called "delete_default_rules" or something - and mention in the doc string that it only has any effect when you are creating a security group.

2017-04-27 19:08 UTC, nhicher commented on lib/ansible/modules/cloud/openstack/os_security_group.py
> +                if egress_default_rules == 'absent':
you're right, I didn't think about others default rules. I fixe the patch. Thanks for the review

2017-04-28 14:54 UTC, nhicher commented
@emonty I did the change, but used push -f, not sure it was the right thing to do.

2017-08-03 14:49 UTC, closed without merging