[WIP] Network debug docs
ansible/ansible pull request #22652
Opened 2017-03-15 16:40 UTC by gundalow

##### SUMMARY
WIP

##### ISSUE TYPE
 - Docs Pull Request

2017-03-27 21:13 UTC, gundalow commented
Note to self: may need to add notes, or better yet link to existing documentation on:
```
-* provider (and vars)
-* ssh keys
-* command line (``-u someuser -k``)
-* what else?
```

2017-03-30 18:30 UTC, dharmabumstead requested changes
See comments. Might be a good idea to move some of the content off into separate docs and/or merge with the existing 'intro to networking' content.

2017-03-30 18:30 UTC, dharmabumstead commented on docs/docsite/rst/network_debug_troubleshooting.rst
> +Playbook Structure from 2.1 to 2.3
This seems to somewhat duplicate the 'Specifying Credentials' section below.

2017-03-30 18:30 UTC, dharmabumstead commented on docs/docsite/rst/network_debug_troubleshooting.rst
> +Specifying Credentials
Maybe merge some of the 'Playbook Structure' content detail in with this section.

2017-03-30 18:30 UTC, dharmabumstead commented on docs/docsite/rst/network_debug_troubleshooting.rst
> +Ansible Network Roadmap
Not sure if this content is something that should be included in this document.

2017-04-10 21:21 UTC, Qalthos commented on docs/docsite/rst/network_debug_troubleshooting.rst
> +If the above still fails you can combine it the enable_network_logging_, for example::
I don't know what `it the` is supposed to mean

2017-04-10 21:26 UTC, rcarrillocruz requested changes

2017-04-10 21:26 UTC, rcarrillocruz commented on docs/docsite/rst/network_debug_troubleshooting.rst
> +  * Use of ``delgate_to``, instead of ``ProxyCommand``
s/delgate_to/delegate_to

2017-04-10 21:35 UTC, gundalow commented on docs/docsite/rst/network_debug_troubleshooting.rst
> +If the above still fails you can combine it the enable_network_logging_, for example::
Fixed

2017-04-19 11:09 UTC, gundalow commented
Debug guide is live, so I've moved those changes to a fresh PR https://github.com/ansible/ansible/pull/23735

2017-05-12 15:59 UTC, closed without merging