cloud: ovirt: add developer README.md
ansible/ansible pull request #22685
Opened 2017-03-16 10:43 UTC by machacekondra

##### SUMMARY

Add developer README file.

##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

ovirt

##### ANSIBLE VERSION

```
2.3.0
```

##### ADDITIONAL INFORMATION

```

```

2017-03-16 10:44 UTC, machacekondra commented
@mwperina

2017-04-23 07:11 UTC, mykaul commented on lib/ansible/modules/cloud/ovirt/README.md
> +These are a set of modules for interacting with oVirt. This document serves
oVirt/RHV perhaps?

2017-04-23 07:11 UTC, mykaul commented on lib/ansible/modules/cloud/ovirt/README.md
> +* All modules should start with `ovirt_`
start with -> an 'ovirt_' prefix

2017-04-23 07:11 UTC, mykaul commented on lib/ansible/modules/cloud/ovirt/README.md
> +  version 4 of the API. The version 3 of the API is not and don't have to
Rephrase: 'Version 3 of the API is not supported.'

2017-04-23 07:11 UTC, mykaul commented on lib/ansible/modules/cloud/ovirt/README.md
> +to know what common things every module must have.
things -> properties, functions, features

2017-04-23 07:11 UTC, mykaul commented on lib/ansible/modules/cloud/ovirt/README.md
> +Now, if your module must support some action handling, like for example
remove 'like'

2017-04-24 14:27 UTC, mwperina approved these changes
👍

2017-04-26 03:54 UTC, mattclay commented
CI is now passing. There was a bug in the module validator which was causing CI to fail.

2017-04-26 03:56 UTC, mattclay commented
@machacekondra New documentation should use reStructuredText instead of Markdown. We're slowly migrating away from using Markdown in most places.

2017-04-26 07:29 UTC, mattclay commented
The validate-module errors are wrong. I'll fix the validator and re-run CI.

2017-04-26 07:59 UTC, mattclay commented
The one remaining CI failure appears to be valid:

```
lib/ansible/modules/cloud/ovirt/README.rst:180:0: (python) expected an indented block
```

2017-04-26 08:44 UTC, machacekondra commented
Thanks for help @mattclay

2017-04-26 08:55 UTC, mattclay commented
/cc @dharmabumstead

2017-04-26 08:56 UTC, machacekondra commented
shipit

2017-05-03 02:15 UTC, mwperina approved these changes
👍

2017-06-06 05:59 UTC, machacekondra commented
@ryansb

2017-06-08 20:54 UTC, ryansb commented
Waiting on docs approval from @dharmabumstead

2017-06-15 08:58 UTC, dharmabumstead commented
Review in progress. ETA ~Thursday 6/15 by 6pm PDT.

2017-06-16 05:01 UTC, dharmabumstead requested changes

2017-06-16 05:01 UTC, dharmabumstead commented on lib/ansible/modules/cloud/ovirt/README.rst
> +create the basic flow of the module:
Please reword this; I'm unclear what you're trying to say here.

2017-06-17 18:18 UTC, machacekondra commented
Thank you for review, I've changed the requested paragraph.

2017-07-19 10:05 UTC, machacekondra commented
@dharmabumstead please re-review.

2017-07-25 09:47 UTC, machacekondra commented
@dharmabumstead Can you please re-review?

2017-08-22 14:03 UTC, mwperina approved these changes
Looks good to me, thanks! 👍

2017-08-22 14:03 UTC, mwperina commented
@dharmabumstead Can you please re-review?

2017-08-28 22:13 UTC, dharmabumstead approved these changes
Docs are OK with a few minor edits. Still needs core team sign off before merging. Thanks @machacekondra!

2017-08-29 00:58 UTC, merged