add ecr facts, new module_utils/aws
ansible/ansible pull request #22758
Opened 2017-03-18 00:25 UTC by tedder

##### SUMMARY
- ecs ecr facts. pretty straightforward. Get information about docker containers from your private AWS registry. Not appropriate for the existing ECR module.
- new module_utils/aws.py. This is designed to be cleaner and easier to use than ec2.py, which needs to support old boto, various call styles, etc.

Combining these into one PR because they are dependent on each other, and `ecs_ecr_facts` is a good example of aws util usage.

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
`ecs_ecr_facts` (new)

##### ANSIBLE VERSION

```
devel
```

##### ADDITIONAL INFORMATION
Examples in the module are fairly complete for running it yourself.

The aws util may not support some common authentication schemes. I'm not sure. It'll be good to have this early in the 2.4 lifecycle.

2017-03-20 14:14 UTC, bcoca requested changes

2017-03-20 14:14 UTC, bcoca commented on lib/ansible/module_utils/aws.py
> +# This code is part of Ansible, but is an independent component.
most of this already exists in ec2.py (badly named, but that is used by most aws modules)

2017-03-20 15:58 UTC, tedder commented on lib/ansible/module_utils/aws.py
> +# This code is part of Ansible, but is an independent component.
bcoca: that's what I was trying to say in the PR text. I'm trying to start a clean-sheet so old versions of py and boto (vs boto3) don't have to be supported. It's also designed to not require so much setup (variables passed around, for instance). @agaffney and @ryansb and I talked about it briefly on IRC.

2017-03-20 22:32 UTC, tedder commented
I'm hoping this module can be marked as "py3 only" or at least move compatibility up to py2.7 instead of py2.6. I believe that was the plan with Ansible 2.4.0.

2017-03-21 18:44 UTC, ryansb commented on lib/ansible/module_utils/aws.py
> +# This code is part of Ansible, but is an independent component.
Yup, the idea was to leave ec2.py, and to put new work (especially boto3 stuff) into aws.py when it scoped outside just EC2.

2017-03-21 18:45 UTC, ryansb commented on lib/ansible/module_utils/aws.py
> +# This code is part of Ansible, but is an independent component.
Though if things are a literal copy of what's in ec2.py (as CloudRetry is) I'd rather use an import so we don't duplicate all the code.

2017-03-21 19:22 UTC, tedder commented on lib/ansible/module_utils/aws.py
> +# This code is part of Ansible, but is an independent component.
[fixed]

2017-03-24 20:06 UTC, ryansb commented
Our plan for 2.4 is to support 2.6+, so you'll have to support back that far for this module.

2017-03-24 20:12 UTC, ryansb requested changes
Overall looks good, but there doesn't seem to be a way to filter thinks (such as listing images of a certain tag, etc).

2017-03-24 20:12 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/ecs_ecr_facts.py
> +import ansible.module_utils.aws as awsutils
Please use the `_` here to follow style, like `aws_utils` or `aws_common`

2017-03-24 20:12 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/ecs_ecr_facts.py
> +    ret['repo_by_name'] = {v['repositoryName']:v for v in repos}
This is a no-go in Python 2.6, so will have to be a loop.

2017-03-24 20:12 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/ecs_ecr_facts.py
> +    ret['valid_image_ids'] = {x['imageTag']:x for x in res.get('imageIds', []) if re.match(r'^[\.0-9]+$', x.get('imageTag', ''))}
Same for these, also this line is a bit much on the complexity front so would be better as a loop anyhow.

2017-04-11 19:09 UTC, tedder commented
FWIW, I haven't forgotten this. Just need a bunch of time to deal with it.

2017-07-20 09:32 UTC, tedder commented
I'm gonna close, don't have time to dress this up.

2017-07-20 09:32 UTC, closed without merging