Why: Feature to deploy monit on target host and make the module work with newer versions of monit
ansible/ansible pull request #22770
Opened 2017-03-19 12:11 UTC by prakritish

Feature to deploy monit on target host
*

This change addresses the need by:
The change allows user to specify a monit version or url of monit binary
to 'deploy' monit on target host. On specifying a version, the module
identifies the platform and architecture of the host and downloads the
required binary from mmonit.com and deploys it at the given path.

The other changes are to make this module work with newer versions of
monit. The module did not work with newer versions of monit because of
change in monit output.
*

##### SUMMARY

##### ISSUE TYPE

 - Feature Pull Request
 - New Module Pull Request
 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME

##### ANSIBLE VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

2017-03-20 14:32 UTC, bcoca requested changes

2017-03-20 14:32 UTC, bcoca commented on lib/ansible/modules/monitoring/monit.py
> +version_added: "1.3"
not sure why you are changing version here

2017-03-20 14:32 UTC, bcoca commented on lib/ansible/modules/monitoring/monit.py
> +    choices: [ "present", "started", "stopped", "restarted", "monitored", "unmonitored", "reloaded", "deployed" ]
I don't think installation should be covered by this modules, there are plenty of package management modules that are better suited for this, at worst a role that downloads and installs it

2017-03-21 10:11 UTC, prakritish commented on lib/ansible/modules/monitoring/monit.py
> +version_added: "1.3"
Reverted back to "1.2" as suggested.

2017-03-21 10:12 UTC, prakritish commented on lib/ansible/modules/monitoring/monit.py
> +    choices: [ "present", "started", "stopped", "restarted", "monitored", "unmonitored", "reloaded", "deployed" ]
Removed "deployed" and the implementation as suggested.

2017-03-21 10:22 UTC, prakritish commented
@bcoca The requested changes are in place. Please review and let me know if any further changes are needed. 

**Playbook**
```
- hosts: monitHost
  become: yes
  become_method: sudo
  vars:
    version: 5.21.0
  tasks:
  - name: Start monit if not started
    monit:
      path: "/opt/monit/bin/monit"
      config: "/etc/monitrc"
      state: started
  - name: Check service {{ ohai_machinename }} present
    monit:
      path: "/opt/monit/bin/monit"
      config: "/etc/monitrc"
      service: "{{ ohai_machinename }}"
      state: "present"
  - name: Start service apache
    monit:
      path: "/opt/monit/bin/monit"
      config: "/etc/monitrc"
      name: "apache"
      state: "started"
  - name: Reload monit configuration
    monit:
      path: "/opt/monit/bin/monit"
      config: "/etc/monitrc"
      state: "reloaded"
  - name: Stop Service apache
    monit:
      path: "/opt/monit/bin/monit"
      config: "/etc/monitrc"
      service: "apache"
      state: "stopped"
  - name: Restart apache
    monit:
      path: "/opt/monit/bin/monit"
      config: "/etc/monitrc"
      service: "apache"
      state: "restarted"
  - name: Unmonitor Service apache
    monit:
      path: "/opt/monit/bin/monit"
      config: "/etc/monitrc"
      name: "apache"
      state: "unmonitored"
  - name: Monitor Service apache
    monit:
      path: "/opt/monit/bin/monit"
      config: "/etc/monitrc"
      service: "apache"
      state: "monitored"
  - name: Stop monit
    monit:
      path: "/opt/monit/bin/monit"
      config: "/etc/monitrc"
      state: "stopped"
```
**Output:**
```
[root@prakritish1 playbooks]# ansible-playbook monit.yml

PLAY [monitHost] ***************************************************************

TASK [setup] *******************************************************************
ok: [prakritish3]

TASK [Start monit if not started] **********************************************
changed: [prakritish3]

TASK [Check service prakritish3 present] ***********************
ok: [prakritish3]

TASK [Start service apache] ****************************************************
ok: [prakritish3]

TASK [Reload monit configuration] **********************************************
changed: [prakritish3]

TASK [Stop Service apache] *****************************************************
changed: [prakritish3]

TASK [Restart apache] **********************************************************
changed: [prakritish3]

TASK [Unmonitor Service apache] ************************************************
changed: [prakritish3]

TASK [Monitor Service apache] **************************************************
changed: [prakritish3]

TASK [Stop monit] **************************************************************
changed: [prakritish3]

PLAY RECAP *********************************************************************
prakritish3 : ok=10   changed=7    unreachable=0    failed=0

[root@prakritish1 playbooks]#
```

2020-08-17 03:39 UTC, closed without merging