file module doesn't create hard link to given target directory
ansible/ansible pull request #22771
Opened 2017-03-19 17:54 UTC by snowsky

##### SUMMARY

See #22738

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

##### ANSIBLE VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

2017-03-20 14:35 UTC, bcoca requested changes

2017-03-20 14:35 UTC, bcoca commented on lib/ansible/modules/files/file.py
> +            prev_state = 'hard'
this will break other pathways as you are 'lying' to the code instead of having the code handle this particular combination correctly.

2017-03-20 17:03 UTC, mattclay commented
CI failure due to multiple integration test failures. Here's one example:

```
2017-03-19 18:02:59 The full traceback is:
2017-03-19 18:02:59 Traceback (most recent call last):
2017-03-19 18:02:59   File "/tmp/ansible_s1id7q/ansible_module_file.py", line 485, in <module>
2017-03-19 18:02:59     main()
2017-03-19 18:02:59   File "/tmp/ansible_s1id7q/ansible_module_file.py", line 403, in main
2017-03-19 18:02:59     if not (state == 'hard' and os.stat(b_path).st_ino == os.stat(b_src).st_ino):
2017-03-19 18:02:59 OSError: [Errno 2] No such file or directory: '/root/ansible_testing/hard.txt'
```

2017-03-20 18:01 UTC, snowsky commented on lib/ansible/modules/files/file.py
> +            prev_state = 'hard'
That is also my concern. It would not work for this case.

2017-03-21 02:02 UTC, snowsky commented on lib/ansible/modules/files/file.py
> +            prev_state = 'hard'
What is prev_state variable for?

2017-03-21 02:59 UTC, snowsky commented
Have to say that file module is a mess :(

2017-03-21 18:09 UTC, bcoca commented
prev_state is a bad attempt at change control, i don't disagree ti is a mess, too much was shoehorned. 

I've already reformatted the module x2 times and it is begging for a third or just a full rewrite.

2017-03-25 03:17 UTC, snowsky commented
@bcoca ready for your review please.

2017-03-27 14:44 UTC, bcoca requested changes

2017-03-27 14:44 UTC, bcoca commented on lib/ansible/modules/files/file.py
> +            changed = True
remove this line, not needed

2017-03-27 14:44 UTC, bcoca commented on lib/ansible/modules/files/file.py
> +                    changed = True
move this to under the If

2017-03-27 14:44 UTC, bcoca commented on lib/ansible/modules/files/file.py
> +                    changed = False
remove this line as it is not needed

2017-03-27 14:44 UTC, bcoca commented on lib/ansible/modules/files/file.py
> +                    module.exit_json(path=path, changed=False)
changed=changed

2017-03-27 16:42 UTC, snowsky commented on lib/ansible/modules/files/file.py
> +            changed = True
done.

2017-03-27 16:42 UTC, snowsky commented on lib/ansible/modules/files/file.py
> +                    changed = True
done.

2017-03-27 16:42 UTC, snowsky commented on lib/ansible/modules/files/file.py
> +                    changed = False
done.

2017-03-27 16:42 UTC, snowsky commented on lib/ansible/modules/files/file.py
> +                    module.exit_json(path=path, changed=False)
done.

2017-03-27 16:49 UTC, bcoca requested changes

2017-03-27 16:49 UTC, bcoca commented on lib/ansible/modules/files/file.py
> +                    module.exit_json(path=path, changed=changed)
the changed = True from 410 should be moved below this

2017-03-27 16:49 UTC, bcoca commented on lib/ansible/modules/files/file.py
> +                    module.exit_json(path=path, changed=changed)
i need to think about the if in 411, it does not look right to me ... but there are many complex combinations here

2017-03-27 18:34 UTC, snowsky commented on lib/ansible/modules/files/file.py
> +                    module.exit_json(path=path, changed=changed)
it is unchanged if the if in 411 is true.

2017-03-27 18:41 UTC, snowsky commented
If I push my changes by force, the previous reviews will be removed. How could I avoid this? Should I pull and rebase first and then squash?

2017-03-27 18:56 UTC, snowsky commented
@bcoca this should be better now. Please review. Thanks.

2017-04-10 16:20 UTC, merged