win_secedit module: adds ability to mod local security policies
ansible/ansible pull request #22775
Opened 2017-03-19 20:50 UTC by rndmh3ro

##### ISSUE TYPE

Feature Pull Request
##### COMPONENT NAME

win_secedit
##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```
##### SUMMARY

Allows users to modify local security policies via the secedit utility for example:

``` yml
    - name: Set local password age policy to 14 days
      win_secedit:
        category: System Access
        key: MaximumPasswordAge
        value: 14
```

2017-03-19 20:50 UTC, rndmh3ro commented
Migrated from https://github.com/ansible/ansible-modules-extras/pull/3214 by rndmh3ro (not original author)

2017-04-02 21:52 UTC, jborean93 commented
Hey @rndmh3ro and @defionscode I'll try and get to looking at this sometime soon, looks like a good module to have, I know I've written a once off script to do this before. There are a few things in there from a brief look that would need to be made more standard to our other Windows module and I'll add some comments for a first round look.

2017-04-02 22:09 UTC, jborean93 requested changes
This is probably enough comments for a first round check. Three major things that would need to be done would be to;
* Add check mode to the module
* Add some tests
* More of a question for us to answer in the next WUG around how do we want to handle pipelining and indenting in powershell modules. I'll raise an agenda item.

Please feel free to ask me questions around any of my comments or if you need guidance around check mode/testing.

2017-04-02 22:09 UTC, jborean93 commented on lib/ansible/modules/windows/win_secedit.ps1
> +Set-StrictMode -Version Latest
We usually set StrictMode to 2 when running a module automatically, this should be needed

2017-04-02 22:09 UTC, jborean93 commented on lib/ansible/modules/windows/win_secedit.ps1
> +        [parameter(mandatory=$true, position=0, valuefrompipelinebypropertyname=$true, valuefrompipeline=$true)][string]$FilePath
Are we able to just move this to function Get-IniFile($FilePath) to make it more python like

2017-04-02 22:09 UTC, jborean93 commented on lib/ansible/modules/windows/win_secedit.ps1
> +                        $ini.Add($curSectionName, $currentSection)
Probably want to remove an indent for these lines so they match up in each case statement

2017-04-02 22:09 UTC, jborean93 commented on lib/ansible/modules/windows/win_secedit.ps1
> +                        throw "Unidentified: $_"  # should not happen
Change to Fail-Json @{} "Error Message here" and change the error to be a bit more descriptive

2017-04-02 22:09 UTC, jborean93 commented on lib/ansible/modules/windows/win_secedit.ps1
> +        if ($ini.Keys -notcontains $curSectionName) { $ini.Add($curSectionName, $currentSection) }
Move the if body to a new line

2017-04-02 22:09 UTC, jborean93 commented on lib/ansible/modules/windows/win_secedit.ps1
> +        [parameter(mandatory=$true, position=0, valuefrompipelinebypropertyname=$true, valuefrompipeline=$true)][System.Collections.Specialized.OrderedDictionary]$ini,
Probably want more input from the other Windows guys but I don't think we want to do pipelining in the modules if we can avoid it. I believe this is so we keep a similar standard between the python and powershell ones. @jhawkesworth @dagwieers @nitzmahone?

2017-04-02 22:09 UTC, jborean93 commented on lib/ansible/modules/windows/win_secedit.ps1
> +$result = New-Object psobject @{
`$result = @{`

2017-04-02 22:09 UTC, jborean93 commented on lib/ansible/modules/windows/win_secedit.ps1
> +$category = Get-Attr $params "category" -failifempty $true
Have a look at `Get-AnsibleParam` which can be seen in other modules like `win_tempfile`. This way you can specify the object type and other options.

2017-04-02 22:09 UTC, jborean93 commented on lib/ansible/modules/windows/win_secedit.ps1
> +$key = Get-Attr $params "key" -failifempty $true
Change to `Get-AnsibleParam` as above

2017-04-02 22:09 UTC, jborean93 commented on lib/ansible/modules/windows/win_secedit.ps1
> +$value = Get-Attr $params "value" -failifempty $true
Change to `Get-AnsibleParam` as above

2017-04-02 22:09 UTC, jborean93 commented on lib/ansible/modules/windows/win_secedit.ps1
> +    Fail-Json $result "This host is joined to a Domain Controller, you'll need to modify GPO directly instead of secedit"
I don't think this should be here, in some GPO policies I've seen set definitely allowed me to change certain entries just not others. This should probably be a warning in the python document.

2017-04-03 09:10 UTC, dagwieers requested changes

2017-04-03 09:10 UTC, dagwieers commented on lib/ansible/modules/windows/win_secedit.py
> +    default: null
If parameter is required, there is no default.

2017-04-03 09:10 UTC, dagwieers commented on lib/ansible/modules/windows/win_secedit.py
> +    default: null
Same.

2017-04-03 09:10 UTC, dagwieers commented on lib/ansible/modules/windows/win_secedit.py
> +    default: null
Same.

2017-05-13 01:31 UTC, jborean93 commented
@rndmh3ro are you still willing to look into getting this merged in. I'm happy to take it on if you don't have the time as I think this would be good to have in Ansible.

2017-05-13 21:04 UTC, rndmh3ro commented
@jborean93, feel free to take this on!

2017-05-23 07:12 UTC, jhawkesworth commented
@jborean93 - sorry I couldn't make the WWG meeting.
I'd prefer to avoid pipelining in ansible powershell modules just because I think its another thing to understand.
I think splitting into 2 modules is valid - perhaps win_user_privilege and win_audit_event - I think the first one would be much more useful than the second one.  I'm less concerned about common code at the moment - eventually we will be able to share code between modules - but there's also the issue of 'findability'.  I don't think we have the ability to do a redirect in the documentation, but perhaps we could have a 'stub' win_secedit or win_secpol module which just has documentation links to win_user_privilege and win_audit_event.  If stub modules aren't acceptable, maybe just mentioning secpol and 'security policy' in the short module description is enough.

2017-05-23 07:17 UTC, jborean93 commented
No worries time zones can be quite annoying, the general consensus was to split it up into separate modules mostly focusing on the user right stuff and one to do what this PR focuses on. This is similar to how win_path and win_environment fit together.

2017-07-07 14:43 UTC, defionscode commented
Given where this has gone, should we close this particular pr?

2017-07-07 16:20 UTC, rndmh3ro commented
Yes, #26332 superseeds this.

2017-07-07 16:20 UTC, closed without merging