GCP: backend service module
ansible/ansible pull request #22857
Opened 2017-03-22 05:02 UTC by supertom

This module supports the creation and deletion of Backend Services.

##### SUMMARY

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

gcp_backendservice

##### ANSIBLE VERSION

```
ansible 2.4.0 (ans-http-lb 0f3a05413d) last updated 2017/03/22 05:00:26 (GMT +000)
  config file = /home/supertom/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]
```

##### ADDITIONAL INFORMATION
Backend Services are part of the GCP stack required for load balancing with managed services.  More on backend services can be found [here](https://cloud.google.com/compute/docs/load-balancing/http/backend-service)

2017-03-27 20:41 UTC, ryansb requested changes

2017-03-27 20:41 UTC, ryansb commented on lib/ansible/module_utils/gcp.py
> +    :rtype: ``bool``
This signature isn't right anymore - this function is `tuple(bool, error_str)`

2017-03-27 20:41 UTC, ryansb commented on lib/ansible/module_utils/gcp.py
> +    :rtype: ``bool``
Also, is there a reason this doesn't raise a ValueError with the message instead? Then you could catch and fail_json instead of having to `if` check it.

2017-03-27 20:41 UTC, ryansb commented on lib/ansible/modules/cloud/google/gcp_backend_service.py
> +def _validate_backend_params(backends):
Same here, seems a ValueError would be cleaner.

2017-03-27 20:41 UTC, ryansb commented on lib/ansible/modules/cloud/google/gcp_backend_service.py
> +def get_bes(gce, name):
Can you name this a little more verbosely? I can't unsee "get best"

2017-03-28 02:48 UTC, supertom commented on lib/ansible/module_utils/gcp.py
> +    :rtype: ``bool``
Done

2017-03-28 02:48 UTC, supertom commented on lib/ansible/modules/cloud/google/gcp_backend_service.py
> +def _validate_backend_params(backends):
Done

2017-03-28 02:50 UTC, supertom commented
@ryansb Thanks for the review.  PTAL.

2017-03-28 15:41 UTC, supertom commented on lib/ansible/modules/cloud/google/gcp_backend_service.py
> +def get_bes(gce, name):
Done.

2017-03-28 21:05 UTC, ryansb approved these changes
Two minor bits, would be fine to do in a followup PR

2017-03-28 21:05 UTC, ryansb commented on lib/ansible/modules/cloud/google/gcp_backend_service.py
> +    - Create, or Destroy a Backend Service.  See
comma?

2017-03-28 21:05 UTC, ryansb commented on lib/ansible/modules/cloud/google/gcp_backend_service.py
> +      Full install/configuration instructions for the gce* modules can
maybe spell out "Google Cloud" here since we have gc, gce, and gcp modules.

2017-03-30 20:59 UTC, merged