Removing temporary files when not proxing inside urls utils
ansible/ansible pull request #22851
Opened 2017-03-21 20:00 UTC by vccabral

##### SUMMARY
The unarchive module leaves behind files in /tmp. 

```
- name: "Download new version of the apps"
  unarchive: 
    src: "https://github.com/vccabral/ansible/archive/master.zip"
    dest: "/tmp/ansible/"
    remote_src: true
    validate_certs: true
```
After running a task like the one above, I noticed several files left behind including cert files and empty files. 

It is unknown is this is an outstanding issue. I found no documentation of ansible's unarchive module that suggests this behaviour and the mkstemp module explicitly states the user is responsible for clean up. 

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME

module_utils/urls/fetch_url

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel 4a8f2dde20) last updated 2017/03/21 15:28:04 (GMT -400)
  config file = /Users/cabralv/Documents/code/ansible-consumer-finance/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.11 (default, Dec 16 2015, 13:23:46) [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
```

##### ADDITIONAL INFORMATION
You can recreate this bug with a simple playbook.

```
- name: "Download new version of the apps"
  unarchive: 
    src: "https://github.com/vccabral/ansible/archive/master.zip"
    dest: "/tmp/ansible/"
    remote_src: true
    validate_certs: true
```

To watch the /tmp directory fill up during the execution and never get cleaned up use this command:
```
$ watch "ls -la /tmp | grep tmp"
```

2017-04-06 12:29 UTC, OrlandoSoto commented
👍

2017-08-17 18:36 UTC, jctanner requested changes

2017-08-17 18:36 UTC, jctanner commented on lib/ansible/module_utils/urls.py
> +                os.remove(tmp_ca_cert_path)
Should check if the path exists before it is removed.

2018-01-31 22:20 UTC, acrewdson commented
@jctanner Please consider closing this PR and see instead https://github.com/ansible/ansible/pull/35583, which has the fixes you requested here.

2018-02-01 15:29 UTC, samdoran commented
Closing since this is fixed in #35583

2018-02-01 15:29 UTC, closed without merging