Fix incorrect command-line parameters for Solaris
ansible/ansible pull request #22865
Opened 2017-03-22 11:12 UTC by AlexZolotarenko

##### SUMMARY

Solaris 'mount' command does not have flag to point to fstab file.
So no such flags should be passed to the command. 
Fixes #22135

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

mount module

##### ANSIBLE VERSION

```
ansible 2.2.1.0 and later 

```

##### ADDITIONAL INFORMATION

```

```

2017-08-17 18:37 UTC, calfonso commented
cc @jtyr would you mind reviewing this?

2017-08-17 22:21 UTC, jtyr requested changes
After the requested change is in place I fine it to be merged. Unfortunately I cannot verify whether Solaris doesn't really need this option. I guess we must trust the usere here.

2017-08-17 22:22 UTC, jtyr commented on lib/ansible/modules/system/mount.py
> +    if fstab_file and fstab_file != '/etc/fstab' and get_platform().lower() != 'sunos':
Please could you change it to:

```
    if (
            fstab_file and
            fstab_file != '/etc/fstab' and
            get_platform().lower() != 'sunos'):
```

2017-08-18 22:24 UTC, bcoca commented
rebuild_merge

2017-08-24 13:36 UTC, AlexZolotarenko commented on lib/ansible/modules/system/mount.py
> +    if fstab_file and fstab_file != '/etc/fstab' and get_platform().lower() != 'sunos':
Not sure if I did it correct, but it's updated according your request.

2017-08-24 13:40 UTC, jtyr commented on lib/ansible/modules/system/mount.py
> +    if fstab_file and fstab_file != '/etc/fstab' and get_platform().lower() != 'sunos':
it looks good!

2017-08-24 13:53 UTC, calfonso commented
@jtyr Any other changes requested from you?

2017-08-24 14:15 UTC, jtyr commented
Nop. I think if that works for you on Solaris then we can merge it now. @bcoca can you take care of it?

2017-08-24 14:22 UTC, merged