New module for managing AWS Datapipelines
ansible/ansible pull request #22878
Opened 2017-03-22 14:48 UTC by s-hertel

- Supports create/activate/deactivate and deletion
- Handles idempotent creation by embeding the version in the
  uniqueId field
- Waits for requested state to be reached, as Botocore doesn't
  have waiters yet for datapipelines

2017-03-22 14:48 UTC, s-hertel commented
Migrated from https://github.com/ansible/ansible-modules-extras/pull/1547 by s-hertel (not original author)

2017-03-24 10:04 UTC, wimnat commented on lib/ansible/modules/cloud/amazon/datapipeline.py
> +module: datapipeline
I would prefer `data_pipeline` over `datapipeline`

2017-03-24 10:07 UTC, wimnat commented on lib/ansible/modules/cloud/amazon/datapipeline.py
> +    choices: ['present', 'absent', 'active', 'deactive']
Should be `inactive` rather than `deactive`

2017-03-24 13:46 UTC, s-hertel commented
Thanks wimnat. When I fix this up I will also make the changes you requested [previously](https://github.com/ansible/ansible-modules-extras/pull/1547).

2017-03-28 13:10 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/datapipeline.py
> +def pipeline_status_timeout(client, dp_id, status, timeout):
Unfortunately, there seems to be no built in waiter for datapipelines - get_waiter() returns an empty list. Going to keep this as is.

2017-03-28 13:12 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/datapipeline.py
> +def pipeline_exists_timeout(client, dp_id, timeout):
As above, keeping as is since there is no built in waiter.

2017-04-11 16:42 UTC, mattclay commented
CI failure in unit tests. 5 failures for python 2.x and 15 for 3.x:

https://app.shippable.com/github/ansible/ansible/runs/18680/2/tests
https://app.shippable.com/github/ansible/ansible/runs/18680/4/console

2017-04-12 23:45 UTC, mattclay commented
CI failure in python 3.x unit tests:

https://app.shippable.com/github/ansible/ansible/runs/18770/4/tests
https://app.shippable.com/github/ansible/ansible/runs/18770/5/tests

All of the failures appear to be related:

```
>       hashed_data = hashlib.md5(json_data).hexdigest()
E       TypeError: Unicode-objects must be encoded before hashing

lib/ansible/modules/cloud/amazon/data_pipeline.py:400: TypeError
```

2017-04-19 16:27 UTC, s-hertel commented
ready_for_review

2017-05-15 12:03 UTC, ryansb requested changes

2017-05-15 12:03 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/data_pipeline.py
> +      - List of pipeline Objects
Is there a link specific to the structure of these objects? I like to include as much info about complex types in the docs as possible.

2017-05-15 12:03 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/data_pipeline.py
> +      - List of pipeline values
Same here

2017-05-15 12:03 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/data_pipeline.py
> +    assert type(status) == list
Instead of equality, I think you want to check for `isinstance` here.

2017-05-15 12:03 UTC, ryansb commented on test/units/modules/cloud/amazon/test_data_pipeline.py
> +def tear_down_pipeline(connection, module):
This sort of work is best done as a pytest fixture. With [fixtures](https://docs.pytest.org/en/latest/fixture.html) you could write it such that one fixture would set up & tear down the whole setup. 

```
@pytest.fixture
def pipeline_fixture(placeboify, objects, tags):
    connection = placeboify.client('datapipeline')
    [insert params stuff and FakeModule]
    _, result = db.create_pipeline(connection, m)
    yield {'module': m, 'connection': connection, 'pipeline_id': result['data_pipeline']['pipeline_id']}
    
    # this part runs after the test finishes, pass or fail
    dp.delete_pipeline({'name': 'ansible-test-create-pipeline', 'state': 'absent'})
```

And that would merge the setup/teardown functions into a fixture that you could use in tests like:

```
test_define_pipeline(pipeline_fixture, maybe_sleep):
    pipeline_fixture['module'].[call a method or what have you](pipeline_fixture['pipeline_id'])
```

2017-05-15 15:30 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/data_pipeline.py
> +      - List of pipeline Objects
Should I move the link on [line 37](https://github.com/ansible/ansible/pull/22878/files#diff-03217c7dfd53337741c986624bc4e7c9R37) here? I'll also add `suboptions` here to make it clearer what is expected.

2017-07-28 17:58 UTC, s-hertel commented
ready_for_review

2017-08-01 18:32 UTC, ryansb reviewed
Minor docs things, otherwise looks good.

2017-08-01 18:32 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/data_pipeline.py
> +# This file is part of Ansible
New license block: http://docs.ansible.com/ansible/latest/dev_guide/developing_modules_documenting.html#documentation-block

2017-08-01 18:32 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/data_pipeline.py
> +author: Raghu Udiyar <raghusiddarth@gmail.com> (@raags)
You can definitely add yourself here as well.

2017-08-02 16:14 UTC, s-hertel commented
@wimnat Would you please re-review this?

2017-08-03 19:03 UTC, ryansb approved these changes

2017-08-03 19:04 UTC, merged