Update AWS CloudTrail module to use boto3
ansible/ansible pull request #22884
Opened 2017-03-22 17:50 UTC by shepdelacreme

##### SUMMARY

Rewrite of the AWS CloudTrail module to support the following options/parameters that are not currently supported in the module:

- Tagging of the resource
- Enabling/disabling Multi-region trail
- Starting and stopping logging on the trail at will
- Enabling/disabling log file validation feature for delivered log files
- Enabling/disabling log file encryption using KMS key for delivered log files 
- Setting/removing an SNS Topic for log delivery notifications
- Enabling/disabling event delivery to a CloudWatch Logs log group

The boto2 modules for CloudTrail do not support the above features so this module was rewritten to use boto3.

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

lib/ansible/modules/cloud/amazon/cloudtrail.py

##### ANSIBLE VERSION

```
ansible 2.4.0 (devel 9ad62a48ab) last updated 2017/03/22 12:04:36 (GMT -400)
  config file = /Users/username/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 18 2016, 07:03:39) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### ADDITIONAL INFORMATION

```

```

2017-03-22 17:55 UTC, mattclay commented
Closing and re-opening to trigger CI.

2017-03-23 20:54 UTC, shepdelacreme commented
I'm not really sure how this process works so I'll ask. Should I rebase my changes against devel every time there is an update to devel or wait until the code is reviewed, then rebase? i.e. Is it worth the effort to have it merge ready at all times or wait till a reviewer says "yes we want this change - now go rebase"?

2017-03-23 21:02 UTC, mattclay commented
@shepdelacreme Generally you only need to rebase when there are merge conflicts with your PR, as there currently are. Most of the time updates to devel won't cause merge conflicts, but they do happen, particularly on modules which see more frequent updates.

However, if there is a question as to whether or not your PR will be accepted at all, you may want to hold off on rebasing until you've discussed your changes with the appropriate maintainers.

2017-03-23 21:39 UTC, shepdelacreme commented
@mattclay Thanks. I just squashed my commits and rebased.

I know this is a very busy project so apologies for asking but having not done this before I don't know. Do I need to reach out to specific maintainers or a specific mailing list to say "hey here is a PR for a community module that needs review" or is the preferred method to just submit the PR and wait in line. My aim in asking is to not come across as pushy and make sure I'm respecting everyone that works on this projects time!

Thanks again!

2017-03-23 22:13 UTC, mattclay commented
@shepdelacreme Take a look at the [bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md) for information on our PR workflow.

If you would like to discuss your PR, the best place is usually our #ansible-devel IRC channel on Freenode. Since this is a cloud module, you probably want to talk to @s-hertel (shertel on IRC).

2017-03-24 12:59 UTC, s-hertel commented
Hi, @shepdelacreme. Let me know if I can do anything to help you out! :) I'm excited things are being updated to use Boto3.

2017-03-24 16:22 UTC, shepdelacreme commented
@s-hertel Thanks! Let me know if you have any questions during review. It is nearly a complete rewrite but I decided to keep the interface compatible with the old module that used `state=enabled` and `state=disabled` instead of the more standard `present/absent` so any existing tasks shouldn't break upon module update.

2017-03-31 06:04 UTC, willthames commented
@shepdelacreme here to help too.

I would advise just allowing state to be present, absent, enabled or disabled. Less surprising

2017-03-31 06:05 UTC, willthames commented
bot_status

2017-03-31 06:12 UTC, willthames requested changes

2017-03-31 06:12 UTC, willthames commented on lib/ansible/modules/cloud/amazon/cloudtrail.py
> +        TrailARN:
This should be trail_arn.

The camel_dict_to_snake_dict should be used to convert boto3 objects to ansible objects before returning them through module.exit_json

2017-03-31 06:12 UTC, willthames commented on lib/ansible/modules/cloud/amazon/cloudtrail.py
> +            trail.update({'LogFileValidationEnabled': ct_params['EnableLogFileValidation']})
use `trail['LogFileValidationEnabled'] = ct_params['EnableLogFileValidation']`

2017-03-31 06:12 UTC, willthames commented on lib/ansible/modules/cloud/amazon/cloudtrail.py
> +        s3_key_prefix=dict(type='str', required=False),
`required=False` is the default, and no not required.

Same for `type=str`

2017-03-31 06:12 UTC, willthames commented on lib/ansible/modules/cloud/amazon/cloudtrail.py
> +        module.fail_json(msg=str(err))
Use standard boto3 exception handling: 

- https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/GUIDELINES.md#boto3-2

I've just noticed there's a missing `c` at the end of `traceback.format_exc()`, so just be careful  there :)

2017-03-31 19:06 UTC, shepdelacreme commented
@willthames Made the requested updates and rebased. Thanks for the review!

ready_for_review

2017-05-08 13:52 UTC, ryansb commented
cc/ @tedder

2017-05-08 19:31 UTC, tedder commented
`shipit`. Thanks for rewriting.

2017-05-10 16:49 UTC, s-hertel commented
shipit

2017-05-10 16:51 UTC, s-hertel approved these changes

2017-05-16 13:55 UTC, shepdelacreme commented
Is there a reason this hasn't automerged yet even though it has the correct number of approvals? Do I need to rebase or something?

2017-05-16 16:42 UTC, s-hertel commented
@shepdelacreme Because it touches more than just a module file.

2017-05-16 16:44 UTC, s-hertel commented
@willthames can you clear your review?

2017-05-16 16:48 UTC, s-hertel commented
bot_status
changes_requested

2017-05-16 20:44 UTC, ryansb approved these changes

2017-05-16 20:45 UTC, merged