Update playbooks_prompts.rst
ansible/ansible pull request #22910
Opened 2017-03-23 15:09 UTC by johnboy2

Clarify prompting only occurs when not in extra_vars

##### SUMMARY
Document omission of vars_prompt prompts when var in extra_vars.

##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

n/a

##### ANSIBLE VERSION

n/a

##### ADDITIONAL INFORMATION
The fact that vars_prompt doesn't actually prompt if the var was defined via CLI isn't documented. Nor is the fact that if you _want_ a conditional vars prompt, you can already do that with the built-in behavior (ie no need to resort to complicated conditional includes).

2017-03-23 19:19 UTC, bcoca commented on docs/docsite/rst/playbooks_prompts.rst
> +   Prompts for "vars_prompt" variables will be skipped for any variable that is already defined on the command line. See :ref:`_passing_variables_on_the_command_line` in the /Variables/ chapter.
or when running from a batch system (cron, tower, etc) when you don't have a tty

2017-03-27 15:28 UTC, johnboy2 commented on docs/docsite/rst/playbooks_prompts.rst
> +   Prompts for "vars_prompt" variables will be skipped for any variable that is already defined on the command line. See :ref:`_passing_variables_on_the_command_line` in the /Variables/ chapter.
Revised upstream.

2017-03-27 23:32 UTC, bcoca requested changes

2017-03-27 23:32 UTC, bcoca commented on docs/docsite/rst/playbooks_prompts.rst
> +   Prompts for individual "vars_prompt" variables will be skipped for any variable that is already defined on the command line, or when running from a non-interactive session (such as cron or Ansible
not defined in command line, but specifically 'extra-vars' which have precedence, so it makes no sense to prompt when those will override anyways. Just to make sure people don't confuse with env vars nor command line switches

2017-03-29 15:22 UTC, johnboy2 commented
Updated.

2017-03-30 03:14 UTC, dharmabumstead approved these changes

2017-03-30 03:14 UTC, dharmabumstead commented
Looks good. Thanks @johnboy2!

2017-03-30 03:14 UTC, merged