Update ec2_eni_facts to boto3
ansible/ansible pull request #22941
Opened 2017-03-24 11:38 UTC by wimnat

##### SUMMARY
Update to boto3

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
ec2_eni_facts

##### ANSIBLE VERSION
2.4

##### ADDITIONAL INFORMATION
Updated to boto3 and added return doc

2017-05-27 03:06 UTC, willthames requested changes

2017-05-27 03:06 UTC, willthames commented on lib/ansible/modules/cloud/amazon/ec2_eni_facts.py
> +        snaked_network_interfaces['tags'] = boto3_tag_list_to_ansible_dict(tag_set_copy)
Ah, it's nice that the syntax checker caught this bug.

This should be `network_interface['tags'] = boto3_tag_list_to_ansible_dict(tag_set_copy)`

2017-12-08 14:51 UTC, gundalow commented
As agreed in 2017-12-07 Core meeting, we've done bulk pep8 fixes across all modules in `devel`.

This was done in https://github.com/ansible/ansible/pull/33682 and https://github.com/ansible/ansible/pull/33690 which have been merged into `devel`. because of this you will need to rebase your PR. Thanks in advance.

2017-12-08 14:52 UTC, biomassives commented
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (100/100 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o6.sgmail.github.com ([192.254.113.101]:51745)
	by chi-server32.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1eNK0r-002laO-46
	for greg@biomassiv.es; Fri, 08 Dec 2017 08:52:29 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=Go3n57K4oJFCG03qVqjGsLjQ9DA=; b=KtaziKnWpGrdKIh7
	SUl2qjS2EQjcIbGqZyl90Lx/tKkJoE3o9maUkvRty4scz1qDFrHPP1GSosrJm2gX
	Kiwniii8hBjKlZV3nsdVn7cmbK0/j7hbwmAo+8NiCQT4NnqamJIIGUQQ/XkKO+qw
	511x7pUKRSIZHi9rb+6uucNChz0=
Received: by filter0207p1las1.sendgrid.net with SMTP id filter0207p1las1-4729-5A2AA706-15
        2017-12-08 14:51:50.328779596 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0011p1iad2.sendgrid.net (SG) with ESMTP id EGJubdFIRXKSgoiRZAUSUg
	for <greg@biomassiv.es>; Fri, 08 Dec 2017 14:51:50.218 +0000 (UTC)
Date: Fri, 08 Dec 2017 14:51:50 +0000 (UTC)
From: John R Barker <notifications@github.com>
Reply-To: ansible/ansible <reply@reply.github.com>
To: ansible/ansible <ansible@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Message-ID: <ansible/ansible/pull/22941/c350281743@github.com>
In-Reply-To: <ansible/ansible/pull/22941@github.com>
References: <ansible/ansible/pull/22941@github.com>
Subject: Re: [ansible/ansible] Update ec2_eni_facts to boto3 (#22941)
Mime-Version: 1.0
Content-Type: multipart/alternative;
 boundary="--==_mimepart_5a2aa706c9a7_26ce3f7f6f338f289034d8";
 charset=UTF-8
Content-Transfer-Encoding: 7bit
Precedence: list
X-GitHub-Sender: gundalow
X-GitHub-Recipient: biomassives
X-GitHub-Reason: subscribed
List-ID: ansible/ansible <ansible.ansible.github.com>
List-Archive: https://github.com/ansible/ansible
List-Post: <mailto:reply@reply.github.com>
List-Unsubscribe: <mailto:unsub+0042d4e2e4618c942559dab324e65ce7ac47fd30e07cd73f92cf000000011642690692a169ce0ceb70ec@reply.github.com>,
 <https://github.com/notifications/unsubscribe/AELU4r6r0jDh70w8uoowM4GiSUPfNMAoks5s-U0GgaJpZM4MoIe3>
X-Auto-Response-Suppress: All
X-GitHub-Recipient-Address: greg@biomassiv.es
X-SG-EID: ZlaDthyue/4HG+EgTb7JoZYs48JNb2iQtCcPV6oIs9VlSZYGO/UD5gFsQynZvPSjxVK+jQktxlPsb/
 TkYDgpXJSCTx1W1qY8akl/oM11lE5/Xp+Fq6+eDVQCCHjX1I5zSSl2hnTxU4WT03BIpcPAeeW5DrfR
 TEWociXykAaLS4CFDf+2kARqtwk88fZOpGfyTRDH7IZ7DkBCKtKJVbifSuRpkD4bcxRCCAjLer8h9g
 Q=

----==_mimepart_5a2aa706c9a7_26ce3f7f6f338f289034d8
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

As agreed in 2017-12-07 Core meeting, we've done bulk pep8 fixes across all modules in `devel`.

This was done in https://github.com/ansible/ansible/pull/33682 and https://github.com/ansible/ansible/pull/33690 which have been merged into `devel`. because of this you will need to rebase your PR. Thanks in advance.

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/ansible/ansible/pull/22941#issuecomment-350281743
----==_mimepart_5a2aa706c9a7_26ce3f7f6f338f289034d8
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<p>As agreed in 2017-12-07 Core meeting, we've done bulk pep8 fixes across =
all modules in <code>devel</code>.</p>
<p>This was done in <a href=3D"https://github.com/ansible/ansible/pull/3368=
2" class=3D"issue-link js-issue-link" data-error-text=3D"Failed to load iss=
ue title" data-id=3D"280202668" data-permission-text=3D"Issue title is priv=
ate" data-url=3D"https://github.com/ansible/ansible/issues/33682">#33682</a=
> and <a href=3D"https://github.com/ansible/ansible/pull/33690" class=3D"is=
sue-link js-issue-link" data-error-text=3D"Failed to load issue title" data=
-id=3D"280277734" data-permission-text=3D"Issue title is private" data-url=
=3D"https://github.com/ansible/ansible/issues/33690">#33690</a> which have =
been merged into <code>devel</code>. because of this you will need to rebas=
e your PR. Thanks in advance.</p>

<p style=3D"font-size:small;-webkit-text-size-adjust:none;color:#666;">&mda=
sh;<br />You are receiving this because you are subscribed to this thread.<=
br />Reply to this email directly, <a href=3D"https://github.com/ansible/an=
sible/pull/22941#issuecomment-350281743">view it on GitHub</a>, or <a href=
=3D"https://github.com/notifications/unsubscribe-auth/AELU4ta1AHEpzD0O07rY4=
pQjKvyfAIt1ks5s-U0GgaJpZM4MoIe3">mute the thread</a>.<img alt=3D"" height=
=3D"1" src=3D"https://github.com/notifications/beacon/AELU4srQ_CrGZr8iDyc26=
8WChjYYMnlJks5s-U0GgaJpZM4MoIe3.gif" width=3D"1" /></p>
<div itemscope itemtype=3D"http://schema.org/EmailMessage">
<div itemprop=3D"action" itemscope itemtype=3D"http://schema.org/ViewAction=
">
  <link itemprop=3D"url" href=3D"https://github.com/ansible/ansible/pull/22=
941#issuecomment-350281743"></link>
  <meta itemprop=3D"name" content=3D"View Pull Request"></meta>
</div>
<meta itemprop=3D"description" content=3D"View this Pull Request on GitHub"=
></meta>
</div>

<script type=3D"application/json" data-scope=3D"inboxmarkup">{"api_version"=
:"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"Gi=
tHub"},"entity":{"external_key":"github/ansible/ansible","title":"ansible/a=
nsible","subtitle":"GitHub repository","main_image_url":"https://cloud.gith=
ubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7b=
b5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/1434=
18/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Ope=
n in GitHub","url":"https://github.com/ansible/ansible"}},"updates":{"snipp=
ets":[{"icon":"PERSON","message":"@gundalow in #22941: As agreed in 2017-12=
-07 Core meeting, we've done bulk pep8 fixes across all modules in `devel`.=
\r\n\r\nThis was done in https://github.com/ansible/ansible/pull/33682 and =
https://github.com/ansible/ansible/pull/33690 which have been merged into `=
devel`. because of this you will need to rebase your PR. Thanks in advance.=
"}],"action":{"name":"View Pull Request","url":"https://github.com/ansible/=
ansible/pull/22941#issuecomment-350281743"}}}</script>=

----==_mimepart_5a2aa706c9a7_26ce3f7f6f338f289034d8--

2020-02-17 13:56 UTC, tremble commented
close_me

https://github.com/ansible/ansible-modules-extras/pull/2425

2020-02-17 14:05 UTC, closed without merging