Fix #22968 - Setting registry ACLs using win_acl is broken by ALL APPLICATION PACKAGES
ansible/ansible pull request #22969
Opened 2017-03-25 09:37 UTC by Novex

##### SUMMARY
Fixes #22968. The root cause is pretty much exactly the same problem which was resolved in #20555, but for registry ACLs instead.

The fix in #20555 only applied to filesystem ACLs. This PR applies the fix to both filesystem and registry ACLs.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
win_acl

##### ANSIBLE VERSION
```
ansible 2.4.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### ADDITIONAL INFORMATION
Before:
```
[root@70daada2e2f6 /]# ansible windows -m win_acl -a 'path="HKLM:\SOFTWARE" user="Administrator" type="allow" rights="ReadKey"' -vvvv
No config file found; using defaults
Loading callback plugin minimal of type stdout, v2.0 from /opt/ansible/lib/ansible/plugins/callback/__init__.pyc
META: ran handlers
Using module file /opt/ansible/lib/ansible/modules/windows/win_acl.ps1
<iis-services> ESTABLISH WINRM CONNECTION FOR USER: Administrator on PORT 5986 TO iis-services
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
EXEC (via pipeline wrapper)
iis-services | FAILED! => {
    "changed": false,
    "failed": true,
    "msg": "an error occurred when attempting to present ReadKey permission(s) on HKLM:\\SOFTWARE for Administrator - Exception calling \"Translate\" with \"1\" argument(s): \"Some or all identity references could not be translated.\""
```

After:
```
[root@70daada2e2f6 /]# ansible windows -m win_acl -a 'path="HKLM:\SOFTWARE" user="Administrator" type="allow" rights="ReadKey"' -vvvv
No config file found; using defaults
Loading callback plugin minimal of type stdout, v2.0 from /opt/ansible/lib/ansible/plugins/callback/__init__.pyc
META: ran handlers
Using module file /opt/ansible/lib/ansible/modules/windows/win_acl.ps1
<iis-services> ESTABLISH WINRM CONNECTION FOR USER: Administrator on PORT 5986 TO iis-services
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
EXEC (via pipeline wrapper)
iis-services | SUCCESS => {
    "changed": true
}
META: ran handlers
META: ran handlers
```

2017-04-29 20:58 UTC, trondhindenes commented
not sure I'm the right one to review it, I only did some very minor changes to the original.

2017-05-25 12:11 UTC, jborean93 commented
Just tested it locally on a 2016 box using a test key I manually created. Before the patch I get the same issue and after the fix it works as expected.

@dagwieers @nitzmahone @jhawkesworth are you able to review and merge when ready.

shipit

2017-05-25 14:21 UTC, schwartzmx commented
lgtm
shipit

2017-06-06 11:15 UTC, dagwieers commented
bot_status

2017-06-14 13:06 UTC, jborean93 commented
@nitzmahone are you able to have a look at this and potentially merge in if it is all good. Waiting for this to be in before writing some integration tests.

2017-06-27 00:28 UTC, jborean93 requested changes
Hey @Novex just picked up on one more issue, hoping to get this in before the next 2.3 RC.

2017-06-27 00:28 UTC, jborean93 commented on lib/ansible/modules/windows/win_acl.ps1
> +    ForEach($rule in $objACL.Access){
You have another ForEach loop on line 287, are you able to remove one of them?

2017-07-11 00:07 UTC, jborean93 commented
@Novex I've made the changes in this PR plus a minor fix in https://github.com/ansible/ansible/pull/26629. It has been cherry picked to 2.3 and will be available when 2.3.3 is released down the track.

2017-07-11 00:07 UTC, closed without merging