Add support for Elastic EBS Volumes. Fixes #21588
ansible/ansible pull request #22978
Opened 2017-03-26 09:05 UTC by WooDzu

Fixes #21588

##### SUMMARY

Currently it is possible to create, detach, attach and remove EBS volumes.
This PR add support for modifying existing Elastic EBS Volumes either using volume's 'id' directly or by specifying both 'instance_id' with 'device_name'.
This is an important addition since it does not cause downtime on the instance if volume is already attached but it sends `modify_volume` request through boto3 instead.

##### ISSUE TYPE
 - Feature Pull Request
 - Bugfix Pull Request

##### COMPONENT NAME
ec2_vol module

##### ANSIBLE VERSION

```
ansible 2.4.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/etc/ansible/library']
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### ADDITIONAL INFORMATION

The traditional way of extending volumes was to stop ec2 instance, create new (updated) volume snapshot, create a new (extended) volume from the snapshot, detach old volume, attach the new volume back to the instance and start it. This traditional approach, however, is current not supported in Ansible since the ec2_vol module prevents specifying both `volume_size` and `snapshot_id` at the same time:

```python
if volume_size and (id or snapshot):
        module.fail_json(msg="Cannot specify volume_size together with id or snapshot")
```
This PR covers fixing the above limitation as well.

##### USE CASES AND EXAMPLES
```yaml
# Update existing volume using volume id
- ec2_vol:
    id: "{{ volume_id }}"
    volume_size: "{{ new_volume_size }}"
    volume_type: io1
    iops: "{{ new_iops }}

# Extend existing volume using instance and device_name
- ec2_vol:
    volume_size: "{{ new_volume_size }}"
    volume_type: gp2
    instance: "{{ an_instance_id }}"
    device_name: /dev/sdf

# Create new volume from snapshot using extended size and attach to existing instance
- ec2_vol:
    snapshot: "{{ a_snapshot_id }}"
    volume_size: "{{ new_volume_size }}"
    volume_type: gp2
    instance: "{{ an_instance_id }}"
    device_name: /dev/sda1
```

##### LIMITATIONS

There are some caveats to be noted upon modifying volumes:

* Most importantly, only one modification is allowed per volume within 6 hours
* Modification changes state of a volume to 'modifying' for a few seconds and IO is completely stopped during that time. Then it enters 'optimizing' state and IO resumes. I'm still waiting for an answer from the AWS team, whether it is safe to resize the filesystem while a volume is 'optimizing'
* Modifications of magnetic volumes, aka 'standard', are unsupported in either direction

The latter has impact on existing ansible configurations since it is not possible to modify 'standard' volumes, and this is the default in ec2_vol. The API will refuse any change to/from 'standard' volume.

2017-04-05 15:16 UTC, s-hertel requested changes

2017-04-05 15:16 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/ec2_vol.py
> +    HAS_BOTO3 = True
You can import HAS_BOTO3 from ansible.module_utils.ec2 instead.

2017-04-05 15:16 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/ec2_vol.py
> +        module.fail_json(msg="Can't authorize connection - "+str(e))
You could use traceback here. You'll need to import it too. https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/GUIDELINES.md#exception-handling

2017-04-05 15:16 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/ec2_vol.py
> +            module.fail_json(msg=str(e))
Add a comment here (such as "Failed to modify volume") to help someone figure out where the issue is and use traceback here too to help give some debugging clues, please.

2017-04-05 15:16 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/ec2_vol.py
> +    if volume_size and id:
snapshot and volume_size can be specified together? Did you mean to remove id, not snapshot? But can you change this to use mutually_exclusive while you're here? i.e. 
module = AnsibleModule(argument_spec=argument_spec,
                                          mutually_exclusive=[(volume_size, snapshot)])

2017-04-09 06:26 UTC, WooDzu commented
Thanks for the review! I should be able to provide requested updates shortly.

2017-04-09 06:50 UTC, WooDzu commented on lib/ansible/modules/cloud/amazon/ec2_vol.py
> +    if volume_size and id:
Good point. I assume it is safe to remove the condition.

2017-04-09 08:58 UTC, willthames commented
Looks pretty good to me following the revisions. I'm not 100% convinced by the halfway port to boto3 (I'd rather the module was fully converted), but can understand limiting the scope of the change.

2017-04-09 09:25 UTC, WooDzu commented
Hi @willthames and thanks for looking into revised updates. I agree that a move to boto3 is absolutely reasonable and will have to happen (counted 10 places in ec2_vol using old boto), however, would it be considered a breaking change given the required library changes? Alternative approach could be implementing both boto3 and the legacy boto as a failover. Is there a general RFC for moving the aws modules towards boto3

2017-04-09 23:11 UTC, willthames commented
The [guidelines](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/GUIDELINES.md) could perhaps still be clearer, but basically, moving away from boto is a work in progress - as big changes are made to modules, we'll move the modules across if it makes sense. At some point it might be the case that people don't even need to have boto installed.

The main goal is to try and avoid breaking change from a usage point of view (which really means that return values often need translating) - so if users can't tell the difference, other than the need for boto3, then you've succeeded.

2017-04-10 08:16 UTC, WooDzu commented
That makes a lot of sense. I will be happy to migrate ec2_vol to boto3 while on this. Let me know if that is ok.

2017-04-22 10:15 UTC, WooDzu commented
What is needed to get this going?

2017-05-14 11:57 UTC, wimnat commented
@WooDzu i would update this PR to include full boto3 rewrite

2018-11-30 19:20 UTC, nitzmahone commented
This should be brought to an AWS Working Group meeting if it's still desired behavior...

2018-11-30 22:11 UTC, s-hertel commented
This would be a nice feature to have. This module needs to be ported to boto3 (and have tests added) rather than supporting both boto and boto3. There is a PR working on that, though it hasn't had any activity for some time https://github.com/ansible/ansible/pull/45500. @WooDzu If you (or anyone else wishing for this PR) need some help porting this module or writing tests feel free to ping me (handle shertel) or the general #ansible-aws working group on freenode. I'd be happy to help out however I can. This document also has some helpful information on using boto3 and AnsibleAWSModule https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/GUIDELINES.md#guidelines-for-aws-modules.  I'm closing this for the time being as it isn't an implementation we've been comfortable to merge, but please reopen it when you have time to work on it.

2018-11-30 22:11 UTC, closed without merging