[WIP] Inventory refactor
ansible/ansible pull request #23001
Opened 2017-03-27 14:14 UTC by bcoca

##### SUMMARY

Implementing https://github.com/ansible/proposals/issues/41

- Move from hardcoded 'options' to real plugins (ini, script and yaml as minimal requirements)
- Allow multiple inventories to be specified
- Allow inventory plugins to use the configured cache plugin
- Transition from inventory scripts to plugins (script plugin will exist for backwards compatibility)
- Simplify logic (currently it is duplicated a lot, specially in plugins)
   * Defer data loading to 'data loader' and variable management to 'variable manager'
   * Fold in vars "inventory" plugins

##### ISSUE TYPE

 - Feature Pull Request
 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME

inventory

##### ANSIBLE VERSION

```
2.4
```

##### ADDITIONAL INFORMATION

```

```

2017-04-06 18:03 UTC, mattclay commented
Closing and re-opening to trigger CI.

2017-04-06 18:10 UTC, abadger commented on lib/ansible/plugins/inventory/__init__.py
> +class BaseInventoryPlugin(object):
Make this an abstractbaseclass so we make a well-defined interface.  (See plugins/connection/__init__.py for an example)

2017-04-06 18:15 UTC, bcoca commented on lib/ansible/plugins/inventory/__init__.py
> +class BaseInventoryPlugin(object):
I started that way, but since some of the methods do actually implement code I thought it was not appropriate anymore.

2017-04-07 20:41 UTC, mattclay commented
Multiple CI failures in integration tests, including timeouts like this one:

https://app.shippable.com/github/ansible/ansible/runs/18454/18/console

Where prior to the timeout an error occurs:

```
2017-04-07 18:50:23 TASK [setup_postgresql_db : install rpm dependencies for postgresql test] ******
2017-04-07 18:50:23 Traceback (most recent call last):
2017-04-07 18:50:23   File "/usr/lib/python2.7/multiprocessing/queues.py", line 266, in _feed
2017-04-07 18:50:23     send(obj)
2017-04-07 18:50:23 PicklingError: Can't pickle <class '/root/ansible/lib/ansible/plugins/inventory/group_host_vars.InventoryModule'>: import of module /root/ansible/lib/ansible/plugins/inventory/group_host_vars failed
```

Then execution hangs for about 55 minutes until the job is terminated.

2017-04-18 10:30 UTC, pilou- commented on CHANGELOG.md
> +	- Inventory classes have been split to allow for better management and dedupication
s/dedupication/deduplication/

2017-04-18 10:30 UTC, pilou- commented on CHANGELOG.md
> +	- group_vars/host_vars loading is now a plugin and can be overriden (for inventory)
s/overriden/overridden/

2017-04-18 10:30 UTC, pilou- commented on docs/docsite/rst/intro_inventory.rst
> +Be aware that this is only a convinient way to apply variables to multiple hosts at once, even though you can target hosts by group, variables are always flattened to the host level before a play is
s/convinient/convenient/

2017-04-18 10:30 UTC, pilou- commented on docs/docsite/rst/intro_inventory.rst
> +Child groups have a couple of properties to note, first, any host that is member of a child group is automatically a member of the parten group.
s/parten/parent/

2017-04-18 10:30 UTC, pilou- commented on lib/ansible/plugins/inventory/ini.py
> +        - Anything found outside a section is considerd an 'ungrouped' host.
s/considerd/considered/

2017-04-18 10:30 UTC, pilou- commented on lib/ansible/plugins/inventory/__init__.py
> +    Returnes True if the given line contains a pattern, else False.
s/Returnes/Returns/

2017-04-18 10:30 UTC, pilou- commented on lib/ansible/plugins/inventory/__init__.py
> +    if '[' in line:
`return '[' in line` could be used.

2017-04-18 10:30 UTC, pilou- commented on lib/ansible/plugins/inventory/__init__.py
> +        ''' Verify if file is usable by this plugin, base does minimal accesability check '''
s/accesability/accessability/

2017-04-18 10:30 UTC, pilou- commented on lib/ansible/parsing/dataloader.py
> +        if os.path.exists(b_path):
`os.walk` could be used here.

2017-04-18 10:30 UTC, pilou- commented on lib/ansible/inventory/__init__.py
> +        if len(results) == 0 and pattern in C.LOCALHOST:
`if not results` and `results.append(implicit)` could be used.

2017-04-18 10:30 UTC, pilou- commented on lib/ansible/inventory/__init__.py
> +        self._inventory_processors = {} # for modifyng inventory
s/modifyng/modifying/

2017-04-18 10:30 UTC, pilou- commented on lib/ansible/inventory/__init__.py
> +                display.warning("Skipping invalid hostname: %s" % to_text(h))
`h` could be an empty string, therefore `%r` could be used here instead of `%s`.

2017-04-18 10:30 UTC, pilou- commented on lib/ansible/inventory/__init__.py
> +                        parsed = True
`parsed` should not be set here.

2017-04-18 10:30 UTC, pilou- commented on lib/ansible/inventory/__init__.py
> +                        if i.startswith('.') and not i.startswith('./') or \
Isn't `not i.startswith('./')` always `True` ?

2017-04-27 03:47 UTC, mattclay commented
CI is timing out on many tests due to hanging after an exception is raised:

```
2017-04-27 00:52:31 TASK [loops : debug] ***********************************************************
2017-04-27 00:52:31 Traceback (most recent call last):
2017-04-27 00:52:31   File "/usr/lib64/python2.7/multiprocessing/queues.py", line 266, in _feed
2017-04-27 00:52:31     send(obj)
2017-04-27 00:52:31 PicklingError: Can't pickle <class '/root/ansible/lib/ansible/plugins/inventory/group_host_vars.InventoryModule'>: import of module /root/ansible/lib/ansible/plugins/inventory/group_host_vars failed
```

@bcoca Please keep an eye on CI after pushing a commit to this PR and cancel the run if it hangs. Otherwise it ends up tying up ~20 nodes on Shippable for an hour.

2017-05-10 17:15 UTC, dharmabumstead requested changes

2017-05-10 17:15 UTC, dharmabumstead commented on CHANGELOG.md
> +  you'll need to install Python-2.6 or better there or run Ansible-2.3 until you can upgrade the system.
s/there/on the managed system

2017-05-10 17:15 UTC, dharmabumstead commented on docs/docsite/rst/intro_inventory.rst
> +Not only is this inventory configurable, but you can also use multiple inventory files at the same time and also
Suggest removing the last instance of the word 'also'

2017-05-10 17:15 UTC, dharmabumstead commented on docs/docsite/rst/intro_inventory.rst
> +Be aware that this is only a convenient way to apply variables to multiple hosts at once, even though you can target hosts by group, variables are always flattened to the host level before a play is
Please change the comma after the word "once" to a semicolon or split this into two sentences.

2017-05-10 17:15 UTC, dharmabumstead commented on docs/docsite/rst/intro_inventory.rst
> +Child groups have a couple of properties to note, first, any host that is member of a child group is automatically a member of the parent group.
Suggest changing this to a bulleted list, or ending the sentence at the word "note"

2017-05-13 03:28 UTC, mattclay commented
Network tests (now that they've been restored in CI) are failing on this PR:

```
2017-05-13 03:18:43 TASK [vyos_command : test contains operator] ***********************************
2017-05-13 03:18:43 task path: /root/src/github.com/ansible/ansible/test/integration/targets/vyos_command/tests/cli/contains.yaml:4
2017-05-13 03:18:43 fatal: [vyos-1_1_0]: FAILED! => {
2017-05-13 03:18:43     "failed": true, 
2017-05-13 03:18:43     "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'cli' is undefined\n\nThe error appears to have been in '/root/src/github.com/ansible/ansible/test/integration/targets/vyos_command/tests/cli/contains.yaml': line 4, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: test contains operator\n  ^ here\n"
2017-05-13 03:18:43 }
```

This is the 2nd CI run where I've seen it fail like this. The same test is currently passing in devel, so it's possible something in this PR is responsible. /cc @gundalow

2017-05-13 06:46 UTC, gundalow commented
`cli` should be defined in `test/integration/group_vars/vyos.yaml`

2017-05-13 07:26 UTC, resmo commented on lib/ansible/cli/__init__.py
> +            parser.add_option('-i', '--inventory-file', dest='inventory', action="append",
since inventory can also be a directory, `--inventory-file` is misleading. Add another alias e.g.`--inventory-dir or `--inventory-path`?

2017-05-13 07:45 UTC, resmo commented on lib/ansible/cli/__init__.py
> +            parser.add_option('-i', '--inventory-file', dest='inventory', action="append",
after a short review of the whole PR, it would even call it just `--inventory` as it is not limited to files and dirs or paths anymore.

2017-05-14 18:16 UTC, bcoca commented on lib/ansible/cli/__init__.py
> +            parser.add_option('-i', '--inventory-file', dest='inventory', action="append",
it never was, since 'host list' was always accepted. I'll add it and make note of deprecating `--inventory-fie`

2017-05-14 18:30 UTC, bcoca commented
@mattclay  @gundalow  the test command passes `-i inventory.networking` but i only see inventory.network existing. Warning message indicates the test has no inventory so only localhost is avialable, which would not trigger reading the group_vars, hence the 'undefined'.

2017-05-15 05:55 UTC, mattclay commented on test/runner/lib/executor.py
> +        filename = 'test/integration/inventory.network'
This inventory filename (and the following one) should not be changed.

The file `test/integration/inventory.network` already exists and is used by the old tests. The file `test/integration/inventory.networking` is used by `ansible-test` and is generated at the time tests are run.

2017-05-15 16:52 UTC, bcoca commented on test/runner/lib/executor.py
> +        filename = 'test/integration/inventory.network'
after rename it finds inventory, w/o it .. it doesn't

2017-05-15 16:54 UTC, bcoca commented on test/runner/lib/executor.py
> +        filename = 'test/integration/inventory.network'
reverted change, but it goes back to not finding the inventory

2017-05-16 10:15 UTC, mattclay commented
I don't see a warning about missing inventory in the latest test run. I do see a message indicating the inventory was found:

```
Parsed /root/src/github.com/ansible/ansible/test/integration/inventory.networking inventory source with ini plugin
```

2017-05-16 17:46 UTC, mattclay commented
The group vars in `vyos.yaml` aren't being loaded. It appears the vars are only loaded if they're defined using ini format.

2017-05-16 20:08 UTC, bcoca commented
vars are being loaded .. just not given correctly to vars manager in this case

2017-05-23 21:16 UTC, merged

2017-09-15 18:14 UTC, abadger commented on lib/ansible/plugins/inventory/__init__.py
> +class BaseInventoryPlugin(object):
Sorry, didn't notice your reply until now.  Having methods (even abstractmethods) implement actual code is one of the features of AbstractBaseClasses.

2017-10-22 05:46 UTC, sagarising commented
Is this fix available in stable 2.4 ?

2017-10-22 18:09 UTC, tima commented
The APIs were added 2.4. Porting a bunch of inventory scripts to plugins is on the roadmap for 2.5. 

It’s not a fix really. The inventory scripts work perfectly fine as is. Plugins will provide an improved and more consistent experience across all inventory sources.