Add rundeck_acl_policy module
ansible/ansible pull request #23025
Opened 2017-03-28 08:56 UTC by nerzhul

##### SUMMARY

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

rundeck_acl_policy

##### ANSIBLE VERSION

```
2.2.1.0
```

##### ADDITIONAL INFORMATION

This module add an ansible interface to rundeck permitting to manage rundeck ACLs dynamicly through rundeck API.
Rundeck is a nice frontend tool which can trigger tasks on events (API, periodic, at like), but ACLs are very static in configuration files and rundeck doesn't reload them. API module permits to dynamicly change ACLs.

```
TASK [rundeck : RUNDECK_ACL_POLICY | Manage rundeck projects] ******************
ok: [RUNDECK001] => (item={u'policy': {u'context': {u'application': u'rundeck'}, u'description': u'Admin, all access.', u'for': {u'project': [{u'allow': u'*'}], u'resource': [{u'allow': u'*'}], u'storage': [{u'allow': u'*'}], u'project_acl': [{u'allow': u'*'}]}, u'by': {u'group': u'ops'}}, u'name': u'admin_all_app_rundeck'})
ok: [RUNDECK001] => (item={u'policy': {u'context': {u'project': u'.*'}, u'description': u'Admin, all access.', u'for': {u'node': [{u'allow': u'*'}], u'job': [{u'allow': u'*'}], u'resource': [{u'allow': u'*'}], u'adhoc': [{u'allow': u'*'}]}, u'by': {u'group': u'ops'}}, u'name': u'admin_all'})
changed: [RUNDECK001] => (item={u'policy': {u'context': {u'application': u'rundeck'}, u'description': u'Company users project access', u'for': {u'project': [{u'match': {u'name': u'Plateform.*'}, u'allow': [u'read']}]}, u'by': {u'username': [u'john.doe', u'karl.johnson', u'jack.bauer'], u'group': [u'devs']}}, u'name': u'etai_project_access'})
```

2017-03-28 09:19 UTC, gundalow commented on lib/ansible/modules/web_infrastructure/rundeck_acl_policy.py
> +            token=dict(required=True, type='str'),
Please add ` , no_log=True` so secret things are masked from user output

2017-03-28 09:23 UTC, nerzhul commented on lib/ansible/modules/web_infrastructure/rundeck_acl_policy.py
> +            token=dict(required=True, type='str'),
oh yeah, i missed it

2017-03-28 13:44 UTC, bjolivot commented
Great work
shipit

2017-04-06 15:07 UTC, jctanner commented
shipit

2017-04-06 15:26 UTC, nerzhul commented
bot_status

2017-04-11 12:13 UTC, bjolivot commented
shipit

2017-04-11 12:18 UTC, resmo requested changes

2017-04-11 12:18 UTC, resmo commented on lib/ansible/modules/web_infrastructure/rundeck_acl_policy.py
> +changed:
this is a common return, please remove it.

2017-04-11 12:18 UTC, resmo commented on lib/ansible/modules/web_infrastructure/rundeck_acl_policy.py
> +            state=dict(required=True, type='str', choices=['present', 'absent']),
it is common to have the default `state=present`. Consider it for consistency reasons across modules. But it is not a blocker.

2017-04-11 12:18 UTC, resmo commented on lib/ansible/modules/web_infrastructure/rundeck_acl_policy.py
> +    if module.params["policy"] is None and module.params["state"] == "present":
this is a common pattern and there is some code which does the same in basic module_utils. e.g. https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/exoscale/exo_dns_record.py#L394 

FYI

2017-04-11 12:20 UTC, bjolivot commented
bot_status

2017-04-11 13:09 UTC, nerzhul commented
@resmo updated !

2017-04-11 14:21 UTC, bjolivot commented
shipit

2017-04-11 14:39 UTC, bjolivot commented
shipit

2017-04-11 14:52 UTC, resmo approved these changes

2017-04-11 14:53 UTC, resmo commented
shipit

2017-04-28 14:50 UTC, merged

2017-04-28 14:50 UTC, abadger commented
I see enough shipits from people that I'm going to merge this (I know the bot is doing the right thing by resetting the shipit count each time changes are made but I'm trusting that the reviewers are just seeing the code improve.)

A few *really* minor notes that are not blockers:
* Usually we use actual comments for the license headers instead of docstrings.  docstrings would be visible as the module's help() if someone were to import the module in python and also take up memory at runtime whereas comments do not.
* We try to avoid using "_" as an identifier.  This is because we may one day want to localize the messages in our code.  gettext convention is to use "_" as the name of the function which both marks translatable strings and replaces the strings with their translated values.

Just some things to change when you next need to make changes to the module.

2017-04-28 14:51 UTC, abadger commented
Merged to devel