Replaced deprecated option autosubscribe with the new one called auto…
ansible/ansible pull request #23034
Opened 2017-03-28 13:47 UTC by mliljedahl

##### SUMMARY

Fixes #23014 by replacing deprecated option "--autosubscribe" with the new one called "--auto-attach". Pull requests also holds a refresh option for refreshing subscription after adding a new one.

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME
redhat_subscription

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

2017-04-18 08:29 UTC, Akasurde requested changes

2017-04-18 08:29 UTC, Akasurde commented on lib/ansible/modules/packaging/os/redhat_subscription.py
> +                args.append('--auto-attach')
Could you please update documentation and examples to reflect these changes ?

2017-04-18 08:29 UTC, Akasurde commented on lib/ansible/modules/packaging/os/redhat_subscription.py
> +    def refresh(self):
Is this related  to auto-attach option ? IMHO, this will go in different PR.

2017-04-18 08:29 UTC, Akasurde commented on lib/ansible/modules/packaging/os/redhat_subscription.py
> +            refresh=dict(default=False,
IMHO, this will go in different PR.

2017-04-18 08:29 UTC, Akasurde commented on lib/ansible/modules/packaging/os/redhat_subscription.py
> +    refresh = module.params["refresh"]
Add this to different PR.

2017-04-18 08:29 UTC, Akasurde commented on lib/ansible/modules/packaging/os/redhat_subscription.py
I think, we can add `autoattach` as module parameter with documentation and examples.

2017-04-18 08:29 UTC, Akasurde commented on lib/ansible/modules/packaging/os/redhat_subscription.py
> +                if refresh:
This can be moved to different PR.

2017-05-12 04:33 UTC, Akasurde commented
@mliljedahl Are you still working on this ?

2017-05-19 07:09 UTC, gundalow commented
@mliljedahl Hi, is this something you still have time, if not someone else could possibly take the PR and continue the work?

2017-09-26 13:48 UTC, mkrizek commented
Taking over in https://github.com/ansible/ansible/pull/30927, thanks @mliljedahl!

2017-09-26 13:48 UTC, closed without merging