add uncompress module
ansible/ansible pull request #23048
Opened 2017-03-28 17:47 UTC by Jmainguy

##### SUMMARY
This adds the uncompress module, for people who wish to uncompress things like .gz or .bz2 or .xz which are not archives, and would not be appropriate for the unarchive module.

##### ISSUE TYPE
 - Feature Pull Request
##### COMPONENT NAME

./lib/ansible/modules/files/uncompress.py
./lib/ansible/plugins/action/uncompress.py

##### ANSIBLE VERSION
Latest Devel

```
[jmainguy@jmainguy-fedora test]$ ansible -i hosts all -m uncompress -a "src=forge.tar.gz dest=/tmp/forge.tar2" -u root
ns1.example.com | SUCCESS => {
    "changed": true
}
[jmainguy@jmainguy-fedora test]$ ansible -i hosts all -m uncompress -a "src=forge.tar.gz dest=/tmp/forge.tar2" -u root
ns1.example.com | SUCCESS => {
    "changed": false
}

```

2017-03-28 17:48 UTC, Jmainguy commented
See https://github.com/ansible/ansible-modules-extras/pull/1301 and https://github.com/ansible/ansible/pull/13352 for previous discussion

2017-03-29 19:04 UTC, Jmainguy commented
@ansibot ready_for_review

2017-03-30 00:55 UTC, dagwieers commented
I thought we were going to use uncompress as a pure-python implementation for both compressed files as well as archives ? Just like we already support both compressed files as well as archives in the compress module.

2017-03-30 19:41 UTC, Jmainguy commented
I am just behind the times and got reminded to resubmit this recently. If discussion has been agreed to replace unarchive with compress and uncompress, then I can get behind that.

@dagwieers Got a link to the compress module? I looked on https://docs.ansible.com/ansible/list_of_files_modules.html and search quickly for open PRs on here for compress and did not find it. 

I am shelling out to run file on the file to see which program to uncompress it with, I can look into replacing that with pure python.

Originally I had to support python 2.4, but with ansible 2.4 that is no longer the case, so I can go back and rewrite the xz section to be pure python now I believe.

Is there an uncompress module already being worked on I need to roll this into? Or do I just need to add the unarchive features as well to this?

2017-07-05 23:17 UTC, dagwieers commented
I would like to see this module support .tar, .tar.gz, .tar.bz2, tar.xz and .zip files too. So that we can deprecate `unarchive` over time.

2017-07-16 12:12 UTC, robinro commented
I'd rather add support in `unarchive` to support non-archives. Unarchive is widely used and I see no reason to deprecate it.

2017-07-16 12:20 UTC, dagwieers commented
@robinro **unarchive** is unmaintainable and full of issues we cannot fix. We need a pure-python implementation, and it can't be a drop-in replacement. So if there is someone around who still wants to spend effort on unarchive (and scraping command output and lack of idempotency, etc..), be my guest, but the consensus here  is that it's a dead cause.

2017-07-16 12:49 UTC, robinro commented
@dagwieers I'm all for idempotency and pure-python implementations.
Why can't we make a drop-in replacement? It should be able to reimplement the most common unarchive usecases and I'd rather break some rare edgecases than throw away the module and force all users to rewrite their playbooks.
With a quick look at the code I don't see gamestopers for a pure-python replacement. One could also incrementally move over by implementing the most common cases first and using the old code as fallback when other arguments exist.

Is there documentation on the previous discussions? The issues linked above mention unarchive in a good light.

2017-07-16 12:50 UTC, robinro requested changes
IMO this should be part of `unarchive` instead of a seperate module.

2017-07-16 16:42 UTC, dagwieers commented
@robinro The behavior will be different, unarchive overwrite all files everytime (unless it expects no change). This detection is very weak since it scrapes gtar output for only a limited set of messages. Besides that it fails to work on systems without gtar (many reports for those, people feeling left out that e.g. BSD tar is not supported). Furthermore `extra_opts` cannot be supported and it was the most-requested option, the way `exclude` works in gtar is very unusual and specific (which in itself is a problem since unzip and gtar are so different) and the many quirks.

So people expecting the old behavior with a variety of options, using a pure-python implementation. Good luck with that. But if you like to support it, fine by me. In my opinion, introducing a new module and giving people time to migrate is the easiest (both for getting the module up to speed, as well as making sure users can opt-in or opt-out over a period of time and supporting them). We don't have to deprecate at the initial release either, we could start doing it when we're confident **uncompress** fits all use-cases. I don't think you can do a big-bang swap, because you will only know what you break if it ships in a new release.

One reason we couldn't do a pure-python implementation that was feature-complete was the limitations of the pure-python gz, xz, bz2 implementations, but I think with the removal of python 2.4 and 2.5 this is no longer a problem.

2017-09-27 21:25 UTC, ecv commented
@dagwieers' insistence that archives are not files is anti-Unix and simply wrong. Unarchive *as a verb* should have no trouble with files, everything is a file. The module being trash and needing replacement with pure Python is a separate issue, and I endorse this PR, but I object to the archive-vs-file distinction as artificial and borne of a misunderstanding of Unix and filesystems. 

https://en.wikipedia.org/wiki/Everything_is_a_file

2017-09-27 21:29 UTC, dagwieers commented
@ecv And where exactly did I say that archives are not files ? What nonsense is this.

2017-10-19 22:38 UTC, twedta commented
Is there a timeline for this PR? Per https://github.com/ansible/ansible-modules-core/issues/3241, dagwieers has demurred on maintaining unarchive and it is now unmaintained with the bug mentioned in 3241 still outstanding.  Please advise.

2019-03-17 09:52 UTC, teadur commented
Two years since the start of this PR do we have hope for getting it merged in any timeframe ?
Seems to be a bit fail that ansible users have to use shell commands to extract bz/gz compressed archives.

2020-04-07 23:13 UTC, colans commented
@robinro Given the previous maintainers [comments above](https://github.com/ansible/ansible/pull/23048#issuecomment-315621056), I think it's fair to say that this no longer needs revision, and can be merged.

Or is there anything else that needs to be done here?  Please provide us with an update so that we can keep moving this forward.  Thanks!

2020-08-20 09:44 UTC, Akasurde commented
Hi @Jmainguy, Thank you very much for your interest in Ansible. This plugin/module is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.general<br><br>If you have further questions please stop by IRC or the mailing list:<br><br>* IRC: #ansible on irc.freenode.net<br>* mailing list: https://groups.google.com/forum/#!forum/ansible-project<br><br>needs_info<br>

2020-08-20 09:44 UTC, closed without merging