win_command: Correctly handle command arguments
ansible/ansible pull request #23055
Opened 2017-03-28 20:23 UTC by dagwieers

I am not convinced that how the module works now is what we expect. For instance the following task fails with a "No such file or directory" error because of "dir":

```yaml
  - win_command: dir C:\
```

With this PR it would work like this:

```yaml
  - win_command: dir C:\
    args:
      executable: cmd
```

IMO **win_command** should default to use `cmd.exe`, whereas **win_shell** uses `powershell` by default.

This fixes #23019

##### SUMMARY

##### ISSUE TYPE

 - Feature Pull Request
 - New Module Pull Request
 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME

##### ANSIBLE VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

2017-03-28 21:30 UTC, nitzmahone commented
If I read this right, you just turned `win_command` into `win_shell`- IIRC the only reason that `command` *has* `executable` is because it shares its impl with `shell`.

2017-03-28 21:31 UTC, nitzmahone commented
There shouldn't be an executable- if anything, we'd just use `CreateProcess` directly...

2017-03-28 21:32 UTC, nitzmahone commented
Can you describe an actual thing that this fixes?

2017-03-28 21:36 UTC, dagwieers commented
We don't just concat all the arguments together in a large string, when the arguments should be the original array. (If you read the issue, you'd know).

I added executable because:
- the command module allows the same thing, and it is very convenient (rather than doing `cmd /c "foo bar"`)
- it is now using powershell to run a command, whereas I would have expected it using cmd.exe instead

2017-03-28 21:38 UTC, nitzmahone commented
Ah, I missed the bug report. Yeah, this isn't the way to fix that- `command` is basically "run a process", so `win_command` should remain the analogue to that, not "use cmd"- that'd be `win_shell` with executable == `cmd.exe`. I delegated the command line parsing to the Win32 `CommandLineToArgvW` API function (which IIRC is exactly what cmd.exe does, too), so it's possible that there's something else that's breaking the parsing that we might want to fix.

2017-03-28 21:40 UTC, dagwieers commented
@nitzmahone This is the fix: https://github.com/ansible/ansible/pull/23055/files#diff-2e1e53e798f59df98c4fd5a175af0c3eR127

2017-03-28 21:41 UTC, dagwieers commented
Still, I think it is preferable to add `executable: cmd` rather than wrap everything in `cmd /c "foo bar"` which makes it harder to quote correctly.

2017-03-28 21:45 UTC, nitzmahone commented
But if you want to exec under a shell, use `win_shell`- it already does all that.

The actual fix (sans all the executable stuff) looks fine, but IIRC there's a reason I didn't do it that way. It might be that I was having trouble with pathing or something- I ran into that with the exec wrapper (where `CreateProcess` doesn't always properly find a naked executable, so had to manually call `SearchPath` to find it first). If that's working, though, I'm happy to take that change alone for 2.3.

2017-03-28 21:55 UTC, dagwieers commented
@nitzmahone I don't see why the `executable` option would be documented in the command module, if it would not be working. That would be a bug in itself then. My interpretation is that it is on purpose so you can run e.g. expect as executable and provide the expect script/commands.

2017-03-28 22:15 UTC, nitzmahone commented
It's not that it doesn't work in `command`, but talking with @jimi-c and @bcoca, they tend to agree that it's likely a nonsensical accident of history that it's defined on `command` at all (due to shared code). @bcoca even proposed deprecating it and removing from docs. It sorta makes sense since we're not calling an API to launch a process on *nix (so it's still just a single command line that's passed over SSH), but we are for Windows (rather than passing it through cmd or powershell). 

I really don't want to add `executable` to command, but if you want to cut this down to just the parsing change, I'm happy to take that.

2017-03-28 22:17 UTC, dagwieers commented
Ok, fair enough. I agree that it should be removed from the command module documentation too.

2017-03-28 22:17 UTC, nitzmahone commented
PRs welcome ;)

2017-03-28 22:21 UTC, dagwieers commented
So, I reverted everything related to the executable parameter. However, there are a few cleanups related to win_command/win_shell consistency and docs. You want that in another PR, or not having it at all ?

2017-03-28 22:25 UTC, nitzmahone commented
s'ok

2017-03-28 22:29 UTC, nitzmahone requested changes

2017-03-28 22:29 UTC, nitzmahone commented on lib/ansible/modules/windows/win_command.ps1
> +    $exec_args = $parsed_command_line[1..-1]
PS slices aren't the same as Python (I *hate* the way the PS ones work)- this is incorrect, it needs to be the way I originally had it. Try the following: ` @(1,2,3,4)[1..-1]`, you'll see that it reorders the args.

2017-03-28 22:33 UTC, dagwieers commented on lib/ansible/modules/windows/win_command.ps1
> +    $exec_args = $parsed_command_line[1..-1]
What ? That makes no sense :-)
It showed 2 1 4 in my case.
What's the purpose of this behaviour ?

PS I looked it up and stackexchange told me to do it like that ;-)

2017-03-28 22:33 UTC, nitzmahone commented on lib/ansible/modules/windows/win_command.ps1
> +    $exec_args = $parsed_command_line[1..-1]
(`[1..-1]` creates a range of values `@(1,0,-1)`)

2017-03-28 22:37 UTC, nitzmahone commented on lib/ansible/modules/windows/win_command.ps1
> +    $exec_args = $parsed_command_line[1..-1]
PS doesn't really have array slices, so go downvote that SO answer ;)- it accepts a list of indices in the brackets, which the range operator `..` can be used to generate in limited cases.

2017-03-28 22:53 UTC, dagwieers commented
@nitzmahone Shippable errors are still problematic, but unrelated to the PR...

2017-03-28 23:45 UTC, nitzmahone commented
It doesn't appear that this fixes the referenced bug (I tried it- doesn't work with this change in place)- I think running it through cmd.exe might have, just because the shell reparsed the command line, but your change is effectively no change (since assigning the `exec_args` array to `$psi.Arguments` just turns it into a space-separated string anyway).

2017-03-28 23:47 UTC, dagwieers commented
Sigh. Again not how Unix works with arguments I guess :-/

2017-03-28 23:49 UTC, nitzmahone commented
Actually, I just dumped the raw arg values- the quotes never made it. So it's probably a YAML issue (or something in between).

2017-03-28 23:55 UTC, nitzmahone commented
Hmm, it's correct up to the _raw_params that are getting sent to the module...

2017-03-28 23:58 UTC, nitzmahone commented
Dammit- it's Microsoft's own function that's eating the quotes (`ParseCommandLine`).

2017-03-29 00:19 UTC, nitzmahone commented
Gonna zap this one, since the fix will be more involved (and probably wait for 2.4, since we can workaround with win_shell for now).

2017-03-29 00:19 UTC, closed without merging