Dhcp option check mode
ansible/ansible pull request #23106
Opened 2017-03-30 03:34 UTC by willthames

##### SUMMARY
ec2_vpc_dhcp_options_facts supports check mode by default.

Also various tidy ups based on Ansible and AWS module best practices (in a separate commit)

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
ec2_vpc_dhcp_options_facts

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel c1b3d6a51f) last updated 2017/03/30 09:17:50 (GMT +1000)
  config file = ./ansible.cfg
  configured module search path = [u'./library']
  python version = 2.7.13 (default, Jan 12 2017, 17:59:37) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```

##### ADDITIONAL INFORMATION

2017-04-04 12:58 UTC, ryansb requested changes
Small tweak, otherwise looks great.

2017-04-04 12:58 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/ec2_vpc_dhcp_options_facts.py
> +    aliases: ['DhcpOptionsIds']
:+1:

2017-04-04 12:58 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/ec2_vpc_dhcp_options_facts.py
> +        params['DryRun'] = module.params.get("dry_run")
Shouldn't this just be `params['DryRun'] = True` since the dry_run property is a boolean, so it'll only hit this when it's true anyway?

2017-04-05 00:17 UTC, willthames commented on lib/ansible/modules/cloud/amazon/ec2_vpc_dhcp_options_facts.py
> +        params['DryRun'] = module.params.get("dry_run")
Fixed

2017-04-18 12:56 UTC, ryansb approved these changes

2017-04-18 12:56 UTC, merged