Added priority attribute for pool members (bigip_pool_member module)
ansible/ansible pull request #23128
Opened 2017-03-30 12:40 UTC by ossark

##### SUMMARY
Added the ability to specify priority for pool members.

##### ISSUE TYPE
Feature pull request 

##### COMPONENT NAME
bigip_pool_member

##### ANSIBLE VERSION

```
ansible 2.4.0 (bigip_pool_member_prioritygroup 7054e453e3) last updated 2017/03/30 14:35:41 (GMT +200)
  python version = 2.7.10 (default, Oct 23 2015, 19:19:21) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]
```

2017-04-03 16:36 UTC, caphrim007 commented
@ossark if you'll be a champ and rename that `priority` variable to `priority_group`, then I'd be happy to approve.

Also, in the future, you can file issues at this repo for the F5 modules

https://github.com/F5Networks/f5-ansible

We upstream those modules and changes to those modules during each Ansible release cycle.

2017-04-05 23:52 UTC, caphrim007 commented
@gundalow shipit

This does not need to be cherry picked.

2017-04-06 06:39 UTC, gundalow requested changes

2017-04-06 06:39 UTC, gundalow commented on lib/ansible/modules/network/f5/bigip_pool_member.py
> +        priority_group=dict(type='int')
Thus needs adding to the DOCUMENTION block code a the top of the file, just below where preserves node is documented. 

 This PR will be released in Ansible 2.4, so please add `version_added:"2.4"`

2017-06-06 10:58 UTC, gundalow commented on lib/ansible/modules/network/f5/bigip_pool_member.py
> +        priority_group=dict(type='int')
@ossark Could you please address this then we can get this merged. Thanks for your fixes.

2017-07-06 19:36 UTC, gundalow commented on lib/ansible/modules/network/f5/bigip_pool_member.py
> +        priority_group=dict(type='int')
@ossark Thanks for the PR, just one change then I can get this merged. Thanks :)

2017-07-19 16:29 UTC, ossark commented
Give me a day or two and I should have this fixed. Thanks

> On 6 juli 2017, at 21:37, John R Barker <notifications@github.com> wrote:
> 
> @gundalow commented on this pull request.
> 
> In lib/ansible/modules/network/f5/bigip_pool_member.py:
> 
> > @@ -384,7 +402,8 @@ def main():
>          description=dict(type='str'),
>          rate_limit=dict(type='int'),
>          ratio=dict(type='int'),
> -        preserve_node=dict(type='bool', default=False)
> +        preserve_node=dict(type='bool', default=False),
> +        priority_group=dict(type='int')
> @ossark Thanks for the PR, just one change then I can get this merged. Thanks :)
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2017-07-19 16:35 UTC, caphrim007 commented
@ossark fyi after this PR goes in, future PR's for F5 "stuff" usually start over here

https://github.com/F5Networks/f5-ansible

There's still time to get this in before 2.4 is released.

2017-07-20 07:23 UTC, ossark commented on lib/ansible/modules/network/f5/bigip_pool_member.py
> +        priority_group=dict(type='int')
Updated as requested.

2017-07-31 18:01 UTC, gundalow commented
closing & reopening totrigger CI

2017-08-01 14:15 UTC, gundalow approved these changes

2017-08-01 14:15 UTC, merged

2017-08-01 14:16 UTC, gundalow commented
Thanks. Merged into `devel`, this will be released in `2.4.0`