Add a DHCP option for network settings
ansible/ansible pull request #23148
Opened 2017-03-30 17:11 UTC by Studiosixer

##### SUMMARY

Add a DHCP option for network settings that will allow DHCP rather than a static IP when creating a customized VM

##### ISSUE TYPE

 - Feature Pull Request
 - Docs Pull Request

##### COMPONENT NAME

vmware_guest module
##### ANSIBLE VERSION

```
ansible 2.4.0 (vmware-guest-allow-dhcp 4ee10eaaaa) last updated 2017/03/30 11:57:46 (GMT -500)
  config file = 
  configured module search path = ['/home/<user>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  python version = 3.6.0 (default, Jan 16 2017, 12:12:55) [GCC 6.3.1 20170109]
```

##### ADDITIONAL INFORMATION

```

```

2017-03-30 18:33 UTC, nerzhul requested changes

2017-03-30 18:33 UTC, nerzhul commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +            guest_map.adapter = vim.vm.customization.IPSettings()
you force the adapter creation if we don't set ip/netmask, this is wrong.

In my usecase we don't use this VMWare device

2017-03-30 18:49 UTC, Studiosixer commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +            guest_map.adapter = vim.vm.customization.IPSettings()
I see. I'll move the `guest_map.adapter = vim.vm.customization.IPSettings()` to be inside the `if 'ip' in network:` and `elif 'dhcp' in network:` conditions. Then I'll move all of the other `.adapter` property changes inside a block that checks for the `adapter` property.

2017-03-30 19:58 UTC, nerzhul commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +            if ('ip' in network and 'netmask' in network) or ('dhcp' in network):
no need for parenthesis, and is prior on or

2017-03-30 22:20 UTC, dav1x commented
@nerzhul @Studiosixer I'll test this in my env tomorrow. It's been a busy day with my other work.

2017-03-31 21:20 UTC, dav1x commented
tested this and works great. shipit

2017-05-12 15:35 UTC, Studiosixer commented
ping @jctanner can we merge this?

2017-07-07 16:51 UTC, Studiosixer commented
Fixed in PR https://github.com/ansible/ansible/pull/24768

2017-07-07 16:51 UTC, closed without merging