New Module: nfsexport.py
ansible/ansible pull request #23200
Opened 2017-04-01 18:55 UTC by randynobx

##### SUMMARY
nfsexport.py is a new system module for configuring the exports file for nfs servers. It supports multiple clients, with their own options, as well as options shared across all authorized clients. Each task calling nfsexport configures exactly one line for one path/share in the exports file. By using the destination ('dest') argument, you can change the location of the exports file.

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
nfsexport.py

##### ANSIBLE VERSION
```
ansible 2.2.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### ADDITIONAL INFORMATION
The module uses syntax based on that found in the exports manpage, which can be found at https://linux.die.net/man/5/exports

2017-04-01 20:05 UTC, randynobx commented
Addressing issues now

2017-04-01 23:41 UTC, krzysztof-magosa commented
IMO would be good to add `state` parameter, so user can remove previously added export.

2017-04-02 00:09 UTC, randynobx commented
@krzysztof-magosa I agree that a `state` parameter would be good to have. I am working on implementing that now.

Another scenario that I have been considering:
Would it be better for the module to fail if the requested export file does not exist? Or create a new one in that case? Currently, the module will exit with a failure if the specified export file does not exist.

2017-04-07 01:22 UTC, randynobx commented
Rebased commits on top of latest commits from devel branch, and squashed my commits into one.

2017-04-27 20:13 UTC, randynobx commented
ready_for_review

2017-05-12 21:02 UTC, pchauncey approved these changes
LGTM, tested with ansible 2.4.0

2017-05-12 21:03 UTC, pchauncey commented
shipit

2017-05-17 06:30 UTC, alxgu requested changes
The module fail, when the /etc/exports file contains an empty line

2017-05-17 06:30 UTC, alxgu commented on lib/ansible/modules/system/nfsexport.py
> +version_added: 2.4
This should be a string

2017-05-17 06:30 UTC, alxgu commented on lib/ansible/modules/system/nfsexport.py
> +        required: false
Only needed if true, otherwise it is assumed to be false.

2017-05-17 06:30 UTC, alxgu commented on lib/ansible/modules/system/nfsexport.py
> +        required: false
Only needed if true, otherwise it is assumed to be false.

2017-05-17 06:30 UTC, alxgu commented on lib/ansible/modules/system/nfsexport.py
> +        required: false
Only needed if true, otherwise it is assumed to be false.

2017-05-17 06:30 UTC, alxgu commented on lib/ansible/modules/system/nfsexport.py
> +        required: false
Only needed if true, otherwise it is assumed to be false.

2017-05-17 06:30 UTC, alxgu commented on lib/ansible/modules/system/nfsexport.py
> +short_description: This module will configure a nfs exports file
Missing full stop
> Descriptions should always start with a capital letter and end with a full stop. Consistency always helps.

2017-05-17 06:30 UTC, alxgu commented on lib/ansible/modules/system/nfsexport.py
> +            - list of nfs clients and host specific options
> Descriptions should always start with a capital letter and end with a full stop. Consistency always helps.

2017-05-17 06:30 UTC, alxgu commented on lib/ansible/modules/system/nfsexport.py
> +            path=dict(required=True),
maybe you add the type
`type='path'`

2017-05-17 06:30 UTC, alxgu commented on lib/ansible/modules/system/nfsexport.py
> +        module.fail_json(msg="failed to open dest for writing: %s" % str(err))
Please add the module as a function parameter and maybe replace `dest `trough the `filepath` in the error message
error: global name 'module' is not defined

2017-05-17 06:30 UTC, alxgu commented on lib/ansible/modules/system/nfsexport.py
> +    else:
This else part could be removed

2017-05-17 20:01 UTC, randynobx commented
@alxgu I've address all of your review points, tested, and rebased the commit.

2017-05-18 10:29 UTC, randynobx commented
ready_for_review

2017-05-19 07:18 UTC, alxgu requested changes
Some more feedback :)

2017-05-19 07:18 UTC, alxgu commented on lib/ansible/modules/system/nfsexport.py
> +    for client in client_list:
Do you need that step? `clients = client_list` should be enough

2017-05-19 07:18 UTC, alxgu commented on lib/ansible/modules/system/nfsexport.py
> +    client_list = params['clients'] \
IMHO this statement is hard to read. Woul rewrite to simple if else and for loop.

2017-05-19 07:18 UTC, alxgu commented on lib/ansible/modules/system/nfsexport.py
> +RETURN = """
We should fill the RETURN variable, but right now it should be `RETURN = ''' # '''`

> If your module doesn’t return anything (apart from the standard returns), you can use RETURN = ''' # '''.

2017-05-19 07:18 UTC, alxgu commented on lib/ansible/modules/system/nfsexport.py
> +__docformat__ = 'reStructuredText'
Could be removed?

2017-05-19 20:46 UTC, randynobx commented
@alxgu Thanks for the feedback! I've refactored some of the code to make it easier to read, and to remove some unneeded operations; both what you pointed out and other spots with the same issues.

A side question regarding the Return block: what sort of information could be expected to be returned for this module?

ready_for_review

2017-06-18 13:46 UTC, randynobx commented
ready_for_review

2018-02-08 02:58 UTC, maxamillion commented
Why not just use an already existing module to manage this configuration file? Why does it need it's own module?

2018-02-08 12:02 UTC, gundalow commented
From what I've seen in the field most people just use templates to manage `/etc/exports`, something similar to 
https://github.com/geerlingguy/ansible-role-nfs

2018-06-19 23:09 UTC, closed without merging