Do not alter (lower) the TXT records, as it breaks lets encrypt DNS c…
ansible/ansible pull request #23210
Opened 2017-04-03 09:29 UTC by fagaillard

…halenge

##### SUMMARY

Let's encrypt can be used with a DNS chalenge to verify domain ownership.  The challenge use a token that must be set on a specific TXT DNS record.  This token is case sensitive.

The exoscale DNS module does a content.lower() on the TXT record, breaking the Let's encrypt chalenge.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME

exo_dns_record

##### ANSIBLE VERSION

```
ansible 2.4.0 (letsencrypt-with-exoscale-dns 8f76872f97) last updated 2017/04/03 11:15:20 (GMT +200)
  config file = 
  configured module search path = [u'/Users/fabrice/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  python version = 2.7.13 (default, Mar 30 2017, 14:50:20) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```

##### ADDITIONAL INFORMATION
I'm  trying to use the exo_dns_record module to automate SSL certificate generation with let's encrypt, using the DNS validation method.

To do that, you need to create a TXT DNS entry with a chalenge string :

So for example if I want to create a certificate for the host toto.example.org
I need to create this TXT record on the domain example.org

_acme-challenge.toto IN TXT "BjMxdFFfRmvTkb49sNFnsj35xHpywmTQddSmwMbbvPA"

​The chalenge is case sensitive

In the exo_dns_record.py code, near line 279, you do a .lower()  on the content parameter passed to the module :

self.content = self.module.params.get('content')
if ​self.content:
self.content = self.content.lower()

So If I try to update my TXT record on the exoscale platform, the string is transformed to lowercase, and my let's encrypt challenge fails.

As a workaround, I directly update the record with a curl command.

But I think it will be better to leave the content parameter unchanged (at least for the TXT case).

2017-04-08 12:25 UTC, Mayeu commented
Note that this is also and issue when setting DKIM signature, that are case sensitive.

2017-04-08 18:01 UTC, resmo requested changes

2017-04-08 18:01 UTC, resmo commented on lib/ansible/modules/network/exoscale/exo_dns_record.py
> +            self.content = self.content
Assigning the same value again, does not make much sense.

~~~python
        self.content = self.module.params.get('content')
        if self.content and self.record_type != 'TXT':
            self.content = self.content.lower()
~~~

2017-04-25 08:39 UTC, resmo commented
ping @fagaillard, any change to look at my revision request?

2017-04-25 08:52 UTC, fagaillard commented
Yes, your solution is better

2017-04-25 08:52 UTC, closed without merging

2017-04-25 08:54 UTC, resmo commented
I didn't want to be rude, want to update your PR according my suggestion?

2017-04-25 09:07 UTC, fagaillard commented
?Hi  René


No problem,  I'm just quite busy and may not have a lot of time to follow the project.  May be it will be better to do the changes yourself.


Best regards


--fabrice




________________________________
From: René Moser <notifications@github.com>
Sent: Tuesday, April 25, 2017 10:55 AM
To: ansible/ansible
Cc: Gaillard Fabrice; State change
Subject: Re: [ansible/ansible] Do not alter (lower) the TXT records, as it breaks lets encrypt DNS c… (#23210)


I didn't want to be rude, want to update your PR according my suggestion?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub<https://github.com/ansible/ansible/pull/23210#issuecomment-296964509>, or mute the thread<https://github.com/notifications/unsubscribe-auth/ALl0g8rVu9qTRYR_7ULmIxqOQK41A07hks5rzbT5gaJpZM4MxSue>.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ansible/ansible","title":"ansible/ansible","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ansible/ansible"}},"updates":{"snippets":[{"icon":"PERSON","message":"@resmo in #23210: I didn't want to be rude, want to update your PR according my suggestion?"}],"action":{"name":"View Pull Request","url":"https://github.com/ansible/ansible/pull/23210#issuecomment-296964509"}}}

2017-04-25 09:19 UTC, resmo commented
ok, thanks for your efforts!