New module for AWS CodeCommit SSH Public Key Facts
ansible/ansible pull request #23261
Opened 2017-04-04 16:42 UTC by psharkey

##### SUMMARY
codecommit_ssh_key_facts.py is a new module  for gathering AWS CodeCommit SSH key facts.

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
codecommit_ssh_key_facts.py

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /home/ansible.cfg
  configured module search path = Default w/o overrides
```

##### ADDITIONAL INFORMATION

##### EXAMPLE PLAYBOOK

```
---
- hosts: localhost
  tasks:

  - name: get SSH public key content for an IAM user
    codecommit_ssh_key_facts:
      user_name: "psharkey"
      encoding: 'SSH'
    register: ssh_key_facts

  - debug: var=ssh_key_facts
```

2017-04-05 07:55 UTC, gundalow reviewed
1) name of the module doesn't seem to be online with the other AWS modules, though I'm not as familiar with them.

2017-04-05 07:55 UTC, gundalow commented on lib/ansible/modules/cloud/amazon/codecommit_ssh_key_facts.py
> +      - The desired format for the returned key PEM | SSH
Are these the only two valid options? 
If do please add as `choices:`  and add as choices to the arg spec. 

Of write 
`.. returned key, such as ssh or pen.`

2017-04-05 12:53 UTC, psharkey commented on lib/ansible/modules/cloud/amazon/codecommit_ssh_key_facts.py
> +      - The desired format for the returned key PEM | SSH
@gundalow Thanks for your comments. Regarding the name, AWS has a CodeCommit service (http://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_ssh-keys.html) and this module will gather the SSH public key(s) for all IAM users.  Do you have any suggestions for a different name - maybe `codecommit_ssh_facts` or `code_commit_facts` (with the caveat that only SSH information is currently supported)?
I'll work on adding `PEM` and `SSH` as the only valid choices to the encoding parameter. This is simply passed as a required parameter to the boto method `get_ssh_public_key` (http://boto3.readthedocs.io/en/latest/reference/services/iam.html#IAM.Client.get_ssh_public_key).

2017-04-05 13:26 UTC, gundalow commented on lib/ansible/modules/cloud/amazon/codecommit_ssh_key_facts.py
> +      - The desired format for the returned key PEM | SSH
Thanks for confirming, name sounds sensible to me them
http://docs.ansible.com/ansible/dev_guide/developing_modules_documenting.html#documentation-block

details `choices:`

2017-04-05 14:16 UTC, gundalow commented on lib/ansible/modules/cloud/amazon/codecommit_ssh_key_facts.py
> +      - The desired format for the returned key which can be either PEM or SSH
```yaml
description:
  - The desired format for the returned key.
choices:
  - PEM
  - SSH
```

2017-04-05 14:20 UTC, psharkey commented on lib/ansible/modules/cloud/amazon/codecommit_ssh_key_facts.py
> +      - The desired format for the returned key which can be either PEM or SSH
@gundalow Thanks! - I think I got this right now...

2017-05-16 20:53 UTC, ryansb requested changes
Other than exception handling, looks great. Thanks for contributing!

2017-05-16 20:53 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/codecommit_ssh_key_facts.py
> +        module.fail_json(msg=e.message, **camel_dict_to_snake_dict(e.response))
In addition to the error message from boto, can you include a nice message like "ClientError while listing SSH public keys" for users? 

Also, please catch a generic exception and fail with the traceback, like `module.fail_json(msg="Could not list SSH public keys", exception=traceback.format_exc())`

2020-08-20 09:44 UTC, Akasurde commented
Hi @psharkey, Thank you very much for your interest in Ansible. This plugin/module is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.aws<br><br>If you have further questions please stop by IRC or the mailing list:<br><br>* IRC: #ansible on irc.freenode.net<br>* mailing list: https://groups.google.com/forum/#!forum/ansible-project<br><br>needs_info<br>

2020-08-20 09:44 UTC, closed without merging