Add Notification Module for Office 365 Connector Cards
ansible/ansible pull request #23277
Opened 2017-04-04 21:56 UTC by marc-sensenich

##### SUMMARY
Using the Incoming Webhook connector, create Office 365 Connector Cards

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
Office 365 Connector Cards

##### ANSIBLE VERSION
```
ansible 2.2.2.0
  config file =
  configured module search path = Default w/o overrides
```

##### ADDITIONAL INFORMATION
Similar to PR #22215, but covers all functionality as referenced by the [API](https://dev.outlook.com/Connectors/reference)

2017-04-05 07:47 UTC, gundalow requested changes
Thanks for the new module
1) There are a few pep8 warning to clear up. 
2) Is this module idempotent, I don't see check mode defined. 
3) Can you remove cards? If so adding state=absent, present may be useful.

2017-04-05 07:47 UTC, gundalow commented on lib/ansible/modules/notification/office_365_connector_card.py
> +  - The C(office_365_connector_card) module creates Connector Card messages through Office 365 Connectors U(https://dev.outlook.com/Connectors)
No need to repeat the module name just say 
`Creates Connector Cards... `

2017-04-05 07:47 UTC, gundalow commented on lib/ansible/modules/notification/office_365_connector_card.py
> +      - The webhook URL is given to you when you create a new Connector
Missing full stop.

2017-04-05 11:24 UTC, marc-sensenich commented
Thanks for reviewing this.

1. Resolved in latest update
2. The actions wouldn't be idempotent, so check mode would not be present.
3. Currently the webhook does not allow delete, therefore it is create only

2017-04-05 15:34 UTC, gundalow commented
Could you please add a `note:` to say that this module isn't idempotent.

I assume it's safe to run the same playbook twice, or will you get two Connector Cards created?

2017-04-07 02:30 UTC, marc-sensenich commented
I added a note to say that it is not idempotent and will cause 2 cards to be created. I added the check mode in similar to how other notification modules have handled it as well.

2017-04-07 07:48 UTC, gundalow commented
Please work with the creator of https://github.com/ansible/ansible/pull/22215 to decide which module should go forward. You can both me authors & maintainers of the unified module.

2017-05-05 12:43 UTC, marc-sensenich commented
Any thoughts on moving this forward. I see there hasn't been a response from the owner of #22215

2017-06-16 11:35 UTC, closed without merging

2017-06-16 11:41 UTC, marc-sensenich commented
Closed this one, will reopen with new branch if there is still interest in this module