vmware_guest: Add support for Linked Clones
ansible/ansible pull request #23284
Opened 2017-04-05 07:42 UTC by cigamit

##### SUMMARY
One thing I sorely miss from the vsphere_guest module is the ability to create linked clones.  I have implemented it into vmware_guest with minimal changes required.  I added one addition parameter
```
snapshot_name:
        description:
            - A string that when specified, will create a linked clone copy of the VM. Snapshot must already be taken in vCenter.
```
I had first thought to use the original parameter name from vsphere_guest but decided to instead keep the name in line with the vmware_guest_snapshot module.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel 1daa69d685) last updated 2017/04/05 01:07:34 (GMT -500)
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### ADDITIONAL INFORMATION
I used this playbook to test (plus a few others to shutdown / remove).  If the VM/Template does not contain a snapshot with that name, it will error out.  The function "get_snapshots_by_name_recursively" was used from "vmware_guest_snapshot"
```
      vmware_guest:
        validate_certs: False
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        name: "{{ vmname }}"
        template: "{{ vmtemplate }}"
        snapshot_name: "Snapshot1"
        wait_for_ip_address: True
        state: poweredon
        datacenter: "{{ vmdatacenter }}"
        cluster: "{{ vmcluster }}"
      register: newvm
```

2017-04-05 08:10 UTC, nerzhul commented
why don't use vmware_guest_snapshot after vmware_guest ? We split snapshot ops from vmware_guest , but i need to know what is the purpose of this PR and if it's not better to use vmware_guest_snapshot

2017-04-05 08:21 UTC, cigamit commented
vmware_guest_snapshot just manages a VMs snapshots, this is completely different.   This PR allows you to create a completely new VM that is based off a snapshot of another VM.   This is commonly referred to as a "Linked Clone".  The parent disk is untouched, and can be utilized by multiple VMs at the same time as the Base Disk, while all changes just go to its own "Snapshot Disk".  Using this, I can spawn completely new clone of a VM in under 5 seconds.

The VMWare docs explain it a bit better than I can

> Using Linked Clones
A linked clone is a copy of a virtual machine that shares virtual disks with the parent virtual machine in an ongoing manner.
Because a linked clone is made from a snapshot of the parent, disk space is conserved and multiple virtual machines can use the same software installation. All files available on the parent at the moment you take the snapshot continue to remain available to the linked clone.
Ongoing changes to the virtual disk of the parent do not affect the linked clone, and changes to the disk of the linked clone do not affect the parent. A linked clone must have access to the parent. Without access to the parent, you cannot use a linked clone.
Because linked clones are created swiftly, you can create a unique virtual machine for each task. You can also share a virtual machine with other users by storing the virtual machine on your local network where other users can quickly make a linked clone. For example, a support team can reproduce a bug in a virtual machine, and an engineer can quickly make a linked clone of that virtual machine to work on the bug.
You can make a linked clone from a linked clone, but the performance of the linked clone degrades. If you make a full clone from a linked clone, the full clone is an independent virtual machine that does not require access to the linked clone or its parent. You should make a linked clone of the parent virtual machine, if possible.

2017-04-05 08:25 UTC, nerzhul requested changes

2017-04-05 08:25 UTC, nerzhul commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +   snapshot_name:
snapshot_src is better name i think for linked clone, it's unclear for non linked clones usage

2017-04-05 08:40 UTC, cigamit commented
As an additional feature, we could also add an "is_linked" bool variable that will allow toggling of the Linked Clone.  This would allow us to clone from a Snapshot but still create a full copy of the disk without any dependency on the parent disk.  This has some Enterprise use cases.

2017-04-06 01:54 UTC, cigamit commented
ready_for_review

2017-04-07 03:24 UTC, cigamit commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +   snapshot_name:
Code has been updated to use snapshot_src

2017-04-11 03:22 UTC, cigamit commented
ready_for_review

2017-04-11 03:23 UTC, cigamit reviewed
I updated the name of the parameter

2017-04-23 04:16 UTC, cigamit commented
ready_for_review

2017-04-27 20:46 UTC, cigamit commented
bot_status

2017-04-28 23:03 UTC, cigamit commented
nerzhul, can you clear your Change Request flag?  As I have already added the changes you requested.

2017-04-29 09:55 UTC, nerzhul requested changes

2017-04-29 09:55 UTC, nerzhul commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +   snapshot_linked:
why not just call this linked_clone as it's the feature name ?

2017-04-29 09:55 UTC, nerzhul commented
Sorry for to be late, many issues and work to do :)

2017-05-02 23:56 UTC, cigamit commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +   snapshot_linked:
I have no qualms with that and it does sound a bit better.  I will submit the changes in a few minutes.

2017-05-05 05:24 UTC, nerzhul approved these changes

2017-05-05 05:25 UTC, nerzhul commented
okay for me, @dav1x @jctanner please review :)

2017-05-08 12:58 UTC, pchauncey commented
Works for me, tested with Ansible 2.40 against vSphere 6.5
shipit

2017-05-08 13:04 UTC, nerzhul requested changes

2017-05-08 13:04 UTC, nerzhul commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +                    if len(snapshot) == 1:
you can remove this condition as the previous condition already handle other cases

2017-05-16 11:52 UTC, nerzhul commented
shipit

2017-05-16 12:06 UTC, pchauncey commented
shipit

2017-05-16 12:25 UTC, nerzhul approved these changes

2017-05-16 13:25 UTC, dav1x commented
@cigamit great functionality! shipit

2017-05-16 13:26 UTC, merged