win_psexec: Enable -nobanner option by default
ansible/ansible pull request #23422
Opened 2017-04-07 19:52 UTC by dagwieers

##### SUMMARY

PR also includes:
- Option `nobanner:` to remove this flag
- Improvements to Examples
- Improvement to Return Value
- Add types to all parameters now that we have those

TODO:
- Add integration tests

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

win_psexec

##### ANSIBLE VERSION

v2.3

2017-05-09 00:20 UTC, nitzmahone requested changes

2017-05-09 00:20 UTC, nitzmahone commented on test/integration/targets/win_psexec/tasks/main.yml
> +    path: C:\Program Files\sysinternals
Why not unzip/run this in the tempdir in case someone actually has a C:\Program Files\sysinternals dir that wasn't created by the test?

2017-05-09 00:27 UTC, dagwieers commented on test/integration/targets/win_psexec/tasks/main.yml
> +    path: C:\Program Files\sysinternals
Good point, I just always do it that way :-) Doing it in tempdir also would require me to create a directory, as the zip files is a blob of binaries with no directory. Will fix !

Actually I don't understand why Microsoft doesn't properly package it...

2017-05-09 01:15 UTC, dagwieers commented on test/integration/targets/win_psexec/tasks/main.yml
> +    path: C:\Program Files\sysinternals
Fixed !

2017-05-10 23:10 UTC, nitzmahone approved these changes

2017-05-10 23:10 UTC, merged