Add monitor and failover support to DNSMadeEasy module
ansible/ansible pull request #23434
Opened 2017-04-08 21:10 UTC by ericworkman

##### SUMMARY
Extends the DNSMadeEasy module to allow for monitoring and failover configuration for A records.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
DNSMadeEasy

##### ANSIBLE VERSION
```
ansible 2.4.0
```

##### ADDITIONAL INFORMATION
I've manually tested failover and monitor configuration in all the permutations I could think of using the [DNSMadeEasy sandbox](http://sandbox.dnsmadeeasy.com).

- Existing modules options still work
- Required groups of parameters are specified according to what I could work out from [DNSMadeEasy's documentation](https://www.dnsmadeeasy.com/pdf/API-Docv2.pdf) and from poking at the API
- Applying both monitoring and failover work or fail with helpful error messages
- Removal of monitoring and failover work
- The module reports changed status appropriately if either the monitor "record" or the record change

2017-04-09 15:54 UTC, gundalow requested changes

2017-04-09 15:54 UTC, gundalow commented on lib/ansible/modules/network/dnsmadeeasy.py
> +    version_added: 2.4.0
`version_added: "2.4"`

2017-04-09 15:54 UTC, gundalow commented on lib/ansible/modules/network/dnsmadeeasy.py
> +      - If true, add or change the monitor
Descriptions should be full sentences, and end with a full stop.

2017-04-11 14:00 UTC, ericworkman commented
@gundalow Thanks for the review! How's this look?

2017-04-27 16:41 UTC, gundalow commented
Hi,
A number of files have been git moved from `modules/network` to `modules/net_tools`, which has effected this PR. Please rebase this PR to pull in that change.

2017-04-27 16:42 UTC, gundalow commented
@briceburg I've given this PR the once over and it looks good, as the module maintainer we'd like to get your approval before it gets merged (pending on rebase)

2017-04-27 16:47 UTC, ericworkman commented
I've rebased this PR. Thank you @gundalow !

2017-04-27 18:22 UTC, gundalow approved these changes

2017-05-23 12:43 UTC, briceburg commented
Thanks @gundalow. I say shipit

2017-05-26 14:22 UTC, merged

2017-05-26 14:23 UTC, gundalow commented
Thank you all for the PR and the reviews. This has been merged into `devel` and will be released in Ansible 2.4, as we don't backport new features.