ecs_taskdefinition module : proposal : add `state=create` parameter
ansible/ansible pull request #23480
Opened 2017-04-11 03:54 UTC by nazo

##### SUMMARY

ecs_taskdefinition module : add `state=create` parameter.

`create` parameter is similar to `present`.
always create a new task definition when `create` parameter is set.

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

ecs_taskdefinition module

##### ANSIBLE VERSION

```
2.2.0
```

2017-04-11 04:47 UTC, simplesteph commented
Thanks for the PR. 
I think I'd like better a parameter saying: `force_create: true` or something along these lines

2017-04-18 04:23 UTC, nazo commented
@simplesteph changed `state=create`  to `force_create: true`. please review this.

2017-04-18 05:06 UTC, simplesteph commented on lib/ansible/modules/cloud/amazon/ecs_taskdefinition.py
> +        force_create=dict(required=False, type='bool'),
is it worth adding a default value of False here?

2017-04-18 05:06 UTC, simplesteph reviewed
just a quick comment, otherwise LGTM

2017-04-18 05:39 UTC, nazo commented
@simplesteph thanks! add default parameter.

2017-07-12 19:44 UTC, mspiegle commented
I made this exact same change in my environment and was about to create a PR until I found this.  I agree w/ the approach and it has worked well in my production environments.

Just in case anyone is curious why this is needed (at least my reason):
Part of my development workflow involves building new docker images with the 'latest' tag.  The AWS ECS agent doesn't periodically check to see if the 'latest' tag has been updated, but you can force it to re-pull the image by creating a new ECS task definition revision.  Fortunately/Unfortunately, the ansible ecs_taskdefinition module is smart and won't create a new revision if it "looks" the same.  With this parameter, we can force creating a new revision which then triggers the AWS ECS agent to automatically re-pull the image.

2017-07-13 13:56 UTC, s-hertel requested changes
Looks good.

2017-07-13 13:56 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/ecs_taskdefinition.py
> +        if existing and not ('force_create' in module.params and module.params['force_create']):
Can we change this to `if existing and not module.params.get('force_create'):`?

2017-07-31 07:48 UTC, nazo commented on lib/ansible/modules/cloud/amazon/ecs_taskdefinition.py
> +        if existing and not ('force_create' in module.params and module.params['force_create']):
changed.

2017-07-31 17:50 UTC, s-hertel approved these changes

2017-07-31 17:50 UTC, s-hertel commented
shipit

2017-12-29 18:46 UTC, s-hertel commented
rebuild_merge

2018-01-03 13:56 UTC, merged

2018-01-03 13:56 UTC, s-hertel commented
Thanks @nazo!