Improve Fortios IPv4 policy with logging capabilities and use the backup_filename param
ansible/ansible pull request #23544
Opened 2017-04-12 21:22 UTC by claer

##### SUMMARY

- Improve Fortios IPv4 policy with logging capabilities and fix typos in examples.

Add the logtraffic and logtraffic_start options to firewall rule.
Fix 2 small typos in examples.

- Forti_config: use the backup_filename param and don't enforce the the filename value.

The backup_filename parameter was defined but code never used it. Now, if backup_filename is present, it overrrides the default config name.

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

Affects modules/network/fortios

##### ANSIBLE VERSION

```
[claer@sebastian ansible-fg]$ ansible --version
ansible 2.3.0.0 (stable-2.3 9818ca366d) last updated 2017/04/12 13:55:20 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 12 2017, 17:59:37) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
[claer@sebastian ansible-fg]$ 

```

##### ADDITIONAL INFORMATION

```

```

2017-04-12 21:40 UTC, gundalow requested changes

2017-04-12 21:40 UTC, gundalow commented on lib/ansible/modules/network/fortios/fortios_ipv4_policy.py
> +    choices: ["disable", "utm", "all"]
Please add
`version_added: "2.4"`

2017-04-12 21:40 UTC, gundalow commented on lib/ansible/modules/network/fortios/fortios_ipv4_policy.py
> +    default: false
Please add
`version_added: "2.4"`

2017-04-12 21:42 UTC, gundalow commented on lib/ansible/modules/network/fortios/fortios_ipv4_policy.py
> +      - Logs begining of session as well.
Missing `description:`

2017-04-12 21:55 UTC, claer commented on lib/ansible/modules/network/fortios/fortios_ipv4_policy.py
> +      - Logs begining of session as well.
Thanks for the quick reply!
I didn't pay attention to the 'please add version_added..' it should be corrected now.

2017-04-13 13:02 UTC, gundalow commented
@bjolivot Could you please take a look at this?

You will now get pinged on changed to this directory https://github.com/ansible/ansibullbot/commit/f7e72e9f727db6d71cdd84e9ddc7a31ba35e14df

2017-04-13 13:02 UTC, gundalow approved these changes

2017-04-13 14:41 UTC, bjolivot commented
Hello @claer thank you for your pull request
Looks good to me.
shipit

2017-04-13 16:20 UTC, merged

2017-04-13 16:21 UTC, gundalow commented
@claer Thanks for the PR
@bjolivot Thank you for the review

As this is a "feature pull request" it's only gone into `devel` (which will be 2.4)

I wonder if you'd want to create a PR based off `stable-2.3` to backport *only* the bug fix parts of this?

Ansible 2.3.1 will be released in a week or so.