filesystem: introduce swap
ansible/ansible pull request #23632
Opened 2017-04-15 14:49 UTC by romain-dartigues

* aggregate failures
* introduce swap support

##### SUMMARY

Before the patch (`/dev/DATA/swap` is an empty, newly created LV):

``` yaml
- name: mkswap
  filesystem: fstype=swap dev=/dev/DATA/swap
```

Returned:

```
ok: [docker02] => (item={u'fs_vfstype': u'swap', u'fs_spec': u'/dev/DATA/swap', u'size': u'2G'})
```

But on the target, nothing much happened:

``` console
root@docker02:~# blkid /dev/DATA/swap
root@docker02:~# file -Ls /dev/DATA/swap
/dev/DATA/swap: data
```

After the patch, the playbook says:

```
changed: [docker02] => (item={u'fs_vfstype': u'swap', u'fs_spec': u'/dev/DATA/swap', u'size': u'2G'})
```

Now on the target:

``` console
root@docker02:~# blkid /dev/DATA/swap
/dev/DATA/swap: UUID="40fc8cb4-f18a-4693-85e4-189b52ff66b3" TYPE="swap"
root@docker02:~# file -Ls /dev/DATA/swap
/dev/DATA/swap: Linux/i386 swap file (new style), version 1 (4K pages), size 524287 pages, no label, UUID=40fc8cb4-f18a-4693-85e4-189b52ff66b3
```

Thanks to the existing code, the swap functionality is idempotent and when re-run will detect the FS is already a swap:

```
ok: [docker02] => (item={u'fs_vfstype': u'swap', u'fs_spec': u'/dev/DATA/swap', u'size': u'2G'})
```

The target is:

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty
```

##### ISSUE TYPE

 - Feature Pull Request
 - Bugfix Pull Request

##### COMPONENT NAME
- module filesystem

##### ANSIBLE VERSION
```
ansible 2.1.2.0
```

##### ADDITIONAL INFORMATION
Originally presented in ansible/ansible-modules-extras#3345; more information there.

2017-04-18 09:57 UTC, robinro requested changes

2017-04-18 09:57 UTC, robinro commented on lib/ansible/modules/system/filesystem.py
> +        if rc:
This block should probably be unindented one level to work for all filesystem types.

2017-04-18 12:40 UTC, romain-dartigues commented on lib/ansible/modules/system/filesystem.py
> +        if rc:
You are right, it's a typo on my side when I imported m initial patch... I'm fixing it, thank you for your eye.

2017-08-03 18:55 UTC, calfonso commented
@romain-dartigues Note: the bot has noted this PR requires a rebase, and we are waiting for someone from the community to come review this. You will want to rebase and fix any conflicts before having someone review the PR.

2017-12-21 03:33 UTC, Akasurde commented
@romain-dartigues Any news ?

2017-12-21 09:56 UTC, romain-dartigues commented
hope this will get somewhere...

2018-06-30 20:28 UTC, romain-dartigues commented
@Akasurde < finally got the grisp of the unittests; sorry for the verbose trial and errors, I couldn't test locally before pushing.

Do you think this PR could advance to the next stage?

Critics welcome.

2018-07-01 06:02 UTC, romain-dartigues commented
@robinro, @calfonso < hi there, do you think this PR could move on? I suppose the **need_revision** tag  is preventing it to get further...

Thanks.

2018-11-29 16:47 UTC, gundalow commented
@romain-dartigues Hi, you'll need to rebase this branch, see https://docs.ansible.com/ansible/latest/dev_guide/developing_rebasing.html

How to communicate with the Ansible community: https://docs.ansible.com/ansible/devel/community/communication.html
How to contribute to Ansible: https://docs.ansible.com/ansible/devel/community/index.html

2019-09-03 12:42 UTC, gundalow commented
Looks like this was done by @pilou- in https://github.com/ansible/ansible/pull/49456/

So I'm going to close this PR

2019-09-03 12:42 UTC, closed without merging