add filters variable to allow servers to be selected based on arbitra…
ansible/ansible pull request #23638
Opened 2017-04-15 18:31 UTC by dbckz

##### SUMMARY
Module currently allows us to retrieve servers from nova based on their name or uuid. This PR extends this to allow us to filter the servers that are returned based on an arbitrary set of nova properties by providing a 'filters' dictionary. This makes direct use of the filters option provided by shade.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
os_server_facts.py module

##### ANSIBLE VERSION
ansible 2.3.0.0

My use case is retrieving all instances deployed on a particular hypervisor, so that I can power those VMs down to do maintenance on the underlying server:

  - name: Retrieve all VMs deployed on hypervisor
     os_server_facts:
       cloud: "{{ overcloud }}"
       filters:
          OS-EXT-SRV-ATTR:hypervisor_hostname: "{{ hypervisor }}"

  - name: Power down all VMs deployed on hypervisor
     os_server_actions:
       cloud: "{{ overcloud }}"
       action: stop
       server: "{{ item.name }}"
     with_items: "{{ openstack_servers }}"

2017-04-18 13:40 UTC, gundalow requested changes

2017-04-18 13:40 UTC, gundalow commented on lib/ansible/modules/cloud/openstack/os_server_facts.py
> +          filters (e.g., {vm_state: 'active'})
Please add
`version_added: "2.4"`

2017-04-18 13:42 UTC, gundalow commented on lib/ansible/modules/cloud/openstack/os_server_facts.py
> +          filters (e.g., {vm_state: 'active'})
This line is breaking the YAML, I think  you need something closer to 

`filters, for example: C({vm_state: 'active'}).`

2017-08-30 21:00 UTC, dbckz commented
Commits have been made to fix issues pointed out in review.

2017-08-30 21:20 UTC, rcarrillocruz commented
shipit

2018-10-14 13:18 UTC, mnaser requested changes

2018-10-14 13:18 UTC, mnaser commented on lib/ansible/modules/cloud/openstack/os_server_facts.py
> +     version_added: "2.4"
Sorry for the delay, could you bump this to `version_added: "2.8"` and we'll be able to get this merged.

2018-10-14 15:06 UTC, mnaser commented
@dbckz I think we just need a rebase and we can ship it

2018-10-19 08:29 UTC, dbckz commented
Rebased

2018-10-20 21:52 UTC, mnaser approved these changes

2018-10-20 21:52 UTC, mnaser commented
shipit

2018-10-30 10:49 UTC, odyssey4me approved these changes

2018-10-30 10:49 UTC, odyssey4me commented
shipit

2018-10-30 18:14 UTC, gundalow approved these changes

2018-10-30 18:14 UTC, gundalow commented
shipit

2018-10-30 18:34 UTC, merged

2018-11-01 19:21 UTC, jamescassell commented on lib/ansible/modules/cloud/openstack/os_server_facts.py
> +        openstack_servers = cloud.search_servers(
Why do we set the openstack_servers variable twice in a row?  Is the first call required?  Seems like the second call will overwrite the result from the first call.

2018-11-01 19:26 UTC, mnaser commented on lib/ansible/modules/cloud/openstack/os_server_facts.py
> +        openstack_servers = cloud.search_servers(
Ah crap, I guess we all missed it.

Do you think you could quickly submit a PR to fix this?

2018-11-01 19:55 UTC, jamescassell commented on lib/ansible/modules/cloud/openstack/os_server_facts.py
> +        openstack_servers = cloud.search_servers(
see #47940