spelling fixes (non-trivial, changing messages)
ansible/ansible pull request #23645
Opened 2017-04-16 12:29 UTC by ka7

##### SUMMARY

patch contains some spelling fixes as found by a bot ( http://www.misfix.org, https://github.com/ka7/misspell_fixer ). Any upcoming License changes (e.g. GPL2 to GPL3+) are hereby granted.

Fhe fixes touching spelling-fixes in output, so _might break_ some stuff if somebody relays one that ??

##### ISSUE TYPE

 - Feature Pull Request
 - New Module Pull Request
 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME

##### ANSIBLE VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

2017-04-16 15:05 UTC, Akasurde requested changes
Except github_release change, I am OK with other changes.

2017-04-16 15:05 UTC, Akasurde commented on lib/ansible/modules/source_control/github_release.py
> -        module.fail_json(msg='Missing required github3 module (check docs or '
This change reverts #23641

2017-04-16 16:03 UTC, ka7 commented
sorry for the exclusion of that, error by me while rebase.. :-/
fixed that now.

2017-04-26 12:16 UTC, gundalow requested changes

2017-04-26 12:16 UTC, gundalow commented on lib/ansible/module_utils/aos.py
> +        module.fail_json(msg="Ans error occurred while running 'find_collection_item'")
`An error occurred`

2017-04-26 12:16 UTC, gundalow commented
Rebase needed

2017-05-19 16:24 UTC, calfonso commented
@ka7 still interested in making these changes? If so, please update the PR and if not, you can close it. Thanks!

2017-05-26 14:38 UTC, Akasurde commented
@ka7 are you still working on this ? I can take over this PR.

2017-05-26 15:26 UTC, ka7 commented
Hi,

sorry, got stuck a bit, as git-rebase trys to make me crazy.

If you want to take over - feel free.

.klemens


On 2017-05-26 16:38, Abhijeet Kasurde wrote:
> @ka7 [1] are you still working on this ? I can take over this PR.
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the
> thread [3].
> 
> 	*
> 
> Links:
> ------
> [1] https://github.com/ka7
> [2] 
> https://github.com/ansible/ansible/pull/23645#issuecomment-304300053
> [3]
> https://github.com/notifications/unsubscribe-auth/ABW8jJWsLFafzE42PhI970wx371y7OHaks5r9uPogaJpZM4M-ncD

2017-05-26 16:21 UTC, Akasurde commented
@ka7 OK. Thanks.

2017-06-06 10:59 UTC, gundalow commented
Closing as this has been fixed in another PR

2017-06-06 10:59 UTC, closed without merging