New module : github_issue
ansible/ansible pull request #23654
Opened 2017-04-17 06:44 UTC by Akasurde

##### SUMMARY
Using github_issue module, user can retrive status of issue
listed on Github repository and depending upon status takes
various actions e.g., workarounds and downloading patches.

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
lib/ansible/modules/source_control/github_issue.py

##### ANSIBLE VERSION
```
2.4 devel
```

2017-04-19 13:35 UTC, gundalow requested changes

2017-04-19 13:35 UTC, gundalow commented on lib/ansible/modules/source_control/github_issue.py
> +    required: false
This doesn't match argument_spec

2017-04-19 13:35 UTC, gundalow commented on lib/ansible/modules/source_control/github_issue.py
> +      - issue number for which information is required.
s/issue/Issue

2017-04-19 13:35 UTC, gundalow commented on lib/ansible/modules/source_control/github_issue.py
> +  action:
Is the idea that other `actions` may be added in the future?

2017-04-19 13:35 UTC, gundalow commented on lib/ansible/modules/source_control/github_issue.py
> +      - Name of repository from which issue needs to be retrived.
s/retrived/retrieved/

2017-04-19 13:35 UTC, gundalow commented on lib/ansible/modules/source_control/github_issue.py
> +      - Name of Github organization in which repository is hosted.
GitHub

2017-04-19 13:35 UTC, gundalow commented on lib/ansible/modules/source_control/github_issue.py
> +    description: State of github issue
GitHub

2017-04-19 13:37 UTC, gundalow commented
Hi @djmattyg007 @pcgentry @adrianmoisey @dj-wasabi @robinro
You are listed as maintainers for other Git modules, so it would be good to get your views on this new module.

Thanks in advance

2017-04-19 14:46 UTC, Akasurde commented on lib/ansible/modules/source_control/github_issue.py
> +      - Name of repository from which issue needs to be retrived.
OK.

2017-04-19 14:46 UTC, Akasurde commented on lib/ansible/modules/source_control/github_issue.py
> +      - Name of Github organization in which repository is hosted.
OK.

2017-04-19 14:46 UTC, Akasurde commented on lib/ansible/modules/source_control/github_issue.py
> +      - issue number for which information is required.
OK.

2017-04-19 14:47 UTC, Akasurde commented on lib/ansible/modules/source_control/github_issue.py
> +  action:
Yes. I don't have any idea except "get_status". This will make it generic enough for future expansion.

2017-04-19 14:47 UTC, Akasurde commented on lib/ansible/modules/source_control/github_issue.py
> +    description: State of github issue
OK.

2017-04-19 14:48 UTC, Akasurde commented on lib/ansible/modules/source_control/github_issue.py
> +    required: false
Can you elaborate more on `argument_spec`? Just pin point, I will find more about it.

2017-04-19 15:43 UTC, gundalow commented on lib/ansible/modules/source_control/github_issue.py
> +  action:
Cool

2017-04-19 15:44 UTC, gundalow commented on lib/ansible/modules/source_control/github_issue.py
> +    required: false
`action=dict(required=True, choices=['get_status']),`

So this should be `required: false`

2017-04-20 03:44 UTC, djmattyg007 commented
I don't think this belongs in the source_control folder. It's a module for interacting with the Github API, not for managing a version control repository.

2017-04-26 12:20 UTC, Akasurde commented
@djmattyg007 Could you please suggest appropriate directory for this module ?

2017-04-26 12:25 UTC, adrianmoisey commented
> I don't think this belongs in the source_control folder. It's a module for interacting with the Github API, not for managing a version control repository.

There are quite a few other modules that work like this one in the source_control directory. I think it makes sense to move them too, if this one needs to move.

2017-04-26 22:37 UTC, djmattyg007 commented
Perhaps there should be a web_services folder or something along those lines.

2017-04-27 07:51 UTC, gundalow commented
So although this module isn't about source_control, from an ability to find things to do the source_control directory does make sense, especially since there are existing modules in there:

source_control/github_hooks.py
source_control/github_key.py
source_control/github_release.py

2017-04-27 07:53 UTC, gundalow approved these changes

2017-04-27 07:54 UTC, gundalow commented
Could someone else please review this module, and add their feedback? Thanks in advance.

2017-04-27 19:27 UTC, pchauncey reviewed
This works for me, Ansible 2.4.0.

One suggestion:  Since there's only a single action at the moment, get_status, why not make it the default and not required?

```diff
diff --git a/lib/ansible/modules/source_control/github_issue.py b/lib/ansible/modules/source_control/github_issue.py
index c96f008..1358e12 100644
--- a/lib/ansible/modules/source_control/github_issue.py
+++ b/lib/ansible/modules/source_control/github_issue.py
@@ -47,7 +47,7 @@ options:
     description:
         - Get various details about issue depending upon action specified.
     default: 'get_status'
-    required: true
+    required: false
     choices:
         - ['get_status']
 
@@ -104,7 +104,7 @@ def main():
             organization=dict(required=True),
             repo=dict(required=True),
             issue=dict(required=True),
-            action=dict(required=True, choices=['get_status']),
+            action=dict(required=False, choices=['get_status']),
         ),
         supports_check_mode=True,
     )
@@ -126,7 +126,7 @@ def main():
                              "Please check organization, repo and issue "
                              "details and try again.")
 
-    if action == 'get_status':
+    if action == 'get_status' or action == None:
         if module.check_mode:
             result.update(changed=True)
         else:
```

2017-04-27 21:35 UTC, djmattyg007 commented
Explicit is usually better than implicit. Allowing a user to not specify the action could create issues with backwards compatibility later.

2017-04-29 13:16 UTC, Akasurde commented
ready_for_review

2017-05-02 14:51 UTC, gundalow commented
Retriggering CI as we've just made some new tests live

2017-05-02 14:51 UTC, gundalow approved these changes

2017-05-02 14:52 UTC, gundalow commented
@pchauncey are you happy with the explicit option?

Looking for another nod then we can get this merged

2017-05-03 16:20 UTC, pchauncey commented
@gundalow yes, explicit is good with me.

2017-05-04 11:16 UTC, merged

2017-05-04 11:16 UTC, gundalow commented
Merged into `devel` so this will be released in Ansible 2.4

Thanks for the modules and the reviews.

2017-05-04 11:39 UTC, Akasurde commented
@gundalow @pchauncey @djmattyg007 @adrianmoisey Thanks for your valuable comments and time. I really appreciated help.

2017-05-04 11:47 UTC, adrianmoisey commented
:+1: