Add Password for login method in github_release
ansible/ansible pull request #23661
Opened 2017-04-17 14:25 UTC by Akasurde

##### SUMMARY
Fix allows user to specify username and password for
using github_release to perform various operations

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/modules/source_control/github_release.py

##### ANSIBLE VERSION
```
2.4 devel
```

2017-04-17 15:02 UTC, adrianmoisey commented on lib/ansible/modules/source_control/github_release.py
> +        if user and password:
Just a thought, and this was a problem I created, `user` was meant to be used of the repository that needs to be accessed, not for auth.
I think we should change `repo` to be the full path of the repository (`username/repo`) and then we can split it for use later on.

2017-04-17 15:02 UTC, adrianmoisey commented on lib/ansible/modules/source_control/github_release.py
> +from ansible.module_utils.basic import AnsibleModule, get_exception
❤️

2017-04-17 15:15 UTC, adrianmoisey commented
shipit

2017-04-17 15:16 UTC, adrianmoisey commented on lib/ansible/modules/source_control/github_release.py
> +        if user and password:
This is something that can be fixed/changed in another PR

2017-04-17 15:43 UTC, Akasurde commented on lib/ansible/modules/source_control/github_release.py
> +        if user and password:
@adrianmoisey Yes. Sure I will raise another PR for that.

2017-04-17 15:43 UTC, Akasurde commented on lib/ansible/modules/source_control/github_release.py
> +from ansible.module_utils.basic import AnsibleModule, get_exception
@adrianmoisey Thanks.

2017-04-26 12:17 UTC, Akasurde commented
ready_for_review

2017-05-03 03:41 UTC, Akasurde commented
ready_for_review

2017-05-03 07:35 UTC, gundalow requested changes

2017-05-03 07:35 UTC, gundalow commented on lib/ansible/modules/source_control/github_release.py
> +            - The Github account password for the user
GitHub

This applies in a number of places.

2017-05-03 07:35 UTC, gundalow commented on lib/ansible/modules/source_control/github_release.py
> +            password=dict(required=True),
Please add `, no_log=True`

2017-05-03 07:35 UTC, gundalow commented on lib/ansible/modules/source_control/github_release.py
> +            password=dict(required=True),
Is this actually a required option?

1) Are `password` and `token` mutually exclusive. 
2) can you use this without auth? 


There are some options to `AnsibleModule` which you may be able to use to validate options passed in.
Look at existing modules for examples:
```
mutually_exclusive
required_one_of
```

2017-05-03 07:35 UTC, gundalow commented on lib/ansible/modules/source_control/github_release.py
> +        required: true
Based on your examples I don't believe this is a required option, so this lime can be removed.

2017-05-03 07:35 UTC, gundalow commented on lib/ansible/modules/source_control/github_release.py
> +- name: Get latest release of test repo using username and password
`Get latest release of test repo using username and password. Ansible 2.4.`

2017-05-03 07:36 UTC, gundalow commented
Closing and reopening to rerun CI.

2017-05-03 09:18 UTC, Akasurde commented on lib/ansible/modules/source_control/github_release.py
> +            - The Github account password for the user
Done

2017-05-03 09:18 UTC, Akasurde commented on lib/ansible/modules/source_control/github_release.py
> +- name: Get latest release of test repo using username and password
Done.

2017-05-03 09:19 UTC, Akasurde commented on lib/ansible/modules/source_control/github_release.py
> +        required: true
Done.

2017-05-03 09:22 UTC, Akasurde commented on lib/ansible/modules/source_control/github_release.py
> +            password=dict(required=True),
Done.

2017-05-03 10:26 UTC, gundalow commented on lib/ansible/modules/source_control/github_release.py
> +        required_one_of=(('password', 'token'),),
I believe you need to remove `required=True` from `password` and `token` in `argument_spec` and in the `DOCUMENTATION` block.

2017-05-03 15:34 UTC, gundalow approved these changes

2017-05-03 15:35 UTC, gundalow commented
@adrianmoisey There have been a few changes since you looked last, could you please cast your eye over this again. Thanks

2017-05-10 14:45 UTC, Akasurde commented
@adrianmoisey Could you please take a look into this PR ?

2017-05-19 02:21 UTC, Akasurde commented
@adrianmoisey Ping.

2017-05-19 05:24 UTC, adrianmoisey commented
Sorry, I've been missing the notification.
This looks great! :+1:

2017-05-19 05:25 UTC, adrianmoisey commented
shipit

2017-05-19 05:26 UTC, adrianmoisey commented
(I don't know how this bot works, or if I'm considered a maintainer)

2017-05-19 07:06 UTC, gundalow commented
Closing/re-opening to trigger CI

2017-05-19 07:49 UTC, merged

2017-05-19 07:49 UTC, gundalow commented
Merged, thanks :)

2017-05-19 08:04 UTC, Akasurde commented
@gundalow Thanks for review.

2017-05-19 08:05 UTC, Akasurde commented
@adrianmoisey Thanks for review.