Set terminal width for network *_command modules to avoid paging Fixes #23474
ansible/ansible pull request #23728
Opened 2017-04-19 06:44 UTC by trishnaguha

Signed-off-by: Trishna Guha <trishnaguha17@gmail.com>

##### SUMMARY

Fixes #23474 
The terminal width on network devices isn't being set to avoid paging. If a command goes over the default amount the output from a `*_command` module will include the paged output of the command first.
The PR adds Terminal width to `512` so that paging can be avoided in the output for network `*_command` modules.

##### ISSUE TYPE

 Bugfix Pull Request

##### COMPONENT NAME

- plugins/terminal/ios.py
- plugins/terminal/iosxr.py
- plugins/terminal/eos.py
- plugins/terminal/nxos.py
- plugins/terminal/vyos.py
- plugins/terminal/dellos10.py
- plugins/terminal/dellos6.py
- plugins/terminal/dellos9.py

##### ANSIBLE VERSION

```
2.3
```

2017-04-19 07:13 UTC, gundalow commented
@dhivyap @skg-net are these commands valid on dellos?

2017-04-19 07:59 UTC, ganeshrn requested changes
For `junos` please add command to set the screen-width ```set cli screen-width 1024```

2017-04-19 08:22 UTC, trishnaguha commented on lib/ansible/plugins/terminal/junos.py
> +            for c in ['set cli timestamp disable', 'set cli screen-length 0', 'set cli screen-width 1024']:
@ganeshrn Added `width` for `junos`.

2017-04-19 10:19 UTC, privateip commented
@skg-net could you please review?

2017-04-21 05:48 UTC, ganeshrn approved these changes

2017-04-24 18:51 UTC, skg-net requested changes

2017-04-24 18:51 UTC, skg-net commented on lib/ansible/plugins/terminal/dellos10.py
> +            for cmd in ['terminal length 0', 'terminal width 512']:
'terminal width 512' command is not supported in dellos10

2017-04-24 18:51 UTC, skg-net commented on lib/ansible/plugins/terminal/dellos6.py
> +            for cmd in ['terminal length 0', 'terminal width 512']:
'terminal width 512' command is not supported in dellos6

2017-04-24 18:51 UTC, skg-net commented on lib/ansible/plugins/terminal/dellos9.py
> +            for cmd in ['terminal length 0', 'terminal width 512']:
'terminal width 512' command is not supported in dellos9.

2017-04-25 03:08 UTC, trishnaguha commented on lib/ansible/plugins/terminal/dellos9.py
> +            for cmd in ['terminal length 0', 'terminal width 512']:
@skg-net Thanks for the review. I will modify the PR.

2017-04-25 06:45 UTC, gundalow approved these changes

2017-04-25 08:40 UTC, merged

2017-04-26 16:48 UTC, skg-net reviewed
Approved

2017-04-26 16:56 UTC, trishnaguha commented
Thanks @skg-net .