Add support for 'MapPublicIpOnLaunch' subnet attribute in cloud/amazon/ec2_vpc_subnet
ansible/ansible pull request #23783
Opened 2017-04-20 05:19 UTC by brandond

##### SUMMARY
Adds support for MapPublicIpOnLaunch option on VPC subnets. Boto3 is required, as this option is not exposed by the legacy boto API.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
cloud/amazon/ec2_vpc_subnet

##### ANSIBLE VERSION
```
ansible 2.4.0
  config file = /home/ec2-user/repos/cmb-infosec-ansible/ansible.cfg
  configured module search path = [u'/home/ec2-user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ec2-user/ansible-env/lib/python2.7/site-packages/ansible
  executable location = /home/ec2-user/ansible-env/bin/ansible
  python version = 2.7.13+ (default, Feb 24 2017, 13:51:49) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

2017-06-01 22:23 UTC, brandond commented
@willthames @s-hertel any chance I could get a review?

2017-06-02 08:50 UTC, willthames requested changes
Just minor things really, shouldn't be too huge a blocker

2017-06-02 08:50 UTC, willthames commented on lib/ansible/modules/cloud/amazon/ec2_vpc_subnet.py
> +from ansible.module_utils.ec2 import *  # noqa
please make the imports explicit

2017-06-02 08:50 UTC, willthames commented on lib/ansible/modules/cloud/amazon/ec2_vpc_subnet.py
> +            module.fail_json(msg='Unable to update tags for {0}: {1}'.format(subnet['id'], e))
Use the [boto3 exception guidelines](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/GUIDELINES.md#boto3-2)

2017-06-02 08:50 UTC, willthames commented on lib/ansible/modules/cloud/amazon/ec2_vpc_subnet.py
> +    if 'subnet_id' in subnet:
Nice, I was a bit worried the output might change but I see you've thought about that with this.

2017-06-02 08:54 UTC, willthames commented
I've run this on a test EC2 VPC and it seems to work exactly as I'd expect, so no concerns over functionality.

2017-06-29 13:11 UTC, willthames approved these changes

2017-06-29 13:11 UTC, willthames commented
Closing and reopening for hopefully one more last CI run

2017-06-29 13:39 UTC, merged