amazon/ec2_vpc_igw: Allow EC2 VPC internet gateways to be tagged
ansible/ansible pull request #23782
Opened 2017-04-20 05:11 UTC by brandond

##### SUMMARY
Add tags support to ec2_vpc_igw modlue

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
cloud/amazon/ec2_vpc_igw

##### ANSIBLE VERSION
```
ansible 2.4.0
  config file = /home/ec2-user/repos/cmb-infosec-ansible/ansible.cfg
  configured module search path = [u'/home/ec2-user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ec2-user/ansible-env/lib/python2.7/site-packages/ansible
  executable location = /home/ec2-user/ansible-env/bin/ansible
  python version = 2.7.13+ (default, Feb 24 2017, 13:51:49) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

2017-04-25 15:05 UTC, s-hertel requested changes

2017-04-25 15:05 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/ec2_vpc_igw.py
> +    if tags != igw.tags:
I think this should be `if tags and tags != igw.tags:`. Otherwise if we're creating a gateway with no tags this condition will be met and it will crash later since there are no tags. On second thought, just make the default of tags be an empty dict instead of None, [here](https://github.com/ansible/ansible/pull/23782/files#diff-7c7439a69b0a017fb8e03a769c5ef29bR179) and it will fix the problem.

2017-04-25 15:05 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/ec2_vpc_igw.py
> +            result = ensure_igw_absent(connection, vpc_id, tags, check_mode=module.check_mode)
We don't need to pass tags here.

2017-04-25 15:05 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/ec2_vpc_igw.py
> +def ensure_igw_absent(vpc_conn, vpc_id, tags, check_mode):
We don't need tags in this function, I think.

2017-06-01 22:13 UTC, brandond commented on lib/ansible/modules/cloud/amazon/ec2_vpc_igw.py
> +    if tags != igw.tags:
@s-hertel tags defaults to an empty dict as per the argument spec; can you mark this as reviewed?

2017-06-02 09:04 UTC, willthames commented on lib/ansible/modules/cloud/amazon/ec2_vpc_igw.py
> +def ensure_tags(vpc_conn, resource_id, tags, add_only, check_mode):
Should probably use `compare_aws_tags` for future reference but not a blocker here as it is only recently available

2017-06-02 09:06 UTC, willthames commented
shipit

2017-06-02 10:11 UTC, s-hertel approved these changes

2017-06-02 11:38 UTC, merged

2017-06-09 22:59 UTC, grugnog commented
I believe this change may have introduced an issue: #25561