Added Support for creating a Zabbix Inventory. It is possible to tag the
ansible/ansible pull request #23792
Opened 2017-04-20 10:04 UTC by argo1984

##### SUMMARY

Added Support for creating a Zabbix Inventory. It is possible to tag the hosts and add Locations etc.

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

Module: zabbix_host

##### ANSIBLE VERSION

```
> ansible --version
ansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Mar 24 2017, 09:43:28) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### ADDITIONAL INFORMATION

Usage Example in task:

```
- name: "Create a new host or update an existing host's info"
  local_action:
    module: zabbix_host
    server_url: "{{ zabbix_url }}"
    login_user: "{{ zabbix_api_user }}"
    login_password: "{{ zabbix_api_pass }}"
    host_name: "{{ zabbix_hostname }}"
    host_groups: "{{ zabbbix_hostgroup }}"
    link_templates: "{{ zabbix_link_templates }}"
    inventory_mode: automatic
    inventory_zabbix:
      tag: "{{ your_tag }}"
      alias: "{{ your_alias }}"
      notes: "Special Informations: {{ your_informations | default('None') }}"
      location: "{{ your_location }}"
      site_rack: "{{ your_site_rack }}"
      os: "{{ your_os }}"
      hardware: "{{ your_hardware }}"
      vendor: "{{ your_vendor }}"
    status: "{{ zabbix_host_status }}"
    state: "{{ zabbix_create_host }}"
    proxy: "{{ zabbix_proxy }}"
    interfaces: "{{ zabbix_interfaces }}"
  tags:
    - api
```

2017-04-22 10:35 UTC, gundalow requested changes

2017-04-22 10:35 UTC, gundalow commented on lib/ansible/modules/monitoring/zabbix_host.py
> +        version_added: '2.3'
`'2.4'`

2017-04-22 10:35 UTC, gundalow commented on lib/ansible/modules/monitoring/zabbix_host.py
> +    inventory_zabbix:
Could you please add an example for this new option. Thanks

2017-06-08 12:44 UTC, argo1984 commented on lib/ansible/modules/monitoring/zabbix_host.py
> +        version_added: '2.3'
Hi,

i added an example. Sorry i didn't see your message before.

2017-06-08 15:21 UTC, gundalow approved these changes

2017-06-08 15:22 UTC, gundalow commented
@eikef Could you please cast your eye over this PR, thanks

2017-09-15 07:25 UTC, D3DeFi commented
Description of this option can use a link to [host inventory arguments](https://www.zabbix.com/documentation/3.2/manual/api/reference/host/object#host_inventory) as well as note that this needs to be paired with `inventory_mode: manual`.

Other than that it just needs [rebase](http://docs.ansible.com/ansible/latest/dev_guide/developing_rebasing.html) due to merge conflicts and will be good to ship.

2017-10-05 21:03 UTC, eikef commented
Of the same opinion as @D3DeFi 

After a rebase it looks good to ship.

2017-10-18 20:54 UTC, eikef commented
Thank you :-)

2017-10-18 20:54 UTC, eikef commented
shipit

2017-10-20 08:41 UTC, D3DeFi commented
shipit

2017-10-20 08:45 UTC, merged