Add wait_for_reboot option to win_reboot module
ansible/ansible pull request #23835
Opened 2017-04-20 20:23 UTC by andrewsaraceni

##### SUMMARY
Adds support for issuing a reboot on a Windows machine without waiting for the system to re-appear on the network.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
lib/ansible/plugins/action/win_reboot.py

##### ANSIBLE VERSION

```
ansible 2.4.0
```

##### ADDITIONAL INFORMATION
Set to a default value of True for backward compatibility.
```
- name: Issue reboot without waiting for system to re-appear
  win_reboot:
    wait_for_reboot: no
```

2017-04-20 23:10 UTC, dagwieers commented
If you're not interested in a successful completion, use the async_wrapper instead.
That is what it is used for.

I am not in favor of this change.

2017-04-20 23:25 UTC, andrewsaraceni commented
Hey @dagwieers , I think depending on your perspective, the definition of a successful completion can vary.  e.g. In the case of invoking Restart-Computer in PowerShell, without any additional parameters, the issuing of the restart itself essentially is determined to be a successful completion, rather than requiring a check for the machine's re-appearance on the network.

https://msdn.microsoft.com/en-us/powershell/reference/5.1/microsoft.powershell.management/restart-computer

We've also had cases on our end where after domain joining and restarting, Group Policy gets applied that can impact the ability for `ansible_user` and `ansible_password`, as defined prior to running the play, to continue as the remote connection after reboot.  The ability to end the win_reboot immediately after issuing it, override the credentials, and carry on is a great convenience.

Happy to explain further if it helps!

2017-04-20 23:33 UTC, dagwieers commented
@andrewsaraceni There is no guarantee that a Restart-Computer will work after issuing it.

Regardless your feature request could be requested for any module, and the async_wrapper was designed for exactly the purpose. http://docs.ansible.com/ansible/playbooks_async.html

```yaml
- win_reboot:
  async: 3600
  poll: 0
```
This works for any task.

2017-04-21 00:11 UTC, andrewsaraceni commented
Thanks for the reply @dagwieers !  When I run the following:
```
  - name: Test restart with async
    win_reboot:
    async: 10
    poll: 0
    register: reboot_register
```

I get a response back of async not being supported and the task being skipped, though it actually executes.

```
ok: [10.150.25.233] => {
    "msg": {
        "changed": true,
        "msg": "async is not supported for this task.",
        "rebooted": true,
        "skipped": true,
        "warnings": []
    }
}
```

Seems like a false positive - is there something I'm doing wrong, or should the module be modified to handle this better?

2017-04-21 00:13 UTC, andrewsaraceni commented
I should note that the "ok" is for the debug output of my register variable, the actual -v output is:
```
TASK [Test restart with async] *****************************************************************
skipping: [10.150.25.233] => {"changed": true, "msg": "async is not supported for this task.", "rebooted": true, "skipped": true, "warnings": []}
```

2017-04-21 00:18 UTC, dagwieers commented
@nitzmahone Do we still have known issues with the async support on Windows ? Or is this related to async+action plugins ?

2017-04-21 00:21 UTC, dagwieers commented
@andrewsaraceni Looking at the code, we should probably tell Ansible that win_reboot supports async, currently it does not. Why it did run while it should have been skipped, is beyond my comprehension, and possible another bug. Welcome into uncharted territory :)

2017-04-21 00:53 UTC, dagwieers commented
I added check-mode and async support in PR #22178 however beware that the integration tests indicate an issue. Feel free to test this and report back ! Thanks in advance.

2017-04-21 01:02 UTC, nitzmahone commented
@dagwieers likely the latter- async actions are kind of a misnomer, as IIRC they're not actually async'd by the executor (something about running internal modules via async). @bcoca explained it to me when he first put it in (as I had similar questions), but the salient details have been lost in the fog. 

Regardless, just marking this action async will likely not have the desired effect. However the fact that it ran anyway is of concern to me- to wit: https://github.com/ansible/ansible/issues/23840

All that said, I'm actually not opposed to some form of this change...

2017-04-21 01:04 UTC, dagwieers commented
I think I nailed the bug in PR #22178 related to it running when it should have been skipped.

2017-04-21 01:17 UTC, dagwieers commented
Well, after some testing, async and check-mode seem to work with PR #22178 !?

2017-04-21 01:22 UTC, nitzmahone commented
Yeah, was gonna say, there's some magic happening I'm not privy to if async works. ;)

2017-04-21 01:55 UTC, andrewsaraceni commented
Thanks @dagwieers, #22178 fixes the bug for me (just tested it).  @nitzmahone, happy to adjust my PR (if needed) if you end up moving forward with this.

2017-08-20 03:35 UTC, dagwieers commented
So I moved the fix from PR #22178 into PR #28448 to get it merged, and backported to v2.3 !

2017-08-20 03:36 UTC, dagwieers requested changes
I do not want this feature to be added.

2017-08-20 15:55 UTC, andrewsaraceni commented
@dagwieers  If #28448 will make:
```yml
- win_reboot:
  async: 10
  poll: 0
```
possible, that's a sufficient alternative in my view to what I put into this PR.  I've been doing a mix of `win_shell: Restart-Computer` and 
```yml
- win_reboot:
    reboot_timeout_sec: 5
  failed_when: no
``` 
to get around this in the interim.

2017-08-29 21:49 UTC, closed without merging