ec2: Allow EC2-VPC instances to modify security groups - fixes #18928
ansible/ansible pull request #23831
Opened 2017-04-20 19:57 UTC by s-hertel

make ec2 pep8

##### SUMMARY
EC2-VPC instances can modify security groups. Added that feature to the ec2 module. Made ec2 pep8 and removed from legacy file. Fixes #18928

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
lib/ansible/modules/cloud/amazon/ec2.py

##### ANSIBLE VERSION
```
2.4.0
```

2017-05-12 13:50 UTC, ryansb requested changes

2017-05-12 13:50 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/ec2.py
> +            if inst.vpc_id and (group_id or group_name):
Can you restructure this to:

```
if inst.vpc_id and group_name:
    # current contents of the if group_name$s
elif inst.vpc_id and group_id:
    # the contents of the elif below
```

To bring things in an indentation level?

2017-05-15 11:26 UTC, ryansb approved these changes
Looks great, thanks!

2017-05-31 14:57 UTC, abadger commented on lib/ansible/modules/cloud/amazon/ec2.py
> +                if len(unmatched) > 0:
note: tests for zero length and nonzero length containers can test the container directly:
``` python
# equivalent:
if unmatched: pass
if len(unmatched) == 0: pass

# also equivalent:
if not unmatched: pass
if len(unmatched) > 0: pass
```

2017-06-14 15:10 UTC, ryansb approved these changes

2017-06-14 15:10 UTC, merged

2017-06-29 08:13 UTC, davidfischer-ch commented
Hello, is it possible to provide us with an example call ? I am eager to test it when released.

Thanks.

2017-06-30 18:07 UTC, s-hertel commented
hi @davidfischer-ch, thanks for the interest.
This change allows you to run something like:
```
      ec2:
        region: us-east-1
        instance_ids: "{{ instance_ids }}"
        vpc_subnet_id: subnet-XXXXXXXX
        state: running
        group_id:
          - sg-XXXXXXXX
          - sg-XXXXXXXX
```
which replaces the instances' security groups with the newly specified one(s), and if you don't specify new groups (using `group_id` or `group`) no change will be made.

2017-09-20 12:03 UTC, AnishAnil commented
What version of Ansible will this fix be available??
This is one of the most needed feature in AWS and hoping to have this released on priority.

2017-09-20 17:00 UTC, s-hertel commented
@AnishAnil This fix is available in version 2.4.