fix 23810
ansible/ansible pull request #23907
Opened 2017-04-24 10:17 UTC by bjolivot

##### SUMMARY

Fix bug in systemd module when used for daemon-reload only

Fixes #23810

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

systemd

##### ANSIBLE VERSION

```
ansible 2.4.0 (fix_23810 6bbd19de73) last updated 2017/04/24 12:15:49 (GMT +200)
```

##### ADDITIONAL INFORMATION

```

```

2017-04-24 10:44 UTC, resmo requested changes
based on code review the patch looks reasonable. Please use more detailed commit messages (https://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message) and minor improvement, that is why I mark it for "request changes"

2017-04-24 10:44 UTC, resmo commented on lib/ansible/modules/system/systemd.py
> +        if module.params[requires] is not None and unit is None:
I would even change it to:
~~~ python
if module.params.get(requires) is not None and unit is None:
~~~

2017-04-24 11:20 UTC, bjolivot commented on lib/ansible/modules/system/systemd.py
> +        if module.params[requires] is not None and unit is None:
done

2017-04-24 11:50 UTC, bjolivot commented
ready_for_review

2017-04-24 11:53 UTC, resmo approved these changes

2017-04-24 12:51 UTC, bcoca requested changes

2017-04-24 12:51 UTC, bcoca commented on lib/ansible/modules/system/systemd.py
> +        if module.params.get(requires) is not None and unit is None:
no need for get, you always have the paramters initialized to default (None)

2017-04-24 12:51 UTC, bcoca commented on lib/ansible/modules/system/systemd.py
> +
this is not needed as each section checks for the parameter

2017-04-24 13:19 UTC, bjolivot commented on lib/ansible/modules/system/systemd.py
> +
I don't check parameters, I exit module if nothing else to do.

2017-04-24 16:40 UTC, bcoca commented on lib/ansible/modules/system/systemd.py
> +
yes, this is equivalent to the 3 ifs that follow, there is no need for this duplication

2017-04-25 00:22 UTC, mscherer commented on lib/ansible/modules/system/systemd.py
> +
wouldn't it be easier to verify if 'unit' is None ? as that's the issue as discussed on irc?

2017-04-25 12:23 UTC, bjolivot commented
bug fixed in other PR

2017-04-25 12:23 UTC, closed without merging