nxos_acl fixes
ansible/ansible pull request #23915
Opened 2017-04-24 15:27 UTC by Qalthos

##### SUMMARY

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

nxos_acl

##### ANSIBLE VERSION

```
2.4
``

##### ADDITIONAL INFORMATION

```

```

-

2017-04-25 18:06 UTC, rcarrillocruz approved these changes

2017-04-26 05:56 UTC, trishnaguha requested changes
So this initialization `results = {}` can be removed now https://github.com/Qalthos/ansible/blob/3571cfd7919c0be455f989a987bf87a96ed57148/lib/ansible/modules/network/nxos/nxos_acl.py#L538

2017-04-26 13:54 UTC, Qalthos commented
Good catch, @trishnaguha, fixed.

2017-04-26 13:57 UTC, trishnaguha approved these changes

2017-04-26 20:29 UTC, merged