[WIP] Docs how to test
ansible/ansible pull request #23925
Opened 2017-04-24 19:28 UTC by gundalow

##### SUMMARY
Large refactor and update of testing docs

* Combine all the testing documentation in to one place to make it easier
to find
* Convert everything to RST
* Create `testing_network` guide
* Create `testing` landing page
* For each section detail "how to run" and "how to extend testing"

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
Testing

##### ANSIBLE VERSION
2.4.0

2017-04-26 14:44 UTC, gundalow commented
This is in a decent enough state now to get extra eyes on it

@s-hertel Could you please look at `testing_integration_legacy.rst` which has Cloud info in

2017-04-26 14:57 UTC, samdoran commented on docs/docsite/rst/dev_guide/testing.rst
> +* how ansible is tested
Capitalize 'ansible'

2017-04-26 14:57 UTC, samdoran commented on docs/docsite/rst/dev_guide/testing.rst
> +This page, and it's subpages, describes:
describes --> describe

2017-04-26 14:58 UTC, samdoran commented on docs/docsite/rst/dev_guide/testing.rst
> +If you're a developer, one of the most valuable things you can do is look at the github issues list and help fix bugs.  We almost always prioritize bug fixing over
github --> GitHub

2017-04-26 14:59 UTC, samdoran commented on docs/docsite/rst/dev_guide/testing.rst
> +This goes for testing new features as well as testing bugfixes.
bugfixes --> bug fixes

2017-04-26 14:59 UTC, samdoran commented on docs/docsite/rst/dev_guide/testing.rst
> +Testing withing GitHub & Shippable
Testing **within** GitHub and Shippable

2017-04-26 15:00 UTC, samdoran commented on docs/docsite/rst/dev_guide/testing.rst
> +When Pull Requests (PRs) are created they are tested using Shippable, a Continuous Integration (CI) tool. Results are show at the end of every PR.
show --> shown

2017-04-26 15:02 UTC, samdoran commented on docs/docsite/rst/dev_guide/testing.rst
> +Thankfully helping test ansible is pretty straightforward, assuming you are already used to how ansible works.
Thankfully**,** helping test Ansible...

2017-04-26 15:02 UTC, samdoran commented on docs/docsite/rst/dev_guide/testing.rst
> +Thankfully helping test ansible is pretty straightforward, assuming you are already used to how ansible works.
Also capitalize the other "ansible".

2017-04-26 15:02 UTC, samdoran commented on docs/docsite/rst/dev_guide/testing.rst
> +You can do this by checking out ansible, making a test branch off the main one, merging a GitHub issue, testing,
ansible --> Ansible

2017-04-26 15:03 UTC, samdoran commented on docs/docsite/rst/dev_guide/testing.rst
> +   or Docker for this, but they are optional.  It is also useful to have virtual machines of different Linux or
Two spaces before "It". Most sentences seem to have one space (which is preferable, IMO).

2017-04-26 15:04 UTC, samdoran commented on docs/docsite/rst/dev_guide/testing.rst
> +   It is important that the PR request target be ansible:devel, as we do not accept pull requests into any other branch.  Dot releases are cherry-picked manually by Ansible staff.
Two spaces before "Dot".

2017-04-26 15:05 UTC, samdoran commented on docs/docsite/rst/dev_guide/testing.rst
> +The first command creates and switches to a new branch named testing_PRXXXX, where the XXXX is the actual issue number associated with the pull request (for example, 1234). This branch is based on th
I'm a fan of use inline code syntax highlighting for branch names.

devel --> `devel`

2017-04-26 15:05 UTC, samdoran commented on docs/docsite/rst/dev_guide/testing.rst
> +   If the GitHub user interface shows that the pull request will not merge cleanly, we do not recommend proceeding if you are not somewhat familiar with git and coding, as you will have to resolve a
Two spaces before "This".

2017-04-26 15:05 UTC, samdoran commented on docs/docsite/rst/dev_guide/testing.rst
> +   Some users do not create feature branches, which can cause problems when they have multiple, un-related commits in their version of `devel`. If the source looks like `someuser:devel`, make sure th
un-related --> unrelated

2017-04-26 15:06 UTC, samdoran commented on docs/docsite/rst/dev_guide/testing.rst
> +The first command creates and switches to a new branch named testing_PRXXXX, where the XXXX is the actual issue number associated with the pull request (for example, 1234). This branch is based on th
This is consistent with other branches mentioned below.

2017-04-26 15:06 UTC, samdoran commented on docs/docsite/rst/dev_guide/testing.rst
> +full installation, that is frequently used by developers on Ansible.
Remove comma after "installation".

2017-04-26 15:14 UTC, samdoran commented on docs/docsite/rst/dev_guide/testing.rst
> +   Some users do not create feature branches, which can cause problems when they have multiple, un-related commits in their version of `devel`. If the source looks like `someuser:devel`, make sure th
Needs double backtick rather than single.

2017-04-26 15:14 UTC, samdoran commented on docs/docsite/rst/dev_guide/testing.rst
> +   | Works for me!  Tested on `Ansible 2.3.0`.  I verified this on CentOS 6.5 and also Ubuntu 14.04.
Double backtick.

2017-04-26 15:16 UTC, samdoran commented on docs/docsite/rst/dev_guide/testing_httptester.rst
> +Both ways of building docker utilize the ``nginx:alpine`` image, but can
Maybe capitalize Docker, or change to "building the container".

2017-04-26 15:18 UTC, samdoran commented on docs/docsite/rst/dev_guide/testing_httptester.rst
> +When utilizing ``packer`` or configuring with ``ansible-playbook``
Commas placement:

 When utilizing ``packer`` or configuring with ``ansible-playbook``, the services will not automatically start on launch and will have to be...
 +manually started using::

2017-04-26 15:19 UTC, samdoran commented on docs/docsite/rst/dev_guide/testing_httptester.rst
> +If you have sometime to improve httptester please add a comment on the `Testing Working Group Agenda <https://github.com/ansible/community/blob/master/MEETINGS.md>`_ to avoid duplicated effort.
httptester --> `httptester`

2017-04-26 15:19 UTC, samdoran commented on docs/docsite/rst/dev_guide/testing_integration.rst
> +to a virtual environment, such as docker.  They won't reformat your filesystem::
docker --> Docker or `docker`

2017-04-26 15:20 UTC, samdoran commented on docs/docsite/rst/dev_guide/testing_integration.rst
> +  * To run the network tests you will need a number of test machines and suitably configured inventory file, a sample is included in `test/integration/inventory.network`
Need double backticks.

2017-04-26 15:20 UTC, samdoran commented on docs/docsite/rst/dev_guide/testing_integration.rst
> +  * As with the rest of the integration tests, they can be found grouped by module in `test/integration/targets/MODULENAME/`
Need double backticks.

2017-04-26 15:21 UTC, samdoran commented on docs/docsite/rst/dev_guide/testing_integration.rst
> +To filter a set of test cases set `limit_to` to the name of the group, generally this is the name of the module::
Need double backticks.

2017-04-26 15:21 UTC, trishnaguha reviewed
Is this an empty file or WIP for this PR? https://github.com/gundalow/ansible/blob/12d3db35654f6a9e84a46d762623f68b04a6a097/docs/docsite/rst/dev_guide/developing_modules_networking.rst

2017-04-26 15:23 UTC, samdoran commented on docs/docsite/rst/dev_guide/testing_pep8.rst
> +`PEP 8`_ style guidelines are enforced by ``pep8`` on all python files in the repository by default.
Maybe need double backticks around PEP 8?

2017-04-26 15:26 UTC, samdoran commented on docs/docsite/rst/modules_support.rst
> +For development-oriented topics, use the `ansible-devel google group <https://groups.google.com/forum/#!forum/ansible-devel>`_  or Ansible's "#ansible" and "#ansible-devel" channels, located on irc.f
Use double backticks around IRC channel names rather than double quotes.

"#ansible" --> `#ansible`

"#ansible-devel" --> `#ansible-devel`

2017-04-26 15:27 UTC, trishnaguha commented on docs/docsite/rst/dev_guide/testing.rst
> +  * Functional tests of modules and Ansible language and core functionality.
Anything else can be used instead of `Ansible language` ?

2017-04-26 15:29 UTC, trishnaguha commented on docs/docsite/rst/dev_guide/testing.rst
> +  * Tests directly directly against individual parts of the code base.
*directly* used twice here.

2017-04-26 15:48 UTC, trishnaguha commented on docs/docsite/rst/dev_guide/testing.rst
> +When Shippable detects an error and it can be linked back to a file that has been modified in the PR then then relevant lines will be added as a GitHub comment, for example::
*then the* relevant lines?

2017-04-26 15:50 UTC, trishnaguha commented on docs/docsite/rst/dev_guide/testing.rst
> +From the above we can see that that ``--test pep8`` and ``--test validate-modules`` have identified issues. The commands given allow you to run the same tests locally to ensure you've fixed the issue
Double use of **that** here.

2017-04-26 15:51 UTC, gundalow commented on docs/docsite/rst/dev_guide/testing.rst
> +The first command creates and switches to a new branch named testing_PRXXXX, where the XXXX is the actual issue number associated with the pull request (for example, 1234). This branch is based on th
Yup agreed

2017-04-26 15:54 UTC, gundalow commented on docs/docsite/rst/dev_guide/testing.rst
> +   | Works for me!  Tested on `Ansible 2.3.0`.  I verified this on CentOS 6.5 and also Ubuntu 14.04.
Should be an example of markdown, fixed

2017-04-26 16:26 UTC, trishnaguha commented on docs/docsite/rst/dev_guide/testing.rst
> +   | Works for me!  Tested on `Ansible 2.3.0`.  I verified this on CentOS 6.5 and also Ubuntu 14.04.
Double space after `!` and `.`

2017-04-26 16:32 UTC, trishnaguha commented on docs/docsite/rst/dev_guide/testing_httptester.rst
> +* httpbin
Looks like these are bullet points. There must be an empty line right after the sentence in order to have the bullets.

2017-04-26 16:39 UTC, trishnaguha commented on docs/docsite/rst/dev_guide/testing_integration.rst
> +   From Ansible 2.4 all network modules MUST include corrisponding unit tests to defend functionality.
s/corrisponding/corresponding

2017-04-26 16:45 UTC, trishnaguha commented on docs/docsite/rst/dev_guide/testing_integration_legacy.rst
> +   unexpected resources are running.
Double space after `.` dots.

2017-04-26 16:48 UTC, trishnaguha commented on docs/docsite/rst/dev_guide/testing_sanity.rst
> +A full lust of tests can be obtained by doing ``ansible-test sanity --list-tests``.
s/lust/list :-).

2017-04-26 17:58 UTC, gundalow commented on docs/docsite/rst/dev_guide/testing.rst
> +  * Functional tests of modules and Ansible language and core functionality.
Changed to `Functional tests of modules and Ansible core functionality.`

2017-04-26 18:10 UTC, gundalow commented on docs/docsite/rst/dev_guide/testing_httptester.rst
> +* httpbin
Good spot, fixed

2017-04-26 18:14 UTC, gundalow commented on docs/docsite/rst/dev_guide/testing_integration.rst
> +   From Ansible 2.4 all network modules MUST include corrisponding unit tests to defend functionality.
How annoying, vim doesn't spell check within `.. foo::` sections, good spot, thanks

2017-04-26 19:01 UTC, s-hertel commented on docs/docsite/rst/dev_guide/testing_integration_legacy.rst
> +
You could maybe add something along the lines of:

Some AWS tests may use environment variables. It is recommended to either unset any AWS environment variables (AWS_DEFAULT_PROFILE, AWS_SECRET_ACCESS_KEY, etc) or be sure that the environment variables match the credentials provided in credentials.yml to ensure the tests run with consistency to their full capability on the expected account . See http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html for information on creating a profile. 

Subsets of tests may be run by #commenting out unnecessary roles in the appropriate playbook (such as test/integration/amazon.yml).

2017-04-26 19:32 UTC, gundalow commented on docs/docsite/rst/dev_guide/testing_integration_legacy.rst
> +
Thanks, added

2017-04-27 04:45 UTC, dharmabumstead approved these changes
Looks good with some edits. Good stuff @gundalow - thank you!

2017-04-27 04:45 UTC, dharmabumstead commented on docs/docsite/rst/dev_guide/testing_running_locally.rst
> +This page describes how to:
Please use the word 'document' instead of 'page'.

2017-04-27 12:56 UTC, s-hertel commented on docs/docsite/rst/dev_guide/testing_integration_legacy.rst
> +Some AWS tests may use environment variables. It is recommended to either unset any AWS environment variables( such as ``AWS_DEFAULT_PROFILE``, ``AWS_SECRET_ACCESS_KEY``, etc) or be sure that the env
Extra space in front of the . My fault, sorry!

2017-04-27 19:09 UTC, s-hertel approved these changes

2017-04-27 19:51 UTC, gundalow commented
@mattclay Good spot, fixed.

The only thing documentation wise is to move `testing_running_locally.rst` into other files. Though I think that can be done in a follow up PR.

2017-04-27 23:43 UTC, mattclay commented
CI failure was unrelated to this PR. The issue has been resolved and CI is now passing.

2017-04-28 01:03 UTC, mattclay requested changes

2017-04-28 01:03 UTC, mattclay commented on Makefile
> +#   make tests ---------------- run the tests (see https://docs.ansible.com/ansible/dev_guide/testing_integration_legacy.html for requirements)
Running `make tests` runs unit tests via `ansible-test`, not the legacy integration tests, so this should link to: https://docs.ansible.com/ansible/dev_guide/testing_units.html

2017-04-28 01:03 UTC, mattclay commented on docs/docsite/rst/dev_guide/testing_pep8.rst
> +.. _skip list: skip.txt
The preceding 4 links should be updated to reference the appropriate locations on GitHub.

2017-04-28 01:03 UTC, mattclay commented on docs/docsite/rst/dev_guide/testing_running_locally.rst
> +See the `list of supported platforms and versions <runner/completion/remote.txt>`_ for additional details.
This should link to: https://github.com/ansible/ansible/blob/devel/test/runner/completion/remote.txt

2017-04-28 01:03 UTC, mattclay commented on docs/docsite/rst/dev_guide/testing_validate-modules.rst
> +****************
We should be encouraging use of validate-modules through `ansible-test sanity`. I'd put instructions for that at the top before the direct usage instructions.

2017-04-28 06:28 UTC, mattclay approved these changes

2017-04-28 06:37 UTC, trishnaguha approved these changes

2017-04-28 10:09 UTC, closed without merging

2017-04-28 10:09 UTC, gundalow commented
Merged into `devel` https://github.com/ansible/ansible/commit/ecbf8e933a7eaccc8e341413d703e45d45d78986