Fixes #23890 ShellError import nxos
ansible/ansible pull request #23947
Opened 2017-04-25 05:32 UTC by trishnaguha

Signed-off-by: Trishna Guha <trishnaguha17@gmail.com>

##### SUMMARY

Fixes #23890 
Import `ShellError` to avoid `undefined` error.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

- modules/network/nxos/nxos_bgp.py
- modules/network/nxos/nxos_bgp_af.py
- modules/network/nxos/nxos_bgp_neighbor.py
- modules/network/nxos/nxos_bgp_neighbor_af.py
- modules/network/nxos/nxos_evpn_vni.py
- modules/network/nxos/nxos_file_copy.py
- modules/network/nxos/nxos_igmp.py
- modules/network/nxos/nxos_interface.py
- modules/network/nxos/nxos_interface_ospf.py
- modules/network/nxos/nxos_ntp_auth.py
- modules/network/nxos/nxos_ospf.py
- modules/network/nxos/nxos_ospf_vrf.py
- modules/network/nxos/nxos_pim.py
- modules/network/nxos/nxos_pim_rp_address.py
- modules/network/nxos/nxos_smu.py
- modules/network/nxos/nxos_vrf_af.py
- modules/network/nxos/nxos_vxlan_vtep.py

##### ANSIBLE VERSION

```
devel
```

2017-04-25 06:48 UTC, gundalow approved these changes

2017-04-25 13:04 UTC, Qalthos requested changes
So none of these modules actually need ShellError... it's an old carryover from pre-2.3 days. What you can do instead is remove the `try [...] except ShellError` blocks around the code, as that code should not throw ShellErrors

2017-04-25 14:22 UTC, trishnaguha commented
@Qalthos Let me clarify that sounds like refactor of `nxos_interface` for `2.3` right? 
If yes I will push refactor of `nxos_interface` here in this PR and exclude other modules from the PR.

2017-04-25 17:47 UTC, Qalthos reviewed
Other than stepping on the toes of my nxos_bgp PR, this looks good. Look into the comments I left and this should be good to go.

2017-04-25 17:47 UTC, Qalthos commented on lib/ansible/modules/network/nxos/nxos_evpn_vni.py
> +from ansible.module_utils.shell import ShellError
Do we really still need this?

2017-04-25 17:47 UTC, Qalthos commented on lib/ansible/modules/network/nxos/nxos_interface.py
> -        except (IndexError, ShellError):
The IndexError seems like it might still be relevant, given the `[0]` above

2017-04-25 18:02 UTC, trishnaguha commented on lib/ansible/modules/network/nxos/nxos_evpn_vni.py
> +from ansible.module_utils.shell import ShellError
Looks like I missed it.

2017-04-26 09:46 UTC, trishnaguha commented
It makes sense to remove `nxos_interface` from this PR as the nxos_interface refactoring PR in on the way https://github.com/ansible/ansible/pull/24008.

2017-04-26 15:16 UTC, Qalthos approved these changes

2017-04-26 15:16 UTC, Qalthos commented
shipit

2017-04-26 15:18 UTC, Qalthos requested changes
Er, actually, rename that commit if you are no longer fixing the mentioned issue, otherwise github will probably autoclose it

2017-04-28 05:11 UTC, trishnaguha commented
@Qalthos Oh yeah right. Thanks.
FYI #24008 has closed the issue #23890 . I will merge this PR now.

2017-04-28 05:12 UTC, merged

2017-04-28 05:12 UTC, trishnaguha commented
This should be cherry picked in `stable-2.3`.