Allow to specify a custom zone_id for a new Google Cloud DNS zone
ansible/ansible pull request #23953
Opened 2017-04-25 09:16 UTC by dmzkrsk

##### SUMMARY
A current implementation of gcdns_zone relies on `libcloud` to convert a domain name to zone_id for Google Cloud DNS.

However their implementation is buggy when domain name is started with a digit.

https://cloud.google.com/dns/troubleshooting says:

The managed zone creation operation can fail with this error if the managed zone name does not begin with a letter, end with a letter or digit, and contain only lowercase letters, digits, or dashes.

I created a corresponding issue on ASF JIRA: https://issues.apache.org/jira/browse/LIBCLOUD-913

However, I think, that ansible should provide a way to manually customize zone id

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
gcdns_zone

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 18 2016, 07:03:39) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### ADDITIONAL INFORMATION

```

```

2017-05-31 15:11 UTC, ryansb commented
cc/ @erjohnso

2017-07-11 18:47 UTC, erjohnso commented
This looks good to merge @ryansb

2017-07-12 20:56 UTC, ryansb requested changes

2017-07-12 20:56 UTC, ryansb commented on lib/ansible/modules/cloud/google/gcdns_zone.py
> +        default: null
This needs a version_added key, per Shippable. `ERROR: lib/ansible/modules/cloud/google/gcdns_zone.py:0:0: E309 version_added for new option (zone_id) should be 2.4. Currently 0.0 (75%)`

2018-02-04 10:18 UTC, ilgarm commented
hi! would be great to have this functionality, as reverse zones are not manageable on gcp through ansible currently

2020-08-17 03:37 UTC, closed without merging