Pep8 fixes for known_hosts.py
ansible/ansible pull request #24029
Opened 2017-04-26 18:01 UTC by Akasurde

##### SUMMARY
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/modules/system/known_hosts.py

##### ANSIBLE VERSION
```
2.4 devel
```

2017-04-26 21:05 UTC, resmo approved these changes
shipit

2017-04-26 22:14 UTC, mcv21 commented on lib/ansible/modules/system/known_hosts.py
> +                        continue  # skip this line to replace its key
I don't like this change - why add a second space before the `#`?

2017-04-26 22:14 UTC, mcv21 commented on lib/ansible/modules/system/known_hosts.py
> +
Why this extra blank line?

2017-04-26 22:15 UTC, mcv21 commented on lib/ansible/modules/system/known_hosts.py
> +    rc, stdout, stderr = module.run_command([sshkeygen, '-F', host, '-f', outf.name], check_rc=True)
This is a very long line (and wraps in my editor). Are you sure this is an improvement?

2017-04-26 22:16 UTC, mcv21 commented on lib/ansible/modules/system/known_hosts.py
> +
ditto previous comment re extra blank lines before functions.

2017-04-26 22:17 UTC, mcv21 commented on lib/ansible/modules/system/known_hosts.py
> +        argument_spec=dict(
No, the previous formatting was much better here for this block, much more readable.

2017-04-26 22:18 UTC, mcv21 commented
+needs_revision

See my comments on the diff. Thanks!

2017-04-26 22:18 UTC, mcv21 commented
needs_revision

2017-04-27 06:03 UTC, Akasurde commented on lib/ansible/modules/system/known_hosts.py
> +                        continue  # skip this line to replace its key
Inline comment requires 2 spaces.

2017-04-27 06:08 UTC, Akasurde commented on lib/ansible/modules/system/known_hosts.py
> +
pep8 warning say : E302 expected 2 blank lines, found 1

2017-04-27 06:09 UTC, Akasurde commented on lib/ansible/modules/system/known_hosts.py
> +    rc, stdout, stderr = module.run_command([sshkeygen, '-F', host, '-f', outf.name], check_rc=True)
Will revert to original.

2017-04-27 06:10 UTC, Akasurde commented on lib/ansible/modules/system/known_hosts.py
> +        argument_spec=dict(
ok.

2017-04-27 06:45 UTC, Akasurde commented
ready_for_review

2017-04-27 07:26 UTC, mcv21 commented
Thanks for this.
shipit

2017-04-27 11:26 UTC, sivel requested changes

2017-04-27 11:26 UTC, sivel commented on lib/ansible/modules/system/known_hosts.py
> +            state     = dict(default='present', choices=['absent', 'present']),
If you are fixing pep8 please remove all of these spaces so we can remove this file from legacy.

I see there was a comment here before saying someone liked the formatting better originally but you seem to have squashed commits removing history.

Unfortunately, if that is what the other comment was for, it was wrong.

2017-04-27 12:11 UTC, mcv21 commented on lib/ansible/modules/system/known_hosts.py
> +            state     = dict(default='present', choices=['absent', 'present']),
It's a matter of aesthetics, but I do think the `argument_spec` is clearly laid out and very readable as it is (i.e. with all the `=` lining up). Which is why I requested it be left alone.

2017-04-27 14:21 UTC, sivel approved these changes

2017-04-27 14:21 UTC, merged

2017-04-27 14:21 UTC, sivel commented
Merged, Thanks!

2017-04-28 04:17 UTC, Akasurde commented
@sivel @resmo @mcv21 Thanks.