Jboss Cli Module for Ansible
ansible/ansible pull request #24086
Opened 2017-04-27 20:01 UTC by Wolfant

##### SUMMARY

Is a new module, connect ansible with jboss cli,
jboss-cli.sh is needed on remote host because remote connectios could cause errors when jboss
is running on heavy loads.

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME

JBoss-Cli module

##### ANSIBLE VERSION

```
ansible --version
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 12 2017, 17:59:37) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```
and

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```

##### ADDITIONAL INFORMATION

```

```

2017-04-28 08:10 UTC, Akasurde requested changes

2017-04-28 08:10 UTC, Akasurde commented on lib/ansible/modules/web_infrastructure/jbosscli.py
> +  - "jboss-cli.sh need to be runing on client host, and $JAVA_HOME/bin is needeth in Client $PATH"
s/needeth/needed/

2017-04-28 08:10 UTC, Akasurde commented on lib/ansible/modules/web_infrastructure/jbosscli.py
> +# chage scan-interval value, on user wildfy instalation
s/instalation/installation/

2017-04-28 08:10 UTC, Akasurde commented on lib/ansible/modules/web_infrastructure/jbosscli.py
> +#  change ExampleDS datasource user-name, on 192.168.20.55:9990 default instalation
s/instalation/installation/

2017-04-28 08:10 UTC, Akasurde commented on lib/ansible/modules/web_infrastructure/jbosscli.py
> +# Undeploy the hello world application on wildfy server
s/wildfy/wildfly/

2017-04-28 08:10 UTC, Akasurde commented on lib/ansible/modules/web_infrastructure/jbosscli.py
> +        module.fail_json(name='jbosscli', msg=re.findall("failure-description.+", out))
Here, you might want to return `out` if `re.findall`  returns `[]`

2017-04-28 08:10 UTC, Akasurde commented on lib/ansible/modules/web_infrastructure/jbosscli.py
> +      - The location in the filesystem where jboss-cli.sh is
missing 'located.' at end.

2017-04-28 08:10 UTC, Akasurde commented on lib/ansible/modules/web_infrastructure/jbosscli.py
> +      - JBoss server or domain controller, whit management port
Possible typo.

2017-04-28 08:10 UTC, Akasurde commented on lib/ansible/modules/web_infrastructure/jbosscli.py
> +  - "jboss-cli.sh need to be runing on client host, and $JAVA_HOME/bin is needeth in Client $PATH"
s/runing/running/

2017-04-28 08:36 UTC, sm4rk0 commented
Thank you, @Wolfant
That's a valuable contribution.
Did you check what @liquidat did in https://github.com/ansible/ansible-modules-extras/pull/1862 ?
I'm using that module with some [local enhancements](https://gist.github.com/sm4rk0/276b1fdb529fab8d928b7c100fb4f0d8) (changed `command` with `commands` and improved return values).

2017-05-01 05:33 UTC, Wolfant commented
@sm4rk0 i see yours and @liquidat, i try to change JBoss Cli output to json but fail when you use --file and the file have 2 or more commands, or when you have "undefined" data, check my with src instead of command

2017-05-01 06:45 UTC, Akasurde requested changes

2017-05-01 06:45 UTC, Akasurde commented on lib/ansible/modules/web_infrastructure/jbosscli.py
> +# chage scan-interval value, on user wildfly installation
s/chage/change/

2017-05-01 06:45 UTC, Akasurde commented on lib/ansible/modules/web_infrastructure/jbosscli.py
> +    description: if jboss cli command change something
s/jboss/JBoss/

2017-05-01 06:45 UTC, Akasurde commented on lib/ansible/modules/web_infrastructure/jbosscli.py
> +import shutil
Unused import

2017-05-01 06:45 UTC, Akasurde commented on lib/ansible/modules/web_infrastructure/jbosscli.py
> +import time
Unused import

2017-05-01 06:45 UTC, Akasurde commented on lib/ansible/modules/web_infrastructure/jbosscli.py
> +import grp
Unused import

2017-05-01 06:45 UTC, Akasurde commented on lib/ansible/modules/web_infrastructure/jbosscli.py
> +    jsout = None
Unused variable.

2017-05-01 06:45 UTC, Akasurde commented on lib/ansible/modules/web_infrastructure/jbosscli.py
> +    changed = False
Unused variable.

2017-05-01 06:45 UTC, Akasurde commented on lib/ansible/modules/web_infrastructure/jbosscli.py
> +    if command and src:
You can use `mutually_exclusive` for `command` and `src`. You can check [here](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/basic.py#L668) and [here](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/cloudformation.py#L410)

2017-05-01 06:45 UTC, Akasurde commented on lib/ansible/modules/web_infrastructure/jbosscli.py
> +  - "jboss-cli.sh need to be running on client host, and $JAVA_HOME/bin is needed in Client $PATH"
s/Client/client/

2017-05-01 06:45 UTC, Akasurde commented on lib/ansible/modules/web_infrastructure/jbosscli.py
> +        module.fail_json(msg="Argument 'user' need 'password' ")
s/need/needs/

2017-05-01 14:55 UTC, Wolfant commented on lib/ansible/modules/web_infrastructure/jbosscli.py
> +    if command and src:
@Akasurde thanks for your advice, and sorry for my English

2017-05-02 15:14 UTC, Wolfant commented
ready_for_review

2017-05-05 15:37 UTC, smbambling commented
Was going to look at developing a module that used the jboss http api to do something similar.  Any reason you went with using the the jboss-cli.sh script vs hitting the http api end point locally on the host ?

2017-05-31 21:22 UTC, wbrefvem commented
@smbambling 
I have been thinking of doing something similar. I've also been looking at providing extra features for [Jolokia](https://jolokia.org/)-enabled instances and have started working on a Jolokia [python client](https://github.com/wbrefvem/python-jolokia) towards that end. My thought was that I would modify the existing jboss module.

2017-05-31 21:55 UTC, smbambling commented
@wbrefvem From a quick look it seems the current jboss module just drops a war/ear to be deployed.  If you do end up working on it and want a hand or someone to help test let me know.

2017-06-03 12:40 UTC, Wolfant commented
@wbrefvem  the existing jboss module just drop an artifact file and deploy it, do not permit really administration of JBoss.

2017-06-03 12:42 UTC, Wolfant commented
@smbambling  thanks, please test it,  It would be very helpful

2017-07-07 18:52 UTC, wbrefvem commented
@Wolfant 
@smbambling 
For whomever is interested, we're putting together a JBoss/Wildfly working group to coordinate work around Ansible & JBoss. We need at least two members to get it started. Email me or respond to the [thread](https://groups.google.com/forum/#!topic/ansible-devel/nttHHu0nMxI) on the ansible-devel list.

2018-10-17 15:08 UTC, LeoUfimtsev commented
would be nice to have this module available. We have a client who would like to use this functionality.

2018-12-03 11:13 UTC, gundalow commented
@LeoUfimtsev Hi, have you tested this module does it work for you?

2019-07-15 11:03 UTC, rthaenert commented
I am using this module currently for performing CLI commands on various JBoss instances (EAP 6 as well as EAP 7) and it is working fine.

One minor thing: The error handling is incorrect if `jboss-cli.sh` returns an error code:
```
cause = re.findall("Caused.+", err)
        if cause is not None:
```
re.findall() would return an empty list if there is no match which leads to incomplete error messages (for example if the JRE for the jboss cli is incorrect).

2019-09-13 09:39 UTC, hvisage commented
Progress on including this?

Easiest to "test" this locally?

2020-08-17 03:08 UTC, closed without merging