Fixes #23948 body not defined nxos_hsrp
ansible/ansible pull request #24093
Opened 2017-04-28 06:54 UTC by trishnaguha

##### SUMMARY

Fixes #23948 
NameError issue.

##### ISSUE TYPE

 - Bugfix Pull Request 

##### COMPONENT NAME

`modules/network/nxos/nxos_hsrp`
##### ANSIBLE VERSION

```
devel
```

2017-04-28 11:42 UTC, gundalow approved these changes

2017-04-28 14:05 UTC, Qalthos requested changes

2017-04-28 14:05 UTC, Qalthos commented on lib/ansible/modules/network/nxos/nxos_hsrp.py
> +            body = load_config(module, commands)
I don't think this should ever return anything. Can you verify that this actually solves the issue?

2017-04-30 12:13 UTC, trishnaguha commented on lib/ansible/modules/network/nxos/nxos_hsrp.py
> +                body = run_commands(module, commands)
@Qalthos fixed now. Tested with pylint.

2017-05-04 15:04 UTC, Qalthos approved these changes

2017-05-05 01:50 UTC, Akasurde approved these changes
LGTM

2017-05-05 03:06 UTC, merged