Refactor nxos_system module
ansible/ansible pull request #24101
Opened 2017-04-28 10:17 UTC by trishnaguha

Signed-off-by: Trishna Guha <trishnaguha17@gmail.com>

##### SUMMARY

Refactor nxos_system module

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

`modules/network/nxos/nxos_system`
##### ANSIBLE VERSION

```
devel
```

2017-04-28 11:00 UTC, gundalow approved these changes

2017-04-28 14:01 UTC, Qalthos requested changes
So this is one of the modules we produced that keeps getting pulled into Peter's NXOS P1 list (alongside _config, _command, and _facts). I don't think there's really any need for this PR, as nothing of any consequence is being changed aside from style changes.

2017-04-28 14:01 UTC, Qalthos commented on lib/ansible/modules/network/nxos/nxos_system.py
> +    result = dict(chaned=False, warnings=warnings)
changed

2017-05-05 14:56 UTC, trishnaguha commented
Closing the PR as discussed with @Qalthos .

2017-05-05 14:56 UTC, closed without merging