new module allowing users to schedule and remove downtime for icinga
ansible/ansible pull request #24131
Opened 2017-04-28 20:28 UTC by Shaita-KrZ

##### SUMMARY
new module allowing users to schedule and remove downtime for icinga (able to work with regex)

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
icinga2_downtime.py

##### ANSIBLE VERSION
```
ansible 2.4.0
```

2017-05-02 23:35 UTC, Shaita-KrZ commented
lib/ansible/modules/monitoring/icinga2_downtime.py:0:0: E203 requests import found, should use ansible.module_utils.urls instead.

Do I have to change that ? I mean I'm using "import requests" because it supports a fully restful API, and I don't really want to change all my code cause of this import.

thanks !

2017-05-02 23:39 UTC, sivel commented
Yes, we have effectively blacklisted the use of the requests module.  To accept this we will need the module converted to using our module_utils package which requires no additional dependencies.

2017-05-03 00:18 UTC, Shaita-KrZ commented
Alright so don't know if someone could help to use ansible.module_utils.urls instead of requests to do : 

r = requests.post(uri, data=json.dumps(payload), verify=False, headers=headers, auth=(icinga2_api_user, icinga2_api_password))

2017-05-03 00:29 UTC, sivel commented
```
r = open_url(uri, data=json.dumps(payload), validate_certs=False, headers=headers, url_username=icinga2_api_user, url_password=icinga2_api_password)
```

You may also need `force_basic_auth=True` in there, I'm not sure how icinga works.

Also you will need to expose a validate_certs option through the module, defaulting to True, and allow the user to disable if needed.  It shouldn't default to false or be hard coded to false.

2017-05-03 00:55 UTC, Shaita-KrZ commented
Alright "All checks have passed"

2017-05-03 01:03 UTC, sivel requested changes

2017-05-03 01:03 UTC, sivel commented on lib/ansible/modules/monitoring/icinga2_downtime.py
> +'''
An option to control `validate_certs` should be included and default to false

2017-05-03 01:03 UTC, sivel commented on lib/ansible/modules/monitoring/icinga2_downtime.py
> +#
All new modules should include actual RETURN data.

2017-05-03 20:17 UTC, Shaita-KrZ commented
Ok @sivel I made the change.

2017-05-04 08:32 UTC, Lowess commented on lib/ansible/modules/monitoring/icinga2_downtime.py
> +    - requests
Hi @Shaita-KrZ you should remove requests from the requirements

2017-05-11 18:58 UTC, Shaita-KrZ commented
@sivel ?

2017-07-24 16:13 UTC, thmshmm commented
Hi @Shaita-KrZ, nice module.

I have two changes you might want to add to your code. At line 432 there exists a problem on Python 2.6 where deltatime has no method total_seconds. You can fix it with these lines:

```
delta_time = datetime.timedelta(seconds=end_time_duration)
total_seconds = (delta_time.days * 24 * 3600) + delta_time.seconds + (delta_time.microseconds / 10**6)
end_time = start_time + total_seconds
```
And at line 283 you should check if the key "name" exists.

```
if message[0].has_key('name'):
    result['name'] = message[0]['name']
```

2018-07-13 12:21 UTC, yasa1987 commented
Is still something happening there ? This module would be useful for me...

2018-07-13 12:41 UTC, Lowess commented
@yasa1987 @sivel Let me get in touch with @Shaita-KrZ who is in my team to make sure those changes you requested get updated so that we can hopefully have this merged soon !

Thanks !

2020-08-17 03:07 UTC, closed without merging