vmware_guest: Fix VM creation when adding a network device without a MAC address
ansible/ansible pull request #24138
Opened 2017-04-29 00:53 UTC by gptech

##### SUMMARY

create_nic() sets the nic's address type as 'assigned', which requires you to supply a MAC address. This causes an error when omitting the MAC address from a playbook. 

This patch will set the address type to 'generated' if a MAC address is not specified.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```
devel
```

##### ADDITIONAL INFORMATION

Example Playbook: 
```
---
- hosts: test-vms
  gather_facts: false
  connection: local
  vars_prompt:
    - name: "esxi_user"
      prompt: "Enter ESXi username"
      private: no
    - name: "esxi_pass"
      prompt: "Enter ESXi password"
      private: yes
  vars:
    datacenter: 'ha-datacenter'
    notes: 'Created by Ansible'
  tasks:
    - name: "Deploy VM"
      vmware_guest:
        name: "{{ inventory_hostname }}"
        validate_certs: False
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_user }}"
        password: "{{ esxi_pass }}"
        state: present
        guest_id: "{{ osid }}"
        disk:
        - size_gb: "{{ disk_size }}"
          type: thin
          datastore: "{{ datastore }}"
        hardware:
          memory_mb: "{{ memory }}"
          num_cpus: "{{ cpucount }}"
        networks:
        - name: VM Network
      delegate_to: localhost
```
Error: 
```
fatal: [test-vm01 -> localhost]: FAILED! => {
    "changed": true,
    "failed": true,
    "invocation": {
        "module_args": {
            "annotation": null,
            "cluster": null,
            "customization": {},
            "customvalues": [],
            "datacenter": "ha-datacenter",
            "disk": [
                {
                    "datastore": "datastore1",
                    "size_gb": 10,
                    "type": "thin"
                }
            ],
            "esxi_hostname": null,
            "folder": "/vm",
            "force": false,
            "guest_id": "centos64Guest",
            "hardware": {
                "memory_mb": 512,
                "num_cpus": 1
            },
            "hostname": "1.1.1.1",
            "is_template": false,
            "name": "test-vm01",
            "name_match": "first",
            "networks": [
                {
                    "name": "VM Network"
                }
            ],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "resource_pool": null,
            "state": "present",
            "template_src": null,
            "username": "root",
            "uuid": null,
            "validate_certs": false,
            "wait_for_ip_address": false
        }
    },
    "msg": "Invalid configuration for device '2'."
}

```

2017-04-29 07:00 UTC, nerzhul requested changes
Just one change, else, nice job !

2017-04-29 07:00 UTC, nerzhul commented on lib/ansible/module_utils/vmware.py
> +            'macaddress_dash': entry.macAddress.replace(':', '-') if entry.macAddress else None,
this ternary operator is not compatible with python 2.4 and we should supply a such compat for Ansible 2.3 (not 2.4).
Can you fix it ?

2017-05-03 23:43 UTC, gptech commented on lib/ansible/module_utils/vmware.py
> +            'macaddress_dash': entry.macAddress.replace(':', '-') if entry.macAddress else None,
Just pushed an updated PR - Let me know if this works better!

2017-05-04 05:55 UTC, nerzhul commented
Sounds good to me. @gundalow @jctanner is the PR okay for you to backport to 2.3-stable ?

2017-05-04 17:25 UTC, dav1x commented
shipit

2017-05-04 20:06 UTC, nerzhul commented
shipit

2017-05-04 20:07 UTC, nerzhul commented
bot_status

2017-05-04 20:12 UTC, nerzhul approved these changes

2017-05-04 20:29 UTC, nerzhul commented
bot_status

2017-05-16 15:47 UTC, merged