Win_package argument parser improvements
ansible/ansible pull request #24141
Opened 2017-04-29 11:08 UTC by trondhindenes

##### SUMMARY
Flag for normalizing `arguments` into a format the installer will understand. 
This fixes the problem where a path had to be specified in the arguments string, for example `INSTALLDIR=C:\\Test` - this would cause the installer to throw since the double backslashes weren't normalized before passed to the installer.

This PR breaks the arguments string up by ` ` (space) and `=`, and then looks at each block to see if its likely a path (second character is `:`). If so, it will replace `\\` with `\` before the argument string is passed down to the installer

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
win_package

##### ANSIBLE VERSION
```
2.4.0
```

2017-04-30 18:25 UTC, trondhindenes commented
@jhawkesworth: would you mind reviewing this one?

2017-05-13 01:03 UTC, dagwieers requested changes

2017-05-13 01:03 UTC, dagwieers commented on lib/ansible/modules/windows/win_package.ps1
> +$normalizeargs = Get-Attr -obj $params -name normalize_arguments -type "bool"
Could we move the *win_package* module over to the new `Get-AnsibleParam` call and options ?
I know it is an alias, but all our modules should be exemplary to contributors IMO.

2017-05-13 01:07 UTC, dagwieers commented
Personally I would prefer this to be the default behavior. Maybe we should consider the current implementation to be a bug and this is the bugfix ?

Or add a new parameter for the new behaviour, and deprecate the older parameter over time. A lot of modules already use parameter **extra_opts** or **options** for additional functionality passed through.

2017-05-18 09:51 UTC, trondhindenes commented on lib/ansible/modules/windows/win_package.ps1
> +$normalizeargs = Get-Attr -obj $params -name normalize_arguments -type "bool"
Definetely.

2017-05-18 09:53 UTC, trondhindenes commented
@dagwieers I see your point. Tho I'm a bit worried as this could be considered a breaking change. How would we go about implementing your suggestion (new param/old param that gets deprecated)

2017-05-26 05:35 UTC, jhawkesworth commented
Apologies for the long time I've taken to get to this one.

I think it is fair to consider this change to be a bug fix - in order to be able to use the paths, the installer needs to 'see' something that looks like a windows path.  Perhaps make argument parsing the default but add a new parameter 'parse_arguments' (default: true) which could be set to false to restore current (unparsed) behavior?

2017-05-29 03:30 UTC, trondhindenes commented
yup. I think the right thing to do is to get it in first (after updating the internal ansible functions like @dagwieers suggests) and then at some point make the switch to use the "new" behavior. Not sure if "parse_arguments" might be a better name than "normalize_arguments"? I kinda like your suggestion better.

2017-05-29 07:39 UTC, dagwieers commented
This is what I would do:
- `arguments:` The current implementation
- `options:` The new normalized implementation

I would add a `module.warn()` call whenever `arguments:` is being used to indicate that `options:` is the new way o working. Then starting from v2.5 we can really start a deprecating process for `arguments:` so that it can be removed starting with Ansible v2.9 (4 releases).

2017-05-29 07:41 UTC, dagwieers requested changes

2017-05-29 07:41 UTC, dagwieers commented on lib/ansible/modules/windows/win_package.py
> +      - false
These 4 lines nowadays should be written as:
```yaml
    type: bool
    default: 'no'
```

2017-05-29 07:41 UTC, dagwieers commented on lib/ansible/modules/windows/win_package.py
> +    version_added: 2.4
The version_added key has string values.
```yaml
    version_added: '2.4'
```

2017-05-29 21:56 UTC, trondhindenes commented
@dagwieers your proposal makes sense to me. @jhawkesworth do you agree? if so I'll change this pr to incorporate the suggested changes.

2017-06-22 14:42 UTC, trondhindenes commented
Not waiting for Jon. I'll just do it :-)

2017-06-22 14:48 UTC, jhawkesworth commented
make sense to me (sorry for late reply)

2017-06-22 14:55 UTC, dagwieers commented
The other thing that comes to mind is that we want to standardize on the `rc` return value, rather than `exit_code`. So eventually we will have to deprecate `exit_code` but for the time being it's probably best to promote `rc` in the documentation.

2017-06-22 17:21 UTC, trondhindenes commented
I've made the changes @dagwieers suggested, so that we (in time) can deprecate the "argument" option. Please review, especially that the documentation is clear enough.

2017-06-27 00:38 UTC, dagwieers commented on lib/ansible/modules/windows/win_package.ps1
> +                        $result["exit_code"] = $exitCode
Using `$result.exit_code` is perfectly fine and arguably more readable than doing `$result['exit_code']`.

*I may have given the wrong impression earlier because I was likely in *mental* python mode which does not allow this for dictionaries.*


@jborean93 What is your opinion as general advice ?

2017-06-27 00:38 UTC, dagwieers commented on lib/ansible/modules/windows/win_package.ps1
> +                        $result["exit_code"] = $exitCode
(Found this pending comment in review...)

2017-06-27 00:57 UTC, jborean93 requested changes
Some questions around some of the changes, I'm wondering whether we want to just display a warning instead of failing if both `arguments` and `options` are set.

2017-06-27 00:57 UTC, jborean93 commented on lib/ansible/modules/windows/win_package.ps1
> +                        $result["exit_code"] = $exitCode
I would keep it the same as it is, I prefer `$result.exit_code` myself but it depends on the context. Looks like this module uses that form so I would keep it the way it was.

2017-06-27 00:57 UTC, jborean93 commented on lib/ansible/modules/windows/win_package.ps1
> +#$normalizeargs = Get-AnsibleParam -obj $params -name "normalize_arguments" -type "bool" -aliases "parse_arguments"
Not needed anymore.

2017-06-27 00:57 UTC, jborean93 commented on lib/ansible/modules/windows/win_package.ps1
> +$result["name"] = $name
Are you able to keep it with what it was before?

2017-06-27 00:57 UTC, jborean93 commented on lib/ansible/modules/windows/win_package.ps1
> +        $result["restart_required"] = $true
Are you able to keep it with what it was before?

2017-06-27 00:57 UTC, jborean93 commented on lib/ansible/modules/windows/win_package.ps1
> +    $result["changed"] = $true
Are you able to keep it with what it was before?

2017-06-27 00:57 UTC, jborean93 commented on lib/ansible/modules/windows/win_package.py
>        - Any arguments the installer needs
Should there be a brief sentence around using `options` from Ansible 2.4 instead?

2017-06-27 00:57 UTC, jborean93 commented on lib/ansible/modules/windows/win_package.py
> +    required: false
This line isn't needed, `required: false` is the default.

2017-06-27 00:57 UTC, jborean93 commented on lib/ansible/modules/windows/win_package.py
> +      - mutually exclusive with "arguments"
Should start with a capital and end with a period.

2017-06-27 00:57 UTC, jborean93 commented on lib/ansible/modules/windows/win_package.py
> +      - See examples below
End with a period.

2017-06-27 00:57 UTC, jborean93 commented on lib/ansible/modules/windows/win_package.ps1
> +    fail-json "specify either arguments or options"
Should be `Fail-Json $result "specify either arguments or options"` / did we just want to overwrite `argument` with `options` and just display a deprecation warning + add to the docs?

2017-06-27 00:57 UTC, jborean93 commented on lib/ansible/modules/windows/win_package.ps1
> +$arguments = Get-AnsibleParam -obj $params -name "arguments"
Can we set a deprecation warning if `arguments` is set to tell the users to use `options` intead? Will need to add it to the docs if this is the case.

2017-06-28 22:47 UTC, trondhindenes commented on lib/ansible/modules/windows/win_package.ps1
> +    fail-json "specify either arguments or options"
you are probably completely right. Thanks!

2017-06-28 22:49 UTC, trondhindenes commented on lib/ansible/modules/windows/win_package.ps1
> +                        $result["exit_code"] = $exitCode
me too. I was just scared of Dag. Reverting.

2017-06-28 22:54 UTC, trondhindenes commented on lib/ansible/modules/windows/win_package.ps1
> +$arguments = Get-AnsibleParam -obj $params -name "arguments"
I was thinking reflect the planned changes in docs for now, and then add the warnings a bit later? Happy with whatever you guys are thinking

2017-06-28 22:57 UTC, trondhindenes commented on lib/ansible/modules/windows/win_package.py
>        - Any arguments the installer needs
yup, done.

2017-09-02 00:09 UTC, trondhindenes commented
@jborean93 should I try and get this back on track or do you have any overlapping PRs that allows us to close this one?

2017-09-02 00:28 UTC, jborean93 commented
I don't have one ready right now but was looking at building a util to convert a list of strings to an escaped argument string to be used by `Process`. I don't think it is is wise to manually parse a string in case people are doing it correctly but in fact would be better for this option to take in a list and we do it from there.

2017-12-04 12:04 UTC, dagwieers commented
Beware that the deadline for getting new features/modules accepted in [Ansible v2.5 is nearing](https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/roadmap/ROADMAP_2_5.rst), it is set to either 2018-01-15 or 2018-01-31. If you are blocked, or you need feedback, please discuss on IRC channel #ansible-windows or add a comment to [the Windows Working Group meeting agenda]

2017-12-12 23:32 UTC, jborean93 commented
Being able to supply arguments as a list was added to win_package with https://github.com/ansible/ansible/commit/9dc9313c65ceafd4f840ccb67cbe50db42db47a8#diff-015c6ab28b2a53b29b2fa4d1d6c225ff. While it doesn't work in all cases (mostly MSI path arguments) it does what it intends. I am going to close this issue as I believe there is not much we can do after this without interfering with the rules set by Microsoft.

2017-12-12 23:32 UTC, closed without merging