New Module: os_tempest_run module
ansible/ansible pull request #24173
Opened 2017-05-01 18:17 UTC by TalShafir

##### SUMMARY
New module that lets the user run Tempest

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
os_tempest_run

##### ANSIBLE VERSION
```
ansible 2.4.0 (module/os_tempest_run c7c81835cb) last updated 2017/05/01 21:11:35 (GMT +300)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/tshafir/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/tshafir/ansible/lib/ansible
  executable location = /home/tshafir/ansible/bin/ansible
  python version = 2.7.5 (default, Aug 18 2016, 15:58:25) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

2017-05-01 18:34 UTC, TalShafir commented
ready_for_review

2017-05-01 18:41 UTC, TalShafir commented
bot_status

2017-05-03 12:45 UTC, gundalow requested changes

2017-05-03 12:45 UTC, gundalow commented on lib/ansible/modules/cloud/openstack/os_tempest_run.py
> +            The workspace as was configured in 'Tempest init <I(workspace)>'
The `I(workspace)` will turn into italics, which I'm not sure if that's what you want in this case

https://docs.ansible.com/ansible/dev_guide/developing_modules_documenting.html#formatting-options

2017-05-03 12:45 UTC, gundalow commented on lib/ansible/modules/cloud/openstack/os_tempest_run.py
> +    - The options I(whitelist_file) and I(blacklist_file) are mutually exclusive, if they are both given only the I(whitelist_file) will be used
If you use the `mutually_exclusive` function you can remove this line

2017-05-03 12:45 UTC, gundalow commented on lib/ansible/modules/cloud/openstack/os_tempest_run.py
> +# Run all tests with default number of workers
As per Ansible best practice, please use `- name: Run all tests with default number of workers` then remove the `- ` from in front of the module name

http://docs.ansible.com/ansible/dev_guide/developing_modules_documenting.html#examples-block

2017-05-03 12:45 UTC, gundalow commented on lib/ansible/modules/cloud/openstack/os_tempest_run.py
> +    ))
There are some options to `AnsibleModule` which you may be able to use to validate options passed in.
Look at existing modules for examples:
```
mutually_exclusive
required_together
required_one_of
require_if
```


Should `whitelist_file` and `blacklist_file` be `mutually_exclusive`
`mutually_exclusive=(('blacklist_file', 'whitelist_file'),),`

2017-05-03 12:45 UTC, gundalow commented on lib/ansible/modules/cloud/openstack/os_tempest_run.py
> +short_description: Runs Tempest
I wonder if it might be worth saying `Run OpenStack Tempest` to make it a little easier for people to find via a search engine.

2017-05-03 12:45 UTC, gundalow commented on lib/ansible/modules/cloud/openstack/os_tempest_run.py
> +    :rtype: A text string (unicode on pyyhon2, str on python3).
pyyhon2 -> python2

2017-05-03 13:36 UTC, TalShafir commented on lib/ansible/modules/cloud/openstack/os_tempest_run.py
> +            The workspace as was configured in 'Tempest init <I(workspace)>'
The documentation says "I() for option names" but I think I'll change that to C(workspace) to make it more visible.

2017-05-03 13:48 UTC, TalShafir commented on lib/ansible/modules/cloud/openstack/os_tempest_run.py
> +# Run all tests with default number of workers
Yeah fixed it, I wrote it after looking at the pip module as an example (https://docs.ansible.com/ansible/pip_module.html#examples), might be nice to add it as a issue for something like 'First Timers Only' or 'YourFirstPR'.

2017-05-03 13:51 UTC, TalShafir commented
Thanks for the review @gundalow 
ready_for_review

2017-05-03 14:04 UTC, TalShafir commented
ready_for_review
bot_status

2017-05-03 14:11 UTC, gundalow commented on lib/ansible/modules/cloud/openstack/os_tempest_run.py
> +# Run all tests with default number of workers
That's a good idea.

Where in the existing documentation/examples did you look?

I'm wondering where I can put/link to the example so people will find it.

2017-05-03 14:11 UTC, TalShafir commented
ready_for_review

2017-05-03 14:13 UTC, gundalow approved these changes

2017-05-03 14:14 UTC, gundalow commented
@TalShafir Thanks for the prompt updates.

I'll let someone that understands OpenStack do the final review, so over to @emonty @shrews @juliakreger @j2sol @rcarrillocruz @thingee

2017-05-03 14:17 UTC, TalShafir commented on lib/ansible/modules/cloud/openstack/os_tempest_run.py
> +# Run all tests with default number of workers
In the documentation website: https://docs.ansible.com/ansible/pip_module.html#examples
And the module implementation starts at: https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/language/pip.py#L148

2017-05-15 12:49 UTC, TalShafir commented
@emonty @Shrews @juliakreger @j2sol @rcarrillocruz @Thingee
A kind reminder, please review the module.
Thanks!

bot_status

2017-05-24 14:33 UTC, Shrews commented
Hi!  Thanks for the new module. However, I don't feel like tempest modules are a good fit here. The current set of modules are geared toward *using* OpenStack services. Modules for *testing* the services seems like they should be kept separate. Most consumers of the core Ansible OpenStack cloud modules are only going to be interested in the former, not the latter.

And on a more personal level, as a core maintainer for these modules, I don't want to have to learn the tempest testing environment in order to support these going forward. I just have no interest in it.

I'd like to get more feedback from possibly @emonty, @j2sol, or @rcarrillocruz and get their thoughts on this.

2017-05-24 22:58 UTC, j2sol commented
I agree with @Shrews

2018-10-13 11:54 UTC, mnaser commented
I agree with @omgjlk and @Shrews.  I would recommend the following role to run Tempest if you'd like

https://github.com/openstack/openstack-ansible-os_tempest

@emonty do you feel the same as well?

2020-01-20 13:53 UTC, sshnaidm commented
Thanks for submitting patch for Openstack Ansible modules!
We moved Openstack Ansible modules to Openstack repositories.
Next patches should be submitted not with Ansible Github but with
Openstack Gerrit: https://review.opendev.org/#/q/project:openstack/ansible-collections-openstack
Please submit your code there from now.
Thanks for your contribution and sorry for inconvienience.

2020-08-19 08:51 UTC, Akasurde commented
Closing as per above.

2020-08-19 08:51 UTC, closed without merging