updates examples and documentation
ansible/ansible pull request #24211
Opened 2017-05-02 14:59 UTC by privateip

includes better examples of valid and invalid usage of the lines
argument

fixes #22828

2017-05-02 17:52 UTC, gundalow requested changes

2017-05-02 17:52 UTC, gundalow commented on lib/ansible/modules/network/sros/sros_config.py
> +      - description "invalid lines example"
valid?

2017-05-02 17:52 UTC, gundalow commented
Looks good, just one minor thing to change then you can merge and cherry-pick into `stable-2.3`.

Needs to go into 2.3 for the docs.

2017-05-12 21:59 UTC, wisotzky commented on lib/ansible/modules/network/sros/sros_config.py
> +      - description "invalid lines example"
Looks okay... "current context lines" might be misread.

Should say: lines are executed in the context specified. It is not allowed/possible to enter any children context.

2017-08-10 17:09 UTC, merged