adds jinja2 filters for working with network devices
ansible/ansible pull request #24216
Opened 2017-05-02 17:37 UTC by privateip

* adds network textfsm filters
* adds network config filter

2017-05-02 18:00 UTC, gundalow requested changes

2017-05-02 18:00 UTC, gundalow commented on docs/docsite/rst/playbooks_filters.rst
> +To generate a list of command diffs for a network configuration:
For code blocks in RST you use `::`, blank line, four spaces

e.g.
```
To generate a list of command diffs for a network configuration::

    {{ myvar | diff_network_config(current_config, indent=1 }}

````

2017-05-02 18:00 UTC, gundalow commented on lib/ansible/plugins/filter/network.py
> +NETWORK_OS = {
I wonder if this should be called `NETWORK_OS_INDENT`, or similar

2017-05-02 18:00 UTC, gundalow commented on lib/ansible/plugins/filter/network.py
> +            if 'HTTP_PROXY' in os.environ:
Might be worth adding some comments to say why you set the proxy to localhost.

2017-05-02 19:17 UTC, jedelman8 commented
Glad to see TextFSM integration going into core.

Few questions for now.

* Are you doing anything with respect a template repository?  I hope not.
* Are you open to having more options in the filter such as returning a list of dictionaries and normalizing the TextFSM object a bit more.
* Are you open to using the `clitable` and add inputs such as template directory, command, and platform?

2017-05-03 01:40 UTC, itdependsnetworks commented on docs/docsite/rst/playbooks_filters.rst
> +  {{ myvar | diff_network_config(current_config, indent=1 }}
need to close out the function: e.g. 
`{{ myvar | diff_network_config(current_config, indent=1 ) }}`

Also might be a good idea to show example using a file lookup.

2017-05-03 02:53 UTC, itdependsnetworks commented on lib/ansible/plugins/filter/network.py
> +    if network_os:
Not sure how this would ever hit base on the previous assert? Perhaps the assert should be here?

2017-05-03 16:24 UTC, itdependsnetworks commented
Just want to confirm there is no namespace issue with filter_plugins, like there is with modules, e.g. the setup.py issue. Otherwise network.py may be too generic.

2017-05-08 00:38 UTC, privateip commented
@jedelman8 

> Are you doing anything with respect a template repository? I hope not.

No, nothing planned

> Are you open to having more options in the filter such as returning a list of dictionaries and normalizing the TextFSM object a bit more.

Can you elaborate more what you are thinking here? 

> Are you open to using the clitable and add inputs such as template directory, command, and platform?

I'm not sure this is needed as we the same thing can be easily accomplished in the playbook  unless I'm not completely understanding what you are asking here.  WRT `clitable` sure

2017-05-08 00:40 UTC, privateip commented
@itdependsnetworks 

> Just want to confirm there is no namespace issue with filter_plugins, like there is with modules, e.g. the setup.py issue. Otherwise network.py may be too generic.

filters same as modules aren't namespaced, not sure what the concern here is

2017-05-09 12:24 UTC, gundalow commented
I wonder if it would be worth adding this to `CHANGELOG.md` as well

2017-07-29 19:47 UTC, closed without merging