Updated pip module to always return changed if venv is created
ansible/ansible pull request #24233
Opened 2017-05-03 06:31 UTC by kulinacs

##### SUMMARY

Fixes #23204

Currently, the pip module may not return changed if a venv is created. This change ensures it does.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

pip module

##### ANSIBLE VERSION

```
ansible 2.4.0 (pip-fixes f7f22b1ee9) last updated 2017/05/03 01:23:43 (GMT -500)
  config file =
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/Development/python/ansible/lib/ansible
  executable location = /home/user/Development/python/ansible/bin/ansible
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

##### ADDITIONAL INFORMATION

The following playbook now returns changed on first run, as it should.

```
- name: Create Python Virtual Environment
  pip:
    name: pip
    virtualenv: /home/user/venv/
    virtualenv_python: python2
```

2017-07-14 13:15 UTC, Lujeni requested changes

2017-07-14 13:15 UTC, Lujeni commented on lib/ansible/modules/packaging/language/pip.py
> +            else:
you should remove this part and setup `the venv_created = False` on the top (~ L443)

2017-07-14 13:15 UTC, Lujeni commented on lib/ansible/modules/packaging/language/pip.py
> +        if venv_created:
you can juste move this part after all processing (~L578) and keep the rest of the code intact 
```python
changed = changed or venv_created
```

2017-07-14 13:18 UTC, Lujeni commented
Hello @kulinacs 

Thanks for your patch !
Few modifications and your patch will merge :):
- I create a pull request to add integration test direcly on your repository.
- you must rebase your branch also.
- few code reviews 

Thanks again

Ciao

2017-07-15 04:16 UTC, kulinacs commented
Updated with recommended changes and added the integration test.

2017-07-15 07:10 UTC, Lujeni commented
@kulinacs thanks, seems good to me,

@robinro you want to review this one also ?

Ciaoo

2017-07-15 07:41 UTC, robinro commented
LGTM
ship_it

Thanks @kulinacs

2017-07-25 07:16 UTC, robinro commented
@Lujeni Can you review the last version?

From my side:
shipit

2017-08-03 01:55 UTC, Lujeni commented
sorry for the delay, lgtm.

shipit

2017-08-31 05:17 UTC, kulinacs commented
Is there anything I need to do to get this merged?

2017-09-12 15:39 UTC, abadger commented
rebuild_merge

2017-09-12 17:01 UTC, merged

2017-09-12 17:02 UTC, abadger commented
Merged to devel and cherrypicked for the 2.4.0rc3 release