vmware_guest: Fix VM creation when creating a VM from a template with network adapters not setting ip/netmask
ansible/ansible pull request #24283
Opened 2017-05-04 08:25 UTC by DMarby

##### SUMMARY
When using vmware_guest to create a VM from a template with networks that does not explicitly set ip/netmask, the networks are not included in the customization policy.

This causes an error as vcenter expects the same amount of nic's (or more) in the customization policy as ones existing on the vm.

This fixes #19860.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /Users/DMarby/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Feb  2 2017, 09:05:20) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### ADDITIONAL INFORMATION
Example playbook:
```
---

- name: Launch server
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: "Deploy VM"
      vmware_guest:
        name: "test"
        validate_certs: False
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        datacenter: "{{ datacenter }}"
        guest_id: "{{ guest_id }}"
        template: "{{ template }}"
        state: present
        disk:
        - size_gb: "10"
          type: thin
          datastore: "{{ datastore }}"
        hardware:
          memory_mb: "512"
          num_cpus: "1"
        networks:
        - name: VM Network
```

Error:
```
fatal: [localhost]: FAILED! => {
    "changed": true,
    "failed": true,
    "invocation": {
        "module_args": {
            "annotation": null,
            "cluster": null,
            "customization": {},
            "customvalues": [],
            "datacenter": "",
            "disk": [
                {
                    "datastore": "",
                    "size_gb": "10",
                    "type": "thin"
                }
            ],
            "esxi_hostname": null,
            "folder": "/vm",
            "force": false,
            "guest_id": "ubuntu64Guest",
            "hardware": {
                "memory_mb": "512",
                "num_cpus": "1"
            },
            "hostname": "",
            "is_template": false,
            "name": "test",
            "name_match": "first",
            "networks": [
                {
                    "name": "VM Network"
                }
            ],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "resource_pool": null,
            "state": "present",
            "template": "ubuntu-template",
            "template_src": "ubuntu-template",
            "username": "",
            "uuid": null,
            "validate_certs": false,
            "wait_for_ip_address": false
        }
    },
    "msg": "The number of network adapter settings in the customization specification: 0 does not match the number of network adapters present in the virtual machine: 1."
}
```

2017-05-04 09:15 UTC, nerzhul commented
You break the usecase when we deploy a VM without a template_src, can you test it without sourcing a template without setting IP settings ? you break this behaviour i think

2017-05-09 04:25 UTC, DMarby commented
Hi, as far as I can tell it works fine without a template, playbook used:

```
---

- name: Launch server
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: "Deploy VM"
      vmware_guest:
        name: "test"
        validate_certs: False
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        datacenter: "{{ datacenter }}"
        guest_id: "{{ guest_id }}"
        state: poweredon
        disk:
        - size_gb: "10"
          type: thin
          datastore: "{{ datastore }}"
        hardware:
          memory_mb: "512"
          num_cpus: "1"
        networks:
        - name: VM Network
```

2017-05-10 21:12 UTC, nerzhul commented
ship_it

2017-05-10 21:12 UTC, nerzhul commented
+label affects_2.3

2017-05-16 15:51 UTC, jctanner commented
@dav1x can you test?

2017-05-16 16:01 UTC, dav1x commented
@jctanner works great! ship_it

```
    "invocation": {
        "module_args": {
            "annotation": null, 
            "cluster": null, 
            "customization": {}, 
            "customvalues": [], 
            "datacenter": "Boston", 
            "disk": [
                {
                    "datastore": "ose3-vmware", 
                    "size_gb": "10", 
                    "type": "thin"
                }
            ], 
            "esxi_hostname": null, 
            "folder": "/vm", 
            "force": false, 
            "guest_id": "rhel7guest", 
            "hardware": {
                "memory_mb": "512", 
                "num_cpus": "1"
            }, 
            "hostname": "x.x.x.x", 
            "is_template": false, 
            "name": "test2", 
            "name_match": "first", 
            "networks": [
                {
                    "name": "VM Network"
                }
            ], 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "resource_pool": null, 
            "state": "poweredon", 
            "template_src": null, 
            "username": "administrator@vsphere.local", 
            "uuid": null, 
            "validate_certs": false, 
            "wait_for_ip_address": false

```

2017-05-17 22:54 UTC, dagwieers commented
I have an objection on this fix. It assumes that if no IP address is specified, the NIC should be using DHCP. But we have use-cases where we clone from a template and we want the NIC to stay as it was configured. (It was pre-configured with static IP addresses).

The reason for this use-case is that in large lab environments, the exact same scenario can be tested in isolated environments, including the same network configuration. The only customization that is required is to add it to the right isolated network (portgroup).

So I would prefer that, unless it is explicitly specified DHCP is desired, the code does not touch the NIC at all. If you desire DHCP, maybe modify the template to do DHCP by default or we should add another option to the configuration.

2017-05-17 23:04 UTC, dagwieers requested changes

2017-05-17 23:04 UTC, dagwieers commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +                guest_map.adapter.ip = vim.vm.customization.DhcpIpGenerator()
Please don't assume DHCP if there's no IP information configured. We should have a flag for enabling DHCP.

2017-05-18 22:31 UTC, DMarby commented
@dagwieers Good catch! Your solution in #24768 looks way better, I'll close this PR in favor of it 👍

2017-05-18 22:31 UTC, closed without merging