adding module to control management of sensu silence entries
ansible/ansible pull request #24332
Opened 2017-05-05 16:19 UTC by smbambling

##### SUMMARY

##### ISSUE TYPE

 - Feature Pull Request
 - New Module Pull Request
 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME

sensu_silence module

##### ANSIBLE VERSION

```
ansible 2.2.1.0 (detached HEAD fe33c937c4) last updated 2017/03/15 09:13:16 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 48a3ce1223) last updated 2017/03/15 09:13:18 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 4e720b48ae) last updated 2017/03/15 09:13:18 (GMT -400)
  config file = /Users/smbambling/Documents/arin/git/bitbucket/operations/ansible/ansible.cfg
  configured module search path = ['library']

```

##### ADDITIONAL INFORMATION

This module grants the ability to post to the sensu api endpoint creating and verifying the existence of a sensu silence to prevent sensu handlers from alerts on a subscription. 

```
```

2017-05-10 11:49 UTC, gundalow requested changes

2017-05-10 11:49 UTC, gundalow commented on lib/ansible/modules/monitoring/sensu_silence.py
> +version_added: "2.2"
`version_added: "2.4"`

2017-05-10 11:49 UTC, gundalow commented on lib/ansible/modules/monitoring/sensu_silence.py
> +    required: false
Please remove `required: false` and `default: []` lines as they are the defaults.

The following page explains this https://docs.ansible.com/ansible/dev_guide/developing_modules_documenting.html

2017-05-10 11:49 UTC, gundalow commented on lib/ansible/modules/monitoring/sensu_silence.py
> +    required: false
Please add `type: bool`.

2017-05-10 11:49 UTC, gundalow commented on lib/ansible/modules/monitoring/sensu_silence.py
> +      - Example: client:server1.example.dev
`Example: C(client:server1.example.dev)`

See https://docs.ansible.com/ansible/dev_guide/developing_modules_documenting.html#formatting-options

2017-05-10 11:49 UTC, gundalow commented on lib/ansible/modules/monitoring/sensu_silence.py
> +      - To create a silence entry for a client append `client:` to client name
`client append C(client:) to client name`

See https://docs.ansible.com/ansible/dev_guide/developing_modules_documenting.html#formatting-options

2017-05-10 11:49 UTC, gundalow commented on lib/ansible/modules/monitoring/sensu_silence.py
> +                    'version': '0.1'}
` 'metadata_version': '1.0'`

2017-05-10 11:49 UTC, gundalow commented on lib/ansible/modules/monitoring/sensu_silence.py
> +
Missing `RETURN` block, please see http://docs.ansible.com/ansible/dev_guide/developing_modules_documenting.html#return-block

2017-05-10 11:49 UTC, gundalow commented on lib/ansible/modules/monitoring/sensu_silence.py
> +            expire_on_resolve=dict(required=False),
`type='bool'`

2017-05-10 11:49 UTC, gundalow commented on lib/ansible/modules/monitoring/sensu_silence.py
> +            state=dict(default='create', choices=['create', 'clear']),
We generally use `absent` and `present` for `state`

2017-05-10 11:49 UTC, gundalow commented on lib/ansible/modules/monitoring/sensu_silence.py
> +short_description: Manage Sensu slience entries
slience -> silence

2017-05-10 11:49 UTC, gundalow commented on lib/ansible/modules/monitoring/sensu_silence.py
> +      resolved.
Indentation doesn't look right here

2017-05-10 11:49 UTC, gundalow commented on lib/ansible/modules/monitoring/sensu_silence.py
> +      was created.
Indentation doesn't look right here

2017-05-10 11:49 UTC, gundalow commented on lib/ansible/modules/monitoring/sensu_silence.py
> +    default: No reason given, tisk tisk
`No reason given` is fine

2017-05-10 11:49 UTC, gundalow commented on lib/ansible/modules/monitoring/sensu_silence.py
> +      - Specifies the URL of the Sensu monitoring host server
Missing full stop at the end of the sentence.

2017-05-10 11:49 UTC, gundalow commented on lib/ansible/modules/monitoring/sensu_silence.py
> +    default: []
`default: Created via Ansible`?

2017-05-10 11:50 UTC, gundalow commented
@andsens I believe you've worked on other Sensu modules before, it would be good to get your input on this

2017-05-10 11:54 UTC, smbambling commented on lib/ansible/modules/monitoring/sensu_silence.py
> +            state=dict(default='create', choices=['create', 'clear']),
Thanks for all these comments, I'll look into these hopefully tomorrow or Friday

2017-05-10 15:47 UTC, andsens commented
@gundalow, unfortunately I do not enough experience with neither the sensu api nor the silence feature :-/

2017-05-12 18:59 UTC, smbambling commented
I'm having some issues with getting ansible-doc to pass (which is what the CI is failing on), any hints into what might be causing this ?

Also for the return block...would the data for that section be the output of running the module like below ?

```
hacking/test-module -m lib/ansible/modules/monitoring/sensu_silence.py -a "url='https://sensu.stage.arin.net' subscription='client:jbossint1.stage.arin.net' creator='smbambling'"
* including generated source, if any, saving to: /Users/smbambling/.ansible_module_generated
* ansiballz module detected; extracted module source to: /Users/smbambling/debug_dir
***********************************
RAW OUTPUT

{"msg": "success", "invocation": {"module_args": {"creator": "smbambling", "url": "https://sensu.stage.arin.net", "expire_on_resolve": null, "reason": null, "state": "present", "expire": null, "check": null, "subscription": "client:jbossint1.stage.arin.net"}}, "changed": true, "result": ""}


***********************************
PARSED OUTPUT
{
    "changed": true,
    "invocation": {
        "module_args": {
            "check": null,
            "creator": "smbambling",
            "expire": null,
            "expire_on_resolve": null,
            "reason": null,
            "state": "present",
            "subscription": "client:jbossint1.stage.arin.net",
            "url": "https://sensu.stage.arin.net"
        }
    },
    "msg": "success",
    "result": ""
}```

2017-05-12 22:05 UTC, gundalow commented
http://docs.ansible.com/ansible/dev_guide/developing_modules_documenting.html may give you some pointers

2017-05-12 22:10 UTC, gundalow requested changes

2017-05-12 22:10 UTC, gundalow commented on lib/ansible/modules/monitoring/sensu_silence.py
> +                    'version': '1.0'}
This should be `metadata_version`

2017-05-12 22:10 UTC, gundalow commented on lib/ansible/modules/monitoring/sensu_silence.py
> +EXAMPLES = '''
Please add example, see http://docs.ansible.com/ansible/dev_guide/developing_modules_documenting.html#examples-block

2017-05-12 22:10 UTC, gundalow commented
http://docs.ansible.com/ansible/dev_guide/developing_modules_documenting.html#testing-documentation

See the tip regarding using an online yaml validators

2017-05-13 11:58 UTC, smbambling commented on lib/ansible/modules/monitoring/sensu_silence.py
> +EXAMPLES = '''
Corrected

2017-05-13 11:59 UTC, smbambling commented
Build is finally green let me know if there are any further correction and if not i'll squash the commits

2017-05-17 17:16 UTC, smbambling commented
@gundalow Any further changes needed for this ?

2017-05-26 09:29 UTC, gundalow approved these changes

2017-05-26 10:37 UTC, gundalow approved these changes

2017-05-26 10:49 UTC, merged

2017-05-26 10:52 UTC, gundalow commented
@smbambling Merged, thanks.

As we don't backport new modules this will be released in Ansible 2.4

I've set you as the maintainer, so you will be notified if their are issues or PRs raised against this module

https://github.com/ansible/ansibullbot/pull/546