Update nocache to be the proper bool type instead of string
ansible/ansible pull request #24358
Opened 2017-05-06 19:39 UTC by mattsch

##### SUMMARY
Fixes the 'nocache' param type for the docker_image module

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
docker_image

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /home/matt/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 12 2017, 17:59:37) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]

```

##### ADDITIONAL INFORMATION
Output from a run with nocache set to true, note that nocache is showing "true".

```
    "invocation": {
        "module_args": {
            "api_version": null, 
            "archive_path": null, 
            "buildargs": null, 
            "cacert_path": null, 
            "cert_path": null, 
            "container_limits": null, 
            "debug": false, 
            "docker_host": null, 
            "dockerfile": null, 
            "filter_logger": false, 
            "force": true, 
            "http_timeout": null, 
            "key_path": null, 
            "load_path": null, 
            "name": "some/image", 
            "nocache": "true", 
            "path": "/var/cache/docker_checkouts/", 
            "pull": true, 
            "push": false, 
            "repository": null, 
            "rm": true, 
            "ssl_version": null, 
            "state": "present", 
            "tag": "25", 
            "timeout": null, 
            "tls": null, 
            "tls_hostname": null, 
            "tls_verify": null, 
            "use_tls": "no"
        }

```
Fixed:
```
    "invocation": {
        "module_args": {
            "api_version": null, 
            "archive_path": null, 
            "buildargs": null, 
            "cacert_path": null, 
            "cert_path": null, 
            "container_limits": null, 
            "debug": false, 
            "docker_host": null, 
            "dockerfile": null, 
            "filter_logger": false, 
            "force": true, 
            "http_timeout": null, 
            "key_path": null, 
            "load_path": null, 
            "name": "some/image", 
            "nocache": true, 
            "path": "/var/cache/docker_checkouts/", 
            "pull": true, 
            "push": false, 
            "repository": null, 
            "rm": true, 
            "ssl_version": null, 
            "state": "present", 
            "tag": "25", 
            "timeout": null, 
            "tls": null, 
            "tls_hostname": null, 
            "tls_verify": null, 
            "use_tls": "no"
```

2017-05-08 02:15 UTC, Akasurde requested changes

2017-05-08 02:15 UTC, Akasurde commented on lib/ansible/modules/cloud/docker/docker_image.py
> +        nocache=dict(type='bool', default=False),
Could you please update the `DOCUMENTATION` section to reflect this change? Except that LGTM.

2017-05-08 11:53 UTC, mattsch commented on lib/ansible/modules/cloud/docker/docker_image.py
> +        nocache=dict(type='bool', default=False),
I'm not sure what needs to be updated in the docs, I believe this PR fixes the behavior to fit what's there?

2017-05-08 12:01 UTC, Akasurde commented on lib/ansible/modules/cloud/docker/docker_image.py
> +        nocache=dict(type='bool', default=False),
Something like [DNF autoremove](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/os/dnf.py#L100-L107)

2017-05-08 13:18 UTC, mattsch commented on lib/ansible/modules/cloud/docker/docker_image.py
> +        nocache=dict(type='bool', default=False),
Ah, that makes sense.  Should I update the other boolean options to match, or just set the choices for this one to true/false?

2017-05-10 12:00 UTC, gundalow requested changes

2017-05-10 12:00 UTC, gundalow commented on lib/ansible/modules/cloud/docker/docker_image.py
> +        nocache=dict(type='bool', default=False),
Hi,
In the `DOCUMENTATION` block please use `type: bool` and NO `choices:`

http://docs.ansible.com/ansible/dev_guide/developing_modules_documenting.html#documentation-block

If you could tidy up all instances of that in the `DOCUMENTATION` anywhere `dict(type='bool'` is used that would be great.

2017-05-10 12:05 UTC, mattsch commented on lib/ansible/modules/cloud/docker/docker_image.py
> +        nocache=dict(type='bool', default=False),
I think I've got it sorted.

2017-05-10 12:16 UTC, Akasurde approved these changes
LGTM

2017-05-10 13:37 UTC, gundalow commented on lib/ansible/modules/cloud/docker/docker_image.py
> +        nocache=dict(type='bool', default=False),
Looks good, thanks

2017-05-10 13:37 UTC, gundalow approved these changes

2017-05-12 19:31 UTC, pchauncey approved these changes
LGTM, tested with ansible 2.4.0

2017-05-12 19:31 UTC, pchauncey commented
shipit

2017-06-18 07:35 UTC, gundalow approved these changes

2017-06-18 07:35 UTC, gundalow commented
bot_status

2017-06-18 10:39 UTC, gundalow commented
Closing & reopen to trigger CI, once that's good ill merge into devel

2017-06-19 10:24 UTC, merged

2017-06-19 10:24 UTC, gundalow commented
Merged into `devel`, so this will be released in Ansible 2.4