added docker swarm inventory
ansible/ansible pull request #24359
Opened 2017-05-07 06:16 UTC by morph027

##### SUMMARY

This adds a dynamic inventory for Docker swarm cluster nodes.

##### ISSUE TYPE

 - Feature Pull Request

##### ANSIBLE VERSION

```
2.3.0.0
```

2017-05-07 13:06 UTC, sivel commented
At minimum, this script is missing the GPL3 license header

2017-05-08 02:41 UTC, Akasurde requested changes

2017-05-08 02:41 UTC, Akasurde commented on contrib/inventory/docker_swarm_nodes.py
> +        import docker
Might want to import at top level

2017-05-08 02:41 UTC, Akasurde commented on contrib/inventory/docker_swarm_nodes.py
> +SwarmNodesInventory()
Nit pick - `if __name__ == "__main__"`

2017-05-08 02:41 UTC, Akasurde commented on contrib/inventory/docker_swarm_nodes.py
> +        print json.dumps(self.data)
print missing parentheses

2017-05-08 05:22 UTC, morph027 commented
Thanks for the feedback. Being "just" a lazy sysadmin ansible user, my python is not the best ;)

2018-07-10 12:18 UTC, closed without merging