Multiple fixes in digital_ocean_tag module
ansible/ansible pull request #24361
Opened 2017-05-07 12:10 UTC by Akasurde

##### SUMMARY
* Pep8 fixes
* Removed redundant check for name
* Check validity of api_token
* Don't report changed when tag is already present

Fixes #24265

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/modules/cloud/digital_ocean/digital_ocean_tag.py

##### ANSIBLE VERSION
```
2.4 devel
```

2017-05-09 12:02 UTC, Akasurde commented
ready_for_review

2017-05-15 09:02 UTC, Akasurde commented
@kontrafiktion Could you please take a look into this ?

2017-06-11 16:42 UTC, Akasurde commented
ready_for_review

2017-06-29 10:10 UTC, Akasurde commented
@resmo Can you please take a look into this PR ? Thanks.

2017-06-29 10:17 UTC, resmo commented on lib/ansible/modules/cloud/digital_ocean/digital_ocean_tag.py
> +                        module.fail_json(msg="error tagging resource '{}': {}".format(resource_id, response.json["message"]))
IMHO this is not python 2.6 compatible (https://docs.python.org/2/library/string.html#format-string-syntax). I usually avoid format at all and use the % syntax.

2017-06-29 10:18 UTC, resmo requested changes
would recommend to replace format syntax with %, but at least make it 2.6 compatible

2017-06-29 10:26 UTC, Akasurde commented
@resmo Done.

2017-06-29 11:39 UTC, resmo approved these changes

2017-06-29 11:43 UTC, resmo commented
perfect. (realized that format {} was even there before your works...) 
code LGTM, but could not test.

shipit

@kontrafiktion @brad2014 were you able to verify?

2017-07-02 20:50 UTC, BondAnthony approved these changes

2017-07-04 05:13 UTC, BondAnthony commented
shipit

2017-07-04 06:04 UTC, merged

2017-07-04 06:42 UTC, Akasurde commented
@resmo @BondAnthony @gundalow Thanks for review and merge.

2017-07-04 12:39 UTC, BondAnthony commented
Thank you for the contribution @Akasurde. We have more DigitalOcean modules that need to be updated and additional DigitalOcean api functionatilty that needs to included in Ansible.

2017-07-04 15:01 UTC, Akasurde commented
@BondAnthony Thanks. Let me know if you need any help from my side.