New Module: github_deploy_key
ansible/ansible pull request #24364
Opened 2017-05-07 20:14 UTC by bincyber

##### SUMMARY

Added a new module for managing deploy keys for GitHub repositories.

Currently, this can be accomplished using the uri module, however it requires some effort to achieve idempotency and I figured it would be better to have a native module that can do the same thing in 1 task.

Additionally, this module supports authenticating to GitHub's API using username and password, username and password and 2-factor authentication code (OTP), OAuth2 token, or personal access token.

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME

github_deploy_key

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /vagrant/ansible.cfg
  configured module search path = [u'modules/']
  python version = 2.7.5 (default, Nov 20 2015, 02:00:19) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

##### ADDITIONAL INFORMATION

A module for managing deploy keys for GitHub repositories was initially requested in ansible/ansible-modules-core#2626. I began a discussion on the [ansible-devel](https://groups.google.com/forum/#!msg/ansible-devel/XY9XUYFRZvQ/yqOhynX1EQAJ;context-place=forum/ansible-devel) Google Group, but nobody was interested in developing this module. So, I finally got around to doing it myself.

2017-05-09 01:52 UTC, Akasurde requested changes

2017-05-09 01:52 UTC, Akasurde commented on lib/ansible/modules/source_control/github_deploy_key.py
> +# -*- coding: utf-8 -*-
Add GNU GPL like [github_issue](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/source_control/github_issue.py#L4-L17)

2017-05-09 01:52 UTC, Akasurde commented on lib/ansible/modules/source_control/github_deploy_key.py
> +        self.module     = module
Remove spaces before operator `=`

2017-05-09 01:52 UTC, Akasurde commented on lib/ansible/modules/source_control/github_deploy_key.py
> +        elif username is not None and password is not None:
This condition can come early

```
if username is not None and password is not None:
    self.auth = (self.username, self.password)
    if self.otp is not None:
        self.headers = {"X-GitHub-OTP": self.otp}
```

2017-05-09 01:52 UTC, Akasurde commented on lib/ansible/modules/source_control/github_deploy_key.py
> +            self.headers = {"Authorization": "token " + self.token}
I would prefer `format` here.

2017-05-09 01:52 UTC, Akasurde commented on lib/ansible/modules/source_control/github_deploy_key.py
> +            if len(resp.json()) > 0:
This can be simplified as `if resp.json()`

2017-05-09 01:52 UTC, Akasurde commented on lib/ansible/modules/source_control/github_deploy_key.py
> +            self.module.fail_json(msg="Failed to connect to github.com due to connection timeout")
Print exception using `get_exception()`, it will easy for debugging purpose.

2017-05-09 01:52 UTC, Akasurde commented on lib/ansible/modules/source_control/github_deploy_key.py
> +            owner       = dict(required=True, type='str', aliases=['account', 'organization']),
Remove spaces before operator `=`

2017-05-09 01:52 UTC, Akasurde commented on lib/ansible/modules/source_control/github_deploy_key.py
> +    owner       = module.params['owner']
Remove spaces before operator.

2017-05-09 01:52 UTC, Akasurde commented on lib/ansible/modules/source_control/github_deploy_key.py
> +            resp = requests.get(self.url, auth=self.auth, headers=self.headers, timeout=self.timeout)
use `fetch_url` instead of `requests.get`

2017-05-10 12:13 UTC, gundalow requested changes

2017-05-10 12:13 UTC, gundalow commented on lib/ansible/modules/source_control/github_deploy_key.py
> +version_added: "2.3"
version_added: "2.4"

2017-05-10 12:13 UTC, gundalow commented on lib/ansible/modules/source_control/github_deploy_key.py
> +            otp         = dict(required=False, type='int', aliases=['2fa_token']),
Please add `no_log=True`

2017-05-10 12:13 UTC, gundalow commented on lib/ansible/modules/source_control/github_deploy_key.py
> +            token       = dict(required=False, type='str')
Please add `no_log=True`

2017-05-10 12:13 UTC, gundalow commented on lib/ansible/modules/source_control/github_deploy_key.py
> +            supports_check_mode = False,
What would be needed to support checkmode?h

2017-05-10 12:15 UTC, gundalow commented
@pcgentry @adrianmoisey I believe you two are maintainers for other GitHub modules, it would be good to get your input on this PR. Thanks in advance.

2017-05-16 03:20 UTC, bincyber commented
Thanks @Akasurde and @gundalow for your feedback on this PR. I've addresses all of your comments in my latest commit.

2017-05-16 03:40 UTC, Akasurde commented on lib/ansible/modules/source_control/github_deploy_key.py
> +  - "Adds or removes deploy keys for GitHub repositories. Supports authentication using username and password, username and password and 2-factor authentication code (OTP), OAuth2 token, or personal
Line too long.

2017-05-16 03:42 UTC, Akasurde commented
@bincyber Shippable is not happy with changes. Can you please fix [issues](https://app.shippable.com/github/ansible/ansible/runs/21883/1/tests) to match coding style?

2017-05-20 14:53 UTC, bincyber commented
@Akasurde I've corrected the PEP8 issues.

2017-05-20 16:29 UTC, Akasurde approved these changes
LGTM

2017-05-26 10:21 UTC, gundalow approved these changes

2017-05-26 10:22 UTC, gundalow commented
Looking good, would like to get it review by some other people

@pcgentry @adrianmoisey I believe you two are maintainers for other GitHub modules, it would be good to get your input on this PR. Thanks in advance.

2017-05-26 10:24 UTC, gundalow commented
@bincyber Poke me in a week if and if there isn't any other feedback I'll merge it

2017-05-26 22:04 UTC, bincyber commented
Thanks @Akasurde @gundalow !

2017-06-18 19:28 UTC, bincyber commented
@gundalow Can we get this PR merged please?

2017-06-18 21:11 UTC, gundalow commented
Triggering ci

2017-06-19 10:13 UTC, merged

2017-06-19 10:15 UTC, gundalow commented
Merged into `devel`, so this will be released in Ansible 2.4

2017-06-20 01:34 UTC, bincyber commented
Thanks @gundalow, appreciate it