vmware_guest_facts: require either UUID or name
ansible/ansible pull request #24420
Opened 2017-05-09 22:10 UTC by nerzhul

##### SUMMARY

vmware_guest_facts required name, whereas you add a uuid

Fix issue #24398

A backport to 2.3 is required
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

vmware_guest_facts
##### ANSIBLE VERSION

```
2.3.0.0
```

##### ADDITIONAL INFORMATION

```

```

2017-05-10 06:34 UTC, Akasurde requested changes
LGTM except requested change.

2017-05-10 06:34 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_guest_facts.py
> +    if module.params['name'] is None and module.params['uuid'] is None:
Could you please use `required_one_of` just like [here](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/systemd.py#L313) ?

2017-05-10 07:41 UTC, nerzhul commented
@Akasurde updated, i also added support_check_mode flag to true as it's a facts gathering only module

2017-05-10 13:00 UTC, jctanner commented
bot_status

2017-05-10 13:25 UTC, Akasurde approved these changes
LGTM

2017-05-10 13:26 UTC, nerzhul commented
+label affects_2.3

2017-05-10 16:01 UTC, pchauncey commented
I'm getting this error on both 2.3 and 2.4 when I supply uuid (with or without name):

```
localhost | FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Shared connection to localhost closed.\r\n", 
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_E2AoBn/ansible_module_vmware_guest_facts.py\", line 218, in <module>\r\n    main()\r\n  File \"/tmp/ansible_E2AoBn/ansible_module_vmware_guest_facts.py\", line 203, in main\r\n    uuid=module.params['uuid'])\r\n  File \"/tmp/ansible_E2AoBn/ansible_module_vmware_guest_facts.py\", line 121, in getvm\r\n    vm = find_vm_by_id(self.content, vm_id=uuid, vm_id_type=\"uuid\")\r\n  File \"/tmp/ansible_E2AoBn/ansible_modlib.zip/ansible/module_utils/vmware.py\", line 158, in find_vm_by_id\r\n  File \"/usr/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py\", line 580, in <lambda>\r\n    self.f(*(self.args + (obj,) + args), **kwargs)\r\n  File \"/usr/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py\", line 385, in _InvokeMethod\r\n    list(map(CheckField, info.params, args))\r\n  File \"/usr/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py\", line 915, in CheckField\r\n    raise TypeError('Required field \"%s\" not provided (not @optional)' % info.name)\r\nTypeError: Required field \"uuid\" not provided (not @optional)\r\n", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
```

2017-05-10 16:16 UTC, nerzhul commented
@pchauncey can you give us the play ?

2017-05-10 16:36 UTC, pchauncey commented
Heres both the command and the playbook, supplying name instead of uuid works just fine:
```
$ ansible localhost -m vmware_guest_facts -a "username=administrator@blah password=password hostname=10.0.0.0 validate_certs=False datacenter=Datacenter uuid=4206950d-90ca-28bd-644d-a22e72079818"
$ ansible 2.3.0.0 (pr24420-2.3 ef1aa46c29)
---
- hosts: localhost
  tasks:
  
    - name: uuid
      vmware_guest_facts:
        username: administrator@blah
        password: password
        hostname: 10.0.0.0
        validate_certs: False
        datacenter: Datacenter
        uuid: 4206950d-90ca-28bd-644d-a22e72079818
```

2017-07-06 20:45 UTC, resmo commented
needs_info

2017-07-27 04:34 UTC, Akasurde commented
@nerzhul I have covered this fix in https://github.com/ansible/ansible/pull/26040 while fixing other issues. Thanks.

2017-07-27 05:38 UTC, nerzhul commented
@Akasurde noted, should it close this pr ?

2017-07-27 05:38 UTC, closed without merging

2017-07-27 05:49 UTC, Akasurde commented
@nerzhul Thanks for your help and time.