Fixed import of urlencode and pathname2url from urllib for python3
ansible/ansible pull request #24424
Opened 2017-05-09 22:56 UTC by michael-k

##### SUMMARY

`urllib.urlencode` fails on python 3, because `urlencode` has been moved to `urllib.parse .urlencode`.

try-except block taken from https://github.com/ansible/ansible/blob/a07d42e16d6f53d2cacb4a270f36a79ff6cebabd/test/runner/lib/http.py#L10-L14

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
multiple

##### ANSIBLE VERSION
```
ansible-playbook 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 3.6.1 (default, Apr 26 2017, 20:20:42) [GCC 4.9.2]
```

2017-05-09 23:01 UTC, sivel requested changes

2017-05-09 23:01 UTC, sivel commented on contrib/inventory/collins.py
> +    from urllib.parse import urlencode  # pylint: disable=locally-disabled, import-error, no-name-in-module
Since we are already using `six`, we should use `six.moves` here instead.

```
from six.moves.urllib.parse import urlencode
```

2017-05-09 23:01 UTC, sivel commented on lib/ansible/modules/cloud/cloudscale/cloudscale_server.py
> +    from urllib.parse import urlencode  # pylint: disable=locally-disabled, import-error, no-name-in-module
Anything within ansible itself (not contrib) should use the following:

```
from ansible.module_utils.six.moves.urllib.parse import urlencode
```

2017-05-10 08:51 UTC, michael-k commented
@sivel Thanks for the review.  I've updated the PR.

2017-05-19 16:35 UTC, calfonso commented
shipit from the network side as it's  minor change. I removed the networking label but it may get added back by the bot.

2017-05-19 16:47 UTC, sivel approved these changes

2017-05-19 16:47 UTC, sivel commented
Closing/Opening to re-trigger CI

2017-05-19 17:22 UTC, sivel commented
CI is clean.  LGTM

2017-05-19 17:22 UTC, merged