Be explicit about pickle protocol and encoding
ansible/ansible pull request #24454
Opened 2017-05-10 16:34 UTC by abadger

On Python3 and Python2 use pickle slightly differently so we need to be
explicit about some things.

If pickles could be shared between python2 and python3, as in
ansible-connection and the pickle cache, we need to specify the protocol
to use when dumping and the encoding to use for byte strings when
loading.

The dumping protocol needs to be no higher than 2 as python-2 only
supports up to protocol 2.  The encoding should usually be 'bytes' so
that python2 str type becomes python3 bytes type.  However, doing this
means that we must make sure that the objects being serialized properly
make their strings into text strings except when they're supposed to be
bytes.  If strings are improperly byte strings, they may cause
tracebacks on the receiving end

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME
ansible-connection, cache/pickle.py and service module

##### ANSIBLE VERSION

```
devel
```

##### ADDITIONAL INFORMATION
Although technically a bugfix, I'm hesitant to backport this to 2.3.  So far we haven't had reports of users encountering this (for ansible-connection, they'd need to be using python2 locally and python3 remotely and have non-ascii data in play_context.  For the cache plugin they'd have to be switching back and forth between running ansible under python2 and python3 ).  If all of our data in play_context isn't properly a text string then we may suddenly start getting errors.  If no one reports bugs that are fixed by this, I'd like this to be devel-only (2.4) so that it gets tested there for a good long while before making it into a release.

2017-05-11 11:07 UTC, ganeshrn requested changes
`src` is removed [here](https://github.com/ansible/ansible/pull/24454/files#diff-4c18935d3e440cd47023c99343feef79L270) , need to replace `src` with `init_data` in L353 (pc_data = 'CONTEXT: %s' % src.getvalue()) and remove L355 (src.close())

2017-05-11 19:55 UTC, abadger commented
Now rebased on top of https://github.com/ansible/ansible/pull/24431 which is the python3 changes which likely are not dangerous to backport to Ansible 2.3.x

2017-05-11 20:41 UTC, abadger commented
Thinking about changing the encoding of the dict to bytes to not change the keys.  Then it will look like this: https://gist.github.com/abadger/3ff5b0e5c2de5814e9a5d5d8a4cc3e52

2017-05-13 01:04 UTC, merged

2017-05-13 01:04 UTC, abadger commented
Merged to the devel branch