Update hpilo_facts.py
ansible/ansible pull request #24503
Opened 2017-05-11 12:14 UTC by bushvin

Add option to change the ssl version used to connect to the remote iLO

##### SUMMARY

Default ssl connections may be unsupported, or disabled due to security requirements, hence the need to be able to change the type used.

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

hpilo_facts
##### ANSIBLE VERSION

2.3.0.0
```

```

##### ADDITIONAL INFORMATION

```

```

2017-05-11 16:11 UTC, Akasurde requested changes

2017-05-11 16:11 UTC, Akasurde commented on lib/ansible/modules/remote_management/hpilo/hpilo_facts.py
> +            ssl_version = dict(default='TLSv1', choices=['SSLv3','SSLv23','TLSv1','TLSv1_1','TLSv1_2']),
In list, space after ,

2017-05-11 16:11 UTC, Akasurde commented on lib/ansible/modules/remote_management/hpilo/hpilo_facts.py
> +    ssl_version = getattr(hpilo.ssl, 'PROTOCOL_' + module.params.get('ssl_version').upper().replace('V','v'))
space after , in replace

2017-05-11 16:51 UTC, Akasurde approved these changes
LGTM

2017-07-13 14:39 UTC, haad commented
shipit

2017-07-13 17:41 UTC, dagwieers commented
shipit

2017-07-13 17:47 UTC, merged