[GCP] Target Proxy Module
ansible/ansible pull request #24527
Opened 2017-05-11 21:23 UTC by supertom

##### SUMMARY

Target Proxy Module.  Currently only the HTTP proxy is supported.

This module builds upon the existing UrlMap and BackendService modules towards the eventual (soon) goal of building a GCP Cross Region load balancer with Ansible.  For reference, the collection of modules required is [here](https://cloud.google.com/compute/docs/load-balancing/http/#overview)

To read more about the GCP HTTP proxy, [see this page](https://cloud.google.com/compute/docs/load-balancing/http/target-proxies)

More details about the HTTP proxy API can be found [here](https://cloud.google.com/compute/docs/reference/latest/targetHttpProxies)

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME
gcp_target_proxy

##### ANSIBLE VERSION

```
ansible 2.4.0 (glb-modules 2bba8bb2d8) last updated 2017/05/11 21:06:10 (GMT +000)
  config file = 
  configured module search path = [u'/home/supertom/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/supertom/virts/ans-http-lb/code/ansible/lib/ansible
  executable location = /home/supertom/virts/ans-http-lb/code/ansible/bin/ansible
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
```

2017-05-12 16:37 UTC, supertom commented
@ryansb PTAL!  This is the target proxy module, which uses the urlmap we just merged.

2017-05-16 15:02 UTC, ryansb requested changes

2017-05-16 15:02 UTC, ryansb commented on lib/ansible/modules/cloud/google/gcp_target_proxy.py
> +    - Create, Update or Destory a Target_Proxy. See
s/Destory/Destroy

2017-05-16 15:02 UTC, ryansb commented on lib/ansible/modules/cloud/google/gcp_target_proxy.py
> +  target_proxy_name:
I think this can just be `name`

2017-05-16 15:02 UTC, ryansb commented on lib/ansible/modules/cloud/google/gcp_target_proxy.py
> +  url_map:
Are there any other IDs/names that a url_map would be known by? If so, we should call this "url_map_name" or something.

2017-05-16 15:02 UTC, ryansb commented on lib/ansible/modules/cloud/google/gcp_target_proxy.py
> +    HAS_PYTHON26 = False
Python 2.6+ is required for Ansible 2.4 and newer, so no need for these checks.

2017-05-16 15:02 UTC, ryansb commented on lib/ansible/modules/cloud/google/gcp_target_proxy.py
> +        req = client.targetHttpProxies().get(project=project_id,
If you're just raising, you can skip the try/except since it's handled in the caller.

2017-05-16 18:03 UTC, supertom commented on lib/ansible/modules/cloud/google/gcp_target_proxy.py
> +  target_proxy_name:
We want to stay (more) consistent with our API.  We're shying away from 'name' as it's vague.

2017-05-16 18:06 UTC, supertom commented on lib/ansible/modules/cloud/google/gcp_target_proxy.py
> +  url_map:
There isn't anything else it could be referred to as.  Still, to be consistent I renamed it.

2017-05-16 18:06 UTC, supertom commented on lib/ansible/modules/cloud/google/gcp_target_proxy.py
> +    HAS_PYTHON26 = False
removed

2017-05-16 18:07 UTC, supertom commented on lib/ansible/modules/cloud/google/gcp_target_proxy.py
> +        req = client.targetHttpProxies().get(project=project_id,
Removed.

2017-05-16 19:25 UTC, ryansb approved these changes

2017-05-16 19:25 UTC, ryansb commented on lib/ansible/modules/cloud/google/gcp_target_proxy.py
> +  target_proxy_name:
Fair enough, I'm good with that.

2017-05-16 19:25 UTC, merged