Remove host field from example doc and minor refactor
ansible/ansible pull request #24534
Opened 2017-05-12 07:18 UTC by trishnaguha

Signed-off-by: Trishna Guha <trishnaguha17@gmail.com>

##### SUMMARY

Fixes #24088 

##### ISSUE TYPE

 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME

```modules/network/nxos/nxos_file_copy```
##### ANSIBLE VERSION

```
devel 2.4
```

2017-05-12 08:27 UTC, ganeshrn requested changes
I think `host` is a required argument. 
If `host` is not provided the connection attempt
will fail here https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/nxos/nxos_file_copy.py#L159-L161

2017-05-12 10:50 UTC, trishnaguha commented
@ganeshrn Updated now.

2017-05-12 18:28 UTC, Qalthos commented on lib/ansible/modules/network/nxos/nxos_file_copy.py
> +def execute_show_command(command, module):
Any reason why you don't drop this method entirely?

2017-05-12 21:38 UTC, Qalthos requested changes
I don't think this is the right way to do this. Probably a better way would be through the action plugin, as that's where the values get generated in the first place.

2017-05-12 21:38 UTC, Qalthos commented on lib/ansible/modules/network/nxos/nxos_file_copy.py
> +        host=dict(required=True),
This will get overridden by `argument_spec.update(nxos_argument_spec)` below

2017-05-13 04:58 UTC, trishnaguha commented on lib/ansible/modules/network/nxos/nxos_file_copy.py
> +def execute_show_command(command, module):
The method has command type `cli_show_ascii` all the time it was called https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/nxos/nxos_file_copy.py#L114-L141 which means `text` as output.
I think it the output is `text` anyway by default. Correct me if I am wrong.
That's the reason to drop the parameter.

2017-05-15 06:30 UTC, trishnaguha commented
@Qalthos I have updated the PR.

2017-05-16 15:22 UTC, Qalthos commented on lib/ansible/modules/network/nxos/nxos_file_copy.py
> +def execute_show_command(command, module):
But regardless of the transport, the only thing it does is `run_commands(module, [command])`. why not replace all `execute_show_command()` with that?

2017-05-18 05:58 UTC, trishnaguha commented
Closing the PR and reopening to trigger the shippable again. Looks like there was connection timed out.

2017-05-18 06:02 UTC, trishnaguha commented
@Qalthos Right. Removing `execute_show_command` makes sense. Please have a look now.
Thanks!

2017-05-19 16:34 UTC, Qalthos approved these changes

2017-05-19 16:37 UTC, merged