Tower user remove organization
ansible/ansible pull request #24544
Opened 2017-05-12 13:34 UTC by lshake

##### SUMMARY
The tower-user module suggests that when adding a user it should be added to an organisation when the organization option is set on the task : "Organization the user should be made a member of."  This fails and user is not made a member of the specified organisation.  Fixes #24510 

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
module: tower_user

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /Users/xxxxxxx/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Mar  3 2017, 11:49:06) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### ADDITIONAL INFORMATION
Fixes issue : https://github.com/ansible/ansible/issues/24510

Removed the organization fields from the tower_user module and doc string.

2017-05-12 14:28 UTC, matburt requested changes
make that small change and it'll be fine

2017-05-12 14:28 UTC, matburt commented on lib/ansible/modules/web_infrastructure/ansible_tower/tower_user.py
> +# (c) 2017, Wayne  Witzel III <wayne@riotousliving.com>
remove added space

2017-05-12 14:42 UTC, matburt approved these changes
lgtm

2017-05-15 19:03 UTC, wwitzel3 approved these changes
lgtm

2017-05-16 02:22 UTC, matburt commented
shipit

2017-05-17 16:18 UTC, wwitzel3 commented
shipit

2017-05-17 18:30 UTC, merged