route53: `value` may not be specified; default to empty list instead of None - fixes #24471
ansible/ansible pull request #24555
Opened 2017-05-12 17:56 UTC by s-hertel

##### SUMMARY
Updates value to default to an empty list. On line [516](https://github.com/ansible/ansible/compare/devel...s-hertel:route53_get?expand=1#diff-ee65e55980e15661bf789266142f496cL516) the value of the option `value` is iterated over. Broken in #23156. Fixes #24471

Also allowed the results from `get` to be empty without failing.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/modules/cloud/amazon/route53.py

##### ANSIBLE VERSION
```
2.4.0
```

##### ADDITIONAL INFORMATION

```

```

2017-05-16 14:12 UTC, ryansb requested changes

2017-05-16 14:12 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/route53.py
> +            ns = record['values'] if 'values' in record else []
Instead, you can make this `record.get('values') or []` instead of the inline conditional.

2017-05-16 14:12 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/route53.py
> +            ns = record['values'] if 'values' in record else []
Instead, you can make this `record.get('values') or []` instead of the inline conditional.

2017-06-01 14:06 UTC, ryansb approved these changes

2017-06-01 14:12 UTC, ryansb commented
My one concern here is that when creating alias-type records, this might pass a value for the `Value` key when that's not allowed on the special Alias type. http://boto3.readthedocs.io/en/latest/reference/services/route53.html#Route53.Client.change_resource_record_sets

Can you test with alias records and check that this doesn't break that case?

2017-06-13 11:52 UTC, willthames commented on lib/ansible/modules/cloud/amazon/route53.py
> +            ns = record.get('values') or []
`record.get('values', [])`

2017-06-13 19:54 UTC, ryansb approved these changes

2017-06-13 19:55 UTC, merged