[GCP] Healthcheck module
ansible/ansible pull request #24564
Opened 2017-05-12 20:50 UTC by supertom

##### SUMMARY
GCP Healthcheck module.  Currently only HTTP and HTTPS HealthChecks are supported.

More information about GCP Healthchecks is available in the [docs](https://cloud.google.com/compute/docs/load-balancing/health-checks)

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME
gcp_healthcheck

##### ANSIBLE VERSION

```
ansible 2.4.0 (ans-healthcheck 7f0de89453) last updated 2017/05/12 20:38:23 (GMT +000)
  config file = 
  configured module search path = [u'/home/supertom/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/supertom/virts/ans-http-lb/code/ansible/lib/ansible
  executable location = /home/supertom/virts/ans-http-lb/code/ansible/bin/ansible
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]

```

##### ADDITIONAL INFORMATION

###### SAMPLE PLAYBOOK
```
- name: Compute Engine Healthcheck
  hosts: localhost
  vars_files:
    - vars/auth
  vars:
    http_healthcheck: my-http-hc
    https_healthcheck: my-https-hc
  tasks:
    - name: param check
      gcp_healthcheck:
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        healthcheck_name: "{{ http_healthcheck }}"
        healthcheck_type: HTTP
        host_header: my-host
        request_path: /hc
        check_interval: 10
        timeout: 30
        unhealthy_threshold: 2
        healthy_threshold: 1
        state: present
      ignore_errors: True
      register: result
    - name: check interval
      assert:
        that:
          'result.msg == "timeout (30) is greater than check_interval (10)"'
    - name: create "{{ http_healthcheck }}"
      gcp_healthcheck:
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        healthcheck_name: "{{ http_healthcheck }}"
        healthcheck_type: HTTP
        host_header: my-host
        request_path: /hc
        check_interval: 5
        timeout: 5
        unhealthy_threshold: 2
        healthy_threshold: 1
        state: present
      register: result
    - name: assert create
      assert:
        that:
          - 'result.state == "present"'
          - 'result.changed'

```

###### OUTPUT

```
changed: [localhost] => {
    "changed": true, 
    "check_interval": 5, 
    "healthcheck": {
        "checkIntervalSec": 5, 
        "creationTimestamp": "2017-05-12T13:43:47.957-07:00", 
        "description": "", 
        "healthyThreshold": 1, 
        "host": "", 
        "id": "5587511137340727404", 
        "kind": "compute#httpHealthCheck", 
        "name": "my-http-hc", 
        "port": 80, 
        "requestPath": "/hc", 
        "selfLink": "https://www.googleapis.com/compute/v1/projects/graphite-demo-supertom/global/httpHealthChecks/my-http-hc", 
        "timeoutSec": 5, 
        "unhealthyThreshold": 2
    }, 
    "healthcheck_name": "my-http-hc", 
    "healthcheck_type": "HTTP", 
    "healthy_threshold": 1, 
    "host_header": "my-host", 
    "port": null, 
    "request_path": "/hc", 
    "state": "present", 
    "timeout": 5, 
    "unhealthy_threshold": 2
}

```

2017-05-12 22:47 UTC, supertom commented
@ryansb PTAL!  Includes an integration test.  This module, required for Load Balancing, is standalone and can be used for VMs, MIGs and Backend Services.

2017-05-15 13:45 UTC, bcoca commented on lib/ansible/modules/cloud/google/gcp_healthcheck.py
> +    required: false
state is not documented?

2017-05-15 13:46 UTC, bcoca commented on lib/ansible/modules/cloud/google/gcp_healthcheck.py
> +    HAS_PYTHON26 = True
2.6 is minimum requirement for Ansible >=2.4

2017-05-15 13:47 UTC, bcoca commented on lib/ansible/modules/cloud/google/gcp_healthcheck.py
> +        pem_file=dict(),
it seems this and other parameters are missing from docs

2017-05-16 13:26 UTC, ryansb requested changes

2017-05-16 13:26 UTC, ryansb commented on lib/ansible/modules/cloud/google/gcp_healthcheck.py
> +short_description: Create, Update or Destory a Healthcheck.
Maybe add what these healthchecks are for, like "Manage healthchecks used in GCP load balancers"? Also, `s/Destory/Destroy/`.

2017-05-16 13:26 UTC, ryansb commented on lib/ansible/modules/cloud/google/gcp_healthcheck.py
> +      HTTPS Healthchecs are supported. Healthchecks are used to monitor
Healthchecks

2017-05-16 13:26 UTC, ryansb commented on lib/ansible/modules/cloud/google/gcp_healthcheck.py
> +         value than check_interval.
Is this how long the health-checking service will wait for a response from the server it is healthchecking?

2017-05-16 13:26 UTC, ryansb commented on lib/ansible/modules/cloud/google/gcp_healthcheck.py
> +        pem_file=dict(),
I thought we had these in a GCP docs fragment, but now I'm not able to find it.

2017-05-16 13:26 UTC, ryansb commented on lib/ansible/modules/cloud/google/gcp_healthcheck.py
> +    if not HAS_PYTHON26:
This isn't needed, since we now only support 2.6+ anyway.

2017-05-16 13:26 UTC, ryansb commented on lib/ansible/modules/cloud/google/gcp_healthcheck.py
> +updated_healthcheck:
This isn't really needed - the task should already be returning changed==[true | false], so users interested in whether the resource was altered can just check that property instead.

2017-05-16 20:37 UTC, ryansb requested changes

2017-05-16 20:37 UTC, ryansb commented on lib/ansible/modules/cloud/google/gcp_healthcheck.py
> +    required: false
Resolved: documented on line 82

2017-05-16 20:37 UTC, ryansb commented on lib/ansible/modules/cloud/google/gcp_healthcheck.py
> +    description: State of the Healthcheck.
Can you add the options here (present/absent)?

2017-05-16 20:37 UTC, ryansb commented on test/integration/roles/test_gcp_healthcheck/tasks/main.yml
> +      - 'result.updated_healthcheck'
This shouldn't work anymore, I don't think.

2017-05-16 20:37 UTC, ryansb commented on test/integration/roles/test_gcp_healthcheck/tasks/main.yml
> +      - 'result.changed'
Can you add a repeat here that asserts changed is false, to show that it detects when there are no changes to be made?

2017-05-16 23:24 UTC, supertom commented on test/integration/roles/test_gcp_healthcheck/tasks/main.yml
> +      - 'result.changed'
Thanks for the request.  This unearthed a bug, which is now fixed.  Added some additional tests.

2017-05-16 23:24 UTC, supertom commented on lib/ansible/modules/cloud/google/gcp_healthcheck.py
> +    description: State of the Healthcheck.
Done

2017-05-17 17:43 UTC, gundalow requested changes

2017-05-17 17:43 UTC, gundalow commented on lib/ansible/modules/cloud/google/gcp_healthcheck.py
> +         value is 5 seconds.
Please use `default:` and remove from `description:`

http://docs.ansible.com/ansible/dev_guide/developing_modules_documenting.html#documentation-block

2017-05-17 17:43 UTC, gundalow commented on lib/ansible/modules/cloud/google/gcp_healthcheck.py
> +         The default value is "/".
Please use `default:`

2017-05-17 17:43 UTC, gundalow commented on lib/ansible/modules/cloud/google/gcp_healthcheck.py
> +    module = AnsibleModule(argument_spec=dict(
Anywhere you've set a default in `argument_spec` please ensure that
1) You do `default: $value` 
2) Remove the default from the `description:`

See http://docs.ansible.com/ansible/dev_guide/developing_modules_documenting.html#documentation-block for mor einfo

2017-05-17 20:46 UTC, supertom commented on lib/ansible/modules/cloud/google/gcp_healthcheck.py
> +         value is 5 seconds.
Done.

2017-05-17 20:46 UTC, supertom commented on lib/ansible/modules/cloud/google/gcp_healthcheck.py
> +         The default value is "/".
Done

2017-05-17 20:46 UTC, supertom commented on lib/ansible/modules/cloud/google/gcp_healthcheck.py
> +    module = AnsibleModule(argument_spec=dict(
Done

2017-05-17 21:07 UTC, supertom commented
@ryansb Latest changes are in.  PTAL!

2017-05-18 16:39 UTC, ryansb approved these changes

2017-05-18 16:41 UTC, gundalow approved these changes

2017-05-18 16:49 UTC, merged