Provide the list of files that were included by include_vars
ansible/ansible pull request #24577
Opened 2017-05-13 12:22 UTC by dmsimard

##### SUMMARY
include_vars will now also return a key 'included_files' which
contains the list of files that were successfully loaded.
This is useful information and, amongst other things, a way for users
to know exactly what files were included when debugging their
playbooks.
This also allows us to improve the integration tests around
include_vars.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
include_vars

##### ANSIBLE VERSION
```
ansible 2.3.0.0
```

2017-05-24 01:59 UTC, bcoca requested changes

2017-05-24 01:59 UTC, bcoca commented on lib/ansible/plugins/action/include_vars.py
> +        result['ansible_included_var_files'] = self.included_files
we shoudl actually mention this in the RETURN docs, noting that it is available since version 2.4

2017-05-24 14:11 UTC, dmsimard commented on lib/ansible/plugins/action/include_vars.py
> +        result['ansible_included_var_files'] = self.included_files
Done.

2017-05-24 14:14 UTC, bcoca approved these changes

2017-05-24 14:14 UTC, bcoca commented
lgtm, cc @mattclay  to go over the testing

2017-05-24 14:46 UTC, dmsimard commented
How did my patch end up failing on pep8 on a file I haven't touched ? I rebased on top of devel.

``lib/ansible/plugins/vars/host_group_vars.py:74:41: E261 at least two spaces before inline comment``

2017-05-24 16:59 UTC, bcoca commented
some idiot did direct commit and your rebased picked up
<= idiot

2017-06-16 15:50 UTC, dmsimard commented
Rebased the patch on top of current devel.

2017-06-16 19:18 UTC, gundalow commented
https://github.com/ansible/ansible/pull/25810 which updates `validate-modules` has been updated so closing & re-opening trigger CI to rerun

2017-06-28 15:24 UTC, dmsimard commented
@gundalow @bcoca @mattclay still hoping to be able to merge this soon, please. Thanks.

2017-06-28 15:29 UTC, mattclay approved these changes

2017-06-28 19:25 UTC, merged