Refactor EOS modules
ansible/ansible pull request #24574
Opened 2017-05-13 08:09 UTC by Akasurde

##### SUMMARY
* PEP8 fixes
* Refactor lambda functions
* Python 3 fixes

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/modules/network/eos/_eos_template.py
lib/ansible/modules/network/eos/eos_banner.py
lib/ansible/modules/network/eos/eos_command.py
lib/ansible/modules/network/eos/eos_config.py
lib/ansible/modules/network/eos/eos_eapi.py
lib/ansible/modules/network/eos/eos_facts.py
lib/ansible/modules/network/eos/eos_system.py
lib/ansible/modules/network/eos/eos_user.py
test/sanity/pep8/legacy-files.txt

##### ANSIBLE VERSION
```
2.4 devel
```

2017-05-15 09:07 UTC, Akasurde commented
@trishnaguha Could you please take a look at this PR?

2017-05-16 05:55 UTC, trishnaguha commented on lib/ansible/modules/network/eos/eos_banner.py
> +    if state == 'absent' and 'text' in list(have.keys()) and have['text']:
Can you explain why you need list conversion here?

2017-05-16 06:18 UTC, trishnaguha commented on lib/ansible/modules/network/eos/eos_eapi.py
> -    needs_update = lambda x: want.get(x) is not None and (want.get(x) != have.get(x))
Any reason to drop lambda here?

2017-05-16 06:19 UTC, trishnaguha commented on lib/ansible/modules/network/eos/eos_user.py
> -        add = lambda x: commands.append('username %s %s' % (want['username'], x))
Same question for dropping lambda here as well.

2017-05-16 06:21 UTC, trishnaguha commented on lib/ansible/modules/network/eos/eos_facts.py
> +VALID_SUBSETS = frozenset(list(FACT_SUBSETS.keys()))
Same question on list conversion here.

2017-05-16 06:26 UTC, Akasurde commented on lib/ansible/modules/network/eos/eos_banner.py
> +    if state == 'absent' and 'text' in list(have.keys()) and have['text']:
In Python 3, dict.keys() will return iterable views instead of lists. So typecasting to list.

2017-05-16 06:26 UTC, Akasurde commented on lib/ansible/modules/network/eos/eos_eapi.py
> -    needs_update = lambda x: want.get(x) is not None and (want.get(x) != have.get(x))
`test/runner/ansible-test sanity --test pep8` didn't like it :)

2017-05-16 06:26 UTC, Akasurde commented on lib/ansible/modules/network/eos/eos_user.py
> -        add = lambda x: commands.append('username %s %s' % (want['username'], x))
`test/runner/ansible-test sanity --test pep8` didn't like it :)

2017-05-16 06:27 UTC, Akasurde commented on lib/ansible/modules/network/eos/eos_facts.py
> +VALID_SUBSETS = frozenset(list(FACT_SUBSETS.keys()))
same as above, Python 3 returns iterable views instead of list.

2017-05-16 06:34 UTC, trishnaguha commented on lib/ansible/modules/network/eos/eos_banner.py
> +    if state == 'absent' and 'text' in list(have.keys()) and have['text']:
Looks like list conversion is unnecessary here as the line above is checking if `text` is a key in `have` dictionary. `key in have.keys()` already accomplishes that. Typecasting to list will only increase the complexity. If you disagree please comment.

2017-05-16 06:39 UTC, trishnaguha commented on lib/ansible/modules/network/eos/eos_eapi.py
> -    needs_update = lambda x: want.get(x) is not None and (want.get(x) != have.get(x))
Ah. lambda is prettier though :). maybe we can run pep8 with ignore lambda error.

2017-05-16 07:06 UTC, Akasurde commented on lib/ansible/modules/network/eos/eos_banner.py
> +    if state == 'absent' and 'text' in list(have.keys()) and have['text']:
I disagree. It will not add complexity in any way. we can agree on `list(have)` instead of `list(have.keys())` if is not that Pythonic.

2017-05-16 07:12 UTC, Akasurde commented on lib/ansible/modules/network/eos/eos_eapi.py
> -    needs_update = lambda x: want.get(x) is not None and (want.get(x) != have.get(x))
I think `def` statements are more readable and simple to understand. Also, using `def` will make code uniform. I do, agree lambda is prettier but I would use it where it is not assigned to any variable. e.g.,

`sorted(cars, key=lambda car: car.color)`

2017-05-16 07:13 UTC, trishnaguha commented on lib/ansible/modules/network/eos/eos_banner.py
> +    if state == 'absent' and 'text' in list(have.keys()) and have['text']:
Not sure what you are trying to accomplish with list conversion here.
The purpose is to check if the key exist in the dictionary or not, that does not require list conversion. We can either do `key in have` or `key in have.keys()`.

2017-05-16 07:16 UTC, trishnaguha requested changes
Please look in the comment https://github.com/ansible/ansible/pull/24574/files/75a971bdc539b8a3618ddd356bda43b3b9560112#diff-1fd7bf472949eba0f39bdbcb527eeefc

2017-05-16 08:27 UTC, Akasurde commented
@trishnaguha I removed `list` thingy altogether. Please have a look.

2017-05-17 07:14 UTC, closed without merging