Pep8 fixes for rabbitmq modules
ansible/ansible pull request #24590
Opened 2017-05-14 10:49 UTC by Akasurde

##### SUMMARY
* PEP8 Fixes
* Code refactoring

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
- lib/ansible/modules/messaging/rabbitmq_binding.py
- lib/ansible/modules/messaging/rabbitmq_exchange.py
- lib/ansible/modules/messaging/rabbitmq_parameter.py
- lib/ansible/modules/messaging/rabbitmq_plugin.py
- lib/ansible/modules/messaging/rabbitmq_policy.py
- lib/ansible/modules/messaging/rabbitmq_queue.py
- lib/ansible/modules/messaging/rabbitmq_user.py
- lib/ansible/modules/messaging/rabbitmq_vhost.py

##### ANSIBLE VERSION
```
2.4 devel
```

2017-05-14 10:50 UTC, Akasurde commented
Simpler version - https://github.com/ansible/ansible/pull/24590/files?w=1

2017-05-15 09:08 UTC, Akasurde commented
ready_for_review

2017-06-07 02:06 UTC, Akasurde commented
ready_for_review

2017-06-07 06:52 UTC, resmo requested changes

2017-06-07 06:52 UTC, resmo commented on lib/ansible/modules/messaging/rabbitmq_binding.py
> -                name = module.params['name'],
It seems name param removed from the return, but it should not.

2017-06-07 06:52 UTC, resmo commented on lib/ansible/modules/messaging/rabbitmq_exchange.py
> -            name = module.params['name'],
Same here, what is the reason to remove the name from the return?

2017-06-07 06:52 UTC, resmo commented on lib/ansible/modules/messaging/rabbitmq_exchange.py
> -                name = module.params['name']
here as well.

2017-06-07 06:52 UTC, resmo commented on lib/ansible/modules/messaging/rabbitmq_exchange.py
> -            name = module.params['name']
and here :)

2017-06-07 09:03 UTC, Akasurde commented on lib/ansible/modules/messaging/rabbitmq_binding.py
> -                name = module.params['name'],
Are you referring [this](https://github.com/ansible/ansible/pull/24590/files/aee05ea2ae7c5e7cdd84e9037c080b39f0f8e66e#diff-d33fa8ead78fe967669bddbe3e490f6fR140)

2017-06-07 09:04 UTC, resmo commented on lib/ansible/modules/messaging/rabbitmq_binding.py
> -                name = module.params['name'],
Yes, never mind.

2017-06-07 09:05 UTC, resmo approved these changes

2017-06-14 02:36 UTC, Akasurde commented
ready_for_review

2017-07-05 14:22 UTC, Akasurde commented
ready_for_review

2017-07-19 07:57 UTC, resmo approved these changes
shipit

2017-08-07 08:40 UTC, Akasurde commented
@resmo Could you please merge this PR ?

2017-08-07 08:44 UTC, resmo commented
shipit

since this is a community module, asking @gundalow to review to get 2 shipits

2017-08-10 08:33 UTC, gundalow approved these changes

2017-08-10 08:34 UTC, gundalow commented
Rebase needed

2017-08-10 09:35 UTC, Akasurde commented
@gundalow Done with rebase.

2017-08-10 09:57 UTC, merged

2017-08-10 10:08 UTC, Akasurde commented
@resmo @gundalow Thanks for review and merge.