Alicloud/module: Added alicloud new module ecs
ansible/ansible pull request #24641
Opened 2017-05-16 02:38 UTC by xiaozhu36

SUMMARY

Added a new module alicloud ecs.py that can manage alicloud ecs instance.

COMPONENT NAME

lib/ansible/module_utils/alicloud_ecs.py
lib/ansible/modules/cloud/alicloud/ecs.py

ANSIBLE VERSION

2.4.0

2017-05-17 09:40 UTC, xiaozhu36 commented
Hello @sivel 

According to the last PR feedback, I have pulled new request about alicloud module, but there is always an error: No RETURN provided, but I noticed that the 'RETURN' is optional, could you please give me a hand to avoid the error? Thanks.

Regards,
Guimin

2017-05-17 11:13 UTC, sivel commented
RETURN is required for all new modules

2017-05-17 18:19 UTC, gundalow requested changes

2017-05-17 18:19 UTC, gundalow commented on shippable.yml
> -    - integrationName: slack
Please revert the change to this file

2017-05-17 18:19 UTC, gundalow commented on lib/ansible/modules/cloud/alicloud/ecs.py
> +      aliases: []
Please remove empty `aliases:` lines

2017-05-17 18:19 UTC, gundalow commented on lib/ansible/modules/cloud/alicloud/ecs.py
> +      choices: ["true", "false"]
Please replace this line with
`type: bool`

2017-05-18 01:33 UTC, xiaozhu36 commented
Ok, thank you for your feedback. By the way, which version from start to require RETURN for all modules?

2017-05-18 03:06 UTC, sivel commented
RETURN has been required for all new modules since 2.1, specifically it has been in CI enforcement since December 22, 2015.

2017-05-18 03:12 UTC, xiaozhu36 commented on shippable.yml
> -    - integrationName: slack
I'm very sorry, it's my fault. In order to make shippable test in my repository conveniently, I changed them, and I forgot to revert them when I pull new request. I will revert them in the next PR.

2017-05-18 03:13 UTC, xiaozhu36 commented
Thank you very much.

2017-06-21 16:17 UTC, closed without merging