slurp: PEP8, imports, cosmetics
ansible/ansible pull request #24677
Opened 2017-05-16 15:37 UTC by dagwieers

##### SUMMARY
- Make PEP8 compliant
- Ensure imports are specific
- Few cosmetic changes (sort lists, casing, punctuation)

##### ISSUE TYPE

 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME

slurp

##### ANSIBLE VERSION
v2.4

2017-05-16 17:55 UTC, mattclay commented
CI failure in integration tests. Here's an example:

```
{
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_qHHLvu/ansible_module_slurp.py\", line 94, in <module>\n    main()\n  File \"/tmp/ansible_qHHLvu/ansible_module_slurp.py\", line 83, in main\n    if not os.path.exists(source):\nNameError: global name 'os' is not defined\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
```

2017-05-16 17:56 UTC, gundalow requested changes
broken imports

2017-05-16 18:12 UTC, dagwieers commented
@gundalow I can read :-) Again caused by wildcard importing.

2017-05-18 07:40 UTC, gundalow approved these changes

2017-05-18 07:40 UTC, merged