skip_broken even if we've got package with broken headers
ansible/ansible pull request #24671
Opened 2017-05-16 13:42 UTC by ii343hbka

##### SUMMARY
skip_broken flag will skip also packages those got with broken headers. I.e. packages specified as URIs. And those URIs occasionally returns HTTP/200 and kind of garbage instead of rpm package.

current ansible will fail with error like:
```
Error in launch ansible playbook: /tmp/tmp.RkLCrRo5iy
Error log: ./logs/localhost/2017-05-14_13:05:02.log
2017-05-14 13:07:53,374 p=3D28801 u=3Drobot |  fatal: [localhost]=
: FAILED! =3D> {"changed": false, "failed": true, "module_stderr": "Tra=
ceback (most recent call last):\n  File \"/tmp/ansible_2KaU9y/ansible_m=
odule_yum.py\", line 1275, in <module>\n    main()\n  File \"/tmp/ansib=
le_2KaU9y/ansible_module_yum.py\", line 1266, in main\n    skip_broken,=
 params['installroot'])\n  File \"/tmp/ansible_2KaU9y/ansible_module_yu=
m.py\", line 1164, in ensure\n    res =3D install(module, pkgs, repoq, =
yum_basecmd, conf_file, en_repos, dis_repos, installroot=3Dinstallroot)=
\n  File \"/tmp/ansible_2KaU9y/ansible_module_yum.py\", line 696, in in=
stall\n    nvra =3D local_nvra(module, package)\n  File \"/tmp/ansible_=
2KaU9y/ansible_module_yum.py\", line 589, in local_nvra\n    header =3D=
 ts.hdrFromFdno(fd)\n  File \"/usr/lib64/python2.7/site-packages/rpm/tr=
ansaction.py\", line 160, in hdrFromFdno\n    raise rpm.error(\"error r=
eading package header\")\n_rpm.error: error reading package header\n", =
"module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
2017-05-14 13:08:13,914 p=3D28801 u=3Drobot |  localhost         =
   : ok=3D117  changed=3D0    unreachable=3D0    failed=3D1  =20
```

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
ansible yum module

##### ANSIBLE VERSION
up to HEAD

2017-05-16 15:46 UTC, ii343hbka commented
ready_for_review

2017-06-07 14:52 UTC, ii343hbka commented
up?

2017-08-15 15:48 UTC, mkrizek requested changes

2017-08-15 15:48 UTC, mkrizek commented on lib/ansible/modules/packaging/os/yum.py
> +            return None
The exception needs to be re-raised if `skip_broken` is not set, otherwise it's lost.

2017-08-15 15:48 UTC, mkrizek commented on lib/ansible/modules/packaging/os/yum.py
>              nvra = local_nvra(module, package)
There are more `local_nvra` calls in this file (please rebase, some were added since this PR), should we check for the return values of those too?

2018-03-19 16:38 UTC, maxamillion commented
It appears from the most recent conversation on this bug that there's still some changes requested to the code and now as an unfortunate side effect of the elapsed time, there's a merge conflict. Please rebase the code, resolve the merge conflicts and update based on feedback. Thank you!

2018-03-19 16:39 UTC, maxamillion commented
It appears from the most recent conversation on this bug that there's still some changes requested to the code and now as an unfortunate side effect of the elapsed time, there's a merge conflict. Please rebase the code, resolve the merge conflicts and update based on feedback. Thank you!

2018-07-18 20:47 UTC, maxamillion commented
@ii343hbka do you still desire to contribute this pull request?

2018-09-11 19:55 UTC, maxamillion commented
Closing PR due to inactivity, please feel free to re-open and ping me if you desire to continue working on it.

2018-09-11 19:55 UTC, closed without merging