Add autoscaling metrics collection support
ansible/ansible pull request #24723
Opened 2017-05-17 13:16 UTC by tomislacker

##### SUMMARY
This addition adds support to [enable/disable ASG metrics collection](http://docs.aws.amazon.com/autoscaling/latest/userguide/as-instance-monitoring.html#as-enable-group-metrics), as well as picking which metrics should be collected.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
`ec2_asg`

##### ANSIBLE VERSION

```
ansible 2.3.0.0 (detached HEAD d56ba0945d) last updated 2017/04/27 12:13:35 (GMT -500)
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Nov 28 2015, 19:16:30) [GCC 4.8.5]
```

2017-05-17 18:01 UTC, gundalow requested changes

2017-05-17 18:01 UTC, gundalow commented on lib/ansible/modules/cloud/amazon/ec2_asg.py
> +      - The granularity to associate with the metrics to collect. The only valid value is 1Minute.
Please remove `The only valid value is 1Minute.`

That is covered by the `choices:` line

2017-05-17 18:01 UTC, tomislacker commented
ready_for_review

2017-05-17 18:43 UTC, tomislacker commented
ready_for_review
@gundalow I've made the requested change.

2017-05-26 10:26 UTC, gundalow approved these changes

2017-05-26 10:27 UTC, gundalow commented
@tomislacker Thanks, looks good

Needs a review from people that know AWS, I believe @willthames is the maintainer for this module.

2017-05-27 06:54 UTC, willthames requested changes
This is all mostly good, just want to get the exception handling more standardised.

2017-05-27 06:54 UTC, willthames commented on lib/ansible/modules/cloud/amazon/ec2_asg.py
> +            if any(metrics_to_disable):
is the `any` required here - `if metrics_to_disable:` should suffice, I'd think

2017-05-27 06:54 UTC, willthames commented on lib/ansible/modules/cloud/amazon/ec2_asg.py
> +            except botocore.exceptions.BotoCoreError as e:
Please use [standard exception handling guidelines](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/GUIDELINES.md#boto3-2)

2017-05-27 06:54 UTC, willthames commented on lib/ansible/modules/cloud/amazon/ec2_asg.py
> +    required: False
`required: False` is the default and so not required here

2017-06-14 18:58 UTC, jippi commented
Any ETA for this PR ? :)

2017-10-17 04:15 UTC, levisbakalinsky commented
+1

2018-01-05 19:42 UTC, ryansb commented
Waiting on edits from @tomislacker

2018-05-14 20:35 UTC, SurenNihalani commented
I think this is already merged in master in 404f9260d9e

2018-05-14 20:51 UTC, s-hertel commented
Thanks @SurenNihalani 
Closing since this was added in 404f926

2018-05-14 20:51 UTC, closed without merging