aos_login change default port and add version check
ansible/ansible pull request #24752
Opened 2017-05-17 20:01 UTC by dgarros

##### SUMMARY

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
modules/network/aos/aos_login.py
##### ANSIBLE VERSION
```
ansible 2.4.0 (fix-eos-user 87959c6578) last updated 2017/05/17 12:56:06 (GMT -700)
  config file = /Users/damien/projects/cloudlabs-topologies/vpod-l2-xs/ansible.cfg
  configured module search path = [u'/Users/damien/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/damien/projects/ansible/lib/ansible
  executable location = /Users/damien/projects/ansible/bin/ansible
  python version = 2.7.10 (default, Feb  6 2017, 23:53:20) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### ADDITIONAL INFORMATION
 - Updating the default port number from 8888 to 443
 - Enforce the port number to be an integer
 - Add a minimum version check for a dependency lib

2017-05-18 07:11 UTC, gundalow requested changes

2017-05-18 07:11 UTC, gundalow commented on lib/ansible/modules/network/aos/aos_login.py
> +            port=dict(default='443', type="int"),
`DOCUMENTATION` block still says default 8888.

We need to be careful when changing `defaults` in code that's already been released.

2017-05-23 17:01 UTC, dgarros commented on lib/ansible/modules/network/aos/aos_login.py
> +            port=dict(default='443', type="int"),
Understood, I agree we need to be careful with default value but the default port changed recently in our product as well.
We think it's better to update it now.

2017-05-23 17:01 UTC, dgarros commented
Good catch for the documentation, I updated it with the new default port number

2017-05-26 10:58 UTC, gundalow commented on lib/ansible/modules/network/aos/aos_login.py
> +            port=dict(default='443', type="int"),
Thanks for the background, I agree that the default should be changed here then

2017-05-26 10:58 UTC, gundalow approved these changes

2017-05-26 10:59 UTC, merged

2017-05-26 11:07 UTC, gundalow commented
Merged into `devel`
PR raised for backport into `stable-2.3` https://github.com/ansible/ansible/pull/25062 which needs your review.