apt: include arch in check for installed packages on multi-arch systems
ansible/ansible pull request #24846
Opened 2017-05-19 21:23 UTC by evgeni

##### SUMMARY
See #24673 and #24703.

On systems that have multi-arch enabled, you need to lookup packages via `package:arch` from `apt.Cache()`. Newer versions of `python-apt` also accept this notation when multi-arch is not enabled, but the version shipped in Debian Jessie and Ubuntu 14.04 does not.

Thanks: Stefan Löwen <stefan.loewen@gmail.com>

Fixes: #24673 
##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
apt

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel 7563d93901) last updated 2017/05/19 23:17:35 (GMT +200)
```

2017-05-21 22:27 UTC, pilou- requested changes

2017-05-21 22:27 UTC, pilou- commented on test/integration/targets/apt/tasks/apt.yml
> +- name: add second architecture
You need to check that `{{ apt_foreign_arch }}` isn't the default architecture.

2017-05-21 22:27 UTC, pilou- commented on test/integration/targets/apt/tasks/apt.yml
> +- name: verify installation of hello:{{ apt_foreign_arch }}
You could check results of previous tasks  `install hello` and `uninstall hello` too.

2017-05-21 22:27 UTC, pilou- commented on test/integration/targets/apt/tasks/apt.yml
> +- name: remove second architecture
The cleaning tasks need to be executed on an [`always`](http://docs.ansible.com/ansible/playbooks_blocks.html#error-handling) block.

2017-05-21 22:27 UTC, pilou- commented on test/integration/targets/apt/tasks/apt.yml
> +# verify that apt is handling multi-arch systems properly
In order to improve readability, test tasks related to multi-arch could be moved in a dedicated YAML file and used here using an `include` task.

2017-05-22 12:05 UTC, gundalow commented
Number of failures in the integration tests

2017-05-22 12:29 UTC, pilou- commented on test/integration/targets/apt/tasks/apt.yml
> +  with_lines: dpkg-query --showformat='${Package}:${Architecture}\n' --show '*:{{ apt_foreign_arch }}'
This task fails due to #23601 when the control machine isn't using Debian (or a derivatives).

Besides, when Debian is used on the control machine, following error appears:

```
TASK [apt : remove second architecture] *********************************************************************************************************************
fatal: [testhost]: FAILED! => {"changed": true, "cmd": ["dpkg", "--remove-architecture", "i386"], "delta": "0:00:00.015897", "end": "2017-05-21 21:55:06.487061", "failed": true, "rc": 2, "start": "2017-05-21 21:55:06.471164", "stderr": "dpkg: error: cannot remove architecture 'i386' currently in use by the database", "stderr_lines": ["dpkg: error: cannot remove architecture 'i386' currently in use by the database"], "stdout": "", "stdout_lines": []}
```

You could use instead something like:
```
 - name: Remove packages with foreign architecture
   apt:
     name: "*:{{ apt_foreign_arch }}"
     state: absent
     purge: yes
```

2017-05-23 05:55 UTC, evgeni commented on test/integration/targets/apt/tasks/apt.yml
> +  with_lines: dpkg-query --showformat='${Package}:${Architecture}\n' --show '*:{{ apt_foreign_arch }}'
ack, did that (not pushed yet), works fine, thanks

2017-05-23 05:56 UTC, evgeni commented on test/integration/targets/apt/tasks/apt.yml
> +- name: remove second architecture
why? the tests are marked as destructive, and having the second arch enabled does not really hurt. on the other side blocks make playbooks less readable.

2017-05-25 08:05 UTC, evgeni commented
ready_for_review

2017-05-26 08:08 UTC, mikedlr reviewed
Hi @evgeni ;  I think this is fine as a small fix and reasonable to go forward.  You could close this as is.

Talking generally (not just this specific patch) the module should have a bit of work done on it;

- the module currently calls dpkg three times for every single .deb it queries - this could be replaced with one call querying 
- the dpg call should return a simple data structure which can be queried (like the cache??) which could then be mocked and tested easily.
- it would be good to have more coverage in the test cases for package upgrades [which are currently missing from the tests (https://codecov.io/gh/ansible/ansible/src/e38c29e71907e273b14b55c60e2899254949a2b2/lib/ansible/modules/packaging/os/apt.py#L660) 

If I was refactoring, I think I would pull out the following functions which would be easy to unit test:

```
def read_debs(list_of_files):
    # blah blah
   available_packages = (# equivalent of 
   for i in *; 
       do dpkg-deb --showformat '${PACKAGE} ${ARCHITECTURE} ${VERSION}\n' --show $i ; 
    done ) 
    return 
```

```
def identify_changes(installed_packages, available_packages):
    # blah blah
    return [list of packages where available is better]
```

And I'd probably pull out a Package object for both installed and available packages which would have

- package.version()
- package.architecture()
- package.name()

which you can do a comparison on but would could run `package.path()` for the installable debs so you could easily build the list of packages to install  

I met with @gundalow yesterday and we were discussing this.  If you want to take it these you could do it together with the rest of the patch.  If not then one of us will bring this up at the core team meeting and hopefully someone else would look into it.

2017-05-26 08:08 UTC, mikedlr commented on lib/ansible/modules/packaging/os/apt.py
> +                installed_pkg = apt.Cache()[pkg_key]
Elsewhere in this module the cache which is returned from `get_cache(module)` is always carefully used.  In this case there is a direct call to apt.Cache().  Do you know why there is this discrepancy and is it safe?  If possible it would be preferable to use the cache object which is already passed into this function as an argument.

2017-05-26 08:08 UTC, mikedlr commented on lib/ansible/modules/packaging/os/apt.py
>              pkg = apt.debfile.DebPackage(deb_file)
This is a huge try/except block which makes debugging what's going on quite difficult and can mask nasty errors.  This and other prolbems with this code are from before the current PR, however it would be really good if this situation could be improved.

2017-05-26 08:19 UTC, evgeni commented
HI @mikedlr, I totally agree that the module could need some good love, refactoring and tests. I tried to be as non-invasive as possible in my patch, as I did not want to take the refactoring route just now and I have no clue why some parts (like the Cache you mention) are written like they are today.

I would favor we would fix that bug (which it is) now, and then decide on a separate plan how to get the module in a nicer shape. Happy to help with the further tasks, but probably not as the main driver (time constraints etc).

2017-05-26 08:23 UTC, mikedlr commented
Okay, then please don't merge the [unit test I made](https://github.com/mikedlr/ansible/commit/25dbdacbe8ad83b62d370c321d7d6afdc22cab7c) right now.  It will be brittle under the refactoring.  Whoever does the refactoring should either merge it or add new separate unit tests.

2017-05-26 08:26 UTC, mikedlr commented
+1

2017-05-26 08:29 UTC, evgeni commented
OK, backed out your commit.

2017-05-30 20:09 UTC, merged