[google] adding a GCE labels module
ansible/ansible pull request #24845
Opened 2017-05-19 21:20 UTC by erjohnso

##### SUMMARY
New Google Cloud Platform module. This module provides support for [GCE Labels](https://cloud.google.com/compute/docs/labeling-resources). As of today, this feature is only available in BETA, but is expected to become generally available in the coming weeks (and make it into the 'v1' API).

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
`gce_labels` module

##### ANSIBLE VERSION
```
ansible 2.4.0 (gce_labels 73a585c541) last updated 2017/05/19 21:13:01 (GMT +000)
  config file = /home/erjohnso/.ansible.cfg
  configured module search path = [u'/home/erjohnso/ansible/lib/ansible', u'/home/erjohnso/ansible/lib/ansible/utils']
  ansible python module location = /home/erjohnso/ansible/lib/ansible
  executable location = /home/erjohnso/ansible/bin/ansible
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]

```

##### ADDITIONAL INFORMATION
```
erjohnso@ansible-dev$ ansible localhost -m gce_labels -a "labels={'foo':'bar','baz':'ugh'} resource_name=ansible-dev resource_location=us-central1-f resource_type=disks project_id=graphite-demos credentials_file=/home/erjohnso/pkey.json" 
 [WARNING]: Host file not found: /home/erjohnso/ansible_hosts

 [WARNING]: provided hosts list is empty, only localhost is available

localhost | SUCCESS => {
    "changed": true, 
    "label_fingerprint": "42WmSpB8rSM=", 
    "labels": {
        "baz": "ugh", 
        "foo": "bar"
    }, 
    "project_id": "graphite-demos", 
    "resource_location": "us-central1-f", 
    "resource_name": "ansible-dev", 
    "resource_type": "disks", 
    "resource_url": null, 
    "state": "present"
}

```

/cc @supertom if you don't mind an initial review

2017-05-31 15:11 UTC, ryansb requested changes

2017-05-31 15:11 UTC, ryansb commented on lib/ansible/modules/cloud/google/gce_labels.py
> +    state: absent
Is there an option to remove a particular tag, or only all tags on a resource?

2017-05-31 15:11 UTC, ryansb commented on lib/ansible/modules/cloud/google/gce_labels.py
> +        resource_url=dict(required=False, type='str'),
In the module args, you can set certain arguments as mutually exclusive so users don't specify them together. For this module I think resource_url should be exclusive with the _name, _location, and _type options.

2017-05-31 20:12 UTC, supertom commented on lib/ansible/modules/cloud/google/gce_labels.py
> +    state: absent
@erjohnso I'm not familiar with the labels API, but if what @ryansb is asking for is true, there are some [helper functions in gce_tag](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/google/gce_tag.py#L133) that can handle the union, intersection, what's different, etc.

2017-06-28 16:54 UTC, erjohnso commented on lib/ansible/modules/cloud/google/gce_labels.py
> +    state: absent
Current implementation only allows for deleting all labels.  It also doesn't support an additive change, each call will overwrite the labels.

Sounds like I need to revamp this to make it more like gce_tags.

2017-06-28 16:54 UTC, erjohnso commented on lib/ansible/modules/cloud/google/gce_labels.py
> +        resource_url=dict(required=False, type='str'),
Great, found some examples. Next update will include this.

2017-07-12 11:38 UTC, erjohnso commented
Looks like only one test failed. Something to do with building the CI on rhel7.3 and likely just a transient error.

2017-07-12 20:18 UTC, erjohnso commented on lib/ansible/modules/cloud/google/gce_labels.py
> +            labels=dict(required=False, type='dict'),
set default to empty dict

2017-07-12 20:18 UTC, erjohnso commented on lib/ansible/modules/cloud/google/gce_labels.py
> +    params['state'] = module.params.get('state')
silly. should just use module.params

2017-07-12 20:21 UTC, erjohnso commented on lib/ansible/modules/cloud/google/gce_labels.py
> +        'label_fingerprint': resource.get('labelFingerprint'),
don't return label_fingerprint

2017-07-12 20:21 UTC, erjohnso commented on lib/ansible/modules/cloud/google/gce_labels.py
> +label_fingerprint:
don't return label_fingerprint

2017-07-12 20:25 UTC, erjohnso commented on lib/ansible/modules/cloud/google/gce_labels.py
> +                raise ValueError("Unmatched label pair '%s':'%s'" % (k, v))
module.fail_json(msg)

2017-07-12 20:25 UTC, ryansb commented on lib/ansible/modules/cloud/google/gce_labels.py
> +                raise ValueError("Unmatched label pair '%s':'%s'" % (k, v))
s/ValueError/module.fail_json(msg=".....")/

2017-07-25 12:42 UTC, ryansb approved these changes

2017-07-25 13:37 UTC, ryansb commented
Merged as https://github.com/ansible/ansible/commit/09e92038445a05e72202acff11e0dfe7a2c68598

2017-07-25 13:37 UTC, closed without merging