vmware_vm_facts: pep8, imports, docs, cosmetics
ansible/ansible pull request #24841
Opened 2017-05-19 17:24 UTC by pchauncey

##### SUMMARY

- PEP8 compliance
- Cosmetics
- AnsibleModule import

##### ISSUE TYPE
 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME
vmware_vm_facts module

##### ANSIBLE VERSION
```
ansible 2.4.0 (vmware_vm_facts-pep8 a6bccb286d) last updated 2017/05/19 12:03:07 (GMT -500)
```

2017-05-19 17:53 UTC, dagwieers commented on lib/ansible/modules/cloud/vmware/vmware_vm_facts.py
> +                           supports_check_mode=False)
This is not strictly necessary, as lines can have 160 columns.

2017-05-19 17:53 UTC, dagwieers requested changes

2017-05-19 17:53 UTC, dagwieers commented on lib/ansible/modules/cloud/vmware/vmware_vm_facts.py
> +                                         vmware_argument_spec)
Imports are now specified right after the documentation strings.

2017-05-19 17:54 UTC, dagwieers requested changes

2017-05-19 17:54 UTC, dagwieers commented on lib/ansible/modules/cloud/vmware/vmware_vm_facts.py
>  version_added: 2.0
version_added needs to be a string.

2017-05-19 18:04 UTC, pchauncey commented on lib/ansible/modules/cloud/vmware/vmware_vm_facts.py
>  version_added: 2.0
Thanks appreciate it.  Update pushed.

2017-05-19 21:21 UTC, pchauncey commented
@dagwieers  Thanks for the suggested changes, done.

ready_for_review

2017-05-23 15:11 UTC, ryansb commented
!needs_revision

2017-07-27 05:01 UTC, Akasurde approved these changes
shipit

2017-07-27 14:50 UTC, pchauncey commented
bot_status

2017-07-27 14:59 UTC, pchauncey commented
ready_for_review

2017-07-27 21:30 UTC, dagwieers requested changes
LGTM only if we have integration tests for this module. Rewriting imports is dangerous without proper integration tests.

2017-07-27 21:30 UTC, dagwieers commented on lib/ansible/modules/cloud/vmware/vmware_vm_facts.py
> +short_description: Return basic facts pertaining to vSphere virtual machines.
Short description should not have trailing dot. (Other descriptions do...)

2017-07-27 21:30 UTC, dagwieers commented on lib/ansible/modules/cloud/vmware/vmware_vm_facts.py
> +author: Joseph Callen (@jcpowermac)
Make this a proper YAML list:
```yaml
author:
- Joseph Callen (@jcpowermac)
```

2017-07-28 15:41 UTC, pchauncey commented
@dagwieers Thanks, I'll pull the import cleanup changes for now and pending some free cycles get some integration test written too.  Other changes implemented as well.

2017-08-09 13:52 UTC, closed without merging