Replace - workaround for non-utf8 text
ansible/ansible pull request #24861
Opened 2017-05-20 18:02 UTC by EvanK

##### SUMMARY
Implemented a suggested workaround for non-utf8 input files that would otherwise raise exception.

Fixes ansible/ansible#24521

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
`replace` module

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel e9e661ebbb) last updated 2017/05/20 17:49:52 (GMT +000)
  config file = 
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/vagrant/ansible/lib/ansible
  executable location = /home/vagrant/ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:32:47) [GCC 4.8.4]
```

2017-05-21 03:10 UTC, Akasurde requested changes

2017-05-21 03:10 UTC, Akasurde commented on lib/ansible/modules/files/replace.py
> +        try:
You can use `to_native`. See [here](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/_text.py#L273)

2017-05-22 05:29 UTC, Akasurde approved these changes
shipit

2017-05-31 20:41 UTC, bcoca commented
cc @abadger

2017-05-31 23:41 UTC, abadger commented
This doesn't look like a good change.  I'll go ahead an pick it apart line by line to show why.

2017-05-31 23:43 UTC, abadger commented on lib/ansible/modules/files/replace.py
> +            contents = bytes(data)
The file is opened in binary mode.  So there's no reason to try converting here as data is already bytes.

2017-05-31 23:46 UTC, abadger commented on lib/ansible/modules/files/replace.py
> +        try:
The try: except will lead to tracebacks on python3 as non-utf8 text will be left as bytes and then the byte strings will attempt to be combined with text strings later in the code on python3.

2017-06-01 00:00 UTC, abadger commented
I'm not sure what the best path forward for this is.... On the one hand It's not really safe to try using replace with non-utf8 files as you can end up substituting utf-8 characters into the file.  So perhaps failing stops us from corrupting files.

On the other hand, we could make this work by making sure to transform all strings into bytes and operate on them that way.  If the string being substituted is compatible with the encoding of the file that should be okay (most encodings in the *nix world are compatible with ascii so we should be okay most of the time.  God forbid you have a utf-16 or other non-ascii compatible file, though....)

As a third choice, we could add an encoding parameter to the module which would let us control the encoding for the file.  Not sure if the other core devs would agree that that should be a common parameter that we'd want, though.  Also don't know the best way to use the encoding parameter inside of the module... Probably use it to decode the file's contents.  (Maybe have to decode the AnsibleModule.params using utf-8 as well).  Then operate on the data.  Finally, use the encoding parameter again to encode to the end encoding just before writing out the data.  If we traceback at that point, it's a clear indication that the user gave replacement strings that aren't valid in the chosen encoding so the traceback protects us from corrupting data.

2017-06-01 16:48 UTC, flokru commented
> I'm not sure what the best path forward for this is.... On the one hand It's not really safe to try using replace with non-utf8 files as you can end up substituting utf-8 characters into the file. So perhaps failing stops us from corrupting files.

This would not work for me (I am the one opening #24521). In my case I have a config file containing German comments in iso-8859-1 (it's a German software not made by me). The lines I want to change via the replace module are no comments and completely 7-bit ascii. Ansible still fails. I have no way of convincing the software author to use utf-8. 

Both other options (ignoring the encoding and working on bytes or adding an encoding option) seem fine to me from a user perspective.

2017-06-01 16:56 UTC, abadger commented
<nod> Talked with bcoca and nitzmahone and I think all three of us agree that adding an encoding parameter to this (and similar modules like lineinfile) would be the best way to proceed.  The use case that an encoding parameter won't be able to address is a file which has mixed encodings (a config file with comments in iso-8859-1 and paths in utf-8, for instance) but hopefully that's uncommon.  The workaround for that (and a workaround for this before a correct fix is created) would be to use something like /usr/bin/iconv to convert to a single expected encoding before running the replace module.

2017-06-05 02:17 UTC, EvanK commented
@abadger I'm not _entirely_ confident in my understanding of encodings and bytes vs text, but I've taken a shot at an `encoding` parameter and a fix discussed as above.

2017-06-05 02:44 UTC, abadger commented
Cool, that looks pretty good.  Let me take a longer look at it on Monday but I think at least the basics are correct.

2017-06-05 23:31 UTC, abadger commented
This looks good in terms of solving this problem.  I'm not 100% certain if this is safe from tracebacks on both python2 and python3 when any of the patterns or replacement strings contain non-ascii values, though.  Need to confirm what will happen with those.

2017-06-05 23:52 UTC, abadger commented
yeah ... looks like the replacement patterns work on python3 but not on python2.  I'll point out what needs to be done inline.

2017-06-06 00:13 UTC, abadger commented
Forgot that github comments can't be added to areas that aren't part of the patch So: 

Around line 218, need the following
```
encoding = params['encoding']
params['after'] = to_text(params['after'], errors='surrogate_or-strict')
params['before'] = to_text(params['before'], errors='surrogate_or_strict')
params['regexp'] = to_text(params['regexp'], errors='surrogate_or_strict')
params['replace'] = to_text(params['replace'], errors='surrogate_or_strict')
```

Around line 232 need to make sure that all the strings for pattern are text type (also noticed a bug if both before and after are specified):
```
    pattern = u''
    if params['after'] and params['before']:
        pattern = u'%s(.*?)%s' % (params['before'], params['after'])
    elif params['after']:
        pattern = u'%s(.*)' % params['after']
    elif params['before']:
        pattern = u'(.*)%s' % params['before']
```

2017-06-06 00:17 UTC, abadger commented
Needs a few more tweaks... Working on testing my changes.

2017-06-06 00:20 UTC, abadger commented
Okay, one more parameter needed for the block around line 218:
```
    encoding = params['encoding']
    params['after'] = to_text(params['after'], errors='surrogate_or_strict', nonstring='passthru')
    params['before'] = to_text(params['before'], errors='surrogate_or_strict', nonstring='passthru')
    params['regexp'] = to_text(params['regexp'], errors='surrogate_or_strict', nonstring='passthru')
    params['replace'] = to_text(params['replace'], errors='surrogate_or_strict', nonstring='passthru')
```

2017-06-06 00:22 UTC, abadger commented
Found another bug but it can be addressed in another PR:
```
        if match:
            section = match.group(0)

        mre = re.compile(params['regexp'], re.MULTILINE)
        if result[1] > 0 and section != result[0]:
            result = (contents.replace(section, result[0]), result[1])

```

section needs to be given some sort of default value or the rest of the block needs to be indented under the ```if match``` condition.

2017-06-06 01:37 UTC, EvanK commented
These changes have been implemented, and thank you for catching the first bug in before/after!

The second bug mentioned should be addressed by #24875 (into which I will also apply the first bug's fix)

2017-06-06 02:35 UTC, merged

2017-06-06 02:35 UTC, abadger commented
Merged to devel.  Thanks for the report and fix!  I realized that the change also needs to have documentation of the encoding parameter but I'll add that separately.