Added timeout to jenkins_script POST request
ansible/ansible pull request #24924
Opened 2017-05-23 10:26 UTC by alexanderteves

##### SUMMARY
The timeout value is passed to fetch_url to allow a custom timeout bigger than the predefined 10 seconds. Bigger scripts send to the Jenkins API will often fail otherwise.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
jenkins_script

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel 4ac135c1b5) last updated 2017/05/23 11:23:15 (GMT +200)
```

2017-05-23 10:28 UTC, Akasurde requested changes

2017-05-23 10:28 UTC, Akasurde commented on lib/ansible/modules/web_infrastructure/jenkins_script.py
> +            timeout=dict(required=False, no_log=True, type="int", default=10),
Timeout don't require `no_log`. Option is for hiding sensitive information like auth_token or password from log_file.

2017-05-23 10:55 UTC, hogarthj commented
Thanks for your contribution, this is definitely sensible to add

-label needs_triage
-label needs_revision

shipit

2017-05-23 11:50 UTC, Akasurde approved these changes
shipit

2017-05-24 09:57 UTC, hogarthj commented
shipit

2017-05-24 10:15 UTC, gundalow commented
bot_status

2017-05-24 10:15 UTC, gundalow approved these changes

2017-05-24 10:16 UTC, merged

2017-05-24 10:18 UTC, gundalow commented
@alexanderteves Thank you for PR, first of many perhaps :)

Thanks also to reviewers.

As we don't backport new functionality this update will be released in Ansible 2.4, which we are currently targeting Aug/Mid-September 2017


[1] https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/roadmap/ROADMAP_2_4.rst