Ansible module to manage global parameters in Foreman
ansible/ansible pull request #24939
Opened 2017-05-23 15:31 UTC by Fobhep

##### SUMMARY
We wrote an Ansible module to manage the Global Parameter Entitiy in Foreman with the nailgun library.

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
foreman_global_parameter.py

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

2017-05-24 11:00 UTC, gundalow requested changes

2017-05-24 11:00 UTC, gundalow commented on lib/ansible/modules/remote_management/foreman/foreman_global_parameter.py
> +            username=dict(required=True, no_log=True),
Username shouldn't need `no_log`

2017-05-24 11:00 UTC, gundalow commented on lib/ansible/modules/remote_management/foreman/foreman_global_parameter.py
> +            name=dict(required=True, no_log=False),
Please remove `no_log=False` as it's the default

2017-05-24 11:00 UTC, gundalow commented on lib/ansible/modules/remote_management/foreman/foreman_global_parameter.py
> +            value=dict(required=False, no_log=False),
Please remove `no_log=False` as it's the default

2017-05-24 11:00 UTC, gundalow commented on lib/ansible/modules/remote_management/foreman/foreman_global_parameter.py
> +            state=dict(required=True, no_log=False),
Please remove `no_log=False` as it's the default

2017-05-24 11:00 UTC, gundalow commented on lib/ansible/modules/remote_management/foreman/foreman_global_parameter.py
> +        required: false
`default: true`

2017-05-24 11:00 UTC, gundalow commented on lib/ansible/modules/remote_management/foreman/foreman_global_parameter.py
> +            verify_ssl=dict(required=False, type='bool', default=False),
Please change the default to true (assuming this is what other Forman modules do)

2017-05-24 11:00 UTC, gundalow commented on lib/ansible/modules/remote_management/foreman/foreman_global_parameter.py
> +            msg="""Missing required nailgun module (check docs or install
Missing closing `)`

2017-05-24 11:00 UTC, gundalow commented on lib/ansible/modules/remote_management/foreman/foreman_global_parameter.py
> +                module.fail_json(msg='value is required when state=present')
There are built in helpers for this,

See the following draft example https://github.com/gundalow/ansible/blob/docs-argspec/docs/docsite/rst/dev_guide/developing_modules_general.rst#main-and-ansiblemodule-argument-spec

2017-05-24 11:00 UTC, gundalow commented on lib/ansible/modules/remote_management/foreman/foreman_global_parameter.py
> +            module.fail_json(msg='state can only be present or absent')
Please remove and add the suggested line in the arg spec

2017-05-24 11:00 UTC, gundalow commented on lib/ansible/modules/remote_management/foreman/foreman_global_parameter.py
> +            state=dict(required=True, no_log=False),
Please add `, choices=['present', 'absent']`

2017-05-24 11:00 UTC, gundalow commented on lib/ansible/modules/remote_management/foreman/foreman_global_parameter.py
> +        required: false
Please add `choices:` here

http://docs.ansible.com/ansible/dev_guide/developing_modules_documenting.html

2017-05-24 11:03 UTC, gundalow commented
@Fobhep Thanks for the PR. I believe this is your first, ace :)
The following page has details of regarding how to document your module, which may be of use https://docs.ansible.com/ansible/dev_guide/developing_modules_documenting.html

@ehelms I believe you created the other Foreman modules, it would be good to get your input on this new module.

2017-05-24 11:08 UTC, Fobhep commented
@gundalow thx for the review. 
Hehe, yes it is indeed my first, thx :)

I wrote this basically to try and get a feeling for nailgun and foreman entities.
There could come more at a later point, regarding other foreman entitites. ;)

2017-05-24 12:59 UTC, gundalow approved these changes

2017-05-26 14:59 UTC, ehelms commented
Sorry - just now seeing this and taking a look.

2017-05-26 17:47 UTC, ehelms commented on lib/ansible/modules/remote_management/foreman/foreman_global_parameter.py
> +def create_CommonParameter(name, value):
This mixture of snakecase and camcelcase for method names seems a bit strange and divergent from typical python best practices. A bit of syntactic nitpick but it is nice to follow standard practice.

2017-05-26 17:48 UTC, ehelms commented
Minor syntactic nitpick but the strategy looks good and is in line with how I want to re-factor the katello module.

2017-05-29 08:07 UTC, Fobhep commented
@ehelms thank your very much for your review and your suggestion. I will change the synaptics of my own code into a more standard practice conform way.

2017-05-29 11:19 UTC, Fobhep commented
ok, seems to be fine now :)

2018-09-19 21:16 UTC, maxamillion commented
@Fobhep apologies for the lag time on this. If you're still interested in contributing this, the code looks good. We'd just need to update the `version_added` field and add some tests. Thank you!

2019-07-17 10:34 UTC, ekohl commented
wontfix because I think https://github.com/theforeman/foreman-ansible-modules is a better place for this (and already contains an updated version of this PR).

2019-07-17 10:43 UTC, closed without merging