Added the docker_volume module
ansible/ansible pull request #24957
Opened 2017-05-23 22:54 UTC by agronholm

##### SUMMARY

This module provides the ability to create and delete Docker volumes.

The "force" option deletes and recreates the volume with state=present to ensure that a volume exists
with the exact given options.

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

docker_volume
##### ANSIBLE VERSION

```
ansible 2.4.0 (docker_volume 80ec8c49ba) last updated 2017/05/23 15:48:45 (GMT -700)
  config file = /home/alex/.ansible.cfg
  configured module search path = [u'/home/alex/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/alex/checkout/ansible/lib/ansible
  executable location = /home/alex/checkout/ansible/venv/bin/ansible
  python version = 2.7.13 (default, May 10 2017, 20:04:28) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```

##### ADDITIONAL INFORMATION

I've done manual testing using both docker-py 1.10.6 and docker 2.3.0 and the code worked fine with either one.

```

```

2017-05-24 03:38 UTC, Akasurde requested changes

2017-05-24 03:38 UTC, Akasurde commented on lib/ansible/modules/cloud/docker/docker_volume.py
> +#!/usr/bin/python
shabang should be first line.

2017-05-24 03:38 UTC, Akasurde commented on lib/ansible/modules/cloud/docker/docker_volume.py
> +      - Dictionary of volume settings. Consult docker docs for valid options and values.
Link to docs would be helpful.

2017-05-24 03:38 UTC, Akasurde commented on lib/ansible/modules/cloud/docker/docker_volume.py
> +from ansible.module_utils.docker_common import *
Try importing specific.

2017-05-24 03:38 UTC, Akasurde commented on lib/ansible/modules/cloud/docker/docker_volume.py
> +        volume_name        = dict(type='str', required=True, aliases=['name']),
No space before and after operator in `dict()`

2017-05-24 03:38 UTC, Akasurde commented on lib/ansible/modules/cloud/docker/docker_volume.py
> +            self.results['actions'].append("Removed volume %s" % (self.parameters.volume_name,))
Redundant parens.

2017-05-24 03:38 UTC, Akasurde commented on lib/ansible/modules/cloud/docker/docker_volume.py
> +                for key, value in self.parameters.driver_options.items():
use `from ansible.module_utils.six import iteritems`

2017-05-24 03:38 UTC, Akasurde commented on lib/ansible/modules/cloud/docker/docker_volume.py
> +        Evaluates an existing volume and returns a tuple containing a boolean
Could you please correct docstring? There is no boolean value in return value.

2017-05-24 04:14 UTC, agronholm commented
Ok, I'm pretty confused now. The tests are now complaining about the `from ansible.module_utils.basic import *` line at the end which is included in every single Ansible module. Have the code style rules changed recently? Why do the other modules even import that stuff?

2017-05-26 03:39 UTC, agronholm commented
@Akasurde it should be okay now, yes?

2017-05-30 01:10 UTC, willthames commented
This seems to meet all the criteria for being a high quality module. Only remaining question is whether it would be considered widely useful - and I can't see why that wouldn't be the case.

2017-05-31 14:56 UTC, dagwieers requested changes
Looking good, only some minor issues to documentation.
I did not test the module itself.

2017-05-31 14:56 UTC, dagwieers commented on lib/ansible/modules/cloud/docker/docker_volume.py
> +    default: null
Unneeded, the default is null, so you don't have to explicitly mention that.

2017-05-31 14:56 UTC, dagwieers commented on lib/ansible/modules/cloud/docker/docker_volume.py
> +    - "Alex Grönholm (@agronholm)"
No need for quotes here.

2017-05-31 14:56 UTC, dagwieers commented on lib/ansible/modules/cloud/docker/docker_volume.py
> +      - I(absent) deletes the volume.
For options, use C(absent) instead of I(absent)

2017-05-31 14:56 UTC, dagwieers commented on lib/ansible/modules/cloud/docker/docker_volume.py
> +    default: false
Add + update default to: 
```yaml
    type: bool
    default: 'no'
```

2017-05-31 14:56 UTC, dagwieers commented on lib/ansible/modules/cloud/docker/docker_volume.py
> +
I don't see the debug-option mentioned in the documentation.
Is that on purpose ?

2017-05-31 15:03 UTC, dagwieers requested changes

2017-05-31 15:03 UTC, dagwieers commented on lib/ansible/modules/cloud/docker/docker_volume.py
> +      - >
There is no need to do `- >` here, just like a bit higher up, list items can be multiline.

2017-05-31 15:06 UTC, agronholm commented on lib/ansible/modules/cloud/docker/docker_volume.py
> +      - >
The `->` **is** necessary because the line ends up with a colon. Without the `->`, YAML thinks it's a dictionary key.

2017-05-31 15:10 UTC, dagwieers commented on lib/ansible/modules/cloud/docker/docker_volume.py
> +      - >
Right, we tend to quote the complete string in such cases.
But ok, not a big deal.

2017-05-31 15:11 UTC, dagwieers approved these changes

2017-05-31 15:17 UTC, agronholm commented on lib/ansible/modules/cloud/docker/docker_volume.py
> +
I'm not entirely sure why the original module had this option. I left it there since I wasn't confident about removing it.

2017-06-01 09:36 UTC, gundalow commented on lib/ansible/modules/cloud/docker/docker_volume.py
> +      - >
Or just don't use a `:`

2017-06-04 08:34 UTC, mattclay commented
Closing and re-opening to trigger CI.

2017-06-04 13:12 UTC, agronholm commented
Isn't CI normally triggered after every push? Works that way with Travis at least.

2017-06-05 04:17 UTC, mattclay commented
@agronholm Normally, yes. However, there are several conditions under which CI won't be triggered. The two most common are GitHub failing to send a webhook on push and the webhook failing to trigger CI (for various reasons).

2017-06-23 12:21 UTC, chouseknecht commented on lib/ansible/modules/cloud/docker/docker_volume.py
> +
You can remove `debug` from argument_spec, as it actually gets added by `docker_common`. But doesn't hurt to mention it here. 

The point of the parameter is to enable output to a file, `debug.log`, during development. Check `docker_common` for the `log` method. You can uncomment the `print` operations in your local environment.

2017-06-23 16:02 UTC, chouseknecht requested changes
Seem my comments. Missing error handling around calls to the Docker API.

You'll want to import APIError from docker_common.

2017-06-23 16:02 UTC, chouseknecht commented on lib/ansible/modules/cloud/docker/docker_volume.py
> +        volumes = self.client.volumes()
Wrap calls to self.client.X in try/except block. On APIError call self.client.fail() with an error message and exception details.

2017-06-23 16:02 UTC, chouseknecht commented on lib/ansible/modules/cloud/docker/docker_volume.py
> +
Missing doc string for 'labels'

2017-06-23 16:02 UTC, chouseknecht commented on lib/ansible/modules/cloud/docker/docker_volume.py
> +                                                 labels=self.parameters.labels)
Same as above.

Wrap calls to self.client.X in try/except block. On APIError call self.client.fail() with an error message and exception details.

2017-06-23 16:02 UTC, chouseknecht commented on lib/ansible/modules/cloud/docker/docker_volume.py
> +                self.client.remove_volume(self.parameters.volume_name)
And here... 

Wrap calls to self.client.X in try/except block. On APIError call self.client.fail() with an error message and exception details.

2017-06-23 16:04 UTC, chouseknecht commented
@agronholm 

Thanks for working on this!  It looks great. Just a couple minor changes needed to properly handle errors. 

I tested the module, and it creates and removes volumes as expected. Seems to be idempotent. Good work!

2017-07-07 09:43 UTC, agronholm commented
@chouseknecht I just pushed some changes which should bring the module up to spec.

2017-07-19 17:43 UTC, merged

2017-07-19 17:45 UTC, agronholm commented
Thanks!