Add some clarifying docs regarding module search paths
ansible/ansible pull request #24980
Opened 2017-05-24 13:32 UTC by kamranayub

Fixes #7633

##### SUMMARY

Add some clarifying documentation regarding how Ansible discovers modules. As a new user, I was unable to find the `library` relative search path--it looks like the only page that mentions it in passing is the Ansible Configuration File docs.

Let me know if any of the info is wrong or has to be reworded.

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
dev_guide

2017-05-31 08:32 UTC, D3N14L approved these changes

2017-05-31 17:39 UTC, bcoca commented on docs/docsite/rst/dev_guide/developing_modules.rst
> +the executing playbook, the path specified by :envvar:`ANSIBLE_LIBRARY`, the ``--module-path``
missing ` or inside a role`

2017-05-31 17:39 UTC, bcoca commented on docs/docsite/rst/dev_guide/developing_modules_best_practices.rst
> +those search paths.
a section of 'inside a role' would also be needed.

2017-05-31 19:54 UTC, kamranayub commented on docs/docsite/rst/dev_guide/developing_modules_best_practices.rst
> +those search paths.
Thanks, I updated both parts, let me know if I got it right or if I misunderstood.

2017-05-31 22:46 UTC, bcoca commented
looks good .. .but now i'm thinking this should be in 'user' part of docs, not just developers @gundalow , @dharmabumstead you guys have any feedback?

2017-05-31 22:47 UTC, bcoca commented on docs/docsite/rst/dev_guide/developing_modules.rst
> +the executing playbook or inside a ``role`` directory, the path specified by :envvar:`ANSIBLE_LIBRARY`, the ``--module-path``
inside a role, `role directory` can be misleading

2017-06-01 11:48 UTC, gundalow commented
Working is good, thanks for that.
I agree with @bcoca that this needs moving out of `dev_guide` (and dev_guide should link to the new section of docs).

Maybe in `intro_configuration.rst`?

2017-06-12 13:30 UTC, kamranayub commented
@gundalow I wonder if there's another location in addition to/other than the Configuration page... like I said I only noticed the blurb on that page while doing this PR, it never came up in my "natural" exploration of the documentation.

A few places that we could expose in the TOC:

- About Modules
 - Module Locations
- Playbooks: Special Topics
 - Loading Modules

These are the two top level topics that I tried looking in to no avail, so they may be good bets on where to put this information. Thoughts?

2017-06-19 19:13 UTC, dharmabumstead requested changes
Minor edits.

2017-06-19 19:13 UTC, dharmabumstead commented on docs/docsite/rst/dev_guide/developing_modules_best_practices.rst
> +you about these kind of things.
Suggest revising this sentence to something like "Use the hacking/test-module script when developing modules to receive warnings about these issues".

2017-06-19 19:13 UTC, dharmabumstead commented on docs/docsite/rst/dev_guide/developing_modules_best_practices.rst
> +you about these kind of things.
Suggest revising this sentence to something like "Use the hacking/test-module script when developing modules to receive warnings about these issues".

2017-06-19 19:37 UTC, gundalow commented
I wonder if http://docs.ansible.com/ansible/modules_support.html might be a good place to link to this?

2017-06-19 19:46 UTC, gundalow commented
Also possibly here: http://docs.ansible.com/ansible/modules_intro.html
we don't seem to discuss *how* modules get installed, or which ones come packaged with ansible, at least not in the intro sections.

2017-06-21 15:55 UTC, kamranayub commented
@gundalow Yeah I second the Modules Intro or a section underneath that. Not sure about Support, I'd advocate a separate topic vs. putting it in there.

I can update the PR to at least add the into the Modules Intro section and we can go from there.

2017-06-21 17:50 UTC, kamranayub commented on docs/docsite/rst/dev_guide/developing_modules_best_practices.rst
> +you about these kind of things.
Done!

2017-06-28 01:18 UTC, dharmabumstead approved these changes
Looks good

2017-09-05 20:46 UTC, dharmabumstead commented
Doc changes look good to me. @gundalow, please review and merge if you agree.

2017-09-13 11:34 UTC, gundalow requested changes
Content looks good though the links need updating

```
.. _my-reference-label:

    Section to cross-reference
    --------------------------

    This is the text of the section.

    It refers to the section itself, see :ref:`my-reference-label`.
```

2017-09-13 15:02 UTC, kamranayub commented
Thanks, will update that soon. 👍

2017-11-23 00:24 UTC, dharmabumstead commented
Closing due to inactivity. Feel free to reopen/rebase.

2017-11-23 00:24 UTC, closed without merging