Fixed issue 24969
ansible/ansible pull request #24991
Opened 2017-05-24 16:57 UTC by ColOfAbRiX

##### SUMMARY
Fixes #24969

As suggested by the reporter, an environment variable is passed to parted so that the locale is always us_US.UTF-8

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
parted

##### ANSIBLE VERSION
```
ansible 2.4.0 (bugfix/24969 a31b01b68e) last updated 2017/05/24 16:52:30 (GMT +000)
  config file = 
  configured module search path = [u'/home/fcolonna/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/fcolonna/ansible_dev/ansible/lib/ansible
  executable location = /home/fcolonna/ansible_dev/ansible/bin/ansible
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

2017-05-26 13:40 UTC, ColOfAbRiX commented
ready_for_review

2017-05-26 14:19 UTC, ColOfAbRiX commented
ready_for_review

2017-05-31 20:52 UTC, bcoca requested changes

2017-05-31 20:52 UTC, bcoca commented on lib/ansible/modules/system/parted.py
> +env_default = {'LANG': 'us_US.UTF-8'}
you are not guarenteed us_US is available on all machines, use C/POSIX instead

2017-05-31 20:53 UTC, bcoca requested changes

2017-05-31 20:53 UTC, bcoca commented on lib/ansible/modules/system/parted.py
> +    rc, out, err = module.run_command(command, environ_update=env_default)
instead of calling it for every command, you can just use `module.run_command_environ_update` to set it once

2017-06-01 10:48 UTC, ColOfAbRiX commented
Two things I didn't know, thanks. I looked how other modules do it and then applied the change.

2017-06-01 19:26 UTC, bcoca approved these changes

2017-06-01 19:27 UTC, merged