Get rid of various warnings in test output
ansible/ansible pull request #25087
Opened 2017-05-26 22:28 UTC by dagwieers

##### SUMMARY
Skimming the test output for issues is easier without the bright purple
warnings. I believe each of these need to be surpressed (by fixing them
or disabling the warning itself).

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME
test

##### ANSIBLE VERSION

v2.4

2017-05-27 00:48 UTC, bcoca commented on test/integration/group_vars/all
> +test_bare_nested_bad: "test_bare_var == 321"
this is 'bad' on purpose

2017-05-27 11:26 UTC, dagwieers commented on test/integration/group_vars/all
> +test_bare_nested_bad: "test_bare_var == 321"
I assumed the bad was related to the value. At least that was obvious.

2017-05-30 21:50 UTC, dagwieers commented
Shippable acting out again. Close and re-open.

(SSL23_GET_SERVER_HELLO:tlsv1 alert internal error.)

2017-05-31 11:36 UTC, dagwieers commented
Unclear why this fails. Close and re-open again.

2017-06-02 14:09 UTC, gundalow commented
For my locally `devel` passes though `test-warnings` branch fails

`ansible-test integration  -vvv --docker centos6 get_url`

2017-06-02 14:11 UTC, gundalow requested changes
`task path: /root/ansible/test/integration/targets/get_url/tasks/main.yml:90` fails

not sure why though. Wonder if a rebase would help

2017-06-03 01:50 UTC, dagwieers commented
@gundalow Rebasing does not make a difference. Reverting the integration test to its original content, fails with the same error too...

2017-06-03 01:56 UTC, sivel submitted a review, later dismissed

2017-06-03 01:56 UTC, sivel commented on test/integration/targets/prepare_http_tests/tasks/main.yml
> +    has_httptester: lookup('env', 'HTTPTESTER') != ''
This may very well be the reason tests are failing.

This no longer templates this and is setting the value to the literal string here.

2017-06-03 01:59 UTC, sivel commented on test/integration/targets/prepare_http_tests/tasks/main.yml
> +    has_httptester: lookup('env', 'HTTPTESTER') != ''
From the error its communicating with httpbin.org when it should be talking to httptester.

2017-06-03 02:10 UTC, dagwieers commented on test/integration/targets/prepare_http_tests/tasks/main.yml
> +    has_httptester: lookup('env', 'HTTPTESTER') != ''
Thanks ! Now that you have spelled it out, it is strange I did not see this. Testing again.

2017-06-03 02:27 UTC, dagwieers commented
One thing that would help skimming Shippable output (and saves time) is if we could avoid the red color for ignored errors. This was a feature request from the community and maybe we should make it optional (and use it for integration tests too).

2017-06-03 02:56 UTC, dagwieers commented
Ready to be reviewed and merged. Thanks @sivel and @gundalow for your help !

2017-08-15 00:17 UTC, mattclay commented
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/33168/19/tests

2017-08-15 20:52 UTC, closed without merging