implements logging for the iptables module as requested in #25100
ansible/ansible pull request #25118
Opened 2017-05-28 22:39 UTC by jsrolon

##### SUMMARY
Adds two new parameters to the `iptables` module which allow logging: `log_prefix` and `log_level`. This is an implementation of the feature requested in issue #21500. Because `iptables` itself doesn't allow these options unless the `jump` target is the LOG extension, so does this implementation.

If the `jump` parameter is not specified but either of the added parameters is, the `jump` parameter is set as LOG.

This implementation creates the expected command:
```
iptables -A LOGGING -m limit --limit 2/second --limit-burst 20 -j LOG --log-prefix 'iptables: ' --log-level info
```
Given this:
```
iptables:
  chain: LOGGING
  action: append
  state: present
  limit: 2/second
  limit_burst: 20
  log_prefix: "iptables: "
  log_level: info
```

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
`iptables` module

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel 9c40fa9c89) last updated 2017/05/28 16:45:38 (GMT -500)
  config file = 
  configured module search path = [u'/~/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = ~/ansible/lib/ansible
  executable location = ~/ansible/bin/ansible
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

2017-05-29 07:39 UTC, LinusU approved these changes
Nice 👍

2017-11-03 13:51 UTC, sebastiendarocha commented
@jsrolon Hello, could you rebase your PR ? to see if the unit test pass, thanks

http://docs.ansible.com/ansible/latest/dev_guide/developing_rebasing.html

2017-11-21 12:35 UTC, sebastiendarocha requested changes
Please fix version_added and some duplicated lines in the code

Do you think you can add a unit test for this change ? (test/units/modules/system/test_iptables.py)

2017-11-21 12:35 UTC, sebastiendarocha commented on lib/ansible/modules/system/iptables.py
> +    version_added: "2.4"
It will be added in 2.5, you can backport it on 2.4.2 if it get merge on time.

2017-11-21 12:35 UTC, sebastiendarocha commented on lib/ansible/modules/system/iptables.py
> +    version_added: "2.4"
Same as previous comment

2017-11-21 12:35 UTC, sebastiendarocha commented on lib/ansible/modules/system/iptables.py
> +            log_prefix=dict(required=False, default=None, type='str'),
This param is already present on line 529 ;-)

2017-11-21 12:35 UTC, sebastiendarocha commented on lib/ansible/modules/system/iptables.py
> +    append_param(rule, params['log_prefix'], '--log-prefix', False)
This line is already present line 416

2017-11-21 12:35 UTC, sebastiendarocha commented on lib/ansible/modules/system/iptables.py
> +            log_prefix=dict(required=False, default=None, type='str'),
By the way, fixing this will resolve all the checks problems

2017-11-21 17:48 UTC, jsrolon commented on lib/ansible/modules/system/iptables.py
> +    version_added: "2.4"
Hi, I'm new so I don't exactly know what this means. Should I replace `version_added` to read 2.5, 2.4.2, or remove it altogether?

2017-11-21 17:53 UTC, sebastiendarocha commented on lib/ansible/modules/system/iptables.py
> +    version_added: "2.4"
Oh sorry: put 2.5 ;-)

2018-11-16 17:15 UTC, Akasurde commented
@jsrolon Are you still working on this ? Thanks.

2019-02-23 12:03 UTC, Akasurde commented
@jsrolon Thanks for the contribution. I have created new PR https://github.com/ansible/ansible/pull/52880 based upon your work. Thanks.

superseded by https://github.com/ansible/ansible/pull/52880

2019-02-23 12:03 UTC, closed without merging