Add note to `apt_key` doc about update requirement
ansible/ansible pull request #25111
Opened 2017-05-28 15:32 UTC by rcuza

##### SUMMARY

When a new repo and new key are added, attempts to install packages
signed by that key fail until `apt-get update` is run.  This note
is an attempt to help users avoid getting errors when they miss
this step.

Helps with #25091

##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

module: `apt_key`

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 18 2016, 07:03:34) [GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
```

##### ADDITIONAL INFORMATION

Adds one line to the notes section. I'm not sure how to represent that here.

2017-05-28 19:57 UTC, sivel commented
Instead of referencing running the `apt-get` command, it should instead reference using the `apt` ansible module to perform the cache update.

2017-05-31 21:42 UTC, bcoca requested changes

2017-05-31 21:42 UTC, bcoca commented on lib/ansible/modules/packaging/os/apt_key.py
> +    - adding a new key requires an apt cache update (e.g. `apt-get update`)
also point to the 'apt' module that is able to do this

2017-10-09 13:40 UTC, rcuza commented
@bcoca - Was this what you were looking for?

2018-05-15 16:29 UTC, Akasurde commented
@rcuza Could you please rebase ?

2018-05-15 16:41 UTC, rcuza commented
@akashihi - done

2018-08-07 20:57 UTC, acozine commented
Thanks for contributing to the docs @rcuza!

2018-08-07 20:57 UTC, acozine commented
rebuild_merge

2018-08-16 18:17 UTC, acozine commented
I don't know why this didn't auto-merge . . . merging manually now. Thanks again @rcuza.

2018-08-16 18:18 UTC, merged