vcenter_license: New module to manage vCenter licenses
ansible/ansible pull request #25143
Opened 2017-05-29 21:49 UTC by dagwieers

##### SUMMARY
This module supports check-mode and diff output.

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

vcenter_license

##### ANSIBLE VERSION

v2.4

2017-06-13 21:49 UTC, jctanner commented
cc @dav1x @nerzhul

2017-06-14 07:08 UTC, nerzhul commented
Sorry i cannot test this module as I don't have access to any license in my dc

2017-06-15 04:28 UTC, cigamit commented
Tested against VCenter 6.5.  Working well.  I can add / remove both my extra VCenter and my extra VMWare Cloud Suite (ESXi) keys.
I haven't looked at the API calls yet, but I would like the ability to modify the name of the assigned license key (since I can do it via the UI).  Also could use an example of the use of "labels".

2017-07-05 11:39 UTC, dagwieers commented
@cigamit We don't have a need to manage the labels, the license key provides all needed information so the label does not really add anything useful, and is just another complexity for no real gain IMO. I wouldn't mind if others would add that functionality, but I am not going to spend time on this.

Same for changing the name for assigned licenses, we have no need for this. There is a lot more you can do with the API, sure, but for us this works as designed. You add the licenses, the vcenter license will be auto-assigned to the vcenter if possible, and new ESXi systems will automatically get assigned to the correct license, so everything works out of the box for us.

Renaming to vmware_license seems wrong, since this module only works with vcenter. The namespace indicates what it is working against, not what you can do with it. So this module manages licenses on vCenter, nothing else.

2017-07-05 16:31 UTC, cigamit requested changes

2017-07-05 16:31 UTC, cigamit commented on lib/ansible/modules/cloud/vmware/vcenter_license.py
> +    module: vmware_license
Example is using the wrong module name, should be "vcenter_license"

2017-07-05 16:31 UTC, cigamit commented on lib/ansible/modules/cloud/vmware/vcenter_license.py
> +    module: vmware_license
Example is using the wrong module name, should be "vcenter_license"

2017-07-05 16:32 UTC, cigamit commented
@dagwieers I'm fine with all that, I can add managing the names later via a PR.

2017-07-06 11:48 UTC, dagwieers commented on lib/ansible/modules/cloud/vmware/vcenter_license.py
> +    module: vmware_license
Good catch. Fixed.

2017-07-06 11:49 UTC, dagwieers commented on lib/ansible/modules/cloud/vmware/vcenter_license.py
> +    module: vmware_license
Good catch. Fixed.

2017-07-06 12:56 UTC, cigamit commented
Works for me
shipit

2017-07-06 18:11 UTC, mattclay commented on test/integration/targets/vcenter_license/tasks/main.yml
> +  vmware_license:
CI failure in integration tests due to incorrect module name.

2017-07-06 20:57 UTC, mattclay commented
CI failure in integration tests:

```
{
    "failed": true, 
    "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined.The error was: 'vcenter_hostname' is undefined\n\nThe error appears to have been in '/root/ansible/test/integration/targets/vcenter_license/tasks/main.yml': line 31, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Wait for vcsim controller to come online {{ vcenter_hostname }}\n  ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes.  Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'vcenter_hostname' is undefined"
}
```

2017-07-14 14:20 UTC, Akasurde approved these changes
LGTM

2017-07-14 14:36 UTC, dagwieers commented
We need shipits :-)

shipit

2017-07-14 14:36 UTC, dagwieers commented
bot_status

2017-07-14 14:45 UTC, cigamit commented
shipit

2017-07-14 14:52 UTC, cigamit approved these changes

2017-07-14 14:52 UTC, cigamit commented
bot_status

2017-07-16 03:16 UTC, cigamit commented
shipit

2017-07-16 10:09 UTC, dagwieers commented
bot_status

2017-07-18 13:06 UTC, dagwieers commented
+label new_module

2017-08-06 05:40 UTC, mattclay commented
The simulator has recently been updated. Is anyone tracking whether or not the necessary licensing support has been or will be added to the simulator?

2017-08-07 06:46 UTC, Akasurde commented
@mattclay govcsim doesn't support addLicence feature, yet.

2017-08-07 16:49 UTC, merged