vmware_host: Small fixes and docs updates
ansible/ansible pull request #25144
Opened 2017-05-29 22:18 UTC by dagwieers

##### SUMMARY
This PR includes:
- A fix to no longer require a datacenter folder for adding a host
- Documentation improvements
- Ensure imports are specific

##### ISSUE TYPE

 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME

vmware_host

##### ANSIBLE VERSION
v2.4

2017-07-20 02:49 UTC, Akasurde requested changes

2017-07-20 02:49 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_host.py
>          self.dc = find_datacenter_by_name(self.content, self.datacenter_name)
if self.dc is None:

2017-07-20 02:49 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_host.py
> +  choices: [absent, present]
Indent is required here and below line.

2017-07-20 12:10 UTC, dagwieers commented on lib/ansible/modules/cloud/vmware/vmware_host.py
> +  choices: [absent, present]
Yeah, I know, is a man allowed to sleep around here ? :-D

2017-07-20 12:12 UTC, dagwieers commented on lib/ansible/modules/cloud/vmware/vmware_host.py
>          self.dc = find_datacenter_by_name(self.content, self.datacenter_name)
Nope, that's the whole point of my PR, self.dc can be None !

2017-07-20 13:19 UTC, Akasurde approved these changes
LGTM

2017-07-22 03:26 UTC, Akasurde commented
shipit

2017-07-24 17:02 UTC, merged