Fixes https://github.com/ansible/ansible/issues/25018
ansible/ansible pull request #25150
Opened 2017-05-30 07:20 UTC by basictheprogram

##### SUMMARY

Fixes #25018 

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

win_chocolatey

##### ANSIBLE VERSION

```
ansible 2.4.0 (issue-25018 6dd8a4cf78) last updated 2017/05/30 01:14:14 (GMT -500)
  config file =
  configured module search path = [u'/Users/tanner/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/tanner/projects/ansible.git/ansible/lib/ansible
  executable location = /Users/tanner/projects/ansible.git/ansible/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### ADDITIONAL INFORMATION

```

```

2017-05-31 15:43 UTC, gundalow commented
/cc @smadam813 @nitzmahone

2017-06-07 15:21 UTC, dagwieers requested changes

2017-06-07 15:21 UTC, dagwieers commented on lib/ansible/modules/windows/win_chocolatey.ps1
> +   if ($package -like "all")
Why use `-like`, and not just:

if ($package -eq "all") {
    return $true
}

2017-06-07 17:38 UTC, basictheprogram commented on lib/ansible/modules/windows/win_chocolatey.ps1
> +   if ($package -like "all")
Not a powershell guy, but -like matches "ALL" and "all" and "AlL", etc?

2017-06-07 18:10 UTC, dagwieers commented on lib/ansible/modules/windows/win_chocolatey.ps1
> +   if ($package -like "all")
And that works with chocolatey ?

2017-06-10 02:27 UTC, basictheprogram commented on lib/ansible/modules/windows/win_chocolatey.ps1
> +   if ($package -like "all")
I'm not very good at this open source/colab thing. 

Does it normally take 11 days for a trivial patch to get merged into master? 

If the syntactic sugar needs changing, just change it?

This bug is pretty shallow but waiting 11 days on the fix makes it feel really deep.

2017-06-10 10:11 UTC, dagwieers commented on lib/ansible/modules/windows/win_chocolatey.ps1
> +   if ($package -like "all")
If you are talking to me, I have no powers.

2017-07-04 22:30 UTC, dagwieers commented
@basictheprogram It seems I got that fix from your PR. So this one should have been merged instead of mine. If I had realised today, it would have saved me the effort to make a PR out of it. Sorry for not reading up on IRC about it :-(

2017-07-04 22:46 UTC, jborean93 commented on lib/ansible/modules/windows/win_chocolatey.ps1
> +   if ($package -like "all")
Sorry for not getting back to this but appreciate the effors @basictheprogram. `-eq` is case insensitive while `-ceq` is the case sensitive version. We merged `-eq` into devel just recently.

2017-07-06 11:35 UTC, dagwieers commented
This is implemented by #26417

2017-07-06 11:36 UTC, gundalow commented
Closing as it's been fixed by https://github.com/ansible/ansible/pull/26417

2017-07-06 11:36 UTC, closed without merging