Amazon Redshift module cluster deletion fix
ansible/ansible pull request #25164
Opened 2017-05-30 14:05 UTC by banzo

##### SUMMARY

This pull requests fixes the Redshift cluster deletion operation.

It corrects a typo error in the call to boto.redshift.create_cluster and adds necessary parameters (final snapshot creation options).

Fix #25161 

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

amazon redshift module

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 3.5.2 (default, Nov 17 2016, 17:05:23) [GCC 5.4.0 20160609]
```

##### ADDITIONAL INFORMATION

2017-05-31 15:17 UTC, ryansb requested changes

2017-05-31 15:17 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/redshift.py
> +        final_cluster_snapshot_identifier   = dict(aliases=['snapshot_identifier'], required=False),
I think this "snapshot_identifier" alias might be too terse. How about "final_snapshot_id" or similar?

2017-05-31 15:17 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/redshift.py
> +        module.fail_json(msg="Snapshot identifier (final_cluster_snapshot_identifier) must be provided if skip_final_cluster_snapshot is false.")
Instead of enforcing in code, you can use "required_if" on the argspec to enforce this.

2017-07-18 10:09 UTC, banzo commented
@ryansb thank you for the review, I did the suggested modifications. 
Is there anything else needed from me?

2017-07-18 20:24 UTC, ryansb requested changes

2017-07-18 20:24 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/redshift.py
> +    aliases: ['snapshot_identifier']
Changed to `final_snapshot_id`

2017-07-18 20:24 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/redshift.py
> +    aliases: ['skip_snapshot']
Changed to `skip_final_snapshot`

2017-07-18 21:11 UTC, s-hertel approved these changes
Tested and working as expected. LGTM after the docs are fixed.

2017-08-21 09:06 UTC, banzo commented
@s-hertel the doc has been updated

2017-08-24 18:49 UTC, ryansb approved these changes

2017-08-24 20:41 UTC, merged

2018-02-07 19:00 UTC, rafaeldriutti commented
Hello! 
I think there´s a bug here... I'm trying to create a redshift cluster but get an error about missing parameters:

```
"msg": "skip_final_cluster_snapshot is False but the following are missing: final_cluster_snapshot_identifier"
```
And the command is create, according to the docs these parameters shouldn't be mandatory for create
```
"invocation": {
        "module_args": {
            "allow_version_upgrade": true, 
            "automated_snapshot_retention_period": "35", 
            "cluster_parameter_group_name": "XXXXXXX", 
            "cluster_subnet_group_name": "XXXXXXXX", 
            "cluster_type": "multi-node", 
            "command": "create", 
            "db_name": "XXXXXXX", 
            "encrypted": false, 
            "enhanced_vpc_routing": false, 
            "identifier": "XXXXXXXX", 
            "maint_window": "Mon:02:00-Mon:02:30", 
            "node_type": "dc2.large", 
            "number_of_nodes": 3, 
            "param_group_name": "XXXXXXXXXXX", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 5439, 
            "preferred_maintenance_window": "Mon:02:00-Mon:02:30", 
            "publicly_accessible": false, 
            "region": "us-east-1", 
            "retention_period": "35", 
            "skip_final_cluster_snapshot": false, 
            "subnet": "axxxxxxxxx", 
            "username": "master", 
            "validate_certs": true, 
            "vpc_security_group_ids": [
                "xxxxxxx"
            ], 
            "vpc_security_groups": "xxxxxxx", 
            "wait": false, 
            "wait_timeout": 300
        }

```
I think this is caused by https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/redshift.py#L453

```
skip_final_cluster_snapshot=dict(aliases=['skip_final_snapshot'], type='bool', default=False),
```
It should be  otherwise it defaults to False even when you don't set it calling the module.