Fixes #25179, refactored Redis Lookup
ansible/ansible pull request #25180
Opened 2017-05-30 22:49 UTC by padajuan

##### SUMMARY
Fixes #25179 

This refactor will take care of those enhancements:

- redis_kv Lookup Plugin are a bit old and need a refactor
- Receive an array and returns all the values required on this array
- Receive an string and returns the value associated to the Key
- Environment variables for IP and Port Server

New Environment Variables with default values:

- **ANSIBLE_REDIS_URL:** 127.0.0.1
- **ANSIBLE_REDIS_PORT:** 6379

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
**redis_kv** Lookup Plugin

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, May 10 2017, 20:04:36) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]

```

##### ADDITIONAL INFORMATION
This change is necessary because you cannot pass an array with a group of keys to recover, before this changes you need to concat the server url and a bunch of keys.

Now the URL and Port are Environment variables and it's more clean to claim a variable from redis without the server in the lookup call.

- Input YML file:

```yml
---
- name: 'Ansible Configuration Management'
  hosts: localhost
  connection: local
  vars:
    entry_files: ['key1','key2','key5']
  tasks:
    - name: '[CFG MGMT] Recover the file status from storage'
      set_fact:
        redis_multi_var: "{{ lookup('redis_kv', 'key1', 'key2', 'key3') }}"
        redis_array: "{{ lookup('redis_kv', entry_files) }}"

    - debug: var=redis_multi_var
    - debug: var=redis_array
```

- Output:

```
PLAY [Ansible Configuration Management] ******************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [[CFG MGMT] Recover the file status from storage] ***************************************************************************************************************************************************************************************
ok: [localhost]

TASK [debug] *********************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false, 
    "redis_multi_var": "Value1,Value2,Value3"
}

TASK [debug] *********************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false, 
    "redis_array": "Value1,Value2,Value5"
}

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0   
```

2017-05-31 20:38 UTC, bcoca requested changes

2017-05-31 20:38 UTC, bcoca commented on lib/ansible/plugins/lookup/redis_kv.py
> +if os.getenv('ANSIBLE_REDIS_URL') is not None:
wny not just ```myvar = os.getenv('var', 'default')```?

2017-06-01 09:58 UTC, padajuan commented on lib/ansible/plugins/lookup/redis_kv.py
> +if os.getenv('ANSIBLE_REDIS_URL') is not None:
More elegant, implementing it ;)

2017-06-01 11:52 UTC, padajuan commented
I think that this error are a platform one :D 
`ReadTimeout: HTTPSConnectionPool(host='ec2-13-58-110-185.us-east-2.compute.amazonaws.com', port=5986): Read timed out. (read timeout=30)`

2017-06-01 15:35 UTC, padajuan commented
I think there is some problems with the deployment platform, isn't it?

2017-06-01 19:18 UTC, gundalow commented
I've triggered a rerun of Shippable.
For future reference you can do this by closing & opening the PR

2017-06-17 07:56 UTC, padajuan commented
It's Ok for you @bcoca ?

2017-06-17 11:45 UTC, gundalow commented
closing and reopening to trigger CI

2017-12-13 18:26 UTC, bcoca commented
i hope #33883 supersedes this one

2017-12-31 08:44 UTC, Akasurde commented
Closing this issue as PR #33883 is merged and supersedes this.

2017-12-31 08:44 UTC, closed without merging