New Module - Adds the bigip_config module to Ansible
ansible/ansible pull request #25191
Opened 2017-05-31 03:31 UTC by caphrim007

##### SUMMARY
This patch adds the bigip_config module to Ansible to support
merging SCF files, saving running configs, resetting config
and validating SCF configs

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

lib/ansible/modules/network/f5/bigip_config.py

##### ANSIBLE VERSION

```

```

##### ADDITIONAL INFORMATION
Unit tests are provided. Integration tests can be found here

http
s://github.com/F5Networks/f5-ansible/blob/devel/test/integration/bigip_command.yaml#L23
https://github.com/F5Networks/f5-ansible/tree/devel/test/integration/targets/bigip_command/tasks

2017-05-31 15:03 UTC, gundalow commented on lib/ansible/modules/network/f5/bigip_config.py
> +                choices=BOOLEANS
No need to specify `choices`

2017-05-31 15:03 UTC, gundalow commented on lib/ansible/modules/network/f5/bigip_config.py
> +                default='no',
I think this should be false (not a string)

2017-05-31 15:03 UTC, gundalow commented on lib/ansible/modules/network/f5/bigip_config.py
> +  - Requires Ansible >= 2.3.
New modules only go into `devel`, so this will only be available in Ansible 2.4

2017-05-31 16:18 UTC, caphrim007 commented
@gundalow i dont know what it's talking about about conflicts. there were no conflicts on my branch and it rebased just fine.

2017-05-31 16:40 UTC, caphrim007 commented
@gundalow ready for review

2017-06-06 10:38 UTC, gundalow requested changes

2017-06-06 10:38 UTC, gundalow commented on lib/ansible/modules/network/f5/bigip_config.py
> +    significant importence because it allows you to save your running
importance

2017-06-06 10:38 UTC, gundalow commented on lib/ansible/modules/network/f5/bigip_config.py
> +    modify running configuration, or merge SCF formatted files intp
intp -> into?

2017-06-06 10:38 UTC, gundalow commented on lib/ansible/modules/network/f5/bigip_config.py
> +        Ansible's C(file) or C(template) lookup plugins respectively.
+1 to stating this.
I wonder if an example would be useful

2017-06-06 17:22 UTC, caphrim007 commented on lib/ansible/modules/network/f5/bigip_config.py
> +        Ansible's C(file) or C(template) lookup plugins respectively.
fixed

2017-06-06 17:22 UTC, caphrim007 commented on lib/ansible/modules/network/f5/bigip_config.py
> +    significant importence because it allows you to save your running
fixed

2017-06-06 17:22 UTC, caphrim007 commented on lib/ansible/modules/network/f5/bigip_config.py
> +    modify running configuration, or merge SCF formatted files intp
fixed

2017-06-06 17:52 UTC, gundalow approved these changes

2017-06-06 17:52 UTC, merged