Pr 19786
ansible/ansible pull request #25290
Opened 2017-06-02 03:26 UTC by willthames

##### SUMMARY

This module manages the creation, modification, deletion of RDS Option groups and the associated options applied to those groups.

Note: Some of the options list output has been removed for the sake of brevity.

TASK [print new option group] **************************************************
ok: [localhost] => {
    "msg": {
        "changed": true, 
        "option_group": {
            "OptionGroupsList": [
                {
                    "AllowsVpcAndNonVpcInstanceMemberships": false, 
                    "EngineName": "mysql", 
                    "MajorEngineVersion": "5.6", 
                    "OptionGroupDescription": "test mysql option group", 
                    "OptionGroupName": "test-mysql-option-group", 
                    "Options": [
                        {
                            "DBSecurityGroupMemberships": [], 
                            "OptionDescription": "Innodb Memcached for MySQL", 
                            "OptionName": "MEMCACHED", 
                            "OptionSettings": [
                                {
                                    "AllowedValues": "1-2", 
                                    "ApplyType": "STATIC", 
                                    "DataType": "FLOAT", 
                                    "DefaultValue": "1.25", 
                                    "Description": "Chunk size growth factor that controls the size of each successive chunk with each chunk growing times this amount larger than the previous chunk.", 
                                    "IsCollection": false, 
                                    "IsModifiable": true, 
                                    "Name": "CHUNK_SIZE_GROWTH_FACTOR", 
                                    "Value": "1.35"
                                }, 
                                {
                                    "AllowedValues": "10-1024", 
                                    "ApplyType": "STATIC", 
                                    "DataType": "INTEGER", 
                                    "DefaultValue": "1024", 
                                    "Description": "Maximum number of concurrent connections. Setting this value to anything less than 10 prevents MySQL from starting.", 
                                    "IsCollection": false, 
                                    "IsModifiable": true, 
                                    "Name": "MAX_SIMULTANEOUS_CONNECTIONS", 
                                    "Value": "20"
                                }
                            ], 
                            "Permanent": false, 
                            "Persistent": false, 
                            "Port": 11211, 
                            "VpcSecurityGroupMemberships": [
                                {
                                    "Status": "active", 
                                    "VpcSecurityGroupId": "sg-d188c123"
                                }
                            ]
                        }
                    ], 
                    "VpcId": "vpc-aad24123"
                }
            ], 
            "ResponseMetadata": {
                "HTTPStatusCode": 200, 
                "RequestId": "cb9bf613-7027-11e6-8515-d3586c4629c2"
            }
        }
    }
}

##### ISSUE TYPE
New Module Pull Request

##### COMPONENT NAME
rds_option_group

##### ANSIBLE VERSION

```
ansible 2.4.0 (devel 4847613725) last updated 2017/06/02 13:25:04 (GMT +1000)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/will/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/will/src/ansible/lib/ansible
  executable location = /home/will/src/ansible/bin/ansible
  python version = 2.7.13 (default, Jan 12 2017, 17:59:37) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]

```

##### ADDITIONAL INFORMATION

Supersedes #19786

2017-06-02 13:20 UTC, jctanner commented
cc @s-hertel @ryansb

2017-06-28 13:06 UTC, s-hertel requested changes

2017-06-28 13:06 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/rds_option_group.py
> +        if 'OptionGroupNotFound' not in e.message:
The OptionGroupNotFoundFault exception doesn't seem to have a .message. Neither does the exception for invalid parameters (though maybe we don't care about that since that's user error). This should be something like
`if e.response['Error']['Code'] != 'OptionGroupNotFoundFault':` or `if 'OptionGroupNotFoundFault' not in str(e):`

2017-06-28 13:06 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/rds_option_group.py
> +    results = response['OptionGroupsList'][0]
Sometimes response is None so this doesn't work

2017-06-28 13:06 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/rds_option_group.py
> +    current_option_group = get_option_group(client, module)
should be `current_option =`

2017-06-28 13:06 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/rds_option_group.py
> +    for current_option in current_option_group['OptionGroupsList']:
Can lead to a KeyError - maybe
`for current_option in current_option_group.get('OptionGroupsList', []):`

2017-06-28 13:06 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/rds_option_group.py
> +        return to_be_added, to_be_removed
Needs to be unindented so these are always returned

2017-06-28 13:06 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/rds_option_group.py
> +                    for name in iter(setting_name):
Not excited by all the nested for loops but working as expected.

2017-06-28 13:06 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/rds_option_group.py
> +'''
could add boto3 and botocore to the docs as requirements

2018-03-05 12:48 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/rds_option_group.py
> +        if 'OptionGroupNotFound' not in e.message:
^ Just updating this if anything is looking at it. That's a general Python3 thing (no .message), not specific to this exception.

2018-10-26 12:35 UTC, SimplySeth commented
Is this dead ??
I don't see it in the docs nor in the repo.

2018-10-27 07:36 UTC, willthames commented
It's not dead it's just resting. I haven't addressed @s-hertel's feedback and I should have, it just slipped off my to-do list. I'll see if I can resurrect it.

2018-10-27 12:33 UTC, SimplySeth commented
Thank you @willthames. I started `rds_option_group_facts`

2018-10-29 14:52 UTC, SimplySeth commented
I rant it with this ... 

```
- name: Make sure option group exists
  rds_option_group:
    option_group_name: "{{ rds_name }}-optgroup"
    profile: "{{ aws_profile }}"
    region: "{{ aws_region }}"
    state: present
  register: rog

- debug:
    var: rog
```
```
Got this output ... 
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'OptionGroupNotFoundFault' object has no attribute 'message'
fatal: [localhost]: FAILED! => changed=false 
  module_stderr: |-
    Traceback (most recent call last):
      File "/tmp/ansible_rds_option_group_payload_0tutyoi0/__main__.py", line 166, in get_option_group
      File "/home/sr001/aws_rds/venv/lib/python3.6/site-packages/botocore/client.py", line 320, in _api_call
        return self._make_api_call(operation_name, kwargs)
      File "/home/sr001/aws_rds/venv/lib/python3.6/site-packages/botocore/client.py", line 623, in _make_api_call
        raise error_class(parsed_response, operation_name)
    botocore.errorfactory.OptionGroupNotFoundFault: An error occurred (OptionGroupNotFoundFault) when calling the DescribeOptionGroups operation: Specified OptionGroupName: devops-poc-optgroup not found.
  
    During handling of the above exception, another exception occurred:
  
    Traceback (most recent call last):
      File "/home/sr001/.ansible/tmp/ansible-tmp-1540824136.3155136-274541110823145/AnsiballZ_rds_option_group.py", line 113, in <module>
        _ansiballz_main()
      File "/home/sr001/.ansible/tmp/ansible-tmp-1540824136.3155136-274541110823145/AnsiballZ_rds_option_group.py", line 105, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/sr001/.ansible/tmp/ansible-tmp-1540824136.3155136-274541110823145/AnsiballZ_rds_option_group.py", line 48, in invoke_module
        imp.load_module('__main__', mod, module, MOD_DESC)
      File "/home/sr001/aws_rds/venv/lib/python3.6/imp.py", line 235, in load_module
        return load_source(name, filename, file)
      File "/home/sr001/aws_rds/venv/lib/python3.6/imp.py", line 170, in load_source
        module = _exec(spec, sys.modules[name])
      File "<frozen importlib._bootstrap>", line 618, in _exec
      File "<frozen importlib._bootstrap_external>", line 678, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/tmp/ansible_rds_option_group_payload_0tutyoi0/__main__.py", line 384, in <module>
      File "/tmp/ansible_rds_option_group_payload_0tutyoi0/__main__.py", line 379, in main
      File "/tmp/ansible_rds_option_group_payload_0tutyoi0/__main__.py", line 291, in setup_rds_option_group
      File "/tmp/ansible_rds_option_group_payload_0tutyoi0/__main__.py", line 168, in get_option_group
    AttributeError: 'OptionGroupNotFoundFault' object has no attribute 'message'
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```

2018-10-31 15:43 UTC, SimplySeth commented
in `get_option_group` I had to add: 
```
except client.exceptions.OptionGroupNotFoundFault:
      response = {'OptionGroupsList': list([None])}
```

in  `match_option_group_options` I changed .... 

`if current_option['Options'] == []:` to `current_option_group['Options']:`
  and 
`for option in current_option['Options']:` to `for option in current_option_group['Options']:`

that's how I got it to work for me without errors when creating a new option_group

2019-09-19 12:38 UTC, gundalow commented
I just spoke with @willthames, he doesn't have time to work on this, so closing.
Others are welcome to use this as a base for a fresh PR.

2019-09-19 12:38 UTC, closed without merging