Add dynamic inventory for Scaleway
ansible/ansible pull request #25294
Opened 2017-06-02 09:43 UTC by blubber

The script requires a scaleway.ini file, an example with the
default values is supplied. The only configuration value that is
required is `api_token`.

The inventory is generated by iterating over all servers in all
regions. All API information thati s available on each server
is also available as host variables prefixed with `scw_`.

Hosts are put into a group called `scaleway`, any additional
groups can be specified by adding tags formatted as
`ansible:<group>` (e.g. `ansible:nginx`).

Note: the `requests` package is required.

2017-06-02 13:13 UTC, Akasurde requested changes

2017-06-02 13:13 UTC, Akasurde commented on contrib/inventory/scaleway.py
> +
GNU GPL Licence

2017-06-02 13:31 UTC, blubber commented on contrib/inventory/scaleway.py
> +
Done.

2018-04-11 08:26 UTC, sieben commented
@blubber could you rebase? @Akasurde do you have additional reviews about this MR?

2018-04-11 08:41 UTC, Akasurde reviewed
Rest looks good to me.

2018-04-11 08:41 UTC, Akasurde commented on contrib/inventory/scaleway.ini
> +api_token =
A brief introduction to each parameter would be very helpful to new person. I would expect at least one liner for each parameter.

2018-04-11 08:41 UTC, Akasurde commented on contrib/inventory/scaleway.py
> +# (c) 2017, Tiemo Kieft
```Copyright: (c) 2018, Tiemo Kieft```

2018-04-11 08:41 UTC, Akasurde commented on contrib/inventory/scaleway.py
> +# This file is part of Ansible,
Replace Line 4 to 19 to 

```
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
```

2018-04-16 11:59 UTC, sieben commented
I've created a dynamic inventory plugin for ansible. You can check it out here: https://github.com/ansible/ansible/pull/38739

2018-05-14 10:02 UTC, blubber commented
Guess this PR can be closed now #38739 was merged.

2018-05-14 10:29 UTC, Akasurde commented
@blubber Thanks for the contribution.

2018-05-14 10:29 UTC, closed without merging

2018-07-17 08:40 UTC, sieben commented
https://github.com/ansible/ansible/pull/41658