Allow creation of github release tags
ansible/ansible pull request #25338
Opened 2017-06-04 11:33 UTC by adrianmoisey

##### SUMMARY

Allows a user to create a github release from Ansible.
Useful for anyone doing code releases with Ansible and GitHub Releases.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
github_release
##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```

##### ADDITIONAL INFORMATION
A replacement for https://github.com/ansible/ansible/pull/22741 which got stale, and difficult to rebase.

2017-06-04 16:58 UTC, Akasurde requested changes

2017-06-04 16:58 UTC, Akasurde commented on lib/ansible/modules/source_control/github_release.py
> +            - Tag name when creating a release. Required when using create_release.
Reword as 

`Required when using action is set to C(create_release).`

2017-06-04 16:58 UTC, Akasurde commented on lib/ansible/modules/source_control/github_release.py
> +            module.fail_json(msg="Specify tag in order to create a release.")
Use `required_if` 

`required_if = [('action', 'create_release', ['tag'])]`

2017-06-05 05:45 UTC, adrianmoisey commented on lib/ansible/modules/source_control/github_release.py
> +            module.fail_json(msg="Specify tag in order to create a release.")
I've implemented it here: 4399c301a2413f394e78bb048656b9cf744940e9
Please let me know if that's right.

2017-06-05 05:46 UTC, adrianmoisey commented on lib/ansible/modules/source_control/github_release.py
> +            - Tag name when creating a release. Required when using create_release.
Fixed in fcdac88cdcb21fa76f0879f3b96d402c8fb6e2dc

2017-06-05 05:59 UTC, Akasurde approved these changes
shipit

2017-07-06 08:46 UTC, adrianmoisey commented
:bell:

2017-07-14 08:38 UTC, adrianmoisey commented
@Akasurde how do I get this merged?

2017-07-14 12:31 UTC, Akasurde commented
@adrianmoisey Try to ping someone on #ansible-devel on IRC, to get review and merge. @gundalow  might help you.

2017-07-14 18:57 UTC, merged