Formatted Dynamic Inventory link for Openstack
ansible/ansible pull request #25351
Opened 2017-06-05 10:25 UTC by san7ket

##### SUMMARY

##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME
docs/docsite/rst/intro_dynamic_inventory.rst

##### ANSIBLE VERSION

```
2.4devel
```

2017-06-05 10:50 UTC, Akasurde approved these changes
shipit

2017-06-15 08:52 UTC, dharmabumstead requested changes

2017-06-15 08:52 UTC, dharmabumstead commented on docs/docsite/rst/intro_dynamic_inventory.rst
> +You can download the latest version of the OpenStack inventory script at: `here <https://raw.githubusercontent.com/ansible/ansible/devel/contrib/inventory/openstack.py>`_
Please remove the "at:"

2017-06-15 09:38 UTC, san7ket commented
@dharmabumstead done.

2017-06-15 09:59 UTC, dharmabumstead approved these changes
Thanks @san7ket!

2017-06-15 10:00 UTC, merged