Initial commit for Pure Storage Ansible module
ansible/ansible pull request #25386
Opened 2017-06-06 13:34 UTC by sdodsley

##### SUMMARY
Storage module for Pure Storage FlashArray device. Modules for create/delete/modify volumes, create/delete hosts, attach hosts to volumes, create/modify/delete host groups and create/delete protection groups

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
 - purefa_host
 - purefa_volume
 - purefa_pg
 - purefa_hg

##### ANSIBLE VERSION
```
ansible 2.4.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/pureuser/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

2017-06-07 10:12 UTC, gundalow requested changes

2017-06-07 10:12 UTC, gundalow commented on lib/ansible/module_utils/pure.py
> +        api_token=dict(),
Please add `no_log=true` to ensure the API token gets masked in output

2017-06-07 10:12 UTC, gundalow commented on lib/ansible/utils/module_docs_fragments/purestorage.py
> +  - You must set PUREFA_URL and PUREFA_API environment variables
`You must set C(PUREFA_URL) and C(PUREFA_API) environment variables`

2017-06-07 10:12 UTC, gundalow commented on lib/ansible/utils/module_docs_fragments/purestorage.py
> +    if url and api_token arguments are not passed to the module directly
`if I(url) and I(api_token) arguments are not passed to the module directly.`

2017-06-07 10:15 UTC, gundalow commented
@sdodsley Thanks for these new modules, from a quick look they seem sensible.

We've found the following process works best for getting groups of modules integrated
http://docs.ansible.com/ansible/dev_guide/developing_modules_in_groups.html#your-first-pull-request

So if you could remove the other modules from this PR is merged, that would be great.

You may also find some of the documentation & formatting information in http://docs.ansible.com/ansible/dev_guide/developing_modules_in_groups.html useful.

2017-06-07 16:51 UTC, sdodsley commented
@gundalow Happy to do these changes, but concerned about timing for the batched PRs after the initial merge. If there is any risk of a RC for 2.4 that would split the PRs then this would make the whole module useless. All modules have to be available to be effective.

2017-06-07 19:58 UTC, gundalow commented
If this is the total set of modules, you are fine for 2.4.

Feel free to `@gundalow` in the PRs that get raised after the first one has been merged

2017-06-07 20:03 UTC, gundalow requested changes
Thanks for removing the other modules

2017-06-07 20:03 UTC, gundalow commented on lib/ansible/modules/storage/purestorage/purefa_host.py
> +      - Creates/Modifies Host when present or removes when absent
This doesn't seem to read right with present vs absent

2017-06-07 20:03 UTC, gundalow commented on lib/ansible/modules/storage/purestorage/purefa_host.py
> +      - Defines the host connection protocol for volumes, either iscsi of fc
`Defines the host connection protocol for volumes.`

No need to mention iscsi or fc, docs will be generated by the `choices:` line.

2017-06-07 20:03 UTC, gundalow commented on lib/ansible/modules/storage/purestorage/purefa_host.py
> +    description:
For consistence please ensure all `description:` lines are full sentences (capital letters + full stop at the end)

2017-06-07 20:03 UTC, gundalow commented on lib/ansible/modules/storage/purestorage/purefa_host.py
> +version_added: 2.4
`version_added: "2.4"`

2017-06-07 20:03 UTC, gundalow commented on lib/ansible/utils/module_docs_fragments/purestorage.py
> +      - FlashArray API token for admin privilaed user.
privileged

2017-06-08 15:42 UTC, sdodsley commented
@gundalow Can you have a look to see if these revisions are correct?

2017-06-13 13:39 UTC, sdodsley commented
Hi John



Any chance you could have a look at this PR so I can start work on the
others once we have the first one merged?



I modified as per your requests, but one of them isn’t being picked up by
ansibot so it still appears there is a request outstanding.



 | *Simon Dodsley MBCS CITP* |  Director, New Stack Technologies

 | Pure Storage, Inc. | One Penn Plaza – Suite 3430, New York, NY 10119
 | t: +1 (510) 516-2682 | simon@purestorage.com | www.purestorage.com

[image: http://www.purestorage.com/_media/header_logo.png?130529]



*From:* John R Barker [mailto:notifications@github.com]
*Sent:* Wednesday, June 7, 2017 4:05 PM
*To:* ansible/ansible <ansible@noreply.github.com>
*Cc:* Simon Dodsley <simon@purestorage.com>; Mention <
mention@noreply.github.com>
*Subject:* Re: [ansible/ansible] Initial commit for Pure Storage Ansible
module (#25386)



*@gundalow* requested changes on this pull request.

Thanks for removing the other modules
------------------------------

In lib/ansible/modules/storage/purestorage/purefa_host.py
<https://github.com/ansible/ansible/pull/25386#discussion_r120729225>:

> +DOCUMENTATION = '''

+---

+module: purefa_host

+version_added: 2.4

+short_description: Create, Delete and Modify Hosts on Pure Storage FlashArray

+description:

+    - This module creates, deletes or modifies hosts on Pure Storage
FlashArray.

+author: Simon Dodsley (@simondodsley)

+options:

+  host:

+    description:

+      - Host Name

+    required: true

+  state:

+    description:

+      - Creates/Modifies Host when present or removes when absent

This doesn't seem to read right with present vs absent
------------------------------

In lib/ansible/modules/storage/purestorage/purefa_host.py
<https://github.com/ansible/ansible/pull/25386#discussion_r120729338>:

> +author: Simon Dodsley (@simondodsley)

+options:

+  host:

+    description:

+      - Host Name

+    required: true

+  state:

+    description:

+      - Creates/Modifies Host when present or removes when absent

+      - When removing all connected volumes will be disconnected

+    required: false

+    default: present

+    choices: [ "present", "absent" ]

+  protocol:

+    description:

+      - Defines the host connection protocol for volumes, either iscsi of fc

Defines the host connection protocol for volumes.

No need to mention iscsi or fc, docs will be generated by the choices: line.
------------------------------

In lib/ansible/modules/storage/purestorage/purefa_host.py
<https://github.com/ansible/ansible/pull/25386#discussion_r120729405>:

> +

+DOCUMENTATION = '''

+---

+module: purefa_host

+version_added: 2.4

+short_description: Create, Delete and Modify Hosts on Pure Storage FlashArray

+description:

+    - This module creates, deletes or modifies hosts on Pure Storage
FlashArray.

+author: Simon Dodsley (@simondodsley)

+options:

+  host:

+    description:

+      - Host Name

+    required: true

+  state:

+    description:

For consistence please ensure all description: lines are full sentences
(capital letters + full stop at the end)
------------------------------

In lib/ansible/modules/storage/purestorage/purefa_host.py
<https://github.com/ansible/ansible/pull/25386#discussion_r120729700>:

> +# but WITHOUT ANY WARRANTY; without even the implied warranty of

+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the

+# GNU General Public License for more details.

+#

+# You should have received a copy of the GNU General Public License

+# along with Ansible. If not, see <http://www.gnu.org/licenses/>.

+

+ANSIBLE_METADATA = {'metadata_version': '1.0',

+                    'status': ['preview'],

+                    'supported_by': 'community'}

+

+

+DOCUMENTATION = '''

+---

+module: purefa_host

+version_added: 2.4

version_added: "2.4"
------------------------------

In lib/ansible/utils/module_docs_fragments/purestorage.py
<https://github.com/ansible/ansible/pull/25386#discussion_r120729955>:

> +# You should have received a copy of the GNU General Public License

+# along with Ansible.  If not, see <http://www.gnu.org/licenses/>.

+

+

+class ModuleDocFragment(object):

+

+    # Standard Pure Storage documentation fragment

+    DOCUMENTATION = '''

+options:

+  fa_url:

+    description:

+      - FlashArray management IPv4 address or Hostname.

+    required: true

+  api_token:

+    description:

+      - FlashArray API token for admin privilaed user.

privileged

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ansible/ansible/pull/25386#pullrequestreview-42717412>,
or mute the thread
<https://github.com/notifications/unsubscribe-auth/AN6CwvWW6xVKHXAvO_HZVPudrlPIMU7Fks5sBwJtgaJpZM4NxWZ_>
.

2017-06-16 10:28 UTC, gundalow approved these changes

2017-06-16 10:28 UTC, merged

2017-06-16 10:29 UTC, gundalow commented
Merged, thanks
You can now raise one PR per module for the remaining