win_package: Clean up parameters, bugfix, docs
ansible/ansible pull request #25398
Opened 2017-06-06 18:04 UTC by dagwieers

##### SUMMARY
This PR includes:
- Used strict tryping for module parameters
- Added check-mode support
- Added `-aliases` support
- Renamed `user_name` to `username`
- Renamed `user_password` to `password`
- Clean up documentation

This fixes ansible/ansible-modules-extras#3067

##### ISSUE TYPE

 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME

win_package

##### ANSIBLE VERSION

v2.4

2017-06-06 22:55 UTC, dagwieers commented
@nitzmahone @jborean93 @jhawkesworth @trondhindenes Ready to be reviewed and merged.

2017-06-14 13:25 UTC, dagwieers commented
Wake up call to to WWG :-) @nitzmahone @jborean93 @jhawkesworth @trondhindenes

2017-06-16 23:06 UTC, jborean93 requested changes
Are you able to add check mode tests to the integration tests as well if you have added the support.

I can see the need to review this module and win_msi at some point and come up with an easier solution when installing programs.

2017-06-16 23:06 UTC, jborean93 commented on lib/ansible/modules/windows/win_package.py
>    product_id:
Isn't it the opposite, this should be `productid` and the alias is `product_id`?

2017-06-16 23:06 UTC, jborean93 commented on lib/ansible/modules/windows/win_package.py
>  '''
Are you able to add the return values for this?

2017-06-20 16:56 UTC, dagwieers commented on lib/ansible/modules/windows/win_package.py
>    product_id:
You are right, fixed.

2017-06-20 17:08 UTC, dagwieers commented on lib/ansible/modules/windows/win_package.py
>  '''
Sure, missed it.

2017-06-21 19:26 UTC, mattclay commented
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/26064/9/tests

2017-06-29 15:53 UTC, trondhindenes commented
I'm not sure I see the point in just "brutally" changing param names. People use these modules in production, so we should be _very_ careful / have good reasons for just ripping out params and replacing them. We have alias and depcrecation stuff available, so lets use those to make sure we give users a smooth transition.

2017-06-29 16:26 UTC, dagwieers commented
@trondhindenes I am surprised you call this brutal. There are aliases, so there is no impact. The change in naming is to bring these in line with other modules and get more conformity between Windows modules themselves and the other non-Windows modules. This is going to make it much easier for people that don't have to remember that **win_package** uses *user_name* and *user_password* uniquely, contrary to standard practice.

There may only be a problem for people using the new parameters and then going back to an older version of this module. But that's the case for so many things, we are not forward-compatible.

PS There is a ticket for improving these things and it was discussed once during a core meeting. ansible/ansible#20160

2017-06-29 22:32 UTC, mattclay commented
CI failure in integration tests `test/integration/targets/win_package/tasks/main.yml:51`:

```
{
    "assertion": "not win_package_install_again_result|failed", 
    "changed": false, 
    "evaluated_to": false, 
    "failed": true
}
```

2017-06-30 13:53 UTC, dagwieers commented
@mattclay Not sure what is going on there, the previous task clearly did not fail. Still the assert fails on the fact that it not failed...

2017-06-30 17:48 UTC, mattclay commented
@dagwieers The problem is caused by the module result:

```
ok: [windows-2012-R2_RTM] => {
    "failed": false,
    "win_package_install_again_result": {
        "arguments": null,
        "changed": false,
        "failed": false,
        "name": "C:\\Program Files\\7z922-x64.msi",
        "path": "C:\\Program Files\\7z922-x64.msi",
        "productid": "{23170F69-40C1-2702-0922-000001000000}",
        "rc": null,
        "restart_required": false
    }
}
```

Specifically, the presence of `rc: null` causes the failure.

2017-07-01 11:13 UTC, dagwieers commented
@mattclay Hmm, the `failed` filter plugin still makes assumptions about the `rc` return value. That's not right, we wanted to get rid of that.

2017-07-12 21:52 UTC, mattclay commented
CI failure in integration tests:

```
{
    "arguments": null, 
    "changed": false, 
    "failed": true, 
    "msg": "This error A parameter with the name 'WhatIf' was defined multiple times for the command.", 
    "name": "C:\\Program Files\\7z922-x64.msi", 
    "path": "C:\\Program Files\\7z922-x64.msi", 
    "productid": "{23170F69-40C1-2702-0922-000001000000}", 
    "rc": null, 
    "restart_required": false
}
```

2017-07-12 22:05 UTC, nitzmahone requested changes

2017-07-12 22:05 UTC, nitzmahone commented on lib/ansible/modules/windows/win_package.ps1
> +        Fail-Json -obj $result -message "This error $errormsg"
Suspect this is debug cruft? (just noticed it in the test failure)

2017-07-12 22:29 UTC, dagwieers commented on lib/ansible/modules/windows/win_package.ps1
> +        Fail-Json -obj $result -message "This error $errormsg"
Yes, need to figure out where in the code it's doing -WhatIf twice, because I do not understand it.

2017-07-12 22:36 UTC, dagwieers commented on lib/ansible/modules/windows/win_package.ps1
> +        Fail-Json -obj $result -message "This error $errormsg"
So this code has 2 issues now that I cannot explain:
- It reports a failure on rc=null (even when the task did not appear to have failed
- Somehow Set-TargetResource reports having -WhatIf provided twice (which is not possible).

2017-07-14 03:26 UTC, mattclay commented
CI failure with the same `WhatIf` error as before.

2017-08-06 05:41 UTC, mattclay commented
CI failure in integration tests due to:

```
{
"arguments": null, 
"changed": false, 
"failed": true, 
"msg": "A parameter with the name 'WhatIf' was defined multiple times for the command.", 
"name": "C:\\Program Files\\7z922-x64.msi", 
"path": "C:\\Program Files\\7z922-x64.msi", 
"productid": "{23170F69-40C1-2702-0922-000001000000}", 
"rc": null, 
"restart_required": false
}
```

2017-08-29 01:44 UTC, jborean93 commented
@dagwieers, are you find with me closing this PR now that the win_package rewrite has been merged?

2017-08-29 15:01 UTC, dagwieers commented
Fine by me. Thanks !

2017-08-29 15:01 UTC, closed without merging