Added a `name` to the example block
ansible/ansible pull request #25409
Opened 2017-06-07 00:39 UTC by dflock

##### SUMMARY
Blocks have supported `names` for a while (#18985), but it's not documented anywhere, afaik - so I added here.

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
blocks

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = 
  configured module search path = [u'/usr/local/lib/python2.7/dist-packages/ara/plugins/modules']
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

```

2017-06-07 09:45 UTC, dagwieers requested changes

2017-06-07 09:45 UTC, dagwieers commented on docs/docsite/rst/playbooks_blocks.rst
> +      - name: Install, confugure & start services
Can you fix the type (configure), and use 'and' instead of '&' ?

2017-06-07 18:26 UTC, dflock commented on docs/docsite/rst/playbooks_blocks.rst
> +      - name: Install, confugure & start services
Done!

2017-06-15 08:47 UTC, dharmabumstead approved these changes

2017-07-27 02:20 UTC, dflock commented
Any chance of getting this merged? I made the suggested changes, so I don't think the needs_revision tag is accurate any more.

2017-11-28 04:02 UTC, dharmabumstead commented
Closing due to inactivity. Please feel free to reopen and rebase. Thanks.

2017-11-28 04:02 UTC, closed without merging