[WIP] Add ios_user implementation module
ansible/ansible pull request #25413
Opened 2017-06-07 07:08 UTC by trishnaguha

Signed-off-by: Trishna Guha <trishnaguha17@gmail.com>

##### SUMMARY

- ios_user implementation module
- integration test

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

modules/network/ios/ios_user
##### ANSIBLE VERSION

```
devel 2.4
```

2017-06-07 11:20 UTC, gundalow commented
```
lib/ansible/modules/network/ios/ios_user.py:168:9: E731 do not assign a lambda expression, use a def
lib/ansible/modules/network/ios/ios_user.py:169:9: E731 do not assign a lambda expression, use a def
lib/ansible/modules/network/ios/ios_user.py:170:9: E731 do not assign a lambda expression, use a def
lib/ansible/modules/network/ios/ios_user.py:244:4: E114 indentation is not a multiple of four (comment)
```

2017-06-07 15:09 UTC, ganeshrn commented on lib/ansible/modules/network/ios/ios_user.py
> +from ansible.module_utils.ios import get_config, load_config
for declarative intent modules plan to use cliconf api's
```
from ansible.module_utils.connection import Connection
conn = Connection(module)
conn.get_config()
```

2017-06-08 09:46 UTC, ganeshrn requested changes
for declarative intent modules can use cliconf api's

2017-06-09 08:16 UTC, rcarrillocruz approved these changes

2017-06-09 08:20 UTC, merged

2017-07-15 21:20 UTC, nickrusso42518 commented
If possible, I am requesting an additional option to better secure password hashes.

```
ios_user:
  algorithm: ["md5", "sha256", "scrypt"]
```

These possible text values can be passed directly to the IOS CLI. The default (and weakest) option is MD5 which is what the module currently uses as the result of not specifying anything when the "secret" option is invoked. For those who work in high-security industries, maximum security for device passwords is a requirement.

The CLI syntax would be something like this:

`username admin2 privilege 15 algorithm-type scrypt secret MyPass123`

For module testing, "sha256" and "scrypt" use the digits 8 and 9, respectively, as seen below.

```
username admin1 secret 8 $8$krelHiyqebytyn$mzmwAnfueMwCiFQs96I89rSEENOvAQucSo99kxebfGs
username admin2 privilege 15 secret 9 $9$2VIfYlnbMhf6v9$/J6A7r7hgI7HvUB3Hsf5hiG0Rn7bn.VeY8VtfdRorBg
```

2017-07-16 09:06 UTC, trishnaguha commented
@nickrusso42518 Acknowledged.