##### SUMMARY
ansible/ansible pull request #25527
Opened 2017-06-09 09:30 UTC by rcarrillocruz

##### ISSUE TYPE

 - Feature Pull Request
 - New Module Pull Request
 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME

##### ANSIBLE VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

2017-06-15 10:40 UTC, gundalow submitted a review, later dismissed
Minor code issue. Docs and examples seem good.

What's the plan for tests for this?

2017-06-15 10:40 UTC, gundalow commented on lib/ansible/modules/network/ios/ios_static_route.py
> +        next_hop(required=True, type='str'),
Missing `=dict` on this and the next few lines

2017-06-29 09:13 UTC, trishnaguha requested changes

2017-06-29 09:13 UTC, trishnaguha commented on lib/ansible/modules/network/ios/ios_static_route.py
> +            response = load_config(module, commands)
`load_config` doesn't return anything https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/ios.py#L121

2017-06-29 10:05 UTC, merged