[WIP] Various Undefined variable fixes
ansible/ansible pull request #25572
Opened 2017-06-10 14:01 UTC by sivel

##### SUMMARY

Currently we are ignoring `undefined-variable` in pylint.  We probably shouldn't do this long term.

This is an initial set of fixes that I could perform. There are a few other places where:

1. The code where the undefined var is located isn't used anywhere
1. The code is a bit complicated (double lambda, cascaded var inspection) and I haven't determined the proper outcome
1. There is really no way to make the code work without understanding how it's supposed to work, in the places the code is completely broken now.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
various

##### ANSIBLE VERSION

```
devel
```

##### ADDITIONAL INFORMATION

```

```

2017-06-10 14:46 UTC, sivel commented
@jctanner in `module_utils/vmware.py` there are 2 functions, that aren't used anywhere, and don't have access to the vars they use.  Do you think it's OK, to just remove those functions?

```
ansible/module_utils/vmware.py:385: [E0602(undefined-variable), fetch_file_from_guest] Undefined variable 'fetch_url'
ansible/module_utils/vmware.py:385: [E0602(undefined-variable), fetch_file_from_guest] Undefined variable 'self'
ansible/module_utils/vmware.py:430: [E0602(undefined-variable), push_file_to_guest] Undefined variable 'os'
ansible/module_utils/vmware.py:446: [E0602(undefined-variable), push_file_to_guest] Undefined variable 'fetch_url'
ansible/module_utils/vmware.py:446: [E0602(undefined-variable), push_file_to_guest] Undefined variable 'self'
```

2017-06-10 17:47 UTC, Akasurde commented
@sivel I have a couple fixes for that in this PR #25288

2017-06-12 14:33 UTC, bcoca requested changes

2017-06-12 14:33 UTC, bcoca commented on lib/ansible/modules/cloud/azure/azure.py
> +        raise AzureException("failed to get or delete disk %s, error was: %s" % (disk_name, str(e)))
this is  not a fix, module should always exist gracefully (not in exception) .. the str() should be changed to_native though

2017-06-12 14:39 UTC, bcoca requested changes

2017-06-12 14:39 UTC, bcoca commented on lib/ansible/modules/network/panos/panos_restart.py
> -            module.exit_json(changed=True, msg=str(msg))
str should probably be converted to_native here also 

@abadger

2017-06-12 14:40 UTC, sivel commented on lib/ansible/modules/cloud/azure/azure.py
> +        raise AzureException("failed to get or delete disk %s, error was: %s" % (disk_name, str(e)))
The module later catches this exception already and converts the exception for use with `fail_json`

2017-06-12 14:41 UTC, bcoca requested changes

2017-06-12 14:41 UTC, bcoca commented on lib/ansible/plugins/strategy/debug.py
> -            display.display(pprint.pformat(result))
doesn't this break functionality for debug strategy?

2017-06-12 14:42 UTC, sivel commented on lib/ansible/modules/network/panos/panos_restart.py
> -            module.exit_json(changed=True, msg=str(msg))
I get that.  And I can make these changes.  However my goal here is to do very targeted changes to resolve the undefined errors, not necessarily do py3 compat.

2017-06-12 14:43 UTC, sivel commented on lib/ansible/plugins/strategy/debug.py
> -            display.display(pprint.pformat(result))
No, that var is completely undefined at that point, so this is already broken. I also couldn't find any useful information from the called methods that I could actually return.

2017-06-12 14:49 UTC, sivel commented on lib/ansible/modules/cloud/azure/azure.py
> +        raise AzureException("failed to get or delete disk %s, error was: %s" % (disk_name, str(e)))
https://github.com/sivel/ansible/blob/bd1779292ff1c11bdc7e98c916533bf28be4b00a/lib/ansible/modules/cloud/azure/azure.py#L500

2017-06-16 02:05 UTC, closed without merging