Add new CloudStack module cs_physical_network
ansible/ansible pull request #25647
Opened 2017-06-13 10:23 UTC by netservers

##### SUMMARY

Add a new CloudStack module for adding/updating/removing PhysicalNetworks.

This is part of a set of new modules that will also allow management of:
* TrafficTypes
* Storage IP Ranges
* Primary Storage Pools
* VLAN IP Ranges

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

lib/ansible/modules/cloud/cloudstack/cs_physical_network.py
##### ANSIBLE VERSION

```
ansible 2.4.0
  config file = /home/john/.ansible.cfg
  configured module search path = [u'/home/john/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible-2.4.0-py2.7.egg/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, May 10 2017, 20:04:28) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]

```

##### ADDITIONAL INFORMATION

Sample playbook:

```
---
- name: Setup Cloudstack
  hosts: host1
  tasks:
  - local_action:
      module: cs_physical_network
      name: testnet
      zone: London
      isolation_method: VLAN
      broadcast_domain_range: ZONE
      tag: vlan
      state: present
```

2017-06-14 07:38 UTC, resmo requested changes
Thanks for your works!

I am missing async polling for the apis supporting it. Some parts do not support idempotency, let's verify if this can be added. As I wrote by mail, let's also add some integration tests.

2017-06-14 07:38 UTC, resmo commented on lib/ansible/modules/cloud/cloudstack/cs_physical_network.py
> +                res = self.cs.updatePhysicalNetwork(**args)
The `physcialNetwork` API is an async API, that is why the `poll_async` function should be used (e.g. https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/cloudstack/cs_vpc.py#L334-L336) to query the updated resource and return it to the user.

2017-06-14 07:38 UTC, resmo commented on lib/ansible/modules/cloud/cloudstack/cs_physical_network.py
> +        self.result['changed'] = True
It seems this method does not currently handle idempotency, it always reports changed=true, right? I am not yet fully aware if idempotency can be implemented to only update changed elements and report changed=true in this case.

Do you have more infos about that?

2017-06-14 07:38 UTC, resmo commented on lib/ansible/modules/cloud/cloudstack/cs_physical_network.py
> +        res = self.cs.configureInternalLoadBalancerElement(**args)
this also supports async

2017-06-14 10:48 UTC, netservers commented on lib/ansible/modules/cloud/cloudstack/cs_physical_network.py
> +                res = self.cs.updatePhysicalNetwork(**args)
OK. I think that all async polling is now done correctly.

2017-06-14 10:48 UTC, netservers commented on lib/ansible/modules/cloud/cloudstack/cs_physical_network.py
> +        res = self.cs.configureInternalLoadBalancerElement(**args)
Done.

2017-06-14 10:51 UTC, netservers commented on lib/ansible/modules/cloud/cloudstack/cs_physical_network.py
> +        self.result['changed'] = True
The function as a whole is idempotent, as it begins by checking if the current value matches the desired value and returns early if it does.

2017-06-14 10:57 UTC, resmo commented on lib/ansible/modules/cloud/cloudstack/cs_physical_network.py
> +        self.result['changed'] = True
Okay, I see. (should not look at code before the first coffee)

2017-06-14 11:01 UTC, resmo approved these changes

2017-09-06 21:27 UTC, resmo commented
module still needs integration tests. If the author is not picking it up, I will work on it for ansible 2.5. 

waiting_on_contributor

2018-04-18 07:08 UTC, resmo commented
I am about to close this PR due to too outdated (many interfaces have changed) and the integration tests are still missing. But I am open for discussions. 

I would appreciate a re-submit of this functionality! Let us know when you plan to do to avoid doubled identical work.

2018-08-31 06:19 UTC, resmo commented
close_me

2018-08-31 06:23 UTC, closed without merging