Add new module cs_storage_ip_range
ansible/ansible pull request #25692
Opened 2017-06-14 13:04 UTC by netservers

##### SUMMARY

Add a new CloudStack module for adding/updating/removing Storage IP Ranges.

This is part of a set of new modules that will also allow management of:
- Physical Networks
- TrafficTypes
- Storage IP Ranges
- Primary Storage Pools
- VLAN IP Ranges
- Console SSL Certificates

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

lib/ansible/modules/cloud/cloudstack/cs_storage_ip_range.py
##### ANSIBLE VERSION

```
ansible 2.4.0
  config file = /home/john/.ansible.cfg
  configured module search path = [u'/home/john/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible-2.4.0-py2.7.egg/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, May 10 2017, 20:04:28) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]

```

##### ADDITIONAL INFORMATION

Sample playbook:

```
---
- name: Setup Cloudstack
  hosts: host1
  tasks:
  - name: Create Public VLAN IP Range
    local_action:
      module: cs_storage_ip_range
      pod: Pod01
      ipv4_start: 1.0.0.10
      ipv4_end: 1.0.0.100
      ipv4_netmask: 255.255.255.0
      ipv4_gateway: 1.0.0.1
      vlan: 101
```

2017-06-14 15:16 UTC, gundalow commented
/cc @resmo FYI

2017-06-14 15:16 UTC, resmo commented
waiting for integration tests

2017-06-14 15:46 UTC, resmo requested changes

2017-06-14 15:46 UTC, resmo commented on lib/ansible/modules/cloud/cloudstack/cs_storage_ip_range.py
> +        pod=dict(default=None),
missing required=True here?

2017-06-14 15:46 UTC, resmo commented on lib/ansible/modules/cloud/cloudstack/cs_storage_ip_range.py
> +class AnsibleCloudStackCluster(AnsibleCloudStack):
Would you mind choosing a more accourate name, e.g. AnsibleCloudStackStorageIpRange?

2017-06-14 15:46 UTC, resmo commented on lib/ansible/modules/cloud/cloudstack/cs_storage_ip_range.py
> +        self.module.fail_json(msg="Pod %s not found in zone %s." % (self.module.params.get('pod'), self.get_zone(key='name')))
just a little hint, there is a cloudstack optimized fail_json `self.fail_json` which would also return the zone on failure as return value. But this is fine as well

2017-06-14 15:46 UTC, resmo commented on lib/ansible/modules/cloud/cloudstack/cs_storage_ip_range.py
> +        vlan=dict(default=None),
I would suggest to set `type='int' for vlan.

2017-06-14 15:46 UTC, resmo commented on lib/ansible/modules/cloud/cloudstack/cs_storage_ip_range.py
> +zoneid:
`zone` is returned, but not zoneid

2017-06-14 15:46 UTC, resmo commented on lib/ansible/modules/cloud/cloudstack/cs_storage_ip_range.py
> +podid:
I don't see code returning podid, I usually do not return the ids for the arguments. When you looks at the integration tests, you'll see I compare the return values with the arguments to make sure the API used the same. I see no benefit in returning id for subelements.

2017-06-14 18:42 UTC, netservers commented on lib/ansible/modules/cloud/cloudstack/cs_storage_ip_range.py
> +podid:
I made the mistake of copying down the list of variables the API documentation claims to return. I've now shortened the list to those I actually see returned.

2017-06-14 18:43 UTC, netservers commented on lib/ansible/modules/cloud/cloudstack/cs_storage_ip_range.py
> +zoneid:
Remove

2017-06-14 18:43 UTC, netservers commented on lib/ansible/modules/cloud/cloudstack/cs_storage_ip_range.py
> +class AnsibleCloudStackCluster(AnsibleCloudStack):
Done. Was just copying and pasting. I'll have to review my other modules too.

2017-06-14 18:44 UTC, netservers commented on lib/ansible/modules/cloud/cloudstack/cs_storage_ip_range.py
> +        self.module.fail_json(msg="Pod %s not found in zone %s." % (self.module.params.get('pod'), self.get_zone(key='name')))
OK, I'll try to remember that.

2017-06-14 18:44 UTC, netservers commented on lib/ansible/modules/cloud/cloudstack/cs_storage_ip_range.py
> +        pod=dict(default=None),
Yes. Has now been corrected.

2017-06-15 10:20 UTC, netservers commented on lib/ansible/modules/cloud/cloudstack/cs_storage_ip_range.py
> +        vlan=dict(default=None),
This is also done.

2017-06-16 07:08 UTC, resmo approved these changes

2017-06-16 07:08 UTC, resmo commented
in my queue for testing

2017-09-06 21:16 UTC, resmo commented
module still needs integration tests. If the author is not picking it up, I will work on it for ansible 2.5.

2018-01-17 10:34 UTC, resmo commented
needs_revision

2018-08-31 06:27 UTC, resmo commented
close_me

2018-08-31 06:31 UTC, closed without merging