Implement vmware_argument_spec for required params
ansible/ansible pull request #25731
Opened 2017-06-15 07:29 UTC by Akasurde

##### SUMMARY
Without the fix hostname, username and password params
used to skip required check.

Fixes #25696

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/modules/cloud/vmware/vmware_guest.py

##### ANSIBLE VERSION
```
2.4 devel
```

2017-06-19 16:34 UTC, Akasurde commented
ready_for_review

2017-06-19 19:34 UTC, dagwieers requested changes
For parameters I prefer to add options that are prevalent, over options that are optional, or have implicit values, or are seldom added. So I prefer to use the following order: `type`, `required`, `default`, `choices`, `aliases`, `no_log` . (`required` is a second, because it is also more important and mutual exclusive with `default`)

2017-06-19 19:34 UTC, dagwieers commented on lib/ansible/modules/cloud/vmware/vmware_guest_find.py
> +        uuid=dict(required=False, type='str'),
Please do not add  `required=False`, it is implicit.

2017-06-19 19:34 UTC, dagwieers commented on lib/ansible/modules/cloud/vmware/vmware_guest_facts.py
> +        name_match=dict(required=False, type='str', default='first'),
Please remove `required=False`.

2017-06-19 19:34 UTC, dagwieers commented on lib/ansible/modules/cloud/vmware/vmware_guest_facts.py
> +        uuid=dict(required=False, type='str'),
Please remove `required=False`.

2017-06-19 19:34 UTC, dagwieers commented on lib/ansible/modules/cloud/vmware/vmware_guest_facts.py
> +        folder=dict(required=False, type='str', default='/vm'),
Please remove `required=False`.

2017-06-19 19:34 UTC, dagwieers commented on lib/ansible/modules/cloud/vmware/vmware_guest_snapshot.py
> +            required=False,
Please remove `required=False`.

2017-06-19 19:34 UTC, dagwieers commented on lib/ansible/modules/cloud/vmware/vmware_guest_snapshot.py
> +        name_match=dict(required=False, type='str', default='first'),
Please remove `required=False`.

2017-06-19 19:34 UTC, dagwieers commented on lib/ansible/modules/cloud/vmware/vmware_guest_snapshot.py
> +        uuid=dict(required=False, type='str'),
Please remove `required=False`.

2017-06-19 19:34 UTC, dagwieers commented on lib/ansible/modules/cloud/vmware/vmware_guest_snapshot.py
> +        folder=dict(required=False, type='str', default='/vm'),
Please remove `required=False`.

2017-06-19 19:34 UTC, dagwieers commented on lib/ansible/modules/cloud/vmware/vmware_guest_snapshot.py
> +        snapshot_name=dict(required=False, type='str'),
Please remove `required=False`.

2017-06-19 19:34 UTC, dagwieers commented on lib/ansible/modules/cloud/vmware/vmware_guest_snapshot.py
> +        description=dict(required=False, type='str', default=''),
Please remove `required=False`.

2017-06-20 02:16 UTC, Akasurde commented
@dagwieers Done.

2017-06-26 12:57 UTC, Akasurde commented
ready_for_review

2017-06-28 04:48 UTC, mattclay commented
CI failure in integration test `test/integration/targets/vmware_guest_find/tasks/main.yml:35 / [testhost] testhost: vmware_guest_find : find folders for each vm username={{ vcsim_instance['json']['username'] }}, datacenter={{ (item|basename).split('_')[0] }}, hostname={{ vcsim }}, name={{ item|basename }}, password={{ vcsim_instance['json']['password'] }}, validate_certs=False`:

```
{
"changed": false, 
"failed": true, 
"msg": "All items completed"
}
```

2017-06-28 05:51 UTC, Akasurde commented
Failures in last CI run are not related to the change. Closing and re-opening for CI.

2017-06-28 11:35 UTC, Akasurde commented
ready_for_review

2017-07-03 17:40 UTC, jctanner commented
@Akasurde this needs a rebase after the previous merge on vmware_guest_snapshot

2017-07-14 17:30 UTC, Akasurde commented
@jctanner ready_for_review

2017-07-21 16:12 UTC, merged

2017-07-21 16:14 UTC, Akasurde commented
@jctanner @dagwieers @mattclay Thanks for review and comments.