optionally show failure on changes with junit report
ansible/ansible pull request #25752
Opened 2017-06-15 15:00 UTC by hogarthj

##### SUMMARY
This commit provides an environment option to change the behaviour so
that it's possible to declare any changes shoudl be considered a junit
failure.

This is useful when carrying out idempotent testing to ensure that
multiple runs are safe and any changes should be considered a test
failure.

In a CI test of an ansible role the practice would be to run the role
once without this to configure the test system, and tehn to run a second
time including this environment vairable so that the CI engine
processing the junit report recognise any changes to be a test fail.

Fixes #25740 

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
junit

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, May 31 2017, 17:58:17) [GCC 7.1.1 20170503 (Red Hat 7.1.1-1)]
```

##### ADDITIONAL INFORMATION
This worked with a test in our environment.

The idempotent test that we only consider valid if there are no changes or failures reported showed a junit test failure when I force a task to always report changed and the junit report screen pinpointed precisely which task was reporting changed.

![screenshot from 2017-06-15 15-55-07](https://user-images.githubusercontent.com/3037132/27187567-7d17a070-51e3-11e7-9573-aa3e450b4ea7.png)

2017-08-02 11:54 UTC, hogarthj commented
@mattclay @gundalow just saw this needed a rebase ... I'd really like to see this in 2.4 as I'd find it extremely useful. Would you please take a look?

2017-08-02 13:58 UTC, gundalow commented
@hogarthj Sure, looks sensible. Could you please rebase then we can review & merge

2017-08-02 15:01 UTC, hogarthj commented
@gundalow I did rebase this morning ... not sure why ansibot missed that ... maybe this will poke it

ready_for_review

2017-08-04 13:49 UTC, hogarthj commented
@mattclay @gundalow there ansibot just needed a little poke :)

2017-08-04 17:49 UTC, mattclay requested changes

2017-08-04 17:49 UTC, mattclay commented on lib/ansible/plugins/callback/junit.py
> +            self._finish_task('ok', result)
Any logic for handling `changed` should be in `_finish_task` instead of here.

2017-08-04 17:49 UTC, mattclay commented on lib/ansible/plugins/callback/junit.py
> +        if self._fail_on_change == 'true' and status == 'changed':
This should be:

```python
if self._fail_on_change == 'true' and status == 'ok' and result._result.get('changed', False):
```

2017-08-04 20:35 UTC, hogarthj commented
Thanks @mattclay for taking a look. I modelled the changes after the [dense plugin](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/callback/dense.py#L405) for consistency but indeed the code would work either way round so I'll flip it to your preference.

I'm curious as to why you prefer it that way though?

2017-08-04 20:51 UTC, mattclay commented
@hogarthj The original logic added a `changed` status, but only part of the code was updated to handle that status. The easiest way to fix it was to eliminate the new status.

2017-08-04 20:52 UTC, mattclay approved these changes

2017-08-04 20:57 UTC, hogarthj commented
@mattclay there was only one place I saw that used that and it changed it from changed to ok or failed as appropriate before it passed it on ... but I see the logic in not having a very transient status like that. 

Thanks for the review... though I moved on from my last role I'm sure they will be able to use this with the team remaining and I'll definitely be making use of this functionality in the next ansible CI pipelines I'll be building in my next role :)

2017-08-09 20:39 UTC, abadger commented
Merged to devel as:

* https://github.com/ansible/ansible/commit/fc274bda8a8d416517a92c48cb38076cb5013d97
* https://github.com/ansible/ansible/commit/7ec34b4cb28bca4d4c6af1ac0abea351c167be54

Thanks for working on this!

2017-08-09 20:39 UTC, closed without merging