Fixes #25781: add playbook runtime stat in the logstash callback stats
ansible/ansible pull request #25785
Opened 2017-06-16 09:11 UTC by rrey

##### SUMMARY
Add the playbook runtime statistic in the logstash plugin statistics.
The playbook runtime computation is based on the timer callback implementation.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
lib/ansible/plugins/callback/logstash.py

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config_file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
```

##### ADDITIONAL INFORMATION
With this patch the event sent to logstash will contain a new field called "ansible_playbook_duration" containing the duration in seconds (float).

2017-06-16 11:22 UTC, jctanner commented
cc @ujenmr

2017-08-07 18:13 UTC, samdoran requested changes

2017-08-07 18:13 UTC, samdoran commented on lib/ansible/plugins/callback/logstash.py
> +        self.start_time = datetime.now()
It would be better to use `datetime.utcnow()`to account for changes in daylight savings time that could happen during a job run.

2017-08-08 08:21 UTC, rrey commented on lib/ansible/plugins/callback/logstash.py
> +        self.start_time = datetime.now()
Hi @samdoran ,

Just applied your comment. 

Thanks for the feedback.

2017-08-10 17:38 UTC, samdoran approved these changes

2017-08-10 17:43 UTC, merged