nmcli: do not run cmd twice, it's already run by calling function
ansible/ansible pull request #25818
Opened 2017-06-17 08:19 UTC by krzysztof-magosa

##### SUMMARY
Fixes bug #20925. For unknown reason function generating command was running it and returning program output as command to run instead of simply returning built command.  

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
nmcli

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = /opt/km-ansible/ansible.cfg
  configured module search path = ['extensions/library']
```

2017-06-18 01:53 UTC, ianaharding approved these changes
Worked for me!  Tested in my environment and succeeded the first time.

2017-06-19 10:53 UTC, gundalow commented
@ianaharding Thanks for the review
@mliker  Does this resolve the issue for you?

2017-06-21 09:59 UTC, mliker commented
@gundalow This patch fixes the issue for me as the task with a nmcli module does not throw errors anymore. Thanks for the fix @krzysztof-magosa

2017-08-30 18:36 UTC, bcoca requested changes

2017-08-30 18:36 UTC, bcoca commented on lib/ansible/modules/net_tools/nmcli.py
> +        return cmd
this change breaks the pattern of other methods like down_connection (1/2 of the methods are constructors the other 1/2 executors) so i would change the caller instead.

2017-08-30 18:39 UTC, abadger commented
@krzysztof-magosa We took a look at this today and think that this should be a change to ```create_connection()``` instead.  ```create_connection()``` calls ```up_connection()```  several times and expects that a string is returned.  Instead, we think that it should expect that the command will be executed inside of ```up_connection()```.  This would leave symmetry between ```up_connection()``` and ```down_connection()```. 

So, for instance, this section of code: https://github.com/krzysztof-magosa/ansible/blob/fee42cac92c803bd3d1220949577828958a56d92/lib/ansible/modules/net_tools/nmcli.py#L1023  
will change like so:
``` python
- cmd=self.up_connection()
- return self.execute_command(cmd)
+ return self.up_connection()
```

2017-10-10 22:35 UTC, dlspano commented
@bcoca and @abadger I am also directly affected by this bug. I haven't seen a resolution in a while, so I created this PR here that addreses the concerns you have above. https://github.com/ansible/ansible/pull/31550

2017-12-27 11:52 UTC, Akasurde commented
@krzysztof-magosa Are you still working on this PR ?

2018-01-27 02:58 UTC, Akasurde commented
superseded by https://github.com/ansible/ansible/pull/34261

@krzysztof-magosa Thanks for your interest and valuable contribution in Ansible.

2018-01-27 02:58 UTC, closed without merging