change print to pprint in inventory/digital_ocean.py
ansible/ansible pull request #25830
Opened 2017-06-17 17:55 UTC by loqutus

##### SUMMARY

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

##### ANSIBLE VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

2017-06-19 20:17 UTC, alikins requested changes

2017-06-19 20:17 UTC, alikins commented on contrib/inventory/digital_ocean.py
> +            pprint(json.dumps(json_data, sort_keys=True))
Why?

2017-06-19 20:32 UTC, bcoca requested changes
-1, there does not seem to be a good reason for these changes

2017-11-30 05:52 UTC, BondAnthony commented
wontfix

Today the inventory script will print the raw json object and a nicely 2 indented json document. Adding this change actually defeats the purpose of `--pretty`. This will respond with the raw unformatted json response.

2017-11-30 05:56 UTC, closed without merging