Add external-dir argument for facter module (Issue #25839)
ansible/ansible pull request #25840
Opened 2017-06-18 02:59 UTC by mithmatt

2018-04-23 09:58 UTC, Akasurde commented
@mithmatt Could you please rebase this PR ?

2019-02-23 16:10 UTC, Akasurde commented
@mithmatt Are you still working on this ? Thanks.

2019-02-24 05:08 UTC, mithmatt commented
@Akasurde I have rebased off of devel

2019-02-24 15:05 UTC, Akasurde requested changes

2019-02-24 15:05 UTC, Akasurde commented on lib/ansible/modules/system/facter.py
> +            external_dir = dict(required=False, type='str')
`facter` accepts multiple `external_dir` at a time. So we can make this is as a `list` rather than `str`.

2019-02-24 15:05 UTC, Akasurde commented on lib/ansible/modules/system/facter.py
> +            external_dir = dict(required=False, type='str')
Also, add documentation for this new parameter.

2020-08-17 03:05 UTC, closed without merging