Add junos_system declartive module and other related change
ansible/ansible pull request #25859
Opened 2017-06-19 10:10 UTC by ganeshrn

##### SUMMARY

*  junos_system declartive module
*  integration test for junos_system
*  integration test for net_system (junos platform)
*  pep8 fixes for junos modules
*  move to lxml from elementree for xml parsing as it support
   complete set of xpath api's
*  other minor changes

##### ISSUE TYPE

 - Feature Pull Request
 - Docs Pull Request

##### COMPONENT NAME

junos_system
junos_command
junos_config
junos_package
junos_rpc
junos_user
junos_vlan
junos_interface

##### ANSIBLE VERSION

```
2.4
```

##### ADDITIONAL INFORMATION

```

```

2017-06-19 14:54 UTC, gundalow commented
Unit tests are failing as lxml isn't installed

2017-06-21 14:11 UTC, Qalthos requested changes

2017-06-21 14:11 UTC, Qalthos commented on lib/ansible/module_utils/junos.py
> +    from xml.etree.ElementTree import SubElement, fromstring, tostring
You appear to have dropped `Element`

2017-06-21 14:11 UTC, Qalthos commented on lib/ansible/module_utils/netconf.py
> +    from xml.etree.ElementTree import SubElement, fromstring, tostring
Again, no `Element` here?

2017-06-21 15:08 UTC, ganeshrn commented on lib/ansible/module_utils/junos.py
> +    from xml.etree.ElementTree import SubElement, fromstring, tostring
Fixed

2017-06-21 15:08 UTC, Qalthos approved these changes

2017-06-21 15:08 UTC, ganeshrn commented on lib/ansible/module_utils/netconf.py
> +    from xml.etree.ElementTree import SubElement, fromstring, tostring
Fixed

2017-06-21 15:10 UTC, ganeshrn commented
@Qalthos Thank you for review

2017-06-22 04:04 UTC, merged