New module: database and key management for ManageIQ (monitoring/manageiq/manageiq_{database,key})
ansible/ansible pull request #25865
Opened 2017-06-19 13:03 UTC by abraverm

##### SUMMARY
ManageIQ is an open source management platform for Hybrid IT.

This change is adding:
- manageiq_database - database setting of newly deployed ManageIQ appliance
- manageiq_key - security key creation
- manageiq modules integration tests

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
manageiq_database
manageiq_key

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel 2220362a5f)
```

##### ADDITIONAL INFORMATION
Extending the PR #25106
Depends on PR https://github.com/ManageIQ/manageiq/pull/15396

2017-06-19 13:27 UTC, cben commented on test/integration/manageiq_service/aliases
> +posix/ci/cloud/managqiq
typo s/gq/ge/

2017-06-19 15:41 UTC, gundalow requested changes

2017-06-19 15:41 UTC, gundalow commented on lib/ansible/modules/remote_management/manageiq/manageiq_key.py
> +    - create and import encryption key using the appliance_console_cli
`Create and import encryption key using the appliance_console_cli on ManageIQ`

2017-06-19 15:41 UTC, gundalow commented on lib/ansible/modules/remote_management/manageiq/manageiq_key.py
> +        description: to fetch or not encryption key
All `descriptions` should be full sentences, eg with capital letters and full stops.

2017-06-19 15:41 UTC, gundalow commented on test/integration/manageiq_service/meta/main.yml
> +---
These files should be in the `targets` directory if they can be run via our CI,

`test/integration/targets/manageiq_service/`

2017-06-19 15:41 UTC, gundalow commented on test/integration/manageiq_service/tasks/main.yml
> +# Test 2 - External database
Please add a blank line before each test, it will increase readability

2017-06-19 15:41 UTC, gundalow commented on test/integration/manageiq_service/tasks/main.yml
> +    TERM: xterm
Why is this needed? Please add a note

2017-06-20 15:22 UTC, abraverm commented
The Shippable tests fail on the last two tests (  TEST=cloud/ubuntu1604  and TEST=cloud/ubuntu1604py3 ) : "to use the 'ssh' connection type with passwords, you must install the sshpass program"
I did add sshpass to ubuntu1604 Dockerfile but looks like Shippable doesn't rebuild the image based on those changes. What to do ?

2017-06-21 18:57 UTC, mattclay commented
@abraverm Please submit a separate PR (and reference this one) to add sshpass to the docker images. Once that's merged I can rebuild the docker images and re-run CI on this PR.

2017-06-29 18:54 UTC, mattclay commented
CI is now failing on integration tests:

```
2017-06-29 18:06:47 Failed to get D-Bus connection: Operation not permitted
2017-06-29 18:06:47 ERROR: Command "docker exec manageiq_master /usr/bin/systemctl stop appliance-initialize evmserverd evminit evm-watchdog miqvmstat miqtop" returned exit status 1.
```

2017-06-29 19:10 UTC, abraverm commented
The CI fails because mangeiq need also to change their dockerfile: https://github.com/ManageIQ/manageiq/pull/15396

2017-06-29 19:15 UTC, mattclay commented
@abraverm It looks like the manageiq modules are intended to run directly on the manageiq system over ssh instead of using an API. Is there no API for manageiq, or is it not capable of supporting the desired operations?

2017-06-29 19:33 UTC, mattclay commented
Now that I've looked at more than just the tests, it seems like the modules should be roles hosted on https://galaxy.ansible.com/ instead, since they're only a wrapper around a third-party CLI tool.

@abraverm Have you considered implementing these as roles instead?

2017-06-30 07:57 UTC, abraverm commented
@mattclay, my first implementation for this were roles. The reason that I've rewritten  it in module, was that the role started to look more like a module rather than a common list of tasks that can be shared by playbooks. That is they had too much logic (conditions) if it was in a single role, or too many simple roles that didn't feel like helping enough. Also looking at my playbooks for scaling manageIQ deployment, they started to look like they have common case that can be simplified in to a role. The two cases that I'm handling in this commit are just a start for other parts I thought to modularize.

Thanks,
Alex

2017-07-02 10:01 UTC, abraverm commented
> It looks like the manageiq modules are intended to run directly on the manageiq system over ssh instead of using an API. Is there no API for manageiq, or is it not capable of supporting the desired operations?

ManageIQ has API for when the system is running, but to initialize a deployment or a node to cluster you only have the CLI tool.

2017-07-03 08:22 UTC, abraverm commented
@mattclay, fixed shippable CI tests. Is there anything else need to be done for this commit?

2017-07-09 08:41 UTC, abraverm commented
Hi @gundalow , I addressed the issues you pointed out, is there anything else need to be done?

2017-07-20 16:37 UTC, abraverm commented
Hi @gtanzillo can you take a look at this PR?

2017-07-20 18:02 UTC, bcoca commented
-1 on this for several reasons, mostly for ignoring the guildelines http://docs.ansible.com/ansible/latest/dev_guide/developing_modules_checklist.html
For example:
  * multiple modules submitted in single request, ignoring our guidelines 
  *  modules are thing wrappers to cli tool with very little added value, no change management, status reporting nor validation
  * cli tools are assumed in path (should be using find_bin)
  * catchall error reporting ... really not user friendly

... there is probably more but I stopped at this point as it seems this requires a rereading of the guidelines.

2017-08-23 17:55 UTC, gtanzillo approved these changes
Looks good to me 👍 . Just had the suggestion about the default region number being 0

2017-08-23 17:55 UTC, gtanzillo commented on lib/ansible/modules/remote_management/manageiq/manageiq_database.py
> +            region=dict(default=1, type='int'),
I think it would be better if the default region number is 0

2017-08-24 07:44 UTC, abraverm commented on lib/ansible/modules/remote_management/manageiq/manageiq_database.py
> +            region=dict(default=1, type='int'),
Thanks! I will fix that  and address @bcoca comments.

2017-09-05 15:33 UTC, abraverm commented
Hi @bcoca, thank you for your time, can you please review my last update?

2017-09-11 10:37 UTC, abraverm commented
ping

2017-09-11 12:43 UTC, cben commented on lib/ansible/modules/remote_management/manageiq/manageiq_database.py
> +        description: ManageIQ region the database assosieted with.
typo associated

2017-09-11 12:47 UTC, cben commented on lib/ansible/modules/remote_management/manageiq/manageiq_database.py
> +        description: When removing database, the files are removed too.
Not exactly a description of this param.  Is this stating a fact, and the param just sets the path?  Or can you inhibit this behavior by unsetting this?

2017-09-11 12:49 UTC, cben commented on lib/ansible/modules/remote_management/manageiq/manageiq_database.py
> +        state=dict(default='internal', type='str'),
Doc describes `intenal`, no `state`

2017-09-11 12:56 UTC, cben commented on lib/ansible/modules/remote_management/manageiq/manageiq_database.py
> +        # http://talk.manageiq.org/t/setup-region-join-region-in-darga/1654/6
Please explain this in doc.

2020-08-19 09:03 UTC, Akasurde commented
Please submit a new module request to https://github.com/ansible-collections/community.general. Thanks for your contribution.

2020-08-19 09:03 UTC, closed without merging