win_iis_website: Add integration tests, check mode and better param support
ansible/ansible pull request #25902
Opened 2017-06-20 11:40 UTC by jborean93

##### SUMMARY
Brings the following to win_iis_website

* check mode
* integration tests
* better handling of attributes
* better idempotency checks
* updated documentation
* more return values
* deprecations to parameters that shouldn't be used

##### ISSUE TYPE
 - Feature Pull Request
 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME
win_iis_website

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel e08f068dca) last updated 2017/06/20 07:00:17 (GMT +1100)
  config file = None
  configured module search path = [u'/home/jordan/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /mnt/c/dev/linux-ansible/lib/ansible
  executable location = /mnt/c/dev/linux-ansible/bin/ansible
  python version = 2.7.13 (default, Jun 18 2017, 20:35:39) [GCC 5.4.0 20160609]
```

##### ADDITIONAL INFORMATION
In lieu with the changes to win_iis_webapppool, this will continue to align the win_iis_* modules and fix bugs that have been reported and make them easier to use.

2017-06-20 14:32 UTC, jctanner commented
cc @nitzmahone

2017-06-28 21:10 UTC, nitzmahone requested changes

2017-06-28 21:10 UTC, nitzmahone commented on test/integration/targets/win_iis_website/tasks/main.yml
> +  - name: this is too finicky reboot before feature install
Probably better to call setup and check the `ansible_reboot_pending` fact rather than blindly rebooting

2017-06-28 21:10 UTC, nitzmahone commented on test/integration/targets/win_iis_website/tasks/main.yml
> +      includ_sub_features: True
s/includ_/include_/ - I can't wait for declarative argspec to catch this kind of thing automatically. :)

IIRC including Web-Server and all subfeatures fails on some OS's (problem with the underlying cmdlet).

2017-06-28 21:10 UTC, nitzmahone commented on test/integration/targets/win_iis_website/tasks/main.yml
> +  win_command: powershell.exe "Get-WindowsFeature"
FYI: `raw: Get-WindowsFeature` is faster

2017-06-28 21:10 UTC, nitzmahone commented on test/integration/targets/win_iis_website/tasks/tests.yml
> +  failed_when: "create_fail_invalid_path.msg != 'physical_path is not a valid path: T:\\\\fakepath'"
The outer expression shouldn't need quotes, so theoretically shouldn't need to escape the path on the inner one?

2017-06-28 21:10 UTC, nitzmahone commented on lib/ansible/modules/windows/win_iis_website.ps1
> +if ((Get-Module "WebAdministration" -ErrorAction SilentlyContinue) -eq $null) {
Should we have a failure case on this?

2017-06-28 21:10 UTC, nitzmahone commented on lib/ansible/modules/windows/win_iis_website.ps1
> +    Add-DeprecationWarning -obj $result -message "port is deprecated, use win_iis_webbinding to modify a site bindings" -version 2.6
s/modify a site/modify site/ (and other instances below)

2017-06-28 21:10 UTC, nitzmahone commented on lib/ansible/modules/windows/win_iis_website.ps1
> +        Add-Warning -obj $result -message "Both the parameters (deprecated) and attributes parameter is set, ignoring parameters"
s/attributes parameter/attributes arguments/ (heh, how many synonyms for parameters can we use in the same sentence ;) )

2017-06-28 21:10 UTC, nitzmahone commented on lib/ansible/modules/windows/win_iis_website.ps1
> +        Add-DeprecationWarning -obj $result -message "The parameter parameters is deprecated, use attributes with a dict value" -version 2.6
s/parameter parameters/parameters argument/

2017-06-28 21:10 UTC, nitzmahone commented on lib/ansible/modules/windows/win_iis_website.ps1
> +$elements = @("attributes", "limits", "logFile", "traceFailedRequestsLogging", "applicationDefaults", "virtualDirectoryDefaults")
For new module stuff, we usually try to use snake-case everywhere in the args and return values (eg `log_file`, `trace_failed_requests_logging`) just for a consistent UI look/feel across modules.

2017-06-28 21:10 UTC, nitzmahone commented on lib/ansible/modules/windows/win_iis_website.py
> +        not match a site.
sentence fragment hanging off the end here...

2017-06-28 21:10 UTC, nitzmahone commented on lib/ansible/modules/windows/win_iis_website.py
> +      - If the site ID does not match then the site will be deleted and
suggest: `will be deleted (by name) and`

2017-06-28 21:22 UTC, jborean93 commented on test/integration/targets/win_iis_website/tasks/main.yml
> +      includ_sub_features: True
Well if this is working without this actually there I don't see a reason why we need all sub features

2017-06-28 21:23 UTC, jborean93 commented on test/integration/targets/win_iis_website/tasks/main.yml
> +  win_command: powershell.exe "Get-WindowsFeature"
Here I was thinking raw was a no no, will swap over.

2017-06-28 21:23 UTC, jborean93 commented on test/integration/targets/win_iis_website/tasks/main.yml
> +  - name: this is too finicky reboot before feature install
Didn't know that was there, will do that

2017-06-28 21:23 UTC, jborean93 commented on test/integration/targets/win_iis_website/tasks/tests.yml
> +  failed_when: "create_fail_invalid_path.msg != 'physical_path is not a valid path: T:\\\\fakepath'"
I'll give it a try, I believe I've come across issues with the `:` in the middle but I don't see how it is an actual issue.

2017-06-28 21:24 UTC, jborean93 commented on lib/ansible/modules/windows/win_iis_website.ps1
> +        Add-Warning -obj $result -message "Both the parameters (deprecated) and attributes parameter is set, ignoring parameters"
It was confusing when writting it.

2018-05-14 12:17 UTC, dagwieers commented
Beware that the deadline for getting new features/modules accepted in [Ansible v2.6](https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/roadmap/ROADMAP_2_6.rst#release-schedule) is nearing, it is set to either 2018-05-17 or 2018-05-25. If you are blocked, or you need feedback, please discuss on IRC channel #ansible-windows or add a comment to [the Windows Working Group meeting agenda](https://github.com/ansible/community/issues/294) to get it resolved.

2018-08-16 09:52 UTC, dagwieers commented
Beware that the deadline for getting new features/modules accepted in [Ansible v2.7 is nearing](https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/roadmap/ROADMAP_2_7.rst#release-schedule), it is set to either 2018-08-23 or 2018-08-30. If you are blocked, or you need feedback, please discuss on IRC channel #ansible-windows or add a comment to the [Windows Working Group meeting agenda](https://github.com/ansible/community/issues/294) to get it resolved.

2019-04-11 15:08 UTC, mhunsber commented
Are there any plans to do more work on either this pr or the win_iis_website module? I have seen some comments about not wanting to take on more iis modules, does that mean less support for the existing iis modules as well?

2019-04-11 19:33 UTC, jborean93 commented
@mhunsber I was working on this, and other IIS modules, at the time but had to put it aside for other issues that had more priority. I never got back to this but you are more than welcome to try and take on the changes here and push it further. Apart from 2 that I know of, the rest of the IIS modules don't have an active maintainer so they sort of just sit there. Our usually stance is to try the [xWebAdministration](https://github.com/PowerShell/xWebAdministration) DSC module through `win_dsc` if they've come across a bug.

> I have seen some comments about not wanting to take on more iis modules, does that mean less support for the existing iis modules as well?

That's mostly around we don't have any active maintainers for IIS and due to the various issues with existing IIS modules we've had over the years we didn't want to end up in the same situation for those. We've just conveniently added collections to Ansible 2.8 which should allow people to more easily package up their own modules outside of Ansible.

2019-11-12 23:42 UTC, closed without merging