Add support for direct http template uploading.
ansible/ansible pull request #25919
Opened 2017-06-20 17:39 UTC by netservers

##### SUMMARY

This is a new feature that allows direct http uploading of CloudStack templates.

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

lib/ansible/modules/cloud/cloudstack/cs_template.py
##### ANSIBLE VERSION

```
ansible 2.4.0
  config file = /home/john/.ansible.cfg
  configured module search path = [u'/home/john/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible-2.4.0-py2.7.egg/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, May 10 2017, 20:04:28) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```

##### ADDITIONAL INFORMATION

As an alternative to specifying *url* or *vm*, specify a *file*, which is a path to a local template.

Sample playbook:
```
---
- name: Upload Templates
  hosts: host1
  tasks:
  - local_action:
      module: cs_template
      name: "{{ item.name }}"
      display_text: "{{ item.name }}"
      file: "{{ item.file }}"
      zone: London
      hypervisor: KVM
      format: QCOW2
      is_featured: no
      is_public: yes
      is_extractable: yes
      sshkey_enabled: no
      password_enabled: no
      requires_hvm: yes
      os_type: "{{ item.type }}"
    with_items:
    - { type: "Other 2.6x Linux (32-bit)", name: "OpenWRT", file: "openwrt-x86-kvm_guest-combined-ext4.qcow2" }
```

2017-06-21 09:27 UTC, resmo requested changes
some minor changes, lgtm overall. Needs manual testing.

(this module is on my list for adding integration testing)

2017-06-21 09:27 UTC, resmo commented on lib/ansible/modules/cloud/cloudstack/cs_template.py
> +import requests
please make a comment here that is okay here to depend on requests since this module depends on cs which depends on requests.

2017-06-21 09:27 UTC, resmo commented on lib/ansible/modules/cloud/cloudstack/cs_template.py
> +            args                    = self._get_args()
this module is marked as "legacy" and therefore the CI is not complaining about pep8 here, but it would help if we try to be pep8 compliant.

2017-06-21 09:38 UTC, netservers commented on lib/ansible/modules/cloud/cloudstack/cs_template.py
> +            args                    = self._get_args()
I think it would look weird if I only pep8 that one line. I'll pep8 the whole block.

2017-06-21 09:40 UTC, resmo commented on lib/ansible/modules/cloud/cloudstack/cs_template.py
> +            args                    = self._get_args()
yep, that is what I meant, basically make sure new code is pep8 compliant

2017-06-21 09:41 UTC, netservers commented on lib/ansible/modules/cloud/cloudstack/cs_template.py
> +import requests
Please see my last push that crossed with your comment. During testing it became clear that requests alone is not sufficient. I've followed a pattern I saw in the aws_api_gateway module for not imposing the dependency on those that don't use the new functionality.

2018-10-30 09:00 UTC, rhtyd commented
@netservers please fix the conflict

2019-09-19 12:29 UTC, gundalow commented
@netservers 
Thank you for your PR.
As part of reviewing the backlog of PRs we are looking at PRs older PRs that haven't been updated in a while

Given that:
* PR has needed a rebase since Oct 2017
* This is a feature rather than a bug fix

Therefore I'm going to close this.

If you or anyone else wants to continue with this work then please do feel free to create a fresh PR and `@mention` the previous reviewers in here.

@rhtyd If you are interested in this perhaps you could raise a fresh PR?

2019-09-19 12:29 UTC, closed without merging