Allow setting hash merging per hash
ansible/ansible pull request #25948
Opened 2017-06-21 10:41 UTC by puiterwijk

##### SUMMARY
This allows using the "merge" hash behavior for specific hashes.
This way, it is possible to have the base system operate with the default "replace" behavior, so as to not break e.g. roles/playbooks or assumptions, while still being able to take advantage of hash merging when it's useful.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME

utils/vars

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/srv/web/infra/ansible/library', u'/usr/share/ansible']
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

##### ADDITIONAL INFORMATION
This PR allows people to add !merge or !replace to a hash, and that will override the system-wide default hash behavior.

2017-06-21 11:10 UTC, puiterwijk commented
/cc @bcoca @jimi-c

2017-06-22 08:14 UTC, puiterwijk commented
This replaces #24160

2017-06-27 19:20 UTC, bcoca requested changes

2017-06-27 19:20 UTC, bcoca commented on lib/ansible/parsing/yaml/objects.py
> +        self.mergereplace = kwargs.pop('__mergereplace__', None)
I think we are fine with having the property and can do w/o the 'special dict key' which would show in the user's dict definition

2017-06-27 19:23 UTC, bcoca commented
discussed in core meeting,  most agree with this but would like more docs/examples/changelog

2019-01-03 15:31 UTC, lucastheisen commented
This would likely solve [my problem](#49992), as its real goal is to be able to conditionally merge vars/vaults files.

2019-01-03 16:29 UTC, pilou- commented
Some [context](https://meetbot.fedoraproject.org/ansible-meeting/2019-01-03/ansible_core_public_irc_meeting.2019-01-03-15.00.log.html#l-42):
```
15:18:20 <Pilou> it seems the only missing bits from #25948 are doc and changelog
15:18:34 <bcoca> Pilou: no, biggest issue is json encoding/decoding
15:23:31 <bcoca> https://github.com/ansible/ansible/issues/47295 <= this shows the json issue, we need to be able to represent any 'yaml object' in a way that it passes json boundries, since we use those internally in some systems
15:28:13 <bcoca> i have the json issue on my list, once solved for unsafe we can do same for ansiblemapping and then deal with !merge !replace handlers
```

2019-07-22 15:08 UTC, Vladimir-csp commented
I'll repeat my message from #22559, as it would be more on topic here:

Using yaml tags to explicitly control merging/replacing data would eliminate SO MANY hurdles and monstrous workarounds! This feature is in "must have" category.

Please also add this for lists to effectively enable deep merge.
Maybe including set filters: `!union`, `!difference`, `!intersect`, `!append`, `!insert` (at beginning), `!replace`
This would remove the need for a heap of conditions, inline filters, clumsy generators, extra intermediate variables, etc, etc...

2019-07-22 22:25 UTC, bcoca commented
@Vladimir-csp  except most of the merging happens well after the YAML is loaded, it is not as simple as defining a tag and doing the merge on import (yaml importer has no access to other vars). Doing it this way requires a lot of redesign of the internals.

2019-07-29 12:31 UTC, Vladimir-csp commented
> @Vladimir-csp except most of the merging happens well after the YAML is loaded, it is not as simple as defining a tag and doing the merge on import (yaml importer has no access to other vars). Doing it this way requires a lot of redesign of the internals.

Is it possible to make this construct not going into recursive loop?:
```
some_list: "{{ some_list | union(['new item']) }}"
```

2019-07-30 17:59 UTC, bcoca commented
not really, since we pass it to jinja as `"{{ some_list | union(['new item']) }}"` and then the `varialbes` passed to Jinja to be used as source data for the template, we also pass `variables['some_list']="{{ some_list | union(['new item']) }}"` so when it looks up the variable to resolve the token `some_list` it gets it's own template. I'm not sure how that would be avoided.

2020-11-20 15:34 UTC, samdoran commented
This will not work fully. The best solution is to use [the combine filter](https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#combining-and-selecting-data).

To discuss this further, please reach out on IRC or the mailing list:

   * IRC: #ansible-devel on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-devel

2020-11-20 15:34 UTC, closed without merging