windows: Two simple errors using Add-Warning
ansible/ansible pull request #25955
Opened 2017-06-21 11:06 UTC by dagwieers

##### SUMMARY
I noticed these before, finally nailed them...

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

win_regedit and win_lineinfile

##### ANSIBLE VERSION

v2.4

2017-06-25 19:28 UTC, dagwieers commented
@nitzmahone @jborean93 @jhawkesworth Easy one to merge.

2017-06-26 22:52 UTC, jborean93 requested changes
Just 2 minor things to change.

2017-06-26 22:52 UTC, jborean93 commented on lib/ansible/modules/windows/win_lineinfile.ps1
> +		Add-Warning $result 'Both insertbefore and insertafter parameters found, ignoring "insertafter=$insertafter"'
Are you able to change the message to be `"` double quotes. The variable `$insertafter` won't actually be shown in this example. Would also be good to use `-obj` and `-message` for the parameters.

2017-06-26 22:52 UTC, jborean93 commented on lib/ansible/modules/windows/win_regedit.ps1
> +    Add-Warning $result "Please use path: HKCC:\... instead of path: $path"
If you are changing the above can you add the parameters?

2017-06-26 22:55 UTC, dagwieers commented on lib/ansible/modules/windows/win_lineinfile.ps1
> +		Add-Warning $result 'Both insertbefore and insertafter parameters found, ignoring "insertafter=$insertafter"'
I am torn for the options though. We don't do it for Exit-Json or Fail-Json, and this one is in the same category.

2017-06-26 22:57 UTC, jborean93 commented on lib/ansible/modules/windows/win_lineinfile.ps1
> +		Add-Warning $result 'Both insertbefore and insertafter parameters found, ignoring "insertafter=$insertafter"'
Happy to merge it now (apart from the quoting side), we can always revisit it as yes you are correct there seems to be different ways we are doing this stuff.

2017-06-26 22:59 UTC, dagwieers commented on lib/ansible/modules/windows/win_lineinfile.ps1
> +		Add-Warning $result 'Both insertbefore and insertafter parameters found, ignoring "insertafter=$insertafter"'
Thanks, I fixed the quotes already.

2017-06-26 23:07 UTC, jborean93 approved these changes

2017-06-26 23:40 UTC, jborean93 commented
LGTM, merging the changes into devel

2017-06-26 23:40 UTC, merged