zabbix_host: added zabbix host property (description)
ansible/ansible pull request #25969
Opened 2017-06-21 14:59 UTC by schast

##### SUMMARY
added support for zabbix default host property ```description```.
https://www.zabbix.com/documentation/3.2/manual/api/reference/host/object#host

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/modules/monitoring/zabbix_host.py

##### ANSIBLE VERSION
```
2.4.0 (devel 33c61d1cdf)
```

2017-06-22 12:47 UTC, resmo reviewed
needs_info

2017-06-22 12:47 UTC, resmo commented on lib/ansible/modules/monitoring/zabbix_host.py
> +                parameters['description'] = ""
imho there should be no else here, otherwise no description param would not keep the current description, wouldn't it

2017-06-22 14:41 UTC, schast commented on lib/ansible/modules/monitoring/zabbix_host.py
> +                parameters['description'] = ""
that's right.
but there is no way to unset the parameters (description, visible_name, ...).
you can only overwrite them.

how can i solve that problem?

2017-06-23 06:02 UTC, resmo requested changes

2017-06-23 06:02 UTC, resmo commented on lib/ansible/modules/monitoring/zabbix_host.py
> +            if description:
as a response to your question: change this condition to check for not None. So an empty str will be handeled.

```
if description is not None:
```

2017-06-23 08:14 UTC, schast commented on lib/ansible/modules/monitoring/zabbix_host.py
> +            if description:
i have tested with ```if description is not None:``` but it is not the desired result.

I think we should leave it as it is. so the behavior is the same for all options.

2017-06-23 20:41 UTC, resmo commented on lib/ansible/modules/monitoring/zabbix_host.py
> +            if description:
I am curious, what was your test case? AFAICS it is only relevant if you like to clear an existing description. I don't know the api that well and if this is even supported, etc.

2017-06-23 20:42 UTC, resmo approved these changes

2017-06-23 20:43 UTC, resmo commented
ready_for_review

2017-10-05 23:01 UTC, eikef commented
This looks good to me, but needs to be rebased. Thank you :-)

2017-10-09 10:23 UTC, eikef commented
I just tested this locally. While I can add a description to a host, it seems impossible to update it -- any changed descriptions do not reach Zabbix and do not yield a changed: True.

2017-10-09 10:36 UTC, eikef commented
you are missing something like
`        # The Zabbbix API returns an empty description as an empty string
        if description is None:
            description = ''
        if host['description'] != description:
            return True
`

in the check_all_properties function. With that in there, updates work as expected (at least for me). If you put that in this should be mergable :)

2017-10-09 11:06 UTC, eikef commented
shipit

2017-10-09 12:17 UTC, eikef commented
!needs_rebase

2017-10-09 12:17 UTC, eikef commented
bot_status

2017-10-09 12:28 UTC, eikef commented
@schast this PR still contains a merge commit; The PR needs to be rebased on current -devel (or at least non-conflicting-devel) instead of containing a merge commit.

Please rebase your changes. The bot did linked to http://docs.ansible.com/ansible/latest/dev_guide/developing_rebasing.html for a how-to; if that proves impossible you can also close this PR and open a new one based on current -devel.

Sorry for the inconvencience :)

2017-10-09 12:28 UTC, eikef commented
And thank you

2017-10-09 15:48 UTC, schast commented
@eikef: can you merge now?

cannot reproduce the failing check...
```
2017-10-09 15:29:20 Run command: pycodestyle --max-line-length 160 --config /dev/null --ignore E305,E402,E722,E741 lib/ansible/modules/monitoring/zabbix_host.py
2017-10-09 15:29:20 ERROR: Found 1 pep8 issue(s) which need to be resolved:
2017-10-09 15:29:20 ERROR: test/sanity/pep8/legacy-files.txt:208:1: A201 Remove "lib/ansible/modules/monitoring/zabbix_host.py" since it passes the current rule set (75%)
```

```
[schast@pc01:~/repos/github/schast-ansible.git (devel)]$ pycodestyle -v --max-line-length 160 --config /dev/null --ignore E305,E402,E722,E741 lib/ansible/modules/monitoring/zabbix_host.py
local configuration: in /data01/WORKING/repos/github/schast-ansible.git
checking lib/ansible/modules/monitoring/zabbix_host.py
[schast@pc01:~/repos/github/schast-ansible.git (devel)]$ echo $?
0
```

2017-10-09 16:12 UTC, eikef commented
Since I'm only a community maintainer, the only way I can merge is via ansibot.

This is a funny (IMHO) situation -- it appears zabbix_host was whitelisted for containing superfluous whitespace which your patch removes, and now the test whether said whitelist is still needed fails. I suspect that if you edit your commits to not clear said superfluous whitespace (lines 220/232) the checks will pass and the changeset can be merged via ansibot.

If you can do that, I will try to get this check and whitespace removed in a separate PR. Sorry for the inconvenience.

2017-10-09 21:22 UTC, eikef commented
shipit

2017-10-09 21:25 UTC, resmo commented
shipit

2017-10-11 20:26 UTC, merged