Add reference to VNET resource group
ansible/ansible pull request #26052
Opened 2017-06-23 18:21 UTC by ozboms

When creating a new virtual machine, added new parameter to allow creation of VM in a resource group using virtual network from another resource group

##### SUMMARY
Fixes bug #25032 - azure_rm_virtualmachine fails to find VNET in different resource group 
(https://github.com/ansible/ansible/issues/25032)

Created a new parameter to create an option for another resource group specific to the VNET you want to use called: virtual_network_resource_group. 

Need to input the other resource group where your VNET resides to use another VNET not in the resource group of your new virtual machine. 

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
azure_rm_virtualmachine

2017-06-23 18:31 UTC, harijayms commented
looks good to me, if there is a test for Virtual machines please add a test as well

2017-06-26 15:41 UTC, tstringer commented
@ozboms add a `version_added` prop to your new param:

```
    virtual_network_resource_group:
        description:
            - When creating a virtual machine, if a specific virtual network from another resource group should be
              used, use thus parameter to specify the resource group to use.
        default: null
        required: false
        version_added: "2.4"
```

This is explained [here in the docs](http://docs.ansible.com/ansible/dev_guide/developing_modules_documenting.html) (thanks to @gundalow and @jctanner for pointing that out!).

2017-06-27 23:48 UTC, haroldwongms commented
This looks good to me.

2017-06-27 23:48 UTC, haroldwongms commented
shipit

2017-06-27 23:50 UTC, tstringer commented
shipit

2017-06-28 20:42 UTC, jborean93 commented
bot_status

2017-07-10 16:44 UTC, s-hertel commented on lib/ansible/modules/cloud/azure/azure_rm_virtualmachine.py
> +                except Exception as exc:
Can CloudError be caught instead of Exception to be more specific?

2017-07-10 16:44 UTC, s-hertel commented on lib/ansible/modules/cloud/azure/azure_rm_virtualmachine.py
> +                except Exception as exc:
Here too?

2017-07-12 14:38 UTC, tstringer commented on lib/ansible/modules/cloud/azure/azure_rm_virtualmachine.py
> +                except Exception as exc:
Yes, completely agreed. @ozboms can you use `CloudError` for your error handling here?

2017-07-12 14:38 UTC, tstringer commented on lib/ansible/modules/cloud/azure/azure_rm_virtualmachine.py
> +                except Exception as exc:
Yep, agreed. // @ozboms

2017-07-13 18:19 UTC, ozboms commented on lib/ansible/modules/cloud/azure/azure_rm_virtualmachine.py
> +                except Exception as exc:
Yep! Fixed and recommitted!

2017-07-13 20:19 UTC, nitzmahone requested changes

2017-07-13 20:19 UTC, nitzmahone commented on lib/ansible/modules/cloud/azure/azure_rm_virtualmachine.py
> -# Copyright (c) 2016 Matt Davis, <mdavis@ansible.com>
Why have you removed our copyright and replaced it with your own for making a few lines of change?

2017-07-13 20:19 UTC, nitzmahone commented on lib/ansible/modules/cloud/azure/azure_rm_virtualmachine.py
> +                    subnets = self.network_client.subnets.list(self.virtual_network_resource_group, virtual_network_name)
No need to duplicate these lines of code- just conditionally assign a local `virtual_network_resource_group` as `self.resource_group` or `self.virtual_network_resource_group` as appropriate and use it below the conditional.

2017-07-13 22:42 UTC, ozboms commented on lib/ansible/modules/cloud/azure/azure_rm_virtualmachine.py
> -# Copyright (c) 2016 Matt Davis, <mdavis@ansible.com>
Oh my bad! I'm creating a few new modules and mistakenly changed this one also in this branch. I apologize for the error and will fix that.

2017-07-13 22:43 UTC, ozboms commented on lib/ansible/modules/cloud/azure/azure_rm_virtualmachine.py
> +                    subnets = self.network_client.subnets.list(self.virtual_network_resource_group, virtual_network_name)
I could have sworn I tried that and it wouldn't let me use a local variable but I didn't really understand how the module worked that well then. I'll test out the local variable and make the necessary changes.

2017-07-13 22:57 UTC, nitzmahone commented on lib/ansible/modules/cloud/azure/azure_rm_virtualmachine.py
> -# Copyright (c) 2016 Matt Davis, <mdavis@ansible.com>
No worries- we assumed it was an oversight. ;)

2017-07-19 15:18 UTC, tstringer commented
@nitzmahone just revisiting this, are the necessary changes @ozboms made sufficient?

2017-07-31 18:36 UTC, ozboms commented
@nitzmahone Just wanted to check in to see if my changes are correct and if it's possible to have it merged into the devel branch?

Thanks!

2017-07-31 19:46 UTC, tstringer commented
@ozboms let's do this. Join up on the IRC meeting tomorrow at 3pm EST (freenode `#ansible-meeting` channel) and let's bring this up then.

@thaumos can you get this PR on the agenda for tomorrow's meeting?

2017-07-31 22:22 UTC, nitzmahone approved these changes

2017-07-31 22:29 UTC, merged

2017-07-31 22:31 UTC, nitzmahone commented
Sorry, been a hectic couple of weeks- changes look good. I just took the opportunity to get rid of some superfluous `default`/`required` lines (used to be required but aren't anymore). Thanks!

2017-07-31 22:38 UTC, tstringer commented
Thanks, @nitzmahone!

And thanks for the contribution, @ozboms! 👍 😄

2017-07-31 22:48 UTC, ozboms commented
Good to know about the default/required lines! 
Thanks for the suggestions and reviewing and approving @nitzmahone @tstringer