win_iis_webapplication: Parameter fixes and check-mode
ansible/ansible pull request #26082
Opened 2017-06-26 09:32 UTC by dagwieers

##### SUMMARY
This PR includes:
- General cleanup of parameters
- Added check-mode support
- Cleanup of return values

##### ISSUE TYPE

 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME

win_iis_webapplication

##### ANSIBLE VERSION

v2.4

2017-06-28 00:52 UTC, jborean93 requested changes
Only minor point around removing an application and check mode

2017-06-28 00:52 UTC, jborean93 commented on lib/ansible/modules/windows/win_iis_webapplication.ps1
> +        $application = Remove-WebApplication -Site $site -Name $name
Remove-WebApplication supports `-WhatIf`

2017-06-28 01:18 UTC, dagwieers commented on lib/ansible/modules/windows/win_iis_webapplication.ps1
> +        $application = Remove-WebApplication -Site $site -Name $name
Done !

2017-06-28 02:15 UTC, jborean93 approved these changes

2017-06-28 02:16 UTC, jborean93 commented
looks good, will merge through

2017-06-28 02:16 UTC, merged

2017-07-28 09:11 UTC, sm4rk0 commented on lib/ansible/modules/windows/win_iis_webapplication.ps1
> +    $application = Remove-WebApplication -Site $site -Name $name $WhatIf:$check_mode
`$WhatIf:$check_mode` should be `-WhatIf:$check_mode`

2017-07-28 09:15 UTC, sm4rk0 commented on lib/ansible/modules/windows/win_iis_webapplication.ps1
> +    $application = Remove-WebApplication -Site $site -Name $name $WhatIf:$check_mode
BTW, is it OK to correct small typos this way, or should I report an issue and/or make a PR?

2017-07-28 10:40 UTC, jhawkesworth commented on lib/ansible/modules/windows/win_iis_webapplication.ps1
> +    $application = Remove-WebApplication -Site $site -Name $name $WhatIf:$check_mode
@sm4rk0 - if a PR has been merged like this one, best to make a new PR - maintainers don't tend to get notified once a PR has been merged.