Fix ansible ad-hoc to respect ANSIBLE_STDOUT_CALLBACK
ansible/ansible pull request #26098
Opened 2017-06-26 14:29 UTC by armab

Fixes https://github.com/ansible/ansible/issues/16194

##### SUMMARY
Stdout callback for `ansible` ad-hoc is hardcoded to `minimal`.

This PR allows overriding the default stdout callback for `ansible` via `ANSIBLE_STDOUT_CALLBACK` env or respective `stdout_callback` ini setting.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
ansible ad-hoc

##### ANSIBLE VERSION
```
2.4.0
```

2017-06-26 15:43 UTC, bcoca requested changes

2017-06-26 15:43 UTC, bcoca commented on lib/ansible/cli/adhoc.py
> +            cb = 'minimal' if C.DEFAULT_STDOUT_CALLBACK == 'default' else C.DEFAULT_STDOUT_CALLBACK
adhoc has an extra config `bin_ansible_callbacks` which should determine this, not just stdout_callback

2017-06-26 16:19 UTC, armab commented on lib/ansible/cli/adhoc.py
> +            cb = 'minimal' if C.DEFAULT_STDOUT_CALLBACK == 'default' else C.DEFAULT_STDOUT_CALLBACK
So custom `stdout_callback` is picked up only with enabled `bin_ansible_callbacks`.

Done in https://github.com/ansible/ansible/pull/26098/commits/d8afdcd47b69a3c207d8446f351b41103f3eed50

2017-06-26 16:42 UTC, bcoca approved these changes

2017-06-26 20:01 UTC, merged

2017-06-26 20:02 UTC, bcoca commented
backported to stable 2.3 and 2.2

2017-09-19 19:58 UTC, artburkart commented
Hi, this may be the wrong place to ask this, but how does this PR work?

I'm using the latest ansible available on pip:

```
$ ansible --version
ansible 2.4.0.0
  config file = /Users/artburkart/Code/ansible.cfg
  configured module search path = [u'/Users/artburkart/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Jul 18 2017, 09:17:00) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

When I write a playbook that looks like this:

```yml
---
- hosts: all
  gather_facts: False
  tasks:
    - debug: msg="hello"
```

and run:

```command
ANSIBLE_STDOUT_CALLBACK=json ansible-playbook -i localhost, -c local playbook.yml
```

I get:

```json
{
    "plays": [
        {
            "play": {
                "id": "9801a7a4-290d-65bb-c394-000000000006",
                "name": "all"
            },
            "tasks": [
                {
                    "hosts": {
                        "localhost": {
                            "_ansible_no_log": false,
                            "_ansible_verbose_always": true,
                            "changed": false,
                            "failed": false,
                            "msg": "hello"
                        }
                    },
                    "task": {
                        "id": "9801a7a4-290d-65bb-c394-000000000008",
                        "name": ""
                    }
                }
            ]
        }
    ],
    "stats": {
        "localhost": {
            "changed": 0,
            "failures": 0,
            "ok": 1,
            "skipped": 0,
            "unreachable": 0
        }
    }
}
```

But when I write an `ansible.cfg` that looks like this:

```ini
[defaults]
bin_ansible_callbacks = True
```

And run this command:

```command
ANSIBLE_STDOUT_CALLBACK=json ansible all -i localhost, -c local -m setup
```

The output looks like this:

```command
$ ANSIBLE_STDOUT_CALLBACK=json ansible all -i localhost, -c local -m setup
$
```

Should this work now that this PR has been merged?

I also tried an `ansible.cfg` that looked like this:

```
[defaults]
bin_ansible_callbacks = True
callback_plugins = /usr/local/lib/python2.7/site-packages/ansible/plugins/callback
```

No dice. 

Thanks for your insight! Cheers

2017-09-20 09:55 UTC, armab commented
@arbabnazar The PR includes functionality to respect custom callback for ansible ad-hoc command,
but from what I see built-in `ANSIBLE_STDOUT_CALLBACK=json` needs an adjustment.

See `v2_runner_on_ok` in core `json` callback plugin which doesn't output anything:
https://github.com/ansible/ansible/blob/07f5a186fbb02fb1c133817dafa4beb4012f4150/lib/ansible/plugins/callback/json.py#L58-L60

There might be more core plugins which don't implement printing anything for ad-hoc runner, but you may modify `json` plugin or create any custom callback plugin and place it in custom location, - that'll work for now.

This example can help you: 
http://docs.ansible.com/ansible/latest/dev_guide/developing_api.html#python-api-2-0
```py
    """A sample callback plugin used for performing an action as results come in

    If you want to collect all results into a single object for processing at
    the end of the execution, look into utilizing the ``json`` callback plugin
    or writing your own custom callback plugin
    """
    def v2_runner_on_ok(self, result, **kwargs):
        """Print a json representation of the result

        This method could store the result in an instance attribute for retrieval later
        """
        host = result._host
        print json.dumps({host.name: result._result}, indent=4)
```

2017-09-20 14:20 UTC, artburkart commented
@armab - Wow you went above and beyond answering the question. You could've also told me to look at the json.py file and figure it out myself. 😛 The snippet you shared was exactly what I was looking for. Thanks!