Document AnsibleModule Arg spec
ansible/ansible pull request #26115
Opened 2017-06-26 18:46 UTC by gundalow

##### SUMMARY

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
basic

##### ANSIBLE VERSION
```
2.4.0
```

2017-06-26 23:58 UTC, willthames requested changes
This is a good start. I wish I could answer some of the FIXMEs better myself!

2017-06-26 23:58 UTC, willthames commented on docs/docsite/rst/dev_guide/developing_modules_general.rst
> +                state=dict(default='present', choices=['present', 'absent']),
Should probably be `required=True` - my understanding is that a default state is now frowned upon? (If not we should get that clarified once and for all)

2017-06-26 23:58 UTC, willthames commented on docs/docsite/rst/dev_guide/developing_modules_general.rst
> +      If not specified by the user what is the default value for this option.
Defaults to `None`

2017-06-26 23:58 UTC, willthames commented on docs/docsite/rst/dev_guide/developing_modules_general.rst
> +      Currently supports ``env_fallback``. In this case the environment variable of where Ansible is run is used.
perhaps 'the environment variable on the Ansible controller' - or just s/of/from/

2017-06-26 23:58 UTC, willthames commented on docs/docsite/rst/dev_guide/developing_modules_general.rst
> +          This option should accept the common terms for truth, such as "yes", "on", 1, True, etc.
This option *will* accept the common terms you list. They then get converted to `True` or `False` from a module point of view.

2017-06-26 23:58 UTC, willthames commented on docs/docsite/rst/dev_guide/developing_modules_general.rst
> +          Allows passing a YAML list in via the Playbook.
Also converts 'one,two,three' to a python list, I believe.

2017-06-26 23:58 UTC, willthames commented on docs/docsite/rst/dev_guide/developing_modules_general.rst
> +          Ensure option is a path where the playbook is executed.
More sophisticated than this - also does things like `~` expansion. Perhaps 'allows a path to a filesystem object to be specified'. Also, the path could be on controller or target, depending on the module implementation

2017-06-26 23:58 UTC, willthames commented on docs/docsite/rst/dev_guide/developing_modules_general.rst
> +
FIXME: document required_one_of etc.

2017-06-26 23:58 UTC, willthames commented on docs/docsite/rst/dev_guide/developing_modules_general.rst
>  The :class:`AnsibleModule` provides lots of common code for handling returns, parses your arguments
Should this be moved to the top of this section?

2017-07-03 11:48 UTC, gundalow commented on docs/docsite/rst/dev_guide/developing_modules_general.rst
> +                state=dict(default='present', choices=['present', 'absent']),
Good question, let me ask

2017-07-26 02:14 UTC, dharmabumstead reviewed
Looks like a WIP commit?

2017-10-16 07:53 UTC, gundalow commented
Need to find a new home for this as the original file has been repurposed.

2017-10-24 14:08 UTC, gundalow commented
Moved to new section https://github.com/ansible/ansible/pull/32052

2017-10-24 14:08 UTC, closed without merging