Iam managed policy improvements
ansible/ansible pull request #26219
Opened 2017-06-29 03:11 UTC by willthames

##### SUMMARY
Use snake case for module return values
Add exception handling

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
iam_managed_policy

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel dcd1ff2809) last updated 2017/06/29 13:11:02 (GMT +1000)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/will/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/will/src/ansible/lib/ansible
  executable location = /home/will/src/ansible/bin/ansible
  python version = 2.7.13 (default, May 10 2017, 20:04:28) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```

##### ADDITIONAL INFORMATION

2017-06-29 03:14 UTC, willthames commented on lib/ansible/modules/cloud/amazon/iam_managed_policy.py
> +        delete_oldest_non_default_version(module, iam, policy)
@dkhenry I've left the logic here pretty much as it was, but I don't really understand how this section of code is designed to work. Is there a limit to the number of versions allowed (is that what the 5 in your comment refers to?)

2017-06-29 13:41 UTC, dkhenry commented on lib/ansible/modules/cloud/amazon/iam_managed_policy.py
> +        delete_oldest_non_default_version(module, iam, policy)
Yes there is a limit, it defaults to 5 ,but I am not sure its 5 for everyone as many AWS limits can be changed by a customer, so instead I made the logic to just delete one and try again. That way you are not removing more then you need to in the event a user has a higher cap then I did.

2017-06-30 01:06 UTC, willthames commented on lib/ansible/modules/cloud/amazon/iam_managed_policy.py
> +        delete_oldest_non_default_version(module, iam, policy)
Thanks for the extra info @dkhenry. I might update the comment slightly.

2017-06-30 01:26 UTC, willthames commented on lib/ansible/modules/cloud/amazon/iam_managed_policy.py
> +        delete_oldest_non_default_version(module, iam, policy)
I've updated the comments and the error handling.

2017-07-12 04:10 UTC, willthames commented
Once this is merged, #26223 can be merged too

2017-07-12 20:54 UTC, ryansb requested changes

2017-07-12 20:54 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/iam_managed_policy.py
> +        response = iam.list_policies(Scope='Local', **kwargs)
`marker` must be capitalized here per http://boto3.readthedocs.io/en/latest/reference/services/iam.html#IAM.Client.list_policies, so line 140 has to call `get_policy_by_name(module, iam, name, Marker=response['Marker'])`

2017-07-13 00:31 UTC, willthames commented on lib/ansible/modules/cloud/amazon/iam_managed_policy.py
> +        response = iam.list_policies(Scope='Local', **kwargs)
Good point. Easiest to fix using the paginator with build_full_result, along with AWSRetry

2017-07-14 01:10 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/iam_managed_policy.py
> +        response = iam.list_policies(Scope='Local', **kwargs)
Ah, well that'd be even better :+1:

2017-07-14 01:30 UTC, ryansb approved these changes

2017-07-14 01:30 UTC, merged