Add integration test for fact delegation
ansible/ansible pull request #26253
Opened 2017-06-29 16:02 UTC by samdoran

##### SUMMARY
Related to issue #20508, issue #20980 where delegated facts are not set correctly, probably more.

Fixed in PR #25880

##### ISSUE TYPE

 - Test Pull Request

##### COMPONENT NAME
test/integration/targets/delegate_to/test_delegate_to.yml

##### ANSIBLE VERSION

```
ansible 2.4.0 (sdoran-delegate-tests 0531deac50) last updated 2017/06/29 11:55:11 (GMT -400)
  config file = /Users/sdoran/.ansible.cfg
  configured module search path = [u'/Users/sdoran/Source/ansible/library']
  ansible python module location = /Users/sdoran/Source/ansible/lib/ansible
  executable location = /Users/sdoran/Source/ansible/bin/ansible
  python version = 2.7.13 (default, Dec 18 2016, 07:03:39) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### ADDITIONAL INFORMATION

2017-06-29 22:10 UTC, nitzmahone requested changes
Looks pretty good- just those couplea things (and the "skip" only if there's a sane way to do it, which I can't think of off the top of my head)

2017-06-29 22:10 UTC, nitzmahone commented on test/integration/targets/delegate_to/test_delegate_to.yml
> +      when: inventory_hostname == 'facthost2'
might also want to add one to assert that testfact2 isn't set on other hosts

2017-06-29 22:10 UTC, nitzmahone commented on test/integration/targets/delegate_to/test_delegate_to.yml
>  - hosts: testhost3
wondering if there's a sane (cross platform-friendly) way to check for existence of the right IPs and skip this test if they're not present...

2017-06-30 17:37 UTC, samdoran commented on test/integration/targets/delegate_to/test_delegate_to.yml
> +      when: inventory_hostname == 'facthost2'
I added another test to check that facts _aren't_ set on the other hosts.

2017-06-30 17:37 UTC, samdoran commented on test/integration/targets/delegate_to/test_delegate_to.yml
>  - hosts: testhost3
I'm not quite sure what you mean by this.

2017-07-05 15:37 UTC, nitzmahone commented on test/integration/targets/delegate_to/test_delegate_to.yml
>  - hosts: testhost3
Mainly just having the test figure out that the IPs are defined and auto-skip the test if they aren't (IIRC you said you had to preconfigure the IPs on your box to get the test to run locally).

2017-07-05 16:10 UTC, samdoran commented on test/integration/targets/delegate_to/test_delegate_to.yml
>  - hosts: testhost3
Oh, no that was before I was running it in containers. The container based tests have the necessary loopback interfaces, so we shouldn't need to be any preflight checks to see if the loopback IPs are up.

2017-07-13 01:14 UTC, nitzmahone commented on test/integration/targets/delegate_to/test_delegate_to.yml
>  - hosts: testhost3
Think a sane test might be to ICMP ping the IPs (eg, would that work on the platforms you've tried running this test on)?

2017-08-03 15:41 UTC, closed without merging