Pip flexible versions
ansible/ansible pull request #26299
Opened 2017-06-30 19:18 UTC by inhumantsar

##### SUMMARY
Allow users to use version specs when installing pip packages (eg: `>=1.2.3,!=1.2.4`) as well as plain version numbers.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
modules/packaging/languages/pip

##### ANSIBLE VERSION
```
devel
```

##### ADDITIONAL INFORMATION
Added this line to docs but don't know what version to list, so TODO I guess: `As of ... you can use version comparisons in this parameter.`

2017-07-05 20:44 UTC, ssbarnea commented
I would love to see this fixed as current this makes the entire module almost useless. If you cannot specify ranges, like in `requirements.txt`, why to use the module?... it would only create mode maintenance in order to update the pinned version.

2017-07-15 22:37 UTC, Lujeni commented
Hello @inhumantsar 

Thanks for your pull request !
Few modifications before merged your patch :):
- Add integrations test (There is a pull request on your Ansible repository)
- Can you rebase your commit please and keep a single one?

Thanks again

ciao

2017-07-16 12:06 UTC, robinro requested changes
That change (and the example) breaks idempotency and check_mode as far as I see.

See also https://github.com/ansible/ansible/pull/19690 for a similar PR.

I am hesitant to merge such a breaking change.
Essentially as soon as a version specification is detected we have to assume `changed=True` in check_mode and use the `get_packages` codepath to detect changes when running.

2017-07-16 15:30 UTC, ssbarnea commented
changed status should be based on diff result of before and after pip freeze

2018-11-26 16:26 UTC, webknjaz commented
Implemented by #41792

2018-11-26 16:26 UTC, closed without merging