win_secedit: Added module with tests/diff mode
ansible/ansible pull request #26332
Opened 2017-07-02 22:11 UTC by jborean93

##### SUMMARY
Added win_secedit module with the following supported
- check mode
- diff mode
- integration tests

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
win_secedit

##### ANSIBLE VERSION
```
ansible 2.4.0 (win_secedit-module 196d900df3) last updated 2017/07/03 08:09:07 (GMT +1000)
  config file = None
  configured module search path = [u'/home/jborean/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jborean/dev/ansible/lib/ansible
  executable location = /home/jborean/dev/ansible/bin/ansible
  python version = 2.7.13 (default, Jun 28 2017, 21:13:49) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]

```

##### ADDITIONAL INFORMATION
This is a continuing of https://github.com/ansible/ansible/pull/22775 with tests/check and diff mode added.

2017-07-12 02:14 UTC, nitzmahone requested changes
I'm thinking a rename would be good on this one (win_security_policy?). I was never really a fan of naming the modules after the utility they were built on (eg, `win_regedit` should've been `win_registry`). Couple other little things (pretty much same as win_user_right).

2017-07-12 02:14 UTC, nitzmahone commented on lib/ansible/modules/windows/win_secedit.py
> +module: win_secedit
Should this be `win_security_policy` or something now?

2017-07-12 02:14 UTC, nitzmahone commented on lib/ansible/modules/windows/win_secedit.ps1
> +    Fail-Json $result "Failed to export secedit.ini file to $($secedit_ini_path).`nRC: $($export_result.rc)`nSTDOUT: $($export_result.stdout)`nSTDERR: $($export_result.stderr)`nLOG: $($export_result.
same comment from win_user_right WRT: discrete return keys for these instead of all in msg? Could see either way...

2017-07-12 02:14 UTC, nitzmahone commented on lib/ansible/modules/windows/win_secedit.py
> +before_value:
redundant w/ diff mode?

2017-07-12 02:14 UTC, nitzmahone commented on lib/ansible/modules/windows/win_secedit.ps1
> +        $export_result = Run-SecEdit -arguments @("/export", "/cfg", $secedit_ini_path, "/quiet")
same as win_user_right: couldn't we just factor out the change detection, re-run, and fail on change?

2017-07-12 02:17 UTC, jborean93 commented on lib/ansible/modules/windows/win_secedit.ps1
> +    Fail-Json $result "Failed to export secedit.ini file to $($secedit_ini_path).`nRC: $($export_result.rc)`nSTDOUT: $($export_result.stdout)`nSTDERR: $($export_result.stderr)`nLOG: $($export_result.
That makes sense, I think I went this way as older Ansible versions just ignored attributes for `$result`, them being there now makes sense.

2017-07-12 02:17 UTC, jborean93 commented on lib/ansible/modules/windows/win_secedit.ps1
> +        $export_result = Run-SecEdit -arguments @("/export", "/cfg", $secedit_ini_path, "/quiet")
Yep good idea.

2017-07-12 02:18 UTC, jborean93 commented on lib/ansible/modules/windows/win_secedit.py
> +module: win_secedit
Happy to change, the only reason I went this way as I wasn't sure if there were security policies that can't be edited by secedit. If that isn't the case I agree changing it is best.

2017-07-13 09:04 UTC, dagwieers commented
+label new_module

2017-07-14 03:39 UTC, jborean93 commented on lib/ansible/modules/windows/win_secedit.ps1
> +        $export_result = Run-SecEdit -arguments @("/export", "/cfg", $secedit_ini_path, "/quiet")
We could but then we loose the specific error around an invalid keys, I'll try and refactor common code but feel that error would be useful to have.

2017-07-14 17:57 UTC, nitzmahone commented on lib/ansible/modules/windows/win_security_policy.py
> +  win_secedit:
Examples need update to reflect rename

2017-07-14 18:00 UTC, nitzmahone approved these changes

2017-07-14 18:00 UTC, merged