Add Pure Storage Protection Groups module
ansible/ansible pull request #26356
Opened 2017-07-03 13:50 UTC by sdodsley

SUMMARY

Storage module for Pure Storage FlashArray device. Module to create/delete protection groups

ISSUE TYPE

New Module Pull Request
COMPONENT NAME

purefa_pg
ANSIBLE VERSION

ansible 2.4.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/pureuser/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

2017-07-03 14:07 UTC, sdodsley commented
@gundalow As requested separate PR for each remaining module

2017-07-17 18:10 UTC, sdodsley commented
@gundalow  : Can you review, please?

2017-07-25 13:43 UTC, gundalow requested changes

2017-07-25 13:43 UTC, gundalow commented on lib/ansible/modules/storage/purestorage/purefa_pg.py
> +            eradicate=dict(default='false', choices=['false', 'true']),
`eradicate=dict(default='false', type='bool),`

2017-07-25 13:43 UTC, gundalow commented on lib/ansible/modules/storage/purestorage/purefa_pg.py
> +    choices: [ "false", "true" ]
Please replace with `type: bool`

http://docs.ansible.com/ansible/latest/dev_guide/developing_modules_documenting.html#documentation-block

2017-07-25 16:17 UTC, sdodsley commented
@gundalow  changes completed as requested

2017-07-28 10:30 UTC, gundalow approved these changes

2017-08-01 22:05 UTC, sdodsley commented
@gundalow changes added as per comment. Please review together with PR #26355

2017-08-02 14:19 UTC, sdodsley commented
shipit

2017-08-02 14:20 UTC, merged

2017-08-02 14:21 UTC, gundalow commented
Merged, and will be released in Ansible 2.4.0