updated readme with vault and 2.4 inv plugins
ansible/ansible pull request #26361
Opened 2017-07-03 15:22 UTC by bcoca

##### SUMMARY

contrib is contrib

##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

contrib
##### ANSIBLE VERSION

```
2.4
```

2017-07-03 15:26 UTC, rcarrillocruz commented on contrib/README.md
> +Before 2.4 introduced inventory plugins, before that inventory scripts were the only way to provide sources that were not 'built into Ansible'.
'before that' should be removed?

2017-07-04 05:42 UTC, dharmabumstead requested changes

2017-07-04 05:42 UTC, dharmabumstead commented on contrib/README.md
> +Starting with Ansible version 2.4, they are enabled via the 'script' inventory plugin.
Please clarify the word "they" here.

2017-07-05 18:39 UTC, bcoca commented on contrib/README.md
> +Starting with Ansible version 2.4, they are enabled via the 'script' inventory plugin.
could you clarify what i need to clarify?

2017-07-24 20:37 UTC, merged