ec2_elb_lb check mode (Fixes #26428)
ansible/ansible pull request #26442
Opened 2017-07-05 16:49 UTC by aioue

ec2_elb_lb check_mode

Fixes https://github.com/ansible/ansible/issues/26428

##### SUMMARY

add check mode support to ec2_elb_lb

Due to some weakness with python, there are 4 occasions where I am setting changed, with no check against the exist state. This is means check_mode is safe, but not necessarily accurate for:
- create ELB
- delete ELB
- create ELB listeners
- delete ELB listeners

Fixes https://github.com/ansible/ansible/issues/26428

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

ec2_elb_lb

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /Users/tom/repos/aws-codecommit/ansible-tower/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```

##### ADDITIONAL INFORMATION

```

```

2017-07-05 23:10 UTC, abadger commented
/cc @ryansb

2017-07-05 23:17 UTC, aioue commented
RE: Shippable `NameError: global name 'module' is not defined`: I have asked on Google Groups how to approach `check_mode` and as yet received no response.

Need this functionality for work so would very much like to fix, or get this patched up to standard with assistance from the module curator.

2017-07-06 00:37 UTC, mattclay commented
@aioue You should use `self.module` instead of `module`, as can be seen in the surrounding code.

2017-07-06 05:37 UTC, aioue commented
@mattclay thank you. Updated as directed.

2017-07-06 05:58 UTC, aioue commented
@mattclay

2017-07-06 20:48 UTC, mattclay commented
@aioue The syntax error is due to an indentation issue as noted by the ansibot comment:

```
lib/ansible/modules/cloud/amazon/ec2_elb_lb.py:1281:15: E901 IndentationError: unindent does not match any outer indentation level
```

I recommend running the test `ansible-test sanity --test pep8 lib/ansible/modules/cloud/amazon/ec2_elb_lb.py` locally. That will help catch issues such as this.

This particular issue appears to be due to use of 2 spaces for indentation instead of 4.

2017-07-10 21:50 UTC, aioue commented
@mattclay all fixed up 👍

2017-07-11 05:41 UTC, willthames requested changes

2017-07-11 05:41 UTC, willthames commented on lib/ansible/modules/cloud/amazon/ec2_elb_lb.py
> +            self.staus = 'created'
self.status

2017-07-11 05:41 UTC, willthames commented on lib/ansible/modules/cloud/amazon/ec2_elb_lb.py
> +                        if elb_info.policies.app_cookie_stickiness_policies[0].policy_name == self._policy_name(
Not sure why we've wrapped here and 1118, decreasing readability, while not wrapping longer lines.

2017-07-11 11:23 UTC, willthames commented
shipit

2017-07-11 11:23 UTC, willthames approved these changes

2017-07-26 09:53 UTC, aioue commented
No longer able to work on this. Closing.

2017-07-26 09:53 UTC, closed without merging