delete datetime object from RDS cluster responses in ec2.py
ansible/ansible pull request #26481
Opened 2017-07-06 10:43 UTC by mwjackson

##### SUMMARY

this is to prevent TypeError: x is not JSON serializable when pulling down RDS cluster information

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

ec2.py

##### ANSIBLE VERSION

```
ansible 2.2.1.0
```

##### ADDITIONAL INFORMATION

```

```

2017-09-07 20:14 UTC, s-hertel approved these changes

2017-11-09 11:49 UTC, StephenKing commented
Can confirm the problem and solution.

2017-11-09 12:05 UTC, willthames commented
It's not the best solution though.

Just convert it to ISO8601

https://stackoverflow.com/a/22238613

2017-11-09 12:05 UTC, willthames requested changes

2017-11-09 12:05 UTC, willthames commented on contrib/inventory/ec2.py
> +                del c['ClusterCreateTime']
Let's fix this properly rather than deleting useful information

https://stackoverflow.com/a/22238613

2019-06-25 11:03 UTC, closed without merging