PEP8 legacy fixes
ansible/ansible pull request #26538
Opened 2017-07-07 16:19 UTC by aioue

##### SUMMARY

PEP8 legacy fixes
ec2_ami
ec2_elb_facts
ec2_eni_facts
ec2_snapshot
ec2_tag

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

ec2_ami
ec2_elb_facts
ec2_eni_facts
ec2_snapshot
ec2_tag

##### ANSIBLE VERSION

```
ansible 2.4.0 (pep8-legacy 6f923e67c7) last updated 2017/07/07 17:18:34 (GMT +100)
  config file = None
  configured module search path = [u'/Users/tom/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/tom/repos/github/ansible/lib/ansible
  executable location = /Users/tom/repos/github/ansible/bin/ansible
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```

##### ADDITIONAL INFORMATION

```

```

2017-07-11 15:43 UTC, s-hertel approved these changes

2017-07-11 18:45 UTC, ryansb requested changes
One last tweak, then LGTM.

2017-07-11 18:45 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/ec2_ami.py
> +            if (('InvalidAMIID.NotFound' not in e.error_code and 'InvalidAMIID.Unavailable' not in e.error_code) and wait and i == wait_timeout - 1):
These added parens aren't needed.

2017-07-12 01:23 UTC, willthames commented
https://github.com/ansible/ansible/blob/devel/CODING_GUIDELINES.md#pep8-and-basic-style-checks says that we don't really do PRs just for PEP8

The reason I point this out is that, unless someone has reviewed https://ansible.sivel.net/pr/byfile.html for PRs that might clash, this could cause merge conflicts with PRs that are otherwise good to merge, increasing an already frustrating merge cycle.

2017-07-12 10:54 UTC, aioue commented
Understood. Closing.

2017-07-12 10:54 UTC, closed without merging