added module ec2_snapshot_copy
ansible/ansible pull request #26578
Opened 2017-07-10 06:47 UTC by Deepakkothandan

##### SUMMARY
The module allows to copy EC2 snapshots from one region to another region.

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
ec2_snapshot_copy

##### ANSIBLE VERSION
```
Ansible Version: 2.4.0
```

2017-07-27 15:55 UTC, dchsueh commented
Could you add support for param wait_timeout please?  Thanks!

2017-07-27 20:34 UTC, s-hertel requested changes
Thanks for working on this!

2017-07-27 20:34 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/ec2_snapshot_copy.py
> +    except NoCredentialsError:
Can remove this one. If there is a credentials issue it should happen when the connection is created, I think.

2017-07-27 20:34 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/ec2_snapshot_copy.py
> +        module.fail_json(msg='An error occurred waiting for the snapshot to become available. (%s)' % we.reason)
Can you add we.message if it adds anything helpful?

2017-07-27 20:34 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/ec2_snapshot_copy.py
> +        module.fail_json(msg=ce.message)
You can add traceback and ce.response to this. Helpful for future debugging.
https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/GUIDELINES.md#boto3-2

2017-07-27 20:34 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/ec2_snapshot_copy.py
> +    except Exception as e:
Since it's just boto calls in this try/except you can get rid of this one.

2017-07-27 20:34 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/ec2_snapshot_copy.py
> +        module.exit_json(changed=True, snapshot_id=snapshot_id)
This line doesn't need to be in the try/except.

2017-07-27 20:34 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/ec2_snapshot_copy.py
> +    except NoCredentialsError as e:
botocore.exceptions.ProfileNotFound may also be raised

2017-07-27 20:34 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/ec2_snapshot_copy.py
> +        region, ec2_url, aws_connect_kwargs = get_aws_connection_info(module, boto3=True)
This doesn't need to be in the try/except.
After it you should also do something like
```
if not region:
    module.fail_json(msg="region must be specified")
```

2017-08-29 21:34 UTC, s-hertel approved these changes

2017-08-29 22:11 UTC, merged