[WIP] changed collection arg to argregate on 2.4 network modules
ansible/ansible pull request #26649
Opened 2017-07-11 15:19 UTC by newswangerd

##### SUMMARY

##### ISSUE TYPE

 - Network Pull Request

##### COMPONENT NAME

- network modules

##### ANSIBLE VERSION

```
ansible 2.4.0 (collection-to-agregate 0eb6ecb932) last updated 2017/07/11 11:17:03 (GMT -400)
  config file = None
  configured module search path = [u'/Users/dnewswan/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/dnewswan/code/ansible/lib/ansible
  executable location = /Users/dnewswan/code/ansible/bin/ansible
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```

##### ADDITIONAL INFORMATION

```

```

2017-07-11 16:21 UTC, privateip requested changes

2017-07-11 16:21 UTC, privateip commented on lib/ansible/modules/network/eos/eos_user.py
> -        users=dict(type='list', aliases=['collection']),
change argument to `aggregate` and add alias to `users`

2017-07-11 16:21 UTC, privateip commented on lib/ansible/modules/network/junos/junos_user.py
> +        users=dict(type='list', aliases=['collection', 'aggregate']),
swap `aggregate` and `users` so the argument is `aggregate` and the alias is `users`

2017-07-11 16:21 UTC, privateip commented on lib/ansible/modules/network/nxos/nxos_user.py
> +        users=dict(type='list', no_log=True, aliases=['collection', 'aggregate']),
same as earlier about swapping

2017-07-11 18:26 UTC, newswangerd commented on lib/ansible/modules/network/eos/eos_user.py
> -        users=dict(type='list', aliases=['collection']),
I made the change. Not sure why github isn't registering it.

2017-07-14 18:30 UTC, newswangerd commented
need to change collections in tests

2017-07-24 15:37 UTC, newswangerd commented
Can't test the following modules because tests are already failing:
* ios_user
* junos_user
* iosxr_user
* net_user
* nxos_user
* vyos_user

2017-07-26 14:09 UTC, merged