python3k compatibility for ec2_vpc_net_facts module
ansible/ansible pull request #26652
Opened 2017-07-11 17:02 UTC by silviot

##### SUMMARY
python3k compatibility for ec2_vpc_net_facts module

The `StandardError` exception is no longer present in python 3.
Use `Exception` instead, re-raising in case the exception was
not also part of `StandardError`.

See https://docs.python.org/2/library/exceptions.html#exceptions.StandardError

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
ec2_vpc_net_facts

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel b880ad8566) last updated 2017/07/11 18:53:06 (GMT +200)
  config file = /.../.../redacted/ansible.cfg
  configured module search path = ['/.../.../.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /.../.../redacted/lib/ansible
  executable location = /.../.../redacted/bin/ansible
  python version = 3.5.2 (default, Nov 17 2016, 17:05:23) [GCC 5.4.0 20160609]
```

2017-07-11 20:36 UTC, s-hertel requested changes

2017-07-11 20:36 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/ec2_vpc_net_facts.py
> +        except (StopIteration, GeneratorExit, KeyboardInterrupt, SystemExit):
Thanks for making this Python3 compatible. You can remove this line and the line below. Catching boto.exception.NoAuthHandlerFound and Exception should be fine.

2017-07-27 15:58 UTC, s-hertel approved these changes

2017-08-11 17:05 UTC, silviot commented
Already fixed in 225fa5d09229bd673ea76f8b8bc8e7d8b50d2399

2017-08-11 17:05 UTC, closed without merging