Initial support for AWS Batch Job Queues
ansible/ansible pull request #26701
Opened 2017-07-12 13:41 UTC by jonmer85

SUMMARY

This adds automation support for the following AWS Batch Job Queues
ISSUE TYPE

Feature Pull Request
COMPONENT NAME

amazon module

ANSIBLE VERSION

ansible 2.2.2.0
config file =
configured module search path = Default w/o overrides

2017-08-03 21:33 UTC, ryansb requested changes

2017-08-03 21:33 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/batch_job_queue.py
> +module: batch_job_queue
Same - `aws_batch_job_queue`

2017-09-15 20:33 UTC, supreethSonos commented on lib/ansible/modules/cloud/amazon/batch_job_queue.py
> +module: batch_job_queue
fixed

2018-01-29 18:36 UTC, s-hertel approved these changes

2018-01-29 19:01 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/aws_batch_job_queue.py
> +# Copyright (c) 2017 Jon Meran <jonathan.meran@sonos.com>
Needs to follow copyright guidelines http://docs.ansible.com/ansible/latest/dev_guide/developing_modules_documenting.html#copyright

2018-01-30 22:06 UTC, ryansb approved these changes

2018-01-30 22:22 UTC, merged