Initial support for AWS Batch Job Definitions
ansible/ansible pull request #26700
Opened 2017-07-12 13:39 UTC by jonmer85

SUMMARY

This adds automation support for the following AWS Batch Job Definitions
ISSUE TYPE

Feature Pull Request
COMPONENT NAME

amazon module

ANSIBLE VERSION

ansible 2.2.2.0
config file =
configured module search path = Default w/o overrides

2017-08-03 21:30 UTC, ryansb requested changes

2017-08-03 21:30 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/batch_job_definition.py
> +module: batch_job_definition
Same for this one: since there's a flat namespace, please prefix this as `aws_batch_job_definition`.

2017-08-03 21:30 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/batch_job_definition.py
> +class AWSConnection:
Since this is only ever used once, I think it would be easier to read to just create the different client/resource connections and pass those in.

2017-09-15 20:30 UTC, supreethSonos commented on lib/ansible/modules/cloud/amazon/batch_job_definition.py
> +module: batch_job_definition
fixed

2018-01-29 15:46 UTC, s-hertel approved these changes

2018-01-29 19:00 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/aws_batch_job_definition.py
> +# Copyright (c) 2017 Jon Meran <jonathan.meran@sonos.com>
Should follow copyright guideline http://docs.ansible.com/ansible/latest/dev_guide/developing_modules_documenting.html#copyright and have author info in module author field.

2018-01-30 22:16 UTC, ryansb approved these changes

2018-01-30 22:31 UTC, ryansb commented
Merged as 05f765bda0

2018-01-30 22:31 UTC, closed without merging