Amazon kms_facts module
ansible/ansible pull request #26733
Opened 2017-07-13 05:27 UTC by willthames

##### SUMMARY
Add a module for KMS facts

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
kms_facts

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel 0b784c65b1) last updated 2017/07/13 15:27:10 (GMT +1000)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/will/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/will/src/ansible/lib/ansible
  executable location = /home/will/src/ansible/bin/ansible
  python version = 2.7.13 (default, May 10 2017, 20:04:28) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```

##### ADDITIONAL INFORMATION

2017-07-13 17:12 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/kms_facts.py
> +        functionality to other modules. Standard tag filters (C(tag-key), C(tag-value) and
Is C() only for files?
http://docs.ansible.com/ansible/dev_guide/developing_modules_documenting.html#formatting-options

2017-07-13 17:43 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/kms_facts.py
> +        functionality to other modules. Standard tag filters (C(tag-key), C(tag-value) and
Is C() only for files?
http://docs.ansible.com/ansible/dev_guide/developing_modules_documenting.html#formatting-options

2017-07-13 17:43 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/kms_facts.py
> +        except botocore.exceptions.ClientError as e:
It looks like the error response for keys that don't have the option of having tags and insufficient permissions for getting tags are the same. Maybe we shouldn't fail here if e.response['Error']['Code'] == 'AccessDeniedException' and just let the keys be empty. I'm not sure if there's a way of differentiating between the permissions and the acceptable key options.

2017-07-13 17:43 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/kms_facts.py
> +    return boto3_tag_list_to_ansible_dict(tags)
I think this should be `return boto3_tag_list_to_ansible_dict(tags, 'TagKey', 'TagValue')` to get any tags back
http://boto3.readthedocs.io/en/latest/reference/services/kms.html#list_resource_tags

2017-07-13 17:43 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/kms_facts.py
> +    module.exit_json(keys=[camel_dict_to_snake_dict(key) for key in filtered])
The tag keys are being lowercased (maybe not a big deal, but I spent 10 minutes trying to figure out why filtering by them wasn't working).

2017-07-13 23:29 UTC, willthames commented on lib/ansible/modules/cloud/amazon/kms_facts.py
> +    module.exit_json(keys=[camel_dict_to_snake_dict(key) for key in filtered])
You've done more testing on the tag functionality than I have, sorry!

It's always best to do camel_to_snake before doing tag conversion, I should know this by now.

2017-07-13 23:30 UTC, willthames commented on lib/ansible/modules/cloud/amazon/kms_facts.py
> +        functionality to other modules. Standard tag filters (C(tag-key), C(tag-value) and
`C()` is for option values. Here `filters` is the key so `tag-key` is part of the value (but also part of a key in the value). It's arguable, I'd say.

2017-07-14 00:27 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/kms_facts.py
> +        functionality to other modules. Standard tag filters (C(tag-key), C(tag-value) and
I apparently cannot read.

2017-07-14 12:40 UTC, s-hertel approved these changes

2017-07-14 12:41 UTC, s-hertel commented
shipit

2017-07-14 12:47 UTC, ryansb requested changes

2017-07-14 12:47 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/aws_kms_facts.py
> +    return paginator.paginate().build_full_result()['Aliases']
The other `get_kms_*` functions return the full response. Can you either return the full response here, or standardize on only returning the objects?

2017-10-22 23:56 UTC, willthames commented
!needs_revision

2017-10-26 14:27 UTC, s-hertel commented
I think rebasing resets the ansibot's stale_review label process, and then it takes another [week](https://github.com/ansible/ansibullbot/blob/c665e5b0e00bff15bd68457883baccdfefd60a7e/ansibullbot/triagers/plugins/needs_revision.py#L359) to remove needs_revision and add stale_review.

2017-10-27 03:24 UTC, willthames commented
@jctanner mentioned that the bot won't remove needs_revision until @ryansb's rejection has been removed.

2017-10-27 13:38 UTC, ryansb approved these changes

2017-10-27 20:15 UTC, s-hertel commented
bot_status

2017-10-29 23:10 UTC, merged