[WIP] ecs_taskdefinition idempotency - fixes 22547
ansible/ansible pull request #26752
Opened 2017-07-13 13:49 UTC by s-hertel

##### SUMMARY
* Fixes 22547; essential and port_mapping['protocol'] don't need to be specified and default to True and 'tcp' respectively; compare default values if they are omitted
* Removed unused requirements (boto, json)
* Pep8
* TODO write tests

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/modules/cloud/amazon/ecs_taskdefinition.py

##### ANSIBLE VERSION
```
2.4.0
```

##### ADDITIONAL INFORMATION

```

```

2017-07-13 13:50 UTC, s-hertel commented
cc @simplesteph

2017-07-13 19:37 UTC, ryansb requested changes

2017-07-13 19:37 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/ecs_taskdefinition.py
> -                existing_volumes = td.get('volumes', []) or []
This is actually useful, since a `.get('volumes', [])` can still return `None` if the value `volumes` is explicitly None, as opposed to nonexistent.

2017-07-13 19:37 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/ecs_taskdefinition.py
> +            elif 'family' in module.params and module.params['family'] is not None and 'revision' in module.params and module.params['revision'] is not None:
It seems like this could be `if module.params.get('family') is not None and module.params.get('revision') is not None`

2017-07-13 22:32 UTC, simplesteph commented
I think it is worth isolating all this and having a bunch of test cases to validate the behaviour if you don't mind. I remember a lot of cases, based on ports (missing hostport for example) during which idempotency doesn't work today

2017-07-14 00:15 UTC, s-hertel commented
@simplesteph Agreed, hence [WIP]. Would you like basic currently-passing unit tests in a separate PR to merge before this and add some in this pull request to validate this fix (since we don't merge broken tests)?

2017-07-14 06:34 UTC, simplesteph commented
I'm not sure the ansible way of doing things, but I don't mind just having the unit tests in this pr

2017-10-27 05:12 UTC, willthames commented
@s-hertel just came across this issue today, would be good to get this merged.

2017-12-08 14:48 UTC, gundalow commented
As agreed in 2017-12-07 Core meeting, we've done bulk pep8 fixes across all modules in `devel`.

This was done in https://github.com/ansible/ansible/pull/33682 and https://github.com/ansible/ansible/pull/33690 which have been merged into `devel`. because of this you will need to rebase your PR. Thanks in advance.

2019-03-01 22:57 UTC, closed without merging