WIP Add ios_logging implementation module
ansible/ansible pull request #26785
Opened 2017-07-14 06:22 UTC by trishnaguha

Signed-off-by: Trishna Guha <trishnaguha17@gmail.com>

##### SUMMARY

ios_logging

##### ISSUE TYPE

 - Feature Pull Request
 
##### COMPONENT NAME

modules/network/ios/ios_logging
##### ANSIBLE VERSION

```
devel 2.4
```

2017-07-14 12:15 UTC, rcarrillocruz requested changes

2017-07-14 12:15 UTC, rcarrillocruz commented on lib/ansible/modules/network/ios/ios_logging.py
> +    if 'collection' in module.params and module.params['collection']:
this should be aggregate now, change it here , argspec and docstrings

2017-07-14 15:14 UTC, ganeshrn commented on lib/ansible/modules/network/ios/ios_logging.py
> +def validate_size(value, module):
Seems like this function is not called from within the module.
You are missing the validate function that calls validation on each param.
Reference: https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/junos/junos_vlan.py#L131-L137
https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/junos/junos_vlan.py#L175

2017-07-14 15:15 UTC, ganeshrn requested changes
Comment added at L111 in ios_logging.py

2017-07-17 05:44 UTC, trishnaguha commented
@rcarrillocruz @ganeshrn updated.

2017-07-17 07:09 UTC, ganeshrn approved these changes

2017-07-17 07:15 UTC, merged

2017-10-01 23:34 UTC, os4mike commented
Many of the prior IOS versions only support  " | include " rather than  " | section " . In order to make my recent change work I've locally amended the map_config_to_obj function to replace the 'section' command with 'include' as when it comes to logging, their outputs are identical. Any thoughts on the matter for future releases?