Add setfacl option --no-mask (#26796)
ansible/ansible pull request #26840
Opened 2017-07-15 00:58 UTC by silvinux

##### SUMMARY

##### ISSUE TYPE

 - Feature Pull Request
 - New Module Pull Request
 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME

##### ANSIBLE VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

2017-07-15 12:34 UTC, silvinux commented
needs_contributor

2017-07-15 13:01 UTC, silvinux commented
@ansibot  needs_contributor

2017-07-15 14:44 UTC, silvinux commented
needs_contributor

2017-07-15 14:46 UTC, silvinux commented
ready_for_review

2017-07-17 13:12 UTC, silvinux commented
@ansibot  ready_for_review

2017-07-17 14:57 UTC, alikins requested changes

2017-07-17 14:57 UTC, alikins commented on lib/ansible/modules/files/acl.py
> +- acl: name=/etc/foo.conf entity=joe etype=user permissions="r" state=present
Why change the example docs? The yaml dict style is the preferred format for EXAMPLES

2017-07-17 14:57 UTC, alikins commented on lib/ansible/modules/files/acl.py
> +from ansible.module_utils.basic import *
`from ansible.module_utils.basic import *` is deprecated now.

See http://docs.ansible.com/ansible/dev_guide/developing_modules_checklist.html

> Import ansible.module_utils code in the same place as you import other libraries. In older code, this was done at the bottom of the file but that’s no longer needed.

2017-07-17 14:59 UTC, alikins commented
ping @bcoca @astorije

2017-07-18 18:55 UTC, mattclay commented
The test `ansible-test sanity --test pep8` failed with the following error:

```
test/sanity/pep8/legacy-files.txt:230:1: A201 Remove "lib/ansible/modules/files/acl.py" since it passes the current rule set
```

2017-10-25 11:14 UTC, VojtechMyslivec commented
I have rebase it locally on v2.4.1.0-0.4.rc2 tag and it seems to work well.

@silvinux could you prepare the branch for merge please? I really need this feature.

Thanks!

2017-10-25 13:40 UTC, silvinux commented
@VojtechMyslivec I'll take a look this week. I've forgot it.

2019-01-11 16:52 UTC, maxamillion commented
Closing because changes were requested over a year ago and the PR seems to be abandoned. Please feel free to reopen if you desire to continue this work.

2019-01-11 16:52 UTC, closed without merging