add Fusionlayer Infinity ansible module into ansible package
ansible/ansible pull request #26855
Opened 2017-07-15 14:04 UTC by MeganLiu

##### SUMMARY

add Fusionlayer company Infinity ansible module into ansible package

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

infinity
##### ANSIBLE VERSION

```
ansible --2.4
```

##### ADDITIONAL INFORMATION

I am submit the first Pull request for Fusionlayer company Infinity software to support ansible usage.

```

```

2017-07-15 14:57 UTC, toshywoshy commented
You import "requests" and "json" in the beginning of your module, the request module is not build in by default, and gives an error, use the "fetch_url" module from the builtin utils to avoid these problems, also I think there is also a builtin module for json, using the builtin means less maintenance for you
eg : from ansible.module_utils.urls import fetch_url

2017-07-15 15:23 UTC, MeganLiu commented
@toshywoshy  thanks   for the suggestion. I will change it right now.

2017-07-15 18:10 UTC, MeganLiu commented
Get error when trying to use ansible.module_utils.urls


    results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars, wrap_async=wrap_async))
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 632, in _execute_module
    (module_style, shebang, module_data, module_path) = self._configure_module(module_name=module_name, module_args=module_args, task_vars=task_vars)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 157, in _configure_module
    task_vars=task_vars, module_compression=self._play_context.module_compression)
  File "/usr/lib/python2.7/site-packages/ansible/executor/module_common.py", line 796, in modify_module
    (b_module_data, module_style, shebang) = _find_module_utils(module_name, b_module_data, module_path, module_args, task_vars, module_compression)
  File "/usr/lib/python2.7/site-packages/ansible/executor/module_common.py", line 678, in _find_module_utils
    recursive_finder(module_name, b_module_data, py_module_names, py_module_cache, zf)
  File "/usr/lib/python2.7/site-packages/ansible/executor/module_common.py", line 504, in recursive_finder
    msg.append('either %s.py or %s.py' % (py_module_name[-1], py_module_name[-2]))
IndexError: tuple index out of range

2017-07-17 15:13 UTC, alikins commented
The module is in the wrong path (lib/ansible/module_utils/infinity/infinity.py). It needs to be moved to the modules path (lib/ansible/modules/*/infinity.py). I'm not sure what category this fits in (the '*') but whatever is approriate.

2017-07-17 15:13 UTC, alikins requested changes
The infinity.py module is in the wrong path. 

It needs to be moved to lib/ansible/modules/ instead of lib/ansible/module_utils/

2017-07-18 06:04 UTC, MeganLiu commented
Thanks,I will change the path of the file.:)
Meirong

2017年7月17日 18:56，"Adrian Likins" <notifications@github.com>写道：

> The module is in the wrong path (lib/ansible/module_utils/infinity/infinity.py).
> It needs to be moved to the modules path (lib/ansible/modules/*/infinity.py).
> I'm not sure what category this fits in (the '*') but whatever is
> approriate.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ansible/ansible/pull/26855#issuecomment-315784952>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AMEij7yxs6Sqy9FgneUtuF-NNRYAGSXyks5sO4LtgaJpZM4OZBi7>
> .
>

2017-07-18 06:24 UTC, MeganLiu commented
Yes,it's about IPAddress management.Do  you mean this category?

2017年7月17日 18:56，"Adrian Likins" <notifications@github.com>写道：

> The module is in the wrong path (lib/ansible/module_utils/infinity/infinity.py).
> It needs to be moved to the modules path (lib/ansible/modules/*/infinity.py).
> I'm not sure what category this fits in (the '*') but whatever is
> approriate.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ansible/ansible/pull/26855#issuecomment-315784952>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AMEij7yxs6Sqy9FgneUtuF-NNRYAGSXyks5sO4LtgaJpZM4OZBi7>
> .
>

2017-07-19 18:39 UTC, MeganLiu commented
based on the review suggestion, I tried to use ansible built-in module "uri" to send rest api request. However, the "url" "post" method could not send the data to server side.
Is it okay that I use python library " urllib2 "  to send rest api call?
Looking forward to your suggestion. Thanks.

2017-07-24 20:59 UTC, MeganLiu commented
hi, 
I have made code changes to remove dependency on requests module. Could you please let me know  what do I need to do next?

2017-07-25 10:47 UTC, MeganLiu commented
HI
I tried to use   ansible.url to post data but it did not work . So I use python  urllib2 to post data.
In this situation, what should I do ? report a bug to url and wait for reply ?

2017-07-27 08:08 UTC, MeganLiu commented
Hi, 
what needs to be done next ?

2017-07-27 10:52 UTC, MeganLiu commented
Thanks for the feedback. Now the file is in the path  "lib/ansible/modules/network/infinity"

2017-07-28 07:00 UTC, MeganLiu commented
Hi, Alikins

for the shippable testing, 30488 failure, could you please let me know what should I do?  Thanks.

2017-07-28 09:38 UTC, gundalow requested changes
You can test this locally with

`./test/runner/ansible-test sanity --test validate-modules infinity` So you can identify and test your fixes locally without having to wait on Shippable.

I believe if you read http://docs.ansible.com/ansible/latest/dev_guide/developing_modules_documenting.html that will answer most of your questions.

2017-07-28 09:38 UTC, gundalow commented on lib/ansible/modules/network/infinity/infinity.py
> +    choices:  [ 'reserve_next_available_ip', 'release_ip' , 'delete_network',
This might be breaking the yaml parser, try rewriting as

```
choices:
  - reserve_next_available_ip
  - release_ip

```

2017-07-28 09:38 UTC, gundalow commented on lib/ansible/modules/network/infinity/infinity.py
> +version_added: "1.0"
`"2.4"`

2017-07-28 09:38 UTC, gundalow commented on lib/ansible/modules/network/infinity/infinity.py
> +from ansible.module_utils.basic import *
Don't import `*`, import only what you need

See: http://docs.ansible.com/ansible/latest/dev_guide/developing_modules_documenting.html#python-imports

2017-07-28 09:38 UTC, gundalow commented on lib/ansible/modules/network/infinity/infinity.py
> +short_description: manage Infinity IPAM using  Web API
`Manage Infinity IPAM using  Web API`

2017-07-28 09:38 UTC, gundalow commented on lib/ansible/modules/network/infinity/infinity.py
> +      - Infinity IP
or hostname?

2017-07-28 09:38 UTC, gundalow commented on lib/ansible/modules/network/infinity/infinity.py
> +      -  username to access Infinity
`- Username to access Infinity.`

2017-07-28 09:38 UTC, gundalow commented on lib/ansible/modules/network/infinity/infinity.py
> +      - Must be indicated as a network_id
"indicated" how/

2017-07-28 09:38 UTC, gundalow commented on lib/ansible/modules/network/infinity/infinity.py
> +    required: False
`required: False` lines can be removed as that's the default.

2017-07-28 09:38 UTC, gundalow commented on lib/ansible/modules/network/infinity/infinity.py
> +RETURN = """
Have a look at the `RETURN` block in another module along side the documentation at http://docs.ansible.com/ansible/latest/dev_guide/developing_modules_documenting.html#return-block

2017-07-28 09:38 UTC, gundalow commented on lib/ansible/modules/network/infinity/infinity.py
> +        "password": {
You need `no_log='True'` here as well

2017-07-28 09:38 UTC, gundalow commented on lib/ansible/modules/network/infinity/infinity.py
> +    fields = {
This seems a lot longer and less readable that the standard way of defining the `argument_spec`.
https://github.com/gundalow/ansible/blob/docs-argspec/docs/docsite/rst/dev_guide/developing_modules_general.rst#main-and-ansiblemodule-argument-spec

2017-07-28 09:38 UTC, gundalow commented on lib/ansible/modules/network/infinity/infinity.py
> +    # mutually_exclusive = [ ["network_id", "network_name"] ]
Is this needed?

If they are then they should be added to the `DOCUMENTATION`

For usage see https://github.com/gundalow/ansible/blob/docs-argspec/docs/docsite/rst/dev_guide/developing_modules_general.rst#main-and-ansiblemodule-argument-spec

http://docs.ansible.com/ansible/latest/dev_guide/developing_modules_documenting.html#documentation-block

2017-07-28 09:38 UTC, gundalow commented on lib/ansible/modules/network/infinity/infinity.py
> +    result2 = ''
`result2` doesn't seem like a very clear variable name. It's difficult to follow what's going on here

2017-07-28 09:38 UTC, gundalow commented on lib/ansible/modules/network/infinity/infinity.py
> +                result2 = 'There is an error in calling method reserve_next_available_ip'
Shouldn't this be a failure, rather than just `exit_json`?

2017-07-28 09:38 UTC, gundalow commented on lib/ansible/modules/network/infinity/infinity.py
> +                'add_network',
Does this not work?
If so delete it or fix it in this PR

2017-07-28 09:38 UTC, gundalow commented on lib/ansible/modules/network/infinity/infinity.py
> +# !/usr/bin/python
`#!/usr/bin/python`

2017-07-28 09:38 UTC, gundalow commented on lib/ansible/modules/network/infinity/infinity.py
> +
All modules must have the following sections defined in this order:

All modules must have the following sections defined in this order:

Copyright
ANSIBLE_METADATA
DOCUMENTATION
EXAMPLES
RETURNS
Python imports


See http://docs.ansible.com/ansible/latest/dev_guide/developing_modules_documenting.html

2017-07-28 09:38 UTC, gundalow commented on lib/ansible/modules/network/infinity/infinity.py
> +has_url_parse = True
Need to move *after* `RETURN`

2017-08-01 06:13 UTC, MeganLiu commented
Hi, John

Many thanks for the help :). I will make the change.
Meirong

On Fri, Jul 28, 2017 at 12:39 PM, John R Barker <notifications@github.com>
wrote:

> *@gundalow* requested changes on this pull request.
>
> You can test this locally with
>
> ./test/runner/ansible-test sanity --test validate-modules infinity So you
> can identify and test your fixes locally without having to wait on
> Shippable.
>
> I believe if you read http://docs.ansible.com/ansible/latest/dev_guide/
> developing_modules_documenting.html that will answer most of your
> questions.
> ------------------------------
>
> In lib/ansible/modules/network/infinity/infinity.py
> <https://github.com/ansible/ansible/pull/26855#discussion_r130047847>:
>
> > +      - Infinity IP
> +    required: True
> +  username:
> +    description:
> +      -  username to access Infinity
> +      - The user must have Rest API privileges
> +    required: True
> +  password:
> +    description:
> +      - Infinity password
> +    required: True
> +  action:
> +    description:
> +      - Action to perform
> +    required: True
> +    choices:  [ 'reserve_next_available_ip', 'release_ip' , 'delete_network',
>
> This might be breaking the yaml parser, try rewriting as
>
> choices:
>   - reserve_next_available_ip
>   - release_ip
>
>
> ------------------------------
>
> In lib/ansible/modules/network/infinity/infinity.py
> <https://github.com/ansible/ansible/pull/26855#discussion_r130047891>:
>
> > +    has_url_parse = False
> +    # print(" using python2 librarary")
> +    import urllib2 as urllib2_request
> +    import urllib
> +    import base64
> +
> +from ansible.module_utils.basic import *
> +from ansible.module_utils.urls import *
> +
> +
> +DOCUMENTATION = """
> +module: infinity
> +short_description: manage Infinity IPAM using  Web API
> +description:
> +  - Manage Infinity IPAM using Web API
> +version_added: "1.0"
>
> "2.4"
> ------------------------------
>
> In lib/ansible/modules/network/infinity/infinity.py
> <https://github.com/ansible/ansible/pull/26855#discussion_r130047975>:
>
> > +has_url_parse = True
> +try:
> +    # python3
> +    import urllib.request as urllib_request
> +    import urllib.parse as urllib_parse
> +    from urllib.request import AbstractHTTPHandler
> +    has_url_parse = True
> +except ImportError as e:
> +    # python2
> +    has_url_parse = False
> +    # print(" using python2 librarary")
> +    import urllib2 as urllib2_request
> +    import urllib
> +    import base64
> +
> +from ansible.module_utils.basic import *
>
> Don't import *, import only what you need
>
> See: http://docs.ansible.com/ansible/latest/dev_guide/developing_modules_
> documenting.html#python-imports
> ------------------------------
>
> In lib/ansible/modules/network/infinity/infinity.py
> <https://github.com/ansible/ansible/pull/26855#discussion_r130048025>:
>
> > +    has_url_parse = True
> +except ImportError as e:
> +    # python2
> +    has_url_parse = False
> +    # print(" using python2 librarary")
> +    import urllib2 as urllib2_request
> +    import urllib
> +    import base64
> +
> +from ansible.module_utils.basic import *
> +from ansible.module_utils.urls import *
> +
> +
> +DOCUMENTATION = """
> +module: infinity
> +short_description: manage Infinity IPAM using  Web API
>
> Manage Infinity IPAM using Web API
> ------------------------------
>
> In lib/ansible/modules/network/infinity/infinity.py
> <https://github.com/ansible/ansible/pull/26855#discussion_r130048060>:
>
> > +from ansible.module_utils.basic import *
> +from ansible.module_utils.urls import *
> +
> +
> +DOCUMENTATION = """
> +module: infinity
> +short_description: manage Infinity IPAM using  Web API
> +description:
> +  - Manage Infinity IPAM using Web API
> +version_added: "1.0"
> +author:
> +  - "Meirong Liu"
> +options:
> +  server:
> +    description:
> +      - Infinity IP
>
> or hostname?
> ------------------------------
>
> In lib/ansible/modules/network/infinity/infinity.py
> <https://github.com/ansible/ansible/pull/26855#discussion_r130048101>:
>
> > +DOCUMENTATION = """
> +module: infinity
> +short_description: manage Infinity IPAM using  Web API
> +description:
> +  - Manage Infinity IPAM using Web API
> +version_added: "1.0"
> +author:
> +  - "Meirong Liu"
> +options:
> +  server:
> +    description:
> +      - Infinity IP
> +    required: True
> +  username:
> +    description:
> +      -  username to access Infinity
>
> - Username to access Infinity.
> ------------------------------
>
> In lib/ansible/modules/network/infinity/infinity.py
> <https://github.com/ansible/ansible/pull/26855#discussion_r130048190>:
>
> > +    required: True
> +  password:
> +    description:
> +      - Infinity password
> +    required: True
> +  action:
> +    description:
> +      - Action to perform
> +    required: True
> +    choices:  [ 'reserve_next_available_ip', 'release_ip' , 'delete_network',
> +    'add_network' ,  'reserve_network', 'release_network', 'get_network_id'],
> +
> +  network_id:
> +    description:
> +      - Network ID
> +      - Must be indicated as a network_id
>
> "indicated" how/
> ------------------------------
>
> In lib/ansible/modules/network/infinity/infinity.py
> <https://github.com/ansible/ansible/pull/26855#discussion_r130048279>:
>
> > +  password:
> +    description:
> +      - Infinity password
> +    required: True
> +  action:
> +    description:
> +      - Action to perform
> +    required: True
> +    choices:  [ 'reserve_next_available_ip', 'release_ip' , 'delete_network',
> +    'add_network' ,  'reserve_network', 'release_network', 'get_network_id'],
> +
> +  network_id:
> +    description:
> +      - Network ID
> +      - Must be indicated as a network_id
> +    required: False
>
> required: False lines can be removed as that's the default.
> ------------------------------
>
> In lib/ansible/modules/network/infinity/infinity.py
> <https://github.com/ansible/ansible/pull/26855#discussion_r130048460>:
>
> > +    default: -1
> + network_type:
> +    description:
> +      - network type defined by     Infinity
> +    required: False
> +    "choices": ['lan', 'shared_lan', 'supernet']
> +    default: "lan"
> + network_family:
> +    description:
> +      - network family defined by  Infinity, e.g. IPv4, IPv6 , Dual stack
> +    required: False
> +    "choices": ['4', '6', 'dual']
> +    default: "4"
> +
> +"""
> +RETURN = """
>
> Have a look at the RETURN block in another module along side the
> documentation at http://docs.ansible.com/ansible/latest/dev_guide/
> developing_modules_documenting.html#return-block
> ------------------------------
>
> In lib/ansible/modules/network/infinity/infinity.py
> <https://github.com/ansible/ansible/pull/26855#discussion_r130048653>:
>
> > +            resource_url=resource_url,
> +            stat_codes=[200],
> +            payload_data=payload_data)
> +        return response
> +
> +
> +def main():
> +
> +    fields = {
> +        "server": {
> +            "required": True,
> +            "type": "str"},
> +        "username": {
> +            "required": True,
> +            "type": "str"},
> +        "password": {
>
> You need no_log='True' here as well
> ------------------------------
>
> In lib/ansible/modules/network/infinity/infinity.py
> <https://github.com/ansible/ansible/pull/26855#discussion_r130048851>:
>
> > +            'network_address': network_address,
> +            'network_size': network_size,
> +            'network_family': network_family,
> +            'network_type': network_type,
> +            'network_location': network_location}
> +        response = self._get_api_call_ansible_handler(
> +            method='post',
> +            resource_url=resource_url,
> +            stat_codes=[200],
> +            payload_data=payload_data)
> +        return response
> +
> +
> +def main():
> +
> +    fields = {
>
> This seems a lot longer and less readable that the standard way of
> defining the argument_spec.
> https://github [...]

2017-08-07 08:45 UTC, MeganLiu commented
Thanks for the feedback :). I am making the changes.

2017-08-07 10:51 UTC, MeganLiu commented
Could some provide the suggestions on what should I do the the failure?

2017-08-07 13:38 UTC, MeganLiu commented
Could you please let me know what needs to be done next when you see my message ?   Thanks.

2017-08-09 18:31 UTC, MeganLiu commented
Could you please let me know what needs to be done next  since the module has passed the test
  ?

2017-08-11 08:29 UTC, MeganLiu commented
hi,  
could you kindly let me know whether I  need to do something else  before merge the code into ansible repo?

2017-08-15 12:25 UTC, gundalow commented
Code looks good, just one minor change, can you please move the files to `modules/net_tools` (rather than `modules/network` thanks.

2017-08-16 08:29 UTC, MeganLiu commented
Thanks for providing the new comments :)  I will change the directory right now

2017-08-16 18:42 UTC, MeganLiu commented
@ansibot  and @gundalow : could you please let me know whether I need to do anything more  before this module is merged into ansible repo ? I would like this module to be shipped with ansible 2.4 release.  I really appreciate your further review comments (if there are) .

2017-08-16 19:09 UTC, gundalow approved these changes

2017-08-16 19:11 UTC, merged

2017-08-16 19:11 UTC, gundalow commented
Merged, will be released in Ansible 2.4.0