Refactor code for find_host_by_cluster_datacenter
ansible/ansible pull request #26859
Opened 2017-07-15 16:11 UTC by Akasurde

##### SUMMARY
Fix adds refactor of code for find_host_by_cluster_datacenter
API in vmware_host and vmware_resource_pool.
Also, adds strict check for cluster and datacenter object find.

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/module_utils/vmware.py
lib/ansible/modules/cloud/vmware/vmware_host.py
lib/ansible/modules/cloud/vmware/vmware_resource_pool.py

##### ANSIBLE VERSION
```
2.4devel
```

2017-07-16 16:18 UTC, Akasurde commented
cc @jctanner

2017-07-17 03:51 UTC, Akasurde commented
ready_for_review

2017-07-27 02:32 UTC, Akasurde commented
ready_for_review

2017-08-09 16:13 UTC, Akasurde commented
cc @dagwieers @pdellaert @dav1x @jctanner Can you please review this ?

2017-08-18 09:01 UTC, dagwieers approved these changes
LGTM, but I haven't tested this. It does have integration tests added, which is always a good thing.

2017-08-18 09:17 UTC, pdellaert requested changes
Some improvements/questions on the use of the datacenter object, rest LGTM

2017-08-18 09:17 UTC, pdellaert commented on lib/ansible/module_utils/vmware.py
> +    cluster = find_cluster_by_name(content, cluster_name)
Shouldn't this be `find_cluster_by_name(content, cluster_name, dc)`? Otherwise, getting the datacenter is a bit useless

2017-08-18 09:17 UTC, pdellaert commented on lib/ansible/modules/cloud/vmware/vmware_resource_pool.py
> +        self.cluster_obj = find_cluster_by_name(self.content, self.cluster)
Shouldn't this be `find_cluster_by_name(self.content, self.cluster, dc_obj)`? As you have the DC, it will speed up the search

2017-08-28 16:36 UTC, dagwieers approved these changes

2017-08-28 16:36 UTC, merged

2017-08-28 16:39 UTC, Akasurde commented
@dagwieers Thanks for review and merge.