rhn_register: fix broken imports and minor changes
ansible/ansible pull request #26878
Opened 2017-07-17 01:13 UTC by pilou-

##### SUMMARY
Fix [broken import]() in `rhn_register` module due to Python 3 incompatibility and minor changes:
- update requirements documentation, improve error message when requirement is missing
- call `logout`
- use `required_*`

These changes are untested.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
packaging/os/rhn_register.py

##### ANSIBLE VERSION

```
ansible-playbook 2.4.0 (devel 30ad30c470) last updated 2017/07/17 03:07:50 (GMT +200)
```

2017-07-31 22:58 UTC, pilou- commented
@jtyr @sysadmind (as randomly selected maintainer of `packaging/os` namespace) could you please review this pull request ? At least two `shipit` comments (from maintainers or namespace maintainers or core team members) are required in order to [automerge](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#community) this pull request.

2017-08-01 08:51 UTC, mkrizek commented on lib/ansible/modules/packaging/os/rhn_register.py
> +            self.server = xmlrpc_client(url)
Am I missing something or is this supposed to be `self.server = xmlrpc_client.ServerProxy(url)`?

2017-08-01 12:46 UTC, sysadmind requested changes

2017-08-01 12:46 UTC, sysadmind commented on lib/ansible/modules/packaging/os/rhn_register.py
> +    - rhnreg_ks, either libxml2 or lxml
I believe this is a yaml array. The hyphen up front indicates an array element. I believe the new requirements should be on a new line.

https://github.com/ansible/ansible/blob/devel/examples/DOCUMENTATION.yml#L31

2017-08-02 23:29 UTC, pilou- commented on lib/ansible/modules/packaging/os/rhn_register.py
> +            self.server = xmlrpc_client(url)
Oups, fixed in https://github.com/ansible/ansible/pull/26878/commits/3c2d147eee21f16abc7cfbe794c60ae154377d79.

2017-08-02 23:29 UTC, pilou- commented on lib/ansible/modules/packaging/os/rhn_register.py
> +    - rhnreg_ks, either libxml2 or lxml
Indeed, fixed in https://github.com/ansible/ansible/pull/26878/commits/b076c80cb208cf34c26a278d1544094cd52c63c2.

2017-08-02 23:32 UTC, pilou- commented
Pull request rebased, both comments have been addressed in separate commits. I have added another commit: unit tests.

ready_for_review

2017-08-03 03:31 UTC, mattclay commented
Closing and re-opening to trigger CI.

2017-08-03 13:04 UTC, pilou- commented
pull-request updated:
- PEP 8 fixed in unit test
- drop support for Python 2.4

2017-08-03 14:06 UTC, pilou- commented
Not sure why this error is detected here, I created a pull request which remove non breaking space in docs/docsite/rst/roadmap/ROADMAP_2_2.rst.

2017-08-03 14:15 UTC, pilou- commented
Last commit updated in order to trigger the CI.

2017-08-03 16:17 UTC, pilou- commented
CI found some Python 3 incompatibility.

2017-08-03 17:45 UTC, alikins commented
https://github.com/ansible/ansible/compare/devel...alikins:pr-26878-py3-mock has some fixes for py3 and Rhn.enable()

2017-08-03 17:52 UTC, alikins approved these changes
LGTM, pending fixing failing py3 tests

2017-08-03 21:52 UTC, pilou- commented
Pull request rebased and updated:
- @alikins you're right, `Rhn.enable` should be mocked
- update units test:
  - XMLRPC `logout` is called now
  - ensure orders of the XMLRPC calls

2017-08-04 08:32 UTC, mkrizek approved these changes

2017-08-04 13:40 UTC, pilou- commented
Get rid of the `needs_revision` label: ready_for_review.

@alikins @mkrizek `approved` pull request status is ignored by the bot, [`shipit`](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#cmd-shipit) command must be used in order to approve a pull request: could you add a comment containing `shipit`? Then:
1. the `shipit` label should automatically be added
2. a core team member would be able to review and potentially merge this pull-request.

2017-08-04 14:09 UTC, alikins commented
shipit :shipit:

2017-08-04 14:12 UTC, merged