Add integration tests and fix nxos_evpn_vni for nxapi provider
ansible/ansible pull request #26913
Opened 2017-07-17 17:35 UTC by saichint

##### SUMMARY
Fixes https://github.com/ansible/ansible/issues/26911
- Adds integration tests
- Fixes nxapi provider issue

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
nxos_evpn_vni

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel b49be56c5b) last updated 2017/07/13 12:38:51 (GMT -400)
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/p2/Projects/nxos_ansible/fix_ansible/lib/ansible
  executable location = /root/p2/Projects/nxos_ansible/fix_ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### ADDITIONAL INFORMATION
- Unit tests results:
```
================================================================== test session starts ==================================================================
platform linux -- Python 3.5.2, pytest-3.1.2, py-1.4.34, pluggy-0.4.0
rootdir: /root/p2/Projects/nxos_ansible/fix_ansible, inifile:
collected 3 items

test_nxos_evpn_vni.py ...

=============================================================== 3 passed in 0.09 seconds ================================================================
```
- Integration tests run against N3k, N7k, N9k, N9k-F on various releases.
```
PLAY RECAP **********************************************************************************************************************************************
camden-nx-2.cisco.com      : ok=47   changed=16   unreachable=0    failed=0                                                                              
dplus-nx-2.cisco.com       : ok=47   changed=16   unreachable=0    failed=0                                                                              
evergreen-nx-2.cisco.com   : ok=47   changed=16   unreachable=0    failed=0                                                                              
freeport-nx-2.cisco.com    : ok=47   changed=16   unreachable=0    failed=0                                                                              
greensboro-nx-2.cisco.com  : ok=47   changed=16   unreachable=0    failed=0                                                                              
n3k-173.cisco.com          : ok=46   changed=16   unreachable=0    failed=0                                                                              
n3x-161.cisco.com          : ok=46   changed=16   unreachable=0    failed=0                                                                              
n7k-99.cisco.com           : ok=46   changed=15   unreachable=0    failed=0                                                                              
n9k-108.cisco.com          : ok=47   changed=16   unreachable=0    failed=0                                                                              
n9k-157.cisco.com          : ok=48   changed=16   unreachable=0    failed=0
```

2017-07-17 18:35 UTC, saichint commented
I did rebasing using https://docs.ansible.com/ansible/dev_guide/developing_rebasing.html
```
git pull --rebase upstream devel
From https://github.com/ansible/ansible
 * branch            devel      -> FETCH_HEAD
Current branch devel is up to date.
```
After that I did git push --force as well.
But it still shows 'needs_rebase' label. Not sure what else I need to do.
Any help from anyone?

2017-07-17 20:49 UTC, saichint commented
never mind, it got removed now.

2017-07-18 12:24 UTC, trishnaguha approved these changes

2017-07-18 12:27 UTC, trishnaguha commented
@saichint mind adding the test task in here https://github.com/ansible/ansible/blob/devel/test/integration/nxos.yaml ?

2017-07-18 15:54 UTC, saichint commented
Added test task to nxos.yaml

2017-07-19 19:08 UTC, saichint commented
@trishnaguha made changes as you suggested. if there are no more comments, could you merge it?
Thanks

2017-07-26 15:51 UTC, Qalthos requested changes

2017-07-26 15:51 UTC, Qalthos commented on lib/ansible/modules/network/nxos/nxos_vrf.py
>      if transport == 'cli':
I would suggest removing the transport check (just so it is clear that the intention is to always ask for JSON), and, as we have this function gatekeeping all the `run_commands()` calls, only annotating the commands with `'output': 'text'` or `'output': 'json'` here. What is here works, but is inconsistent both in process (`'output': 'text'` vs `| json`) and location

2017-07-26 22:28 UTC, saichint commented
@Qalthos Made the changes. Let me know of any more comments

2017-07-27 13:32 UTC, Qalthos approved these changes

2017-07-27 13:32 UTC, merged