EC2 Launch Configuration boto3 return values documentation
ansible/ansible pull request #27039
Opened 2017-07-19 12:05 UTC by wilvk

##### SUMMARY
As requested by @s-hertel , I have documented the return values for the module ec2_lc

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
lib/ansible/modules/cloud/amazon/ec2_lc.py

##### ANSIBLE VERSION

```
ansible 2.4.0 (ec2_lc_boto3_ret_vals bca583adef) last updated 2017/07/19 22:01:29 (GMT +1100)
  config file = None
  configured module search path = [u'/Users/willvk/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/willvk/Source/gits/ansibles/ansible/lib/ansible
  executable location = /Users/willvk/Source/gits/ansibles/ansible/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

2017-07-19 12:50 UTC, samdoran commented
cc @s-hertel

2017-07-26 17:40 UTC, s-hertel requested changes
Just reviewing the documentation. This is a follow-up PR to 26348 which has the rest of the review.

2017-07-26 17:40 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/ec2_lc.py
> +
and security_groups, which is a list

2017-07-26 17:40 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/ec2_lc.py
> +    type: str
type: dict

2017-07-27 11:38 UTC, wilvk commented on lib/ansible/modules/cloud/amazon/ec2_lc.py
> +    type: str
fixed

2017-07-27 11:38 UTC, wilvk commented on lib/ansible/modules/cloud/amazon/ec2_lc.py
> +
added

2017-07-27 15:08 UTC, s-hertel approved these changes

2017-08-25 06:12 UTC, wilvk commented
@s-hertel can this PR be closed now?

2017-08-27 06:46 UTC, closed without merging