ec2_group VPC fixes
ansible/ansible pull request #27038
Opened 2017-07-19 11:53 UTC by willthames

##### SUMMARY
Fix some of the minor flaws in ec2_group identified since the boto3 improvement.

Add tests for all identified problems.

Massively improve information returned by ec2_group and add RETURN to reflect.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
ec2_group

##### ANSIBLE VERSION

```
ansible 2.4.0 (devel 317ad54599) last updated 2017/07/19 21:52:32 (GMT +1000)
  config file = None
  configured module search path = [u'/Users/will/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/will/src/ansible/lib/ansible
  executable location = /Users/will/src/ansible/bin/ansible
  python version = 2.7.13 (default, Dec 18 2016, 07:03:39) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]

```

##### ADDITIONAL INFORMATION

2017-07-19 11:54 UTC, willthames commented
@mattclay this will need DeleteVpc permissions

2017-07-19 12:49 UTC, samdoran commented
cc @s-hertel

2017-07-20 13:56 UTC, s-hertel approved these changes
The tests are passing locally and this looks pretty straightforward.

2017-07-20 13:56 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/ec2_group.py
>      elif 'group_id' in rule and re.match(FOREIGN_SECURITY_GROUP_REGEX, rule['group_id']):
This got fixed one already but was broken during the boto -> boto3 upgrade and I missed it. Can you make this
`elif rule.get('group_id') and re.match(FOREIGN_SECURITY_GROUP_REGEX, rule['group_id']):` please? Refixes if group_id is null. Otherwise the regex fails:
```
"Traceback (most recent call last):\n  File \"/var/folders/by/k8_fbl593dlctgqmwq5wzl2c0000gn/T/ansible_2srlf662/ansible_module_ec2_group.py\", line 836, in <module>\n    main()\n  File \"/var/folders/by/k8_fbl593dlctgqmwq5wzl2c0000gn/T/ansible_2srlf662/ansible_module_ec2_group.py\", line 680, in main\n    group, groups, vpc_id)\n  File \"/var/folders/by/k8_fbl593dlctgqmwq5wzl2c0000gn/T/ansible_2srlf662/ansible_module_ec2_group.py\", line 362, in get_target_from_rule\n    elif 'group_id' in rule and re.match(FOREIGN_SECURITY_GROUP_REGEX, rule['group_id']):\n  File \"/Users/shertel/Workspace/ansible/venv/python3.5.2/lib/python3.5/re.py\", line 163, in match\n    return _compile(pattern, flags).match(string)\nTypeError: expected string or bytes-like object\n",
```
Though a follow up pr is fine too.

2017-07-20 13:56 UTC, s-hertel commented on test/integration/targets/ec2_group/tasks/main.yml
> +          to_port: 8182
It appears between 2.3 and now we lost the functionality provided by https://github.com/ansible/ansible/pull/20806. I suspect that also happened during the boto -> boto3 transition. Let me know if you want to do that or if you want me to make a follow up pr. Either is fine, but that would be another thing we need a test for/need to re-fix.

2017-07-20 13:56 UTC, s-hertel commented on test/integration/targets/ec2_group/tasks/main.yml
> +    - name: add a rule that auto creates another security group
Hurrah for more tests!

2017-07-20 23:14 UTC, willthames commented on test/integration/targets/ec2_group/tasks/main.yml
> +    - name: add a rule that auto creates another security group
Indeed - as I find issues, I'm doing TDD - add a test, make sure it fails, fix the code, make sure the test passes.

2017-07-20 23:14 UTC, willthames commented on lib/ansible/modules/cloud/amazon/ec2_group.py
>      elif 'group_id' in rule and re.match(FOREIGN_SECURITY_GROUP_REGEX, rule['group_id']):
No, I'll fix this now

2017-07-27 15:33 UTC, s-hertel commented
@willthames Looks like there are conflicts now :/ Can you rebase?

@mattclay Can you add permissions please?

2017-07-28 18:35 UTC, s-hertel commented
Now needing permission for ec2:DescribeVpcs.

2017-07-28 22:53 UTC, mattclay commented on test/integration/targets/ec2_group/tasks/main.yml
> +    - name: add a rule that auto creates another security group
Please include cleanup for this security group in the always block.

2017-07-28 22:55 UTC, mattclay commented on test/integration/targets/ec2_group/tasks/main.yml
> +    - name: add a rule that auto creates another security group
Also, when possible, `resource_prefix` should be included in the names of resources so we can more easily identify which test run they came from, should they survive beyond the test run.

2017-07-28 23:05 UTC, mattclay commented
The test policy has been updated. Tests are now passing.

2017-07-28 23:09 UTC, mattclay requested changes
Thanks for the fixes, additional documentation and tests. It looks good overall. Just two minor changes to the tests requested (see previous comments).

2017-07-29 02:19 UTC, willthames commented
@s-hertel the wildcard should indeed work - I haven't had any problems running the tests with just the included policies - can you let me know what error you're seeing? Probably worth checking your IAM role does include the `Describe*` - I had some problems with Default policy versions in my own tests just now that meant it look like I had DeleteVpc but the default policy didn't, because I'd been flipping back and forth between another set of tests with a different set of IAM policies.

2017-07-29 02:20 UTC, willthames commented
@mattclay your concerns should now be addressed.

2017-07-29 04:16 UTC, mattclay approved these changes

2017-07-29 04:17 UTC, mattclay commented
@willthames Yes, thank you. Please note that I haven't reviewed the whole PR, I just spotted the security group naming and cleanup while testing the IAM policy updates.

2017-08-01 10:52 UTC, ryansb approved these changes

2017-08-01 10:53 UTC, merged