AWSRetry: accept a list of extra exceptions to extend retry_on
ansible/ansible pull request #27041
Opened 2017-07-19 13:19 UTC by s-hertel

##### SUMMARY
Some exceptions will be very module specific, such as DirectConnectClientException. Being able to pass special ClientError exceptions to AWSRetry makes more sense to me than padding retry_on with a lot of random exception codes that most things won't use.
Example: 
`@AWSRetry.backoff(tries=5, delay=5, backoff=2.0, added_exceptions=['DirectConnectClientException'])`

Also simplified logic in module_utils/ec2.py found()

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
lib/ansible/module_utils/cloud.py
lib/ansible/module_utils/ec2.py

##### ANSIBLE VERSION
```
2.4.0
```

2017-07-20 01:14 UTC, abadger commented
/cc @mikedlr @ryansb

2017-07-20 12:08 UTC, s-hertel commented
cc @willthames

2017-08-01 18:46 UTC, ryansb requested changes

2017-08-01 18:46 UTC, ryansb commented on lib/ansible/module_utils/cloud.py
> +    def backoff(cls, tries=10, delay=3, backoff=1.1, added_exceptions=[]):
Declaring a method with a pointer-ish type (like list) as the default can result in some unexpected behavior.

```
>>> class Fooo(object): 
...     def bar(self, fizz=[]):                 
...         print(self, fizz)                   
...         fizz.append('a')                    
>>> f = Fooo()          
>>> f.bar()             
(<Fooo object at 0x7f5a61543290>, [])           
>>> f.bar()             
(<Fooo object at 0x7f5a61543290>, ['a'])        
>>> f.bar()             
(<Fooo object at 0x7f5a61543290>, ['a', 'a'])   
```

Instead, we can use `None` as the default and then check `if added_exceptions is not None:` to decide whether to extend the default exception list or not.

2017-08-02 18:39 UTC, s-hertel commented
Closing because this is a duplicate of #17656.

2017-08-02 18:39 UTC, closed without merging