ACI module_utils library for ACI modules
ansible/ansible pull request #27070
Opened 2017-07-19 17:18 UTC by dagwieers

##### SUMMARY
Since we are going to add a ton of new ACI modules, having this one in place now (and merged) is going to help build new stuff with this.

This PR includes:
- ACI argument_spec
- aci_login function
- aci_response function for JSON and XML response
- experimental aci_request function
- included @schunduri as maintainer
- adapted aci_rest to use the library
- moved the existing unit-tests to test the library (not the aci_rest module)

@gundalow: Please merge as soon as possible.

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

module_utils/aci

##### ANSIBLE VERSION

v2.4

2017-07-21 08:20 UTC, gundalow requested changes
Rebase needed.

2017-07-21 08:20 UTC, gundalow commented on lib/ansible/module_utils/aci.py
> +    protocol=dict(type='str'),  # Deprecated in v2.8
Since these modules are new in 2.4, do you need to add them at all?

If this is needed then you can use `removed_in_version`

2017-07-23 00:37 UTC, dagwieers commented on lib/ansible/module_utils/aci.py
> +    protocol=dict(type='str'),  # Deprecated in v2.8
@gundalow We do want to keep compatibility with earlier modules that were around for more than 2 years elsewhere. But maybe we shouldn't keep this compatibility for 4 releases. Let's make that 2.6...

2017-07-23 00:43 UTC, dagwieers commented on lib/ansible/module_utils/aci.py
> +    protocol=dict(type='str'),  # Deprecated in v2.8
Done.

2017-07-24 13:30 UTC, gundalow commented on lib/ansible/module_utils/aci.py
> +    protocol=dict(type='str'),  # Deprecated in v2.8
Oh, so these modules have existed for a while, we are just upstreaming them now, that makes sense.

2017-07-24 15:01 UTC, dagwieers commented
We are reworking them, idempotency, diff support, module_utils. We have 30+ of these we'd like to ship with v2.4

2017-07-25 22:38 UTC, schunduri approved these changes

2017-07-26 17:39 UTC, gundalow commented
Is this good to merge?

2017-07-28 08:25 UTC, gundalow approved these changes

2017-07-31 11:44 UTC, merged