Bulk import of (relevant) docs from devel to 2.3
ansible/ansible pull request #27164
Opened 2017-07-21 15:37 UTC by gundalow

##### SUMMARY
Now that the default docs for the website are from latest stable (`stable-2.3`) we have a number of changes that that haven't been backported.

This needs careful review. There may be other changes that are missing.

##### ISSUE TYPE
 - Docs Pull Request

2017-07-21 15:41 UTC, gundalow commented
There is a reuse page that I've not moved across. not sure about that one.

2017-07-21 15:45 UTC, bcoca commented
also need to wait till end of stable-2.3 freeze

2017-07-21 15:49 UTC, bcoca requested changes
found a couple of issues right away, might be worth splitting this in pr per doc as the whole thing will take very long to review and is not even visible in the github UI

2017-07-21 15:49 UTC, bcoca commented on docs/docsite/rst/dev_guide/developing_module_utilities.rst
> +- aireos.py - Definitions and helper functions for modules that manage Cisco WLC devices.
most of these files in the new entries only exist in 2.4

2017-07-21 15:49 UTC, bcoca commented on docs/docsite/rst/dev_guide/developing_modules_checklist.rst
> +* Modules must be written to support Python 2.6. If this is not possible, required minimum Python version and rationale should be explained in the requirements section in ``DOCUMENTATION``.  In Ansib
this is incorrect for 2.3, it only applies to 2.4

2017-07-23 10:47 UTC, gundalow commented
I've started to split this into multiple PRs
`dev_guide`: https://github.com/ansible/ansible/pull/27205
`network`: https://github.com/ansible/ansible/pull/27204

2017-08-14 21:20 UTC, dharmabumstead commented
Is this still active?

2017-08-14 21:21 UTC, dharmabumstead approved these changes

2017-08-14 21:31 UTC, dharmabumstead requested changes
Is this still an active WIP?

2017-09-20 14:45 UTC, gundalow commented
Killing this as we will be always displaying the `devel` fro dev_guide

2017-09-20 14:45 UTC, closed without merging