New module: Waiting for VMware tools to become available
ansible/ansible pull request #27236
Opened 2017-07-24 13:59 UTC by pdellaert

##### SUMMARY
Adding a new module which supports waiting for VMware tools to become available for a VMware VM (VMware tools in a running state)

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
vmware_guest_tools

##### ANSIBLE VERSION
```
ansible 2.4.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/pdellaer/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/pdellaer/Virtualenvs/ansible/lib/python2.7/site-packages/ansible
  executable location = /home/pdellaer/Virtualenvs/ansible/bin/ansible
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### ADDITIONAL INFORMATION
govcsim does not support mimicking the behaviour of VMware tools, so integration tests are not created at this moment.

2017-07-24 15:04 UTC, nerzhul commented
Sounds interesting idea for a preseed deployment or template deployment. If i'm correct you should use get_obj from vmware utils (ping @Akasurde)

2017-07-24 15:08 UTC, pdellaert commented
@nerzhul Use case is a situation where something is deployed either through ovftool, or cloned from a template (for instance if wait_for_ip is not an option for some reason), and you need to wait on VMware tools to come up before you can push commands to the VM.

for finding the VM, i looked at existing modules, specifically to vmware_guest_facts. Changing that to the get_obj from the utils, is certainly a possibility.

2017-07-24 15:35 UTC, Akasurde requested changes

2017-07-24 15:35 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_guest_tools.py
> +    def getvm(self, name=None, uuid=None, folder=None):
Can you use refactored [getvm](https://github.com/ansible/ansible/pull/27188/files#diff-d5ca044435f1fc628995b038d2e238f7R173) ?

2017-07-24 15:35 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_guest_tools.py
> +def get_obj(content, vimtype, name):
get_obj is unused, can be removed.

2017-07-24 15:35 UTC, Akasurde commented on test/integration/targets/vmware_guest_tools/tasks/main.yml
> +#
LGTM

2017-07-24 17:15 UTC, pdellaert commented on lib/ansible/modules/cloud/vmware/vmware_guest_tools.py
> +    def getvm(self, name=None, uuid=None, folder=None):
Thanks, done

2017-07-24 17:15 UTC, pdellaert commented on test/integration/targets/vmware_guest_tools/tasks/main.yml
> +#
thanks

2017-07-24 17:16 UTC, pdellaert commented
@Akasurde all suggestions were implemented, thanks for the review!

2017-07-26 09:46 UTC, Akasurde approved these changes
shipit

2017-07-26 17:42 UTC, pdellaert commented
@Akasurde @jctanner 
For changelog, i'd like to add this module
For BOTMETA, i can either add myself to $team_vmware, or just add myself as the maintainer, up to you?

2017-08-08 14:26 UTC, dagwieers commented
So the module freeze deadline for v2.4 is getting closer (2017-08-31). Now is the time to finish up, get it reviewed and merged with no delay.

2017-08-08 15:37 UTC, pdellaert commented
@Akasurde @bcoca @jctanner Can you review/merge?

2017-08-08 15:58 UTC, Akasurde approved these changes
shipit

2017-08-08 16:38 UTC, dav1x commented
shipit

2017-08-09 13:25 UTC, dagwieers requested changes
Apart from the (pedantic) cosmetics / documentation bits, LGTM.

2017-08-09 13:25 UTC, dagwieers commented on lib/ansible/modules/cloud/vmware/vmware_guest_tools_wait.py
> +version_added: 2.4
This should be a string.

2017-08-09 13:25 UTC, dagwieers commented on lib/ansible/modules/cloud/vmware/vmware_guest_tools_wait.py
> +    - Wait for VMware tools to become available on the VM and return facts
Requires a trailing dot.

2017-08-09 13:25 UTC, dagwieers commented on lib/ansible/modules/cloud/vmware/vmware_guest_tools_wait.py
> +# This file is part of Ansible
We have a new one-line GPL message that replace the below header.

2017-08-09 13:25 UTC, dagwieers commented on lib/ansible/modules/cloud/vmware/vmware_guest_tools_wait.py
> +            - Name of the VM for which to wait until the tools become available
Descriptions (except short_description) require a trailing dot.

2017-08-09 13:25 UTC, dagwieers commented on lib/ansible/modules/cloud/vmware/vmware_guest_tools_wait.py
> +            - If multiple VMs matching the name, use the first or last found
Descriptions (except short_description) require a trailing dot.

2017-08-09 13:25 UTC, dagwieers commented on lib/ansible/modules/cloud/vmware/vmware_guest_tools_wait.py
> +            - The folder should include the datacenter. ESX's datacenter is ha-datacenter
Descriptions (except short_description) require a trailing dot.

2017-08-09 13:25 UTC, dagwieers commented on lib/ansible/modules/cloud/vmware/vmware_guest_tools_wait.py
> +            - The folder should include the datacenter. ESX's datacenter is ha-datacenter
Maybe do `C(ha-datacenter)` so it stands out better.

2017-08-09 13:25 UTC, dagwieers commented on lib/ansible/modules/cloud/vmware/vmware_guest_tools_wait.py
> +            - This is required if name is supplied.
Please do `C(name)` to make parameters stand out.

2017-08-09 13:25 UTC, dagwieers commented on lib/ansible/modules/cloud/vmware/vmware_guest_tools_wait.py
> +            - This is required if name is not supplied.
Same here, do `C(name)`

2017-08-09 16:07 UTC, pdellaert commented
@dagwieers Thanks for the review, implemented your comments.

2017-08-10 00:48 UTC, dagwieers requested changes
Almost there !

2017-08-10 00:48 UTC, dagwieers commented on lib/ansible/modules/cloud/vmware/vmware_guest_tools_wait.py
> +    if vm:
I would also do this:
```python
if not vm:
    # fail

# continue with the module
```
This makes it easier to read, as you don't have to find what `else` is part of what condition.

2017-08-10 00:48 UTC, dagwieers commented on lib/ansible/modules/cloud/vmware/vmware_guest_tools_wait.py
> +        module.fail_json(msg=msg)
You could actually make this fancier:
```python
    vmid = module.params.get('name') or module.params.get('uuid')
    module.fail_json(msg="Unable to wait for tools for non-existing VM '%s'" % vmid)
```

2017-08-10 00:48 UTC, dagwieers commented on lib/ansible/modules/cloud/vmware/vmware_guest_tools_wait.py
> +            if result['failed']:
Don't add stuff in a try-except block that should not fail.
If possible also catch specific exceptions with specific error messages.
(It is possible not all exceptions provide a workable string the same way, unfortunately)

2017-08-10 00:48 UTC, dagwieers commented on lib/ansible/modules/cloud/vmware/vmware_guest_tools_wait.py
> +short_description: Wait for VMware tools to become available and return facts
I would make the short_description shorter by removing the "and return facts". This description is used in the index, so we don't need those details.

2017-08-10 00:48 UTC, dagwieers commented on lib/ansible/modules/cloud/vmware/vmware_guest_tools_wait.py
> +    import json
I learned yesterday that nowadays we can simply do `import json` as we no longer support Python 2.4

2017-08-10 00:48 UTC, dagwieers commented on lib/ansible/modules/cloud/vmware/vmware_guest_tools_wait.py
> +# import module snippets
This comment does not offer anything useful, kill it !
(It's an old legacy thing)

2017-08-10 01:33 UTC, pdellaert commented
Closing and reopening as my latest commit does not show up in PR...

2017-08-10 01:40 UTC, pdellaert commented
Thanks @dagwieers for the detailed check! On the json import: i just removed it, as it turned out not to be needed (which was your intention, of course ;)), should have caught that initially.

2017-08-10 01:47 UTC, dagwieers approved these changes

2017-08-10 01:50 UTC, merged