Added initial developing module doc for Windows
ansible/ansible pull request #27308
Opened 2017-07-26 07:04 UTC by jborean93

##### SUMMARY
Based on some recent discussions I thought it would be useful to collate some development info on Powershell modules, this is a first stab at attempting to do so.

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
developing_modules_general_windows.rst

##### ANSIBLE VERSION
```
ansible 2.4.0 (windows-module-debugging bb6ef70b77) last updated 2017/07/26 17:02:35 (GMT +1000)
  config file = None
  configured module search path = ['/home/jborean/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jborean/dev/ansible/lib/ansible
  executable location = /home/jborean/dev/ansible/bin/ansible
  python version = 3.6.2 (default, Jul 20 2017, 18:18:25) [GCC 7.1.1 20170622 (Red Hat 7.1.1-3)]
```

2017-07-26 07:05 UTC, jborean93 commented
@nitzmahone @jhawkesworth @dagwieers @trondhindenes, please have a look and either make any changes you wish or comment on stuff that is there.

2017-07-26 08:24 UTC, jhawkesworth commented on docs/docsite/rst/dev_guide/developing_modules_general_windows.rst
> +check mode and 2 times not in check mode. This ensure we test that check mode
ensure -> ensures (reads easier to me, not sure which is grammatically correct).

2017-07-26 08:26 UTC, jhawkesworth commented on docs/docsite/rst/dev_guide/developing_modules_general_windows.rst
> +    # check mode tests for scenario
I think maybe worth going through the task names here and making them as clear as possible.
suggestion: 
- name: remove a file (check mode)

2017-07-26 08:27 UTC, jhawkesworth commented on docs/docsite/rst/dev_guide/developing_modules_general_windows.rst
> +
suggestion: 
- name: get result of remove a file (check mode)

(using 'actual' here confuses with the later meaning of 'not in check mode')

2017-07-26 08:28 UTC, jhawkesworth commented on docs/docsite/rst/dev_guide/developing_modules_general_windows.rst
> +
suggestion: 
- name: assert remove a file (check mode)

2017-07-26 08:29 UTC, jhawkesworth commented on docs/docsite/rst/dev_guide/developing_modules_general_windows.rst
> +
suggestion: 
- name: get result of remove a file

2017-07-26 08:31 UTC, jhawkesworth commented on docs/docsite/rst/dev_guide/developing_modules_general_windows.rst
> +When creating a new module there are a few things to keep in mind of
'of' probably not needed - 'When creating a new module there are a few things to keep in mind'

2017-07-26 08:33 UTC, jhawkesworth commented
This is great, thank you.

A couple of minor suggestions above.

Also looking again I just noticed there's a couple of places where sentences end without a '.' if you are tweaking. L186 possibly and L195.

Otherwise I think this should be merged, its a really useful addition.

2017-07-26 12:22 UTC, gundalow requested changes
Yay for docs :)
Looks good, just a few minor suggestions

2017-07-26 12:22 UTC, gundalow commented on docs/docsite/rst/dev_guide/developing_modules_general_windows.rst
> +-  `Environment setup <#environment-setup>`__
You can remove this and replace with

`.. contents:: Topics`

2017-07-26 12:22 UTC, gundalow commented on docs/docsite/rst/dev_guide/developing_modules_general_windows.rst
> +::
I think this needs to be:

`.. code-block:: powershell`

2017-07-26 12:22 UTC, gundalow commented on docs/docsite/rst/dev_guide/developing_modules_general_windows.rst
> +- Look for common functions at ``./lib/ansible/module_utils/powershell/`` and use the code there instead of duplicating work, these can be imported by adding the line ``#Requires -Module *`` below ``
POWERHSELL_COMMON -> POWERSHELL_COMMON

2017-07-26 12:22 UTC, gundalow commented on docs/docsite/rst/dev_guide/developing_modules_general_windows.rst
> +::
Don't think this is needed

2017-07-26 12:22 UTC, gundalow commented on docs/docsite/rst/dev_guide/developing_modules_general_windows.rst
> +- Create a playbook in any directory ``$ touch testmodule.yml``
No leading `$ ` are needed, they can be removed.

2017-07-26 12:22 UTC, gundalow commented on docs/docsite/rst/dev_guide/developing_modules_general_windows.rst
> +extemely useful when developing a new module or looking at bug fixes. These are
extremely

2017-07-26 20:43 UTC, jborean93 commented on docs/docsite/rst/dev_guide/developing_modules_general_windows.rst
> +check mode and 2 times not in check mode. This ensure we test that check mode
ensures is better in this context to me

2017-07-26 20:43 UTC, jborean93 commented on docs/docsite/rst/dev_guide/developing_modules_general_windows.rst
> +    # check mode tests for scenario
Sounds good, I've added (check mode) and (idempotent) to the relevant tests, good suggestions

2017-07-26 20:43 UTC, jborean93 commented on docs/docsite/rst/dev_guide/developing_modules_general_windows.rst
> +
Changed

2017-07-26 21:36 UTC, jborean93 commented
Thanks @jhawkesworth and @gundalow, I've made the changes you have asked for and moved some old Windows dev docs to now point to this page. Let me know if there is anything else

2017-07-27 08:07 UTC, dharmabumstead requested changes
Thanks for the PR! Needs a few edits.

2017-07-27 08:07 UTC, dharmabumstead commented on docs/docsite/rst/dev_guide/developing_modules_checklist.rst
> +For a checklist and details on how to write Windows modules have a look at :doc:`developing_modules_general_windows`
Please change "have a look at" to "please see"

2017-07-27 08:07 UTC, dharmabumstead commented on docs/docsite/rst/dev_guide/developing_modules_general_windows.rst
> +Because Windows modules are written in Powershell and needs to be run on a
Please change "needs to be run" to "need to be run"

2017-07-27 08:07 UTC, dharmabumstead commented on docs/docsite/rst/dev_guide/developing_modules_general_windows.rst
> +When creating a new module there are a few things to keep in mind
Colon after "mind"

2017-07-27 08:07 UTC, dharmabumstead commented on docs/docsite/rst/dev_guide/developing_modules_general_windows.rst
> +- Module code are in Powershell (.ps1) files while the documentation are in Python (.py) files of the same name
Please change both instances of "are in" to "is contained in"

2017-07-27 08:07 UTC, dharmabumstead commented on docs/docsite/rst/dev_guide/developing_modules_general_windows.rst
> +- Avoid using try/catch statements over a bit code block, rather use then for individual calls so the error message can be more descriptive
Did you mean to say "big" instead of "bit" here? If so, please use "large code block" instead.

2017-07-27 08:07 UTC, dharmabumstead commented on docs/docsite/rst/dev_guide/developing_modules_general_windows.rst
> +- Look for common functions at ``./lib/ansible/module_utils/powershell/`` and use the code there instead of duplicating work, these can be imported by adding the line ``#Requires -Module *`` below ``
"...common functions in" instead of "common functions at"; add period after "work" and start a new sentence.

2017-07-27 08:07 UTC, dharmabumstead commented on docs/docsite/rst/dev_guide/developing_modules_general_windows.rst
> +- Ensure the code is complient with Powershell v3 and above, if it isn't then document the requirements
Spelling: "complient" should be "compliant".

2017-07-27 08:07 UTC, dharmabumstead commented on docs/docsite/rst/dev_guide/developing_modules_general_windows.rst
> +- Ansible uses strictmode version 2.0, be sure to test with that enabled by putting ``Set-StrictMode -Version 2.0`` at the top of your dev script
Period after "version 2.0" and new sentence.

2017-07-27 08:07 UTC, dharmabumstead commented on docs/docsite/rst/dev_guide/developing_modules_general_windows.rst
> +- If adding a object to ``$result`` ensure any trailing slashes are removed or exited out as ``ConvertTo-Json`` will fail to convert it
"an object" instead of "a object"

2017-07-27 08:07 UTC, dharmabumstead commented on docs/docsite/rst/dev_guide/developing_modules_general_windows.rst
> +- If adding a object to ``$result`` ensure any trailing slashes are removed or exited out as ``ConvertTo-Json`` will fail to convert it
Comma after $result

2017-07-27 08:07 UTC, dharmabumstead commented on docs/docsite/rst/dev_guide/developing_modules_general_windows.rst
> +A very basic powershell module template can be found found below
Colon after "below"

2017-07-27 08:07 UTC, dharmabumstead commented on docs/docsite/rst/dev_guide/developing_modules_general_windows.rst
> +When in doubt look at some of the core modules and see how things have been
Comma after "doubt"

2017-07-27 08:07 UTC, dharmabumstead commented on docs/docsite/rst/dev_guide/developing_modules_general_windows.rst
> +is the order to favour when writing modules
Semicolon instead of comma after the word "task"; colon at the end of the sentence.

2017-07-27 08:07 UTC, dharmabumstead commented on docs/docsite/rst/dev_guide/developing_modules_general_windows.rst
> +the new module end to end but there are better ways to test out the module as
Comma after "end to end"

2017-07-27 08:07 UTC, dharmabumstead commented on docs/docsite/rst/dev_guide/developing_modules_general_windows.rst
> +There are multiple IDE's that can be used to debug a Powershell script, two of
IDEs, not "IDE's"

2017-07-28 01:17 UTC, jborean93 commented
Thanks @dharmabumstead I've made the changes that were requested.

2017-07-28 05:42 UTC, jhawkesworth commented on docs/docsite/rst/dev_guide/developing_modules_general_windows.rst
> +- Avoid using try/catch statements over a large code block, rather use then for individual calls so the error message can be more descriptive
Sorry, spotted another tiny thing...

typo: then -> them
Suggest also adding something to say, where possible catch specific exceptions.

2017-07-28 07:39 UTC, gundalow approved these changes

2017-07-31 00:40 UTC, dharmabumstead approved these changes

2017-07-31 00:41 UTC, dharmabumstead commented
Thanks @jborean93!

2017-07-31 17:32 UTC, nitzmahone approved these changes
Great start on this- I made a follow-on commit with a few changes/corrections. If you agree with them, feel free to hit Merge...

2017-07-31 17:35 UTC, nitzmahone commented
I also suspect a few things are differences between en-AU and en-US- I personally don't care if we mix, as there are a lot of folks working on these docs that aren't en-US, but dunno if @dharmabumstead or others want to standardize on that (eg, spelling things without extra `u`s, pluralisms, etc). I don't think it's something we've discussed before...

2017-07-31 21:27 UTC, jborean93 commented
@nitzmahone I just naturally align to the proper English conventions like colour and aluminium :P. I'm happy to fix it up if people point them out but not sure if I will be able to proactively change them all.

2017-07-31 22:02 UTC, merged