Fix for hponcfg on ESXi hypervisors
ansible/ansible pull request #27362
Opened 2017-07-27 07:00 UTC by jasperla

##### SUMMARY

This adds a new option to pass the path to the `hponcfg` binary which may not live in `$PATH`. For example on ESXi hypervisors it tends to be located in `/opt/hp/tools/` instead. Also properly implement a verbose option for which the code was basically already there, but merely already commented out.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

`hponcfg` module

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /home/jasper/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### ADDITIONAL INFORMATION

This is running against:

```
VMkernel esx-hypervisor.local 6.5.0 #1 SMP Release build-5310538 Apr  6 2017 21:58:28 x86_64 x86_64 x86_64 ESXi
```

```
Version 4.4-2 (c) Copyright 2011-2015 Hewlett Packard Enterprise Development LP 
Firmware Revision = 2.50 Device type = iLO 4 Driver name = hpilo
```

Before:
```
failed: [esx-hypervisor.local] (item=HP_SetILO.xml) => {"cmd": "hponcfg -f /opt/hp/hponcfg/HP_SetILO.xml", "failed": true, "item": "HP_SetILO.xml", "msg": "[Errno 2] No such file or directory: 'hponcfg'", "rc": 2}
```

After:
```
changed: [esx-hypervisor.local] => (item=HP_SetILO.xml) => {"changed": true, "item": "HP_SetILO.xml", "stderr": "", "stderr_lines": [], "stdout": "HPE Lights-Out Online Configuration utility\n\nVersion 4.4-2 (c) Copyright 2011-2015 Hewlett Packard Enterprise Development LP \nFirmware Revision = 2.50 Device type = iLO 4 Driver name = hpilo\niLO IP Address: 10.98.77.225 \n<INFORM> DHCP is currently disabled, enable DHCP to use any DHCP setting.</INFORM>\nScript succeeded \n", "stdout_lines": ["HPE Lights-Out Online Configuration utility", "", "Version 4.4-2 (c) Copyright 2011-2015 Hewlett Packard Enterprise Development LP ", "Firmware Revision = 2.50 Device type = iLO 4 Driver name = hpilo", "iLO IP Address: 10.98.77.225 ", "<INFORM> DHCP is currently disabled, enable DHCP to use any DHCP setting.</INFORM>", "Script succeeded "]}
```

2017-07-27 09:13 UTC, haad commented
shipit

2017-07-27 22:16 UTC, dagwieers requested changes
Looking good mostly, a few cosmetic changes and renaming parameter "hponcfg" to "executable".

2017-07-27 22:16 UTC, dagwieers commented on lib/ansible/modules/remote_management/hpilo/hponcfg.py
> +  hponcfg:
This should become `executable`, which is the standard parameter name for this kind of functionality in Ansible.

2017-07-27 22:16 UTC, dagwieers commented on lib/ansible/modules/remote_management/hpilo/hponcfg.py
> +    - Path to the hponcfg executable (`hponcfg` which uses $PATH)
Descriptions should end with a dot. (Yes, the original module is doing this wrong as well because we weren't that strict in the olden days :-p)

2017-07-27 22:16 UTC, dagwieers commented on lib/ansible/modules/remote_management/hpilo/hponcfg.py
> +    required: false
This is not wanted, a parameter is considered optional by default unless you add `required: yes`.

2017-07-27 22:16 UTC, dagwieers commented on lib/ansible/modules/remote_management/hpilo/hponcfg.py
> +    default: false
This should be: `default: 'no'`

2017-07-27 22:16 UTC, dagwieers commented on lib/ansible/modules/remote_management/hpilo/hponcfg.py
> +    - Run hponcfg in verbose mode (-v)
Add trailing dot.

2017-07-27 22:16 UTC, dagwieers commented on lib/ansible/modules/remote_management/hpilo/hponcfg.py
> +    choices: ['yes', 'no']
This should become: `type: bool`

2017-07-27 22:16 UTC, dagwieers commented on lib/ansible/modules/remote_management/hpilo/hponcfg.py
> +    required: false
Not needed.

2017-07-27 22:18 UTC, dagwieers commented
@jasperla Maybe you can add a second example using the ESXi path for hponcfg. That's very useful for anyone who requires this on ESXi (no need to try and figure out the location) :-)

2017-07-28 07:35 UTC, jasperla commented
That was quite unintended to close it; I'll address the things you pointed out, @dagwieers

2017-08-07 00:03 UTC, dagwieers commented
@jasperla So for me this is ready to go, but it needs a rebase. Then we need this merged ASAP if we want this included in v2.4 !

2017-08-07 05:55 UTC, jasperla commented
@dagwieers resolved the conflict.
@bcoca could you please have a look?

2017-08-17 15:44 UTC, jasperla commented
@dagwieers was there anything left for me to address?

2017-08-17 16:20 UTC, merged

2017-08-17 16:20 UTC, dagwieers commented
No, this is looking good. I simply lost track of this. Merged.

2017-08-17 18:02 UTC, jasperla commented
Thanks!