Use apt-get instead of aptitude
ansible/ansible pull request #27370
Opened 2017-07-27 09:33 UTC by valentin-krasontovitsch

##### SUMMARY

In answer to #2540, `aptitude` was introduced as tool of choice for running
upgrades in the apt module and installing new packages that arise as
dependencies during upgrades.

This recently lead to problems, as for example Ubuntu Xenial (16.04) ships
without aptitude (installed).

Studying the man pages of both apt-get and aptitude, it appears that we can
achieve the effects of `aptitude safe-upgrade` using

```
apt-get upgrade --with-new-pkgs --autoremove
```

while `aptitude full-upgrade` seems to be identical to `apt-get dist-upgrade`.

An argument in favor of apt-get over aptitude is that the former is more
back-end, while the latter is more user-friendly - I suppose (peronsal humble
opinion) that in ansible core, we should try to use the potentially more stable
and backwards compatible back-end tools.

Fixes #18987

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
core/apt

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

2017-07-28 07:44 UTC, GMLudo commented
This PR will fix also #27401
Moreover, Debian recommends apt instead of aptitude for upgrades since Debian Lenny, released in 2009.

I vote for the merge of this PR.

2017-07-28 13:51 UTC, bcoca requested changes
I'm not sure of all the consequences of this change, I'm tempted to keep aptitude and use apt-get as a fallback if it isn't present. Debian recommendations aside, this affects other distros also (mainly Ubuntu, but plenty of derivatives from both).

2017-07-28 13:51 UTC, bcoca commented on lib/ansible/modules/packaging/os/apt.py
> +      - 'If dist or full, performs an apt-get dist-upgrade.'
this is  'since 2.4' ,  keep original but make the distinction by version

2017-07-28 13:51 UTC, bcoca commented on lib/ansible/modules/packaging/os/apt.py
> -   - aptitude
also make note that before 2.4 aptitude was required

2017-07-28 13:51 UTC, bcoca commented on lib/ansible/modules/packaging/os/apt.py
> -     C(apt-get) suffices.
again, make note that this only applied to <2.4

2017-07-28 17:03 UTC, GMLudo commented
> I'm tempted to keep aptitude and use apt-get as a fallback if it isn't present. 

I understand your remark, but for #27401, aptitude is broken to do the upgrade to Debian Stretch on an average installation. 
And yes, I use a lot aptitude to check packages, it isn't an option to me to uninstall ;-)

If Ansible Dev team wants to keep aptitude in the loop to be 100% to not have side effects, it might be possible to add an extra flag to force to use aptitude or apt-get behind the scene ?

And keep the actual behaviour depends on the action.

It's technically possible that aptitude could be better in some situations, I already had a situation like that in the past.

2017-07-28 17:18 UTC, bcoca commented
ok, so way forward seems:
 - fallback to apt-get if aptitude is missing 
 - add option to force the 'fallback', off by default

2017-07-29 15:15 UTC, resmo commented
I am +1 with @bcoca suggestion. I would even add a "warning" that the "fallback" was used in case fallback was not forced.

2017-08-02 08:01 UTC, valentin-krasontovitsch commented
Sorry 'bout my long silence - gonna go ahead and try to incorporate the requested changes, both regarding behavior and regarding the notes / comments in the docs as requested by @bcoca

2017-08-10 13:28 UTC, valentin-krasontovitsch commented
Closing in favor of #27962.

2017-08-10 13:28 UTC, closed without merging