bug fix #27487
ansible/ansible pull request #27518
Opened 2017-07-31 19:01 UTC by gregory-dan

##### SUMMARY

bug fix #27487 

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

##### ANSIBLE VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

2017-07-31 19:30 UTC, tedder commented
cc @wdegeus can you take a look at this?

2017-08-01 09:14 UTC, wdegeus commented
Looks good, ship it.

2017-08-02 12:29 UTC, s-hertel approved these changes

2017-08-02 12:29 UTC, s-hertel commented
shipit

2017-08-02 22:35 UTC, ryansb requested changes

2017-08-02 22:35 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/cloudformation.py
> +            changeset_name=stack_params['ChangeSetName']
Needs to be `changeset_name = stack_params['ChangeSetName']` to match PEP8 style of whitespace around operators.

2017-08-03 12:40 UTC, ryansb approved these changes

2017-08-03 12:40 UTC, merged

2017-08-03 12:41 UTC, ryansb commented
Thanks @gregory-dan!