Module for uploading templates into vDirect server
ansible/ansible pull request #27570
Opened 2017-08-01 15:25 UTC by evgenyfedoruk

Module for uploading configuration and workflow templates
into Radware vDirect server

##### SUMMARY

The rational is to give ansible users a module to upload templates into Radware vDirect server

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

vdirect_file
##### ANSIBLE VERSION

```
2.3.1.0
```

##### ADDITIONAL INFORMATION

```

```

2017-08-01 17:45 UTC, gundalow commented
@evgenyfedoruk Thank you for this PR, GitHub tells me this is your first contribution, so double thanks :)

To prevent regressions in the future I wonder if a test could be added in to defend this?


**Testing Expectations for Network Modules**
In an effort to ensure the highest quality of network modules, all contributions must now include unit tests to exercise each feature of the module. Additionally, do to the nature of mocked interfaces unit tests use, network modules should also include integration tests. The integration tests should be runnable against supported versions of network devices as well as their virtual machine images or containers if available.

Examples of existing unit tests can be found in https://github.com/ansible/ansible/tree/devel/test/units
Examples of existing integration tests can be found in https://github.com/ansible/ansible/tree/devel/test/integration

http://docs.ansible.com/ansible/dev_guide/testing_integration.html#network-tests

2017-08-01 17:57 UTC, gundalow requested changes

2017-08-01 17:57 UTC, gundalow commented on lib/ansible/modules/network/radware/vdirect_file.py
> +version_added: "2.3"
version_added: "2.4"

2017-08-01 17:57 UTC, gundalow commented on lib/ansible/modules/network/radware/vdirect_file.py
> +  vdirect_ssl_verify_context:
Please update to be
```
    validate_certs:
      description:
        - If C(no), SSL certificates will not be validated.
        - This should only set to C(no) used on personally controlled sites using self-signed certificates.
      type: bool
      default: 'yes'
```

and update the module spec

2017-08-01 17:57 UTC, gundalow commented on lib/ansible/modules/network/radware/vdirect_file.py
> +notes:
There is a `requirements:`  than should be used for this, see other modules for examples

2017-08-01 17:57 UTC, gundalow commented on lib/ansible/modules/network/radware/vdirect_file.py
> +  vdirect_ip:
Does this have to be an IP address, or can it be a hostname?

2017-08-01 17:57 UTC, gundalow commented on lib/ansible/modules/network/radware/vdirect_file.py
> +    required: false
`type: bool`

2017-08-01 17:57 UTC, gundalow commented on lib/ansible/modules/network/radware/vdirect_file.py
> +    meta_args = dict(
1) Please put each option on a single line
2) use `type='int'` for ports, timeouts, etc
3) use `type='bool`' for booleans (ssl, vdirect_strict_http_results, etc)
4) Are any of these options required?

2017-08-02 07:32 UTC, evgenyfedoruk commented on lib/ansible/modules/network/radware/vdirect_file.py
> +notes:
I will make the ip, user, password mandatory parameters only if they are not defined as env. vars.

2017-08-02 07:32 UTC, evgenyfedoruk commented on lib/ansible/modules/network/radware/vdirect_file.py
> +version_added: "2.3"
Will fix

2017-08-02 07:32 UTC, evgenyfedoruk commented on lib/ansible/modules/network/radware/vdirect_file.py
> +  vdirect_ip:
IP address

2017-08-02 07:33 UTC, evgenyfedoruk commented on lib/ansible/modules/network/radware/vdirect_file.py
> +    required: false
will make all STRING parameters that should be BOOL or INT, to be BOOL or INT

2017-08-02 07:33 UTC, evgenyfedoruk commented on lib/ansible/modules/network/radware/vdirect_file.py
> +  vdirect_ssl_verify_context:
will fix

2017-08-02 07:33 UTC, evgenyfedoruk commented on lib/ansible/modules/network/radware/vdirect_file.py
> +    meta_args = dict(
will do

2017-08-02 13:32 UTC, gundalow commented
to use env you can do something alone the lines of 
`username=dict(fallback=(env_fallback, ['MY_APP_USERNAME'])),`

2017-08-15 08:56 UTC, evgenyfedoruk commented
Hi gundalow, thank you for your reviews and help. I added unit tests in last commit.

2017-08-15 15:45 UTC, gundalow commented on lib/ansible/modules/network/radware/vdirect_file.py
> +      install vdirect-client
To improve the formatting do:
`C(pip install vdirect-client)`

2017-08-16 04:36 UTC, itdependsnetworks commented
@evgenyfedoruk is there plans to introduce the other vdirect modules as well? e.g. template and workflow?

2017-08-16 10:25 UTC, evgenyfedoruk commented on lib/ansible/modules/network/radware/vdirect_file.py
> +      install vdirect-client
Done

2017-08-16 11:15 UTC, evgenyfedoruk commented
@itdependsnetworks Yes, This module is the first one. There will be two more: module for running a template and workflow, module for committing device configuration.
What is your interestin Radware's vdirect modules? Are you using Radware devices and/or vDirect ?

2017-08-16 11:30 UTC, gundalow commented on lib/ansible/modules/network/radware/vdirect_file.py
> +                    'metadata_version': '1.0'}
We've just update the schema version, can you please update this to
`'metadata_version': '1.1'`

2017-08-16 11:36 UTC, evgenyfedoruk commented on lib/ansible/modules/network/radware/vdirect_file.py
> +                    'metadata_version': '1.0'}
Done, thank you

2017-08-16 16:22 UTC, itdependsnetworks commented
Helping a client, and a small integration with vDirect to manage Alteon LB's. Would be great to have those other two modules in for 2.4 :) 

I also put in a PR on the original repo, if you are the current owner over there.

2017-08-17 15:50 UTC, evgenyfedoruk commented
itdependsnetworks: Got it, the original repo is not maintained anymore

2017-08-18 11:22 UTC, gundalow approved these changes

2017-08-25 15:23 UTC, merged

2017-08-25 15:23 UTC, gundalow commented
Merged into `devel` this will be released in `2.4.0`.