ec2_asg: add AWSRetry to boto3 calls
ansible/ansible pull request #27598
Opened 2017-08-01 18:30 UTC by s-hertel

##### SUMMARY
Add AWSRetry to boto3 calls in ec2_asg. 2.3 currently has retry capability but the module was ported to boto3 for 2.4 and had to be redone (AWSRetry itself was not an option for 2.3 since it handles boto3 exceptions).

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/modules/cloud/amazon/ec2_asg.py

##### ANSIBLE VERSION
```
2.4.0
```

2017-08-02 05:04 UTC, willthames requested changes
This looks pretty good. The pagination is worth doing while we're in the area, and the tests need fixing, but this should be relatively straightforward after that.

2017-08-02 05:04 UTC, willthames commented on lib/ansible/modules/cloud/amazon/ec2_asg.py
> +    response = connection.describe_auto_scaling_groups(AutoScalingGroupNames=[group_name])
This should be paginated: http://boto3.readthedocs.io/en/latest/reference/services/autoscaling.html#paginators

2017-08-02 05:04 UTC, willthames commented on lib/ansible/modules/cloud/amazon/ec2_asg.py
> +def describe_launch_configurations(connection, launch_config_name):
This should be paginated

2017-08-08 11:59 UTC, willthames commented on lib/ansible/modules/cloud/amazon/ec2_asg.py
> +    for page in pg.paginate(AutoScalingGroupNames=[group_name]):
is there a reason why you don't do: 

```
return pg.paginate(AutoScalingGroupNames=[group_name]).build_full_result()
```

(other than it being incredibly poorly documented, which is a fair reason)

2017-08-08 14:28 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/ec2_asg.py
> +    for page in pg.paginate(AutoScalingGroupNames=[group_name]):
The reason would just be ignorance. Will fix :)

2017-08-09 23:46 UTC, willthames approved these changes

2017-08-11 15:29 UTC, ryansb approved these changes

2017-08-11 15:30 UTC, merged