New module: manage Citrix Netscaler SSL certificate keys (network/netscaler/netscaler_ssl_certkey))
ansible/ansible pull request #27641
Opened 2017-08-02 14:08 UTC by giorgos-nikolopoulos

##### SUMMARY

This PR adds a new module, netscaler_ssl_certkey

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

lib/ansible/modules/network/netscaler/netscaler_gslb_site.py
##### ANSIBLE VERSION

```
ansible 2.4.0 (netscaler_ssl_certkey f1123ba1c2) last updated 2017/08/02 16:58:13 (GMT +300)
  config file = /home/georgen/.ansible.cfg
  configured module search path = [u'/home/georgen/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/georgen/repos/ansible_fork/lib/ansible
  executable location = /home/georgen/repos/ansible_fork/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

```

##### ADDITIONAL INFORMATION

Unit tests and integration tests are included.

2017-08-02 16:30 UTC, gundalow requested changes

2017-08-02 16:30 UTC, gundalow commented on lib/ansible/modules/network/netscaler/netscaler_ssl_certkey.py
> +        passplain=dict(type='str'),
`,no_log=True`

2017-08-02 16:30 UTC, gundalow commented on lib/ansible/modules/network/netscaler/netscaler_ssl_certkey.py
> +        bundle=dict(type='bool'),
Missing from DOCUMENTATION

In the docs you can use `type: bool` (rather than `choices:`)

2017-08-03 11:30 UTC, gundalow commented on lib/ansible/modules/network/netscaler/netscaler_ssl_certkey.py
> +                'ENABLED',
Can we please get these in lower case in all your modules

2017-08-03 12:57 UTC, giorgos-nikolopoulos commented
Some fixes to netscaler module utils were added that were needed for the unit tests of this module to pass.

This particular commit is replicated in #27639 and #27638 for the same reason.

2017-08-03 14:24 UTC, gundalow approved these changes

2017-08-03 14:24 UTC, gundalow commented
@giorgos-nikolopoulos Thanks for the quick turn around on that, merging into devel

2017-08-03 14:24 UTC, merged