WIP yum: do not hide yum's errors
ansible/ansible pull request #27696
Opened 2017-08-03 11:44 UTC by mkrizek

##### SUMMARY
Fixes #25783

This is still WIP, needs tests and figuring out what it breaks.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
yum

##### ANSIBLE VERSION
```
devel
```

##### ADDITIONAL INFORMATION
None

2017-08-07 13:46 UTC, samdoran requested changes

2017-08-07 13:46 UTC, samdoran commented on test/integration/targets/yum/tasks/yum.yml
> +- name: set what repo to use$
What's the '$' at the end of the name for?

2017-08-07 13:46 UTC, samdoran commented on test/integration/targets/yum/tasks/yum.yml
> +  set_fact: pkg_url=http://download.fedoraproject.org/pub/fedora/linux/releases/26/Server/x86_64/os/Packages/f/fpaste-0.3.8.3-3.fc26.noarch.rpm
Not required, but multiline syntax is preferred.

```yaml
set_fact:
  pkg_url: http://...
```

2017-08-07 13:46 UTC, samdoran commented on test/integration/targets/yum/tasks/yum.yml
> +  when: ansible_distribution in ['RedHat', 'CentOS', 'ScientificLinux'] and ansible_distribution_major_version|int == 7
You can split long 'and' conditionals into a list.

```yaml
when:
  - cond1
  - cond2
```

2017-08-07 13:46 UTC, samdoran commented on test/integration/targets/yum/tasks/yum.yml
> +- debug: var=yum_result
Either remove the debug statements or add `verbosity` so they don't run by default but only when the verbosity gets cranked up.

2017-08-07 14:11 UTC, alikins commented on lib/ansible/modules/packaging/os/yum.py
> +        res['changed'] = True
Can we get away with setting stderr in the return here?

``` python
            res['stderr'] = err
```

The way stderr is the result is handled was changed recently, but not sure of the implication. But having the stderr in the result might be useful in these cases if it doesn't cause the task to fail.

2017-08-08 19:14 UTC, mkrizek commented on lib/ansible/modules/packaging/os/yum.py
> +        res['changed'] = True
It might be good to use `res['stderr']` everywhere in the module. Are you ok with me addressing that in a separate PR?

2017-08-08 19:17 UTC, mkrizek commented on test/integration/targets/yum/tasks/yum.yml
> +- name: set what repo to use$
Nothing, was there by mistake ;)

2017-08-09 00:06 UTC, mattclay commented
In addition to the CI failures mentioned by the bot above, there are also integration test failures: https://app.shippable.com/github/ansible/ansible/runs/32437/9/tests

2017-08-09 07:18 UTC, mattclay commented
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/32517/9/tests

2017-08-10 11:15 UTC, mkrizek commented
ready_for_review

2017-08-10 17:54 UTC, samdoran approved these changes

2017-08-10 17:56 UTC, samdoran commented
Looks good to me. Do create a follow up PR that returns `stderr` please. That will be very helpful.

2017-08-10 17:57 UTC, merged