New Module: Write Windows event log entries (win_eventlog_entry)
ansible/ansible pull request #27828
Opened 2017-08-07 02:08 UTC by andrewsaraceni

##### SUMMARY
As discussed in https://github.com/ansible/ansible/issues/26825, a module does not exist for the creation of event log entries themselves in Windows event logs.  Rounding out the functionality provided by the `*-EventLog` PowerShell cmdlets along with PR https://github.com/ansible/ansible/pull/27827, this module allows for the generation of entries to event logs from a specified source.

Integration tests and check-mode support are both included.

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME
lib/ansible/modules/windows/win_eventlog_entry.ps1

##### ANSIBLE VERSION

```
ansible 2.4.0
```

##### ADDITIONAL INFORMATION

```yml
- name: Write an entry to a Windows event log
  win_eventlog_entry:
    log: MyNewLog
    source: NewLogSource1
    event_id: 1234
    message: This is a test log entry.

- name: Write another entry to a different Windows event log
  win_eventlog_entry:
    log: AnotherLog
    source: MyAppSource
    event_id: 5000
    message: An error has occurred.
    entry_type: Error
    category: 5
    raw_data: 10,20
```

2017-08-07 04:23 UTC, jborean93 requested changes
Looks good to me, nice work, only a few formatting things to change. One thing you may want to look at is creating a custom test module to return all the info of an event log instead of running 4 shell scripts but that's up to you. I did something similar with `win_security_policy` as getting the actual results was too hard to put into one command https://github.com/ansible/ansible/blob/devel/test/integration/targets/win_security_policy/library/test_win_security_policy.ps1

2017-08-07 04:23 UTC, jborean93 commented on lib/ansible/modules/windows/win_eventlog_entry.ps1
> +# (c) 2017, Andrew Saraceni <andrew.saraceni@gmail.com>
The copyright is a lot simpler now, you only need a few lines. See http://docs.ansible.com/ansible/latest/dev_guide/developing_modules_documenting.html#copyright for what has changed.

2017-08-07 04:23 UTC, jborean93 commented on lib/ansible/modules/windows/win_eventlog_entry.ps1
> +# WANT_JSON
You can get right rid of `# WANT_JSON` and `# POWERSHELL_COMMON` and replace it with just `#Requires -Module Ansible.ModuleUtils.Legacy.psm1`. This has more info as well http://docs.ansible.com/ansible/latest/dev_guide/developing_modules_general_windows.html#windows-new-module-development.

2017-08-07 04:23 UTC, jborean93 commented on lib/ansible/modules/windows/win_eventlog_entry.py
> +# (c) 2017, Andrew Saraceni <andrew.saraceni@gmail.com>
Same thing about the copyright.

2017-08-07 04:23 UTC, jborean93 commented on lib/ansible/modules/windows/win_eventlog_entry.py
> +      - Binary data associated with the log entry.
Are you able to give a bit more info, seems like it's just a byte array represented by hex values but would be good to see that in the documentation.

2017-08-07 17:29 UTC, andrewsaraceni commented
Thanks @jborean93, I'll look into making these changes later tonight/tomorrow.

2017-08-08 02:20 UTC, andrewsaraceni commented
@jborean93  Just made the changes you requested - let me know if there's anything I missed or that still needs work, and thanks for the idea about the test module!

2017-08-11 01:17 UTC, jborean93 approved these changes
Cool, looks good.

2017-08-11 01:17 UTC, jborean93 commented
shipit

2017-08-15 05:13 UTC, merged