fixes Traceback generated by nxos_igmp module
ansible/ansible pull request #27869
Opened 2017-08-08 00:54 UTC by privateip

fixes #27488

2017-08-08 13:24 UTC, Qalthos requested changes
This will still fail as candidate needs to be turned into a list of commands (via `.items_text()`) to successfully pass through `load_config()`. Additionally, the response of `load_config()` should no longer be pushed into `result` as it doesn't return anything (notwithstanding my PR, which instead makes it return something we don't want there).

Also, seeing result return a `'commands'` key and updating the docs so it matches most of the rest of the modules would be helpful, even if `'updates'` sticks around.

2017-08-09 01:45 UTC, privateip commented
ready_for_review

2017-08-09 13:56 UTC, Qalthos requested changes

2017-08-09 13:56 UTC, Qalthos commented on lib/ansible/modules/network/nxos/nxos_igmp.py
> +    import q
Yay for `q`, but might want to take it out.

2017-08-09 15:37 UTC, privateip commented on lib/ansible/modules/network/nxos/nxos_igmp.py
> +    import q
doh!.. updated

2017-08-09 19:52 UTC, merged