Rename Openswitch to Libreswitch
ansible/ansible pull request #27971
Opened 2017-08-09 16:37 UTC by skg-net

##### SUMMARY
The old openswitch(ops) (HP) NOS has been migrated to Libreswitch. There is now a new openswitch (opx) NOS supported by Dell and other vendors.
Hence moving the old openswitch modules to libreswitch folders.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 module/network/openswitch
 module/network/libreswitch

##### ANSIBLE VERSION
ansible  --version
ansible 2.4.0 (libreswitch a86782e1ba) last updated 2017/08/09 09:22:17 (GMT -700)
  config file = None
  configured module search path = [u'/home/sganesan/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sganesan/github/ansible/lib/ansible
  executable location = /home/sganesan/github/ansible/bin/ansible
  python version = 2.7.11 |Continuum Analytics, Inc.| (default, Dec  6 2015, 18:08:32) [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
##### ADDITIONAL INFORMATION
- Currently the modules names remain ops
      * the new openswitch have a different short form opx
      * all the existing tests/playbooks needs to change.
      * libreswitch community haven't got back on the naming convention.

- I haven't tested this changes, since libreswitch image is not available currently.

2017-08-09 16:38 UTC, skg-net commented
@gundalow  @privateip Please have a look at it.

2017-08-09 21:10 UTC, Qalthos commented
@skg-net are you planning on maintaining this module and addressing issues with it in the future? I am given to understand that even without the name change, these modules were not working properly.

2017-08-10 07:37 UTC, skg-net commented
@Qalthos No, I am not planning to own/maintain these modules. My understanding is if you try with new openswitch modules, it wont work, since its a completely different NOS. But if you try to run with the old openswitch (now libreswitch) it should work. 

Since we are going to upload the new openswitch modules, I am just trying to cleanup the namespace.

2017-08-10 08:25 UTC, gundalow reviewed
These modules will still be called `ops_facts`

What will the new modules be called?

2017-08-10 08:25 UTC, gundalow commented on docs/docsite/rst/dev_guide/developing_module_utilities.rst
> +- libreswitch.py - Definitions and helper functions for modules that manage libreswitch devices
This list should be in alphabetical order.

2017-08-10 08:25 UTC, gundalow commented on test/sanity/pep8/legacy-files.txt
> +lib/ansible/modules/network/libreswitch/ops_command.py
Alphabetical order

2017-08-11 15:32 UTC, skg-net commented
@gundalow The new modules will be called opx_base_xxxx.

2017-08-11 15:39 UTC, bcoca requested changes

2017-08-11 15:39 UTC, bcoca commented on lib/ansible/modules/network/libreswitch/ops_command.py
> +import ansible.module_utils.libreswitch
too keep compatibility for those using the old name of the lib, this should be a try/except Import with fallback to the old name.

2017-08-11 15:40 UTC, bcoca commented
any plans on renaming the modules themselves? ops_ vs lbs_ ?

2017-08-23 14:56 UTC, Qalthos commented
Since you have neither tested these modules nor do you have any interest in maintaining these modules, we are not going to merge this PR. Good news for you, though is that we have decided instead to just get rid of the modules entirely.

This was decided as the modules do not work at all presently. That being said, if anyone in the future wishes to use this as a base for new LibreSwitch modules, the files are still in git history available for retrofitting.

2017-08-23 14:56 UTC, closed without merging