Cause copy module to fail on empty string as source
ansible/ansible pull request #27975
Opened 2017-08-09 18:58 UTC by samdoran

##### SUMMARY

Cause `copy` to fail rather than copying the content of the current working directory if an empty string is specified as the source. Fixes #27363

Cleaned up formatting on integration tests.

Added integration test for this specific case.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

`action/copy.py`

##### ANSIBLE VERSION

```
2.4
```

##### ADDITIONAL INFORMATION

This has been a bug for quite some time. I don't believe fixing this will have any adverse effects as it seems it was the original intent to fail on no input as the source.

2017-08-10 00:11 UTC, dagwieers requested changes

2017-08-10 00:11 UTC, dagwieers commented on lib/ansible/plugins/action/copy.py
> +        if ((not source or source is None) and content is None) or dest is None:
I would split it out and have more specific error messages:
```python
    if not source and content is None:
        result['msg'] = "src (or content) is required"
    elif dest is not None:
        result['msg'] = "dest is required"
    elif source and content is not None:
        result['msg'] = "src and content are mutually exclusive"
```
Can dest be an empty string ? (current script directory ?)

2017-08-10 00:11 UTC, dagwieers commented on lib/ansible/plugins/action/copy.py
> +        if ((not source or source is None) and content is None) or dest is None:
PS I also modified the last conditional in that list.

2017-08-14 22:18 UTC, dagwieers approved these changes
Good stuff. Check my one note, and then we can merge this.

2017-08-14 22:18 UTC, dagwieers commented on lib/ansible/plugins/action/copy.py
> +        if (not source or source is None) and content is None:
If source is None, the conditional `not source` will be true. So I don't think the second part of this conditional will ever hit.

2017-08-15 14:45 UTC, samdoran commented on lib/ansible/plugins/action/copy.py
> +        if (not source or source is None) and content is None:
Good point. This was what I was originally trying to fix with this PR. I just tested with only `not source` and it passed the tests. Will push shortly.

Please try to merge this today.

2017-08-15 16:41 UTC, merged