fix for nxos_ospf_vrf invalid cmd
ansible/ansible pull request #27977
Opened 2017-08-09 19:45 UTC by saichint

##### SUMMARY
Fixes #27392

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
nxos_ospf_vrf

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel bb5b1680f8) last updated 2017/07/26 08:18:32 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible']
  ansible python module location = /root/agents-ci/ansible/lib/ansible
  executable location = /root/agents-ci/ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### ADDITIONAL INFORMATION
- There is a bug in the code where it is taking ospf_instance_id from the playbook and trying to execute a command "ospf <ospf_instance_id>" under the vrf context (if vrf is non-default or under 'router ospf <ospf_instance_id>' if vrf is default). There is no such command. The ospf_instance_id from the playbook must only used to go to the "router ospf <ospf_instance_id>" context. All other commands are fine.

- Added integration test cases

```
PLAY RECAP ********************************************************************************************************************************************
camden-nx-2.cisco.com      : ok=41   changed=6    unreachable=0    failed=0                                                                            
dplus-nx-2.cisco.com       : ok=41   changed=6    unreachable=0    failed=0                                                                            
evergreen-nx-2.cisco.com   : ok=41   changed=6    unreachable=0    failed=0                                                                            
freeport-nx-2.cisco.com    : ok=41   changed=6    unreachable=0    failed=0                                                                            
greensboro-nx-2.cisco.com  : ok=41   changed=6    unreachable=0    failed=0                                                                            
n3k-173.cisco.com          : ok=40   changed=6    unreachable=0    failed=0                                                                            
n3x-161.cisco.com          : ok=40   changed=6    unreachable=0    failed=0                                                                            
n7k-99.cisco.com           : ok=40   changed=6    unreachable=0    failed=0                                                                            
n9k-108.cisco.com          : ok=41   changed=6    unreachable=0    failed=0                                                                            
n9k-157.cisco.com          : ok=42   changed=6    unreachable=0    failed=0
```

2017-08-10 02:35 UTC, jborean93 commented
Hey @saichint, thanks for the PR, I would probably recommend splitting this so there is 1 PR per module that you touch. If they need to be together that is fine but it is usually easier and quicker to look at smaller chunks.

2017-08-10 02:44 UTC, saichint commented
Can we do this one time. Next time I will open separate PRs.
The code changes are small. The number of files are more as they are integration test cases.


On Aug 9, 2017 7:36 PM, Jordan Borean <notifications@github.com> wrote:

Hey @saichint<https://github.com/saichint>, thanks for the PR, I would probably recommend splitting this so there is 1 PR per module that you touch. If they need to be together that is fine but it is usually easier and quicker to look at smaller chunks.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/ansible/ansible/pull/27977#issuecomment-321434096>, or mute the thread<https://github.com/notifications/unsubscribe-auth/APDrjSnDxrUPmpXgwyLx-dwIHb08cRieks5sWmyegaJpZM4OyjMI>.

2017-08-10 03:00 UTC, jborean93 commented
Up to the people reviewing it :), it should be ok though. I don't know much about this domain so I cannot review it myself.

2017-08-14 15:54 UTC, Qalthos requested changes
I know it's minor, but this minimizes the diff and tries to avoid runaway nesting.

Other than that, good to merge.

2017-08-14 15:54 UTC, Qalthos commented on lib/ansible/modules/network/nxos/nxos_ntp.py
> +        if output[0]:
Take this out and replace the `except` line to `except (AttributeError, TypeError)`

2017-08-14 16:07 UTC, saichint commented
@Qalthos I think you meant to change except to except (AttributeError, IndexError). We are not getting any TypeError, if I put that, it still fails. I changed it to IndexError and now it is fine. If this is ok, Please merge.

2017-08-14 20:09 UTC, merged