New module: xmlrpc_client
ansible/ansible pull request #28065
Opened 2017-08-11 14:14 UTC by stemid

##### SUMMARY

I have an API internally where this module helps a lot because it lets me use ansible for the entire deployment process. 

It's the most basic xmlrpc API client that forwards any call to the API along with positional arguments and keyword arguments. This way the ansible user can decide how to use the xmlrpc api along with the relevant API docs.

Looking at the webfaction modules for example I can see that a basic xmlrpc client module would be able to perform their tasks as well but with less abstractions between the user and the API.

I wasn't sure which category to put the module in. I'm sure people will have issue with placing it under commands, in that case just know that I have no problem with moving it to another category if a more suitable one can be found.

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

lib/ansible/modules/commands/xmlrpc_client
##### ANSIBLE VERSION

```
ansible 2.4.0 (xmlrpc_client-module 5224579d9e) last updated 2017/08/11 16:08:55 (GMT +200)
  config file = None
  configured module search path = ['/home/stemid/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/stemid/Utveckling/ansible/lib/ansible
  executable location = /home/stemid/Utveckling/ansible/bin/ansible
  python version = 3.6.2 (default, Jul 19 2017, 13:09:21) [GCC 7.1.1 20170622 (Red Hat 7.1.1-3)]

```

##### ADDITIONAL INFORMATION

I have run sanity checks and there are no more issues with my code but some sanity checks in ansible-test still fail because of other older modules in the repo. So I expect ansibot to start posting those here soon. What can I do when all my own sanity checks are resolved?

```

```

2017-08-11 21:39 UTC, dagwieers requested changes
Looking good.

2017-08-11 21:39 UTC, dagwieers commented on lib/ansible/modules/commands/xmlrpc_client.py
> +        required: false
This is not needed for parameters that are not required. Guideline dictates to leave it out.

2017-08-11 21:39 UTC, dagwieers commented on lib/ansible/modules/commands/xmlrpc_client.py
> +        required: false
This is not needed for parameters that are not required. Guideline dictates to leave it out.

2017-08-11 21:39 UTC, dagwieers commented on lib/ansible/modules/commands/xmlrpc_client.py
> +        args=dict(type='list', required=False, default=[]),
Here also `required=False` is not needed for parameters that are not required. Guideline dictates to leave it out.

2017-08-11 21:39 UTC, dagwieers commented on lib/ansible/modules/commands/xmlrpc_client.py
> +        kwargs=dict(type='dict', required=False, default={})
Here also `required=False` is not needed for parameters that are not required. Guideline dictates to leave it out.

2017-08-12 09:22 UTC, stemid commented
@dagwieers Requested changes made, committed and sanity checks still report ok for this module.

2017-08-12 10:15 UTC, stemid commented
I made a mistake with the rebase and now we have 20 unnecessary participants so I'm closing this and opening a new one. Sorry for the confusion.

2017-08-12 10:15 UTC, closed without merging

2017-08-12 23:07 UTC, dagwieers commented
@stemid You can always fix that by force-pushing the (corrected) branch. The pull-request will be adapted. (Often you can correct your branch using `git rebase -i HEAD~40` removing all commits unrelated to your change up to the point the branch was still in sync with devel.)