Added eagerzeroedthick disk option to disk spec for vmware_guest
ansible/ansible pull request #28121
Opened 2017-08-13 15:48 UTC by brokenjacobs

##### SUMMARY
Add eagerzeroed disk option to disk spec. This PR adds the option to use an eagerzeroed thick disk for vmware guests. This is different than the 'default' thick spec, and can have performance implications in certain environments. Vmware's API doesn't call this option eagerzeroedthick, but all of their UI interfaces and marketing literature does.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
vmware_guest module

##### ANSIBLE VERSION
```
2.4.0 0.0.devel
```

##### ADDITIONAL INFORMATION

```

```

2017-08-14 03:53 UTC, Akasurde requested changes

2017-08-14 03:53 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +    - ' - C(type) (string): Valid value is C(thin) or C(eagerzeroedthick) (default: None).'
Add a note that this option value is added in version 2.4

2017-08-14 15:48 UTC, brokenjacobs commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +    - ' - C(type) (string): Valid value is C(thin) or C(eagerzeroedthick) (default: None).'
In the text? or is there a way to add a yaml field to the doc to indicate this? (Trying to search for the answer now)

2017-08-14 15:57 UTC, brokenjacobs commented
Done. Hopefully this clarified things a bit as well.

2017-08-18 03:18 UTC, dagwieers requested changes

2017-08-18 03:18 UTC, dagwieers commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +                if expected_disk_spec.get('type', '').lower() == 'eagerzeroedthick':
Make that `elif:`

2017-08-18 03:21 UTC, dagwieers requested changes

2017-08-18 03:21 UTC, dagwieers commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +- Steve Jacobs (@stevejacobs) <sjacobs@brokencrew.com>
Well, I learned yesterday that the author-field is to be used for people that made considerable contributions to the module.

You could add yourself to .github/BOTMETA.yml if you like to help maintain this module.

2017-08-18 03:21 UTC, dagwieers commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +                if expected_disk_spec.get('type', '').lower() == 'eagerzeroedthick':
But I am wondering if these options are supposed to be mutual-exclusive, or rather that these are flags tou can enable/disable (it looks more like that).

2017-08-24 18:04 UTC, brokenjacobs commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +- Steve Jacobs (@stevejacobs) <sjacobs@brokencrew.com>
Roger the change requests I'll get them back today.

2017-09-10 18:07 UTC, brokenjacobs commented
@dagwieers a disk can be only one of 'thin' and 'eager zeroed thick', or 'thick'. They are mutually exclusive. In the vmware UI's you can select one of these types for a disk:
<img width="611" alt="screen shot 2017-09-10 at 12 06 59 pm" src="https://user-images.githubusercontent.com/3159463/30251620-963850be-9620-11e7-8a1c-98267707cb3c.png">

Hopefully this clarifies things.

2017-10-06 15:02 UTC, Akasurde commented
@brokenjacobs Could you please write an integration test for this change?

2017-11-20 16:55 UTC, Akasurde approved these changes

2017-11-21 03:11 UTC, merged