Adding public key type for ECDSA sub-types
ansible/ansible pull request #28326
Opened 2017-08-17 12:11 UTC by SpamapS

This exposes the type in the file, so that it is not lost while
gathering facts.

Closes #28325

Signed-off-by: Clint Byrum <clint@fewbar.com>

2017-08-17 12:50 UTC, emonty approved these changes
shipit

2017-08-18 14:51 UTC, s-hertel commented on lib/ansible/module_utils/facts/system/ssh_pub_keys.py
> +                    type_factname = '{}_type'.format(factname)
This will break on python 2.6. Maybe `'{0}_type'.format(factname)`?

2017-08-20 03:23 UTC, nrwahl2 commented on lib/ansible/module_utils/facts/system/ssh_pub_keys.py
> +                    type_factname = '{}_type'.format(factname)
This doesn't create the fact, at least not on my machine. I created a PR with my proposed (and tested) fix and referenced the issue. Mine could be expanded for all key types like it looks like you're shooting for here; however, if ECDSA is the only type with sub-types, then I'd think that's all we need.

2017-08-20 03:25 UTC, nrwahl2 requested changes
This code doesn't create the fact on my machine. I created PR #28449 with my proposed (and tested) fix and referenced the issue. Mine could be expanded for all key types like it looks like you're shooting for here; however, if ECDSA is the only type with sub-types, then I'd think that's all we need.

2017-08-22 23:32 UTC, SpamapS commented
I like the other one, and don't have a ton of time to devote to seeing this patch through. So thanks @nrwahl2 .. closing this PR.

2017-08-22 23:32 UTC, closed without merging