Docs fixes
ansible/ansible pull request #28383
Opened 2017-08-18 07:21 UTC by abadger

##### SUMMARY
Updates to fix warnings in docs building and updates for the recent network module changes

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME

##### ANSIBLE VERSION

```
devel
```

2017-08-18 07:33 UTC, gundalow approved these changes

2017-08-18 12:46 UTC, dagwieers approved these changes
That was an interesting read.

2017-08-18 14:08 UTC, bcoca commented on docs/bin/plugin_formatter.py
> +                                          'blurb': "These are :doc:`modules maintained by the"
should we use 'plugins' instead in view of extending the coverage?

2017-08-18 19:16 UTC, dharmabumstead requested changes
Overall looks great. A few edit suggestions. Thanks @abadger!

2017-08-18 19:16 UTC, dharmabumstead commented on docs/bin/plugin_formatter.py
> +The Ansible Core Team will review all modules becoming Certified.  Core Committers will review
please don't capitalize "committers" or "certified".

2017-08-18 19:16 UTC, dharmabumstead commented on docs/bin/plugin_formatter.py
> +not** supported by The Ansible Core Team or by companies/partners associated to the module.
Please don't capitalize "The" - should read "the Ansible Core Team"

2017-08-18 19:16 UTC, dharmabumstead commented on docs/docsite/rst/modules_support.rst
> +The Ansible Core Team will review all modules becoming Certified.  Core Committers will review proposed changes to existing Certified modules once the community maintainers of the module have approve
please don't capitalize "certified" or "committers"

2017-08-18 19:16 UTC, dharmabumstead commented on docs/templates/plugin.rst.j2
> +For more information about this module’s supportability from Red Hat, please
Consider revising to "For more information about Red Hat's support for this module..."

2017-08-18 19:16 UTC, dharmabumstead commented on docs/templates/plugin.rst.j2
> +refer to this `Knowledgebase Article<https://access.redhat.com/articles/rhel-top-support-policies>`
Please revise to "knowledge base article".

2017-08-22 18:52 UTC, merged

2017-08-22 18:52 UTC, abadger commented
Merged to devel