Clarify the apt_key module's absent state behavior
ansible/ansible pull request #28453
Opened 2017-08-20 07:11 UTC by andreaso

##### SUMMARY
Currently the apt_key module only supports removing keys based on
explicitly stated key ids. The documentation should reflect that.

Related to #26005

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
apt_key module

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel 535ede4d15) last updated 2017/08/20 09:10:33 (GMT +200)
  config file = None
  configured module search path = [u'/home/andreas/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/andreas/lab/ansible/devel/lib/ansible
  executable location = /home/andreas/lab/ansible/devel/bin/ansible
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

2017-08-23 10:48 UTC, resmo commented
shipit

2017-08-31 09:26 UTC, Shaps commented
shipit

2017-08-31 10:01 UTC, dagwieers requested changes
So there's a lot to improve to the existing documentation. I can't add comments to the stuff that's not part of the diff though.

I wonder why removing using a url is not possible. Wouldn't that be very useful ? Since the key is non-deterministic.

**Update:** I made those changes I believe are needed to the rest of the documentation.

2017-08-31 10:01 UTC, dagwieers commented on lib/ansible/modules/packaging/os/apt_key.py
>          required: false
Not your cause, but we tend to remove the following from parameter docs:
```
  required: false
  default: none
```
As they are implicit.

2017-08-31 10:01 UTC, dagwieers commented on lib/ansible/modules/packaging/os/apt_key.py
> +            - identifier of key. Including this allows check mode to correctly report the changed state. Required when C(state) is set to C(absent).
Descriptions need to start with a Uppercase character. And should be a full English sentence (or description).
So something like:

    The identifier of the key. ...

I would add the remark about when it is required on a separate bulle, at the end.

    - This parameter is required when C(state) is set to C(absent).

2017-08-31 10:01 UTC, dagwieers commented on lib/ansible/modules/packaging/os/apt_key.py
>              - "If specifying a subkey's id be aware that apt-key does not understand how to remove keys via a subkey id.  Specify the primary key's id instead."
No need to add quotes around this line.

2017-08-31 10:35 UTC, merged