Net Ping: Add new action plugin for *_ping network modules
ansible/ansible pull request #28558
Opened 2017-08-23 15:01 UTC by jmcgill298

##### SUMMARY

Add new action plugin for network ping modules

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

net_ping
##### ANSIBLE VERSION

```
2.4
```

##### ADDITIONAL INFORMATION

```

```

2017-08-23 17:30 UTC, gundalow commented
Hi, 
Can you please move this to `modules/net_tools/`

Also I think this and the ping module's `note:` section should link to the other module with `M(ping) ` stating when each one should be used.

2017-08-23 17:51 UTC, Qalthos requested changes
Can I ask why you want this? The only implementation module is presently `nxos_ping`, are you planning on submitting (or expecting to see) a ping module for another platform?

2017-08-23 17:51 UTC, Qalthos commented on lib/ansible/modules/network/ping/net_ping.py
> +                    'supported_by': 'network'}
-> `'supported_by': 'community'`

2017-08-23 17:54 UTC, jmcgill298 commented on lib/ansible/modules/network/ping/net_ping.py
> +                    'supported_by': 'network'}
https://github.com/ansible/ansible/pull/28557

2017-08-23 19:34 UTC, gundalow commented
Ignore my comment about net_tools

2017-08-23 20:32 UTC, jmcgill298 commented
@Qalthos I have updated the "supported_by"

2017-08-23 21:28 UTC, Qalthos commented
That being said, we don't need a new directory just for `ping`, module/network/system is a fine place for this module to live. Sorry for not getting that to you earlier

2017-08-23 21:31 UTC, jmcgill298 commented
alright, I will move it. I didn't like that either, but didn't know what else to do with it.

2017-08-29 15:21 UTC, jmcgill298 commented
@Qalthos any issue with this one now? Do I need to do anything to have this merged with ios_ping?

2017-08-29 15:24 UTC, Qalthos commented
Update RETURN so it matches nxos_ping/ios_ping is all you need

2017-08-29 16:03 UTC, Qalthos approved these changes

2017-08-29 17:28 UTC, merged