Adds ipa_dnszone module
ansible/ansible pull request #28790
Opened 2017-08-29 18:02 UTC by fxfitz

##### SUMMARY
This PR adds an ipa_dnszone record.

Fixes #28789 

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.3.1.0
  config file = /Users/fxfitz/dev/cyclops-ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, May 18 2017, 22:52:22) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

##### ADDITIONAL INFORMATION
We did not have a ipa_dnszone module, so here's one! Borrowed a lot from @Akasurde's work (thanks! made it much easier).

2017-08-29 18:05 UTC, fxfitz commented
Pinging @Akasurde :-D

2017-08-30 02:46 UTC, Akasurde requested changes
Few changes requested else looks good to me.

2017-08-30 02:46 UTC, Akasurde commented on lib/ansible/modules/identity/ipa/ipa_dnszone.py
> +# Borrowed heavily from other modules by Abhijeet Kasurde (akasurde@redhat.com)
Thanks. :)

2017-08-30 02:46 UTC, Akasurde commented on lib/ansible/modules/identity/ipa/ipa_dnszone.py
> +# Ansible is free software: you can redistribute it and/or modify
Can you make this as single liner GPL licence like [this](https://github.com/ansible/ansible/blob/513b582ba39a83c9400b986ff02fdd43c9ed0820/lib/ansible/modules/identity/ipa/ipa_dnsrecord.py#L4)? This is newly added thing.

2017-08-30 02:46 UTC, Akasurde commented on lib/ansible/modules/identity/ipa/ipa_dnszone.py
> +    'metadata_version': '1.0',
s/1.0/1.1/

2017-08-30 02:46 UTC, Akasurde commented on lib/ansible/modules/identity/ipa/ipa_dnszone.py
> +from ansible.module_utils.pycompat24 import get_exception
get_exception is deprecated in favor of native exception handling -

```
except Exception as e:
   module.fail_json(msg=to_native(e))
```

2017-08-30 02:46 UTC, Akasurde commented on lib/ansible/modules/identity/ipa/ipa_dnszone.py
> +        e = get_exception()
As above get_exception is deprecated in favor of native error handling.

2017-08-30 02:46 UTC, Akasurde commented
cc @Nosmoht

2017-08-30 14:49 UTC, fxfitz commented
@Akasurde Got it, thanks for the feedback! All addressed. :-)

2017-08-31 03:46 UTC, Akasurde requested changes
Everything else LGTM

2017-08-31 03:46 UTC, Akasurde commented on lib/ansible/modules/identity/ipa/ipa_dnszone.py
> +            ipa_port=dict(type='int', required=False, default=443),
One small nit pick: required by default is False so no need to specify for false values.

2017-08-31 18:46 UTC, Akasurde approved these changes
shipit

2017-09-16 10:11 UTC, resmo commented on lib/ansible/modules/identity/ipa/ipa_dnszone.py
> +                default='ipa.example.com'
wouldn't it make more sense to have localhost here?

2017-09-17 09:38 UTC, resmo commented
shipit

2017-09-27 06:32 UTC, Akasurde commented
Can someone please merge this ?

2017-09-27 06:51 UTC, resmo commented
rebuild_merge

2017-09-27 07:05 UTC, merged

2017-09-27 07:05 UTC, resmo commented
Thanks!

2017-09-27 07:29 UTC, Akasurde commented
@resmo Thanks. @fxfitz Thanks for your contribution.