EnclosureFactsModule for HPE OneView
ansible/ansible pull request #28852
Opened 2017-08-30 20:22 UTC by fgbulsoni

##### SUMMARY
Added new oneview_enclosure_facts module for retrieving [HPE OneView Enclosure](http://h17007.www1.hpe.com/docs/enterprise/servers/oneview3.0/cic-api/en/api-docs/current/index.html#rest/enclosures) resource and unit tests.

Related issue for more information: [HPE OneView support](https://github.com/ansible/ansible/issues/28354)

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
`oneview_enclosure_facts`

##### ANSIBLE VERSION
```
ansible 2.4.0 (hpe-oneview/enclosure-facts 564ac3f68a) last updated 2017/08/30 20:19:28 (GMT +000)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/vagrant/dev/core_ansible_related/ansible/lib/ansible
  executable location = /home/vagrant/dev/core_ansible_related/ansible/bin/ansible
  python version = 2.7.9 (default, Aug 21 2017, 11:24:49) [GCC 4.8.4]
```

##### ADDITIONAL INFORMATION
Example of usage:
```yaml
- name: Gather facts about all Enclosures
  oneview_enclosure_facts:
    config: /etc/oneview/oneview_config.json
  delegate_to: localhost
- debug: var=enclosures

- name: Gather paginated, filtered and sorted facts about Enclosures
  oneview_enclosure_facts:
    config: /etc/oneview/oneview_config.json
    params:
      start: 0
      count: 3
      sort: name:descending
      filter: status=OK
  delegate_to: localhost
- debug: var=enclosures

- name: Gather facts about an Enclosure by name
  oneview_enclosure_facts:
    config: /etc/oneview/oneview_config.json
    name: Enclosure-Name
  delegate_to: localhost
- debug: var=enclosures

- name: Gather facts about an Enclosure by name with options
  oneview_enclosure_facts:
    config: /etc/oneview/oneview_config.json
    name: Test-Enclosure
    options:
      - script                       # optional
      - environmentalConfiguration   # optional
      - utilization                  # optional
  delegate_to: localhost
- debug: var=enclosures
- debug: var=enclosure_script
- debug: var=enclosure_environmental_configuration
- debug: var=enclosure_utilization

- name: "Gather facts about an Enclosure with temperature data at a resolution of one sample per day, between two
         specified dates"
  oneview_enclosure_facts:
    config: /etc/oneview/oneview_config.json
    name: Test-Enclosure
    options:
      - utilization:                   # optional
          fields: AmbientTemperature
          filter:
            - startDate=2016-07-01T14:29:42.000Z
            - endDate=2017-07-01T03:29:42.000Z
          view: day
          refresh: false
  delegate_to: localhost
- debug: var=enclosures
- debug: var=enclosure_utilization
```

2017-09-12 19:59 UTC, tmiotto requested changes

2017-09-12 19:59 UTC, tmiotto commented on lib/ansible/modules/remote_management/oneview/oneview_enclosure_facts.py
> +    type: dict
I think enclosure_script return type is a string, not a dict.

2017-09-13 19:00 UTC, tmiotto commented
shipit

2017-09-14 12:18 UTC, fgbulsoni commented
@abadger @dagwieers This should be another straightforward module. Could you help review/merge it?
Thanks! :octocat:

2017-09-18 11:50 UTC, fgbulsoni commented
ready_for_review

2017-09-26 16:06 UTC, dagwieers requested changes

2017-09-26 16:06 UTC, dagwieers commented on lib/ansible/modules/remote_management/oneview/oneview_enclosure_facts.py
> +# Copyright (c) 2016-2017 Hewlett Packard Enterprise Development LP
Add blank line and format like:
```python
# Copyright: (c) 2016-2017, Hewlett Packard Enterprise Development LP
```

2017-09-26 17:54 UTC, fgbulsoni commented
Hey @dagwieers , thanks for the comment. Fixed PR according, I think the it is now ready_for_review , let me know if there's anything else or feel free to merge.

2017-10-02 17:50 UTC, tmiotto commented
shipit

2017-10-02 17:59 UTC, adriane-cardozo commented
shipit

2017-10-02 20:32 UTC, merged