Added Azure Traffic Manager Profile Support
ansible/ansible pull request #28856
Opened 2017-08-30 22:24 UTC by code4clouds

##### SUMMARY

New module that adds support for Azure Traffic Manager

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

azure_rm_trafficmanagerprofile
##### ANSIBLE VERSION

```
ansible 2.4.0 (devel 7af529f404) last updated 2017/08/30 15:12:33 (GMT -700)
  config file = None
  configured module search path = ['/home/jucolon/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jucolon/projects/python/github.com/code4clouds/ansible/lib/ansible
  executable location = /home/jucolon/projects/python/github.com/code4clouds/ansible/bin/ansible
  python version = 3.5.2 (default, Nov 17 2016, 17:05:23) [GCC 5.4.0 20160609]
```

2017-08-30 23:06 UTC, mattclay commented on test/integration/targets/azure_rm_trafficmanagerprofile/aliases
> +destructive
Include a `posix/ci/cloud/azure` alias here so the tests can run as part of CI.

2017-08-31 16:23 UTC, mattclay commented
@code4clouds You can run the test(s) which are failing locally, so you can verify your fixes before pushing changes to GitHub. For example:

```
ansible-test sanity --test validate-modules azure_rm_trafficmanagerprofile
```

2017-08-31 16:30 UTC, code4clouds commented
@mattclay Thanks again!  I found the command that did it for me, finally:  `ansible-test sanity --test ansible-doc  azure_rm_trafficmanagerprofile --python 3.5 -vvv`.  I ran the validate-modules you provided anyway and it seems is all good, unless Shippable says otherwise. :-)

2017-11-27 02:16 UTC, yuwzho commented on lib/ansible/module_utils/azure_rm_common.py
> +    def trafficmanager_client(self):
This method may need rebase and align with other create_client method

2017-11-27 02:17 UTC, yuwzho commented on lib/ansible/modules/cloud/azure/azure_rm_trafficmanagerprofile.py
> +        default: false
default is no need here

2017-11-27 02:17 UTC, yuwzho commented on lib/ansible/modules/cloud/azure/azure_rm_trafficmanagerprofile.py
> +    description: Current state of the resource group.
Description for traffic manager

2017-11-27 02:20 UTC, yuwzho commented on lib/ansible/modules/cloud/azure/azure_rm_trafficmanagerprofile.py
> +            properties=dict(type='dict'),
What are the properties? As other modules, we flatten the properties in the ansible module's parameter. And for the second level of dict type, we can use `options` to specific another spec to define the key-value pairs in the dict.

2017-11-27 02:22 UTC, yuwzho commented on lib/ansible/modules/cloud/azure/azure_rm_trafficmanagerprofile.py
> +        except CloudError:
The error is already handled by `azure_rm_common`

2017-11-27 02:23 UTC, yuwzho commented on lib/ansible/modules/cloud/azure/azure_rm_trafficmanagerprofile.py
> +def trafficmanagerprofile_group_to_dict(tm):
not invoked?

2017-11-27 02:33 UTC, yuwzho commented on lib/ansible/modules/cloud/azure/azure_rm_trafficmanagerprofile.py
> +                if self.check_mode:
Why not check the `self.check_mode` condition before call the create/upate/delete API, this can reduce the repeated work in each conditional branch

2017-11-27 02:38 UTC, yuwzho commented on lib/ansible/modules/cloud/azure/azure_rm_trafficmanagerprofile.py
> +                        try:
Is 'the name used in the DNS prefix' check required to create the traffic manager? Or the error is already handled by the create API? If so, I don't this this logic is needed here. If it is required, it should be include in check_mode

2017-11-27 02:40 UTC, yuwzho commented on lib/ansible/modules/cloud/azure/azure_rm_trafficmanagerprofile.py
> +                changed = True
In which case can reach the exception catch and we need to set the `changed` to true?

2017-11-27 02:42 UTC, yuwzho commented on lib/ansible/modules/cloud/azure/azure_rm_trafficmanagerprofile.py
> +        self.results['state'] = results
The `self.results['state']` is already set in the previous complicated logic, why here re-assign?

2017-11-27 02:43 UTC, yuwzho commented on lib/ansible/modules/cloud/azure/azure_rm_trafficmanagerprofile.py
> +                    if not bool(current_traffic_manager):
If this current_traffic_manager exist, where is the update?

2017-11-27 02:46 UTC, yuwzho commented on lib/ansible/modules/cloud/azure/azure_rm_trafficmanagerprofile.py
> +    def exist_traffic_manager_profile(self, resource_group, name):
Duplicate with `get` method? This logic can be handled as `if get_traffic_manager_profile`

2017-11-27 02:50 UTC, yuwzho commented on lib/ansible/modules/cloud/azure/azure_rm_trafficmanagerprofile.py
> +            self.fail(
Fail here make the process exit, but we need to create it if the state is present

2017-11-27 02:58 UTC, yuwzho commented on lib/ansible/modules/cloud/azure/azure_rm_trafficmanagerprofile.py
> +        monitor_properties = properties.get('monitor_config', {})
The properties' key-value and default/required can be defined in the spec.

2017-11-27 03:03 UTC, yuwzho commented on lib/ansible/modules/cloud/azure/azure_rm_trafficmanagerprofile.py
> +    def traffic_manager_to_dict(self, traffic_manager, resource_group, name, location, properties):
Make a method to determine constructing dict from which object will be confused

2017-11-27 03:05 UTC, yuwzho requested changes

2017-11-27 03:05 UTC, yuwzho commented on lib/ansible/modules/cloud/azure/azure_rm_trafficmanagerprofile.py
> +options:
Seems the description is not align with the code

2018-03-16 05:58 UTC, yuwzho commented
@code4clouds Are u still there?

2018-08-09 06:58 UTC, Fred-sun commented
Hi @code4clouds , Are you still paying attention to this PR? This PR has open more than 11 months, It too old, there exist two conflicting files, Could you solve conflict file and fix your PR as @yuwzho and @mattclay reviews?

2018-08-09 07:01 UTC, yungezz commented
duplicate with https://github.com/ansible/ansible/pull/43812

2018-08-09 15:22 UTC, code4clouds commented
My PR got submitted in Aug and it ended up been reviewed in Oct...  by the time it got reviewed it was stale due to the new Ansible release.  I would like to update the PR, but it is been hard to find cycles to fix it due to other projects.

2018-08-16 09:33 UTC, Fred-sun commented
@code4clouds Thanks for the contribution, what should we do? close this PR and reopen new or resolve the conflicting?

2018-08-17 06:23 UTC, Fred-sun commented
@code4clouds Could you help update the comment? Thanks!

2018-08-20 17:55 UTC, closed without merging