Add module to gather facts of a SolidFire cluster.
ansible/ansible pull request #28940
Opened 2017-09-01 21:00 UTC by hulquest

##### SUMMARY

Add module to gather facts of a SolidFire cluster.  The module gathers:
- Cluster information
- List cluster nodes.
- Cluster state
- Accounts
- Drives
- Volumes
- Virtual Volumes (vvols)
- Snapshots
- Cluster Faults

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

ansible/modules/storage/netapp/sf_facts.py
##### ANSIBLE VERSION

```
✔ ~/src/projects/ansible [sf-facts|✚ 1…2] 
14:44 $ ansible --version
ansible 2.4.0 (sf-facts de9f032a10) last updated 2017/09/01 14:55:21 (GMT -600)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/khulques/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/khulques/src/projects/ansible/lib/ansible
  executable location = /home/khulques/src/projects/ansible/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

```

##### ADDITIONAL INFORMATION

```

```

2017-09-02 03:33 UTC, Akasurde commented on lib/ansible/modules/storage/netapp/sf_facts.py
> +# This file is part of Ansible
Can you please replace line 4 to 19 to match a single liner GPL license (which is new in Ansible Module development)? 


```
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
```

2017-09-02 03:36 UTC, Akasurde requested changes
Rest Looks good to me.

2017-09-02 03:36 UTC, Akasurde commented on lib/ansible/modules/storage/netapp/sf_facts.py
> +from ansible.module_utils.pycompat24 import get_exception
get_exception is deprecated in favor of Python native exception handling. 

```
except Exception as e:
    module.fail_json(msg=to_native(e)
```

2017-09-07 21:28 UTC, lmprice commented on lib/ansible/modules/storage/netapp/sf_facts.py
> +        """This is the cluster identifyer."""
Typo here.

2017-09-07 21:29 UTC, lmprice approved these changes
Very minor nit, otherwise, LGTM.
shipit

2017-09-08 01:06 UTC, Akasurde commented on lib/ansible/modules/storage/netapp/sf_facts.py
> +version_added: '2.4'
2.4 branch is freezed so I guess version_added will be 2.5

2017-09-11 19:49 UTC, broncofan commented
LGTM, 
shipit

2017-09-12 04:49 UTC, Akasurde approved these changes
shipit

2017-09-13 07:16 UTC, resmo requested changes

2017-09-13 07:16 UTC, resmo commented on lib/ansible/modules/storage/netapp/sf_facts.py
> +msg:
msg is a common return and must not be documented. But your returns should be identical to the dict of facts returned.

2017-10-16 14:56 UTC, closed without merging

2017-10-16 14:56 UTC, hulquest commented
Closing this PR since I messed up the rebase.  I'll reopen a new one.