Adding support for tags and instance attributes for destination variable.
ansible/ansible pull request #29033
Opened 2017-09-06 00:33 UTC by kwoodson

2017-10-18 15:03 UTC, kwoodson commented
@bcoca,  Any way to get some traction on this one?

Thanks in advance.

2017-10-18 15:11 UTC, bcoca commented
@kwoodson bring it up with aws working group or in irc #ansible-aws

2017-10-18 15:21 UTC, ryansb requested changes
When changing code, please include docs + examples along with the code changes. 

Changing the behavior of this would also cause overlap if tags are named the same as other attributes (e.g. type)

2017-10-23 01:39 UTC, kwoodson commented
@ryansb,

I have updated the code with an explanation of the expected behavior.  Where would you recommend I show examples?  Do you want them inside of the code?  I did provide an example when opening this RFE.  I can elaborate on more examples if desired.

> Changing the behavior of this would also cause overlap if tags are named the same as other attributes (e.g. type)

I think documenting the desired behavior is sufficient (first tags, second instance attributes).  If you'd prefer we can come up with a solution for providing the type of attribute desired.  The current behavior doesn't support instance attributes so I do not believe we will break backwards compatibility.

Please let me know.  Thanks.

2017-10-23 19:19 UTC, ryansb approved these changes

2017-10-23 20:33 UTC, kwoodson commented
@ryansb, I rebased onto the latest devel branch and repushed. The bot mentioned I had a white space issue.  I did not find it on the line that was mentioned.

Thanks and sorry for any confusion.

2017-10-24 20:08 UTC, s-hertel approved these changes

2017-10-24 20:10 UTC, merged