Also render variables in task name for step mode confirmations.
ansible/ansible pull request #29105
Opened 2017-09-07 20:11 UTC by ademmers

##### SUMMARY

When running in step mode and using variables in task names, they do not get rendered. This can confuse users since they expect their variable to exist and have a decent value.

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

plugins/strategy/linear.py

##### ANSIBLE VERSION

```
ansible 2.5.0 (devel 52f2edf19d) last updated 2017/09/07 22:03:17 (GMT +200)
```

##### ADDITIONAL INFORMATION

before:
```
PLAY [Test] ******************************************************************************************************************************
Perform task: TASK: {{ avar }} is readable in task bar (N)o/(y)es/(c)ontinue: y

Perform task: TASK: {{ avar }} is readable in task bar (N)o/(y)es/(c)ontinue: ************************************************************

TASK [avalue is readable in task bar] ****************************************************************************************************
ok: [localhost] => {
    "msg": "see up and verify"
}

PLAY RECAP *******************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0
```

after:
```
PLAY [Test] ******************************************************************************************************************************
Perform task: TASK: avalue is readable in task bar (N)o/(y)es/(c)ontinue: y

Perform task: TASK: avalue is readable in task bar (N)o/(y)es/(c)ontinue: ****************************************************************

TASK [avalue is readable in task bar] ****************************************************************************************************
ok: [localhost] => {
    "msg": "see up and verify"
}

PLAY RECAP *******************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0
```

2017-09-08 01:19 UTC, samdoran commented
cc @bcoca, @jimi-c, @abadger

2018-12-07 16:25 UTC, sivel commented
We believe this could be beneficial, although this PR will need rebased and extended to the `free` strategy as well.

There are a few other concerns, but I'll leave those as a review.

needs_info

2018-12-07 16:26 UTC, sivel requested changes

2018-12-07 16:26 UTC, sivel commented on lib/ansible/plugins/strategy/linear.py
> +                        display.debug("sending task start callback, copying the task so we can template it temporarily")
You cannot move this outside of the `if not callback_sent:` block, because it will send a debug log that the callback is being sent, before we know that it is.  This applies to other lines as well.

Just move the templating outside, and leave the debugs in the `if` block.

2019-02-09 19:43 UTC, closed without merging