Fixes #20443 - Adjust version checking regex to account fo no comma in IOS-XE
ansible/ansible pull request #29157
Opened 2017-09-08 21:53 UTC by karrots

##### SUMMARY
Fixes #20443. IOS-XE doesn't have a comma after the version number. Standard IOS does. This regex allows for either. Example text can be seen here: [https://regex101.com/r/WCVPWb/2](https://regex101.com/r/WCVPWb/2)

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
ios_facts

##### ANSIBLE VERSION
```
15:45 $ ansible --version
ansible 2.5.0
  config file = /home/jkarras/netcom-network-ansible/ansible.cfg
  configured module search path = ['/home/jkarras/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.5/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.5.2 (default, Nov 17 2016, 17:05:23) [GCC 5.4.0 20160609]
```

##### ADDITIONAL INFORMATION
Bug affects back to version 2.2 per the attached issue.

2017-09-08 22:05 UTC, karrots commented
+label affects_2.2

2017-09-09 19:07 UTC, abadger commented
!python3 !needs_triage

2017-09-10 18:50 UTC, itdependsnetworks commented
@karrots 
Just happened to run into this, in the regex101 it looks like it is not catching the last `E` on the first example.

Does this look right? https://regex101.com/r/WCVPWb/3

side note, a bunch of us interested in ansible in the networking space hang out here: http://slack.networktocode.com

2017-09-11 04:17 UTC, ganeshrn approved these changes

2017-09-11 04:32 UTC, ganeshrn requested changes
@karrots As pointed out by @itdependsnetworks the current regex skips part of the version string.

If the regex suggested by @itdependsnetworks looks good to you can you make that change in your PR?

2017-09-11 04:44 UTC, karrots commented
Adjusted with @itdependsnetworks suggested changes.

2017-09-11 04:45 UTC, karrots commented
For posterity
https://regex101.com/r/WCVPWb/6

2017-09-11 05:09 UTC, ganeshrn approved these changes
Looks good

2017-09-11 08:02 UTC, gundalow commented
Can we please ensure that @itdependsnetworks is happy before this gets merged, thanks.

2017-09-11 09:32 UTC, itdependsnetworks commented
Sorry, looks good.

2017-09-11 14:08 UTC, merged