Add boot options to vsphere_guest module.
ansible/ansible pull request #30005
Opened 2017-09-12 13:47 UTC by silid

##### SUMMARY
vsphere_guest allows the creation and reconfiguration of virtual machine, however doesn't currently permit the setting of boot options, ie. boot device order and boot delay.

This modification allows the setting of those values.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
vsphere_guest

##### ANSIBLE VERSION

```
ansible 2.4.0
  config file = None
  configured module search path = [u'/home/silid/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

```

##### ADDITIONAL INFORMATION
When setting the boot order for disks and ethernet you need to know the device key of the disk and nic you want to add.

2017-09-25 22:14 UTC, silid commented
ready_for_review

2017-09-28 12:33 UTC, silid commented
@jctanner

2017-10-08 15:30 UTC, Akasurde requested changes
Rest LGTM

2017-10-08 15:30 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vsphere_guest.py
> +        if 'boot_delay' in vm_boot_options:
Could you please move this to a common function?

2018-04-02 09:04 UTC, Akasurde commented
@silid Any news ?

2018-05-04 15:10 UTC, silid commented
It seems vsphere_guest was removed in 2.5 so this pull request is no longer relevant.

2018-05-04 15:10 UTC, closed without merging