[cloud] Add support for rule description in ec2_group
ansible/ansible pull request #30300
Opened 2017-09-13 17:16 UTC by weisslj

##### SUMMARY

Add support for rule description in ec2_group. Descriptions for security group rules were announced on Aug 31, 2017: https://aws.amazon.com/blogs/aws/new-descriptions-for-security-group-rules/

This requires botocore >= 1.7.2. If an older version is used
- and the user tries to use rule descriptions in the YAML file, an error is printed
- and the rule descriptions are not used, everything works like before this change (i.e. rule descriptions entered via web console are not touched)

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

lib/ansible/modules/cloud/amazon/ec2_group.py

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/weisslj/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/weisslj/.local/lib/python2.7/site-packages/ansible-2.5.0-py2.7.egg/ansible
  executable location = /home/weisslj/.local/bin/ansible
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

2017-09-13 18:00 UTC, weisslj commented
The IAM test policy needs to be updated @mattclay or @gundalow:

> ClientError: An error occurred (UnauthorizedOperation) when calling the UpdateSecurityGroupRuleDescriptionsIngress operation: You are not authorized to perform this operation.

This feature needs `UpdateSecurityGroupRuleDescriptionsIngress` and `UpdateSecurityGroupRuleDescriptionsEgress`.

2017-09-13 18:09 UTC, mattclay commented
@s-hertel is working on updating the test policy.

2017-09-13 18:51 UTC, mattclay commented
Also, this appears to overlap with the changes from https://github.com/ansible/ansible/pull/30273.

2017-09-13 19:44 UTC, weisslj commented
@mattclay Sadly yes, I started implementing today before @s-hertel opened his pull request ...

2017-09-13 22:09 UTC, s-hertel commented
@weisslj Sorry.

2017-09-14 03:16 UTC, willthames requested changes
I know this clashes with #30300 but I'll give minimal feedback anyway.

If the tests need more IAM permissions, please update hacking/aws_config/testing_policies/ec2-policy.json to reflect that so that it's easy for people to test from their own account.

2017-09-14 03:16 UTC, willthames commented on lib/ansible/modules/cloud/amazon/ec2_group.py
> +    if StrictVersion(botocore.__version__) < StrictVersion(minimum_botocore_version):
Prefer to use something like `hasattr(client, "update_security_group_rule_descriptions_ingress")` to test whether we have a new enough botocore.

2017-09-14 15:47 UTC, mattclay commented
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/37295/40/tests

2017-11-01 14:35 UTC, s-hertel commented
Closing because this feature was added for 2.5 in 1dd55acbc211d854a6cded0f813334325bac4038. @weisslj Thanks for the contribution. Sorry we stepped on each other!

2017-11-01 14:35 UTC, closed without merging