modules/system/user.py: Replace deprecated platform.dist() call
ansible/ansible pull request #30481
Opened 2017-09-17 22:10 UTC by nrwahl2

##### SUMMARY
modules/system/user.py: Replace deprecated platform.dist() call

`platform.dist()` and `platform.linux_distribution()` are deprecated and expected to be removed in Py3.7 (https://bugs.python.org/issue1322). There was discussion that due to cross-platform reliability issues it should not be included in the standard library. I don't see much in the way of what should replace it, except a module called `distro` (https://github.com/nir0s/distro#distro---a-linux-os-platform-information-api). `distro` is not part of the standard distribution of Python and currently needs to be installed separately. We probably need to re-evaluate how `module_utils/basic.py` gets distribution info as well.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
modules/system/user.py

##### ANSIBLE VERSION
```
ansible 2.5.0 (issue/30179_3 16b8d24dfd) last updated 2017/09/17 17:01:10 (GMT -500)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/reid/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/reid/git/ansible/lib/ansible
  executable location = /home/reid/git/ansible/bin/ansible
  python version = 2.7.13 (default, Sep  5 2017, 08:53:59) [GCC 7.1.1 20170622 (Red Hat 7.1.1-3)]
```

##### ADDITIONAL INFORMATION
N/A

2017-09-17 22:56 UTC, bcoca commented
Outside of testing this is what a quick `git grep shows`:
```
lib/ansible/module_utils/basic.py:            distribution = platform.dist()[0].capitalize()
lib/ansible/module_utils/basic.py:            distribution_version = platform.dist()[1]
lib/ansible/module_utils/facts/system/distribution.py:            # only the distribution name is set, the version is assumed to be correct from platform.dist()
lib/ansible/module_utils/facts/system/distribution.py:        dist = platform.dist()
lib/ansible/module_utils/facts/system/distribution.py:        dist = platform.dist()
lib/ansible/modules/cloud/misc/xenserver_facts.py:        result = platform.dist()[1]
lib/ansible/modules/system/user.py:                dist = platform.dist()
```

I would create a fix in basic.py and have user/xenserver_facts/general facts all rely on it

2017-09-17 23:02 UTC, nrwahl2 commented
Agreed, once we have a fix in mind. If we choose to merge, this should take care of it in the single-platform use case in the `user` module.

2018-05-11 21:42 UTC, bcoca requested changes
This is not a valid replacement, i would keep the platform call and try it, on capturing the failure i would try alternate methods .. but these need to handle more than just RH linux.

2018-05-11 21:53 UTC, nrwahl2 commented
@bcoca: I apologize for my extended absence on some of these previous PRs from last fall, some of which were ill thought-out. On this one, @alikins has done some much better work. Last updated in February though.

- Remove use of platform.dist() and platform.linux_distribution() methods removed in python 3.7 #30489
- Add compat_platform.py to provide deprecated platform.dist (https://github.com/alikins/ansible/commit/e8c252a6416515afd34e844a6be3455e818188ce)
- WIP: Platform nir0s distro #35985


I'm going to close this PR.

2018-05-11 21:53 UTC, closed without merging