[WIP] updated  plugin docs
ansible/ansible pull request #30490
Opened 2017-09-18 01:26 UTC by bcoca

##### SUMMARY
- for devs:
  - added inventory/vars section
  - made some updates to general section and other plugin types
- for users:
 - added 'user' plugin section to start describing the plugins
 - docs on types, what they are and how to use

TODO: link to docs generated from 'plugin embeded docs'

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME

docs
##### ANSIBLE VERSION

```
2.4/2.5
```

2017-09-18 02:24 UTC, dharmabumstead approved these changes
Approved with copy edits. Thanks @bcoca!

2017-09-21 04:15 UTC, dharmabumstead requested changes
Copy edit pass in progress. Please do not merge until the docs team signs off.

2017-09-21 06:24 UTC, dharmabumstead requested changes
Approved with copy edits, except for one review comment.

2017-09-21 06:24 UTC, dharmabumstead commented on docs/docsite/rst/plugins/shell.rst
> +Aside from the default configuration settings in :doc:`../config`, you can use a 'connection variable'
Is this correct or copy-pasta?

2017-09-21 13:34 UTC, bcoca commented on docs/docsite/rst/plugins/shell.rst
> +Aside from the default configuration settings in :doc:`../config`, you can use a 'connection variable'
yes

2017-09-22 23:47 UTC, dharmabumstead commented on docs/docsite/rst/plugins/shell.rst
> +Aside from the default configuration settings in :doc:`../config`, you can use a 'connection variable'
Which is it?

2017-09-22 23:49 UTC, bcoca commented on docs/docsite/rst/plugins/shell.rst
> +Aside from the default configuration settings in :doc:`../config`, you can use a 'connection variable'
it is correct

2017-09-23 03:19 UTC, merged