Add support for replacing an existing openstack keypair
ansible/ansible pull request #30565
Opened 2017-09-19 18:03 UTC by emonty

##### SUMMARY
Nova doesn't allow updating keypairs, so one must delete and recreate. Add a 'replace' state to allow
replacing a keypair with new content if necessary.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
os_keypair

2018-02-01 16:41 UTC, ssbarnea commented
Can we have this PR refreshed?

2018-02-01 16:42 UTC, ssbarnea requested changes
Please fix current CI errors. Fixing this bug would be great.

2018-10-13 18:13 UTC, mnaser commented
This should resolve #30334 once it lands, if someone can respin this.

2020-01-20 13:53 UTC, sshnaidm commented
Thanks for submitting patch for Openstack Ansible modules!
We moved Openstack Ansible modules to Openstack repositories.
Next patches should be submitted not with Ansible Github but with
Openstack Gerrit: https://review.opendev.org/#/q/project:openstack/ansible-collections-openstack
Please submit your code there from now.
Thanks for your contribution and sorry for inconvienience.

2020-05-20 15:33 UTC, closed without merging