More porting updates
ansible/ansible pull request #30635
Opened 2017-09-20 14:55 UTC by bcoca

##### SUMMARY

added new notes on callbacks
##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

docs
##### ANSIBLE VERSION

```
2.4/2.5
```

2017-09-20 14:58 UTC, gundalow requested changes

2017-09-20 14:58 UTC, gundalow commented on docs/docsite/rst/porting_guide_2.4.rst
> +* Callbacks are now using the new configuration system, users should not need to change anything as the old system still works,
Newline here

https://github.com/bcoca/ansible/blob/more_porting_updates/docs/docsite/rst/porting_guide_2.4.rst#callback-plugins

2017-09-20 14:58 UTC, gundalow commented on docs/docsite/rst/porting_guide_2.4.rst
> +* If your callback does not inherit from ``CallbackBase`` (directly or indirectly via another callback), it will still work, but issue a deprecation notice.
Newline here

2017-09-20 14:59 UTC, gundalow commented on docs/docsite/rst/porting_guide_2.4.rst
> +  but you might see a deprecation notice if any callbacks used are not inheriting from the built in classes. Developers need to update them as stated below.
s/but/however/

2017-09-20 15:03 UTC, gundalow approved these changes

2017-09-20 19:12 UTC, merged

2017-09-21 04:04 UTC, dharmabumstead commented
This needs edits and should not have been merged. Please DO NOT merge documentation PRs until someone from the docs team has had a chance to review them. Thank you.