vmware_guest_snapshot - Add the ability to rename a snapshot, or change it's description.
ansible/ansible pull request #31441
Opened 2017-10-07 16:02 UTC by garbled1

Add the ability to rename a snapshot, or change it's description.
Also add tests for vmware_guest_snapshot, but disable them due to vcsim not fully supporting such operations yet.

##### SUMMARY
vmware_guest_snapshot currently has no way to rename a snapshot, or change it's description.  This patch adds the ability to do so with two new options, new_snapshot_name, and new_description.  If state == present, and these options are specified, it will rename the snapshot to the new name, or change the description, as needed.

This allows me to snap a machine in a loop, always keeping a set number of snapshots, such as a daily snapshot, with 3 I could revert to.

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

lib/ansible/modules/cloud/vmware/vmware_guest_snapshot.py

##### ANSIBLE VERSION

```
ansible 2.5.0 (vmware_snapshot_rename 2e14b1ad29) last updated 2017/10/07 15:56:47 (GMT +000)
  config file = None
  configured module search path = [u'/home/ec2-user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ec2-user/ansible/lib/ansible
  executable location = /home/ec2-user/ansible/bin/ansible
  python version = 2.7.12 (default, Sep  1 2016, 22:14:00) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
```

##### ADDITIONAL INFORMATION

```
 - name: Rename snapshot
   vmware_guest_snapshot:
     validate_certs: False
     hostname: host
     username: user
     password: password
     datacenter: dc1
     folder: /path/to/vm
     name: vm_name
     state: present
     snapshot_name: snap_a
     new_snapshot_name: snap_c
     new_description: "Renamed a to c"

```

2017-10-07 16:17 UTC, Akasurde requested changes

2017-10-07 16:17 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_guest_snapshot.py
> +        new_snapshot_name=dict(required=False, type='str'),
required is by default False, so need to set it explicitly.

2017-10-07 16:17 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_guest_snapshot.py
> +            self.module.exit_json(msg="VM - %s doesn't have any snapshots" % self.module.params["name"])
I would write it as - 

``` 
self.module.params.get('uuid') or self.module.params.get('name') 
```

2017-10-07 16:17 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_guest_snapshot.py
> +                msg="Couldn't find any snapshots with specified name: %s on VM: %s" %
I would write it as - 

``` 
self.module.params.get('uuid') or self.module.params.get('name') 
```

2017-10-07 16:17 UTC, Akasurde commented on test/integration/targets/vmware_guest_snapshot/tasks/main.yml
> +#     description: "snap named {{item}}"
Missing `with_items` or typo.

2017-10-09 15:13 UTC, garbled1 commented on lib/ansible/modules/cloud/vmware/vmware_guest_snapshot.py
> +                msg="Couldn't find any snapshots with specified name: %s on VM: %s" %
This was fixed by my other commits.

2017-10-09 17:11 UTC, Akasurde approved these changes
shipit

2017-10-23 07:42 UTC, Akasurde commented
@jctanner @dagwieers Could you please take a look and merge this ?

2017-10-30 16:20 UTC, merged