Add host vars compatibility  with new variable
ansible/ansible pull request #31513
Opened 2017-10-10 08:57 UTC by aperigault

##### SUMMARY
I like the new `precedence` parameter but I can't use it to change host vars order. This PR add host vars management.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
vars/manager.py

##### ANSIBLE VERSION
```
ansible 2.4.0.0
```

2017-10-10 16:26 UTC, mattclay commented
CI failure in integration test `test/integration/targets/hosts_field/test_hosts_field.yml:48`:

The task includes an option with an undefined variable. The error was: 'inventory_hostname' is undefined The error appears to have been in '/root/ansible/test/integration/targets/hosts_field/test_hosts_field.yml': line 48, column 7, but may be elsewhere in the file depending on the exact syntax problem. The offending line appears to be: tasks: - command: echo 'Running on {{ inventory_hostname }}' ^ here We could be wrong, but this one looks like it might be an issue with missing quotes. Always quote template expression brackets when they start a value. For instance: with_items: - {{ foo }} Should be written as: with_items: - "{{ foo }}"

CI failure in unit tests:

https://app.shippable.com/github/ansible/ansible/runs/40314/2/tests

2017-11-03 17:09 UTC, aperigault commented
@mattclay After rebase all seems to be ok.

2017-11-03 17:26 UTC, bcoca commented
-1 too many things break if you let groups have precedence over hosts

2017-11-03 17:26 UTC, bcoca requested changes
-1 too many things break if you let groups have precedence over hosts

2017-11-07 09:39 UTC, aperigault commented
@bcoca better ?

2017-11-24 15:34 UTC, aperigault commented
Anybody can review this ?

2018-01-03 10:05 UTC, aperigault commented
@bcoca Are you ok with this change ?

2018-03-19 16:29 UTC, aperigault commented
I'm steel waiting for merge that. I use it in production since a lot of month without problem.
@bcoca Are you waiting anything ?

2018-03-28 14:56 UTC, aperigault commented
Nobody want to review this ? Maybe @gundalow ?

2018-10-19 04:10 UTC, mattclay commented
@aperigault This PR contains many unrelated commits, most likely from a rebase. Can you please rebase this PR to eliminate the unwanted commits? Our [rebasing documentation](https://docs.ansible.com/ansible/devel/dev_guide/developing_rebasing.html) may help.

2018-11-27 17:25 UTC, aperigault commented
@mattclay Rebase done !
Can you review this ?

2020-12-04 15:37 UTC, s-hertel commented
@aperigault Can you add tests and a changelog for this?

2021-04-23 08:36 UTC, closed without merging