[WIP] Port ec2_elb to boto3 - fixes #30229
ansible/ansible pull request #31892
Opened 2017-10-18 12:52 UTC by s-hertel

##### SUMMARY
Needs integration tests still. Fixes #30229 by adding AWSRetry.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/modules/cloud/amazon/ec2_elb.py

##### ANSIBLE VERSION
```
2.5.0
```

2017-10-24 17:17 UTC, s-hertel commented
Need to add permissions to Shippable and update the policy in hacking/aws_config.

2017-10-25 23:52 UTC, ryansb requested changes

2017-10-25 23:52 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/ec2_elb.py
> +        module.fail_json_aws(e)
Please also provide a message here.

2017-10-25 23:52 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/ec2_elb.py
> +            self.module.fail_json_aws(e)
Message on fail please :smiley:

2017-10-25 23:52 UTC, ryansb commented on test/integration/targets/ec2_elb/tasks/main.yml
> +- block:
I think `block` has a `environment:` attribute that you can use to set all the aws secret/key id/session token variables as their bash appropriate versions (AWS_SECRET_KEY etc) and not have to do so on every module call. 

For the tests checking that the module fails correctly when missing credentials, put them in a separate block.

2017-10-25 23:52 UTC, ryansb commented on test/integration/targets/ec2_elb/tasks/main.yml
> +          - "result.failed"
The preferred way to check failure is to use the filter, so there's no error if that attribute is undefined. Just `result | failed`

2017-12-05 03:19 UTC, ElijahLynn commented
I have been testing this for some provisioning over the past week and it has saved the day in terms of preventing API throttled errors/messages from AWS!!! So, :+1: for some basic testing so far.

2017-12-11 12:03 UTC, wimnat commented
I thought the plan for this was to just leave this module 'as-is' and instead create elb_classic_lb as the boto3 version allowing us to fix return values etc to be more in line with elb_application_lb?

2017-12-11 21:14 UTC, s-hertel commented
@wimnat Ah....Sigh. Yes, that was the plan. Thanks for noticing this!

2017-12-11 21:14 UTC, closed without merging

2017-12-11 21:17 UTC, s-hertel commented
@wimnat Are you working on elb_classic_lb for 2.5?

2017-12-12 11:54 UTC, wimnat commented
I'd like to but not started yet. However my head is in the space now - just pushed WIP PR for elb_network_lb.

2018-04-10 15:44 UTC, ElijahLynn commented
Here is the WIP PR referenced by @wimnat https://github.com/ansible/ansible/pull/33808

2018-05-12 22:01 UTC, jchristi commented
The above linked PR is for [elb_network_lb](https://github.com/wimnat/ansible/blob/3150abae56f304f6091ae7d1eb42f782de1da501/lib/ansible/modules/cloud/amazon/elb_network_lb.py), not [elb_classic_lb](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/elb_classic_lb.py) or [ec2_elb_lb]((https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/ec2_elb_lb.py)). A quick look at the above two modules show they are both still using old boto. Is there anywhere boto3 conversion for a classic elb is being tracked? @ElijahLynn and I really want this!

2018-07-11 21:44 UTC, ElijahLynn commented
@s-hertel Do you know if this functionality is somehow in the recent 2.6 release? I see https://github.com/ansible/ansible/blame/devel/lib/ansible/modules/cloud/amazon/elb_application_lb.py#L28 uses boto3 but did not see any reference of exponential or backoff, but that doesn't mean for sure it isn't included.

2018-09-12 13:23 UTC, s-hertel commented
@wimnat @ElijahLynn @jchristi Hi, all. Linking a pull request to port elb_classic_lb to boto3 for 2.8. If any of you will use it, testing/reviewing what is there would be greatly appreciated. https://github.com/ansible/ansible/pull/45434

@ElijahLynn Are you having throttling issues with the elb_application_lb module? elb_application_lb is boto3 and uses AWSRetry (the retried calls are being done in module_utils/aws/elbv2.py and module_utils/aws/elb_utils.py).

2018-09-12 16:31 UTC, jchristi commented
@s-hertel I have been using elb_application_lb and have yet to see any API throttling there. I doubt I will be able to find the time to test classic elb, but I'll let you know if I do.

2018-10-10 16:38 UTC, jamiecwilliams commented
> I thought the plan for this was to just leave this module 'as-is' and instead create elb_classic_lb as the boto3 version allowing us to fix return values etc to be more in line with elb_application_lb?

> @wimnat Ah....Sigh. Yes, that was the plan. Thanks for noticing this!

@s-hertel, isn't this PR for porting the `ec2_elb` module? The `ec2_classic_lb` module should not be relevant, because it is for managing the lbs, where `ec2_elb` is for registering instances. As far as I can tell, there is no alternative to `ec2_elb` which is boto3 based, and it is still lacking AWSRetry support. @ryansb added `ec2_elb` to the list of "boto only" modules very recently: https://github.com/ansible/community/blob/master/group-aws/boto3.md

Perhaps @wimnat confused your effort with decisions over the `ec2_elb_lb` module, which has been superceded (if I understand correctly) by `ec2_classic_lb`, `ec2_network_lb`, and `ec2_appliance_lb`?
Issue https://github.com/ansible/ansible/issues/30494 regarding renaming or replacing existing lb-related modules, suggested `ec2_instance` as a new boto3 module. However, `ec2_instance` is also in the list of "boto only" modules. The current documentation does not indicate any retry capability in this new module either.

I'm having major difficulty due to throttling with the `ec2_elb` module. Is there any reason `elb_instance` would reduce throttling problems? What is the difference between `ec2_elb` and `ec2_instance` if they both use boto? Is there still a plan to update either to boto3?

Since issue https://github.com/ansible/ansible/issues/30229 references this PR and is still open, and this is still a current problem with this module, I request that this PR be re-opened or similar changes be made to the `ec2_instance` module.