xml filter plugin
ansible/ansible pull request #31948
Opened 2017-10-19 20:36 UTC by GIC-de

##### SUMMARY
The xml filter plugin allows to retrieve the text of an xml element within an xml structure provided as string. 

Example Usage: 
```
  - name: show version
    junos_rpc:
        rpc: get-software-information
    register: junos_version

  - name: ...
...
     when: junos_version.xml|xml_findtext('.//package-information[name=\"junos-openconfig\"]/comment') != "JUNOS Openconfig [0.0.0.5]"
```

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
- `lib/ansible/plugins/filter/xml.py`

##### ANSIBLE VERSION
```
ansible 2.3.2.0
```

2017-10-21 22:18 UTC, dagwieers commented
In the example, why is the double-quote being escaped ?

2017-10-21 22:22 UTC, dagwieers commented
This is looking good, and should problably get a mention in the xml/win_xml module documentation as well as [the xml module Wiki page](https://github.com/ansible/community/wiki/Module:-xml).

2017-10-21 22:23 UTC, dagwieers requested changes

2017-10-21 22:23 UTC, dagwieers commented on lib/ansible/plugins/filter/xml.py
> +# (c) 2017, Christian Giese (@GIC-de)
This should be:
```python
# Copyright: (c) 2017, Christian Giese (@GIC-de)
```

2017-10-21 22:23 UTC, dagwieers commented on lib/ansible/plugins/filter/xml.py
> +# This file is part of Ansible
We now have a single line GPL license statement.
```python
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
```

2017-11-01 20:09 UTC, dagwieers approved these changes
LGTM

2018-01-10 20:45 UTC, GIC-de commented
New `xml_find` filter which allows to iterate over an xml structure.

```
  - name: check isis adjacency
    fail:
        msg: "isis adjacency not up"
    when: "item|xml_findtext('.//adjacency-state') != 'Up'"
    with_items: "{{ isis_adjacency.xml|xml_find('.//isis-adjacency') }}"
```

2018-01-31 10:28 UTC, GIC-de commented
@dagwieers is there something missing to get this change merged?

2018-12-05 20:23 UTC, maxamillion commented
First off, apologies for the lag time on this and thank you for the pull request!

Could you please add some [integration tests](https://docs.ansible.com/ansible/latest/dev_guide/testing_integration.html) to exercise the new functionality added? Also, please include a [changelog fragment](https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#changelogs). Also, some notation in the [filters doc](https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html) would be appreciated, the notable file is `./docs/docsite/rst/user_guide/playbooks_filters.rst`. Otherwise the changes look good. 👍

2018-12-05 20:24 UTC, maxamillion commented
needs_revision

2018-12-19 21:21 UTC, mattclay commented on test/integration/targets/xml/tasks/main.yml
> +  - include_tasks: test-xml-filter.yml
Put the filter tests in the `filters` target. You'll need to update the requirements list for the test as well:

https://github.com/ansible/ansible/blob/4bd60c313bac585ca012d9729fac8e65da4b2c67/test/integration/targets/filters/runme.sh#L7

2019-05-01 18:45 UTC, thedoubl3j commented
ping @GIC-de are you still interested in getting this merged? Looks like there is conflict with `test/integration/targets/filters/tasks/main.yml` and will need a rebase so that it can run through CI again.

2019-08-08 14:37 UTC, closed without merging