pep8 related changes in file lib/ansible/modules/system/group.py
ansible/ansible pull request #32307
Opened 2017-10-29 07:25 UTC by Akshay67

##### SUMMARY

Easy Fixes related pep8

##### ISSUE TYPE

Bugfix Pull Request

##### COMPONENT NAME

System - group.py
##### ANSIBLE VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

2017-10-30 05:19 UTC, Akasurde requested changes

2017-10-30 05:19 UTC, Akasurde commented on lib/ansible/modules/notification/flowdock.py
> +            type=dict(required=True, choices=["inbox","chat"]),
Remove additional trailing whitespace.

2017-10-30 11:52 UTC, Akasurde commented
@Akshay67 Could you please rebase PR ?

2017-11-07 13:33 UTC, dagwieers commented
These changes have already been fixed in previous merge.

2017-11-07 13:33 UTC, closed without merging