Add adhoc callbacks to mirror playbook start/stats
ansible/ansible pull request #32304
Opened 2017-10-29 05:01 UTC by cognifloyd

##### SUMMARY
This adds two new callbacks to signal before and after all adhoc tasks
have run. The form and function mirror the playbook equivalents.

New callbacks:
- v2_adhoc_on_start (gets a Play instead of Playbook)
- v2_adhoc_on_stats (gets the same stats as v2_playbook_on_stats)

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
adhoc cli
callbacks base

##### ANSIBLE VERSION
devel

##### ADDITIONAL INFORMATION
I want to make the JSON callback work for adhoc commands. However, with the current callbacks, the only way to handle output is to print a stream of objects (triggered via `v2_runner_on_*`. Though a `json_stream` callback could be cool, that's not how the `json` callback functions for playbook, so it shouldn't  send a stream for adhoc either. In order to print the output only after the last host has finished it's task, the callback needs to know when the adhoc "play" has finished. So, I added these two callbacks to signal start and end of the adhoc run.

This has the bonus effect of supplying stats at the end of the adhoc tasks. :)

Though this is a new feature, it feels like a very minor addition to me, one that no one will notice unless they specifically add support for it in a callback plugin. So, could this, perhaps, be considered for a 2.4.* release?

2017-10-29 05:06 UTC, bcoca requested changes
I don't think we need new callbacks, just add a call to the existing ones with 'adhoc' as the playbook.

2017-10-30 19:15 UTC, cognifloyd commented
> I don't think we need new callbacks, just add a call to the existing ones with 'adhoc' as the playbook.

The callback plugins that provide `v2_playbook_on_start` (`default`, `logstash`, `mail`, `slack`, and `junit`) all access only one attribute on the playbook arg of `v2_playbook_on_start`: `playbook._file_name`. So, I created a dummy playbook to make sure callback plugins do not receive unexpected input.

2017-10-30 19:31 UTC, cognifloyd commented
I edited the description to accurately describe this new approach (reusing callbacks instead of making new ones)

2017-10-30 20:49 UTC, cognifloyd commented
CI failures are 404s when downloading an sl-<version>.rpm or a yum installation seems to fail. So, that's not related to this PR.

2017-10-30 21:29 UTC, bcoca approved these changes

2017-10-30 21:31 UTC, bcoca commented
code looks good, posted to core group meeting agenda to get vote on the functionality itself.

2017-10-30 21:38 UTC, sivel commented
I'll try to attend, but I am in favor of this.  Having `_stats` which would allow for a recap to displayed can be a huge benefit, especially if you are running an adhoc task against hundreds of servers, a recap at the end is great.

2017-10-30 21:40 UTC, bcoca commented
@sivel, this makes it possible, it is just not in the default callcback for adhoc (minimal)

2017-10-30 21:41 UTC, sivel commented
> @sivel, this makes it possible, it is just not in the default callcback for adhoc (minimal)

I'm ok with that.  We could always decide to add it by default later.  But this allows for local customizations to get that.

2017-10-30 22:40 UTC, armab commented
This is the part of a bigger idea to make short Ansible `ad-hoc` runs more easily integrated with other tools or workflows where output could be easily parsed via enabling built-in `json` (or other) callback. 

> See related https://github.com/ansible/ansible/pull/26098 which enabled `stdout_callback` for ad-hoc commands and is part of that story.


This brings broader Ansible use as well.
Quick example: `ansible | jq`.

Thanks to this PR, we'll have consistent callback behavior for `ad-hoc` executions following existing playbook runs logic.

2017-10-31 00:14 UTC, cognifloyd commented
@bcoca you put it on November's Agenda [1] instead of October [2]. So, should I plan to attend on Thursday (Nov 2) instead of tomorrow (Oct 31)?

[1] ansible/community#273
[2] ansible/community#263

2017-10-31 00:20 UTC, bcoca commented
@cognifloyd feel free to reschedule, i put in first ticket i found

2017-11-01 19:03 UTC, cognifloyd commented
Including callbacks in adhoc runs was approved in the meeting. Is anything else required before merging?

Example: @bcoca mentioned that the dummy playbook felt off, and I agree, creating it felt weird. Any suggestions on better ways to do this?

2017-11-01 20:46 UTC, merged

2017-11-01 20:46 UTC, bcoca commented
@cognifloyd if i figure out a better way i'll update it, for now the current code works.