[WIP] Add option to `ipa_user` for setting expiration date
ansible/ansible pull request #32369
Opened 2017-10-31 03:46 UTC by akatch

##### SUMMARY
Accept `krbpasswordexpiration` parameter, allowing the user to set an expiration date on the specified user.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
ipa_user module

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ally/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

##### ADDITIONAL INFORMATION

```

```

2017-10-31 04:33 UTC, Akasurde requested changes

2017-10-31 04:33 UTC, Akasurde commented on lib/ansible/modules/identity/ipa/ipa_user.py
> +    - e.g. 20180121182022 will expire on 21 January 2018 at 18:20:22
@akatch please add version in which this option is being added. 

like 

```
version_added: 2.5
```

2017-10-31 05:36 UTC, Akasurde commented
cc @fxfitz @day4skiing

2017-10-31 06:32 UTC, Nosmoht commented
shipit

2017-10-31 18:45 UTC, day4skiing commented
Nice, wasn't sure what format the date would be in but that is good format.  Thanks

2017-11-01 14:46 UTC, fxfitz approved these changes

2017-11-01 15:27 UTC, Akasurde approved these changes
shipit

2017-11-23 02:19 UTC, Akasurde commented
rebuild_merge

2017-11-23 02:29 UTC, merged