safer task results
ansible/ansible pull request #32480
Opened 2017-11-02 02:32 UTC by bcoca

##### SUMMARY

Pass scaled down objects with needed data, but w/o methods

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

task result
##### ANSIBLE VERSION

```
2.5
```

2017-11-02 18:29 UTC, alikins commented
What is this trying to fix?

Does TaskResult need to return the same class types?  
Seems like task_executor should be able to return data objects instead of the
full classes  (more or less a DTO...). Is something later type checking?

Task/Host classes seem like they should be responsible for providing
a copy of just their data. Ideally they would be using it internally (Task has-a TaskModel, etc).

2017-11-02 18:33 UTC, alikins requested changes

2017-11-02 18:33 UTC, alikins commented on lib/ansible/utils/helpers.py
> +class Chameleon(object):
These (Chameleon, data_object_shim) are kind of unusual classes and method. So the comments/commit msgs need to explain why they are needed and how they accomplish that and why normal approaches are not applicable.

2017-11-02 20:56 UTC, bcoca commented
I'm trying to avoid having callbacks influence play behaviour, currently they can alter the actual play objects in ways that user would not be able to easily audit, those behaviors should be apparent in playbook itself. This also can be a security issue once callbacks are easier to install, it is better to have the locks in the engine than the callbacks themselves.

As for class types, this is due to some checks in callbacks, not sure if we can/should support that though, i'm still trying to figure out the happy medium.

That is what taskresult itself does, but I was looking for 'shorter' approach than having to create 'data only' shims for every class.

2017-11-06 00:45 UTC, abadger commented
I've been thinking about this and I'm no longer sure that we should do this because it is a backwards incompatible change.  In our tree we only use callbacks for display but 3rd parties could be using those objects to make changes or other introspection that needs the original objects.  We need to decide if this is something we feel we can break backwards compatibility on immediately or if we should take a different strategy.

2025-06-04 20:18 UTC, closed without merging