win_become: add info about recent admin changes
ansible/ansible pull request #32583
Opened 2017-11-06 02:00 UTC by jborean93

##### SUMMARY
Updates the docs about become `runas` after it has recently been changed https://github.com/ansible/ansible/pull/32485

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
win_become

##### ANSIBLE VERSION
```
2.5
```

2017-11-06 12:37 UTC, dagwieers approved these changes
LGTM

2017-11-06 21:02 UTC, nitzmahone approved these changes

2017-11-07 06:58 UTC, dharmabumstead requested changes

2017-11-07 06:58 UTC, dharmabumstead commented on docs/docsite/rst/become.rst
> +  token, only a subset of the privileges assigned to user are available during
s/comma/period and new sentence here please.

2017-11-07 06:58 UTC, dharmabumstead commented on docs/docsite/rst/become.rst
> +.. Note:: Granting the ``SeTcbPrivilege`` or turning UAC off subverts the
Please change the last bit of this from “subverts the...” to something like “...can cause Windows security vulnerabilities.”

2017-11-07 06:58 UTC, dharmabumstead commented on docs/docsite/rst/become.rst
> -  2.4 release of Ansible.
s/Server 2008/Windows Server 2008

2017-11-09 00:02 UTC, merged