Issue #26951
ansible/ansible pull request #32601
Opened 2017-11-06 17:40 UTC by shitalmule04

##### SUMMARY

   Bug fixed from issue #26951 

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

 /config/data
##### ANSIBLE VERSION

```
2.5
```

##### ADDITIONAL INFORMATION

```

```

2017-11-14 17:41 UTC, Akasurde requested changes

2017-11-14 17:41 UTC, Akasurde commented on lib/ansible/cli/config.py
> +# (c) 2017, Ansible by Red Hat, Inc.
Please do not add this again as short GPL licence is added already.

2017-11-14 17:41 UTC, Akasurde commented on lib/ansible/cli/config.py
> +    VALID_ACTIONS = ("view", "dump", "list")   # TODO: edit, update, search
I think this is typo.

2017-12-08 14:38 UTC, gundalow commented
As agreed in 2017-12-07 Core meeting, we've done bulk pep8 fixes across all modules in `devel`.

This was done in https://github.com/ansible/ansible/pull/33682 and https://github.com/ansible/ansible/pull/33690 which have been merged into `devel`. because of this you will need to rebase your PR. Thanks in advance.

2017-12-08 14:39 UTC, gundalow commented
Or perhaps this PR should be closed?

2017-12-08 18:54 UTC, gundalow requested changes

2017-12-08 18:54 UTC, gundalow commented on lib/ansible/modules/cloud/amazon/aws_kms.py
> +                key_id = a['TargetKeyId']
Please revert this

2017-12-08 18:54 UTC, gundalow commented on lib/ansible/cli/config.py
> +# (c) 2017, Ansible by Red Hat, Inc.
Please revert this

2017-12-08 18:54 UTC, gundalow commented on lib/ansible/cli/config.py
> +    VALID_ACTIONS = ("view", "dump", "list")   # TODO: edit, update, search
Please revert this

2017-12-08 19:00 UTC, sivel requested changes

2017-12-08 19:00 UTC, sivel commented on lib/ansible/modules/cloud/amazon/aws_kms.py
> +                elif role_arn in statement['Principal']['AWS']:   # not one the places the role should be
This is not a PEP8 change this is a functional change, not described as part of this pull request.

2017-12-09 05:51 UTC, Akasurde commented
As agreed in 2017-12-07 Core meeting, we've done bulk pep8 fixes across all modules in devel.

This was done in #33682 and #33690 which have been merged into devel. because of this you will need to rebase your PR. Thanks in advance.

2017-12-09 05:51 UTC, closed without merging