Bug Fixed rax_dns_record
ansible/ansible pull request #32623
Opened 2017-11-07 12:55 UTC by shitalmule04

##### SUMMARY

All bug is fixed present in rax_dns_record file

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

rackspace/rax_dns_record
##### ANSIBLE VERSION

```
2.5
```

##### ADDITIONAL INFORMATION

```

```

2017-11-30 00:16 UTC, dagwieers requested changes
LGTM

2017-11-30 00:16 UTC, dagwieers commented on lib/ansible/cli/config.py
> +# Ansible is free software: you can redistribute it and/or modify
We now have a one-line GPL license statement.

2017-11-30 00:16 UTC, dagwieers commented on lib/ansible/modules/cloud/amazon/aws_kms.py
> +        key_alias=dict(required=False, type='str'),
You don't need `required=False`, it's the default. And we tend to start with the parameter type.

2017-12-08 14:38 UTC, gundalow commented
As agreed in 2017-12-07 Core meeting, we've done bulk pep8 fixes across all modules in `devel`.

This was done in https://github.com/ansible/ansible/pull/33682 and https://github.com/ansible/ansible/pull/33690 which have been merged into `devel`. because of this you will need to rebase your PR. Thanks in advance.

2017-12-08 15:55 UTC, gundalow commented on lib/ansible/modules/cloud/rackspace/rax_dns_record.py
> +                                      setup_rax_module,)
Is this right?

2017-12-08 16:02 UTC, closed without merging