Add mtu option nxos_interface feature idea
ansible/ansible pull request #32680
Opened 2017-11-08 12:15 UTC by trishnaguha

Signed-off-by: Trishna Guha <trishnaguha17@gmail.com>

##### SUMMARY

fixes https://github.com/ansible/ansible/issues/26162
Add `mtu` option `nxos_interface` feature idea

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

modules/network/nxos/nxos_interface
##### ANSIBLE VERSION

```
2.5
```

2017-11-08 15:21 UTC, Qalthos approved these changes

2017-11-08 15:22 UTC, Qalthos requested changes
Tests for MTU parameter?

2017-11-10 05:52 UTC, trishnaguha commented
@Qalthos pushed the test.

2017-11-13 14:37 UTC, Qalthos approved these changes

2017-11-13 14:48 UTC, merged