ec2_key: add a test for the force option
ansible/ansible pull request #32748
Opened 2017-11-09 16:33 UTC by prasadkatti

##### SUMMARY
ec2_key has an option called 'force'. If you try to create a keypair with the name of an already existing different keypair, the force option lets you control what should happen. When `force=no`, the key should not be overwritten.

This PR adds a test for this case.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME
`ec2_key`

##### ANSIBLE VERSION

```
devel
```

2017-11-14 04:00 UTC, willthames requested changes

2017-11-14 04:00 UTC, willthames commented on test/integration/targets/setup_sshkey/tasks/main.yml
> +  shell: mktemp /tmp/id_rsa.XXXXXX
should probably use `tempfile` module for this?

2017-11-14 04:00 UTC, willthames commented on test/integration/targets/setup_sshkey/tasks/main.yml
> +  command: cat {{another_sshkey.stdout}}.pub
use a lookup rather than cat: `lookup('file', '{{ another_sshkey.stdout }}.pub')`

2017-11-14 04:00 UTC, willthames commented on test/integration/targets/setup_sshkey/tasks/main.yml
> +  command: cat {{another_sshkey.stdout}}.pub
in fact `another_key_material` should just be set to that lookup.

2017-11-14 04:00 UTC, willthames commented on test/integration/targets/ec2_key/tasks/main.yml
> +    - name: test removing a non-existant keypair
typo: non-existent

2017-11-14 04:01 UTC, willthames commented on test/integration/targets/ec2_key/tasks/main.yml
> +        name='{{ec2_key_name}}'
We should use full yaml style:

```
  name: '{{ ec2_key_name }}'
  etc...
```

2017-11-15 02:18 UTC, prasadkatti commented
ready_for_review

2017-11-15 12:53 UTC, willthames approved these changes

2017-11-15 12:53 UTC, merged

2017-11-15 12:53 UTC, willthames commented
Merged, thanks @prasadkatti