Add the template lookup escaping to the 2.4 porting guide
ansible/ansible pull request #32760
Opened 2017-11-09 18:41 UTC by abadger

##### SUMMARY

This change can break playbooks so make sure we include it in the porting guide.

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME

##### ANSIBLE VERSION

```
devel and 2.4
```

2017-11-09 18:58 UTC, gundalow requested changes

2017-11-09 18:58 UTC, gundalow commented on docs/docsite/rst/porting_guide_2.4.rst
> +Prior to Ansible 2.4, the strings passed to the template lookup plugin would have backslashes
>template lookup plugin would have backslashes
Would have -> must have?

2017-11-09 18:58 UTC, gundalow commented on docs/docsite/rst/porting_guide_2.4.rst
> +Template lookup plugin
Can we give more or a clue in the heading, perhaps?
`Template lookup plugin: Escaping strings`

2017-11-09 18:58 UTC, gundalow commented on docs/docsite/rst/porting_guide_2.4.rst
> +And the template in :file:`tpl.j2` is::
tpl-> template?

2017-11-09 18:58 UTC, gundalow commented on docs/docsite/rst/porting_guide_2.4.rst
> +Change the template like this::
in the `2.3` guide we used the form
OLD In Ansible 2.2 (and earlier)
NEW In Ansible 2.3:

https://github.com/abadger/ansible/blob/devel/docs/docsite/rst/porting_guide_2.3.rst#openbsd-version-facts

2017-11-09 19:12 UTC, gundalow approved these changes

2017-11-11 00:37 UTC, dharmabumstead approved these changes

2017-11-11 00:40 UTC, dharmabumstead approved these changes
Approved. Thanks @abadger

2017-11-12 22:01 UTC, merged