Timeout option in unarchive module
ansible/ansible pull request #32788
Opened 2017-11-10 12:54 UTC by chromium58

##### SUMMARY
This PR adds timeout option to unarchive module, as requested here https://github.com/ansible/ansible/issues/23864
> unarchive module supports remote_src: https://docs.ansible.com/ansible/unarchive_module.html
> 
> However, it doesn't seem to support setting a timeout parameter on reading the remote url. This is a problem when downloading eg. autogenerated tarballs which may take a while to generate.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
modules/files/unarchive.py

##### ANSIBLE VERSION

```
2.5.0
```

##### ADDITIONAL INFORMATION

```

```

2018-05-02 12:28 UTC, Akasurde commented on lib/ansible/modules/files/unarchive.py
> +    version_added: "2.5"
s/2.5/2.6/

2018-05-02 18:50 UTC, chromium58 commented on lib/ansible/modules/files/unarchive.py
> +    version_added: "2.5"
thank you, version increased.

2018-05-03 04:19 UTC, Akasurde commented
Changes looks good to me. Waiting for @dagwieers

2018-05-09 12:18 UTC, dagwieers requested changes
I am not the maintainer of the module. But my view on this is that the unarchive module should not be used for downloading files. And I am against adding more options related to the downloading-functionality of this module. Use the **uri** or **get_url** modules for downloading files.

If it was up to me, I would remove that functionality from **unarchive**.

Reference: https://github.com/ansible/community/wiki/Module:-unarchive

2018-05-17 16:37 UTC, sijis commented
I agree with @dagwieers. Wanting full functionality in downloading a files via `unarchive` is probably not the right path. The other module mentioned `get_url` is fully featured with timeouts, proxy support, certs, checksums, etc.

We had a very similar request for supporting checksums and talking with core team it was best to suggest to use `get_url`. Eventually the docs will get updated with those suggestions (https://github.com/ansible/ansible/pull/40087).

2019-10-18 15:35 UTC, bcoca commented
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us that you've taken time to contribute.

Unfortunately, we are going to decline this PR because as previously stated, for more complex behaviour on URL fetching use the uri/get_url plugins instead.

However, we're absolutely always up for discussion.  
Since this is a really busy project, we don't always see comments on closed tickets, but want to encourage open dialog.  

You can stop by the development list, and we'd be glad to talk about it - and we might even be persuaded otherwise!

   * https://groups.google.com/forum/#!forum/ansible-devel

In the future, sometimes starting a discussion on the development list prior to implementing a feature can make getting things included a little easier, but it's not always necessary.

Thank you once again for this and your interest in Ansible!

2019-10-18 15:35 UTC, closed without merging