Adding support for managing AWS IOT things
ansible/ansible pull request #32826
Opened 2017-11-12 17:37 UTC by akowpak-miovision

##### SUMMARY

Add support for managing AWS IOT things.  When ansible is used to provision an IOT device, it is convenient to let it set up the state required in the cloud.

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

`iot_thing`

##### ANSIBLE VERSION

```
ansible 2.5.0 (iot_thing 4f6dac2c01) last updated 2017/11/12 12:23:35 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/akowpak/dev/ansible/library']
  ansible python module location = /home/akowpak/dev/ansible/lib/ansible
  executable location = /home/akowpak/dev/ansible/bin/ansible
  python version = 2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]
```

##### ADDITIONAL INFORMATION

N/A

2017-11-15 00:04 UTC, willthames requested changes
This module should be called aws_iot_thing

2017-11-15 00:04 UTC, willthames commented on lib/ansible/modules/cloud/amazon/iot_thing.py
> +def main():
All other modules have main at the bottom - having it here is a little unexpected

2017-11-15 00:04 UTC, willthames commented on lib/ansible/modules/cloud/amazon/iot_thing.py
> +        type=dict(type='str'),
type='str' is the default and thus not required

2017-11-15 00:05 UTC, willthames reviewed
It's probably worth adding integration tests which tend to catch a bunch of things that unit tests don't

2017-11-15 00:06 UTC, willthames commented on lib/ansible/modules/cloud/amazon/iot_thing.py
> +    except ClientError as e:
You need to catch BotoCoreError as well for all AWS API calls.

2017-11-15 00:07 UTC, willthames commented on lib/ansible/modules/cloud/amazon/iot_thing.py
> +    if not region:
This should no longer be required - boto3_conn will catch a NoRegionError and fail there.

2017-11-15 00:08 UTC, willthames commented on lib/ansible/modules/cloud/amazon/iot_thing.py
> +    except (ClientError, ValidationError) as e:
These errors never happen - there are no reasons to add exception handling around boto3_conn, which is designed to turn all exceptions into useful failure messages

2017-11-15 01:25 UTC, akowpak-miovision commented
Thanks for the feedback.  I'll make the requested changes as soon as I have a free moment (likely this weekend).

2017-11-15 02:07 UTC, willthames commented
@akowpak-miovision no worries - it looks to me to be a well written module in general, almost entirely in compliance with latest standards - certainly a great start.

2017-11-15 02:09 UTC, willthames commented on lib/ansible/modules/cloud/amazon/iot_thing.py
> +# Ansible is free software: you can redistribute it and/or modify
The copyright header has changed:

http://docs.ansible.com/ansible/latest/dev_guide/developing_modules_documenting.html#copyright

2017-11-15 02:11 UTC, willthames commented on lib/ansible/modules/cloud/amazon/iot_thing.py
> +attribute:
Pretty sure this should be attributes? http://boto3.readthedocs.io/en/latest/reference/services/iot.html#IoT.Client.describe_thing

2017-11-19 16:48 UTC, akowpak-miovision commented
I think that these commits address all of the comments.  The integration tests are somewhat incomplete, but, I plan have plans to write 3 other IoT modules which will allow me to expand these tests.

2017-11-19 17:54 UTC, akowpak-miovision commented
@mattclay @gundalow @willthames: I assumed that in order to get my integration tests to run on shippable, I'd have to setup a policy in the `testing_policies` directory, as I have done.  I've tried many iterations restricting the resources, all the way to what I have in my commit allowing all resources, and none of that works.

If you can point me in the correct direction of what I need to do to get permissions set up, I would appreciate it.  For what it's worth, this PR is only one of four modules I intend to contribute, so, when I push the other 3 IoT modules, I'll require more IoT permissions.

Thanks very much for any help you can provide.

2017-11-20 17:08 UTC, mattclay commented
@akowpak-miovision The test policies in the repo are for manual testing. Our CI system has separate policies which need to be updated. That's something @s-hertel or myself can take care of.

2017-11-20 17:21 UTC, akowpak-miovision commented
Thanks @mattclay.  If you guys can let me know when the policies have been updated, it would be most appreciated.

2018-02-01 20:10 UTC, ryansb requested changes

2018-02-01 20:10 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/aws_iot_thing.py
> +    remove_type: True
I'd rather have this either:

a) be called `purge_type` as we have in other modules called similar features purge_tags etc
b) distinguish between the user providing `None` and not providing a value, so if they wish to clear the type they can pass `type: null` or similar.

2018-02-01 20:10 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/aws_iot_thing.py
> +    attached_principals:
To me this looks like it should be `principals` and then have a `purge_principals` option to remove any principals not explicitly listed.

2018-02-01 20:10 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/aws_iot_thing.py
> +    absent_attributes:
Same: see `purge_*` options on iam_role and other modules.

2020-09-02 04:48 UTC, mkrizek commented
Thank you for your interest in Ansible! We are no longer accepting new plugins to ansible/ansible directly. Please re-file this pull request against https://www.github.com/ansible-collections/community.aws.

If you have further questions please stop by IRC or the mailing list:
* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project

2020-09-02 04:48 UTC, closed without merging