documentation: render nested return dicts for more then one level
ansible/ansible pull request #33143
Opened 2017-11-21 14:08 UTC by f3lang

##### SUMMARY

Until now, when you define nested dicts in the returned value, the webdocs will only
contain the first nested level. All subsequent levels are dropped and not displayed.
Especially for modules, that fetch sometimes rather comples results from APIs (e.g. the AWS API),
a lot of information is missing right now in the documentation (also on docs.ansible.com).

This changes the rendering of the results and nested dicts (type: complex) to a recursive view.
It drops the "table in table" view for complex data and replaces it with a indented view for
each nested layer.

Fixes #33128 

##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

webdocs
##### ANSIBLE VERSION

```
2.4
```

##### ADDITIONAL INFORMATION

Take the ec2_instance_facts_module as an example: 
Before:
![image](https://user-images.githubusercontent.com/3900374/33076279-9782fa98-cecc-11e7-85b5-5476698f8491.png) (As you can see all of the subsequent documentation about the network_interfaces property is missing)
After:
![image](https://user-images.githubusercontent.com/3900374/33076293-a69bbc40-cecc-11e7-8943-0a1b1b5ae40e.png) (The subsequent documenation of the network_interfaces property is now indented below it

2017-11-21 14:58 UTC, f3lang commented
I uploaded the complete generated documentation after the changes on s3:
[http://ventx.wf.s3-website.eu-central-1.amazonaws.com/ansible-doc/](http://ventx.wf.s3-website.eu-central-1.amazonaws.com/ansible-doc/)

2017-11-21 15:40 UTC, bcoca approved these changes
nice, this fixes a very annoying limitation

2017-11-21 19:24 UTC, dharmabumstead approved these changes
Actually rescinding my 'approved'. The black indentation isn't working for me.

2017-11-21 19:25 UTC, dharmabumstead commented
@gundalow should have a look as well.

2017-11-21 19:51 UTC, gundalow commented
Note to reviewers: Link to an example http://ventx.wf.s3-website.eu-central-1.amazonaws.com/ansible-doc/ec2_instance_facts_module.html

2017-11-21 19:54 UTC, gundalow commented
If we do it this way then maybe the same should be done for nested `options:`

2017-11-21 19:57 UTC, dharmabumstead commented
"Elbow" indent lines or even dots would be preferable.

2017-11-21 19:58 UTC, dharmabumstead requested changes
The black blocks aren't working for me. Would prefer we use "elbow indent" lines or even dots instead.

2017-11-21 20:10 UTC, f3lang commented
Hi all, thanks for the reviews so far. @dharmabumstead i will build the next version with elbow indent, so we can see how it will look like.
@gundalow I will also integrate the options with the next version.

2017-11-22 10:18 UTC, gundalow commented
I wonder if the keys should be sorted as well

2017-11-22 10:47 UTC, f3lang commented
@gundalow just finished the options. Still with black block indentation. Will look at the indentation style next. 

Regarding sorting: I'm not sure if we really should override the order of options and return values. It would definitly be better to get an alphabetically sorted list for overview, but when you have different modules for one topic (e.g. aws), you will have options, that are the same for every module (url, accesskey etc). Those should stay at the same location in the documentation to preserve a consistent documentation (e.g. url should stay at the top of the list).

2017-11-22 12:55 UTC, f3lang commented
New build of the documentation with recursive options:
[http://ventx.wf.s3-website.eu-central-1.amazonaws.com/ansible-doc/1d9d552/](http://ventx.wf.s3-website.eu-central-1.amazonaws.com/ansible-doc/1d9d552/)
you can see the recursive options active in this example:
[http://ventx.wf.s3-website.eu-central-1.amazonaws.com/ansible-doc/1d9d552/os_ironic_module.html](http://ventx.wf.s3-website.eu-central-1.amazonaws.com/ansible-doc/1d9d552/os_ironic_module.html)

2017-11-22 17:32 UTC, f3lang commented
@dharmabumstead i built a new indentation with the latest commit.
new build of the documentation:
[http://ventx.wf.s3-website.eu-central-1.amazonaws.com/ansible-doc/b90228b-1/](http://ventx.wf.s3-website.eu-central-1.amazonaws.com/ansible-doc/b90228b-1/)
example with nested return variables:
[http://ventx.wf.s3-website.eu-central-1.amazonaws.com/ansible-doc/b90228b-1/ec2_instance_facts_module.html](http://ventx.wf.s3-website.eu-central-1.amazonaws.com/ansible-doc/b90228b-1/ec2_instance_facts_module.html)
example with nested options:
[http://ventx.wf.s3-website.eu-central-1.amazonaws.com/ansible-doc/b90228b-1/os_ironic_module.html](http://ventx.wf.s3-website.eu-central-1.amazonaws.com/ansible-doc/b90228b-1/os_ironic_module.html)

2017-11-22 20:27 UTC, bcoca commented
+10

2017-11-22 21:42 UTC, dharmabumstead commented
@f3lang I like the new examples. @gundalow what do you think? If you're OK with it, please merge. Thanks @f3lang!

2017-11-22 21:48 UTC, dharmabumstead approved these changes

2017-11-22 21:53 UTC, merged

2017-11-22 22:06 UTC, jborean93 commented
This might require some tweaking, just tested the ec2 instance facts on FF 57 and the table isn't being generated properly

![screen shot 2017-11-23 at 8 03 22 am](https://user-images.githubusercontent.com/8462645/33151758-24459b1c-d025-11e7-8d0a-0104cd002795.png)

2017-11-23 07:54 UTC, f3lang commented
Hi @jborean93 thank you for the test. Seems like ff didn't like the css very much. I built a fix and now it looks right in ff:
![image](https://user-images.githubusercontent.com/3900374/33162803-c4c05cf2-d02b-11e7-8f66-c01655630e1b.png)
@bcoca The changes are a few lines of css. Should i open up a separate PR or is it possible to update this one here?

2017-11-23 10:05 UTC, jborean93 commented
Please open up a new PR, you can reference this PR from there though. Thanks for your prompt fix for it as well.