Fixes #33156 - Handle Cluster Option correctly
ansible/ansible pull request #33160
Opened 2017-11-21 20:39 UTC by coltsixshooter

##### SUMMARY

Fixes Bug #33156 - Which handles the Cluster option properly with finding a datastore.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

modules/cloud/vmware/vmware_guest.py
##### ANSIBLE VERSION

```
ansible 2.4.1.0
  config file = /home/jzimmett/.ansible.cfg
  configured module search path = [u'/home/jzimmett/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### ADDITIONAL INFORMATION

```

```

2017-11-21 23:07 UTC, mattclay commented
CI failure in integration test: https://app.shippable.com/github/ansible/ansible/runs/45049/47/tests

2017-12-31 04:03 UTC, Akasurde requested changes
Could you please add change requested ? Rest LGTM

2017-12-31 04:03 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +                if self.params['esxi_hostname'] or self.params['cluster']:
This check is OK.

2017-12-31 04:03 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +        elif self.params['esxi_hostname'] or self.params['cluster']:
This check shadows the next elif condition on line 1247.

2018-02-03 08:40 UTC, Akasurde commented
@coltsixshooter Are you still working on this ? 

needs_info

2018-02-05 16:59 UTC, coltsixshooter commented
I will get it done today -

Thanks

On Sat, Feb 3, 2018 at 12:41 AM, Abhijeet Kasurde <notifications@github.com>
wrote:

> @coltsixshooter <https://github.com/coltsixshooter> Are you still working
> on this ?
>
> needs_info
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ansible/ansible/pull/33160#issuecomment-362791056>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AGsRqMIN3WBCc_B110J6TavC5pC1vVHWks5tRBu5gaJpZM4QmdHl>
> .
>

2018-02-06 01:13 UTC, coltsixshooter commented
I cloned the current devel branch today and it appears the changes are in
there.

Thanks -

On Sat, Feb 3, 2018 at 12:41 AM, Abhijeet Kasurde <notifications@github.com>
wrote:

> @coltsixshooter <https://github.com/coltsixshooter> Are you still working
> on this ?
>
> needs_info
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ansible/ansible/pull/33160#issuecomment-362791056>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AGsRqMIN3WBCc_B110J6TavC5pC1vVHWks5tRBu5gaJpZM4QmdHl>
> .
>

2018-03-12 13:55 UTC, coltsixshooter commented
Please go ahead and close -

Thx

On Sat, Mar 10, 2018 at 12:55 AM, ansibot <notifications@github.com> wrote:

> @coltsixshooter <https://github.com/coltsixshooter> This pullrequest is
> waiting for your response. Please respond or the pullrequest will be closed.
>
> click here for bot help
> <https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ansible/ansible/pull/33160#issuecomment-372014690>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AGsRqEbKSDDd3LXZl7sSybn148_tMs31ks5tc5UagaJpZM4QmdHl>
> .
>

2018-03-12 18:18 UTC, closed without merging