cloudstack: fix spelling of "affinity_type"
ansible/ansible pull request #33231
Opened 2017-11-23 13:37 UTC by vincentbernat

##### SUMMARY
Fix spelling of `affinity_type` (not `affinty_type`).

However, to not break existing playbook, add an undocumented alias for
`affinty_type`.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
cloudstack

##### ANSIBLE VERSION
2.4.0.0

2017-11-23 14:20 UTC, vincentbernat commented
Unsure about the best way to fix this E309 error.

2017-11-25 08:52 UTC, resmo requested changes
Salut @vincentbernat 

It looks I screwed... with the argument name, didn't I? :)

I would suggest to deprecate the old argument and add some infos in the description. The old agument has to be kept for 4 releases according policy. That is why we can remove it in 2.9 (2.5-2.8).

Optionally, a pass a set of the two args as `mutually_exclusive` to AnsibleModule, to ensure only one could be used (see https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/basic.py#L774).

Thanks!

2017-11-25 08:52 UTC, resmo commented on lib/ansible/modules/cloud/cloudstack/cs_affinitygroup.py
> +        affinity_type = self.module.params.get('affinity_type')
~~~diff
-        affinity_type = self.module.params.get('affinty_type')
+        affinity_type = self.module.params.get('affinity_type') or self.module.params.get('affinty_type')
~~~

2017-11-25 08:52 UTC, resmo commented on lib/ansible/modules/cloud/cloudstack/cs_affinitygroup.py
> +        affinity_type=dict(aliases=['affinty_type']),
Lets deprecate the "old" param: 
~~~diff
-        affinty_type=dict(),
+        affinty_type=dict(removed_in_version='2.9'),
+        affinity_type=dict(),

2017-11-25 08:52 UTC, resmo commented on lib/ansible/modules/cloud/cloudstack/cs_affinitygroup.py
>      required: false
Please add the old value as an alias here:

~~~diff
...
        - Type of the affinity group. If not specified, first found affinity type is used. 
+       - The misspelled C(affinty_type) is for backwards compatibility and will be removed in version 2.9.
    required: false
+   aliases: [ affinty_type ]

2017-11-27 20:42 UTC, vincentbernat commented
I have updated the commit with the requested changes.

2017-11-28 06:17 UTC, resmo approved these changes
shipit

2017-11-28 06:46 UTC, merged

2017-11-28 06:49 UTC, resmo commented
Thanks.