openssl_publickey: Ensure format OpenSSH is idempotent
ansible/ansible pull request #33264
Opened 2017-11-24 14:42 UTC by Spredzy

##### SUMMARY

Currently the check() method for idempotence only assumes the public
key is under the form of a PEM file when its not always the case.

The module openssl_publickey allows one to generate OpenSSH format
publickey. This leads to idempotence not being detected. This commit
fixes that.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

- openssl_publickey

##### ANSIBLE VERSION

- devel`

##### ADDITIONAL INFORMATION

Playbook to test this patch. Before not-idempotent, after idempotent.

```
---
- hosts: localhost
  tasks:

    - openssl_privatekey:
        path: "/tmp/id_rsa-testing"

    - openssl_publickey:
        privatekey_path: "/tmp/id_rsa-testing"
        path: "/tmp/yanis.pub"
        format: OpenSSH
```

Fixes https://github.com/ansible/ansible/issues/33256

2017-11-24 14:43 UTC, Spredzy commented
Depends-On: https://github.com/ansible/ansible/pull/33255

2017-11-24 16:25 UTC, Spredzy commented
cc @MarkusTeufelberger

2017-11-26 10:40 UTC, Akasurde requested changes

2017-11-26 10:40 UTC, Akasurde commented on lib/ansible/modules/crypto/openssl_publickey.py
> +            except crypto.Error:
`except (crypto.Error, ValueError) as e: `

2017-11-27 07:43 UTC, Spredzy commented on lib/ansible/modules/crypto/openssl_publickey.py
> +            except crypto.Error:
done

2017-11-27 17:28 UTC, MarkusTeufelberger commented
shipit

2017-11-28 08:38 UTC, Akasurde approved these changes
shipit

2017-11-28 08:38 UTC, merged