VMware: Add support for more than 15 disks
ansible/ansible pull request #33338
Opened 2017-11-28 12:24 UTC by Akasurde

##### SUMMARY
This fix adds support for adding more than 15 disk to a given
virtual machine. Also, adds integration tests for this change.

Fixes: #22808

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
test/integration/targets/vmware_guest/tasks/create_multi_disks_d1_c1_f0.yml
lib/ansible/modules/cloud/vmware/vmware_guest.py

##### ANSIBLE VERSION

```
2.5devel
```

2017-11-28 12:27 UTC, Akasurde commented
cc @pdellaert @angystardust @aperigault

2017-12-06 19:57 UTC, BDragonReborn commented
This is still an issue with ansible 2.5

tasks:
    - name: Deploy guest from template
      vmware_guest:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "{{ vm_state }}"
        validate_certs: "{{ validate_certs }}"
        name: "{{ guest_name }}"
        template: "{{ template }}"
        cluster: "{{ cluster }}"
        resource_pool: "{{ resource_pool }}"
        datacenter: "{{ datacenter }}"
        annotation: "{{ vm_description }}"
        disk:
        - autoselect_datastore: "False"
          size_gb: "{{ datastore_one_size }}"
          datastore: "{{ datastore_one }}"
          type: "{{ datastore_type }}" 
        - autoselect_datastore: "False"
          size_gb: "{{ datastore_two_size }}"
          datastore: "{{ datastore_two }}"
          type: "{{ datastore_type }}" 
        - autoselect_datastore: "False"
          size_gb: "{{ datastore_three_size }}"
          datastore: "{{ datastore_three }}"
          type: "{{ datastore_type }}" 
        - autoselect_datastore: "False"
          size_gb: "{{ datastore_four_size }}" 
          datastore: "{{ datastore_four }}"
          type: "{{ datastore_type }}" 
        - autoselect_datastore: "False"
          size_gb: "{{ datastore_five_size }}"
          datastore: "{{ datastore_five }}"
          type: "{{ datastore_type }}" 
        - autoselect_datastore: "False"
          size_gb: "{{ datastore_six_size }}" 
          datastore: "{{ datastore_six }}"
          type: "{{ datastore_type }}" 
        - autoselect_datastore: "False"
          size_gb: "{{ datastore_seven_size }}" 
          datastore: "{{ datastore_seven }}"
          type: "{{ datastore_type }}" 
        hardware:
          memory_mb: "{{ memory_size }}"
          num_cpus: "{{ cpu_numbers }}"
          scsi: paravirtual
        networks:
        - name: "{{ network_name }}"
          ip: "{{ ip_address }}"
          netmask: "{{ netmask }}"
          gateway: "{{ default_gateway }}"
          domain: "{{ domain_name }}"
          dns_servers:
          - "{{ dns_server_one }}"
          - "{{ dns_server_two }}"
        customization:
          autologin: True
          username: "{{ local_username }}"
          password: "{{ local_password }}"
          hostname: "{{ guest_name }}"
          dns_servers:
          - "{{ dns_server_one }}"
          - "{{ dns_server_two }}"
        
This works with everything but assigning different datastores to the disks

2017-12-07 01:59 UTC, Akasurde commented
@BDragonReborn Are you using latest changes using this PR ? I see only 7 disks in configuration. This change need more than 15 disks. Also, multi-datastore PR is not merged, yet.

2018-02-15 20:27 UTC, wfharrigan72 commented
Have tested this fix on several system builds.  It works with no issues that I could find.

2018-03-27 15:48 UTC, thunderpants73 commented
Any idea on which release this will be added in?  We've been using this PR in our current Ansible build and it seems to work as expected.

2018-03-27 15:51 UTC, Akasurde commented
@thunderpants73 I am waiting for code review for this PR. Once it is done we can merge this.

2018-03-27 15:51 UTC, Akasurde commented
cc @pdellaert @tchernomax Could you please review this ?

2018-03-27 18:52 UTC, pdellaert approved these changes
LGTM, have not tested this on my setup in person, but the code itself looks like it should do what is expected :)

2018-05-08 11:02 UTC, Akasurde commented
cc @dericcrago

2018-06-11 16:43 UTC, dericcrago requested changes
Would you be able to add any tests that modify the disk settings and take a VM from <15 disks to >15 disks to add a controller during reconfigure?

2018-06-11 16:43 UTC, dericcrago commented on test/integration/targets/vmware_guest/tasks/create_multi_disks_d1_c1_f0.yml
> +- name: assert that changes were made
assert that changes were *not* made, right?

2018-06-11 16:43 UTC, dericcrago commented on test/integration/targets/vmware_guest/tasks/create_multi_disks_d1_c1_f0.yml
> +- name: assert that changes were made
same as earlier comment, about changes *not* being made, this looks to be in a couple of places.

2018-07-28 18:26 UTC, dericcrago commented
Hi @Akasurde - I'd still like to see a reconfigure test that crosses the threshold to require adding a new controller, like going from <15 to >15, etc.

2019-12-24 13:00 UTC, Akasurde commented
@Tomorrow9 Would you be interested in taking over this PR? Let me know, Thanks.

2019-12-24 13:26 UTC, Akasurde commented
superseded by https://github.com/ansible/ansible/pull/66057

2019-12-24 13:26 UTC, closed without merging