More Pythonic.  More Ansibilized.  Fixes #32618.
ansible/ansible pull request #33436
Opened 2017-11-30 21:15 UTC by kevensen

##### SUMMARY
An attempt to make this module more Pythonic and Ansibilized; if it wasn't a verb before, it is now.  Furthermore, there is a feature request to use the .kube/config file for authentication against an OpenShift cluster.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
oc

##### ANSIBLE VERSION
```
ansible 2.5.0 (oc-rework a4088bab17) last updated 2017/11/30 16:11:48 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/Users/k6n/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/k6n/git/ansible/lib/ansible
  executable location = ./bin/ansible
  python version = 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 12:39:47) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
```

2017-12-02 09:59 UTC, daxlab requested changes

2017-12-02 09:59 UTC, daxlab commented on lib/ansible/modules/clustering/oc.py
> +      - "The OpenShift service account token with which to authenticate agains the OpenShift cluster."
against

2017-12-03 13:10 UTC, towolf commented
@kevensen, there is another cert/key format supported in `kubeconfig` files, specifying paths to the PEM encoded files directly:

```
users:                                                      
- name: tobias.wolf@k8s-aix01                               
  user:                                                     
    client-certificate: /home/towolf/.../admin.pem
    client-key: /home/towolf/.../admin-key.pem
- name: tobias.wolf@k8s-txx01                               
  user:                                                     
    client-certificate: /home/towolf/.../admin.pem
    client-key: /home/towolf/.../admin-key.pem
```

If you want to support `kubeconfig` files, then I think this format should be supported as well.

You can save writing to tmp file, just point python directly to the files.

Why do we use this? We can recycle our staging cluster completely, and just point to the newly generated pki files. No need to re-generate the kubeconfig each time ...

2017-12-03 14:55 UTC, kevensen commented
@towolf I had no idea that was an option.  I agree that it should be included.  Thank you!

2017-12-03 15:07 UTC, juanluisvaladas approved these changes
Other than the comment made by @towolf, looks pretty good to me and and definitely covers my use case.

If you implement those changes, it should be pretty easy to allow users to pass directly a key and a certificate path directly instead of the kubeconfig file. I don't know if there is a use case or if it's worth the work but it's definitely a technically valid use case.

2017-12-03 15:07 UTC, juanluisvaladas commented on lib/ansible/modules/clustering/oc.py
> +      - "The OpenShift service account token with which to authenticate agains the OpenShift cluster."
Technically an oauthaccesstoken would do the very same thing so I would just say. 
 "The token with which to authenticate against the OpenShift cluster."

2017-12-03 16:08 UTC, kevensen commented
@juanluisvaladas I’m glad this worked for you.  I’m not wild about the dependency on PyYAML.  I’m going to think about alternatives.  It occurs to me this would also benefit from unit tests.  I should have all this cleaned up within the week.

2017-12-03 22:40 UTC, juanluisvaladas commented
@kevensen If your issue with PyYAML is only about dependencies, most of the github.com/openshift/openshift-ansible playbooks already depend on PyYAML so I don't think that's much of an issue for most of users as long as there isn't a version conflict.

2017-12-03 22:47 UTC, kevensen commented
@juanluisvaladas Yeah, that is my issue.  On second thought I’ll implement @towolf’s suggestion and call this PR done.

2017-12-03 23:49 UTC, kevensen commented
@daxlab @towolf When you get a chance can you please take another look?

2017-12-04 04:26 UTC, towolf commented
@kevensen thanks for the fix. But I thought this was about pure Kubernetes, we don't have Openshift. Can't test :-(

2017-12-04 12:09 UTC, juanluisvaladas commented
@towolf there is no difference regarding the kubeconfig files. I haven't actually tested it but the way this is done it should be able to manage kubernetes v1 resources.

2018-02-02 19:29 UTC, closed without merging