Add parent pid to persistent connection socket path hash
ansible/ansible pull request #33518
Opened 2017-12-04 07:06 UTC by ganeshrn

##### SUMMARY

Fixes #33192

*  Add parent pid in persistent connection socket path hash
   to avoid using same socket path for multiple simultaneous
   connection to same remote host.

##### ISSUE TYPE

 - Feature Pull Request
 - Bugfix Pull Request

##### COMPONENT NAME

bin/ansible-connection
plugins/connection/ssh.py

##### ANSIBLE VERSION

```
2.5
```

##### ADDITIONAL INFORMATION

```

```

2017-12-05 01:22 UTC, bcoca requested changes

2017-12-05 01:22 UTC, bcoca commented on bin/ansible-connection
> +        cp = ssh._create_control_path(play_context.remote_addr, play_context.port, play_context.remote_user, play_context.connection, os.getppid())
do we want the pid of ansibe-connection or the one from ansible/ansible-playbook that starts ansbile-connection?

2017-12-14 17:59 UTC, ganeshrn commented
ready_for_review

2017-12-15 00:00 UTC, mattclay commented
CI failure due to pep8 check is valid. The RHEL failure is unrelated and can be ignored.

2017-12-15 04:51 UTC, ganeshrn commented
Approved offline by @bcoca

2017-12-15 04:51 UTC, merged