Docs network best 2.5
ansible/ansible pull request #33544
Opened 2017-12-04 16:36 UTC by gundalow

##### SUMMARY
Document best practices for 2.5 Networking, which details:

* Correct way for credentials to be specified
* How to use ``network_cli``
* How to use ``netconf``
* What become mode is, and how to use it

Note: A separate guide for Ansible 21.->2.4 will be created

##### ISSUE TYPE
 - Docs Pull Request

2017-12-04 16:59 UTC, IPvSean commented
Thoughts (shouldn't stop the PR, but maybe we can add to another one)

- Can get a list of all available `ansible_network_os` . i.e. ios, nxos, eos, etc where we talk about the `ansible_network_os`
- This might sound dumb... but maybe we can make a picture and put it up there?  I can try drafting up something with you
- Before we dive into group_vars, etc maybe we could have a folder structure for the demo, like literally just do the `tree` command and show that output so they can see our layout?
- Are we using a ansible.cfg file for this?  inventory is not a normal name so I imagine you set this?  Maybe we can take your literal example and put it on our github.com/network-automation github repo !!
- One or more network devices that are compatible with Ansible.  Maybe we link to this-> https://access.redhat.com/articles/3185021
- At the bottom can we link to the network-automation github repo? github.com/network-automation
- The only thing "confusing" to me at all, is the "Collect data" part.  Is that the name of the example playbook or is this where you talk about gathering facts and explaining that?  I feel like you should call the playbook like backup.yml or something and then we put it on github.  I am just confused at the section title Collect data... its just a bit confusing if thats the name of the playbook, a sub-section or what.... maybe its just the way its rendering in markdown versus the docs page

2017-12-04 17:30 UTC, gundalow commented
> Can get a list of all available `ansible_network_os` . i.e. ios, nxos, eos, etc where we talk about the `ansible_network_os`

Good point, I think I'll add this to intro_network

> This might sound dumb... but maybe we can make a picture and put it up there?  I can try drafting up something with you

Picture of what?

> Before we dive into group_vars, etc maybe we could have a folder structure for the demo, like literally just do the `tree` command and show that output so they can see our layout?

`tree` is good idea

> Are we using a ansible.cfg file for this?  inventory is not a normal name so I imagine you set this? 

No ansible.cfg, I'm just doing
`ansible-playbook -i inventory fetch-facts.yml` where `-i` means "use this file for inventory

> Maybe we can take your literal example and put it on our github.com/network-automation github repo !!

Maybe, will think more on this

>One or more network devices that are compatible with Ansible.  Maybe we link to this-> https://access.redhat.com/articles/3185021

Not seem that page before, though that only lists what has "commercial supported", `dellos*` (for example) supports network_cli, though isn't covered by the "Network Addon"

> At the bottom can we link to the network-automation github repo? github.com/network-automation

Sure, do we have a few lines summary you could provide to explain what is is?

> The only thing "confusing" to me at all, is the "Collect data" part.  Is that the name of the example playbook or is this where you talk about gathering facts and explaining that?  I feel like you should call the playbook like backup.yml or something and then we put it on github.  I am just confused at the section title Collect data... its just a bit confusing if thats the name of the playbook, a sub-section or what.... maybe its just the way its rendering in markdown versus the docs page

I'll have a think about this

2017-12-04 17:46 UTC, Qalthos commented on docs/docsite/rst/network_best_practices_2.5.rst
> +copy:
Looks like some indentation got lost?

2017-12-04 17:47 UTC, Qalthos commented on docs/docsite/rst/network_best_practices_2.5.rst
> +copy:
Ah, ansibot saw it, too

2017-12-04 18:26 UTC, IPvSean commented
>Picture of what?

Was thinking of super simple diagram since we are not talking about anything but backing up configurations here... but something just to break the wall of text up.![picture](https://i.imgur.com/2Fk63Uu.png)

>Sure, do we have a few lines summary you could provide to explain what is is?

The Network-Automation GitHub project is a open community for all things network automation.  Here there will be various examples, demonstrations and Github repos dedicated exclusively for automation networking platforms.  To join simply email ansible-network@redhat.com and we will get you added right away!

>Not seem that page before, though that only lists what has "commercial supported", dellos* (for example) supports network_cli, though isn't covered by the "Network Addon"

Yeah I don't know if we have a great list of "everything yet" so maybe just word it like, List of all Red Hat supported networking modules until we get the community supported list as well (or link to the module index page for networking)

2017-12-05 20:41 UTC, IPvSean commented
branch base was moved/deprecated, adding new Pull Request

2017-12-11 08:32 UTC, gundalow commented
* Removed platform specific notes, this will be documented on pages linked from `intro_network.rst`
* Corrected link to `intro_network`

@IPvSean I'll put a diagram on `intro_network.rst`

2017-12-11 21:56 UTC, ismc commented
It seems confusing to use ansible_network_os at times and the group (when grouped by os) at others, especially when you are setting ansible_network_os in group_vars.

2017-12-11 22:34 UTC, privateip requested changes

2017-12-11 22:34 UTC, privateip commented on docs/docsite/rst/network_best_practices_2.5.rst
> +  Informs Ansible which Network platform this hosts corresponds to. This is required when using ``network_cli``
required for both `network_cli` and `netconf`

2017-12-11 22:34 UTC, privateip commented on docs/docsite/rst/network_best_practices_2.5.rst
> +         when: "'eos' in group_names"
`when: ansible_network_os == 'eos'`

2017-12-11 22:34 UTC, privateip commented on docs/docsite/rst/network_best_practices_2.5.rst
> +         when: "'vyos' in group_names"
as above (except vyos)

2017-12-11 22:34 UTC, privateip commented on docs/docsite/rst/network_best_practices_2.5.rst
> +         when: "'ios' in group_names"
as above (except ios)

2017-12-11 22:34 UTC, privateip commented on docs/docsite/rst/network_best_practices_2.5.rst
> +         when: "'eos' in group_names"
`when:` as above

2017-12-12 06:41 UTC, dharmabumstead commented
Doc review in process. Please don’t merge.

2017-12-12 10:32 UTC, gundalow commented on docs/docsite/rst/network_best_practices_2.5.rst
> +               {% for host in groups['eos'] %}
Is there a way of rewriting this using `ansible_network_os`?

2017-12-12 13:21 UTC, gundalow commented on docs/docsite/rst/network_best_practices_2.5.rst
> +               {% for host in groups['eos'] %}
This is apparently a fine use of groups still.

2017-12-12 22:09 UTC, dharmabumstead requested changes
A few suggestions. Thanks @gundalow!

2017-12-12 22:09 UTC, dharmabumstead commented on docs/docsite/rst/network_best_practices_2.5.rst
> +As Ansible is a flexible tool there are a number of ways of specifying connection information & credentials. We believe however that the best was is to use ``group_vars``.
Please revise to: Because Ansible is a flexible tool, there are a number of ways to specify connection information and credentials. We recommend using ``group_vars``.

2017-12-12 22:09 UTC, dharmabumstead commented on docs/docsite/rst/network_best_practices_2.5.rst
> +.. warning:: Never store passwords in plain text
Period

2017-12-12 22:09 UTC, dharmabumstead commented on docs/docsite/rst/network_best_practices_2.5.rst
> +The "Vault" feature of Ansible allows keeping sensitive data such as passwords or keys in encrypted files, rather than as plain text in your playbooks or roles. These vault files can then be distribu
"allows you to keep" rather than "keeping sensitive data"

2017-12-12 22:09 UTC, dharmabumstead commented on docs/docsite/rst/network_best_practices_2.5.rst
> +  The ansible-connection setting tells Ansible how it should connect to a remote device. When working with Ansible Networking, setting this to ``ansible_connection: network_cli`` informs Ansible that
Suggest revising to: Ansible uses the ``ansible-connection`` setting to determine how to connect to a remote device. When working with Ansible Networking, set this to netweork_cli so Ansible treats the remote node as a network device with a limited execution environment.

2017-12-12 22:09 UTC, dharmabumstead commented on docs/docsite/rst/network_best_practices_2.5.rst
> +To demonstrate how we can move the backup file to a different location we ``register`` the result and use the ``backup_path`` return value as source location to move the file into ``/tmp/backups/`` d
Hard to parse. If I'm understanding it correctly, maybe try: "To demonstrate how we can move the backup file to a different location, we ``register`` the result and move the file to the path stored in ``backup_path``."

2017-12-12 22:09 UTC, dharmabumstead commented on docs/docsite/rst/network_best_practices_2.5.rst
> +If you receive an connection error please double check the inventory and Playbook for typos or missing lines, if the issue still occurs follow the debug steps in :doc:`network_debug_troubleshooting`.
Period instead of comma.

2017-12-19 16:14 UTC, Qalthos approved these changes

2017-12-20 11:38 UTC, gundalow commented
@dharmabumstead Updated based on your feedback, thanks

Ready for final review

2017-12-21 10:04 UTC, dharmabumstead approved these changes
Looks good. Thanks @gundalow!

2018-01-02 14:47 UTC, privateip approved these changes

2018-01-03 10:39 UTC, gundalow commented
rebuild_merge

2018-01-03 10:44 UTC, merged