ios_config save
ansible/ansible pull request #33791
Opened 2017-12-11 22:21 UTC by jmighion

##### SUMMARY

Fixes #32980 by checking `save:`. Adds new option `save_when: changed`. Saves the config if a change has been made during the execution of the module, just like aruba_config.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

ios_config

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.5.0 (ios_config_save cdf087f3f5) last updated 2017/12/11 14:17:14 (GMT -700)
  config file = None
  configured module search path = [u'/Users/james/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/james/Documents/git/ansible/lib/ansible
  executable location = /Users/james/Documents/git/ansible/bin/ansible
  python version = 2.7.13 (default, Jul 18 2017, 09:17:00) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

2017-12-12 15:37 UTC, gundalow requested changes

2017-12-12 15:37 UTC, gundalow commented on lib/ansible/modules/network/ios/ios_config.py
> +        will only be copied to the startup-config if the task has made a change.
Please state that `I(changed) was added in Ansible 2.5.`

2017-12-12 18:24 UTC, gundalow approved these changes

2017-12-12 18:25 UTC, gundalow commented
Final review needed by @Qalthos or @ganeshrn

2017-12-13 11:46 UTC, ganeshrn approved these changes

2017-12-13 14:36 UTC, merged

2017-12-13 17:33 UTC, ganeshrn commented
Backported to 2.4 https://github.com/ansible/ansible/pull/33872

2017-12-13 18:42 UTC, bdowling commented
Does this PR reverse the deprecation of the 'save' option since it brings it back to life?  e.g. should `removed_in_version=2.4` be delete from save?

2017-12-13 20:33 UTC, jmighion commented
@bdowling good catch. fixing that in #33885