HipChat API v2 support for ansible callback plugin
ansible/ansible pull request #33882
Opened 2017-12-13 17:56 UTC by haridas

##### SUMMARY

HipChat API v2 support for ansible callback plugin

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

callback_plugin/hipchat

##### ANSIBLE VERSION

```
ansible 2.3.1.0
```

##### ADDITIONAL INFORMATION

This ansible `callback`  plugin work as it's before, ie; it will still use the Hipchat
`API v1` as default, but user can switch it by passing the API version string via Environment
variable `HIPCHAT_API_VERSION=v2`.

2017-12-13 18:31 UTC, bcoca requested changes

2017-12-13 18:31 UTC, bcoca commented on lib/ansible/plugins/callback/hipchat.py
> +        self.hipchat_api_version = os.getenv('HIPCHAT_API_VERSION', 'v1')
You should not need this anymore, you should have `self.get_option('api_version')` starting in 2.4 (rest of plugin needs updating)

2017-12-13 18:31 UTC, bcoca commented on lib/ansible/plugins/callback/hipchat.py
> +        self.hipchat_api_version = os.getenv('HIPCHAT_API_VERSION', 'v1')
also the new plugin config framework allows for ini entries in ansible.cfg

2017-12-14 06:27 UTC, haridas commented
@bcoca Pushed the changes. Please review it.

2017-12-14 22:30 UTC, bcoca approved these changes

2017-12-14 22:30 UTC, merged