VMware: Refactor vmware_host module
ansible/ansible pull request #33916
Opened 2017-12-14 15:43 UTC by Akasurde

##### SUMMARY
This fix refactor vmware_host module to use PyVmomi.
Also, handle SSLVerifyFault exception to get hostsystem's certificate
thumbprint.

Fixes: #20819

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/modules/cloud/vmware/vmware_host.py

##### ANSIBLE VERSION

```
2.5devel
```

2017-12-14 15:43 UTC, Akasurde commented
cc @tchernomax

2017-12-14 21:13 UTC, tchernomax commented
@Akasurde I now understand why and what exactly you asked me:

> can you paste me TaskError raised while connecting host in vcenter ? I want to see if it contains thumbprint or not this is related  to vmware_host

However, I just checked and I don't have any preproduction vcenter where I can test that… I will ask my colleagues tomorrow to know if they have any spare/test machine.

The PR #30582 was test on "production" machines previously freed of all their VM (so they were not "production" machines during my tests) during special operations ; we where upgrading all our ESXi.
Those operations are now finished… and I can't VMotion all the VM of an ESXi in production just to test the content of TaskError object.

But as I said, I will ask my colleagues tomorrow.

2017-12-15 11:04 UTC, Akasurde commented
cc @pdellaert

2017-12-21 15:35 UTC, tchernomax commented
@Akasurde I tried but couln't get any vim.fault.SSLVerifyFault error.

2017-12-21 16:37 UTC, tchernomax requested changes

2017-12-21 16:37 UTC, tchernomax commented on lib/ansible/modules/cloud/vmware/vmware_host.py
>          success, result = wait_for_task(task)
I would have write:
```
-        try:
-            task = self.cluster.AddHost_Task(host_connect_spec, as_connected, resource_pool, esxi_license)
-            success, result = wait_for_task(task)
-            return success, result
-        except TaskError as add_task_error:
-            # This is almost certain to fail the first time.
-            # In order to get the sslThumbprint we first connect
-            # get the vim.fault.SSLVerifyFault then grab the sslThumbprint
-            # from that object.
-            #
-            # args is a tuple, selecting the first tuple
-            ssl_verify_fault = add_task_error.args[0]
-            host_connect_spec.sslThumbprint = ssl_verify_fault.thumbprint
-
-        task = self.cluster.AddHost_Task(host_connect_spec, as_connected, resource_pool, esxi_license)
-        success, result = wait_for_task(task)
-        return success, result
+        for _ in range(0, 2):
+            try:
+                task = self.cluster.AddHost_Task(host_connect_spec, as_connected, resource_pool, esxi_license)
+                success, result = wait_for_task(task)
+                return success, result
+
+            except TaskError as task_error_exception:
+
+                task_error = task_error_exception.args[0]
+                if self.esxi_ssl_thumbprint == '' and isinstance(task_error, vim.fault.SSLVerifyFault):
+                    # User has not specified SSL Thumbprint for ESXi host,
+                    # try to grab it using SSLVerifyFault exception
+                    host_connect_spec.sslThumbprint = task_error.thumbprint
+                else:
+                    self.module.fail_json(msg="Failed to add host %s to vCenter: %s" % (self.esxi_hostname, task_error.msg))
+
+        self.module.fail_json(msg="Failed to add host %s to vCenter: %s" % (self.esxi_hostname, task_error.msg))
```

It seems vim.fault.SSLVerifyFault and other vim.fault… are always packed in a TaskError.

2017-12-21 16:37 UTC, tchernomax commented on lib/ansible/modules/cloud/vmware/vmware_host.py
>          success, result = wait_for_task(task)
Same here:
```
+            for _ in range(0, 2):
+                try:
+                    task = self.host.ReconnectHost_Task(**reconnecthost_args)
+                    success, result = wait_for_task(task)
+                    return success, result
+
+                except TaskError as task_error_exception:
+
+                    task_error = task_error_exception.args[0]
+                    if self.esxi_ssl_thumbprint == '' and isinstance(task_error, vim.fault.SSLVerifyFault):
+                        # User has not specified SSL Thumbprint for ESXi host,
+                        # try to grab it using SSLVerifyFault exception
+                        reconnecthost_args['cnxSpec'].sslThumbprint = task_error.thumbprint
+                    else:
+                        self.module.fail_json(msg="Failed to reconnect host %s to vCenter: %s" % (self.esxi_hostname, task_error.msg))

+               self.module.fail_json(msg="Failed to reconnect host %s to vCenter: %s" % (self.esxi_hostname, task_error.msg))
+
+        else:
             try:
                 task = self.host.ReconnectHost_Task(**reconnecthost_args)
                 success, result = wait_for_task(task)
                 return success, result
-            except TaskError as add_task_error:
-                # See add_host_to_vcenter
-                ssl_verify_fault = add_task_error.args[0]
-                reconnecthost_args['cnxSpec'].sslThumbprint = ssl_verify_fault.thumbprint
-
-        task = self.host.ReconnectHost_Task(**reconnecthost_args)
-        success, result = wait_for_task(task)
-        return success, result
+            except TaskError as task_error_exception:
+                task_error = task_error_exception.args[0]
+                self.module.fail_json(msg="Failed to reconnect host %s to vCenter due to %s" % (self.esxi_hostname, task_error.msg))
```

2018-01-05 17:51 UTC, tchernomax commented on lib/ansible/modules/cloud/vmware/vmware_host.py
>          success, result = wait_for_task(task)
@Akasurde what do you think ?

2018-01-11 14:10 UTC, Akasurde commented
@tchernomax Thanks, I have integrated your suggestions.

2018-01-12 12:01 UTC, pdellaert approved these changes
LGTM
shipit

2018-01-12 16:27 UTC, tchernomax approved these changes
LGTM

2018-01-12 16:30 UTC, merged

2018-01-12 17:01 UTC, Akasurde commented
@tchernomax @pdellaert Thanks for review and merge.