cloud:ovirt:ovirt_vms.py:  Added 'quota_id','sso', 'boot_menu', 'usb_support', 'serial_console' fields to ovirt_vms module
ansible/ansible pull request #34048
Opened 2017-12-19 17:20 UTC by pmargara

##### SUMMARY
- By adding a 'quota_id' parameter in the ovirt_vms module the administrator could now create VMs by assigning them to a specific quota instead of on the default one, this is very useful when the quota mode of ovirt cluster is set to enforced and every users (or group of) have a specific quota to use.

- By adding a 'sso' parameter in the ovirt_vms module the administrator could now specify if SSO should be enabled or disabled.

- By adding a 'boot_menu' parameter in the ovirt_vms module the administrator could now specify if the boot menu should be enabled or disabled.

- By adding a 'usb_support' parameter in the ovirt_vms module the administrator could now specify if the USB support should be enabled or disabled.

- By adding a 'serial_console' parameter in the ovirt_vms module the administrator could now specify if VirtIO serial console should be enabled or disabled.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
- lib/ansible/modules/cloud/ovirt/ovirt_vms.py

##### ANSIBLE VERSION
```
ansible 2.5.0 (devel d859fdb3a6) last updated 2017/12/19 17:59:51 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/paolomargara/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/paolomargara/workspace-neon/ansible-mrg/lib/ansible
  executable location = /home/paolomargara/workspace-neon/ansible-mrg/bin/ansible
  python version = 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]
```

##### ADDITIONAL INFORMATION
Example: defining a specific quota for a VM
```
- ovirt_quotas_facts:
    data_center: Default
    name: myquota
- ovirt_vms:
    sso: False
    boot_menu: True
    usb_support: True
    serial_console: True
    quota_id: "{{ ovirt_quotas[0]['id'] }}"
```

2018-01-08 08:25 UTC, pmargara commented
@machacekondra @mwperina: any news? In case of need I could refactor/split my pull request, but I think that at least the quota_id option should be merged into 2.5 version considering that a similar patch was already merged into ovirt_disk module.

2018-01-24 14:53 UTC, machacekondra requested changes
Thanks for the patch and sorry for delay on the review. We had to first implement following patch:

 https://github.com/ansible/ansible/pull/35285/files

In order to many attributes check/update works just fine, as oVirt API don't return some paramters by default, but only when user pass all_content header.

2018-01-24 14:53 UTC, machacekondra commented on lib/ansible/modules/cloud/ovirt/ovirt_vms.py
> +            - "Disk quota ID to be used for disk. By default quota is chosen by oVirt/RHV engine."
s/Disk quota ID/Virtual Machine quota ID

2018-01-24 14:53 UTC, machacekondra commented on lib/ansible/modules/cloud/ovirt/ovirt_vms.py
> +                else otypes.Bios(boot_menu=otypes.BootMenu(enabled=False))
I think better would be:

```python
bios=(
  otypes.Bios(boot_menu=otypes.BootMenu(enabled=self.param('boot_menu')))
) if self.param('boot_menu') is not None else None,
```

You already have check for `None`, so it can be only `True` or `False`.

2018-01-24 14:53 UTC, machacekondra commented on lib/ansible/modules/cloud/ovirt/ovirt_vms.py
> +                otypes.Console(enabled=True) if self.param('serial_console') is True else otypes.Console(enabled=False)
Here as well:

```python
console=(
  otypes.Console(enabled=self.param('serial_console'))
) self.param('serial_console') is not None else None,
```

2018-01-24 14:53 UTC, machacekondra commented on lib/ansible/modules/cloud/ovirt/ovirt_vms.py
> +                otypes.Usb(enabled=True) if self.param('usb_support') is True else otypes.Usb(enabled=False)
Same as above.

2018-01-24 14:53 UTC, machacekondra commented on lib/ansible/modules/cloud/ovirt/ovirt_vms.py
> +- ovirt_vms:
please add `name` here as it's reuqired parameter for this example to work.

2018-01-24 14:53 UTC, machacekondra commented on lib/ansible/modules/cloud/ovirt/ovirt_vms.py
> +                otypes.Sso() if self.param('sso') is True else otypes.Sso(methods=[])
```python
sso=(
  otypes.Sso(
    methods=[otypes.Method(id=otypes.SsoMethod.GUEST_AGENT)] if self.param('sso') else []
  )
)
```

2018-01-24 14:59 UTC, machacekondra commented
@pmargara Can you please rebase?

2018-01-24 15:09 UTC, machacekondra commented
Fixes: https://github.com/ansible/ansible/issues/33891

2018-01-24 21:33 UTC, pmargara commented
@machacekondra OK, I've done, let me know if there is something else to change.

2018-01-26 09:32 UTC, machacekondra approved these changes
Thanks a lot! shipit

2018-01-27 20:10 UTC, mwperina approved these changes
shipit

2018-01-27 20:18 UTC, merged

2018-01-28 02:25 UTC, benohara commented
This seems to cause     "msg": "'Vm' object has no attribute 'boot'"

Fixed by changing line 922 of ovirt_vms.py 

from: equal(self.param('boot_menu'), entity.boot.boot_menu.enabled) and
to: equal(self.param('boot_menu'), entity.bios.boot_menu.enabled) and

2018-01-29 12:32 UTC, machacekondra commented
@benohara Thank you for your report. I have sent a fix as you've suggested: https://github.com/ansible/ansible/pull/35454