Refactor IOS libs to use cliconf
ansible/ansible pull request #34136
Opened 2017-12-21 10:53 UTC by rcarrillocruz

2017-12-21 10:55 UTC, rcarrillocruz commented
bot_skip

2018-01-02 17:56 UTC, ganeshrn approved these changes
lgtm.

2018-01-02 17:57 UTC, ganeshrn commented
Please resolve merge conflict before merging.

2018-01-05 13:45 UTC, Qalthos requested changes

2018-01-05 13:45 UTC, Qalthos commented on lib/ansible/plugins/cliconf/ios.py
> +        for cmd in chain([b'configure terminal'], to_list(command), [b'end']):
This shouldn't be byte strings (they cast to bytes later anyway), and byte strings will break Python 3.5

2018-01-11 10:49 UTC, rcarrillocruz commented
merging, failures are CI issues unrelated to change

2018-01-11 10:50 UTC, merged