Add new module mlnxos_facts for retrieving facts of MLNX-OS Mellanox network devices
ansible/ansible pull request #34287
Opened 2017-12-29 04:36 UTC by samerd

Signed-off-by: Samer Deeb <samerd@mellanox.com>

##### SUMMARY

Add module mlnxos_facts for retrieving facts of MLNX-OS Mellanox switches
the module manages the facts: version, interfaces and modules.

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

modules/network/mlnxos/mlnxos_facts
##### ANSIBLE VERSION

```
ansible 2.5.0 (feature/net-facts ea0cf89a73) last updated 2017/12/29 04:29:56 (GMT +000)
  config file = /etc/ansible/ansible.cfg
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### ADDITIONAL INFORMATION

```

```

2017-12-29 05:54 UTC, ganeshrn approved these changes

2018-01-03 13:21 UTC, gundalow requested changes

2018-01-03 13:21 UTC, gundalow commented on lib/ansible/modules/network/mlnxos/mlnxos_facts.py
> +# Note: examples below use the following provider dict to handle
Are you using `provider:`?

2018-01-03 13:21 UTC, gundalow commented on lib/ansible/modules/network/mlnxos/mlnxos_facts.py
> +# Collect all facts from the device
Please change the comment to a `name:`, e.g.
```
- name: Collect all facts from the device
  mlnxos_facts:
    gather_subset: all
````

Best practice is to specify a `name:` in Ansible. We find people often copy examples when writing playbooks.

2018-01-07 20:16 UTC, gundalow commented
@samerd Hi, do you think this is ready for final review and merge?

2018-01-07 21:10 UTC, samerd commented
@gundalow : yes, please review and merge if it is OK.

2018-01-08 14:29 UTC, gundalow approved these changes

2018-01-08 14:29 UTC, merged