Add new module mlnxos_protocol for enabling disabling protocols on MLNX-OS Mellanox network devices
ansible/ansible pull request #34286
Opened 2017-12-29 03:54 UTC by samerd

Signed-off-by: Samer Deeb <samerd@mellanox.com>

##### SUMMARY

Add module mlnxos_protocol for enabling/disabling protocols on Mellanox switches
the module manages several protocols such as mlag, magp, ospf etc.

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

modules/network/mlnxos/mlnxos_protocol

##### ANSIBLE VERSION

```
ansible 2.5.0 (feature/net-protocols 1f9ff75474) last updated 2017/12/29 03:47:34 (GMT +000)
  config file = /etc/ansible/ansible.cfg
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### ADDITIONAL INFORMATION

```

```

2018-01-03 13:05 UTC, gundalow requested changes

2018-01-03 13:05 UTC, gundalow commented on lib/ansible/modules/network/mlnxos/mlnxos_protocol.py
> +        self._module = AnsibleModule(
Does this support checkmode?

2018-01-07 20:16 UTC, gundalow commented
@samerd Hi, do you think this is ready for final review and merge?

2018-01-07 21:09 UTC, samerd commented
@gundalow : yes, please review and merge if it is OK.

2018-01-08 14:30 UTC, gundalow approved these changes

2018-01-08 14:30 UTC, merged