Add new module mlnxos_mlag_vip for configuring MLAG VIP on Mellanox network devices
ansible/ansible pull request #34285
Opened 2017-12-29 03:29 UTC by samerd

Signed-off-by: Samer Deeb <samerd@mellanox.com>

##### SUMMARY

Add module mlnxos_mlag_vip for configuring MLAG VIP on Mellanox switches
the module manages the MLAG Virtual IP and system MAC address.

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

modules/network/mlnxos/mlnxos_mlag_vip
##### ANSIBLE VERSION

```
ansible 2.5.0 (feature/net-mlag-vip f79892b695) last updated 2017/12/29 03:26:08 (GMT +000)
  config file = /etc/ansible/ansible.cfg
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### ADDITIONAL INFORMATION

```

```

2018-01-03 13:19 UTC, gundalow requested changes

2018-01-03 13:19 UTC, gundalow commented on lib/ansible/modules/network/mlnxos/mlnxos_mlag_vip.py
> +short_description: configures MLAG VIP on mlnxos network devices
Configures

2018-01-03 13:19 UTC, gundalow commented on lib/ansible/modules/network/mlnxos/mlnxos_mlag_vip.py
> +      - virtual IP address of the MLAG.
`Virtual IP address of the MLAG. Required if I(state=present).`

2018-01-03 13:19 UTC, gundalow commented on lib/ansible/modules/network/mlnxos/mlnxos_mlag_vip.py
> +    required: true #if state is present
Remove this line

2018-01-03 13:19 UTC, gundalow commented on lib/ansible/modules/network/mlnxos/mlnxos_mlag_vip.py
> +    required: true #if state is present
Please update as per my comments on ipaddress.

2018-01-03 13:19 UTC, gundalow commented on lib/ansible/modules/network/mlnxos/mlnxos_mlag_vip.py
> +    required: true #if state is present
Please update as per my comments on ipaddress.

2018-01-03 13:19 UTC, gundalow commented on lib/ansible/modules/network/mlnxos/mlnxos_mlag_vip.py
> +options:
Please ensure that all `descriptions:` are full sentences (capital letters & full stop)

2018-01-07 20:16 UTC, gundalow commented
@samerd Hi, do you think this is ready for final review and merge?

2018-01-07 21:09 UTC, samerd commented
@gundalow : yes, please review and merge if it is OK.

2018-01-08 14:31 UTC, gundalow approved these changes

2018-01-08 14:31 UTC, merged