Replace MD5 with SHA-1 in jenkins_plugins module.
ansible/ansible pull request #34349
Opened 2018-01-02 14:57 UTC by karlmdavis

##### SUMMARY

Fixes Issue #34304.

The `hashlib.md5(...)` function is disabled on systems running in FIPS 140-2 mode. To accommodate that, this commit just switches to a hash function (`hashlib.sha1(...)`) that is allowed by FIPS 140-2.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

`jenkins_plugin`

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.4.1.0
  config file = None
  configured module search path = [u'/home/karl/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/karl/workspaces/cms/bluebutton-ansible-playbooks-data.git/venv/local/lib/python2.7/site-packages/ansible
  executable location = /home/karl/workspaces/cms/bluebutton-ansible-playbooks-data.git/venv/bin/ansible
  python version = 2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]
```

But this PR is based off `devel`.

##### ADDITIONAL INFORMATION
Applied the same patch against `v2.4.1.0` and confirmed that it resolved the problem described in Issue #34304.

2018-01-02 15:12 UTC, jtyr commented on lib/ansible/modules/web_infrastructure/jenkins_plugin.py
> +                    try:
Do we need this exception here if we doing the checksum on a variable?

2018-01-02 15:15 UTC, Akasurde requested changes

2018-01-02 15:15 UTC, Akasurde commented on lib/ansible/modules/web_infrastructure/jenkins_plugin.py
> +                e = get_exception()
get_exception is deprecated API (used for Python 2.4). Could you please use native Python syntax for exception handling `except Exception as e`

2018-01-02 15:15 UTC, Akasurde commented on lib/ansible/modules/web_infrastructure/jenkins_plugin.py
> +                    details=e.message)
Use `to_native` for wrapping error message.

2018-03-21 13:34 UTC, Akasurde commented
@karlmdavis Are you still working on this PR ? 

needs_info

2018-03-21 16:23 UTC, karlmdavis commented
:-|

Still _planning_ to... But I'm in the middle of a launch right now and haven't had a chance to get back to it. Definitely more than happy to address all the feedback once I do!

2018-09-09 04:16 UTC, Akasurde commented
@karlmdavis Are you still working on this PR ?

needs_info

2018-11-18 01:22 UTC, closed without merging

2018-12-20 08:41 UTC, jesstruck commented
What are the plan of fixing this ??