remove panos_security_policy
ansible/ansible pull request #34433
Opened 2018-01-04 00:43 UTC by ivanbojer

##### SUMMARY
removed panos_security_policy deprecated module in lieu of new panos_security_rule module. The old module uses deprecated API's that do not exist anymore.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
panos_security_policy

##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = None
  configured module search path = [u'/Users/ibojer/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/ibojer/.virtualenvs/ansible/lib/python2.7/site-packages/ansible
  executable location = /Users/ibojer/.virtualenvs/ansible/bin/ansible
  python version = 2.7.13 (default, Feb  6 2017, 11:22:10) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### ADDITIONAL INFORMATION

2018-01-19 21:34 UTC, vinayvenkat commented
Ship it!

2018-01-19 21:39 UTC, ivanbojer commented
ready_for_review

2018-01-19 21:40 UTC, vinayvenkat commented
shipit

2018-01-19 22:05 UTC, shinmog commented
shipit

2018-01-31 12:03 UTC, gundalow commented
Hi,
Need to go through a deprecation cycle for this. Can't just remove the modules

See what was done in http://docs.ansible.com/ansible/devel/dev_guide/developing_modules_documenting.html

https://github.com/ansible/ansible/pull/34100

1) Give notice of deprecation
`git mv` file so it starts with `_`
Add `DOCUMENATION.deprecation` dict
Update changelog to give noticed, under the "will be deleted in Ansible 2.9" section
Add entry into `porting_guide_2.5.rst
2) Wait till Ansible 2.9
Change module to be docs only

2018-01-31 12:03 UTC, gundalow requested changes
Hi,
Need to go through a deprecation cycle for this. Can't just remove the modules

See what was done in http://docs.ansible.com/ansible/devel/dev_guide/developing_modules_documenting.html

https://github.com/ansible/ansible/pull/34100

1) Give notice of deprecation
`git mv` file so it starts with `_`
Add `DOCUMENATION.deprecation` dict
Update changelog to give noticed, under the "will be deleted in Ansible 2.9" section
Add entry into `porting_guide_2.5.rst
2) Wait till Ansible 2.9
Change module to be docs only

2018-01-31 19:47 UTC, ivanbojer commented
I've addressed the comments. If this is correct I will do the same for the other module. @gundalow thank you for the feedback and please let me know if it looks good now.

2018-01-31 19:50 UTC, gundalow requested changes

2018-01-31 19:50 UTC, gundalow commented on lib/ansible/modules/network/panos/_panos_security_policy.py
> +deprecated: In 2.4 use M(panos_security_rule) instead.
```
deprecated:
    removed_in: 2.9
    why: Uses deprecated API calls
    alternative: Use M(panos_security_rule) instead.
``

2018-01-31 19:54 UTC, gundalow commented on lib/ansible/modules/network/panos/_panos_security_policy.py
> +  removed_in: "2.9"
Missing `alternative:`

2018-02-01 11:04 UTC, gundalow commented on lib/ansible/modules/network/panos/_panos_security_policy.py
> +    alternative:
`alternative: Use M(panos_security_rule) instead.`

`why: This module depended on outdated and old SDK.`

2018-02-01 17:11 UTC, ivanbojer commented
@gundalow I think this might do it 👍

2018-02-01 17:26 UTC, ivanbojer commented
ready_for_review

2018-02-02 12:34 UTC, gundalow approved these changes

2018-02-02 12:35 UTC, merged