Fortinet FortiManager Scripting Module
ansible/ansible pull request #34518
Opened 2018-01-05 21:37 UTC by Ghilli3

##### SUMMARY

Adding functionality from playbooks to add/delete/execute CLI or TCL scripts on a FortiManager (FMGR) to run against any number of devices managed by the FMGR.

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

fmgr_script.py
fortimanager.py

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/cse/PycharmProjects/ansible/lib/ansible/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]```

##### ADDITIONAL INFORMATION

Fully developed in-house by Fortinet based on other modules by Fortinet (fortios_config.py) but for a different product.

```

```

2018-01-05 21:46 UTC, gundalow requested changes
All new network modules since 2.4 need tests. Have a look in `test/unit`. Feel free to join #ansible-network on Freenode IRC for help next week.

2018-01-05 22:32 UTC, Ghilli3 commented
@gundalow - Thank you, I wasn't aware of the requirement for unit tests, but that makes sense.  Starting to write the unit tests today

2018-01-09 21:20 UTC, Ghilli3 commented
Hi @gundalow - I've added unit tests for the fortimanager scripting module.

2018-01-10 17:22 UTC, Ghilli3 reviewed
Submitting unit tests for the scripting module and ensuring new code passed all the Ansibot checks

2018-01-10 23:51 UTC, Ghilli3 commented
Hi @gundalow - Please let me know if I need to do anything else to continue moving this forward.  I'm not sure if I have to do anything else for the review.  Thank you for your time and help.

2018-01-12 03:44 UTC, Ghilli3 commented
Hi All, please let me know if I need to do anything else or if you need anything from me for the pending review.  Thank you.

2018-01-16 18:21 UTC, Ghilli3 reviewed
Adding unit tests for the network module for FortiManager scripting per the 2.4 requirement.  Added a few extra commits to trigger the Ansibot scan to ensure all tests passed.

2018-01-23 17:14 UTC, Ghilli3 commented
Is there any progress or status update on this PR?  Is there anything else needed by me for this PR?  Thank you for your help

2018-01-26 14:13 UTC, gundalow requested changes

2018-01-26 14:13 UTC, gundalow commented on lib/ansible/modules/network/fortimanager/fmgr_script.py
> +        username=dict(fallback=(env_fallback, ["ANSIBLE_NET_USERNAME"]), no_log=True),
Please remove `, no_log=True` from the username line

2018-01-26 14:13 UTC, gundalow commented on lib/ansible/modules/network/fortimanager/fmgr_script.py
> +        username=dict(fallback=(env_fallback, ["ANSIBLE_NET_USERNAME"]), no_log=True),
Missing `username` from `DOCUMENTATION`

2018-01-26 14:13 UTC, gundalow commented on lib/ansible/modules/network/fortimanager/fmgr_script.py
> +        vdom=dict(required=False, type="str"),
Missing `vdom` from `DOCUMENTATION:`

2018-01-26 14:13 UTC, gundalow commented on lib/ansible/modules/network/fortimanager/fmgr_script.py
> +short_description: Add/Edit/Delete and execute scripts
`short_description: Add/Edit/Delete and execute scripts on the FortiManager`

2018-01-26 14:13 UTC, gundalow commented on lib/ansible/modules/network/fortimanager/fmgr_script.py
> +- name: EXECUTE SCRIPT
Please have a blank line between tasks, makes it a little more readable.

2018-01-26 14:13 UTC, gundalow commented on test/units/modules/network/fortimanager/test_fmgr_script.py
> +from .fortimanager_module import TestFortimanagerModule
Imports need to be written so the test is gracefully skipped (`raise SkipTest`) if they are not present, see `test/units/modules/network/f5/test_bigip_monitor_snmp_dca.py` for an example

2018-01-26 14:15 UTC, gundalow commented
@Ghilli3 Hi, Looking fairly close to getting this merged :)

2018-01-26 17:01 UTC, Ghilli3 reviewed
Thank you for looking through the code and finding those issues.  I have fixed all the issues you have requested.

2018-01-26 18:39 UTC, gundalow approved these changes

2018-01-26 18:40 UTC, merged

2018-01-26 18:40 UTC, gundalow commented
Merged into `devel` will be released in `2.5.0`