VMware: Add new module: vmware_host_config_manager
ansible/ansible pull request #34627
Opened 2018-01-09 10:32 UTC by Akasurde

##### SUMMARY
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME

lib/ansible/modules/cloud/vmware/vmware_host_config_manager.py
test/integration/targets/vmware_host_config_manager/aliases
test/integration/targets/vmware_host_config_manager/tasks/main.yml

##### ANSIBLE VERSION

```
2.5devel
```

2018-01-09 12:29 UTC, Akasurde commented
Integration test missing due to https://github.com/vmware/govmomi/issues/989

2018-01-09 22:47 UTC, tchernomax requested changes
Except from the documentation part, this PR look good to me.

2018-01-09 22:47 UTC, tchernomax commented on lib/ansible/modules/cloud/vmware/vmware_host_config_manager.py
> +  vmware_host_config_facts:
`vmware_host_config_facts` → `vmware_host_config_manager`.

2018-01-09 22:47 UTC, tchernomax commented on lib/ansible/modules/cloud/vmware/vmware_host_config_manager.py
> +    - Name of the cluster from which the ESXi host belong to.
How the ESXi is selected if we only set `cluster_name` and there is multiple ESXi in the cluster ?

2018-01-09 22:47 UTC, tchernomax commented on lib/ansible/modules/cloud/vmware/vmware_host_config_manager.py
> +    - Name of the cluster from which the ESXi host belong to.
I just read the test.

> Change facts about all hosts in given cluster

You should change the `description` of `cluster_name`.'

2018-01-09 22:47 UTC, tchernomax commented on lib/ansible/modules/cloud/vmware/vmware_host_config_manager.py
> +    - ESXi hostname to gather facts from.
As I understand it, this module isn't about gathering facts.

2018-01-10 22:47 UTC, tchernomax requested changes

2018-01-10 22:47 UTC, tchernomax commented on lib/ansible/modules/cloud/vmware/vmware_host_config_manager.py
> +  vmware_host_config_facts:
`vmware_host_config_facts` → `vmware_host_config_manager`

2018-01-10 22:47 UTC, tchernomax commented on lib/ansible/modules/cloud/vmware/vmware_host_config_manager.py
> +  vmware_host_config_facts:
`vmware_host_config_facts` → `vmware_host_config_manager`

2018-01-10 22:47 UTC, tchernomax commented on lib/ansible/modules/cloud/vmware/vmware_host_config_manager.py
> +  vmware_host_config_facts:
`vmware_host_config_facts` → `vmware_host_config_manager`

2018-01-17 14:42 UTC, Akasurde commented
@tchernomax Could you please take a look again ?

2018-01-17 21:48 UTC, tchernomax approved these changes
LGTM

2018-01-18 04:30 UTC, merged

2018-01-18 04:30 UTC, Akasurde commented
@tchernomax Thanks for your review.