Changing documentation for back up as suggested by  Ganesh
ansible/ansible pull request #34738
Opened 2018-01-11 13:03 UTC by amuraleedhar

##### SUMMARY
Making the documentation correct for the backup option of the module enos_config. The r unning configuration will come as a json object in the result variable of the module. The user has to use the copy command of Ansible to copy the running configuration to a file in the location he desires.

##### ISSUE TYPE
 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME
lib/ansible/modules/network/enos/enos_config.py

##### ANSIBLE VERSION
ansible 2.5.0
config file = /etc/ansible/ansible.cfg
configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible-2.5.0-py2.7.egg/ansible
executable location = /usr/local/bin/ansible
python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]

##### ADDITIONAL INFORMATION
This is a documentation update changes to make it more clear to user regarding the usage of config backup option

2018-01-11 13:36 UTC, ganeshrn reviewed
Any reason why backup directory creation is not handled in config action plugin similar to other platforms Reference: https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/eos_config.py

2018-01-11 13:38 UTC, ganeshrn requested changes
Also currently src option is handled using loadfp api which does not handle relative path and templates correctly. Need to handle it in action plugin similar to other platforms.

2018-01-11 14:04 UTC, amuraleedhar commented
I think I may need another PR to incorporate the changes. Keeping it now, will delete later

2018-01-12 09:50 UTC, amuraleedhar commented
I will add enos_confiSg.py as action plugin in a new PR. This changes has to be discarded. So deleting this PR after 2 days. I tested it and I got the config back up as attached here
Renaming it as txt to put it here
[10.241.105.24_config.2018-01-12@14_54_35.txt](https://github.com/ansible/ansible/files/1625577/10.241.105.24_config.2018-01-12.14_54_35.txt)

2018-01-16 04:09 UTC, closed without merging