Changing BSD to GPL
ansible/ansible pull request #34889
Opened 2018-01-15 17:14 UTC by amuraleedhar

##### SUMMARY
Changing BSD to GPL for license as Suggested by John

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
lib/ansible/plugins/cliconf/enos.py

ansible 2.5.0
config file = /etc/ansible/ansible.cfg
configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible-2.5.0-py2.7.egg/ansible
executable location = /usr/local/bin/ansible
python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]

ADDITIONAL INFORMATION
This is an effort to support Lenovo ENOS Switches in Ansible

2018-01-15 17:21 UTC, sivel requested changes

2018-01-15 17:21 UTC, sivel commented on lib/ansible/plugins/cliconf/enos.py
> +# This particular file snippet, and this file snippet only, is GPL licensed.
This change is not valid. It is only updating a single word within the license, and not updating the full license header.

Additionally, in order to do this, you will need to get approval from the following additional authors to relicense the code:

kedarX
ganeshrn

2018-01-25 03:03 UTC, kedarkekan approved these changes

2018-01-30 15:39 UTC, ganeshrn approved these changes

2018-01-30 15:42 UTC, ganeshrn requested changes

2018-01-30 15:42 UTC, ganeshrn commented on lib/ansible/plugins/cliconf/enos.py
>  # Copyright (C) 2017 Lenovo, Inc.
Please update as below in sync with other community supported platforms.
(c) 2017 Red Hat Inc.
#
(c) 2017 Lenovo, Inc.

2018-01-31 09:06 UTC, ganeshrn approved these changes

2018-01-31 09:06 UTC, ganeshrn commented
rebuild_merge

2018-01-31 16:18 UTC, merged