[new module] azure_rm_keyvault
ansible/ansible pull request #35150
Opened 2018-01-21 10:17 UTC by zikalino

##### SUMMARY
Adding support for azure_rm_keyvault

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME

azure_rm_keyvault

##### ANSIBLE VERSION

 2.4

##### ADDITIONAL INFORMATION

2018-01-21 13:04 UTC, zikalino commented
@jborean please check this pr, pls note fix for sanity test is in a separate pr

2018-01-23 00:27 UTC, mattclay commented
CI failure in integration tests due to traceback:

```
Traceback (most recent call last):
  File "/tmp/ansible_i9pK4R/ansible_module_azure_rm_keyvault.py", line 435, in <module>
    main()
  File "/tmp/ansible_i9pK4R/ansible_module_azure_rm_keyvault.py", line 432, in main
    AzureRMVaults()
  File "/tmp/ansible_i9pK4R/ansible_module_azure_rm_keyvault.py", line 265, in __init__
    supports_tags=False)
  File "/tmp/ansible_i9pK4R/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py", line 321, in __init__
  File "/tmp/ansible_i9pK4R/ansible_module_azure_rm_keyvault.py", line 307, in exec_module
    self.adjust_parameters()
AttributeError: 'AzureRMVaults' object has no attribute 'adjust_parameters'
```

2018-01-23 04:52 UTC, jborean93 requested changes

2018-01-23 04:52 UTC, jborean93 commented on lib/ansible/modules/cloud/azure/azure_rm_keyvault.py
> +    tenant_id:
change this to `vault_tenant`. `tenant_id` is too close to the base option `tenant` used as a credential arg.

2018-01-23 04:52 UTC, jborean93 commented on lib/ansible/modules/cloud/azure/azure_rm_keyvault.py
> +            - "An array of 0 to 16 identities that have access to the key vault. All identities in the array must use the same tenant ID as the key vault's t
don't put a newline right in the middle of a work, just do

```
description:
- An array of 0 to 16 identities that have access to the key value. All identities in the array must use the same
  tenant ID as the key vault's tenant ID.
```

2018-01-23 04:52 UTC, jborean93 commented on lib/ansible/modules/cloud/azure/azure_rm_keyvault.py
> +            - 'default'
Should be set as the default explicitly

2018-01-23 04:52 UTC, jborean93 commented on lib/ansible/modules/cloud/azure/azure_rm_keyvault.py
> +            if self.check_mode:
Running this in check mode will always result in a change even when an update is not needed. You need to do check the existing object to see if it needs updating before you exit here.

2018-01-24 01:53 UTC, zikalino commented
@jborean93 pls recheck and possibly merge

2018-01-24 11:13 UTC, zikalino commented
@nitzmahone could you pls check this pr and possibly merge?

2018-01-25 04:01 UTC, zikalino commented
@jborean93 just made changes as requested by @nitzmahone today.
would you be able to merge this module?

2018-01-30 08:30 UTC, kyliel commented
@nitzmahone , any other feedback to move forward? Thanks.

2018-02-02 07:20 UTC, nitzmahone commented
@zikalino The 2.5.0a1 release stuff took a lot longer than I planned today (we're changing up a bunch of the release processes), so I'll get back to this on Monday and get it merged.

2018-02-05 23:58 UTC, nitzmahone commented
@zikalino Update was totally broken, so had to spend some time fixing that up and added a really basic test for it. Also, "current tenant" doesn't appear to be easily available from CLI or UserPassCredential, so I had to back out the automatic vault tenant_id change. :(

I ended up not `set`-ifying the access_policies list, as the way you're comparing values from the response dict and the Ansible module dict would likely cause issues (eg, missing key vs key present and value is `None`). We wouldn't have this issue with the SDK objects, as they'd normalize this difference automatically (and provide us hashable objects, too). So maybe chalk that up as one more plus for using the SDK objects.

Just as another note: the repeated `setdefault` calls makes the code really hard to read IMO, and isn't really necessary (just maybe do it once upfront for `properties` instead of on every call).

2018-02-06 00:08 UTC, merged