add DragonFlyBSD support to modules/system/user.py
ansible/ansible pull request #35160
Opened 2018-01-21 23:54 UTC by jontow

##### SUMMARY
Duplicate existing FreeBsdUser class as DragonFlyUser, correctly setting platform name.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

system/user

##### ANSIBLE VERSION

```
ansible 2.5.0 (devel 97b51f6187) last updated 2018/01/21 18:28:36 (GMT -400)
  config file = None
  configured module search path = ['/Users/jontow/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/jontow/GIT-external/ansible/lib/ansible
  executable location = /Users/jontow/GIT-external/ansible/bin/ansible
  python version = 3.6.4 (default, Jan  4 2018, 20:49:52) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### ADDITIONAL INFORMATION

This is required on DragonFly, or it fails with an error like 'Failed to find required executable usermod' (DragonFly uses 'pw', like FreeBSD).
Instead of attempting something fancy like loading the FreeBsdUser class and overriding just the platform, I chose to follow existing convention and create a new class, since it is technically a separate platform that can diverge over time.
To trigger this bug, simply define a user that gets applied on a DragonFlyBSD host, like so:
```
---
- user:
    name: jontow
    comment: "jontow"
    groups: "{{ admin_groups }}"
    append: yes
    shell: "{{ zsh_path }}"
    update_password: on_create
    password: '...'
```

Before:
```
TASK [common : user] *********************************************************************************************************************************************
task path: /Users/jontow/GIT-je/ansible/roles/common/tasks/users/jontow.yml:2
fatal: [dbuild.je]: FAILED! => {"attempts": 1, "changed": false, "failed": true, "msg": "Failed to find required executable usermod in paths: /home/jontow/.rbenv/bin:/home/jontow/.cargo/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/games:/usr/local/sbin:/usr/local/bin:/usr/pkg/sbin:/usr/pkg/bin:/home/jontow/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/games:/usr/local/bin:/usr/local/sbin:/usr/pkg/bin:/usr/X11R6/bin:/home/argus/bin:/home/argus/sbin:/home/jontow/bin"}
```

After:
```
TASK [common : user] *********************************************************************************************************************************************
task path: /Users/jontow/GIT-je/ansible/roles/common/tasks/users/jontow.yml:2
ok: [dbuild.je] => {"append": true, "attempts": 1, "changed": false, "comment": "Jonathan Towne", "failed": false, "group": 1000, "groups": "wheel", "home": "/home/jontow", "move_home": false, "name": "jontow", "password": "NOT_LOGGING_PASSWORD", "shell": "/usr/local/bin/zsh", "state": "present", "uid": 1000}
```

2018-02-05 22:35 UTC, maxamillion commented
Thanks for your submission! The code looks good, but I noticed there's no addition to the docs of the module that mention support of DragonflyBSD or any other considerations needed. Could you please add those as necessary? Thanks.

2018-02-05 23:15 UTC, bcoca requested changes

2018-02-05 23:15 UTC, bcoca commented on lib/ansible/modules/system/user.py
> +class DragonFlyUser(User):
maybe just subclass freebsd one and then if there is a divergence you can override those methods

i would prefer that over soo much duplicate code

2018-02-07 17:56 UTC, jontow commented
botched rebase.. closing, will resubmit.

2018-02-07 17:56 UTC, closed without merging