adds two new infoblox lookup plugins
ansible/ansible pull request #35189
Opened 2018-01-22 15:45 UTC by privateip

* nios - lookup plugin to return nios objects to the playbook
* nios_next_ip - lookup plugin to return the next avaiable ip address

2018-01-23 13:12 UTC, gundalow requested changes

2018-01-23 13:12 UTC, gundalow commented on lib/ansible/plugins/lookup/nios.py
> +#
Please add to `.github/BOTMETA.yml` like https://github.com/ansible/ansible/pull/35179/files
Will ensure we get notified about bugs and PRs

2018-01-23 13:12 UTC, gundalow commented on lib/ansible/utils/module_docs_fragments/nios.py
> +          - Value can also be specified using INFOBLOX_HOST environment
`C(INFOBLOX_HOST)`

Same for other ENVs

2018-01-23 13:12 UTC, gundalow commented on lib/ansible/plugins/lookup/nios_next_ip.py
> +            raise AnsibleError('the network must be specified')
Can we say which network?

2018-01-23 13:12 UTC, gundalow commented on lib/ansible/plugins/lookup/nios_next_ip.py
> +extends_documentation_fragment: nios
Not sure if `extends_documentation_fragments:` works. for `lookups`. I don't see it used in any other `lookups`

`make webdocs`
walk to store
buy coffee
Review docs

would confirm

2018-01-23 18:58 UTC, privateip commented on lib/ansible/plugins/lookup/nios_next_ip.py
> +extends_documentation_fragment: nios
confirmed works fine

2018-01-23 19:42 UTC, gundalow approved these changes

2018-01-24 13:28 UTC, gundalow approved these changes

2018-01-24 13:28 UTC, merged

2018-01-24 13:28 UTC, gundalow commented
Merged, CI failures not related