new module that allows for adding DynamicAddressGroup tags to the firewall
ansible/ansible pull request #35201
Opened 2018-01-22 22:15 UTC by ivanbojer

##### SUMMARY
Create the ip address to tag associations. Tags will in turn be used to create DAG's

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME
panos_dag_tags.py

##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = None
  configured module search path = [u'/Users/ibojer/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/ibojer/.virtualenvs/ansible/lib/python2.7/site-packages/ansible
  executable location = /Users/ibojer/.virtualenvs/ansible/bin/ansible
  python version = 2.7.13 (default, Feb  6 2017, 11:22:10) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### ADDITIONAL INFORMATION

2018-01-24 19:07 UTC, ivanbojer commented
ready_for_review

2018-01-24 21:28 UTC, vinayvenkat commented
shipit

2018-01-31 12:05 UTC, gundalow requested changes

2018-01-31 12:05 UTC, gundalow commented on lib/ansible/modules/network/panos/panos_dag_tags.py
> +        password=dict(required=True),
`, no_log=True`

2018-02-01 17:25 UTC, ivanbojer commented
ready_for_review

2018-02-02 12:39 UTC, gundalow approved these changes

2018-02-02 12:40 UTC, gundalow commented
Rebase then we can merge.
In the future ignore the CHANGELOG.md, update that in a separate PR as it's often a source of merge conflicts

2018-02-02 23:05 UTC, ivanbojer commented
ready_for_review

2018-02-03 11:33 UTC, gundalow approved these changes

2018-02-03 11:34 UTC, merged

2018-02-03 11:34 UTC, gundalow commented
Merged, will need tests adding ASAP. We can guide you with this if needed.