Add jenkins_job_facts module
ansible/ansible pull request #35346
Opened 2018-01-25 13:04 UTC by stpierre

##### SUMMARY

Adds a new module, `jenkins_job_facts`, that can be used to discover existence and some basic information about existing Jenkins jobs.

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME

`jenkins_job_facts`

##### ANSIBLE VERSION

```
ansible 2.5.0 (jenkins-job-facts 15074622c1) last updated 2018/01/25 06:55:33 (GMT -500)
  config file = None
  configured module search path = [u'/home/stpierre/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/stpierre/devel/ansible/lib/ansible
  executable location = /home/stpierre/devel/ansible/bin/ansible
  python version = 2.7.14 (default, Jan 17 2018, 14:28:32) [GCC 7.2.1 20170915 (Red Hat 7.2.1-2)]
```

2018-01-26 07:19 UTC, resmo requested changes
needs_revision

2018-01-26 07:19 UTC, resmo commented on lib/ansible/modules/web_infrastructure/jenkins_job_facts.py
> +  type: string
is it a string or a list?

2018-01-26 07:19 UTC, resmo commented on lib/ansible/modules/web_infrastructure/jenkins_job_facts.py
> +    name: some-job-*
shouldn't this use the glob param?

2018-01-26 12:34 UTC, stpierre commented on lib/ansible/modules/web_infrastructure/jenkins_job_facts.py
> +    name: some-job-*
Done.

2018-01-26 12:34 UTC, stpierre commented on lib/ansible/modules/web_infrastructure/jenkins_job_facts.py
> +  type: string
Done

2018-01-26 12:43 UTC, resmo commented
a short tests without valid credetials shows a traceback which should be catched.

~~~
* including generated source, if any, saving to: /home/resmo/.ansible_module_generated
* ansiballz module detected; extracted module source to: /home/resmo/debug_dir
***********************************
RAW OUTPUT

Traceback (most recent call last):
  File "/home/resmo/debug_dir/ansible_module_jenkins_job_facts.py", line 190, in <module>
    main()
  File "/home/resmo/debug_dir/ansible_module_jenkins_job_facts.py", line 186, in main
    run_module()
  File "/home/resmo/debug_dir/ansible_module_jenkins_job_facts.py", line 168, in run_module
    all_jobs = jenkins_conn.get_all_jobs()
  File "/usr/local/lib/python2.7/dist-packages/jenkins/__init__.py", line 814, in get_all_jobs
    jobs = [(0, "", self.get_info(query=JOBS_QUERY)['jobs'])]
  File "/usr/local/lib/python2.7/dist-packages/jenkins/__init__.py", line 551, in get_info
    Request(self._build_url(url))
  File "/usr/local/lib/python2.7/dist-packages/jenkins/__init__.py", line 430, in jenkins_open
    self.maybe_add_crumb(req)
  File "/usr/local/lib/python2.7/dist-packages/jenkins/__init__.py", line 303, in maybe_add_crumb
    self._build_url(CRUMB_URL)), add_crumb=False)
  File "/usr/local/lib/python2.7/dist-packages/jenkins/__init__.py", line 461, in jenkins_open
    raise JenkinsException('Error in request: %s' % (e.reason))
jenkins.JenkinsException: Error in request: [Errno 111] Connection refused
~~~

2018-01-26 12:47 UTC, resmo commented
works for me otherwise, probably one nice feature would be to query by "color"

2018-01-26 15:05 UTC, resmo approved these changes

2018-01-26 15:07 UTC, resmo commented on lib/ansible/modules/web_infrastructure/jenkins_job_facts.py
> +# Copyright: (c) Ansible Project
put your name/company in here

2018-01-29 13:19 UTC, resmo commented
tested, works for me.

shipit

2018-01-30 22:42 UTC, merged