WIP: added aci_static_binding_to_epg module
ansible/ansible pull request #35581
Opened 2018-01-31 21:11 UTC by brunocalogero

##### SUMMARY
added aci_static_binding_to_epg module (fv:RsPathAtt)

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
aci_static_binding_to_epg

##### ANSIBLE VERSION
```
2.5
```

##### ADDITIONAL INFORMATION
Also resolves the following issue: https://github.com/ansible/ansible/issues/35340

2018-01-31 22:49 UTC, brunocalogero commented
@dagwieers man.. these documentation errors :P is it because I have to provide either "choices" or "aliases" for every parameter in the doc ?

2018-01-31 23:21 UTC, dagwieers commented
@brunocalogero Well, it means you have a YAML error in the documentation. What I usually do is copy&paste into yamllint to find the cause.

2018-02-01 01:17 UTC, dagwieers requested changes

2018-02-01 01:17 UTC, dagwieers commented on lib/ansible/modules/network/aci/aci_static_binding_to_epg.py
> +    - the pod number part of the tDn.
Start with a capital.

2018-02-01 01:17 UTC, dagwieers commented on lib/ansible/modules/network/aci/aci_static_binding_to_epg.py
> +    - C(pod) is usually an integer below 10
End with a dot.

2018-02-01 01:17 UTC, dagwieers commented on lib/ansible/modules/network/aci/aci_static_binding_to_epg.py
> +    - the pod number part of the tDn.
Do the same for other descriptions.

2018-02-02 23:49 UTC, merged