VMware: add new module : vcenter_folder
ansible/ansible pull request #35608
Opened 2018-02-01 13:49 UTC by Akasurde

##### SUMMARY
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
lib/ansible/modules/cloud/vmware/vcenter_folder.py
test/integration/targets/vcenter_folder/aliases
test/integration/targets/vcenter_folder/tasks/main.yml

##### ANSIBLE VERSION

```
2.5devel
```

2018-02-02 12:08 UTC, ghost approved these changes

2018-02-05 15:23 UTC, tchernomax commented on lib/ansible/modules/cloud/vmware/vcenter_folder.py
> +    operation: present
operation → state

2018-02-05 15:28 UTC, tchernomax requested changes

2018-02-05 15:28 UTC, tchernomax commented on lib/ansible/modules/cloud/vmware/vcenter_folder.py
> +    operation: present
operation → state

2018-02-05 16:12 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vcenter_folder.py
> +    operation: present
my bad.

2018-02-05 16:44 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vcenter_folder.py
> +    operation: present
Done.

2018-02-05 16:51 UTC, tchernomax approved these changes
LGTM

2018-02-05 17:01 UTC, merged

2018-02-05 17:02 UTC, Akasurde commented
@cvanniekerk @tchernomax Thanks for your valuable feedback and reviews.