fix nxos_vpc_interface peer_link idempotence
ansible/ansible pull request #35737
Opened 2018-02-05 17:45 UTC by saichint

##### SUMMARY

Fixes #35736

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

nxos_vpc_interface

##### ANSIBLE VERSION

```
ansible 2.5.0 (devel 788010d0f0) last updated 2018/01/08 11:49:21 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/agents-ci/ansible/lib/ansible
  executable location = /root/agents-ci/ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### ADDITIONAL INFORMATION
* This PR fixes issues in #35736
* Integration test cases are enhanced for nxos_vpc_interface module to include all parameters
* Tested on all possible platforms and versions.

```
PLAY RECAP **************************************************************************************************************************************************
camden-nx-2.cisco.com      : ok=164  changed=55   unreachable=0    failed=0
dplus-nx-2.cisco.com       : ok=163  changed=55   unreachable=0    failed=0
evergreen-nx-2.cisco.com   : ok=163  changed=55   unreachable=0    failed=0
freeport-nx-2.cisco.com    : ok=163  changed=55   unreachable=0    failed=0
greensboro-nx-2.cisco.com  : ok=163  changed=55   unreachable=0    failed=0
n3k-173.cisco.com          : ok=162  changed=55   unreachable=0    failed=0
n3x-161.cisco.com          : ok=162  changed=55   unreachable=0    failed=0
n7k-99.cisco.com           : ok=162  changed=55   unreachable=0    failed=0
n7k-j.cisco.com            : ok=163  changed=55   unreachable=0    failed=0
n9k-100.cisco.com          : ok=164  changed=55   unreachable=0    failed=0
n9k-108.cisco.com          : ok=163  changed=55   unreachable=0    failed=0
```

2018-02-06 07:37 UTC, trishnaguha requested changes

2018-02-06 07:37 UTC, trishnaguha commented on lib/ansible/modules/network/nxos/nxos_vpc_interface.py
> +    elif delta.get('peer-link') and existing.get('peer-link') is not True:
Please modify this to `elif delta.get('peer-link') and not existing.get('peer-link'):`

2018-02-06 07:37 UTC, trishnaguha commented on lib/ansible/modules/network/nxos/nxos_vpc_interface.py
>      if delta.get('peer-link') is False and existing.get('peer-link') is True:
Modify this one as well? `if not delta.get('peer-link') and existing.get('peer-link'):`

2018-02-06 07:43 UTC, trishnaguha commented
@saichint please push the requested change and we are good to merge after that.

2018-02-06 17:56 UTC, saichint commented
Made changes and pushed

2018-02-07 03:05 UTC, trishnaguha approved these changes

2018-02-07 03:05 UTC, merged