Added code for modifying connection zones in nmcli module
ansible/ansible pull request #35765
Opened 2018-02-06 09:28 UTC by amolkahat

##### SUMMARY

Added code for modifying connection zones in nmcli module
pep8 fixes in test_nmcli.py file.
Fixes: GH 21591

Signed-off-by: Amol Kahat <akahat@redhat.com>

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
nmcli

##### ANSIBLE VERSION
```
ansible 2.5.0 (devel)
```

##### ADDITIONAL INFORMATION

2018-02-06 15:56 UTC, Akasurde requested changes

2018-02-06 15:56 UTC, Akasurde commented on test/units/modules/net_tools/test_nmcli.py
> +# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
No need of the new line here.

2018-11-08 14:46 UTC, oussemos requested changes

2018-11-08 14:46 UTC, oussemos commented on test/units/modules/net_tools/test_nmcli.py
> +        'ansible.module_utils.basic.AnsibleModule.get_bin_path')
The actual `max-line-length` is 160, so there's no need of a new lines here 

https://github.com/ansible/ansible/blob/379a7f4f5a0491964c7896834f3f326412888585/tox.ini#L31

2018-11-13 11:23 UTC, Akasurde commented
@oussemos Would you be interested in taking over this PR ? Let me know.

2018-11-13 12:28 UTC, oussemos commented
ok @Akasurde

2018-11-15 03:47 UTC, Akasurde commented
superseded by #48672

2018-11-15 03:47 UTC, closed without merging