Nictagadm
ansible/ansible pull request #35919
Opened 2018-02-08 19:12 UTC by Smithx10

##### SUMMARY
This change adds the ability to create and destroy nic_tags on SmartOS.

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
Module Name: nictagadm

##### ANSIBLE VERSION
```
(venv) bruce.smith@Bruces-MacBook-Pro /g/m/n/ansible ❯❯❯ ansible --version                                                                                              devel ⬇ ◼
ansible 2.5.0 (devel 273a3d1d51) last updated 2018/02/08 17:32:54 (GMT +700)
  config file = None
  configured module search path = [u'/Users/bruce.smith/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /git/me/nictagadm/ansible/lib/ansible
  executable location = /git/me/nictagadm/ansible/bin/ansible
  python version = 2.7.14 (default, Jan  6 2018, 12:16:16) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

2018-02-10 10:22 UTC, jasperla requested changes
I've not tested this module yet, once you could fix up the comments above I'll try it out. Thanks for adding more SmartOS support!

2018-02-10 10:22 UTC, jasperla commented on lib/ansible/modules/cloud/smartos/nictagadm.py
> +            - MAC Address to attach the NIC tag to when not using an etherstub. mac and etherstub are mutually exclusive.
Referring to other options would be better formatted as I(mac) and I(etherstub) to be consistent with some of the other SmartOS modules.

2018-02-10 10:22 UTC, jasperla commented on lib/ansible/modules/cloud/smartos/nictagadm.py
> +            - Specifies that the NIC tag will be attached to a created etherstub. etherstub is mutually exclusive with both mtu, and mac.
here too.

2018-02-10 10:22 UTC, jasperla commented on lib/ansible/modules/cloud/smartos/nictagadm.py
> +            - MTU size of the NIC tag. mtu and etherstub are mutually exclusive.
and here.

2018-02-10 10:22 UTC, jasperla commented on lib/ansible/modules/cloud/smartos/nictagadm.py
> +            - When State.Absent is set this switch will use the -f parameter and delete the NIC tag regardless of existing VMs
Would be better formatted as "When I(state) is absent this switch will use the C(-f) [...]" and there's a missing full stop.

2018-02-10 10:22 UTC, jasperla commented on lib/ansible/modules/cloud/smartos/nictagadm.py
> +- name: Create 'strage0' on '00:1b:21:a3:f5:4d'
typo, should be 'storage0'

2018-02-10 10:22 UTC, jasperla commented on lib/ansible/modules/cloud/smartos/nictagadm.py
> +  nictagadm: name=storage0 state=absent force=false
`force=false` is the default, so no need to explicitly add it, right?

2018-02-10 10:22 UTC, jasperla commented on lib/ansible/modules/cloud/smartos/nictagadm.py
> +class NICTAG(object):
This is a personal preference, but I'd rather not have a class name in all caps.

2018-02-10 10:22 UTC, jasperla commented on lib/ansible/modules/cloud/smartos/nictagadm.py
> +                         state=nictag.state)
Isn't this a bit too much context to report merely the MAC access is invalid? I'd include the `name`, `mac` and `etherstub` and leave out the others.

2018-02-10 10:22 UTC, jasperla commented on lib/ansible/modules/cloud/smartos/nictagadm.py
> +        if rc == 0:
Could be shortened to `return rc == 0` if you're not doing any further processing other than returning.

2018-02-14 04:29 UTC, Smithx10 commented
@jasperla I made the suggested changes, please critique.  On a side note, do you think we need any other SmartOS particular modules?

2018-02-25 12:47 UTC, jasperla approved these changes
Looks good to me.

2018-02-25 12:49 UTC, jasperla commented
@Smithx10 I don't particularly miss any other modules right now. That said, don't let that stop you from extending SmartOS support.

2018-02-25 12:49 UTC, jasperla commented
shipit

2018-02-27 12:17 UTC, jasperla commented on lib/ansible/modules/cloud/smartos/nictagadm.py
> +  - Create of delete nic tags on SmartOS systems.
s/of/or/

2018-05-22 22:21 UTC, maxamillion commented
@Smithx10 any desire to support `check_mode` ?

2018-05-24 21:30 UTC, Smithx10 commented
@maxamillion,

I've been a little tied up lately, but I'll see what's involved in implementing check_mode.

Thank You,
Bruce Smith

2018-05-25 02:29 UTC, maxamillion commented
@Smithx10 awesome!

2019-01-23 02:16 UTC, dagwieers approved these changes
LGTM, with a few cosmetic/doc changes

2019-01-23 02:16 UTC, dagwieers commented
rebuild_merge

2019-01-23 02:26 UTC, dagwieers commented
rebuild_merge

2019-01-23 03:57 UTC, merged