Changed os_server_facts example page
ansible/ansible pull request #36138
Opened 2018-02-13 21:32 UTC by dverkade

Changed os_server_facts example page, the example given is not working because the printed debug variable is not registered by os_server_facts.

2018-02-14 11:51 UTC, gundalow requested changes
According to the module documentation
> This module creates a new top-level `openstack_servers` fact, which contains a list of servers.

So if `openstack_servers` isn't being set anymore that's a bug

2018-07-31 21:39 UTC, dverkade commented
@gundalow @omgjlk What's needs to be done for this to move forward? Or should we close? It has been open for over 6 months now.

2018-08-01 17:04 UTC, omgjlk commented
This documentation change is incorrect. If the module isn't setting the variable right, then the module needs to be fixed.

2018-08-01 17:55 UTC, dverkade commented
@omgjlk then you should close this PR and create an issue instead?

2018-08-01 18:17 UTC, omgjlk commented
Sorry I don't have access to any OpenStack clouds any more and I'm unable to validate the module or the documentation.

2018-08-01 18:59 UTC, dverkade commented
@omgjlk So who can check it and how are we going forward? Can someone assign the right person to the PR?

2018-08-01 20:44 UTC, omgjlk commented
One of the folks mentioned [here](
https://github.com/ansible/ansible/pull/36138#issuecomment-365413058) should be able to test / act upon the PR.

2018-08-01 20:53 UTC, omgjlk commented
I can see that the module [returns the facts](https://github.com/ansible/ansible/blob/7c13c4b2074ed3e3b4a9301ff686df789478451d/lib/ansible/modules/cloud/openstack/os_server_facts.py#L81-L82) in the json, so I'm really curious why the example play didn't work for you. Can you show me the output with at least 3 `v`s of verbosity?

2018-08-02 02:02 UTC, dverkade commented
Checked again, this is working on my test environment with a test case. Closing this PR.

2018-08-02 02:02 UTC, closed without merging

2018-08-02 20:28 UTC, omgjlk commented
Thanks for testing again @dverkade !