[WIP] added support for --testcase flag in ansible-test
ansible/ansible pull request #36134
Opened 2018-02-13 19:38 UTC by newswangerd

##### SUMMARY

The `--testcase` flag allows users to limit network-integration tests to a specific test case

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

ansible-test

##### ANSIBLE VERSION

```
ansible 2.6.0 (ansible_test_testcase 02a3a2bb96) last updated 2018/02/13 14:32:01 (GMT -400)
  config file = None
  configured module search path = ['/Users/david/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/david/code/ansible/lib/ansible
  executable location = /Users/david/code/ansible/bin/ansible
  python version = 3.6.4 (default, Jan  6 2018, 11:51:59) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### ADDITIONAL INFORMATION

```

```

2018-02-13 19:42 UTC, mattclay requested changes

2018-02-13 19:42 UTC, mattclay commented on test/runner/lib/executor.py
> +                cmd += ['-e testcase=%s' % args.testcase]
This should be:

```python
cmd += ['-e', 'testcase=%s' % args.testcase]
```

2018-02-14 13:51 UTC, gundalow reviewed
Could you please document this at https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/dev_guide/testing_integration.rst#running-network-integration-tests-locally

2018-02-14 16:29 UTC, gundalow approved these changes

2018-02-14 16:32 UTC, gundalow commented
Thanks for updating the docs.
@mattclay Once you approve this are you OK then we cherry-pick this into `stable-2.5`

2018-02-14 22:10 UTC, mattclay approved these changes

2018-02-14 22:10 UTC, mattclay commented
I'm OK with this in stable-2.5. @nitzmahone ?

2018-02-14 23:27 UTC, nitzmahone commented
LGTM for cherry-pick to 2.5

2018-02-14 23:27 UTC, nitzmahone approved these changes

2018-02-14 23:40 UTC, merged

2018-02-14 23:42 UTC, nitzmahone commented
cherry-picked to stable-2.5 for 2.5.0b2