Fix nxos_system tests
ansible/ansible pull request #36201
Opened 2018-02-14 20:06 UTC by mikewiebe

##### SUMMARY
* Moves `targets/nxos_system/tests/cli/sanity.yaml` inside a block so that if a step fails the username is reconfigured.  WIthout this other test can fail that require a specific username.
* Adds an ignore_errors: yes check for a teardown step.  Nxapi will error out when the domain does not exist.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
nxos_system

##### ANSIBLE VERSION
```
ansible 2.6.0 (rel250/fix_nxos_user 5a98076eb3) last updated 2018/02/14 13:01:12 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/Users/mwiebe/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/mwiebe/Projects/nxos_ansible/fix_ansible/lib/ansible
  executable location = /Users/mwiebe/Projects/nxos_ansible/fix_ansible/bin/ansible
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```

2018-02-14 20:06 UTC, mikewiebe commented
@trishnaguha  nxos_system test fixes.

2018-02-15 05:13 UTC, trishnaguha commented
@mikewiebe Can we move the sanity test in common directory because I don't find any test difference for cli and nxapi?

2018-02-15 05:15 UTC, trishnaguha requested changes

2018-02-15 05:15 UTC, trishnaguha commented on test/integration/targets/nxos_system/tests/cli/sanity.yaml
> +- debug: msg="START TRANSPORT:CLI nxos_system sanity test"
Please update the debug statement to:
```
- debug: msg="START connection={{ ansible_connection }}/sanity.yaml"
- debug: msg="Using provider={{ connection.transport }}"
  when: ansible_connection == "local"
```

2018-02-15 05:15 UTC, trishnaguha commented on test/integration/targets/nxos_system/tests/cli/sanity.yaml
> +  - debug: msg="END TRANSPORT:CLI nxos_system sanity test"
Please update the debug statement to
`- debug: msg="END connection={{ ansible_connection }}/sanity.yaml"`

2018-02-17 04:44 UTC, trishnaguha approved these changes

2018-02-17 04:44 UTC, merged

2018-02-17 06:50 UTC, trishnaguha commented
cherry-picked to stable-2.5