New module: manage 1&1 users (cloud/oneandone/oneandone_user)
ansible/ansible pull request #36209
Opened 2018-02-14 22:00 UTC by aajdinov

##### SUMMARY
Adding a new cloud module to support oneandone user management.

##### ISSUE TYPE
 - Feature Pull Request
 - New Module Pull Request

##### COMPONENT NAME
 - oneandone_user cloud module
 - oneandone module_util

##### ANSIBLE VERSION
```
ansible 2.6.0 (oneandone_users ad143452d7) last updated 2018/02/14 22:52:46 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### ADDITIONAL INFORMATION
Below is the output from one of the test playbooks utilizing the new module:
```
PLAY [localhost] ****************************************************************

TASK [Gathering Facts] *******************************************************
ok: [localhost]

TASK [Create a user] **********************************************************

changed: [localhost]

PLAY RECAP ********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0   
```

2018-03-19 21:10 UTC, aajdinov commented
@samdoran @resmo 

Is there anything else that needs to be done for these remaining 3 PRs to get merged?

2018-04-10 15:21 UTC, aajdinov commented
ready_for_review

2018-04-17 00:57 UTC, aajdinov commented
@resmo 
Hello René, is there anything I can do to speed up the merging process for the remaining remaining three PRs (new modules: manage 1&1 resources)

2018-04-17 05:59 UTC, resmo commented
@aajdinov Thanks for pinging, I put these on my list to review.

2018-04-24 01:46 UTC, aajdinov commented
@resmo Thank you. I'm available if there's anything else that needs to be done to get the three remaining PRs merged.

2018-04-24 11:21 UTC, resmo commented on lib/ansible/modules/cloud/oneandone/oneandone_user.py
> +# along with Ansible.  If not, see <http://www.gnu.org/licenses/>.
There is a short version of the GPL header, and add your copyright to it. "This file is part of Ansible" can be removed.

2018-04-24 11:21 UTC, resmo commented on lib/ansible/modules/cloud/oneandone/oneandone_user.py
> +    required: false
not a blocker but `required: false` is the default and can be omitted.

2018-04-24 11:51 UTC, resmo requested changes
please clarify state=update. 

Also consider to implement support for `check_mode`

needs_info

2018-04-24 11:51 UTC, resmo commented on lib/ansible/modules/cloud/oneandone/oneandone_user.py
> +    choices: [ "present", "absent", "update" ]
`update` is not ansible compliant

A task defines a state, so `present` should already update the user according to the params given if needed (and return changed in this case). Please change the logic accordingly or provide some information why `update` is needed.

2018-04-24 11:51 UTC, resmo commented on lib/ansible/modules/cloud/oneandone/oneandone_user.py
> +                    msg="%s parameter is required for new users." % param)
not a blocker but there is a helper in the basic.py in  AnsibleModule `required_if` see https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/cloudstack/cs_vpc.py#L336 for an example.

2018-06-11 21:56 UTC, aajdinov commented
Hello @resmo 
Thank you for the review and feedback. 
I've added `check_mode`.
As far as `state=update` is concerned, it made sense because of the many different aspects of the conditional differences that API makes between the POST and PUT operations. The code is cleaner and has less nesting, and there are already six 1and1 modules merged to the main branch, which use the `state=update` so it is in accordance with the previously accepted code. Changing the approach would complicate things and would require revisioning the previous modules and removing the `state=update` would break backward compatibility with the user's playbooks.
Also, I've noticed that there is a number of other modules using multiple states as well, like [amazon's iam](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/iam.py#L610) and [google's gce](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/google/gce.py#L631).

2020-08-16 21:08 UTC, closed without merging