yum_repository: fix gpgcheck default
ansible/ansible pull request #36242
Opened 2018-02-15 15:54 UTC by mkrizek

##### SUMMARY
By default yum sets gpgcheck to 1, so we need to explicitly set the
module's default, which is 0.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME
yum_repository

##### ANSIBLE VERSION

```
devel
```

##### ADDITIONAL INFORMATION

2018-02-15 16:25 UTC, webknjaz approved these changes

2018-02-15 17:46 UTC, jtyr commented
The default value of `bool` argument is `Null`. That makes the argument to be ignored. If you set it to `False` then the `gpgcheck` argument will be always present which should not be intended behavior. YUM considers the `gpgcheck` option to be [1 by default](https://linux.die.net/man/5/yum.conf). so if somebody want to have it set to `0` then the `gpgcheck` argument should be set explicitly to `no` by the user.

2018-02-15 18:57 UTC, mkrizek commented
@jtyr https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/os/yum_repository.py#L124 module's default is stated as `no`, if we want to leave it that way we need to put `gpgcheck = 0` into `.repo` file because yum sets `gpgcheck = 1` by default. So it's either this PR or fix the docs since they don't reflect the current behavior. Please correct me if I am wrong. Better ideas more than welcome :)

2018-02-15 21:32 UTC, resmo commented
according the current state of the code (when I understand this correctly) the default is `gpgcheck=true`. When we change the default in the code, we break backwards compatibility (and might also break security).

The doc (and code) should be updated to explicitly reflect the current implementation of `gpgcheck: true`.

2018-02-15 21:35 UTC, resmo requested changes
needs_revision

2018-02-15 22:22 UTC, jtyr commented
The code is correct, only the documentation is wrong. I have created PR to fix it: #36267.

2018-02-16 03:33 UTC, webknjaz commented
In such case, I would recommend to also add a test for the correct behavior, so that no one misinterprets the initial intent. Or just convert added test to do `not in` check.

2018-02-16 08:32 UTC, mkrizek commented
Closing in favor of #36267

2018-02-16 08:32 UTC, closed without merging