Update network debug troubleshooting guide
ansible/ansible pull request #36288
Opened 2018-02-16 06:08 UTC by ganeshrn

##### SUMMARY

Fix #35914

Command timeout and connection timeout error messages
are displayed in the log file instead of on the console.
Update the same in the troubleshooting guide.

##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

rst/networking_guide/network_debug_troubleshooting.rst

##### ANSIBLE VERSION

```
2.5
```

##### ADDITIONAL INFORMATION

```

```

2018-02-16 12:16 UTC, gundalow requested changes
Thanks, just a few minor comments

2018-02-16 12:16 UTC, gundalow commented on docs/docsite/rst/networking_guide/network_debug_troubleshooting.rst
> +========================================================
Only need `=` as long as the line above

2018-02-16 12:16 UTC, gundalow commented on docs/docsite/rst/networking_guide/network_debug_troubleshooting.rst
> +The ``socket_path does not exist or cannot be found``  and ``unable to connect to socket`` message is new in Ansible 2.5. This message means that
"message is new" -> "messages are new"
"This message means" -> "These messages means"

2018-02-16 12:16 UTC, gundalow commented on docs/docsite/rst/networking_guide/network_debug_troubleshooting.rst
> +Follow the steps detailed in enable_network_logging_.
May be GitHub formatting issue, though this doesn't look right.
I think you want
```
 :ref:`enable network logging <enable_network_logging>`
```

2018-02-16 12:16 UTC, gundalow commented on docs/docsite/rst/networking_guide/network_debug_troubleshooting.rst
> +If the identified the error message from the log file is
"log file is:"

2018-02-16 12:16 UTC, gundalow commented on docs/docsite/rst/networking_guide/network_debug_troubleshooting.rst
> +For example:
Delete this and a blank line

2018-02-16 12:16 UTC, gundalow commented on docs/docsite/rst/networking_guide/network_debug_troubleshooting.rst
> +Follow the steps detailed in timeout_issues_.
Same as above think you need `:ref`

2018-02-16 12:17 UTC, gundalow commented
Thanks for this. Will need approval from both @acozine and @dharmabumstead 

Once they are happy this will need to go into `devel` & `stable-2.5`

2018-02-16 18:39 UTC, ganeshrn commented
ready_for_review

2018-02-16 18:42 UTC, dharmabumstead approved these changes
OK with some edits.

2018-02-16 18:53 UTC, gundalow approved these changes

2018-02-19 10:08 UTC, rcarrillocruz approved these changes

2018-02-19 13:23 UTC, trishnaguha approved these changes

2018-02-19 14:38 UTC, acozine approved these changes
Good info to include with the release. Thanks @ganeshrn.

2018-02-19 15:10 UTC, ganeshrn commented
@gundalow @acozine @dharmabumstead @trishnaguha @rcarrillocruz Thank you for review.

2018-02-19 15:10 UTC, merged

2018-02-19 15:49 UTC, ganeshrn commented
Cherry-pick to stable-2.5 51673f431f7f8c6ae4dcbdfac97e7d00b4203e46