GCP: HTTP Health Checks
ansible/ansible pull request #36329
Opened 2018-02-16 20:05 UTC by rambleraptor

##### SUMMARY
Adding support for GCP HTTP Health Checks

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
gcp_compute_http_health_check

##### ANSIBLE VERSION
```
2.6
```

##### ADDITIONAL INFORMATION
This was autogenerated using [Magic Modules](https://github.com/GoogleCloudPlatform/magic-modules)

2018-02-16 21:37 UTC, rambleraptor commented
@ryansb please take a look!

2018-03-07 21:54 UTC, ryansb requested changes

2018-03-07 21:54 UTC, ryansb commented on lib/ansible/modules/cloud/google/gcp_compute_http_health_check.py
> +              5
Join this and the line below

2018-03-07 21:54 UTC, ryansb commented on lib/ansible/modules/cloud/google/gcp_compute_http_health_check.py
> +              when
Same here. Looks like some strange linewrapping is going on.

2018-03-07 21:54 UTC, ryansb commented on lib/ansible/modules/cloud/google/gcp_compute_http_health_check.py
> +              by
Same, linewraps

2018-03-07 21:54 UTC, ryansb commented on lib/ansible/modules/cloud/google/gcp_compute_http_health_check.py
> +              means
Same, linewraps

2018-03-07 21:54 UTC, ryansb commented on lib/ansible/modules/cloud/google/gcp_compute_http_health_check.py
> +    timeout_sec:
Can you make this parameter `timeout_seconds` please? An alias would be ok

2018-03-07 21:54 UTC, ryansb commented on lib/ansible/modules/cloud/google/gcp_compute_http_health_check.py
> +        response.raise_for_status
This should be a method call, `response.raise_for_status()`

2018-03-12 06:12 UTC, rambleraptor commented
PTAL

2018-03-21 19:18 UTC, ryansb submitted a review, later dismissed

2018-03-21 19:18 UTC, ryansb commented on lib/ansible/modules/cloud/google/gcp_compute_http_health_check.py
> +            check_interval_sec=dict(type='int'),
This needs the same alias treatment as timeout_sec has

2018-04-02 21:10 UTC, s-hertel approved these changes

2018-04-02 21:10 UTC, s-hertel commented on lib/ansible/modules/cloud/google/gcp_compute_http_health_check.py
> +                fetch = update(module, self_link(module), kind, fetch)
I think changed needs to be set to True here.

2018-04-02 21:10 UTC, s-hertel commented on lib/ansible/modules/cloud/google/gcp_compute_http_health_check.py
> +    auth = GcpSession(module, 'compute')
This function is called in a number of places and auth is set elsewhere as well, so it looks like auth gets set to the same thing a few times for every playbook run. Not a blocker, just making note that it could be set once instead.

2018-04-02 21:10 UTC, s-hertel commented on test/integration/targets/gcp_compute_http_health_check/tasks/main.yml
> +---
Not a blocker, but it would be good to have a test to check resource modification as well. That could apply for #35920 too.

2018-04-19 19:19 UTC, rambleraptor commented on lib/ansible/modules/cloud/google/gcp_compute_http_health_check.py
> +                fetch = update(module, self_link(module), kind, fetch)
Changed! (in next line)

2018-04-25 19:25 UTC, merged