Add support for vmware_guest:connected.
ansible/ansible pull request #36349
Opened 2018-02-17 18:41 UTC by kdienes

##### SUMMARY
This adds support for setting the 'connected' status of a NIC from vmware_guest.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
latest (5242914ae5ac15ea5d5e7ba3607bb6c8eb9c72a6)

##### ADDITIONAL INFORMATION
Lightly tested.  I am happy to revise if I've missed anything or if there is a place I should be adding test cases or additional documentation.

2018-02-19 10:44 UTC, Akasurde commented
@kdienes Thanks for contribution. Could you please add integration test for this change ? You can start [here](https://github.com/ansible/ansible/blob/devel/test/integration/targets/vmware_guest/tasks/network_negative_test.yml).

2018-02-19 10:44 UTC, Akasurde requested changes

2018-02-19 10:44 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +    - ' - C(connected) (bool): Sets if virtual network adapter is connected. version_added: 2.5'
s/2.5/2.6/

2018-03-21 13:53 UTC, Akasurde commented
@kdienes Are you still working on this ? needs_info

2018-04-19 11:07 UTC, Akasurde commented
@kdienes Any news ?

2018-05-05 20:11 UTC, kdienes commented
I'm still interested in completing this patch but haven't had the time to write the tests.  I don't expect to for at least another several weeks.  I'm happy if someone wants to take over the patch, or willing to withdraw the PR and resubmit when I am able if you prefer.

2019-01-21 18:02 UTC, mattclay commented
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/102869/87/tests

2020-08-18 06:14 UTC, Akasurde commented
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.vmware.

Please re-submit this PR in the above repository.

If you have further questions please stop by IRC or the mailing list:

* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project

2020-08-18 06:14 UTC, closed without merging