Adds example on how to "delegate" check_for_connection
ansible/ansible pull request #36524
Opened 2018-02-21 15:58 UTC by tterranigma

##### SUMMARY

`wait_for_connection` is an action plugin and does not support `delegate_to`. I added a note and an example on how to overcome this limitation, without mentioning 'action plugins' or other technical terms that are irrelevant to end users.

See #36519 

##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME
wait_for_connection

##### ANSIBLE VERSION

```
ansible 2.6.0 (waitforconnectiondoc c534f60828) last updated 2018/02/21 16:55:00 (GMT +200)
  config file = None
  configured module search path = ['/home/nikos/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/nikos/Projects/ansible/lib/ansible
  executable location = /home/nikos/Projects/ansible/bin/ansible
  python version = 3.6.4 (default, Jan  5 2018, 02:35:40) [GCC 7.2.1 20171224]
```

2018-02-23 12:56 UTC, dagwieers commented
Well, looking at the example, I think this is the wrong way to do this. Although technically possible, the easier approach is to start targeting the (newly created) remote node in a subsequent play, just as you would do with existing systems.

So I prefer not to add this example because it adds unneeded complexity.

2018-02-23 13:05 UTC, dagwieers commented
The proper example would look like this:
```yaml
# Build an online instance, wait for it to become ready and continue (playbook
# runs against localhost).
- hosts: localhost
  tasks:
    - name: Create instance on Google Cloud
      gce:
        name: instance-name
        zone: europe-west1-b
        network: default
        subnet: subnet-name
        machine-type: n1-highcpu-4
        image-family: windows-2016
      register: instance

    - add_host:
        hostname: win_instance
        groups: new_systems
        ansible_host: "{{ instance.instance_data[0].public_ip }}"
        ansible_connection: winrm
        ansible_port: 5986
        ansible_winrm_server_cert_validation: ignore
        ansible_winrm_transport: ntl
        ansible_password: password

- hosts: new_systems
  tasks:
    - wait_for_connection:
```

Personally I prefer to do the first part differently as well.
- Add the new systems to te inventory (e.g. as part of a temporary group)
- Target the temporary group
- Delegate the tasks to provision the system(s) to localhost (or use connection: local)
- Run subsequent tasks just as you would for existing targets

```yaml
# Build an online instance, wait for it to become ready and continue
- hosts: new_systems
  tasks:
    - name: Create instance on Google Cloud
      gce:
        name: '{{ inventory_hostname }}'
        zone: '{{ gce_zone }}'
        network: default
        subnet: '{{ gce_subnet_name }}'
        machine-type: '{{ gce_machine_type }}'
        image-family: '{{ gce_image_family }}'
      delegate_to: localhost
      register: instance

    - set_fact:
        ansible_host: '{{ instance.instance_data[0].public_ip }}'

    - wait_for_connection:
```

And this is almost identical to the existing VMware example, except that here we update the remote address of the target.

2018-02-23 13:07 UTC, dagwieers requested changes

2018-02-23 13:07 UTC, dagwieers commented on lib/ansible/modules/utilities/logic/wait_for_connection.py
> +      vars: *windows
So I don't think this is something we want to expose to users as the ideal way to do this. See my other comment.

2018-02-23 16:59 UTC, dagwieers commented
This relates ti #36519

2018-11-30 18:22 UTC, maxamillion commented
Thank you for the pull request but it was discussed within the community and agreed to that this is not the recommended best practice. I see there is ongoing discussion in the original issue ticket that will hopefully net a positive result.

2018-11-30 18:22 UTC, closed without merging