module: add ceph volume storage module
ansible/ansible pull request #36590
Opened 2018-02-22 16:33 UTC by leseb

##### SUMMARY

Using the ceph-volume utility available in Ceph this module
can be used to create ceph OSDs that are backed by logical
 volumes.
Only available in ceph versions luminous or greater.

Co-authored-by: Andrew Schoen <aschoen@redhat.com>
Signed-off-by: Sébastien Han <seb@redhat.com>

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME
`lib/ansible/modules/storage/ceph/ceph_volume.py`

##### ANSIBLE VERSION

```
2.5.0
```

2018-02-22 16:34 UTC, leseb commented
FYI: @andrewschoen, @guits, @alfredodeza

2018-02-22 16:45 UTC, leseb commented
Removed the test file, hope that will make the test pass this time.

2018-02-23 14:11 UTC, leseb commented
ready_for_review

2018-05-23 16:06 UTC, maxamillion commented on lib/ansible/modules/storage/ceph/ceph_volume.py
> +    # FIXME: this does not work when data is a raw device
What happens if data is a raw device?

2018-05-23 16:07 UTC, maxamillion commented
As a general note, I would like to encourage the addition of integration tests with the new module addition please. :)

2018-05-23 18:26 UTC, leseb commented
@maxamillion the Ansible CI does not allow adding functional tests. I did that in my initial patch set but it got rejected thinking I was providing 2 modules...

2018-05-23 20:41 UTC, maxamillion commented
@leseb good to know, thank you. What newer content are you suggesting? Let me know when it's ready for review and I'll gladly do so.

2018-05-24 19:18 UTC, leseb commented
@maxamillion thanks for your help, I just need to resync the module with the newer content we have on https://github.com/ceph/ceph-ansible/.
This won't happen immediatly though, expect something from me in 2 weeks.

Thanks again for your help.

2018-05-24 19:24 UTC, maxamillion commented
@leseb the development freeze for Ansible 2.6 is tomorrow as per the [Roadmap](https://docs.ansible.com/ansible/devel/roadmap/ROADMAP_2_6.html), after that we will have to defer to Ansible 2.7

2019-10-22 07:35 UTC, Akasurde requested changes
Thanks for the contribution. Could you please add an unit test for this change ? needs_info

2019-10-22 07:35 UTC, Akasurde commented on lib/ansible/modules/storage/ceph/ceph_volume.py
> +short_description: Create ceph OSDs with ceph-volume
I think you should at least provide update volume functionality to provide idempotency.

2019-10-22 07:35 UTC, Akasurde commented on lib/ansible/modules/storage/ceph/ceph_volume.py
> +version_added: "2.6"
```suggestion
version_added: "2.10"
```

2019-10-22 07:35 UTC, Akasurde commented on lib/ansible/modules/storage/ceph/ceph_volume.py
> +
```suggestion
ceph_bin = module.get_bin_path('ceph-volume', True)
```

2019-10-22 07:35 UTC, Akasurde commented on lib/ansible/modules/storage/ceph/ceph_volume.py
> +    cmd = [
Check if volume already exists or not before proceeding to the creation of volume.

2019-10-22 07:51 UTC, leseb commented
@Akasurde thanks for the review but I'm not planning on pursuing this. The latest version is available here: https://github.com/ceph/ceph-ansible/blob/master/library/ceph_volume.py.
Also, I originally added unit tests but the CI did not accept more than a single file.

2019-10-22 07:51 UTC, closed without merging

2019-10-22 08:01 UTC, Akasurde commented
@leseb Thanks for the information and contribution.