Fixes #36635 - Changed labels type from list to dict on docker_volume module
ansible/ansible pull request #36638
Opened 2018-02-23 13:27 UTC by hdimitriou

##### SUMMARY
'docker_volume' expects 'labels' to be a list which is a mistake - it should be a dict as expected by docker-py (similarly to docker_container module). Creating a volume with labels fails currently

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
docker_volume

##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = /mnt/home/ci/apps64/ansible/mssql/LIT-203040-harris/ansible.cfg
  configured module search path = [u'/home/ci/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
```

2018-02-26 11:25 UTC, Akasurde requested changes

2018-02-26 11:25 UTC, Akasurde commented on lib/ansible/modules/cloud/docker/docker_volume.py
> +        labels=dict(type='dict'),
Could you please update documentation on line 41 as well ? also a note about this change in [changelog.md](https://github.com/ansible/ansible/blob/devel/CHANGELOG.md#minor-changes)

2018-10-20 12:44 UTC, felixfontein commented
@hdimitriou are you still around?

2018-11-12 06:08 UTC, felixfontein commented
I've created a new PR for this in #48536.

2018-11-12 12:23 UTC, webknjaz commented
Implemented by #48536.

2018-11-12 12:23 UTC, closed without merging