Add aws_caller_facts module and use it in setup-iam.yml
ansible/ansible pull request #36683
Opened 2018-02-24 23:47 UTC by orthanc

##### SUMMARY
Introduce a new module aws_caller_facts that returns details about the user and account being used to make AWS calls.

This is primarily useful for getting the account ID so that it can be inserted into templates of IAM policies and other things that need full ARNs.

Specifically in this case I'm updating the `hacking/aws_config/setup-iam.yml` playbook to use it so as to remove the dependency on having the AWS command line tools installed.

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
aws_caller_facts

##### ANSIBLE VERSION
```
ansible 2.6.0 (aws_caller_facts_module ee8565737c) last updated 2018/02/25 12:41:33 (GMT +1300)
  config file = None
  configured module search path = [u'USER_HOME/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = ANSIBLE_CHECKOUT/lib/ansible
  executable location = ANSIBLE_CHECKOUT/bin/ansible
  python version = 2.7.14 (default, Sep 23 2017, 22:06:14) [GCC 7.2.0]
```

2018-02-26 12:45 UTC, s-hertel approved these changes

2018-02-27 01:28 UTC, willthames requested changes
This is generally a good module but just missing the latest improvements to AWS module development.

2018-02-27 01:28 UTC, willthames commented on lib/ansible/modules/cloud/amazon/aws_caller_facts.py
> +from ansible.module_utils.basic import AnsibleModule
I think it's time to say new modules should use aws.core.AnsibleAWSModule

2018-02-27 01:28 UTC, willthames commented on lib/ansible/modules/cloud/amazon/aws_caller_facts.py
> +from ansible.module_utils.ec2 import HAS_BOTO3
Not needed with AnsibleAWSModule

2018-02-27 01:28 UTC, willthames commented on lib/ansible/modules/cloud/amazon/aws_caller_facts.py
> +error:
We don't really document failures, mostly because it's a completely different code path.

2018-02-27 01:28 UTC, willthames commented on lib/ansible/modules/cloud/amazon/aws_caller_facts.py
> +import traceback
Not needed with AnsibleAWSModule

2018-02-27 01:28 UTC, willthames commented on lib/ansible/modules/cloud/amazon/aws_caller_facts.py
> +    if not HAS_BOTO3:
Not needed with AnsibleAWSModule

2018-02-27 01:28 UTC, willthames commented on lib/ansible/modules/cloud/amazon/aws_caller_facts.py
> +    except ClientError as e:
As per the [AWS module development guidelines](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/GUIDELINES.md#using-fail_json_aws), standard AnsibleAWSModule exception handling looks like:

```
except (BotoCoreError, ClientError) as e:
    module.fail_json_aws(e, msg="Couldn't get caller identity")
```

2018-02-27 01:29 UTC, willthames commented
Note that all new AWS modules should include integration tests.

In this case that should be very straightforward - just run the module and check the results look reasonable.

2018-02-27 01:36 UTC, orthanc commented
Thanks @willthames, will review the updated guidelines and update accordingly.

I'll have a look at what we can reasonably assert in an integration test, may be limited to just "Not None" checks on the key fields but that's probably sufficient in this case.

2018-02-27 01:46 UTC, willthames commented
@orthanc that would be absolutely fine. At least that would catch some future change accidentally changing the return keys, which is the kind of thing we're trying to protect against.

2018-02-27 18:15 UTC, orthanc commented
ready_for_review

Have switched to the AnsibleAWSModule and added a test

2018-02-28 01:56 UTC, willthames requested changes

2018-02-28 01:56 UTC, willthames commented on test/integration/targets/aws_caller_facts/tasks/main.yaml
> +  block:
This block isn't really required (as we don't use any block features, such as `always`)

2018-02-28 01:56 UTC, willthames commented
Once the unnecessary block goes, this is good to merge imho.

2018-02-28 04:36 UTC, orthanc commented
ready_for_review

Block removed 

My rational for the block was to name the test (even though there's only one) and make it clear that cleanup activities had been considered.

Probably adds more confusion than it solves though so I've removed it.

2018-02-28 06:29 UTC, willthames commented
I noticed a few minor style issues to fix in the test suite and pushed those to your branch

* Consolidate return value tests
* Use newer `aws_` prefix rather than older `ec2_` prefix for variable names like `aws_region`.
* Remove non-meaningful lines at the top, add space between tasks

2018-02-28 06:30 UTC, willthames approved these changes

2018-02-28 06:30 UTC, merged

2018-02-28 06:31 UTC, willthames commented
Thanks @orthanc, this is a really useful module.

Umm, just realised - do you want to do another PR for adding it to the CHANGELOG?

2018-02-28 06:35 UTC, orthanc commented
Thanks. Will create another pr for the changelog.