crypto/*: Provide a common sanity check across modules
ansible/ansible pull request #36781
Opened 2018-02-27 13:35 UTC by Spredzy

##### SUMMARY

This commit aims to provide few things:

  * Provide a common, reusable, sanity_check(module) method for
    all openssl_* modules

  * Ensure required path exists *and* are not empty, fails otherwise

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

  - openssl_privatekey
  - openssl_publickey
  - openssl_csr
  - openssl_certificate 

##### ANSIBLE VERSION

  - devel

##### ADDITIONAL INFORMATION

Fixes https://github.com/ansible/ansible/issues/36738

2018-02-27 13:45 UTC, MarkusTeufelberger commented
shipit

2018-02-27 13:51 UTC, pilou- commented on lib/ansible/module_utils/crypto.py
> +            msg='The directory %s does not exist or the file is not a directory' % base_dir
s/file/path/

2018-02-27 13:51 UTC, pilou- commented on lib/ansible/module_utils/crypto.py
> +    """Check if the speficied file exists and is not empty."""
s/speficied/specified/

2018-02-27 13:51 UTC, pilou- commented on lib/ansible/module_utils/crypto.py
> +def exists_and_not_empty(file):
You might want to use another variable name.

2018-02-27 13:51 UTC, pilou- commented on lib/ansible/module_utils/crypto.py
> +       raise OpenSSLObjectError("File %s is does not exist" % file)
s/is does/is/

2018-02-27 14:44 UTC, pilou- requested changes
As discussed with the submitter, custom type checker should be used.

2018-02-28 23:45 UTC, mattclay commented
In addition to the sanity test failures, there are integration test failures due to traceback:

```
Traceback (most recent call last):
  File "/tmp/ansible_X9E90v/ansible_module_openssl_certificate.py", line 903, in <module>
    main()
  File "/tmp/ansible_X9E90v/ansible_module_openssl_certificate.py", line 864, in main
    sanity_check(module)
  File "/tmp/ansible_X9E90v/ansible_module_openssl_certificate.py", line 813, in sanity_check
    crypto_utils.load_certificate_request(module.params['csr_path'])
  File "/tmp/ansible_X9E90v/ansible_modlib.zip/ansible/module_utils/crypto.py", line 97, in load_certificate_request
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

2018-09-23 15:21 UTC, Akasurde commented
@Spredzy Are you working on this ?

2019-01-14 12:36 UTC, MarkusTeufelberger commented
@Spredzy - any news?

2019-08-24 12:58 UTC, MarkusTeufelberger commented
The original issue is already fixed, so let's close this one.

close_me

2019-08-24 13:07 UTC, closed without merging