Lenovo license update
ansible/ansible pull request #36840
Opened 2018-02-28 12:19 UTC by amuraleedhar

SUMMARY

Updating License after review from Lenovo legal team.

ISSUE TYPE

- Documentation Pull Request

COMPONENT NAME

lib/ansible/modules/network/enos/enos_command.py
lib/ansible/modules/network/enos/enos_config.py
lib/ansible/modules/network/enos/enos_facts.py
lib/ansible/plugins/action/enos.py
lib/ansible/plugins/action/enos_config.py
lib/ansible/plugins/cliconf/enos.py
lib/ansible/plugins/terminal/enos.py
lib/ansible/utils/module_docs_fragments/enos.py

ANSIBLE VERSION

ansible 2.5.0
config file = /etc/ansible/ansible.cfg
configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible-2.5.0-py2.7.egg/ansible
executable location = /usr/local/bin/ansible
python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]

ADDITIONAL INFORMATION

This is an effort to create config modules for enos based switches from Lenovo.

2018-02-28 16:55 UTC, gundalow commented
It's the copyright character, please use `(c)` instead

2018-02-28 17:25 UTC, gundalow approved these changes

2018-02-28 17:43 UTC, abadger commented
The two things I see are: (1) Inclusion of "All rights reserved".  This is obsolete verbiage that is just confusing in open source software (as we are licensing the work to give away specific rights).  It became 100% obsolete in 2000: https://en.wikipedia.org/wiki/All_rights_reserved

(2) Removing the copyright notice for Red Hat.  I'm always very careful when I remove copyright notices from a file.  We should check that those files have never had a commit from a Red Hat/Ansible employee before doing that.

2018-03-01 13:58 UTC, gundalow requested changes

2018-03-01 13:58 UTC, gundalow commented on lib/ansible/utils/module_docs_fragments/enos.py
> +# Copyright © 2017 Lenovo. All rights reserved.
`(C)`

2018-03-02 17:11 UTC, amuraleedhar commented on lib/ansible/utils/module_docs_fragments/enos.py
> +# Copyright © 2017 Lenovo. All rights reserved.
Done

2018-03-06 17:45 UTC, gundalow approved these changes

2018-03-06 17:56 UTC, abadger commented
Looks good.  +1 to merge.

2018-03-06 18:02 UTC, merged

2018-03-06 18:02 UTC, gundalow commented
Thanks,
Merged