New module: support Alibaba Cloud ECS (cloud/alicloud/alicloud_instance)
ansible/ansible pull request #36898
Opened 2018-03-01 09:44 UTC by xiaozhu36

This is reopen PR of #25975 

SUMMARY

Added a new module alicloud_instance.py that can manage alicloud ecs instance.

COMPONENT NAME

lib/ansible/module_utils/alicloud_ecs.py
lib/ansible/modules/cloud/alicloud/alicloud_instance.py
lib/ansible/modules/cloud/alicloud/alicloud_instance_facts.py

ANSIBLE VERSION

2.4.0

2018-03-09 00:59 UTC, dharmabumstead commented
Edit pending. Please don't merge.

2018-04-05 18:03 UTC, dharmabumstead submitted a review, later dismissed
The guide_alicloud file will need to be moved into the scenario_guides directory.

2018-04-06 10:24 UTC, xiaozhu36 commented
Hi @dharmabumstead I have moved guide_alicloud file into the scenario_guides directory, and please check it. Thanks a lot.

2018-05-07 01:23 UTC, xiaozhu36 commented
HI @dharmabumstead @gundalow Is there any progress about this PR? Do I need to do more works?

2018-05-11 15:29 UTC, ryansb submitted a review, later dismissed

2018-05-11 15:29 UTC, ryansb commented on docs/docsite/rst/scenario_guides/guide_alicloud.rst
> +      alicloud_access_key: "{{alicloud_access_key}}"
Incorrect indentation - these lines need 2 more spaces.

2018-05-11 15:29 UTC, ryansb commented on docs/docsite/rst/scenario_guides/guide_alicloud.rst
> +If ``count_tag`` is not specified, ``coun`` would use ``instance_name`` to create specified number of instances.
s/coun/count/

2018-05-11 15:29 UTC, ryansb commented on lib/ansible/modules/cloud/alicloud/alicloud_instance_facts.py
> +    if ids and (not isinstance(ids, list) or len(ids)) < 1:
This conditional seems incorrect - parenthesis are closed too early. 

I think it should read `if ids and (not isinstance(ids, list) or len(ids) < 1):`

2018-05-11 15:29 UTC, ryansb commented on lib/ansible/modules/cloud/alicloud/alicloud_instance_facts.py
> +    if names and (not isinstance(names, list) or len(names)) < 1:
Same here

2018-05-11 15:29 UTC, ryansb commented on lib/ansible/modules/cloud/alicloud/alicloud_instance.py
> +        - Maximum outgoing bandwidth to the public network, measured in Mbps (Mega bit per second).
"Megabits per second"

2018-05-11 15:29 UTC, ryansb commented on lib/ansible/modules/cloud/alicloud/alicloud_instance.py
> +    host_name:
Please add an alias for "hostname"

2018-05-11 15:29 UTC, ryansb commented on lib/ansible/modules/cloud/alicloud/alicloud_instance.py
> +        - The password to login instance. After rebooting instances, the modified password would be take effect.
`modified password will take effect`

2018-05-11 15:29 UTC, ryansb commented on lib/ansible/modules/cloud/alicloud/alicloud_instance.py
> +      choices: ['join', 'leave']
Adding/removing security groups is usually implemented like this:

```
groups:
- {identifier of security group}
- {identifier of second security group}
purge_groups: true/false
```
That way if a user specifies a set of groups, the instance will be added if they are not already on it. If they want to leave groups, they specify the ones that must remail and then set `purge_groups: true`. For an example, see the `ec2_group` module.

2018-05-11 18:10 UTC, acozine requested changes
Thanks for submitting a guide for the Alibaba Cloud modules. I reviewed the Scenario Guide and pushed some changes to https://github.com/xiaozhu36/ansible/pull/1.

2018-05-14 14:35 UTC, acozine approved these changes

2018-05-15 01:25 UTC, xiaozhu36 commented
HI @ryansb @acozine Thanks for your review and I have improved the pr according to your suggestion. Please check them.

Regards,
He Guimin

2018-10-09 09:58 UTC, xiaozhu36 commented
HI @ryansb This PR has opened more than one year and the module version has modified from 2.5 to 2.6. Now, the CI error show me 
```
ERROR: lib/ansible/modules/cloud/alicloud/ali_instance.py:0:0: E307 version_added should be 2.8. Currently 2.7 (75%)
```
Please let me know when it can be merged?

2018-10-17 12:38 UTC, ryansb reviewed
Needs rerun in CI and update for version_added to 2.7

2018-10-18 03:11 UTC, xiaozhu36 commented
HI @ryansb It seems like `2.7` does not work. What I should do?

2018-10-18 14:08 UTC, acozine commented on lib/ansible/modules/cloud/alicloud/ali_instance_facts.py
> +version_added: "2.7"
@xiaozhu36 you should update this version number from 2.7 to 2.8.

We have already released 2.7, so this module will be added as of version 2.8.

2018-10-18 14:13 UTC, acozine commented on docs/docsite/rst/dev_guide/developing_module_utilities.rst
> +- alicloud_ecs.py - Definitions and utilities for modules working with Alibaba Cloud ECS.
This new line should be the only change to the `docs/docsite/rst/dev_guide/developing_module_utilities` file. Please remove/undo the other changes.

2018-10-20 09:21 UTC, xiaozhu36 commented on lib/ansible/modules/cloud/alicloud/ali_instance_facts.py
> +version_added: "2.7"
Done. When release the version 2.8?

2018-10-20 09:24 UTC, xiaozhu36 commented on docs/docsite/rst/dev_guide/developing_module_utilities.rst
> +- alicloud_ecs.py - Definitions and utilities for modules working with Alibaba Cloud ECS.
Done.

2018-10-23 17:27 UTC, ryansb approved these changes

2018-10-23 18:02 UTC, merged