Improve default values and choices in module docs
ansible/ansible pull request #36901
Opened 2018-03-01 11:49 UTC by dagwieers

##### SUMMARY
So currently we show defaults and choices in separate columns.

For each parameter we have
- Mostly empty default and choices cells
- A list of choices and a separate default value
- Only a default value

So there's a lot of space being wasted on empty cells.
We can do this better.

Before:
![screenshot from 2018-03-01 12-47-38](https://user-images.githubusercontent.com/388198/36843304-d15abcee-1d4e-11e8-8849-f44fd9acd1e8.png)

After:
![screenshot from 2018-03-01 12-42-27](https://user-images.githubusercontent.com/388198/36843254-a4109344-1d4e-11e8-846f-9477fc4a3f9a.png)

##### ISSUE TYPE

 - Feature Pull Request
 - Docs Pull Request

##### COMPONENT NAME
module docs

##### ANSIBLE VERSION
v2.5

2018-03-01 14:29 UTC, jhawkesworth commented
I like this.
I'd maybe consider having column titled Choices / Defaults.
I am out of touch with current practice regarding accessibility so not sure about use of colour, although the use of the <- I guess probably mitigates that.

2018-03-01 14:57 UTC, kbreit commented
`<-` does a good job of showing default, but I'd think even (default) after the default value would do the job.

2018-03-01 14:57 UTC, dagwieers commented
@jhawkesworth Originally that is what I did, but Choices / Defaults was too big for the column header. And what's more, it didn't clearly say when something was a list of choices, or a default value. So that's why I decided to repeat **Choices**. It was a deliberate decision after seeing all the different possibilities.

2018-03-01 14:59 UTC, dagwieers commented
@kbreit Right, but it takes a lot more space. Especially when you have longer items. I'd like to hear for other means of doing it though. I considered very small superscript "default". Maybe there's a good emoji for this ? ;-)

2018-03-01 16:42 UTC, dharmabumstead requested changes
Looks good, but make the column header “Choices” rather than “Default”, and don’t add the word “Choices” to the individual rows.

2018-03-01 16:49 UTC, dagwieers commented
> Looks good, but make the column header “Choices” rather than “Default”, and don’t add the word “Choices” to the individual rows.

That is a problem, because the column doesn't always display choices. That is why we deemed it better to show the value as default as-is, and add Choices when the content actually is a list to choose from.

2018-03-01 17:45 UTC, dagwieers commented
I also have to add that I am currently working on cleaning up the module docs wrt. parameter values, and plan to tackle the **Return Values** section to avoid this mess: http://docs.ansible.com/ansible/devel/modules/win_disk_facts_module.html

I already have something basic there.

2018-03-01 18:58 UTC, nitzmahone commented
Thanks so much for your efforts here @dagwieers! I'm a big +1 to this (or some form of it) and the other changes you've been doing on the module docs formatting lately. I've always disliked the sparsity/wasted space in the tabular views for modules, so these are all huge improvements in my book.

2018-03-01 19:06 UTC, nitzmahone approved these changes

2018-03-01 22:43 UTC, dharmabumstead commented
Well, the column doesn't always include *defaults*, either. And the blank column there makes it kind of look like the docs are incomplete and waste more space.

A suggestion: how about we do away with the middle column altogether? Make the columns just "Name" (which still includes the "Required" flag if necessary) and "Description", with the information in the "Description" column organized something like this (using the "Method" parameter above as an example): 

DESCRIPTION
--------------------------------

The HTTP method of the request.

**Type:** string

**Valid values:** delete | get | post

**Default:** get

**Constraints:** (if any)

**Example:** (optional)

The advantage of this is that we have a lot more *vertical* space to work with than horizontal, which we are sometimes wasting with blank columns for items that don't have defaults. It also gives the module author a little bit more breathing room to work with for more robust descriptions, examples notes, whatever.

Amazon Web Services does this for their API docs (although they use a third column for "Required", which we don't need), and I think it's a little bit easier to implement and to use.

2018-03-05 21:11 UTC, dagwieers commented
So is this going in v2.5 or not ?

2018-03-05 22:10 UTC, dharmabumstead commented
Thanks for your contributions, @dagwieers! I've requested changes above. Please address them and we can consider this for 2.5.

2018-03-06 00:47 UTC, dagwieers commented
@dharmabumstead Ok, I'll put it on tomorrow's core meeting to see what others think is the best option forward.

2018-03-06 14:27 UTC, cldeluna commented
For what its worth I've always found the three columns extremely clear with respect to options, default value, and required.  If the price for that is some white space its well worth it.  It tells me exactly what I need to know.  Is it required or optional, what is the default value, if any, and what are the various parameters I can use and what do they mean.

If I had to find an area in the documentation that needed work it would be in the examples.   This is something I experienced myself and a comment I hear fairly often from students and clients.

They are adequate for those already familiar with Ansible as they assume a great deal.  For beginners they often lead to confusion.  I know its challenging. You can't repeat everything so you have to assume some knowledge but I think today many of the Examples can fall short of being helpful.   What I always wanted to see was a complete playbook with the example to re-enforce the concept of a playbook and show how to use this particular module with various options.   I realize that may be to much but in the interest of having documentation that facilitates use and adoption might be worth considering.  

I'll tell you..when I read this it struck me as fixing something that's not really broken.  Don't underestimate the value of that white space in terms of providing clarity.  And if its that big of an issue then the solution provided by @dharmabumstead is a much better option than smushing everything into one column that does not even have a proper heading.   I do feel that is step backwards in clarity.  Is the white pace really that onerous?

2018-03-06 15:27 UTC, dagwieers commented
@cldeluna We added an "Edit on GitHub" button at the top of module docs so people can propose improvements with a single click. So if you or your students have specific changes they want to contribute to clear up any confusion, that should be a lot easier.

Feel free to encourage this during courses, so we don't waste any opportunities to learn from new users !

2018-03-06 19:34 UTC, gundalow approved these changes
I'm happy with this as is. I think it's a good improvement over what we have.
I'm not personally a fan of the AWS layout.

2018-03-06 19:46 UTC, dagwieers commented
So the problem is rendering "Defaults and Choices" and I suspect here it gets worse because I have a <div><div color=blue>Defaults</div><div>and <br/>Choices</div></div>.
![screenshot from 2018-03-06 20-43-59](https://user-images.githubusercontent.com/388198/37054533-691cdc18-217f-11e8-8225-035557e3c33e.png)

Will try again doing it differently, without <br/>

2018-03-06 19:57 UTC, dagwieers commented
So this was my original problem, which also happened when the content overrun the column width.
![screenshot from 2018-03-06 20-56-33](https://user-images.githubusercontent.com/388198/37055027-efb1442a-2180-11e8-88bf-fc16d1f4bb13.png)

2018-03-06 20:06 UTC, dagwieers commented
This is with `<br>`s` added in every other cell.
![screenshot from 2018-03-06 21-06-04](https://user-images.githubusercontent.com/388198/37055540-4a584526-2182-11e8-9dc6-d34f9416b413.png)

2018-03-06 20:35 UTC, dagwieers commented
So @bcoca's suggestion worked !
![screenshot from 2018-03-06 21-34-43](https://user-images.githubusercontent.com/388198/37056987-4129faa4-2186-11e8-9fba-ed562bd945db.png)

2018-03-06 21:06 UTC, dharmabumstead commented
Please remove the redundant “Choices” from inside the column and we’re good to go here.

2018-03-06 21:19 UTC, dagwieers commented
@abadger Your opinion would be appreciated too.

2018-03-07 04:46 UTC, abadger commented
Those who attended the Core Team IRC meeting today took a look at this and came to the conclusion that if we're putting choices into that column then it needs to have the Choices text inside the fields.  Otherwise people reading the documentation can't tell that it is a list of potential choices.

2018-03-07 15:28 UTC, abadger approved these changes
One of the results of today's meeting was to ask people to be explicit about approving or disapproving of this change.  +1 from me.

2018-03-08 18:46 UTC, dharmabumstead approved these changes

2018-03-08 18:47 UTC, dharmabumstead commented
Thanks @dagwieers!

2018-03-08 18:48 UTC, merged