Add eos_smoke integrtion tests
ansible/ansible pull request #36957
Opened 2018-03-02 19:17 UTC by newswangerd

##### SUMMARY

Adds  eos_smoke integration tests

covers:
module_utils:

    network.common.utils
    network.common.config
    network.eos

plugins:

    plugins.action.eos
    plugins. cliconf.eos
    plugins.terminal.eos

Coverage reports: https://newswangerd.github.io/eos/

##### ISSUE TYPE

 - Test Pull Request

##### COMPONENT NAME

##### ANSIBLE VERSION

```
ansible 2.6.0 (eos_smoke 3d82f1a6e7) last updated 2018/03/02 14:14:32 (GMT -400)
  config file = None
  configured module search path = [u'/Users/david/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/david/code/ansible/lib/ansible
  executable location = /Users/david/code/ansible/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### ADDITIONAL INFORMATION

```

```

2018-04-04 15:08 UTC, ganeshrn commented on test/integration/targets/eos_smoke/tests/eapi/common_utils.yaml
> +# FIXME: uncomment when https://github.com/ansible/ansible/issues/36919 is fixed
The issue is fixed, so as per comment the test should be uncommented.

2018-04-04 15:09 UTC, ganeshrn requested changes
Can you also add test cases related to become and unbecome

2018-04-04 16:27 UTC, newswangerd commented
the unbecome/become tests will break until #38284 is fixed.

2018-04-05 12:24 UTC, gundalow requested changes
`become` & `unbecome` requires `connection: network_cli`.

There isn't an equivalent for `connection: local`, you can only `authorize`, no `unauthorize`

2018-04-05 17:09 UTC, gundalow approved these changes

2018-04-06 03:19 UTC, ganeshrn approved these changes

2018-04-06 10:45 UTC, trishnaguha approved these changes

2018-04-06 12:16 UTC, merged

2018-04-06 12:35 UTC, newswangerd commented
backport: #38397