Validate SSL in panos_import
ansible/ansible pull request #36972
Opened 2018-03-04 01:57 UTC by kbreit

##### SUMMARY
Bug #36936 states `panos_import` should validate SSL connections to avoid man in the middle attacks.

Fixes #36936 
##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
panos_import

##### ANSIBLE VERSION
```
ansible 2.6.0 (panos/bug-36936 67c27ef877) last updated 2018/03/03 19:53:31 (GMT -500)
  config file = None
  configured module search path = ['/Users/kbreit/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/kbreit/Documents/Programming/ansible/lib/ansible
  executable location = /Users/kbreit/Documents/Programming/ansible/bin/ansible
  python version = 3.5.4 (default, Feb 25 2018, 14:56:02) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### ADDITIONAL INFORMATION
This should likely be back ported to previous versions since the code seems to be the same.

No difference in output

2018-03-04 02:06 UTC, kbreit commented
Note to reviewers. This changes default behavior from false to true. It is a much better default but may break existing plays.

2018-03-04 09:45 UTC, gundalow requested changes

2018-03-04 09:45 UTC, gundalow commented on lib/ansible/modules/network/panos/panos_import.py
> +            - Whether or not certificates should be validated
Please change to
If C(no), SSL certificates will not be validated. This should only set to no used on personally controlled sites using self-signed certificates.

2018-03-04 09:45 UTC, gundalow commented on lib/ansible/modules/network/panos/panos_import.py
> +        default: True
Yes

2018-03-04 13:55 UTC, kbreit reviewed
Changes applied

2018-03-05 18:05 UTC, kbreit commented
All requested changes should be integrated. It's now just a question of whether we should change the default to validate SSL or if staying with 'false' as default makes sense.

2018-03-20 00:59 UTC, kbreit commented
I am going to change to have the default to false to not break backwards compatibility.

If there is still a merge conflict, I’ll need someone to help fix that.

2018-03-20 16:30 UTC, kbreit commented
I've changed my mind and am defaulting this to `on`. Please review. If approved, I'm going to propagate this change to the other PAN modules.

2018-03-20 16:34 UTC, gundalow commented on lib/ansible/modules/network/panos/panos_import.py
> +
Please remove blank line

2018-03-20 16:34 UTC, gundalow commented on lib/ansible/modules/network/panos/panos_import.py
> +        required: false
Please remove `required: false`

2018-03-20 16:34 UTC, gundalow commented on lib/ansible/modules/network/panos/panos_import.py
> +        required: false
Please remove `required: false`

2018-03-20 16:40 UTC, kbreit reviewed
All changes integrated in latest push.

2018-03-21 00:49 UTC, gundalow approved these changes

2018-03-21 00:50 UTC, gundalow commented
@ivanbojer @jtschichold You happy with this change?

2018-03-30 22:43 UTC, ericwb commented on lib/ansible/modules/network/panos/panos_import.py
> +    validate_ssl:
"ssl" is a legacy, deprecated term for TLS. Other modules use "validate_certs" which might be better here.

2018-03-31 19:26 UTC, kbreit reviewed
Makes sense. Changes made.

2018-04-02 02:43 UTC, kbreit commented
Can this be merged?

2018-04-02 05:50 UTC, ericwb commented on lib/ansible/modules/network/panos/panos_import.py
> +    validate_cert:
To be consistent with other modules, this should be validate_certs, not validate_cert.

2018-04-02 05:52 UTC, ericwb commented on lib/ansible/modules/network/panos/panos_import.py
> +            - If C(no), SSL certificates will not be validated. This should only set to no used on personally controlled sites using self-signed certificates.
"This should only set to no used on" - sounds awkward.  I also don't recommend reasons for when to turn this off.  I'd just warn them it's not recommend.   Even personally controlled sites using self-signed certs can fall victim to MITM attacks.

2018-04-02 05:53 UTC, ericwb requested changes
Sorry, couple more changes please.  Thanks for your changes so far.

2018-04-02 13:31 UTC, kbreit reviewed
All changes applied and pushed.

2018-04-02 15:40 UTC, ericwb approved these changes
Looks good to me

2018-04-05 12:29 UTC, gundalow approved these changes

2018-04-05 12:29 UTC, merged

2018-04-05 12:29 UTC, gundalow commented
Thanks, merged into `devel` will be releases in `2.6.0`
Not backporting as it introduces a new option.