use str instead of bytes
ansible/ansible pull request #36995
Opened 2018-03-05 10:02 UTC by RobberPhex

##### SUMMARY
`PEP 461` add `% formating` since python 3.5.
But for python 3.4, `% formating` doesn't support bytes. so just use str for regex.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME

`lib/ansible`

##### ANSIBLE VERSION
branch `stable-2.4` and `python 3.4`

##### ADDITIONAL INFORMATION
error output
```
$ ansible --version
ERROR! Unexpected Exception, this is probably a bug: unsupported operand type(s) for %: 'bytes' and 'bytes'
the full traceback was:

Traceback (most recent call last):
  File "/home/www/release/new-deploy/venv/bin/ansible", line 85, in <module>
    mycli = getattr(__import__("ansible.cli.%s" % sub, fromlist=[myclass]), myclass)
  File "/home/www/release/new-deploy/venv/lib/python3.4/site-packages/ansible/cli/__init__.py", line 38, in <module>
    from ansible.inventory.manager import InventoryManager
  File "/home/www/release/new-deploy/venv/lib/python3.4/site-packages/ansible/inventory/manager.py", line 44, in <module>
    IGNORED_EXTS = [b'%s$' % to_bytes(re.escape(x)) for x in C.INVENTORY_IGNORE_EXTS]
  File "/home/www/release/new-deploy/venv/lib/python3.4/site-packages/ansible/inventory/manager.py", line 44, in <listcomp>
    IGNORED_EXTS = [b'%s$' % to_bytes(re.escape(x)) for x in C.INVENTORY_IGNORE_EXTS]
TypeError: unsupported operand type(s) for %: 'bytes' and 'bytes'
```

2018-03-05 14:34 UTC, bcoca requested changes
3.4 is not on the list of 'supported pythons'

2018-03-05 16:18 UTC, sivel commented
As explained above, python3.4 is not an acceptable python version for running ansible.

In the 2.5 release of ansible, you will not be able to get this far using python 3.4:

```
$ ansible localhost -m ping
ERROR: Ansible requires a minimum of Python2 version 2.6 or Python3 version 3.5. Current version: 3.4.7 (default, Jan  8 2018, 14:59:08) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

2018-03-05 16:18 UTC, closed without merging

2018-03-07 01:56 UTC, RobberPhex commented
Many dists only have python 3.4, such as [`Ubuntu 14.04`](https://packages.ubuntu.com/trusty/python3), [`CentOS 7`](https://centos.pkgs.org/7/forensics-x86_64/python3-3.3.2-12.el7.x86_64.rpm.html)(python3.3).

Why not add python 3.4(3.3) support back?

2018-03-07 02:16 UTC, bcoca commented
There is no 'adding back', we never supported them, we only had Python 2 support. We added 3 support starting at 3.5 because previous 3.x pythons had too many corner cases to deal with.

2018-03-07 02:29 UTC, RobberPhex commented
@bcoca There are many machines running `CentOS 7`, `Ubuntu 14.04`. we drop Python 3.3, 3.4 too early.

In this situation, users have to use Python 2. They cannot migrate to python3. *Are we really want user using Python3?*

2018-03-07 03:06 UTC, bcoca commented
@RobberPhex again, we didnt 'drop' them,  we just never added the code to support it.

IIRC both of those distributions also have python 2 also installed so they should be covered under that.