GCP: Storage Bucket Acccess Control
ansible/ansible pull request #37289
Opened 2018-03-12 06:57 UTC by rambleraptor

##### SUMMARY
Adding support for GCP Storage Bucket Access Controls

(These are ACLs on Storage Buckets)

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
gcp_storage_bucket_access_control

##### ANSIBLE VERSION
```
2.6
```

##### ADDITIONAL INFORMATION
This was autogenerated using [Magic Modules](https://github.com/GoogleCloudPlatform/magic-modules)

2018-03-21 19:26 UTC, ryansb requested changes

2018-03-21 19:26 UTC, ryansb commented on lib/ansible/modules/cloud/google/gcp_storage_bucket_access_control.py
> +    module.fail_json(msg="BucketAccessControl cannot be edited")
How are users supposed to change permissions?

2018-04-12 13:15 UTC, s-hertel approved these changes

2018-04-25 19:30 UTC, ryansb commented on lib/ansible/modules/cloud/google/gcp_storage_bucket_access_control.py
> +    - |
This weird paragraph break is still showing up, can you try regenerating this?

2018-04-25 19:30 UTC, ryansb commented on lib/ansible/modules/cloud/google/gcp_storage_bucket_access_control.py
> +            - |
Same

2018-04-30 17:08 UTC, rambleraptor commented
Fixed doc issues on this PR (and others)!

2018-04-30 18:02 UTC, ryansb approved these changes

2018-04-30 18:03 UTC, merged