Add AWS Inspector Run Module
ansible/ansible pull request #37475
Opened 2018-03-15 15:47 UTC by dennisconrad

##### SUMMARY
Adds AWS Inspector Run Module

##### ISSUE TYPE
 - New Module Pull Request

##### ANSIBLE VERSION
```
ansible 2.4.3.0
```

##### ADDITIONAL INFORMATION
Role for installing AWS Inspector Agents, if required:
https://galaxy.ansible.com/sansible/amazon_inspector_agent/

2018-04-30 13:53 UTC, ryansb requested changes

2018-04-30 13:53 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/inspector_run.py
> +  inspector_run:
I think this `query` function should be separated out into a `_facts` module.

2018-04-30 13:53 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/inspector_run.py
> +      - started
As part of convention for Ansible module UX, we like to have a `present` option that's the default. For example, on the AWS EC2 modules `present` is equivalent to `ensure the instance exists, and if you must create it then do so. If it exists and is stopped, leave it stopped`. For Inspector I'd expect a `present` to start a job from the specified template, unless one exists already and is stopped or running.

2019-09-19 15:04 UTC, gundalow commented
@dennisconrad 
Thank you for your PR.
As part of reviewing the backlog of PRs we are looking at PRs older PRs that haven't been updated in a while

Given that:
* PR hasn't been updated since March 2018
* Updates requested in April 2018
* This is a feature rather than a bug fix

Therefore I'm going to close this.

If you or anyone else wants to continue with this work then please do feel free to create a fresh PR and `@mention` the previous reviewers in here.

2019-09-19 15:04 UTC, closed without merging