Fixes #37330: support subnet can refer nsg in another resource group
ansible/ansible pull request #37627
Opened 2018-03-20 04:01 UTC by yuwzho

##### SUMMARY

Fixes #37330
When creating subnet, it can refer a network security group from another resource group

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

azure_rm_subnet

##### ANSIBLE VERSION

```
2.5
```

##### ADDITIONAL INFORMATION

```

```

2018-03-20 05:15 UTC, yuwzho commented
@jborean93

2018-03-21 03:33 UTC, yuwzho commented
You can try the pull request by installing our ansible role:

```bash
ansible-galaxy install Azure.azure_preview_modules
```

samples you can find under this folder and try it:
https://github.com/Azure-Samples/ansible-playbooks/tree/master/azure_rm_subnet 

There are two ways to refer nsg in other resource group:
* [using the nsg.id](https://github.com/Azure-Samples/ansible-playbooks/blob/master/azure_rm_subnet/sub_with_nsg_in_other_rg1.yml)
* [add `nsg_resource_group` as you suggested](https://github.com/Azure-Samples/ansible-playbooks/blob/master/azure_rm_subnet/sub_with_nsg_in_other_rg2.yml)

Could anyone have a try and give the result in this PR?

2018-03-21 06:04 UTC, yuwzho commented
@jborean93

2018-03-29 07:01 UTC, elsiefore commented
Just used this in my project. Amazing work! Didn't expect this feature can come so quick, it works without any problem for me.

2018-04-10 00:49 UTC, kyliel commented
Wonderful. Thank you @elsiefore for feedback.
@jborean93 and @nitzmahone , could you please review it and get it move forward? Thank you.

2018-04-10 01:53 UTC, nitzmahone commented
Rather than proliferate a bunch of extra "X_resource_group" args to every module where we need to do this (and there are a lot of them), I think there's a better pattern... Anytime we accept a linked resource name, we should be able to accept the URL to the resource as well. The code should examine the value passed and if it parses as a URL, treat it as an absolute resource ID, otherwise, assume it's the name of something in the current resource group (the existing behavior).

Thoughts?

2018-04-10 02:13 UTC, nitzmahone commented
After some discussion with @jborean93 we could also go this route, but we should ensure that for usabiliy, everything follows a pattern with consistent prefixes/suffixes (eg, this one has mismatched prefixes with `security_group_name` and `nsg_resource_group`). So it should either be `security_group_resource_group` (which isn't great either IMO) or we do some aliasing and change the primary name of the other one to `nsg_name` or something.

This might be a good one to discuss next week while we're in Redmond...

2018-04-10 05:42 UTC, zikalino commented
@nitzmahone yes, i think you're right. i was actually thinking about creating a lookup to create resource id string that could be used in such cases

2018-04-10 16:18 UTC, yuwzho commented
@nitzmahone Sure, currently we can accept either an id or name for the resource. The `format_resource_id` method firstly check the whether it is an id or name, if id, return directly. Otherwise, format the resource id:

https://github.com/ansible/ansible/blob/89d6c3658481859d69b3b13ec5a1166fd3f7f963/lib/ansible/module_utils/azure_rm_common.py#L172-L177

The nsg_group just provided another way to user set the resource group.

2018-05-03 01:03 UTC, nitzmahone requested changes
based on discussion in #ansible-azure today, we should remove the new `nsg_resource_group` arg, and change `security_group_name` to just `security_group` (adding an alias to `security_group_name` for backward compatibility). `security_group` will accept either an ID URL for a SG, a name of the SG in the same RG as the subnet/vnet (current behavior), or a sub-dict with `name` and optional `resource_group` keys to specify an SG in another RG.

2018-05-04 11:46 UTC, yuwzho commented
ready_for_review

2018-05-11 06:01 UTC, yuwzho commented
ready_for_review

2018-05-15 02:40 UTC, yuwzho commented
ready_for_review

2018-05-21 02:14 UTC, kyliel commented
@yungez and @zikalino , since this is a bug fix, could you please help have a review first? Thanks.

2018-05-24 00:52 UTC, nitzmahone approved these changes

2018-05-24 01:45 UTC, jborean93 approved these changes
Looks good thanks @yuwzho.

2018-05-24 01:45 UTC, merged