Add support for custom hostname and port in JBoss module
ansible/ansible pull request #37632
Opened 2018-03-20 08:45 UTC by jurikolo

##### SUMMARY
Fixed #26379. Additionally to original:

> Updates JBoss module to support deployment through HTTP management API and JBoss CLI.
> 
> As it currently stands, the module only supports filesystem deployments using the deployment scanner, which is not recommended for production in the latest versions of JBoss/Wildfly. These updates provide more flexibility by supporting deployment through the HTTP management API and the JBoss CLI, either of which is preferred over filesystem deployments.

My commit adds support for hostname and port to CLI deployment method. This might be required when Wildfly is running with port offset and is bind to specific IP address.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
JBoss module

##### ANSIBLE VERSION
```
ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/jurikolo/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Feb 27 2018, 20:43:24) [GCC 7.3.1 20180130 (Red Hat 7.3.1-2)]
```

2018-08-06 21:39 UTC, gundalow requested changes

2018-08-06 21:39 UTC, gundalow commented on lib/ansible/modules/web_infrastructure/jboss.py
> +    version_added: 2.6
`version_added: "2.7`

2018-08-06 21:39 UTC, gundalow commented on lib/ansible/modules/web_infrastructure/jboss.py
> +    version_added: 2.6
`version_added: "2.7`

2018-08-06 21:39 UTC, gundalow commented on lib/ansible/modules/web_infrastructure/jboss.py
> +    version_added: 2.6
`version_added: "2.7`

2018-08-06 21:39 UTC, gundalow commented on lib/ansible/modules/web_infrastructure/jboss.py
> +    version_added: 2.6
`version_added: "2.7`

2018-08-06 21:39 UTC, gundalow commented on lib/ansible/modules/web_infrastructure/jboss.py
> +    version_added: 2.6
`version_added: "2.7`

2018-08-06 21:39 UTC, gundalow commented on lib/ansible/modules/web_infrastructure/jboss.py
>  EXAMPLES = """
Please use `- name:` rather than `# ` comments

2018-08-07 01:09 UTC, jairojunior commented
I created a few JBoss modules a while ago to manage it's configuration, command execution and deployment through Management API a while ago

Newest PR's are #40320 and #43682 . It would be nice if you could take a look.

2018-12-12 12:11 UTC, gundalow commented
@jhoekx @Wolfant @wbrefvem @jairojunior could you please review this JBoss PR?

2018-12-12 12:11 UTC, gundalow approved these changes

2020-08-16 21:05 UTC, closed without merging