Updated win_disk_facts module
ansible/ansible pull request #37798
Opened 2018-03-22 21:06 UTC by marqelme

##### SUMMARY
- Added trimmed option to module win_disk_facts
- Removed required administrator privileges

The trimmed option can be used to reduce the output of the module.
Then only the disk fact details will be displayed but no detailed information about the partitions and volumes of the disk.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
win_disk_facts

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]

```

2018-03-22 22:10 UTC, dagwieers commented
This PR is undoing a lot of things we recently added for the v2.5 release.

I am also not convinced we want an option "trimmed" here. This requires a discussion, both for the reasons as well as what would be an acceptable interface.

2018-03-22 22:11 UTC, dagwieers requested changes

2018-03-22 22:11 UTC, dagwieers commented on lib/ansible/modules/windows/win_disk_facts.py
> +- name: output second disk serial number
This is undoing the example.

2018-03-22 22:11 UTC, dagwieers commented on lib/ansible/modules/windows/win_disk_facts.py
> +        disks:
This is undoing the explicit ansible_disk key.

2018-03-22 22:11 UTC, dagwieers commented on lib/ansible/modules/windows/win_disk_facts.py
> +                    sample: "100GiB"
We wanted raw values on purpose.

2018-03-23 07:43 UTC, marqelme commented
@dagwieers 
Yes, this was a mistake, I have corrected it.

Sure, please discuss this, just thought this option would help because the module creates a lot of output if you have a lot disks, partitions and volumes.

2018-04-21 22:20 UTC, varunchopra commented
Is there a reason we're not treating volumes and disks differently? I thought we arrived at a conclusion over at https://github.com/ansible/ansible/pull/27634 that it's better to create different modules.

IMHO this is way too bloated and all I'm all against the disk_facts module. :/

2018-05-14 12:22 UTC, dagwieers commented
Beware that the deadline for getting new features/modules accepted in [Ansible v2.6 is nearing](https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/roadmap/ROADMAP_2_6.rst#release-schedule), it is set to either 2018-05-17 or 2018-05-25. If you are blocked, or you need feedback, please discuss on IRC channel #ansible-windows or add a comment to [the Windows Working Group meeting agenda](https://github.com/ansible/community/issues/294) to get it resolved.

2018-08-16 09:48 UTC, dagwieers commented
Beware that the deadline for getting new features/modules accepted in [Ansible v2.7 is nearing](https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/roadmap/ROADMAP_2_7.rst#release-schedule), it is set to either 2018-08-23 or 2018-08-30. If you are blocked, or you need feedback, please discuss on IRC channel #ansible-windows or add a comment to the [Windows Working Group meeting agenda](https://github.com/ansible/community/issues/294) to get it resolved.

2018-11-05 17:51 UTC, taschaal commented
I don't see it mentioned anywhere, but this module doesn't appear to work with windows dynamic disks.  Am I correct in that?

2018-11-05 19:17 UTC, marqelme commented
Currently I am not sure if I have tried this.
Have you tried to gather the dynamic disks with the module?
Otherwise I will try it by tomorrow.

Outlook für iOS<https://aka.ms/o0ukef> beziehen

________________________________
Von: taschaal <notifications@github.com>
Gesendet: Montag, November 5, 2018 6:52 PM
An: ansible/ansible
Cc: Marc Tschapek; Author
Betreff: Re: [ansible/ansible] Updated win_disk_facts module (#37798)


I don't see it mentioned anywhere, but this module doesn't appear to work with windows dynamic disks. Am I correct in that?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/ansible/ansible/pull/37798#issuecomment-435969545>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AcZinGMBo-bQXjLEeM4mnE6cJ4jLih4nks5usHr5gaJpZM4S3y46>.

2019-01-17 16:07 UTC, it-praktyk commented
@marqelme, could you consider rebasing your fork? I tried to do that by myself and make PR to your repository but - due to a number of commits - it's impossible (a web browser friezes).

I'm interested to help finalize that update.

2019-01-17 16:54 UTC, it-praktyk commented
@taschaal, @marqelme the issue it's not about dynamic but about the bug #51032.

2019-01-17 22:31 UTC, it-praktyk commented
@taschaal, @marqelme I was wrong, the module doesn't handle dynamic disks - details included in the #51032.

2019-01-31 12:48 UTC, it-praktyk commented
I've analyzed what is the real subject of the proposed change and the resulted JSON files are available [here](https://gist.github.com/it-praktyk/ab42cda9656425d7f5251a98c582bebf) as the gist.

IMHO, that change should be abandoned.

2019-01-31 13:21 UTC, chopraaa commented
I think instead of `trimmed`, we can specify what kind of facts we want, such as volumes or partitions.

```yaml
win_disk_facts:
    type: volume
```

Should return facts relevant only to volumes instead of flooding a single variable with stuff we don't really need.

2019-11-15 00:51 UTC, jborean93 commented
Due to the age of the PR and the conflicts with the win_disk_facts module I am going to close this PR. If you still wish to include this change in some form or another please open a new PR against the latest branch of Ansible.

Really sorry for the delay in getting to these PRs and I am hoping we can be a lot more responsive in the future.

2019-11-15 00:51 UTC, closed without merging