Add OpenNebula one_image module
ansible/ansible pull request #37831
Opened 2018-03-23 13:07 UTC by ilicmilan

##### SUMMARY
Add `one_image` module to manage images on the [OpenNebula](https://opennebula.org/) open source cloud platform.
While we were developing this module we were inspired by Google Cloud and Amazon's EC2 modules, but we also aligned with how OpenNebula works.

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
* one_image

##### ADDITIONAL INFORMATION
We've been using this module in the production for the last 3 months.
We also have integration tests, but they require a running OpenNebula instance, so we will have to discuss how to integrate that with your testing system.

2018-03-29 18:07 UTC, resmo commented on lib/ansible/modules/cloud/opennebula/one_image.py
> +    if action and action == 'list':
a list action or state is something we have accepted in the past, but not anymore for new modules. please create a separate facts module for this functionality.

2018-03-29 18:11 UTC, resmo requested changes
see comment about list functionality inline

2018-04-02 08:20 UTC, resmo approved these changes

2018-04-02 08:37 UTC, resmo approved these changes
As a suggestion, I would skip `action` and move these items to `state`. rename is already idempotent so a  `state=renamed` makes sense to me. `state=clone` would be the only non idempotent "action".

2018-04-02 10:46 UTC, ilicmilan commented
@resmo `state=renamed` would be also non idempotent.
```
- one_image:
  name: app
  state: renamed
  new_name: app-new

- one_image:
  name: app
  state: renamed
  new_name: app-new
```
What would you expect here?

2018-04-02 14:27 UTC, resmo commented
I would implement in a way to look for an image named "app-new" (as the identifier) and if this exists and the image "app" does not exist (anymore), I  would assume the image were already renamed, so `changed=false`.

As a user I would expect that the first task renames the image, the second task would be a no-op `changed=false`. 

I am not sure if this makes sense, any thoughts?

2018-04-02 14:41 UTC, ilicmilan commented
I've asked few more Ansible users for an opinion and they expect that second task will fail, because the image "app" doesn't exist anymore since it's renamed.
For now, I have made it possible to rename the image only with an `id`.

2018-04-02 14:43 UTC, resmo commented
fine for me.

2018-04-02 14:53 UTC, resmo approved these changes
counting 4 community shipits + from me
shipit

2018-04-02 14:58 UTC, merged