Initial CloudGenix Cloud Controller API support
ansible/ansible pull request #37853
Opened 2018-03-23 19:17 UTC by ebob9

##### SUMMARY
Add modules and lookup plugin to support CloudGenix Cloud Controller APIs

First module (cloudgenix_login) and namespace definition.

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
lib/ansible/utils/module_docs_fragments/cloudgenix.py
lib/ansible/module_utils/cloudgenix_util.py
lib/ansible/modules/cloud/cloudgenix
lib/ansible/modules/cloud/cloudgenix/__init__.py
lib/ansible/modules/cloud/cloudgenix/cloudgenix_login.py

##### ANSIBLE VERSION

```
ansible 2.6.0 (devel b8df0db62e) last updated 2018/03/23 11:28:23 (GMT -700)
  config file = None
  configured module search path = ['/Users/aaron/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/aaron/Desktop/longterm_project/ansible/lib/ansible
  executable location = /Users/aaron/Desktop/longterm_project/ansible/bin/ansible
  python version = 3.6.4 (default, Jan  6 2018, 11:51:59) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### ADDITIONAL INFORMATION
New modules and plugins for initial support for configuration of CloudGenix's Cloud Controller APIs.

This pull is the first of 16 new modules and 1 new plugin for support.

Examples and usage included in docstrings.

2018-03-26 18:19 UTC, jchristn commented
ship it

2018-03-26 18:20 UTC, jchristn commented
shipit

2018-03-26 18:22 UTC, DevTazz commented
shipit

2018-03-26 18:23 UTC, mkorenbaum commented
shipit

2018-03-26 18:23 UTC, kevinswartz commented
shipit

2018-03-26 18:25 UTC, rbartosik68 commented
shipit

2018-03-26 18:25 UTC, ebob9 commented
shipit

2018-03-26 18:30 UTC, ybajpai commented
shipit

2018-03-26 18:31 UTC, shbhagat commented
shipit

2018-03-26 18:55 UTC, jaredemendel commented
shipit

2018-03-26 19:54 UTC, sumitgoelpw commented
shipit

2018-03-26 20:29 UTC, kshahnawaz commented
shipit

2018-03-26 20:45 UTC, anish-john commented
shipit

2018-03-26 21:38 UTC, gogofree commented
shipit

2018-03-27 03:34 UTC, akshat91 commented
shipit

2018-03-27 14:38 UTC, bipruitt commented
shipit

2018-03-27 15:59 UTC, n0ahfense commented
shipit

2018-03-27 22:18 UTC, coolcps commented
shipit

2018-11-20 05:58 UTC, Akasurde requested changes
Could you please write integration and/or unit test for this module ? Thanks.

2018-11-20 05:58 UTC, Akasurde commented on lib/ansible/module_utils/cloudgenix_util.py
> +# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
`module_utils` should have BSD license so replace line 2 with

```
#
# Simplified BSD License (see licenses/simplified_bsd.txt or https://opensource.org/licenses/BSD-2-Clause)
```

2018-11-20 05:58 UTC, Akasurde commented on lib/ansible/module_utils/cloudgenix_util.py
> +# Copyright (c) 2018 CloudGenix Inc.
```suggestion
# Copyright: (c) 2018, CloudGenix Inc.
```

2018-11-20 05:58 UTC, Akasurde commented on lib/ansible/module_utils/cloudgenix_util.py
> +# try:
Remove this commented code if not required.

2018-11-20 05:58 UTC, Akasurde commented on lib/ansible/module_utils/cloudgenix_util.py
> +        ssl_verify=dict(type='bool', required=False, default=True),
Could you please rename this parameter to `validate_certs` in order to match every other modules in Ansible ?

2018-11-20 05:58 UTC, Akasurde commented on lib/ansible/module_utils/cloudgenix_util.py
> +        auth_token=dict(aliases=['x_auth_token'], no_log=True),
Use 
```python
from ansible.module_utils.basic import env_fallback
...
auth_token=dict(aliases=['x_auth_token'], no_log=True, fallback=(env_fallback, ['X_AUTH_TOKEN'])),
```

2018-11-20 05:58 UTC, Akasurde commented on lib/ansible/module_utils/cloudgenix_util.py
> +    if not auth_token:
If you use `env_fallback` then you don't require this check.

2018-11-20 05:58 UTC, Akasurde commented on lib/ansible/module_utils/cloudgenix_util.py
> +        if 'TENANT_ID' in os.environ:
Use same `env_fallback` as `X_AUTH_TOKEN`

2018-11-20 05:58 UTC, Akasurde commented on lib/ansible/modules/cloud/cloudgenix/cloudgenix_login.py
> +# Copyright (c) 2018 CloudGenix Inc.
```suggestion
# Copyright: (c) 2018, CloudGenix Inc.
```

2018-11-20 05:58 UTC, Akasurde commented on lib/ansible/modules/cloud/cloudgenix/cloudgenix_login.py
> +version_added: "2.6"
s/2.6/2.8/

2018-11-20 05:58 UTC, Akasurde commented on lib/ansible/modules/cloud/cloudgenix/cloudgenix_login.py
> +short_description: "Login to the CloudGenix API endpoint"
```suggestion
short_description: Login to the CloudGenix API endpoint
```

2018-11-20 05:58 UTC, Akasurde commented on lib/ansible/modules/cloud/cloudgenix/cloudgenix_login.py
> +    - "Login to the CloudGenix API endpoint, to obtain an AUTH_TOKEN for use in later calls"
```suggestion
    - Login to the CloudGenix API endpoint, to obtain an AUTH_TOKEN for use in later calls.
```

2018-11-20 05:58 UTC, Akasurde commented on lib/ansible/modules/cloud/cloudgenix/cloudgenix_login.py
> +            - This is the email of the account to login with
```suggestion
            - The email of the account to login with.
```

2018-11-20 05:58 UTC, Akasurde commented on lib/ansible/modules/cloud/cloudgenix/cloudgenix_login.py
> +            - This is the password of the account to login with
```suggestion
            - The password of the account to login with.
```

2018-11-20 05:58 UTC, Akasurde commented on lib/ansible/modules/cloud/cloudgenix/cloudgenix_login.py
> +            - Base URI of controller to use
```suggestion
            - Base URI of controller to use.
```

2018-11-20 05:58 UTC, Akasurde commented on lib/ansible/modules/cloud/cloudgenix/cloudgenix_login.py
> +    ssl_verify:
Rename this to `validate_certs`

2018-11-20 05:58 UTC, Akasurde commented on lib/ansible/modules/cloud/cloudgenix/cloudgenix_login.py
> +            - Boolean of whether to validate SSL connections
```suggestion
            - Boolean of whether to validate SSL connections.
```

2018-11-20 05:58 UTC, Akasurde commented on lib/ansible/modules/cloud/cloudgenix/cloudgenix_login.py
> +    if not HAS_CLOUDGENIX:
You can move this check to `module_utils` as well.

2018-11-20 05:58 UTC, Akasurde commented on lib/ansible/modules/cloud/cloudgenix/cloudgenix_login.py
> +    return result
Seems to be unreachable code to me.

2018-11-20 05:58 UTC, Akasurde commented on lib/ansible/utils/module_docs_fragments/cloudgenix.py
> +      - CloudGenix API AUTH_TOKEN. If not set, then the value of the X_AUTH_TOKEN environment variable is used.
```suggestion
      - CloudGenix API AUTH_TOKEN. If not set, then the value of the C(X_AUTH_TOKEN) environment variable is used.
```

2018-11-20 05:58 UTC, Akasurde commented on lib/ansible/utils/module_docs_fragments/cloudgenix.py
> +      - Tenant ID to make requests on. If not set, the TENANT_ID environment variable is used if set, otherwise the ID
```suggestion
      - Tenant ID to make requests on. If not set, the C(TENANT_ID) environment variable is used if set, otherwise the ID
```

2018-11-20 05:58 UTC, Akasurde commented on lib/ansible/utils/module_docs_fragments/cloudgenix.py
> +      - Enable strict verification of CloudGenix API SSL Certificate
```suggestion
      - Enable strict verification of CloudGenix API SSL Certificate.
```

2020-08-19 10:13 UTC, Akasurde commented
Please submit a new module request to https://github.com/ansible-collections/community.general. Thanks for your contribution.

2020-08-19 10:13 UTC, closed without merging