add vmware_guest support for multiple cdroms
ansible/ansible pull request #37869
Opened 2018-03-24 09:06 UTC by phemmer

##### SUMMARY
This adds support for multiple cdrom devices with the vmware_guest module.

My use case is to be able to automatically kickstart CentOS VMs. The technique I'm using is the one documented [here](https://medium.com/@jackprice/pushing-kickstarts-with-ansible-122b2cd9c1e) where your first CDROM drive is the installer ISO, and your second CDROM drive is an ISO with a special label that the installer pulls the `ks.cfg` from.

Given that someone wrote an article on exactly what I'm trying to do, as well as #35665 also trying to do the same thing, It seems this is a common use case.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = None
  configured module search path = [u'/Users/phemmer/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/phemmer/ansible-2.5/lib/python2.7/site-packages/ansible
  executable location = /Users/phemmer/ansible-2.5/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

2018-03-24 09:08 UTC, phemmer commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +            for cdrom_params in self.params["cdrom"]:
Contrary to what github indicates, the PR is actually really trivial. It's just the addition of this line, then a reindent of the rest of the function, and substition of `self.params["cdrom"]` with `cdrom_params`.

2018-04-02 16:18 UTC, Akasurde requested changes

2018-04-02 16:18 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +        if "cdrom" in self.params and self.params["cdrom"] is not None:
How about 

```
self.params.get('cdrom', None):
```

2018-04-02 16:18 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +                    self.module.fail_json(msg="cdrom.type is mandatory")
Maybe suggesting existing/available options in error message will be help to end user.

2018-04-02 16:18 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +    - A list of CD-ROMs to configure.
Add a note saying that - `cdrom` accepts a list of CD-ROM configurations from version 2.6

2018-04-15 04:11 UTC, Akasurde commented
@phemmer Any news?

2018-04-15 17:31 UTC, phemmer commented
comments addressed

2018-05-06 23:01 UTC, pdellaert commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +                    # Changing CD-ROM settings on a template is not supported
As per PR #37318, should we actually return a fail here?

2018-08-06 12:25 UTC, closed without merging

2019-01-07 05:12 UTC, Tomorrow9 commented
@phemmer Hi, is there a new PR for this or you just close this one? Thanks.

2019-01-07 13:20 UTC, phemmer commented
No new PR. Just closed.
If someone else wants to take ownership of the code and try to get it released, they are more than welcome to.

2019-01-09 06:46 UTC, Tomorrow9 commented
Ok, we really need this feature to be released, I'll take your code in a new PR. Thanks.