add 'localhost_warning' configuration option
ansible/ansible pull request #37871
Opened 2018-03-24 13:00 UTC by larsks

Add the 'localhost_warning' configuration option. When set to 'false',
this will prevent Ansible from issuing a warning when the inventory is
empty and it is using an implicit inventory with only 'localhost'.

Closes #17086

2018-03-26 09:53 UTC, julienvey requested changes
Much needed feature :D

2018-03-26 09:53 UTC, julienvey commented on lib/ansible/config/base.yml
> +    - By default Ansible will issue a warning when there are no hosts in the in the
small typo `in the in the` instead of `in the`

2018-03-26 17:06 UTC, larsks commented
@julienvey thanks for catching that; fixed!

2018-03-27 12:27 UTC, ryansb commented
@bcoca this is relevant to the empty-set/null host list discussion we had yesterday. Please take a look

2018-03-27 13:36 UTC, bcoca commented
@ryansb, not really, this affects an inventory warning 'empty inventory', the other affects host selection, which happens well after inventory is resolved and is to 'pattern not matched in play'.

2018-03-30 10:00 UTC, julienvey approved these changes

2018-04-09 19:45 UTC, larsks commented
@julienvey Hey, how do we get another reviewer on this before it gets stale again?

2018-04-10 14:30 UTC, larsks commented
That CI failure looks erroneous.

2018-04-24 14:32 UTC, larsks commented
@julienvey @bcoca anybody?

2018-04-24 14:42 UTC, agaffney commented on lib/ansible/config/base.yml
> +  version_added: "2.5"
This should probably be `version_added: "2.6"` now that 2.5 has been released

2018-04-24 15:21 UTC, larsks commented
@agaffney I've updated `version_added`.

2018-04-30 17:27 UTC, merged