add user password lock option to user module
ansible/ansible pull request #37962
Opened 2018-03-26 21:44 UTC by lazouz

##### SUMMARY

This adds password lock feature (lock -l command) tu user module.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
module : user 

##### ANSIBLE VERSION
```
ansible 2.4.3.0
```

##### ADDITIONAL INFORMATION

I have not wrote tests for this feature, because i don't know if it can be useful

2018-03-27 07:18 UTC, Akasurde requested changes

2018-03-27 07:18 UTC, Akasurde commented on lib/ansible/modules/system/user.py
> +            - lock the password (usermod -L ) by adding a '!' at the beggining of the password user entry. This option does not disable the user, only lock the password.
s/beggining/beginning/

2018-03-27 07:18 UTC, Akasurde commented on lib/ansible/modules/system/user.py
> +        version_added: "2.4"
version_added: "2.6"

2018-03-27 09:01 UTC, lazouz commented on lib/ansible/modules/system/user.py
> +            - lock the password (usermod -L ) by adding a '!' at the beggining of the password user entry. This option does not disable the user, only lock the password.
done.

2018-03-27 09:01 UTC, lazouz commented on lib/ansible/modules/system/user.py
> +        version_added: "2.4"
done.

2018-03-27 09:02 UTC, lazouz commented
I did what @ansibot told me :)

2018-03-27 09:40 UTC, lazouz commented
ooops. I fixed.

2018-03-27 09:57 UTC, lazouz commented
now i only need @Akasurde validation ;)

2018-04-04 14:25 UTC, lazouz commented
hello @Akasurde 
I think I've done what you asked for ! 
If you have some time, can you give a glance to the code ?

cheers

2018-04-04 16:02 UTC, Akasurde commented
I will take a look into this tomorrow. You will need one more person to approve to this.

2018-04-13 20:19 UTC, bcoca requested changes

2018-04-13 20:19 UTC, bcoca commented on lib/ansible/modules/system/user.py
> +        default: 'no'
don't default to 'no', otherwise how do you know if user is trying to revert the lock or just didn't specify?

2018-04-13 20:19 UTC, bcoca commented on lib/ansible/modules/system/user.py
> +              This option does not disable the user, only lock the password.
not all platforms implement this, nor this way, just say it will "lock the user's password" and warn that this does not always mean the user cannot login via other methods.

2018-04-13 20:19 UTC, bcoca commented on lib/ansible/modules/system/user.py
> +
```
elif self.password_lock is not None:
    cmd.append('-U')
```
so we can 'unlock' also

2018-04-13 20:19 UTC, bcoca commented on lib/ansible/modules/system/user.py
> +            password_lock=dict(type='bool'),
this does not default to no/false, the 'default' default is `None`, but it is actually what we want, so correct the docs and code as i mentioned above

2018-04-16 12:58 UTC, lazouz commented on lib/ansible/modules/system/user.py
> +            password_lock=dict(type='bool'),
I've made the changes for all of your comments !

2018-04-17 13:19 UTC, lazouz commented
hey @Akasurde @bcoca is everything all right for you now ?

2018-04-17 13:22 UTC, bcoca requested changes

2018-04-17 13:22 UTC, bcoca commented on lib/ansible/modules/system/user.py
> +            cmd.append('-L')
this is incorrect for freebsd, `-L` refers to login class, not password lock, just look at a few lines above

2018-04-17 13:31 UTC, lazouz commented on lib/ansible/modules/system/user.py
> +            cmd.append('-L')
my bad.

2018-04-17 16:27 UTC, lazouz commented on lib/ansible/modules/system/user.py
> +            cmd.append('-L')
I've rewrited the lock/unlock commands for FreeBSD and NetBSD, finally, and updated the doc.

2018-04-18 21:09 UTC, bcoca approved these changes

2018-04-19 05:39 UTC, Akasurde approved these changes
LGTM

2018-04-19 08:33 UTC, lazouz commented
Thank you very much @bcoca @Akasurde for your time, your reviews and your validation !
I was my first contribution to an open source project, I think it won't be the last :) .

2018-04-19 14:07 UTC, bcoca commented
@lazouz just need to fix the CI errors and we can merge this, thank you for contributing!

2018-04-19 14:07 UTC, merged

2018-04-20 02:50 UTC, Akasurde commented
@lazouz Thanks for your contribution.

2018-07-15 23:14 UTC, gaddman commented
Nice update to the module, I've just started using it. Noticed that it's not idempotent though. Do you have plans to add that? Just did some testing and shouldn't take much, something like this (at [line 659](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/user.py#L659)) :
```python
        if self.password_lock and info[1][0] != '!':
            cmd.append('-L')
        elif not self.password_lock and info[1][0] == '!':
            cmd.append('-U')
```

2018-07-18 08:57 UTC, lazouz commented
The problem is : the behavior is different on every Operating System, the solution you have works for linux only. We have to find a solution for FreeBSD, etc.

2018-07-18 11:10 UTC, gaddman commented
Yeah, there's a bit more to it for sure. Just checking [FreeBSD docs](https://www.freebsd.org/cgi/man.cgi?pw(8)), they prepend `*LOCKED*`, so it's still possible there at least. Also, the code I wrote above is missing logic for the case where no password is present. I'll have a bash at writing a PR in the next couple of weeks.