Add NSX-T Logical Switch support in vmware_guest
ansible/ansible pull request #37979
Opened 2018-03-27 07:14 UTC by yasensim

##### SUMMARY
Fixes #37975 

It is a simple change. Previously the module checks:
```
if it is distribute vSwitch portgroup:
    attach to DVS portgroup
else:
    attach to VSS portgroup
```
Now the code looks like:
```
if it is distribute vSwitch portgroup:
    attach to DVS portgroup
elif it is nsx-t logical switch:
    attach to nsx-t logical switch
else:
    attach to VSS portgroup
```

##### ISSUE TYPE
 - Bugfix Pull Request
 

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION

```
(venv) YSIMEONOV-PRO15:ansible ysimeonov$ ansible --version
ansible 2.6.0 (devel b8c8fe079b) last updated 2018/03/27 09:04:41 (GMT +200)
  config file = None
  configured module search path = ['/Users/ysimeonov/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/ysimeonov/commitansible/ansible/lib/ansible
  executable location = /Users/ysimeonov/commitansible/ansible/bin/ansible
  python version = 3.6.4 (default, Mar  1 2018, 18:36:50) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
(venv) YSIMEONOV-PRO15:ansible ysimeonov$
```

##### ADDITIONAL INFORMATION
After amending  vmware_guest.py I tested connecting to nsx-t logical switch and it works.
I also tested connecting to Standard vSwitch portgroup and Distributed vSwitch portgroup, just to ensure that there is no break in the previous behaviour and it works!

2018-03-27 07:28 UTC, Akasurde commented
@yasensim Thanks for this PR. Do you think we can add an integration test for this change ? Ansible uses [vcsim](https://github.com/vmware/govmomi/tree/master/vcsim) for integration tests. You can find existing testcases [here](https://github.com/ansible/ansible/tree/devel/test/integration/targets/vmware_guest/tasks)

2018-03-27 07:29 UTC, Akasurde commented
cc @pdellaert @tchernomax

2018-03-27 07:30 UTC, Akasurde requested changes

2018-03-27 07:30 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +                nic.device.deviceInfo.summary = 'nsx.LogicalSwitch: %s'%(self.cache.get_network(network_name).summary.opaqueNetworkId)
space after % operator

2018-03-27 08:28 UTC, yasensim commented
@Akasurde Unfortunately it will take me too much time to add this integration test as it is not implemented in vcsim. I don't mind working with you or someone else to add this. I am also happy to jump on a webex/zoom to show what constructs NSX adds to vim.network.

I will explain below how it works but we can have an e-meeting for more details.
[vim.Network]
```
'vim.OpaqueNetwork:network-o664'
```
o664 is different for every logical switch.

[vim.Network].summary
```
(vim.OpaqueNetwork.Summary) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   network = 'vim.OpaqueNetwork:network-o664',
   name = 'testLS',
   accessible = true,
   ipPoolName = '',
   ipPoolId = <unset>,
   opaqueNetworkId = '948b328f-2572-4452-8714-9400aa231aef',
   opaqueNetworkType = 'nsx.LogicalSwitch'
}
```
network-o664 is the MOREFF visible in the vCenter
opaqueNetworkId is the NSX specific logical switch UUID
name is the name of the logical switch

In order to connect a VM vNIC to NSX-T Logical Switch I take opaqueNetworkId from [vim.Network].summary and supply it to both nic.device.backing.opaqueNetworkId and nic.device.deviceInfo.summary.

2018-03-29 17:07 UTC, Akasurde commented
@yasensim Is there any simulator or mock server which can emulate NSX-T ?

2018-03-30 07:41 UTC, yasensim commented
@Akasurde  for eventual future nsx-t modules we can works together and find a way to do testing. This PR just allows vCenter to connect VMs to nsx-t logical switches. You can use vcsim for integration tests to check that this PR doesn't break the current functionality. If you are interested to see that connecting to nsx-t switch actually works I can show this over zoom.

2018-04-02 05:02 UTC, Akasurde approved these changes

2018-04-02 09:19 UTC, Akasurde commented
rebuild_merge

2018-04-02 09:35 UTC, merged

2018-04-02 09:41 UTC, Akasurde commented
@yasensim Thanks for your contribution. Look forward for more contribution from your side.