Added support for thin provisioned volumes
ansible/ansible pull request #38140
Opened 2018-03-30 12:39 UTC by remixtj

##### SUMMARY
With the boolean option thin, a volume can be provisioned without space
reservation (thin-provisioning).

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
na_cdot_volume
##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/remixtj/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

```

2018-03-30 13:35 UTC, hulquest commented
LGTM shipit

2018-04-02 14:00 UTC, amit0701 requested changes
It works for changing the volume to thin provisioning..but the doesnt work for vice versa operations 

E.g. 
thin: False
should use space-reserve: volume

2018-04-03 05:42 UTC, remixtj commented
@amit0701 space-reserve: volume is the default at creation time, that's why i wasn't setting any value.

Do you mean instead when updating the volume settings?

2018-04-03 09:02 UTC, remixtj commented
@amit0701 Now you should be able to change the volume setting from thin to thick and vice-versa when you want, instead of only setting at creation time.

2018-04-03 18:21 UTC, amit0701 commented
Thanks @remixtj  ! The feature now seems to be truly idempotent.  shipit

2018-04-04 07:35 UTC, remixtj commented
@hulquest would you mind to review again? there has been significant changes

2018-05-23 16:33 UTC, maxamillion commented
friendly re-ping @hulquest

2018-06-08 15:18 UTC, remixtj commented
ping @hulquest

2018-06-08 15:24 UTC, schmots1 commented
The na_cdot modules are being deprecated.  The na_ontap_volume module already has the ability to thin provision (space_guarantee: none)

2018-06-08 15:26 UTC, schmots1 commented
wontfix
close_me
Changes for a module that has depreciation merged for 2.7 and a replacement module that already does the submitted function.

2018-06-08 15:33 UTC, closed without merging