added password options to unarchive module  issue Fixes #30100
ansible/ansible pull request #38252
Opened 2018-04-04 04:40 UTC by Alexander198961

##### SUMMARY
added password to unarchive module

Fix https://github.com/ansible/ansible/issues/30100

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

unarchive module
##### ANSIBLE VERSION

```
ansible 2.5.0
```

2018-04-17 05:42 UTC, Alexander198961 commented
I have faced  with  issue when on freebsd unzip doesnt have -P password option so i skip test not sure what is the best option in this case

2018-04-26 06:59 UTC, mattclay commented on test/integration/targets/unarchive/tasks/main.yml
> +    - zip_is_installed.failed !=  true and ansible_distribution !=  'FreeBSD'
These tests would be cleaner if in a block or using an include so the conditional on FreeBSD isn't repeated.

2018-04-29 15:53 UTC, Alexander198961 commented
@mattclay I have added include and skip tests if unzip doesnt have -P "password"

2018-04-30 16:54 UTC, mattclay requested changes

2018-04-30 16:54 UTC, mattclay commented on test/integration/targets/unarchive/tasks/main.yml
> +- name: Ensure zip & unzup is present to create test archive (pkg)
This task is unnecessary as it repeats the same task above.

2018-04-30 17:53 UTC, abadger commented
Putting passwords on the CLI is insecure.  Can you handle screenscraping the prompt instead?

2018-04-30 18:11 UTC, mattclay requested changes
@Alexander198961 My apologies for not catching this earlier. I only looked at the tests previously.

2018-04-30 18:11 UTC, mattclay commented on lib/ansible/modules/files/unarchive.py
> +            password=dict(required=False, type='str', default=None),
The password argument needs `no_log=True`. The other args are unnecessary as they are the defaults.

2018-04-30 18:11 UTC, mattclay commented on lib/ansible/modules/files/unarchive.py
> +            cmd.extend(['-P', self.password])
Passing the password on the command line is not secure. Although it's more complex, the module should respond to the password prompt instead.

NOTE: Some platforms, such as FreeBSD, do not support password prompts and instead will display a message such as:  `unzip: Passphrase required for this entry`

2018-05-13 15:26 UTC, Alexander198961 commented
@mattclay I have added is_password_protected bool option and captured password using getpass and did manual testing seems working for me . maybe need to add automation test for this case

2018-05-14 16:51 UTC, mattclay commented
@Alexander198961 When I wrote "the module should respond to the password prompt" I meant that the module should wait for the password prompt from the `unzip` command and then send the password provided by the `password` module parameter.

The sending of the password to `unzip` using the `-P` argument is what is insecure. The passing of the password as a module parameter is safe, as long as `no_log` is used. Your original `password` module parameter was correct, it just needed to be changed to:

```python
password=dict(no_log=True),
```

2018-05-21 02:44 UTC, Alexander198961 commented
is it possible use module like pexpect ?

2018-05-21 17:35 UTC, mattclay commented
@Alexander198961 Using pexepect should be OK as long as it's only imported when using the `password` parameter (and this requirement is documented). We can't add pexpect as a requirement for any existing functionality as that would break backwards compatibility. However, if you can reasonably implement the feature without pexpect that would be better.

2018-05-28 03:55 UTC, Alexander198961 commented
@mattclay I have added pexpect and seems it is working nows

2018-06-13 21:36 UTC, mattclay commented on lib/ansible/modules/files/unarchive.py
> +                return dict(cmd=cmd, rc=82, out=out, err='failed to unzip package')
What is special about `rc=82` here?

2018-06-13 21:39 UTC, sivel requested changes

2018-06-13 21:39 UTC, sivel commented on lib/ansible/modules/files/unarchive.py
> +                self.module.fail_json(msg="The pexpect python module is required for password option")
This `try/except` should be moved to top level imports, and restructured to look like:

```
try:
    import pexpect
    HAS_PEXPECT = True
except ImportError:
    HAS_PEXPECT = False
```

And then in this block, use `if not HAS_PEXPECT:`

2018-06-17 08:21 UTC, Alexander198961 commented
@sivel @mattclay fixed

2018-06-18 16:16 UTC, mattclay requested changes

2018-06-18 16:16 UTC, mattclay commented on lib/ansible/modules/files/unarchive.py
> +                return dict(cmd=cmd, rc=e.errno, out=out, err='failed to unzip package')
Use `out=''` instead of `out=out` since `out` will always be empty.

2018-06-18 16:16 UTC, mattclay commented on lib/ansible/modules/files/unarchive.py
> +            rc = 0
Remove the default values for `out` and `rc` since they're unused (when using `out=''` below).

2018-06-18 16:16 UTC, mattclay commented on test/integration/targets/unarchive/tasks/main.yml
> +  shell: python -c "import pexpect"
Use the `pip` module to install `pexpect` instead of detecting it, otherwise the tests will be skipped in CI.

2018-06-18 16:16 UTC, mattclay commented on test/integration/targets/unarchive/tasks/main.yml
> +  when:   pexpect_is_installed.failed != true and 'zip_is_installed.failed != true' and "'must give decryption password with -P' in unzip_has_modifier_P.stderir"
Use `zip_is_installed is not failed` instead of `zip_is_installed.failed != true`.

There is typo in `unzip_has_modifier_P.stderr`.

2018-09-27 16:49 UTC, Alexander198961 commented
@mattclay  @sivel could you pls review ?

2023-07-13 23:16 UTC, Akasurde commented
Closing as per https://github.com/ansible/ansible/issues/30100#issuecomment-389212612

2023-07-13 23:16 UTC, closed without merging