Adding support for GCP Compute Target Https Proxys
ansible/ansible pull request #38908
Opened 2018-04-17 21:06 UTC by rambleraptor

##### SUMMARY
Adding support for GCP Compute Target Https Proxys

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
gcp_compute_target_https_proxy

##### ANSIBLE VERSION
```
2.6
```

##### ADDITIONAL INFORMATION
This was autogenerated using [Magic Modules](https://github.com/GoogleCloudPlatform/magic-modules)

2018-05-11 17:53 UTC, ryansb requested changes
Since this only has a one-argument difference (SSL cert) from this module https://github.com/ansible/ansible/pull/38622 , is it possible to merge them and distinguish whether to create an HTTP or HTTPS target proxy?

2018-05-16 17:25 UTC, rambleraptor commented
I'd prefer not to merge them. It's going to be very difficult with the code generated approach.

Additionally, these are treated as completely independent objects from GCP's perspective. They use different REST endpoints, different gcloud CLI commands, etc. While the objects are very similar currently, that's an assumption we can't make for the future, since they're considered completely separate resources. My worry is that we create a merged TargetHttp(s) proxy object now and then have to retrain users to think of those resources separately when the APIs inevitably diverge down the line.

2018-05-17 19:16 UTC, ryansb approved these changes

2018-05-17 19:16 UTC, ryansb commented
rebuild_merge

2018-05-17 20:34 UTC, merged