Return correct version on installed VyOS
ansible/ansible pull request #39115
Opened 2018-04-21 08:28 UTC by maugli13

Previously existing regexp will shows only "VyOS" without numeric output of router version.
For example: from  "Version:      VyOS 1.1.6" only VyOS will be written in ansible_net_version variable
For more informative output numeric value should be returned as well

##### SUMMARY
Previously existing regexp will shows only "VyOS" without numeric output of router version.
For example: from  "Version:      VyOS 1.1.6" only VyOS will be written in ansible_net_version variable
For more informative output numeric value should be returned as well

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
vyos_facts

##### ANSIBLE VERSION
```
ansible 2.5.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/murmanov/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### ADDITIONAL INFORMATION
Below you can see before and after outputs

```
ok: [nn-vpn.int] => {
    "ansible_facts": {
        "ansible_net_gather_subset": [
            "neighbors", 
            "default"
        ], 
        "ansible_net_hostname": "nn-vpn", 
        "ansible_net_model": "VMware", 
        "ansible_net_serialnum": "VMware-56", 
        "ansible_net_version": "VyOS"
    }, 
    "changed": false, 
    "invocation": {
        "module_args": {
            "gather_subset": [
                "!config"
            ], 
            "host": null, 
            "password": null, 
            "port": null, 
            "provider": null, 
            "ssh_keyfile": null, 
            "timeout": null, 
            "username": null
        }
    }
}

################# After ####################

ok: [nn-vpn.int] => {
    "ansible_facts": {
        "ansible_net_gather_subset": [
            "neighbors", 
            "default"
        ], 
        "ansible_net_hostname": "nn-vpn", 
        "ansible_net_model": "VMware", 
        "ansible_net_serialnum": "VMware-56", 
        "ansible_net_version": "VyOS 1.1.6"
    }, 
    "changed": false, 
    "invocation": {
        "module_args": {
            "gather_subset": [
                "!config"
            ], 
            "host": null, 
            "password": null, 
            "port": null, 
            "provider": null, 
            "ssh_keyfile": null, 
            "timeout": null, 
            "username": null
        }
    }
}

```

2018-04-21 19:04 UTC, maugli13 commented
Tests in Shippable should be adjusted as well, since they're expecting limited output about VyOS version

2018-04-24 13:41 UTC, webknjaz commented
!component +lib/ansible/modules/network/vyos/vyos_facts.py
-label needs_triage

2018-04-26 06:32 UTC, mattclay commented
CI failure in unit tests: https://app.shippable.com/github/ansible/ansible/runs/62201/3/tests

2018-08-31 01:14 UTC, mattclay commented
CI failure in unit tests: https://app.shippable.com/github/ansible/ansible/runs/81682/4/tests

2018-09-04 06:15 UTC, NilashishC commented
@maugli13 The change looks good to me. Could you also modify the assertions in https://github.com/ansible/ansible/blob/devel/test/units/modules/network/vyos/test_vyos_facts.py so that the tests pass and we can merge it?

2018-09-04 09:52 UTC, NilashishC approved these changes

2018-09-04 09:53 UTC, NilashishC requested changes
Please modify the assertions in the unit tests at https://github.com/ansible/ansible/blob/devel/test/units/modules/network/vyos/test_vyos_facts.py so that CI passes.

2018-09-14 11:56 UTC, NilashishC approved these changes

2018-09-14 16:52 UTC, mattclay commented
Closing and re-opening to trigger CI.

2018-09-14 17:21 UTC, merged