Adding haversine filter
ansible/ansible pull request #39114
Opened 2018-04-21 08:21 UTC by Im0

##### SUMMARY
Haversine is a formula to calculate the great-circle distance between two coordinates.

This will help when wanting to determine the distance between coordinates, especially in a `when:` statement.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME

##### ANSIBLE VERSION

```
ansible 2.6.0 (haversine_filter 1391e2b082) last updated 2018/04/21 18:02:55 (GMT +1100)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/johni/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/johni/ansible/hacking/ansible/lib/ansible
  executable location = /home/johni/ansible/hacking/ansible/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### ADDITIONAL INFORMATION

Example playbook:
```
---
- hosts: localhost
  tasks:
    - name: Haversine distance between two lon/lat co-ordinates
      debug:
        msg: "{{ 'km'|haversine('35.9914928','-78.907046', '-33.8523063', '151.2085984') }}"
    - name: Haversine distance between two lon/lat co-ordinates
      debug:
        msg: "{{ 'm'|haversine('35.9914928','-78.907046', '-33.8523063', '151.2085984') }}"

    - name: Fail due to bad co-ordinate
      debug:
        msg: "{{ 'm'|haversine('a35.9914928','-78.907046', '-33.8523063', '151.2085984') }}"
      ignore_errors: yes

    - name: Fail due to bad distance
      debug:
        msg: "{{ 'z'|haversine('35.9914928','-78.907046', '-33.8523063', '151.2085984') }}"
      ignore_errors: yes

```

And example results:

```
$ ansible-playbook only_filter.yml

PLAY [localhost] *********************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************
ok: [localhost]

TASK [Haversine distance between two lon/lat co-ordinates] ***************************************************************************************************
ok: [localhost] => {
    "msg": "15490.46"
}

TASK [Haversine distance between two lon/lat co-ordinates] ***************************************************************************************************
ok: [localhost] => {
    "msg": "9625.31"
}

TASK [Fail due to bad co-ordinate] ***************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "haversine() only accepts floats: could not convert string to float: a35.9914928"}
...ignoring

TASK [Fail due to bad distance] ******************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "haversine() can only be called with km or m"}
...ignoring

PLAY RECAP ***************************************************************************************************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=0   

```

2018-04-21 11:00 UTC, Im0 commented
Windows windows_2012-R2 appears to be bot_broken ?

2018-04-23 05:18 UTC, itdependsnetworks commented
looks good to me, small potential update:

```
def haversine(measurement, lat1, lon1, lat2, lon2):
    from math import radians, sin, cos, sqrt, asin

    if measurement not in ["m", "k"]:
        raise errors.AnsibleFilterError('haversine() can only be called with km or m')

    diameter = {
        'm': 7917.5,
        'km': 12742}

    try:
        lat1 = float(lat1)
        lon1 = float(lon1)
        lat2 = float(lat2)
        lon2 = float(lon2)
    except ValueError as e:
        raise errors.AnsibleFilterError('haversine() only accepts floats: %s' % str(e))

    try:
        dlat = radians(lat2 - lat1)
        dlon = radians(lon2 - lon1)
        lat1 = radians(lat1)
        lat2 = radians(lat2)

        a = sin(dlat / 2) ** 2 + cos(lat1) * cos(lat2) * sin(dlon / 2) ** 2
        c = 2 * asin(sqrt(a))
    except (ValueError, TypeError) as e:
        raise errors.AnsibleFilterError('haversine() only accepts floats: %s' % str(e))

    return round(diameter[measurement] / 2 * c, 2)
```

With this split, not sure if you need value and type error in the second section.

2018-04-23 12:31 UTC, Im0 commented
Thanks @itdependsnetworks for the feedback.  I think you're right about the second exception, but, I feel nervous about removing it completely.

2018-04-23 20:55 UTC, bcoca commented
just a small nitpick on interface, normally filters operate on data ` varname1|filter(varname2, 'otheroption')` .. by making 'units' the thing you operate on it seems to shift away from normal filter usage.

I would propose  shifting to ` point1|haversine(point2, 'm')` as  it keeps the pattern of existing filters.

2018-04-24 11:12 UTC, Im0 commented
Thanks for the comment @bcoca.

Happy to do that especially if that is expected in a filter.  I originally had it like you suggest, but, felt that if felt/looked strange.  

Do you mind taking a look at a few options below?

**1. Current:**
```
def haversine(measurement, lat1, lon1, lat2, lon2)
 looks like => {{ 'm'|haversine('35.9914928','-78.907046', '-33.8523063', '151.2085984') }}
```

**2. Your proposal:**
```
def haversine(lat1, lon1, lat2, lon2, measurement)
 looks like => {{ '35.9914928'|haversine('-78.907046', '-33.8523063', '151.2085984', 'm') }}
```

**3. Discard the variable (doesn't feel right to me):**
```
def haversine(discard, measurement, lat1, lon1, lat2, lon2)
 looks like => {{ anything|haversine('m', '35.9914928','-78.907046', '-33.8523063', '151.2085984') }}
 ```

**4. Accept in a dict { lat1: y1, lon1: x1, lat2: y2, lon2: x2 } and return a dict with both 'km' and 'm' results:**
```
def haversine(coords)
 looks like => {{ coordinates_dict | haversine }}
```

1. My pref.
2. Happy to change to this or similar.
3. Doesn't change much from existing, but, passing and discarding something doesn't feel right.
4. Looks nice and clean but might be a bit harder to use?

Thanks.

2018-04-24 13:39 UTC, webknjaz commented
!component +lib/ansible/plugins/filter/mathstuff.py
-label needs_triage

2018-04-24 14:16 UTC, bcoca commented
Actually, my proposal was for tuple/list
```
def haversine(point1, point2, measurement)
 looks like => {{ ('35.9914928', '-78.907046')|haversine(('-33.8523063', '151.2085984'), 'm') }}
```
but dict also works

2018-04-24 19:13 UTC, Im0 commented
Detect type sounds good.
```
<bcoca> Im0 you want more reviews aside from  mine?
<Imo> bcoca, no.  All good thanks for your reviews.  I will adjust accordingly.
<Imo> And update PR.
<Imo> bcocac, Dict or list/tuple.. not sure yet.
<bcoca> Imo:  either works for me, or all? detect type
``

2018-04-26 13:55 UTC, Im0 commented
Will probably close this PR and open a new one.  Quite a few commits now.

2018-04-26 14:03 UTC, bcoca commented
no need, we can squash or you can just rebase and force push to the branch

2018-04-26 17:45 UTC, mattclay commented
The `no-assert` sanity failure is valid. The `yamllint` failure is unrelated and has already been fixed. The integration test failure is unrelated.

2018-04-27 12:14 UTC, Im0 commented
@bcoca @mattclay I think/hope I'm done now.  Last test seemed unstable, but, passing.  Is this OK to go in, or, any other suggestions for improvement?  Thanks.

2018-05-02 04:22 UTC, mattclay commented
@Im0 I've restarted the tests.

2018-05-02 10:52 UTC, Im0 commented
Thanks @mattclay .  Shippable seems to be struggling a bit at the moment.

2018-05-02 15:59 UTC, mattclay commented
Tests are passing now.

2019-02-21 17:16 UTC, bcoca requested changes
still not addressed https://github.com/ansible/ansible/pull/39114#issuecomment-383719898

2019-05-01 18:39 UTC, gundalow commented
Interested in what you are using this for...

2019-05-02 08:42 UTC, Im0 commented
G’day @gundalow

A traditional use case maybe to select a bunch of switches/routers within a geographic region based on GPS coordinates in the snmp location on the device.

My non-traditional use case is to tell me weather to drive to work, or, stay and work from home. :). 

Step 1.  Get traffic flow data from google and store in a time series database the average speed of a few routes.

Step 2.  If average speed is x % slower than past x work days, raise a warning.

Step 3.  Collect images of the routes from transport websites within x km’s of my routes... stitch them together and post to slack with info from prior steps.

2019-06-05 18:05 UTC, samccann commented
@Im0 Is it worth adding a little of that use case info to the docs or would anyone familiar with haversine know this already?  Can you also address @bcoca comments as there seems to something still to be done here?

2019-06-06 01:01 UTC, Im0 commented
@samccann  @gundalow I'm going to close this and probably create a galaxy role instead.  Thanks.  (Sorry for keeping this open so long).

2019-06-06 01:01 UTC, closed without merging