Adding slxos_lldp module
ansible/ansible pull request #39259
Opened 2018-04-24 22:52 UTC by bigmstone

##### SUMMARY
This PR adds the `slxos_lldp` module

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
`slxos_lldp`

##### ANSIBLE VERSION
```
ansible 2.6.0 (slxos-lldp 43342bf3d1) last updated 2018/04/24 17:49:06 (GMT -500)
  config file = None
  configured module search path = [u'/Users/mstone/dev/stackstorm/ansible/library']
  ansible python module location = /Users/mstone/dev/stackstorm/ansible/lib/ansible
  executable location = /Users/mstone/dev/stackstorm/ansible/bin/ansible
  python version = 2.7.14 (default, Mar 29 2018, 15:58:25) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### ADDITIONAL INFORMATION
```
⟩ ansible-playbook --ask-pass -i hosts.yml lldp.yml
SSH password:
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/Users/mstone/dev/stackstorm/ansible-slxos/lldp.yml': line 7, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - name: LLDP
      ^ here
```
```
⟩ ansible-playbook --ask-pass -i hosts.yml lldp.yml
SSH password:

PLAY [slx] *********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [LLDP] ********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [dc2leaf2]

PLAY RECAP *********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
dc2leaf1                   : ok=1    changed=1    unreachable=0    failed=0
```

2018-05-03 16:04 UTC, bigmstone commented
@gundalow This PR is ready for merge.

2018-05-03 16:04 UTC, bigmstone commented
@gundalow This PR is ready for merge.

2018-05-03 18:18 UTC, LindsayHill approved these changes

2018-05-10 12:12 UTC, gundalow commented
@bigmstone Can you rebase please

2018-05-14 07:11 UTC, ganeshrn requested changes

2018-05-14 07:11 UTC, ganeshrn commented on lib/ansible/modules/network/slxos/slxos_lldp.py
> +    print(module.params['state'])
Please remove `print` lines

2018-05-14 07:11 UTC, ganeshrn commented on lib/ansible/modules/network/slxos/slxos_lldp.py
> +        print('Nope')
same as above

2018-05-14 07:11 UTC, ganeshrn commented on lib/ansible/modules/network/slxos/slxos_lldp.py
> +        print('Adding the commands, captin')
same as above

2018-05-14 07:11 UTC, ganeshrn commented on lib/ansible/modules/network/slxos/slxos_lldp.py
> +
This should be
```
'supported_by': 'community'
```

2018-05-17 22:02 UTC, bigmstone commented
@ganeshrn print statements removed
@gundalow conflicts resolved

2018-05-18 12:02 UTC, gundalow commented
Hi, 
See if http://docs.ansible.com/ansible/devel/dev_guide/index.html helps with the rebase, thanks in advance.

2018-05-22 10:43 UTC, gundalow commented
@bigmstone Can you please rebase, the merge deadline for new functionality in 2.6 is 2018-05-25 Thanks in advance

2018-05-22 15:17 UTC, bigmstone commented
@gundalow Should be fixed up, thanks.

2018-05-25 13:56 UTC, bigmstone commented
@gundalow @ganeshrn Since this is ready to go and the deadline is today can we get this pushed through?

2018-06-26 14:20 UTC, ganeshrn approved these changes

2018-06-26 15:03 UTC, gundalow commented
rebuild_merge

2018-06-26 16:27 UTC, merged

2018-06-26 16:28 UTC, gundalow commented
Merged into `devel` for release in Ansible 2.7