Integration Tests only: nxos_snmp_contact
ansible/ansible pull request #39318
Opened 2018-04-25 18:20 UTC by saichint

##### SUMMARY

IT cases for nxos_snmp_contact

##### ISSUE TYPE

 - IT Pull Request

##### COMPONENT NAME

nxos_snmp_contact

##### ANSIBLE VERSION

```
ansible 2.6.0 (devel 8c819dd9cb) last updated 2018/03/21 18:16:48 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/agents-ci/ansible/lib/ansible
  executable location = /root/agents-ci/ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### ADDITIONAL INFORMATION

* This PR is for adding IT cases for nxos_snmp_contact
* All tests pass on all platforms.
* There are no code changes.

```
PLAY RECAP *******************************************************************************************************************************************************
camden-nx-2.cisco.com      : ok=122  changed=15   unreachable=0    failed=0
dplus-nx-2.cisco.com       : ok=122  changed=15   unreachable=0    failed=0
evergreen-nx-2.cisco.com   : ok=122  changed=15   unreachable=0    failed=0
freeport-nx-2.cisco.com    : ok=122  changed=15   unreachable=0    failed=0
greensboro-nx-2.cisco.com  : ok=122  changed=15   unreachable=0    failed=0
n3k-173.cisco.com          : ok=123  changed=15   unreachable=0    failed=0
n3x-161.cisco.com          : ok=121  changed=15   unreachable=0    failed=0
n7k-99.cisco.com           : ok=122  changed=15   unreachable=0    failed=0
n7k-j.cisco.com            : ok=122  changed=15   unreachable=0    failed=0
n9k-100.cisco.com          : ok=123  changed=15   unreachable=0    failed=0
n9k-108.cisco.com          : ok=122  changed=15   unreachable=0    failed=0

```

2018-04-26 06:54 UTC, trishnaguha requested changes

2018-04-26 06:54 UTC, trishnaguha commented on test/integration/targets/nxos_snmp_contact/tests/cli/sanity.yaml
> +- import_tasks: "{{ role_path }}/tests/common/sanity.yaml"
This file is not necessary as the logic is handled in tasks/. This will run cli tests twice for both connections.

2018-04-26 06:54 UTC, trishnaguha commented on test/integration/targets/nxos_snmp_contact/tests/nxapi/sanity.yaml
> +---
same like above. This file is not necessary as the logic is handled in tasks/. This will run nxapi tests twice.

2018-04-26 15:20 UTC, saichint commented
@trishnaguha Removed the files which are redundant

2018-04-26 17:02 UTC, trishnaguha approved these changes

2018-04-26 17:02 UTC, merged

2018-05-04 06:56 UTC, trishnaguha commented
cherry-picked to 2.5