New virt_clone module for libvirt cloning capabilities
ansible/ansible pull request #39340
Opened 2018-04-26 01:43 UTC by mrlesmithjr

##### SUMMARY

This module is for a new virt_clone module for cloning libvirt VMs. By
using this module we can easily define a template(src) VM to create a
new VM by cloning. This module is idempotent and is check_mode aware.

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

virt_clone

##### ANSIBLE VERSION

```
ansible 2.5.1
  config file = None
  configured module search path = ['/Users/larry/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.5 (default, Mar 30 2018, 06:42:10) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### ADDITIONAL INFORMATION

Example playbook:
```yaml
---
- hosts:          kvm
  vars:
    vm_template:  ubuntu1604-packer-template
    vms:
      - name:     app01
        state:    started
        template: "{{ vm_template }}"
      - name:     db01
        state:    started
        template: "{{ vm_template }}"
      - name:     lb01
        state:    started
        template: "{{ vm_template }}"
      - name:     web01
        state:    started
        template: "{{ vm_template }}"
  tasks:
    - name:       Cloning VMs
      virt_clone:
        name:     "{{ item['name'] }}"
        state:    "{{ item['state'] }}"
        template: "{{ item['template'] }}"
        uuid:     "{{ item['uuid']|default(omit) }}"
      become:     true
      loop:       "{{ vms }}"
```
Example execution:
```bash
PLAY [kvm] *********************************************************************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************************************************************************************************************************************************************************************
ok: [nas02]

TASK [Cloning VMs] *************************************************************************************************************************************************************************************************************************************************************************************************
ok: [nas02] => (item={'name': 'app01', 'state': 'started', 'template': 'ubuntu1604-packer-template'})
changed: [nas02] => (item={'name': 'app02', 'state': 'started', 'template': 'ubuntu1604-packer-template'})
ok: [nas02] => (item={'name': 'db01', 'state': 'started', 'template': 'ubuntu1604-packer-template'})
ok: [nas02] => (item={'name': 'lb01', 'state': 'started', 'template': 'ubuntu1604-packer-template'})
ok: [nas02] => (item={'name': 'web01', 'state': 'started', 'template': 'ubuntu1604-packer-template'})

PLAY RECAP *********************************************************************************************************************************************************************************************************************************************************************************************************
nas02                      : ok=2    changed=1    unreachable=0    failed=0
```

2018-05-01 04:38 UTC, mrlesmithjr commented
Anything else needed from me in regards to this? Finally got everything sorted out as I had some fun getting all of my rebases completed.

2018-11-15 18:48 UTC, bartekrutkowski commented
@TimothyVandenbrande @UnderGreen @drybjed @flaper87 @helldorado @joshainglis @karmab @machacekondra @mwperina 
What's the status of this PR? Anything keeping it from being accepted?

2018-11-15 21:20 UTC, mrlesmithjr commented
Have wondered the same ;)

2018-12-20 04:34 UTC, Akasurde requested changes

2018-12-20 04:34 UTC, Akasurde commented on lib/ansible/modules/cloud/misc/virt_clone.py
> +# Larry Smith Jr. <mrlesmithjr@gmail.com>
```suggestion
# Copyright: (c) 2017, Larry Smith Jr. <mrlesmithjr@gmail.com>
```

2018-12-20 04:34 UTC, Akasurde commented on lib/ansible/modules/cloud/misc/virt_clone.py
> +# Requirements:
Move this information to notes section, so user will be able to see using `ansible-doc` command. Just like [this](https://github.com/ansible/ansible/blob/0127a75132a6802526997496057235b893dcfcf1/lib/ansible/modules/cloud/vmware/vmware_guest.py#L31)

2018-12-20 04:34 UTC, Akasurde commented on lib/ansible/modules/cloud/misc/virt_clone.py
> +  - "This module creates clones for libvirt."
```suggestion
  - This module creates clones for libvirt.
```

2018-12-20 04:34 UTC, Akasurde commented on lib/ansible/modules/cloud/misc/virt_clone.py
> +version_added: "2.6"
s/2.6/2.8/

2018-12-20 04:34 UTC, Akasurde commented on lib/ansible/modules/cloud/misc/virt_clone.py
> +        - Generates a new guest name, and paths for new storage - default true
```suggestion
        - Generates a new guest name, and paths for new storage - default true.
```

2018-12-20 04:34 UTC, Akasurde commented on lib/ansible/modules/cloud/misc/virt_clone.py
> +        - Allows a pre-defined MAC address to be assigned to the cloned VM
```suggestion
        - Allows a pre-defined MAC address to be assigned to the cloned VM.
```

2018-12-20 04:34 UTC, Akasurde commented on lib/ansible/modules/cloud/misc/virt_clone.py
> +        - If the clone should be present or started - default present
```suggestion
        - If the clone should be present or started - default present.
```

2018-12-20 04:34 UTC, Akasurde commented on lib/ansible/modules/cloud/misc/virt_clone.py
> +        - Will also define the VMs hostname
```suggestion
        - Will also define the VMs hostname.
```

2018-12-20 04:34 UTC, Akasurde commented on lib/ansible/modules/cloud/misc/virt_clone.py
> +    required: true
```suggestion
    required: true
    type: str
```

2018-12-20 04:34 UTC, Akasurde commented on lib/ansible/modules/cloud/misc/virt_clone.py
> +    required: false
```suggestion
    required: false
    type: str
```

2018-12-20 04:34 UTC, Akasurde commented on lib/ansible/modules/cloud/misc/virt_clone.py
> +        - The VM to use as the source (template)
```suggestion
        - The VM to use as the source (template).
```

2018-12-20 04:34 UTC, Akasurde commented on lib/ansible/modules/cloud/misc/virt_clone.py
> +    required: true
```suggestion
    required: true
    type: str
```

2018-12-20 04:34 UTC, Akasurde commented on lib/ansible/modules/cloud/misc/virt_clone.py
> +        - Allows a static UUID to be defined for the VM when cloning
```suggestion
        - Allows a static UUID to be defined for the VM when cloning.
```

2018-12-20 04:34 UTC, Akasurde commented on lib/ansible/modules/cloud/misc/virt_clone.py
> +    required: false
```suggestion
    required: false
    type: str
```

2018-12-20 04:34 UTC, Akasurde commented on lib/ansible/modules/cloud/misc/virt_clone.py
> +    conn = libvirt.open('qemu:///system')
Can we make this configurable ?

2018-12-20 20:08 UTC, mrlesmithjr commented on lib/ansible/modules/cloud/misc/virt_clone.py
> +    conn = libvirt.open('qemu:///system')
Absolutely

2019-05-17 00:23 UTC, mrlesmithjr commented
Are we still waiting for anything else here?

2020-02-27 13:55 UTC, louwrentius commented
One year later and this is still open? Would like to see it accepted.

2020-08-16 20:26 UTC, closed without merging