Setting default for gpgcheck in yum_repository
ansible/ansible pull request #39485
Opened 2018-04-30 05:39 UTC by jtyr

##### SUMMARY

This PR is adding missing default value into the documentation of the `yum_repository` module which was previously removed in the PR #36267. The doc generator assigns `no` value to non-defined `default` so it makes sense to add the default back with the `no` value.

##### ISSUE TYPE
Docs Pull Request

##### COMPONENT NAME
`yum_repository`

##### ANSIBLE VERSION
```
ansible 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Apr 16 2018, 20:08:15) [GCC 7.3.1 20180406]
```

##### ADDITIONAL INFORMATION

None

2018-04-30 05:40 UTC, jtyr commented
@mkrizek FYI

2018-05-02 08:14 UTC, mkrizek reviewed
But this reverts https://github.com/ansible/ansible/pull/36267 where we agreed that `default: no` is confusing, no?

2018-05-02 08:25 UTC, jtyr commented
@mkrizek  Yes, it indeed reverts it. But even if `default: null`, the documentation page shows `no`. So I would prefer to have all the documentation source code reflecting what's actually displayed on the web.

2018-05-04 12:35 UTC, webknjaz commented
@jtyr I'd prefer having documentation generator fixed, because the both doc states don't reflect the real behavior: this option falls back to OS default value, not "yes" or "no". This is not a fix, but replacement of one misleading thing with another.
Also according to the current diff there's no `default: null` currently in `devel`. Do you know when/how it disappeared?

2018-05-04 13:15 UTC, webknjaz requested changes
This is not the right way of fixing the issue: it masks the symptom, while the correct thing to do is to have a generic fix for the root of this problem.

It looks this affected all cases of rendering module arguments marked as `bool` by inconsistently assuming that they should all fall back to `Off` by default. While this doesn't take into account that in real life it's not just representation of On/Off switch, but it can also inherit value from some more generic config.
I'm not sure what is the 100% right fix here, but I assume that we might need to implement a three-state type (`optional_bool`) or modify existing one to accept an explicitly available `inherit` option.

Supposingly it's been broken by series of PRs like #36909 and #36901 by @dagwieers.

2018-05-04 13:32 UTC, jborean93 commented
Looks like the fix is in devel but was never backported to stable-2.5 https://docs.ansible.com/ansible/devel/modules/yum_repository_module.html is showing what I believe to be correct which is the `yes`, `no` options but nothing set as a default.

2018-05-04 13:34 UTC, webknjaz commented
@jtyr still I think we'd accept description improvement explaining what happens in case of default value.

2018-05-09 12:02 UTC, dagwieers commented
@gundalow We fixed the documentation issue in https://github.com/ansible/ansible/pull/37514 but it was reverted, not because it actually fixed something, but because project rules are more important than bugfixes. So the bug is still there.

2018-05-09 12:28 UTC, webknjaz commented
@dagwieers actually we have already discussed this in the internal Slack chat and found out that the bug has been fixed in devel, but bugfix was not backported to stable branches.

2018-09-17 22:30 UTC, acozine commented
The documentation for the `gpgcheck` parameter is boolean with no default in `devel`:
https://docs.ansible.com/ansible/devel/modules/yum_repository_module.html
in 2.6 (still as of today, the `latest` on the docsite): https://docs.ansible.com/ansible/latest/modules/yum_repository_module.html 
However, in 2.5 the documentation shows the `gpgcheck` parameter with a default of `no`:
https://docs.ansible.com/ansible/2.5/modules/yum_repository_module.html

2018-09-18 06:06 UTC, webknjaz commented
@acozine back then, documentation generation framework was unable to recognize the `null` value as unset and was pointing to `no` anyway. The real state of things is that if the user does not set a value, it's not being added to the config generated by this module for target repo. But there's another (global) config, which is generated by the OS vendor/maintainer and when `yum` runs it inherits that value, which is `no` by default in most OSs. So setting the default to `no` is not precisely correct (because the user may change that global config or use some nonstandard OS base with different config).
OTOH setting `null` is desired (and done in new docs, which support this, thanks to @dagwieers), but the renderer doesn't know how to render that correctly.

I would recommend:
1) setting the value to `null`, to match the source from newer versions
2) adding a text description explaining what to expect (https://github.com/ansible/ansible/pull/36267/commits/4455766b29ac0faaadf4cf541725f0b96b38f9e7)

But this still will not fix how it's rendered in docs.

2018-09-18 14:11 UTC, dagwieers commented
So the solution here is to leave out a default for the parameter, because it defaults to `null` anyway.
But if the current document parses `null` as `false`, that is obviously wrong.

However, I don't think it is doing this as we specifically test for `true` or `false` (which was the whole point in adding boolean tests to Jinja upstream). We are using the `sameas` Jinja test in the "plugin" template.

I looked through all modules, and I cannot find a case where a parameter of type `bool` has a value of `null` hardcoded (again, which should not be necessary), but there is a concern that type `bool` implies `choices: [ 'no', 'yes' ]` which `null` obviously isn't part of. But I don't think we want to add `null` to that list (as it would render None in the list).

2018-09-18 14:19 UTC, dagwieers commented
So it would render it like this: (see **use_proxy**)
![screenshot from 2018-09-18 16-17-46](https://user-images.githubusercontent.com/388198/45693920-750e6e00-bb5e-11e8-9c3e-d8e7271cdd01.png)

Which may be intentional, but in my opinion is confusing and unwanted. I noticed we have a few modules who are explicitly adding `default: null` and I allow it (as you can tell) but I think we should do it (in most cases).

2018-09-18 14:29 UTC, dagwieers commented
Not providing a default value will render this like this:
![screenshot from 2018-09-18 16-27-19](https://user-images.githubusercontent.com/388198/45694575-d3881c00-bb5f-11e8-95de-8585b5ac2ce1.png)

Which I think is exactly what one would want. You may want to indicate what happens if the option is left out (i.e. it will not be set, and any pre-existing setting may remain as-is)

2018-09-19 16:33 UTC, acozine commented
If you're following this PR, please review #45796. Closing this PR in favor of the newer one.

2018-09-19 16:33 UTC, closed without merging