Update azure_rm_common.py
ansible/ansible pull request #39547
Opened 2018-05-01 09:43 UTC by scassidy-ukcloud

##### SUMMARY

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

```

##### ADDITIONAL INFORMATION

```
```

2018-05-02 02:52 UTC, yuwzho commented
@scassidy-ukcloud Could you please explain what you want to fix? A user friendly issue title and description is needed. Or directly connect to an existing issue is helpful

2018-05-02 04:18 UTC, mattclay commented
CI failure in test `test/integration/targets/azure_rm_networkinterface/tasks/main.yml:60`:

```
{
    "assertion": "not output.changed", 
    "changed": false, 
    "evaluated_to": false
}
```

2018-05-02 06:35 UTC, Fred-sun commented
@scassidy-ukcloud Thanks for your taking the time to open this issue, In order for the community to handle your issue effectively, We need a bit more information, 
Please set the description of the issue with this template, Thanks!
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

2018-05-02 09:04 UTC, scassidy-ukcloud commented
Comments added properly - sorry these were commented out wrongly. Updated the title too

2018-05-02 09:22 UTC, scassidy-ukcloud-zz commented
credentials file used (sensitive information redacted)
[default]
ad_user=************
password=*********
subscription_id=****************
cloud_environment=***********

2018-05-02 09:22 UTC, scassidy-ukcloud-zz commented
playbook used

---
- hosts: localhost
  vars:
    location: frn00006
    resource_group: SC1
    storage_account: ansiblepocsa
    virtual_network: ansiblevn001
    subnet: ansiblesubnet001
    publicip: ansiblepublicip001
    network_interface: ansibletestnic001
    security_group: ansiblesec001
  tasks:
  - name: Create a resource group
    azure_rm_resourcegroup:
      api_profile: '2017-03-09-profile'
      name: "{{ resource_group }}"
      location: "{{ location }}"
  - name: Create storage account
    azure_rm_storageaccount:
      resource_group: "{{ resource_group }}"
      api_profile: '2017-03-09-profile'
      name: "{{ storage_account }}"
      account_type: Standard_LRS
      location: "{{ location }}"
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ resource_group }}"
      name: "{{ virtual_network }}"
      api_profile: '2017-03-09-profile'
      address_prefixes: "10.10.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: "{{ resource_group }}"
      name: "{{ subnet }}"
      api_profile: '2017-03-09-profile'
      address_prefix: "10.10.0.0/24"
      virtual_network: "{{ virtual_network }}"
  - name: Create public ip
    azure_rm_publicipaddress:
      resource_group: "{{ resource_group }}"
      allocation_method: Static
      api_profile: '2017-03-09-profile'
      name: "{{ publicip }}"
  - name: Create security group that allows SSH
    azure_rm_securitygroup:
      resource_group: "{{ resource_group }}"
      api_profile: '2017-03-09-profile'
      name: "{{ security_group }}"
      rules:
      - name: SSH
        source_address_prefix: '*'
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 101
        direction: Inbound
  - name: Create NIC
    azure_rm_networkinterface:
      resource_group: "{{ resource_group }}"
      name: "{{ network_interface }}"
      virtual_network: "{{ virtual_network }}"
      api_profile: '2017-03-09-profile'
      ip_configurations:
      -  name: SC
         public_ip_address_name: "name1"
         primary: True
      subnet: "{{ subnet }}"
      public_ip_name: "{{ publicip }}"
      security_group: "{{ security_group }}"
  - name: Create virtual machine
    azure_rm_virtualmachine:
      api_profile: '2017-03-09-profile'
      resource_group: "{{ resource_group }}"
      name: ansibletestvm001
      vm_size: Standard_D1_v2
      storage_account: "{{ storage_account }}"
      admin_username: ukcloudadmin
      admin_password: Password123!
      network_interfaces: "{{ network_interface }}"
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '6.9'
        version: 6.9.20180105

2018-05-03 05:44 UTC, yuwzho commented on lib/ansible/modules/cloud/azure/azure_rm_networkinterface.py
> -            primary=config.primary,
I think this is duplicate fix of #39213

2018-05-03 05:45 UTC, yuwzho requested changes

2018-05-03 05:45 UTC, yuwzho commented on lib/ansible/modules/cloud/azure/azure_rm_networkinterface.py
> -            primary=config.primary,
I think this is duplicate fix of #39213

2018-05-03 08:51 UTC, scassidy-ukcloud commented
I am happy to say the changes in azure_rm_networkinterface.py are a duplicate of pull request #39213 but I would like the changes in this pull request for azure_rm_common.py to be still merged please.
Thanks
Steve

2018-05-03 08:56 UTC, yuwzho commented
@scassidy-ukcloud Yes, I think the azure_rm_common's change is ok for me. But the network interface may raise other problem since I change the value at the right of `==`, you change the left side, the conditional check will be failed again 😄 Would you mind leaving your azure_rm_common change only?

2018-05-03 09:00 UTC, scassidy-ukcloud commented
Can I remove that file from the pull request as I cannot see any obvious way of doing it? I am not very experienced with pull requests :-)

2018-05-08 08:34 UTC, scassidy-ukcloud commented
Hi,
Is there an easy way to remove the file from the pull request as the only way I can see is by cancelling the pull request and creating a new one - I do not really want to go down that road as we will loose the history of comments that is on this pull request?

Many Thanks

Steve

2018-05-08 08:42 UTC, yuwzho commented
@scassidy-ukcloud You can simply add the line back and make a new commit 😄

2018-05-08 08:45 UTC, scassidy-ukcloud commented
Ok will do now

Thanks

Steve



Steve Cassidy - Cloud Native Infrastructure Engineer
scassidy@ukcloud.com
+441252 936253 / +447741 333654
www.ukcloud.com
A8, Cody Technology Park, Ively Road, Farnborough, GU14 0LX
Notice: This message contains information that may be privileged or confidential and is the property of UKCloud Ltd. It is intended only for the person to whom it is addressed. If you are not the intended recipient, you are not authorised to read, print, retain, copy, disseminate, distribute, or use this message or any part thereof. If you receive this message in error, please notify the sender immediately and delete all copies of this message. UKCloud reserves the right to monitor all e-mail communications through its networks. UKCloud Ltd is registered in England and Wales: Company No: 07619797. Registered office: Hartham Park, Hartham, Corsham, Wiltshire SN13 0RP.
From: Yuwei Zhou [mailto:notifications@github.com]
Sent: 08 May 2018 09:44
To: ansible/ansible <ansible@noreply.github.com>
Cc: Steve Cassidy <scassidy@ukcloud.com>; Mention <mention@noreply.github.com>
Subject: Re: [ansible/ansible] Azure Module Fixes with primary field and base-url (#39547)


@scassidy-ukcloud<https://github.com/scassidy-ukcloud> You can simply add the line back and make a new commit 😄

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/ansible/ansible/pull/39547#issuecomment-387329771>, or mute the thread<https://github.com/notifications/unsubscribe-auth/Aj2TtvRwVaPjeygdkWzAoXw3WGXoxiI8ks5twVrAgaJpZM4TtwYR>.

2018-05-08 08:51 UTC, scassidy-ukcloud commented
I have done that - does it looks OK to you as the file is still showing as changed?

Thanks

Steve

2018-05-08 09:00 UTC, yuwzho commented
@scassidy-ukcloud You need to push it. `git push`

2018-05-08 09:05 UTC, scassidy-ukcloud commented
changes are on the github server see the following

https://github.com/scassidy-ukcloud/ansible/commits/devel/lib/ansible/modules/cloud/azure/azure_rm_networkinterface.py

2018-05-08 09:10 UTC, scassidy-ukcloud commented
I have two pull requests for the same file - I think it is probably best for me to close my two pull requests (this one and the other one I created) and create one consolidated pull request.

2018-05-08 09:34 UTC, scassidy-ukcloud commented
Thanks for all your help but I have created a new pull request that covers what I had in multiple pull requests – the new ID is #39850

Existing ones will be closed in favour of the new one.



Steve Cassidy - Cloud Native Infrastructure Engineer
scassidy@ukcloud.com
+441252 936253 / +447741 333654
www.ukcloud.com
A8, Cody Technology Park, Ively Road, Farnborough, GU14 0LX
Notice: This message contains information that may be privileged or confidential and is the property of UKCloud Ltd. It is intended only for the person to whom it is addressed. If you are not the intended recipient, you are not authorised to read, print, retain, copy, disseminate, distribute, or use this message or any part thereof. If you receive this message in error, please notify the sender immediately and delete all copies of this message. UKCloud reserves the right to monitor all e-mail communications through its networks. UKCloud Ltd is registered in England and Wales: Company No: 07619797. Registered office: Hartham Park, Hartham, Corsham, Wiltshire SN13 0RP.
From: Yuwei Zhou [mailto:notifications@github.com]
Sent: 08 May 2018 10:01
To: ansible/ansible <ansible@noreply.github.com>
Cc: Steve Cassidy <scassidy@ukcloud.com>; Mention <mention@noreply.github.com>
Subject: Re: [ansible/ansible] Azure Module Fixes with primary field and base-url (#39547)


@scassidy-ukcloud<https://github.com/scassidy-ukcloud> You need to push it. git push

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/ansible/ansible/pull/39547#issuecomment-387334768>, or mute the thread<https://github.com/notifications/unsubscribe-auth/Aj2TtjoWrfVbh3fqMgZEOuL533KvTzjHks5twV7egaJpZM4TtwYR>.

2018-05-08 09:34 UTC, closed without merging