Update ios_logging.py
ansible/ansible pull request #39621
Opened 2018-05-02 17:42 UTC by smolz

When calling get_capabilities(module), it is get back a dictionary that does not contain `network_os_version` but `network_os`

##### SUMMARY

##### ISSUE TYPE

 - Feature Pull Request
 - New Module Pull Request
 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME

##### ANSIBLE VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

2018-05-10 00:47 UTC, mattclay commented
CI failure in unit tests: https://app.shippable.com/github/ansible/ansible/runs/63528/3/tests

2018-05-10 08:20 UTC, trishnaguha commented
@smolz I think this is regex issue in cliconf plugin.

get_capabilities returns network_os_version on our lab instance
 `device_info={u'device_info': {u'network_os': u'ios', u'network_os_hostname': u'an-ios-02', u'network_os_model': u'IOSv', u'network_os_version': u'15.6(2)T'}, u'network_api': u'cliconf', u'rpc': [u'get_config', u'edit_config', u'get_capabilities', u'get']}`

Please share `show version` output of your ios device.

2018-05-10 08:23 UTC, trishnaguha requested changes
Please check https://github.com/ansible/ansible/pull/39621#issuecomment-387986480

2018-05-10 17:12 UTC, smolz commented
I think you are correct.

I have attached 3 files, 2 that work that are from a hardware 3850, and IOSv L3 router and 1 not working.  The one that doesnt work is what I was running my testing against which is a IOSv L2 switch which is what I was basing my testing on.

[working_3850.txt](https://github.com/ansible/ansible/files/1992542/working_3850.txt)
[NOT_working_iosv_l2.txt](https://github.com/ansible/ansible/files/1992543/NOT_working_iosv_l2.txt)
[working_iosv_l3.txt](https://github.com/ansible/ansible/files/1992544/working_iosv_l3.txt)

2018-05-14 07:10 UTC, closed without merging

2018-05-14 07:10 UTC, trishnaguha commented
@smolz Thanks for your PR. The issue is fixed by the PR https://github.com/ansible/ansible/pull/40066 and will be cherry-picked for next maintenance release 2.5.3.
Hence closing this one.