yum: Parse also obsoleted packages
ansible/ansible pull request #40001
Opened 2018-05-11 08:34 UTC by machacekondra

##### SUMMARY

Fixes: https://github.com/ansible/ansible/issues/39978

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

yum

##### ANSIBLE VERSION

```
2.5.2
```

##### ADDITIONAL INFORMATION

```

```

2018-05-11 08:45 UTC, mkrizek commented on lib/ansible/modules/packaging/os/yum.py
> +        if '*' in line or len(line) not in [3, 6] or '.' not in line[0]:
Can you also mention what the 6 means in the comment above, please?

2018-05-11 08:59 UTC, mkrizek requested changes
Unit tests failed, looks like tests for obsolete packages are already in `test/units/modules/packaging/os/test_yum.py`.

2018-05-11 09:31 UTC, machacekondra commented
The unit test says that the obsoleted packages shouldn't be part of the updated packages. But we need to handle those somehow, as it's valid use case there is some package obsoloting another we need to perform system update.

2018-05-14 13:44 UTC, mwperina commented
> The unit test says that the obsoleted packages shouldn't be part of the updated packages. But we need to handle those somehow, as it's valid use case there is some package obsoloting another we need to perform system update.

Ondro could you fix (or remove if not possible) those tests? We need to handle this valid use case

@machacekondra

2018-07-18 19:51 UTC, maxamillion commented
@machacekondra any update here?

2018-08-15 10:43 UTC, closed without merging