Add flatpak_remote module
ansible/ansible pull request #40189
Opened 2018-05-15 19:27 UTC by oolongbrothers

##### SUMMARY
This pull request adds the `flatpak_remote` module which is used to manage flatpak repository remotes on the managed host. This will allow users to configure their flatpak installs and upstream remotes for installing flatpaks.

The module utilises the managed system's `flatpak` binary which it depends on.

Both `user` and `system` installation methods are supported.

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
`flatpak_remote`

##### ANSIBLE VERSION
```
ansible 2.6.0 (flatpak_remote ff71498ca2) last updated 2018/05/15 21:08:05 (GMT +200)
  config file = None
  configured module search path = [u'/home/[redacted]/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/alexander/Code/ansible/lib/ansible
  executable location = /home/alexander/Code/ansible/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### ADDITIONAL INFORMATION
Example output:
```
TASK [Test addition] *************************************************************************************************************************************************************************************************************************
changed: [localhost] => {
    "changed": true, 
    "command": "/usr/bin/flatpak remote-add --user flatpak-test https://dl.flathub.org/repo/flathub.flatpakrepo", 
    "invocation": {
        "module_args": {
            "executable": "flatpak", 
            "method": "user", 
            "name": "flatpak-test", 
            "remote": "https://dl.flathub.org/repo/flathub.flatpakrepo", 
            "state": "present"
        }
    }, 
    "rc": 0, 
    "stderr": "", 
    "stderr_lines": [], 
    "stdout": "", 
    "stdout_lines": []
}
```

2018-05-15 19:58 UTC, dagwieers requested changes
Looking good for the most part.

2018-05-15 19:58 UTC, dagwieers commented on lib/ansible/modules/packaging/os/flatpak_remote.py
> +# Copyright: (c) 2017 John Kwiatkoski
So we expect email-adressess for the copyright statements.
```python
# Copyright: (c) 2017, John Kwiatkoski <email-address>
```
or
```python
# Copyright: (c) 2017, John Kwiatkoski (@jaykayy) <email-address>
```

2018-05-15 19:58 UTC, dagwieers commented on lib/ansible/modules/packaging/os/flatpak_remote.py
> +      When used with I(state=absent) the remote with thet name will be removed.
Make this two items.
We prefer the first line of the description explain what the option is for.
So rather:
```yaml
  name:
    description:
    - The name of the flatpak repository to manage
    - When I(state) is set to C(present), I(name) is added as a remote for installing flatpaks.
    - When used with I(state=absent) the remote with that name will be removed.
```
PS There's a type in `thet`.

2018-05-15 19:58 UTC, dagwieers commented on lib/ansible/modules/packaging/os/flatpak_remote.py
> +      When used with I(state=absent) the remote with thet name will be removed.
Do the same for all other descriptions.

2018-05-15 19:58 UTC, dagwieers commented on lib/ansible/modules/packaging/os/flatpak_remote.py
> +      the c(flatpak) executable on the path
Should be C(flatpak) not c(flatpak).

2018-05-15 20:13 UTC, oolongbrothers commented
I attempted to fix the @-mention problem by interactive rebase and force-push. I hope that is adequate.

2018-05-16 05:58 UTC, oolongbrothers commented
I pushed changes addressing you latest comments, @dagwieers :smiley:

2018-05-16 20:55 UTC, JayKayy commented
well done @oolongbrothers thanks for the mention.

2018-05-22 05:54 UTC, oolongbrothers commented on lib/ansible/modules/packaging/os/flatpak_remote.py
> +      When used with I(state=absent) the remote with thet name will be removed.
Thanks for your hints on documentation. It made me realise that I needed to read the Ansible documentation guidelines.
After doing that I reworked the module documentation to be in line with those guidelines. The documentation should be a lot easier to read now.

2018-05-22 13:48 UTC, dagwieers approved these changes
LGTM, so the only thing missing now are integration tests, even if they won't work and they are disabled by default, having them (and using them when one is improving these modules) is important to ensure at least tested use-case work as expected.

2018-05-22 19:00 UTC, oolongbrothers commented
Integration tests are upcoming on this one.

2018-05-22 20:08 UTC, maxamillion approved these changes

2018-05-22 20:08 UTC, merged

2018-05-23 18:41 UTC, oolongbrothers commented
bcoca already fixed it. Good stuff!