aws_ec2 inventory plugin: backport/2.5/40240
ansible/ansible pull request #40277
Opened 2018-05-16 18:35 UTC by s-hertel

##### SUMMARY
Backporting #40240

Fallback to IAM role credentials

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
aws_ec2

##### ANSIBLE VERSION
```
2.5.2
```

2018-05-16 18:38 UTC, ryansb requested changes
Changelog nitpick, LGTM otherwise.

2018-05-16 18:38 UTC, ryansb commented on changelogs/fragments/aws_ec2_inventory_fallback_to_instance_role_credentials.yaml
> +  - Fallback to IAM role temporary credentials if none are explicitly provided for the aws_ec2 inventory plugin
`instance role STS credentials` would be more accurate for the changelog

2018-05-16 19:12 UTC, ryansb approved these changes

2018-05-16 19:14 UTC, nitzmahone approved these changes

2018-05-16 19:14 UTC, nitzmahone commented
rebuild_merge

2018-05-17 05:47 UTC, merged

2018-06-08 19:45 UTC, rseuchter commented
This (backport of) the fix stopped my headaches concerning the aws_ec2 inventory plugin in Ansible 2.5. Great work!