fix netconf_get documentation section and lock logic
ansible/ansible pull request #40357
Opened 2018-05-17 19:16 UTC by wisotzky

##### SUMMARY
Fix documentation to fit the latest updates.
Correct logic for explicit lock.

##### ISSUE TYPE
 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME
Module netconf_get

##### ANSIBLE VERSION

```
2.6.0
```

##### ADDITIONAL INFORMATION
In examples option is no longer called `format` but `output`.
In examples values for `lock` are `never`, `always` and `if-supported`. It was a Boolean before supporting values True and False.

The logic for execute_lock was broken. Actually the warning in case of `if-supported` was never issued.

```

```

2018-05-18 04:28 UTC, ganeshrn approved these changes
~Looks good. Please add your as maintainer in Botmea file here so that you will get notified in case of any issues raised related to this file~

2018-05-18 04:31 UTC, ganeshrn requested changes
> The logic for execute_lock was broken. Actually the warning in case of if-supported was never issued.

Not clear what is breaking in this logic. The warning part will hit only if `lock=always`

2018-05-18 04:37 UTC, ganeshrn commented
Below is the example with a warning message in output.
```
  - name: get data
    netconf_get:
      lock: always
      filter: <interface-configurations xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-ifmgr-cfg"></interface-configurations>

```

```
 [WARNING]: lock operation on 'running' source is not supported on this device

fatal: [an-iosxr-02.ansible.eng.rdu2.redhat.com]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "display": null,
            "filter": "<interface-configurations xmlns=\"http://cisco.com/ns/yang/Cisco-IOS-XR-ifmgr-cfg\"></interface-configurations>",
            "lock": "always",
            "source": null
        }
    },
    "msg": "{'info': '<?xml version=\"1.0\" encoding=\"UTF-8\"?><error-info xmlns=\"urn:ietf:params:xml:ns:netconf:base:1.0\" xmlns:nc=\"urn:ietf:params:xml:ns:netconf:base:1.0\">\\n   <bad-element>running</bad-element>\\n  </error-info>\\n ', 'severity': 'error', 'tag': 'unknown-element', 'path': None, 'message': None, 'type': 'protocol'}"
}
```

2018-05-18 04:45 UTC, ganeshrn commented
With junos
```
  - name: get data
    netconf_get:
      filter: <configuration><system><syslog></syslog></system></configuration>
      lock: always
```

Output:
```
 [WARNING]: lock operation on 'running' source is not supported on this device

fatal: [an-vsrx-02]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "display": null,
            "filter": "<configuration><system><syslog></syslog></system></configuration>",
            "lock": "always",
            "source": null
        }
    },
    "msg": "syntax error"
}
```

2018-05-18 08:11 UTC, wisotzky commented
>> The logic for execute_lock was broken.
>> Actually the warning in case of `if-supported` was never issued.

> Not clear what is breaking in this logic. The warning part will hit only if `lock=always`

Okay, maybe I need to be more precise than this. @privateip defined the rules for the `lock` option. We both agree on value: `never`. In case of `if-supported` we should only execute the lock, if this operation is supported by the system - else we would just do the get/get-config but without executing the lock. To give some indication to the user that the operation was executed without locking, a warning (or corresponding return value) absolutely makes sense. So basically with `if-supported` we expose the desire to lock - but saying we can relax this requirement if not supported by the node.

In case of `always`, we explicitly say that the operation MUST be executed with the lock active. Therefore in any case we can NOT lock the datastore, we would fail the operation with a corresponding error message. Executing it without a lock but issuing a warning does not make any sense to me.

In the implemented logic, you fail the operation only if lock option is set to `always` while lock is not supported (for none of the supported datastores). See code snippet below:
```
if lock == 'always' and not operations.get('supports_lock', False):
    module.fail_json(msg='lock operation is not supported on this device')
```

While if lock is supported for other datastores, but just not for the one defined in `source`, you would raise a warning. In the current solution, this would only be the case for devices supporting `:startup` or `:candidate` but not supporting `:writable-running`.


Additional note:
I am just wondering, if there is any plan to override the generic rules to determine per device/device family lock support. In the current implementation, lock on running depends on `:writable-running`, lock on startup depends on `:startup` and lock on candidate depends on `:candidate`.

Override per device family might make sense, to teach Ansible about RFC6241 non-compliant behavior (beside of lock on running, as discussed earlier). For example, Nokia SROS devices do support `:startup` but do not allow you to lock the startup datastore.

The code proposal, I've provided is based on what was defined as rules by @privateip. Also the logic is more simplified. From 15 content lines of code, it has been reduced to 11 lines of code. You could even remove lines 211 and 212, to bring it down to 9 content lines of code. The only reason I've kept this, is because the user would learn that `lock operation is not supported on this device` at all while in case only the specific datastore is not supported, the failure message would become `lock operation on 'running' source is not supported on this device`.

2018-05-18 14:24 UTC, ganeshrn commented
> Okay, maybe I need to be more precise than this. @privateip defined the rules for the lock option. We both agree on value: never. In case of if-supported we should only execute the lock, if this operation is supported by the system - else we would just do the get/get-config but without executing the lock. To give some indication to the user that the operation was executed without locking, a warning (or corresponding return value) absolutely makes sense. So basically with if-supported we expose the desire to lock - but saying we can relax this requirement if not supported by the node.

That's exactly the way I understood it. Currently it show warning only in `lock:always` case. It can be added in `lock:if-supported` case as well to indicate that lock on datastore is not supported.
Moving ahead in case of `lock:always` the lock is always executed irrespctive of it is supported or not.
In case of `lock:if-supported` it is executed only if it is supported.

> In case of always, we explicitly say that the operation MUST be executed with the lock active. Therefore, in any case, we can NOT lock the datastore, we would fail the operation with a corresponding error message. Executing it without a lock but issuing a warning does not make any sense to me.

With the current implementation, if `lock=alaways` the lock is **always** executed. The warning message is added because later on when the actual lock is executed on datastore the exception error message received from `ncclient` is not self-explanatory. Please refer above comment for the error message on junos and iosxr devices.

> For example, Nokia SROS devices do support :startup but do not allow you to lock the startup datastore.

If there is a deviation from standard rfc the capability dict can always be overwritten in the respective plugin to reflect the exact device capability. One of the main reason for adding individual platform plugins is to add platform-specific implementation details in the plugin instead of having it in modules.
So in this case, `startup` can be removed from `lock_datastore` in the overwritten method.

2018-05-24 01:16 UTC, wisotzky commented
This was the original comment from @privateip 

> Change this argument from bool to choices with the following choices `[never, always, if-supported]`
> 
> In the `never` case, do not attempt to lock the conf data store
> In the `always` case, try to lock the conf data store and error if the lock operation fails
> In the `if-supported` case, try to lock the conf data store and continue unlocked if the lock operation fails
> 
> The default value should be `never`

So he is not going into this level of detail, when to issue a warning. But he clearly says, that the operation should fail in case of lock attribute value set to `always` returns an error.

2018-05-24 04:32 UTC, ganeshrn commented
> But he clearly says, that the operation should fail in case of lock attribute value set to always returns an error.

In current implementation if `lock:always` in that case `lock` is **always executed**

2018-05-24 10:32 UTC, wisotzky commented
I've got your point... It basically means you just render this additional warning, while the intend is to still always call the lock/unlock function and to let it fail.

If this is the case, I believe the following lines in your code violate that principle:
```
    if lock == 'always' and not operations.get('supports_lock', False):
          module.fail_json(msg='lock operation is not supported on this device')
```

So in case the device supports neither :candidate nor :writable-running, you would basically fail this operation.

I will change my implementation, fitting this logic...

2018-05-24 10:57 UTC, ganeshrn commented
> If this is the case, I believe the following lines in your code violate that principle:

I had an offline discussion with @privateip regarding this, we concluded that if remote host doesn't support lock, in that case, it is better to fail early (before executing lock itself).

 > I will change my implementation, fitting this logic..

There can be multiple achieve certain logic, however, I think unless the current implementation breaks something I see no point in changing the code.

2018-05-24 11:43 UTC, wisotzky commented
> There can be multiple ways to achieve certain logic, however, I think unless the current implementation breaks something I see no point in changing the code.

I've just send another update of the actual code. Streamlining makes a lot of sense here, because there is some replication in your implemented logic. This impacts readability and maintainability. My version has 8 lines of code which are easy to read/understand - while the original version has 15.

> I had an offline discussion with @privateip regarding this, we concluded that if remote host doesn't support lock, in that case, it is better to fail early (before executing lock itself).

Technically, every device which supports NETCONF and claims to be standard-compliant (rfc6241) MUST support the lock operation. If it would have been intended by IETF that lock is optional, they would have introduced the :lock capability. So I believe, you are trying to catch a case here, which basically does not exist - it is neither covered by the standards nor I am aware of a NE implementation doing this.

Therefore my clear proposal is, to remove this code - until IETF introduces the :lock capability or you find nodal vendors, who have this implemented.

2018-06-12 05:59 UTC, ganeshrn approved these changes

2018-06-12 06:06 UTC, ganeshrn commented
@wisotzky Thank you!

2018-06-12 06:06 UTC, merged