switch shade with openstacksdk
ansible/ansible pull request #40532
Opened 2018-05-22 13:32 UTC by gtema

##### SUMMARY
shade library is becoming obsoleted in favor of openstacksdk. For ansible 2.5 openstacksdk was set as a dependency for shade to give time for adoption. For 2.6 it is time to retire shade completely

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
openstack

##### ANSIBLE VERSION
```
ansible 2.6.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/gtema/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/gtema/workspace/ansible/.tox/py36/lib/python3.6/site-packages/ansible
  executable location = /home/gtema/workspace/ansible/.tox/py36/bin/ansible
  python version = 3.6.5 (default, Mar 29 2018, 18:20:46) [GCC 8.0.1 20180317 (Red Hat 8.0.1-0.19)]
```

##### ADDITIONAL INFORMATION

2018-05-22 13:33 UTC, gtema commented
PR is not yet completed. It is created to see the tests results of openstack/third-party-check

2018-05-22 13:33 UTC, gtema commented
cc @emonty

2018-05-22 14:02 UTC, ruizink commented on lib/ansible/modules/cloud/openstack/README.md
> +  the [openstacksdk](http://git.openstack.org/cgit/openstackopenstacksdk)
Typo in the URL

2018-05-22 14:09 UTC, gtema commented
Since all tests are passing I would say PR is ready for a wide review

2018-05-23 17:11 UTC, SamYaple commented
LGTM

2018-05-24 18:54 UTC, gtema commented
recheck

2018-05-25 17:27 UTC, emonty commented on lib/ansible/modules/cloud/openstack/os_stack.py
> +    except sdk.OpenStackCloudException as e:
sdk.exceptions.OpenStackCloudException

2018-05-25 17:28 UTC, emonty commented on lib/ansible/modules/cloud/openstack/os_volume.py
> +        except sdk.OpenStackCloudTimeout:
sdk.exceptions.OpenStackCloudTimeout

2018-05-25 17:29 UTC, emonty commented on lib/ansible/modules/cloud/openstack/os_ironic.py
> +        raise sdk.OpenStackCloudException(
sdk.exceptions.OpenStackCloudException

2018-05-25 17:29 UTC, emonty commented on lib/ansible/modules/cloud/openstack/os_quota.py
> +    except sdk.OpenStackCloudURINotFound:
sdk.exceptions

2018-05-25 17:29 UTC, emonty commented on lib/ansible/modules/cloud/openstack/os_quota.py
> +    except sdk.OpenStackCloudURINotFound:
sdk.exceptions

2018-05-25 17:30 UTC, emonty commented on lib/ansible/modules/cloud/openstack/os_quota.py
> +                except sdk.OpenStackCloudException as e:
sdk.exceptions

2018-05-25 17:30 UTC, emonty commented on lib/ansible/modules/cloud/openstack/os_stack.py
> +    except sdk.OpenStackCloudException as e:
sdk.exceptions

2018-05-25 17:30 UTC, emonty commented on lib/ansible/modules/cloud/openstack/os_user_role.py
> +    except sdk.OpenStackCloudException as e:
sdk.exceptions

2018-05-25 17:33 UTC, emonty requested changes
There are a set of places using exceptions directly from sdk. instead of on sdk.exceptions.

2018-05-25 18:00 UTC, emonty approved these changes

2018-05-25 18:07 UTC, gtema commented
close-open to retrigger shippable

2018-05-25 20:24 UTC, sivel commented
bot_skip

2018-05-26 01:40 UTC, merged

2018-05-26 06:01 UTC, gundalow commented
Hi, Can you please add something into the doc/docsite/rst/porting_guide for this

2018-05-26 06:12 UTC, gundalow commented
Looks like there are still some references to the old inventory file

roles: `ansible-role-nodepool`

```
TASK [Download openstack.py dynamic inventory from upstream] ***********************************************************
fatal: [nodepool]: FAILED! => {"changed": false, "dest": "/var/lib/nodepool/inventory", "gid": 1001, "group": "nodepool", "mode": "0755", "msg": "Request failed", "owner": "nodepool", "response": "HTTP Error 404: Not Found", "size": 4096, "state": "directory", "status_code": 404, "uid": 1001, "url": "https://raw.githubusercontent.com/ansible/ansible/devel/contrib/inventory/openstack.py"}

```

2018-05-26 06:14 UTC, gtema commented
@gundalow sure. I will prepare PR on Monday. Should it then go to stable-2.6, or also devel branch?

2018-05-26 06:17 UTC, gtema commented
For the nodepool we I will also take care. It was necessary to rename the inventory module due to the name shadowing. In modules imoirt hack worked, but not in the inventory.

2018-05-26 06:56 UTC, gundalow commented
@gtema The `porting_guide_2.6.rst` file needs to be updated in devel.

In the PR ask for that change to be backported into `stable-2.6` branch aswell.

Locally I've worked round the `ansible-role-nodepool` issue (but just not running it). 
Thanks for the quick response :)

2018-05-26 09:08 UTC, gtema commented
@gundalow can you please point me to the ansible-role-nodepool where you have problem? In the current source of the official role (in galaxy named openstack.nodepool) I can't find such task (see https://git.openstack.org/cgit/openstack/ansible-role-nodepool).

And in the whole ansible docs I would also fix developing_dynamic_inventory.rst, which also refer to the old openstack.py file

2018-05-26 11:12 UTC, gundalow commented
@gtema Oh, i apologize turns out the reference is in part of the private Ansible test repo. I'll fix that myself.

So it's just https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/porting_guides/porting_guide_2.6.rst that needs updating

2018-05-28 22:30 UTC, bryfry commented
I'm getting the below error when running this script.

`keystoneauth1.exceptions.auth_plugins.MissingRequiredOptions: Auth plugin requires parameters which were not given: auth_url`

The shade based version of the script is able to successfully use the clouds.yaml file correctly.  Any suggestions?

2018-05-29 04:25 UTC, gtema commented
@bryfry, can you please post your `clouds.yaml`. I have one assumption, but need to verify.
Openstacksdk supports everything, what was in shade. It might, however, deprecate and have dropped things earlier.

2018-05-30 16:05 UTC, Shrews commented
@bryfry - That should hopefully get fixed with PR #40892 and PR #40894

2018-11-02 18:56 UTC, acozine commented
also related to #17930