Adding a switch to output docker logs
ansible/ansible pull request #40693
Opened 2018-05-25 02:03 UTC by achinthagunasekara

##### SUMMARY

Adding a switch to output docker logs optionally if selected to do so.

```
- name: Create container if required and run command.
  docker_container:
    name: yum_reposync
    image: "{{ reposync_container }}"
    detach: no
    volumes:
      - "/tmp/bootstrap.sh:/tmp/bootstrap.sh"
    entrypoint: /bin/bash /tmp/bootstrap.sh
    log_driver: "json-file"
    output_logs: 'yes'
```
##### ISSUE TYPE

Currently we are only able to see the logs of a container if the `command`, `entrypoint` task fails.
However it's worthwhile having the ability to view these logs optionally regardless.

2018-05-25 02:05 UTC, sambanks commented
This would be great!

2018-06-04 01:06 UTC, achinthagunasekara commented
+label ready_for_review

2018-06-04 01:10 UTC, achinthagunasekara commented
ready_for_review

2018-06-06 06:08 UTC, achinthagunasekara commented
@mkrizek I have tried using ready_for_review on this PR.
Is there anything I need to have this reviewed?

Thanks

2018-06-06 06:22 UTC, kassiansun requested changes

2018-06-06 06:22 UTC, kassiansun commented on lib/ansible/modules/cloud/docker/docker_container.py
> +        output_logs=dict(type='bool', default=False),
move this before paused to make options alphabetically ordered?

2018-06-06 06:34 UTC, achinthagunasekara commented on lib/ansible/modules/cloud/docker/docker_container.py
> +        output_logs=dict(type='bool', default=False),
@kassiansun Updated

2018-06-06 06:46 UTC, achinthagunasekara commented
!needs_revision

2018-06-06 06:48 UTC, achinthagunasekara commented
ready_for_review

2018-06-06 08:36 UTC, kassiansun approved these changes

2018-06-06 08:50 UTC, merged