Fixes ios_logging idempotency issues
ansible/ansible pull request #40701
Opened 2018-05-25 08:47 UTC by NilashishC

##### SUMMARY
Fixes idempotency issues in ios_logging module

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
ios_logging.py

##### ANSIBLE VERSION

```
devel
```

##### ADDITIONAL INFORMATION
Prior to the fix, the following plays/tasks would result in Changed: True for every run.
```
---
- name: Test ios_logging facility
  hosts: ios-L2
  tasks:
    - name: set logging facility
      ios_logging:
        facility: auth
        state: present
      register: res

    - debug:
        var: res
```
```
---
- name: Test ios_logging for idempotency
  hosts: ios-L2
  tasks:
    - name: ios_logging both buffered and facility
      ios_logging:
        dest: buffered
        facility: uucp
        level: alerts
        size: 4096
        state: present
      register: res

    - debug:
        var: res

```
This observation is valid for every option for the *facility* parameter.

2018-05-30 05:52 UTC, trishnaguha approved these changes

2018-05-30 08:19 UTC, ganeshrn approved these changes

2018-05-31 09:25 UTC, NilashishC commented
- Added integration tests
- Fixed facility not being disabled issue

2018-05-31 13:17 UTC, Qalthos requested changes

2018-05-31 13:17 UTC, Qalthos commented on lib/ansible/modules/network/ios/ios_logging.py
> +                elif dest:
Isn't this just else now?

2018-05-31 13:17 UTC, Qalthos commented on lib/ansible/modules/network/ios/ios_logging.py
>                  else:
And then this needs to be even with if dest instead of elif dest

2018-05-31 14:36 UTC, Qalthos approved these changes

2018-05-31 14:37 UTC, merged