Adding module to manage face collections in AWS Rekognition
ansible/ansible pull request #40768
Opened 2018-05-27 16:58 UTC by slapula

##### SUMMARY
This module manages face collections in AWS Rekognition.  It's very simple but I think it's necessary in order to include other modules that use Rekognition to manage face data.

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
`rekognition_collection`

##### ANSIBLE VERSION
```
ansible 2.4.1.0
  config file = None
  configured module search path = [u'/Users/asmith/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/asmith/.pyenv/versions/2.7.13/lib/python2.7/site-packages/ansible
  executable location = /Users/asmith/.pyenv/versions/2.7.13/bin/ansible
  python version = 2.7.13 (default, Sep  8 2017, 15:16:38) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

2018-06-08 18:37 UTC, mattclay commented
CI permissions update needed:

```
Traceback (most recent call last):
  File "/tmp/ansible_Py1Nx5/ansible_module_rekognition_collection.py", line 85, in create_collection
    CollectionId=module.params.get('name')
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
AccessDeniedException: An error occurred (AccessDeniedException) when calling the CreateCollection operation: User: arn:aws:sts::966509639900:assumed-role/ansible-core-ci-test-prod/prod=shippable=ansible=ansible=67512.66 is not authorized to perform: rekognition:CreateCollection on resource: arn:aws:rekognition:us-east-1:966509639900:collection/mytestcollection
```

2018-07-18 15:46 UTC, s-hertel commented
bot_status

2018-07-18 16:05 UTC, s-hertel requested changes
A couple little things, but looks good. I've updated CI permissions for the tests.

2018-07-18 16:05 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/rekognition_collection.py
> +    except (ClientError, IndexError):
Right now this masks valid ClientErrors and doesn't handle BotoCoreErrors. Please only return False for a specific exception (that is caused/if it is caused) when there are no collections. See https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/GUIDELINES.md#using-is_boto3_error_code

Actually, I just testing this out and list_collections() returns {...., 'CollectionsIds': []} when there are no collections. So it looks like there's no need to handle IndexError (iterating over an empty list is fine), and you can just call fail_json_aws for any BotoCoreError or ClientError exceptions.

2018-07-18 16:05 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/rekognition_collection.py
> +from ansible.module_utils.ec2 import boto3_conn, get_aws_connection_info, AWSRetry
These imports are not used.

2018-07-18 16:05 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/rekognition_collection.py
> +from io import BytesIO
locale and BytesIO don't appear to be used.

2018-07-18 16:05 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/rekognition_collection.py
> +from ansible.module_utils.ec2 import camel_dict_to_snake_dict, boto3_tag_list_to_ansible_dict
Also these.

2018-07-18 16:05 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/rekognition_collection.py
> +    result = {
You can just return changed from create_collection and delete_collection and initialize it here as False. No need to pass around the dict.

2018-07-18 16:05 UTC, s-hertel commented on test/integration/targets/rekognition_collection/tasks/main.yaml
> +        name: 'mytestcollection'
Can you name this using {{ resource_prefix }} as the name or part of the name? CI runs these tests in parallel so the names should be unique to avoid conflicting tests.

2020-08-19 10:21 UTC, Akasurde commented
Hi @slapula, Thank you very much for your interest in Ansible. This plugin/module is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.aws<br><br>If you have further questions please stop by IRC or the mailing list:<br><br>* IRC: #ansible on irc.freenode.net<br>* mailing list: https://groups.google.com/forum/#!forum/ansible-project<br><br>needs_info<br>

2020-08-19 10:21 UTC, closed without merging