pip: combine chdir and env only when env is set
ansible/ansible pull request #40793
Opened 2018-05-28 12:51 UTC by tyll

#### SUMMARY
This fixes an AttributeError when chdir without virtualenv is specified:

 File "/tmp/ansible_2UAFsZ/ansible_module_pip.py", line 387, in main
    env = os.path.join(chdir, env)
 File "/usr/lib64/python2.7/posixpath.py", line 75, in join
    if b.startswith('/'):
AttributeError: 'NoneType' object has no attribute 'startswith'

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
pip

##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/till/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, May 16 2018, 17:50:09) [GCC 8.1.1 20180502 (Red Hat 8.1.1-1)]

```

##### ADDITIONAL INFORMATION

```
---
cat > 'bug_pip_chdir.yml' <<EOF
- name: Show pip chdir bug
  hosts: all
  tasks:
    - pip:
        name: pip
        extra_args: --user --upgrade
        chdir: /tmp
EOF
```

```
ansible-playbook -i rhel7, bug_pip_chdir.yml 

PLAY [Run tox tests and nmctl show] *********************************************************************

TASK [Gathering Facts] **********************************************************************************
ok: [rhel7]

TASK [pip] **********************************************************************************************
fatal: [rhel7]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 192.168.122.177 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_Q3ae1r/ansible_module_pip.py\", line 562, in <module>\r\n    main()\r\n  File \"/tmp/ansible_Q3ae1r/ansible_module_pip.py\", line 387, in main\r\n    env = os.path.join(chdir, env)\r\n  File \"/usr/lib64/python2.7/posixpath.py\", line 75, in join\r\n    if b.startswith('/'):\r\nAttributeError: 'NoneType' object has no attribute 'startswith'\r\n", "msg": "MODULE FAILURE", "rc": 1}

PLAY RECAP **********************************************************************************************
rhel7                      : ok=1    changed=0    unreachable=0    failed=1   
```

2018-05-28 13:51 UTC, resmo approved these changes
LGTM

2018-05-28 18:54 UTC, robinro requested changes
Thanks @tyll for this PR.
This issue is already known as #37912 and there is a fix for it under discussion in #40129. The fix given here is not complete.

2018-05-28 22:23 UTC, tyll commented
@robinro thank you for the pointers. The fix here is complete for the error that is reported here. There seem to be other issues with the pip module discussed in #40129  that can be addressed with extra changes, but the `AttributeError` in discussion here could be easily fixed. IMHO it would be better to fix this actual error first and then finish the discussion about other problems. The fix could have been in several releases already and it fixes this playbook:
https://github.com/tyll/nmstate/blob/integration_tests/tests/ci_tests_basic.yml#L36

Therefore it would be great to merge at least this fix and then continue the discussion about the other problems.

2018-06-11 18:55 UTC, robinro commented
Since #40129 is not updated
@tyll Can you add a test for your change? I'd merge the simple fix then and ignore the `executable` situation for now.

2018-06-12 11:54 UTC, tyll commented
@robinro I added an integration test

2018-06-21 18:49 UTC, robinro commented
@tyll Thanks for the test. To me it's a bit over-the-top and also the CI complains. I wouldn't use a custom package for this.
Maybe we can have a test that "only" checks for the original issue: Not failing when `chdir` and `env` are both passed. Maybe use a relative path to a trivial requirements.txt to check if the chdir has effect, but even that is imo not necessary.

2018-06-21 21:58 UTC, tyll commented
On Thu, Jun 21, 2018 at 11:50:23AM -0700, Robin Roth wrote:
> @tyll Thanks for the test. To me it's a bit over-the-top and also the CI complains. I wouldn't use a custom package for this.
> Maybe we can have a test that "only" checks for the original issue: Not failing when `chdir` and `env` are both passed. Maybe use a relative path to a trivial requirements.txt to check if the chdir has effect, but even that is imo not necessary.

This is a test for the use case I have, therefore it would be great if
it could be tested. The CI results are outdated AFAICS, I addressed them
back then, I believe. The original issue happens when only chdir is set
but env is not and this seems to make only sense when running "pip
install ." but I might be missing something.

2018-06-27 23:21 UTC, mattclay commented
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/71710/24/tests

2018-06-28 19:09 UTC, tyll commented
@mattclay  The failure on OS X should be fixed now, Shippable seems to take some time, so we will know later.

2018-07-16 18:56 UTC, robinro commented
shipit

2018-07-16 19:15 UTC, robinro commented
bot_status

2018-07-17 15:32 UTC, resmo commented
shipit

2018-08-11 17:13 UTC, orenwolf commented
any chance of getting this merged?

2018-08-13 17:59 UTC, merged

2018-09-17 16:47 UTC, GaboFDC commented
Will this fix only be avaiable in 2.7, or is there any change of it beeing back ported to 2.5 or 2.6?

2018-09-17 17:03 UTC, resmo commented
it is in 2.7