dig lookup plugins: stop masking resolution errors
ansible/ansible pull request #41195
Opened 2018-06-06 15:43 UTC by fghaas

##### SUMMARY

When users use the `dig` lookup plugin, it is reasonable to assume that they would like the lookup to return meaningful data. If that data is not forthcoming from the DNS, then it's more prudent to just fail the playbook run, rather than carry on and return data of questionable utility (like the empty string, or the literal `NXDOMAIN`).

Fixes #41192.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
dig

##### ANSIBLE VERSION
```
ansible 2.5.4
  config file = /home/florian/.ansible.cfg
  configured module search path = [u'/home/florian/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]

```

##### ADDITIONAL INFORMATION
This is a first stab at the issue; please let me know if I'm headed in the right direction.

2018-06-06 16:01 UTC, jpmens commented
What you propose sounds and looks reasonable. What I would though now like to see is a switch in the plugin which enables it, keeping the handling we had so far intact. Can you add a `raise=true` parameter or something similar to enable the new behavior?

2018-06-06 19:16 UTC, fghaas commented
@jpmens Sorry about the silly typo that broke the test, that one's fixed now.

About your suggestion: I'm normally all for preserving pre-existing functionality by default, in the interest of UX continuity and backwards compatibility, but in this case I'm really quite convinced that the present behavior is broken and should not be preserved by default. Sorry for sounding like a zealot, but I really cannot think of any scenario in which users would find the current behavior not counterintuitive, and potentially outright dangerous. It's akin to the `file` lookup plugin, in the event that a file does not exist, setting a variable value to the string `File not found` or `ENOENT`.

So if we want an additional parameter, I posit it should be called something like `ignore_errors` and default to `false`. In other words, keep the prior behavior available, but be "sane" by default. Even so, I'd like to caution that this parameter would be one that, in my humble opinion, would do little but keep around the opportunity to royally should oneself in the foot in very unexpected ways.

I'd be happy to stand corrected here though, so if you can illustrate a scenario in which it's reasonable to have the string `NXDOMAIN` or the empty string in a place where a user would expect an IP address or an MX hostname or the like, I'm more than willing to change my mind. Thoughts?

2018-06-06 19:20 UTC, jpmens commented
@fghaas I meanwhile came to a similar conclusion. :-)

2018-06-06 19:20 UTC, jpmens commented
shipit

2018-06-07 07:08 UTC, fghaas commented
@jpmens OK great, thanks for reconsidering. :) Let's wait and see what the core folks say.

2018-06-08 09:07 UTC, fghaas commented
@jpmens In case you have a suggestion on specific people to tag in order to ask for reviews here, please do let me know. Thank you!

2018-06-29 09:40 UTC, ls-initiatives commented
The proposal is sane, and I agree it'd be more usefull this way.

However I have a doubt about NXDOMAIN, which not at all like a filesystem ENOENT or a HTTP 404.
My undestanding is that in DNS, NXDOMAIN is a *positive* result, just like "no" is an anwser to "please". DNS caches consider it as valid a result as any other and relay it.
I agree it is intuitive to no-one but DNS admins, and it caused me problems in the past but it does make sense.

So we need at least an option to consider NXDOMAIN a non-error.
Practical examples : I could be checking that user-submitted subdomain is not used yet ; or I could be polling as I wait for DNS propagation.

2018-06-29 12:15 UTC, fghaas commented
@ls-initiatives Sorry, that logic you put forward around `NXDOMAIN` entirely fails to convince me that it's in any way substantially different from `ENOENT` or a 404. By the same logic you could argue that a 404 is a "positive" response because the server _did tell you_ "there's nothing by that name here", as opposed to just ignoring your request.

2018-06-29 13:25 UTC, ls-initiatives commented
My point is, aren't you removing the possibility to check the existence of an entry ?

2018-06-29 14:17 UTC, fghaas commented
Compare to how this works with any other lookup plugin: you'd use `ignore_errors: true` and then make some other task conditional on `is failed`, like so:

```yaml
---
- hosts: all
  tasks:
        - name: display the content of a file lookup
          debug:
                  msg: "{{ lookup('file', '/tmp/foobar') }}"
          register: pipe_result
          ignore_errors: true
 
        - name: create the missing file
          file:
                  path: /tmp/foobar
                  state: touch
          when: pipe_result is failed

        - name: display the content of a file lookup (again)
          debug:
                  msg: "{{ lookup('file', '/tmp/foobar') }}"
```

(Of course, there are smarter ways to do this; the above is meant to be a concise example of the precedent set by other lookup plugins.)

2018-06-29 14:48 UTC, bcoca commented
`ignore_errors`` does not affect lookups, it deals with 'task results', we introduced the `errors` option (introduced in 2.5  https://docs.ansible.com/ansible/latest/porting_guides/porting_guide_2.5.html#lookupfor lookups to control how lookups handle internal errors.

As for this specific change, i would add a field to control changing from old to new behaviour as this can break existing playbooks that rely on NXDOMAIN not being an error.

2018-06-29 14:49 UTC, bcoca requested changes
add a toggle field to change the behaviour, leaving the current as default

2018-06-29 19:09 UTC, fghaas commented
@bcoca That is exactly what @jpmens originally suggested, to which I explained why I thought why this wasn't a good idea, to which he then answered he had come to a similar conclusion. I still think it isn't a good idea.

2018-06-29 19:49 UTC, bcoca commented
@fghaas not sure how that is working for you, but tests show that lookup errors end up causing 'task definition errors', not 'task result errors' ... i would want a reproducer to see how that is working.

As for the toggle, i understand and mostly agree on your reasoning, I just stop at the point that it will break existing plays, so I require a toggle. Later we can change the default after a deprecation period and even remove the toggle in the end.

2019-06-13 09:15 UTC, davidshepherd7 commented
Any chance of this being merged soon? Is there anything I can do to help get it merged?

2019-06-13 09:22 UTC, jpmens commented
I will repeat what I said a year ago:

2019-06-13 09:22 UTC, jpmens commented
shipit

2019-09-17 09:35 UTC, jpmens commented
shipit

2019-11-06 19:07 UTC, jpmens commented
Is this going to be merged or are we stuck on an impasse?

2019-11-26 14:38 UTC, loop-evgeny commented
Over a year later we're still running into this issue and it's still wasting our time. As I understand the status: the author and the reviewer agree that a flag should be added to allow the user to choose between the current and new behaviour, but disagree on what the default value of that flag should be.

@fghaas I understand that you feel strongly about doing the right thing, and I agree with you, but hopefully it's clear by now that the Ansible core devs are not going to budge on this. So in reality, the choice is between giving users the *option* to have sane behaviour and not giving them such an option. I hope you see it that way and decide to help out fellow Ansible users by adding the flag defaulting to current behaviour, so that this can be merged.

2020-03-25 14:55 UTC, leoluk commented
Please merge this or at least add an option to generate an error instead.

2020-03-25 15:01 UTC, jpmens commented
This must be why collections were invented. I don't see this being merged at this stage of the game as Ansible is undergoing a huge restructuring. I speak solely as a small contributor.

2020-03-25 15:16 UTC, leoluk commented
"Resolve this FQDN or fail" is very basic functionality that should be provided by the Ansible core.

2020-08-16 19:17 UTC, closed without merging