Update iptables.py
ansible/ansible pull request #41245
Opened 2018-06-07 11:01 UTC by dshuvar

##### SUMMARY

Added to documentation the required variable 'protocol' for variable destination_port.

##### ISSUE TYPE

 Docs Pull Request

##### COMPONENT NAME

iptables.py
##### ANSIBLE VERSION

```
ansible 2.5.4
```

##### ADDITIONAL INFORMATION

```
if does not use variable 'protocol' you can see error:
iptables v1.6.0: unknown option "--destination-port"
like in https://github.com/ansible/ansible-modules-extras/issues/2100
it means need notes about obligate variable in documentation of module.
```

2018-06-07 11:11 UTC, sebastiendarocha requested changes
You can't put a ":" on documation, it's yaml so it considers the line as a dict.
You have to encapsulate the line between quotes (see "description" of the parameter "to_ports")

2018-06-07 11:29 UTC, dshuvar commented
@sebastiendarocha thank you, I forgot about double quotes and already fix it.

2018-06-07 11:33 UTC, sebastiendarocha commented
shipit

Thanx :)

2018-06-07 13:20 UTC, LinusU commented
ship_it

👍

2018-06-07 13:21 UTC, LinusU commented
shipit

👍

2018-06-13 06:54 UTC, resmo commented
To me it looks like we should enforce this in the code (or fail early). Would this make sense?

2018-07-09 09:31 UTC, dshuvar commented
It makes sense because if you regularly use this role you know how right use this option,
but if you saw or use in the first time this module you with a high probability make mistake.
Documentation and feature which you use must be been able to evident.

2018-08-17 18:14 UTC, merged