change OS X to macOS
ansible/ansible pull request #41294
Opened 2018-06-08 01:19 UTC by tdm00

+label: docsite_pr

##### SUMMARY

##### ISSUE TYPE

 - Feature Pull Request
 - New Module Pull Request
 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME

##### ANSIBLE VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

2018-06-08 08:19 UTC, mkrizek reviewed
Maybe we could fix all occurrences of `OS X` in the docs? Also, looks like there are several uses of `macOS/OS X` already.

2018-06-08 14:07 UTC, samdoran commented
I'm 👍 to changing this in all the docs. While the name is similar to Classic Mac OS, it is the new proper name for the operating system. Plus, Ansible doesn't work on classic Mac OS, so there should be no ambiguity in the context of Ansible which version of the Macintosh operating system we're referring to.

2018-06-09 01:25 UTC, tdm00 commented
@mkrizek and @samdoran I've updated all of the occurrences that I could find from Mac OS X to macOS. I also updated the pull request description based on the provided template. Sorry, I did this pull while pretty tired and somehow glossed over that.

2018-06-09 02:48 UTC, samdoran requested changes

2018-06-09 02:48 UTC, samdoran commented on docs/docsite/rst/scenario_guides/guide_gce.rst
> +.. note:: If you're using Ansible on Mac macOS, libcloud also needs to access a CA cert chain. You'll need to download one (you can get one for `here <http://curl.haxx.se/docs/caextract.html>`_.)
Drop the extra "Mac" here

2018-06-09 02:48 UTC, samdoran commented on lib/ansible/module_utils/urls.py
> +        # Write the dummy ca cert if we are running on Mac macOS
Drop the extra "Mac" here

2018-06-09 02:48 UTC, samdoran commented on lib/ansible/plugins/filter/core.py
> +                raise AnsibleFilterError('|password_hash requires the passlib python module to generate password hashes on Mac macOS/Darwin')
Drop the extra "Mac" here.

2018-06-09 02:48 UTC, samdoran commented on test/units/modules/network/f5/fixtures/load_ltm_irules.json
> +    "apiAnonymous": "nodelete nowrite \n    # Global variables\n    # static::POLICY_RESULT_CACHE_AUTHFAILED\n    #     Administrator can set this into 1, when there is a necessity to cache failed po
Drop the extra "Mac" here.

2018-06-09 02:48 UTC, samdoran commented on test/units/modules/network/f5/fixtures/load_ltm_irules.json
> +    "apiAnonymous": "nodelete nowrite \n    # Global variables\n    # static::POLICY_RESULT_CACHE_AUTHFAILED\n    #     Administrator can set this into 1, when there is a necessity to cache failed po
Drop the extra "Mac" here.

2018-06-11 02:13 UTC, tdm00 commented
Performed a rebase of the latest changes in devel to this pull request to reduce the possibility of any conflicts.

2018-06-20 14:14 UTC, acozine commented
Thanks @tdm00 for updating the docs to use the correct name for Apple's operating system. I appreciate your attention to detail, your response to @samdoran's requests for changes, and your contribution. 

Looking at this PR, though, I see a lot of unrelated commits, including changes to non-docs files like `lib/ansible/module_utils/network/eos/eos.py`. The build is also failing. I suspect something went wrong when you rebased the branch. 

I'd like to get the OS X -> macOS change merged from a clean PR (one that only includes the docs changes and passes our CI suite). If you don't want to (or aren't sure how to) get those changes onto a clean branch/PR, let me know - I can coach you through it or just take care of it.

2018-06-20 14:31 UTC, tdm00 commented
@acozine thank you. Please correct me if my understanding below is incorrect:

1. Close this pull request
2. Go to my repo and patch-1 batch and create a new branch from commit c60038d, which was done prior to the rebase.
3. Push the new branch to my GitHub repo
4. Open a new Pull Request

2018-06-20 15:54 UTC, samdoran commented
@tdm00 This looks like a rebase gone wrong. You should not need to open a new PR. You can try rebasing again, then force-push to the same branch to overwrite the current history.

2018-06-22 23:48 UTC, acozine commented
@tdm00 the most important part is creating a branch that contains only the OS X -> macOS changes - to do that you can try re-re-basing the branch as @samdoran suggests. If that doesn't work, you can try this (commands below assume the main ansible/ansible repo is referred to as `origin` on your system - you can check this by doing `git remote -v`):
1. fetch the latest version of `devel`: `git fetch origin`
2. create a fresh local branch off `devel`: `git checkout -b fresh_branch origin/devel`
3. cherry-pick the commits you want for this PR to the fresh local branch (I think that would be: 
e76f2d1e638170872159e98dc112ac43ec013f22, c1d60ddb0dced40c70eefef6ccae5adb15290d95, 85b3cd4e20559bb58de2f7544fa55fd09f2cc4e7, 8a58efa7131ac0fe99b6af109c749b4c4d18cf1e, 13ca452619d8f52af1b662bea23ba97bf6bef8d6, and 60038d5943435218eb3f914b98c161841507461): `git cherry-pick ####` for each commit hash
4. rename your `patch-1` branch: `git branch -m patch-1 patch-1-bad-rebase`
5. force-push your clean branch to this pr: `git push -f your_remote fresh_branch:patch-1`

2018-06-25 17:45 UTC, tdm00 commented
@acozine and @samdoran I did a `git reset --hard to c60038d` and then did a force push `git push -f origin patch-1`. This should give you a branch that has just the documentation changes.

2018-06-25 17:59 UTC, samdoran approved these changes

2018-06-25 17:59 UTC, samdoran commented
Looks good. Thanks!

2018-06-26 18:09 UTC, merged