Fixed typo and changed requirements to doc
ansible/ansible pull request #41349
Opened 2018-06-09 00:31 UTC by jlozadad

##### SUMMARY
fixed typo
added requirements for gitlab_deploy_key

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
gitlab_deploy_key, gitlab_group

##### ANSIBLE VERSION
```
ansible 2.5.4
  config file = None
  configured module search path = [u'/home/jlozadad/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /data/git/roles/lmao/lib/python2.7/site-packages/ansible
  executable location = /data/git/roles/lmao/bin/ansible
  python version = 2.7.15 (default, May 15 2018, 15:37:31) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
```

##### ADDITIONAL INFORMATION
Looking at the module `gitlab_group` it lists `python-gitlab python module` as a new requirement. Is this change going to be the same for the rest of the gitlab modules? this might cause confusion and have users install both `python-gitlab python module` and `pyapi-gitlab python module`. I think also cause issues since both will have `import gitlab`.

2018-06-09 01:56 UTC, marwatk requested changes
It depends on the author, really.  When I made gitlab_deploy_key and gitlab_hooks I noticed the conflicting library issue and designed them without any external deps because I wasn't sure which library was best (I'm not a python dev, just know enough to be dangerous).

2018-06-09 01:56 UTC, marwatk commented on lib/ansible/modules/source_control/gitlab_deploy_key.py
> +    - python-gitlab python module
gitlab_deploy_key doesn't have any dependencies, some of the other gitlab modules do, however.

2018-06-09 12:26 UTC, aoyawale commented
I'm not an expert in writing python but, right now i'm testing running all the gitlab modules and its getting messy since some require `python-gitlab` on 2.7 and some `pyapi-gitlab`.

2018-06-09 18:35 UTC, marwatk approved these changes

2018-06-09 18:37 UTC, marwatk commented
shipit

2018-07-23 14:43 UTC, Akasurde commented
rebuild_merge

2018-07-23 16:50 UTC, merged

2018-07-23 16:50 UTC, Akasurde commented
@jlozadad Thanks for the contribution. @marwatk Thanks for the review.