Add info about libffi-devel package
ansible/ansible pull request #41437
Opened 2018-06-12 08:30 UTC by Akasurde

##### SUMMARY
Due to package dependency, libffi is required for paramiko

Fixes: #30732
Fixes: #16571

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
docs/docsite/rst/installation_guide/intro_installation.rst

##### ANSIBLE VERSION

```
2.7devel
```

2018-06-12 10:01 UTC, webknjaz commented on docs/docsite/rst/installation_guide/intro_installation.rst
> +    $ sudo apt install build-essential libssl-dev libffi-dev python-dev
By the way, why isn't it an OS package dependency?

2018-06-12 10:01 UTC, webknjaz approved these changes

2018-06-12 11:04 UTC, webknjaz commented on docs/docsite/rst/installation_guide/intro_installation.rst
> +    $ sudo apt install build-essential libssl-dev libffi-dev python-dev
https://github.com/ansible/ansible/blob/devel/packaging/debian/control#L11 like here?

2018-06-12 12:14 UTC, webknjaz requested changes
So after rethinking this dependency issue, I've come to the conclusion that you're not adding this information into right place.

The problem is that those build dependencies are only needed in case user installs stuff from source, not using OS package managers.

So this should be added literally everywhere except OS package managers. Probably somewhere around pip installation flow or have a separate section explaining that because cryptography is being built during installation from sdist, thus requiring build dependencies (header files like `ffi.h` etc.). And then it should explain where to get those dependencies from in different envs.

2018-06-12 12:44 UTC, abadger commented
I don't know that we want to handle this this way.  Ansible has always
prided itself on it's lack of dependencies for core functionality.  So we
have to be mindful of that as we talk about optional deps.  Bring this up
in the core internal channel or today's team meeting as to how to solve it.

On Tue, Jun 12, 2018, 1:30 AM Abhijeet Kasurde <notifications@github.com>
wrote:

> @Akasurde <https://github.com/Akasurde> requested your review on:
> ansible/ansible#41437 <https://github.com/ansible/ansible/pull/41437> Add
> info about libffi-devel package.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/ansible/ansible/pull/41437#event-1675686636>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAMxWtbeGQarB4P1zzsyU_EncwUWqw38ks5t73wsgaJpZM4Uj_xE>
> .
>

2018-06-12 13:26 UTC, Akasurde commented
@webknjaz @abadger OK. Sure.

2018-06-12 13:45 UTC, webknjaz commented
It looks like cryptography and PyNaCl provide wheels so that only outdated pip users will face this:
* https://cryptography.io/en/latest/installation/#building-cryptography-on-linux
* https://pypi.org/project/PyNaCl/#files

2018-06-15 06:51 UTC, Akasurde commented
@abadger @webknjaz I reworded documentation by adding section in FAQs and added link to original installation intro.

2018-06-15 07:58 UTC, webknjaz approved these changes
Great job!

2018-06-15 08:03 UTC, abadger commented
+1 to merge

2018-06-15 15:14 UTC, merged

2018-06-15 15:14 UTC, Akasurde commented
@abadger @webknjaz Thanks for the reviews.