add notes to service_facts about accessing fact data
ansible/ansible pull request #41608
Opened 2018-06-15 20:12 UTC by maxamillion

Signed-off-by: Adam Miller <admiller@redhat.com>

##### SUMMARY
Add notes to the `service_facts` module docs about accessing the fact data using string value keys instead of dot notation. This adds the missing information as it was brought to our attention in #41467

##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

service_facts

##### ANSIBLE VERSION

```
ansible 2.7.0.dev0 (service_facts f9bf4c1e9d) last updated 2018/06/15 13:54:38 (GMT -500)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/admiller/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/admiller/src/dev/ansible/lib/ansible
  executable location = /home/admiller/src/dev/ansible/bin/ansible
  python version = 2.7.15 (default, May 15 2018, 15:37:31) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
```

2018-06-15 20:16 UTC, sivel approved these changes

2018-06-15 20:42 UTC, bcoca requested changes

2018-06-15 20:42 UTC, bcoca commented on lib/ansible/modules/system/service_facts.py
> +    the fact data value, as follows: C(ansible_facts.services['zuul-gateway'])
unquoted `: `

2018-06-19 13:33 UTC, bcoca approved these changes

2018-06-19 13:33 UTC, merged