initial upload of yum_versionlock
ansible/ansible pull request #41778
Opened 2018-06-21 07:27 UTC by florianpaulhoberg

Adds support to lock packages in their version to prevent these from updating by yum.

##### SUMMARY
This module adds support to lock packages in their version to prevent these from updating by yum.

Fixes #13086 

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
- yum_versionlock

##### ANSIBLE VERSION
```
ansible 2.4.2.0
```

##### ADDITIONAL INFORMATION
An example run in local playbook

```
TASK [version_lock : lock nginx to prevent updates] **********************************************************************************************************
changed: [localhost]

TASK [version_lock : update nginx] ***************************************************************************************************************************
ok: [localhost]

TASK [version_lock : unlock nginx from updates] **************************************************************************************************************
changed: [localhost]

TASK [version_lock : update nginx] ***************************************************************************************************************************
changed: [localhost]
```

2018-06-21 11:20 UTC, Akasurde commented on lib/ansible/modules/packaging/os/yum_versionlock.py
> +short_description: Locks/prevents an installed package from beeing updates by (yum) package mamanger.
`Locks/Unlocks`

2018-06-21 11:21 UTC, Akasurde commented on lib/ansible/modules/packaging/os/yum_versionlock.py
> +short_description: Locks/prevents an installed package from beeing updates by (yum) package mamanger.
s/beeing/being/

2018-06-21 11:21 UTC, Akasurde commented on lib/ansible/modules/packaging/os/yum_versionlock.py
> +short_description: Locks/prevents an installed package from beeing updates by (yum) package mamanger.
`s/mamanger/manager/`

2018-06-21 11:23 UTC, Akasurde commented on lib/ansible/modules/packaging/os/yum_versionlock.py
> +      - A package name like C(httpd).
Can we have a list of packages which can be locked/unlocked? just like yum module does.

2018-06-21 11:23 UTC, Akasurde commented on lib/ansible/modules/packaging/os/yum_versionlock.py
> +      - Whether to lock (C(present) or unlock (C(absent) a package.
(C(present) -> C(present)
(C(absent) -> C(absent)

2018-06-21 11:24 UTC, Akasurde commented on lib/ansible/modules/packaging/os/yum_versionlock.py
> +    - Florian Paul Hoberg <florian.hoberg@credativ.de>
add github handle too.

2018-06-21 11:25 UTC, Akasurde commented on lib/ansible/modules/packaging/os/yum_versionlock.py
> +YUM_BINARY = "/bin/yum"
use this instead

```
module.get_bin_path('yum', required=True)
```

2018-06-21 11:25 UTC, Akasurde commented on lib/ansible/modules/packaging/os/yum_versionlock.py
> +    state = os.path.exists("/etc/yum/pluginconf.d/versionlock.conf")
Are there any other way to check if version lock plugin is installed ?

2018-06-21 11:26 UTC, Akasurde commented on lib/ansible/modules/packaging/os/yum_versionlock.py
> +    if rc_code is 0:
```
rc_code == 0
```

2018-06-21 11:27 UTC, Akasurde commented on lib/ansible/modules/packaging/os/yum_versionlock.py
> +            state=dict(required=True, type='str', choices=['present', 'absent']),
state can be optional with default value as 'present'

2018-06-21 11:29 UTC, Akasurde commented on lib/ansible/modules/packaging/os/yum_versionlock.py
> +     - This module adds installed packages to yum versionlock to prevent it from beeing updated.
s/beeing/being/

2018-06-21 11:30 UTC, Akasurde requested changes
Could you please check inline comments and also add testcase for this module ? thanks.

2018-06-21 18:16 UTC, florianpaulhoberg commented
ok thanks, unit test file will be created soon.

2018-10-20 23:02 UTC, avarins commented
What is the status?
Does a ready_for_review have to be attached?

2019-03-01 04:21 UTC, corbinstuard commented
This looks good, can it be reviewed?

2019-05-13 14:07 UTC, a-nldisr commented
@Akasurde any plans to check this, would be great to have! :)

2020-05-12 08:12 UTC, riemers commented
Want this the Ansible way, would need this too. But since its 2 years old, i don't think i should wait on it. (which is a shame) i could even look into it if that would be the default reply (as far as my knowledge goes)

2020-05-12 09:13 UTC, Akasurde commented
@riemers @florianpaulhoberg All community modules are migrated to https://github.com/ansible-collections/community.general repo. Could you please migrate this PR to above-mentioned repo. I am sorry that I missed previous ping messages. Thanks.

2020-05-12 09:36 UTC, riemers commented
I moved it over as is, we shall see how far that gets us :)

2020-05-12 12:31 UTC, Akasurde commented
@riemers Thanks for migrating this module to new repo.

Migrated to https://github.com/ansible-collections/community.general/pull/324

2020-05-12 12:31 UTC, closed without merging