cloudstack: new module cs_disk_offering
ansible/ansible pull request #41795
Opened 2018-06-21 14:44 UTC by dpassante

##### SUMMARY

New module cs_disk_offering.

Mainly a copy/paste from @resmo 's "cs_service_offering" module.

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

lib/ansible/modules/cloud/cloudstack/cs_disk_offering.py

##### ANSIBLE VERSION

```
2.7
```

##### ADDITIONAL INFORMATION

2018-06-21 15:55 UTC, resmo requested changes
minor things otherwise good job

2018-06-21 15:55 UTC, resmo commented on lib/ansible/modules/cloud/cloudstack/cs_disk_offering.py
> +  - "René Moser @resmo)"
missing (

2018-06-21 15:55 UTC, resmo commented on lib/ansible/modules/cloud/cloudstack/cs_disk_offering.py
> +  - Create and delete disk offerings for guest VMs.
, update

2018-06-21 16:26 UTC, dpassante commented on lib/ansible/modules/cloud/cloudstack/cs_disk_offering.py
> +  - Create and delete disk offerings for guest VMs.
I put the update description in the following line but in fact it wasn't really a good idea :)

2018-06-21 16:26 UTC, dpassante commented on lib/ansible/modules/cloud/cloudstack/cs_disk_offering.py
> +  - "René Moser @resmo)"
oops!

2018-06-21 17:13 UTC, resmo commented on lib/ansible/modules/cloud/cloudstack/cs_disk_offering.py
> +  - Create and delete disk offerings for guest VMs.
ah, well. that works for me

2018-06-22 22:39 UTC, resmo approved these changes
shipit

2018-06-22 23:15 UTC, merged