Nxos restore provider to nxapi tests
ansible/ansible pull request #41818
Opened 2018-06-21 21:13 UTC by Qalthos

##### SUMMARY

Otherwise, `connection: local` tests will default to cli

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

nxos

##### ANSIBLE VERSION

```
2.7
```

2018-06-27 06:51 UTC, trishnaguha requested changes

2018-06-27 06:51 UTC, trishnaguha commented on test/integration/targets/nxos_vrf/tests/common/intent.yaml
`provider: {{ connection }}` missing on L167 https://github.com/Qalthos/ansible/blob/69046fba77e38731e01703194a0ccc88206bdd7e/test/integration/targets/nxos_vrf/tests/common/intent.yaml#L167

2018-07-02 12:40 UTC, Qalthos commented on test/integration/targets/nxos_vrf/tests/common/intent.yaml
:heavy_check_mark:

2018-07-02 12:48 UTC, trishnaguha approved these changes

2018-07-02 13:43 UTC, merged