Initial upload of roadmap for 2.7
ansible/ansible pull request #41845
Opened 2018-06-22 15:55 UTC by thaumos

##### SUMMARY

Roadmap doc for 2.7

##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

##### ANSIBLE VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

2018-06-23 20:00 UTC, jctanner commented
missing native types

2018-06-24 23:07 UTC, thaumos commented
@jctanner added in native types.

2018-06-25 00:45 UTC, jctanner approved these changes

2018-06-26 12:38 UTC, gundalow commented
Fixed the CI issues, who else needs to review before we can get this live?

2018-06-27 01:05 UTC, gundalow approved these changes

2018-06-27 16:45 UTC, nitzmahone commented on docs/docsite/rst/roadmap/ROADMAP_2_7.rst
> +* WinRM persistence
WinRM connection persistence (improved performance)

2018-06-27 16:48 UTC, nitzmahone requested changes
minor clarification on WinRM persistence, but otherwise LGTM

2018-06-27 16:48 UTC, nitzmahone commented on docs/docsite/rst/roadmap/ROADMAP_2_7.rst
> +* WinRM persistence
WinRM connection persistence (improves performance)

2018-07-09 19:29 UTC, merged