Adds support for proxy authentication and repoview enablement.
ansible/ansible pull request #41908
Opened 2018-06-25 15:16 UTC by dcode

##### SUMMARY
Adds support for allowing pulp to authenticate through a proxy to download upstream content. This also adds the `repoview` option because this actually broke with the newer Pulp API.

Repeat of #32484 because I screwed up that PR

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME

pulp_repo

##### ANSIBLE VERSION

```
ansible 2.5.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/username/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, May 16 2018, 17:50:09) [GCC 8.1.1 20180502 (Red Hat 8.1.1-1)]
```

2018-06-25 16:03 UTC, dcode commented
Regarding a5711ed, I have no idea about the `force_basic_auth`. I don't see it used and I didn't intend to touch that documentation, so I changed it back.

2018-06-25 20:18 UTC, sysadmind requested changes

2018-06-25 20:18 UTC, sysadmind commented on lib/ansible/modules/packaging/os/pulp_repo.py
> +    choices: ["yes", "no"]
I don't think that choices are appropriate on a boolean option. I don't see them used on other modules on boolean types. I believe the documentation generator will handle this automatically. I think that the defaults of no should also be quoted (at least by precedent here: https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/file.py#L63).

2018-06-25 20:18 UTC, sysadmind commented on lib/ansible/modules/packaging/os/pulp_repo.py
> +        generate_sqlite=dict(default=False, type='bool', choices=[True, False]),
I don't think these parameters should have choices either unless I'm missing an example module that already does include them.

2018-06-26 12:56 UTC, sysadmind approved these changes

2018-06-26 12:56 UTC, sysadmind commented
shipit

Thanks for the contribution!

2018-11-24 16:24 UTC, gundalow commented on lib/ansible/modules/packaging/os/pulp_repo.py
> +    version_added: "2.7"
```suggestion
    version_added: "2.8"
```

2018-11-24 16:24 UTC, gundalow commented on lib/ansible/modules/packaging/os/pulp_repo.py
> +    version_added: "2.7"
```suggestion
    version_added: "2.8"
```

2018-11-24 16:24 UTC, gundalow commented on lib/ansible/modules/packaging/os/pulp_repo.py
> +    version_added: "2.7"
```suggestion
    version_added: "2.8"
```

2018-11-24 16:24 UTC, gundalow commented on lib/ansible/modules/packaging/os/pulp_repo.py
> +    version_added: "2.7"
```suggestion
    version_added: "2.8"
```

2018-11-24 16:24 UTC, gundalow commented on lib/ansible/modules/packaging/os/pulp_repo.py
> +    required: false
```suggestion
```

2018-11-24 16:24 UTC, gundalow commented on lib/ansible/modules/packaging/os/pulp_repo.py
> +    required: false
```suggestion
```

2018-11-24 16:24 UTC, gundalow commented on lib/ansible/modules/packaging/os/pulp_repo.py
> +    required: false
```suggestion
```

2018-11-24 16:27 UTC, gundalow commented
@dcode Thank you for the PR. I've made just updated the `version_added` myself, and will merge this

@sysadmind Thank you for the review.

The reason this didn't get auto merged is because only one maintainer is listed. @dcode would you be interested in becoming a maintainer, if so please raise a fresh PR and add yourself to the `authors:` list

2018-11-24 16:28 UTC, gundalow commented
rebuild_merge

2018-11-24 17:54 UTC, merged

2018-11-25 10:43 UTC, gundalow commented
Merged and will be released in Ansible 2.8