Added ipa_vault ansible module to manage idm secure vault resource
ansible/ansible pull request #41902
Opened 2018-06-25 12:48 UTC by jparrill

##### SUMMARY
IPA module to execute CRUD actions over idm vaults. 

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
Module Name: ipa_vault 

##### ANSIBLE VERSION
```
ansible 2.5.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/jparrill/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jparrill/ownCloud/RedHat/RedHat_Engineering/upshift/tasks/idm/.virtualenv/lib/python2.7/site-packages/ansible
  executable location = /home/jparrill/ownCloud/RedHat/RedHat_Engineering/upshift/tasks/idm/.virtualenv/bin/ansible
  python version = 2.7.15 (default, May 16 2018, 17:50:09) [GCC 8.1.1 20180502 (Red Hat 8.1.1-1)]
```

2018-06-25 16:43 UTC, Akasurde requested changes
I will test this and provide more feedback.

2018-06-25 16:43 UTC, Akasurde commented on lib/ansible/modules/identity/ipa/ipa_vault.py
> +# Copyright: (c) 2017, Juan Manuel Parrilla <jparrill@redhat.com>
s/2017/2018/

2018-06-25 16:43 UTC, Akasurde commented on lib/ansible/modules/identity/ipa/ipa_vault.py
> +        - Description
Description of vault.

2018-06-25 16:43 UTC, Akasurde commented on lib/ansible/modules/identity/ipa/ipa_vault.py
> +        - Mutually exclusive with service
Full stop at end.

2018-06-25 16:43 UTC, Akasurde commented on lib/ansible/modules/identity/ipa/ipa_vault.py
> +        - Any service can own one or more service vaults
Full stop at end

2018-06-25 16:43 UTC, Akasurde commented on lib/ansible/modules/identity/ipa/ipa_vault.py
> +version_added: "2.6"
s/2.6/2.7/

2018-06-25 16:43 UTC, Akasurde commented on lib/ansible/modules/identity/ipa/ipa_vault.py
> +        default: ipa_user variable
Add default value as note rather than `default:` value.

2018-06-25 16:43 UTC, Akasurde commented on lib/ansible/modules/identity/ipa/ipa_vault.py
> +                         ipavaultsalt=dict(type='str', aliases=['salt']),
I would prefer `vault_salt`

2018-06-25 16:43 UTC, Akasurde commented on lib/ansible/modules/identity/ipa/ipa_vault.py
> +                         ipavaulttype=dict(type='str', default='standard',
I would prefer `vault_type`

2018-06-25 16:43 UTC, Akasurde commented on lib/ansible/modules/identity/ipa/ipa_vault.py
> +                         ipavaultpublickey=dict(type='str', aliases=['pubkey']),
I would prefer `vault_public_key`

2018-06-26 06:03 UTC, Akasurde commented
@fxfitz @Nosmoht @flo-renaud Could you please review this ?

2018-06-26 06:04 UTC, Akasurde commented on lib/ansible/modules/identity/ipa/ipa_vault.py
> +        type: string
no need for specifying type here.

2018-06-26 10:50 UTC, jparrill commented
Changes done, also fixed tests.

2018-06-28 07:59 UTC, jparrill commented
ping @Akasurde

2018-06-28 08:02 UTC, Akasurde commented on lib/ansible/modules/identity/ipa/ipa_vault.py
> +- Add, modify and delete vaults and secret vaults
period at end.

2018-06-28 08:03 UTC, Akasurde commented on lib/ansible/modules/identity/ipa/ipa_vault.py
> +        - Description
Add as 
```
- Description of vault.
```

2018-06-28 08:04 UTC, Akasurde commented on lib/ansible/modules/identity/ipa/ipa_vault.py
> +                           supports_check_mode=True,
```
mututally_exclusive=[['username', 'service'],]
```
As per documentation.

2018-06-28 08:05 UTC, Akasurde commented
@jparrill I will test this and provide feedback.

2018-06-29 07:46 UTC, jparrill commented
Latest changes done also

2018-07-02 09:40 UTC, Akasurde commented on lib/ansible/modules/identity/ipa/ipa_vault.py
> +    type: standard
s/type/vault_type/

2018-07-02 09:41 UTC, Akasurde commented on lib/ansible/modules/identity/ipa/ipa_vault.py
> +- Add, modify and delete vaults and secret vaults.
Add a note that - KRA service should be enabled to use this module.

2018-07-02 09:48 UTC, Akasurde commented on lib/ansible/modules/identity/ipa/ipa_vault.py
> +- ipa_vault:
I get error while trying this example

```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ipa_host": "master.ipa.test",
            "ipa_pass": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "ipa_port": 443,
            "ipa_prot": "https",
            "ipa_user": "admin",
            "ipavaulttype": "symmetric",
            "replace": false,
            "state": "present",
            "validate_certs": false
        }
    },
    "msg": "missing required arguments: cn"
}
```

2018-07-02 09:53 UTC, Akasurde commented on lib/ansible/modules/identity/ipa/ipa_vault.py
> +                         username=dict(type='list', mututally_exclusive=['username', 'service'], aliases=['user']))
Mutually exclusive is argument of AnsibleModule.

```python
    module = AnsibleModule(argument_spec=argument_spec,
                           supports_check_mode=True,
                           mutually_exclusive=[['username', 'service']],
                           )
```

2018-07-02 15:37 UTC, jparrill commented on lib/ansible/modules/identity/ipa/ipa_vault.py
> +- ipa_vault:
Yeah, you need at least provide "cn" or "name" field:

```
      - name: '[IDM] Test IDM vault creation'
        ipa_vault:
            state: present
            name: 'vault_ansible_021'       <-- This one or the same with **cn** 
            description: 'test description field'
            vault_type: 'symmetric'
            ipa_host: 'ipa.example.com'
            ipa_user: 'admin'
            ipa_pass: 'XXXXXXX'
            validate_certs: False
            replace: False
        register: vault
```

2018-07-02 16:27 UTC, Akasurde commented on lib/ansible/modules/identity/ipa/ipa_vault.py
> +- ipa_vault:
OK.

2018-07-02 16:30 UTC, Akasurde approved these changes

2018-07-03 14:07 UTC, fxfitz approved these changes
shipit

2018-07-05 04:46 UTC, merged

2018-07-05 04:47 UTC, Akasurde commented
@jparrill Thanks for the contribution. @fxfitz Thanks for the review.