Deprecate foreman and katello modules
ansible/ansible pull request #42043
Opened 2018-06-28 11:49 UTC by ehelms

##### SUMMARY

##### ISSUE TYPE

 - Feature Pull Request
 - New Module Pull Request
 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME

##### ANSIBLE VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

2018-06-28 17:01 UTC, samdoran requested changes

2018-06-28 17:01 UTC, samdoran commented on lib/ansible/modules/remote_management/foreman/foreman.py
> +    why: "Replaced by re-designed individual modules living at https://github.com/theforeman/foreman-ansible-modules"
Please add an `alternative` field describing alternate module(s) to use.

2018-06-28 22:02 UTC, gundalow requested changes
Please add 
1) An entry to to `docs/docsite/rst/porting_guides/porting_guide_2.7.rst`
2) A changelog/fragment

2018-06-28 22:02 UTC, gundalow commented on lib/ansible/modules/remote_management/foreman/foreman.py
> +    removed_in: "2.9"
deprecation cycle is four, so 2.7+4 = `"2.11"`

2018-06-28 22:03 UTC, gundalow commented on lib/ansible/modules/remote_management/foreman/foreman.py
>  __metaclass__ = type
Please rename so file starts with `_`, ie
`git mv lib/ansible/modules/remote_management/foreman/foreman.py lib/ansible/modules/remote_management/foreman/_foreman.py`

2018-06-28 22:04 UTC, gundalow commented on lib/ansible/modules/remote_management/foreman/foreman.py
>  __metaclass__ = type
This will clear most of the `ansible-test` issues

2018-06-29 12:56 UTC, ehelms commented
@samdoran @gundalow Updated addressing comments.

2018-06-29 19:21 UTC, mattclay commented
These paths need to be updated:

https://github.com/ansible/ansible/blob/a342538aba46b3b9b63700daace6b6dc9bea805f/test/sanity/validate-modules/ignore.txt#L1087-L1090

https://github.com/ansible/ansible/blob/858a1b09bb9e100e37645309fa5a13b6a89a40c3/test/sanity/pylint/ignore.txt#L56-L57

2018-06-29 21:21 UTC, samdoran approved these changes

2018-07-01 04:42 UTC, jamescassell commented
I see that the linked repo lists one of its goals as "repository maintainers will be working to push the modules into Ansible proper". Is that still the case?

2018-07-02 13:43 UTC, ehelms commented
@jamescassell Yes. We have not pushed any yet as we've been hardening the module_utils layer and figuring out testing so they are as stable as possible. We are close to having some worthy of being pushed and managed in Ansible proper.

2018-07-09 07:01 UTC, FloThinksPi approved these changes
Good idea to depricate modules as many users sould use this, instead of the better modules of the foreman community

2018-08-02 11:25 UTC, ehelms commented
Rebased, @gundalow can you please re-review

2018-08-02 20:35 UTC, gundalow approved these changes

2018-08-04 05:51 UTC, gundalow commented
Hi, looks like the paths in `test/sanity/pylint/ignore.txt` need updating

2018-08-22 09:41 UTC, sean797 commented
ping @ehelms this needs to be rebased.

2018-09-19 16:41 UTC, acozine commented
Rebased and moved to 2.8, since this PR missed the deadline for 2.7.

2018-09-19 16:41 UTC, merged