Update lambda.py
ansible/ansible pull request #42106
Opened 2018-06-29 13:49 UTC by ToROxI

Update for module's logic to don't destroy pre-configured Lambda VPC settings if vpc_subnet_ids and vpc_security_group_ids not set. Explicit declaration of destruction instead.

##### SUMMARY

##### ISSUE TYPE

 - Feature Pull Request
 - New Module Pull Request
 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME

##### ANSIBLE VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

2018-06-30 00:24 UTC, achinthagunasekara approved these changes

2018-07-01 09:06 UTC, resmo commented
I am -1 with the implementation, having a keywork 'None' is a no go. I even wonder, if the functionality is necessary as it can possible be achieved by using an empty list 


~~~yaml
# Explicit declaration of no-VPC configuration
- name: looped creation
  lambda:
    name: '{{ item.name }}'
    state: present
    zip_file: '{{ item.zip_file }}'
    runtime: 'python2.7'
    role: 'arn:aws:iam::987654321012:role/lambda_basic_execution'
    handler: 'hello_python.my_handler'
    vpc_subnet_ids: []
    vpc_security_group_ids: []
    environment_variables: '{{ item.env_vars }}'
    tags:
      key1: 'value1'
  with_items:
    - name: HelloWorld
      zip_file: hello-code.zip
      env_vars:
        key1: "first"
        key2: "second"
    - name: ByeBye
      zip_file: bye-code.zip
      env_vars:
        key1: "1"
        key2: "2"
~~~

needs_info

2018-07-01 16:20 UTC, ToROxI commented
@resmo, 
Hi! 
Main goal was to avoid destruction of VPC configuration if parameters are not provided in module.
So if keyword 'None' is not applicable for you - I'll remove this.

Please let me know if you have any concerns about my patch.
Thanks!

2018-07-03 13:09 UTC, s-hertel requested changes
Right now both omitting the options from the playbook and setting the options to an empty list remove the current VPC configuration. Rather than setting a special 'None' keyword, it would be better to change that both omitting and setting to [] mean the same thing.
e.g.
* if vpc_security_group_ids and vpc_subnet_ids are both lists that contain things, set the VPC configuration
* if they are empty lists, remove the VPC configuration
* if they are None (module.params['vpc_subnet_ids'] == None when the option isn't provided in the task), leave the VPC configuration as it is

2018-07-04 12:28 UTC, ToROxI commented
@s-hertel, requested change applied

2018-07-07 13:33 UTC, ToROxI commented
@s-hertel , @achinthagunasekara 
there is need to update tests due to changes in the invocation sequence. Will you review test or I need to add this changes of test to PR?

Thanks!

2018-07-16 22:45 UTC, mattclay commented
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/73039/66/tests

2019-09-03 12:30 UTC, gundalow commented
Given feedback from resmo and shertel I'm going to close this.

For this to get in someone will need to raise a new PR that includes tests

2019-09-03 12:30 UTC, closed without merging