Make ios_vlan identify vlans starting with 9
ansible/ansible pull request #42247
Opened 2018-07-03 13:22 UTC by HD650

##### SUMMARY

A minor bug that the parser in parse_to_logical_rows(out) ignores vlans starting with number 9. Details in #42242 
This PR fix that.

Fix #42242 
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

/ansible/lib/ansible/modules/network/ios
##### ANSIBLE VERSION

```
ansible 2.7.0.dev0 (issue_42242 56a485e694) last updated 2018/07/03 09:19:55 (GMT -400)
  config file = None
  configured module search path = [u'/home/zhikangzhang/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/zhikangzhang/Desktop/ansible/lib/ansible
  executable location = /home/zhikangzhang/Desktop/ansible/bin/ansible
  python version = 2.7.15 (default, May 16 2018, 17:50:09) [GCC 8.1.1 20180502 (Red Hat 8.1.1-1)]
```

2018-07-04 23:12 UTC, achinthagunasekara approved these changes

2018-07-05 06:52 UTC, NilashishC commented
@HD650 Thanks for writing the fix. Could you also add an integration test for this as well? That way we can make sure that future changes to this module doesn't result in this bug again.

2018-07-05 06:54 UTC, NilashishC requested changes
@HD650 Thanks for writing the fix. Could you also add an integration test for this as well? That way we can make sure that future changes to this module doesn't result in this bug again.

2018-07-05 15:01 UTC, HD650 commented
@NilashishC Sorry, I'm not an expert of this module and don't have a device to run the integration test... Could you pin someone who is familiar with this module to add the test? Thanks!

2018-07-05 15:32 UTC, trishnaguha approved these changes

2018-07-06 08:31 UTC, NilashishC commented
@HD650 You can add an unit test for this at https://github.com/ansible/ansible/blob/devel/test/units/modules/network/ios/test_ios_vlan.py

2018-07-06 20:30 UTC, HD650 commented
@NilashishC Ok, I have added a unittest for vlan start with 9.

2018-07-09 08:55 UTC, NilashishC approved these changes

2018-07-09 13:50 UTC, merged