Add options for jumphost in netconf connetion
ansible/ansible pull request #42271
Opened 2018-07-03 18:29 UTC by ganeshrn

Fixes #37262
Fixes #36284

*  Updates options in netconf connection to enable
   bastion/jump host setting using configuration/enviornment
   varaibles.
*  Update troubleshooting docs from using bastion host with netconf
   connection

##### SUMMARY

##### ISSUE TYPE

 - Feature Pull Request
 - New Module Pull Request
 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME

##### ANSIBLE VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

2018-07-03 19:47 UTC, mattclay commented
The sanity failures are valid. The integration test failures are unrelated and can be ignored.

2018-07-06 19:39 UTC, acozine requested changes
This is great information to have in the documentation. Thanks, Ganesh. Do any other platforms use NETCONF? Or will other platforms use it in future? if not - if this is JunOS-specific information - I'd vote to put it on https://docs.ansible.com/ansible/latest/network/user_guide/platform_junos.html instead of in the troubleshooting guide.

2018-07-11 10:12 UTC, ganeshrn commented
This information is not specific to junos. Currently iosxr platform uses Netconf transport and in future we may add supports for more platforms over netconf.

2018-07-11 10:13 UTC, ganeshrn reviewed
This information is not specific to junos. Currently iosxr platform uses Netconf transport and in future we may add supports for more platforms over netconf.

2018-07-20 16:03 UTC, merged

2018-08-13 04:15 UTC, eraser215 commented
Does this fix now depend on a .ssh/config file to be in place?  I would have expected it to work like regular Linux hosts, with variables set in the inventory:

ansible_ssh_common_args='-o ProxyCommand="ssh <bastion host> netcat %h %p"'

Have I misunderstood?

2018-08-13 04:34 UTC, ganeshrn commented
It requires a ssh config file the path of which can be customised as mentioned in docs. 

Supporting `ansible_ssh_common_args` might require some major changes in the underlying handling netconf connection within Ansible.
https://github.com/ansible/ansible/issues/37262#issuecomment-404549221

2018-08-13 05:19 UTC, benblasco commented
I am having trouble making the work-around work as per the instructions.

Inventory:

```
[test-eas]
test-eas1

[test-eas:vars]
ansible_network_os=junos
ansible_user=admin
ansible_ssh_pass=xxxxx
```

.ssh/config file:

```Host southport-rte1
  Hostname 10.11.21.101
  User sysadmin
  ServerAliveInterval 22

Host southport-rte2
  Hostname 10.11.21.102
  User sysadmin
  ServerAliveInterval 22

Host test-eas1
 Hostname 172.21.4.16
 User admin
 ProxyCommand bash -c "ssh southport-rte1 netcat %h %p || ssh southport-rte2 netcat %h %p" 2>/dev/null
 ServerAliveInterval 22
```

Playbook output:

```fatal: [test-eas1]: FAILED! => {"msg": "[Errno -3] Temporary failure in name resolution"}

SSH from this host:

user@host:~/ansible$ ssh test-eas1
Password:
--- JUNOS 14.1X53-D45.3 built 2017-07-28 03:54:45 UTC
{master:0}

TASK [CONFIGURE SYSLOG TO REMOTE SERVER] **********************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.module_utils.connection.ConnectionError: socket_path does not exist or cannot be found. Please check https://docs.ansible.com/ansible/latest/network/user_guide/network_debug_troubleshooting.html#category-socket-path-issue
fatal: [test-eas1]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_BQx9Jl/ansible_module_junos_logging.py\", line 288, in <module>\n    main()\n  File \"/tmp/ansible_BQx9Jl/ansible_module_junos_logging.py\", line 270, in main\n    with locked_config(module):\n  File \"/usr/lib/python2.7/contextlib.py\", line 17, in __enter__\n    return self.gen.next()\n  File \"/tmp/ansible_BQx9Jl/ansible_modlib.zip/ansible/module_utils/network/junos/junos.py\", line 180, in locked_config\n  File \"/tmp/ansible_BQx9Jl/ansible_modlib.zip/ansible/module_utils/network/junos/junos.py\", line 170, in unlock_configuration\n  File \"/tmp/ansible_BQx9Jl/ansible_modlib.zip/ansible/module_utils/network/junos/junos.py\", line 73, in get_connection\n  File \"/tmp/ansible_BQx9Jl/ansible_modlib.zip/ansible/module_utils/network/junos/junos.py\", line 89, in get_capabilities\n  File \"/tmp/ansible_BQx9Jl/ansible_modlib.zip/ansible/module_utils/connection.py\", line 143, in __rpc__\n  File \"/tmp/ansible_BQx9Jl/ansible_modlib.zip/ansible/module_utils/connection.py\", line 117, in _exec_jsonrpc\nansible.module_utils.connection.ConnectionError: socket_path does not exist or cannot be found. Please check https://docs.ansible.com/ansible/latest/network/user_guide/network_debug_troubleshooting.html#category-socket-path-issue\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
        to retry, use: --limit @/home/eblaben/ansible/rsyslog_junos.retry
```


Please let me know if this is not the appropriate location to be posting this.

Thanks,