Added license_type attribute to azure_rm_virtualmachine module
ansible/ansible pull request #42400
Opened 2018-07-06 06:33 UTC by cperrin88

##### SUMMARY
I added the license_type attribute to azure_rm_virtualmachine module. This makes it possible to change to use the [hybrid benefit licensing for windows server](https://docs.microsoft.com/de-de/azure/virtual-machines/windows/hybrid-use-benefit-licensing)

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
azure_rm_virtualmachine

##### ANSIBLE VERSION

```
ansible 2.6.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/cperrin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### ADDITIONAL INFORMATION
The docuementation for the attribute can be found here: https://docs.microsoft.com/de-de/python/api/azure.mgmt.compute.v2017_12_01.models.virtualmachine?view=azure-python

2018-07-06 07:31 UTC, yuwzho commented
@cperrin88 Thanks for your contribution, seems the `license_type` is an updatable option, would you mind implement the update part?

2018-07-06 08:10 UTC, cperrin88 commented
I will try

2018-07-09 06:42 UTC, cperrin88 commented
I am a bit unsure how to handle the "None" Value that is used in the API. The API expects "None" as a String if the Hybrid Benefit should be disabled.

I have now interpretet None as "None" but I am not sure whether this is okay.

Also the tests for 2.7 and 3.6 fail and I don't understand the error. Maybe someone can explain to me what I did wrong as the code works.

2018-07-09 11:54 UTC, willthames commented
The error is coming from Azure (or at least the python library that is being used):

```
"msg": "Error creating or updating virtual machine testvm002 - Azure Error: InvalidParameter\nMessage: The license type None is invalid. Valid license types are: Windows_Client or Windows_Server, case sensitive.\nTarget: LicenseType"
```

This matches the docs to which you link. `None` is valid, `"None"` is not.

If you don't want to use license_type, don't set it (let it default to `None`, rather than `"None"`).

2018-07-20 06:43 UTC, cperrin88 commented
@yuwzho Is there anything else needed or am I done?

2018-08-14 06:11 UTC, Fred-sun commented
@cperrin88 Thanks for your contribute, @yuwzho Could you help check the contributor's update, Please help confirm whether the PR ready for review? Thanks!

2018-08-15 08:32 UTC, Fred-sun commented
@yuwzho Could you help to take a look this PR? Thanks!

2018-08-15 08:48 UTC, yuwzho approved these changes

2018-08-15 08:49 UTC, yuwzho commented
@Fred-sun Would you like to help test this PR in local environment with create/update/delete in check mode/idempotent/actual action?

2018-08-16 03:09 UTC, yungezz commented
HI @cperrin88 thanks for contribution. could you pls add some tests to cover those new parameters?

2018-08-16 05:58 UTC, Fred-sun commented
@yuwzho @yungezz  test this PR on my VM, get pass result,
playbook:
```e.g.
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}"
      vm_size: Standard_DS1_v2
      license_type: Windows_Server
      os_type: Windows
      admin_username: azureuser
      admin_password: Password@123
      image:
        offer: WindowsServer
        publisher: MicrosoftWindowsServer
        sku: 2012-Datacenter
        version: latest
```
Run result:
```e.g.
ok: [127.0.0.1] => {
    "ansible_facts": {
        "azure_vm": {
            "id": "/subscriptions/2085065b-00f8-4cba-9675-ba15f4d4ab66/resourceGroups/myRG/providers/Microsoft.Compute/virtualMachines/mymv002", 
            "location": "eastus", 
            "name": "mymv002", 
            "powerstate": "running", 
            "properties": {
                "hardwareProfile": {
                    "vmSize": "Standard_DS1_v2"
                }, 
                "instanceView": {
                    "disks": [
                        {
                            "name": "mymv002.vhd", 
                            "statuses": [
                                {
                                    "code": "ProvisioningState/succeeded", 
                                    "displayStatus": "Provisioning succeeded", 
                                    "level": "Info", 
                                    "time": "2018-08-16T05:35:52.110264Z"
                                }
                            ]
                        }
                    ], 
                    "statuses": [
                        {
                            "code": "ProvisioningState/succeeded", 
                            "displayStatus": "Provisioning succeeded", 
                            "level": "Info", 
                            "time": "2018-08-16T05:46:19.310952Z"
                        }, 
                        {
                            "code": "PowerState/running", 
                            "displayStatus": "VM running", 
                            "level": "Info"
                        }
                    ], 
                    "vmAgent": {
                        "statuses": [
                            {
                                "code": "ProvisioningState/succeeded", 
                                "displayStatus": "Ready", 
                                "level": "Info", 
                                "message": "GuestAgent is running and accepting new configurations.", 
                                "time": "2018-08-16T05:48:35.000Z"
                            }
                        ], 
                        "vmAgentVersion": "2.7.41491.875"
                    }
                }, 
                "licenseType": "Windows_Server", 
                "networkProfile": {
                    "networkInterfaces": [
                        {
                            "id": "/subscriptions/2085065b-00f8-4cba-9675-ba15f4d4ab66/resourceGroups/myRG/providers/Microsoft.Network/networkInterfaces/mymv00201", 
                            "name": "mymv00201", 
                            "properties": {
                                "dnsSettings": {
                                    "appliedDnsServers": [], 
                                    "dnsServers": [], 
                                    "internalDomainNameSuffix": "y235fjzcsxeexhwtru0txl5jqb.bx.internal.cloudapp.net"
                                }, 
                                "enableAcceleratedNetworking": false, 
                                "enableIPForwarding": false, 
                                "ipConfigurations": [
                                    {
                                        "etag": "W/\"a08eb46b-1f02-4365-ba4a-9909532745fd\"", 
                                        "id": "/subscriptions/2085065b-00f8-4cba-9675-ba15f4d4ab66/resourceGroups/myRG/providers/Microsoft.Network/networkInterfaces/mymv00201/ipConfigurations/default", 
                                        "name": "default", 
                                        "properties": {
                                            "primary": true, 
                                            "privateIPAddress": "10.0.0.11", 
                                            "privateIPAddressVersion": "IPv4", 
                                            "privateIPAllocationMethod": "Dynamic", 
                                            "provisioningState": "Succeeded", 
                                            "publicIPAddress": {
                                                "id": "/subscriptions/2085065b-00f8-4cba-9675-ba15f4d4ab66/resourceGroups/myRG/providers/Microsoft.Network/publicIPAddresses/mymv00201", 
                                                "name": "mymv00201", 
                                                "properties": {
                                                    "idleTimeoutInMinutes": 4, 
                                                    "ipAddress": "40.121.60.82", 
                                                    "ipConfiguration": {
                                                        "id": "/subscriptions/2085065b-00f8-4cba-9675-ba15f4d4ab66/resourceGroups/myRG/providers/Microsoft.Network/networkInterfaces/mymv00201/ipConfigurations/default"
                                                    }, 
                                                    "ipTags": [], 
                                                    "provisioningState": "Succeeded", 
                                                    "publicIPAddressVersion": "IPv4", 
                                                    "publicIPAllocationMethod": "Static", 
                                                    "resourceGuid": "45dd804b-fad8-4fa7-a638-3e50b57b32e4"
                                                }
                                            }, 
                                            "subnet": {
                                                "id": "/subscriptions/2085065b-00f8-4cba-9675-ba15f4d4ab66/resourceGroups/myRG/providers/Microsoft.Network/virtualNetworks/myVMVNET/subnets/myVMSubnet"
                                            }
                                        }
                                    }
                                ], 
                                "macAddress": "00-0D-3A-1E-65-81", 
                                "networkSecurityGroup": {
                                    "id": "/subscriptions/2085065b-00f8-4cba-9675-ba15f4d4ab66/resourceGroups/myRG/providers/Microsoft.Network/networkSecurityGroups/mymv00201"
                                }, 
                                "primary": true, 
                                "provisioningState": "Succeeded", 
                                "resourceGuid": "b0596b5f-5967-4af7-bc49-0acee087b157", 
                                "virtualMachine": {
                                    "id": "/subscriptions/2085065b-00f8-4cba-9675-ba15f4d4ab66/resourceGroups/myRG/providers/Microsoft.Compute/virtualMachines/mymv002"
                                }
                            }
                        }
                    ]
                }, 
                "osProfile": {
                    "adminUsername": "azureuser", 
                    "computerName": "mymv002", 
                    "secrets": [], 
                    "windowsConfiguration": {
                        "enableAutomaticUpdates": true, 
                        "provisionVMAgent": true
                    }
                }, 
                "provisioningState": "Succeeded", 
                "storageProfile": {
                    "dataDisks": [], 
                    "imageReference": {
                        "offer": "WindowsServer", 
                        "publisher": "MicrosoftWindowsServer", 
                        "sku": "2012-Datacenter", 
                        "version": " [...]

2018-08-16 06:12 UTC, yuwzho commented
shipit

2018-08-16 06:28 UTC, yuwzho commented
@nitzmahone for a further review for the new feature

2018-08-23 09:10 UTC, Fred-sun commented
@nitzmahone could you help review this PR? Thanks!

2018-08-29 05:47 UTC, yungezz approved these changes

2018-08-29 05:48 UTC, yungezz commented
@nitzmahone  could  you pls help to review the PR?

2018-08-29 05:48 UTC, yungezz commented
win_rm part of the PR is duplicate with PR #25251

2018-08-29 12:10 UTC, cperrin88 commented
@yungezz I will try to write tests. I think my PR is a bit better for win_rm.

2018-09-03 01:27 UTC, LeoUfimtsev commented
One of our (red hat) customers was looking for this feature. Would be useful to have it in the next version of ansible.

2018-09-03 01:40 UTC, yungezz commented
@cperrin88  could you pls rebase  the PR? 
@nitzmahone  @jborean93  could you pls help to review the PR? and @kyliel   for awareness.

2018-09-18 07:53 UTC, Fred-sun commented
@nitzmahone @jborean93 could you pls help to review the PR?

2018-09-28 08:45 UTC, Fred-sun commented
@nitzmahone @jborean93

2018-10-24 05:42 UTC, Fred-sun commented
@nitzmahone @jborean93

2018-11-06 07:31 UTC, Fred-sun commented
@cperrin88 Thanks for the contribution, The last time commit fail, Could you help recheck this? Thanks!

2018-11-06 09:09 UTC, cperrin88 commented
@Fred-sun What is the problem? The Ci seems to be okay.

2018-11-06 09:29 UTC, Fred-sun commented
@cperrin88 Thanks for you update, no problem, I will push to merged, Thanks!

2018-11-06 09:31 UTC, Fred-sun commented
@nitzmahone @jborean93 Could you help review this PR and push this to merged? All ready and need you review. Thanks!

2018-11-13 03:31 UTC, Fred-sun commented
@nitzmahone @jborean93 Could you help review this PR and push this to merged? already and need you review. Thanks!

2018-11-22 09:18 UTC, Fred-sun commented
@nitzmahone @jborean93

2018-11-29 05:25 UTC, Fred-sun commented
@yuwzho Could you help push this PR to merged? Thanks!

2018-11-29 05:41 UTC, yungezz commented
@yuwzho  could you help to look at the update?

2018-12-13 02:55 UTC, Fred-sun commented
@yuwzho @nitzmahone @jborean93 Could you help take a look this PR and push for merged? All check pass, waiting merged. Thanks!

2018-12-26 05:34 UTC, Fred-sun commented
@nitzmahone @jborean93

2019-01-09 08:03 UTC, Fred-sun commented
@yungezz @yuwzhou How about the PR going ahead? Could you help push this PR to merge? Thanks!

2019-01-14 08:24 UTC, yungezz commented
need_revision

2019-01-14 08:24 UTC, yungezz commented
pls rebase this PR.

2019-01-14 09:10 UTC, cperrin88 commented
@yungezz No. I opened this MR half a year ago. I rebased it once. This is ridiculous. I'd rather close the MR.

2019-01-14 09:20 UTC, zikalino commented
@cperrin88 would it be ok for you to add me to your fork of ansible. I could rebase this pr and merge it.

2019-01-15 01:43 UTC, yungezz commented
@cperrin88 sorry for late response. Would you like to grant permission of  your repo to me or @zikalino ,  then we can help on the rebase?

2019-01-16 08:44 UTC, cperrin88 commented
I gave @zikalino access.

Am Di., 15. Jan. 2019 um 02:44 Uhr schrieb Yunge Zhu <
notifications@github.com>:

> @cperrin88 <https://github.com/cperrin88> sorry for late response. Would
> you like to grant permission of your repo to me or @zikalino
> <https://github.com/zikalino> , then we can help on the rebase?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ansible/ansible/pull/42400#issuecomment-454236313>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAI3PI9_M0QsIQNPT773Y54kGsAp7t50ks5vDTKagaJpZM4VE89w>
> .
>

2019-01-17 01:54 UTC, yungezz approved these changes

2019-01-17 01:54 UTC, yungezz commented
@nitzmahone  HI Matt, could you pls review this PR since it adding win_rm argument?

2019-01-22 07:01 UTC, Fred-sun commented
@nitzmahone Please help review this PR when you're available. Thanks!

2019-02-01 07:09 UTC, Fred-sun commented
@nitzmahone need you review! Thanks!

2019-02-06 14:42 UTC, rdtechie commented
Any update on this? We're much in need of the licenseType option.

2019-02-07 00:26 UTC, nitzmahone commented
@yungezz IIRC we're waiting for you to ask around internally if the winrm stuff in instance creation was being "soft deprecated" in favor of extensions; I've heard rumblings to that effect, and just want to make sure we're not adding support for something that should be done a different way.

2019-02-15 05:57 UTC, Fred-sun commented
@yungezz Can you help reply to Matt's comments?

2019-02-28 08:32 UTC, Fred-sun commented
@yungezz

2019-03-12 08:15 UTC, Fred-sun commented
@yungezz Please help take a look this issue when you're available! Thanks!

2019-03-18 05:53 UTC, yungezz commented
@nitzmahone  sorry for late response.  I didn't get response from internal, will update here when got it. but after looked at winrm configure doc https://docs.microsoft.com/en-us/azure/virtual-machines/windows/winrm i think it's not deprecated, there's people actively response to it, and the quick start template repo is active https://github.com/Azure/azure-quickstart-templates/tree/master/201-vm-winrm-keyvault-windows. so I think this PR is good to go.

2019-03-18 05:54 UTC, yungezz commented
shipit

2019-03-21 00:16 UTC, nitzmahone commented on lib/ansible/modules/cloud/azure/azure_rm_virtualmachine.py
> +            license_type=dict(type='str', choices=['Windows_Server', 'Windows_Client', 'None']),
We need to fix the `None` handling before merging this

2019-03-21 07:07 UTC, nitzmahone requested changes
need to fix the `None` handling on `license_type`, then good to go (as mentioned in today's IRC meeting)

2019-03-21 07:07 UTC, nitzmahone commented on lib/ansible/modules/cloud/azure/azure_rm_virtualmachine.py
> +    win_rm:
we call this `winrm` everywhere else in Ansible, so might be good to be consistent

2019-04-02 08:10 UTC, rdtechie commented
When will this be merged? I have a need for the license_type and vm_identity options.

2019-04-02 08:37 UTC, yungezz commented
HI @nitzmahone  here's instruction on how to configure winrm on existing machine https://docs.microsoft.com/en-us/windows/desktop/winrm/installation-and-configuration-for-windows-remote-management#quick-default-configuration

2019-04-09 02:47 UTC, Fred-sun commented
@yungezz How to push the PR going ahead? need further review or waiting merge.

2019-04-11 05:27 UTC, yungezz commented
shipit

2019-04-11 05:27 UTC, zikalino commented
shipit

2019-04-11 06:39 UTC, yuwzho commented
shipit

2019-04-11 07:33 UTC, merged

2019-04-11 07:40 UTC, rdtechie commented
Thanks guys, much appreciated!