[WIP]Add net_config module
ansible/ansible pull request #42413
Opened 2018-07-06 09:44 UTC by trishnaguha

Signed-off-by: Trishna Guha <trishnaguha17@gmail.com>

##### SUMMARY

fixes https://github.com/ansible/ansible/issues/39228

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

modules/network/config/net_config.py
##### ANSIBLE VERSION

```
devel
```

2018-07-25 07:30 UTC, ganeshrn commented on lib/ansible/modules/network/cli/cli_config.py
> +    )
You can also add option the enable/disable logging of command and it's response in output using [enable_response_logging](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/cliconf/__init__.py#L159) and [disable_response_logging](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/cliconf/__init__.py#L163) api

2018-08-03 12:11 UTC, Qalthos approved these changes

2018-08-08 05:30 UTC, ganeshrn requested changes

2018-08-08 05:30 UTC, ganeshrn commented on lib/ansible/modules/network/cli/cli_config.py
> +    diff_response = connection.get_diff(**kwargs)
get_diff() need to be called only when device doesn't support on-box diff ie. check for value of `supports_onbox_diff` in device capability.

2018-08-08 05:30 UTC, ganeshrn commented on lib/ansible/modules/network/cli/cli_config.py
> +    diff_response = connection.get_diff(**kwargs)
If device supports onbox diff directly call edit_config() with required parameters the diff part will be taken care by device and if diff is present will be added in the edit_config() resposne

2018-08-09 11:15 UTC, ganeshrn commented on lib/ansible/modules/network/cli/cli_config.py
> +                result['commands'] = resp['diff']
Use module._diff to check if diff is enabled and add the diff to prepared key

2018-08-14 07:26 UTC, ganeshrn approved these changes

2018-08-14 08:22 UTC, merged