Ecs service force new deployment
ansible/ansible pull request #42518
Opened 2018-07-09 15:23 UTC by via

##### SUMMARY
Allow forcing a deployment of an ECS service.

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME
ecs_service

##### ANSIBLE VERSION

```
  config file = /home/via/automation/ansible.cfg
  configured module search path = [u'/home/via/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/via/venv/lib/python2.7/site-packages/ansible
  executable location = /home/via/venv/bin/ansible
  python version = 2.7.9 (default, Apr 27 2015, 17:49:25) [GCC 4.6.3]
```

##### ADDITIONAL INFORMATION
This has the same goal as https://github.com/ansible/ansible/pull/39600 but it seems incomplete and hasn't been updated in some time.

2018-07-09 22:54 UTC, willthames requested changes
Needs tests (see existing tests/integration/targets/ecs_cluster), and to support backward compatibility (don't pass the new parameters if they're not required, and fail gracefully if botocore is too old to support `forceNewDeployment` (older than 1.8.4))

2018-07-18 17:11 UTC, ryansb approved these changes

2018-07-18 17:12 UTC, ryansb commented
Agree with @willthames' review comments, but the code itself looks good so far.

2018-10-29 11:29 UTC, filiptepper commented
@via Any chances you might be submitting suggested changes? I'm happy to try to take this one ever, it would be very useful for us.

2020-08-16 18:44 UTC, closed without merging