added dynamic docker swarm nodes inventory
ansible/ansible pull request #42667
Opened 2018-07-12 08:14 UTC by morph027

##### SUMMARY

This adds a dynamic inventory for docker swarm nodes.

##### ISSUE TYPE

 - Feature Pull Request

##### ANSIBLE VERSION

```
2.5.0
```

2018-12-11 06:46 UTC, DBendit reviewed
Although new modules and plugins don't require changelog fragments, I don't believe dynamic inventory scripts fall into those categories - I'm double checking that in IRC now. If I'm right, then you'll need to include a changelog fragment along with this. See https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#creating-new-fragments for details.

Additionally, Ansible now supports inventory plugins as an alternative to dynamic inventory scripts. See https://docs.ansible.com/ansible/latest/plugins/inventory.html for more details there. It might be a better idea to implement this as an inventory plugin instead, as it has better integration with the rest of Ansible.

2018-12-11 06:46 UTC, DBendit commented on contrib/inventory/docker_swarm_nodes.py
> +# Installation
Could you please wrap the documentation in a `DOCUMENTATION` block, similar to https://github.com/ansible/ansible/blob/devel/contrib/inventory/docker.py?

Additionally, please split into similar sections: general info, requirements, configuration, and examples. I see that you have most of these, but making it more explicit would be helpful for future users.

2018-12-11 17:08 UTC, DBendit requested changes
After checking with the folks in #ansible-devel, it seems that we're no longer accepting new inventory scripts. Please re-write this as an inventory plugin instead. See the link above for more information on that.

needs_revision

2018-12-12 07:49 UTC, morph027 commented
Okay, thanks for your feedback ;)

2019-01-14 11:37 UTC, gundalow commented
@morph027 Hi, Are you able to rewrite this as an inventory plugin

https://docs.ansible.com/ansible/devel/dev_guide/developing_inventory.html#inventory-plugins https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/inventory/

2019-01-14 12:53 UTC, morph027 commented
Will try, if i can make up some spare time ;)

2019-02-13 18:41 UTC, gundalow commented
@morph027 Please do shout out if you need any help with this. Their is an active Docker community at Ansible

2019-02-13 19:47 UTC, morph027 commented
I've got 2 weeks vacation next week, with sun and fun. Guess, there will be some time. Docker is no problem, just need to adjust my poor coding skills to the guidelines ;)

2019-02-27 12:00 UTC, morph027 commented
moved to https://github.com/ansible/ansible/pull/53058

2019-02-27 12:00 UTC, closed without merging