VMware: dns_suffix as a list of domain suffixes
ansible/ansible pull request #42678
Opened 2018-07-12 11:40 UTC by Akasurde

##### SUMMARY
This fix adds dns_suffix as a list of domain suffixes and
also updates documentation and example.

Fixes: #42229

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME
lib/ansible/modules/cloud/vmware/vmware_guest.py

##### ANSIBLE VERSION

```
2.7-devel
```

2018-07-17 03:54 UTC, Akasurde commented
@dericcrago @pdellaert @dagwieers Could you please review this ?

2018-07-17 12:50 UTC, dagwieers requested changes
Only a single remark.

2018-07-17 12:50 UTC, dagwieers commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +          Also accepts space separated domain suffixes.'
I would not advertise space-delimited lists as this is only for backward compatibility. We don't want to offer people this choice, only support people that did not have the choice before. I would even deprecate space-delimited lists over time.

2018-07-17 12:51 UTC, dagwieers commented
Over time we should use suboptions and argspec options.

2018-07-17 12:51 UTC, dagwieers commented
Should we add/update tests ?

2018-07-17 13:28 UTC, Akasurde commented
@dagwieers VCSIM does not support customisation (yet) so I don't think so we can add/update any test.

2018-07-17 13:35 UTC, Akasurde commented
@dagwieers I removed the doc update. Please take a look.

2018-07-17 14:05 UTC, dagwieers approved these changes
Looking good mostly. Only some notes on cosmetic changes for consistent documentation/examples.

2018-07-17 14:05 UTC, dagwieers commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +    validate_certs: False
We standardized to using yes/no booleans in documentation (mostly because it is easier to read and reflects programming less).

2018-07-17 14:05 UTC, dagwieers commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +    folder: "/{{datacenter}}/vm"
No need to quote strings here.

2018-07-17 14:05 UTC, dagwieers commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +    cluster: "DC1_C1"
No need to quote strings here.

2018-07-17 14:05 UTC, dagwieers commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +      - name: "VM Network"
No need to quote strings here.

2018-07-17 21:49 UTC, dagwieers approved these changes
LGTM

2018-07-17 21:49 UTC, dagwieers commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +    wait_for_ip_address: True
We standardized to using yes/no booleans in documentation (mostly because it is easier to read and reflects programming less).

2018-07-17 21:53 UTC, merged

2018-07-18 03:45 UTC, Akasurde commented
@dagwieers Thanks for the reviews.

2018-07-18 14:12 UTC, dagwieers commented
@akasurde You're welcome. I hadn't expected @ansibot to automerge. I still don't know when exactly automerge is activated and when not...