Add module asa_user for Cisco ASA user management
ansible/ansible pull request #42962
Opened 2018-07-18 16:21 UTC by sts

##### SUMMARY

Adds a network module for user management on Cisco ASA devices.

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
asa_user

##### ANSIBLE VERSION
```
2.6.1
```

2018-08-03 07:09 UTC, gdpak reviewed
Thanks @sts for your contributions.
Can you also add integrations test for this module ?

2018-08-03 07:09 UTC, gdpak commented on lib/ansible/modules/network/asa/asa_user.py
> +            if item != 'admin':
while purging all username we should preserve the username which is used to run the playbook otherwise we might hit connection timeout in middle and leave the box with partial configurations

2019-04-01 10:47 UTC, NilashishC requested changes
Since this is a new module, could you please add some tests (unit or integration) for it?

2020-05-27 13:51 UTC, danielmellado commented
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/cisco.asa
Please re-submit this PR in the above repository.
If you have further questions please stop by IRC or the mailing list:

IRC: #ansible-network on irc.freenode.net
mailing list: https://groups.google.com/forum/#!forum/ansible-project

2020-05-27 13:51 UTC, closed without merging