elb_application_lb purge rules option
ansible/ansible pull request #43113
Opened 2018-07-20 21:27 UTC by mjmayer

##### SUMMARY
Adds the ability to leave existing rules in place on an ELB.
Fixes #43109

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
elb_application_lb

##### ANSIBLE VERSION

```
ansible 2.7.0.dev0 (detached HEAD f6160c675d) last updated 2018/07/20 18:28:16 (GMT +000)
  config file = /home/vagrant/.ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/vagrant/ansible/lib/ansible
  executable location = /home/vagrant/ansible/bin/ansible
  python version = 2.7.15 (default, May  9 2018, 11:32:33) [GCC 7.3.1 20180130 (Red Hat 7.3.1-2)]
```

2018-07-24 00:07 UTC, s-hertel approved these changes

2018-07-24 04:30 UTC, willthames requested changes

2018-07-24 04:30 UTC, willthames commented on lib/ansible/modules/cloud/amazon/elb_application_lb.py
> +      - Keeps the existing load balancer rules in place. Will modify and add, but will not delete.
This description reads as if setting `purge_rules` to `yes` would keep the existing load balancer rules in place. 

Perhaps just prefix it with 'When set to no, keep the existing...'

2018-07-25 09:51 UTC, wimnat approved these changes

2018-07-25 10:54 UTC, willthames approved these changes

2018-07-25 10:55 UTC, willthames commented
Merged, thanks @mjmayer

2018-07-25 10:55 UTC, merged