Detect failed sysvinit module
ansible/ansible pull request #43127
Opened 2018-07-22 10:33 UTC by Uwila

##### SUMMARY

The rationale for this change was to close #42957

- This checks the stderr instead of the rc to detect whether the
  sysvinit module was successful or not, as even when failing, the
  rc would be 0.

- It immediatly became obvious that the debug info when failing
  was far too little to properly debug the role. To improve this,
  I also added the rc, stderr and stdout to the debug output.

Fixes #42957
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

`sysvinit` (module)

##### ANSIBLE VERSION

```
ansible 2.7.0.dev0 (detect-failed-sysvinit 0f49244c8b) last updated 2018/07/22 12:28:39 (GMT +200)
  config file = None
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/documents/programming/ansible/lib/ansible
  executable location = /home/user/.venv/bin/ansible
  python version = 3.6.6 (default, Jun 27 2018, 13:11:40) [GCC 8.1.1 20180531]
```

2018-07-22 19:16 UTC, sivel commented
I don't think this is the correct route forward.  init scripts may print non error related info to stderr.

This indicates a poorly written init script, that should be adjusted to fail with a non zero exit code.

2018-07-23 14:20 UTC, bcoca requested changes
I agree with @sivel, the standard requires non 0 rc, while it allows info/debug information to go to stderr w/o indicating a failure.

This is an issue with the init script and not the module.

2018-07-23 14:22 UTC, bcoca commented
As for the extra return data, that is OK.

One workaround is using `failed_when` for non compliant init scripts.

2018-07-23 14:22 UTC, bcoca commented on lib/ansible/modules/system/sysvinit.py
> +                module.fail_json(msg="Failed to %s service: %s" % (action, name), rc=rc, out=out, err=err)
i would uset stdout and stderr as these are how we commonly name these fields in other modules.

2018-07-23 15:08 UTC, Uwila commented
@bcoca so close #43127 then?

2018-07-23 15:10 UTC, bcoca commented
no, the extra return data on fail_json seems fine, allows you to manage the task result better to compensate for bad init scripts

2018-07-23 15:12 UTC, Uwila commented
Sorry, my bad, I meant #42957

2018-07-23 15:22 UTC, bcoca commented
oh, yeah, in that case it clearly is a bug in the init script, not the module

2018-07-23 15:30 UTC, bcoca approved these changes

2018-07-23 23:50 UTC, achinthagunasekara approved these changes

2018-07-23 23:58 UTC, merged