New option for module 'user'
ansible/ansible pull request #43169
Opened 2018-07-23 20:48 UTC by madejusz

##### SUMMARY
New option for module 'user' allow define uid range within new user will be create. This is option can be use in any way, when service/application uid account maybe defined in specific uid range.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
module user
##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = /home/madej/.ansible.cfg
  configured module search path = [u'/home/madej/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### ADDITIONAL INFORMATION
user module allow define new value: uid_min and uid_max and new user UID will be assigned from this, user defined range. 

```

```

2020-05-27 16:01 UTC, samdoran requested changes
Please create a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment) and integration tests. See [this fragment](https://github.com/ansible/ansible/blob/c2f528b7686c9573aa8493357219e0bbe4416dd3/changelogs/fragments/reboot-change-default-boot-command.yaml) as an example.

2020-05-27 16:01 UTC, samdoran commented on lib/ansible/modules/system/user.py
> +        if self.uid_min is not None and self.uid_max is not None:
Since both parameters are required on BSD, we need to add a failure here if both are not specified.

2020-05-27 16:01 UTC, samdoran commented on lib/ansible/modules/system/user.py
> +            cmd.append(self.uid_max)
I'm not sure this is the correct way to do this for OpenBSD. The [man page I found](https://man.openbsd.org/useradd.8) seems to use the `-r min..max` syntax.

2020-05-27 16:01 UTC, samdoran commented on lib/ansible/modules/system/user.py
> +        version_added: "2.7"
The documentation for these new options needs to explain on what platforms it is supported, that it only matters on user creation, and that for BSD, both are required.

2022-01-26 19:58 UTC, jborean93 commented
Closing due to the conflicts and age of the PR. There were also concerns around cross platform support with these options. If this is still something you wish to continue with I recommend going to our IRC channels or mailing list to talk about this further. More details on these channels are documented at https://docs.ansible.com/ansible/latest/community/communication.html.

2022-01-26 19:58 UTC, closed without merging