Fix referenced before assignment in role requirements
ansible/ansible pull request #43306
Opened 2018-07-26 12:48 UTC by robert-bo-davis

##### SUMMARY
If the SCM provider is missing during role require, `run_scm_cmd()` throws an uncaught Unbound exception error:

```
ERROR! Unexpected Exception, this is probably a bug: local variable 'stdout' referenced before assignment
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-galaxy", line 118, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/site-packages/ansible/cli/galaxy.py", line 152, in run
    self.execute()
  File "/usr/lib/python2.7/site-packages/ansible/cli/__init__.py", line 155, in execute
    fn()
  File "/usr/lib/python2.7/site-packages/ansible/cli/galaxy.py", line 395, in execute_install
    installed = role.install()
  File "/usr/lib/python2.7/site-packages/ansible/galaxy/role.py", line 200, in install
    tmp_file = RoleRequirement.scm_archive_role(keep_scm_meta=self.options.keep_scm_meta, **self.spec)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/role/requirement.py", line 208, in scm_archive_role
    run_scm_cmd(clone_cmd, tempdir)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/role/requirement.py", line 197, in run_scm_cmd
    display.debug("\tstdout: " + stdout)
UnboundLocalError: local variable 'stdout' referenced before assignment
```

##### ISSUE TYPE
Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/playbook/role/requirement.py

##### ANSIBLE VERSION
```
2.6.1
```

##### ADDITIONAL INFORMATION
```

```

2018-07-26 13:55 UTC, bcoca requested changes

2018-07-26 13:55 UTC, bcoca commented on lib/ansible/playbook/role/requirement.py
> +                stderr = None
this will create a concatenation error if they are still 'None' in the exception handling, initialize as '' (empty string)

2018-07-26 16:19 UTC, bcoca approved these changes

2018-08-01 20:48 UTC, merged

2018-11-07 22:02 UTC, jamescassell commented
Any chance of backporting this to 2.6?