[WIP] adding postgresql server facts
ansible/ansible pull request #43328
Opened 2018-07-26 21:01 UTC by zikalino

##### SUMMARY
Adding missing PostgreSQL server facts.

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
azure_rm_postgresqlserver_facts

##### ANSIBLE VERSION
2.6

##### ADDITIONAL INFORMATION

2018-08-08 23:53 UTC, nitzmahone requested changes
A couple minor docs tweaks and this one's good to go

2018-08-08 23:53 UTC, nitzmahone commented on lib/ansible/modules/cloud/azure/azure_rm_postgresqlserver_facts.py
> +    server_name:
Let's just standardize on `resource_group` and `name` for these (feel free to leave `server_name` as an alias though); the resource type should already be clear from the module name in a playbook context

2018-08-08 23:53 UTC, nitzmahone commented on lib/ansible/modules/cloud/azure/azure_rm_postgresqlserver_facts.py
> +            sample: user_visible_state
not sure what this is?

2018-08-08 23:53 UTC, nitzmahone commented on lib/ansible/modules/cloud/azure/azure_rm_postgresqlserver_facts.py
> +            sample: fully_qualified_domain_name
real sample value

2018-08-08 23:53 UTC, nitzmahone commented on lib/ansible/modules/cloud/azure/azure_rm_postgresqlserver_facts.py
> +            sample: version
real sample value

2018-08-08 23:53 UTC, nitzmahone commented on lib/ansible/modules/cloud/azure/azure_rm_postgresqlserver_facts.py
> +                        - The scale capacity."
spurious quote?

2018-08-08 23:53 UTC, nitzmahone commented on lib/ansible/modules/cloud/azure/azure_rm_postgresqlserver_facts.py
> +            sample: onebox
real sample location?

2018-08-10 00:16 UTC, mattclay commented
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/77921/75/tests

2018-08-14 08:15 UTC, Fred-sun commented
@zikalino has fixed test according with comment. @mattclay @nitzmahone Could you help review again？ Thanks!

2018-08-15 05:39 UTC, Fred-sun commented
@mattclay @nitzmahone Thanks for your contribution, Could you help review again？

2018-08-16 02:28 UTC, yungezz commented on lib/ansible/modules/cloud/azure/azure_rm_postgresqlserver_facts.py
> +short_description: Get PostgreSQL Server facts.
azure

2018-08-16 02:29 UTC, yungezz commented on lib/ansible/modules/cloud/azure/azure_rm_postgresqlserver_facts.py
> +        if (self.resource_group is not None and
how to get per tags?

2018-08-16 02:29 UTC, yungezz commented on lib/ansible/modules/cloud/azure/azure_rm_postgresqlserver_facts.py
> +        self.mgmt_client = self.get_mgmt_svc_client(PostgreSQLManagementClient,
pls, put all managemt  client into azure_rm_common

2018-08-16 02:52 UTC, yungezz commented on lib/ansible/modules/cloud/azure/azure_rm_postgresqlserver_facts.py
> +            ansible_facts=dict()
ansible_facts?

2018-08-16 06:54 UTC, yungezz approved these changes

2018-08-16 06:54 UTC, yungezz commented
shipit

2018-08-16 06:55 UTC, zikalino commented
shipit

2018-08-17 08:23 UTC, Fred-sun commented
@nitzmahone Could you help review this PR? Thanks!

2018-08-21 09:59 UTC, Fred-sun commented
@nitzmahone Could you help review this PR? Thanks!

2018-08-22 22:17 UTC, nitzmahone approved these changes

2018-08-22 22:18 UTC, merged