[git] Better filtering of unknown files.
ansible/ansible pull request #43359
Opened 2018-07-27 14:14 UTC by ElectronicRU

Reopening #4763 as it got lost in time.

##### SUMMARY
If the only thing that interests us is if there are any changed files in
the repository, we can circumvent
parsing git status output.
Instead of capturing, splitting and regexp filtering unknown files, it's
much easier to just tell git to ignore them.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
Ansible core modules

##### ANSIBLE VERSION
```
ansible 2.2.0
  config file = 
  configured module search path = Default w/o overrides
```

2018-07-27 18:46 UTC, achinthagunasekara approved these changes

2018-07-31 11:17 UTC, ElectronicRU commented
Any updates re: status?

2018-09-16 13:18 UTC, mscherer commented
So, I didn't look, but that is portable for all git version ?

2018-10-08 21:38 UTC, maxamillion commented
I'm also curious about how portable that option is.

needs_info

2018-11-29 14:02 UTC, gundalow requested changes
Do we know when `--untracked-files=no` was added and if Git on all major Operating Systems supports it?

2018-12-15 06:35 UTC, closed without merging