Fileglob: support wildcard directories
ansible/ansible pull request #43393
Opened 2018-07-28 19:50 UTC by monoflo

##### SUMMARY

Modified `run` so that fileglob supports wildcards in directories.
Accomplished by removing `find_file_in_search_path` from `run`.

Fixes ansible/ansible#17136

##### ISSUE TYPE

Bugfix Pull Request

##### COMPONENT NAME

fileglob (lookup plugin)
##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/monoflo/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

2018-07-29 13:39 UTC, monoflo commented
I don't believe the failed check has anything to do with my contribution.

80 / 84 environments succeed. The four that do not report the same issues:

### Failures
**apt-amdrie90 / /root/ansible/test/integration/targets/apt/tasks/repo.yml:2 / [testhost] testhost: apt : Install foo package version 1.0.0 allow_unauthenticated=True, name=foo=1.0.0**

*failure: No package matching 'foo' is available*

### Errors
**apt-1etzmtil / /root/ansible/test/integration/targets/apt/tasks/repo.yml:2 / [testhost] testhost: apt : Install foo package version 1.0.0 name=foo=1.0.0, allow_unauthenticated=True**

*error: raise KeyError('The cache has no package named %r' % key)*

### Details
https://app.shippable.com/github/ansible/ansible/runs/76286/summary/console

2018-07-30 10:29 UTC, monoflo commented
@nitzmahone, would you care to review, given your involvement with the issue?
https://github.com/ansible/ansible/issues/17136

2018-09-04 23:20 UTC, mattclay commented
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/82500/41/tests

The affected playbook code is probably this:

https://github.com/ansible/ansible/blob/296ad80002880d7f7be9829d736c2327fe01998d/test/integration/targets/setup_deb_repo/tasks/main.yml#L23

2018-09-05 15:37 UTC, bcoca requested changes
This ignores 'dwimed' paths so relative files will only be searched in relation to CWD but not in playbook/role contexts.

2020-04-03 15:37 UTC, relrod commented
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us that you've taken time to contribute.

Unfortunately, we're not sure if we want this feature in the program, and I don't want this to seem confrontational.  Our reasons for this are:

   * Use the `filetree` lookup instead.

However, we're absolutely always up for discussion.  Since this is a really busy project, we don't always see comments on closed tickets, but want to encourage
open dialog.  You can stop by the development list, and we'd be glad to talk about it - and we might even be persuaded otherwise!

   * https://groups.google.com/forum/#!forum/ansible-devel

In the future, sometimes starting a discussion on the development list prior to implementing a feature can make getting things included a little easier, but it's not always necessary.

Thank you once again for this and your interest in Ansible!

2020-04-03 15:37 UTC, closed without merging