modules/terraform: Quote the variable values in the command line
ansible/ansible pull request #43493
Opened 2018-07-31 15:00 UTC by rrey

##### SUMMARY
The variables values are not quoted and it can result in an interpretation by the shell during command line execution.
Example of possible failure available in #43492

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME
terraform.py

##### ANSIBLE VERSION

```
ansible 2.6.0
  config file = /Users/remirey/dev/grtgaz/avignon/ansible.cfg
  configured module search path = [u'/Users/remirey/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/remirey/.virtualenvs/avignon/lib/python2.7/site-packages/ansible
  executable location = /Users/remirey/.virtualenvs/avignon/bin/ansible
  python version = 2.7.13 (default, Jul 18 2017, 09:17:00) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

##### ADDITIONAL INFORMATION

Fixes: #43492

2018-07-31 15:01 UTC, rrey commented
cc @ryansb

2018-07-31 15:32 UTC, ryansb requested changes

2018-07-31 15:32 UTC, ryansb commented on lib/ansible/modules/cloud/misc/terraform.py
> +            '{0}="{1}"'.format(k, v)
Hm, quoting was a major oversight when I wrote this module. Thanks for catching it! I have some thoughts on how to make this better: first, we want to quote the full value (before and after the `=`), and second I think a value might also contain quotes such as if the variable contents is a bash command for some reason.

To best handle this, we should use the `shlex` library's quote function. But to work on both python 2 and 3 we'd need `from six.moves import shlex_quote` and then this line could be:

`shlex_quote('{0}={1}'.format(k, v))`

2018-08-09 16:05 UTC, rrey commented
Hi @ryansb,

I did the suggested change.

I'm a bit worried that the module is not covered with tests, or at least I don't see were the tests are.
Is there a documentation about how a contributor can add tests in the ansible project ?

2018-08-27 18:37 UTC, ryansb approved these changes

2018-08-27 18:38 UTC, ryansb commented
@rrey there aren't integration tests right now, but I'd be very open to adding some.

2018-08-27 18:38 UTC, merged