Deprecate dest with uri module. get_url should be used instead
ansible/ansible pull request #43545
Opened 2018-08-01 14:15 UTC by sivel

##### SUMMARY
Deprecate dest with uri module. get_url should be used instead

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
lib/ansible/modules/net_tools/basic/uri.py

##### ANSIBLE VERSION

```
2.7
```

##### ADDITIONAL INFORMATION

```

```

2018-08-01 23:57 UTC, jamescassell approved these changes

2018-08-02 07:25 UTC, jborean93 requested changes
Are you able to add the deprecation info to the module doc entry as well as to the porting guide.

2018-08-02 13:04 UTC, sivel commented
> Are you able to add the deprecation info to the module doc entry as well as to the porting guide.

yes, sorry there are a few other things I want to look into as well.

2018-08-02 13:19 UTC, sivel commented
I may not continue with this.  It's been on my mind for a while, but the thing I haven't taken into account is whether something like a `POST` request is required to download the file.  `get_url` only performs `GET` requests.

2018-08-06 16:03 UTC, sivel commented
Not going to proceed with this, due to the above described shortcoming of `get_url`.

2018-08-06 16:03 UTC, closed without merging