elb_target_facts Fixes #39780
ansible/ansible pull request #43565
Opened 2018-08-01 19:21 UTC by yaakov-github

##### SUMMARY

Fixes #39780 

Adds an 'elb_target_facts' module which will gather a list of all target groups to which a given instance is registered, covering both IP and instance target groups.  This is added to a fact called 'ec2_tgs', which can be used by a playbook to change deregister/reregister nodes to the target groups.

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME

lib/ansible/modules/cloud/amazon/elb_target_facts.py

##### ANSIBLE VERSION

```
ansible 2.7.0.dev0 (elb_target_facts f4d8b185f4) last updated 2018/08/01 14:26:26 (GMT -400)
  config file = None
  configured module search path = [u'/Users/ykuperman/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/ykuperman/code/ansible_devel/lib/ansible
  executable location = /Users/ykuperman/code/ansible_devel/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]

```

##### ADDITIONAL INFORMATION

```

localhost | SUCCESS => {
    "ansible_facts": {
        "ec2_tgs": [
            {
                "target_group_arn": "<arn>", 
                "target_group_type": "instance", 
                "targets": [
                    {
                        "target_az": null, 
                        "target_health": {
                            "description": "Health checks failed", 
                            "reason": "Target.FailedHealthChecks", 
                            "state": "unhealthy"
                        }, 
                        "target_id": "i-0289cbd5cc4f5f458", 
                        "target_port": 8081
                    }, 
                    {
                        "target_az": null, 
                        "target_health": {
                            "description": "Health checks failed", 
                            "reason": "Target.FailedHealthChecks", 
                            "state": "unhealthy"
                        }, 
                        "target_id": "i-0289cbd5cc4f5f458", 
                        "target_port": 8080
                    }
                ]
            }, 
            {
                "target_group_arn": "<arn>", 
                "target_group_type": "ip", 
                "targets": [
                    {
                        "target_az": "us-west-2a", 
                        "target_health": {
                            "state": "healthy"
                        }, 
                        "target_id": "172.31.22.138", 
                        "target_port": 22
                    }, 
                    {
                        "target_az": "us-west-2a", 
                        "target_health": {
                            "state": "healthy"
                        }, 
                        "target_id": "172.31.24.19", 
                        "target_port": 22
                    }
                ]
            }
        ]
    }, 
    "changed": false
}
```

2018-08-22 23:32 UTC, willthames commented
Let's not use ansible_facts. Just return a dict containing instance_target_groups or something

2018-08-22 23:36 UTC, willthames commented on lib/ansible/modules/cloud/amazon/elb_target_facts.py
> +    if not HAS_BOTO3:
Not needed with AnsibleAWSModule

2018-08-22 23:36 UTC, willthames commented on lib/ansible/modules/cloud/amazon/elb_target_facts.py
> +            ec2 = self.module.client(
I really don't see the point of using a class if you're just going to create the client inside methods! 

I'd create the ec2 and elbv2 clients at `__init__` time and just use self.ec2 in the methods

2018-08-23 15:55 UTC, ryansb requested changes
Minor style change needed, looks good otherwise.

2018-08-23 15:55 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/elb_target_facts.py
> +ec2_tgs:
`ec2_tags`

2018-08-23 15:55 UTC, ryansb commented on lib/ansible/modules/cloud/amazon/elb_target_facts.py
> +class Target:
These declarations need to be new-style classes like `Target(object):`

2018-08-30 14:46 UTC, ryansb approved these changes

2018-08-30 14:47 UTC, merged

2018-08-30 15:19 UTC, arbabnazar commented
@ryansb will it be available for 2.6 future release or 2.7.0?

2018-08-30 15:21 UTC, ryansb commented
2.7 is the targeted release for this.

2018-08-30 22:15 UTC, willthames commented
You can use it with 2.6 though: http://willthames.github.io/2017/12/12/using-updated-modules-with-stable-ansible.html