Ucs disk group policy
ansible/ansible pull request #43578
Opened 2018-08-01 21:35 UTC by dsoper2

##### SUMMARY

Disk group policy config for manual and automatic config

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

ucs_disk_group_policy
##### ANSIBLE VERSION

```
ansible 2.7.0.dev0 (ucs_disks a28c2fec2c) last updated 2018/08/01 16:31:32 (GMT -500)
  config file = /Users/dsoper/.ansible.cfg
  configured module search path = [u'/Users/dsoper/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/dsoper/Documents/ansible/lib/ansible
  executable location = /Users/dsoper/Documents/ansible/bin/ansible
  python version = 2.7.12 (default, Oct 11 2016, 05:20:59) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)]
```

##### ADDITIONAL INFORMATION

```

```

2018-08-09 07:04 UTC, SDBrett commented
JBOD options need to be removed as it raises an exception and not needed for the creation of disk group policies.

Error: "msg": "setup error: [ErrorCode]: ERR-xml-parse-error[ErrorDescription]: XML PARSING ERROR: unknown attribute 'useJbodDisks' in element 'lstorageDiskGroupQualifier' "

2018-08-09 07:05 UTC, SDBrett requested changes
Bug in code with JBOD options.

2018-08-23 09:01 UTC, dagwieers requested changes

2018-08-23 09:01 UTC, dagwieers commented on lib/ansible/modules/remote_management/ucs/ucs_disk_group_policy.py
> +      If C(absent), will verify that the disk group policy is absent and will delete if needed.
Make this 2 items in the description.
Also, the first line should explain what the parameter is about.
(In the future we may want to highlight the first line in the documentation)

2018-08-23 09:01 UTC, dagwieers commented on lib/ansible/modules/remote_management/ucs/ucs_disk_group_policy.py
> +    - Option applies when configuration mode is automatic. Specify the number of drives for the disk group. This can be from 0 to 24.
Same here, the first line should give information what the parameter is about. Subsequent lines clarify the value and dependencies. So in this case you'd have at least 3 items in the description.

2018-08-23 09:01 UTC, dagwieers commented on lib/ansible/modules/remote_management/ucs/ucs_disk_group_policy.py
> +    default: '1'
Why a string ?

2018-08-23 09:01 UTC, dagwieers commented on lib/ansible/modules/remote_management/ucs/ucs_disk_group_policy.py
> +    - Option applies when configuration mode is automatic. Specify the number of drives for the disk group. This can be from 0 to 24.
Do the same for the following options too.

2018-08-23 09:01 UTC, dagwieers commented on lib/ansible/modules/remote_management/ucs/ucs_disk_group_policy.py
> +    suboptions:
I understand what you're trying to do here, but managing both parent as child objects in a single module is going to be problematic IMO. This can only work if your childs are always fully listed (and replaced/updated).

2018-08-23 09:01 UTC, dagwieers commented on lib/ansible/modules/remote_management/ucs/ucs_disk_group_policy.py
> +                        choices=["1024KB", "128KB", "16KB", "256KB", "32KB", "512KB", "64KB", "8KB",
In the metric system, 'kilo' is abbreviated as 'k'. I guess this is wrong in the UCS interface though.

2018-08-28 20:40 UTC, dsoper2 commented on lib/ansible/modules/remote_management/ucs/ucs_disk_group_policy.py
> +    suboptions:
This is done to match what's in the UI with ability to add/remove and we have present/absent on the individual disks.

2018-08-28 20:40 UTC, dsoper2 commented on lib/ansible/modules/remote_management/ucs/ucs_disk_group_policy.py
> +                        choices=["1024KB", "128KB", "16KB", "256KB", "32KB", "512KB", "64KB", "8KB",
The KB does match the UI and strings expected by the API.

2018-08-28 20:46 UTC, dsoper2 commented on lib/ansible/modules/remote_management/ucs/ucs_disk_group_policy.py
> +      If C(absent), will verify that the disk group policy is absent and will delete if needed.
Fixed

2018-08-28 20:47 UTC, dsoper2 commented on lib/ansible/modules/remote_management/ucs/ucs_disk_group_policy.py
> +    - Option applies when configuration mode is automatic. Specify the number of drives for the disk group. This can be from 0 to 24.
Fixed

2018-08-28 20:47 UTC, dsoper2 commented on lib/ansible/modules/remote_management/ucs/ucs_disk_group_policy.py
> +    default: '1'
Fixed - arg spec sets to string for API use but can be a number in the play

2018-08-28 21:31 UTC, SDBrett commented on lib/ansible/modules/remote_management/ucs/ucs_disk_group_policy.py
> +                        choices=["1024KB", "128KB", "16KB", "256KB", "32KB", "512KB", "64KB", "8KB",
The case for the strips was derived from the object class in ucsmsdk.

2018-08-28 21:41 UTC, dagwieers commented on lib/ansible/modules/remote_management/ucs/ucs_disk_group_policy.py
> +                        choices=["1024KB", "128KB", "16KB", "256KB", "32KB", "512KB", "64KB", "8KB",
I expected that much.

2018-08-28 21:42 UTC, dagwieers commented on lib/ansible/modules/remote_management/ucs/ucs_disk_group_policy.py
> +    default: '1'
Ah, right.

2018-08-29 03:41 UTC, dagwieers commented on lib/ansible/modules/remote_management/ucs/ucs_disk_group_policy.py
> +    suboptions:
Looking for outside counsel on this one ;-)

2018-11-14 02:24 UTC, movinalot approved these changes
shipit

2018-11-19 11:42 UTC, dagwieers approved these changes

2018-11-20 12:34 UTC, merged