Fix openstack inventory plugin
ansible/ansible pull request #43581
Opened 2018-08-01 22:52 UTC by emonty

##### SUMMARY
The inventory plugin api grew a self.cache that wasn't there when we
first wrote it. There's also a need to pull in the documentation
fragments so that we have the cache parameters.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/plugins/inventory/openstack.py

##### ANSIBLE VERSION
```
ansible 2.6.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.5 (default, Apr  1 2018, 05:46:30) [GCC 7.3.0]

```

2018-08-13 22:05 UTC, mattclay commented
Commit https://github.com/ansible/ansible/pull/43581/commits/33a3921e4ddf3327e96f993585c3174bc413287f is a backport of https://github.com/ansible/ansible/pull/41664

Commit https://github.com/ansible/ansible/pull/43581/commits/19f601724ed6ba939ef5b7df6f8fad05c5ecd4a2 does not exist in devel

@emonty The changes in https://github.com/ansible/ansible/pull/43581/commits/19f601724ed6ba939ef5b7df6f8fad05c5ecd4a should be merged to devel before this backport can be merged.

2018-08-13 22:12 UTC, mattclay requested changes
Once the changes in https://github.com/ansible/ansible/pull/43581/commits/19f601724ed6ba939ef5b7df6f8fad05c5ecd4a2 have been merged to devel, comment on this PR with a link to the new PR or the merged commit so the backport can proceed.

2018-08-17 11:30 UTC, emonty commented
@mattclay The change has now been merged into master https://github.com/ansible/ansible/commit/e89e4c991c3ecda187e81d4241096efa60209d93

2018-09-04 22:38 UTC, mattclay approved these changes

2018-09-04 22:39 UTC, merged