Give warning if user inputs not encrypted password to user module
ansible/ansible pull request #43615
Opened 2018-08-02 18:39 UTC by HD650

##### SUMMARY

`user` module doesn't check the input password and return very little information if users input unencrypted password (which is wrong), it's hard for users to figure out what's wrong. This PR check the format of the input password and give a warning if the password is not encrypted.
Fix #28772

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

/lib/ansible/modules/system/user.py
##### ANSIBLE VERSION

```
ansible 2.7.0.dev0 (issue_28772 f5fa73be30) last updated 2018/08/02 13:59:35 (GMT -400)
  config file = None
  configured module search path = [u'/home/zhikangzhang/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/zhikangzhang/Desktop/ansible/lib/ansible
  executable location = /home/zhikangzhang/Desktop/ansible/bin/ansible
  python version = 2.7.15 (default, May 16 2018, 17:50:09) [GCC 8.1.1 20180502 (Red Hat 8.1.1-1)]

2018-08-02 21:07 UTC, samdoran commented on lib/ansible/modules/system/user.py
> +                self.module.warn("The iunput password seems not been hashed, "
"iunput" --> "input"

2018-08-02 21:09 UTC, samdoran commented
This is a very nice sanity check. Can you add some integration tests for this as well?

2018-08-03 20:54 UTC, samdoran commented
Tests look good. Thanks! Please create a changelog fragment and I'll get this merged (sorry I forgot to mention that earlier). See [fragments](https://github.com/ansible/ansible/tree/stable-2.6/changelogs/fragments) for examples.

2018-08-07 18:29 UTC, HD650 commented
@samdoran I have created a changelog fragment, could you review again? Thanks!

2018-08-07 21:34 UTC, ericwb requested changes

2018-08-07 21:34 UTC, ericwb commented on lib/ansible/modules/system/user.py
> +                                 "please note that 'password' argument requires an encrypted value or the password will not work properly.")
The English on this sentence needs to be reworked.  "The input password appears not to have been hashed."  "The 'password' argument must be encrypted for this module to work properly."

2018-08-07 21:34 UTC, ericwb commented on lib/ansible/modules/system/user.py
> +                    # contains character outside crypt constrain
"outside the crypto constraint"

2018-08-07 21:34 UTC, ericwb commented on lib/ansible/modules/system/user.py
> +            # these character are invalid in password
s/character/characters

2018-08-07 21:34 UTC, ericwb commented on lib/ansible/modules/system/user.py
> +            # these character are invalid in password
"the password"

2018-08-07 22:18 UTC, ericwb reviewed
Thanks for reworking the words

2018-08-07 22:19 UTC, ericwb commented on changelogs/fragments/password_sanity_check.yml
> +  - user module - add a sanity check for user password and a more helpful warning message (https://github.com/ansible/ansible/pull/43615)
Sorry one more nit: "a user's password"

2018-08-08 14:22 UTC, HD650 commented on changelogs/fragments/password_sanity_check.yml
> +  - user module - add a sanity check for user password and a more helpful warning message (https://github.com/ansible/ansible/pull/43615)
No problem!

2018-08-09 14:28 UTC, HD650 commented
@ericwb Fixed the grammar mistake.

2018-08-09 22:53 UTC, ericwb approved these changes

2018-08-10 13:38 UTC, HD650 commented
@samdoran Need any other change?

2018-08-13 16:45 UTC, merged