add external provider to ovirt network
ansible/ansible pull request #43636
Opened 2018-08-03 10:40 UTC by ocasek

##### SUMMARY

#42895

##### ISSUE TYPE

 - Feature Pull Request
 - New Module Pull Request
 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME

ovirt
##### ANSIBLE VERSION

```
ansible 2.6.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/mnecas/Desktop/Projects/Redhat/ansible/lib/ansible/modules/cloud/ovirt']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, May 16 2018, 17:50:09) [GCC 8.1.1 20180502 (Red Hat 8.1.1-1)]

```

##### ADDITIONAL INFORMATION

```

```

2018-08-03 21:20 UTC, jamescassell approved these changes
Add an example?

2018-08-13 09:13 UTC, ocasek commented
I still got one error in engine so don't merge yet I'll open another issue.

2018-08-31 05:28 UTC, mwperina approved these changes
shipit

2018-08-31 08:28 UTC, mnecas commented
dont shipit yet, still wroking on it

2018-08-31 08:34 UTC, mwperina requested changes
OK, removing ack

2018-08-31 12:07 UTC, machacekondra commented on lib/ansible/modules/cloud/ovirt/ovirt_network.py
> +            - "Type name of external network provider."
Type name? Isn't it just a name?

2018-08-31 12:07 UTC, machacekondra commented on lib/ansible/modules/cloud/ovirt/ovirt_network.py
> +        res = [e for e in ons_service.list() if e.name == self._module.params['external_provider']]
please use `get_id_by_name` here

2018-08-31 12:07 UTC, machacekondra commented on lib/ansible/modules/cloud/ovirt/ovirt_network.py
> +        res = [e for e in ons_service.list() if e.name == self._module.params['external_provider']]
Even better use it in `import_external_network` method

2018-08-31 12:07 UTC, machacekondra commented on lib/ansible/modules/cloud/ovirt/ovirt_network.py
> +        network = on_service.networks_service().network_service(self.build_entity().id)
`network = on_service.networks_service().network_service(search_entity().id)`

2018-08-31 12:07 UTC, machacekondra commented on lib/ansible/modules/cloud/ovirt/ovirt_network.py
> +        ons_service = self._connection.system_service().openstack_network_providers_service()
This method don't handle idemptency and dry-mode.

2018-08-31 12:07 UTC, machacekondra commented on lib/ansible/modules/cloud/ovirt/ovirt_network.py
> +            external_provider=otypes.OpenStackNetworkProvider(id=self._get_external_provider_id())
I think we can't change the `external_provider` on network once it's created.

2018-08-31 12:22 UTC, mnecas commented on lib/ansible/modules/cloud/ovirt/ovirt_network.py
> +        res = [e for e in ons_service.list() if e.name == self._module.params['external_provider']]
When I used get_id_by_name i got this error: "Entity 'ovirt-provider-ovn' was not found."

2018-09-12 20:24 UTC, mwperina approved these changes
shipit

2018-09-19 12:27 UTC, machacekondra approved these changes
shipit

2018-09-19 13:03 UTC, mwperina approved these changes
shipit

2018-09-26 14:18 UTC, machacekondra commented
shipit

2018-10-04 22:55 UTC, merged