Deprecated Old NetApp Cdot Modules
ansible/ansible pull request #43781
Opened 2018-08-07 14:58 UTC by carchi8py

##### SUMMARY
Deprecates all NetApp Cdot Modules 

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME
na_cdot_*

##### ANSIBLE VERSION

```
ansible 2.7.0.dev0 (ontap-dep 338f8715f5) last updated 2018/08/07 07:52:50 (GMT -700)
  config file = None
  configured module search path = [u'/Users/chrisarchibald/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /private/tmp/ansible/lib/ansible
  executable location = /private/tmp/ansible/bin/ansible
  python version = 2.7.12 (default, Oct 11 2016, 05:20:59) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)]
```

##### ADDITIONAL INFORMATION

```

```

2018-08-09 19:51 UTC, schmots1 approved these changes
shipit

2018-08-10 16:37 UTC, gundalow requested changes
Can you please add an entry in `docs/docsite/rst/porting_guides/porting_guide_2.7.rst` under `Deprecation notices`

In the format
```
* ``na_cdot_aggregate`` use :ref:`na_ontap_aggregate <na_ontap_aggregate>` instead.
```

2018-08-13 15:22 UTC, schmots1 approved these changes
shipit

2018-08-13 17:49 UTC, carchi8py commented
@gundalow i'm not sure what i need to add to get rid of the following error above on porting_guide_2.7

2018-08-13 19:43 UTC, gundalow approved these changes

2018-08-13 19:43 UTC, gundalow commented on docs/docsite/rst/porting_guides/porting_guide_2.7.rst
> +* ``na_cdot_aggregate`` use :ref:`na_ontap_aggregate <na_ontap_aggregate>` instead.
Ah, my mistake, we've changed how the links work, they need `_module` adding.

```
``na_cdot_aggregate`` use :ref:`na_ontap_aggregate <na_ontap_aggregate_module>` instead.
```

2018-08-14 16:39 UTC, merged

2018-08-14 16:40 UTC, gundalow commented
Merged into `devel`