Adds new module win_mssql_login
ansible/ansible pull request #43866
Opened 2018-08-09 07:28 UTC by dlazz

##### SUMMARY
New windows module that allows to add or remove MS SQL Server logins

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
win_mssql_login

##### ANSIBLE VERSION
```
2.7
```
##### ADDITIONAL INFORMATION
Idempotent creation or deletion of a MS SQL SERVER Login

Ansible Task:
```
- name: create new sql login
  win_mssql_login:
    server_instance: 'myserver\instance'
    login_name: john_doe
    password: "{{ my_super_secret }}"
    state: present
```
Output: 
```
TASK [create new sql login] *********************************************************************************************************************************
changed: [ansible] => {"changed": true, "output": "login john_doe created"}
```

2018-08-16 09:44 UTC, dagwieers commented
Beware that [the deadline](https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/roadmap/ROADMAP_2_7.rst#release-schedule) for getting new features/modules accepted in Ansible v2.7 is nearing, it is set to either 2018-08-23 or 2018-08-30. If you are blocked, or you need feedback, please discuss on IRC channel #ansible-windows or add a comment to the [Windows Working Group meeting agenda](https://github.com/ansible/community/issues/294) to get it resolved.

2018-08-21 19:39 UTC, jhawkesworth commented on test/integration/targets/win_mssql_login/tasks/main.yml
> +    - name: install SqlServer powershell module
If this and other .msi files listed below are needed to run this module, they should be mentioned in the module documentation (i think there is a 'requirements' section).
Also I would consider adding the steps to install these required things into the 'examples' section of the documentation page.

2018-08-21 19:41 UTC, jhawkesworth commented on lib/ansible/modules/windows/win_mssql_login.py
> +  - If the user that runs ansible has the appropriated permission on the db,
is  'appropriated' a typo?  I think 'appropriate' is intended perhaps?
Also I would not use 'db' but instead use full word 'database' in documentation.

2018-08-21 19:47 UTC, jhawkesworth commented
@dlazz This looks like a good module, I hope you can make tiny changes I suggest to documentation and this can soon be merged.

2018-09-27 03:04 UTC, jborean93 requested changes
I would like to see this use the proper cmdlets for adding/removing/checking the login accounts instead of manually crafting the SQL queries yourself.

2018-09-27 03:04 UTC, jborean93 commented on lib/ansible/modules/windows/win_mssql_login.ps1
> +# -*- coding: utf-8 -*-
Not needed in PowerShell

2018-09-27 03:04 UTC, jborean93 commented on lib/ansible/modules/windows/win_mssql_login.ps1
> +    'changed' = $False;
You don't need to quote a hashtable key or use `;` if you have it on a newline, just do `changed = $False`

2018-09-27 03:04 UTC, jborean93 commented on lib/ansible/modules/windows/win_mssql_login.ps1
> +        if (!($ServerInstanceUser) -or !($ServerInstancePassword)) {
Look at splatting that I mentioned in the other review

2018-09-27 03:04 UTC, jborean93 commented on test/integration/targets/win_mssql_login/tasks/main.yml
> +    - name: install SqlServer powershell module
+1 to this idea

2018-09-27 03:04 UTC, jborean93 commented on lib/ansible/modules/windows/win_mssql_login.ps1
> +                    Invoke-SQLCmd -ServerInstance $ServerInstance -Query $QUERY
We should be using the `*-SqlLogin` cmdlets for these operations and not crafting the queries ourselves. They can deal with all the escaping issues  and handle whatever checks are necessary.

2018-09-27 03:04 UTC, jborean93 commented on lib/ansible/modules/windows/win_mssql_login.py
> +version_added: '2.7'
Bump to 2.8.

2018-09-27 03:04 UTC, jborean93 commented on lib/ansible/modules/windows/win_mssql_login.py
> +  check_expiration:
Probably prefer `enforce_expiration` as a module option. Check seems to indicate whether Ansible will check something not set something.

2018-09-27 03:04 UTC, jborean93 commented on lib/ansible/modules/windows/win_mssql_login.py
> +  check_policy:
Same here, `enforce_policy` instead of `check_policy`

2018-09-27 03:04 UTC, jborean93 commented on lib/ansible/modules/windows/win_mssql_login.py
> +    description: specifies what type of login has to be created (sql or windows)
Would be great to give a brief spiel about the 2, I know `windows` doesn't support explicit credentials so maybe say `password` is not required for that.

I would also put this in a new list entry and start with a capital and end with a full stop.

2018-09-27 03:04 UTC, jborean93 commented on lib/ansible/modules/windows/win_mssql_login.py
> +options:
Each option entry should be a full sentence, i.e. it starts with a capital and ends with a full stop.

2019-01-23 15:37 UTC, dagwieers commented
During the [next Windows WG meeting](https://github.com/ansible/community/issues/420) on 2019-01-29 we will review and decide on the inclusion of this module in Ansible v2.8. Your presence in the meeting could be helpful.

*If there's anything you wanted to improve/fix, please do so before the meeting.*

2019-01-29 21:10 UTC, nitzmahone commented
After some discussion at the Windows Working Group module review, we're a little nervous to take on a set of SQL Server modules into the core distribution right now, since we can't sanely test against a SQL Server  in CI today. This would be a good candidate for the new collections feature that's coming in Ansible 2.8, which would allow these modules to be hosted on galaxy.ansible.com and easily installed/upated by users on their Ansible controller.

2019-01-31 08:06 UTC, dlazz commented
Ok, thank you all. I'll try the new feature.

2019-01-31 08:06 UTC, closed without merging