Adding ElementSW Ldap Module
ansible/ansible pull request #43969
Opened 2018-08-10 18:18 UTC by carchi8py

##### SUMMARY
Adding ElementSW Ldap Module

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME
- na_elementsw_ldap.py

##### ANSIBLE VERSION

```
bash-3.2# ansible --version
ansible 2.7.0.dev0 (sf_commonfiles caf71e24dd) last updated 2018/08/06 10:46:57 (GMT -700)
  config file = None
  configured module search path = [u'/Users/chrisarchibald/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /private/tmp/ansible/lib/ansible
  executable location = /private/tmp/ansible/bin/ansible
  python version = 2.7.12 (default, Oct 11 2016, 05:20:59) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)]

```

##### ADDITIONAL INFORMATION

```

```

2018-08-10 18:37 UTC, schmots1 approved these changes
shipit

2018-08-23 19:58 UTC, schmots1 approved these changes
shipit

2018-08-24 16:20 UTC, gundalow requested changes

2018-08-24 16:20 UTC, gundalow commented on lib/ansible/modules/storage/netapp/na_elementsw_ldap.py
> +            searchBindPassword=dict(required=False, type=str),
`, no_log=True`

2018-08-28 10:45 UTC, gundalow approved these changes

2018-08-28 10:45 UTC, merged