Adding ElementSW Volume Clone
ansible/ansible pull request #43983
Opened 2018-08-10 20:44 UTC by carchi8py

##### SUMMARY
Adding ElementSW Volume Clone->

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME
- na_elementsw_volume_clone.py

##### ANSIBLE VERSION

```
bash-3.2# ansible --version
ansible 2.7.0.dev0 (sf_commonfiles caf71e24dd) last updated 2018/08/06 10:46:57 (GMT -700)
  config file = None
  configured module search path = [u'/Users/chrisarchibald/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /private/tmp/ansible/lib/ansible
  executable location = /private/tmp/ansible/bin/ansible
  python version = 2.7.12 (default, Oct 11 2016, 05:20:59) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)]
```

##### ADDITIONAL INFORMATION

```

```

2018-08-23 20:31 UTC, schmots1 approved these changes
shipit

2018-08-28 14:29 UTC, gundalow requested changes

2018-08-28 14:29 UTC, gundalow commented on lib/ansible/modules/storage/netapp/na_elementsw_volume_clone.py
> +    password:
Should be in docs_fragment

2018-08-28 17:40 UTC, gundalow approved these changes

2018-08-28 17:40 UTC, merged