New GCP Module: gcp_compute_global_address_facts
ansible/ansible pull request #44029
Opened 2018-08-13 06:24 UTC by rambleraptor

##### SUMMARY

New GCP Module: gcp_compute_global_address_facts
##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
gcp_compute_global_address_facts

##### ANSIBLE VERSION
```
2.7
```

##### ADDITIONAL INFORMATION
```
This was generated by [Magic Modules](https://github.com/googlecloudplatform/magic-modules)
```

2018-08-13 16:29 UTC, ryansb requested changes

2018-08-13 16:29 UTC, ryansb commented on lib/ansible/modules/cloud/google/gcp_compute_global_address_facts.py
> +    address:
Same here - this return should probably be `{items: [{id: ....}, ....]}`

2018-08-17 05:55 UTC, rambleraptor commented
Notes on facts modules have been addressed!

2018-08-22 14:30 UTC, ryansb approved these changes

2018-08-22 14:30 UTC, ryansb approved these changes

2018-08-22 14:31 UTC, merged