Fix typos in 2.6 changelog
ansible/ansible pull request #44076
Opened 2018-08-13 15:38 UTC by bersace

Hi,

##### SUMMARY

While reading changelog of 2.6, I bugged on some typo. So a reviewed it a bit.

##### ISSUE TYPE

 - Docs Pull Request

2018-08-13 15:40 UTC, sivel commented
The changelog entry at changelogs/CHANGELOG-v2.6.rst is auto generated by files within the `changelogs/fragments` directory.  You will need to update the source fragments instead.

2018-08-13 15:55 UTC, bersace commented
@sivel, thanks for the feedback ! How do you generate the changelog from fragments ?

2018-08-13 15:56 UTC, bersace commented
Trying `make changelog`.

``` console
$ make changelog
packaging/release/changelogs/changelog.py release -vv && packaging/release/changelogs/changelog.py generate -vv
Traceback (most recent call last):
  File "packaging/release/changelogs/changelog.py", line 11, in <module>
    import docutils.utils
ImportError: No module named docutils.utils
Makefile:244 : la recette pour la cible « changelog » a échouée
make: *** [changelog] Erreur 1
```

2018-08-13 16:04 UTC, bersace commented
@sivel, ok, got it. PR updated.

2018-08-13 16:05 UTC, sivel commented
cc @mattclay

2018-08-13 22:10 UTC, mattclay requested changes

2018-08-13 22:10 UTC, mattclay commented on changelogs/fragments/clarify_error_message.yml
> +    - Fix an atomic_move error that is 'true', but misleading. Now we show all 3 files involved and clarify what happened.
This file exists in devel. The fix needs to be applied there and backported in a separate PR.

2018-08-13 22:10 UTC, mattclay commented on changelogs/CHANGELOG-v2.6.rst
> -- Sceanrio guide for removing an existing virtual machine is added.
This file is generated and should not be edited.

It will be regenerated from the changelog fragments during the next release.

2018-08-14 08:04 UTC, bersace commented
Updated.

2018-08-14 14:48 UTC, mattclay approved these changes

2018-08-14 14:50 UTC, merged