WIP: smart fact gathering
ansible/ansible pull request #44099
Opened 2018-08-14 00:06 UTC by pilou-

##### SUMMARY

When smart gathering is enabled: facts aren't gathered if `setup` module had been called before.

Test play (use `ANSIBLE_GATHERING=smart ansible-playbook play.yml`):
```yaml
- hosts: localhost
  gather_facts: false
  tasks:
    - setup:
        gather_subset:
          - '!min'
- hosts: localhost
  tasks:
    - debug:
        msg:
          "{{ ansible_distribution_release }}"
```
This pull request modify smart fact gathering behavior (when smart fact gathering is enabled):
1. facts aren't gathered when already the facts already gathered are a superset of requested facts
2. facts are gathered in all other cases

Notes:
- require #44008 (44008 should be merged before this one)
- integration tests included

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
gather_facts

##### ANSIBLE VERSION
```
2.7
```

2018-08-22 13:24 UTC, pilou- commented
Rebased, I need to analyse this new integration test failure:
```
2018-08-22 09:01:02 TASK [check gather_subset fact] ************************************************
2018-08-22 09:01:02 task path: /root/ansible/test/integration/targets/gathering_facts/test_smart_gathering_gather_subset.yml:47
2018-08-22 09:01:02 fatal: [facthost1]: FAILED! => {"changed": false, "msg": "expected: ['!min', 'local'], encountered: [u'!min,local']"}
```

2018-08-22 13:31 UTC, bcoca commented
This is not really 'fact gathering' itself,  but specific subset you want to consume but explicitly avoid collecting beforehand.

2018-08-22 13:48 UTC, pilou- commented
Using the playbook given on the description, the current behavior seems unexpected (because facts aren't gathered at the beginning of the 2nd play).

2018-08-22 13:54 UTC, bcoca commented
Yes, and we can do similar examples with all kinds of facts, in hardware, networking, etc .. every category has the same issue. If you restrict facts gathered to begin with, they wont be available even when gathering is 'smart' as it assumes that the previous options you selected are the ones you want for the whole run.

2018-08-28 04:42 UTC, mattclay commented
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/80028/54/tests

2018-08-28 21:43 UTC, bcoca requested changes
not something we want as this would only cover a small subset of facts, in the end any customization of fact gathering with 'gathering=smart' will trigger this problem, at most we should warn in the documentation about this.

2018-08-28 22:18 UTC, pilou- commented
I don't understand, the whole point of this PR is to compare what has been gathered by previous `setup` tasks with what should be gathered in order to comply with the play level `gather_subset`. Is that something which can not be done ?

2020-04-03 15:28 UTC, relrod commented
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us that you've taken time to contribute.

Unfortunately, we're not sure if we want this feature in the program, and I don't want this to seem confrontational.  Our reasons for this are:

   * This could cause potentially unexpected behavior. We'd recommend just making `gather_facts=True` explicit in the second play.

However, we're absolutely always up for discussion.  Since this is a really busy project, we don't always see comments on closed tickets, but want to encourage
open dialog.  You can stop by the development list, and we'd be glad to talk about it - and we might even be persuaded otherwise!

   * https://groups.google.com/forum/#!forum/ansible-devel

In the future, sometimes starting a discussion on the development list prior to implementing a feature can make getting things included a little easier, but it's not always necessary.

Thank you once again for this and your interest in Ansible!

2020-04-03 15:28 UTC, closed without merging