add updated licensing guidelines to docs
ansible/ansible pull request #44144
Opened 2018-08-14 21:51 UTC by maxamillion

Signed-off-by: Adam Miller <admiller@redhat.com>

##### SUMMARY
It was decided during the Ansible Core Developer Community Meeting
on 2018-08-14 that GPLv3 is acceptable for module_utils in specific
scenarios.

https://github.com/ansible/community/issues/329#issuecomment-413005278

##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

docs

##### ANSIBLE VERSION

```
ansible 2.7.0.dev0 (docs/licensing ee770890d0) last updated 2018/08/14 16:50:49 (GMT -500)
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/admiller/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/admiller/src/dev/ansible/lib/ansible
  executable location = /home/admiller/src/dev/ansible/bin/ansible
  python version = 3.6.6 (default, Jul 19 2018, 14:25:17) [GCC 8.1.1 20180712 (Red Hat 8.1.1-5)]
```

2018-08-16 13:56 UTC, abadger commented on docs/docsite/rst/dev_guide/shared_snippets/Licensing.txt
> +   under the GPLv3 license. Files under the ``lib/ansible/module_utils/``
GPLv3 or later.  (in case there's ever a GPLv3.1, GPLv4, etc)

2018-08-16 13:57 UTC, abadger commented on docs/docsite/rst/dev_guide/shared_snippets/Licensing.txt
> +   **LICENSING GUIDELINE** - All modules shipped with Ansible must be done so
It's all files except for module_utils.

2018-08-16 21:32 UTC, acozine requested changes
+1 to the change, but please don't merge it via this PR - I've got a massive re-write in progress on the Developer Guide - see #44098. I'll assign this PR to myself and incorporate it either as part of the re-write, or after the re-write is merged.

2018-08-17 14:11 UTC, maxamillion commented
@abadger should I specify 2-clause BSD or does it matter?

2018-08-17 14:17 UTC, abadger commented
It does matter but probably best to point to our boilerplate and the
copies of the license in our repo

On Fri, Aug 17, 2018, 7:11 AM Adam Miller <notifications@github.com> wrote:

> @abadger <https://github.com/abadger> should I specify 2-clause BSD or
> does it matter?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ansible/ansible/pull/44144#issuecomment-413878545>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAMxWgdqFvU9ZPOQIWcNSxYAprtBTh-cks5uRs8fgaJpZM4V9PH7>
> .
>

2018-08-17 14:36 UTC, abadger commented
* license copies: https://github.com/ansible/ansible/tree/devel/licenses
* boilerplate: https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/dev_guide/developing_modules_documenting.rst#id1

Perhaps the snippet should point to the  developing_modules_documenting.rst section on Copyright and we add the bulk of this information there. (It will also be good to add the one-liner for BSD licensed code there.  (The one-liner for BSD can be taken from basic.py: https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/basic.py#L3  

```# Simplified BSD License (see licenses/simplified_bsd.txt or https://opensource.org/licenses/BSD-2-Clause)```

2018-09-12 16:26 UTC, acozine commented
Closing in favor of #45574 to incorporate changes from #45349.

2018-09-12 16:26 UTC, closed without merging