Add ontap_cluster_peer.py Modules
ansible/ansible pull request #44189
Opened 2018-08-15 17:08 UTC by carchi8py

##### SUMMARY
Add ontap_cluster_peer.py Modules

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME
- na_ontap_cluster_peer.py

##### ANSIBLE VERSION

```
bash-3.2# ansible --version
ansible 2.7.0.dev0 (sf_commonfiles caf71e24dd) last updated 2018/08/06 10:46:57 (GMT -700)
  config file = None
  configured module search path = [u'/Users/chrisarchibald/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /private/tmp/ansible/lib/ansible
  executable location = /private/tmp/ansible/bin/ansible
  python version = 2.7.12 (default, Oct 11 2016, 05:20:59) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)]
```

##### ADDITIONAL INFORMATION

```

```

2018-08-16 20:53 UTC, lonico commented on lib/ansible/modules/storage/netapp/na_ontap_cluster_peer.py
> +            required_together=(['source_intercluster_lif', 'dest_intercluster_lif', 'passphrase']),
According to documentation, we should have two sets of [ ] :

required_together
This is self explanatory, all specified parameters need to be specified together:

required_together=[
  [ 'a', 'b' ]
]

2018-08-24 12:32 UTC, schmots1 approved these changes
shipit

2018-08-28 14:32 UTC, gundalow requested changes

2018-08-28 14:32 UTC, gundalow commented on lib/ansible/modules/storage/netapp/na_ontap_cluster_peer.py
> +            passphrase=dict(required=False, type='str'),
`, no_log=True)`

2018-08-28 14:32 UTC, gundalow commented on lib/ansible/modules/storage/netapp/na_ontap_cluster_peer.py
> +        dest_hostname: "{{ netapp_hostname }}"
Does this example make sense, are you peering to yourself?

2018-08-28 16:38 UTC, carchi8py commented on lib/ansible/modules/storage/netapp/na_ontap_cluster_peer.py
> +        dest_hostname: "{{ netapp_hostname }}"
@gundalow we are peering to a second netapp host. I'll update the documentation to say {{ destination_netapp_hostname }} to clear that up

2018-08-28 17:39 UTC, gundalow approved these changes

2018-08-28 17:40 UTC, merged