Adding na_ontap_disks.py Module
ansible/ansible pull request #44192
Opened 2018-08-15 17:13 UTC by carchi8py

##### SUMMARY
Adding na_ontap_disks.py Module

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME
- na_ontap_disks.py

##### ANSIBLE VERSION

```
bash-3.2# ansible --version
ansible 2.7.0.dev0 (sf_commonfiles caf71e24dd) last updated 2018/08/06 10:46:57 (GMT -700)
  config file = None
  configured module search path = [u'/Users/chrisarchibald/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /private/tmp/ansible/lib/ansible
  executable location = /private/tmp/ansible/bin/ansible
  python version = 2.7.12 (default, Oct 11 2016, 05:20:59) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)]
```

##### ADDITIONAL INFORMATION

```

```

2018-08-24 12:31 UTC, schmots1 approved these changes
shipit

2018-08-24 15:27 UTC, gundalow requested changes

2018-08-24 15:27 UTC, gundalow commented on lib/ansible/modules/storage/netapp/na_ontap_disks.py
> +    - Used only with auto or all parameter. It specifies the node
This doesn't make sense to me (though I'm not a NetApp user)
* `Used only with auto or all parameter` - What defines `auto` or `all`?
* Is this meant to be the name of a node? does node mean disk, cluster, ...?

2018-08-24 17:57 UTC, schmots1 approved these changes
shipit

2018-08-28 10:45 UTC, gundalow requested changes

2018-08-28 10:45 UTC, gundalow commented on lib/ansible/modules/storage/netapp/na_ontap_disks.py
> +- name: Assign unowned disks
How would you unassign, set `node:` to empty, null? 
Would be worth adding an example for that. 

If it's not possible then I think `short_description` may need updating

2018-08-28 14:42 UTC, schmots1 commented
Updated.  Will change short description back for a later release when we modify how much this module does.

2018-08-28 15:43 UTC, gundalow approved these changes

2018-08-28 15:43 UTC, merged