Adding ontap_node.py Module
ansible/ansible pull request #44211
Opened 2018-08-15 17:43 UTC by carchi8py

##### SUMMARY
Adding ontap_node.py Module

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME
- na_ontap_node.py

##### ANSIBLE VERSION

```
bash-3.2# ansible --version
ansible 2.7.0.dev0 (sf_commonfiles caf71e24dd) last updated 2018/08/06 10:46:57 (GMT -700)
  config file = None
  configured module search path = [u'/Users/chrisarchibald/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /private/tmp/ansible/lib/ansible
  executable location = /private/tmp/ansible/bin/ansible
  python version = 2.7.12 (default, Oct 11 2016, 05:20:59) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)]
```

##### ADDITIONAL INFORMATION

```

```

2018-08-24 12:29 UTC, schmots1 approved these changes
shipit

2018-08-24 15:16 UTC, gundalow requested changes

2018-08-24 15:16 UTC, gundalow commented on lib/ansible/modules/storage/netapp/na_ontap_node.py
> +    from_name: laurentn-vsim1
What happens if this playbook is run twice, ie if `laurentn-vsim1` doesn't exist on the 2nd run?

Code needs to deal wit that and the documentation needs to explain it

2018-08-24 15:21 UTC, schmots1 commented on lib/ansible/modules/storage/netapp/na_ontap_node.py
> +    from_name: laurentn-vsim1
The code does deal with it, it returns no change because it sees that the new node name already exists and the old doesn't.  What explanation in the documentation are you looking for?

2018-08-28 10:49 UTC, gundalow commented on lib/ansible/modules/storage/netapp/na_ontap_node.py
> +    - The name of the node to be renamed.
Suggestion: ``The name of the node to be renamed. If I(name) already exists, no action will be performed.`

2018-08-28 17:41 UTC, gundalow approved these changes

2018-08-28 17:41 UTC, merged