Adding ontap_vserver_peer.py Module
ansible/ansible pull request #44226
Opened 2018-08-15 18:07 UTC by carchi8py

##### SUMMARY
Adding ontap_vserver_peer.py Module

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME
- na_ontap_vserver_peer.py

##### ANSIBLE VERSION

```
bash-3.2# ansible --version
ansible 2.7.0.dev0 (sf_commonfiles caf71e24dd) last updated 2018/08/06 10:46:57 (GMT -700)
  config file = None
  configured module search path = [u'/Users/chrisarchibald/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /private/tmp/ansible/lib/ansible
  executable location = /private/tmp/ansible/bin/ansible
  python version = 2.7.12 (default, Oct 11 2016, 05:20:59) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)]

```

##### ADDITIONAL INFORMATION

```

```

2018-08-17 13:08 UTC, schmots1 approved these changes
shipit

2018-08-22 15:48 UTC, gundalow requested changes

2018-08-22 15:48 UTC, gundalow commented on lib/ansible/modules/storage/netapp/na_ontap_vserver_peer.py
> +            dest_password=dict(required=False, type='str')
Please add
`, no_log=True`

2018-08-22 19:04 UTC, gundalow approved these changes

2018-08-22 19:04 UTC, merged