new na_ontap_motd module
ansible/ansible pull request #44255
Opened 2018-08-16 08:35 UTC by dprts

##### SUMMARY
This module allows setting/removing cluster and SVM level MOTD 

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
- na_ontap_motd
##### ANSIBLE VERSION
2.7

2018-08-22 15:42 UTC, gundalow requested changes
Needs review by someone in the NetApp org

2018-08-27 17:37 UTC, carchi8py approved these changes

2018-08-27 17:38 UTC, carchi8py commented
@gundalow we are good with this one being merged in.

2018-08-27 17:43 UTC, lonico approved these changes

2018-08-27 17:43 UTC, lonico commented on lib/ansible/modules/storage/netapp/na_ontap_motd.py
> +        choices: ['present', 'absent']
I would make present the default

2018-08-27 17:43 UTC, lonico commented on lib/ansible/modules/storage/netapp/na_ontap_motd.py
> +        self.vserver = params['vserver']
only FYI.
We found this not to be very useful, and we now prefer to assign the whole params dictionary to a single variable.

2018-08-27 17:43 UTC, lonico commented on lib/ansible/modules/storage/netapp/na_ontap_motd.py
> +        query = netapp_utils.zapi.NaElement('query')
I don't know if the query element is really needed.  It seems superfluous as the API is already directed to this vserver.   (But we found other cases where the request seems over qualified).

2018-08-28 09:44 UTC, dprts commented on lib/ansible/modules/storage/netapp/na_ontap_motd.py
> +        choices: ['present', 'absent']
Agree, I am going to corrected.

2018-08-28 09:45 UTC, dprts commented on lib/ansible/modules/storage/netapp/na_ontap_motd.py
> +        self.vserver = params['vserver']
Also I am going to apply this change

2018-08-28 09:46 UTC, dprts commented on lib/ansible/modules/storage/netapp/na_ontap_motd.py
> +        query = netapp_utils.zapi.NaElement('query')
It looks like here it is necessary but i will check it once more

2018-08-28 09:46 UTC, dprts commented
By mistake I pushed rebased branch. I am closing this and open new PR.

2018-08-28 09:46 UTC, closed without merging