DCI devel iosxr fix : on-device diffs does not work always
ansible/ansible pull request #44265
Opened 2018-08-16 11:52 UTC by gdpak

##### SUMMARY
IOSXR's on device diff functionality is buggy. It does not work in some situations like the one we hit on dci nodepool iosxr. If you try to unconfigure a per-configure interface "show commit changes diff" shows nothing so we do not commit it and device is left with old configurations

```
RP/0/0/CPU0:iosxr01#show running-config interface
Thu Aug 16 10:49:47.838 UTC
interface Loopback888
 description test for ansible
 shutdown
!
interface MgmtEth0/0/CPU0/0
 ipv4 address dhcp
!
interface GigabitEthernet0/0/0/1
 shutdown
!
interface preconfigure GigabitEthernet0/0/0/2
 description test-interface-2
 mtu 516
 speed 100
 duplex full
 shutdown
!
interface preconfigure GigabitEthernet0/0/0/3
 description test-interface-1
 mtu 256
 speed 100
 duplex full
 shutdown
!
interface preconfigure GigabitEthernet0/0/0/4
 description test_interface_1
!
interface preconfigure GigabitEthernet0/0/0/5
 description test_interface_2
!

RP/0/0/CPU0:iosxr01#conf t
Thu Aug 16 10:49:56.378 UTC
RP/0/0/CPU0:iosxr01(config)#no interface gigabitEthernet 0/0/0/4
RP/0/0/CPU0:iosxr01(config)#no interface gigabitEthernet 0/0/0/5
RP/0/0/CPU0:iosxr01(config)#show commit changes diff
Thu Aug 16 10:50:34.265 UTC
Building configuration...
!! IOS XR Configuration 6.1.2
end

RP/0/0/CPU0:iosxr01(config)#
```

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
iosxr_*

##### ANSIBLE VERSION

```
2.7
```

##### ADDITIONAL INFORMATION
DCI 's failed test case passes with this change
```
nodepool@nodepool:~/debug/ansible$ ansible-test network-integration --inventory /tmp//invent iosxr_interface -vvvv
--
PLAY RECAP *************************************************************************************************************************
iosxr01                    : ok=187  changed=61   unreachable=0    failed=0

```

2018-08-16 12:11 UTC, ganeshrn requested changes
This change will execute commit every time module is run even if there is no change in candidate datastore.  Is that the desired behavior? Since commit is costly operation should we allow empty commits?

2018-08-16 13:06 UTC, gdpak commented
@ganeshrn NetworkConfig is still used on iosxr modules to find diff from candidate and configs from module args so commit will be done only if there is a change.

2018-08-16 13:29 UTC, ganeshrn commented
@gdpak The [cli_config](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/cli/cli_config.py#L244) module depends on the onbox diff capalilty and this change will result in sending commit on each run in case of cli_config mdoule

2018-08-17 05:56 UTC, gdpak commented
@ganeshrn then cli_config can't be used for iosxr. I told earlier also iosxr's on-device functionality does not work for prefix-sets, as-path and route-filters etc . We need to revert 
https://github.com/ansible/ansible/pull/43837 to use networkConfig and handle special objects as done for iosxr_config ..thoughts ?

2018-08-17 06:09 UTC, ganeshrn commented
@gdpak The cli_config module is designed to use on box diff capability if the host supports it. If the diff capability on the host has issues nothing much can be done about it apart from adding the caveat in cli_config module.

The `supports_generate_diff` flag in capabilities can be set to True in iosxr_config module code and in iosxr cliconf edit_config() add a check to see if the flag `supports_generate_diff` is set don't call get_diff function. This should work with both iosxr_config and cli_config module.

2018-08-17 06:27 UTC, trishnaguha requested changes
Please set `supports_generate_diff` to True and `supports_onbox_diff` to False if iosxr isn't going to rely on onbox diff. Also `get_diff` function needs to be modified to use NetworkConfig.

2018-08-17 06:44 UTC, ganeshrn approved these changes
Looking at the code I think we can update get_diff function in iosxr cliconf to generate diff within Ansible so that cli_conifg module has feature parity with iosxr_config module. I will make that change in different PR

2018-08-17 06:55 UTC, gdpak commented
@ganeshrn :) gives me relief . caveats come back to bite . @trishnaguha I think that should take care of cli_config as well. I will push this change now so we have clean DCI for now.

2018-08-17 07:03 UTC, trishnaguha approved these changes

2018-08-17 07:04 UTC, merged