Add support for MySQL plugin authentication
ansible/ansible pull request #44267
Opened 2018-08-16 13:03 UTC by tomaszkiewicz

##### SUMMARY
The change adds support for MySQL plugin authentication, eg. AWS RDS IAM Authentication plugin.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
MySQL

##### ANSIBLE VERSION
```
ansible 2.6.2
  config file = /home/luktom/.ansible.cfg
  configured module search path = [u'/home/luktom/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### ADDITIONAL INFORMATION

2018-08-18 23:12 UTC, achinthagunasekara approved these changes

2019-02-18 14:50 UTC, gundalow reviewed
Hi,
Thanks for this, just a few minor formatting comments.
You can accept these from the GitHub web interface

2019-02-18 14:50 UTC, gundalow commented on lib/ansible/modules/database/mysql/mysql_user.py
> +author: "Jonathan Mainguy (@Jmainguy), Lukasz Tomaszkiewicz (@tomaszkiewicz)"
```suggestion
author:
  - Jonathan Mainguy (@Jmainguy)
  - Lukasz Tomaszkiewicz (@tomaszkiewicz)
```

2019-02-18 14:50 UTC, gundalow commented on lib/ansible/modules/database/mysql/mysql_user.py
> +      - set the user's plugin used to authenticate (CREATE USER user IDENTIFIED WITH plugin)
```suggestion
      - Set the user's plugin used to authenticate C(CREATE USER user IDENTIFIED WITH plugin).
```

2019-02-18 14:50 UTC, gundalow commented on lib/ansible/modules/database/mysql/mysql_user.py
> +      - set the user's plugin hash string (CREATE USER user IDENTIFIED WITH plugin AS plugin_hash_string)
```suggestion
      - Set the user's plugin hash string C(CREATE USER user IDENTIFIED WITH plugin AS plugin_hash_string).
```

2019-02-18 14:50 UTC, gundalow commented on lib/ansible/modules/database/mysql/mysql_user.py
> +      - set the user's plugin auth_string (CREATE USER user IDENTIFIED WITH plugin BY plugin_auth_string)
```suggestion
      - Set the user's plugin auth_string C(CREATE USER user IDENTIFIED WITH plugin BY plugin_auth_string).
```

2019-02-18 14:50 UTC, gundalow commented on lib/ansible/modules/database/mysql/mysql_user.py
> +    version_added: "2.7"
```suggestion
    version_added: "2.8"
```

2019-02-18 14:50 UTC, gundalow commented on lib/ansible/modules/database/mysql/mysql_user.py
> +    version_added: "2.7"
```suggestion
    version_added: "2.8"
```

2019-02-18 14:50 UTC, gundalow commented on lib/ansible/modules/database/mysql/mysql_user.py
> +    version_added: "2.7"
```suggestion
    version_added: "2.8"
```

2019-08-13 15:28 UTC, abohne commented
@tomaszkiewicz are you able to rebase this and accept @gundalow's comments?  Would really like to see this merged.

2019-08-13 15:31 UTC, abohne commented
This would resolve #27179

2019-08-15 18:43 UTC, abohne commented on lib/ansible/modules/database/mysql/mysql_user.py
> +            cursor.execute("SELECT plugin, authentication_string FROM user WHERE user = %s AND host = %s", (user, host))
I believe this needs to be
```cursor.execute("SELECT plugin, authentication_string FROM mysql.user WHERE user = %s AND host = %s", (user, host))```

2019-08-15 18:47 UTC, abohne commented on lib/ansible/modules/database/mysql/mysql_user.py
> +                    changed = user_mod(cursor, user, host, host_all, password, encrypted, plugin, plugin_hash_string, plugin_auth_string,
this needs to be `changed, msg` or else a nonexistent value for msg is returned

2019-08-15 18:48 UTC, abohne commented on lib/ansible/modules/database/mysql/mysql_user.py
> +                    changed = user_mod(cursor, user, host, host_all, None, encrypted, plugin, plugin_hash_string, plugin_auth_string,
this needs to be `changed, msg` or else a nonexistent value for msg is returned

2019-08-16 16:06 UTC, abohne commented on lib/ansible/modules/database/mysql/mysql_user.py
> +author: "Jonathan Mainguy (@Jmainguy), Lukasz Tomaszkiewicz (@tomaszkiewicz)"
```suggestion
author:
- Jonathan Mainguy (@Jmainguy)
- Benjamin Malynovytch (@bmalynovytch)
- Lukasz Tomaszkiewicz (@tomaszkiewicz)
```

2019-08-19 18:57 UTC, abohne commented on lib/ansible/modules/database/mysql/mysql_user.py
> +            cursor.execute("SELECT plugin, authentication_string FROM mysql.user WHERE user = %s AND host = %s", (user, host))```
Looks like we got an extra 3 backticks :(

```suggestion
            cursor.execute("SELECT plugin, authentication_string FROM mysql.user WHERE user = %s AND host = %s", (user, host))
```

2019-08-19 19:01 UTC, abohne commented on lib/ansible/modules/database/mysql/mysql_user.py
> +                                       priv, append_privs, module)
Make pep8 happy

```suggestion
                                            priv, append_privs, module)
```

2019-08-19 19:02 UTC, abohne commented on lib/ansible/modules/database/mysql/mysql_user.py
> +                                       priv, append_privs, module)
Make pep8 happy

```suggestion
                                            priv, append_privs, module)
```

2019-08-19 20:21 UTC, abohne commented on lib/ansible/modules/database/mysql/mysql_user.py
> +                                       priv, append_privs, module)
```suggestion
                                            priv, append_privs, module)
```

2019-08-21 15:51 UTC, abohne approved these changes
🎉

2019-09-03 15:20 UTC, abohne commented
bot_status

2019-09-03 19:51 UTC, gundalow commented
bot_status

2019-09-17 19:07 UTC, abohne commented
What do we need to do to get this PR merged?

2019-09-17 19:39 UTC, Andersson007 commented
@tomaszkiewicz , thank you for working on this!
@abohne , @tomaszkiewicz i would review it if it was covered by integration tests (completely, all cases of using these options. Also better to check existing tests, maybe there are uncovered points that might be broken by the pr)

2019-09-22 10:08 UTC, tomaszkiewicz commented
@Andersson007 do you mean tests similar to https://github.com/ansible/ansible/blob/devel/test/integration/targets/mysql_user/tasks/create_user.yml ?

Is the environment the CI executes tests capable of using mysql plugin auth? (as e.g. AWS RDS requires to enable a specific setting for IAM auth)

2019-09-23 09:00 UTC, Andersson007 commented
I asked aws community

2019-09-23 09:49 UTC, Andersson007 commented
@tomaszkiewicz folks said it's possible, see test/integration/targets/rds_instance.
If you have any questions you can ask in [#ansible-aws](https://www.irccloud.com/irc/freenode/channel/ansible-aws) irc channel.

2019-10-01 18:44 UTC, abohne commented
> @Andersson007 do you mean tests similar to https://github.com/ansible/ansible/blob/devel/test/integration/targets/mysql_user/tasks/create_user.yml ?
> 
> Is the environment the CI executes tests capable of using mysql plugin auth? (as e.g. AWS RDS requires to enable a specific setting for IAM auth)

Maybe I'm mistaken, but I think you could use one of the standard auth plugins (even mysql_native_password) for the integration tests?

2019-10-28 20:18 UTC, abohne commented
Any updates here?

2019-11-14 15:44 UTC, daraul commented
I've been pulling my hair out wondering why I can do `sudo mysql -u root`, but not `ansible -i hosts -m mysql_user -a "user=root"...`. Hopefully this gets merged in soon...

2019-11-18 11:54 UTC, gundalow commented
@daraul @abohne have you both tested this PR locally, does it work for you?

2019-11-18 17:05 UTC, daraul commented
I've been wondering how I could do that, @gundalow, but couldn't find anything in the docs. Point me in the right direction and I'll test this out ASAP

2019-11-18 18:31 UTC, gundalow commented
@daraul Since this PR only modifies a single file download https://raw.githubusercontent.com/ansible/ansible/50a6ec33f44989b980c9e0563ea4278667f481b0/lib/ansible/modules/database/mysql/mysql_user.py into `library/`

ie
```
roles/
library/mysql_user.py
```

2019-11-18 19:09 UTC, daraul commented
@gundalow just ran this in my playbook:

```
         - name: Setup database user
           become: yes
           mysql_user:
             user: "{{ database_user }}"
             password: "{{ database_password }}"
             priv: "{{ database_name }}.*:ALL"
```
and was given this error:

```
TASK [Setup database user] *******************************************************************************************************************************************************************
task path: /home/daraul/dev/gwi-core-laravel/site.yml:108
<3.226.47.77> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<3.226.47.77> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ubuntu"' -o ConnectTimeout=10 -o StrictHostKeyChecking=no -o ControlPath=/home/daraul/.ansible/cp/a4d893a731 3.226.47.77 '/bin/sh -c '"'"'echo ~ubuntu && sleep 0'"'"''
<3.226.47.77> (0, b'/home/ubuntu\n', b'')
<3.226.47.77> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<3.226.47.77> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ubuntu"' -o ConnectTimeout=10 -o StrictHostKeyChecking=no -o ControlPath=/home/daraul/.ansible/cp/a4d893a731 3.226.47.77 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1574103853.575425-175696853591014 `" && echo ansible-tmp-1574103853.575425-175696853591014="` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1574103853.575425-175696853591014 `" ) && sleep 0'"'"''
<3.226.47.77> (0, b'ansible-tmp-1574103853.575425-175696853591014=/home/ubuntu/.ansible/tmp/ansible-tmp-1574103853.575425-175696853591014\n', b'')
Using module file /home/daraul/dev/gwi-core-laravel/library/mysql_user.py
<3.226.47.77> PUT /home/daraul/.ansible/tmp/ansible-local-15306qt9fl977/tmp_rq_1n0k TO /home/ubuntu/.ansible/tmp/ansible-tmp-1574103853.575425-175696853591014/AnsiballZ_mysql_user.py
<3.226.47.77> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ubuntu"' -o ConnectTimeout=10 -o StrictHostKeyChecking=no -o ControlPath=/home/daraul/.ansible/cp/a4d893a731 '[3.226.47.77]'
<3.226.47.77> (0, b'sftp> put /home/daraul/.ansible/tmp/ansible-local-15306qt9fl977/tmp_rq_1n0k /home/ubuntu/.ansible/tmp/ansible-tmp-1574103853.575425-175696853591014/AnsiballZ_mysql_user.py\n', b'')
<3.226.47.77> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<3.226.47.77> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ubuntu"' -o ConnectTimeout=10 -o StrictHostKeyChecking=no -o ControlPath=/home/daraul/.ansible/cp/a4d893a731 3.226.47.77 '/bin/sh -c '"'"'chmod u+x /home/ubuntu/.ansible/tmp/ansible-tmp-1574103853.575425-175696853591014/ /home/ubuntu/.ansible/tmp/ansible-tmp-1574103853.575425-175696853591014/AnsiballZ_mysql_user.py && sleep 0'"'"''
<3.226.47.77> (0, b'', b'')
<3.226.47.77> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<3.226.47.77> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ubuntu"' -o ConnectTimeout=10 -o StrictHostKeyChecking=no -o ControlPath=/home/daraul/.ansible/cp/a4d893a731 -tt 3.226.47.77 '/bin/sh -c '"'"'sudo -H -S -n  -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-hxvcwzybqegfmasbftpojwwinhabguxl ; /usr/bin/python3 /home/ubuntu/.ansible/tmp/ansible-tmp-1574103853.575425-175696853591014/AnsiballZ_mysql_user.py'"'"'"'"'"'"'"'"' && sleep 0'"'"''
Escalation succeeded
<3.226.47.77> (1, b'\r\n{"msg": "unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (1698, \\"Access denied for user \'root\'@\'localhost\'\\")", "failed": true, "exception": "  File \\"/tmp/ansible_mysql_user_payload_oc31z0d7/__main__.py\\", line 691, in main\\n    connect_timeout=connect_timeout)\\n  File \\"/tmp/ansible_mysql_user_payload_oc31z0d7/ansible_mysql_user_payload.zip/ansible/module_utils/mysql.py\\", line 79, in mysql_connect\\n    db_connection = mysql_driver.connect(**config)\\n  File \\"/usr/local/lib/python3.6/dist-packages/pymysql/__init__.py\\", line 94, in Connect\\n    return Connection(*args, **kwargs)\\n  File \\"/usr/local/lib/python3.6/dist-packages/pymysql/connections.py\\", line 325, in __init__\\n    self.connect()\\n  File \\"/usr/local/lib/python3.6/dist-packages/pymysql/connections.py\\", line 599, in connect\\n    self._request_authentication()\\n  File \\"/usr/local/lib/python3.6/dist-packages/pymysql/connections.py\\", line 861, in _request_authentication\\n    auth_packet = self._read_packet()\\n  File \\"/usr/local/lib/python3.6/dist-packages/pymysql/connections.py\\", line 684, in _read_packet\\n    packet.check_error()\\n  File \\"/usr/local/lib/python3.6/dist-packages/pymysql/protocol.py\\", line 220, in check_error\\n    err.raise_mysql_exception(self._data)\\n  File \\"/usr/local/lib/python3.6/dist-packages/pymysql/err.py\\", line 109, in raise_mysql_exception\\n    raise errorclass(errno, errval)\\n", "invocation": {"module_args": {"user": "laravel", "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "priv": "laravel.*:ALL", "login_host": "localhost", "login_port": 3306, "encrypted": false, "host": "localhost", "host_all": false, "state": "present", "append_privs": false, "check_implicit_admin": false, "update_password": "always", "connect_timeout": 30, "config_file": "/root/.my.cnf", "sql_log_bin": true, "login_user": null, "login_password": null, "login_unix_socket": null, "plugin": null, "plugin_hash_string": null, "plugin_auth_string": null, "client_cert": null, "client_key": null, "ca_cert": null}}}\r\n', b'Shared connection to 3.226.47.77 closed.\r\n')
<3.226.47.77> Failed to connect to the host via ssh: Shared connection to 3.226.47.77 closed.
<3.226.47.77> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<3.226.47.77> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ubuntu"' -o ConnectTimeout=10 -o StrictHostKeyChecking=no -o ControlPath=/home/daraul/.ansible/cp/a4d893a731 3.226.47.77 '/bin/sh -c '"'"'rm -f -r /home/ubuntu/.ansible/tmp/ansible-tmp-1574103853.575425-175696853591014/ > /dev/null 2>&1 && sleep 0'"'"''
<3.226.47.77> (0, b'', b'')
The full traceback is:
  File "/tmp/ansible_mysql_user_payload_oc31z0d7/__main__.py", line 691, in main
    connect_timeout=connect_timeout)
  File "/tmp/ansible_mysql_user_payload_oc31z0d7/ansible_mysql_user_payload.zip/ansible/module_utils/mysql.py", line 79, in mysql_connect
    db_connection = mysql_driver.connect(**config)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 599, in connect
    self._request_authentication()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 861, in _request_authentication
    auth_packet = self._read_packet()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception [...]

2019-11-18 19:31 UTC, gundalow commented
From your debug
`Using module file /home/daraul/dev/gwi-core-laravel/library/mysql_user.py` So that means it's using the correct version.

@Andersson007 Any ideas?

2019-11-19 07:03 UTC, bmalynovytch commented
@daraul I know this is annoying sometimes, but some client libraries convert implicitly `localhost` into `use the unix socket instead of localhost over TCP`.
Could you try configuring the path of the unix socket (`login_unix_socket`) in your ansible task instead of the `login_host`?

2019-11-19 14:12 UTC, daraul commented
Setting `login_unix_socket: /var/run/mysqld/mysqld.sock` worked like a charm using both the existing and updated versions of this module, @bmalynovytch.

2019-11-20 05:24 UTC, Andersson007 requested changes
could you please put the empty lines between examples back
1. it is not related to the changes
2. it was much more better (when not one bunch of text)

2019-11-20 11:23 UTC, gundalow commented on lib/ansible/modules/database/mysql/mysql_user.py
> -
Could you please keep the blank lines between tasks, it helps readability.

2019-11-20 11:23 UTC, gundalow commented on lib/ansible/modules/database/mysql/mysql_user.py
> +    version_added: "2.9"
```suggestion
    version_added: '2.10'
```

2019-11-20 11:23 UTC, gundalow commented on lib/ansible/modules/database/mysql/mysql_user.py
> +    version_added: "2.9"
```suggestion
    version_added: '2.10'
```

2019-11-20 11:23 UTC, gundalow commented on lib/ansible/modules/database/mysql/mysql_user.py
> +    version_added: "2.9"
```suggestion
    version_added: '2.10'
```

2019-11-20 11:23 UTC, gundalow commented on lib/ansible/modules/database/mysql/mysql_user.py
> +- mysql_user:
```suggestion

# Create database user with name 'bob' authenticated with 'AWSAuthenticationPlugin' (with proper hash_string) with all database privileges
- name:Create database user
  mysql_user:
```

ie
blank line
comment
task with name

2019-11-20 11:23 UTC, gundalow commented on lib/ansible/modules/database/mysql/mysql_user.py
> +    state: present
```suggestion
    state: present

```

2019-11-20 11:30 UTC, Andersson007 commented
considering that CI tests can be difficult to implement in this case, if there are a couple of people who tried it manually, IMO it might be merged after @gundalow 's requests are done

2019-11-22 16:33 UTC, abohne commented
@gundalow @Andersson007 I've been using this for a while to manage users with the `AWSAuthenticationPlugin` on AWS RDS.

2019-11-25 05:30 UTC, Andersson007 commented
@abohne , thanks for the feedback!
will wait for the author (until the next week, then i rewrite it if there's no feedback)

2019-12-04 14:49 UTC, 20ton requested changes
tested (with typo fixed):
```
- mysql_user:
    name: prometheus
    plugin: unix_socket
    priv: '*.*:PROCESS,REPLICATION CLIENT,SELECT'
    login_unix_socket: /run/mysqld/mysqld.sock
```
result:
```
MariaDB [(none)]> select Host,User,Password,Plugin from mysql.user;
+-----------+------------+-------------------------------------------+-------------+
| Host      | User       | Password                                  | Plugin      |
+-----------+------------+-------------------------------------------+-------------+
| localhost | root       |                                           | unix_socket |
| localhost | prometheus |                                           | unix_socket |
+-----------+------------+-------------------------------------------+-------------+
2 rows in set (0.001 sec)
```

2019-12-04 14:49 UTC, 20ton commented on lib/ansible/modules/database/mysql/mysql_user.py
> +        cursor.execute("CREATE USER %s@%s IDENTIFIED WITH %s", (user, host, plugin_auth_string))
plugin, not plugin_auth_string

2019-12-13 06:37 UTC, Andersson007 commented
Hey all!
I completed this one for you :) https://github.com/ansible/ansible/pull/65789
The code was copied. I only changed the doc strings a bit and functions argument strings.
@20ton i fixed the typo there
@abohne @bmalynovytch @gundalw please look

2019-12-13 07:43 UTC, Andersson007 commented
@gundalow , could you please close this via via https://github.com/ansible/ansible/pull/65789

2019-12-13 09:15 UTC, closed without merging