Add extended error message. issue#: 44340
ansible/ansible pull request #44375
Opened 2018-08-19 21:39 UTC by srinivascodes

Commit in the regard of issue: https://github.com/ansible/ansible/issues/44340, where a user is trying to unarchive an empty archive. This commit adds an extended message of not supporting unarchiving of empty archive files.

##### SUMMARY

##### ISSUE TYPE

 - Feature Pull Request
 - New Module Pull Request
 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME

##### ANSIBLE VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

2018-08-21 15:07 UTC, webknjaz commented
@srinivascodes please fill in the PR template when submitting new ones.

2018-08-21 15:09 UTC, sivel requested changes

2018-08-21 15:09 UTC, sivel commented on lib/ansible/modules/files/unarchive.py
> +        return False, 'Command "%s" found no files in archive. Unarchiving empty archive file is not supported yet.' % self.cmd_path
I don't think we should use the word `yet`, as that indicates we have already made the decision that it should, and we are actively working on changing it.

Also, we need to work a little on the grammar.

"Empty archive files are not supported"

2018-11-19 05:46 UTC, Akasurde commented
@srinivascodes Are you working on this ? Thanks.

2019-10-23 07:08 UTC, Akasurde commented
@srinivascodes Are you still working on this, let us know ? Thanks, needs_info

2019-11-04 05:57 UTC, srinivascodes commented
No. I am not working on this. Please close the PR.

Thanks.

On Wed, 23 Oct 2019, 12:40 pm Abhijeet Kasurde, <notifications@github.com>
wrote:

> @srinivascodes <https://github.com/srinivascodes> Are you still working
> on this, let us know ? Thanks, needs_info
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ansible/ansible/pull/44375?email_source=notifications&email_token=ADIBMLHTZWDGG2RQR5PC4SLQP72ERA5CNFSM4FQMQP3KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECAKO6A#issuecomment-545302392>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADIBMLHECK22INOJ3DMDH2LQP72ERANCNFSM4FQMQP3A>
> .
>

2019-11-08 09:54 UTC, closed without merging