Switch to LiteralPath instead of Path. Closes #44508
ansible/ansible pull request #44509
Opened 2018-08-22 14:13 UTC by crossan007

##### SUMMARY
Change all instances of `-Path` to `-LiteralPath`

Closes #44508

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
`win_lineinfile`

##### ANSIBLE VERSION
```
ansible 2.6.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

```

##### ADDITIONAL INFORMATION

https://www.reddit.com/r/PowerShell/comments/2wmzv8/why_you_should_consider_always_using_literalpath/

It's worth noting that the bracket usage within PowerShell paths does provide some functionality; however, I believe that the majority of Ansible playbook authors are not expecting PowerShell variable expansion / interpretation to occur on the paths passed to `win_lineinfile`.

2018-08-23 02:41 UTC, jborean93 requested changes
Are you able to add a changelog fragment for this fix?

2018-08-23 03:14 UTC, crossan007 commented
@jborean93 like so?

2018-08-27 05:53 UTC, jborean93 approved these changes

2018-08-27 06:18 UTC, merged

2018-08-27 06:19 UTC, jborean93 commented
@crossan007 are you able to create a backport PR to bring the fix to the stable-2.6 branch. Details on how to do this can be found here https://docs.ansible.com/ansible/latest/community/development_process.html#pull-requests.