Feature junos filter
ansible/ansible pull request #44703
Opened 2018-08-27 03:11 UTC by linnil1

##### SUMMARY

Add filter on vlan, l2_interface, l3_interface.

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

junos_vlan
junos_l3_interface
junos_l2_interface

##### ANSIBLE VERSION

```
devel
```

##### ADDITIONAL INFORMATION

```

```
Test on EX4300 14.1X53-D42.3.

2018-08-27 10:32 UTC, achinthagunasekara approved these changes

2018-09-07 03:31 UTC, linnil1 commented
I think that these options should be put in `junos_firewall` modules because it need to create a firewall filter before applying to these options.

2018-09-30 07:47 UTC, ganeshrn requested changes
Since 2.7 branch is in feature freeze. This PR can't be merged to devel in the current state. Can yo please update the `version_added` string to `2.8`

2019-01-08 14:38 UTC, abenokraitis commented
@linnil1 Can you please update this so that it works with 2.8 soon?

2019-01-08 14:43 UTC, IPvSean commented
@linnil1 are you saying to close this PR and add to junos firewall modules?  

If not.... @linnil1 can you make sure to provide examples, e.g. in the markdown portion of the https://docs.ansible.com/ansible/latest/modules/junos_l2_interface_module.html#examples there is rendered examples

2019-01-08 16:43 UTC, linnil1 commented
I think `junos_firewall` should be implemented before this PR.
`junos_firewall` may work like this:
```
    - name: set Firewall
      junos_firewall:
        name: firewall
        terms:
          - from:
              source-address: 192.168.200.3/32
              destination-address: 192.168.201.10/32
            then:
              count: c1
              accept:
          - from:
              source-address:
                - 192.168.201.3/32
                - 192.168.201.4/32
              destination-address: 192.168.200.10/32
            then:
              log:
            name: term_name
          - then:
              discard:
        active: True
        state: present
```
Do I need to provide another PR or just give feature request in issue?
There may be lots of detail for implement that I cannot handle now.

2019-01-22 15:15 UTC, ganeshrn approved these changes

2019-01-23 04:06 UTC, merged

2019-01-23 04:07 UTC, ganeshrn commented
@linnil1 Please raise a feature request issue on Github for `junos_firewall` issue so that it is not lost in PR comment.