Depreciate elementsw modules
ansible/ansible pull request #44792
Opened 2018-08-28 21:31 UTC by carchi8py

##### SUMMARY
With the new ElementSW modules merged in today the old Solidfire ones need to be deprecated 

##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME
* _sf_account_manager.py
* _sf_check_connections.py
* _sf_snapshot_schedule_manager.py
* _sf_volume_access_group_manager.py
* _sf_volume_manager.py

##### ANSIBLE VERSION

```
bash-3.2# ansible --version
ansible 2.7.0.dev0 (sf_commonfiles caf71e24dd) last updated 2018/08/06 10:46:57 (GMT -700)
  config file = None
  configured module search path = [u'/Users/chrisarchibald/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /private/tmp/ansible/lib/ansible
  executable location = /private/tmp/ansible/bin/ansible
  python version = 2.7.12 (default, Oct 11 2016, 05:20:59) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)]
```

##### ADDITIONAL INFORMATION

```

```

2018-08-28 22:19 UTC, lonico approved these changes

2018-08-29 08:00 UTC, gundalow requested changes

2018-08-29 08:00 UTC, gundalow commented on lib/ansible/modules/storage/netapp/_sf_account_manager.py
> +  alternative: please use na_elementsw_account
If you use `M(...)` you can get a link to the module's documentation. 

`alternative: Please use M(na_elementsw_account) `

Please update this for the tyer modules in this PR.

2018-08-29 16:51 UTC, gundalow approved these changes

2018-08-29 16:51 UTC, merged