add vcenter plugin module
ansible/ansible pull request #44963
Opened 2018-08-31 12:47 UTC by CastawayEGR

##### SUMMARY

##### ISSUE TYPE

 - Feature Pull Request
 - New Module Pull Request
 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME

##### ANSIBLE VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

2018-09-02 04:39 UTC, Akasurde requested changes
Could you please check if we can add unit tests for this change ?

2018-09-02 04:39 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vcenter_plugin.py
> +  type:
Could you please rename this parameter to something more descriptive ?

2018-09-02 04:39 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vcenter_plugin.py
> +- name: vCenter Plugin Examples
Line 68 to 73 not required.

2018-09-02 04:39 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vcenter_plugin.py
> +from ansible.module_utils.vmware import (HAS_PYVMOMI, connect_to_api, vmware_argument_spec)
Use 

```python
from ansible.module_utils.vmware import PyVmomi, ...
````

2018-09-02 04:39 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vcenter_plugin.py
> +    if not HAS_PYVMOMI:
not required if `PyVmomi` is used.

2018-09-02 04:39 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vcenter_plugin.py
> +        content = connect_to_api(module, False)
not required if `PyVmomi` is used.

2018-09-02 04:39 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vcenter_plugin.py
> +        results = dict(changed=False, result=dict())
rename return dict `result` to more specific name.

2018-09-03 00:58 UTC, CastawayEGR commented
To the best of my knowledge it does not look like unit tests can be added.

2018-09-03 01:34 UTC, CastawayEGR reviewed
@Akasurde recommended changes have been implemented at this time.

2018-09-05 12:33 UTC, CastawayEGR commented
@Akasurde can you advise on the next steps to remove the needs_revision label?

2018-09-05 13:01 UTC, Akasurde commented
@CastawayEGR Thanks for updating code as per code review comments. I will test it and let you know, that will hopefully remove needs_revision tag. Thanks.

2018-09-10 07:13 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vcenter_plugin.py
> +    from pyVmomi import vim, vmodl
vmodl is not used, so can be safely removed.

2018-09-10 07:14 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vcenter_plugin.py
> +    import datetime
I think datetime is basic datatype of Python and is available in all installation. So this check will not be required.

2018-09-10 11:12 UTC, Akasurde commented
@CastawayEGR I am sorry, but can we rename this to `vcenter_extension` or something similar. I found that it is more apt as we are dealing extension than plugins. People might get confused by name, as extension is more common than plugins. Let me know your views. Thanks.

2018-09-10 12:51 UTC, CastawayEGR commented
@Akasurde no worries at all. I had it named this way at first but thought it might be confusing. I agree with you considering how it is called in the pyvmomi documentation. All recommended edits have been made at this time. Thanks!

2018-09-18 12:58 UTC, CastawayEGR commented
@Akasurde is there anything else you need me to do on this end to get this module added?

2018-09-19 05:25 UTC, Akasurde approved these changes

2018-09-19 05:25 UTC, Akasurde commented
rebuild_merge

2018-09-19 12:28 UTC, merged

2018-09-19 12:28 UTC, Akasurde commented
@CastawayEGR Thanks for the contribution.