cpm_user concat string changes
ansible/ansible pull request #45044
Opened 2018-09-01 00:13 UTC by syncpak

##### SUMMARY
change the way the strings are concatenated 

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
cpm_user

##### ANSIBLE VERSION

```
ansible 2.8.0.dev0 (cpm_user_mod 048c517045) last updated 2018/08/31 17:10:27 (GMT -700)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/kenp/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/kenp/ansible/lib/ansible
  executable location = /home/kenp/ansible/bin/ansible
  python version = 2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]

```

##### ADDITIONAL INFORMATION
Changed str() to to_native()
Changed + string concat to %

```

```

2018-09-01 06:22 UTC, achinthagunasekara approved these changes

2018-09-04 15:22 UTC, samdoran requested changes
There are several other text strings that also need `to_native()`, such as `user_password` and `user_callbackphone`.

2018-09-04 17:33 UTC, syncpak commented
@samdoran we added what we believe to_native() to all the places that incorporate external values into strings. Thanks

2018-09-07 16:11 UTC, samdoran approved these changes

2018-11-09 21:29 UTC, samdoran approved these changes

2018-11-09 21:30 UTC, samdoran commented
rebuild_merge

2018-11-09 22:22 UTC, merged