IBM_Storage: Added a module to define volume mapping on IBM spectrum …
ansible/ansible pull request #45110
Opened 2018-09-03 12:02 UTC by tzurE

…Accelerate

storage systems.

##### SUMMARY
Adding a new module to the IBM storage modules. This module adds or removes volume mapping to hosts on the IBM Spectrum accelerate storage array

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME
ibm_sa_vol_map

##### ANSIBLE VERSION

```
ansible 2.8.0.dev0 (add_ibm_storage_vol_mapping_module 1eb5a95f80) last updated 2018/09/03 14:30:33 (GMT +300)
```

##### ADDITIONAL INFORMATION

```

```

2018-10-18 15:24 UTC, samdoran requested changes
For new modules that we cannot test, we like to have a few community members weigh in and state the module works as intended.

2018-10-18 15:24 UTC, samdoran commented on lib/ansible/modules/storage/ibm/ibm_sa_vol_map.py
> +from ansible.module_utils.ibm_sa_utils import execute_pyxcli_command, \
Rather than using a backslash continuation for multiple imports, use parentheses:

```suggestion
from ansible.module_utils.ibm_sa_utils import (
    execute_pyxcli_command,
    connect_ssl,
    spectrum_accelerate_spec,
    is_pyxcli_installed,
)
```

See [PEP 328](https://www.python.org/dev/peps/pep-0328/#rationale-for-parentheses) for rationale.

2018-10-21 08:00 UTC, tzurE commented on lib/ansible/modules/storage/ibm/ibm_sa_vol_map.py
> +from ansible.module_utils.ibm_sa_utils import execute_pyxcli_command, \
will fix

2018-10-21 08:01 UTC, tzurE commented on lib/ansible/modules/storage/ibm/ibm_sa_vol_map.py
> +from ansible.module_utils.ibm_sa_utils import execute_pyxcli_command, \
Regarding the new modules - We've tested this internally with our arrays. Same as we tested the other modules we contributed in Ansible 2.7

2018-10-24 13:07 UTC, tzurE commented
@samdoran - Hi, I fixed and commented on all of the issues :)

2018-10-29 13:48 UTC, samdoran approved these changes

2018-10-29 13:50 UTC, merged