expect ssh_key_data to be a string instead of path
ansible/ansible pull request #45158
Opened 2018-09-04 11:31 UTC by Meecr0b

ssh_key_data should be a string filled with the private key
the old behavior can be archived with a lookup

##### SUMMARY
The *ssh_key_data* variable should behave like in Tower/AWX. It should contain the content of the  ssh_key_data instead of being the path to the ssh_key_file.
The old behavior can be archived with a lookup.

Fixes #45119

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
tower_credential

##### ANSIBLE VERSION
```
2.8.0
```

##### ADDITIONAL INFORMATION

2018-09-04 11:34 UTC, MarkusTeufelberger commented
Might need some line(s) in the changelog, but thanks for the quick patch! :+1:

2018-09-04 15:39 UTC, samdoran reviewed
Also add an option for `ssh_key_path` and an example of how to use the `file` lookup.

It may be good to add a note to the porting guide for 2.8 as well.

2018-09-04 15:39 UTC, samdoran commented on lib/ansible/modules/web_infrastructure/ansible_tower/tower_credential.py
> +        - SSH private key.
Add a note to use a lookup in order to maintain the previous behavior.

2018-09-04 15:39 UTC, samdoran commented on lib/ansible/modules/web_infrastructure/ansible_tower/tower_credential.py
> +      default: null
This line is not needed.

2018-09-04 15:39 UTC, samdoran commented on lib/ansible/modules/web_infrastructure/ansible_tower/tower_credential.py
> -                if not os.path.exists(filename):
Rather than remove this entirely, I would leave this in as a fallback and warn (do not fail) that this behavior will be changed in the future.

2018-09-04 15:39 UTC, samdoran commented on test/integration/targets/tower_credential/tasks/main.yml
> +  local_action: "shell cat {{ tempdir.stdout }}/id_rsa"
Use a lookup with `set_fact` rather that `local_action: shell`.

2018-09-05 08:10 UTC, Meecr0b commented
Hi @samdoran,
first of all, thx for review. I implemented your comments, except of the additional ``ssh_key_path`` option, because i really don't see the benefits. Can you explain your thoughts?

2018-09-05 18:09 UTC, samdoran commented
@Meecr0b I was just thinking you could add it as a new, accurately named option if someone wanted the existing behavior of having the module ingest the key data from a file without having to use a lookup. But it was just a suggestion and if you don't see value in it, then don't worry about adding it.

2018-09-05 18:19 UTC, samdoran requested changes

2018-09-05 18:19 UTC, samdoran commented on lib/ansible/modules/web_infrastructure/ansible_tower/tower_credential.py
> +                        msg='ssh_key_data should be a string, filled with the private key. Use lookup(\'file\', \'/path/to/file\') instead'
I would reword this message to indicated a path to a file was provided. Something like "ssh_key_data should be a string, not a path to a file".

Also add `version=2.12` the `deprecate()` call.

2018-09-05 18:19 UTC, samdoran commented on lib/ansible/modules/web_infrastructure/ansible_tower/tower_credential.py
> +                        module.fail_json(msg='attempted to read contents of directory: %s' % data)
I would also add the deprecation warning here in addition to the failure.

2018-09-05 20:17 UTC, Meecr0b commented
@samdoran thx for explanation. In this case, i would prefer the ansible native solution, instead of supporting custom python code.

2018-09-05 20:28 UTC, Meecr0b commented on lib/ansible/modules/web_infrastructure/ansible_tower/tower_credential.py
> +                        module.fail_json(msg='attempted to read contents of directory: %s' % data)
The failure is just an additional error, the depraction warning will be returned in any case.
Or did i misunderstand you?

2018-09-06 13:48 UTC, samdoran commented on lib/ansible/modules/web_infrastructure/ansible_tower/tower_credential.py
> +                        module.fail_json(msg='attempted to read contents of directory: %s' % data)
You're correct. I misread that this `if` statement is indented. Looks good!

2018-09-06 13:48 UTC, samdoran approved these changes

2018-09-06 13:53 UTC, samdoran commented
Please create a changelog fragment. See [fragments](https://github.com/ansible/ansible/blob/stable-2.6/changelogs/fragments/user-properly-unexpire-new-user.yaml) for examples.

2018-09-07 08:02 UTC, Meecr0b commented
Thx for example, [done](https://github.com/Meecr0b/ansible/blob/devel/changelogs/fragments/tower_credential_ssh_key_data.yaml)

2018-09-07 15:22 UTC, acozine commented
Thanks @Meecr0b for contributing! I wordsmithed the documentation a bit. PR looks good to me.

2018-09-07 17:41 UTC, merged

2018-09-08 01:37 UTC, mattclay commented
This change appears to be causing the tower_project integration test to fail:

https://app.shippable.com/github/ansible/ansible/runs/83068/90/tests