Fix systemd service checks against rc return code. Fixes #44409.
ansible/ansible pull request #45253
Opened 2018-09-05 21:37 UTC by vwbusguy

##### SUMMARY
Fixes #44409 .  In short, systemctl returns 0 for a service that is known and enabled and 1 if a service is known and disabled.  There is additional logic in ansible for determining if a service is a valid sysv service but not a systemd service, however, it evaluated this on the basis of an rc of 1 (in the systemd module) or !0 (service module).  A missing system service file will return an rc of 4, not 1.  By evaluating based on 1, Ansible returns a false positive for a service being enabled for services that ship *both* systemd and sysc init files.  Examples include, nginx's official debian packaging and Treasure Data's rpm packaging (see associated issue for source links).
Evaluating rc >1 fixes the false positive while properly retaining the sysv check in the case that a service file is not found as a systemd service, but exists as a sysv service.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
service and systemd modules

##### ANSIBLE VERSION

```
ansible 2.8.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, May 15 2018, 15:37:31) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
```
This output is from a Fedora 28 docker container with Ansible built against this commit via rpm.  The same bug has been seen in 2.6.2 and 2.6.3 as reported in the issue.

##### ADDITIONAL INFORMATION
As an example against a remote system with td-agent installed:
```paste below
ansible ... -m 'service' -a 'name=network enabled=yes'
ansible ... -m 'systemd' -a 'name=network enabled=yes'
```
Before fix and after running either of these:
`systemctl is-enabled td-agent.service` reports "disabled"
Ansible shows service is enabled with no change despite reporting `"UnitFileState": "disabled"` with verbose output

After the fix:
`systemctl is-enabled td-agent.service` reports "enabled"
Ansible detects a the service was disabled and reports a change

Also tested:
Proper reporting of various sysv only services in RHEL 7.4 remote target.

2018-09-05 21:43 UTC, bcoca commented on lib/ansible/modules/system/service.py
> +        elif rc > 1 and sysv_exists(service_name):
this has changed over time, rc is not a reliable way to judge existence ... looking at alternative way .. currently dbus seems like only reliable way to get the info.

2018-09-05 22:23 UTC, bcoca requested changes
change requires 'latest' systemd as previous versions dont' respond the same way via their RC code

i.e on jessie you always get rc == 1 on error or missing 

so we still need separate checks or start using dbus (looking to see if these statuses are more reliable)

2018-09-05 23:03 UTC, vwbusguy commented
Thanks - I'll test against Jessie.

2018-09-05 23:55 UTC, bcoca commented on lib/ansible/modules/system/service.py
> +        elif rc > 1 and sysv_exists(service_name):
so here we just need to check if service file exists and can handle ==1 and >1 rc more intelligently

2018-09-05 23:56 UTC, bcoca commented on lib/ansible/modules/system/systemd.py
> +            elif rc > 1:
found and is_sysv variables allow us to handle the rc better, `rc == 1 and found and not is_sysv ...  else`

2018-09-05 23:57 UTC, bcoca commented on lib/ansible/modules/system/systemd.py
> +            elif rc > 1:
might still need to check stdout/err for errors

2018-09-06 00:26 UTC, vwbusguy commented
Would it make more sense to combine the logic on these with a common handler in module utils? If not for this PR, perhaps a followup refactoring would help for maintaining this better longterm?

2018-09-06 01:35 UTC, bcoca commented
possibly, but the service module is on it's way out, the  'init specific' modules do things in different ways to allow for more custom options as service needs to cater to 'all' vs the specific init system, so I have tried to avoid updating it.

2022-01-26 19:25 UTC, jborean93 commented
Looks like the original issue linked was fixed with https://github.com/ansible/ansible/pull/46245 and it should have also fixed this particular problem in another way.

2022-01-26 19:25 UTC, closed without merging

2022-01-26 23:26 UTC, vwbusguy commented
Thanks for the follow up @jborean93 !