meraki_network - Fix enabling my.meraki.com
ansible/ansible pull request #45352
Opened 2018-09-07 15:19 UTC by kbreit

##### SUMMARY
- A parameter of "no" wouldn't be picked up
- Check for False in addition to whether it exists

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
meraki_network

##### ANSIBLE VERSION
```
ansible 2.8.0.dev0 (meraki/fix_merakicom f27a1cf680) last updated 2018/09/07 09:49:04 (GMT -500)
  config file = None
  configured module search path = ['/Users/kbreit/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/kbreit/Documents/Programming/ansible/lib/ansible
  executable location = /Users/kbreit/Documents/Programming/ansible/bin/ansible
  python version = 3.5.4 (default, Feb 25 2018, 14:56:02) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

2018-09-08 01:48 UTC, dagwieers requested changes

2018-09-08 01:48 UTC, dagwieers commented on lib/ansible/modules/network/meraki/meraki_network.py
> -        if meraki.params['disable_my_meraki']:
I don't get this. So a boolean parameter can only be True, False or None.
So in this case I would expect this (and other checks) to state:
```python
    if meraki.params['disable_my_meraki'] is not None:
        payload['disableMyMerakiCom'] = meraki.params['disable_my_meraki']
```

2018-09-08 15:22 UTC, kbreit commented on lib/ansible/modules/network/meraki/meraki_network.py
> -        if meraki.params['disable_my_meraki']:
Good call, fixed.

2018-09-09 18:31 UTC, dagwieers approved these changes

2018-09-09 18:31 UTC, merged