Move network utils that are used by AWS modules
ansible/ansible pull request #45579
Opened 2018-09-12 19:32 UTC by s-hertel

##### SUMMARY
Separate networking tools that may be used by modules outside of networking so changes to networking-only utilities don't trigger AWS integration tests

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/module_utils/common/network.py

##### ANSIBLE VERSION
```
ansible 2.8.0.dev0
```

2018-09-12 19:49 UTC, mattclay requested changes

2018-09-12 19:49 UTC, mattclay commented on lib/ansible/module_utils/network/common/utils.py
>  def to_bits(val):
Although only used by the network modules, it isn't specific to them, so this should probably move as well.

2018-09-13 13:33 UTC, ryansb approved these changes

2018-09-13 15:57 UTC, mattclay approved these changes

2018-09-19 14:28 UTC, Qalthos approved these changes

2018-09-19 14:30 UTC, pabelanger commented
I'll look into this

2018-09-26 12:28 UTC, pabelanger approved these changes
+1 looks correct

2018-10-02 18:14 UTC, s-hertel commented
rebuild_merge

2018-10-02 19:08 UTC, merged