Port the sns module to boto3
ansible/ansible pull request #45634
Opened 2018-09-13 19:49 UTC by flowerysong

##### SUMMARY

Ports the sns module to boto3 and AnsibleAWSModule. Adds support for protocol-specific messages targeting newer protocols, including 'lambda'.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

sns

##### ANSIBLE VERSION
2.8

##### ADDITIONAL INFORMATION

```paste below
ok: [tasty-deepone.syslog.x.mail.umich.edu -> localhost] => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "application": null, 
            "aws_access_key": null, 
            "aws_secret_key": null, 
            "ec2_url": null, 
            "email": null, 
            "email_json": null, 
            "http": null, 
            "https": null, 
            "lambda": "{\"source\": \"pandora.x.mail.umich.edu\", \"message\": \"H\\u00e9r fylgir stu\\u00f0ning hverri sannkenning, sv\\u00e1 sem k\\u00f6llu\\u00f0 er eggin \\u00f3h\\u00f6r\\u00f0, en fullhvatir mennirnir.\", \"sourcetype\": \"ansible\"}", 
            "message_attributes": null, 
            "message_structure": "json", 
            "msg": "Hér er stafasetning sú, er hætti ræðr ok kveðandi gerir.", 
            "profile": "vdc-nonprod", 
            "region": "us-west-2", 
            "security_token": null, 
            "sms": null, 
            "sqs": null, 
            "subject": "Hello from Ansible", 
            "topic": "rootmail", 
            "validate_certs": true
        }
    }, 
    "message_id": "d46335db-7f32-5843-a5f2-61cfbf9eb7b5", 
    "msg": "OK"
}
```

2018-09-13 21:59 UTC, willthames requested changes

2018-09-13 21:59 UTC, willthames commented on lib/ansible/modules/cloud/amazon/sns.py
> +        token = response.get('NextToken')
ListTopics has a [paginator](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sns.html#SNS.Paginator.ListTopics)

2018-09-13 21:59 UTC, willthames commented on lib/ansible/modules/cloud/amazon/sns.py
> +        argument_spec[p] = dict(type='str', default=None)
You can use just `dict()` rather than `dict(type='str', default=None)`

2018-09-13 22:00 UTC, willthames commented
This is great work, thanks. Could we have a test suite too please.

2018-09-14 00:19 UTC, flowerysong commented on lib/ansible/modules/cloud/amazon/sns.py
> +        token = response.get('NextToken')
Why, so it does.

2018-09-18 14:23 UTC, s-hertel reviewed
Looks good. Just could use some integration tests to help ensure backwards compatibility.

2018-09-18 14:23 UTC, s-hertel commented on lib/ansible/modules/cloud/amazon/sns.py
> +    topic_iterator = paginator.paginate()
Please wrap the client and paginator methods in a try/except and handle BotoCoreError and ClientError

2018-10-05 19:12 UTC, ryansb approved these changes

2018-10-05 19:12 UTC, ryansb commented
@willthames can you have a second look at this?

2018-10-07 07:31 UTC, willthames approved these changes

2018-10-07 07:32 UTC, willthames commented
rebuild_merge

2018-10-07 20:03 UTC, merged