Ovirt_disk fails with "The 'value' parameter must be an integer"
ansible/ansible pull request #45643
Opened 2018-09-14 10:02 UTC by rhodain

##### SUMMARY

Ovirt_disk fails with error:

An exception occurred during task execution. To see the full traceback, use
-vvv. The error was: TypeError: The 'value' parameter must be an integer
localhost | FAILED! => {
    "changed": false,
    "msg": "The 'value' parameter must be an integer"
}

when specifying a port for iSCSI target for direct LUN creation. This
commit converts the port string into the integer.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

ovirt_disk
##### ANSIBLE VERSION

```paste below
ansible 2.6.3
```

##### ADDITIONAL INFORMATION

This issue can be reproduced by calling. It has to be a new disk with new LUN_ID

./hacking/test-module -m ./lib/ansible/modules/cloud/ovirt/ovirt_disk.py -a "name=Disk01 logical_unit=target=iqdn,address=10.10.10.10,id=36001405fb6247061a564688a9baa34db,port=3260"

```paste below
Before:
An exception occurred during task execution. To see the full traceback, use
-vvv. The error was: TypeError: The 'value' parameter must be an integer
localhost | FAILED! => {
    "changed": false,
    "msg": "The 'value' parameter must be an integer"
}

After:
no error message and disk is created.
```

2018-09-16 10:22 UTC, mscherer requested changes

2018-09-16 10:22 UTC, mscherer commented on lib/ansible/modules/cloud/ovirt/ovirt_disk.py
> +                lun["port"] = int(lun.get("port"))
So, if a user give a invalid value, thos would fail, could a better error message be added ?

2018-09-17 06:58 UTC, rhodain commented on lib/ansible/modules/cloud/ovirt/ovirt_disk.py
> +                lun["port"] = int(lun.get("port"))
These are the parameters which I used. 
    logical_unit=target=iqdn,address=10.10.10.10,id=36001405fb6247061a564688a9baa34db,port=3260

The port seems to be correct. So maybe a better documentation is needed if setting the port in this way is incorrect.

2018-09-24 12:08 UTC, rhodain commented on lib/ansible/modules/cloud/ovirt/ovirt_disk.py
> +                lun["port"] = int(lun.get("port"))
Is the port really incorrectly set? I seem correct to me.

2018-09-24 19:06 UTC, mscherer commented on lib/ansible/modules/cloud/ovirt/ovirt_disk.py
> +                lun["port"] = int(lun.get("port"))
No, I mean if someone set port=foo , the module will show a traceback, and I think it would a better UX to show a message or something.

2020-04-08 12:42 UTC, mnecas commented
We can close this PR and if needed can continue on it in ovirt collection.
https://github.com/oVirt/ovirt-ansible-collection

2020-06-30 12:58 UTC, Akasurde commented
Hi @rhodain, Thank you very much for your interest in Ansible. This plugin/module is no longer maintained in this repository and has been migrated to https://github.com/oVirt/ovirt-ansible-collection<br><br>If you have further questions please stop by IRC or the mailing list:<br><br>* IRC: #ansible on irc.freenode.net<br>* mailing list: https://groups.google.com/forum/#!forum/ansible-project<br>

2020-06-30 12:58 UTC, closed without merging