Add the ability to reset the master log too
ansible/ansible pull request #45668
Opened 2018-09-14 19:35 UTC by mikeSimonson

##### SUMMARY
I am in a situation where I need to reset a set of cluster regularly and to do so reliably, I need to be able to reset the master too.
The pull request is really small as it's just a matter of sending one query.
First PR in python so very open to suggestion.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
mysql_replication

##### ANSIBLE VERSION

##### ADDITIONAL INFORMATION

2018-09-14 20:17 UTC, s-hertel commented on lib/ansible/modules/database/mysql/mysql_replication.py
> +    except:
You've probably done it for consistency with the rest of the module, but this should handle specifically anticipated exceptions here. At the minimum it should be `except Exception:`. Here's an open pull request that's fixing the rest of those in this module: https://github.com/ansible/ansible/pull/45389

2019-02-19 13:47 UTC, bmalynovytch requested changes

2019-02-19 13:47 UTC, bmalynovytch commented on lib/ansible/modules/database/mysql/mysql_replication.py
> +    except:
```suggestion
    except Exception:
```

2019-10-11 11:34 UTC, gundalow commented
This has been fixed in `devel` by another PR, so closing.

2019-10-11 11:34 UTC, closed without merging