botmeta support: core
ansible/ansible pull request #45917
Opened 2018-09-20 13:42 UTC by gundalow

##### SUMMARY
Lets protect against accidental/deliberate changes to BOTMETA

```

Command exited with status 0 after 0.368102073669 seconds.
ERROR: Found 1 botmeta issue(s) which need to be resolved:
ERROR: .github/BOTMETA.yml:0:0: .github/BOTMETA.yml MUST be support: core
ERROR: The 1 sanity test(s) listed below (out of 1) failed. See error output above for details.
botmeta
```
##### ISSUE TYPE
- Bugfix Pull Request

2018-09-20 13:46 UTC, dagwieers commented
Ansibot could write the last successful parsed document out, and use it as a backup when the real stuff fails. (And escalate)

Do we already parse the BOTMETA.yml file in CI ?

2018-09-20 13:46 UTC, dagwieers approved these changes
LGTM

2018-09-20 14:05 UTC, mkrizek approved these changes

2018-09-20 17:12 UTC, mattclay requested changes

2018-09-20 17:12 UTC, mattclay commented on test/sanity/code-smell/botmeta.py
> +    botmeta_support = botmeta.get('files', {}).get('.github/BOTMETA.yml', '').get('support', '')
```python
botmeta_support = botmeta.get('files', {}).get('.github/BOTMETA.yml', {}).get('support', '')
```

2018-09-25 15:35 UTC, mattclay approved these changes

2018-09-25 17:37 UTC, merged