nmcli: Introduce SIT Tunnel
ansible/ansible pull request #45937
Opened 2018-09-20 21:55 UTC by ssahani

This work enables to add sit tunnel via nmcli module

Signed-off-by: Susant Sahani <susant@redhat.com>

##### SUMMARY

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

nmcli
##### ANSIBLE VERSION

```paste below
2.8
```

##### ADDITIONAL INFORMATION

```
  - nmcli:
       state: present
       type: ipip
       conn_name: sit_test1
       autoconnect: yes
       sit_dev: enp0s8
       sit_local: 192.168.1.2
       sit_remote: 192.168.1.5
```

2018-09-27 15:54 UTC, Akasurde requested changes
Thanks for the contribution. Could you please write a test for this change here - https://github.com/ansible/ansible/blob/devel/test/units/modules/net_tools/test_nmcli.py ? Thanks.

2018-09-27 15:54 UTC, Akasurde commented on lib/ansible/modules/net_tools/nmcli.py
> +        cmd = [self.nmcli_bin]
```python
cmd = [self.nmcli_bin, 'con', 'add', 'type', 'ip-tunnel', 'mode', 'sit', 'con-name']
```

2018-09-27 15:54 UTC, Akasurde commented on lib/ansible/modules/net_tools/nmcli.py
> +        cmd = [self.nmcli_bin]
```python
cmd = [self.nmcli_bin, 'con', 'mod']
```

2018-09-28 03:51 UTC, ssahani commented on lib/ansible/modules/net_tools/nmcli.py
> +        cmd = [self.nmcli_bin]
yes sure . updated.

2018-09-28 03:56 UTC, ssahani commented
I have updated not sure how to run these tests locally ?

2018-09-28 04:04 UTC, Akasurde commented
@ssahani You can run tests locally using following command - 

```
# pytest -r a -n auto --color yes --junit-xml test/results/junit/python2.6-units.xml -v test/units/modules/net_tools/test_nmcli.py
```

2018-09-28 04:22 UTC, ssahani commented
Thanks apparently I am missing something
```

 pytest -r a -n auto --color yes --junit-xml test/results/junit/python2.6-units.xml -v test/units/modules/net_tools/test_nmcli.py
usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: -n test/units/modules/net_tools/test_nmcli.py
  inifile: /home/sus/py/ansible-nmcli-sit/tox.ini
  rootdir: /home/sus/py/ansible-nmcli-sit
```
Ok I fixed it  will fix the test cases

2018-09-28 10:16 UTC, ssahani commented
@Akasurde Thanks for reviewing. Seems all tests passed.

2018-10-26 19:58 UTC, ssahani commented
@Akasurde  Ping

2018-10-30 09:03 UTC, Akasurde commented
@ssahani Could you please rebase this ? needs_info

2018-10-31 08:27 UTC, ssahani commented
Thanks for looking into it. I have updated https://github.com/ansible/ansible/pull/45933 . SInce again be a be conflict once IPIP PR get merged I will rebase it.

2018-11-17 05:15 UTC, Akasurde commented
@ssahani #45933 is merged. Could you please rebase this ? Thanks.

2018-11-17 11:44 UTC, ssahani commented
@Akasurde Thanks updated.

2018-11-18 06:00 UTC, Akasurde approved these changes

2018-12-13 03:42 UTC, Akasurde commented
rebuild_merge

2018-12-13 04:06 UTC, merged