stop requiring description. this is not a mandated jira field for all…
ansible/ansible pull request #46023
Opened 2018-09-22 01:03 UTC by stobias123

##### SUMMARY

Fixes: #46022  https://github.com/ansible/ansible/issues/46022

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

jira
##### ANSIBLE VERSION

Only tested below.
```paste below
ansible 2.7.0.a1.post0
```

##### ADDITIONAL INFORMATION

```paste below

```

2018-11-29 12:24 UTC, Akasurde requested changes

2018-11-29 12:24 UTC, Akasurde commented on lib/ansible/modules/web_infrastructure/jira.py
> +OP_REQUIRED = dict(create=['project', 'issuetype', 'summary'],
Could you please add a note in DOCUMENTATION section stating this requirement ? Thanks.

2018-11-29 12:24 UTC, gundalow commented
Could you please add a changelog/fragment for this, see https://docs.ansible.com/ansible/devel/community/development_process.html#changelogs

2018-11-29 12:28 UTC, webknjaz commented on lib/ansible/modules/web_infrastructure/jira.py
> +OP_REQUIRED = dict(create=['project', 'issuetype', 'summary'],
(and a changelog note)

2018-12-11 05:49 UTC, stobias123 commented on lib/ansible/modules/web_infrastructure/jira.py
> +OP_REQUIRED = dict(create=['project', 'issuetype', 'summary'],
- added changelog 
- documentation already shows that description is not required [L#59](https://github.com/ansible/ansible/blob/aabc1e072c59bd9074613f2fc6e9eab2109cab75/lib/ansible/modules/web_infrastructure/jira.py#L59)

2018-12-11 14:24 UTC, gundalow approved these changes

2018-12-11 14:24 UTC, merged

2018-12-11 14:24 UTC, gundalow commented
Merged into `devel` for release in Ansible 2.8, thanks