Update typetalk.py
ansible/ansible pull request #46039
Opened 2018-09-22 13:14 UTC by is2ei

Now Typetalk uses "com" domain.
FYI: https://www.typetalk.com/blog/typetalk-gets-new-top-level-domain-typetalk-com/

+label: docsite_pr

##### SUMMARY
Typetalk usess "com" domain now.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
typetalk

##### SUMMARY

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### COMPONENT NAME

##### ANSIBLE VERSION

```paste below

```

##### ADDITIONAL INFORMATION

```paste below

```

2018-09-22 18:42 UTC, dagwieers requested changes

2018-09-22 18:42 UTC, dagwieers commented on lib/ansible/modules/notification/typetalk.py
> +  - Send a message to typetalk using typetalk API ( https://developer.nulab-inc.com/docs/typetalk/ )
Is there any relevance in having the URL in the module's description ?
I would move it into the notes and make it a proper link.
Use either U(https://developer.nulab-inc.com/docs/typetalk/) or L(Typetalk API,https://developer.nulab-inc.com/docs/typetalk/).

2018-09-22 19:31 UTC, is2ei commented
@dagwieers 
Thanks for your comment! I updated it. Could you review it?

2018-09-23 03:07 UTC, closed without merging

2018-09-24 10:15 UTC, dagwieers commented
@is2ei Why did you close this ?

2018-09-24 14:10 UTC, is2ei commented
@dagwieers 
Thanks for your comment. I created another PR. 
https://github.com/ansible/ansible/pull/46045