Fortinet FortiManager Firewall Objects - Addresses
ansible/ansible pull request #46084
Opened 2018-09-24 19:01 UTC by ftntcorecse

##### SUMMARY

This module allows the add/set/delete of Firewall Objects -- in specific address objects -- to packages within FortiManager. These to be pushed later.

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

fmgr_fwobj_address.py
test_fmgr_fwobj_address.py
fixtures/test_fmgr_fwobj_address.json
##### ANSIBLE VERSION

```paste below
ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/ansible_modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### ADDITIONAL INFORMATION

```paste below

```

2018-11-09 16:42 UTC, samccann requested changes

2018-11-09 16:42 UTC, samccann commented on lib/ansible/modules/network/fortimanager/fmgr_fwobj_address.py
> +  -  Allows for the management of ipv4, ipv6, and multicast address objects within FortiManager
```suggestion
  -  Allows for the management of IPv4, IPv6, and multicast address objects within FortiManager.
```

2018-11-09 16:42 UTC, samccann commented on lib/ansible/modules/network/fortimanager/fmgr_fwobj_address.py
> +      - The FortiManager Address.
```suggestion
      - The FortiManager address.
```

2018-11-09 16:42 UTC, samccann commented on lib/ansible/modules/network/fortimanager/fmgr_fwobj_address.py
> +      - Color of the object in FortiManager GUI
```suggestion
      - Color of the object in the FortiManager GUI.
```

2018-11-09 16:42 UTC, samccann commented on lib/ansible/modules/network/fortimanager/fmgr_fwobj_address.py
> +      - Comment for the object in FortiManager
```suggestion
      - Comment for the object in FortiManager.
```

2018-11-09 16:42 UTC, samccann commented on lib/ansible/modules/network/fortimanager/fmgr_fwobj_address.py
> +      - Country name. Required if type = geographic
```suggestion
      - Country name. Required if type = geographic.
```

2018-11-09 16:42 UTC, samccann commented on lib/ansible/modules/network/fortimanager/fmgr_fwobj_address.py
> +      - Must not be specified with either multicast or ipv6 parameters
```suggestion
      - Must not be specified with either multicast or IPv6 parameters.
```

2018-11-09 16:42 UTC, samccann commented on lib/ansible/modules/network/fortimanager/fmgr_fwobj_address.py
> +      - End IP. Only used when ipv4 = range.
```suggestion
      - End IP. Only used when ipv4 = iprange.
```

2018-11-09 16:42 UTC, samccann commented on lib/ansible/modules/network/fortimanager/fmgr_fwobj_address.py
> +      - When multicast is set to Broadcast Subnet the ipv4addr parameter is used to specify the subnet
```suggestion
      - When multicast is set to Broadcast Subnet the ipv4addr parameter is used to specify the subnet.
```

2018-11-09 16:42 UTC, samccann commented on lib/ansible/modules/network/fortimanager/fmgr_fwobj_address.py
> +      - Must not be specified with either ipv4 or multicast parameters
```suggestion
      - Must not be specified with either ipv4 or multicast parameters.
```

2018-11-09 16:42 UTC, samccann commented on lib/ansible/modules/network/fortimanager/fmgr_fwobj_address.py
> +      - IPv6 Address in Full
```suggestion
      - IPv6 address in full.
```

2018-11-09 16:42 UTC, samccann commented on lib/ansible/modules/network/fortimanager/fmgr_fwobj_address.py
> +      - IPv6 Address in Full
it might be worth adding an example of what you mean by IPv6 address in full, like you have in the example - 2001:0db8:85a3:0000:0000:8a2e:0370:7334

2018-11-09 16:42 UTC, samccann commented on lib/ansible/modules/network/fortimanager/fmgr_fwobj_address.py
> +      - Sets one of three modes for managing the object
```suggestion
      - Sets one of three modes for managing the object.
```

2018-11-09 16:42 UTC, samccann commented on lib/ansible/modules/network/fortimanager/fmgr_fwobj_address.py
> +      - Start IP. Only used when ipv4 = range.
```suggestion
      - Start IP. Only used when ipv4 = iprange.
```

2018-11-09 16:42 UTC, samccann commented on lib/ansible/modules/network/fortimanager/fmgr_fwobj_address.py
> +      - IP address and wildcard netmask. Required if ipv4 = wildcard
```suggestion
      - IP address and wildcard netmask. Required if ipv4 = wildcard.
```

2018-11-09 16:42 UTC, samccann commented on lib/ansible/modules/network/fortimanager/fmgr_fwobj_address.py
> +      - Wildcard FQDN. Required if ipv4 = wildcard-fqdn
```suggestion
      - Wildcard FQDN. Required if ipv4 = wildcard-fqdn.
```

2018-11-09 16:42 UTC, samccann commented on lib/ansible/modules/network/fortimanager/fmgr_fwobj_address.py
> +    ipv6: "ipprefix"
This doesn't match the choices listed on line 114 for this parameter.

2018-11-12 18:34 UTC, ftntcorecse commented
@samccann Hola! Made the changes you requested. Thanks much. Going to go through our other PRs and start to make similar changes.

2018-11-12 18:53 UTC, samccann approved these changes
Looks good from the docs perspective, thanks!

2018-11-12 19:25 UTC, ftntcorecse commented
Removed "@" mentions under author and instead replaced with a hyphen not to "trip" the cascading notifications ansibot detected.

2018-11-21 06:30 UTC, NilashishC approved these changes

2018-11-21 06:30 UTC, NilashishC commented
LGTM

2018-11-21 06:30 UTC, merged