support for connection_name on multi-source replication (https://mari…
ansible/ansible pull request #46243
Opened 2018-09-28 01:47 UTC by diegobill

…adb.com/kb/en/library/multi-source-replication/)

##### SUMMARY
support for connection_name on multi-source replication (https://mariadb.com/kb/en/library/multi-source-replication/)

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
module mysql mysql_replication

##### ANSIBLE VERSION
```
ansible 2.8.0.dev0
  config file = None
  configured module search path = ['/home/felix/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/felix/workspace/tapweb.cgi/.env/lib/python3.5/site-packages/ansible
  executable location = /home/felix/workspace/tapweb.cgi/.env/bin/ansible
  python version = 3.5.2 (default, Nov 23 2017, 16:37:01) [GCC 5.4.0 20160609]
```

2018-10-01 15:41 UTC, bcoca requested changes

2018-10-01 15:41 UTC, bcoca commented on lib/ansible/modules/database/mysql/mysql_replication.py
> +    connection_name:
missing version_added

2019-03-03 03:38 UTC, CyberBLN commented
@diegobill Can you please rebase your branch to get it merged into official repo? Thank you :)

2019-10-01 11:36 UTC, Andersson007 commented
@diegobill  , hello, thank you for the pr
I've recently added integration tests for mariadb from scratch ```test/integration/targets/mariadb_replication/tasks/```.
Now it is possible to test mysql_replication module.
So, could you please
1. add tests for this pr by separate file and including it to test/integration/targets/mariadb_replication/tasks/main.yml
2. An example of using this parameter to Example block

After that i review it.
(Would be cool to get a feedback ASAP, i can wait a couple of days - no more :) , then, if you're busy, i could rewrite it, no problem)
Thank you!

2019-10-08 12:08 UTC, Andersson007 commented
@gundalow , please, close this via https://github.com/ansible/ansible/pull/63229

2019-10-08 12:11 UTC, gundalow commented
resolved_by_pr: 63229

2019-10-08 12:11 UTC, closed without merging