VMware: Add check mode support to module vmware_host_ntp
ansible/ansible pull request #46268
Opened 2018-09-28 14:47 UTC by ckotte

##### SUMMARY
The module doesn't execute in check mode.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
vmware_host_ntp

##### ANSIBLE VERSION
```
# ansible --version
ansible 2.6.3
  config file = /root/ansible-vmware/ansible.cfg
  configured module search path = [u'/root/ansible-vmware/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### ADDITIONAL INFORMATION
before:
```
TASK [esxi : Configure NTP] ******************************************************************************************************************************************************************************************************************
```
```
TASK [esxi : Configure NTP] ******************************************************************************************************************************************************************************************************************
changed: [esxi_host -> jump_server] => {"changed": true, "results": {"esxi_host": {"after_change_ntp_servers": ["time1", "time2", "time3"], "available_ntp_servers": [], "current_state": "present", "desired_state": "present", "ntp_servers_to_change": ["time1", "time2", "time3"]}}}
```

2018-09-28 16:23 UTC, Akasurde requested changes
Thanks for the contribution. Could you please write testcase for this change ?

2018-09-28 16:23 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_host_ntp.py
> +                    self.results[host.name]['after_change_ntp_servers'] = host_date_time_manager.dateTimeInfo.ntpConfig.server
I think we should set value for `after_change_ntp_servers` in results dictionary, otherwise in check mode we will receive blank and will raise KeyError for playbook.

2018-09-29 19:15 UTC, ckotte commented on lib/ansible/modules/cloud/vmware/vmware_host_ntp.py
> +                    self.results[host.name]['after_change_ntp_servers'] = host_date_time_manager.dateTimeInfo.ntpConfig.server
It just doesn't display ```after_change_ntp_servers``` in check mode. There are no errors raised. However, I just found out that the NTP servers will be added and an existing dummy entry isn't deleted. I will add ```after_change_ntp_servers``` and change the code to overwrite existing NTP servers.

2018-09-29 19:30 UTC, ckotte commented on lib/ansible/modules/cloud/vmware/vmware_host_ntp.py
> +                    self.results[host.name]['after_change_ntp_servers'] = host_date_time_manager.dateTimeInfo.ntpConfig.server
Ok, I added:
```
if self.module.check_mode:
    self.results[host.name]['after_change_ntp_servers'] = available_ntp_servers
```
Now the NTP server configuration after the change will be displayed.

2018-10-08 09:41 UTC, Akasurde approved these changes

2018-10-08 09:41 UTC, merged

2018-10-08 09:42 UTC, Akasurde commented
@ckotte Thanks for the contribution.