Add 'connected' option for virtual network adapters.
ansible/ansible pull request #46276
Opened 2018-09-28 15:57 UTC by mpk93

##### SUMMARY

Added the option to connect or disconnect virtual network adapters in vmware_guest when reconfiguring 
networks. Before it was not possible to connect/disconnect a virtual network adapter.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```paste below
ansible 2.8.0.dev0 (devel 812f439d11)
```

##### ADDITIONAL INFORMATION

```paste below

```

2018-09-28 16:18 UTC, Akasurde requested changes
Thanks for the contribution. Could you please add test case for this change ?

2018-09-28 16:18 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +    - ' - C(start_connected) (bool): Connects or disconnects the virtual network adapter.'
Could you please rephrase this as - 

```
- ' - C(connected) (bool): Connects or disconnects the virtual network adapter. version_added: 2.8'
```

2018-09-28 16:31 UTC, mpk93 commented
How would I add a test case for this? There don't seem to be any unit tests for vmware.

2018-09-28 16:36 UTC, Akasurde commented
@mpk93 Integration tests for VMware can be found [here](https://github.com/ansible/ansible/tree/devel/test/integration/targets/vmware_guest/tasks)

2018-09-28 17:02 UTC, mpk93 commented
@Akasurde Thanks. Could you please review my integration test, as I am not very familiar with it.

2018-09-29 02:01 UTC, Akasurde commented on test/integration/targets/vmware_guest/tasks/network_connected.yml
> +- name: disconnect network
Perform same operation again and check status of this task, this will test the idempotency of this feature.

2018-09-29 02:01 UTC, Akasurde commented on test/integration/targets/vmware_guest/tasks/network_connected.yml
> +  vmware_guest:
Same here.

2018-10-02 12:47 UTC, mpk93 commented
Not sure if you meant that by testing idempotency. As I am not sure if I can assume that the network is connected when I first test the VM.

2018-10-05 10:37 UTC, mpk93 commented
@Akasurde does this PR need more work?

2019-05-08 11:49 UTC, Akasurde requested changes
Could you please review new comments ? Thanks.

2019-05-08 11:49 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +    - ' - C(connected) (bool): Connects or disconnects the virtual network adapter. version_added: 2.8'
```suggestion
    - ' - C(connected) (bool): Connects or disconnects the virtual network adapter. version_added: 2.9'
```

2019-05-08 11:49 UTC, Akasurde commented on test/integration/targets/vmware_guest/tasks/network_connected.yml
> +# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
Add this test here as well https://github.com/ansible/ansible/blob/1462fd740b279ebe7dd791c8cac338a36ad413f6/test/integration/targets/vmware_guest/tasks/main.yml#L47

2019-05-23 16:08 UTC, goneri commented
hi @mpk93, your PR includes =~ 100 unrelated commits. Could you please base it or prepare a new PR.

2019-05-24 14:23 UTC, closed without merging