parse cloud formation templates
ansible/ansible pull request #46366
Opened 2018-10-01 19:02 UTC by sjmiller609

##### SUMMARY
Include a new lookup function for parsing cloud formation templates

I closed PR 44123 because I was not getting a response.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME
lookup cloudformation

##### ANSIBLE VERSION
2.6.1

2018-11-23 19:38 UTC, gundalow requested changes
Few minor comments, can you also please add a `changelog/fragment` file

2018-11-23 19:38 UTC, gundalow commented on lib/ansible/plugins/lookup/cloudformation_parse.py
> +from cfn_flip import load as cfn_load
Please add a try/expect around this import like in https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/lookup/consul_kv.py#L108-L123

2018-11-23 19:38 UTC, gundalow commented on lib/ansible/plugins/lookup/cloudformation_parse.py
> +DOCUMENTATION = """
Please add `requirements:` for `cfn_flip`

Example: https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/lookup/consul_kv.py#L20-L21

2018-11-23 19:38 UTC, gundalow commented on lib/ansible/plugins/lookup/cloudformation_parse.py
> +    version_added: "2.6"
2.8

2018-11-23 19:38 UTC, gundalow commented on lib/ansible/plugins/lookup/cloudformation_parse.py
> +    short_description: Parse cloudformation files
CloudFormation

Applies to multiple places

2018-12-14 17:37 UTC, sjmiller609 commented
@gundalow Thank you for your review. I have taken care of your comments.

2019-01-02 16:25 UTC, sjmiller609 commented
@gundalow This PR is ready for final review

2019-04-18 17:16 UTC, closed without merging