static systemd unit : fix idempotent issue
ansible/ansible pull request #46490
Opened 2018-10-04 16:02 UTC by fconil

##### SUMMARY
Fixes #46247

Fixes both service and systemd modules

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

service
systemd

##### ANSIBLE VERSION

```paste below
2.8
```

##### ADDITIONAL INFORMATION

```paste below

```

2018-10-09 21:01 UTC, maxamillion approved these changes

2018-10-09 21:01 UTC, maxamillion commented
shipit

2018-10-14 16:21 UTC, pilou- commented
shipit

2018-10-16 17:13 UTC, maxamillion commented
I think @bcoca had some concerns with this patch but I can't remember what they were.

2018-10-16 18:27 UTC, pilou- commented
Here it is. bcoca ca wrote on #ansible-devel:
> i thought we already had this discussion, its doing a negative match, it should specifically look for a return and not assume that if we failed to enable is cause service is not possible to enable

2018-11-05 17:00 UTC, gundalow requested changes
Needs update based on Pilou's /bcoca's feedback above

2019-02-07 04:35 UTC, maxamillion commented
waiting_on_contributor

2019-04-17 03:18 UTC, pilou- commented on lib/ansible/modules/system/systemd.py
> +                if not enabled:
Should not `action` value be tested here ?

2019-04-17 03:23 UTC, pilou- commented
> Here it is. bcoca ca wrote on #ansible-devel:
>> i thought we already had this discussion, its doing a negative match, it should specifically look for a return and not assume that if we failed to enable is cause service is not possible to enable

@bcoca: which module is concerned (`service` or `systemd`) ? which line ?

2022-01-26 19:23 UTC, jborean93 commented
Due to the age of the PR and the concerns/feedback raised on the PR I'm going to close this.

2022-01-26 19:23 UTC, closed without merging