slack: Add validate_certs option in plugin
ansible/ansible pull request #46567
Opened 2018-10-06 08:47 UTC by Akasurde

##### SUMMARY
This fix adds a configurable parameter for slack plugin.

Fixes: #45682

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
lib/ansible/plugins/callback/slack.py

##### ANSIBLE VERSION

```paste below
2.8-devel
```

2018-10-09 13:56 UTC, sivel commented on lib/ansible/plugins/callback/slack.py
> +          - name: SLACK_VALIDATE_CERT
This env name should probably be plural, to match the option and ini key.

2018-10-09 13:57 UTC, sivel commented on lib/ansible/plugins/callback/slack.py
> +          - name: SLACK_VALIDATE_CERT
`SLACK_VALIDATE_CERTS`

2018-10-15 18:34 UTC, Akasurde commented
@sivel Could you please take another look on new changes ? Thanks.

2018-10-19 19:46 UTC, sivel approved these changes

2018-10-19 19:47 UTC, sivel requested changes

2018-10-19 19:47 UTC, sivel commented on lib/ansible/plugins/callback/slack.py
> +        description: validate the SSL certificate of the Slack server. (For HTTPS URLs)
Please add a `version_added` to this as well.

2018-11-15 04:12 UTC, Akasurde commented
@sivel Could you please take another look on new changes ? Thanks.

2018-11-15 15:15 UTC, sivel approved these changes

2018-11-15 15:15 UTC, merged

2018-11-15 15:15 UTC, sivel commented
@Akasurde sorry for the delay.  I don't see when people make commits, only comments.

This is merged now.

2018-11-15 16:02 UTC, Akasurde commented
@sivel no problem. Thanks for review and merge.