adding explanation of replace_all_instances
ansible/ansible pull request #46694
Opened 2018-10-09 14:06 UTC by biohazd

How does "replace_all_instances" work? does it increase the number of instances by 1 in the Load balancer and it scales in a server and waits for it to complete its health check, OR   does it terminate a node a that causes an autoscale event to happen and then adds a new server?
+label: docsite_pr

##### SUMMARY

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### COMPONENT NAME

##### ANSIBLE VERSION

```paste below

```

##### ADDITIONAL INFORMATION

```paste below

```

2018-10-09 14:58 UTC, gundalow commented
@biohazd Hi, Nice use to Edit on GitHub to ask the question :)

The right people have been pinged on this so lets see if they can provide some more info.

Welcome to the Ansible Community

2018-10-09 14:59 UTC, webknjaz commented
@biohazd it seems to me that you are new to GitHub and have created this PR accidentally. That's why I'm closing it.

But no worries! If you wanted to create an actual bug report, please create an issue rather than a PR.

Assuming that you wanted to create actual contribution, I think that you may want to learn and read through the following articles I've gathered for you:

* https://opensource.guide/how-to-contribute/
* https://docs.ansible.com/ansible/devel/community/

Have a nice day!

2018-10-09 19:38 UTC, biohazd commented
hi, yeah sorry, i just wanted to ask the question and will then create a pull request with the new info in.

2018-10-10 07:11 UTC, willthames commented
The main logic is at https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/ec2_asg.py#L1335-L1360

From my reading, it increases the ASG size by `replace_batch_size`, waits for the new instances to be up and running. After that, it terminates a batch of old instances, waits for the replacements, and repeats, until all old instances are replaced. Once that's done the ASG size is reduced back to the expected size.

2018-10-10 07:34 UTC, biohazd commented
thanks, i will add that info to the pull request

2018-10-10 07:39 UTC, biohazd commented
i have updated the pull request - is it ok now ?

2018-10-10 07:58 UTC, willthames requested changes
Could you reduce the line length of these changes to somewhere below 100 (I have to scroll to read the PR!) - again, I realise it wasn't great before but as there are other updates to make it would be better to make this more readable.

2018-10-10 07:58 UTC, willthames commented on lib/ansible/modules/cloud/amazon/ec2_asg.py
> +        It increases the ASG size by replace_batch_size, waits for the new instances to be up and running.
Probably worth using `C(replace_batch_size)` here

2018-10-10 07:58 UTC, willthames commented on lib/ansible/modules/cloud/amazon/ec2_asg.py
> +      - In a rolling fashion, replace all instances with an old launch configuration with one from the current launch configuration.
"replace all instances with an old launch configuration" is confusing (it was confusing before this change)

Might be better as "replace all instances from an old launch configuration"

2018-10-10 08:07 UTC, biohazd commented
howz it look now?  Sorry if this is a mess, im still learning how to use github :)

2018-10-10 09:53 UTC, willthames commented
That's great, thanks!

The automated tests are still failing with trailing whitespace on lines 85-87. Once those are fixed up and the tests pass, this is good to merge.

2018-10-10 09:58 UTC, willthames approved these changes

2018-10-10 09:59 UTC, merged

2018-10-10 09:59 UTC, willthames commented
Thanks very much for this improvement @biohazd