Added secure boot enable/disable to vmware_guest_boot_manager.
ansible/ansible pull request #46717
Opened 2018-10-09 21:09 UTC by healem

##### SUMMARY

Modifying the boot order has no effect on VMs with secure_boot enabled.  This pull request adds the state of secure_boot to facts and the ability to enable/disable secure_boot for the VM.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

vmware_guest_boot_manager module

##### ANSIBLE VERSION

```paste below
ansible 2.8.0.dev0 (vsphereCopy 1cfa4c1228) last updated 2018/10/09 17:46:32 (GMT +000)
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /ansible/lib/ansible
  executable location = /ansible/bin/ansible
  python version = 2.7.15 (default, Sep 12 2018, 02:38:23) [GCC 6.4.0]
```

##### ADDITIONAL INFORMATION

```paste below

```

2018-10-10 05:07 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_guest_boot_manager.py
> +     default: False
add
```
version_added: 2.8
```

2018-10-11 10:11 UTC, Akasurde approved these changes
LGTM

2018-10-11 10:12 UTC, Akasurde commented
@dericcrago @pdellaert @tchernomax @Im0 @ckotte Could you please review this ?

2018-10-11 22:15 UTC, tchernomax commented
@healem In vmware is it possible to have secure boot enable and boot firmware to "bios" ?
If that's the case, ok for me.
But if it's not, you should document that and verify the user don't try to set "boot_firmware" to bios and "secure_boot_enabled" to true.
If you can't test and you don't know… well, ok for me, users should be grown up enough to know what they are doing.

2018-10-11 23:32 UTC, healem commented
@tchernomax, good point.  I don't think you can enable secure boot with bios firmware.  I'll try it out on vSphere 6.7 rig and add some verification if needed.

2018-10-12 14:07 UTC, healem commented
@tchernomax, I tested this on vSphere 6.7.  VMware's behavior is not ideal - they allow you to set boot_firmware = 'bios' and enable EFI secure boot.  There is no failure until you attempt to boot the VM.  So I added some guardrails for the user to prevent this situation.

2018-10-12 21:01 UTC, tchernomax requested changes

2018-10-12 21:01 UTC, tchernomax commented on lib/ansible/modules/cloud/vmware/vmware_guest_boot_manager.py
> +        "previous_secure_boot_enabled": true,
if secure_boot can't be enabled with boot_firmware = bios you should set the examples accordingly.

2018-10-12 21:01 UTC, tchernomax commented on lib/ansible/modules/cloud/vmware/vmware_guest_boot_manager.py
> +                self.module.fail_json(msg="EFI secure boot cannot be enabled when boot_firmware = bios, but both are specified")
I think you should do this test right before `pyv = VmBootManager(module)` (at line 350).
This way you can call fail_json as soon as possible.

2018-10-12 21:01 UTC, tchernomax commented on lib/ansible/modules/cloud/vmware/vmware_guest_boot_manager.py
> +                self.module.fail_json(msg="EFI secure boot cannot be enabled when boot_firmware = bios, but both are specified")
also don't use `if self.params.get('secure_boot_enabled') is True …`,  `self.params.get('secure_boot_enabled')` is already a boolean so `if self.params.get('secure_boot_enabled') …` is sufficient.

2018-10-12 21:01 UTC, tchernomax commented on lib/ansible/modules/cloud/vmware/vmware_guest_boot_manager.py
> +            if self.params.get('secure_boot_enabled') is True and self.params.get('boot_firmware') is None:
same here (remove the `is True`)

2018-10-12 21:01 UTC, tchernomax commented on lib/ansible/modules/cloud/vmware/vmware_guest_boot_manager.py
> +                if self.vm.config.firmware == 'bios':
also, merge the two level of `if`.
```
if self.params.get('secure_boot_enabled') and
   self.params.get('boot_firmware') is None and
   self.vm.config.firmware == 'bios':
  …
```

2018-10-12 21:29 UTC, healem commented on lib/ansible/modules/cloud/vmware/vmware_guest_boot_manager.py
> +        "previous_secure_boot_enabled": true,
Will do - thanks for catching it.

2018-10-12 21:37 UTC, healem commented on lib/ansible/modules/cloud/vmware/vmware_guest_boot_manager.py
> +                self.module.fail_json(msg="EFI secure boot cannot be enabled when boot_firmware = bios, but both are specified")
I'm not sure this is a good idea.  I can move lines 258-9 to just before line 350, but I can't move 263-5 to there as we haven't gotten the previous settings yet (we get them at line 195).  I think that makes the maintenance harder as the code is spread out.  Given that all the lines between 195 and 265 are also parameter handling and validation, I think the difference in time to failure is negligible.

I'll remove the "is True"

2018-10-12 21:37 UTC, healem commented on lib/ansible/modules/cloud/vmware/vmware_guest_boot_manager.py
> +                if self.vm.config.firmware == 'bios':
Will do

2018-10-13 08:47 UTC, tchernomax approved these changes
LGTM

2018-10-13 08:47 UTC, tchernomax commented on lib/ansible/modules/cloud/vmware/vmware_guest_boot_manager.py
> +                self.module.fail_json(msg="EFI secure boot cannot be enabled when boot_firmware = bios, but both are specified")
ok, well argued.

2018-10-15 02:23 UTC, pdellaert approved these changes
LGTM, great contribution :)

2018-10-15 09:32 UTC, merged

2018-10-15 09:32 UTC, Akasurde commented
@healem Thanks for the contribution. @tchernomax @pdellaert Thanks for the valuable reviews.