Fix Issue #46410 Onyx show facts module does not work for onyx versio…
ansible/ansible pull request #47027
Opened 2018-10-14 13:23 UTC by anasbadaha

…n 3.6.6000 and higher

Signed-off-by: Anas Badaha <anasb@mellanox.com>

##### SUMMARY

Fixes #46410 Onyx show facts module does not work for onyx version 3.6.6000 and higher

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

onyx_facts.py
##### ANSIBLE VERSION

```
ansible 2.6.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] 

```

##### ADDITIONAL INFORMATION

```paste below

```

2018-10-14 17:01 UTC, samerd requested changes

2018-10-14 17:01 UTC, samerd commented on lib/ansible/modules/network/onyx/onyx_facts.py
> +                if_name = if_dict["Interface Name"] = if_data["header"]
you have a duplicate code here.
extracting values from json dict should be done once.
Add a function def _extractIfData(interface_data)
that should get all interface data except the interface name

2018-11-01 08:48 UTC, ganeshrn commented
@anasbadaha The PR contains merge commit. Please rebase the PR, refer https://docs.ansible.com/ansible/devel/dev_guide/developing_rebasing.html for steps to rebase

2018-11-13 09:02 UTC, anasbadaha commented
Hi ganeshrn,
I pulled megre commits please merge this PR.

Anas Badaha

2018-11-13 13:35 UTC, ganeshrn commented
bot_status

2018-11-13 13:41 UTC, ganeshrn commented
The PR still has merge commit and changes requested by @samerd
Can you fix the issues with PR

2018-12-02 09:52 UTC, anasbadaha commented
Will push it in new pull request!

2018-12-02 09:52 UTC, closed without merging