Avoid undefined names by initializing variables
ansible/ansible pull request #47304
Opened 2018-10-18 17:51 UTC by cclauss

##### SUMMARY

Linters properly complain about _undefined names_ when code access variables before they have defined.  These changes include two approaches to help linters (and humans) to understand and relax about these undefined names:
* The __key__ fixes add a __key = None__ statement at the top of the function.
* The __retry_count__ fix adds a __global retry_count__ statement at the top of the function which allows tests to pass on both PyLint and flake8 without any linter directives.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

* module_utils
* modules/network

##### ANSIBLE VERSION

* https://github.com/ansible/ansible

##### ADDITIONAL INFORMATION

[flake8](http://flake8.pycqa.org) testing of https://github.com/ansible/ansible on Python 3.7.0

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./lib/ansible/module_utils/api.py:114:21: F823 local variable 'retry_count' (defined in enclosing scope on line 107) referenced before assignment
                    retry_count += 1  # pylint: disable=undefined-variable
                    ^
./lib/ansible/modules/network/dellos9/dellos9_facts.py:379:24: F821 undefined name 'key'
                parsed[key] += '\n%s' % line
                       ^
./lib/ansible/modules/network/dellos9/dellos9_facts.py:399:24: F821 undefined name 'key'
                parsed[key] += '\n%s' % line
                       ^
./lib/ansible/modules/network/dellos9/dellos9_facts.py:403:24: F821 undefined name 'key'
                parsed[key] += '\n%s' % line
                       ^
./lib/ansible/modules/network/dellos9/dellos9_facts.py:418:24: F821 undefined name 'key'
                parsed[key] += '\n%s' % line
                       ^
./lib/ansible/modules/network/ironware/ironware_facts.py:274:24: F821 undefined name 'key'
                parsed[key] += '\n%s' % line
                       ^
./lib/ansible/modules/network/ironware/ironware_facts.py:514:24: F821 undefined name 'key'
                parsed[key] += '\n%s' % line
                       ^
6    F821 undefined name 'key'
1     F823 local variable 'retry_count' (defined in enclosing scope on line 107) referenced before assignment
6
```

2019-01-25 19:03 UTC, cclauss commented
@ryanpetrello You advise on issues that can be raised via:
[flake8](http://flake8.pycqa.org) testing of https://github.com/ansible/ansible on Python 3.7.1



$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./lib/ansible/modules/files/archive.py:404:92: F821 undefined name 'e'
                module.fail_json(dest=dest, msg='Error deleting some source files: ' + str(e), files=errors)
                                                                                           ^
./lib/ansible/modules/network/dellos9/dellos9_facts.py:379:24: F821 undefined name 'key'
                parsed[key] += '\n%s' % line
                       ^
./lib/ansible/modules/network/dellos9/dellos9_facts.py:399:24: F821 undefined name 'key'
                parsed[key] += '\n%s' % line
                       ^
./lib/ansible/modules/network/dellos9/dellos9_facts.py:403:24: F821 undefined name 'key'
                parsed[key] += '\n%s' % line
                       ^
./lib/ansible/modules/network/dellos9/dellos9_facts.py:418:24: F821 undefined name 'key'
                parsed[key] += '\n%s' % line
                       ^
./lib/ansible/modules/network/ironware/ironware_facts.py:274:24: F821 undefined name 'key'
                parsed[key] += '\n%s' % line
                       ^
./lib/ansible/modules/network/ironware/ironware_facts.py:514:24: F821 undefined name 'key'
                parsed[key] += '\n%s' % line
                       ^
./lib/ansible/modules/cloud/misc/rhevm.py:593:24: F821 undefined name 'e'
            setMsg(str(e))
                       ^
./lib/ansible/module_utils/api.py:114:21: F823 local variable 'retry_count' (defined in enclosing scope on line 107) referenced before assignment
                    retry_count += 1  # pylint: disable=undefined-variable
                    ^
./lib/ansible/module_utils/six/__init__.py:54:20: F821 undefined name 'basestring'
    string_types = basestring,
                   ^
./lib/ansible/module_utils/six/__init__.py:55:27: F821 undefined name 'long'
    integer_types = (int, long)
                          ^
./lib/ansible/module_utils/six/__init__.py:57:17: F821 undefined name 'unicode'
    text_type = unicode
                ^
./lib/ansible/module_utils/six/__init__.py:660:16: F821 undefined name 'unicode'
        return unicode(s.replace(r'\\', r'\\\\'), "unicode_escape")
               ^
./lib/ansible/module_utils/six/__init__.py:756:37: F821 undefined name 'basestring'
            if not isinstance(data, basestring):
                                    ^
./lib/ansible/module_utils/six/__init__.py:759:32: F821 undefined name 'file'
            if (isinstance(fp, file) and
                               ^
./lib/ansible/module_utils/six/__init__.py:760:38: F821 undefined name 'unicode'
                    isinstance(data, unicode) and
                                     ^
./lib/ansible/module_utils/six/__init__.py:770:32: F821 undefined name 'unicode'
            if isinstance(sep, unicode):
                               ^
./lib/ansible/module_utils/six/__init__.py:776:32: F821 undefined name 'unicode'
            if isinstance(end, unicode):
                               ^
./lib/ansible/module_utils/six/__init__.py:784:36: F821 undefined name 'unicode'
                if isinstance(arg, unicode):
                                   ^
./lib/ansible/module_utils/six/__init__.py:788:23: F821 undefined name 'unicode'
            newline = unicode("\n")
                      ^
./lib/ansible/module_utils/six/__init__.py:789:21: F821 undefined name 'unicode'
            space = unicode(" ")
                    ^
20    F821 undefined name 'basestring'
1     F823 local variable 'retry_count' (defined in enclosing scope on line 107) referenced before assignment
21
```
__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. These 5 are different from most other flake8 issues which are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

2019-01-25 19:16 UTC, sivel commented
None of the items in `six/__init__.py` should be changed.  `six` is a vendored library used for compatibility between python2 and python3 so flake8 is likely flagging false positives in regards to how they are actually used.  All of those issues it picked up are going to be behind feature or version guards.

2019-01-25 19:22 UTC, sivel requested changes

2019-01-25 19:22 UTC, sivel commented on lib/ansible/module_utils/api.py
> +            global retry_count
This is an incorrect change.  `retry_count` is not a global.  Technically it is a nonlocal.  `nonlocal` is not available in py2, so this closure just needs rewritten

2019-01-25 19:24 UTC, sivel commented on lib/ansible/module_utils/api.py
> +            global retry_count
I should also note that this `retry` decorator isn't in use anywhere that I could tell.

2019-04-17 08:10 UTC, cclauss commented
Closing as __global__ works in Python 2 and 3 but __nonlocal__ only works in Python 3.

2019-04-17 08:10 UTC, closed without merging