WinRM/PSRP: Ensure shell returns UTF-8 output
ansible/ansible pull request #47404
Opened 2018-10-22 02:50 UTC by dagwieers

##### SUMMARY
This PR makes UTF-8 output work in PSRP shells.

This relates to #46998

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
WinRM/PSRP

##### ANSIBLE VERSION
v2.8

2018-10-23 20:15 UTC, jborean93 commented
Local tests seem to be fine, now we have a psrp only testing location are you able to add a win_shell or win_command test with unicode characters to https://github.com/ansible/ansible/blob/devel/test/integration/targets/connection_psrp/tests.yml. This will test that we don't loose the unicode chars end to end.

2018-10-23 20:50 UTC, jborean93 commented on test/integration/targets/connection_psrp/tests.yml
> +  connection: psrp
No need for this here

2018-10-23 20:50 UTC, jborean93 commented on changelogs/fragments/psrp-utf8-stdio.yaml
> +
Remove this newline

2018-10-23 21:39 UTC, nitzmahone approved these changes

2018-10-23 21:53 UTC, jborean93 requested changes

2018-10-23 21:53 UTC, jborean93 commented on test/integration/targets/connection_psrp/tests.yml
> +  raw: |
Not needed, this is tested above

2018-10-23 21:53 UTC, jborean93 commented on test/integration/targets/connection_psrp/tests.yml
> +  win_command: |
do `win_command: "powershell.exe -ExecutionPolicy ByPass -Command \"Write-Host '\U0001F4A9'\""`. Due to the PyYAML issue you can't put unicode characters that are a surrogate pair in YAML files.

2018-10-23 21:53 UTC, jborean93 commented on test/integration/targets/connection_psrp/tests.yml
> +    - command_unicode_output.stdout == '💩'
`"command_unicode_output.stdout == '\U0001F4A9\n'". Need to use the `\U` form and add `\n` to the end.

2018-10-23 21:53 UTC, jborean93 commented on test/integration/targets/connection_psrp/tests.yml
> +    - shell_unicode_output.stdout == '💩'
`"shell_unicode_output.stdout == '\U0001F4A9\n'". Need to use the `\U` form and add `\n` to the end.

2018-10-23 21:53 UTC, jborean93 commented on test/integration/targets/connection_psrp/tests.yml
> +  win_shell: |
do `win_shell: "Write-Host '\U0001F4A9'"`

2018-10-23 21:54 UTC, jborean93 commented
@dagwieers you also need to indent the new tests to it lines up with the other tasks.

2018-10-23 23:25 UTC, jborean93 approved these changes

2018-10-23 23:27 UTC, jborean93 commented on test/integration/targets/connection_psrp/tests.yml
> +      - command_unicode_output.stdout == "\U0001F4A9\n"
Hopefully this is the last one, you need to quote this entire line for the `\U` to take effect, e.g. `"command_unicode_output.stdout == '\U0001F4A9\n'"`. Same as the win_shell assertion below.

2018-10-24 00:40 UTC, merged

2018-10-24 00:51 UTC, jborean93 commented
@dagwieers I've cherry-picked this commit to https://github.com/ansible/ansible/pull/47530 so they will be merged together.

2018-10-24 08:41 UTC, dagwieers commented
@jborean93 Thanks !