WIP: Implement connection plugin for podman
ansible/ansible pull request #47519
Opened 2018-10-23 16:06 UTC by TomasTomecek

##### SUMMARY
This is a new connection plugin for [podman](https://github.com/containers/libpod) container manager.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
connection_podman

##### ADDITIONAL INFORMATION
Please see test_connection.inventory file for instructions how to test this.

The reason why this is WIP is that when I change `ansible_remote_user` to `1000`, ansible figures out the out_path to `~1000`. I'm actually not sure where the problem is.
```
<podman-container> PUT /home/tt/.ansible/tmp/ansible-local-6366fTcbAW/tmpuYEzv5 TO ~1000/.ansible/tmp/ansible-tmp-1540310223.97-201232050279128/AnsiballZ_file.py
```

I'm also not interested in changing the posix.sh file, this is just current iteration how I tried to debug and fix stuff.

CC @rhatdan @baude

2018-10-23 16:15 UTC, sivel commented
> The reason why this is WIP is that when I change `ansible_remote_user` to `1000`, ansible figures out the out_path to `~1000`. I'm actually not sure where the problem is.

I believe this is due to how we expand remote paths:

https://github.com/ansible/ansible/blob/95e77ac853f902f4b19c70be41e5e3cb905bd193/lib/ansible/plugins/action/__init__.py#L581-L591

We effectively run `echo ~1000` where `1000` would be a username that is present on the target system.

If `1000` was a username on the remote system, and assuming the home dir was set to `/home/1000` that should return `/home/1000` instead.

Based on what you have found, it appears as though there is no user with a username of `1000` on the remote host.  As such you end up with a literal `~1000`

2018-10-23 16:22 UTC, sivel commented
I'm guessing by the fact that the user is `1000` that it is a UID and not a username.  Which would be the problem.

2018-10-23 16:22 UTC, samdoran commented
@TomasTomecek Thanks for submitting this. I'm working on a suite of Podman modules for TripleO, and this connection plugin was on my list.

I wrote [`podman_image_facts`](https://github.com/openstack/tripleo-ansible/tree/master/library) and am working on [`podman_image`](https://review.openstack.org/#/c/611698/). Let me know if this is of interest to you since we may upstream these in Ansible once they are complete.

2018-10-24 10:58 UTC, TomasTomecek commented
Matt, thank you, that's so helpful!

Unfortunately that doesn't work well for containers. The thing is that it's a fairly normal use case to run a command in a container under a user which is not defined in `/etc/passwd`:
```
$ podman run -d --name hi busybox sleep 99999
bf639cb1daee8888a319021a1f0d085ddf5611bcdd90f89cd6da6972d4093d85
$ podman exec hi id                                                                                                                                              
uid=0(root) gid=0(root) groups=65534(nogroup),0(root),65534(nogroup)
$ podman exec -u 1234 hi id                                                                                                                                      
uid=1234 gid=0(root) groups=65534(nogroup),0(root),65534(nogroup)
```

I'm not sure if we can change that logic or whether I should handle such case inside the connection plugin.


Sam, thanks for update! I'll definitely take a look. Maybe to give you some context, I wrote buildah connection plugin back then for ansible-container. Doing podman now pretty much for the same reason.

2018-10-24 11:29 UTC, TomasTomecek commented
Just pushed the initial support without remote_user. Keeping en eye on CI.

2018-10-24 13:57 UTC, TomasTomecek commented
All is green and nice now! Please let me know what I should do to get this merged.

2018-10-24 14:20 UTC, sivel commented
> I'm not sure if we can change that logic or whether I should handle such case inside the connection plugin.

The logic for expanding the remote path has gone through many iterations to cover as many edge cases as possible.  What we have currently we believe is the most flexible.

However, you might add a note with this connection plugin that `ansible_remote_tmp` (host or group var) should be set for hosts using this connection plugin to use a path not dependent on the users home directory such as `/tmp` when the user you are running the command as does not exist on the system.

I don't know much about podman, but fwiw, we already support various container types as connection plugins, and we haven't run into your scenario before.

As far as handling it in the connection, I don't think that can be easily influenced from the connection plugin, since the command building is handled in the action plugin.  I don't think we would accept code that tried to parse those commands and modify them from the connection.

2018-10-25 17:58 UTC, TomasTomecek commented
@sivel, you're a genius!

Setting `ansible_remote_user` indeed did the trick. To be honest, I tried that myself and I actually expected that this line does it:

https://github.com/ansible/ansible/blob/devel/test/integration/targets/connection_posix/test.sh#L17

Unfortunately it didn't.

2018-10-25 20:46 UTC, rhatdan commented
@mheon @baude @mrunalp FYI

2018-10-26 10:52 UTC, TomasTomecek commented
@sivel @samdoran All is green, shall we merge?

I'll write down a quick blog post once this is merged. Can I expect this to be in 2.8?

2018-10-29 20:53 UTC, samdoran requested changes
I wanted to do some testing with it first. Seems to work very well. Thank you for writing this (and for including tests). Just a few minor changes to the documentation.

2018-10-29 20:53 UTC, samdoran commented on lib/ansible/plugins/connection/podman.py
> +            - User specified via name or ID which is used to execute commands inside the container. If you
```suggestion
            - User specified via name or UID which is used to execute commands inside the container. If you
```

2018-10-29 20:53 UTC, samdoran commented on lib/ansible/plugins/connection/podman.py
> +              specify the user via user ID please make sure to also set ANSIBLE_REMOTE_USER to e.g. /tmp so
```suggestion
              specify the user via UID, you must set C(ANSIBLE_REMOTE_TMP) to a path that exits
```

2018-10-29 20:53 UTC, samdoran commented on lib/ansible/plugins/connection/podman.py
> +              that Ansible is able to put the temporary data into a well-known, writable directory.
```suggestion
               inside the container and is writable by Ansible.
```

2018-10-29 20:53 UTC, samdoran commented on lib/ansible/plugins/connection/podman.py
> +    This is a connection plugin for podman: it uses podman binary to interact with the containers
```suggestion
    This is a connection plugin for podman. It uses podman binary to interact with the containers
```

2018-10-30 07:23 UTC, TomasTomecek commented
Thanks Sam, very good suggestions. I squashed them into a single commit.

2018-11-01 14:14 UTC, samdoran approved these changes

2018-11-01 14:14 UTC, merged

2018-11-01 19:43 UTC, TomasTomecek commented
So stoked to have this!! Gonna write that blog post so that people know how to use this.

Sam and Matt, thanks a lot for your help!