RabbitMQ Bindings - Finish implementation of client side TLS settings
ansible/ansible pull request #47714
Opened 2018-10-27 18:25 UTC by hyperized

##### SUMMARY
Also implement TLS client settings for POST and DELETE requests in this module.

Currently the module will not honor client TLS settings with these two.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
messaging/rabbitmq_binding

##### ANSIBLE VERSION
```paste below
2.8-devel
```

##### ADDITIONAL INFORMATION
Since the module has been a full rewrite in the past, added an overdue copyright as well.

2018-10-30 08:43 UTC, hyperized commented
@Akasurde I'd appreciate your review as well, but I'm going to take some time in the next few days to add full integration tests to this module since there's none yet.

2018-11-02 09:10 UTC, Akasurde commented on lib/ansible/modules/messaging/rabbitmq/rabbitmq_binding.py
> +# Copyright (c) 2015, Manuel Sousa <manuel.sousa@gmail.com>
```suggestion
# Copyright: (c) 2015, Manuel Sousa <manuel.sousa@gmail.com>
```

2018-11-02 09:10 UTC, Akasurde commented on lib/ansible/modules/messaging/rabbitmq/rabbitmq_binding.py
> +# Copyright (c) 2018, Gerben Geijteman <gerben@hyperized.net>
```suggestion
# Copyright: (c) 2018, Gerben Geijteman <gerben@hyperized.net>
```

2018-11-02 09:11 UTC, Akasurde commented
@mattclay Could you please review this? Thanks.

2018-11-02 09:15 UTC, hyperized commented
It's work in progress at this point, I'm still to finish the bindings integration test that utilises TLS.

2018-11-05 18:34 UTC, mattclay commented
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/91510/40/tests

2018-11-26 19:52 UTC, mattclay requested changes

2018-11-26 19:52 UTC, mattclay commented on test/integration/targets/rabbitmq_lookup/tasks/main.yml
> +    - ansible_distribution_release != 'trusty'
Keep the line ending here.

2018-11-28 00:29 UTC, mattclay commented
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/95070/40/tests

2018-12-12 10:35 UTC, gundalow commented
@hyperized Could you please rebase this https://docs.ansible.com/ansible/devel/dev_guide/developing_rebasing.html

2018-12-14 14:24 UTC, closed without merging

2018-12-15 06:30 UTC, Akasurde commented
@hyperized What happened ?

2018-12-15 10:08 UTC, hyperized commented
@Akasurde got real tired of the tests failing and I didn't feel like I got an answer in #ansible-devel for this. However I realized this PR is doomed anyway because the tests are lacking. I'm going to spend some time in the upcoming holidays to finish the TLS testing ability for the whole of the RabbitMQ spectrum and then resubmit this PR at a later stage.