added openstack module for retrieving stack facts
ansible/ansible pull request #47748
Opened 2018-10-29 14:48 UTC by xinau

##### SUMMARY

Added a new module for retrieving facts for a given openstack stack by name. 
I created this module, due to the fact that I want to create a stack in one playbook and use these stack facts in another playbook. At a point later in time. I didn't extend the existing `os_stack` module cause it seems to be a convention for the openstack modules (`os_image_facts`, `os_server_facts`...)

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

##### ANSIBLE VERSION

```paste below
devel
```

2018-11-01 11:08 UTC, mnaser commented
Seems straight forward

2018-11-01 11:08 UTC, mnaser commented
shipit

2018-11-05 11:15 UTC, gtema approved these changes
LGTM

2019-03-06 16:08 UTC, brtknr commented
For the record, we build a similar module to solve this problem a while back (https://github.com/stackhpc/ansible-role-os-container-infra/blob/master/library/os_stack_facts.py) but I like this approach as it doesn't depend on the python-heatclient!

2019-03-06 16:18 UTC, brtkwr approved these changes

2019-03-10 12:59 UTC, brtknr commented on lib/ansible/modules/cloud/openstack/os_stack_facts.py
> +  os_stack:
Shouldn't this be os_stack_facts:?

2019-04-04 17:01 UTC, gtema requested changes
@xinau, if you would fix this small thing the PR will be accepted

2019-04-04 17:01 UTC, gtema commented on lib/ansible/modules/cloud/openstack/os_stack_facts.py
> +  os_stack:
should be

2019-04-04 18:04 UTC, xinau commented
@gtema sry for the late reply, should be fixed now.

2019-04-05 11:05 UTC, gtema requested changes
a few more issues in comments

2019-04-05 11:05 UTC, gtema commented on lib/ansible/modules/cloud/openstack/os_stack_facts.py
> +    - Retrieve facts about a image image from OpenStack.
image image -> stack

2019-04-05 11:05 UTC, gtema commented on lib/ansible/modules/cloud/openstack/os_stack_facts.py
> +        - Name of the stack that should be created, name could be char and digit, no space
stack will not be created

2019-04-05 12:01 UTC, xinau commented
Thanks, good catch. Fixed these mistakes.

2019-04-05 12:48 UTC, gtema approved these changes

2019-04-05 12:48 UTC, gtema commented
shipit

2019-06-18 10:30 UTC, gtema commented
recheck

2019-06-18 13:53 UTC, gtema commented
shipit

2019-06-20 16:36 UTC, cloudnull approved these changes
shipit

2020-01-20 13:52 UTC, sshnaidm commented
Thanks for submitting patch for Openstack Ansible modules!
We moved Openstack Ansible modules to Openstack repositories.
Next patches should be submitted not with Ansible Github but with
Openstack Gerrit: https://review.opendev.org/#/q/project:openstack/ansible-collections-openstack
Please submit your code there from now.
Thanks for your contribution and sorry for inconvienience.

2020-08-19 10:32 UTC, Akasurde commented
@xinau Thanks for the contribution. Closing as per above.

2020-08-19 10:32 UTC, closed without merging