Fix #47864 : Add the ability to download a specific version of an S3 object
ansible/ansible pull request #47867
Opened 2018-10-31 14:35 UTC by gaelL

##### SUMMARY

Fix #47864 : Add the ability to download a specific version of an S3 object

As descibed in #47864 aws_s3 ignore the version specified while downloading the object.

Example of ansible config to test the code :

```
- name: Get a specific version of an object.
  aws_s3:
    bucket: mybucket
    object: /my/desired/key.txt
    version: 48c9ee5131af7a716edc22df9772aa6f
    dest: /usr/local/myfile.txt
    mode: get
```

`aws_s3.py` use boto `s3.download_file(bucket, obj, dest)` command to download the s3 object.
However it does not take into account the version of the object.

Looking on boto doc https://github.com/boto/boto3/issues/1120, it is possible to specify object VersionId as ExtraArgs of s3.download_file.

```
s3.download_file(bucket, obj, dest, ExtraArgs={'VersionId': version})
```

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME

aws_s3

2018-11-19 09:40 UTC, Akasurde requested changes
LGTM

2018-11-19 09:40 UTC, Akasurde approved these changes

2018-11-29 11:00 UTC, webknjaz commented on lib/ansible/modules/cloud/amazon/aws_s3.py
> +                s3.download_file(bucket, obj, dest)
It'd be cleaner to have only kwargs conditional:
```suggestion
            optional_kwargs = {'ExtraArgs': {'VersionId': version}} if version else {}
            s3.download_file(bucket, obj, dest, **optional_kwargs)
```

2018-11-29 11:03 UTC, webknjaz commented on lib/ansible/modules/cloud/amazon/aws_s3.py
>      for x in range(0, retries + 1):
Even better:
```suggestion
    optional_kwargs = {'ExtraArgs': {'VersionId': version}} if version else {}
    for x in range(0, retries + 1):
```

2018-11-29 11:04 UTC, webknjaz commented on lib/ansible/modules/cloud/amazon/aws_s3.py
> +                s3.download_file(bucket, obj, dest)
Oh.. `version` is immutable within the loop. You can move kwargs outside: https://github.com/ansible/ansible/pull/47867/files#r237441147
```suggestion
            s3.download_file(bucket, obj, dest, **optional_kwargs)
```

2018-11-29 13:20 UTC, gaelL commented
Changes have been applied + a rebase on the last devel branch

2018-11-29 13:47 UTC, gaelL commented
Changes have been applied + a rebase on the last devel branch

2018-11-29 15:20 UTC, webknjaz approved these changes

2018-11-30 03:29 UTC, merged

2018-11-30 03:29 UTC, Akasurde commented
@gaelL Thanks for the contribution. @webknjaz Thanks for the review.