WIP VMware: New module vmware_host_ad_auth
ansible/ansible pull request #47901
Opened 2018-10-31 21:56 UTC by ckotte

##### SUMMARY
Join an ESXi host to an AD domain. Requirement to enable AD authentication.

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
vmware_host_ad_auth

##### ANSIBLE VERSION
```
2.8-devel
```

##### ADDITIONAL INFORMATION

2018-11-02 08:23 UTC, Akasurde requested changes
Rest LGTM

2018-11-02 08:23 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_host_ad_auth.py
> +        - AD Domain to join.
```suggestion
        - AD Domain to join.
        type: str
```

2018-11-02 08:23 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_host_ad_auth.py
> +        - Username for AD domain join.
```suggestion
        - Username for AD domain join.
        type: str
```

2018-11-02 08:23 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_host_ad_auth.py
> +        - Password for AD domain join.
```suggestion
        - Password for AD domain join.
        type: str
```

2018-11-02 08:23 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_host_ad_auth.py
> +                        msg = "Host is joined to AD domain, but "
👍

2018-11-02 09:18 UTC, ckotte commented on lib/ansible/modules/cloud/vmware/vmware_host_ad_auth.py
> +        - AD Domain to join.
thx. done

2018-11-02 09:19 UTC, ckotte commented on lib/ansible/modules/cloud/vmware/vmware_host_ad_auth.py
> +        - Username for AD domain join.
thx. done

2018-11-02 09:19 UTC, ckotte commented on lib/ansible/modules/cloud/vmware/vmware_host_ad_auth.py
> +        - Password for AD domain join.
thx. done

2018-11-02 09:27 UTC, Akasurde approved these changes

2018-11-14 09:10 UTC, Akasurde commented
@pdellaert @dericcrago @Im0 @tchernomax @jeking3 Could you please review this ?

2018-11-14 13:24 UTC, jeking3 reviewed
Nice results handling, looks very complete.  Not sure how this can be integration tested however.  The VMware modules are begging for a unit test framework with MagicMock that would enable error path validation.  I had a few questions, but likely nothing that should block a commit.

2018-11-14 13:24 UTC, jeking3 commented on lib/ansible/modules/cloud/vmware/vmware_host_ad_auth.py
> +#
Is a copyright statement for Ansible, RedHat, or IBM required here?

2018-11-14 13:24 UTC, jeking3 commented on lib/ansible/modules/cloud/vmware/vmware_host_ad_auth.py
> +     choices: [ join, leave ]
Should this be `present`, `absent` similar to all the other cases of `state:`?  Or perhaps this should have another name like `action:` or `ad_state:` instead? (that way all the ad related variables would start with `ad_`.

2018-11-14 13:24 UTC, jeking3 commented on lib/ansible/modules/cloud/vmware/vmware_host_ad_auth.py
> +  domain:
Should this have an alias of `domain_name`, and or be named `ad_domain:` ?

2018-11-14 13:24 UTC, jeking3 commented on lib/ansible/modules/cloud/vmware/vmware_host_ad_auth.py
> +  ad_user:
Should there also be the ability to authenticate by kerberos ticket, so that the solution can be more secure, and usernames and passwords to not need to be copied and shipped around?

2018-11-14 16:00 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_host_ad_auth.py
> +#
Nope, Generally people who add module/code adds their / their company's copyright.

2018-12-03 13:34 UTC, ckotte commented on lib/ansible/modules/cloud/vmware/vmware_host_ad_auth.py
> +  ad_user:
Looks like this isn't possible

2018-12-03 13:35 UTC, ckotte commented on lib/ansible/modules/cloud/vmware/vmware_host_ad_auth.py
> +  domain:
I changed it to `ad_domain` and added aliases

2018-12-03 14:18 UTC, ckotte commented on lib/ansible/modules/cloud/vmware/vmware_host_ad_auth.py
> +     choices: [ join, leave ]
I also thought about that when I wrote the script. I changed it to `ad_state` w/ `absent` and `present`.

2018-12-03 14:21 UTC, ckotte commented
> Not sure how this can be integration tested however. The VMware modules are begging for a unit test framework with MagicMock that would enable error path validation.

I added some tests, but they are disabled because I assume we don't have an AD domain.

2018-12-03 15:01 UTC, Akasurde commented
@jeking3 @ckotte I have started on unit test for VMware module_utils - https://github.com/ansible/ansible/pull/49421/files

2018-12-03 16:04 UTC, jeking3 commented
@Akasurde 👍 for unit tests

2018-12-18 10:46 UTC, Akasurde commented
Closing and re-opening for CI trigger.

2018-12-18 11:04 UTC, merged