Add CloudWatch as grafana datasource type (#44298)
ansible/ansible pull request #48174
Opened 2018-11-06 17:14 UTC by martinwangjian

##### SUMMARY

Add CloudWatch as grafana datasource type.
Fixes #44298

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
grafana_datasource

##### ANSIBLE VERSION
Here is my ansible --version
```
ansible 2.6.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.6 (default, Jul 19 2018, 16:29:00) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
```

2018-11-07 09:26 UTC, seuf requested changes
Some documentation issues. The rest looks good

2018-11-07 09:26 UTC, seuf commented on lib/ansible/modules/monitoring/grafana_datasource.py
> +  - Martin Wang (@Mart1nWang)
you should put your github account here

2018-11-07 09:26 UTC, seuf commented on lib/ansible/modules/monitoring/grafana_datasource.py
> +      - Profile for AWS credentials for CloudWatch datasource type when aws_auth_type is 'credentials"
when C(aws_auth_type) es C(credentials)

2018-11-07 09:26 UTC, seuf commented on lib/ansible/modules/monitoring/grafana_datasource.py
> +      - AWS access key for CloudWatch datasource type when aws_auth_type is 'keys"
when C(aws_auth_type) is C(keys)

2018-11-07 09:26 UTC, seuf commented on lib/ansible/modules/monitoring/grafana_datasource.py
> +      - AWS secret key for CloudWatch datasource type when aws_auth_type is 'keys"
when C(aws_auth_type) is C(keys)

2018-11-07 09:26 UTC, seuf commented on lib/ansible/modules/monitoring/grafana_datasource.py
> +      - AWS IAM role arn to assume for CloudWatch datasource type when aws_auth_type is 'arn"
when C(aws_auth_type) is C(arn)

2018-11-07 09:54 UTC, martinwangjian commented
Thx! all documentation issues are fixed

2018-11-29 19:53 UTC, resmo approved these changes
shipit

2018-11-29 19:56 UTC, resmo commented
closes #44298

2018-11-29 19:58 UTC, merged

2018-11-29 19:59 UTC, resmo commented
Thanks!