Changed single file zip write parameter for arcname to use os.path.ba…
ansible/ansible pull request #48285
Opened 2018-11-07 02:53 UTC by bbyhuy

…sename rather than string splicing path

Fixes #46277

##### SUMMARY

Previously, single file compression used string splicing to get arcname paramter for zip.write. Changes it to use os.path.basename.

Fixes #46277
##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

archive
##### ANSIBLE VERSION

```paste below
ansible 2.8.0.dev0 (archive_module_arcroot_len_path_bug baa7a0db45) last updated 2018/11/06 18:50:37 (GMT -700)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/mlghugma/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/mlghugma/ansible/lib/ansible
  executable location = /home/mlghugma/ansible/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### ADDITIONAL INFORMATION

Tested with both archiving with file in a directory and without. Without directory no longer truncs first character of filename. 

```paste below

```

2018-11-29 10:44 UTC, gundalow requested changes
Thank you for this bug fix.
Can you please extend the integration tests to cover this https://github.com/ansible/ansible/tree/devel/test/integration/targets/archive

https://docs.ansible.com/ansible/latest/dev_guide/testing_integration.html#testing-integration

Ensure that the test fails without your patch.

2018-11-29 10:55 UTC, webknjaz commented on lib/ansible/modules/files/archive.py
>                          arcfile = zipfile.ZipFile(dest, 'w', zipfile.ZIP_DEFLATED, True)
probably not related to this PR but if someone will be doing future refactoring, please replace this with `with` block using a context manager.

2018-11-29 10:57 UTC, webknjaz approved these changes

2018-11-29 10:58 UTC, webknjaz requested changes
A regression test is required.

2018-12-12 10:34 UTC, gundalow commented
@bbyhuy Would you be able to look at the comments above, thanks in advance.

2020-08-16 16:19 UTC, closed without merging