rabbitmq_binding: Fix using empty routing key
ansible/ansible pull request #48597
Opened 2018-11-13 13:22 UTC by sn4kebite

If the routing key is an empty string we need to use the special props
value ~ in the URL. Otherwise the last part of the URL will be empty,
which will instead be equivalent to the "list all bindings" API call
which always returns 200 OK (as long as the exchange and queue exists).

##### SUMMARY

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
rabbitmq_binding

##### ANSIBLE VERSION

```paste below
ansible 2.8.0.dev0 (devel 03f71e778b) last updated 2018/11/13 13:28:04 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/jon/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jon/ansible-git/lib/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.1 (default, Oct 22 2018, 10:41:28) [GCC 8.2.1 20180831]
```

##### ADDITIONAL INFORMATION

Example playbook:
```yaml
- hosts: localhost
  connection: local
  tasks:
    - name: rabbitmq exchange
      rabbitmq_exchange:
        name: test
        type: direct
    - name: rabbitmq queue
      rabbitmq_queue:
        name: test
    - name: rabbitmq bindings
      rabbitmq_binding:
          source: test
          destination: test
          routing_key: ''
          type: queue
```

Before fix (no changes are detected even when the binding is missing):
```paste below
PLAY [localhost] **************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [rabbitmq exchange] ******************************************************************************************************************************************************************************************************************************************************************************************************
changed: [localhost]

TASK [rabbitmq queue] *********************************************************************************************************************************************************************************************************************************************************************************************************
changed: [localhost]

TASK [rabbitmq bindings] ******************************************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost]

PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=4    changed=2    unreachable=0    failed=0   
```

After fix:
```paste below
 PLAY [localhost] **************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [rabbitmq exchange] ******************************************************************************************************************************************************************************************************************************************************************************************************
changed: [localhost]

TASK [rabbitmq queue] *********************************************************************************************************************************************************************************************************************************************************************************************************
changed: [localhost]

TASK [rabbitmq bindings] ******************************************************************************************************************************************************************************************************************************************************************************************************
changed: [localhost]

PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=4    changed=3    unreachable=0    failed=0    skipped=0   
```

2018-11-29 10:51 UTC, Shaps requested changes
The `routing_key` parameter defaults to `#` [(L279)](https://github.com/ansible/ansible/blob/a02558c8ff8a9eca65a25485f5b3137c34ab7690/lib/ansible/modules/messaging/rabbitmq/rabbitmq_binding.py#L279) so I don't see how it could be an empty string. In  any case I would rather change the `default` then have an `if ... else ...`

2018-11-29 11:12 UTC, sn4kebite commented
Just changing the default won't work. If you explicitly specify an empty string (like in the provided example) as the routing key it will still break.

2018-11-29 12:18 UTC, Shaps commented
This is a fair point, I'd still prefer to have the `if/else` outside the `format` setting the `self.routing_key` var

2018-12-19 13:18 UTC, Shaps commented
shipit

2018-12-19 13:20 UTC, resmo approved these changes
LGTM

2018-12-19 13:30 UTC, merged