Point feature for Pluribus Networks netvisor
ansible/ansible pull request #48647
Opened 2018-11-14 07:26 UTC by rajaspachipulusu17

##### SUMMARY
Point feature for Pluribus Networks Netvisor switches 

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

pn_access_list

##### ADDITIONAL INFORMATION

```paste below
ansible 2.4.0.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

2018-11-14 07:41 UTC, Akasurde commented
@rajaspachipulusu17 Thanks for the PR. Any reason that we are removing other modules while adding new modules?

2018-11-14 07:43 UTC, rajaspachipulusu17 commented
> @rajaspachipulusu17 Thanks for the PR. Any reason that we are removing other modules while adding new modules?

Those are old modules. It has compatibility issues.

2018-11-14 08:26 UTC, Akasurde commented
@rajaspachipulusu17 In order to remove / deprecate a module, you need to follow [module deprecation workflow](https://docs.ansible.com/ansible/latest/dev_guide/module_lifecycle.html#deprecating-modules).

2018-11-14 15:56 UTC, Akasurde requested changes

2018-11-14 15:56 UTC, Akasurde commented on lib/ansible/module_utils/network/netvisor/pn_nvos.py
> +#
`module_utils` generally covered under BSD License, so 

Replace line 1-16 with
```
# Simplified BSD License (see licenses/simplified_bsd.txt or https://opensource.org/licenses/BSD-2-Clause)
```

2018-11-14 15:56 UTC, Akasurde commented on lib/ansible/modules/network/netvisor/pn_access_list.py
> +#
Replace line 2 to 17 with 

```
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)


from __future__ import absolute_import, division, print_function
__metaclass__ = type
```

2018-11-14 15:56 UTC, Akasurde commented on lib/ansible/modules/network/netvisor/pn_access_list.py
> +#
Add Copyright like 

```
# Copyright: (c) 2018, Pluribus Networks
```

2018-11-14 15:56 UTC, Akasurde commented on lib/ansible/modules/network/netvisor/pn_access_list.py
> +  - create and delete an access list
```suggestion
  - This module can be used to create and delete an access list.
```

2018-11-14 15:56 UTC, Akasurde commented on lib/ansible/modules/network/netvisor/pn_access_list.py
> +short_description: CLI command to create/delete access-list.
```suggestion
short_description: CLI command to create/delete access-list
```

2018-11-14 15:56 UTC, Akasurde commented on lib/ansible/modules/network/netvisor/pn_access_list.py
> +      - Access List Name
```suggestion
      - Access List Name.
```

2018-11-14 15:56 UTC, Akasurde commented on lib/ansible/modules/network/netvisor/pn_access_list.py
> +      - scope - local or fabric
```suggestion
      - 'scope. Available valid values - local or fabric.'
```

2018-11-14 15:56 UTC, Akasurde commented on lib/ansible/modules/network/netvisor/pn_access_list.py
> +    if out:
This block can be simplified as - 

```Python
    results = dict(
        command=' '.join(cmd).replace(remove_cmd, ''),
        msg="%s operation completed" % command,
        changed=True
    )

    if out:
        results['stdout'] = out.strip()
    
    module.exit_json(**results)
    
```

2018-11-19 09:53 UTC, rajaspachipulusu17 commented
Can i know what is the procedure to merge this commit. I have made all the requested changes.

2018-11-19 11:21 UTC, Akasurde commented
@rajaspachipulusu17 First we need to merge this PR https://github.com/ansible/ansible/pull/48791 then we can start working on this.

2018-11-20 02:58 UTC, rajaspachipulusu17 commented
Hi Team,Should I change any thing to merge #48791? There is no comments yet it's been 4 days now.Thanks,RajasOn 19-Nov-2018 4:52 PM, Abhijeet Kasurde <notifications@github.com> wrote:@rajaspachipulusu17 First we need to merge this PR #48791 then we can start working on this.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

2018-11-26 06:10 UTC, amitsi commented
ship it

2018-11-26 06:10 UTC, amitsi commented
shipit

2018-11-27 05:34 UTC, rajaspachipulusu17 commented
Creating another PR as ansibot added stale_cl and stale_review state.

2018-11-27 05:34 UTC, closed without merging

2018-11-27 06:09 UTC, rajaspachipulusu17 commented
PR https://github.com/ansible/ansible/pull/49176