[WIP] add redis cache facts
ansible/ansible pull request #48652
Opened 2018-11-14 09:06 UTC by yungezz

##### SUMMARY

will add tests later

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2018-11-14 09:22 UTC, zikalino commented on lib/ansible/modules/cloud/azure/azure_rm_rediscache_facts.py
> +        new_result['id'] = rediscache.id
you can create entire dictionary at once

2018-11-26 03:17 UTC, yungezz commented
add tests after redis cache merged

2018-11-26 07:38 UTC, Fred-sun commented
@yungezz I have tested this PR and get successful result, Does this PR ready for review? could you can remove the WIP label ?

2019-01-16 06:36 UTC, Fred-sun commented
@yungezz How about the PR going, Could we can remove the WIP label and push for review? Thanks!

2019-02-01 02:29 UTC, yungezz commented
ready_for_review

2019-02-14 08:28 UTC, Fred-sun commented
@yuwzho @zikalino

2019-02-19 00:56 UTC, zikalino commented on lib/ansible/modules/cloud/azure/azure_rm_rediscache_facts.py
> +            - Indicate wheather to return access keys of the redis cache.
whether

2019-02-19 00:57 UTC, zikalino commented on lib/ansible/modules/cloud/azure/azure_rm_rediscache_facts.py
> +    rediscaches:
that should be example of module usage, not return value

2019-02-19 01:01 UTC, zikalino commented on lib/ansible/modules/cloud/azure/azure_rm_rediscache_facts.py
> +            sample: /subscriptions/<subs_id>/resourceGroups/<resourcegroup>/providers/Microsoft.Cache/Redis/testredis1
should be consistent with sample name and resource_group

2019-02-19 01:02 UTC, zikalino commented on lib/ansible/modules/cloud/azure/azure_rm_rediscache_facts.py
> +                - The full resource ID of a subnet in a virtual network to deploy the Redis cache in.
should use consistently "redis cache" or "Redis cache" upper case / lower case?

2019-02-19 01:03 UTC, zikalino requested changes
the main comment is about examples, others are minor.

2019-02-19 01:55 UTC, yungezz commented
ready_for_review

2019-02-19 04:43 UTC, zikalino approved these changes

2019-02-19 04:43 UTC, merged