Changes to redfish-based parameters
ansible/ansible pull request #48717
Opened 2018-11-15 12:35 UTC by tomasg2012

Corrected redfish parameters to their Schematic counterparts

##### SUMMARY
Changes all playbook related variables to counterparts related to their Redfish terminology as best as possible, in order to maintain a similar vocabulary between the playbooks and Redfish.  In the event of conflicting terms, prefix with appropriate information.

user -> username
userid -> id
username -> new_username
password -> new_password
userrole -> roleid
bios_attr_name -> bios_attribute_name
mgr_attr_name -> manager_attribute_name
bios_attr_name -> bios_attribute_name
mgr_attr_name -> manager_attribute_name

Fixes #46549

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/modules/remote_management/redfish

##### ADDITIONAL INFORMATION
No changed behavior.

2018-11-15 13:03 UTC, tomasg2012 commented
Oh, I didn't check the unit tests, but even so I don't exactly know what this means...

2018-11-15 16:34 UTC, billdodd commented
For the command names that changed, looks like you need to add a version_added in the DOCUMENTATION section. For example, the username command doc section should now look like:

```
  username:
    required: true
    description:
      - User for authentication with OOB controller
    version_added: "2.8"
```

2018-11-26 22:46 UTC, jose-delarosa commented
@tomasg2012 I get an error when attempting to apply the 2nd commit in my dev environment. I am grabbing the patch https://patch-diff.githubusercontent.com/raw/ansible/ansible/pull/48717.patch. Even if I split it up into 2 patches (one per commit), I still can't apply. @billdodd are you able to apply cleanly?

2018-11-27 00:18 UTC, billdodd commented
@jose-delarosa - I didn't try to apply the diff; I just copied the PR versions of those 3 files into my dev env.

But I just tried to apply the patch and it fails for me too. It is because there was a recent change to the "author" field in the doc string. See:

https://github.com/ansible/ansible/pull/48934/files#diff-3d4788ad762224c470f73e56259e2b01

I'd say just copy the 3 changed files into your dev env for any testing/review. When the PR gets approved it may need some manual intervention to merge. But that bridge can be crossed when and if needed.

2018-11-27 19:42 UTC, billdodd requested changes
See inline comment about creds dict in redfish_config.py. Otherwise looked good to me.

2018-11-27 19:42 UTC, billdodd commented on lib/ansible/modules/remote_management/redfish/redfish_config.py
> +    creds = {'username': module.params['username'],
Key name should stay "user":

```
    creds = {'user': module.params['username'],
```

2018-11-27 21:07 UTC, jose-delarosa commented
No wonder it was failing for me :)

2018-11-27 22:23 UTC, jose-delarosa commented
Looks good to me.

shipit

2018-11-27 22:23 UTC, tomasg2012 commented
shipit

2018-11-27 22:32 UTC, billdodd approved these changes
With the latest commit, looks good now.

shipit

2018-11-27 23:05 UTC, jose-delarosa commented
This doesn't touch module_utils, so it *should* auto-merge...

2018-11-27 23:16 UTC, merged