templar: ensure that exceptions are handled, fix 'AttributeError'
ansible/ansible pull request #48792
Opened 2018-11-16 10:58 UTC by pilou-

##### SUMMARY

Fix `AttributeError`:
```
The full traceback is:
Traceback (most recent call last):
  File "ansible/lib/ansible/template/vars.py", line 106, in __getitem__
    value = self._templar.template(variable)
  File "ansible/lib/ansible/template/__init__.py", line 430, in template
    disable_lookups=disable_lookups,
  File "ansible/lib/ansible/template/__init__.py", line 678, in do_template
    res = j2_concat(rf)
  File "<template>", line 11, in root
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ansible/lib/ansible/executor/task_executor.py", line 144, in run
    res = self._execute()
  File "ansible/lib/ansible/executor/task_executor.py", line 535, in _execute
    self._task.post_validate(templar=templar)
  File "ansible/lib/ansible/playbook/task.py", line 271, in post_validate
    super(Task, self).post_validate(templar)
  File "ansible/lib/ansible/playbook/base.py", line 364, in post_validate
    value = templar.template(getattr(self, name))
  File "ansible/lib/ansible/template/__init__.py", line 475, in template
    disable_lookups=disable_lookups,
  File "ansible/lib/ansible/template/__init__.py", line 430, in template
    disable_lookups=disable_lookups,
  File "ansible/lib/ansible/template/__init__.py", line 678, in do_template
    res = j2_concat(rf)
  File "<template>", line 9, in root
  File "ansible/lib/ansible/template/__init__.py", line 236, in resolve_or_missing
    val = super(AnsibleContext, self).resolve_or_missing(key)
  File "lib/python3.7/site-packages/jinja2/runtime.py", line 217, in resolve_or_missing
    return resolve_or_missing(self, key)
  File "lib/python3.7/site-packages/jinja2/runtime.py", line 129, in resolve_or_missing
    return context.parent[key]
  File "ansible/lib/ansible/template/vars.py", line 110, in __getitem__
    msg = getattr(e, 'message') or to_native(e)
AttributeError: 'JSONDecodeError' object has no attribute 'message'
```

Unit test provided.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/template/vars.py

##### ADDITIONAL INFORMATION

```paste below

```

2018-11-16 14:58 UTC, bcoca requested changes

2018-11-16 14:58 UTC, bcoca commented on lib/ansible/template/vars.py
> -                msg = getattr(e, 'message') or to_native(e)
we still want message if it exists, another way to fix this:
``` 
msg = getattr(e, 'message', to_native(e)) or to_native(e)
```

2018-11-27 18:54 UTC, bcoca approved these changes

2018-11-29 10:01 UTC, gundalow approved these changes

2018-11-29 10:03 UTC, webknjaz approved these changes

2018-11-29 14:56 UTC, merged

2018-11-30 10:27 UTC, gundalow commented
@pilou- You OK to backport + changelog this?

2018-11-30 14:05 UTC, pilou- commented
@gundalow: backport PR created.