prepend 'ANSIBLE' to overlooked variables, define DEFAULT_VERBOSITY constant
ansible/ansible pull request #48802
Opened 2018-11-16 12:46 UTC by tb3088

##### SUMMARY
a simple grep turned up settings that didn't have ANSIBLE_ prepended to the environment variable. Also trying to use ANSIBLE_VERBOSITY=N failed during parser.add_option() because the constant was not defined.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
Config

2018-11-16 14:07 UTC, tb3088 commented
Does the Shippable config need to be toned down on parallelism? It's hitting quota limit on instance slots.

2018-11-16 16:43 UTC, mattclay commented
@tb3088 There was an issue with the CI AWS account which has been fixed. I've restarted the tests.

2018-11-16 17:10 UTC, bcoca requested changes

2018-11-16 17:10 UTC, bcoca commented on lib/ansible/config/base.yml
> +  env: [{name: ANSIBLE_DISPLAY_SKIPPED_HOSTS}]
you can add a new variable, don't just remove the old one, it requires a deprecation period

2020-06-05 15:17 UTC, jimi-c commented
Hi @tb3088, sorry for taking so long to get back to this, but it looks like since you've opened this PR the variables in question have been modified already. As such, we're going to go ahead and close this PR. If there are any other variables that might still need to be tweaked, you're welcome to open a new PR, however we do ask that they be added to the list of variable names rather than replaced so that the old names continue to work.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code
   * IRC: #ansible or #ansible-devel on irc.freenode.net

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

2020-06-05 15:17 UTC, closed without merging