Add integration test for password_hash
ansible/ansible pull request #48922
Opened 2018-11-20 08:52 UTC by Akasurde

##### SUMMARY
* Tests for password_hash filter
* Documentation update

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
docs/docsite/rst/user_guide/playbooks_filters.rst
lib/ansible/plugins/filter/core.py
test/integration/targets/filters/tasks/main.yml

2018-11-26 21:23 UTC, mattclay requested changes

2018-11-26 21:23 UTC, mattclay commented on test/runner/requirements/integration.txt
> +bcrypt
This dependency isn't needed for all tests, so install it during the test instead:

https://github.com/ansible/ansible/blob/26a677c2a921f30204a2911dd1482cb087c3124f/test/integration/targets/filters/runme.sh#L7

2018-11-27 02:33 UTC, Akasurde commented on test/runner/requirements/integration.txt
> +bcrypt
OK.

2018-11-27 02:51 UTC, mattclay approved these changes

2018-12-19 21:12 UTC, mattclay commented
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/99126/44/tests

2019-02-05 06:14 UTC, closed without merging