Aws waf region
ansible/ansible pull request #48953
Opened 2018-11-20 20:09 UTC by mjmayer

##### SUMMARY
Adds support for WAF Regional to the Ansible WAF Modules

Fixes #44767 #44896
##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
aws_waf_condition
aws_waf_facts
aws_waf_rule
aws_waf_web_acl
module_utils/aws/waf
module_utils/aws/waiters

##### ADDITIONAL INFORMATION
There are two WAF modules in botocore. WAF and WAFRegional. They function largely in the same way. But there are differences. These changes add support for WAFRegional without changing the existing behavior of the module.

Previously WAF worked like:
```
- name: create IP address condition
  aws_waf_condition:
    name: "{{ resource_prefix }}_ip_condition"
    filters:
      - ip_address: "10.0.0.0/8"
      - ip_address: "192.168.0.0/24"
    type: ip
```

It now supports WAF Regional and takes the waf_regional bool parameter
```
- name: create IP address condition
  aws_waf_condition:
    name: "{{ resource_prefix }}_ip_condition"
    filters:
      - ip_address: "10.0.0.0/8"
      - ip_address: "192.168.0.0/24"
    type: ip
    waf_regional: true
    region: '{{ aws_region }}'
```

2018-11-21 15:32 UTC, DaveHewy commented
@mjmayer well done for raising the PR! Looks v.v.similar to my working branch :+1:

2018-11-28 16:38 UTC, DaveHewy commented
@mjmayer want a hand with tidying this pr up at all?

2018-11-28 17:18 UTC, mjmayer commented
@DaveHewy Sure, if you think it can be improved on. I'll take the help.

@Sivel Could you look over this PR and give feedback if any changes are needed?

2018-12-04 19:24 UTC, mjmayer commented
@sivel are you able to review this PR?

2018-12-13 03:24 UTC, willthames commented on lib/ansible/modules/cloud/amazon/aws_waf_condition.py
> +        description: Wether to use waf_regional module. Defaults to false.
typo: whether

2018-12-13 03:26 UTC, willthames commented
Other than the 'Wether' typo, this looks good to me.

2018-12-31 11:29 UTC, davehewy commented
@mjmayer @willthames @sivel  what is now required to get this over the line?

2019-03-11 11:34 UTC, DaveHewy commented
> Other than the 'Wether' typo, this looks good to me.

@willthames - can we get merging then?

2019-04-05 20:01 UTC, mjmayer commented
@willthames Any chance we can get some love on adding support for the regional wafs and get it merged?

2019-05-15 20:09 UTC, mjmayer commented
@sivel This PR is good to go. What is preventing it from getting merged?

2019-05-16 01:21 UTC, willthames requested changes

2019-05-16 01:21 UTC, willthames commented on lib/ansible/modules/cloud/amazon/aws_waf_condition.py
> +        version_added: 2.8
Needs to be 2.9 now

2019-05-16 01:21 UTC, willthames commented on lib/ansible/modules/cloud/amazon/aws_waf_facts.py
> +      version_added: "2.8"
2.9 now

2019-05-16 01:21 UTC, willthames commented on lib/ansible/modules/cloud/amazon/aws_waf_rule.py
> +            module.fail_json_aws(e, msg='Could not list WAF rules')
Is it worth saying regional rules here?

2019-05-16 01:21 UTC, willthames commented on lib/ansible/modules/cloud/amazon/aws_waf_web_acl.py
> +        version_added: "2.8"
2.9

2019-05-16 01:21 UTC, willthames commented on lib/ansible/modules/cloud/amazon/aws_waf_web_acl.py
> +        description: Wether to use waf_regional module. Defaults to false.
typo: whether

2019-05-16 01:21 UTC, willthames commented on lib/ansible/modules/cloud/amazon/aws_waf_web_acl.py
> +            module.fail_json_aws(e, msg='Could not list rules')
regional rules?

2019-05-16 01:21 UTC, willthames commented on lib/ansible/modules/cloud/amazon/aws_waf_rule.py
> +        description: Wether to use waf_regional module. Defaults to false
typo: Whether

2019-05-16 01:21 UTC, willthames commented on lib/ansible/modules/cloud/amazon/aws_waf_rule.py
> +        version_added: "2.8"
2.9 now

2019-05-16 01:22 UTC, willthames commented
Apologies for not revisiting this sooner - I don't always see mentions. Feel free to nudge me on IRC for re-reviews (nudging here does work, as seen now, but it less likely)

2019-05-16 18:50 UTC, mjmayer commented on lib/ansible/modules/cloud/amazon/aws_waf_condition.py
> +        version_added: 2.8
48288e1

2019-05-17 00:35 UTC, willthames approved these changes

2019-05-17 00:36 UTC, merged

2019-05-17 00:36 UTC, willthames commented
Merged, thanks @mjmayer! Apologies again for the various delays