mail: restore module working with python 2.7
ansible/ansible pull request #49016
Opened 2018-11-22 05:02 UTC by k0ste

##### SUMMARY

Try to fix `mail` module for Python 2.7 & Python 3.7

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

mail

##### ANSIBLE VERSION

```paste below
ansible 2.7.2
  config file = /home/k0ste/.ansible.cfg
  configured module search path = ['/home/k0ste/ansible/my_modules', '/home/k0ste/ceph-ansible/library']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.1 (default, Oct 22 2018, 10:41:28) [GCC 8.2.1 20180831]
```

##### ADDITIONAL INFORMATION

Resolve #48785.

2018-11-22 06:08 UTC, Akasurde requested changes

2018-11-22 06:08 UTC, Akasurde commented on lib/ansible/modules/notification/mail.py
> +import sys
```suggestion
from ansible.module_utils.six import PY3
```

2018-11-22 06:08 UTC, Akasurde commented on lib/ansible/modules/notification/mail.py
> +                if python_version < 3:
```suggestion
                params = dict(timeout=timeout)
                if PY3:
                   params['host'] = host
                   params['port'] = port
                smtp = smtplib.SMTP_SSL(**params)
                code, smtpmessage = smtp.connect(host=host, port=port)
```

2018-11-22 06:08 UTC, Akasurde commented on lib/ansible/modules/notification/mail.py
> +            if python_version < 3:
same as above

2018-11-28 13:39 UTC, dagwieers commented
I propose we close this PR as it hasn't seen any progress for the past 6 days.
There's a new PR #49197 and a backport #49222 which includes integration tests for the mail module.

2018-11-28 14:08 UTC, k0ste commented
@dagwieers 
There are a progress in #48785.

2018-11-28 14:14 UTC, dagwieers commented
@k0ste I am sorry, but I started fixing this yesterday not realising this PR and issue were already open for 6 days.

I am the maintainer of this module, but was not notified about this issue and PR by @ansibot. In the meantime I added integration tests to ensure the mail module is working correctly, so that in the future changes won't break it anywhere in our test-matrix. So I prefer we continue with the more extensive PR.

bot_broken

2018-11-29 03:34 UTC, k0ste commented on lib/ansible/modules/notification/mail.py
> +import sys
+

2018-11-29 03:34 UTC, k0ste commented on lib/ansible/modules/notification/mail.py
> +                if python_version < 3:
`+`

2018-11-29 03:34 UTC, k0ste commented on lib/ansible/modules/notification/mail.py
> +            if python_version < 3:
Done

2018-12-05 07:40 UTC, jpmens commented
This PR fixes `mail.py` for me on Python 2.7.15

2018-12-05 10:16 UTC, webknjaz commented on lib/ansible/modules/notification/mail.py
> +                params = dict(timeout=timeout)
I'd use a dict literal.

2018-12-11 03:50 UTC, Akasurde commented
@k0ste Thanks for the contribution. This PR is superseded by https://github.com/ansible/ansible/pull/49197

2018-12-11 03:50 UTC, closed without merging