SSL mongo: certs parametrs
ansible/ansible pull request #49035
Opened 2018-11-22 19:28 UTC by incognito1990

##### SUMMARY
- add ssl parametrs for mongo template

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

2018-11-26 10:28 UTC, incognito1990 commented
##### SUMMARY
- add ssl parametrs for mongo template

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME


##### ADDITIONAL INFORMATION

2019-02-13 12:50 UTC, dagwieers requested changes
A few remarks:
- I would make this behave differently, enable ssl automatically when ssl-parameters are specified.
- I was expecting dependencies between ssl-options. Are all these SSL options independent ?
- These options should go in all MongoDB modules, and we should have a mongodb module_utils and doc_fragments (currently this PR has them undocumented)

2019-02-13 12:50 UTC, dagwieers commented on lib/ansible/modules/database/mongodb/mongodb_user.py
> +            ssl_certfile=dict(default=None),
```suggestion
            ssl_certfile=dict(type='path'),
```

2019-02-13 12:50 UTC, dagwieers commented on lib/ansible/modules/database/mongodb/mongodb_user.py
> +            ssl_keyfile=dict(default=None),
```suggestion
            ssl_keyfile=dict(type='path'),
```

2019-02-13 12:50 UTC, dagwieers commented on lib/ansible/modules/database/mongodb/mongodb_user.py
> +            ssl_ca_certs=dict(default=None),
```suggestion
            ssl_ca_certs=dict(type='path'),
```

2019-02-13 12:53 UTC, dagwieers commented
@mikhail-yarosh @ymrsmns It appears you want/need this functionality, it helps if people review PRs to get them merged. Aside from other users (i.e. the community) we shouldn't expect a higher entity to accept and merge new functionality.

If you like to help out, [join the MongoDB Working Group](https://github.com/ansible/community/wiki/MongoDB).

2019-02-13 14:38 UTC, mikhail-yarosh commented
@dagwieers ok, understood... so, should we report an issue or feature request or whatever to see this functionality in future?

2020-08-16 15:56 UTC, closed without merging