aix_chsec module
ansible/ansible pull request #49057
Opened 2018-11-23 12:28 UTC by flynn1973

##### SUMMARY
adds stanzas to aix config files using the chsec command.

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
aix_chsec

##### ADDITIONAL INFORMATION
example plays:
- name: add ldap user stanza
  aix_chsec:
    path: /etc/security/user
    stanza: ldapuser
    options: SYSTEM=LDAP,registry=LDAP
    state: present
    mode: 0644

- name: change login times for user
  aix_chsec:
    path: /etc/security/user
    stanza: ldapuser
    options: logintimes=:0800-1700
    state: present

- name: remove registry option from stanza
  aix_chsec:
    path: /etc/security/user
    stanza: ldapuser
    options: SYSTEM=LDAP,registry=
    state: present

```

2019-01-08 23:22 UTC, dagwieers requested changes
LGTM, some cosmetic changes and an important fix to documentation.

2019-01-08 23:22 UTC, dagwieers commented on lib/ansible/modules/system/aix_chsec.py
> +    - files
```suggestion
```
I don't think this is correct, it would include all the default files-parameters, al lot which are not supported by this module. It is better to only add those that are relevant to this module.

2019-01-08 23:22 UTC, dagwieers commented on lib/ansible/modules/system/aix_chsec.py
> +short_description: modify aix stanza files
```suggestion
short_description: Modify AIX stanza files
```

2019-01-08 23:22 UTC, dagwieers commented on lib/ansible/modules/system/aix_chsec.py
> +version_added: "0.1"
```suggestion
version_added: '2.8'
```
This is a required fix as it states the first version this module ships with.

2019-01-08 23:22 UTC, dagwieers commented on lib/ansible/modules/system/aix_chsec.py
> +    - "adds stanzas to aix config files using the chsec command. see "man chsec" for additional infos"
```suggestion
    - Modify stanzas to AIX config files using the chsec command.
notes:
    - See `man chsec` for additional information.
```
This fixes an important documentation syntax error, causing a lot of errors as a result.

2019-01-08 23:22 UTC, dagwieers commented on lib/ansible/modules/system/aix_chsec.py
> +            - Path to the stanza file
```suggestion
            - Path to the stanza file.
        type: path
```

2019-01-08 23:22 UTC, dagwieers commented on lib/ansible/modules/system/aix_chsec.py
> +            - name of stanza
```suggestion
            - Name of stanza.
```

2019-01-08 23:22 UTC, dagwieers commented on lib/ansible/modules/system/aix_chsec.py
> +             - comman separated key/value pairs eg. key=val,key=val
```suggestion
             - A list of key/value pairs, e.g. `key=val,key=val`
         type: list
```

2019-01-08 23:22 UTC, dagwieers commented on lib/ansible/modules/system/aix_chsec.py
> +         choices: [ absent, present ]
```suggestion
         type: str
         choices: [ absent, present ]
```

2019-01-08 23:22 UTC, dagwieers commented on lib/ansible/modules/system/aix_chsec.py
> +extends_documentation_fragment:
```suggestion
```

2019-01-08 23:22 UTC, dagwieers commented on lib/ansible/modules/system/aix_chsec.py
> +- name: add ldap user stanza
```suggestion
- name: Add an LDAP user stanza
```

2019-01-08 23:22 UTC, dagwieers commented on lib/ansible/modules/system/aix_chsec.py
> +- name: change login times for user
```suggestion
- name: Change login times for user
```

2019-01-08 23:22 UTC, dagwieers commented on lib/ansible/modules/system/aix_chsec.py
> +    mode: 0644
```suggestion
    mode: '0644'
```

2019-01-08 23:22 UTC, dagwieers commented on lib/ansible/modules/system/aix_chsec.py
> +- name: remove registry option from stanza
```suggestion
- name: Remove registry option from stanza 
```

2019-01-08 23:22 UTC, dagwieers commented on lib/ansible/modules/system/aix_chsec.py
> +    options: SYSTEM=LDAP,registry=
```suggestion
    options:
    - SYSTEM=LDAP
    - registry=
```

2019-01-08 23:22 UTC, dagwieers commented on lib/ansible/modules/system/aix_chsec.py
> +        supports_check_mode=False,
It would be nice if this module supported check-mode.

2019-01-08 23:28 UTC, dagwieers requested changes

2019-01-08 23:28 UTC, dagwieers commented on lib/ansible/modules/system/aix_chsec.py
> +        path=path
```suggestion
        path=path,
```
This is a recommendation for dictionaries (and explained in PEP8)

2019-01-08 23:28 UTC, dagwieers commented on lib/ansible/modules/system/aix_chsec.py
> +    results = dict(
```suggestion
    result = dict(
```
More in line with a lot of modules.

2019-01-08 23:28 UTC, dagwieers commented on lib/ansible/modules/system/aix_chsec.py
> +    module.exit_json(**results)
```suggestion
    module.exit_json(**result)
```
More in line with a lot of modules.

2019-01-08 23:30 UTC, dagwieers commented
A few ideas to improve this module:
- Add check-mode support
- Add a `seealso:` section pointing to official `man chsec` documentation or online docs

2019-01-09 14:28 UTC, dagwieers requested changes

2019-01-09 14:28 UTC, dagwieers commented on lib/ansible/modules/system/aix_chsec.py
> +from ansible.module_utils.basic import *
```suggestion
from ansible.module_utils.basic import AnsibleModule
```
This is not allowed.

2019-01-09 14:34 UTC, dagwieers commented
@flynn1973 There is still a long list of issues to resolve before we can even start considering this module. My other concern is that you proposed this module which was written by someone else. So you are not the copyright holder of the code. We prefer contributions to come from the copyright holder, or are done with the copyright holder's consent.

2019-01-09 14:56 UTC, flynn1973 commented
@dagwieers this module is not written by someone else, you may refering to the modules from molekuul. he as already part of the aix community and he already gave me his approval to do the PR's.

2019-01-09 15:09 UTC, molekuul commented
> 
> 
> @dagwieers this module is not written by someone else, you may refering to the modules from molekuul. he as already part of the aix community and he already gave me his approval to do the PR's.

@dagwieers This module is indeed not written by me, but by flynn1973

2019-01-09 15:28 UTC, dagwieers commented
Oh ok, I am really confused now :-) It did not have a copyright-statement so I jumped to conclusions.

2019-01-09 15:39 UTC, molekuul commented
> 
> 
> Oh ok, I am really confused now :-) It did not have a copyright-statement so I jumped to conclusions.

@dagwieers,

sorry for the confusion, flynn1973, issued a lot of pull requests for modules which I wrote, but flynn1973 
also issued this pull request of his own written module :-)

2019-01-09 21:19 UTC, dagwieers commented
@flynn1973 I fixed all the open issues from CI. But we need to work on:
- idempotency (not making changes when they are not needed)
- check-mode support (act as if you're making a change without making the change)
- integration tests (playbooks that use the module for making changes and testing if it behaves as expected)

2019-01-15 10:40 UTC, flynn1973 commented
@dagwieers 
ad idempotency: i am not aware of any option to the chsec command which allows pre checks. it is a fire and forget thing. same goes for the check mode support.

ad integration tests: i use this module on a daily basis and it works smoothly.

2019-01-15 11:12 UTC, molekuul commented
> 
> 
> @dagwieers
> ad idempotency: i am not aware of any option to the chsec command which allows pre checks. it is a fire and forget thing. same goes for the check mode support.

@flynn1973 there is also a command lssec. It lists attributes in the security stanza files.
You first check the value of each of the parameters in the stanza by the lssec command, and than change only those. which are different.

2019-01-19 19:55 UTC, dagwieers requested changes

2019-01-19 19:55 UTC, dagwieers commented on lib/ansible/modules/system/aix_chsec.py
> +    - SYSTEM=LDAP
To me it seems more logical if the format is not a list, but a dictionary.
```yaml
      options:
        SYSTEM: LDAP
        registry: LDAP
        logintimes: :0800-1700
```

The only reasons for using a list here, would be to ensure a specific order for processing, or to ensure that a specific key can be duplicate (so provided keys are not unique). But I don't think these are no applicable here.

2019-01-19 19:55 UTC, dagwieers commented on lib/ansible/modules/system/aix_chsec.py
> +    - SYSTEM=LDAP
If you are worried about breaking backward compatibility with existing users, you can use `type: raw` and test if a string, a list or a dict was provided, and handle strings as `key=val`, use dicts as an iterable `key: value` store, and a list could contain either of those two.

And then only document/showcase the dicts syntax, and provide a deprecation message for people using a list or a string. Which could then be removed after 4 major releases (which is what we typically do).

2019-01-19 19:55 UTC, dagwieers commented on lib/ansible/modules/system/aix_chsec.py
> +            changed = True
There is no guarantee something was changed here. So this would mean the module can only either fail or report changes.

2019-01-19 19:55 UTC, dagwieers commented on lib/ansible/modules/system/aix_chsec.py
> +    options = list(arguments_generator(options))
It's probably better to loop over the items and check the value before changing, so you can report back if there was a change or not.

2019-07-14 19:51 UTC, d-little commented
I've written a proposal below for what I think the behaviour of the aix_chsec module should have, with a few open design questions.  I'd like aix_chsec to be in 2.9, so am looking for responses!

##### SUMMARY

Below is a IBM AIX [chsec]((https://www.ibm.com/support/knowledgecenter/en/ssw_aix_72/com.ibm.aix.cmds1/chsec.htm)) module design proposal.

I've been trying to write a role to 'easily' wrap up the IBM AIX chsec command and make it idempotent.  While I've got it (mostly) working [here](https://github.com/d-little/ansible-role-aix-chsec), I'd rather help to make a module to perform this work instead of maintaining such a clunky role.

##### COMPONENT NAME

aix_chsec

##### Idempotency

We can make the tool idempotent by first checking the output of [`lssec`](https://www.ibm.com/support/knowledgecenter/en/ssw_aix_72/com.ibm.aix.cmds3/lssec.htm) before making changes.  It should be trivial to use this command in Python.

I'm achieving this in the ansible-role-aix-chsec using something similar to:

```shell
shell: >
  ( lssec -f '{{ file }}' -s '{{ stanza }}' -a '{{ key }}' | grep -q '{{ stanza }} {{ key }}={{ value }}' ) && echo nochange || chsec -f '{{ file }}' -s '{{ stanza }}' -a '{{ key }}={{ value }}'
```

##### Scope

This module could be part of a larger module to manage many types of AIX settings (aix_settings ?), or simply focus on the chsec command itself.  For now we can focus on aix_chsec.

##### Potential Layout(s)

###### 'Simple'

One example implementation with multiple key/value being set within a single files+stanza at a time:

```yaml
- name: Name of Task
  aix_chsec:
    file: filename
    stanza: stanzaname
    attributes:
      key1: value1
      key2: value2
      keyN: valueN
    state: [ present, absent ]
    backup: bool (default no, timestamped backup before making changes.)
```

This would return `Changed` if *any number* of the above key/value pairs were changed.  If *none* were changed it would be `OK`.  Failure to change *any* key:value pair would consitute as a `failure` regardless of how many attributes were successfully set.  In order to check for failure we need to re-check the `lssec` command after chsec is run;  chsec will often return 0 even if nothing changed.

- `attributes` can have an alias `attrs`
- Attributes alternatives:
  - `attributes: [ (key, value), (key, value), (key, value) ]`
  - `attributes: [ key: value, key2: value2 ]`

**Real world use:**

- Allow logins from 8:00 a.m. until 5:00 p.m. for all users
- Change the CPU time limit of user joe AND chrlie to 1 hour (3600 seconds):

```yaml
---
- hosts: targetserver
  gather_facts: no
  vars:
    example_chsec:
      - file: /etc/security/user
        stanza: default
        attrs:
          logintimes: ":0800-1700"
      - file: /etc/security/limits
        stanza: joe
        attrs: [ cpu: 3600 ]
      - file: /etc/security/limits
        stanza: charlie
        attrs:
          cpu: 3600
  remote_user: deploy
- tasks:
  name: Example chsec
    aix_chsec:
      file: "{{ item.file }}"
      stanza: "{{ item.stanza }}"
      attrs: "{{ item.attrs }}"
    loop:
      - "{{ example_chsec }}"
```

The example_chsec YAML above converts to the following JSON:

```JSON
{
  "example_chsec": [
    {
      "file": "/etc/security/user",
      "stanza": "default",
      "attrs": {
        "logintimes": ":0800-1700"
      }
    },
    {
      "file": "/etc/security/limits",
      "stanza": "joe",
      "attrs": {
        "cpu": 3600
      }
    },
    {
      "file": "/etc/security/limits",
      "stanza": "charlie",
      "attrs": {
        "cpu": 3600,
        "file": -1
      }
    }
  ]
}
```

###### 'Nested' Stanzas

We could 'nest' stanzas for a single file within a single module call.  This makes configuration slightly more complicated, but can potentially reduce the amount of required tasks/YAML code.  We can keep the `stanza` option available in addition to `stanzas`, mutually exclusive.

```yaml
- name: Name of Task
  aix_chsec:
    file: filename
    stanzas:
      - stanza1:
          key1: value1
          key2: value2
          keyN: valueN
        state: [ present|absent ]
      - stanza2:
          key1: value1
          key2: value2
          keyN: valueN
        state: [ present|absent ]
    backup: bool (default no, timestamped backup before making changes.)
```

Real world use:

- Allow logins from 8:00 a.m. until 5:00 p.m. for all users
- Change the CPU time limit of user joe AND chrlie to 1 hour (3600 seconds):

```yaml
---
- hosts: targetserver
  gather_facts: no
  vars:
    example_chsec:
      - file: /etc/security/user
        stanza: default
        attrs:
          logintimes: ":0800-1700"
      - file: /etc/security/limits
        stanzas:
        - joe:
            cpu: 3600
            file: -1
        - charlie:
            cpu: 3600
  remote_user: deploy
- tasks:
  name: Example chsec
    aix_chsec:
      file: "{{ item.file }}"
      stanza: "{{ item.stanza }}"
      attrs: "{{ item.attrs }}"
    loop:
      - "{{ example_chsec }}"
```

The example_chsec YAML above converts to the following JSON:

```JSON
{
  "example_chsec": [
    {
      "file": "/etc/security/user",
      "stanza": "default",
      "attrs": {
        "logintimes": ":0800-1700"
      }
    },
    {
      "file": "/etc/security/limits",
      "stanzas": [
        {
          "joe": {
            "cpu": 3600,
            "file": -1
          }
        },
        {
          "charlie": {
            "cpu": 3600
          }
        }
      ]
    }
  ]
}
```

##### Open Questions

- When setting multiple attributes per stanza, do we:
  - Run one chsec per attribute, or using a single chsec with multiple attributes
  - Fail as soon as one attribute fails, or try to set every attribute before failing the module?
    - ie: IF we're setting the ulimits `file`, `count`, and `size`;  if `file` fails to set, do we continue to try `count` and `size` and then quit with failure, or quit at the point of failure?
- Do we stick with **one-stanza-per-file** or allow **many-stanzas-per-file**?

2019-08-20 18:41 UTC, d-little commented on lib/ansible/modules/system/aix_chsec.py
> +            changed = True
Unless I am mistaken, this doesnt actually do anything.  I do not believe it's possible to have an 'absent' flag to remove an entire stanza.  `chsec` can only remove given attrs/options from a given stanza, it cannot remove the entire stanza.

This code block is just 'unsetting' all of the given attrs/options and ignoring the value assigned to them.  These two YAML examples behave exactly the same way even though one has state=present and the other state=absent:
```yaml
- name: Remove LDAP user stanzas
  aix_chsec:
    path: /etc/security/user
    stanza: ldapuser
    options: SYSTEM=LDAP,registry=LDAP
    state: absent
```

```yaml
- name: Remove LDAP user stanzas
  aix_chsec:
    path: /etc/security/user
    stanza: ldapuser
    options: SYSTEM=,registry=
    state: present
```

HOWEVER, if there are other attrs set on that user stanza, the *stanza will still exist*.  You need to specify every single user attr/option on that stanza to remove the stanza.  Adding a 'true' state=absent will mean going through the given `file`, finding the stanza, getting all of the key:value pairs in that stanza, and then running chsec key=null to every one of those.

That's a loooot more work.

2019-09-27 11:52 UTC, flynn1973 commented
closed in favour of #60976

2019-09-27 11:52 UTC, closed without merging