Correct the suggestion how to get rid of the command module's recommendation.
ansible/ansible pull request #49339
Opened 2018-11-29 22:54 UTC by aknrdureegaesr

##### SUMMARY

In many cases when the `command` module is used for something for which a more specific module
exists, a warning is generated. That warning contains instructs to

> ... add warn=False to this command task ... to get rid of this message.

This is a useful hint, only it doesn't work. What one should add is `warn: no`.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

command

##### ADDITIONAL INFORMATION

Even though `warn: false` might also work, I prefer `warn: no` for consistency with the `warn` parameter's [documentation](https://docs.ansible.com/ansible/latest/modules/command_module.html#parameters).

To demonstrate the bug, save this as file `bug_produce.yaml` and run with `ansible-playbook bug_produce.yaml`.

```
# This playbook demonstrates the warning and how to get rid of it properly.

- hosts: localhost

  tasks:

  - name: This shows the warning.
    command:
      argv:
        - touch
        - /tmp/some_stupid_file

  - name: This does not show the warning, the proper way.
    command:
      warn: no
      argv:
        - touch
        - /tmp/some_other_file

#   - name: This does as the present buggy instructions say. Does not work.
#     command:
#       warn=False
#       argv:
#         - touch
#         - /tmp/yet_another_file
```

The message you see is:

> TASK [This shows the warning.] *************************************************    
>  [WARNING]: Consider using the file module with state=touch rather than running touch.  If you need to use command because file is insufficient you can add warn=False to this command task or set command_warnings=False in ansible.cfg to get rid of this message.

2018-12-02 11:05 UTC, aknrdureegaesr commented
I just see there is another problem. It says `file module with state=touch`, but it should read `file module with state: touch`. I fix that, too.

2018-12-02 15:31 UTC, aknrdureegaesr commented
ready_for_review

2018-12-04 21:17 UTC, sivel requested changes
This change, although it meets your needs more specifically, will actually cause more confusion for the majority of users using the `command` and `shell` modules.

The typical usage is not using `argv` by instead using `_raw_params` such as:

```
- command: touch /tmp/yet_another_file
```

To address the warning there, you would use the form provided in the message:

```
- command: touch /tmp/yet_another_file warn=False
```

Simply making the change you suggest would not work for the most common case here, as that would become:

```
- command: touch /tmp/yet_another_file warn: false
```

Or in the other case:

```
- command: touch /tmp/yet_another_file
  warn: false
```

Both of those last 2 will not work.  Instead, in order to use `warn: false` with a raw string as the parameter, you would need to use

```
- command: touch /tmp/yet_another_file
  args:
    warn: false
```

I do not believe that trying to relay that much information in the message is useful.

As such, we should leave the message as is, but instead improve the documentation by adding examples of how to use `warn=False`/`warn: false`.

2018-12-04 23:56 UTC, aknrdureegaesr commented
Thanks! Good point!

> As such, we should leave the message as is, but instead improve the documentation by adding examples of how to use warn=False/warn: false.

I agree.

2019-10-26 14:13 UTC, Akasurde commented
@aknrdureegaesr Are you still working on this, let us know ? Thanks, needs_info

2019-10-26 15:41 UTC, aknrdureegaesr commented
No, sorry. I still think it would be a good idea to improve the documentation as outlined by @sivel, but I'm active elsewhere right now and lack the time + opportunity to do so in the foreseeable future. If someone else want to take this over, go for it with many thanks from me!

2019-10-26 16:15 UTC, Akasurde commented
@aknrdureegaesr Thanks for the information. Closing this in-favor of #63825. Thanks for the contribution.

2019-10-26 16:15 UTC, closed without merging

2019-10-26 16:15 UTC, Akasurde commented
@aknrdureegaesr Thanks for the information. Closing this in-favor of #63825. Thanks for the contribution.

2019-10-26 18:28 UTC, aknrdureegaesr commented
Fine with me, and you're welcome.