Pluribus Networks admin service module
ansible/ansible pull request #49354
Opened 2018-11-30 08:31 UTC by rajaspachipulusu17

##### SUMMARY

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION
ansible 2.4.0.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

```

2018-11-30 09:13 UTC, Akasurde commented on lib/ansible/modules/network/netvisor/pn_admin_service.py
> +      - Web (HTTP) to enable or disable
```suggestion
      - Web (HTTP) to enable or disable.
```

2018-11-30 09:13 UTC, Akasurde commented on lib/ansible/modules/network/netvisor/pn_admin_service.py
> +      - Web SSL (HTTPS) to enable or disable
```suggestion
      - Web SSL (HTTPS) to enable or disable.
```

2018-11-30 09:13 UTC, Akasurde commented on lib/ansible/modules/network/netvisor/pn_admin_service.py
> +      - Simple Network Monitoring Protocol (SNMP) to enable or disable
```suggestion
      - Simple Network Monitoring Protocol (SNMP) to enable or disable.
```

2018-11-30 09:16 UTC, Akasurde commented on lib/ansible/modules/network/netvisor/pn_admin_service.py
> +      - Netvisor API to enable or disable APIs
```suggestion
      - Netvisor API to enable or disable APIs.
```

2018-11-30 09:16 UTC, Akasurde commented on lib/ansible/modules/network/netvisor/pn_admin_service.py
> +      - Web (HTTP) port to enable or disable
```suggestion
      - Web (HTTP) port to enable or disable.
```

2018-11-30 09:17 UTC, Akasurde requested changes
Could you please add integration/unit test for  this change? Thanks.

2018-11-30 09:18 UTC, Akasurde commented on lib/ansible/modules/network/netvisor/pn_admin_service.py
> +author: "Pluribus Networks (rpachi@pluribusnetworks.com)"
```suggestion
author: "Pluribus Networks (@rajaspachipulusu17)"
```

2018-11-30 10:10 UTC, rajaspachipulusu17 commented
@Akasurde , Thanks for the review. I have made all suggested changes.

2018-11-30 11:03 UTC, rajaspachipulusu17 commented
@Akasurde 

Could you please add integration/unit test for this change? Thanks.

Where should i add it. I have given example.

2018-11-30 11:59 UTC, Akasurde commented
> Where should i add it. I have given example.

You can take a look into [this](https://github.com/ansible/ansible/tree/devel/test/units/modules/network). You can read more about [Ansible testing](https://docs.ansible.com/ansible/latest/dev_guide/testing.html) here.

2018-12-03 11:58 UTC, rajaspachipulusu17 commented
@Akasurde  it will be merged only if i send PR of unit testing?

2018-12-03 12:42 UTC, Akasurde commented
> @Akasurde it will be merged only if i send PR of unit testing?

Yes.

2018-12-14 06:24 UTC, rajaspachipulusu17 commented
This is pushed with units in PR #49854

2018-12-14 06:24 UTC, closed without merging