Issue: 46475 Fix onyx magp module for supporting new json format
ansible/ansible pull request #49417
Opened 2018-12-02 12:05 UTC by anasbadaha

Signed-off-by: Anas Badaha <anasb@mellanox.com>

##### SUMMARY
Fixes #46475 by supporting new json changes

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
/lib/ansible/modules/network/onyx/onyx_magp.py
test/units/modules/network/onyx/test_onyx_magp.py

##### ADDITIONAL INFORMATION
ansible 2.8.0.dev0 (issue/46410 122601e) last updated 2018/12/02 10:06:44 (GMT +000)
config file = /etc/ansible/ansible.cfg
configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
ansible python module location = /.autodirect/mtrswgwork/anasb/ansible_dev6/lib/ansible
executable location = /.autodirect/mtrswgwork/anasb/ansible_dev6/bin/ansible
python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

```paste below

```

2018-12-02 12:50 UTC, anasbadaha commented
Hi @ganeshrn,
Please merge this PR

2018-12-03 05:24 UTC, ganeshrn commented on lib/ansible/modules/network/onyx/onyx_magp.py
> +        self._os_version = self._get_os_version()
Refer https://github.com/ansible/ansible/pull/49414#pullrequestreview-180616762 The capability dict in onyx cliconf plugin can store version and other product releated information at time of connection initilaization instead of executing `show version` for every task run.

2018-12-03 05:26 UTC, ganeshrn requested changes
onyx cliconf `get_capabilities()` api can be reused to fetch version related information in the module instead of executing `show version` for each task run.

2018-12-16 07:04 UTC, anasbadaha commented
@ganeshrn please merge!

2018-12-17 05:22 UTC, ganeshrn approved these changes

2018-12-17 05:22 UTC, ganeshrn commented
@anasbadaha Thank you!

2018-12-17 05:22 UTC, merged