Fixes #46410 Onyx show facts module does not work for onyx version 3.…
ansible/ansible pull request #49414
Opened 2018-12-02 10:10 UTC by anasbadaha

…6.6000 and higher

Signed-off-by: Anas Badaha <anasb@mellanox.com>

##### SUMMARY
Fixes #46410 Onyx show facts module does not work for onyx version 3.6.6000 and higher

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
onyx_facts.py

##### ADDITIONAL INFORMATION
ansible 2.8.0.dev0 (issue/46410 122601ec90) last updated 2018/12/02 10:06:44 (GMT +000)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /.autodirect/mtrswgwork/anasb/ansible_dev6/lib/ansible
  executable location = /.autodirect/mtrswgwork/anasb/ansible_dev6/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

```paste below

```

2018-12-02 12:50 UTC, anasbadaha commented
Hi @ganeshrn,
Please merge this PR

2018-12-03 05:19 UTC, ganeshrn requested changes
If `Product Release` information is not available in capability dict it can be added in onyx cliconf plugin which can be reused by all the other onyx modules if required

2018-12-03 05:19 UTC, ganeshrn commented on lib/ansible/modules/network/onyx/onyx_facts.py
> +    COMMANDS = ['show version', 'show interfaces ethernet']
I can see onyx has a [cliconf plugin](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/cliconf/onyx.py#L65) that retrieves the target version at the time of initial connection.
You can refer to `get_capabilities()` [here](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/network/ios/ios.py#L82)

2018-12-16 07:05 UTC, anasbadaha commented
@ganeshrn please merge!

2018-12-17 05:23 UTC, ganeshrn approved these changes

2018-12-17 05:23 UTC, merged