New module: xenserver_guest_facts - returns facts of XenServer VMs
ansible/ansible pull request #49426
Opened 2018-12-02 23:54 UTC by bvitnik

##### SUMMARY
This module implements fact gathering of XenServer VMs (guests) with module interface comparable to vmware_guest_facts module. In simple use cases, these modules are interchangeable. It complements xenserver_guest module.

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
xenserver_guest_facts

##### ADDITIONAL INFORMATION
The module is trivially implemented since all the functionality is contained in xenserver module_util.

2018-12-03 02:37 UTC, Akasurde commented
Same like other module, could you please add unit test cases for this change - [here](https://github.com/ansible/ansible/tree/devel/test/units/modules/cloud) ? Thanks.

2019-01-15 04:17 UTC, bvitnik commented
@Akasurde Hi. Sorry for the delay. I've added some unit tests for the module. I will need this PR merged first before I commit unit tests for other module (xenserver_guest_powerstate, PR #49425) since these two modules will share some testing code.

As this module is just using functions from the xenserver module util, I've also implemented a complete suite of unit tests for xenserver module util itself in separate PR #50850 .

2019-02-06 18:37 UTC, bvitnik commented
@Akasurde Hi. PR #50850 has been reviewed and merged by mattclay and I've also made appropriate changes to unit testing code in this PR. Can you please review this PR again and notify me if other changes are needed before the merge?

2019-02-09 08:14 UTC, Akasurde requested changes
Rest LGTM

2019-02-09 08:14 UTC, Akasurde commented on lib/ansible/modules/cloud/xenserver/xenserver_guest_facts.py
> +import re
Unused import.

2019-02-09 08:14 UTC, Akasurde commented on lib/ansible/modules/cloud/xenserver/xenserver_guest_facts.py
> +from ansible.module_utils._text import to_text, to_native
Unused import

2019-02-09 08:14 UTC, Akasurde commented on lib/ansible/modules/cloud/xenserver/xenserver_guest_facts.py
> +from ansible.module_utils import six
Unused import.

2019-02-09 18:11 UTC, bvitnik commented
@Akasurde Done. Thanks for noticing unused imports.

2019-02-12 11:26 UTC, Akasurde approved these changes
LGTM

2019-02-12 11:26 UTC, merged