Allow win_uri to send json with just one item
ansible/ansible pull request #49484
Opened 2018-12-04 15:16 UTC by ilpianista

##### SUMMARY
Fixes #49483

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
win_uri

##### ADDITIONAL INFORMATION
As per subject, actually win_uri fails to send a JSON which contains just one item; instead it sends "System.Object[]".

2018-12-04 16:19 UTC, ilpianista commented
BTW, I cherry-picked this to v2.7.4, but the integration test fails there. Any idea why?

2018-12-04 21:17 UTC, jhawkesworth commented
@ilpianista - This looks good to me.  Thanks for adding a test.
 Can you share link for the cherry-pick PR - I will take a look?

2018-12-04 21:19 UTC, jhawkesworth commented
@ilpianista I meant to ask as well -  please can you add a changelog fragment.? They are a new(ish) thing but very helpful when upgrading ansible playbooks between versions.  Details of how are described here: https://docs.ansible.com/ansible/2.7/reference_appendices/release_and_maintenance.html#creating-new-fragments

2018-12-05 02:16 UTC, dagwieers commented on test/integration/targets/win_uri/tasks/test.yml
> +    body: "[{{ lookup('file', 'item.json') }}]"
We don't actually need to use a lookup plugin and a data file here, this is equivalent::
```yaml
  - name: send JSON body with 1 item in list
    win_uri:
      url: https://{{ httpbin_host }}/post
      method: POST
      body:
      - foo: bar
      headers:
        Content-Type: text/json
      return_content: yes
```

2018-12-05 02:17 UTC, dagwieers approved these changes
LGTM, although I would make the test not rely on a lookup plugin and additional file if there's a better minimal reproducer.

2018-12-05 02:30 UTC, jborean93 commented
> BTW, I cherry-picked this to v2.7.4, but the integration test fails there. Any idea why?

@ilpianista I'll need to look a bit further but there has been recent changes in devel where list values inside a dict were actually converted to an ArrayList whereas before it would not. This caused various issues and inconsistencies such as this and I believe is probably the cause of these issues. I'm sure the backported fix may be slightly different because of this but have a play around and see what the type is for the `$body` variable on older versions.

2018-12-05 08:07 UTC, ilpianista commented
> @ilpianista I'll need to look a bit further but there has been recent changes in devel where list values inside a dict were actually converted to an ArrayList whereas before it would not. This caused various issues and inconsistencies such as this and I believe is probably the cause of these issues. I'm sure the backported fix may be slightly different because of this but have a play around and see what the type is for the `$body` variable on older versions.

`$body`'s type is `PSCustomObject`. Which is wrong because you already lost the information about the array this way; thus this must be fixed somewhere during the "ansible-to-powershell" conversion.

2018-12-05 10:13 UTC, ilpianista commented
> @ilpianista - This looks good to me. Thanks for adding a test.
> Can you share link for the cherry-pick PR - I will take a look?

Done: https://github.com/ansible/ansible/pull/49535

2018-12-10 01:27 UTC, jborean93 requested changes

2018-12-10 01:27 UTC, jborean93 commented on lib/ansible/modules/windows/win_uri.ps1
> +    if ($body -is [Hashtable] -or $body -is [Array]) {
I would change this to `if ($body -is [System.Collections.IDictionary] -or $body -is [System.Collections.IList]) {`. This will future proof ourselves for the future if the format for a raw list value is not an array. This means that the ConvertTo-Json will be called if the body is either

* Hashtable
* Dictionary
* List
* ArrayList
* Array

2018-12-10 01:31 UTC, jborean93 commented
> $body's type is PSCustomObject. Which is wrong because you already lost the information about the array this way; thus this must be fixed somewhere during the "ansible-to-powershell" conversion.

Potentially this line https://github.com/ansible/ansible/blob/stable-2.7/lib/ansible/plugins/shell/powershell.py#L77 is the reason why it doesn't work for the older branches. An unfortunate aspect of PowerShell pipelining is if a single object is returned (or single entry array) then this will automatically be unpacked and seen as the single object in that array. What is going to make this difficult is that the exec wrapper has recently changed in devel and no longer uses this code. I'm wary about touching this code as it is no longer live and I assume you can just pass a json string as the body to get this all working on older versions.

2018-12-10 10:06 UTC, ilpianista commented
> I'm wary about touching this code as it is no longer live and I assume you can just pass a json string as the body to get this all working on older versions.

I'm already using a json string as the body, but it doesn't work (see https://github.com/ansible/ansible/pull/49535)

2018-12-10 10:06 UTC, ilpianista commented on lib/ansible/modules/windows/win_uri.ps1
> +    if ($body -is [Hashtable] -or $body -is [Array]) {
done

2018-12-10 11:12 UTC, jborean93 commented
@ilpianista I don't see where in that PR where you have set the body as a json string. It's still set to a list of dicts. What I'm trying to say is while I agree these changes should be merged into devel and part of the 2.8 release, I think the changes required to get this working on 2.7 and older will be too much.

I need to dig a little deeper to verify all this for the older branches but we can look into that once we get the fix into devel. If we can't backport this fix then someone should still be able to do `body: '[{"foo":"bar"}]' in their task.

2018-12-10 11:43 UTC, ilpianista commented
> I need to dig a little deeper to verify all this for the older branches but we can look into that once we get the fix into devel. If we can't backport this fix then someone should still be able to do `body: '[{"foo":"bar"}]'` in their task.

Oh I'm sorry, you are right - I thought I wrote it as string, but instead it uses the YAML syntax now.

And I can also confirm that it works by using the json string.

2018-12-12 04:06 UTC, jborean93 approved these changes
Looks great, thanks.

2018-12-12 04:06 UTC, merged