Add Direct Rule support for Firewall Module (rebase of #34027)
ansible/ansible pull request #49514
Opened 2018-12-04 23:26 UTC by maxamillion

##### SUMMARY

rebase/port of https://github.com/ansible/ansible/pull/34027 post `firewalld` module refactor

Add support Direct rule operations add/remove
Operation syntax
 Add Chain
```yaml
    -  firewalld:
          chain: sshg
          fw_family: ipv4
          table: filter
          permanent: true
          state: enabled
```
Add rule to chain
```yaml
    -  firewalld:
          chain: sshg
          fw_family: ipv4
          table: filter
          direct_rule: '-m tcp -p tcp --dport 332 -j ACCEPT'
          permanent: true
          state: enabled
```
Remove rule from chain
```yaml
    - firewalld:
          chain: sshg
          fw_family: ipv4
          table: filter
          direct_rule: '-m tcp -p tcp --dport 332 -j ACCEPT'
          permanent: true 
          state: disabled
```
Remove chain
```yaml
    -  firewalld:
          chain: sshg
          fw_family: ipv4
          table: filter
          permanent: true
```

Add passthrough
```yaml
    - firewalld:
          fw_family: ipv4
          direct_rule: '-I FORWARD -o bridge3 -j ACCEPT'
          permanent: true
          state: enabled
```
Remove passthrough
```yaml
    - firewalld:
          fw_family: ipv4
          direct_rule: '-I FORWARD -o bridge3 -j ACCEPT'
          permanent: true
          state: disabled
```

Contact: pershin87@yandex.ru

##### ISSUE TYPE
Feature Pull Request

##### COMPONENT NAME
firewalld module

2018-12-04 23:40 UTC, dagwieers commented
cc @rokat Please test this PR and provide feedback !

2018-12-05 21:11 UTC, rokat commented
So just tested, it works good +1: 
It was not documented 
But we can also set the rule priority :)  Thanks a lot !

2018-12-08 02:13 UTC, dagwieers approved these changes
I do not use this module, but based on feedback of @rokat, I approve.

2018-12-08 02:23 UTC, dagwieers requested changes
Still have some cosmetic comments though.

2018-12-08 02:23 UTC, dagwieers commented on lib/ansible/modules/system/firewalld.py
> +      - 'firewalld iptables direct rule'
Descriptions must be in Sentence case and have a trailing dot.
(Same for other descriptions)
There's also no need to quote the whole line.

2018-12-08 02:23 UTC, dagwieers commented on lib/ansible/modules/system/firewalld.py
> +      - 'ip address family for the firewall rule (C(ipv4) or C(ipv6)), used with the C(direct_rule) option'
Must be in Sentence case, and IP needs bee upper case.
Also it should mention that the default is to be both ipv4 and ipv6.

2018-12-08 02:23 UTC, dagwieers commented on lib/ansible/modules/system/firewalld.py
> +- firewalld:
Examples require `name:` entries because that is what we recommend everywhere. So we should follow our own recommendation.
(I know the other examples do not have this correct either, so at least this PR is consistent)

2018-12-08 02:23 UTC, dagwieers commented on lib/ansible/modules/system/firewalld.py
> +            chain=dict(required=False, default=None),
We avoid adding `required=False` and `default=None`, but we must add `type=str`.
Same for the other options.
```suggestion
            chain=dict(type='str'),
```

2018-12-13 17:09 UTC, maxamillion commented
@dagwieers I think I've resolved the items you requested changed, please review at your earliest convenience. Thanks!

2019-01-17 15:20 UTC, wyrstz commented
Also tested adding and removing rules.  Just a couple of comments to clarify usage ;

1. Make sure you add the **immediate: true** in your ansible-playbook if you define a task for **firewalld:**, for example ;

- tasks:
    - name: add direct rules
      firewalld:
        ...
        immediate: true
        ...
If you dont include the above, when ansible runs the playbook it will show that a change has occured, but when you log onto the host, neither the command 'firewall-cmd --direct --get-all-rules, or an iptables -L <your chain name> -n' will show either the rule you are adding or removing. Alternativly you you need to run a 'firewall-cmd --reload' on your target host to see the rule changes you applied with Ansible.

Users should also be aware that if your used to using the **firewall-cmd firewall-cmd --query-port=<some_port_numer>/tcp --zone=<some_zone>** to confirm the addition or removal of a port, then this command will not confirm the addition or removal of a port as this command does not work with rules defined as a **direct rule**.

2019-02-07 04:20 UTC, maxamillion commented
rebased and squashed commits

2019-02-08 05:01 UTC, dagwieers requested changes
Still some changes I would make.
Do you want me to make this instead in an additional commit ?

2019-02-08 05:01 UTC, dagwieers commented on lib/ansible/modules/system/firewalld.py
> +      - 'The firewalld iptables direct rule you would like to enable/disable.'
We should be adding type-information to all parameters starting with Ansible v2.8.
Also, no need to quote the description, we tend to only quote when it is required by YAML.
```suggestion
      - The firewalld iptables direct rule you would like to enable/disable.
    type: str
```

2019-02-08 05:01 UTC, dagwieers commented on lib/ansible/modules/system/firewalld.py
> +    direct_rule: '-m tcp -p tcp --dport 332 -j ACCEPT'
No need to quote this line.
```suggestion
    direct_rule: -m tcp -p tcp --dport 332 -j ACCEPT
```

2019-02-08 05:01 UTC, dagwieers commented on lib/ansible/modules/system/firewalld.py
> +            table=dict(required=False, default=None),
```suggestion
            table=dict(type='str'),
```

2019-02-08 05:01 UTC, dagwieers commented on lib/ansible/modules/system/firewalld.py
> +            direct_rule=dict(required=False, default=None),
```suggestion
            direct_rule=dict(type='str'),
```

2019-02-08 05:01 UTC, dagwieers commented on lib/ansible/modules/system/firewalld.py
> +            fw_family=dict(required=False, default=None),
```suggestion
            fw_family=dict(type='str'),
```

2019-02-08 05:01 UTC, dagwieers commented on lib/ansible/modules/system/firewalld.py
> +            rule_priority=dict(type='int', required=False, default=0)
```suggestion
            rule_priority=dict(type='int', default=0),
```

2019-02-08 05:01 UTC, dagwieers commented on lib/ansible/modules/system/firewalld.py
>          supports_check_mode=True
```suggestion
        supports_check_mode=True,
```

2019-02-08 05:01 UTC, dagwieers commented on lib/ansible/modules/system/firewalld.py
> +    chain = None if not module.params['chain'] else module.params['chain']
It reads better the other way around:
```suggestion
    chain = module.params['chain'] if module.params['chain'] else None
```
But what is the purpose here ? To catch when the user provides an empty string ?

2019-02-08 05:01 UTC, dagwieers commented on lib/ansible/modules/system/firewalld.py
> +    direct_rule: '-m tcp -p tcp --dport 332 -j ACCEPT'
Same here.
```suggestion
    direct_rule: -m tcp -p tcp --dport 332 -j ACCEPT
```

2019-02-08 05:01 UTC, dagwieers commented on lib/ansible/modules/system/firewalld.py
> +    - ipv4
This example looks wrong, nowhere is `{{ item }}` used.
The loop should not be added, if `fw_family` is not provided it matches both ipv4 as well as ipv6.
So looping over this is unnecessary and unrecommended.
(Maybe explain this in the `name:` part ?)

2019-02-08 05:21 UTC, maxamillion commented on lib/ansible/modules/system/firewalld.py
> +      - 'The firewalld iptables direct rule you would like to enable/disable.'
Ah, sorry ... I've been shuffled off on a side project for a while so I'm a little out of the loop on Core on-goings. Thanks, will fix.

2019-02-08 05:27 UTC, maxamillion commented on lib/ansible/modules/system/firewalld.py
> +- firewalld:
Yes, I just copied these over from the original PR and I really should have sanitized it.

2019-02-12 04:16 UTC, dagwieers commented on lib/ansible/modules/system/firewalld.py
> +      - 'The firewalld iptables direct rule you would like to enable/disable.'
Please do :-)

2019-02-12 04:17 UTC, dagwieers requested changes

2019-02-12 04:17 UTC, dagwieers commented on lib/ansible/modules/system/firewalld.py
> +      - 'The iptables chain in which to insert the direct_rule, used with the C(direct_rule) option.'
Please do this for all parameters.
```suggestion
      - The iptables chain in which to insert the direct_rule, used with the C(direct_rule) option.
    type: str
```

2019-07-04 10:54 UTC, lemmy04 commented
what's holding this up? can I help?

... I *need* direct rules support, badly.

2019-10-09 13:05 UTC, till commented
Hi — We'd like to have this as well. Is there anything we can do to help here?

2019-10-10 21:11 UTC, maxamillion commented
@till - if you have any desire to take this over, I'll gladly hand it off ... it's unfortunately fallen way down my priority list these days

2019-10-22 02:39 UTC, roperto commented
I am happy to help pushing this one forward. Apart from the rebase, what else is blocking it?

Should I create a new PR or how can I amend this one?

2019-10-22 04:19 UTC, maxamillion commented
@roperto thank you so much for picking this up! definitely open a new PR and just reference this one for posterity, I'll gladly join in on the review and make sure we get it moving along from a review/merge perspective. Thank you again!!!

2019-10-22 04:19 UTC, closed without merging

2019-10-22 04:52 UTC, roperto commented
Thanks @maxamillion -- can you please review especially the names in the examples to make sure they are what you intended? Cheers, Daniel