Parse multiple values for single keys in cmdline facts
ansible/ansible pull request #49591
Opened 2018-12-06 09:36 UTC by Akasurde

##### SUMMARY
* Facts parsing for cmdline can now handle multiple values for a single key.
* Unit tests for cmdline fact parsing

Fixes: #22766

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
changelogs/fragments/22766-fact-cmdline-return_multiple_lvm_values.yaml
lib/ansible/module_utils/facts/system/cmdline.py
test/units/module_utils/facts/system/test_cmdline.py

2018-12-11 20:04 UTC, bcoca requested changes
This should be a new key, not give 2 diff results on same one, leave current as is and create new fact that always returns this as a list, then we can deal with deprecating/removing the current fact.

2018-12-19 20:38 UTC, mattclay commented
CI failure in unit tests: https://app.shippable.com/github/ansible/ansible/runs/99138/9/tests

2019-02-18 17:21 UTC, Akasurde commented
@bcoca Could you please take another look into this ? Thanks.

2019-02-18 17:39 UTC, bcoca approved these changes

2019-02-19 10:17 UTC, merged