Use blkid instead of udevadm when lsblk < 2.33 to gather fs uuids
ansible/ansible pull request #49598
Opened 2018-12-06 11:23 UTC by gfidente

##### SUMMARY
Sometimes udevadm takes more than 10 seconds to gather the device
informations, causing facts gathering to hit the default timeout.

This change tries to fix #43884 by replacing use of udevadm with
blkid, which collects a lot less informations but still provides
for a fs-independent way to gather a fs uuid.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
module_utils

2018-12-07 07:11 UTC, mkrizek commented
I recall I used `udevadm` for a reason. Doesn't `blkid` require root?

2018-12-07 09:13 UTC, gfidente commented
@mkrizek thanks for reviewing the change; both seem to work as non-root for me

2018-12-07 09:42 UTC, mkrizek commented
> @mkrizek thanks for reviewing the change; both seem to work as non-root for me

I assume that is because you have that information cached. Try running `blkid` in a fresh session.

From `man blkid` on my machine (Fedora 29):

`blkid reads information directly from devices and for non-root users it returns cached  unverified information.`

2018-12-07 09:43 UTC, mkrizek requested changes
As per the comment above.

2018-12-11 20:20 UTC, bcoca commented
this does not really fix the issue but tries to bypass by using different tools that won't always provide the same information in the same contexts. See original issue for proposed solution in comment.

2018-12-12 09:54 UTC, gfidente commented
@bcoca closing

2018-12-12 09:54 UTC, closed without merging