add static facility and apply to register
ansible/ansible pull request #49737
Opened 2018-12-10 17:52 UTC by bcoca

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

playbooks

2018-12-11 23:07 UTC, nitzmahone requested changes
Impl LGTM, probably should have a unit test for the static attr support and/or an integration test that confirms `register` emits the warning and uses the un-templated value.

2019-01-23 21:45 UTC, nitzmahone approved these changes

2019-01-23 21:45 UTC, nitzmahone commented
rebuild_merge

2019-01-24 09:57 UTC, mkrizek commented
bot_status

2019-01-24 16:51 UTC, merged