A lot of fixes after extensive use in production
ansible/ansible pull request #49789
Opened 2018-12-11 19:03 UTC by t794104

##### SUMMARY

After 1 year in productioin use we have a bunch of fixes

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

icinga2_host.py

##### ADDITIONAL INFORMATION

After extensive use in production we have multiple fixes for this module. This improves stability, error handling and function reliability

2018-12-12 05:35 UTC, Akasurde commented
@t794104 Thanks for the PR. Could you please add test case for this change [here](https://github.com/ansible/ansible/tree/devel/test/units/modules/monitoring) ? Thanks.

needs_info

2018-12-19 10:42 UTC, Akasurde requested changes
Could you please write unit test for this change ? Thanks.

2018-12-30 18:20 UTC, t794104 commented
Schip it

2019-08-14 06:05 UTC, mattclay commented on .settings/org.eclipse.core.resources.prefs
> +eclipse.preferences.version=1
This file should not be included in the PR.

I recommend adding `/.settings` to your global git ignore. See https://help.github.com/en/articles/ignoring-files#create-a-global-gitignore for how to do that.

2020-08-20 09:31 UTC, Akasurde commented
Hi @t794104, Thank you very much for your interest in Ansible. This plugin/module is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.general<br><br>If you have further questions please stop by IRC or the mailing list:<br><br>* IRC: #ansible on irc.freenode.net<br>* mailing list: https://groups.google.com/forum/#!forum/ansible-project<br><br>needs_info<br>

2020-08-20 09:31 UTC, closed without merging