[docker_container] Cleaning `env` of Python booleans
ansible/ansible pull request #49843
Opened 2018-12-12 22:41 UTC by DBendit

##### SUMMARY
Fixes #49802

Before, using Python booleans in the `env` option of docker_container would cause Docker to be unable to interpret them as booleans. Now, they're turned into data usable by the Docker API.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
docker_container

##### ADDITIONAL INFORMATION
N/A

2018-12-13 04:52 UTC, felixfontein requested changes
I'm not sure this is a good idea. We have no clue what exactly the user wanted (`yes`/`true`/`True`/..., `no`/`false`/`False`/...), and we currently simply select a random variant (`true`/`false`). It's probably better to fail and advise the user to quote this correctly. The official values accepted by YAML as booleans are `y|Y|yes|Yes|YES|n|N|no|No|NO|true|True|TRUE|false|False|FALSE|on|On|ON|off|Off|OFF` (see [here](https://yaml.org/type/bool.html)).

The `clean_dict_booleans_for_docker_api` function has so far been used in situations where certain boolean strings are more likely (namely `true` and `false`). But here, any of these variants is equally likely.

Instead of making a random choice, we should fail when we find a non-string (the same problem is true if the user writes `1.00`, which will end up as `1.0` by being converted to a `float` first -- depending on the context this is ok, or absolutely *not* ok).

2018-12-13 07:28 UTC, DBendit commented
@felixfontein Alright, I've redone it all to error out on non-string values. I've had my fair share of issues with YAML in the past, but I didn't realize that data loss was one of them. Totally with you - failure (with a helpful error message) is better than silent data loss.

ready_for_review

2018-12-13 22:26 UTC, felixfontein commented on lib/ansible/modules/cloud/docker/docker_container.py
> +        SECRET_KEY: "ssssh"
For most values (like this one) not quoting them is fine, but it's probably a good idea to set a good example here :)

Maybe add a second example with `"yes"` or so (and add a comment that quotations are needed as it is otherwise parsed as a bool).

2018-12-13 22:26 UTC, felixfontein commented on lib/ansible/modules/cloud/docker/docker_container.py
> +      - Values must be quoted in order to avoid YAML parsing losing data.
I wouldn't say "must", since most values do not need to be quoted to be parsed correctly. Maybe something like: `Make sure to quote values which might be parsed as numbers, booleans or other types by a YAML parser.`

2018-12-13 22:26 UTC, felixfontein commented on lib/ansible/modules/cloud/docker/docker_container.py
> -      - arg1: true
LOL, I didn't realize we had such a bad example already here! (And even worse: I added it...)

2018-12-13 22:26 UTC, felixfontein commented on lib/ansible/modules/cloud/docker/docker_container.py
> +                              "Env options must be wrapped in quotes to avoid YAML parsing. Key: %s Value: %s" % (name, str(value)))
I would formulate it a bit different (and don't add the value, the key should be fine):
```suggestion
                              "Ambiguous env options must be wrapped in quotes to avoid YAML parsing. Key: %s" % (name, ))
```

2018-12-13 22:26 UTC, felixfontein commented on test/integration/targets/docker_container/tasks/tests/options.yml
> +      TEST1: "val1"
I wouldn't add quotes to values where they aren't needed.

2018-12-13 22:26 UTC, felixfontein commented on test/integration/targets/docker_container/tasks/tests/options.yml
> +      TEST4: "true"
Maybe use `"yes"`, to have another truish value which would get corrupted (and probably not converted back correctly by any sane implementation).

2018-12-13 23:02 UTC, DBendit commented
Updated.

ready_for_review

2018-12-14 05:09 UTC, felixfontein approved these changes
LGTM

2018-12-14 17:57 UTC, felixfontein commented
bot_status

2018-12-14 19:21 UTC, merged

2018-12-14 20:45 UTC, felixfontein commented
@DBendit thanks for the PR! Do you want to create a backport PR for it?
@sivel thanks for merging!

2019-01-04 10:55 UTC, felixfontein commented
@DBendit please don't forget the backport PR for this and #49839 :-)

2019-01-04 20:17 UTC, DBendit commented
@felixfontein I completely had! Thank you for the reminder. Still trying to get back into the swing of things post-holidays

2019-01-07 23:27 UTC, felixfontein commented
@DBendit no problem :) There will probably be a new 2.7 release next week, so backports should probably be there until next Monday or so. (If you don't have time, I can also create them, just tell me.)

2019-01-14 20:50 UTC, felixfontein commented
@DBendit I created a backport in #50899 for this one; I also noticed that the other one was a Feature PR, so it won't get backported anyway. I hope you don't mind me creating the backport, I just wanted to have it in 2.7.6 :)