Pluribus Networks dhcp filter module with unit tests
ansible/ansible pull request #49848
Opened 2018-12-13 06:12 UTC by rajaspachipulusu17

##### SUMMARY

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME
pn_dhcp_filter.py module with unit tests.

##### ADDITIONAL INFORMATION
ansible 2.4.0.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

```

2018-12-14 06:26 UTC, rajaspachipulusu17 commented
@Akasurde  can you merge these if you dont have any issues?

Thanks,
Rajas

2018-12-14 06:33 UTC, pdam-arista approved these changes

2018-12-14 09:57 UTC, Akasurde commented on lib/ansible/modules/network/netvisor/pn_dhcp_filter.py
> +      - State the action to perform. Use 'present' to create dhcp-filter and
```suggestion
      - State the action to perform. Use C(present) to create dhcp-filter and
```

2018-12-14 09:57 UTC, Akasurde commented on lib/ansible/modules/network/netvisor/pn_dhcp_filter.py
> +        'absent' to delete dhcp-filter 'update' to modify the dhcp-filter.
```suggestion
        C(absent) to delete dhcp-filter and C(update) to modify the dhcp-filter.
```

2018-12-14 09:58 UTC, Akasurde commented on lib/ansible/modules/network/netvisor/pn_dhcp_filter.py
> +    choices: ['present', 'absent', 'update']
Type is missing.

2018-12-14 09:58 UTC, Akasurde requested changes
Rest LGTM

2018-12-18 07:19 UTC, rajaspachipulusu17 commented
@Akasurde can you merge this if you dont see any issue?

2018-12-19 11:45 UTC, Akasurde approved these changes

2018-12-19 11:46 UTC, merged