Pluribus Networks cpu class module with unit tests
ansible/ansible pull request #49847
Opened 2018-12-13 05:57 UTC by rajaspachipulusu17

##### SUMMARY

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME
pn_cpu_class.py module with unit tests.

##### ADDITIONAL INFORMATION
ansible 2.4.0.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

```

2018-12-13 08:42 UTC, rajaspachipulusu17 commented
@Akasurde can you review the commits?

2018-12-14 03:53 UTC, Akasurde commented on lib/ansible/modules/network/netvisor/pn_cpu_class.py
> +    choices: ['present', 'absent', 'update']
type is missing

2018-12-14 03:53 UTC, Akasurde commented on lib/ansible/modules/network/netvisor/pn_cpu_class.py
> +      - State the action to perform. Use 'present' to create cpu-class and
```suggestion
      - State the action to perform. Use C(present) to create cpu-class and
```

2018-12-14 03:54 UTC, Akasurde commented on lib/ansible/modules/network/netvisor/pn_cpu_class.py
> +        'absent' to delete cpu-class 'update' to modify the cpu-class.
```suggestion
        C(absent) to delete cpu-class C(update) to modify the cpu-class.
```

2018-12-14 03:55 UTC, Akasurde requested changes
Rest LGTM

2018-12-14 05:54 UTC, rajaspachipulusu17 commented
@Akasurde ansibot has some problem? It is in processing state from 40 mins.

2018-12-17 06:16 UTC, pdam-arista approved these changes

2018-12-17 06:20 UTC, rajaspachipulusu17 commented
@Akasurde  can you approve if there is no issue? i have made all the requested changes.

Thanks,
Rajas

2018-12-18 07:12 UTC, Akasurde approved these changes

2018-12-18 07:12 UTC, merged