Pluribus Networks admin service module with unit tests
ansible/ansible pull request #49854
Opened 2018-12-13 07:38 UTC by rajaspachipulusu17

##### SUMMARY

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME
pn_admin_service.py module with unit tests.

##### ADDITIONAL INFORMATION
ansible 2.4.0.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

```

2018-12-14 06:40 UTC, pdam-arista approved these changes

2018-12-17 05:32 UTC, rajaspachipulusu17 commented
@Akasurde can you merge this if you dont see any issue?

2018-12-18 07:05 UTC, Akasurde commented on lib/ansible/modules/network/netvisor/pn_admin_service.py
> +      - State the action to perform. Use 'update' to modify the admin-service.
```suggestion
      - State the action to perform. Use C(update) to modify the admin-service.
```

2018-12-18 07:06 UTC, Akasurde commented on lib/ansible/modules/network/netvisor/pn_admin_service.py
> +import shlex
Unused import

2018-12-18 07:08 UTC, Akasurde commented on lib/ansible/modules/network/netvisor/pn_admin_service.py
> +from ansible.module_utils.network.netvisor.pn_nvos import pn_cli, booleanArgs
```suggestion
from ansible.module_utils.network.netvisor.pn_nvos import pn_cli, booleanArgs, run_cli
```

2018-12-18 07:10 UTC, Akasurde requested changes
Rest LGTM

2018-12-19 06:23 UTC, rajaspachipulusu17 commented
@Akasurde can you merge this? if you dont have any issue?

2018-12-19 06:46 UTC, Akasurde commented
@rajaspachipulusu17 Could you please fix above mentioned error ?

2018-12-19 07:24 UTC, rajaspachipulusu17 commented
@Akasurde  i have fixed it

2018-12-19 11:44 UTC, Akasurde approved these changes

2018-12-19 11:44 UTC, merged