Added Ansible UTM Module for managing reverse proxy form template entries
ansible/ansible pull request #49866
Opened 2018-12-13 09:24 UTC by getjack

##### SUMMARY
This PR will add a new utm module which allows the management of reverse proxy form template entries of the Sophos UTM. This module integrates with the existing utm_utils .

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
- module/web_infrastructure/sophos_utm/utm_proxy_form_template.py
- module/web_infrastructure/sophos_utm/utm_proxy_form_template_info.py

2018-12-13 19:59 UTC, MatrixCrawler requested changes

2018-12-13 19:59 UTC, MatrixCrawler commented on lib/ansible/modules/web_infrastructure/sophos_utm/utm_proxy_form_template_info.py
> +            assets=dict(type='list', elements='str', required=False),
For an info module you will only need the name as this will be the identifier.
Please remove the other options

2018-12-18 08:06 UTC, MatrixCrawler commented on lib/ansible/modules/web_infrastructure/sophos_utm/utm_proxy_form_template_info.py
> +    module = UTMModule(
missing key_to_check_for_changes

2019-02-05 11:07 UTC, getjack commented
I am very sorry but i deleted the remote repo and i didn't check the PRs beforehand. Will redo the PRs and fix it. Sorry for the overhead :(

2019-02-05 11:07 UTC, closed without merging