Added Ansible UTM Module for managing AAA groups.
ansible/ansible pull request #49860
Opened 2018-12-13 09:05 UTC by getjack

##### SUMMARY
This PR will add a new utm module which allows the management of aaa groups of the Sophos UTM. This module integrates with the existing utm_utils .

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
- module/web_infrastructure/sophos_utm/utm_aaa_group.py

2018-12-13 11:57 UTC, MatrixCrawler commented
LGTM

shipit

2018-12-13 12:42 UTC, Akasurde requested changes
Could you please add Pytest unit test for this change - [here](https://github.com/ansible/ansible/tree/devel/test/units/modules/web_infrastructure)?

2018-12-13 12:42 UTC, Akasurde commented on lib/ansible/modules/web_infrastructure/sophos_utm/utm_aaa_group.py
> +short_description: create, update or destroy reverse_proxy frontend entry in Sophos UTM
I think this is wrong. Could you please check description of this again ? Thanks.

2018-12-13 12:42 UTC, Akasurde commented on lib/ansible/modules/web_infrastructure/sophos_utm/utm_aaa_group.py
> +          - The name of the object. Will be used to identify the entry
```suggestion
          - The name of the object. Will be used to identify the entry.
```

2018-12-13 12:42 UTC, Akasurde commented on lib/ansible/modules/web_infrastructure/sophos_utm/utm_aaa_group.py
> +          - list of adirectory group strings
```suggestion
          - list of adirectory group strings.
```

2018-12-13 12:42 UTC, Akasurde commented on lib/ansible/modules/web_infrastructure/sophos_utm/utm_aaa_group.py
> +          - list of adirectory group strings
Same for other description.

2018-12-13 14:37 UTC, getjack commented
@Akasurde What do you want me to test? The module calls the utm_utils module and behaves like a AnsibleModule that fails with fail_json in case of an exception.
That means the exception case should be covered by the AnsibleModule class and the UTMModule call will fail if the utm_module code is changed.

2018-12-13 15:34 UTC, getjack commented
Just noticed my PR is a duplicate to https://github.com/ansible/ansible/issues/48926

2019-01-24 10:24 UTC, getjack commented
@Akasurde Still need your feedback. @MatrixCrawler any idea regarding the unit test?

2019-01-31 04:18 UTC, Akasurde approved these changes
LGTM

2019-02-02 12:41 UTC, gundalow approved these changes

2019-02-02 12:41 UTC, merged

2019-02-02 12:41 UTC, gundalow commented
Thanks all, merged