Added Ansible UTM Info Module for managing reverse proxy profile entries info state
ansible/ansible pull request #49869
Opened 2018-12-13 09:32 UTC by getjack

##### SUMMARY
This PR will add a new utm info module which allows the management of reverse proxy profile entries of the Sophos UTM. This module integrates with the existing utm_utils .

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
- module/web_infrastructure/sophos_utm/utm_proxy_profile_info.py

2018-12-17 13:05 UTC, MatrixCrawler commented
shipit

2018-12-20 15:48 UTC, gundalow requested changes

2018-12-20 15:48 UTC, gundalow commented on lib/ansible/modules/web_infrastructure/sophos_utm/utm_proxy_profile_info.py
> +    - Stephan Schwarz (@stearz)
This should be your name

2019-01-24 10:20 UTC, getjack commented on lib/ansible/modules/web_infrastructure/sophos_utm/utm_proxy_profile_info.py
> +    - Stephan Schwarz (@stearz)
I'm not the author. This code was done by me working colleague so he deserves the honor. Just committed it to github for him.
@stearz Any opinion on that request?

2019-02-05 11:07 UTC, getjack commented
I am very sorry but i deleted the remote repo and i didn't check the PRs beforehand. Will redo the PRs and fix it. Sorry for the overhead :(

2019-02-05 11:07 UTC, closed without merging