Added Ansible UTM Module for managing network aaa entries.
ansible/ansible pull request #49863
Opened 2018-12-13 09:15 UTC by getjack

##### SUMMARY
This PR will add a new utm module which allows the management of network aaa entries of the Sophos UTM. This module integrates with the existing utm_utils .

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
- module/web_infrastructure/sophos_utm/utm_network_aaa.py

2018-12-13 20:01 UTC, MatrixCrawler commented
bot_status

2018-12-24 10:04 UTC, stearz approved these changes

2018-12-24 10:04 UTC, stearz commented
shipit

2019-01-11 11:28 UTC, gundalow requested changes

2019-01-11 11:28 UTC, gundalow commented on lib/ansible/modules/web_infrastructure/sophos_utm/utm_network_aaa.py
> +    - Stephan Schwarz (@stearz)
Please update this to your name

2019-01-12 12:26 UTC, stearz commented on lib/ansible/modules/web_infrastructure/sophos_utm/utm_network_aaa.py
> +    - Stephan Schwarz (@stearz)
Sorry? This is my name. What am I missing?

2019-01-24 10:22 UTC, getjack commented on lib/ansible/modules/web_infrastructure/sophos_utm/utm_network_aaa.py
> +    - Stephan Schwarz (@stearz)
Same as the other PR. stearz did the code but i commited it in his name so he is the author. We're working colleagues and i was reviewing the code.

2019-02-05 11:07 UTC, getjack commented
I am very sorry but i deleted the remote repo and i didn't check the PRs beforehand. Will redo the PRs and fix it. Sorry for the overhead :(

2019-02-05 11:07 UTC, closed without merging