Tested netbox_prefix.py and works as should
ansible/ansible pull request #49902
Opened 2018-12-13 18:34 UTC by FragmentedPacket

##### SUMMARY

This Netbox module allows for the creation and deletion of prefixes within Netbox

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

netbox_prefix.py

2018-12-13 19:34 UTC, FragmentedPacket commented
shipit

2018-12-14 21:06 UTC, FragmentedPacket commented
@gundalow Do you mind restarting the shippable tests?

2019-01-06 18:36 UTC, FragmentedPacket commented
@gundalow Hey John, do you mind having this merged? I had to make a few changes due to some changes with the method I'm using to fetch the data that will have to be fixed in the other modules as well.

2019-01-11 03:23 UTC, FragmentedPacket commented
@Anthony25 Hey! I reworked it to match your changes on netbox_device. Do you mind reviewing the changes and testing? My tests were successful, but want to have more testing until I can look into the proper way to test this.

2019-01-11 09:38 UTC, Anthony25 commented
@FragmentedPacket: Sure, thanks!
I will try to do it for today, or at least for monday ;)

2019-01-11 16:11 UTC, Anthony25 commented
@FragmentedPacket: I just had a few little comments regarding your changes, otherwise it seems great for me!
Thanks a lot for your changes

2019-01-14 12:51 UTC, FragmentedPacket commented
@Anthony25 You can post your comments here or I'm available on NTC slack or by email (mikhail.yohman at gmail.com)

2019-01-14 12:56 UTC, Anthony25 commented
Thanks, I already did in the review ;)

2019-01-14 13:09 UTC, FragmentedPacket commented
@Anthony25 I don't see any review on the PR?

2019-01-14 13:11 UTC, aruhier commented on lib/ansible/modules/net_tools/netbox/netbox_prefix.py
> +    return nb_endpoint.create(data)
Maybe if it's only one line to create a function (and the call is not really complicated), you can remove this function and use directly `nb_enpoint.create()` instead, like you do with `nb_endpoint.delete()`.

2019-01-14 13:11 UTC, aruhier commented on lib/ansible/modules/net_tools/netbox/netbox_prefix.py
> +    prefix_list = data["prefix"].split('/')
I would replace these 3 lines by:
```
# Add these imports
from ansible.module_utils.compat import ipaddress
from ansible.module_utils._text import to_text
###

prefix = ipaddress.ip_network(data["prefix"])
network = to_text(prefix.network_address)
mask = prefix.prefixlen
```

This way, it will not fail if `data["prefix"]` doesn't have a netmask (default it to /32 for ipv4, /128 for ipv6).

2019-01-14 13:11 UTC, aruhier commented on lib/ansible/modules/net_tools/netbox/netbox_prefix.py
> +    prefix_list = data["prefix"].split('/')
Or if you want your module to fail if the prefix sent as parameter doesn't have a netmask, you should handle the error.

2019-01-14 13:11 UTC, Anthony25 commented
Oh I'm really sorry, I didn't confirm the review!

Should be good now ;)

2019-01-16 01:51 UTC, FragmentedPacket commented
@Anthony25 Those changes were implemented and tested. Does it look good to merge now?

Were you going to submit the changes to `netbox_ip_address` with the new object creation in pynetbox?

2019-01-16 08:57 UTC, aruhier commented
Great, thanks for the changes!

Yes, I will. Probably today, but I have a quite busy schedule for this week.

2019-01-17 11:05 UTC, Anthony25 commented
@FragmentedPacket: I'm really sorry, I saw some issues in the `netbox_ip_address` module that I didn't saw here (but problems are quite the same), I'm going to do another review.

2019-01-25 19:09 UTC, Anthony25 commented
If you're interested, I can implement quite the same feature than what I did in #51006: I would need to get the next available prefix inside a prefix.

I don't know how exactly I will implement it, but I thought maybe using a `parent` attribute.

2019-01-30 17:50 UTC, Anthony25 commented
I thought about doing something like this:
```
      netbox_ip_address:
        netbox_url: http://netbox.local
        netbox_token: thisIsMyToken
        data:
          parent: 192.168.1.0/24
          size: 31
          vrf: Test
        state: present
        first_available: True
```
What would get a new available /31 in 192.168.1.0/24.

2019-02-06 12:50 UTC, Anthony25 commented
@FragmentedPacket: you can follow my work here: https://github.com/Anthony25/ansible/tree/netbox_prefix

I implemented what I wrote about earlier, tell me if it's looks good for you.

2019-02-06 13:10 UTC, Anthony25 commented
However I wanted to get your opinion about that: I thought about using a state `new` for this scenario, to be coherent with what I did with the ip_address module. However, a state `new` would not make any sense with anything else, as you cannot duplicate a prefix inside the same VRF. That's why I stayed with the state `present`, but I'm really open to comments.

2019-02-08 02:48 UTC, FragmentedPacket commented
It probably makes sense on this one to do what you were using
earlier:`first_available`.

It doesn't look quite all the way completed on your branch for this, but
once you complete it, I'll review it and update my testing playbook to make
sure everything is working as it should.

On Wed, Feb 6, 2019 at 6:11 AM Anthony Ruhier <notifications@github.com>
wrote:

> However I wanted to get your opinion about that: I thought about using a
> state new for this scenario, to be coherent with what I did with the
> ip_address module. However, a state new would not make any sense with
> anything else, as you cannot duplicate a prefix inside the same VRF. That's
> why I stayed with the state present, but I'm really open to comments.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ansible/ansible/pull/49902#issuecomment-461017335>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/Ab9PuhcKzx8gMM42d7GmgLzmEtyoXVMaks5vKtSCgaJpZM4ZSMBj>
> .
>

2019-02-16 11:06 UTC, Anthony25 commented
Sorry for the delay, will do today!

2019-02-21 21:18 UTC, FragmentedPacket commented
@Anthony25 How's it going?

2019-02-28 00:11 UTC, Anthony25 commented
Really sorry, tomorrow should be good.

2019-03-01 00:16 UTC, Anthony25 commented
@FragmentedPacket: I pushed my change, will try to test it correctly tomorrow.

2019-03-01 05:00 UTC, FragmentedPacket commented
@Anthony25 I changed `size` to `prefix_length` as that is what is expected when creating the prefix within `available_prefixes`. This also allows people to add more fields like creating prefix (role, vrf, site, etc.).

2019-03-01 09:38 UTC, Anthony25 commented
@FragmentedPacket Great, thanks!

2019-03-01 16:44 UTC, FragmentedPacket commented
@Anthony25 Do you mind reviewing it and letting me know if everything looks good?

2019-03-02 12:14 UTC, aruhier commented on lib/ansible/modules/net_tools/netbox/netbox_prefix.py
> +            data["prefix"] += "/%s" % data["prefix_length"]
Sorry, I know it was in my changes, but I forgot to remove that line…
Changing the data seems a bit ugly here, could you remove this line and changing the next one by:
```
prefix = ipaddress.ip_network(data["prefix"] + "/" + data["prefix_length"])
```

2019-03-02 12:16 UTC, Anthony25 commented
LGTM, thanks to merge and fix my bugs

2019-03-02 16:39 UTC, FragmentedPacket commented on lib/ansible/modules/net_tools/netbox/netbox_prefix.py
> +            data["prefix"] += "/%s" % data["prefix_length"]
Added changes. I did change the following:
`prefix = ipaddress.ip_network(data["prefix"])`

The examples show to have the prefix defined on `prefix:` and the `prefix_length` is only used with `parent`. Documents should reflect this as well.

2019-03-04 19:16 UTC, gundalow reviewed
Please see review comments on your other PRs

2019-03-04 19:16 UTC, gundalow commented on lib/ansible/modules/net_tools/netbox/netbox_prefix.py
> +version_added: "2.8"
```suggestion
version_added: '2.8'
```

2019-03-04 21:36 UTC, FragmentedPacket commented on lib/ansible/modules/net_tools/netbox/netbox_prefix.py
> +version_added: "2.8"
Add types and changed this!

2019-03-06 15:05 UTC, NilashishC requested changes
@FragmentedPacket Could you please add some unit tests for this new module?

2019-03-18 02:21 UTC, FragmentedPacket reviewed
Tests were added on PR #53631 - These should cover the refactor I just did.

If those are good, could we get this merged after #53631 ?

2019-03-20 14:40 UTC, FragmentedPacket commented
@NilashishC I just wanted to follow up on this. We ended up moving the creation/deletion parts into netbox_utils and there are some tests written for those. Does everything look good to merge after the referenced PR above?

2019-03-25 07:43 UTC, NilashishC commented
@FragmentedPacket The approach looks fine to me. I have added some minor comments to #53631.

2019-03-26 06:48 UTC, NilashishC approved these changes

2019-04-02 19:21 UTC, FragmentedPacket commented
shipit

2019-04-03 12:36 UTC, gundalow approved these changes

2019-04-03 12:45 UTC, NilashishC commented
rebuild_merge

2019-04-03 15:35 UTC, FragmentedPacket commented
I'm not sure how I closed this PR. Can we reopen it? @NilashishC

2019-04-03 16:54 UTC, FragmentedPacket commented
shipit

2019-04-03 16:55 UTC, FragmentedPacket commented
@NilashishC I've got everything squared away now!

2019-04-03 16:59 UTC, merged