Do not load user kube config if path specified
ansible/ansible pull request #49952
Opened 2018-12-14 15:59 UTC by AlanCoding

##### SUMMARY
The existing inventory plugins for k8s will create a `client` object with default parameters before using the parameters specified in the inventory file.

That is a major problem if anyone using this ever intends to save their kube config somewhere other than the default location - because this caused it to fail on trying to read from the default location.

Doing this is unnecessary, so the duplication creation of the `client` object is removed here.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/plugins/inventory/openshift.py
lib/ansible/plugins/inventory/k8s.py

##### ADDITIONAL INFORMATION
Walking through reproduction of issue:

 - do `oc login <host>`
 - `cp ~/.kube/config ./mai_config`
 - `rm -rf ~/.kube/`
 - `ansible-inventory -i openshift.yml --list` with the following inventory:

```yaml
plugin: openshift
connections:
    - host: https://<my host>:8443
      kubeconfig: mai_config
      verify_ssl: false
      namespaces:
        - <my namespace>
```

Running that before this fix produces:

```paste below
 [WARNING]:  * Failed to parse /Users/alancoding/Documents/repos/tower-qa/openshift.yml with auto plugin: [Errno 2] No such file or directory: '/Users/alancoding/.kube/config'

  File "/Users/alancoding/.virtualenvs/tower-qa/lib/python2.7/site-packages/ansible/inventory/manager.py", line 267, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/Users/alancoding/.virtualenvs/tower-qa/lib/python2.7/site-packages/ansible/plugins/inventory/auto.py", line 55, in parse
    plugin.parse(inventory, loader, path, cache=cache)
  File "/Users/alancoding/.virtualenvs/tower-qa/lib/python2.7/site-packages/ansible/plugins/inventory/k8s.py", line 147, in parse
    self.setup(config_data, cache, cache_key)
  File "/Users/alancoding/.virtualenvs/tower-qa/lib/python2.7/site-packages/ansible/plugins/inventory/k8s.py", line 165, in setup
    self.fetch_objects(connections)
  File "/Users/alancoding/.virtualenvs/tower-qa/lib/python2.7/site-packages/ansible/plugins/inventory/openshift.py", line 126, in fetch_objects
    client = self.get_api_client()
  File "/Users/alancoding/.virtualenvs/tower-qa/lib/python2.7/site-packages/ansible/module_utils/k8s/common.py", line 164, in get_api_client
    kubernetes.config.load_kube_config(auth.get('kubeconfig'), auth.get('context'))
  File "/Users/alancoding/.virtualenvs/tower-qa/lib/python2.7/site-packages/kubernetes/config/kube_config.py", line 521, in load_kube_config
    config_persister=config_persister)
  File "/Users/alancoding/.virtualenvs/tower-qa/lib/python2.7/site-packages/kubernetes/config/kube_config.py", line 478, in _get_kube_config_loader_for_yaml_file
    with open(filename) as f:
```

(some line numbers might be a little off)

With this fix, the inventory content will get returned.

Note: this seems to _not_ fix username/password or token authentication, but I believe it gets us closer. See https://github.com/openshift/openshift-restclient-python/issues/249 for more on that.

2018-12-17 19:45 UTC, fabianvf commented
Good catch,

shipit

2018-12-17 21:32 UTC, maxamillion commented
shipit

2018-12-19 19:08 UTC, fabianvf commented
bot_status

2018-12-20 11:50 UTC, gundalow requested changes
Can we please get a changelog/fragment for this then we can merge and backport

2019-01-03 15:06 UTC, fabianvf commented
shipit

2019-01-11 16:33 UTC, AlanCoding commented
ready_for_review

2019-01-11 17:26 UTC, gundalow approved these changes

2019-01-11 17:26 UTC, merged

2019-01-11 17:27 UTC, gundalow commented
Merged into devel, thanks.
If you'd like this in 2.7 please raise a backport PR.