Put in documented default for gcp_compute filters
ansible/ansible pull request #50025
Opened 2018-12-17 15:14 UTC by AlanCoding

##### SUMMARY
The plugin documentation claims that this field has a default, but it will not work without adding a field in the inventory file.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/plugins/inventory/gcp_compute.py

##### ADDITIONAL INFORMATION
Previously, inventory files of this type would fail with a KeyError (surfaced confusingly)

```yaml
plugin: gcp_compute
zones:
  - us-east1-d
projects:
  - foo-bar-foo
service_account_file: example_gce/creds.json
auth_kind: serviceaccount
```

the docs from `ansible-doc -t inventory gcp_compute` give the following:

```
- filters
        A list of filter value pairs. Available filters are listed here
        https://cloud.google.com/compute/docs/reference/rest/v1/instances/list. Each additional filter in the list will act be added
        as an AND condition (filter1 and filter2)
        [Default: (null)]
```

If the default is null, then I expect that the user does not need to provide it to avoid errors. That's the point of having defaults.

2018-12-19 10:00 UTC, gundalow requested changes
Could you please add a changelog/fragment file https://docs.ansible.com/ansible/devel/community/development_process.html#making-your-pr-merge-worthy

2019-01-03 19:52 UTC, AlanCoding commented
example here could use to be updated:

https://github.com/ansible/ansible/blob/31309b84198db8841e5135eda36472d44b72236f/docs/docsite/rst/scenario_guides/guide_gce.rst

```yaml
plugin: gcp_compute
projects:
  - graphite-playground
filters:
auth_kind: serviceaccount
service_account_file: /home/alexstephen/my_account.json
```

2019-01-11 16:33 UTC, AlanCoding commented
ready_for_review

2019-01-18 11:39 UTC, gundalow approved these changes

2019-01-18 11:39 UTC, merged

2019-01-18 11:40 UTC, gundalow commented
Thanks, merged into `devel` for release in Ansible 2.8.
If you think this would be good in 2.7 please raise a backport PR.