#47654 Adds a new `constraints` parameter to pip command
ansible/ansible pull request #50092
Opened 2018-12-18 14:14 UTC by frague59

##### SUMMARY
Adds the `constraints` argument to the pip packaging command

Fixes #47654

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
pip

##### ADDITIONAL INFORMATION
Adds a new parameter for the pip command: constraints

```yml
- name: Installs requirements with constraints
  pip:
    requirements: requirements.txt
    constraints: constraints.txt
```

2018-12-18 21:18 UTC, sivel requested changes
In addition to other changes listed here, please:

1. rebase to remove the merge commits
1. add tests for this functionality
1. add a changelog fragment to `changelog/fragments`

2018-12-18 21:18 UTC, sivel commented on lib/ansible/modules/packaging/language/pip.py
> +from ansible.module_utils.six import PY3
These imports need to be moved back to where they were.  As you can see moving it has caused CI to fail.

2018-12-18 21:18 UTC, sivel commented on lib/ansible/modules/packaging/language/pip.py
> +        File can be specified as a relative path if using the chdir option.
Need `version_added: "2.8"` here

2018-12-18 21:18 UTC, sivel commented on lib/ansible/modules/packaging/language/pip.py
> +            constraints=dict(type='str'),
arguments pointing to a file should use `type='path'`.

2018-12-18 21:18 UTC, sivel commented on lib/ansible/modules/packaging/language/pip.py
> +            if constraints:
constraints isn't dependent on requirements.  constraints can still be useful if the libraries being installed are liberal in their selection.

This should be moved outside.

2018-12-18 21:18 UTC, sivel commented on lib/ansible/modules/packaging/language/pip.py
> +        if constraints:
There is no reason to make this conditional.  We don't do this for `requirements` don't do it here too.  Just use a single `module.exit_json`

2020-06-26 15:33 UTC, samdoran commented
Closing due to inactivity.

2020-06-26 15:33 UTC, closed without merging