Pluribus Networks pn_dscp_map_pri_map module with Unit tests
ansible/ansible pull request #50142
Opened 2018-12-19 11:51 UTC by rajaspachipulusu17

##### SUMMARY

Point feature of dscp map pri map for Pluribus Networks Netvisor switches 

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME
pn_dscp_map_pri_map.py module with unit tests.

##### ADDITIONAL INFORMATION
ansible 2.4.0.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

```

2018-12-19 20:32 UTC, mattclay commented
CI failure in unit tests: https://app.shippable.com/github/ansible/ansible/runs/99187/9/tests

2018-12-19 20:36 UTC, mattclay commented on test/units/modules/network/netvisor/test_pn_dscp_map_pri_map.py
> +from ansible.modules.network.netvisor import pn_dhcp_map_pri_map
Typo, this looks like it should be `pn_dscp_map_pri_map` here and in several places below.

2018-12-24 05:39 UTC, rajaspachipulusu17 commented
@Akasurde can you merge this?

Thanks,
Rajas

2018-12-24 06:06 UTC, Akasurde requested changes
Rest LGTM

2018-12-24 06:06 UTC, Akasurde commented on lib/ansible/modules/network/netvisor/pn_dscp_map_pri_map.py
> +      - State the action to perform. Use 'update' to modify
```suggestion
      - State the action to perform. Use C(update) to modify
```

2018-12-24 06:06 UTC, Akasurde commented on lib/ansible/modules/network/netvisor/pn_dscp_map_pri_map.py
> +      - State the action to perform. Use 'update' to modify
Apply this to rest of modules too.

2018-12-24 06:21 UTC, rajaspachipulusu17 commented on lib/ansible/modules/network/netvisor/pn_dscp_map_pri_map.py
> +      - State the action to perform. Use 'update' to modify
I have somehow missed it. I will apply to future modules. 

Thanks,
Rajas

2018-12-24 07:07 UTC, rajaspachipulusu17 commented
Can you merge now @Akasurde ?

2018-12-24 08:13 UTC, Akasurde requested changes

2018-12-24 08:13 UTC, Akasurde commented on test/units/modules/network/netvisor/test_pn_dscp_map_pri_map.py
> +    def test_dhcp_map_pri_map_t1(self):
```suggestion
    def test_dscp_map_pri_map_t1(self):
```

2018-12-24 08:13 UTC, Akasurde commented on test/units/modules/network/netvisor/test_pn_dscp_map_pri_map.py
> +    def test_dhcp_map_pri_map_t2(self):
```suggestion
    def test_dscp_map_pri_map_t2(self):
```

2018-12-24 08:13 UTC, Akasurde commented on test/units/modules/network/netvisor/test_pn_dscp_map_pri_map.py
> +    def test_dhcp_map_pri_map_t3(self):
```suggestion
    def test_dscp_map_pri_map_t3(self):
```

2018-12-24 08:13 UTC, Akasurde commented on test/units/modules/network/netvisor/test_pn_dscp_map_pri_map.py
> +        self.mock_run_nvos_commands.stop()
```suggestion
        self.mock_run_nvos_commands.stop()
        self.mock_run_check_cli.stop()
```

2018-12-24 09:07 UTC, rajaspachipulusu17 commented on test/units/modules/network/netvisor/test_pn_dscp_map_pri_map.py
> +        self.mock_run_nvos_commands.stop()
Committed it.

2018-12-25 03:38 UTC, Akasurde approved these changes

2018-12-26 05:46 UTC, rajaspachipulusu17 commented
@Akasurde can you merge this?

2019-01-07 04:18 UTC, rajaspachipulusu17 commented
@Akasurde can you merge this?

Thanks,
Rajas

2019-01-08 16:49 UTC, rajaspachipulusu17 commented
Can someone merge? its been quite some time now.

Thanks,
Rajas

2019-01-09 09:42 UTC, rajaspachipulusu17 commented
@Akasurde can you merge this?

2019-01-10 07:21 UTC, merged