Doc frag plugins
ansible/ansible pull request #50172
Opened 2018-12-19 22:54 UTC by bcoca

promote doc fragments to full fledged plugins

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

doc fragments

2019-01-11 20:20 UTC, mattclay reviewed
Also need to update: https://github.com/ansible/ansible/blob/fd56788a142efde6b24553978906d43d2d4ea771/test/runner/lib/classification.py#L520

2019-01-11 20:20 UTC, mattclay commented on test/runner/lib/sanity/ansible_doc.py
> +        # TODO: use documentable plugins from contsants instead
Typo:

```suggestion
        # TODO: use documentable plugins from constants instead
```

2019-01-11 20:21 UTC, mattclay commented
@bcoca Should this PR be marked `WIP`?

2019-01-11 20:24 UTC, mattclay commented
Another path to update:

https://github.com/ansible/ansible/blob/fd56788a142efde6b24553978906d43d2d4ea771/test/runner/lib/sanity/yamllint.py#L47

2019-01-11 20:56 UTC, bcoca commented
@mattclay nope, i just didnt realize soo many things hardcoded the path to doc fragments

2019-01-12 08:30 UTC, gundalow requested changes
For my understanding, what are the benefits of this over the current implementation? 

1) `docs/rst/` has lots of references to the fragments directory which need updating in this PR

2) I wonder of this neecsyadfing to the developer section of the Porting guide? 

3) Once merged this needs announcing https://github.com/ansible/community/issues/346

4) After merge need to review all PRs which add/update fragments

2019-01-14 16:21 UTC, bcoca commented
Two main changes, we put doc_fragments under the same umbrella as other plugins (easier to deal with less exceptions) AND we allow for user provided doc_fragments, currently module/plugin authors must repeat all their docs when providing modules or are required to commit to ansible/ansible to make them available.

1. I'll have to update those
2. Yes
3. of course
4. ????

2019-01-18 06:38 UTC, webknjaz commented on lib/ansible/config/base.yml
> +  env: [{name: ANSIBLE_DOC_FRAGMENT_PLUGINS}]
Could you please use native YAML syntax and do multi-line?

2019-01-18 06:39 UTC, webknjaz commented on lib/ansible/config/base.yml
> +  - {key: doc_fragment_plugins, section: defaults}
Multi-line would look better here as well

2019-01-23 21:12 UTC, bcoca commented
bot_status

2019-01-23 21:56 UTC, nitzmahone approved these changes

2019-01-24 01:03 UTC, merged