added timestamps to nxos_command module
ansible/ansible pull request #50261
Opened 2018-12-21 20:39 UTC by vaneuk

nxos_command module now returns timestamps field, which shows command execution time

##### SUMMARY

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

nxos_command

##### ADDITIONAL INFORMATION
**before**
```
ok: [nexus9k-1] => {
    "output": {
        "changed": false, 
        "failed": false, 
        "stdout": [
            "23:23:02.257 MSK Fri Dec 21 2018\nTime source is NTP", 
            "n9k-1"
        ], 
        "stdout_lines": [
            [
                "23:23:02.257 MSK Fri Dec 21 2018", 
                "Time source is NTP"
            ], 
            [
                "n9k-1"
            ]
        ]
    }
}
```

**after**
```	
ok: [nexus9k-1] => {
    "output": {
        "changed": false, 
        "failed": false, 
        "stdout": [
            "23:17:33.679 MSK Fri Dec 21 2018\nTime source is NTP", 
            "n9k-1"
        ], 
        "stdout_lines": [
            [
                "23:17:33.679 MSK Fri Dec 21 2018", 
                "Time source is NTP"
            ], 
            [
                "n9k-1"
            ]
        ], 
        "timestamps": [
            "2018-12-21T23:17:33", 
            "2018-12-21T23:17:33"
        ]
    }
}
```

**before (tranposrt nx-api)**
```
ok: [nexus9k-1] => {
    "output": {
        "changed": false, 
        "deprecations": [
            {
                "msg": "Param 'transport' is deprecated. See the module docs for more information", 
                "version": 2.9
            }
        ], 
        "failed": false, 
        "stdout": [
            {
                "simple_time": "23:23:16.577 MSK Fri Dec 21 2018\n"
            }, 
            {
                "hostname": "n9k-1"
            }
        ], 
        "stdout_lines": [
            {
                "simple_time": "23:23:16.577 MSK Fri Dec 21 2018\n"
            }, 
            {
                "hostname": "n9k-1"
            }
        ]
    }
}
```
**after (tranposrt nx-api)**
```
ok: [nexus9k-1] => {
    "output": {
        "changed": false, 
        "deprecations": [
            {
                "msg": "Param 'transport' is deprecated. See the module docs for more information", 
                "version": 2.9
            }
        ], 
        "failed": false, 
        "stdout": [
            {
                "simple_time": "23:18:39.082 MSK Fri Dec 21 2018\n"
            }, 
            {
                "hostname": "n9k-1"
            }
        ], 
        "stdout_lines": [
            {
                "simple_time": "23:18:39.082 MSK Fri Dec 21 2018\n"
            }, 
            {
                "hostname": "n9k-1"
            }
        ], 
        "timestamps": [
            "2018-12-21T23:18:38", 
            "2018-12-21T23:18:38"
        ]
    }
}
```

2018-12-22 01:12 UTC, mattclay commented on lib/ansible/module_utils/basic.py
> +from datetime import datetime
This conflicts with the `import datetime` above.

2018-12-23 10:21 UTC, vaneuk commented on lib/ansible/module_utils/basic.py
> +from datetime import datetime
thanks, fixed

2019-01-09 15:11 UTC, trishnaguha approved these changes

2019-01-09 15:33 UTC, trishnaguha requested changes
this can be done in module level without going all the way through cliconf and module_utils

2019-01-15 18:01 UTC, vaneuk commented
> this can be done in module level without going all the way through cliconf and module_utils

could you elaborate on this? I believe this is the only way to do this. Short discussion regarding the same was held in https://github.com/ansible/ansible/pull/50323

2019-01-16 03:30 UTC, trishnaguha commented
@vaneuk ah got it. Would you mind explaining the use case of it please?

2019-01-16 08:46 UTC, vaneuk commented
@trishnaguha I have a playbook, which collects several commands from ~1k devices, playbook takes ~20 minutes to complete. Output of some commands is used for monitoring purposes and it is crucial to know exact time of command collection. 
Without this enchancement the only way to know command collection time is to register output, save it fo file and rely on file creation time. But it does not give seconds precision - for example If there are 10 commands and each command collection takes 5 seconds, then file will be created 50 seconds after first command actual collection time.
With this enchancement there is a way to know at what exact time each command from each device was collected.

2019-01-16 12:28 UTC, trishnaguha approved these changes

2019-01-16 14:13 UTC, Qalthos approved these changes

2019-01-17 04:44 UTC, merged

2019-01-17 04:44 UTC, trishnaguha commented
Thanks for the PR @vaneuk

2019-05-08 07:14 UTC, trishnaguha commented
Reverted by https://github.com/ansible/ansible/pull/56206