Feat/rundeck key storage
ansible/ansible pull request #50453
Opened 2019-01-02 15:31 UTC by aminx4

##### SUMMARY
Create a new module for using Rundeck API Key Storage

- New Module Pull Request

##### COMPONENT NAME
rundeck_key_storage

2019-01-03 11:00 UTC, nerzhul requested changes
A little change, algorithm seems good but not tested

2019-01-03 11:00 UTC, nerzhul commented on lib/ansible/modules/web_infrastructure/rundeck_key_storage.py
> +        if self.module.params["type"] == "public_key":
elif on each condition :) this will not change

2019-01-03 11:11 UTC, aminx4 commented on lib/ansible/modules/web_infrastructure/rundeck_key_storage.py
> +        if self.module.params["type"] == "public_key":
it's done 👍 thank you.

2019-01-03 15:45 UTC, aminx4 commented on lib/ansible/modules/web_infrastructure/rundeck_key_storage.py
> +        if self.module.params["type"] == "public_key":
@nerzhul 
Can you please give me an exemple of unit test to add it please, i'm trying to find unit test for rundeck_project and rundeck_acl_policy modules but i can't find them. 

thank you for your help 👍

2019-01-03 15:50 UTC, nerzhul commented on lib/ansible/modules/web_infrastructure/rundeck_key_storage.py
> +        if self.module.params["type"] == "public_key":
yeah unittests are not really applicable on rundeck modules because we need a working rundeck instance. @gundalow do you got some ideas ?

2019-01-03 16:09 UTC, aminx4 commented on lib/ansible/modules/web_infrastructure/rundeck_key_storage.py
> +        if self.module.params["type"] == "public_key":
@nerzhul Normally we can mock the calls to rundeck webservices, i'm not a python developper but i think there is a way to do it 👍

2019-01-07 10:03 UTC, aminx4 commented on lib/ansible/modules/web_infrastructure/rundeck_key_storage.py
> +        if self.module.params["type"] == "public_key":
@gundalow Hello :) any ideas ?

2019-01-17 15:05 UTC, aminx4 commented on lib/ansible/modules/web_infrastructure/rundeck_key_storage.py
> +        if self.module.params["type"] == "public_key":
@AlanCoding @MatrixCrawler @Slezhuk @agmezr @berendt @fleu42 @getjack @ghjm @hogarthj @inetfuture @jainnikhil30 @jhoekx @jlaska @jtyr @lekum @matburt @mattupstate @n0trax @nerzhul @oboukili @ramondelafuente @robinro @rooftopcellist @ryanpetrello @scottanderson42 @sermilrod @simfarm @stearz @stpierre @tarka @tastychutney @wbrefvem @wwitzel3 

This PR will be merged or not ? any ideas to improve testing ? thank you.

2019-08-22 09:41 UTC, aminx4 commented
Hello can you tell me why the PR is not merged thank you

2019-08-22 11:43 UTC, jtyr commented
@aminx4 You have to take your PR through the [Public Ansible Project Meeting](https://github.com/ansible/community/issues/482).

2020-08-16 11:38 UTC, closed without merging