na_ontap_dns: Add new parameter skip_validation
ansible/ansible pull request #50458
Opened 2019-01-02 17:22 UTC by albinpopote

##### SUMMARY

Add skip_validation parameter to bypass the DNS configuration check on the Netapp Ontap. Refers to the skip-config-validation parameter on the SDK.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

na_ontap_dns

##### ADDITIONAL INFORMATION

Tested on FAS8200 with DOT 9.4 with DNS and domain not reachabled (Create and Modify): OK

```paste below

```

2019-01-02 21:21 UTC, lonico requested changes

2019-01-02 21:21 UTC, lonico commented on lib/ansible/modules/storage/netapp/na_ontap_dns.py
> +    - If set to "TRUE", this option bypass the DNS check on the Ontap.
I would prefer 'true', actually C(true).

2019-01-02 21:21 UTC, lonico commented on lib/ansible/modules/storage/netapp/na_ontap_dns.py
> +        skip_validation: yes
should be true rather than yes

2019-01-07 21:07 UTC, lonico approved these changes

2019-01-07 21:07 UTC, lonico commented on lib/ansible/modules/storage/netapp/na_ontap_dns.py
> +    - If set to 'true', this option bypass the DNS check on the Ontap.
should be ONTAP

2019-02-08 15:10 UTC, gundalow requested changes
@albinpopote Look good, could you just make the two minor changes that @lonico has suggested then we can merged

2019-02-15 02:17 UTC, lonico approved these changes
shipit

2019-03-07 15:18 UTC, thedoubl3j commented
ping @albinpopote if you could address @lonico requests, we can start moving this forward after that :)

2019-03-11 14:43 UTC, gundalow commented on lib/ansible/modules/storage/netapp/na_ontap_dns.py
> +    - If set to 'true', this option bypass the DNS check on the ONTAP.
Would end users know when they should use this setting?

2019-03-12 09:53 UTC, albinpopote commented on lib/ansible/modules/storage/netapp/na_ontap_dns.py
> +    - If set to 'true', this option bypass the DNS check on the ONTAP.
I added more details about the option. Personnally, as the end user, I find the option name sufficiently explicit

2019-03-13 16:19 UTC, lonico approved these changes
shipit

2019-03-13 16:19 UTC, lonico commented on lib/ansible/modules/storage/netapp/na_ontap_dns.py
> +    - If you DNS servers are not yet installed or momentarily not available, you can set this option to 'true'
nitpick: you --> your

2019-03-13 16:22 UTC, carchi8py approved these changes
Shipit

2019-03-13 18:28 UTC, gundalow commented on lib/ansible/modules/storage/netapp/na_ontap_dns.py
> +    - If you DNS servers are not yet installed or momentarily not available, you can set this option to 'true'
```suggestion
    - If your DNS servers are not yet installed or momentarily not available, you can set this option to I(true).
```

2019-03-13 18:29 UTC, gundalow approved these changes

2019-03-13 18:29 UTC, merged

2019-03-13 18:29 UTC, gundalow commented on lib/ansible/modules/storage/netapp/na_ontap_dns.py
> +    - If you DNS servers are not yet installed or momentarily not available, you can set this option to 'true'
Apparently, I don't have permissions to push to your branch. I didn't want to hold up merge. Feel free to raise a PR to fix this if you'd like, though don't lose sleep over it