playbooks_intro: idempotence
ansible/ansible pull request #50506
Opened 2019-01-03 17:04 UTC by Alexis-benoist

+label: docsite_pr

##### SUMMARY
I changed the playbook doc.
If a set of actions are idempotent independently, 
then the actions are idempotent as a group.

If I'm wrong, could you guys explain to me?

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
playbooks_intro doc

2019-01-05 17:59 UTC, jamescassell requested changes
Modules could very well conflict in their changes, breaking idempotence.

2019-01-05 21:57 UTC, Alexis-benoist commented
Do you have an example?

2019-01-09 17:17 UTC, acozine commented
Thanks @Alexis-benoist for your interest in the Ansible documentation, and for opening a PR. I don't have a good example to prove that your suggested change is not true. However, I do think it would make an implicit promise we can't keep - a promise that running the same playbook twice in a row won't leave users with a broken system. 

If we leave "is likely to" and "should" in the description, we encourage everyone to think about what their playbooks are doing, and to test the results of running them multiple times (preferably not on production systems). I think a little hedging is a good thing in this case, especially when we use the word "safe."

2019-01-23 19:43 UTC, acozine commented
I'm going to close this PR - thanks again @Alexis-benoist for submitting this change, but we would like to encourage all users to think about the effects of running their playbooks multiple times, by leaving some wiggle room in the documentation about idempotency.

2019-01-23 19:43 UTC, closed without merging