assert: change AnsibleError to warning
ansible/ansible pull request #50531
Opened 2019-01-04 06:56 UTC by Akasurde

##### SUMMARY
assert checks for string value for msg, failed_msg from Ansible 2.7 version.
As it is core module, this change should go through proper deprecation cycle
to avoid regression.

Fixes: #48547

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
changelogs/fragments/48547-assert-incorrect_msg_type.yml
lib/ansible/plugins/action/assert.py

2019-01-08 21:29 UTC, bcoca requested changes
this was my bad and i should have caught in review of the pr that created the problem.

the solution would be to allow for string or list of strings, not deprecate the latter

2019-01-09 16:21 UTC, Akasurde commented
@bcoca Could you please take another look into this ? Thanks in advance.

2019-01-09 16:51 UTC, bcoca commented on lib/ansible/plugins/action/assert.py
> +            raise AnsibleError('Incorrect type for fail_msg or msg, expected a string or list and got %s' % type(fail_msg))
i would check that all list elements are strings at that point

2019-03-04 18:39 UTC, bcoca approved these changes

2019-03-05 05:42 UTC, merged