Added new vmware module for gathering facts for DRS groups
ansible/ansible pull request #50649
Opened 2019-01-08 13:02 UTC by karstenjakobsen

##### SUMMARY
New module to gather information about DRS VM/Host groups in a given cluster. 

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
vmware_drs_group_facts

##### ADDITIONAL INFORMATION
This module complements ```vmware_drs_group``` and ```vmware_vm_host_drs_rule```

2019-01-10 08:50 UTC, Akasurde approved these changes
LGTM

2019-01-10 08:51 UTC, Akasurde commented
@pdellaert @dericcrago @Im0 @tchernomax @ckotte @jeking3 Could you please review this ?

2019-01-11 10:29 UTC, pdellaert requested changes
Great module! I like the structure, code style is nice (some whitespace might not be necessary, but that's just a silly personal preference :)).

One suggestion to optimize performance a bit in large environments.

2019-01-11 10:29 UTC, pdellaert commented on lib/ansible/modules/cloud/vmware/vmware_drs_group_facts.py
> +        if datacenter_name:
Coming back to my other comment: With this code, if both `datacenter` and `cluster_name` is set, it will end up looping through the DC (which could have a lot of clusters, and take unnecessary time) to just discard all that info... 

It would be nice if there is a `required_one_of` and a `mutually_exclusive` in the module signature, in which case this unnecessary time would not be needed.

2019-01-11 10:29 UTC, pdellaert commented on lib/ansible/modules/cloud/vmware/vmware_drs_group_facts.py
> +        supports_check_mode=True,
What happens if both `cluster_name` and `datacenter` is set? Should there be a `required_one_of` added here, and a `mutually_exclusive`?
```suggestion
        supports_check_mode=True,
        required_one_of=[['cluster_name', 'datacenter']],
        mutually_exclusive=[['cluster_name', 'datacenter']],
```

2019-01-11 12:47 UTC, karstenjakobsen commented on lib/ansible/modules/cloud/vmware/vmware_drs_group_facts.py
> +        supports_check_mode=True,
You are absolutely right. No need for `cluster_name` if `datacenter` is set.

2019-01-11 13:01 UTC, pdellaert approved these changes
LGTM!

2019-01-14 16:26 UTC, merged