VMware: New module vmware_drs_group
ansible/ansible pull request #50650
Opened 2019-01-08 13:08 UTC by karstenjakobsen

##### SUMMARY
New module to gather information about DRS VM/Host groups in a given cluster. 

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
vmware_drs_group

##### ADDITIONAL INFORMATION
This module complements:
```vmware_drs_group_facts``` https://github.com/ansible/ansible/pull/50649
```vmware_vm_host_drs_rule```

2019-01-10 07:34 UTC, Akasurde requested changes
Rest LGTM

2019-01-10 07:34 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_drs_group.py
> +  - "This module can be used to create VM/Host groups in a given cluster. Creates a vm group if C(vms) is set. Creates host group if C(hosts) is set"
```suggestion
  - "This module can be used to create VM/Host groups in a given cluster. Creates a vm group if C(vms) is set. Creates a host group if C(hosts) is set."
```

2019-01-10 07:34 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_drs_group.py
> +      - "Cluster to create vm/host group"
```suggestion
      - "Cluster to create vm/host group."
```

2019-01-10 07:34 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_drs_group.py
> +        self.__msg = "Created host group %s successfully" % (self.__group_name)
Change message according to the operation specified.

2019-01-10 07:34 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_drs_group.py
> +        self.__msg = "Created vm group %s successfully" % (self.__group_name)
Same as host group, change message according to the operation specified.

2019-01-10 07:34 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_drs_group.py
> +        self.__msg = "Delete group %s successfully" % (self.__group_name)
May want to show message for already deleted or non-existent rule.

2019-01-10 07:34 UTC, Akasurde commented on test/integration/targets/vmware_drs_group/tasks/main.yml
> +# Test code for the vmware_drs_group_facts module
```suggestion
# Test code for the vmware_drs_group module
```

2019-01-10 07:34 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_drs_group.py
> +      - DC0_C0_H2
Add an example of Delete operation

2019-01-10 07:34 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_drs_group.py
> +        self.__msg = "Created host group %s successfully" % (self.__group_name)
Also, update result if Host group already exists.

2019-01-10 07:34 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_drs_group.py
> +        self.__msg = "Created vm group %s successfully" % (self.__group_name)
Update VM group details in results for already existing VM groups.

2019-01-10 07:47 UTC, Akasurde commented
@karstenjakobsen Thanks for the PR.

2019-01-10 10:05 UTC, karstenjakobsen commented
Added new review changes - please let me know if anything else is missing :)

2019-01-10 11:06 UTC, Akasurde approved these changes

2019-01-10 11:06 UTC, Akasurde commented
@pdellaert @dericcrago @Im0 @tchernomax @ckotte @jeking3 Could you please review this ?

2019-01-11 11:03 UTC, pdellaert requested changes
I like the new module, it is a great addition and functionality! Thanks :)

Added some remarks and suggestions below

I do think that there is room for optimization when it comes to making API calls into vCenter... pyvmomi in combination with the vCenter SOAP API is not known to be speedy, every extra API call comes at a big cost. Anything you can do to optimize, limit and minimize those calls is always a very good thing.

2019-01-11 11:03 UTC, pdellaert commented on lib/ansible/modules/cloud/vmware/vmware_drs_group.py
> +  state: absent
`state` should be in the module parameters
```suggestion
  vmware_drs_group:
      state: absent
```

2019-01-11 11:03 UTC, pdellaert commented on lib/ansible/modules/cloud/vmware/vmware_drs_group.py
> +  state: present
`state` should be in the module parameters
```suggestion
  vmware_drs_group:
      state: present
```

2019-01-11 11:03 UTC, pdellaert commented on lib/ansible/modules/cloud/vmware/vmware_drs_group.py
> +  state: present
`state` should be in the module parameters
```suggestion
  vmware_drs_group:
      state: present
```

2019-01-11 11:03 UTC, pdellaert commented on lib/ansible/modules/cloud/vmware/vmware_drs_group.py
> +                raise Exception("Datacenter '%s' not found" % self.__datacenter_name)
Raising exceptions in Ansible modules is not allowed, your module should fail. Otherwise you break the Ansible runtime and following tasks automatically will stop (even for hosts for which they could continue)
```suggestion
                self.module.fail_json(msg="Datacenter '%s' not found" % self.__datacenter_name)
```

2019-01-11 11:03 UTC, pdellaert commented on lib/ansible/modules/cloud/vmware/vmware_drs_group.py
> +            raise Exception("Cluster '%s' not found" % self.__cluster_name)
Same as above, please fail the module, instead of raising an exception
```suggestion
            self.module.fail_json(msg="Cluster '%s' not found" % self.__cluster_name)
```

2019-01-11 11:03 UTC, pdellaert commented on lib/ansible/modules/cloud/vmware/vmware_drs_group.py
> +                        raise Exception("VM %s does not exist in cluster %s" % (vm,
Same as above, please fail the module, instead of raising an exception
```suggestion
            self.module.fail_json(msg="VM %s does not exist in cluster %s" % (vm,
```

2019-01-11 11:03 UTC, pdellaert commented on lib/ansible/modules/cloud/vmware/vmware_drs_group.py
> +                        raise Exception("ESXi host %s does not exist in cluster %s" % (host, self.__cluster_name))
Same as above, please fail the module, instead of raising an exception
```suggestion
            self.module.fail_json(msg="ESXi host %s does not exist in cluster %s" % (host, self.__cluster_name))
```

2019-01-11 11:03 UTC, pdellaert commented on lib/ansible/modules/cloud/vmware/vmware_drs_group.py
> +            raise Exception('Failed, no hosts or vms defined')
Same as above, please fail the module, instead of raising an exception
```suggestion
### This requires to store the module as self.__module in the init
            self.__module.fail_json(msg='Failed, no hosts or vms defined')
```

2019-01-11 11:03 UTC, pdellaert commented on lib/ansible/modules/cloud/vmware/vmware_drs_group.py
> +            existing_group_obj = self.__get_group_by_name()
Wouldn't it be easier to just do this first, then do `if existing_group_obj:`? (no need to call the `__group_exists` method. As you basically are doing twice the same operation of finding the group by name, which is all unnecessary API calls into vCenter)

2019-01-11 11:03 UTC, pdellaert commented on lib/ansible/modules/cloud/vmware/vmware_drs_group.py
> +        list_a = self.__vm_list if host_group is False else self.__host_list
```suggestion
        list_a = self.__host_list if host_group else self.__vm_list
```
Just a little suggestion to keep it easier/cleaner

2019-01-11 11:03 UTC, pdellaert commented on lib/ansible/modules/cloud/vmware/vmware_drs_group.py
> +    def __get_group_by_name(self, group_name=None, cluster_obj=None):
You seem to call this method multiple times in your code to get the actual group. Every time it will execute API calls into vCenter... It would be a lot easier to just cache the group you found once inside the object/class (`self.__group` for instance) and use that every time?

2019-01-11 11:03 UTC, pdellaert commented on lib/ansible/modules/cloud/vmware/vmware_drs_group.py
> +                task = self.__cluster_obj.ReconfigureEx(config_spec, modify=True)
this should be in a try/catch block to capture several type of exceptions that might be thrown... have a look at some of the other modules on how to do this, there's several exceptions you can catch, if you do a generic catch (which is ok), make sure to add a clear `self.module.fail_json(msg=...)` statement

2019-01-11 11:03 UTC, pdellaert commented on lib/ansible/modules/cloud/vmware/vmware_drs_group.py
> +            self.__set_result(existing_group_obj)
You are updating an existing group, but do not fetch it again after the update? Doesn't that result in the old data being returned as a result?

2019-01-11 11:03 UTC, pdellaert commented on lib/ansible/modules/cloud/vmware/vmware_drs_group.py
> +            existing_group_obj = self.__get_group_by_name()
same comment as in the `__create_host_group` section

2019-01-11 11:03 UTC, pdellaert commented on lib/ansible/modules/cloud/vmware/vmware_drs_group.py
> +                task = self.__cluster_obj.ReconfigureEx(config_spec, modify=True)
Same remark as with the `__create_host_group` on try/catch

2019-01-11 11:03 UTC, pdellaert commented on lib/ansible/modules/cloud/vmware/vmware_drs_group.py
> +            self.__set_result(existing_group_obj)
same remark as with the `__create_host_group` on the use of `existing_group_obj`

2019-01-11 13:02 UTC, karstenjakobsen commented on lib/ansible/modules/cloud/vmware/vmware_drs_group.py
> +                raise Exception("Datacenter '%s' not found" % self.__datacenter_name)
Ok. I've put in a try/catch block in the main() - is this not enough to catch an error? I've done this in all my modules. I'll change it to `self.module.fail_json` if you think it's necessary..

2019-01-11 13:03 UTC, karstenjakobsen commented on lib/ansible/modules/cloud/vmware/vmware_drs_group.py
> +            self.__set_result(existing_group_obj)
Will fix

2019-01-11 13:24 UTC, pdellaert commented on lib/ansible/modules/cloud/vmware/vmware_drs_group.py
> +                raise Exception("Datacenter '%s' not found" % self.__datacenter_name)
ah, i missed that, sorry... Sure, that's fine then :)

2019-01-13 17:02 UTC, karstenjakobsen commented on lib/ansible/modules/cloud/vmware/vmware_drs_group.py
> +            existing_group_obj = self.__get_group_by_name()
Fixed in latest commit by setting `group_obj` in the init() - later testing if this is set.

2019-01-14 16:08 UTC, pdellaert approved these changes
LGTM!

Thanks for the quick adjustments!

2019-01-14 16:25 UTC, merged