reworked sqs_queue
ansible/ansible pull request #50686
Opened 2019-01-09 01:22 UTC by sbj-ss

##### SUMMARY
Fully reworked `sqs_queue` module.
- Moved to AnsibleAWSModule
- Compacted code
- Added FIFO queues, tagging and KMS support
- Added ability to remove policies.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
`lib.ansible.modules.cloud.amazon.sqs_queue`

##### ADDITIONAL INFORMATION
I'm aware of #34526, but the change request looks stuck and that implementation contains some bugs.

2019-01-09 20:28 UTC, mattclay commented
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/101235/68/tests

2019-01-09 22:54 UTC, sbj-ss commented
@mattclay Please see this: https://github.com/ansible/ansible/pull/40110/commits/6e44bd6b8c1152edaa4ab6c5d483fbd9e5ab257c#diff-727e795eecd556311091aadde40702abR58
Tests are failing because they're expecting wrong result type. I can open another PR to fix tests :)

2019-01-09 22:59 UTC, mattclay commented
@sbj-ss If the tests can be fixed independently of the changes in this PR and still pass, then a separate PR to fix would be good. Otherwise they'll need to be fixed as part of this PR, since we can't merge changes that result in failing tests.

2019-01-09 23:01 UTC, sbj-ss commented
@mattclay will tests included in PR be used to test the PR itself?

2019-01-09 23:19 UTC, mattclay commented
@sbj-ss Yes

2019-01-09 23:34 UTC, samicemalone commented
Could the queue URL be returned to resolve #41260 ?
Also is it possible to return the queue ARN (and URL) in check mode (if the queue exists)?

2019-01-09 23:45 UTC, sbj-ss commented
@samicemalone Yes, will add them today.

2019-01-10 00:02 UTC, sbj-ss commented
@mattclay @samicemalone done.

2019-06-13 10:21 UTC, mente commented
Any chances to move this forward? What is missing here?

2019-09-24 07:07 UTC, tremble requested changes
@sbj-ss Sorry you've not heard anything for so long.

Since you're adding new features to a module marked as "stableinterface" please add tests for the additional features.

I've had a quick run through the code nothing else stands out.

2019-09-24 07:07 UTC, tremble commented on lib/ansible/modules/cloud/amazon/sqs_queue.py
> +    if new_tags is None:
This logic seems ignore the use case of removing all tags.

2019-09-24 07:07 UTC, tremble commented on lib/ansible/modules/cloud/amazon/sqs_queue.py
> +    version_added: "2.8"
This will need updating

2019-09-24 07:07 UTC, tremble commented on lib/ansible/modules/cloud/amazon/sqs_queue.py
> +      - Standard or FIFO queue.
This should probably mention that the queue_type can only be selected at creation time and is *ignored* when making other changes

2020-01-02 13:58 UTC, citrix-ericgo commented
Any update on this? Looks like a merge conflict.

2020-01-02 14:11 UTC, sbj-ss commented
Sorry, I'm now very far from ansible on my new job. If someone wants to push this forward - you're really welcome.

2020-02-27 22:26 UTC, closed without merging