adding vmss extension
ansible/ansible pull request #50709
Opened 2019-01-09 13:29 UTC by zikalino

##### SUMMARY
This module adds VMSS Extension functionality, which is quite essential when using VMSS.

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
azure_rm_virtualmachinescalesetextension

##### ADDITIONAL INFORMATION

2019-01-10 07:39 UTC, Fred-sun commented
@yungezz @yuwzho

2019-01-10 07:41 UTC, yungezz approved these changes

2019-01-15 02:18 UTC, Fred-sun commented
@nitzmahone Please help review this PR  and push for merge.  Thanks!

2019-01-16 22:24 UTC, nitzmahone requested changes
Couple minor things and outstanding questions, but generally looks good.

2019-01-16 22:24 UTC, nitzmahone commented on lib/ansible/modules/cloud/azure/azure_rm_virtualmachinescalesetextension.py
> +            - Assert the state of the SQL server. Use 'present' to create or update a server and
s/SQL server/VMSS extension/

2019-01-16 22:24 UTC, nitzmahone commented on lib/ansible/modules/cloud/azure/azure_rm_virtualmachinescalesetextension.py
> +                auto_upgrade_minor_version=self.auto_upgrade_minor_version,
Does the API handle `None` OK here, or do we need a default?

2019-01-16 22:24 UTC, nitzmahone commented on lib/ansible/modules/cloud/azure/azure_rm_virtualmachinescalesetextension.py
> +
Are location/version/type/auto-upgrade things that should be checked for changes? Not sure which (if any) are updateable...

2019-01-16 23:46 UTC, zikalino commented on lib/ansible/modules/cloud/azure/azure_rm_virtualmachinescalesetextension.py
> +
yeah... I will check all of those. there should be warnings if not updatable (according to our recent discussion).
actually vmss extension is very similar to vm extension, so I will update both if necessary.

2019-01-17 03:04 UTC, zikalino commented on lib/ansible/modules/cloud/azure/azure_rm_virtualmachinescalesetextension.py
> +                auto_upgrade_minor_version=self.auto_upgrade_minor_version,
yes it does

2019-01-17 03:07 UTC, zikalino commented
@nitzmahone i have just revisited azure_virtualmachine_extension as well.
fixed all the idempotence issues according to our current guidelines:
https://github.com/ansible/ansible/pull/51005
i have applied the same fixes here.

2019-01-22 03:29 UTC, mattclay commented
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/102624/77/tests

2019-01-23 23:50 UTC, nitzmahone approved these changes

2019-01-23 23:51 UTC, merged