Allow to to upgrade more than 1 node at a time.
ansible/ansible pull request #50780
Opened 2019-01-10 21:57 UTC by carchi8py

##### SUMMARY
Allow to to upgrade more than 1 node at a time. 

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME
* na_ontap_software_update

##### ADDITIONAL INFORMATION

```paste below

```

2019-01-25 21:50 UTC, lonico approved these changes

2019-01-28 17:02 UTC, thedoubl3j approved these changes
docs were updated to reflect change, tests looked good. lgtm ping @gundalow

2019-01-29 14:52 UTC, gundalow requested changes

2019-01-29 14:52 UTC, gundalow commented on lib/ansible/modules/storage/netapp/na_ontap_software_update.py
> +    version_added: "2.8"
Please remove and add `aliases` instead

2019-01-29 14:52 UTC, gundalow commented on lib/ansible/modules/storage/netapp/na_ontap_software_update.py
> +            nodes=dict(required=False, type='list'),
please add aliases for node.

This will allow older Ansible 2.7 Playbooks to still work.

2019-02-06 18:46 UTC, gundalow approved these changes

2019-02-15 02:14 UTC, lonico commented
shipit

2019-02-19 14:33 UTC, merged