add option to change packages on hold (packages/apt)
ansible/ansible pull request #50859
Opened 2019-01-14 10:13 UTC by yfoelling

##### SUMMARY
Added an option to be able to change held back packages (apt-mark hold).

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
change held back packages

##### ADDITIONAL INFORMATION
Please check if the new option is everywhere it needs to be.

2019-01-15 23:37 UTC, bcoca requested changes

2019-01-15 23:37 UTC, bcoca commented on lib/ansible/modules/packaging/os/apt.py
> +    version_added: "2.8"
missing 'default: false' in docs

2019-05-21 13:51 UTC, tinproject commented
@yfoelling @bcoca Any new on this? I believe all the requested changes are already fulfilled.

(I'm pinging here because I was expecting this went into 2.8, but I could not found it on the changelog)

2019-05-21 14:41 UTC, samdoran commented
!component =lib/ansible/modules/packaging/os/apt.py

2020-03-05 02:55 UTC, immesys commented
This would be handy. Is there a reason it is stuck?

2020-05-27 15:09 UTC, samdoran commented
This needs a changelog entry and integration tests (plus a rebase).

2024-03-18 19:50 UTC, Akasurde commented
superseded by https://github.com/ansible/ansible/pull/73629

@yfoelling Thanks for the contribution.

2024-03-18 19:50 UTC, closed without merging