Add msix and appx support to win_package
ansible/ansible pull request #50864
Opened 2019-01-14 12:11 UTC by agowa338

##### SUMMARY

Add msix and appx support to win_package

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

win_package

##### ADDITIONAL INFORMATION

Implements #50765

2019-01-14 12:41 UTC, ahmadgb commented
a check failed, i don't think i can verify

2019-01-14 13:32 UTC, dagwieers commented
Sure you can, just click on the Details-link and scroll through the failure-logs.
```
00:20 Run command: test/sanity/pslint/pslint.ps1 lib/ansible/modules/windows/win_package.ps1
00:22 ERROR: Command "test/sanity/pslint/pslint.ps1 lib/ansible/modules/windows/win_package.ps1" returned exit status 1.
00:22 >>> Standard Error
00:22 Invoke-ScriptAnalyzer : Parse error in file /root/ansible/lib/ansible/modules/windows/win_package.ps1:  You must provide a value expression following the '-or' operator at line 174 column 93.
00:22 At /root/ansible/test/sanity/pslint/pslint.ps1:16 char:25
00:22 + ... $Results += Invoke-ScriptAnalyzer -Path $Path -Setting $PSScriptRoot/ ...
00:22 +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
00:22 + CategoryInfo          : ParserError: (ExpectedValueExpression:String) [Invoke-ScriptAnalyzer], ParseException
00:22 + FullyQualifiedErrorId : Parse error in file /root/ansible/lib/ansible/modules/windows/win_package.ps1:  You must provide a value expression following the '-or' operator at line 174 column 93.,Microsoft.Windows.PowerShell.ScriptAnalyzer.Commands.InvokeScriptAnalyzerCommand
```

Syntax error on line 174: https://github.com/ansible/ansible/pull/50864/files#diff-015c6ab28b2a53b29b2fa4d1d6c225ffR174

2019-01-14 13:35 UTC, ahmadgb commented on lib/ansible/modules/windows/win_package.ps1
> +            $path.EndsWith(".appx", [System.StringComparison]::CurrentcultureIgnoreCase) -or
fix syntax please

2019-01-15 06:55 UTC, ahmadgb approved these changes

2019-01-18 14:00 UTC, chopraaa commented
I think tests for this would be nice.

Also, I think `appx`, `dism` and `PackageManagement` shouldn't be hard requirements to run this module.

2019-01-20 11:22 UTC, agowa commented
dism is a hard requirement, as the command Add-AppxProvisionedPackage belongs to it, without it there is no possibility to instal appx/msix for all users.
appx is currently not used, I forgot to remove it before commiting, it is required for installing appx/msix for a single user
PackageManagement is required for Get-Package to get a list of installed software. This is the only way to check if it is already installed or not (I'm not quite sure if it uses appx underneath for querying the appx/msix-es though).

Or do you just mean to replace the `#Requires foo` with something like `import-module -name foo -erroraction stop`?

2019-01-20 13:14 UTC, chopraaa commented
That is correct.

Check if the user is installing an appx/msix. Then check if the required modules are present.

2019-01-21 11:40 UTC, agowa338 commented
@ahmadgb can you please verify this version, too? I've currently no Windows Box to test this.

2019-01-22 05:40 UTC, jborean93 commented
I'm starting to think `win_package` is being overloaded with too many things to do. I'm wondering whether we should have a separate module to install UWAs instead of trying to shoehorn it into here. I'll add it to the discuss at the next Windows Working Group. It would be great if you could come along https://github.com/ansible/community/issues/420#issuecomment-456277586.

2019-01-22 05:43 UTC, jborean93 requested changes

2019-01-22 05:43 UTC, jborean93 commented on lib/ansible/modules/windows/win_package.ps1
> +$isAllUsers = Get-AnsibleParam -obj $params -name "AllUsers" -type "bool" -default $true -aliases "isAllUser"
When creating module options it's best to keep them align with the Ansible standard of snake_case, e.g. `install_all_users` or something like that. It is also best to have the variable reflect the same format of the actual option and keep it aligned to the existing standard in the module.

2019-01-29 23:50 UTC, jborean93 commented
Without trying it out yet I'm fairly happy with the code changes, the only remaining thing left is to add some integration tests. It would be great if we could use our own custom packages that are simple to install just like we have done for the .msi and .exe tests. Please shout out if you need help with anything around testing.

2019-03-17 14:48 UTC, agowa338 commented
@jborean93 can you update you review?

2019-03-17 18:57 UTC, jborean93 commented
@agowa338, my last comment is still stands, I’m fine with the code but this still need some integration tests.

2020-02-13 06:51 UTC, jborean93 commented
This functionality has been added with https://github.com/ansible/ansible/pull/66931. Not everything in this PR was added there but now win_package can do the basic install and uninstall of appx/msix packages.

If more functionality is required it should be done in a separate module, similar to how `package` is generic for all package managers but more features can be done in ones like `dnf`, `apt`, and so on.

2020-02-13 06:51 UTC, closed without merging