fix ansible_connect_timeout variable in network_cli,httpapi and nxos_install_os timeout check
ansible/ansible pull request #50965
Opened 2019-01-16 06:46 UTC by trishnaguha

Signed-off-by: Trishna Guha <trishnaguha17@gmail.com>

##### SUMMARY

fixes https://github.com/ansible/ansible/issues/50626

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

plugins/action/nxos.py
plugins/connection/{network_cli,httpapi}.py

2019-01-16 07:36 UTC, ganeshrn approved these changes

2019-01-16 07:46 UTC, ganeshrn requested changes

2019-01-16 07:46 UTC, ganeshrn commented on lib/ansible/plugins/connection/napalm.py
> +      - name: ansible_connect_timeout
Since the connection is initiated even before task variable is read this option might not work for per task basis

2019-01-16 08:05 UTC, ganeshrn approved these changes

2019-01-16 08:40 UTC, merged

2019-01-23 05:57 UTC, trishnaguha commented
Backporting PR https://github.com/ansible/ansible/pull/51209