reboot - Fix connection timeout reset
ansible/ansible pull request #51000
Opened 2019-01-16 22:25 UTC by jborean93

##### SUMMARY
The current logic to reset the connection timeout is not correct as it won't run if the original connection timeout (connection plugin) was never set. This PR changes the logic to compare the previous value with the current value instead to detect if there were any changes.

Fixes https://github.com/ansible/ansible/issues/48665.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
reboot

2019-01-16 22:29 UTC, nitzmahone requested changes
I think there might be a couple issues here

2019-01-16 22:29 UTC, nitzmahone commented on lib/ansible/plugins/action/reboot.py
> +            if original_connection_timeout != connect_timeout:
Isn't it possible for connect_timeout to be undefined now?

2019-01-16 22:29 UTC, nitzmahone commented on lib/ansible/plugins/action/reboot.py
> -            connect_timeout = self._task.args.get('connect_timeout', self._task.args.get('connect_timeout_sec', self.DEFAULT_CONNECT_TIMEOUT))
doesn't this line still need to be here for the one specified by the task and the fallback behavior for the old arg name?

2019-01-16 22:30 UTC, jborean93 commented on lib/ansible/plugins/action/reboot.py
> +            if original_connection_timeout != connect_timeout:
That's true, will fix that up

2019-01-16 22:31 UTC, jborean93 commented on lib/ansible/plugins/action/reboot.py
> -            connect_timeout = self._task.args.get('connect_timeout', self._task.args.get('connect_timeout_sec', self.DEFAULT_CONNECT_TIMEOUT))
This was only used for the original comparison. It is used at https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/reboot.py#L177 to override it initially.

2019-01-16 22:42 UTC, nitzmahone commented on lib/ansible/plugins/action/reboot.py
> -            connect_timeout = self._task.args.get('connect_timeout', self._task.args.get('connect_timeout_sec', self.DEFAULT_CONNECT_TIMEOUT))
Ah yeah, I see now (damn contextual review) ;) ...

2019-01-16 22:43 UTC, nitzmahone approved these changes

2019-01-17 15:44 UTC, samdoran approved these changes

2019-01-17 15:45 UTC, merged

2019-01-17 19:39 UTC, jborean93 commented
Backport PR to stable-2.7 https://github.com/ansible/ansible/pull/51039