Fix 'defaults' option in the nxos_config module
ansible/ansible pull request #51076
Opened 2019-01-18 17:41 UTC by OlivierB

##### SUMMARY
Nxos get_config is allways called with the 'all' option.
* Fix flag's calculation
* Add tests

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
nxos_config

##### ADDITIONAL INFORMATION

* This issue seems to be added in the PR #26565.
* The eos_config module has already been fixed:
  * #26798 logic fix.
  * #42300 functional change: 'all' option is used on the backup config.

I did not change the backup behavior as in the eos_config module.

2019-01-22 15:02 UTC, trishnaguha requested changes

2019-01-22 15:02 UTC, trishnaguha commented on lib/ansible/modules/network/nxos/nxos_config.py
> +            # Optimization: The running-config has already been recovered by the backup
To make it work, `not module.params['defaults']` needs to be removed from this condition.

2019-01-22 15:22 UTC, trishnaguha reviewed
@OlivierB Also instead of only fixing it in `get_running_config`, I would something like https://github.com/trishnaguha/ansible/commit/4f343491a3de63cbc9fd99eb7c120a34f7c143aa

2019-01-22 15:55 UTC, OlivierB commented
@trishnaguha OK !
I will implement it like in the eos_config module.

2019-01-23 05:59 UTC, trishnaguha approved these changes
Thanks for the PR!

2019-01-23 05:59 UTC, merged