meraki_device - Support for creating and modifying device notes
ansible/ansible pull request #51100
Opened 2019-01-19 19:39 UTC by kbreit

##### SUMMARY
Meraki added support for adding device notes to a device via API. This PR adds a `note` parameter which allows assigning notes to a device.

Fixes #50962

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
meraki_device

2019-01-28 23:32 UTC, dagwieers requested changes
LGTM, except the changelog fragment

2019-01-28 23:32 UTC, dagwieers commented on changelogs/fragments/49037-digital_ocean_tag_facts_keyerror.yaml
> +- "digital_ocean_tag_facts - Fixed KeyError exception when using tag_name parameter"
This is Meraki, not Digital Ocean ?

2019-02-18 01:09 UTC, kbreit commented on changelogs/fragments/49037-digital_ocean_tag_facts_keyerror.yaml
> +- "digital_ocean_tag_facts - Fixed KeyError exception when using tag_name parameter"
Fixed

2019-02-18 01:09 UTC, kbreit commented
@dagwieers Please take a look at this one.

2019-03-29 13:26 UTC, dagwieers approved these changes
LGTM

2019-03-29 13:26 UTC, merged