New module - meraki/meraki_content_filtering
ansible/ansible pull request #51223
Opened 2019-01-23 14:29 UTC by kbreit

##### SUMMARY
Meraki added support for setting content filtering policy via their API. This modules allows for control of it.

I do want feedback on if it should use the word filtering or filter.

The only reason this is WIP is because Meraki has a bug in the API which doesn't allow setting content categories. I've reported this and their support group has reproduced it. Once the bug is fixed, I will remove WIP. Although, I may remove it earlier to make sure this gets into 2.8.

Fixes #51102

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
meraki_content_filtering

2019-02-06 23:16 UTC, dagwieers requested changes
Similar changes to previous PR.

2019-02-06 23:16 UTC, dagwieers commented on lib/ansible/modules/network/meraki/meraki_content_filtering.py
> +        choices: [top sites, full list]
```suggestion
        choices: [ full list, top sites ]
```

2019-02-06 23:16 UTC, dagwieers commented on lib/ansible/modules/network/meraki/meraki_content_filtering.py
> +        - Determines whether a network filters fo rall URLs in a category or only the list of top blocked sites.
```suggestion
        - Determines whether a network filters for all URLs in a category or only the list of top blocked sites.
```

2019-02-06 23:16 UTC, dagwieers commented on lib/ansible/modules/network/meraki/meraki_content_filtering.py
> +        - "http://www.ansible.com/*"
No quoting needed, no indentation needed, don't fool others :-)
```suggestion
      - http://www.ansible.com/*
```

2019-02-06 23:16 UTC, dagwieers commented on lib/ansible/modules/network/meraki/meraki_content_filtering.py
> +        -
This is wrong, you are making a single-list entry. If you want an empty list, it's either
```yaml
    allowed_urls:
```
(Will become None though, so would need special handling)
or JSON syntax (recommended)
```yaml
    allowed_urls:  []
```

2019-02-06 23:16 UTC, dagwieers commented on lib/ansible/modules/network/meraki/meraki_content_filtering.py
> +        state=dict(type='str', choices=['present'], default='present'),
Defaults before choices.
```suggestion
        state=dict(type='str', default='present', choices=['present']),
```

2019-02-06 23:16 UTC, dagwieers commented on lib/ansible/modules/network/meraki/meraki_content_filtering.py
> +        category_list_size=dict(type='str', choices=['top sites', 'full list']),
Order alphabetically
```suggestion
        category_list_size=dict(type='str', choices=['full list', 'top sites']),
```
Also I think it's a weird name, not my first choice. Why not just 'category' ?

2019-02-06 23:16 UTC, dagwieers commented on lib/ansible/modules/network/meraki/meraki_content_filtering.py
> +        meraki.fail_json(msg='net_name and net_id are mutually exclusive')
Again, quote names and values:
```suggestion
        meraki.fail_json(msg="Parameters 'net_name' and 'net_id' are mutually exclusive")
```

2019-02-06 23:16 UTC, dagwieers commented on lib/ansible/modules/network/meraki/meraki_content_filtering.py
> +        return meraki.result
This is wrong, already explained.

2019-02-06 23:16 UTC, dagwieers commented on lib/ansible/modules/network/meraki/meraki_content_filtering.py
> +                           supports_check_mode=False,
No check-mode either ?

2019-02-07 03:37 UTC, kbreit commented
@dagwieers Requested changes are integrated.

2019-02-18 23:04 UTC, dagwieers approved these changes

2019-02-18 23:04 UTC, dagwieers commented
rebuild_merge

2019-02-19 00:27 UTC, merged