Don't fail if exos can't configure cli columns
ansible/ansible pull request #51364
Opened 2019-01-26 14:11 UTC by zombah

##### SUMMARY

Fixes #51363 

Some exos versions don't have ```configure cli columns``` command, don't fail in this case

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

ansible-connection

##### ADDITIONAL INFORMATION

```paste below

```

2019-01-28 15:41 UTC, ganeshrn reviewed
cc @rdvencioneck @hlrichardson Please review this PR

2019-04-23 22:10 UTC, ujwalkomarla commented
@zombah Can you close and reopen the pull request, to let the CI run again?

2019-04-23 22:35 UTC, zombah commented
@ujwalkomarla sure

2019-09-10 17:04 UTC, ujwalkomarla commented
@Qalthos @ganeshrn As I recall, using display was discouraged. What would be the way to log a message and continue when the 'configure cli columns' fail?

Is it `self.queue_message('log', 'MSG')`?

2019-09-11 16:29 UTC, Qalthos requested changes

2019-09-11 16:29 UTC, Qalthos commented on lib/ansible/plugins/terminal/exos.py
> +            display.display('WARNING: Unable to configure cli columns, command responses may be truncated')
```suggestion
            self._connection.queue_message('warning', 'Unable to configure cli columns, command responses may be truncated')
```

And then remove the `Display` import above.

2019-09-11 23:00 UTC, zombah commented on lib/ansible/plugins/terminal/exos.py
> +            display.display('WARNING: Unable to configure cli columns, command responses may be truncated')
Resolved and tested, works fine.

2019-09-12 14:58 UTC, Qalthos approved these changes

2019-09-12 15:12 UTC, merged