Spotinst - add emr module
ansible/ansible pull request #51517
Opened 2019-01-31 00:00 UTC by jeffnoehren

##### SUMMARY
Adding new Spotinst module - EMR

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION
```paste below
ok: [localhost] => {
    "result": {
        "changed": true, 
        "failed": false, 
        "group_id": "smrs-35124875", 
        "message": "Created Ocean Cluster successfully."
    }
}
```

2019-01-31 03:00 UTC, mattclay requested changes

2019-01-31 03:00 UTC, mattclay commented on test/sanity/validate-modules/ignore.txt
> +lib/ansible/modules/cloud/spotinst/spotinst_mrScaler.py E326
New ignores should not be added. Correct the underlying issue in the module. If the issue is in an existing module_utils, fix that issue in a separate PR first.

2019-01-31 03:02 UTC, mattclay submitted a review, later dismissed

2019-01-31 03:02 UTC, mattclay commented on lib/ansible/modules/cloud/spotinst/spotinst_mrScaler.py
> +#!/usr/bin/python
Use lowercase letters for module names.

2019-01-31 19:26 UTC, jeffnoehren commented on test/sanity/validate-modules/ignore.txt
> +lib/ansible/modules/cloud/spotinst/spotinst_mrScaler.py E326
removed!

2019-01-31 19:27 UTC, jeffnoehren commented on lib/ansible/modules/cloud/spotinst/spotinst_mrScaler.py
> +#!/usr/bin/python
module name has been changed! thanks for letting me know

2019-02-05 17:23 UTC, talzur commented
shipit

2019-02-06 18:54 UTC, kmcgrath commented
@mattclay Is there anything else you need from our side to get this task in the release flow?

2019-02-16 00:57 UTC, mattclay commented on changelogs/fragments/spotinst-add-emr-resource.yml
> +  - spotinst - Added EMR resource
New modules should not have changelog entries.

2019-02-28 18:59 UTC, closed without merging