Adds 'y', 'n', 'on', 'off' to Values to be Converted to Booleans
ansible/ansible pull request #51619
Opened 2019-02-01 16:41 UTC by dennisconrad

##### SUMMARY

Fixes #51618

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

set_fact

##### ADDITIONAL INFORMATION

Short playbook which will succeed if `DEFAULT_JINJA2_NATIVE` is set to `False` after applying the patch:

```yaml
- hosts: localhost
  gather_facts: no

  tasks:
    - set_fact:
        string_y: "y"
        string_n: "n"
        string_yes: "yes"
        string_no: "no"
        string_on: "on"
        string_off: "off"
        string_true: "true"
        string_false: "false"
    
    - assert:
        that:
          - string_y ==  "y"
          - string_n ==  "n"
          - string_yes ==  "yes"
          - string_no ==  "no"
          - string_on ==  "on"
          - string_off ==  "off"
          - string_true ==  "true"
          - string_false ==  "false"
      when: lookup('config', 'DEFAULT_JINJA2_NATIVE') == true

    - assert:
        that:
          - string_y ==  true
          - string_n ==  false
          - string_yes ==  true
          - string_no ==  false
          - string_on ==  true
          - string_off ==  false
          - string_true ==  true
          - string_false ==  false
      when: lookup('config', 'DEFAULT_JINJA2_NATIVE') == false
```

2019-02-01 16:47 UTC, bcoca commented on lib/ansible/plugins/action/set_fact.py
> +                if v_is_boolean and not C.DEFAULT_JINJA2_NATIVE:
`import ansible.module_utils.parsing.convert_bool import BOOLEANS` and use that constant

2019-02-01 19:17 UTC, dagwieers commented
This is wrong, if you define it as a string, it should be a string. It always has been like this for good reasons. Otherwise people wouldn't be able to create a string containing "yes" or "True".

2019-02-01 21:53 UTC, dennisconrad commented
> This is wrong, if you define it as a string, it should be a string. It always has been like this for good reasons. Otherwise people wouldn't be able to create a string containing "yes" or "True".

This has **not** "always" been the case - as a matter of fact, it is the **default** behavior to convert strings resembling Booleans right now, and there was no way to disable this until 77d2008150b26a14911006d1c542612408dc5bc4 , which introduced `DEFAULT_JINJA2_NATIVE` (disabled by default).

Thanks to the above commit, it is now possible to enable as I would argue is proper behavior, but it is not the default.

Simply put, if you use a string resembling a Boolean value in a "toplevel" scalar except variations of , it will be converted to proper Boolean.  Easily demonstrated - put the following in a file `test.yml`:

```yaml
- hosts: localhost
  gather_facts: no

  tasks:
    - set_fact:
        string_y: "y"
        string_n: "n"
        string_yes: "yes"
        string_no: "no"
        string_on: "on"
        string_off: "off"
        string_true: "true"
        string_false: "false"

    - debug:
        var: string_y
    - debug:
        var: string_n
    - debug:
        var: string_yes
    - debug:
        var: string_no
    - debug:
        var: string_on
    - debug:
        var: string_off
    - debug:
        var: string_true
    - debug:
        var: string_false
```

Then run it with `ANSIBLE_JINJA2_NATIVE=False` (again, the default):

```bash
$ ANSIBLE_JINJA2_NATIVE=False ansible-playbook test.yml
 [WARNING]: Unable to parse /etc/ansible/hosts as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not
match 'all'


PLAY [localhost] ************************************************************************************************

TASK [set_fact] *************************************************************************************************
ok: [localhost]

TASK [debug] ****************************************************************************************************
ok: [localhost] => {
    "string_y": "y"
}

TASK [debug] ****************************************************************************************************
ok: [localhost] => {
    "string_n": "n"
}

TASK [debug] ****************************************************************************************************
ok: [localhost] => {
    "string_yes": true
}

TASK [debug] ****************************************************************************************************
ok: [localhost] => {
    "string_no": false
}

TASK [debug] ****************************************************************************************************
ok: [localhost] => {
    "string_on": "on"
}

TASK [debug] ****************************************************************************************************
ok: [localhost] => {
    "string_off": "off"
}

TASK [debug] ****************************************************************************************************
ok: [localhost] => {
    "string_true": true
}

TASK [debug] ****************************************************************************************************
ok: [localhost] => {
    "string_false": false
}

PLAY RECAP ******************************************************************************************************
localhost                  : ok=9    changed=0    unreachable=0    failed=0   
```

You will notice that all strings resembling Booleans have been converted to Booleans, with the exception of `y`/`n`/`on`/`off` - inconsistent behavior.

Now there is a lot to be said for enabling `ANSIBLE_JINJA2_NATIVE` (as I mentioned in the corresponding bug report https://github.com/ansible/ansible/issues/51618 ), but right now, it isn't, and this patch is enabling consistent behavior.

Please also see this comment: https://github.com/ansible/ansible/issues/39414#issuecomment-389495418

2019-02-02 02:12 UTC, dagwieers commented
@dennisconrad Ok, let's make it clear this is about **set_fact** only, and that someone (incorrectly) changed **set_fact** to convert certain strings to booleans. This behaviour is wrong, **set_fact** should be behaving exactly as **vars:** in YAML format.

I traced this back to a change more than 4 years ago (https://github.com/ansible/ansible/commit/a6d6a89ad1d460f8d29589128549e2bac1e54db8). I think we should either keep it as it is (to not break anyone's playbooks) or if we do want to correct this, we should remove this conversion in **set_fact**.

2019-02-02 02:13 UTC, dagwieers commented
Issue #39414 makes it very clear to me we shouldn't be performing conversions at all. The problem is that we have been doing it for very specific cases, where we should have stayed clear from doing so in all cases.

2019-02-02 02:16 UTC, dagwieers requested changes
I am firmly against this. As this will be breaking existing playbooks. If we do consider we should make **set_fact** more consistent, we should be removing this conversion altogether (so that `set_fact` behaves like `vars:`), rather than extending the erratic behaviour that was added more than 4 years ago.

2019-02-02 05:48 UTC, mattclay commented
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/105310/37/tests

2019-02-02 19:59 UTC, gundalow requested changes
Whatever is decided to be the correct solutions I'd like to see tests to defend that functionality.

If a change in functionality is applied I wonder if a Porting Guide entry is also needed.

2019-02-03 23:22 UTC, dagwieers commented
@gundalow I was looking in those tests to see what the intent was, and I find them quite confusing.
https://github.com/ansible/ansible/blob/devel/test/integration/targets/set_fact/set_fact_bool_conv.yml

```yaml
    - assert:
        that:
          - string_var == 'no'
          - this_is_string == True
          - this_is_not_string == True
          - this_is_also_string == False
          - this_is_another_string == False
          - this_is_more_strings == False
```
So `this_is_string` (and all the other *strings*) are actually booleans? However the test-file is named `set_fact_bool_conv.yml` so I assume this is intended. 

Nowhere is it explained why we would expect **set_fact** to convert (some) string values to booleans.
Another assumption is that this is somehow wanted for key=value pairs (because that's where this was done in the past AFAIK) but this is IMO the wrong thing to do in YAML. But this behaviour seems to have been introduced in Ansible v2.0? Which is quite late in the game to be for key=value pairs?

BTW If we would be using `BOOLEANS` from https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/parsing/convert_bool.py, as suggested, **set_fact** will be converting variables set to 1 and 0 (or 'f' and 't') to booleans as well. I don't think we want to go that path either.

Safest path is to keep it as it is, and the cleanest is to not do any conversion in **set_fact**. If the user wants a boolean, the user should declare it as a boolean (in YAML).

2020-07-10 15:40 UTC, bcoca commented on lib/ansible/plugins/action/set_fact.py
> +                if v_is_boolean and not C.DEFAULT_JINJA2_NATIVE:
This should just force strict and leave unchanged on typeerror
```diff --git a/lib/ansible/plugins/action/set_fact.py b/lib/ansible/plugins/action/set_fact.py
index d7fe573c1a..934245d07c 100644
--- a/lib/ansible/plugins/action/set_fact.py
+++ b/lib/ansible/plugins/action/set_fact.py
@@ -51,8 +51,11 @@ class ActionModule(ActionBase):
                                      "letters, numbers and underscores." % k)
                     return result

-                if not C.DEFAULT_JINJA2_NATIVE and isinstance(v, string_types) and v.lower() in ('true', 'false', 'yes', 'no'):
-                    v = boolean(v, strict=False)
+                if not C.DEFAULT_JINJA2_NATIVE and isinstance(v, string_types):
+                    try:
+                        v = boolean(v, strict=True)
+                    except TypeError:
+                        pass  # not valid bool string
                 facts[k] = v

         result['changed'] = False```

2020-07-10 15:47 UTC, samdoran commented
After discussing more today, that we are converting strings to booleans _at all_ only in `set_fact` is problematic. Making it accept _more_ string values and converting to booleans would make this problematic behavior worse.

To discuss this further, please reach out on IRC or the mailing list:

   * IRC: #ansible-devel on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-devel

2020-07-10 15:47 UTC, closed without merging