Fix to allow Po interface descriptions
ansible/ansible pull request #51726
Opened 2019-02-05 08:40 UTC by thomasdstewart

##### SUMMARY

Add port-channel support for onyx_interface.py by defining IF_PO_REGEX, IF_TYPE_PO and modifying IF_TYPE_MAP, UNSUPPORTED_ATTRS and UNSUPPORTED_STATES.

Fixes 51725

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

onyx_interface

##### ADDITIONAL INFORMATION

See https://github.com/ansible/ansible/issues/51725 to reproduce. After this change I get the following working:

```paste below
$ cat test2.yaml 
- hosts: switches
  gather_facts: no
  tasks:
  - onyx_interface:
      name: 'Po1'
      description: 'test'

$ ansible-playbook test2.yaml -l mellswitch01

PLAY [switches] *******************************************************************************************************************

TASK [onyx_interface] *************************************************************************************************************
changed: [mellswitch01]

PLAY RECAP ************************************************************************************************************************
mellswitch01           : ok=1    changed=1    unreachable=0    failed=0    skipped=0   

```

2019-03-08 13:50 UTC, samerd requested changes
Hi @thomasdstewart ,
Creation/removal of Port channels are handled in the module  ansible/modules/network/onyx/onyx_linkagg.py
So I suggest adding absent as unsupported attribute

2019-03-11 14:11 UTC, thomasdstewart commented
Hi @samerd ,

Thank you for the review. I've pushed a new version with absent as an unsupported state. I was confused by "unsupported attribute", I assume you meant unsupported state?

Thanks :)

Kind Regards
Tom

2019-03-11 14:11 UTC, samerd approved these changes

2019-03-11 14:12 UTC, samerd commented
Thanks @thomasdstewart 
The fix looks good.

2019-03-27 14:04 UTC, merged