Added Ansible UTM Info Module for proxy profile entities.
ansible/ansible pull request #51740
Opened 2019-02-05 13:12 UTC by getjack

##### SUMMARY
This PR will add a new utm info module which allows the management of proxy profile entries of the Sophos UTM. This module integrates with the existing utm_utils .

##### ISSUE TYPE
* New Module Pull Request

##### COMPONENT NAME
* module/web_infrastructure/sophos_utm/utm_proxy_profile_info.py

2019-02-05 13:12 UTC, getjack commented
@stearz @RickS-C137 Please help out reviewing :)

2019-02-05 14:01 UTC, MatrixCrawler approved these changes

2019-02-05 14:01 UTC, MatrixCrawler commented
shipit

2019-02-11 15:02 UTC, gundalow commented on lib/ansible/modules/web_infrastructure/sophos_utm/utm_proxy_profile_info.py
> +    - Stephan Schwarz (@stearz)
@getjack This should be your details here

2019-02-11 15:02 UTC, gundalow commented on lib/ansible/modules/web_infrastructure/sophos_utm/utm_proxy_profile_info.py
> +- name: Reading UTM proxy_profile
Is this a full example, would you need to `register` the result (info) returned?

2019-02-11 15:02 UTC, gundalow commented on lib/ansible/modules/web_infrastructure/sophos_utm/utm_proxy_profile_info.py
> +#!/usr/bin/python
I wonder if this would be better as a facts module?

2019-02-12 14:34 UTC, gundalow requested changes
Updates needed

2019-02-19 15:21 UTC, getjack commented on lib/ansible/modules/web_infrastructure/sophos_utm/utm_proxy_profile_info.py
> +    - Stephan Schwarz (@stearz)
I'm not the author just commiting it for my colleague.

2020-08-16 10:28 UTC, closed without merging