VMware: do create VMDK for new VMs
ansible/ansible pull request #51753
Opened 2019-02-05 16:31 UTC by Akasurde

##### SUMMARY
While creating new VM, don't assume the VMDKs are present,
create them as we attache the disk to VM.

Possible regression fix for introduced via #45953

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/modules/cloud/vmware/vmware_guest.py

2019-02-05 16:35 UTC, Akasurde commented
@zolvaring @pdellaert @dericcrago @Im0 @tchernomax @ckotte @jeking3 @Tomorrow9 Could you please review this ? Thanks

2019-02-06 00:38 UTC, jeking3 approved these changes

2019-02-06 00:41 UTC, jeking3 requested changes
Changed my mind... on line 1774 if vm_obj is none then we fall to line 1780 which calls create_scsi_disk, which should already set the create flag.

2019-02-06 09:50 UTC, Akasurde commented
`create_scsi_disk` does not contain any call to create flag.

2019-02-06 21:15 UTC, jeking3 approved these changes
Well, okay then.  :)

2019-02-08 04:44 UTC, merged