ipa_user: Support for homedirectory
ansible/ansible pull request #51765
Opened 2019-02-05 20:29 UTC by FraserMCampbell

Add support for specifying homedirectory in ipa_user module

+label: docsite_pr

##### SUMMARY

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2019-02-21 14:59 UTC, gundalow requested changes

2019-02-21 14:59 UTC, gundalow commented on lib/ansible/modules/identity/ipa/ipa_user.py
> +    description: Home directory
```suggestion
    description: Home directory
    version_added: "2.8"
```

2020-01-23 09:30 UTC, Akasurde commented
@FraserMCampbell Thanks for the contribution. This PR is superseded by https://github.com/ansible/ansible/pull/49151. Thanks.

2020-01-23 09:30 UTC, closed without merging

2020-01-23 15:36 UTC, FraserMCampbell commented
> @FraserMCampbell Thanks for the contribution. This PR is superseded by #49151. Thanks.

No problem, I need to figure out the process of better committing and testing these patches, I have others ...