Pluribus Networks vrouter interface ip module with UT
ansible/ansible pull request #51792
Opened 2019-02-06 04:42 UTC by rajaspachipulusu17

##### SUMMARY

Point feature of pn vrouter interface ip for Pluribus Networks Netvisor switches 

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME
pn_vrouter_interface_ip.py module with unit tests.

##### ADDITIONAL INFORMATION
ansible 2.4.0.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

```

2019-02-06 10:56 UTC, Akasurde requested changes

2019-02-06 10:56 UTC, Akasurde commented on lib/ansible/modules/network/netvisor/pn_vrouter_interface_ip.py
> +
```suggestion
        if VROUTER_EXISTS is False:
            module.fail_json(
                failed=True,
                msg='vRouter %s does not exist' % vrouter_name
            )
        if NIC_EXISTS is False:
            module.fail_json(
                failed=True,
                msg='vRouter with nic %s does not exist' % nic
            )
```

2019-02-06 10:56 UTC, Akasurde commented on lib/ansible/modules/network/netvisor/pn_vrouter_interface_ip.py
> +                msg='vrouter with interface %s doesnt exist' % ip
```suggestion
                msg='vRouter with interface %s does not exist' % ip
```

2019-02-07 06:06 UTC, Akasurde approved these changes
LGTM

2019-02-12 08:03 UTC, ganeshrn approved these changes

2019-02-12 08:03 UTC, merged