Pluribus Networks vrouter ospf6 module with UT
ansible/ansible pull request #51793
Opened 2019-02-06 05:01 UTC by rajaspachipulusu17

##### SUMMARY

Point feature of vrouter ospf6 for Pluribus Networks Netvisor switches 

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME
pn_vrouter_ospf6.py module with unit tests.

##### ADDITIONAL INFORMATION
ansible 2.4.0.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

```

2019-02-06 11:11 UTC, Akasurde requested changes
Rest LGTM

2019-02-06 11:11 UTC, Akasurde commented on lib/ansible/modules/network/netvisor/pn_vrouter_ospf6.py
> +
```suggestion
if VROUTER_EXISTS is False:
  module.fail_json(failed=True, msg='vRouter %s does not exist' % vrouter_name)
```

2019-02-07 14:44 UTC, Akasurde approved these changes

2019-02-07 14:44 UTC, Akasurde commented
cc @justjais

2019-02-12 08:10 UTC, ganeshrn approved these changes

2019-02-12 08:11 UTC, merged