docs: update docs about pipelining
ansible/ansible pull request #51856
Opened 2019-02-07 07:53 UTC by Akasurde

##### SUMMARY
Additional documentation about `keep_remote_files` and
`pipelining` configurations.

Fixes: #33702

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Bugfix Pull Request
- Docs Pull Request

##### COMPONENT NAME
lib/ansible/config/base.yml
lib/ansible/plugins/action/__init__.py

2019-02-07 15:28 UTC, samdoran requested changes

2019-02-07 15:28 UTC, samdoran commented on lib/ansible/config/base.yml
> +    - This options is disabled if `ANSIBLE_KEEP_REMOTE_FILES` is enabled.
```suggestion
    - This options is disabled if ``ANSIBLE_KEEP_REMOTE_FILES`` is enabled.
```

2019-02-07 15:28 UTC, samdoran commented on lib/ansible/config/base.yml
> +    - If this option is enabled, then it will disable ``ANSIBLE_PIPELINING`` option.
```suggestion
    - If this option is enabled it will disable ``ANSIBLE_PIPELINING``.
```

2019-02-12 14:41 UTC, Akasurde commented
@samdoran Could you please take another look ? Thanks.

2019-02-12 17:48 UTC, samdoran approved these changes

2019-02-12 17:49 UTC, merged