template: add additional variable for dest path
ansible/ansible pull request #52015
Opened 2019-02-11 05:03 UTC by Akasurde

##### SUMMARY
Signed-off-by: Dustin Spicuzza <dustin@virtualroadside.com>
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
lib/ansible/modules/files/template.py
lib/ansible/modules/windows/win_template.py
lib/ansible/plugins/action/template.py
lib/ansible/template/__init__.py

2019-02-12 04:09 UTC, dagwieers requested changes

2019-02-12 04:09 UTC, dagwieers commented on lib/ansible/template/__init__.py
> +        temp_vars['template_destpath'] = to_native(dest_path)
I think it's best to always provide **template_destpath**, and if it wasn't defined return `jinja.StrictUndefined` or possible `None`.

2019-02-13 12:59 UTC, Akasurde commented
@dagwieers Could you please take another look ? Thanks.

2019-02-13 13:17 UTC, gundalow approved these changes
Working and formatting looks good
Thanks for removing the "The six additional" bits

2019-02-18 17:14 UTC, Akasurde commented
@dagwieers Could you please take another look into this ? Thanks.

2019-02-19 01:05 UTC, dagwieers approved these changes

2019-02-19 08:45 UTC, merged

2019-02-19 08:45 UTC, Akasurde commented
@gundalow @dagwieers Thanks for the reviews.