Add ProxySQL to $team_mysql
ansible/ansible pull request #52054
Opened 2019-02-12 00:26 UTC by dagwieers

##### SUMMARY
Thanks to @timorunge
This relates to https://github.com/ansible/ansible/pull/51374#issuecomment-462515701.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
proxysql

2019-02-15 07:41 UTC, bmalynovytch approved these changes

2019-02-15 08:29 UTC, bmalynovytch commented
@dagwieers could you rebase ? :)

2019-02-19 12:41 UTC, gundalow requested changes
Update is good, though on hold as we are fighting some Bot issues at the moment

2019-02-22 10:17 UTC, gundalow approved these changes

2019-02-22 18:03 UTC, dagwieers commented
rebuild_merge

2019-02-22 18:40 UTC, merged