Update os_image requirements
ansible/ansible pull request #52156
Opened 2019-02-13 14:13 UTC by erolg

shade is required for this module

 FAILED! => {"changed": false, "msg": "shade is required for this module"}

+label: docsite_pr

##### SUMMARY
shade is required for this module

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
os_image

##### ADDITIONAL INFORMATION

2019-02-14 11:26 UTC, Akasurde commented
@erolg Thanks for the PR. I am sure that [`shade`](https://docs.openstack.org/shade/latest/) is deprecated in favor of [`openstacksdk`](https://docs.openstack.org/openstacksdk/latest/user/). What is your Ansible version which produces this error ? 

Thanks.

2019-02-14 11:26 UTC, Akasurde requested changes
Need one more person to confirm this.

2019-02-14 16:17 UTC, erolg commented
@Akasurde I updated issue description.

$ ansible --version
ansible 2.5.1
python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]

2019-02-15 08:13 UTC, erolg commented
I add extra info for ansible version

2019-02-19 17:50 UTC, gtema requested changes
It would not work this way. If you use old version of ansible you also use old version of module, which requires shade instead of sdk.
With your pull request you suggest to modify a current version of the module and not the old one (which was requiring shade) which is used in your case.

A reference doc: https://docs.ansible.com/ansible/2.5/modules/os_image_module.html states, that shade is required. Modern Ansible requires openstacksdk.

This pull request will not be merged this way.

2019-02-20 11:39 UTC, erolg commented
@gtema ah OK. Thank you.

2019-02-20 11:39 UTC, closed without merging