vault: Read stdin data as binary on python3
ansible/ansible pull request #52229
Opened 2019-02-14 11:37 UTC by swegener

##### SUMMARY

On python3 sys.stdin is an encoded file and does not support reading raw data. Use the buffer object of the file object to read raw binary data.

Signed-off-by: Sven Wegener <sven.wegener@inovex.de>
##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
vault

2019-02-14 22:35 UTC, sivel commented
Can you show what problem you are solving?  I cannot replicate any incorrect behavior with python3 as of now.

2019-02-15 06:15 UTC, swegener commented
Try encrypting binary data from stdin:

```
dd bs=512 count=4 if=/dev/urandom status=none | ansible-vault encrypt --vault-password=/tmp/pass --output /tmp/test.file
```

Python3's sys.stdin assumes the data is encoded according to the current locale and fails with:

```
ERROR! Unable to read source file (-): 'utf-8' codec can't decode byte 0x94 in position 4: invalid start byte
```

2019-02-19 20:44 UTC, bcoca requested changes
change looks good, but i would also add changelog entry and tests

2020-10-16 08:23 UTC, hvhaugwitz commented
Can this pull request please be merged?

2020-12-03 19:21 UTC, mattclay commented
/azp run

2020-12-08 19:25 UTC, frittentheke commented
This is a very nice PR, thank you @swegener for fixing this!

@swegener did you see the changes @bcoca requested in https://github.com/ansible/ansible/pull/52229#pullrequestreview-205441532? Any chance you could still add those?

@bcoca could we please then get this merged? Python3 is very much common on most systems nowadays.

2020-12-08 21:07 UTC, swegener commented
It already contains a unit test and I just rebased it onto the current devel branch. I can't close the review change request, because it's on a commit no longer present.

2020-12-09 08:45 UTC, mkrizek approved these changes

2020-12-09 08:46 UTC, merged