Rewrite of na_ontap_snapshot to follow NetAppModule, add new option to rename snapshot, bug fix to modify snapmirror_label
ansible/ansible pull request #52297
Opened 2019-02-14 23:04 UTC by carchi8py

##### SUMMARY
Rewrite to fit NetAppModule
Add new option from_name to rename snapshot 
bug fix to allow modifying of snapmirror_label

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME
- na_ontap_snapshot

##### ADDITIONAL INFORMATION

```paste below

```

2019-02-15 01:27 UTC, lonico commented on test/units/modules/storage/netapp/test_na_ontap_snapshot.py
> +    pytestmark = pytest.skip('skipping as missing required netapp_lib')
pytest.mark.skip

How come this one is not up to date?

2019-02-15 01:52 UTC, lonico requested changes
pytest.mark.skip

2019-02-20 20:01 UTC, lonico approved these changes
shipit

2019-03-11 15:45 UTC, thedoubl3j approved these changes
rewrite looks good, no big changes aside from qol changes and `module_utils`. Tests added always good. lgtm

2019-03-11 15:50 UTC, merged