New Module: na_ontap_snapshot_policy.py
ansible/ansible pull request #52299
Opened 2019-02-14 23:10 UTC by carchi8py

##### SUMMARY
New Module: na_ontap_snapshot_policy -- Create and delete policys
##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2019-02-15 01:25 UTC, lonico approved these changes
shipit

2019-02-15 01:30 UTC, lonico commented on test/units/modules/storage/netapp/test_na_ontap_snapshot_policy.py
> +    pytestmark = pytest.skip('skipping as missing required netapp_lib')
pytest.mark.skip

Though I'm surprised we did not see any bot error.

2019-02-15 01:47 UTC, lonico requested changes
We need to change pytest.skip to pytest.mark.skip

2019-02-20 20:01 UTC, lonico approved these changes

2019-02-20 20:09 UTC, lonico commented
shipit

2019-03-14 13:29 UTC, thedoubl3j approved these changes
Simple, documentation looks good. tests and CI are in good shape, lgtm.

2019-03-14 13:29 UTC, thedoubl3j commented
cc @thaumos

2019-03-14 13:30 UTC, merged