Add ability to run in Privileged mode to Na_ontap_command
ansible/ansible pull request #52343
Opened 2019-02-15 17:12 UTC by carchi8py

##### SUMMARY
New Option to allow running in privileged mode 

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME
- na_ontap_command.py

##### ADDITIONAL INFORMATION

```paste below

```

2019-02-16 00:07 UTC, lonico requested changes

2019-02-16 00:07 UTC, lonico commented on lib/ansible/modules/storage/netapp/na_ontap_command.py
> +        ''' calls the command and returs raw output '''
typo: returns

2019-02-16 00:07 UTC, lonico commented on test/units/modules/storage/netapp/test_na_ontap_command.py
> +    pytestmark = pytest.skip('skipping as missing required netapp_lib')
pytest.mark.skip

2019-02-20 20:03 UTC, lonico approved these changes
shipit

2019-03-19 13:50 UTC, thedoubl3j approved these changes
looks good to me, only a small nit pick that isn't a blocker.

2019-03-19 13:50 UTC, thedoubl3j commented on lib/ansible/modules/storage/netapp/na_ontap_command.py
> +        Create and Autosupport log event with the given module name
nit pick `and` -> `an`

2019-03-19 14:49 UTC, merged

2019-03-19 14:50 UTC, gundalow commented
Merged, thanks.
Typo was just in comment, so I'm OK with this as is.