New module serviceguard_facts
ansible/ansible pull request #52360
Opened 2019-02-15 19:55 UTC by sandrich

##### SUMMARY

New facts module to collect HP ServiceGuard cluster facts. This is the first out of 3 modules coming.

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME
serviceguard_facts

##### ADDITIONAL INFORMATION

```paste below
ansible 2.7.1
  config file = None
  configured module search path = ['/Users/chris/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.7.1/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.0 (default, Oct  2 2018, 09:18:58) [Clang 10.0.0 (clang-1000.11.45.2)]
```

2019-02-27 15:45 UTC, sandrich commented
bot_status

2019-03-15 15:52 UTC, sandrich commented
Anything I can do to speed up the approval process?

2019-05-13 15:08 UTC, resmo requested changes

2019-05-13 15:08 UTC, resmo commented on lib/ansible/module_utils/serviceguard.py
> +import re
missing license header (must not be gpl here)

2019-05-13 15:08 UTC, resmo commented on lib/ansible/modules/clustering/serviceguard_facts.py
> +version_added: "2.8"
please update verision to 2.9

2019-05-13 15:28 UTC, closed without merging

2019-05-13 15:33 UTC, sandrich commented
@resmo Created a new one #56358