[WIP] mysql_user: fix idempotence check for ALL GRANT In MySQL 8.0
ansible/ansible pull request #52469
Opened 2019-02-18 09:11 UTC by azeliashchonak

##### SUMMARY

In MySQL 8.0 SHOW GRANTS no longer displays ALL PRIVILEGES in its global-privileges output. Instead, SHOW GRANTS explicitly lists each granted global privilege. The issue is that the mysql_user module is using a simple comparison between new and current privileges and if we define "_._:ALL,GRANT" it will return changed, because "ALL" != list_of_privileges, so idempotence check will be failed.

##### ISSUE TYPE

- Bugfix Pull Request
##### COMPONENT NAME

mysql_user
##### ADDITIONAL INFORMATION

```paste below

```

2019-02-19 13:40 UTC, bmalynovytch requested changes

2019-02-19 13:40 UTC, bmalynovytch commented on lib/ansible/modules/database/mysql/mysql_user.py
> +            """GRANT (.+) ON (.+) TO (['`"]).*\\3@(['`"]).*\\4( IDENTIFIED BY PASSWORD (['`"]).+\5)? ?(.*)""", grant[0])
You'll need to rebase to fix the regex (see https://github.com/ansible/ansible/pull/52278/files#diff-399cf46d54197b26de359e13cb8bc033R430 )

2019-02-19 14:00 UTC, bmalynovytch approved these changes

2019-02-20 11:12 UTC, Xyon commented
Code LGTM, not tested however.

2019-02-21 09:05 UTC, azeliashchonak commented
ready_for_review

2019-02-21 09:20 UTC, bmalynovytch commented
@azeliashchonak I'm waiting for my own PR to be merged, because you'll need to rebase / rework it.
I'll review as soon as the merge + rebase will be ok

2019-02-22 09:40 UTC, azeliashchonak commented
ready_for_review

2019-02-22 09:42 UTC, tgadiev commented
@bmalynovytch can you pls take a look?

2019-02-22 09:52 UTC, bmalynovytch commented
Still waiting for #45355 to be merged before.
We need more people testing and reviewing it before it gets merged.

2019-04-11 10:26 UTC, azeliashchonak commented
Created new with clear code https://github.com/ansible/ansible/pull/55140

2019-04-11 10:26 UTC, closed without merging

2019-04-15 09:17 UTC, azeliashchonak commented
/ready_for_review