Added port_security_enabled option to openstack port
ansible/ansible pull request #52502
Opened 2019-02-18 16:13 UTC by 514amir

##### SUMMARY

Its useful to be able to set port_security_enabled to false in some specific network configuration.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

openstack
##### ADDITIONAL INFORMATION

I made the matching fix in shade https://github.com/openstack-infra/shade/pull/8 and i am waiting for the merge

```paste below

```

2019-02-19 18:00 UTC, gtema requested changes
I would prefer not setting a default value here at all. We got a problem merging port_security_enabled for the os_network (which changed accidentally the default value)

2019-02-19 18:22 UTC, gtema commented
dunplicate of #47715

2020-01-20 13:51 UTC, sshnaidm commented
Thanks for submitting patch for Openstack Ansible modules!
We moved Openstack Ansible modules to Openstack repositories.
Next patches should be submitted not with Ansible Github but with
Openstack Gerrit: https://review.opendev.org/#/q/project:openstack/ansible-collections-openstack
Please submit your code there from now.
Thanks for your contribution and sorry for inconvienience.

2020-08-19 10:31 UTC, Akasurde commented
@514amir Thanks for the contribution. Closing as per above.

2020-08-19 10:31 UTC, closed without merging