template handler _handle_src_option does not honor failures
ansible/ansible pull request #52745
Opened 2019-02-21 20:08 UTC by chrisvanheuveln

##### SUMMARY
PR #50301 moved template error handling out of run() and into its own method in `handle_src_option`; however, after the change run() ignores the return value so any errors are ignored.

My fix looks for error state and returns it if present. Verified fix with `nxos_config/tests/common/src_*` tests.

Ref:
    https://github.com/ansible/ansible/commit/71113ee291aa51f5363486537b3407204acb5a99#diff-7477bf046013758366cc85b06f90709aR43

Also updated the `src_basic.yaml` test which didn't actually test with `src:` before.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
`plugins/action/network`

##### ADDITIONAL INFORMATION
Reproduceable with `nxos_config/tests/common/src_invalid.yaml`. The symptom is that the src: string fails the template handling (as expected) but the string is sent to the device anyway.

From `src_invalid.yaml`:
```
- name: configure with invalid src
  nxos_config:
    src: basic/foobar.j2
    provider: "{{ connection }}"
  register: result
  ignore_errors: yes
```

Test output:
```paste below
    "msg": "basic/foobar.j2\r\r\n                   ^\r\n% Invalid command at '^' marker.\r\n\rn9k-109(config)# "
...
fatal: [n9k-109.cisco.com]: FAILED! => {
    "assertion": "result.msg == 'path specified in src not found'",
    "changed": false,
    "evaluated_to": false,
    "msg": "Assertion failed"
```

2019-02-21 20:18 UTC, chrisvanheuveln commented
@mikewiebe

2019-02-27 15:14 UTC, ganeshrn requested changes
The issue is similar to https://github.com/ansible/ansible/issues/52911 which is fixed by PR https://github.com/ansible/ansible/pull/52912
However, the changes in integration test are still valid. Can you please revert the changes to file `plugins/action/network.py` as it not required after PR #52912 is merged

2019-02-27 22:02 UTC, chrisvanheuveln commented
> Can you please revert the changes to file `plugins/action/network.py` as it not required after PR #52912 is merged

@ganeshrn The file has been reverted.

2019-02-28 05:36 UTC, ganeshrn approved these changes
@chrisvanheuveln Thank you!

2019-02-28 05:37 UTC, merged