Fixes #52111
ansible/ansible pull request #52853
Opened 2019-02-22 18:43 UTC by sudhirmohanraj

##### SUMMARY
Added the version name to the log generated. Fixed #52111

##### ISSUE TYPE

- Bugfix Pull Request fixes #52111

##### COMPONENT NAME
ansible/cli

##### ADDITIONAL INFORMATION
Added the version name to the log.

2019-02-22 18:43 UTC, sudhirmohanraj commented
@vmindru can you review the fix.

2019-02-22 21:47 UTC, mattclay commented
The reported sanity test failures are valid. The integration test failures are unrelated to the changes.

2019-02-25 09:15 UTC, vmindru commented
I am not sure this will help anyhow, simply printing the TAG version I have in the config is not much different than the current behavior. I would expect rather an explicit Failure cause e.g. error that the tag is missing remotely.

2019-02-26 20:29 UTC, bcoca requested changes

2019-02-26 20:29 UTC, bcoca commented on lib/ansible/cli/galaxy.py
> +                display.warning(u"- %s  and %s version was NOT installed successfully: %s " % (role.name, role.version, to_text(e)))
remove 'and' and 'version' as the name + version should be good enough to identify and the 'and' is confusion as it seems you installed (or failed to ) 2 things.

2020-01-06 06:57 UTC, Akasurde commented
@sudhirmohanraj Are you still working on this, let us know ? Thanks, needs_info

2020-02-07 13:39 UTC, closed without merging