VMware: add support for http_proxy in connection API
ansible/ansible pull request #52936
Opened 2019-02-25 16:57 UTC by Akasurde

##### SUMMARY
This fix allows users to specify http_proxy and https_proxy
while connection to vCenter or ESXi systems

Fixes: #42221

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
lib/ansible/module_utils/vmware.py
lib/ansible/plugins/doc_fragments/vmware.py
test/units/module_utils/test_vmware.py

2019-02-25 16:59 UTC, Akasurde commented
@pdellaert @dericcrago @Im0 @ckotte @jeking3 @Tomorrow9  Could you please review this ? Thanks.

2019-02-25 19:20 UTC, jamescassell requested changes
Does the module currently look at the 'http_proxy', 'https_proxy', 'no_proxy' (all lower case) env vars?  That is the de-facto standard way of configuring these items.  (These are also the only env vars I know of that are required to be lower case, rather than required as upper case.)

2019-03-04 09:37 UTC, Im0 commented
@Akasurde - this is great, thank you.  I'll try to test in the coming days.

2019-03-19 03:38 UTC, Akasurde commented
@Im0 Could you please confirm if this works for you ? 

@pdellaert @dericcrago @ckotte @jeking3 @Tomorrow9 @alongchamps @adarobin Could you please review this ?

2019-03-19 03:45 UTC, jamescassell commented
Does this change honor the no_proxy environment variable? If not, this will break for a lot of folks who have a corporate proxy but a VMware server on the local network.  I'll try to test when I get a chance, but it might be a while.

2019-03-19 15:06 UTC, alongchamps commented on lib/ansible/plugins/doc_fragments/vmware.py
> +      - If the value is not specified in the task, the value of environment variable C(https_proxy) will be used instead.
I think this line should say C(http_proxy)

2019-03-19 15:07 UTC, alongchamps commented
I unfortunately won't be able to test this due to my schedule for the next couple of weeks.

2019-03-29 23:53 UTC, Im0 commented
@Akasurde - I managed to get to test this.  Unfortunately I'm having an issue:

I've set both an environment variable, as well as, a env: https_proxy in the playbook.

Playbook:
`
  tasks:
    - name: Gather facts from standalone ESXi server having datacenter as 'ha-datacenter'
      vmware_vm_facts:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
      delegate_to: localhost
      register: facts

`

Error:
`
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "hostname": "10.0.0.100",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "username": "administrator@vsphere.lab",
            "validate_certs": false
        }
    },
    "msg": "Unsupported parameters for (vmware_vm_facts) module: _ansible_string_conversion_action Supported parameters include: hostname, password, port, proxy, proxy_port, show_attribute, username, validate_certs, vm_type"
}
`

Using: ansible 2.8.0.dev0

2019-06-05 15:12 UTC, goneri submitted a review, later dismissed

2019-06-05 15:12 UTC, goneri commented on lib/ansible/module_utils/vmware.py
> +        https_proxy=dict(type='str',
I think we should just expose a `proxy_host` and and `proxy_port` parameters. This way we avoid all the complexity of the URL parsing and we don't need to deal with the environment variables (https_proxy/http_proxy/HTTPS_PROXY/no_proxy/etc).

2019-06-05 15:12 UTC, goneri commented on lib/ansible/module_utils/vmware.py
> +def parse_proxy_url(module, proxy_url):
as a consequence, this method would not be necessary anymore.

2019-06-06 13:46 UTC, goneri commented
I pushed a PR against your branch here https://github.com/Akasurde/ansible/pull/6

- simplify the way we pass the proxy paramerer with just two new parameters.
- simplify a bit the way we format the error message ensure vmware_host can also collaborate with a proxy
- add a changelog entry.

This PR depends on vmware/pyvmomi#799.

2019-07-29 10:44 UTC, felixfontein commented
vmware/pyvmomi#799 has been merged; what's the current state of this?

2019-07-30 12:24 UTC, goneri commented
Hi @pgbidkar, Could you push a pyvmomi release that include the HTTP support?

2019-07-30 15:41 UTC, pgbidkar commented
> Hi @pgbidkar, Could you push a pyvmomi release that include the HTTP support?

Hi @goneri , We have planned release by end of August. This change will be included in same release.
Thanks

2019-07-31 11:59 UTC, goneri approved these changes
Works fine with Worldstream

2019-08-01 13:57 UTC, merged