fix #46187: Adds injected_file_content_bytes and injected_file_path_b…
ansible/ansible pull request #52955
Opened 2019-02-25 22:40 UTC by userlerueda

…ytes

##### SUMMARY
Adds injected_file_content_bytes and injected_file_path_bytes in order to fix the problem described in #46187

Fixes #46187

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
os_quota.py

##### ADDITIONAL INFORMATION
Tested using the new options
```
$ ansible-playbook test/develop/set_quotas.yaml

PLAY [Test os_quotas] ****************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Get quotas before changing] ****************************************************************************************************************************************************************************************
ok: [localhost]

TASK [debug] *************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "before.openstack_quotas.compute.injected_file_content_bytes": "65536"
}

TASK [Set quotas] ********************************************************************************************************************************************************************************************************
changed: [localhost]

TASK [Get quotas after changing] *****************************************************************************************************************************************************************************************
ok: [localhost]

TASK [debug] *************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "after.openstack_quotas.compute.injected_file_content_bytes": "888"
}

PLAY RECAP ***************************************************************************************************************************************************************************************************************
localhost                  : ok=6    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

2019-02-26 15:00 UTC, mnaser commented
shipit

2019-02-28 18:18 UTC, userlerueda commented
bot_status

2019-03-06 17:02 UTC, userlerueda commented
Can we get another shipit ?

2019-10-25 15:53 UTC, ignatenkobrain commented
@mnaser ping

2019-10-29 10:12 UTC, ignatenkobrain commented
shipit

2019-10-29 11:13 UTC, ignatenkobrain commented
@emonty @Shrews could you please take a look on this & merge? I've tested it and it works just fine.

2019-10-29 11:33 UTC, gtema commented
recheck

2019-10-29 12:31 UTC, gtema commented
shipit

2020-01-03 16:49 UTC, cloudnull requested changes
The version_added key needs to be set to 2.10, otherwise this looks fine.

2020-01-03 16:49 UTC, cloudnull commented on lib/ansible/modules/cloud/openstack/os_quota.py
> +        version_added: "2.8"
These lines need to be changed to 2.10. Sadly I cant edit this file for you.

2020-01-20 13:50 UTC, sshnaidm commented
Thanks for submitting patch for Openstack Ansible modules!
We moved Openstack Ansible modules to Openstack repositories.
Next patches should be submitted not with Ansible Github but with
Openstack Gerrit: https://review.opendev.org/#/q/project:openstack/ansible-collections-openstack
Please submit your code there from now.
Thanks for your contribution and sorry for inconvienience.

2020-08-19 10:34 UTC, Akasurde commented
@userlerueda Thanks for the contribution. Closing as per above.

2020-08-19 10:34 UTC, closed without merging