VMware: make properties configurable
ansible/ansible pull request #53050
Opened 2019-02-27 05:44 UTC by Akasurde

##### SUMMARY
This allows user to control set of properties which can be included
in the hostvars.

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
lib/ansible/plugins/inventory/vmware_vm_inventory.py

2019-02-27 06:57 UTC, Akasurde commented
cc @angystardust I made properties configurable. This will help to improvise performance while gathering VM inventory.

2019-02-27 06:57 UTC, Akasurde commented
@pdellaert @dericcrago @Im0 @jeking3  Could you please review this ?

2019-02-27 08:01 UTC, angystardust commented
One more thing I would like to have in the new inventories (both for vms and esxi hosts) that was possibile in the older inventory script is the `alias_pattern` parameter to alter the default inventory object names (so, for example, one can choose to strip the uuid)
Right now I’m editing the Python file in order to do that :)

2019-02-27 13:30 UTC, jeking3 commented
Does this build on the work I did in vmware_guest_facts and pyVmomi to extract raw vSphere API properties?

2019-03-04 16:54 UTC, Akasurde commented
> Does this build on the work I did in vmware_guest_facts and pyVmomi to extract raw vSphere API properties?

No. Since your fix is available in 6.7 and onwards. But I can include that change as well with fallback mechanism.

2019-03-04 16:57 UTC, adarobin approved these changes
LGTM

2019-03-04 17:03 UTC, alongchamps approved these changes
LGTM

2019-03-05 18:20 UTC, jeking3 commented
> > Does this build on the work I did in vmware_guest_facts and pyVmomi to extract raw vSphere API properties?
> 
> No. Since your fix is available in 6.7 and onwards. But I can include that change as well with fallback mechanism.

Just to clarify, you need `pyvmomi>6.7.1` to get the pyVmomi json conversion of vSphere objects.

2019-05-08 18:53 UTC, jeking3 requested changes
I haven't worked on an inventory module before, but I'm wondering why the list of default properties is what it is.

2019-05-08 18:53 UTC, jeking3 commented on lib/ansible/plugins/inventory/vmware_vm_inventory.py
> +            - Specify the list of Property associated with VM.
```suggestion
            - Specify the list of VMware schema properties associated with the VM.
```

2019-05-08 18:53 UTC, jeking3 commented on lib/ansible/plugins/inventory/vmware_vm_inventory.py
> +            - Each value in list specifies the path to a specific property in VM object.
```suggestion
            - Each value in the list specifies the path to a specific property in VM object.
```

2019-05-08 18:53 UTC, jeking3 commented on lib/ansible/plugins/inventory/vmware_vm_inventory.py
> +            default: [ 'name', 'config.cpuHotAddEnabled', 'config.cpuHotRemoveEnabled',
tags?

Does it make sense to have a default list of properties?

2019-07-24 09:48 UTC, merged