add another automatic group by tag name (which can easily set when...
ansible/ansible pull request #53165
Opened 2019-03-01 08:41 UTC by desmap

…creating Vultr instances via Ansible)

##### ISSUE TYPE
- Feature Pull Request
- New Module Pull Request

##### COMPONENT NAME
vultr plugin

2019-03-01 18:52 UTC, bcoca requested changes
to support those features you just need to inherit from Constructable, seems a lot more useful than updating the code each time you want new groups (also it forces these groups on other users that might already be happy with current output).

2019-03-02 07:27 UTC, desmap commented
> you just need to inherit from Constructable

Could you pls elaborate on this? Thx.

> seems a lot more useful than updating the code each time you want new groups

I think you might missed the point. The 'tag' field at Vultr is exactly for this use case, to just add any kind of group/filter/whatever you like without updating the code each time you want new groups. It gives you full freedom/flexibility and you can set it to any value you want. Leaving this important field out feels even more like a bug than a feature. I'll edit my PR on this regard.

I could say that for all my use case a default region-based setting like it is now implemented, is completely useless. All my system are global/CDN-like and I never change their state based on a region.

So, I think that this Vultr plugin without 'tag'-support, without all the nice things the AWS-EC2-plugins has (keyed groups, groups, etc.) is a nice toy but not really for production. Hence, I'd love to see Vultr's 'tag' field supported.

2019-03-02 14:27 UTC, chopraaa commented
@desmap He's not against it, he's just advising that you use `Constructable`: https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/inventory/__init__.py#L295

This allows you to specify how you want to list your inventory instead of hardcoding it. Unfortunately, I don't know much about this and there's not a lot to go by in the [docs](https://docs.ansible.com/ansible/latest/dev_guide/developing_inventory.html) for me but you can give it a shot.

2019-03-02 20:49 UTC, desmap commented
@chopraaa, thanks for your comment. Ok, maybe I got @bcoca wrong but I am not a Pyhton-native and still don't understand his idea. So, I would be happy if he or whoever could make a suggestion. Thx

2019-03-04 18:30 UTC, bcoca commented
other plugins (ec2) also use this to allow user to use any 'cloud field' to create groups according to user logic. `tags` are also available on ec2 and a good example for `keyed_groups` feature.

2019-03-05 07:46 UTC, desmap commented
> other plugins (ec2) also use this to allow user to use any 'cloud field' to create groups according to user logic. `tags` are also available on ec2 and a good example for `keyed_groups` feature.

@bcoca hm... this is exactly what I am saying: the AWS-EC2 has all this fancy stuff while the Vultr plugin does **not** have any of them just OS and region hard-coded and that we need to change that. Or I didn't get your message again... 

So what's next? I am not a Python guy and should not mess more with that code base, I mean I can try if you tell what should be exactly done beyond my extra 'tag' field. Btw, what's with @Spredzy? Any opinions, you wrote the plugin, would be awesome if you sent a sign of life!

Or should I switch to Terraform, I mean look what full-fledged solution they have => https://github.com/squat/terraform-provider-vultr?  Compared to them, the Ansible-Vultr-plugin feels like...

@bcoca, @Spredzy, c'mon let's either fix this asap (merge my PR or make a better suggestion) or just decide against, then I know where I am at and can move on. A weeks long discussion wouldn't be appropriate here. 

Looking forward to next steps!

2019-03-15 15:33 UTC, resmo commented
@desmap Thanks for your time, because we run out of time for 2.8, I implemented this in

Superseded by #53869

2019-03-19 06:26 UTC, closed without merging