Fix wrong number of arguments in string format
ansible/ansible pull request #53265
Opened 2019-03-04 10:22 UTC by Akasurde

##### SUMMARY
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/config/manager.py

2019-03-04 19:05 UTC, bcoca requested changes

2019-03-04 19:05 UTC, bcoca commented on lib/ansible/config/manager.py
> +            raise AnsibleError("Unhandled exception when retrieving %s" % config, orig_exc=e)
i would actually add the exception message to_native(e) instead, which was my original intention

2019-03-05 20:32 UTC, bcoca approved these changes

2019-03-05 20:32 UTC, merged

2019-03-06 02:04 UTC, Akasurde commented
@bcoca Thanks for the review.