Python 2: accept both long and int for type=int (module options)
ansible/ansible pull request #53289
Opened 2019-03-04 19:49 UTC by felixfontein

##### SUMMARY
If a user passes large integers to a module option, the module will not accept them under Python 2 because they will be of type `long` and not of type `int`.

Fixes #53225.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/module_utils/basic.py

2019-03-04 20:10 UTC, samdoran requested changes
This fix looks good. The unit tests need a few more adjustments to pass. Something like this should do the trick.

```diff
diff --git a/test/units/module_utils/basic/test_argument_spec.py b/test/units/module_utils/basic/test_argument_spec.py
index a402eb2aad..f548ba5a51 100644
--- a/test/units/module_utils/basic/test_argument_spec.py
+++ b/test/units/module_utils/basic/test_argument_spec.py
@@ -14,7 +14,7 @@ import pytest
 
 from units.compat.mock import MagicMock, patch
 from ansible.module_utils import basic
-from ansible.module_utils.six import string_types
+from ansible.module_utils.six import string_types, integer_types, PY2
 from ansible.module_utils.six.moves import builtins
 
 from units.mock.procenv import ModuleTestCase, swap_stdin_and_argv
@@ -183,7 +183,10 @@ def test_validator_basic_types(argspec, expected, stdin):
     am = basic.AnsibleModule(argspec)
 
     if 'type' in argspec['arg']:
-        type_ = getattr(builtins, argspec['arg']['type'])
+        if PY2 and argspec['arg']['type'] == 'int':
+            type_ = integer_types
+        else:
+            type_ = getattr(builtins, argspec['arg']['type'])
     else:
         type_ = str
 
@@ -198,7 +201,7 @@ def test_validator_function(mocker, stdin):
     argspec = {'arg': {'type': MOCK_VALIDATOR_SUCCESS}}
     am = basic.AnsibleModule(argspec)
 
-    assert isinstance(am.params['arg'], int)
+    assert isinstance(am.params['arg'], integer_types)
     assert am.params['arg'] == 27
```

2019-03-04 20:23 UTC, felixfontein commented
Thanks for the unit test update! I've integrated it, and added one `long` example to `test_validator_function()`.

BTW: why the `PY2` condition? For Python 3, `six.integer_types` contains only `int`, so `type_ = integer_types` should work there as well (and yield the same result).

2019-03-04 21:45 UTC, samdoran commented
You're right: no need for the `PY2` test. This works just fine:
```diff
diff --git a/test/units/module_utils/basic/test_argument_spec.py b/test/units/module_utils/basic/test_argument_spec.py
index a4e42a3406..e5f6126a9c 100644
--- a/test/units/module_utils/basic/test_argument_spec.py
+++ b/test/units/module_utils/basic/test_argument_spec.py
@@ -185,7 +185,7 @@ def test_validator_basic_types(argspec, expected, stdin):
     am = basic.AnsibleModule(argspec)
 
     if 'type' in argspec['arg']:
-        if PY2 and argspec['arg']['type'] == 'int':
+        if argspec['arg']['type'] == 'int':
             type_ = integer_types
         else:
             type_ = getattr(builtins, argspec['arg']['type'])
```

2019-03-04 21:46 UTC, samdoran approved these changes

2019-03-04 22:01 UTC, samdoran approved these changes

2019-03-05 07:27 UTC, felixfontein commented
ready_for_review

2019-03-05 14:39 UTC, merged