Module seboolean: added support for list syntax for name parameter
ansible/ansible pull request #53608
Opened 2019-03-10 16:53 UTC by esantoro

The new syntax allows the following (previously not possible):

```
- name: set all the above selinux booleans using list syntax
  seboolean:
    # old syntax (still available and working):
    #name: samba_share_nfs
    # new syntax:
    name: [samba_share_nfs, samba_export_all_ro, samba_export_all_rw]
    state: yes
    persistent: yes
```

Note: this commit does not break old syntax in my tests.

I agree to Ansible's Contributors License Agreement as stated in https://docs.ansible.com/ansible/latest/community/contributor_license_agreement.html

2019-03-10 16:56 UTC, esantoro commented
Here is an ansible playbook sampling the new possibilities:

```
---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: install seboolean-python
      yum:
        name: libsemanage-python
        state: present
    
    - name: set samba_share_nfs selinux boolean using old syntax
      seboolean:
        name: samba_share_nfs
        state: yes
        persistent: yes

    - name: set samba_export_all_ro selinux boolean using old syntax
      seboolean:
        name: samba_export_all_ro
        state: yes
        persistent: yes

    - name: set samba_export_all_rw selinux boolean using old syntax
      seboolean:
        name: samba_export_all_rw
        state: yes
        persistent: yes


    - name: set all the above selinux booleans using list syntax
      seboolean:
        #name: samba_share_nfs
        name: [samba_share_nfs, samba_export_all_ro, samba_export_all_rw]
        state: no
        persistent: yes

    - name: set all the above selinux booleans using items syntax
      seboolean:
        #name: samba_share_nfs
        name: "{{ item }}"
        state: yes
        persistent: yes
      with_items:
        - samba_share_nfs
        - samba_export_all_ro
        - samba_export_all_rw

    - name: set them all again to for testing purpose
      ## this is to be able to run the playbook over and over again
      seboolean:
        #name: samba_share_nfs
        name: "{{ item }}"
        state: no
        persistent: yes
      with_items:
        - samba_share_nfs
        - samba_export_all_ro
        - samba_export_all_rw
```

In my tests I am able to run such playbook (thus mixing old syntax and new syntax) without issues.

2019-03-10 17:56 UTC, esantoro commented
As suggested by felixfontein on irc (#ansible-devel on freenode) in commit ec0cc8d i am returning a string if the name parameter is a single name, and a list of names if multiple selinux boolean names are provided.

2019-03-10 18:50 UTC, esantoro commented
All checks are passing now. I can squash all commits into one, if needed.

2019-03-11 18:43 UTC, esantoro commented
ready_for_review

2019-03-13 10:14 UTC, esantoro commented
@sfromm any news ?

2019-03-20 16:33 UTC, esantoro commented
@sfromm any news ?

2019-03-28 14:37 UTC, jamescassell requested changes
I'd like to have the module remain atomic -- either all changes are applied or none.

2019-03-28 14:37 UTC, jamescassell commented on lib/ansible/modules/system/seboolean.py
> +                    try:
I'd move this entire block outside of the loop to ensure the module is atomic.

2019-03-28 14:37 UTC, jamescassell commented on lib/ansible/modules/system/seboolean.py
> +            changed = semanage_boolean_value(module, name, state)
I'd want to see the role stay atomic and have either everything or nothing change.  If the module fails, nothing should change on the system.  That might either mean moving the loop into the `semanage_boolean_value` function, or supporting externally-triggered commit for the function.

2020-08-16 09:04 UTC, closed without merging