add template version
ansible/ansible pull request #53636
Opened 2019-03-11 15:42 UTC by mnecas

##### SUMMARY

@machacekondra I had some issues with setting version number, maybe you could see where I made mistake.

Fixes #53620
##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

ovirt
##### ADDITIONAL INFORMATION

```paste below

```

2019-03-12 07:37 UTC, machacekondra commented on lib/ansible/modules/cloud/ovirt/ovirt_template.py
> +                version_number=self._module.params['version']['number'],
please use here `self.param('version').get('number')`

2019-03-12 07:37 UTC, machacekondra commented on lib/ansible/modules/cloud/ovirt/ovirt_template.py
> +                    name=self._module.params['version']['base_template']
please use here `self.param('version').get('base_template')`

2019-03-12 07:38 UTC, machacekondra commented on lib/ansible/modules/cloud/ovirt/ovirt_template.py
> +                ) if self._module.params['version'].get('base_template') else None,
please use here self.param('version').get('base_template')

2019-03-12 07:38 UTC, machacekondra commented on lib/ansible/modules/cloud/ovirt/ovirt_template.py
> +                version_name=self._module.params['version']['name'] if self._module.params['version'].get('name') else None,
please use here self.param('version').get('name')

2019-03-12 07:38 UTC, machacekondra commented on lib/ansible/modules/cloud/ovirt/ovirt_template.py
> +            )if self._module.params['version'] else None,
please use here `self.param('version')`

2019-03-12 07:38 UTC, machacekondra commented on lib/ansible/modules/cloud/ovirt/ovirt_template.py
> +            )if self._module.params['version'] else None,
and please add space after `)`

2019-03-12 07:39 UTC, machacekondra requested changes
Code looks ok, just few formatting comments

2019-03-12 12:27 UTC, machacekondra commented on lib/ansible/modules/cloud/ovirt/ovirt_template.py
> +                    name=self._module.params('version').get('base_template')
Please use `self.param('')` instead of self._module.params()

2019-03-12 13:54 UTC, machacekondra commented on lib/ansible/modules/cloud/ovirt/ovirt_template.py
> +                version_name=self.param('version').get('name') if self.param('version').get('name') else None,
the `if` isn't needed here

2019-03-12 13:54 UTC, machacekondra commented on lib/ansible/modules/cloud/ovirt/ovirt_template.py
> +                version_number=self.param('version').get('number') if self.param('version').get('number') else None,
the `if` isn't needed here

2019-03-19 08:44 UTC, mwperina approved these changes
Looks good to me. Ondro?

2019-03-20 19:27 UTC, machacekondra commented on lib/ansible/modules/cloud/ovirt/ovirt_template.py
> +            - "C(base_template) - ID of the referenced template that this version is associated with."
Can we use (also) name?

2019-03-20 19:27 UTC, machacekondra commented on lib/ansible/modules/cloud/ovirt/ovirt_template.py
> +        templates = templates_service.list()
Can you please add this logic to some method called `find_template` so you don't have to reimplenet the logic of update/create.

2019-03-20 19:27 UTC, machacekondra commented on lib/ansible/modules/cloud/ovirt/ovirt_template.py
> +            - "C(base_template) - ID of the referenced template that this version is associated with."
Please add some example of how to use this parameter into EXAMPLES section.

2019-03-29 08:01 UTC, machacekondra commented on lib/ansible/modules/cloud/ovirt/ovirt_template.py
> +            if entity is None:
Can you please add this condition to `find_subversion_template` function?

2019-03-29 08:04 UTC, machacekondra commented on lib/ansible/modules/cloud/ovirt/ovirt_template.py
> +            force_create = False
Please write a better comment like:

When user want to create new template subversion, we must make sure template is force created as it already exists, but new version should be created.

2019-03-29 08:04 UTC, machacekondra commented on lib/ansible/modules/cloud/ovirt/ovirt_template.py
> +            force_create = False
An maybe put it directly to create call like:

```python
ret = templates_module.create(
  entity=entity,
  # When user want to create new template subversion, we must make sure template is force created as it already exists, but new version should be created.
  force_create=entity is None and module.params['version'] is not None,
  ...
)
```

2019-03-29 12:05 UTC, machacekondra commented on lib/ansible/modules/cloud/ovirt/ovirt_template.py
> +            resp = template
Just add return here, no need for break and creating resp variable.

```python
    version = module.params.get('version')
    templates = templates_service.list()
    for template in templates:
        if version.get('number') == template.version.version_number and module.params.get('name') == template.name:
	    return template

    raise ValueError(
	            "Template with name '%s' and version '%s' in cluster '%s' was not found'" % (
	                module.params['name'],
	                module.params['version']['number'],
	                module.params['cluster'],
	            )
	        )
```

2019-04-01 08:09 UTC, machacekondra commented on lib/ansible/modules/cloud/ovirt/ovirt_template.py
> +    raise ValueError(
Well actually, should we in this case return new version of that template, rather then raise Exception?

2019-04-01 09:42 UTC, machacekondra commented on lib/ansible/modules/cloud/ovirt/ovirt_template.py
> +    raise ValueError(
Please ignore, this is called when non-existin number is passed. So it's ok

2019-04-01 09:44 UTC, machacekondra commented
shipit

2019-04-01 13:26 UTC, closed without merging