AWS: new module ec2_transit_gateway fixes #49376
ansible/ansible pull request #53651
Opened 2019-03-11 19:15 UTC by BobBoldin

##### SUMMARY
AWS: new module ec2_transit_gateway Fixes #49376

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME
ec2_transit_gateway

2019-03-11 19:17 UTC, BobBoldin commented
The integration tests will fail until following permissions are added:

        {
            "Sid": "AllowTransitGatewayManagement",
            "Effect": "Allow",
            "Action": [
                "ec2:CreateTransitGateway",
                "ec2:DeleteTransitGateway",
                "ec2:DescribeTransitGateways"
            ],
            "Resource": "*"
        }

2019-03-12 10:15 UTC, BobBoldin commented
ready_for_review

2019-03-12 12:04 UTC, willthames commented on test/integration/targets/ec2_transit_gateway/tasks/main.yml
> +#  no_log: yes
Please uncomment this :)

2019-03-12 12:16 UTC, willthames commented
I'll let @mattclay weigh in on this, but I'd be happy to merge this if it used the unsupported alias for now - the test suite passes fine for me locally

2019-03-12 12:17 UTC, willthames requested changes
Needs no_log fix but no other issues once that's addressed.

2019-03-13 19:54 UTC, BobBoldin commented
ready_for_review

2019-03-13 23:42 UTC, willthames approved these changes

2019-03-13 23:42 UTC, merged

2019-03-13 23:43 UTC, willthames commented
Merged, thanks @BobBoldin, that was a flawless attempt for a first module!

2019-03-29 20:41 UTC, mattclay commented
The tests for this module have been enabled in CI: https://github.com/ansible/ansible/pull/54619

However, they are currently marked unstable as they sometimes try to delete the transit gateway while it is in the pending state:

https://app.shippable.com/github/ansible/ansible/runs/116823/104/console