Add workspace module for azure
ansible/ansible pull request #53731
Opened 2019-03-13 06:44 UTC by yuwzho

##### SUMMARY

Azure workspace module which is used for container  monitoring like AKS

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2019-03-13 08:50 UTC, yuwzho commented
@mattclay The Ansible CI  is not register to `OperationInsight` namespaces. Could you please help me to do the registeration? ref: [Resolve errors for resource provider registration](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-register-provider-errors)

2019-03-13 14:02 UTC, mattclay commented
@yuwzho `Microsoft.OperationalInsights` has been registered and the tests restarted.

2019-03-14 00:24 UTC, nitzmahone commented on lib/ansible/modules/cloud/azure/azure_rm_workspace.py
> +module: azure_rm_workspace
should probably be `azure_rm_loganalyticsworkspace` or something; "workspace" seems awfully generic

2019-03-14 00:25 UTC, nitzmahone commented on lib/ansible/modules/cloud/azure/azure_rm_workspace_facts.py
> +module: azure_rm_workspace_facts
... and match whatever the module above ends up being called

2019-03-14 00:27 UTC, nitzmahone commented on lib/ansible/modules/cloud/azure/azure_rm_workspace.py
> +RETURN = '''
documented results keys don't appear to match actual results returned

2019-03-14 00:28 UTC, nitzmahone requested changes
just name bikeshedding and results docs, otherwise looks OK to me

2019-03-15 01:59 UTC, yuwzho commented
ready_for_review

2019-03-18 03:09 UTC, Fred-sun commented
@yungezz @zikalino review_need

2019-03-18 08:01 UTC, yungezz commented on lib/ansible/module_utils/azure_rm_common.py
> +            self._log_analytics_client = self.get_mgmt_svc_client(LogAnalyticsManagementClient,
no api version?

2019-03-18 08:01 UTC, yungezz commented on lib/ansible/modules/cloud/azure/azure_rm_loganalyticsworkspace.py
> +        default: per_gb2018
why default?

2019-03-18 08:01 UTC, yungezz commented on lib/ansible/modules/cloud/azure/azure_rm_loganalyticsworkspace.py
> +            - "Enable one pack by setting it to C(true). E.g. {'Backup': true}."
didn't get it, what's backup mean? are keys of the dict random?  or choices?

2019-03-18 08:01 UTC, yungezz commented on lib/ansible/modules/cloud/azure/azure_rm_loganalyticsworkspace.py
> +location:
return those info in main module?

2019-03-18 08:01 UTC, yungezz commented on lib/ansible/modules/cloud/azure/azure_rm_loganalyticsworkspace_facts.py
> +short_description: Manage Azure Log Analytics workspaces.
Get facts of xxx

2019-03-19 01:56 UTC, yuwzho commented on lib/ansible/module_utils/azure_rm_common.py
> +            self._log_analytics_client = self.get_mgmt_svc_client(LogAnalyticsManagementClient,
no

2019-03-19 02:19 UTC, yuwzho commented on lib/ansible/modules/cloud/azure/azure_rm_loganalyticsworkspace.py
> +        default: per_gb2018
According to Azure CLI and docs, they use the per_gb2018 as default SKU.

2019-03-19 02:22 UTC, yuwzho commented on lib/ansible/modules/cloud/azure/azure_rm_loganalyticsworkspace.py
> +            - "Enable one pack by setting it to C(true). E.g. {'Backup': true}."
I didn't find an official docs here. My understanding this is a list contains many configurations of the workspace. `backup` is one of the configurations. All the list with value will be returned in this module and facts module

2019-03-21 02:47 UTC, yuwzho commented
ready_for_review

2019-03-26 02:43 UTC, Fred-sun commented
@yungezz @zikalino Please help review this PR when you're available! Thanks!

2019-03-28 00:04 UTC, nitzmahone approved these changes

2019-03-28 00:04 UTC, merged