add vnet facts module
ansible/ansible pull request #53942
Opened 2019-03-18 09:26 UTC by yungezz

##### SUMMARY

add azure_rm_virtualnetworkpeering_facts module

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2019-03-18 17:17 UTC, bcoca requested changes
this module does NOT return `ansible_facts` so it should not be a _facts module

2019-03-18 22:06 UTC, zikalino requested changes
one major thing to change is **virtual_network** parameter.
others are minor

2019-03-18 22:06 UTC, zikalino commented on lib/ansible/modules/cloud/azure/azure_rm_virtualnetworkpeering_facts.py
> +# Copyright (c) 2019 Yunge Zhu <yungez@microsoft.com>
(@yungezz)

2019-03-18 22:06 UTC, zikalino commented on lib/ansible/modules/cloud/azure/azure_rm_virtualnetworkpeering_facts.py
> +    virtual_network:
is that actually correct?
virtual network peering is a subresource of virtual network, so I think this param should be just a **virtual_network_name**
The description looks like description for **virtual_remote_network**

2019-03-18 22:06 UTC, zikalino commented on lib/ansible/modules/cloud/azure/azure_rm_virtualnetworkpeering_facts.py
> +        name: vnet_peer1
i would move name param to the end, just for consistency.
ALso we could call it **myVnetPeering**

2019-03-18 22:06 UTC, zikalino commented on lib/ansible/modules/cloud/azure/azure_rm_virtualnetworkpeering_facts.py
> +            self.log('Did not find the Virtual Network Peering.')
fail?

2019-03-18 22:13 UTC, zikalino commented
@bcoca this is something we have been discussing with @nitzmahone and @jborean93 . 
At some point we have agreed that cloud resource related modules should not stick facts into **ansible_facts**.
Apparently facts should apply to the host where playbook is executed, but in case of azure_rm_*_facts are always executed on localhost.

2019-03-21 00:32 UTC, nitzmahone commented
Policy on `_facts` will change in 2.9 (changing to `_info` and we'll alias), but for now, it's not a blocker to merge for 2.8.

2019-03-21 03:06 UTC, yungezz commented
ready_for_review

2019-03-21 03:07 UTC, yungezz commented
HI  @bcoca  could you pls look at the pr  again?  it's  updated and discussed with Matt about the _facts.

2019-03-21 03:23 UTC, zikalino approved these changes

2019-03-21 03:27 UTC, zikalino commented
shipit

2019-03-26 02:14 UTC, Fred-sun commented
@bcoca Please help re-review this PR when you're available! Thanks!

2019-03-26 14:30 UTC, bcoca requested changes
these are still improperly named _facts while not returning ansible_facts, the rename to _info is a new requirement and not a blocker, but them being improperly named _facts is a blocker.

2019-04-02 20:59 UTC, nitzmahone approved these changes
now that https://github.com/ansible/ansible/issues/54280#issuecomment-479171217 has been settled, good to merge.

2019-04-03 01:34 UTC, yungezz commented
rebuild_merge

2019-04-03 14:22 UTC, yungezz commented
per IRC core meeting result as commented in https://github.com/ansible/ansible/issues/54280#issuecomment-479172664, keep this module as _facts for 2.8. and update it later.

2019-04-03 14:22 UTC, merged