Add Bitbucket Pipelines variable module
ansible/ansible pull request #54049
Opened 2019-03-19 16:11 UTC by catcombo

##### SUMMARY

Manages [Bitbucket](http://bitbucket.org/) Pipelines variables.

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

bitbucket_pipelines_variable

2019-03-19 16:31 UTC, zyv commented
/cc @marns93

2019-03-20 07:16 UTC, zyv commented
@Akasurde could you please be so kind to help us to find reviewers for this new module? We tried our best to produce a clean one according to the community guidelines and it also has full test coverage to ease reviews. Thank you!

Besides, we are aiming to open source a few more Bitbucket modules, but they all build upon this PR. What would be the best way to proceed? Wait until this one is through and open more PRs, one PR per new module?

/cc @dagwieers hi there, here I come :-) 🍻

2019-03-20 15:27 UTC, dagwieers requested changes
Looks good. A few cosmetic changes only. I did not test the module.

2019-03-20 15:27 UTC, dagwieers commented on lib/ansible/module_utils/bitbucket.py
> +# Simplified BSD License (see licenses/simplified_bsd.txt or https://opensource.org/licenses/BSD-2-Clause)
```suggestion
# -*- coding: utf-8 -*-

# Simplified BSD License (see licenses/simplified_bsd.txt or https://opensource.org/licenses/BSD-2-Clause)
```

2019-03-20 15:27 UTC, dagwieers commented on lib/ansible/modules/source_control/bitbucket_pipelines_variable.py
> +#!/usr/bin/python
```suggestion
#!/usr/bin/python
# -*- coding: utf-8 -*-
```

2019-03-20 15:27 UTC, dagwieers commented on lib/ansible/modules/source_control/bitbucket_pipelines_variable.py
> +DOCUMENTATION = '''
```suggestion
DOCUMENTATION = r'''
```

2019-03-20 15:27 UTC, dagwieers commented on lib/ansible/modules/source_control/bitbucket_pipelines_variable.py
> +      - OAuth consumer key. If not set the environment variable C(BITBUCKET_CLIENT_ID) will be used.
```suggestion
      - OAuth consumer key. If not set the environment variable C(BITBUCKET_CLIENT_ID) will be used.
    type: str
```

2019-03-20 15:27 UTC, dagwieers commented on lib/ansible/modules/source_control/bitbucket_pipelines_variable.py
> +      - OAuth consumer secret. If not set the environment variable C(BITBUCKET_CLIENT_SECRET) will be used.
```suggestion
      - OAuth consumer secret. If not set the environment variable C(BITBUCKET_CLIENT_SECRET) will be used.
    type: str
```

2019-03-20 15:27 UTC, dagwieers commented on lib/ansible/modules/source_control/bitbucket_pipelines_variable.py
> +      - Repository name.
```suggestion
      - Repository name.
    type: str
```

2019-03-20 15:27 UTC, dagwieers commented on lib/ansible/modules/source_control/bitbucket_pipelines_variable.py
> +      - Repository owner.
```suggestion
      - Repository owner.
    type: str
```

2019-03-20 15:27 UTC, dagwieers commented on lib/ansible/modules/source_control/bitbucket_pipelines_variable.py
> +      - Pipeline variable name.
```suggestion
      - Pipeline variable name.
    type: str
```

2019-03-20 15:27 UTC, dagwieers commented on lib/ansible/modules/source_control/bitbucket_pipelines_variable.py
> +      - Pipeline variable value.
```suggestion
      - Pipeline variable value.
    type: str
```

2019-03-20 15:27 UTC, dagwieers commented on lib/ansible/modules/source_control/bitbucket_pipelines_variable.py
> +      - Indicates desired state of the variable.
```suggestion
      - Indicates desired state of the variable.
    type: str
```

2019-03-20 15:27 UTC, dagwieers commented on lib/ansible/modules/source_control/bitbucket_pipelines_variable.py
> +EXAMPLES = '''
```suggestion
EXAMPLES = r'''
```

2019-03-20 15:27 UTC, dagwieers commented on lib/ansible/modules/source_control/bitbucket_pipelines_variable.py
> +RETURN = ''' # '''
```suggestion
RETURN = r''' # '''
```

2019-03-20 15:31 UTC, dagwieers commented
@zyv Yes, it's best to get the module_utils in first, and then add the rest.
Also, the community freeze is next week, which does not give a lot of time to get these included in Ansible 2.8.

Going forward, it could help to tap into the existing Bitbucket community to find people that need/use these modules and form a Working Group to increase the testing "clout".

2019-03-21 11:08 UTC, catcombo commented
@ansibot ready_for_review

2019-03-21 18:16 UTC, dagwieers approved these changes

2019-03-21 18:19 UTC, zyv approved these changes
Awesome 👍

2019-03-22 12:17 UTC, dagwieers approved these changes
LGTM, thanks !

2019-03-22 12:17 UTC, merged

2019-03-22 12:18 UTC, dagwieers commented
@marns93 You can now create PRs for the other modules. Please take into account all remarks we made for this module. Thanks!

2019-03-22 12:23 UTC, zyv commented
@dagwieers oh wow, thanks! 🎉 

Just to set the record straight ;), the maintainers will be @zyv (me), @marns93 and @catcombo. We'll take into account your comments for this module, clean up other modules to match style, and make new PRs, hopefully today still.