docs: Add example of anchor and aliases in playbook
ansible/ansible pull request #54079
Opened 2019-03-20 04:25 UTC by Akasurde

##### SUMMARY
YAML supports anchors and aliases, add examples for explaining
this functionality with respect to Ansible playbook.

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
docs/docsite/rst/user_guide/playbooks_advanced_syntax.rst

2019-03-20 17:43 UTC, samccann commented on docs/docsite/rst/user_guide/playbooks_advanced_syntax.rst
> +If you want to refer to the same object from different parts of playbook, you need to use anchors and aliases.
```suggestion
If you want to refer to the same object from different parts of a playbook, you need to use anchors and aliases.
```

2019-03-20 17:43 UTC, samccann commented on docs/docsite/rst/user_guide/playbooks_advanced_syntax.rst
> +Anchors are denoted by ``&`` indicator while aliases are denoted by ``*``
```suggestion
Anchors are denoted by the ``&`` indicator while aliases are denoted by ``*``
```

2019-03-20 17:43 UTC, samccann commented on docs/docsite/rst/user_guide/playbooks_advanced_syntax.rst
> +information using ``&jvm_opts`` and re-use this information by indicating ``<<: *jvm_opts``.
I'm having difficulty following this, as someone not familiar with YAML's support for anchor and aliases.  Initially a * meant alias, if so, what's the <<: about here?

Also not sure how I would know that the alias only reuses 'opts' and 'port'. If I put 'port: 2000' for app2, that would mean it was only sharing 'opts'?  (that is, I can reuse part of a set of variables if I set values for the other variables directly where I'm reusing as the alias?)

2019-03-20 17:43 UTC, samccann commented on docs/docsite/rst/user_guide/playbooks_advanced_syntax.rst
> +information using ``&jvm_opts`` and re-use this information by indicating ``<<: *jvm_opts``.
```suggestion
information using ``&jvm_opts`` as the anchor and re-use this information by indicating ``<<: *jvm_opts`` as the alias to that anchor.
```

2019-03-20 17:43 UTC, samccann commented on docs/docsite/rst/user_guide/playbooks_advanced_syntax.rst
> +This way you can access nested values inside dictionaries.
Confused here. I don't see *my_version used at all here? Did you mean to use msg: "{ *my_version | join('-') }} here?

2019-03-20 17:46 UTC, samccann commented
In general, it might help to add anchors and aliases description to our yaml syntax reference as well:
https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html?highlight=yaml

2019-03-20 17:47 UTC, samccann commented on docs/docsite/rst/user_guide/playbooks_advanced_syntax.rst
> +If you want to refer to the same object from different parts of playbook, you need to use anchors and aliases.
This would be a good point to add a link to the YAML syntax page, if you add a description there that further describes yaml anchors and aliases.

2019-03-21 20:34 UTC, acozine requested changes
Anchors and aliases are YAML features, not specifically Ansible features, and I'm wondering how much detail we want to include about them in the Ansible docs. I've made some suggestions here - let's talk about the best way to approach this content.

2019-03-21 20:34 UTC, acozine commented on docs/docsite/rst/user_guide/playbooks_advanced_syntax.rst
> +Using nested variables
```suggestion
Sharing variable values with YAML anchors and aliases
```

2019-03-21 20:34 UTC, acozine commented on docs/docsite/rst/user_guide/playbooks_advanced_syntax.rst
> +If you want to refer to the same object from different parts of playbook, you need to use anchors and aliases.
```suggestion
If you want to share variable values across tasks, `YAML anchors and aliases <https://yaml.org/spec/1.2/spec.html#id2765878>`_ help you define, maintain, and use those values in a flexible way.
```

2019-03-21 20:34 UTC, acozine commented on docs/docsite/rst/user_guide/playbooks_advanced_syntax.rst
> +Anchors are denoted by ``&`` indicator while aliases are denoted by ``*``
```suggestion
You define an anchor with ``&``, then refer to it using an alias, denoted with ``*``.
```

2019-03-21 20:34 UTC, acozine commented on docs/docsite/rst/user_guide/playbooks_advanced_syntax.rst
> +In a playbook, this may look like::
```suggestion
Here's an example that sets three values with an anchor, uses two of those values with an alias, and overrides the third value::
```

2019-03-21 20:34 UTC, acozine commented on docs/docsite/rst/user_guide/playbooks_advanced_syntax.rst
> +Here, 'app1' and 'app2' variables shares 'opts' and 'port' information so you can anchor that
```suggestion
Here, ``app1`` and ``app2`` share the values for ``opts`` and ``port`` 
```

2019-03-21 20:34 UTC, acozine commented on docs/docsite/rst/user_guide/playbooks_advanced_syntax.rst
> +information using ``&jvm_opts`` and re-use this information by indicating ``<<: *jvm_opts``.
```suggestion
using the anchor ``&jvm_opts`` and the alias ``<<: *jvm_opts``. The value for ``path`` is set by the anchor but overridden after the alias.
```

2019-03-21 20:34 UTC, acozine commented on docs/docsite/rst/user_guide/playbooks_advanced_syntax.rst
> +Another example can be::
```suggestion
Anchors and aliases let you share complex sets of variable values, including nested variables::
```

2019-03-22 13:23 UTC, samccann commented on docs/docsite/rst/user_guide/playbooks_advanced_syntax.rst
> +If you want to refer share variable values across tasks, `YAML anchors and aliases <https://yaml.org/spec/1.2/spec.html#id2765878>`_ help you define, maintain, and use those values in a flexible way.
```suggestion
If you want to share variable values across tasks, `YAML anchors and aliases <https://yaml.org/spec/1.2/spec.html#id2765878>`_ help you define, maintain, and use those values in a flexible way.
```

2019-03-22 13:28 UTC, samccann commented
I re-read what we have on the YAML syntax page an I agree w/ @acozine - we don't need to add this detail over there.  I added one more copy-edit nit and when that's complete, I think we're ready to merge.

2019-03-29 05:12 UTC, Akasurde commented
@acozine Thanks for the update. changes LGTM, feel free to merge.

2019-03-29 14:46 UTC, acozine approved these changes

2019-03-29 14:47 UTC, merged