Adding a new filter plugin that can encrypt and decrypt values using AWS KMS service
ansible/ansible pull request #54150
Opened 2019-03-21 04:38 UTC by achinthagunasekara

## SUMMARY

Adding a new filter plugin that can encrypt and decrypt values using AWS KMS service.
This filter plugin can be used to encrypt values using the AWS KMS service and store them within your repository, then decrypt then when you want to use them.

## Example

#### Decrypting

In `my_role\defaults\main.yml`
```
encrypted_value: >-
  {{ abcd123abcd13 abcd123abcd13abcd12abcd13
  abcd123abcd13abcd123abcd13abcd123ab1d1312
  abcd123abcd13abcd123abcd13abcd123ssdsas12
  sadsdsasd | aws_kms_decrypt(KEY_ARN) }}
```

In `my_role\tasks\main.yml`

```
- debug:
    msg: "Decrypted value is {{ encrypted_value }}"
```

Same can be done for encrypting values.

#### Encrypting

In `my_role\tasks\main.yml`

```
- debug:
    msg: "Encrypted value is {{ 'abc123abc123abc123' | aws_kms_encrypt(KEY_ARN) }}"
```

## Arguments

You can call `aws_kms_encrypt` and `aws_kms_encrypt` from this plugin with following variables.

*  Mandatory - `ciphertext` (str): Encrypted item to decrypt.
*  Mandatory - `key_arn` (str): AWS ARN to the KMS key.
*  Optional - `region` (str): AWS region to use.
*  Optional - `profile` (str): AWS credential profile to use.
*  Optional - `role_arn` (str): AWS IAM role to use to get credentials.
*  Optional - `aws_access_key` (str): AWS access key to use.
*  Optional - `aws_secret_key` (str): AWS secret key to use.

Getting AWS Credentias will use following order.

`profile ` > `role_arn ` > `aws_access_key ` and `aws_secret_key ` > `instance IAM profile` or `default profile`

## ADDITIONAL INFORMATION

* https://aws.amazon.com/documentation/kms/
* https://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/introduction.html

2019-03-22 10:23 UTC, Akasurde requested changes
Could you please add integration tests for this change? Thanks.

2019-03-22 10:23 UTC, Akasurde commented on lib/ansible/plugins/lookup/aws_kms_decrypt.py
> +(c) 2019, Achintha Gunasekara <contact@achinthagunasekara.com>.
```suggestion
Copyright: (c) 2019, Achintha Gunasekara <contact@achinthagunasekara.com>
```

2019-03-22 10:23 UTC, Akasurde commented on lib/ansible/plugins/lookup/aws_kms_decrypt.py
> +lookup: :aws_kms_decrypt
```suggestion
lookup: aws_kms_decrypt
```

2019-03-22 10:23 UTC, Akasurde commented on lib/ansible/plugins/lookup/aws_kms_decrypt.py
> +    - Achintha Gunasekara (@achinthagunasekara) <contact@achinthagunasekara.com>
```suggestion
    - Achintha Gunasekara (@achinthagunasekara)
```

2019-03-22 10:23 UTC, Akasurde commented on lib/ansible/plugins/lookup/aws_kms_decrypt.py
> +        default: 'us-east-1'
```suggestion
        default: 'us-east-1'
        env:
          - name: AWS_REGION
```

2019-03-22 10:23 UTC, Akasurde commented on lib/ansible/plugins/lookup/aws_kms_decrypt.py
> +        description: AWS secret key to use. Must use togather with aws_`access_key` option.
```suggestion
        description: AWS secret key to use. Must use together with `aws_access_key` option.
```

2019-03-22 10:23 UTC, Akasurde commented on lib/ansible/plugins/lookup/aws_kms_decrypt.py
> +        description: AWS access key to use. Must use togather with `aws_secret_key` option.
```suggestion
        description: AWS access key to use. Must use together with `aws_secret_key` option.
```

2019-03-22 10:23 UTC, Akasurde commented on lib/ansible/plugins/lookup/aws_kms_decrypt.py
> +        String decrypted value of the provided encrypted srting.
```suggestion
        String decrypted value of the provided encrypted string.
```

2019-03-22 10:23 UTC, Akasurde commented on lib/ansible/plugins/lookup/aws_kms_decrypt.py
> +    from aws_encryption_sdk.key_providers.kms import KMSMasterKey
I would keep both dependencies separate so that user can pin-point which library is missing. Just a suggestion.

2019-03-22 10:23 UTC, Akasurde commented on lib/ansible/plugins/lookup/aws_kms_decrypt.py
> +        raise AnsibleError('You need to install "boto3" and "aws_encryption_sdk"'
Might want to use https://github.com/ansible/ansible/blob/3c20a9b12b054a455ec54988983005401fe04868/lib/ansible/module_utils/basic.py#L563

2019-03-22 10:23 UTC, Akasurde commented on lib/ansible/plugins/lookup/aws_kms_decrypt.py
> +def role_arn_to_session(role_arn, role_session_name):
Can this be replaced by https://github.com/ansible/ansible/blob/3c20a9b12b054a455ec54988983005401fe04868/lib/ansible/module_utils/ec2.py#L128

2019-03-22 10:23 UTC, Akasurde commented on lib/ansible/plugins/lookup/aws_kms_encrypt.py
> +(c) 2018, Achintha Gunasekara <contact@achinthagunasekara.com>.
```suggestion
Copyright: (c) 2018, Achintha Gunasekara <contact@achinthagunasekara.com>
```

2019-03-22 10:23 UTC, Akasurde commented on lib/ansible/plugins/lookup/aws_kms_encrypt.py
> +lookup: :aws_kms_encrypt
```suggestion
lookup: aws_kms_encrypt
```

2019-03-22 10:23 UTC, Akasurde commented on lib/ansible/plugins/lookup/aws_kms_encrypt.py
> +    - Achintha Gunasekara (@achinthagunasekara) <contact@achinthagunasekara.com>
```suggestion
    - Achintha Gunasekara (@achinthagunasekara)
```

2019-03-25 00:32 UTC, achinthagunasekara commented on lib/ansible/plugins/lookup/aws_kms_decrypt.py
> +(c) 2019, Achintha Gunasekara <contact@achinthagunasekara.com>.
Fixed

2019-03-25 00:33 UTC, achinthagunasekara commented on lib/ansible/plugins/lookup/aws_kms_decrypt.py
> +lookup: :aws_kms_decrypt
Fixed

2019-03-25 00:34 UTC, achinthagunasekara commented on lib/ansible/plugins/lookup/aws_kms_decrypt.py
> +    - Achintha Gunasekara (@achinthagunasekara) <contact@achinthagunasekara.com>
Fixed

2019-03-25 00:35 UTC, achinthagunasekara commented on lib/ansible/plugins/lookup/aws_kms_decrypt.py
> +        default: 'us-east-1'
Fixed

2019-03-25 00:36 UTC, achinthagunasekara commented on lib/ansible/plugins/lookup/aws_kms_decrypt.py
> +        description: AWS access key to use. Must use togather with `aws_secret_key` option.
Fixed

2019-03-25 00:37 UTC, achinthagunasekara commented on lib/ansible/plugins/lookup/aws_kms_decrypt.py
> +        description: AWS secret key to use. Must use togather with aws_`access_key` option.
Fixed

2019-03-25 00:50 UTC, achinthagunasekara commented
@Akasurde I have updated the PR for your comments. Can you please take another look?

Thanks :)

2019-03-25 05:01 UTC, Akasurde requested changes

2019-03-25 05:01 UTC, Akasurde commented on lib/ansible/plugins/lookup/aws_kms_decrypt.py
> +Copyright 2019, Achintha Gunasekara <contact@achinthagunasekara.com>.
```suggestion
Copyright: (c) 2019, Achintha Gunasekara <contact@achinthagunasekara.com>
```

2019-03-25 05:01 UTC, Akasurde commented on lib/ansible/plugins/lookup/aws_kms_decrypt.py
> +def role_arn_to_session(role_arn, role_session_name):
Is this addressed ?

2019-03-25 22:10 UTC, achinthagunasekara commented on lib/ansible/plugins/lookup/aws_kms_decrypt.py
> +Copyright 2019, Achintha Gunasekara <contact@achinthagunasekara.com>.
Updated :)

2019-03-25 22:10 UTC, achinthagunasekara commented
@Akasurde I have updated the PR for your latest comments. Can you please take another look?

Thanks :)

2019-03-29 02:09 UTC, achinthagunasekara commented
@Akasurde I have updated the PR for your latest comments. Can you please take another look?

Thanks :)

2019-04-09 06:59 UTC, achinthagunasekara commented
@Akasurde I have updated the PR for your latest comments. Can you please take another look?

Thanks :)

2019-04-16 23:50 UTC, achinthagunasekara commented
@Akasurde I have updated the PR for your latest comments. Can you please take another look?

Thanks :)

2019-04-30 11:57 UTC, achinthagunasekara commented
Seems to be abandoned :( I'll re PR this

2019-04-30 11:57 UTC, closed without merging