Add new Redfish config module to handle Dell-specific OEM extensions
ansible/ansible pull request #54359
Opened 2019-03-25 21:33 UTC by jose-delarosa

- Extends the existing RedfishUtils class and leverages its methods

##### SUMMARY

Implements code taken out by https://github.com/ansible/ansible/pull/51898 and provides module to implement all iDRAC-specific configuration settings. 

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

idrac_redfish_config

##### ADDITIONAL INFORMATION

This new module can be used as a model for other OEMs to implement their own Redfish extensions.

2019-03-26 23:06 UTC, jamescassell commented
Is it possible to have it be a vendor-neutral redfish module?

2019-03-27 14:44 UTC, jose-delarosa commented
@jamescassell There are already vendor-neutral modules in this same directory. This Dell-specific module implements code that was taken out of those vendor-neutral modules, and it follows a framework we discussed to implement OEM-specific Redfish implementations. Refer to https://github.com/ansible/ansible/issues/48364#issuecomment-439129431.

2019-03-28 16:41 UTC, billdodd reviewed
Since the 'timeout' PR has now been merged, this PR will need to be updated to add the timeout support. See the recent timeout related commit to idrac_redfish_command.py.

2019-03-28 17:26 UTC, jose-delarosa commented
Yeah I realized that yesterday, will update today, thanks Bill.

2019-03-29 00:14 UTC, billdodd approved these changes
Looks good.

shipit

2019-03-29 00:36 UTC, jose-delarosa commented
shipit

2019-04-01 17:16 UTC, gundalow requested changes

2019-04-01 17:16 UTC, gundalow commented on lib/ansible/modules/remote_management/redfish/idrac_redfish_config.py
> +    version_added: "2.8"
```suggestion
```

2019-04-01 17:16 UTC, gundalow commented on lib/ansible/modules/remote_management/redfish/idrac_redfish_config.py
> +    version_added: "2.8"
```suggestion
```

2019-04-01 17:16 UTC, gundalow commented on lib/ansible/modules/remote_management/redfish/idrac_redfish_config.py
> +    version_added: '2.8'
```suggestion
```

2019-04-01 17:16 UTC, gundalow commented on lib/ansible/modules/remote_management/redfish/idrac_redfish_config.py
> +version_added: "2.8"
```suggestion
version_added: '2.8'
```

2019-04-01 17:16 UTC, gundalow commented on lib/ansible/modules/remote_management/redfish/idrac_redfish_config.py
> +    description:
```suggestion
    type: str
    description:
```

2019-04-01 18:10 UTC, jose-delarosa commented on lib/ansible/modules/remote_management/redfish/idrac_redfish_config.py
> +    description:
Updates committed. Thank you @gundalow

2019-04-01 19:59 UTC, merged

2019-04-01 19:59 UTC, gundalow commented
Merged, thanks for the quick update!