Adding more information about blocks and blocks error handling.
ansible/ansible pull request #54429
Opened 2019-03-26 21:29 UTC by caiohsramos

Signed-off-by: Caio Ramos <caioramos97@gmail.com>
Signed-off-by: Gabriely Pereira <gabriely.pereira@usp.br>

##### SUMMARY
Adding more information about Blocks error handling in the Error handling page. Also, adding `ignore_errors`  in the example at the Blocks documentation.

Fixes #27165 

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
docsite
playbooks_blocks.rst
playbooks_error_handling.rst

##### ADDITIONAL INFORMATION
https://docs.ansible.com/ansible/devel/user_guide/playbooks_blocks.html
https://docs.ansible.com/ansible/devel/user_guide/playbooks_error_handling.html

2019-03-28 13:00 UTC, jamescassell requested changes

2019-03-28 13:00 UTC, jamescassell commented on docs/docsite/rst/user_guide/playbooks_error_handling.rst
> +Blocks only deal with 'failed' status of a task. A bad task definition, an undefined variable or an unreachable host are not `rescuable` errors::
Undefined variables are "rescuable" errors
```suggestion
Blocks only deal with 'failed' status of a task. A bad task definition or an unreachable host are not 'rescuable' errors::
```

2019-03-28 16:04 UTC, caiohsramos commented
ready_for_review

2019-03-28 16:18 UTC, jamescassell approved these changes
shipit

2019-04-03 19:15 UTC, felixfontein commented on docs/docsite/rst/user_guide/playbooks_error_handling.rst
> +This will 'revert' the failed status of the task for the run and the play will continue as if it had succeeded.
```suggestion
This will 'revert' the failed status of the outer ``block`` task for the run and the play will continue as if it had succeeded. 
```

2019-04-03 19:15 UTC, felixfontein commented on docs/docsite/rst/user_guide/playbooks_blocks.rst
> +for all the enclosed tasks. Finally, ``ignore_errors: yes`` will continue executing the playbook even if some of the tasks fails.
```suggestion
for all the enclosed tasks. Finally, ``ignore_errors: yes`` will continue executing the playbook even if some of the tasks fail.
```

2019-04-03 19:23 UTC, felixfontein approved these changes
shipit

2019-04-05 21:49 UTC, merged