Allow all of yum version compare operators
ansible/ansible pull request #54603
Opened 2019-03-29 14:24 UTC by rosowiecki

##### SUMMARY
Improved fix for #47744, which allows all version comparison operators (not only '==').

Fixes: #47744

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
yum

##### ADDITIONAL INFORMATION
 In our playbooks we often use yum: name= 'package >= VERSION' and we'd like ansible-2.7 to support it. Instead of listing all possible operators like '<=' '>=' yum module allows spaces when other special sign (@<>=) appers.

2019-03-29 16:46 UTC, mkrizek requested changes
LGTM but changelog and tests are missing.

2019-03-29 17:28 UTC, rosowiecki commented
> LGTM but changelog and tests are missing.

Is test/units/modules/packaging/os/test_yum.py a good choice for tests of this code?

2019-03-29 17:30 UTC, mkrizek commented
See https://github.com/ansible/ansible/pull/47744/files#diff-d057b4b95cb10fb15c4e193ac5746861R560

2019-04-08 08:34 UTC, mkrizek approved these changes

2019-04-08 08:34 UTC, merged

2019-04-08 08:34 UTC, mkrizek commented
Thanks @rosowiecki!

2019-04-08 08:41 UTC, mkrizek commented
@rosowiecki FYI I created a PR for this change to be backported to `2.7`. See above.