[WIP] add azure monitor log profile module
ansible/ansible pull request #54702
Opened 2019-04-02 03:47 UTC by yungezz

##### SUMMARY

add new module azure_rm_monitorlogprofile. mark as WIP to avoid be merged into 2.8.

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2019-04-12 02:10 UTC, yungezz commented
HI @mattclay  seems test account doesn't have permission to create log profile, pls see  below error:
```
"Error creating/updating log profile: Azure Error: AuthorizationFailed\nMessage: The client 'xxxxxxxxxxxxxxxxxxx' with object id 'xxxxxxxxxxx' does not have authorization to perform action 'microsoft.insights/logprofiles/write' over scope '/subscriptions/xxxxxxxxxxxxxxxxxxxx'."
```
https://app.shippable.com/github/ansible/ansible/runs/117172/114/tests

Could you pls grant necessary permission? Thanks.

2019-04-12 18:05 UTC, mattclay commented
@yungezz I don't think we'll be able to test this with our current CI system. This feature appears to operate at the subscription level, rather than the resource group or resource level. We don't have a safe way to expose privileges for managing the subscription currently.

You can still create tests and run them locally, but you'll need to mark the test `unsupported` in the aliases file to have it skipped in CI.

2019-04-15 01:32 UTC, yungezz commented
got it. thanks Matt @mattclay .

2019-04-16 08:49 UTC, yungezz commented
ready_for_review

2019-04-18 02:05 UTC, Fred-sun commented
@yuwzho @zikalino review_need

2019-05-05 08:08 UTC, Fred-sun commented
@yuwzho @zikalino Please help review this PR when you're available! Thanks a lot!

2019-05-31 07:14 UTC, Fred-sun commented
@yuwzho @zikalino @nitzmahone Please take a review this when you're free? Thank you very much!

2019-06-19 08:43 UTC, Fred-sun commented
@yuwzho @zikalino @nitzmahone  review_need

2019-07-16 23:50 UTC, yungezz commented
ready_for_review

2019-07-22 09:22 UTC, Fred-sun commented
@nitzmahone @jborean93 Please take a review this PR when you're free! Thank you very much!

2019-07-24 23:25 UTC, nitzmahone requested changes
couple little docs things, otherwise LGTM

2019-07-24 23:25 UTC, nitzmahone commented on lib/ansible/modules/cloud/azure/azure_rm_monitorlogprofile.py
> +            - List of categories of logs. These categories are created as is convinient to  user. Some Values are Write, Delete and/or Action.
convenient

2019-07-24 23:25 UTC, nitzmahone commented on lib/ansible/modules/cloud/azure/azure_rm_monitorlogprofile.py
> +            - format like {serice_bus_resource_id}/authorizationrules{key_name}.
service_bus_resource_id

2019-08-19 09:36 UTC, Fred-sun commented
@nitzmahone It has been updated, please help to review it again!  thank you very much!

2019-08-26 21:00 UTC, zikalino commented
all minor comments addressed now -- merging

2019-08-26 21:00 UTC, merged