Better test for cache method availability
ansible/ansible pull request #54740
Opened 2019-04-02 19:58 UTC by bcoca

fixes #54737

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

inventory

2019-04-02 21:02 UTC, s-hertel approved these changes
This would be good to fix in auto too, if plugin._cache is not predictably created via Cacheable.

2019-04-02 22:31 UTC, nitzmahone requested changes
just changelog is out of date (maybe might want to also include a bugfix line about tweaking the instancing behavior)

2019-04-02 22:31 UTC, nitzmahone commented on changelogs/fragments/fix_cache_assumption.yml
> +    - use class inheritance vs internal attribute indicator before executing inherited method for inventory plugins.
no longer accurate, now "duck typed" ;)

2019-04-02 23:03 UTC, s-hertel reviewed
Looks good besides changelog

2019-04-09 16:28 UTC, nitzmahone approved these changes

2019-04-09 16:32 UTC, merged