cloudscale_server: implement param server_groups
ansible/ansible pull request #54868
Opened 2019-04-04 14:55 UTC by resmo

##### SUMMARY
Implement new param server_groups, deprecates anti_affinity_with
##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

cloudscale_server

##### ADDITIONAL INFORMATION

```paste below

```

2019-04-09 08:23 UTC, gaudenz requested changes
Thanks for this change. Beside the problem with duplicate names, I think we should extend the test coverage a bit. Maybe it's easiest to rebase this branch onto the cloudscale_server_group branch. Without the `cloudscale_server_group` module this change is pretty useless anyway.

2019-04-09 08:23 UTC, gaudenz commented on lib/ansible/modules/cloud/cloudscale/cloudscale_server.py
> +                server_group_params.remove(server_group['name'])
This has the effect to only add the first server group with this name to the list of server group ids. Is this intended? I'd prefer either warning the user in this case or adding all matching server groups. What do you think?

2019-04-10 15:51 UTC, resmo commented
ready_for_review

2019-04-10 17:42 UTC, resmo commented
rebased

2019-04-10 22:16 UTC, merged