filters: Add additional Truth values to bool filter
ansible/ansible pull request #54969
Opened 2019-04-08 04:19 UTC by Akasurde

##### SUMMARY
Fixes: #54964

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
lib/ansible/plugins/filter/core.py
test/integration/targets/filters/files/foo.txt
test/integration/targets/filters/templates/foo.j2

2019-04-09 20:30 UTC, bcoca commented
this needs at least to be a toggle to enable the new behaviour

2019-04-10 01:07 UTC, bcoca requested changes
do not change current behaviour in backwards incompatible ways

2019-04-16 15:29 UTC, bcoca commented on lib/ansible/plugins/filter/core.py
> +    if extended:
instead of extended we might want `logic=python|jinja|yaml|ansible`

2019-07-31 15:28 UTC, bcoca commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +Possible values for argument ``logic`` are 'python', 'yaml' and 'ansible', where 'yaml' is a default value.
you should describe what each option actually uses, knowing the option names is not enough, you only describe ansible above, but yaml and python are not clear to most users.

2019-07-31 15:29 UTC, bcoca requested changes

2019-07-31 15:29 UTC, bcoca commented on lib/ansible/plugins/filter/core.py
> +        return bool(a)
this can return an exception

2019-07-31 15:31 UTC, bcoca commented on lib/ansible/plugins/filter/core.py
> +        return a in BOOLEANS_TRUE
don't we have a 'boolean' function that also does 'false' comparisons?

2019-10-06 13:15 UTC, Akasurde commented
superseded by https://github.com/ansible/ansible/pull/62602

2019-10-06 13:15 UTC, closed without merging