modules/files : Fill result in touch check mode, fix #50452
ansible/ansible pull request #55011
Opened 2019-04-08 21:23 UTC by Turgon37

##### SUMMARY
Add diff and result informations on file module with state "touch" even in check mode

#50452

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/modules/files/file.py

##### ADDITIONAL INFORMATION

2019-04-09 20:39 UTC, samdoran commented
Please create a changelog fragment. See [this fragment](https://github.com/ansible/ansible/blob/stable-2.7/changelogs/fragments/reboot-change-default-boot-command.yaml) as an example.

2019-04-16 14:54 UTC, s-hertel requested changes

2019-04-16 14:54 UTC, s-hertel commented on lib/ansible/modules/files/file.py
> +        result['changed'] = True
If the `access_time` and `modification_time` options are set to "preserve" check mode is still going to show changed=True, even though no change will be made without check mode.

2020-06-18 08:16 UTC, Akasurde commented
@Turgon37 Are you still working on this? Thanks.

needs_info

2020-06-20 13:30 UTC, Turgon37 commented
Hello yes It's in my todo list :)

2022-04-13 19:20 UTC, mattclay commented
Thanks for your interest in working on this. Since this PR hasn't been updated for some time it is being closed. If you're interested in continuing work on this, please open a new PR.

2022-04-13 19:20 UTC, closed without merging