Module ec2_asg: added support for mixed instance type
ansible/ansible pull request #55067
Opened 2019-04-10 02:05 UTC by Elsvent

added support for mixed instance type

##### SUMMARY
This PR adds support for mixed instance type in ec2_asg

##### ISSUE TYPE
Feature Pull Request

##### COMPONENT NAME
ec2_asg

##### ADDITIONAL INFORMATION
mixed_instances_policy:
  instance_types: '{{ list }}'
  on_demand_base_capacity: '{{ int }}'
  on_demand_percentage_above_base_capacity: '{{ int }}'

2019-04-10 03:54 UTC, Elsvent commented
ready_for_review

2019-04-10 04:03 UTC, Elsvent commented
@garethr Hi, Please help me review about the change. Thanks a lot

2019-04-18 05:34 UTC, Elsvent commented
re_ci

2019-05-17 21:55 UTC, jillr requested changes
Thanks for this patch.  Could you also please add integration tests and an example for this new option?

2019-05-17 21:55 UTC, jillr commented on lib/ansible/modules/cloud/amazon/ec2_asg.py
> +        launch_object = {'LaunchTemplate': launch_object}
This is unnecessary, it's creating an object that looks like: launch_object={'LaunchTemplate': {'LaunchTemplate': {'LaunchTemplateId': 'lt-02f29cf111d929cbb', 'Version': '1'}}}

2019-08-16 21:59 UTC, worldmediaagency commented
What version of Ansible is this PR targeting?

2019-09-06 12:20 UTC, avishefi commented
@worldmediaagency looks like 2.9 according to the module documentation.

Is this still in progress?

2019-10-22 08:48 UTC, GoodMirek commented
Is there any chance that this PR will be included in 2.9 ?

2019-10-22 09:53 UTC, s-hertel commented
@worldmediaagency @avishefi @GoodMirek This is now targeting 2.10. The PR is waiting on requested changes and the version_added needs to be updated. If any of you are able help get it across the line by making the requested changes, feel welcome to cherry-pick the changes from this branch to open a new PR.

2019-10-24 05:52 UTC, markuman reviewed
@Elsvent still interested or just no time in writing an integration test?

2019-10-24 05:52 UTC, markuman commented on lib/ansible/modules/cloud/amazon/ec2_asg.py
> +    version_added: "2.9"
2.10

2019-11-11 10:51 UTC, markuman requested changes

2019-11-11 10:51 UTC, markuman commented on lib/ansible/modules/cloud/amazon/ec2_asg.py
> +            if 'MixedInstancesPolicy' in launch_object:
This handling is also missing in line 1185, otherwise existing AutoScalingGroups cannot be updated with a mixed instance policy.

2019-11-11 10:51 UTC, markuman commented on lib/ansible/modules/cloud/amazon/ec2_asg.py
> +        launch_object = {'LaunchTemplate': launch_object}
the object is build wrong for mixed instance type containing the launch template information (even if I comment line 727 out).

current object return value
```
'MixedInstancesPolicy': 
    {'LaunchTemplate': 
        {'LaunchTemplateSpecification': 
            {'LaunchTemplate': 
                {'LaunchTemplateId': 'lt-09c2271ea154ad8f9', 
                'Version': '8'}
```

results in 

```
nUnknown parameter in MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification: \"LaunchTemplate\", must be one of: LaunchTemplateId, LaunchTemplateName, Version
```

according to the boto3 documentation, it must look like

```
MixedInstancesPolicy={
        'LaunchTemplate': {
            'LaunchTemplateSpecification': {
                'LaunchTemplateId': 'string',
                'LaunchTemplateName': 'string',
                'Version': 'string'
            },
```

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/autoscaling.html#AutoScaling.Client.create_auto_scaling_group

Must be fixed in line 732.

2019-11-11 10:51 UTC, markuman commented on lib/ansible/modules/cloud/amazon/ec2_asg.py
> +                    'LaunchTemplateSpecification': launch_object
```
                     'LaunchTemplateSpecification': launch_object["LaunchTemplate"]
```

2019-11-11 10:51 UTC, markuman commented on lib/ansible/modules/cloud/amazon/ec2_asg.py
> +                    'LaunchTemplateSpecification': launch_object
This is very important. Otherwise nor creating nor updating will work.

2020-02-05 08:09 UTC, felixfontein commented
No longer necessary since #67045 has been merged.

2020-02-05 08:09 UTC, closed without merging