Add oracle compute instance module
ansible/ansible pull request #55240
Opened 2019-04-13 00:26 UTC by nalsaber

##### SUMMARY
Add oracle compute instance module

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
Oracle cloud infrastructure compute instance module

##### ADDITIONAL INFORMATION
New files:
lib/ansible/module_utils/oracle/oci_compute_utils.py
lib/ansible/modules/cloud/oracle/oci_instance.py
lib/ansible/modules/cloud/oracle/oci_instance_facts.py
test/units/modules/cloud/oracle/test_oci_instance.py

```paste below

```

2019-04-13 01:00 UTC, mattclay submitted a review, later dismissed

2019-04-13 01:00 UTC, mattclay commented on test/runner/requirements/units.txt
> +oci
Instead of adding a dependency on `oci`, can you mock the `oci` module instead?

See https://github.com/ansible/ansible/pull/50850/files#diff-d075108943a235e1989fb4a5ac471049R38 for an example of how this can be done.

2019-04-17 04:54 UTC, mattclay commented on test/units/modules/cloud/oracle/test_oci_instance.py
> +from nose.plugins.skip import SkipTest
Use pytest instead of nose.

2019-04-23 22:30 UTC, nalsaber commented on test/runner/requirements/units.txt
> +oci
removed

2019-04-23 22:30 UTC, nalsaber commented on test/units/modules/cloud/oracle/test_oci_instance.py
> +from nose.plugins.skip import SkipTest
removed

2019-04-24 22:34 UTC, nalsaber commented
@mattclay can you please review this PR?

2019-05-06 21:34 UTC, nalsaber commented
@gundalow can you please review this?

2019-05-06 23:37 UTC, mross22 approved these changes

2019-05-08 09:29 UTC, rohitChaware commented
/shipit

2019-05-08 09:33 UTC, rohitChaware commented
shipit

2019-05-09 18:49 UTC, mross22 commented
shipit

2019-05-09 19:32 UTC, bcoca requested changes

2019-05-09 19:32 UTC, bcoca commented on lib/ansible/module_utils/oracle/oci_compute_utils.py
> +# Apache License v2.0
do not dual license files

2019-05-09 20:14 UTC, nalsaber commented on lib/ansible/module_utils/oracle/oci_compute_utils.py
> +# Apache License v2.0
removed dual license

2019-05-10 05:51 UTC, manojmeda commented
shipit

2020-03-04 01:09 UTC, closed without merging