TRANSFORM_INVALID_GROUP_CHARS: no warning for "ignore"
ansible/ansible pull request #55402
Opened 2019-04-16 21:14 UTC by jamescassell

##### SUMMARY

Provide an option to explicitly opt-in to the old group chars behavior, squashing the deprecation warnings.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2019-04-17 23:41 UTC, jamescassell commented
made obsolete by #55474

2019-05-22 04:09 UTC, jamescassell commented
reopening because the other one never got any traction

2019-05-22 04:27 UTC, felixfontein approved these changes
LGTM

2019-05-22 04:28 UTC, felixfontein commented
CC @resmo @willthames

2019-05-22 04:29 UTC, willthames commented on changelogs/fragments/group-chars-ignore.yaml
> +- fixed ``ignore`` option to ``TRANSFORM_INVALID_GROUP_CHARS`` to supress deprecation warnings
typo: suppress

2019-05-22 04:31 UTC, jamescassell commented on changelogs/fragments/group-chars-ignore.yaml
> +- fixed ``ignore`` option to ``TRANSFORM_INVALID_GROUP_CHARS`` to supress deprecation warnings
fixed, thanks

2019-05-22 04:32 UTC, willthames approved these changes

2019-05-22 14:52 UTC, bcoca commented
subset of #55474

2019-05-22 17:19 UTC, resmo approved these changes
shipit

2019-05-22 17:58 UTC, bcoca requested changes
this is dupe/subset of existing PR

2019-05-22 18:12 UTC, jamescassell commented
> this is dupe/subset of existing PR

Can we ship that one?

2019-05-22 18:32 UTC, bcoca commented
once reviewed and approved

2019-06-04 23:57 UTC, closed without merging