url lookup: add user agent option; use consistent default
ansible/ansible pull request #55733
Opened 2019-04-24 19:52 UTC by scottsb

##### SUMMARY
Add ability to set user agent with URL lookup. At the same time, apply a default of `ansible-httpget` to match the URL module and various other modules that do HTTP requests.

The change in default is particularly useful because otherwise the default Python user agent of `Python-urllib*` is used, which can end up blocked by the [OWASP ModSecurity ruleset](https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/f844b8510beb619ebad0d17d23a6dac08c1bd62d/rules/scripting-user-agents.data#L22). As a particular example, this currently blocks simple retrieval of [Cloudflare IP ranges](https://www.cloudflare.com/ips-v4).

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
url

##### ADDITIONAL INFORMATION
n/a

2019-04-25 20:45 UTC, scottsb commented
ready_for_review

Think this test failure is not caused by this PR.

2019-04-25 21:13 UTC, bcoca requested changes
LGTM but needs version change, also a changelog would be nice (minor_change)

2019-04-25 21:13 UTC, bcoca commented on lib/ansible/plugins/lookup/url.py
> +    version_added: "2.8"
2.9 at this point

2019-06-20 21:59 UTC, scottsb commented
@bcoca Took me long enough, but your requests have been addressed.

ready_for_review

2019-06-20 22:04 UTC, bcoca approved these changes

2019-06-21 19:35 UTC, samdoran commented
@scottsb The test failures were due to an expired private GPG key, which I have fixed. I triggered a new test run.

2020-10-23 16:30 UTC, samdoran commented
Sorry this got overlooked. This was added by #64892 but the `http_agent` was not set to `ansible-httpget` by default. I will open a separate PR for that.

2020-10-23 16:30 UTC, closed without merging