add new module zabbix_host_triggers.py in monitoring/zabbix
ansible/ansible pull request #55812
Opened 2019-04-26 12:02 UTC by stravassac

##### SUMMARY
Add a module in monitoring zabbix to see trigger for a given Zabbix Host
Usefull to check the status of a host before run playbook on it

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
zabbix_host_triggers

##### ADDITIONAL INFORMATION

```paste below

```

2019-04-29 14:55 UTC, D3DeFi requested changes
Thank you for the contribution @stravassac! I like your code, but it needs a few adjustments to match other zabbix modules (see my other comments).

Unfortunately, I need to you close this pull request and open it from a new branch (not named "devel") as it is required by [ansible guidelines](https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_general.html#contributing-back-to-ansible).

2019-04-29 14:55 UTC, D3DeFi commented on lib/ansible/modules/monitoring/zabbix/zabbix_host_triggers.py
> +    server_url:
There is a lot of duplicate options that are already present in [this document fragment](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/doc_fragments/zabbix.py). All of the listed options in the document fragemnt are required in Zabbix modules. Please, remove them from here and add missing options to instance created at line 198. Module [zabbix_host_facts](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/monitoring/zabbix/zabbix_host_facts.py) is a good example for this.

2019-04-29 14:55 UTC, D3DeFi commented on lib/ansible/modules/monitoring/zabbix/zabbix_host_triggers.py
> +    class ZabbixAPIExtends(ZabbixAPI):
Extending of ZabbixAPI class was used with very old zabbix-api module versions. I am trying to get rid of this in #53334 as it is now working fine with just a base class. Please remove this as well. Your code will work fine without it :)

2019-04-29 14:55 UTC, D3DeFi commented on lib/ansible/modules/monitoring/zabbix/zabbix_host_triggers.py
> +    - zabbix-api
```suggestion
    - "zabbix-api >= 0.5.3"
```

2019-04-29 14:55 UTC, D3DeFi commented on lib/ansible/modules/monitoring/zabbix/zabbix_host_triggers.py
> +        default: 3
a range of available values would be suitable in the description. Also, checking it in the code and then failing implicitly would be imho better than getting python error from zabbix-api module

2019-05-01 07:47 UTC, stravassac commented
@D3DeFi thanks for your review, I'll take a look next week and fix yours comments, I can't this week

2019-05-06 09:57 UTC, stravassac commented
Hello @D3DeFi  can you have a look at this new push. 
And can you explain why I need to make another branch not named "devel", in guidelines I see:
"develop against a new feature branch using the devel branch as a starting point"  
In this document 'https://docs.ansible.com/ansible/latest/dev_guide/testing.html#developing-testing' I see:
"
It is important that the PR request target be ansible:devel, as we do not accept pull requests into any other branch. Dot releases are cherry-picked manually by Ansible staff."
Maybe I missing some thing

2019-05-07 10:02 UTC, D3DeFi requested changes
Just a few details in comments below. Otherwise, It looks good.

As for the devel branch: "develop against a new feature branch using the devel branch as a starting point". This means that you should use new feature branch (like `new_zbx_host_triggers_module`) and open a PR against ansible:devel.

Second cite: "It is important that the PR request target be ansible:devel, as we do not accept pull requests into any other branch. Dot releases are cherry-picked manually by Ansible staff." just states what PR targeted branch should be.

If I do remember correctly, ansibot used to tag PRs opened from `*:devel` to `ansible:devel` with `needs_revision` or something similar right away. It looks like it is not a problem anymore. There is just a note: "Some users do not create feature branches, which can cause problems when they have multiple, unrelated commits in their version of devel. If the source looks like someuser:devel, make sure there is only one commit listed on the pull request."

Can you at least try to squash the commits into a single commit? I will then cast my shipit vote.

Other than that, pushing from *:devel forbids PR reviewer/tester to easily checkout the PR branch locally
```
git fetch origin pull/55812/head:devel
fatal: Refusing to fetch into current branch refs/heads/devel of non-bare repository
```

2019-05-07 10:02 UTC, D3DeFi commented on lib/ansible/modules/monitoring/zabbix/zabbix_host_triggers.py
> +    - "zabbix-api"
Duplicate occurence of zabbix-api requirement

```suggestion
```

2019-05-07 10:02 UTC, D3DeFi commented on lib/ansible/modules/monitoring/zabbix/zabbix_host_triggers.py
> +    timeout:
timeout and validate_certs module arguments are documented in zabbix document fragment as well, no need to have them documented here

2019-05-07 10:02 UTC, D3DeFi commented on lib/ansible/modules/monitoring/zabbix/zabbix_host_triggers.py
> +    from zabbix_api import ZabbixAPI, ZabbixAPISubClass
ZabbixAPISubClass import no longer needed
```suggestion
    from zabbix_api import ZabbixAPI
```

2019-05-07 12:05 UTC, stravassac commented
@D3DeFi I close this PR and re-open another

2019-05-07 12:05 UTC, closed without merging