New modules to list AWS API Gateway.
ansible/ansible pull request #55859
Opened 2019-04-28 09:04 UTC by cahlchang

##### SUMMARY

Added list module for AWS API Gateway.

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
aws_api_gateway_facts

##### ANSIBLE VERSION
```
(myenv) $ ansible --version
ansible 2.9.0.dev0 config file = None configured module search path =
['/Users/myuser/.ansible/plugins/modules',
'/usr/share/ansible/plugins/modules'] ansible python module location =
/Users/myuser/git/ansible/lib/ansible executable location = ./bin/ansible
python version = 3.7.3 (default, Mar 27 2019, 09:23:15) [Clang 10.0.1
(clang-1001.0.46.3)]
```

##### ADDITIONAL INFORMATION

```paste below

- hosts: localhost
  tasks:
    - aws_api_gateway_facts:
        profile: default
        api_id: 'myapigatewayid'
      register: facts1

    - aws_api_gateway_facts:
        profile: default
      register: facts2

    - debug:
        msg: "{{ facts1 }}"

    - debug:
        msg: "{{ facts2 }}"
```

2019-04-29 05:59 UTC, willthames requested changes

2019-04-29 05:59 UTC, willthames commented on lib/ansible/modules/cloud/amazon/aws_api_gateway_facts.py
> +    HAS_BOTO3 = True
HAS_BOTO3 is not needed with AnsibleAWSModule

2019-04-29 05:59 UTC, willthames commented on lib/ansible/modules/cloud/amazon/aws_api_gateway_facts.py
> +from ansible.module_utils.ec2 import (boto3_conn, ec2_argument_spec, get_aws_connection_info, camel_dict_to_snake_dict)
boto3_conn, ec2_argument_spec, get_aws_connection_info
are not needed with AnsibleAWSModule

2019-04-29 05:59 UTC, willthames commented on lib/ansible/modules/cloud/amazon/aws_api_gateway_facts.py
> +        module.fail_json(msg=err.message, exception=traceback.format_exc(), **camel_dict_to_snake_dict(err.response))
use `module.fail_json_aws(msg=err.message)`

2019-04-29 05:59 UTC, willthames commented on lib/ansible/modules/cloud/amazon/aws_api_gateway_facts.py
> +    if region:
just use `client = module.client('apigateway')`

2019-04-29 05:59 UTC, willthames commented on lib/ansible/modules/cloud/amazon/aws_api_gateway_facts.py
> +            api_result = client.get_rest_apis()
You'll need to handle pagination if there are a lot of APIs. Should probably handle rate limiting here too

https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/GUIDELINES.md#api-throttling-rate-limiting-and-pagination

2019-04-29 05:59 UTC, willthames commented on lib/ansible/modules/cloud/amazon/aws_api_gateway_facts.py
> +  contains:
This does not seem to be at all comprehensive compared to what is in https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/apigateway.html#APIGateway.Client.get_rest_apis

You can generate the RETURN list using hacking/return_skeleton_generator.py

2019-05-08 05:41 UTC, cahlchang commented
Thank you for the review.
I will fix the contents and submit it in the near future.

2020-08-16 05:50 UTC, closed without merging