add path to return val of file touch
ansible/ansible pull request #55904
Opened 2019-04-30 07:30 UTC by mlda065

##### SUMMARY

Fixes #55898 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

file module

##### ADDITIONAL INFORMATION

Here is a playbook which fails without this patch, and passes with it.

```
---
- hosts: localhost
  tasks:

     - name: touch file
       file:
          state: touch
          path: file.txt
       register: touch
       failed_when: touch.path != 'file.txt'

     - name: file check
       file:
          state: file
          path: file.txt
       register: file
       failed_when: file.path != 'file.txt'

     - name: remove file
       file:
          state: absent
          path: file.txt
       register: absent
       failed_when: absent.path != 'file.txt'

     - name: directory check
       file:
          state: directory
          path: dir
       register: dir
       failed_when: dir.path != 'dir'
```

2019-04-30 16:17 UTC, s-hertel requested changes
It seems like it would be good to document the return values instead since the path is already available in the output via `dest`. Here's an example of what that looks like: 
https://docs.ansible.com/ansible/latest/modules/copy_module.html#return-values
https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/copy.py#L197-L258

2019-05-01 00:10 UTC, mlda065 commented
Adding an explanation of return values to the documentation would be good too.
I can do that.

I think that the code itself does need to change. Currently `state: touch` returns `ret.dest`, but `state: file` returns `ret.path`. That inconsistency is a bad thing.

I don't think there's any substantial drawback to modifying both. It's not even that inefficient to return both `path` and `dest`, since python will just make two pointers to the same `malloc`ed string.

2019-05-01 02:38 UTC, mlda065 commented
Looking at the code, it is a bit inconsistent.

`state: hard` returns `path` if no change is made and path is a directory. Otherwise it returns `dest`.

What should the return behavior be for `link` and `hard`?

2019-05-01 02:44 UTC, mlda065 commented
Also, `state: link` returns `dest` on success, but `path` on failure. What should it be?

2019-05-01 05:01 UTC, mlda065 commented
Also, when you have `state: touch`, the return value is `state: file`. That's really confusing. What is it supposed to be?

2019-05-01 05:55 UTC, mlda065 commented
I was a bit unclear on what to put for some of the details of the return values.

Here is a playbook which passes (with this patch). I wrote the documentation based on this behavior:

```
---
- hosts: localhost
  tasks:

     - name: touch file
       file:
          state: touch
          path: file.txt
       register: touch
       failed_when: >
          (touch.path != 'file.txt') or
          (touch.state != 'file') or
          ((touch.diff is not defined) and touch.changed)

     - name: file check
       file:
          state: file
          path: file.txt
       register: file
       failed_when: >
          (file.path != 'file.txt') or
          (file.state != 'file') or
          ((file.diff is not defined) and file.changed)

     - name: create soft link
       file:
          dest: link.txt
          src: file.txt
          state: link
       register: link
       failed_when: >
         (link.dest != 'link.txt') or
         (link.state != 'link') or
         ((link.diff is not defined) and link.changed)

     - name: touch link
       file:
         state: touch
         path: link.txt
       register: link_touch
       failed_when: link_touch.state != 'link'

       # because the next task will fail with a relative path
     - name: create file from absolute path
       file:
         path: /tmp/file.txt
         state: touch

     - name: create hard link
       file:
          dest: hard.txt
          src: /tmp/file.txt
          state: hard
       register: hard
       failed_when: >
         (hard.dest != 'hard.txt') or
         (hard.state != 'hard') or
         ((hard.diff is not defined) and hard.changed)

     - name: touch hard
       file:
         state: touch
         path: hard.path
       register: hard_touch
       failed_when: hard_touch.state != 'file'

     - name: remove file
       file:
          state: absent
          path: file.txt
       register: absent
       failed_when: >
          (absent.path != 'file.txt') or
          (absent.path is not defined) or
          (absent.state != 'absent') or
          ((absent.diff is not defined) and absent.changed)

     - name: directory check
       file:
          state: directory
          path: dir
       register: dir_check
       failed_when: >
         (dir_check.path != 'dir') or
         (dir_check.state != 'directory') or
         ((dir_check.diff is not defined) and dir_check.changed)

     - name: touch directory
       file:
         state: touch
         path: dir
       register: dir_touch
       failed_when: dir_touch.state != 'directory'
```

2022-01-13 23:03 UTC, s-hertel requested changes
@mdavis-xyz I'm sorry for letting this one fall through the cracks. I'm glad your other PR documenting the RETURN values made it in though. I was looking at the code change again, and it looks incomplete. I haven't tested it, but here is a diff that more thoroughly covers all the exit/failure points that I can spot (and adds consistency for `dest` too): https://github.com/s-hertel/ansible/commit/9e3d51b6624058781ae726e49459b5e8cfa6df29.

2022-01-14 02:57 UTC, mdavis-xyz reviewed
This looks fine. Although this PR has been open for so long that I forgot the details.

2022-01-14 03:07 UTC, mdavis-xyz commented
There's now some git conflicts. I just rebased and force-pushed

2022-08-11 21:11 UTC, s-hertel commented
@mdavis-xyz This is still incomplete as indicated in https://github.com/ansible/ansible/pull/55904#pullrequestreview-852333266 . `dest` is documented for state=touch, but it's inconsistently returned. Now `path` is consistently returned for state=touch but not documented. If we're making dest/path aliases, we should make sure the returned values are generally consistent, maybe along the lines of my attempt https://github.com/s-hertel/ansible/commit/9e3d51b6624058781ae726e49459b5e8cfa6df29.

Also, we generally don't document `diff` as a return value, so I'm not sure if we want to do that for `file`.

Closing, but feel free to reopen if you're able to update this.

2022-08-11 21:11 UTC, closed without merging

2022-08-11 21:44 UTC, bcoca commented
if we return 'path' in all other cases, i would do the same here and add 'aliases' to return docs, so path, can show the other aliases like 'dest'