Fix nxapi failures
ansible/ansible pull request #55993
Opened 2019-05-01 16:42 UTC by mikewiebe

##### SUMMARY
Fixes the following issues for `nxos_install_os` in the devel branch
    * Recent refactoring in module_utils broke upgrades using nxapi local
    * Refactored integration tests to make them more flexible for choosing connection type

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
nxos_install_os

##### ADDITIONAL INFORMATION

Please cherry-pick into stable-2.8

2019-05-08 18:53 UTC, mikewiebe commented
@trishnaguha I fixed the conflicts with the base branch here.

2019-05-10 04:56 UTC, trishnaguha commented on lib/ansible/module_utils/network/nxos/nxos.py
> +            resp, msg_timestamps = self.send_request(commands, output='config', check_status=True,
As the return_timestamps is reverted, `msg_timestamps` can be now ignored here.

2019-05-10 04:59 UTC, trishnaguha requested changes

2019-05-10 04:59 UTC, trishnaguha commented on lib/ansible/module_utils/network/nxos/nxos.py
> +            resp, msg_timestamps = self.send_request(commands, output='config', check_status=True,
As the `return_timestamps` is reverted, `msg_timestamps` is not needed anymore.

2019-05-22 13:05 UTC, trishnaguha commented
@mikewiebe We are merging 2.8 PRs now, will you be able to get this PR ready if this is required in 2.8.1?

2019-05-23 17:23 UTC, mikewiebe commented
> @mikewiebe We are merging 2.8 PRs now, will you be able to get this PR ready if this is required in 2.8.1?

@trishnaguha Yes, I can do that.  Will tomorrow be too late for these changes?

2019-06-04 17:30 UTC, mikewiebe commented
@trishnaguha Finally got around to removing the `msg_timestamps`. This should be good to go now.

2019-06-05 15:54 UTC, Qalthos approved these changes

2019-06-06 04:04 UTC, trishnaguha approved these changes

2019-06-06 04:05 UTC, merged