Update include_role description
ansible/ansible pull request #56001
Opened 2019-05-01 20:01 UTC by acozine

##### SUMMARY

Rebased and updated version of #50204. 

Clarifies documentation of `include_role`: where is it allowed, etc.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
docs.ansible.com
include_role

2019-05-02 02:43 UTC, bcoca commented on lib/ansible/modules/utilities/logic/include_role.py
> +  - Does not support C(do_until) loops.
`until:` is the proper keyword for those loops

2019-05-02 02:45 UTC, bcoca requested changes

2019-05-02 02:45 UTC, bcoca commented on lib/ansible/modules/utilities/logic/include_role.py
> +  - Supports most keywords, including C(loop), C(with_items), and C(conditionals) (unlike M(import_role)).
`import_role` supports those keywords, but for inheritance, for include it applies to the task itself, the original phrasing was more accurate

2019-05-06 18:36 UTC, bcoca requested changes

2019-05-06 18:36 UTC, bcoca commented on lib/ansible/modules/utilities/logic/include_role.py
> +  - Task-level keywords, L(loops,../user_guide/playbooks_loops.html), and L(conditionals,../user_guide/playbooks_conditionals.html) will be applied only to the C(include_role) statement itself. If yo
1/2 is good, the other 1/2 should be more. 'If you want to have keywords applied to the contained tasks, consider using  import_role instead or use the "apply" keyword'

2019-05-06 18:36 UTC, bcoca commented on lib/ansible/modules/utilities/logic/include_role.py
> +  - The C(until) keyword, which retries a task until a condition is met, does not apply to C(include_role).
I would rephrase since its not just `until` 'There are several keywords ignored by this action, like `until` and `retries`.

2019-05-06 19:48 UTC, bcoca approved these changes

2019-05-06 20:17 UTC, samccann approved these changes

2019-05-06 20:17 UTC, merged