Add comment parameter to openssl_publickey
ansible/ansible pull request #56149
Opened 2019-05-06 22:29 UTC by tterranigma

##### SUMMARY

This adds a new parameter to the `openssl_publickey` module that allows the user to have a comment at the end of the public key, similar to the `-C` option of `ssh-keygen`.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

openssl_publickey

2019-05-07 04:52 UTC, felixfontein requested changes
First of all, how should this look like for PEM (OpenSSL) keys?

Then:
 - Idempotency checks are missing.
 - You should add integration tests for this.
 - You should add some validations, like disallowing `\n` in comments for OpenSSH keys. Also, what should be returned in absence of comments? Currently you're returning `undefined`.

2019-05-07 04:52 UTC, felixfontein commented on lib/ansible/modules/crypto/openssl_publickey.py
> +        version_added: "2.8"
```suggestion
        version_added: "2.9"
```
No new features are accepted for Ansible 2.8.

2019-05-07 04:52 UTC, felixfontein commented on lib/ansible/modules/crypto/openssl_publickey.py
> +            result['comment'] = self.pubkey_comment
You need to document this in return values if you return it.

2019-05-07 04:52 UTC, felixfontein commented on lib/ansible/modules/crypto/openssl_publickey.py
> +                    publickey_content = publickey_content + (" " + self.pubkey_comment).encode('utf-8')
I think this only makes sense for OpenSSH keys. For OpenSSL PEM keys, you don't want to append text in the same line directly after `----- END PUBLIC KEY -----`.

2019-05-23 20:57 UTC, mattclay commented
bot_status

2019-06-23 20:04 UTC, felixfontein commented
@nkakouros are you still around?

2019-06-23 21:41 UTC, nkakouros commented
@felixfontein Yes, but I am really swamped right now.. I would like to address the issues but I don't see this happening before September.

2019-06-24 04:44 UTC, felixfontein commented
No problem! Just a little warning: if this isn't merged before 2.9's Feature Freeze ([currently scheduled for August 29th](https://docs.ansible.com/ansible/devel/roadmap/ROADMAP_2_9.html#expected)), it will have to wait for Ansible 2.10.

2020-08-16 05:47 UTC, closed without merging