docs: display 'string' instead of '-' when 'type' isn't set
ansible/ansible pull request #56312
Opened 2019-05-10 17:15 UTC by pilou-

##### SUMMARY
[docs] default type is `str`: display `string` instead of `-` when `type` isn't set

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION
* without this change ([`zabbix_action` doc](https://docs.ansible.com/ansible/devel/modules/zabbix_action_module.html))
![Screenshot_2019-05-10_19-04-22](https://user-images.githubusercontent.com/1356830/57544483-fbbec800-7346-11e9-9947-78fe45a0036f.png)
* with this change
![Screenshot_2019-05-10_19-05-10](https://user-images.githubusercontent.com/1356830/57544492-02e5d600-7347-11e9-8e7c-190dde48d20b.png)

2019-05-10 17:54 UTC, bcoca approved these changes

2019-05-13 13:47 UTC, dagwieers commented
Please don't do this. If the type has not been set, it doesn't mean it is a string.
You have to explicitly add that a string is a string, if you want to make it appear correctly.
Lots of modules do not have types set, that is why I wrote https://github.com/ansible/ansible/pull/45805
And that is why we ended up with that dash.

2019-05-13 13:48 UTC, dagwieers requested changes
Please don't do this. If the type has not been set, it doesn't mean it is a string.
You have to explicitly add that a string is a string, if you want to make it appear correctly.
Lots of modules do not have types set, that is why I wrote https://github.com/ansible/ansible/pull/45805
And that is why we ended up with that dash.

2019-05-13 14:14 UTC, acozine commented
> If the type has not been set, it doesn't mean it is a string.

The default type is `string`, so I would argue that if a type has not been set, it is a string.

> You have to explicitly add that a string is a string, if you want to make it appear correctly.

We have done this for a lot of modules. But why not make things easier for the module docs where we have not added an explicit `type=string`? What would this break?

To me, this PR seems like the best of both worlds - the docs will display the `string` type and we don't have to update every single module to get there. 

@dagwieers am I missing or forgetting something?

2019-05-13 14:17 UTC, dagwieers commented
@acozine You are correct for the arg_spec, but you are wrong for the documentation.

In the documentation, if you did not specify a type, it means you did not specify a type, it doesn't mean that all undocumented arguments are strings.

2019-05-13 14:19 UTC, dagwieers commented
Just consider this:
https://docs.ansible.com/ansible/latest/modules/zabbix_host_module.html

Not everything in that module is a string. The only type that was mandatory in the past was boolean. So we know that all undocumented parameters are not booleans.

2019-05-13 14:22 UTC, dagwieers commented
This is also why I think it was silly my PR never got the proper attention, because it means we have to update *all* documentation, while that information is (except for raw) in the arg_spec.

2019-05-13 14:34 UTC, acozine commented
Hm. So in the validate-modules test, when we check the documentation against the argspec, we are not checking for `type`? I'm looking at https://github.com/ansible/ansible/blob/devel/test/sanity/validate-modules/ignore.txt and I don't see that `zabbix_host` module listed.

2019-05-13 14:37 UTC, pilou- commented
@acozine: when type is mentioned in `arg_specs` but missing in metadata, `validate-modules` doesn't raise an error and documented type should not be a string.

2019-05-13 14:39 UTC, dagwieers commented
No, we don't validate modules if parameter types are missing, because that would get almost every module listed in the ignore.txt. Maybe we should be reporting this when someone updates the module (so that she must fix the module before making any other changes).

But I am not sure we want to add to frustration of contributors like this.

2019-05-13 14:40 UTC, pilou- commented
Is there any reason to allow missing type in metadata but specified in `argument_spec` ?

2019-05-13 14:42 UTC, dagwieers commented
@pilou- We simply never documented parameter types in the past. They are missing because we only added the functionality to the documentation after we got 2500 modules that did not have this yet.

Again, the whole idea was to get that information from the arg_spec (and in cases where it was needed, the documentation could override the arg_spec, mostly useful for raw-type). But my PR/proposal was rejected/postponed at AnsibleFest San Francisco because this would be completely revised in the future. This might still be the case.

2019-05-13 14:43 UTC, dagwieers commented
Do we want 2500 modules listed in ignore.txt ? What does it bring us ? They will still be documented with a dash as the parameter type :-)

2019-05-13 14:48 UTC, acozine commented
> Do we want 2500 modules listed in ignore.txt ? What does it bring us ? They will still be documented with a dash as the parameter type :-)

No, definitely not. However, if we could discover how many of the modules have undocumented types that are NOT `string` that would give us the scope of the problem. If 80% or more of undocumented types really are `string`, then we could fix just the undocumented non-`string` options and use this approach for the rest.

2019-05-13 14:55 UTC, dagwieers commented
I had those numbers, and it is a lot of work. Using the arg_spec for this information is the best way forward. Every effort spend on this would be better spent elsewhere IMO. But I am not going to stop anyone from trying :-)

I focussed on the most important modules (and my own modules), and some of my PRss are still open. So maybe someone can look at those before accepting new PRs ?

2019-05-13 15:10 UTC, pilou- commented
> Do we want 2500 modules listed in ignore.txt ?

Why not ? 

```
$ git show 50adc5409bd23051dec718a0442f9075b13b4696:test/sanity/validate-modules/ignore.txt | wc -l
3362
```

At least, from now, new modules won't have undocumented type.

My proposal:
* short term
  1. update `validate-modules` (raise an error when type isn't documented) and `ignore.txt`
  2. once all types have been documented: apply this change
* long term: #45805

> some of my PRs are still open. So maybe someone can look at those before accepting new PRs ?

I don't understand: are they other PRs related to #45805 ?

2019-05-13 15:51 UTC, dagwieers commented
@pilou- That's 2500 modules times number of missing parameters. So most likely in the 15.000+ entries. If you want to fix all of them, be my guest. But beware that it is a moving target, so expect to be merging conflicts until everything is fixed.

2019-05-13 15:52 UTC, dagwieers commented
> At least, from now, new modules won't have undocumented type.

You can only do that, and leave the rest unchanged until #45805

2019-05-13 16:43 UTC, felixfontein commented on docs/templates/plugin.rst.j2
> +                        <span style="color: purple">@{ value.type | default('string') | documented_type }@</span>
Shouldn't this be
```suggestion
                        <span style="color: purple">@{ value.type | default('str') | documented_type }@</span>
```
?

2019-05-13 23:35 UTC, pilou- commented
I close this issue: undocumented types are allowed.

2019-05-13 23:35 UTC, closed without merging