VMware: Allow user to specify VM version to latest
ansible/ansible pull request #56391
Opened 2019-05-14 10:41 UTC by Akasurde

##### SUMMARY
User now can specify VM Hardware version to latest.

Fixes: #56273

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
lib/ansible/modules/cloud/vmware/vmware_guest.py

##### ADDITIONAL INFORMATION
```yaml
    - name: deploy vm
      vmware_guest:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: no
        datacenter: "{{ datacenter }}"
        state: present
        folder: "/{{ datacenter }}/vm"
        name: VM_1448
        disk:
          - size: 10mb
            autoselect_datastore: yes
        hardware:
          memory_mb: 512
          num_cpus: 1
          version: latest
        guest_id: rhel7_64guest
```

2019-05-14 10:52 UTC, Akasurde commented
cc @Tomorrow9

2019-05-17 18:22 UTC, jillr requested changes
one suggestion, otherwise lgtm - working on 6.7.

2019-05-17 18:22 UTC, jillr commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +                if temp_version == 'latest':
```suggestion
                if temp_version.lower() == 'latest':
```

2019-07-16 10:04 UTC, Tomorrow9 commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +                    if vm_obj is not None:
If 'template' parameter is set, and 'version' is also set, then 'vm_obj' is template, it's upgrade is not supported?

2019-09-12 11:22 UTC, Akasurde commented
superseded by #62188

2019-09-12 11:22 UTC, closed without merging