Fix chech_mode in ec2_instance
ansible/ansible pull request #56474
Opened 2019-05-15 16:33 UTC by fridlik

##### SUMMARY
This bugfix repairs bug in ec2_instance module during check_mode.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
cloud/aws/ec2_instance

##### ADDITIONAL INFORMATION
When I run a step with ec2_instance module, there is a bug in check_mode. The step will rename all the tags in matched ec2 instances even in check_mode. This bugfix repairs this bug.

2019-05-21 01:23 UTC, abadger requested changes
This change does not appear in devel and the stable-2.8 branches.  Unless there's a reason that this is not needed there, bugfixes need to be applied to devel and then backported to the stable-X.Y branches.  Otherwise, regressions can happen when a user upgrades from 2.7.x to the next release.

If you'd care to resubmit this against the devel branch, that would be great.

If you'd want it backported after that, it will also need a changelog entry.  Thanks.

2019-05-21 10:28 UTC, Shaps commented
@fridlik yes, this would happen in `devel` too, change the base branch to it so we can get this merged, we'll then get backport PRs to `stable-2.7` and `stable-2.8`. Please add a changelog fragment to this PR as well.

2019-05-21 14:51 UTC, abadger commented
2.7.11 is being released on Thursday.  We try to merge all backports on Monday before the release so that other projects, sites, and people have a chance to test the upcoming tree before a release.  This PR was not ready to merge on Monday so it won't go into 2.7.11 unless 2.7.11 is delayed.

2.7.11 is also the last release in the 2.7.x series which will contain non-critical bugfixes.  We don't think this qualifies as a critical bugfix so I will be closing it after the release on Thursday.  If you think this is critical, please take it to a Core Team IRC meeting ( https://github.com/ansible/community/tree/master/meetings ) to have a vote on whether to either slip the 2.7.11 release to get it in or to release a 2.7.12 with this change included.

2019-05-21 16:43 UTC, fridlik commented
@abadger I changed the base branch, so it could be merged into `devel` now. I think it is not so critical bug, so it is enought to be merged into `devel` only and backported into `stable-2.8`.
@Shaps changelog fragment: "ec2_instance - fix tags rename in check mode"

2019-05-21 18:48 UTC, Shaps commented
@fridlik Yes, that's what the changelog would look like. Follow the steps in the [docs](https://docs.ansible.com/ansible/latest/community/development_process.html#making-your-pr-merge-worthy), also make sure you rebase the PR as there seem to be lots of conflicts

2019-05-23 20:38 UTC, mattclay commented
Closing and re-opening to correct CI issues.

2019-06-05 23:12 UTC, jamescassell commented
bot_broken

Labeled as a backport even though it's against devel.  Likely the bot doesn't handle changing the base branch in a PR.

2019-06-07 22:30 UTC, fridlik commented
@Shaps I finally added the changelog fragment...

2019-06-09 18:30 UTC, Shaps commented
shipit

2019-07-11 12:47 UTC, fridlik commented
@mattclay why did you remove backport label? There is new version of unsible and still without this repair.

2019-07-11 15:38 UTC, mattclay commented
@fridlik The `backport` label is for PRs that do not target the devel branch. If this PR is merged, and a backport created for the stable branches, then those PRs would get the `backport` label.

2020-08-16 05:45 UTC, closed without merging