apt: honor cache_update=false on auto-install deps
ansible/ansible pull request #56549
Opened 2019-05-16 21:54 UTC by resmo

##### SUMMARY
 Fixed the issue the cache being updated while auto-installing its
  dependencies even ``update_cache`` is set to false. Fixes #51489

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

apt

##### ADDITIONAL INFORMATION

```paste below

```

2019-05-24 11:49 UTC, mkrizek commented on lib/ansible/modules/packaging/os/apt.py
> +            if module.params.get('update_cache') is not False:
I wonder if `is not False` needs an explaining comment.

2019-06-06 08:47 UTC, resmo commented
ready_for_review

2019-08-13 19:15 UTC, felixfontein approved these changes
Looks good, but core team has to make up their mind whether they want this change.

2019-08-14 11:56 UTC, jamescassell approved these changes
shipit

2019-08-15 15:23 UTC, samdoran requested changes
As discussed in the public IRC meeting on 2019-08-15, please add a porting guide entry describing the behavior change and we can merge this. Thanks!

2019-08-29 14:43 UTC, samdoran approved these changes

2019-08-29 14:43 UTC, samdoran commented on docs/docsite/rst/porting_guides/porting_guide_2.9.rst
> +* The ``apt`` module now honors ``update_cache=false`` while installing its own dependency and skips the cache update. Explicitly set ``update_cache=true` or omitting the param ``update_cache`` will
```suggestion
* The ``apt`` module now honors ``update_cache=false`` while installing its own dependency and skips the cache update. Explicitly setting ``update_cache=true`` or omitting the param ``update_cache`` will result in a cache update while installing its own dependency.
```

2019-08-29 14:43 UTC, samdoran commented on changelogs/fragments/51489-apt-not-honor-update-cache.yml
> +  dependencies even ``update_cache`` is set to false.
```suggestion
  dependencies even when ``update_cache`` is set to false.
```

2019-08-30 19:54 UTC, samdoran approved these changes

2019-08-30 19:57 UTC, merged