Fix junos zuul CI failures
ansible/ansible pull request #56601
Opened 2019-05-17 20:07 UTC by ganeshrn

##### SUMMARY

*  Fix assertion check to work with zuul CI
   for junos integration testcases

##### ISSUE TYPE

- Testcas Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2019-05-17 20:40 UTC, Qalthos approved these changes

2019-05-17 21:55 UTC, pabelanger approved these changes
This was tested at: 
  https://logs.zuul.ansible.com/74/74/a12f6c87d6ca0ef51e955a4bcb008d11ceda1915/check/ansible-test-network-integration-junos-python36/a85f910/job-output.html

no failures related to this any more

2019-05-23 14:55 UTC, pabelanger commented
recheck

2019-05-23 18:11 UTC, pabelanger commented
recheck

2019-05-23 20:08 UTC, pabelanger requested changes

2019-05-23 20:08 UTC, pabelanger commented on test/integration/targets/junos_rpc/tests/netconf/rpc.yaml
> +      - "'<interface-information' in result['xml']"
This isn't correct, we need to drop the single quote:

  https://logs.zuul.ansible.com/01/56601/0ddf48a36c67950e70abe358a8bb43fb4a9cf8d9/third-party-check/ansible-test-network-integration-junos-python37/d38da69/controller/ara-report/result/9ce267ed-c1b3-4ff8-9d61-69531b7807d7/

2019-05-23 21:17 UTC, pabelanger commented
recheck

2019-06-11 11:56 UTC, ganeshrn commented
Fixed by https://github.com/ansible/ansible/pull/57309

2019-06-11 11:56 UTC, closed without merging