Give open_url the same default user-agent as fetch_url
ansible/ansible pull request #56635
Opened 2019-05-20 12:18 UTC by mjrider

after debugging de difference between `get_url` and `lookup('url'` the difference seems to be the User-Agent.
This sync's the user-agent in both function

##### SUMMARY
While automating the configuration of our loadbalancer with an ip whitelist of cloudflare. had an issue that `get_url` could fetch the list of ip's and `lookup('url',..)` gave an 403, because cloudflare blocks the default python request user-agent.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
urls

##### ADDITIONAL INFORMATION
Broken url example:
`ansible -mdebug -a"msg={{lookup('url','https://cloudflare.com/ips-v4')}}" localhost`

More verbose output doesn't add any information
```
url lookup connecting to https://cloudflare.com/ips-v4
localhost | FAILED! => {
    "msg": "An unhandled exception occurred while running the lookup plugin 'url'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Received HTTP error for https://cloudflare.com/ips-v4 : HTTP Error 403: Forbidden"
}
```

Working get_url
`ansible -v -m get_url -a "url=https://cloudflare.com/ips-v4 dest=/tmp/foo" localhost`

2019-05-23 19:31 UTC, samdoran commented
Please create a changelog fragment. See [this fragment](https://github.com/ansible/ansible/blob/stable-2.8/changelogs/fragments/reboot-change-default-boot-command.yaml) as an example.

2019-05-23 19:32 UTC, sivel requested changes
Please also add a unit test to validate this change.

2020-07-19 12:19 UTC, Akasurde commented
@mjrider Are you still working on this change? Let me know. 


needs_info

2020-07-20 06:11 UTC, mjrider commented
no i'm not working on this
please consider this as a big report that there is a difference between the lookup `url` and the method `get_url` with an suggested fix.

i would not know how to write a unittest for this

2020-12-03 14:36 UTC, samdoran commented
Duplicate of #72324.

2020-12-03 14:36 UTC, closed without merging

2020-12-03 14:40 UTC, samdoran commented
The default will change in 2.11. If you are using Ansible 2.10 or later, you can set [`http_agent`](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/url_lookup.html#parameter-http_agent) for the lookup.