Add msg parameter to the mandatory filter
ansible/ansible pull request #56724
Opened 2019-05-21 14:53 UTC by bcavns01

The `mandatory` filter would be more useful, particularly when dealing with nested dictionaries, with the simple addition of a `msg` parameter for supplying it with a custom failure message.

##### SUMMARY

This change would make it possible to pass a custom failure message to be displayed when the `mandatory` filter catches an undefined variable.

The mandatory filter is great, but its failure message sometimes lacks enough context to be helpful with more complex templates and nested dictionaries.

This PR will let template designers add more context with custom error messages via a `msg` parameter.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

mandatory

##### ADDITIONAL INFORMATION

Before:
```
{% set current_prefix = source_details['prefixes'][neighbor['uplink_name']]|mandatory %}
```
```
fatal: [mpr01.xxx]: FAILED! => {"changed": false, "msg": "AnsibleFilterError: Mandatory variable 'verizon'  not defined."}
```
After:
```
{% set current_prefix = source_details['prefixes'][neighbor['uplink_name']]|mandatory(neighbor['uplink_name'] ~ ' not properly defined in source_details dictionary.') %}
```
```
fatal: [mpr01.xxx]: FAILED! => {"changed": false, "msg": "AnsibleFilterError: verizon not properly defined in source_details dictionary."}
```

2019-05-24 16:03 UTC, s-hertel requested changes
Works for me.

2019-05-24 16:03 UTC, s-hertel commented on lib/ansible/plugins/filter/core.py
> +            raise AnsibleFilterError(str(msg))
Use to_native instead of str.
```suggestion
            raise AnsibleFilterError(to_native(msg))
```

2019-07-10 19:06 UTC, bcavns01 commented on lib/ansible/plugins/filter/core.py
> +            raise AnsibleFilterError(str(msg))
I never got the github alert for this change request for some reason. :sob:  Requested change has been made.  Sorry for the delay.

2019-07-10 19:51 UTC, s-hertel approved these changes

2019-07-10 19:53 UTC, merged