nxos_ospf_vrf: Add 'bfd' support
ansible/ansible pull request #56748
Opened 2019-05-21 19:41 UTC by chrisvanheuveln

##### SUMMARY
Add support for `bfd` state in `nxos_ospf_vrf`

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
`nxos_ospf_vrf`

##### ADDITIONAL INFORMATION
```paste below

```

2019-05-29 19:00 UTC, mikewiebe commented
LGTM

2019-06-05 15:50 UTC, Qalthos requested changes

2019-06-05 15:50 UTC, Qalthos commented on lib/ansible/modules/network/nxos/nxos_ospf_vrf.py
> +    type: bool
You've listed a default in the argspec, but not in the documentation
```suggestion
    type: bool
    default: false
```

2019-06-05 15:51 UTC, Qalthos commented on lib/ansible/modules/network/nxos/nxos_ospf_vrf.py
> +    type: bool
You've listed a default in the argspec, but not in the documentation
```suggestion
    type: bool
    default: false
```

2019-06-05 19:52 UTC, closed without merging

2019-06-05 20:20 UTC, chrisvanheuveln commented
I did a rebase and push --force but... *something* happened and it wiped out my earlier commits, which apparently then caused it to auto-close this PR. I wasn't sure if the branch was fixable so I just created a new branch and patched the commits to it. The replacement PR is #57425