Update __init__.py
ansible/ansible pull request #57164
Opened 2019-05-30 08:44 UTC by amirwollman

##### SUMMARY
GCP dynamic inventory - removed separator in case prefix is an empty string.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
inventory plugin

##### ADDITIONAL INFORMATION
Added conditional before setting the separator (default '_') which sets it to '' in case prefix is '' as well.

**Before change**
```
 "all": {
     "children": [
         "__built_in_method_items_of_dict_object_at_0x2bc4db0_",
         "_analytics",
         "_consul_server",
         "_dashboardapi",
         "_elasticsearch",
         "_http_server",
         "_https_server",
         "_inventory",
         "_k2bq",
         "_kafka",
         "_kibana",
         "_logstash_k2bq",
         "_logstash_k2es",
         "_mysql",
         "_neo4j",
         "_ssl_offload",
         "_zookeeper",
         "ungrouped"
     ]
```
**After change**
```
 "all": {
     "children": [
         "_built_in_method_items_of_dict_object_at_0x2bc4db0_",
         "analytics",
         "consul_server",
         "dashboardapi",
         "elasticsearch",
         "http_server",
         "https_server",
         "inventory",
         "k2bq",
         "kafka",
         "kibana",
         "logstash_k2bq",
         "logstash_k2es",
         "mysql",
         "neo4j",
         "ssl_offload",
         "zookeeper",
         "ungrouped"
     ]
```

2019-05-30 19:38 UTC, bcoca requested changes
I do think the new behaviour is 'nicer' but this would require a configuration toggle, that defaults to current behaviour, any change on the default would have to go through a deprecation period

2019-06-01 11:15 UTC, amirwollman commented
Just noticed now my commit is missing an equal (=) sign. But by your comment @bcoca I'm assuming there is more to be done here.
I'm a very new contributor and am not entirely familiar with the best practices applied here, so if there's a manual or guidelines document you can refer me to, I'll do my very best to follow these.

P.S I'll go ahead and patch my last commit just so it will at least pass the compilation tests.

2019-06-06 16:01 UTC, s-hertel commented
@amirwollman This is a nice improvement. :-)

I don't know if there's documentation on keeping backwards compatibility. Since the separator is used currently by Ansible regardless of whether or not a prefix is specified and only omitted with `separator: ""`, people using this behavior will have their playbooks potentially broken by this PR. To take away behavior a [deprecation period](https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#deprecation-cycle) needs to be used so people are warned and have time to update their setup without things breaking. You should add a toggle to enable this behavior, but keep the current behavior as the default (optionally adding a deprecation period to change the default). You can add a toggle here: https://github.com/ansible/ansible/blob/devel/lib/ansible/config/base.yml (check out the other INVENTORY related toggles for example), and then you can access that toggle by importing constants as C and using C.TOGGLE_NAME.

2019-06-13 18:44 UTC, kustodian commented
Maybe we could introduce a new parameter which would toggle this. That way we wouldn't have to worry about depreciation or backward compatibility. Not sure about the name, maybe "trailing_separator"?

2020-10-23 15:26 UTC, relrod commented
Closing in favor of #60882

2020-10-23 15:26 UTC, closed without merging