group_chars: default change warning only when needed
ansible/ansible pull request #57312
Opened 2019-06-03 15:01 UTC by jamescassell

##### SUMMARY

This squashed the "future default change" deprecation warning in cases where the user is not using the default value for the TRANSFORM_INVALID_GROUP_CHARS setting.

This is a minimal change as requested in https://meetbot.fedoraproject.org/ansible-meeting/2019-05-23/ansible_core_irc_public_meeting.2019-05-23-15.00.log.html#l-319

This should be backported to 2.8.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2019-06-03 15:37 UTC, jamescassell commented
from IRC #ansible-devel
> 11:29 <•abadger1999> Toshio Kuratomi: @ sivel @ cyberpear https://github.com/ansible/ansible/pull/57312 looks like it matches with what we discussed to me.  It looks good to merge and open backports for.

2019-06-03 16:11 UTC, bcoca requested changes
it is missing proper validation of choices and documentation

2019-06-03 16:17 UTC, jamescassell commented
> it is missing proper validation of choices and documentation

Can you describe what you mean in more detail?  I'm not adding any new choices here.  The change itself is documented in the changelog fragment.

2019-06-03 16:21 UTC, bcoca commented
but does not appear as a documented option, nor are the options being correctly displayed in docs

2019-06-03 16:26 UTC, jamescassell commented
> but does not appear as a documented option, nor are the options being correctly displayed in docs

This PR does not claim to fix any docs issues.  Would you like the currently-undocumented `ignore` option to be documented as part of this PR?  I'm happy to do that in a separate PR, to expedite this one unless you think feel it should be part of this one.  At least @abadger is fine with backporting this this as-is.

2019-06-04 15:52 UTC, bcoca commented
closing as subset of #55474

2019-06-04 20:16 UTC, samdoran commented
I'm reopening this because it does seem to do exactly what we asked for in the [2019-05-23 IRC meeting](https://meetbot.fedoraproject.org/ansible-meeting/2019-05-23/ansible_core_irc_public_meeting.2019-05-23-15.00.log.html#l-354): small targeted fix that checks origin.

This PR needs to dovetail with the work being done in #55474.

2019-06-04 20:31 UTC, abadger commented
I've evaluated the changes.  The only difference is that the other fix moves the condition outside of the check for ```"never"```.  This is only an important difference if the default value is changed.  Since the point of this deprecation message is to warn that the default will change in the future, it feels like the soonest this would happen is when we change the default value intentionally in 2.12.  At that point we'd want to remove this check altogether.  If we forgot to remove it then, the positioning of the conditional in this PR, we would not get a deprecation message at that point (which is our desired behaviour) whereas we would continue to get the deprecation message with the positioning in bcoca's PR (Undesirable but it would point out that we had dead code lying around).  Six in one, half dozen the other.

rebuild_merge

2019-06-04 21:04 UTC, merged