Fixing bug - netbox_device
ansible/ansible pull request #57435
Opened 2019-06-05 22:21 UTC by DoctorKM

##### SUMMARY

Fixing bug that made impossible to add device to Netbox via ansible when Netbox has more than one rack. 
Fixes: #57397 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

netbox_device

2019-06-09 22:06 UTC, FragmentedPacket requested changes

2019-06-09 22:06 UTC, FragmentedPacket commented on test/units/module_utils/net_tools/test_netbox.py
> +    assert QUERY_TYPES.get("rack") == "name"
You'll have to change L27 to match the `name` of the rack. ex. `Some rack` so the test passes for it.

2019-06-10 14:47 UTC, FragmentedPacket approved these changes

2019-06-10 14:48 UTC, FragmentedPacket commented
!component_name=lib/ansible/module_utils/net_tools/netbox/netbox_utils.py

2019-06-10 14:48 UTC, FragmentedPacket commented
shipit

2019-07-10 14:41 UTC, FragmentedPacket commented
@s-hertel Here is another one to be merged and fix some issues.

2019-09-03 17:49 UTC, minitriga commented
Any update on when this will be merged?

2019-09-03 17:54 UTC, FragmentedPacket commented
I would've hoped a few minor versions ago.

I'm in the process of moving everything to Ansible Collections if you want to use it from there and should have the bug fixes that have been merged and haven't been merged. This will be the preferred way of using the Netbox modules moving forward from 2.9 on.

https://galaxy.ansible.com/fragmentedpacket/netbox_modules

Unfortunately it only works with running Ansible from source at the moment

2019-11-26 17:48 UTC, richardjohnallsopp commented
Hey can I get an update on where this will be live? I'm running ansible 2.9.1 and still seeing the bug. Or is there a workaround I can implement?

2019-11-27 15:37 UTC, FragmentedPacket commented
@richardjohnallsopp I would suggest using the Netbox Modules Ansible Collection from now on. It's under active development.

2019-11-27 16:17 UTC, richardjohnallsopp commented
@FragmentedPacket, thanks man I took a look, is there anymore documentation on getting it up and running and on using the new modules? I see you've added loads so I'm really keen to get it working.

2019-11-27 22:31 UTC, FragmentedPacket commented
@richardjohnallsopp I do need to update the README.md, but it does have an example of a playbook.

Since you're on Ansible 2.9 you would install the collection via galaxy:
`ansible-galaxy collection install fragmentedpacket.netbox_modules`

And then look at the following doc on how to use them:
https://docs.ansible.com/ansible/latest/user_guide/collections_using.html#id7

You can always open an issue on the github repo for them and we can discuss further there.

2019-11-28 00:06 UTC, richardjohnallsopp commented
Thanks man I've opened an issue as I have installed the collections and still see the rack key error.

2020-07-14 12:56 UTC, Akasurde commented
Fixed via https://github.com/netbox-community/ansible_modules/commit/becfd7b878a65d821e8e15c7a0c9e0a520ed7496

2020-07-14 12:56 UTC, closed without merging