Avi credentials added sub-options
ansible/ansible pull request #57531
Opened 2019-06-07 08:31 UTC by chaitanyaavi

##### SUMMARY

Avi credentials added sub-options

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

- module_utils/network/avi/ansible_utils.py
- plugins/doc_fragments/avi.py

##### ADDITIONAL INFORMATION

```paste below

```

2019-06-10 18:34 UTC, grastogi23 approved these changes

2019-06-10 18:35 UTC, grastogi23 reviewed
+shipit

2019-06-12 14:33 UTC, Qalthos requested changes

2019-06-12 14:33 UTC, Qalthos commented on lib/ansible/module_utils/network/avi/ansible_utils.py
> +        controller=dict(default=os.environ.get('AVI_CONTROLLER', '')),
I think you should instead use `fallback` in these cases. See https://docs.ansible.com/ansible/latest/dev_guide/developing_program_flow_modules.html#fallback

For example:
```suggestion
        controller=dict(fallback=(env_fallback, ['AVI_CONTROLLER'])),
```

(Requires `from ansible.module_utils.basic import env_fallback` above)

2019-06-12 16:00 UTC, grastogi23 approved these changes
+shipit

2019-06-12 16:13 UTC, grastogi23 commented
@Qalthos Thanks for your suggestion. This was very helpful and we would rewire some more modules with similar approach.

2019-06-12 16:19 UTC, merged