[WIP] Validate args for includes in handlers too
ansible/ansible pull request #57537
Opened 2019-06-07 12:37 UTC by mkrizek

##### SUMMARY
Fixes issue when the following would fail with `No include file was specified to the include`:

```yaml
  handlers:
    - name: handler
      include_tasks:                                                                                                                                                                                              
        file: include_tasks_file_include.yml
```

It is because `HandlerTaskInclude.load()` was missing args validation that `TaskInclude.load()` had. So override `load_data()` in `TaskInclude` and put the validation there so `HandlerTaskInclude` could use it too.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

lib/ansible/playbook/task_include.py

2019-06-07 12:55 UTC, mkrizek commented on lib/ansible/playbook/task_include.py
> +    def load_data(self, ds, variable_manager=None, loader=None):
Ugh, `IncludeRole` is inherited from `TaskInclude` as well.

2019-07-26 06:40 UTC, Andersson007 requested changes
there are no unit tests for HandlerTaskInclude, would be great to see them

2020-05-08 08:55 UTC, kustodian commented
It would be great if this got fixed. It's really annoying because when it happens you are not sure if you made a mistake, or it's bug.

2020-05-11 14:44 UTC, sivel approved these changes
This looks simple enough to me.

My only comment is instead of doing:

```python
task = t.load_data(...)
task = t.check_options(task)
```

I'd have normally done:

```python
task = t.check_options(
    t.load_data(...),
    data
)
```

This also needs a changelog fragment.

2020-05-12 07:35 UTC, merged