Update local module options
ansible/ansible pull request #57553
Opened 2019-06-07 17:57 UTC by itdependsnetworks

##### SUMMARY

Update local module options

Update local module options to include ansible.cfg file.
##### ISSUE TYPE
- Docs Pull Request

+label: docsite_pr

##### SUMMARY

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

Docs

##### ADDITIONAL INFORMATION

```paste below

```

2019-06-11 15:23 UTC, bcoca requested changes

2019-06-11 15:23 UTC, bcoca commented on docs/docsite/rst/dev_guide/developing_locally.rst
> +* Adding or adjusting the ``library`` parameter to the ``ansible.cfg`` file
I would point to the actual config setting DEFAULT_MODULE_PATH, which then details the different ways of setting it, not just the ini key w/o section information.

2019-06-17 18:57 UTC, bcoca commented on docs/docsite/rst/dev_guide/developing_locally.rst
> +
this is conflating the 'setting name' with the ini section/key, I would just point to the link to the config page that explains the different ways of setting it.

2019-06-17 18:57 UTC, bcoca commented on docs/docsite/rst/dev_guide/developing_locally.rst
> +
also that is only for modules, you might want to point out that each plugin type has it's own config setting

2019-06-17 19:30 UTC, bcoca approved these changes

2019-06-17 19:33 UTC, itdependsnetworks commented
Thanks, I wasn’t following, and meant I circle back and ask

2019-06-17 20:22 UTC, acozine commented
Thanks @itdependsnetworks for suggesting updates to the ansible documentation. I hope the updated version of your changes still addresses your use case.

2019-06-17 20:22 UTC, merged