file: Raise error on permission denied
ansible/ansible pull request #57574
Opened 2019-06-08 16:20 UTC by Jakski

##### SUMMARY
Fixes #57573.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
`file` module

##### ADDITIONAL INFORMATION
`os.path.lexists` won't report error when process has no permission to access path. See: https://github.com/python/cpython/blob/e119b3d136bd94d880bce4b382096f6de3f38062/Lib/posixpath.py#L174. It means that inaccessible paths will be treated as absent.

2019-09-16 01:09 UTC, Jakski commented
This fix is waiting for approval for more than month. Should I change it somehow before it can be considered good for merging?

2019-12-25 15:51 UTC, Akasurde commented
@Jakski Thanks for the PR. I added this PR in the next IRC meeting  https://github.com/ansible/community/issues/507. Please make sure you attend the meeting and get reviews for this PR.

2020-01-23 21:53 UTC, samdoran requested changes
Please create a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment) and integration tests. See [this fragment](https://github.com/ansible/ansible/blob/c2f528b7686c9573aa8493357219e0bbe4416dd3/changelogs/fragments/reboot-change-default-boot-command.yaml) as an example.

2020-01-23 21:53 UTC, samdoran commented on lib/ansible/modules/files/file.py
> +        if os.lstat(b_path):
This is not quite the correct fix. We probably need to use something `os.access()` to check if the file exists and if we can access it:
```python
if os.access(b_path, os.F_OK):  # checks that the file exists, following symlinks
    if not os.access(b_path, os.R_OK):  # check that we can read the file
        # probably warn, for now, then change to an error later

2026-02-25 23:05 UTC, pkingstonxyz commented
@Jakski Any interest in continuing this? If not I'll pick it back up. Thanks!

2026-02-26 23:57 UTC, Jakski commented
@pkingstonxyz Feel free to pick it up. Code probably changed a lot since I reported this issue, so you will probably need to rebase.

2026-03-11 12:08 UTC, Akasurde commented
Superseded by https://github.com/ansible/ansible/pull/86608

2026-03-11 12:08 UTC, closed without merging