ios_config: Handle confirmation prompt after version change (#57745)
ansible/ansible pull request #57749
Opened 2019-06-12 11:44 UTC by jrunu

##### SUMMARY
Handle "Warning different version" prompt when saving config to Non-Volatile RAM on Cisco iOS devices.
Fixes #57745

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
ios_config

##### ADDITIONAL INFORMATION
First time contributer to ansible. Has no idea what he's doing.

2019-06-12 13:46 UTC, pabelanger commented
Do you have a way to reproduce this, on an already configured ios device? If so, we can write a test here and add it to our integration test suite.

2019-06-13 15:25 UTC, jrunu commented
I played a bit in the lab and wasn't able to trigger this without performing an actual upgrade i.e. booting from one image into another. (I had ideas about messing with the version in the startup-config and reloading). So basically: 
1. Set the older to boot and load into it
2. Set the newer version to boot
3. Write config
4. Reload
5. Write config -> Warning prompt

The versions in my particular case were 15.4-M3(M8) to 15.6-M3(M6a). My resident cisco expert told me that this is an edge case.  This warning isn't trigger with all minor release (not bugfix releases)  upgrades, which I originally thought. There was at some point a breaking change in the configuration syntax. This is what triggers the warning. However I can't tell you the specific release. And for completeness sake, this was performed on a C886 device.

2019-06-13 15:46 UTC, pabelanger commented
Thanks for the detailed write up, that is what I was expecting. Today we don't do in-place upgrades of ios appliances for testing (in theory is something we could do). Lets wait until others review, to see if they have ideas how we could test.

2019-12-11 15:18 UTC, Qalthos commented
recheck

2019-12-11 15:27 UTC, Qalthos requested changes

2019-12-11 15:27 UTC, Qalthos commented on lib/ansible/modules/network/ios/ios_config.py
> +                                                prompt='Overwrite the previous NVRAM configuration?[confirm]',
You almost had it right the first time, but you needed to use a raw string instead (or double escape, but this is why we have raw strings)

```suggestion
                                                prompt=r'Overwrite the previous NVRAM configuration\?\[confirm\]',
```

2020-05-22 13:37 UTC, danielmellado commented
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/cisco.ios
Please re-submit this PR in the above repository.
If you have further questions please stop by IRC or the mailing list:

IRC: #ansible-network on irc.freenode.net
mailing list: https://groups.google.com/forum/#!forum/ansible-project

2020-05-22 13:37 UTC, closed without merging