Fix junos integration zuul CI failures
ansible/ansible pull request #57755
Opened 2019-06-12 14:06 UTC by ganeshrn

##### SUMMARY

* Fix netconf plugin to return `data_xml` object if present for the device handler object or else return raw xml

* Add check to run lldp integration test cases only if lldp is supported on the target host

Merged to devel https://github.com/ansible/ansible/pull/57309
(cherry picked from commit 0957835a4814bfc0c7649675963de5e88df5060e)

##### ISSUE TYPE

- Bugfix Pull Request
- Test Pull Request

##### COMPONENT NAME

plugins/netconf/__init__.py
netconf_config

##### ADDITIONAL INFORMATION

```paste below

```

2019-06-12 14:42 UTC, danielmellado approved these changes

2019-06-12 19:40 UTC, pabelanger approved these changes

2019-06-15 19:51 UTC, pabelanger commented
recheck

2019-06-18 18:20 UTC, pabelanger requested changes
It looks like we are seeing a failure in netconf_config:

  https://logs.zuul.ansible.com/55/57755/fffe63f82ed015983d45553d435d7347b2be4388/third-party-check-silent/ansible-test-network-integration-junos-python27/d964840/controller/ara-report/result/d66b1496-2033-4f1b-ad07-eaeefd5957c7/

We should also fix that here, to minimize the number of backports.

2019-06-19 06:22 UTC, ganeshrn commented
@pabelanger Backported PR https://github.com/ansible/ansible/pull/56138 and updated the changelog

2019-06-20 16:27 UTC, pabelanger commented
recheck

2019-06-20 18:17 UTC, pabelanger commented
@ganeshrn please include https://github.com/ansible/ansible/pull/57966 and https://github.com/ansible/ansible/pull/57073 to help improve test stability

2019-06-20 21:10 UTC, pabelanger commented
@ganeshrn I also need you to backport https://github.com/ansible/ansible/pull/57882 as you have included https://github.com/ansible/ansible/pull/56138/ which had a bug.

2019-06-24 22:02 UTC, abadger commented
The decision from the networking team leadership is that none of these bugs qualify as critical so we'll have to continue testing stable-2.7 releases manually rather than enabling zuul for 2.7.x

2019-06-24 22:02 UTC, closed without merging