Add Python 3 support to ovirt4 inventory script.
ansible/ansible pull request #57824
Opened 2019-06-14 04:34 UTC by rmkraus

##### SUMMARY
Python 3 only allows strings through the config parser. This is fine for 
the URL, Username, and Password since these values are required. The CA 
File is optional so an empty string is used in lieu of None in the 
config dictionary.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
ovirt4

##### ADDITIONAL INFORMATION

2019-06-14 05:35 UTC, machacekondra commented
+1

2019-06-14 06:35 UTC, mwperina approved these changes
shipit

2019-06-15 08:07 UTC, resmo commented
Please add a changelog fragment https://docs.ansible.com/ansible/latest/community/development_process.html?#creating-a-changelog-fragment, thanks.

2019-06-16 13:00 UTC, rmkraus commented
@resmo 

I have added the changelog fragment. Thanks!

2019-06-19 20:55 UTC, samdoran requested changes

2019-06-19 20:55 UTC, samdoran commented on changelogs/fragments/57824-python-3-support-ovirt-dynamic-inv.yml
> +  - ovirt3 inventory - Updated the dynamic inventory script for Python 3 support
```suggestion
  - ovirt4 inventory - Updated the dynamic inventory script for Python 3 support
```

2019-06-20 21:21 UTC, rmkraus commented on changelogs/fragments/57824-python-3-support-ovirt-dynamic-inv.yml
> +  - ovirt3 inventory - Updated the dynamic inventory script for Python 3 support
Good catch, should be fixed now. 👍

2019-06-20 21:36 UTC, rmkraus commented
Looks like the Shippable tests ran before the commit was made available. Is there a way to re-run it? It should check out fine.

2019-06-21 16:04 UTC, samdoran approved these changes

2019-06-21 16:05 UTC, samdoran commented
@rmkraus That happens sometimes. The GitHub CDN can be a bit slow to show new commits. We can rerun the tests or you can close/reopen the PR to trigger a new test run.

2019-06-21 16:05 UTC, merged