More iosxr integration zuul CI test fixes
ansible/ansible pull request #57909
Opened 2019-06-16 06:53 UTC by ganeshrn

##### SUMMARY

* Ignore `<rpc-reply>` node from candidate and
  running configuration in xml diff

* Add route-policy as prerequisite to BGP coonfiguration
  in integration test

##### ISSUE TYPE

- Bugfix Pull Request
- Test Pull Request

##### COMPONENT NAME

module_utils/network/iosxr/iosxr.py
test/integration/targets/iosxr_bgp/tests/cli/basic.yaml
##### ADDITIONAL INFORMATION

```paste below

```

2019-06-16 08:19 UTC, ganeshrn commented
recheck

2019-06-16 15:14 UTC, pabelanger requested changes

2019-06-16 15:14 UTC, pabelanger commented on lib/ansible/module_utils/network/iosxr/iosxr.py
> +            running_data = etree.tostring(running_data_ele).strip()
Another encoding issue, I believe you need:

  to_text(etree.tostring())

2019-06-16 15:14 UTC, pabelanger commented on lib/ansible/module_utils/network/iosxr/iosxr.py
> +            candidate_data = etree.tostring(candidate_data_ele).strip()
same comment

2019-06-16 23:23 UTC, pabelanger commented on test/integration/targets/iosxr_bgp/tests/cli/basic.yaml
> +      register: result
This isn't used, perhaps we can assert it was removed.

2019-06-17 14:10 UTC, pabelanger approved these changes
Thanks!

2019-06-17 15:22 UTC, danielmellado approved these changes
LGTM, Thanks!

2019-06-17 15:22 UTC, merged