PR to fix ios bgp TC failure
ansible/ansible pull request #58010
Opened 2019-06-18 17:42 UTC by justjais

Signed-off-by: Sumit Jaiswal <sjaiswal@redhat.com>

##### SUMMARY

PR to fix ios bgp TC failure, as the cleanup was not done properly in case of failure or if the execution was terminated abruptly. 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

ios_bgp
##### ADDITIONAL INFORMATION

```paste below

```

2019-06-18 17:44 UTC, justjais commented
recheck

2019-06-18 19:38 UTC, pabelanger commented
The python37 failure is new, looks to be a network failure or appliance problem. But, to be safe we should look to see if our testing didn't cause it. This is the first time I have seen it.

2019-06-18 19:38 UTC, pabelanger commented
recheck

2019-06-18 21:08 UTC, pabelanger commented
recheck

2019-06-18 21:38 UTC, pabelanger commented
@justjais Looking at the code, we are not changing anything in our testing, just making sure we always delete the ios_bgp code we've added. Can you explain more how this will actually fix our flapping tests?

2019-06-20 11:06 UTC, justjais commented
recheck

2019-06-20 13:03 UTC, justjais commented
recheck

2019-06-20 13:50 UTC, pabelanger requested changes

2019-06-20 13:50 UTC, pabelanger commented on test/integration/targets/ios_bgp/tests/cli/basic.yaml
> +    when: ansible_net_version != "15.6(2)T"
Lets move this 1 task down, as we can still do the idempotent task, just not validate the results.

2019-06-20 13:50 UTC, pabelanger commented on test/integration/targets/ios_bgp/tests/cli/basic.yaml
> +        - 'result.changed == false'
Or, if we want to keep above, we also need to add a condition check here.

2019-06-20 15:04 UTC, pabelanger approved these changes
Thanks!

2019-06-20 15:08 UTC, danielmellado approved these changes
/lgtm

2019-06-20 15:09 UTC, merged