Add aci_extsubnet.py
ansible/ansible pull request #58087
Opened 2019-06-19 17:18 UTC by sig9org

##### SUMMARY

Implementation of ACI External Subnet module.

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

aci_extsubnet.py

##### ADDITIONAL INFORMATION

Tested on 4.1(2g).

2019-06-24 10:24 UTC, sig9org commented
Hi,

Do you need anything to merge?
Please let me know if there is a shortage.

Regards,

2019-08-16 21:12 UTC, devarshishah3 approved these changes

2019-08-16 21:16 UTC, devarshishah3 requested changes
please change the naming convention of the module to aci_l3out_extsubnet.

Add a note to specify the tested version in the comments in the module

2019-08-27 13:55 UTC, merged

2019-08-27 13:55 UTC, dagwieers commented
Thanks !