Added unit tests for avi API utils
ansible/ansible pull request #58382
Opened 2019-06-26 10:27 UTC by chaitanyaavi

##### SUMMARY

Added unit tests for avi API utils

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

- Added unit tests for ansibble_utils.py

##### ADDITIONAL INFORMATION

```paste below

```

2019-06-26 16:14 UTC, grastogi23 approved these changes
+shipit

2019-07-17 16:31 UTC, Qalthos requested changes

2019-07-17 16:31 UTC, Qalthos commented on test/units/module_utils/network/avi/test_avi_api_utils.py
> +            'cloud_ref': 'https://10.10.25.42/api/cloud/cloud-afe8bf2c-9821-4272-9bc6-67634c84bec9',
Please don't use routable IP addresses in tests, even if they are never used. Documentation ranges (https://tools.ietf.org/html/rfc5737) help ensure that this is clear to readers.

2019-07-17 16:31 UTC, Qalthos commented on test/units/module_utils/network/avi/test_avi_api_utils.py
> +        assert not x
I'm really not sure what this is supposed to do. You've proved that `diff` is truthy above, and now you're asserting that whatever object `diff` is is symmetric over `not`, but I'm not sure why. You don't seem to be making any claims about the contents of `diff`, so I don't quite see what the value of this test is.

2019-07-18 08:16 UTC, chaitanyaavi commented on test/units/module_utils/network/avi/test_avi_api_utils.py
> +            'cloud_ref': 'https://10.10.25.42/api/cloud/cloud-afe8bf2c-9821-4272-9bc6-67634c84bec9',
Updated all the ips

2019-07-18 08:17 UTC, chaitanyaavi commented on test/units/module_utils/network/avi/test_avi_api_utils.py
> +        assert not x
Removed unnecessary code

2019-07-19 04:13 UTC, grastogi23 approved these changes
+shipit

2019-07-24 15:05 UTC, Qalthos approved these changes

2019-07-24 15:05 UTC, merged