BUGFIX azure_rm_subnet_facts: when trying to get all subnets, the wro…
ansible/ansible pull request #58491
Opened 2019-06-28 08:31 UTC by ronansalmon

##### SUMMARY
- fix the following error :
 An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: get() takes at least 4 arguments (3 given)

- fix ansible_facts variable

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
azure_rm_subnet_facts.py

2019-06-28 09:39 UTC, felixfontein requested changes

2019-06-28 09:39 UTC, felixfontein commented on lib/ansible/modules/cloud/azure/azure_rm_subnet_facts.py
> +azure_subnets:
Same here: never change return values.

2019-06-28 09:39 UTC, felixfontein commented on lib/ansible/modules/cloud/azure/azure_rm_subnet_facts.py
> +            ansible_facts=dict(azure_subnets=[])
Also, don't return `ansible_facts` from cloud modules.

2019-07-01 07:12 UTC, Fred-sun commented
@ronansalmon Thank for your contribution, Please help resolve the shippable fail when you're free! Thank you very much!

2019-07-01 08:38 UTC, ronansalmon commented
Will send a patch when i'll get back in 3 weeks.

2019-07-22 10:13 UTC, ronansalmon commented on lib/ansible/modules/cloud/azure/azure_rm_subnet_facts.py
> +azure_subnets:
fix in last commit

2019-08-06 09:55 UTC, Fred-sun commented
@yungezz @MyronFanQiu Please take a look this PR when you are free! ready_for_review, Thank you very much!

2019-08-28 02:11 UTC, Fred-sun commented
@zikalino @yungezz ready_for_review

2019-09-06 08:50 UTC, ronansalmon commented
I have updated the path to be compatible with azure_rm_subnet_info

2019-09-06 09:38 UTC, felixfontein commented
@ronansalmon please ask someone from the Azure team, I'm not familiar with Azure at all.

BTW, all bugfixes need a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#changelogs-how-to). So you should definitely add one.

2019-09-06 09:40 UTC, felixfontein reviewed
Needs changelog fragment. Can't comment besides that.

2019-09-06 10:16 UTC, ronansalmon commented
Ok, I've pushed a changelog.
@felixfontein, as far as I can understand, this PR says that you have requested a change. What needs to be changed ?
Ronan

2019-09-06 20:42 UTC, felixfontein commented
@ronansalmon if you scroll up, then you can see that on June 28, I request some changes with regard to return values. Since these changes have been addressed, I'm happy.

2019-09-06 20:43 UTC, felixfontein approved these changes
Ok with regard that no `ansible_facts` are returned. This was a problem with an earlier version of the PR. I cannot comment on anything else; this should be reviewed by the Azure team.

2019-09-06 20:43 UTC, felixfontein commented
(It seems to be hard to get rid of the "request changes"...)

2019-09-09 02:17 UTC, Fred-sun commented
@yungezz @zikalino The PR change small, please review and push for merge! Thank you very much!

2019-09-20 07:32 UTC, Fred-sun commented
ping to merge

2019-10-21 08:01 UTC, Fred-sun commented
ready_for_review

2019-11-25 08:00 UTC, Fred-sun commented
@haiyuazhang merge or not? Please check! Thank you very much!

2019-12-31 06:03 UTC, Fred-sun commented
@haiyuazhang @gavinfish ping to merge!

2020-02-11 02:35 UTC, Fred-sun commented
@haiyuazhang @gavinfish @zikalino Ping to merge!

2020-03-18 02:35 UTC, Fred-sun commented
@ronansalmon Thank you for taking the time to contribute to this PR. We will transfer ansible 's azure module related Issue and PR to azure collection (https://github.com/ansible-collections/azure/pulls), can you transfer the Issue to azure collection repo?

2020-03-18 14:16 UTC, ronansalmon commented
Unfortunately I won't bother. I don't think that this issue will ever be merged. The Azure team didn't care about this minor patch for the last 6 month. They didn't event bother replying to your multiple calls:(

So, I gave up using Azure and Ansible's azure module. I'm still using Ansible though, and will still try to contribute !

@Fred-sun, thanks for trying.

2020-03-18 14:17 UTC, closed without merging