Add the azure_rm_..._info modules
ansible/ansible pull request #58576
Opened 2019-07-01 08:07 UTC by smile37773

##### ISSUE TYPEt
- New Module Pull Request

##### COMPONENT NAM
azure_rm_azurefirewall_info.py
azure_rm_gallery_info.py
azure_rm_galleryimage_info.py 
azure_rm_galleryimageversion_info .py

2019-07-02 01:20 UTC, zikalino commented on lib/ansible/modules/cloud/azure/azure_rm_azurefirewall_info.py
> +#!/usr/bin/python
pls exclude firewall for now from this commit, this one is a bit more complex and will require some more work.
gallery modules are simpler and higher priority

2019-07-02 01:20 UTC, zikalino commented on lib/ansible/modules/cloud/azure/azure_rm_gallery_info.py
> +# Copyright (c) 2019 Zim Kalinowski, (@zikalino)
Change the name to yours

2019-07-02 01:21 UTC, zikalino commented on lib/ansible/modules/cloud/azure/azure_rm_gallery_info.py
> +          sample: null
we need also sample values, if you run the playbook you can copy it from there

2019-07-02 06:43 UTC, zikalino commented on lib/ansible/modules/cloud/azure/azure_rm_gallery_info.py
> +    properties:
properties should be flattened. so for instance value returned by azure_rm_gallery_info should be similar to structure of parameters passed to azure_rm_gallery.

2019-07-02 06:43 UTC, zikalino commented on lib/ansible/modules/cloud/azure/azure_rm_gallery_info.py
> +    type:
don't return type, it's irrelevant

2019-07-02 06:44 UTC, zikalino commented
please also add tests to azure_rm_gallery integration test

2019-07-02 06:46 UTC, zikalino commented on lib/ansible/modules/cloud/azure/azure_rm_gallery_info.py
> +    properties:
you should implement and use format_item() function to do that

2019-07-03 04:03 UTC, zikalino requested changes
just a bunch of smaller comments and we will be done :-)

2019-07-03 04:03 UTC, zikalino commented on lib/ansible/modules/cloud/azure/azure_rm_gallery_info.py
> +            'provisioningState': item['properties']['provisioningState']
just change to snake case -> provisioning_state, to follow Ansible conventions

2019-07-03 04:03 UTC, zikalino commented on lib/ansible/modules/cloud/azure/azure_rm_galleryimage_info.py
> +    osState:
same here, snake case, and convert value to lowercase

2019-07-03 04:03 UTC, zikalino commented on lib/ansible/modules/cloud/azure/azure_rm_galleryimage_info.py
> +    osType:
snake_case, value to lower (linux/windows)

2019-07-03 04:03 UTC, zikalino commented on lib/ansible/modules/cloud/azure/azure_rm_galleryimageversion_info.py
> +    publishingProfile:
snake_case

2019-07-03 04:03 UTC, zikalino commented on lib/ansible/modules/cloud/azure/azure_rm_galleryimageversion_info.py
> +    provisioningState:
snake_case

2019-07-03 04:03 UTC, zikalino commented on lib/ansible/modules/cloud/azure/azure_rm_gallery_info.py
> +short_description: Get Gallery info.
Gallery -> Azure Shared Image Gallery

2019-07-03 04:03 UTC, zikalino commented on lib/ansible/modules/cloud/azure/azure_rm_gallery_info.py
> +  - Get info of Gallery.
Gallery -> Azure Shared Image Gallery

2019-07-03 04:03 UTC, zikalino commented on lib/ansible/modules/cloud/azure/azure_rm_gallery_info.py
> +    A list of dict results where the key is the name of the Gallery and the
Gallery can be lowercase here

2019-07-03 04:03 UTC, zikalino commented on lib/ansible/modules/cloud/azure/azure_rm_galleryimage_info.py
> +short_description: Get GalleryImage info.
I think we can just change "GalleryImage" to "Azure SIG Image"

2019-07-03 04:03 UTC, zikalino commented on lib/ansible/modules/cloud/azure/azure_rm_galleryimage_info.py
> +    A list of dict results where the key is the name of the GalleryImage and the
here we can just use "image" instead of GalleryImage

2019-07-03 04:03 UTC, zikalino commented on lib/ansible/modules/cloud/azure/azure_rm_galleryimage_info.py
> +gallery_images:
gallery_images -> `"images"`

2019-07-03 04:03 UTC, zikalino commented on lib/ansible/modules/cloud/azure/azure_rm_galleryimageversion_info.py
> +gallery_image_versions:
just "versions" will be ok

2019-07-03 05:47 UTC, zikalino approved these changes

2019-07-03 05:48 UTC, merged

2019-07-03 12:18 UTC, Andersson007 commented
@smile37773 @zikalino hey, these azure tests fail on unrelated PR, e.g., https://app.shippable.com/github/ansible/ansible/runs/130646/110/console for https://github.com/ansible/ansible/pull/58623.

Testing became difficult...

Looks like this:
```
10:20 <testhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1562154933.93-98980176504656/ > /dev/null 2>&1 && sleep 0'
10:20 The full traceback is:
10:20 WARNING: The below traceback may *not* be related to the actual failure.
10:20   File "/tmp/ansible_azure_rm_galleryimageversion_payload_DCkqlY/__main__.py", line 397, in create_update_resource
10:20     30)
10:20   File "/tmp/ansible_azure_rm_galleryimageversion_payload_DCkqlY/ansible_azure_rm_galleryimageversion_payload.zip/ansible/module_utils/azure_rm_common_rest.py", line 80, in query
10:20     raise exp
10:20 
10:20 fatal: [testhost]: FAILED! => {
10:20     "changed": false, 
10:20     "invocation": {
10:20         "module_args": {
10:20             "ad_user": null, 
10:20             "adfs_authority_url": null, 
10:20             "api_profile": "latest", 
10:20             "append_tags": true, 
10:20             "auth_source": null, 
10:20             "cert_validation_mode": null, 
10:20             "client_id": null, 
10:20             "cloud_environment": "AzureCloud", 
10:20             "gallery_image_name": "myImage", 
10:20             "gallery_name": "myGalleryebce060794", 
10:20             "location": "West US", 
10:20             "name": "10.1.3", 
10:20             "password": null, 
10:20             "profile": null, 
10:20             "publishing_profile": {
10:20                 "endOfLifeDate": "2021-10-01t00:00:00+00:00", 
10:20                 "excludeFromLatest": true, 
10:20                 "replicaCount": 3, 
10:20                 "source": {
10:20                     "managedImage": {
10:20                         "id": "/subscriptions/6d22db98-3e5f-4ab9-bdf9-2f911a2775f7/resourceGroups/ansible-core-ci-prod-991ee744-e8ec-4af3-888b-6f86a91dedfc-1/providers/Microsoft.Compute/images/testimagea"
10:20                     }
10:20                 }, 
10:20                 "storageAccountType": "Standard_LRS", 
10:20                 "targetRegions": [
10:20                     {
10:20                         "name": "West US", 
10:20                         "regionalReplicaCount": 1
10:20                     }, 
10:20                     {
10:20                         "name": "East US", 
10:20                         "regionalReplicaCount": 2, 
10:20                         "storageAccountType": "Standard_ZRS"
10:20                     }
10:20                 ]
10:20             }, 
10:20             "resource_group": "ansible-core-ci-prod-991ee744-e8ec-4af3-888b-6f86a91dedfc-1", 
10:20             "secret": null, 
10:20             "state": "present", 
10:20             "subscription_id": null, 
10:20             "tags": null, 
10:20             "tenant": null
10:20         }
10:20     }, 
10:20     "msg": "Error creating the GalleryImageVersion instance: Azure Error: InvalidParameter\nMessage: Parameter 'galleryImageVersion.properties.storageProfile' is not allowed.\nTarget: galleryImageVersion.properties.storageProfile"
10:20 }
10:20 
10:20 PLAY RECAP *********************************************************************
10:20 testhost                   : ok=29   changed=8    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
10:20 
10:21 Command exited with status 2 after 276.723038912 seconds.
10:21 NOTICE: If azure_rm_gallery failed due to permissions, the test policy may need to be updated. For help, consult @mattclay or @gundalow on GitHub or #ansible-devel on IRC.
```
Could you look at this, please

2019-07-03 12:34 UTC, zikalino commented
@Andersson007 could you add "unstable" to the aliases? I will look into that tomorrow, since something changed with the service

2019-07-03 12:43 UTC, willthames commented
It may be https://github.com/ansible/ansible/pull/57386 rather than this PR

2019-07-03 13:53 UTC, Andersson007 commented
@zikalino , https://github.com/ansible/ansible/pull/58670

2019-07-03 14:00 UTC, Andersson007 commented
but we found out that it wouldn't work https://docs.ansible.com/ansible/latest/dev_guide/testing/sanity/integration-aliases.html#unstable :)
There's no rush for me, I can wait for tomorrow, nps

2019-07-03 14:39 UTC, Andersson007 commented
@zikalino , we are going to disable them by https://github.com/ansible/ansible/pull/58672