azure recovery services vault modules
ansible/ansible pull request #58743
Opened 2019-07-05 06:09 UTC by smile37773

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
azure_rm_recoveryservicesvault.py
azure_rm_recoveryservicesvault_info.py

2019-07-05 06:23 UTC, zikalino commented
looks good in general, i think you may start putthing together integration test, in a meanwhile i will add detailed review

2019-07-05 06:26 UTC, smile37773 commented
> looks good in general, i think you may start putthing together integration test, in a meanwhile i will add detailed review
Ok~

2019-07-09 01:45 UTC, zikalino commented on lib/ansible/modules/cloud/azure/azure_rm_recoveryservicesvault.py
> +# Copyright (c) 2019 Zim Kalinowski, (@zikalino)
pls change the name to yours

2019-07-09 01:46 UTC, zikalino commented on lib/ansible/modules/cloud/azure/azure_rm_recoveryservicesvault.py
> +  e_tag:
we can remove this one, it's readonly

2019-07-09 01:47 UTC, zikalino commented on lib/ansible/modules/cloud/azure/azure_rm_recoveryservicesvault.py
> +  upgrade_details:
need to check if upgrade_details should be here. I think it may be readonly. is there anything here that we can actually update?

2019-07-09 01:48 UTC, zikalino commented on lib/ansible/modules/cloud/azure/azure_rm_recoveryservicesvault.py
> +  provisioning_state:
provisioning_state is readonly as well, so let's remove it from parameters

2019-07-09 01:48 UTC, zikalino commented on lib/ansible/modules/cloud/azure/azure_rm_recoveryservicesvault.py
> +  provisioning_state:
it should be returned in response though

2019-07-09 01:48 UTC, zikalino commented on lib/ansible/modules/cloud/azure/azure_rm_recoveryservicesvault.py
> +  sample: null
needs sample value

2019-07-09 01:49 UTC, zikalino commented on lib/ansible/modules/cloud/azure/azure_rm_recoveryservicesvault_info.py
> +      sample: null
no sample value

2019-07-09 01:49 UTC, zikalino commented on lib/ansible/modules/cloud/azure/azure_rm_recoveryservicesvault_info.py
> +
could you check if "upgrade_details" are returned in real scenario?

2019-07-09 01:50 UTC, zikalino commented on test/integration/targets/azure_rm_recoveryservicesvault/aliases
> +disabled
remove "disabled", if it's here test won't run

2019-07-09 01:51 UTC, zikalino commented on test/integration/targets/azure_rm_recoveryservicesvault/aliases
> +disabled
also add "azure_rm_recoveryservicesvault_info" in aliases

2019-07-09 01:52 UTC, zikalino commented on test/integration/targets/azure_rm_recoveryservicesvault/tasks/main.yml
> +    sku:
shouldn't be "sku_name"?

2019-07-09 01:53 UTC, zikalino commented on test/integration/targets/azure_rm_recoveryservicesvault/tasks/main.yml
> +
also run the same task again to check if nothing changes,

and then try to change one of the parameters, I wonder if we can change for instance SKU

2019-07-09 09:15 UTC, zikalino commented
@mattclay could you pls add Microsoft.RecoveryServices?

2019-07-09 14:49 UTC, samdoran commented
@zikalino I can take care of adding that to the account. I am helping out @mattclay so you can ping me with testing related things as well.

2019-07-09 17:38 UTC, samdoran commented
@zikalino I have added Microsoft.RecoverServices

2019-07-09 22:07 UTC, zikalino commented
thanks @samdoran !

2019-08-07 08:10 UTC, Fred-sun commented
@yungezz @zikalino @MyronFanQiu Please take a look this PR when you free! Thank you very much!

2019-08-07 08:10 UTC, Fred-sun commented
ready_for_review

2019-08-07 08:38 UTC, yungezz requested changes

2019-08-07 08:38 UTC, yungezz commented on lib/ansible/modules/cloud/azure/azure_rm_recoveryservicesvault.py
> +class AzureRMVaults(AzureRMModuleBaseExt):
full service name: AzureRMRecoveryServiceVault

2019-08-07 08:38 UTC, yungezz commented on lib/ansible/modules/cloud/azure/azure_rm_recoveryservicesvault.py
> +            response = self.mgmt_client.query(self.url,
why use rest api?

2019-08-27 02:50 UTC, Fred-sun commented
@smile37773 @zikalino Please update this PR according by comments! Thank you very much!

2019-09-18 08:43 UTC, Fred-sun commented
@nitzmahone @jborean93 review_need

2019-10-16 07:58 UTC, Fred-sun commented
ping to review

2019-11-11 07:40 UTC, Fred-sun commented
@mybayern1974 @haiyuazhang review_need!

2020-01-08 03:21 UTC, Fred-sun commented
@haiyuazhang @gavinfish @nitzmahone @jborean93

2020-02-11 02:22 UTC, Fred-sun commented
@haiyuazhang @gavinfish @nitzmahone @jborean93 review_need!

2020-03-18 02:34 UTC, Fred-sun commented
@smile37773 Thank you for taking the time to contribute to this PR. We will transfer ansible 's azure module related Issue and PR to azure collection (https://github.com/ansible-collections/azure/pulls), can you transfer the Issue to azure collection repo?

2020-08-20 09:36 UTC, Akasurde commented
Hi @smile37773, Thank you very much for your interest in Ansible. This plugin/module is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/azure<br><br>If you have further questions please stop by IRC or the mailing list:<br><br>* IRC: #ansible on irc.freenode.net<br>* mailing list: https://groups.google.com/forum/#!forum/ansible-project<br><br>needs_info<br>

2020-08-20 09:36 UTC, closed without merging