update ce_vrrp to fix a bug
ansible/ansible pull request #59185
Opened 2019-07-17 14:10 UTC by yanzhangi

##### SUMMARY

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2019-07-18 07:18 UTC, yuandongx requested changes
Missed type

2019-07-18 07:18 UTC, xuxiaowei0512 commented on lib/ansible/modules/network/cloudengine/ce_vrrp.py
> -        default: 'no'
miss type defined.
The blow is same as this.

2019-07-18 12:13 UTC, xuxiaowei0512 commented
shipit

2019-07-18 12:14 UTC, xuxiaowei0512 commented
bot_status

2019-07-19 01:02 UTC, yanzhangi commented
read_for_review

2019-07-19 01:28 UTC, hwDCN commented
shipit

2019-07-19 01:33 UTC, merged