Enable vault configuration via environment variables
ansible/ansible pull request #59334
Opened 2019-07-20 06:44 UTC by UkuLoskit

##### SUMMARY
These changes enable specifying all of the `hashi_vault` configuration options via environment variables. This is useful, because having to specify these values on each invocation is quite cumbersome. 

As an added bonus, this also serves as a workaround for https://github.com/ansible/ansible/issues/57414.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
hashi_vault lookup plugin

2019-07-22 15:07 UTC, bcoca requested changes

2019-07-22 15:07 UTC, bcoca commented on lib/ansible/plugins/lookup/hashi_vault.py
> +        - name: VAULT_PASSWORD
missing version_added

2019-07-22 15:07 UTC, bcoca commented on lib/ansible/plugins/lookup/hashi_vault.py
> +        self.namespace = kwargs.get('namespace', os.environ.get('VAULT_NAMESPACE'))
this is not needed, use `get_option` instead

2019-09-11 20:49 UTC, darxriggs commented
@UkuLoskit can you resolve the conflicts and incorporate the review comments?

2019-09-12 00:49 UTC, bcoca commented on lib/ansible/plugins/lookup/hashi_vault.py
> +        - name: VAULT_USERNAME
i would use HASHIVAULT or some other way to avoid confusing with other 'vaults'

2020-08-16 05:32 UTC, closed without merging