Fixed line 174 changed from None to the actual net_id variable
ansible/ansible pull request #59395
Opened 2019-07-22 16:20 UTC by borborpa

##### SUMMARY

Changed line 174 to use the net_id variable that is passed to it, instead of the static value of None.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

meraki_content_filtering

##### ADDITIONAL INFORMATION

Fix for Bug #59391
Allows you to specify net_id instead of net_name.

```paste below
Before:
TASK [meraki-mx : Set Content Filtering] **************************************************************************************************************************************************
failed: [localhost] (item=N_VALIDNET1) => {"ansible_loop_var": "item", "changed": false, "item": "N_VALIDNET1", "msg": "No network found with the name None", "my_idx2": 0, "response": "OK (unknown bytes)", "status": 200}
failed: [localhost] (item=L_VALIDNET2) => {"ansible_loop_var": "item", "changed": false, "item": "L_VALIDNET2", "msg": "No network found with the name None", "my_idx2": 1, "response": "OK (unknown bytes)", "status": 200}

PLAY RECAP ********************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

After:
TASK [meraki-mx : Set Content Filtering] **************************************************************************************************************************************************
changed: [localhost] => (item=N_VALIDNET1)
changed: [localhost] => (item=L_VALIDNET2)

PLAY RECAP ********************************************************************************************************************************************************************************
localhost                  : ok=3    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

```

2019-07-22 21:54 UTC, kbreit commented
@borborpa This looks pretty good. Would you remove the whitespace so shippable is happy? I'll test it and work on getting it merged then. Thank you very much for the contribution. I think you're the first person to write a PR against Meraki, so thank you!

2019-07-23 10:39 UTC, borborpa commented
Trailing whitespace removed.

2019-08-01 04:07 UTC, kbreit commented
@borborpa I apologize for not being responsive on this one. I haven’t been receiving these updates via email and haven’t had an opportunity to follow up. I’ll review probably tomorrow night and work with the team on getting it merged.

2019-08-01 09:15 UTC, borborpa commented
No worries - I'm sure this isn't even close to a huge issue for 99.9% of users.

2019-08-02 01:39 UTC, kbreit commented
@borborpa I'm happy with this. Please add a changelog fragment in `changelogs/fragments` to document this bug fix.

2019-08-07 16:20 UTC, kbreit requested changes
Please create a changelog fragment describing the fix.

2019-12-05 18:23 UTC, borborpa commented
I apologize for the delay.  changelog/fragment has been added.

2019-12-05 19:45 UTC, kbreit commented
shipit

2019-12-18 16:08 UTC, Qalthos approved these changes

2019-12-18 17:10 UTC, merged