post-rebase, sed rhv/ovirt
ansible/ansible pull request #59413
Opened 2019-07-23 01:56 UTC by funixz

##### SUMMARY

follow-up to funixz:patch-8, setting up ovirt/rhv to have presence in scenario guides.

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

ovirt scenario guides in docs

##### ADDITIONAL INFORMATION

n/a

2019-07-23 02:21 UTC, Akasurde requested changes

2019-07-23 02:21 UTC, Akasurde commented on docs/docsite/rst/scenario_guides/ovirt_scenarios/faq.rst
> +Ansible oVirt FAQ
```suggestion
Ansible oVirt FAQ
*****************
```

2019-07-23 02:21 UTC, Akasurde commented on docs/docsite/rst/scenario_guides/ovirt_scenarios/faq.rst
> +oVirt is the upsteam open-source edition of Red Hat Virtualization.
```suggestion
oVirt is the upstream open-source edition of Red Hat Virtualization. 
```

2019-07-23 02:21 UTC, Akasurde commented on docs/docsite/rst/scenario_guides/ovirt_scenarios/faq.rst
> +oVirt is the upsteam open-source edition of Red Hat Virtualization.
```suggestion
oVirt is the upstream open-source edition of Red Hat Virtualization. 
```

2019-07-23 02:21 UTC, Akasurde commented on docs/docsite/rst/scenario_guides/ovirt_scenarios/oVirt_concepts.rst
> +This delegation host will be any host where you have ``pyVmomi`` installed.
Replace pyVmomi with `ovirt-engine-sdk-python` library.

2019-07-23 02:21 UTC, Akasurde commented on docs/docsite/rst/scenario_guides/ovirt_scenarios/oVirt_concepts.rst
> +Ansible oVirt modules often require the ovirt-engine-sdk-python package installed.
```suggestion
Ansible oVirt modules often require the ``ovirt-engine-sdk-python`` package installed.
```

2019-07-23 02:21 UTC, Akasurde commented on docs/docsite/rst/scenario_guides/ovirt_scenarios/oVirt_intro.rst
> +They are found here: `oVirt Modules <https://docs.ansible.com/ansible/latest/modules/list_of_cloud_modules.html#ovirt>`
```suggestion
They are found here: `oVirt Modules <https://docs.ansible.com/ansible/latest/modules/list_of_cloud_modules.html#ovirt>`_
```

2019-07-23 02:21 UTC, Akasurde commented on docs/docsite/rst/scenario_guides/ovirt_scenarios/scenario_remove_vm.rst
> +    * The Python module ``Pyvmomi`` must be installed on the Ansible control node (or Target host if not executing against localhost).
```suggestion
    * The Python module ``ovirt-engine-sdk-python`` must be installed on the Ansible control node (or Target host if not executing against localhost).
```

2019-07-23 02:21 UTC, Akasurde commented on docs/docsite/rst/scenario_guides/ovirt_scenarios/scenario_remove_vm.rst
> +    * We recommend installing the latest version with pip: ``pip install Pyvmomi`` (as the OS packages are usually out of date and incompatible).
```suggestion
    * We recommend installing the latest version with pip: ``pip install ovirt-engine-sdk-python`` (as the OS packages are usually out of date and incompatible).
```

2019-07-23 02:21 UTC, Akasurde commented on docs/docsite/rst/scenario_guides/ovirt_scenarios/scenario_remove_vm.rst
> +You can run these modules against another server that would then connect to the API if localhost does not have access to oVirt/RHV engine. If so, the required Python modules will need to be installed
```suggestion
You can run these modules against another server that would then connect to the API if localhost does not have access to oVirt/RHV engine. If so, the required Python modules will need to be installed on that target server. We recommend installing the latest version with pip: ``pip install ovirt-engine-sdk-python`` (as the OS packages are usually out of date and incompatible).
```

2019-07-23 02:21 UTC, Akasurde commented on docs/docsite/rst/scenario_guides/ovirt_scenarios/scenario_rename_vm.rst
> +You can run these modules against another server that would then connect to the API if localhost does not have access to engine. If so, the required Python modules will need to be installed on that t
```suggestion
You can run these modules against another server that would then connect to the API if localhost does not have access to engine. If so, the required Python modules will need to be installed on that target server. We recommend installing the latest version with pip: ``pip install ovirt-engine-sdk-python`` (as the OS packages are usually out of date and incompatible).
```

2019-07-23 02:21 UTC, Akasurde commented on docs/docsite/rst/scenario_guides/ovirt_scenarios/scenario_rename_vm.rst
> +    {
Replace this with actual output of `ovirt_` module output.

2019-07-23 02:21 UTC, Akasurde commented on docs/docsite/rst/scenario_guides/ovirt_scenarios/oVirt_external_doc_links.rst
> +List of useful links for oVirt/ oVirt
```suggestion
List of useful links for oVirt/RHV
```

2019-07-23 02:21 UTC, Akasurde commented on docs/docsite/rst/scenario_guides/ovirt_scenarios/oVirt_external_doc_links.rst
> +oVirt/ oVirt and Ansible.
```suggestion
oVirt/RHV and Ansible.
```

2019-07-23 02:21 UTC, Akasurde commented on docs/docsite/rst/scenario_guides/ovirt_scenarios/faq.rst
> +What is oVirt? What is oVirt?
```suggestion
What is oVirt? What is RHV?
```

2019-07-24 08:19 UTC, Akasurde commented on docs/docsite/rst/scenario_guides/ovirt_scenarios/faq.rst
> +----------------------------------------------------------------
```suggestion
Can I deploy a virtual machine on a standalone oVirt Host server ?
------------------------------------------------------------------
```

2019-07-24 08:19 UTC, Akasurde commented on docs/docsite/rst/scenario_guides/ovirt_scenarios/faq.rst
> +What version of oVirt/RHV will Ansible modules work with?
```suggestion
What version of oVirt/RHV will Ansible modules work with?
---------------------------------------------------------
```

2019-07-24 08:20 UTC, Akasurde commented on docs/docsite/rst/scenario_guides/ovirt_scenarios/faq.rst
> +Does oVirt/RHV have a REST APT?
```suggestion
Does oVirt/RHV have a REST APT?
-------------------------------
```

2019-07-24 09:35 UTC, Akasurde commented on docs/docsite/rst/scenario_guides/ovirt_scenarios/oVirt_scenarios.rst
> +   scenario_find_vm_folder
This is non-existing document reference.

2019-07-24 09:48 UTC, Akasurde commented
@funixz I updated few things in this PR. You can build docs locally by installing [`sphinx`](http://www.sphinx-doc.org/en/master/) and 

```
cd <Ansible_checkout>/docs/docsite
rst=scenario_guides/guide_ovirt.rst make htmlsingle
```

Check errors and warnings

2019-07-31 18:01 UTC, samccann commented
Please remove all mention of RHV  and keep this as oVirt only please, unless someone in  Red Hat is signing up to officially support these modules.

2019-07-31 18:05 UTC, funixz commented
> Please remove all mention of RHV and keep this as oVirt only please, unless someone in Red Hat is signing up to officially support these modules.

will do

2019-08-12 16:20 UTC, acozine commented
@funixz you can fix the `not-in-toc-tree` errors by either adding the page(s) in question to a TOC, or marking them `:orphan:`. See https://raw.githubusercontent.com/ansible/ansible/devel/docs/docsite/rst/scenario_guides/vmware_scenarios/vmware_getting_started.rst for an example.

2020-02-11 20:38 UTC, samccann commented
@funixz can you please fix the merge commit comment above and rebase etc?

I will add some general comments in a review as well.

2020-02-11 20:43 UTC, samccann commented
Some general comments:

- include only files/sections that have actual content. If you want to keep the other sections as reminders to yourself or another contributor, you can comment them out so they won't generate HTML.  

- remove the list of modules. By the time we get this in shape and published, they'll all have moved to a collection so you can just point there. For now, they aren't needed.

- remove the basic stuff like what is a playbook, etc. That is already covered in the ansible docs. You can link to https://docs.ansible.com/ansible/latest/user_guide/basic_concepts.html#ansible-concepts for example (though please use an rst :ref: for that.

I'll take a deeper look once you've cleaned these bigger items up.  Thanks!

2020-02-21 20:07 UTC, funixz commented
Sorry I haven't been able to jump back onto this. Once I can slide in the time, I will. I haven't forgotten.

2020-08-21 15:21 UTC, samccann commented
Hi @funixz  - any update on this PR and where you want to go with it?  Thanks!

2020-08-21 15:36 UTC, arendej commented
> Hi @funixz - any update on this PR and where you want to go with it? Thanks!

I'll eventually jump back on this. If anyone else is in line to contribute, the more the merrier.
We can close the PR, if that's preferred.

2021-12-20 20:08 UTC, samccann commented
At this point, scenario guides should be added or moved to the most appropriate collection repository.  See https://github.com/ansible-collections/kubernetes.core/pull/143 and https://github.com/ansible/ansible/pull/75249 for an example of how this is done.

Thanks @arendej for the work you put into this!

2021-12-20 20:08 UTC, closed without merging