Resource module for ios_lacp_interfaces
ansible/ansible pull request #59516
Opened 2019-07-24 11:54 UTC by justjais

##### SUMMARY

Resource module for `ios_lacp_interfaces`, with supported operations and respective integration tests.
(ref model: https://github.com/ansible-network/resource_module_models/pull/33)

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

ios_lacp_interfaces
##### ADDITIONAL INFORMATION

```paste below

```

2019-07-24 12:29 UTC, NilashishC requested changes

2019-07-24 12:29 UTC, NilashishC commented on lib/ansible/module_utils/network/ios/facts/lacp_interfaces/lacp_interfaces.py
> +            # params = utils.validate_config(self.argument_spec, {'config': objs})
The `validate_config` call needs to be present.

2019-07-24 12:29 UTC, NilashishC commented on lib/ansible/modules/network/ios/ios_lacp_interfaces.py
> +  sample: ['command 1', 'command 2', 'command 3']
Having a couple of sample commands in doc would be good.

2019-07-24 12:29 UTC, NilashishC commented on lib/ansible/modules/network/ios/ios_lacp_interfaces.py
> +before:
We need to specify the type of before/after in docs, else, Shippable complains.

2019-07-24 12:29 UTC, NilashishC commented on lib/ansible/module_utils/network/ios/config/lacp_interfaces/lacp_interfaces.py
> +            commands = self._state_overridden(**kwargs)
As @ganeshrn pointed out, using kwargs is redundant, since we know what we're sending to the methods.

2019-07-24 14:38 UTC, pabelanger commented
recheck

2019-07-24 16:02 UTC, justjais commented
recheck

2019-07-24 16:06 UTC, justjais commented
recheck

2019-07-31 14:25 UTC, pabelanger commented
Note to myself, this will need a new image for zuul.a.c to properly test.

2019-08-19 12:02 UTC, danielmellado requested changes
A few nits there! starts looking good!

2019-08-19 12:02 UTC, danielmellado commented on lib/ansible/modules/network/ios/ios_lacp_interfaces.py
> +#
don't forget the python shebang here

2019-08-19 12:02 UTC, danielmellado commented on lib/ansible/modules/network/ios/ios_lacp_interfaces.py
> +          type: int
this is marked as int on the argspec.

2019-08-19 17:03 UTC, justjais commented
recheck

2019-08-19 17:06 UTC, pabelanger commented
lets not merge this until we understand why it is failing, if we don't this will affect other PRs.

2019-08-19 17:11 UTC, justjais commented
@pabelanger It was failing coz of IOS version, as this would work only on IOS L2 switches and now I have included a version check and based on which it'll skip the current zuul IOS version. I have tested the integration tests locally via IOS L2 device and it passes and smooth. :)

2019-08-19 17:23 UTC, pabelanger commented
k, thanks! As for 'recheck' you only need to leave the comment to trigger another run of testing. When you pushed up your new PR, zuul started running it. So, recheck here is not needed

2019-08-20 05:32 UTC, ganeshrn approved these changes

2019-08-20 08:07 UTC, merged