Add na_santricity_firmware module
ansible/ansible pull request #59529
Opened 2019-07-24 13:46 UTC by ndswartz

##### SUMMARY
Module performs controller firmware downloads on NetApp E-Series storage systems.
Add unit and integration tests.

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
na_santricity_firmware

##### ADDITIONAL INFORMATION

```paste below
ansible 2.9.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/swartzn/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/swartzn/projects/ansible/ansible/lib/ansible
  executable location = /home/swartzn/projects/ansible/ansible/bin/ansible
  python version = 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]
```

2019-08-01 22:20 UTC, ndswartz commented
shipit

2019-08-14 15:03 UTC, lmprice requested changes

2019-08-14 15:03 UTC, lmprice commented on lib/ansible/modules/storage/netapp/na_santricity_firmware.py
> +short_description: NetApp E-Series manage firmware bundles and for legacy systems manage embedded firmware, and nvsram file.
"NetApp E-Series manage firmware" -- better short description

2019-08-14 15:03 UTC, lmprice commented on lib/ansible/modules/storage/netapp/na_santricity_firmware.py
> +            - Use at you own risk. Certain non-optimal states could result in data loss.
your

2019-08-14 15:03 UTC, lmprice commented on lib/ansible/modules/storage/netapp/na_santricity_firmware.py
> +            - This flag will force firmware to be activated in spite of the health check.
"regardless of the result of the health check"

2019-08-14 15:03 UTC, lmprice commented on lib/ansible/modules/storage/netapp/na_santricity_firmware.py
> +    ssid: "{{ eseries_ssid }}"
Can you give some hard-coded examples here? I find that things like the api_url are difficult to discern.

2019-08-14 15:03 UTC, lmprice commented on lib/ansible/modules/storage/netapp/na_santricity_firmware.py
> +        self.nvsram_name = re.split(r"/", self.nvsram)[-1]
I would consider using os.path.basename() here as well. Technically, the path separator is system dependent.

2019-08-19 19:07 UTC, lmprice approved these changes
shipit

2019-08-21 15:45 UTC, thedoubl3j reviewed
everything looks good to me, only question I have is the module naming. This deviates from previous e-series module naming?

2019-08-22 18:07 UTC, ndswartz commented
@thedoubl3j We've decided to be consistent with the netapp_e prefix and make the adjustments when we move to collections. I'll try to make the necessary changes for both na_santricity_firmware and na_santricity_drive_firmware modules by the end of the week.

2019-08-23 20:06 UTC, ndswartz commented
@thedoubl3j I've updated the module's name to reflect the netapp_e prefix.

2019-08-23 20:14 UTC, carchi8py approved these changes

2019-08-26 20:07 UTC, ndswartz commented
@lmprice @carchi8py Would you mind reapplying the shipit. I changed the name from na_santricity_firmware to netapp_e_firmware. The new naming convention will be applied in the santricity collection.

2019-08-26 20:36 UTC, lmprice approved these changes
shipit

2019-08-26 20:59 UTC, carchi8py approved these changes

2019-08-28 21:17 UTC, thedoubl3j approved these changes
thanks for adjusting the name back. lgtm. shipit

2019-08-28 21:17 UTC, merged