Update mso_schema_template_anp_epg.py
ansible/ansible pull request #59746
Opened 2019-07-29 20:13 UTC by aciguru

##### SUMMARY

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2019-08-14 18:08 UTC, aciguru commented
ready_for_review

2019-08-16 20:57 UTC, devarshishah3 commented on lib/ansible/modules/network/aci/mso_schema_template_anp_epg.py
> +        type: str
Add example of the task as well

2019-08-16 20:58 UTC, devarshishah3 requested changes
add task example with vrfref

2019-08-16 23:01 UTC, aciguru commented
ready_for_review

2019-08-16 23:21 UTC, devarshishah3 approved these changes

2019-08-16 23:45 UTC, dagwieers commented
rebuild_merge

2019-08-19 17:03 UTC, aciguru commented
ready_for_review

2019-08-19 20:40 UTC, aciguru commented
bot_status

2019-08-19 22:00 UTC, aciguru commented
@dagwieers, shippable check seems to get canceled. Could you please suggest a work around for this?

2019-08-21 02:00 UTC, merged