Only error out if the gid exists with a different group name
ansible/ansible pull request #59769
Opened 2019-07-30 11:22 UTC by rpluem-vf

##### SUMMARY
Only error out if the gid exists with a different group name as
otherwise it will error out if the group with this gid already
exists, like on a rerun of the playbook. This fixes a regression
introduced by 4898b0a4a298448677c2aee2a03157ba5b662759.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
group

2019-07-30 11:50 UTC, rpluem-vf commented
ready_for_review

2019-07-30 11:53 UTC, rpluem-vf commented
bot_status

2019-07-31 13:01 UTC, mkrizek requested changes
This needs changelog, please see https://docs.ansible.com/ansible/latest/community/development_process.html#changelogs-how-to.

I'd also add a test, basically duplicate the one we already have to test idempotence.

2019-07-31 14:49 UTC, rpluem-vf commented
ready_for_review

2019-07-31 15:07 UTC, rpluem-vf commented
ready_for_review

2019-08-02 13:50 UTC, mkrizek approved these changes
:+1: Thanks!

2019-08-02 13:51 UTC, merged

2019-08-02 13:53 UTC, mkrizek commented
@rpluem-vf Would you be also interested in creating a backport PR to get this into the next `2.8` release? See https://docs.ansible.com/ansible/latest/community/development_process.html#backporting-merged-prs

If not, let me know and I'll do it. Thanks for the patch!

2019-08-02 18:41 UTC, rpluem-vf commented
> 
> 
> @rpluem-vf Would you be also interested in creating a backport PR to get this into the next `2.8` release? See https://docs.ansible.com/ansible/latest/community/development_process.html#backporting-merged-prs
> 
> If not, let me know and I'll do it. Thanks for the patch!

Just created [PR 60012](https://github.com/ansible/ansible/pull/60012)