Fortinet's new module for fortios_system_ha
ansible/ansible pull request #59790
Opened 2019-07-30 15:52 UTC by mamunozgonzalez

##### SUMMARY
 
Fortinet is adding Ansible support for FortiOS and FortiGate products. This module follows the same structure, guidelines and ideas given in previous approved module for a parallel feature of FortiGate (user device): https://github.com/ansible/ansible/pull/56447
In this case we are providing a different functionality: "Fortios System HA".
 
Please note that this will be part of other modules to come for FortiGate, including different functionalities: system, wireless-controller, firewall, webfilter, ips, web-proxy, wanopt, application, dlp spamfilter, log, vpn, certificate, user, dnsfilter, antivirus, report, waf, authentication, switch controller, endpoint-control and router. We plan to follow the same style, structure and usage as in the previous module in order to make it easier to comply with Ansible guidelines.
 
This PR has been updated according to suggestions and code reviews given in previous submissions of Fortinet modules.

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

fortios_system_ha

##### ANSIBLE VERSION

```
ansible 2.8.2
python version = 3.7.3 (default, Apr  3 2019, 05:39:12) [GCC 8.3.0]
```

2019-07-30 17:42 UTC, thomnico commented
shipit

2019-07-31 14:37 UTC, NilashishC requested changes
`state` key seems to be missing.

2019-07-31 14:38 UTC, NilashishC commented on lib/ansible/modules/network/fortios/fortios_system_ha.py
> +                    - Number of lost heartbeats to signal a failure (1 _ 60). Increase to reduce false positives.
probably?
```suggestion
                    - Number of lost heartbeats to signal a failure (1 - 60). Increase to reduce false positives.
```

2019-07-31 14:38 UTC, NilashishC commented on lib/ansible/modules/network/fortios/fortios_system_ha.py
> +                    - Time to wait before changing from hello to work state (5 _ 300 sec).
probably?
```suggestion
                    - Time to wait before changing from hello to work state (5 - 300 sec).
```

2019-07-31 14:38 UTC, NilashishC commented on lib/ansible/modules/network/fortios/fortios_system_ha.py
> +                    - Time between sending heartbeat packets (1 _ 20 (100*ms)). Increase to reduce false positives.
```suggestion
                    - Time between sending heartbeat packets (1 - 20 (100*ms)). Increase to reduce false positives.
```

2019-07-31 14:38 UTC, NilashishC commented on lib/ansible/modules/network/fortios/fortios_system_ha.py
> +                    - Cluster group ID  (0 _ 255). Must be the same for all members.
```suggestion
                    - Cluster group ID  (0 - 255). Must be the same for all members.
```

2019-07-31 14:39 UTC, NilashishC commented on lib/ansible/modules/network/fortios/fortios_system_ha.py
> +                    - Number of gratuitous ARPs (1 _ 60). Lower to reduce traffic. Higher to reduce failover time.
```suggestion
                    - Number of gratuitous ARPs (1 -60). Lower to reduce traffic. Higher to reduce failover time.
```

2019-07-31 14:39 UTC, NilashishC commented on lib/ansible/modules/network/fortios/fortios_system_ha.py
> +                    - Time between gratuitous ARPs  (1 _ 20 sec). Lower to reduce failover time. Higher to reduce traffic.
```suggestion
                    - Time between gratuitous ARPs  (1 - 20 sec). Lower to reduce failover time. Higher to reduce traffic.
```

2019-07-31 14:40 UTC, NilashishC reviewed
The ranges in the documentation seem to have `_` instead of `-`. Could you please have a look?

2019-08-16 14:39 UTC, closed without merging