add vfat to selinux special_context_filesystems
ansible/ansible pull request #59823
Opened 2019-07-30 21:31 UTC by jamescassell

##### SUMMARY

vfat is the format of the /boot/efi partition on UEFI hosts and does
not support SELinux labels

add an environment variable for this config option

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

file

##### ADDITIONAL INFORMATION

```paste below

```

2019-07-31 18:11 UTC, bcoca requested changes

2019-07-31 18:11 UTC, bcoca commented on lib/ansible/config/base.yml
> +  env: [{name: ANSIBLE_SPECIAL_CONTEXT_FILESYSTEMS}]
missing version_added, also i would add in description that vfat was added to defaults in 2.9

2019-08-01 15:27 UTC, bcoca approved these changes

2019-08-06 19:11 UTC, s-hertel commented
should it be added here too? https://github.com/ansible/ansible/blob/1d3f2c77642bcd4f0cef761bad7e30ebf9d33906/lib/ansible/module_utils/common/parameters.py#L31

2019-08-06 19:13 UTC, bcoca commented
not really needed, that is 'fallback in case passing args to module fails'

2019-08-06 19:39 UTC, samdoran commented
We discussed this during the IRC meeting today. Since this is a change to a default option, it is not eligible to be backported.

Also, it does need to be updated in the location @s-hertel indicated as well.

2019-08-10 15:42 UTC, jamescassell commented
> should it be added here too?
> 
> https://github.com/ansible/ansible/blob/1d3f2c77642bcd4f0cef761bad7e30ebf9d33906/lib/ansible/module_utils/common/parameters.py#L31

added.

2019-08-12 13:38 UTC, samdoran commented
Please create a changelog fragment. See [this fragment](https://github.com/ansible/ansible/blob/stable-2.7/changelogs/fragments/reboot-change-default-boot-command.yaml) as an example.

2019-08-12 13:47 UTC, jamescassell commented
> Please create a changelog fragment. See [this fragment](https://github.com/ansible/ansible/blob/stable-2.7/changelogs/fragments/reboot-change-default-boot-command.yaml) as an example.

Added.

2019-08-12 13:52 UTC, samdoran commented
rebuild_merge

2019-08-12 18:45 UTC, merged