New Module: Cloud Volume for azure NetApp Volume
ansible/ansible pull request #59943
Opened 2019-08-01 16:33 UTC by carchi8py

##### SUMMARY
Cloud Volume for azure NetApp Volume

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME
- azure_rm_netapp_volume.py 

##### ADDITIONAL INFORMATION

```paste below

```

2019-08-02 05:14 UTC, Fred-sun commented
@carchi8py Thank you for contributor this PR. Could you fix the CI fail, when you finished changed, I will push for review! Thanks a lot!

2019-08-05 16:13 UTC, carchi8py commented
@fred-sun the fix for this is in pr #59939, i'm talking with Matt and the Redhat team on how to handle the unit test. We might just drop them.

2019-08-27 10:01 UTC, Fred-sun commented
@carchi8py How about the PR going ahead? Any update? Thanks a lot!

2019-08-29 15:26 UTC, anshulbehl commented
@carchi8py This is still using get_client_from_cli_profile, Please make the changes in azure_rm_common.py and commit a new change.

2019-08-29 15:27 UTC, anshulbehl requested changes

2019-08-29 15:27 UTC, anshulbehl commented on lib/ansible/modules/cloud/azure/azure_rm_netapp_volume.py
> +    from azure.common.client_factory import get_client_from_cli_profile
Please change this like, https://github.com/ansible/ansible/pull/59939

2019-09-18 08:55 UTC, Fred-sun commented
kindly ping

2019-10-16 06:31 UTC, Fred-sun commented
@carchi8py Are you still there? Can you update PR according to comments? Thank you very much!

2019-10-16 06:40 UTC, Fred-sun commented
@carchi8py Another, you should add document for test_azure_rm_netapp_volume. Thank you very much!

2019-10-16 15:31 UTC, carchi8py commented
Hey @Fred-sun since we were told there would be no new modules accepted in ansible after 2.9 (and this missed that window) we made this in to a collection here. 

https://github.com/ansible/ansible_collections_netapp/tree/master/ansible_collections/netapp/azure

2019-10-17 02:16 UTC, Fred-sun commented
@carchi8py I see, Thanks for your info. If we are not adding to ansible 2.9, maybe we need to turn off this PR. Thank you very much!

2019-11-11 02:58 UTC, Fred-sun commented
@mybayern1974 If we can't add a new Module to Ansible after 2.9, what should we do with this kind of PRs? Please check! Thank you very much!

2020-01-08 03:12 UTC, Fred-sun commented on lib/ansible/modules/cloud/azure/azure_rm_netapp_volume.py
> +author: NetApp Ansible Team (@carchi8py) <ng-ansibleteam@netapp.com>
You should move the author to the end of the document and change the format as follows:
```suggestion
author:
    - NetApp Ansible Team (@carchi8py)
```

2020-01-08 03:12 UTC, Fred-sun commented on lib/ansible/modules/cloud/azure/azure_rm_netapp_volume.py
> +'''
Add the return value and example.

2020-02-10 07:29 UTC, Fred-sun commented
@carchi8py Would you please help fixes the CI fail when you're free？It will push for PR review and merge. Thank you very much!

2020-03-18 02:30 UTC, Fred-sun commented
@carchi8py Thank you for taking the time to contribute to this PR. We will transfer ansible 's azure module related Issue and PR to azure collection (https://github.com/ansible-collections/azure/pulls), can you transfer the Issue to azure collection repo?

2020-08-20 09:36 UTC, Akasurde commented
Hi @carchi8py, Thank you very much for your interest in Ansible. This plugin/module is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/azure<br><br>If you have further questions please stop by IRC or the mailing list:<br><br>* IRC: #ansible on irc.freenode.net<br>* mailing list: https://groups.google.com/forum/#!forum/ansible-project<br><br>needs_info<br>

2020-08-20 09:36 UTC, closed without merging