Resolve Issue
ansible/ansible pull request #60211
Opened 2019-08-07 14:20 UTC by gyorgypeter

Resolving #59970

##### SUMMARY
Now lists can be passed for source_received, source_transmitted and destination ports.
Fixing #59970

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
vmware_vspan_session

2019-08-26 19:33 UTC, goneri commented
Thanks @gyorgypeter for the bugfix PR, could you extend the integration test that you did (  test/integration/targets/vmware_vspan_session/tasks/main.yml ) to cover this use-case?

2020-01-19 18:48 UTC, gyorgypeter commented
@goneri Sorry for the late update, I modified the test cases as you requested, could you please merge the PR? Thanks in advance.

2020-01-29 15:42 UTC, goneri requested changes

2020-01-29 15:42 UTC, goneri commented on lib/ansible/modules/cloud/vmware/vmware_vspan_session.py
> +        type: list
correct me if I'm wrong, but if someone continue to pass a string (e.g: '13'), the module will cast the string to a list. And you will end-up with a list of character. So `['1', '3']` with my example. This is not what we want.

My conclusion is that this changeset will silently break the users playbooks.

2020-01-29 15:42 UTC, goneri commented on test/integration/targets/vmware_vspan_session/tasks/main.yml
> +        source_port_transmitted: [13, 11]
I would prefer you keep the existing tasks, and just extend the test playbook with the new use-case. This way we can be sure we don't introduce any regression.

2020-03-20 19:15 UTC, goneri commented
Hi!

Thank you for your PR. Since March 2, 2020, the Ansible team does not accept any new changes on the VMware modules on the core `ansible/ansible` repository.
The development continue but in the new VMware collection repository: https://github.com/ansible-collections/vmware
We have no way to properly migrate a Github issue  between the two projects. Could you please reopen the PR there? https://github.com/ansible-collections/vmware

Links:
- https://groups.google.com/forum/#!msg/ansible-devel/6UAfogEDtG8/wMTgxBGWCgAJ
- https://github.com/ansible-collections/overview/blob/master/README.rst

needs_info

2020-06-01 15:53 UTC, closed without merging