Add filters to os_router and os_subnet Fixes #37921 (#47220)
ansible/ansible pull request #60222
Opened 2019-08-07 16:42 UTC by GeorginaShippey

Would like this bugfix backported into 2.7

2019-08-07 19:59 UTC, abadger commented
Informational: backport of https://github.com/ansible/ansible/pull/47220  (which is already in 2.8.x as it was merged before stable-2.8 branched).

@GeorginaShippey  2.7.x is only open for critical bugfixes and security fixes.  At first glance, this doesn't look like that's the case here.  Is there something that makes it critical?  (Like it affects core code or is an issue that is affecting a ton of users?)  If it's not critical, we'd usually advise users to update to the newer version, 2.8.x in order to fix the problem.

2019-08-12 21:03 UTC, jrosser commented
@abadger I appreciate that 2.7.x is closed - however we are in a rather unfortunate position here because the patch has been backported to 2.6.x (and possibly earlier), exists in 2.8.x but was never merged to 2.7.x.

Life is never quite as simple as just updating to 2.8.x, some notably major ansible projects such as ceph-ansible and openstack-ansible pin their ansible version and own major release versions together and do not modify released stable branches to accommodate new ansible versions.

Whilst it may be arguable that this is neither a critical bugfix nor a security fix, it does not seem right to leave a regression in 2.7.x when earlier and later branches include the fix. My particular interest is that this bug affects users of the currently released Stein version of openstack-ansible who are pinned to ansible 2.7.x for the lifetime of that release.

2019-08-13 01:53 UTC, abadger commented
@GeorginaShippey or @jrosser Could you take this to one of the IRC meetings to ask if this should qualify as a critical bug (critical bugs trigger of enough importance that they trigger a new 2.7.x release)?  A regression within the 2.7.x line would be a good case.  A regression from 2.6.x is not as strong but sounds like it might be the best basis you have.  The counter argument to that is that 2.7.x has survived with this bug in place for ten months without a backport being mentioned so that depresses the chances that this would be considered a critical bug.  (As does the fact that this isn't a bug in the core engine).  At the meeting, the core team can take a vote on whether they'd like to consider this a critical bug to trigger a release.

Meetings are Tuesdays and Thursdays: https://github.com/ansible/community/tree/master/meetings#tuesdays

2019-08-23 18:18 UTC, cloudnull requested changes
couple of nits but otherwise looks good to me.

2019-08-23 18:18 UTC, cloudnull commented on lib/ansible/modules/cloud/openstack/os_router.py
> +                changed=_system_state_change(cloud, module, router, net, subnet_internal_ids, internal_portids, filters)
nit: I think this should be wrapped. 121 line length is longer than it should be. While Ansible has a lot of code which doesn't adhere to pep8 we should strive to be better, so lets try and keep the line length to 80 or 120.

2019-08-23 18:18 UTC, cloudnull commented on lib/ansible/modules/cloud/openstack/os_router.py
> +                if _needs_update(cloud, module, router, net, subnet_internal_ids, internal_portids, filters):
nit: I think this should be wrapped. 121 line length is longer than it should be. While Ansible has a lot of code which doesn't adhere to pep8 we should strive to be better, so lets try and keep the line length to 80 or 120.

2019-08-23 18:18 UTC, cloudnull commented on lib/ansible/modules/cloud/openstack/os_router.py
> +                        external_ids, subnet_internal_ids, internal_portids = _validate_subnets(module, cloud, filters)
nit: I think this should be wrapped. 121 line length is longer than it should be. While Ansible has a lot of code which doesn't adhere to pep8 we should strive to be better, so lets try and keep the line length to 80 or 120.

2019-08-30 17:11 UTC, closed without merging

2019-09-06 20:36 UTC, cloudnull commented
@abadger was this change meant to be closed?