fix: check_mode, add suboptions, return the facts
ansible/ansible pull request #60264
Opened 2019-08-08 09:18 UTC by chkp-orso

##### SUMMARY

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2019-08-08 10:40 UTC, ganeshrn commented on lib/ansible/modules/network/checkpoint/cp_network_facts.py
> +DOCUMENTATION = """
If the module is not returning `anisble_facts` it can be renamed to `_info`.
Refer: https://github.com/ansible/ansible/issues/54280

2019-08-20 09:57 UTC, justjais requested changes

2019-08-20 09:57 UTC, justjais commented on lib/ansible/modules/network/checkpoint/cp_network.py
>      description:
This is not properly aligned/indented, plz indent it wrt to `tags`

2019-08-20 12:05 UTC, justjais commented on test/units/modules/network/checkpoint/test_cp_network.py
> +                                                   'ip_address': '192.168.1.111'},
```suggestion
OBJECT = {'name': 'test_network', 'nat_settings': [{'auto_rule': True,
                                                   'hide_behind': 'ip-address',
                                                   'ip_address': '192.168.1.111'}],
```

2019-08-20 12:05 UTC, justjais commented on test/units/modules/network/checkpoint/test_cp_network.py
> +                                                   'ip_address': '192.168.1.111'},
change the dict to list of dict for both Create and Update option and it should pass then

2019-08-20 13:41 UTC, justjais requested changes

2019-08-20 13:41 UTC, justjais commented on lib/ansible/plugins/doc_fragments/checkpoint_facts.py
> +
plz include:
```suggestion
from __future__ import (absolute_import, division, print_function)
__metaclass__ = type
```

2019-08-21 06:53 UTC, justjais approved these changes

2019-08-21 06:53 UTC, merged