Solve issue 58592
ansible/ansible pull request #60406
Opened 2019-08-12 10:51 UTC by gen2kes

Added support to select disk_mode.

##### SUMMARY
Added ability to select disk_mode between ['persistent', 'independent_persistent', 'independent_nonpersistent']
Fixes issue #58592.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
vmware_guest_disk

##### ADDITIONAL INFORMATION

2019-08-13 05:11 UTC, Akasurde requested changes
Thanks for the contribution. Could you please add an integration test for this change ? Thanks.

2019-08-13 05:11 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_guest_disk.py
> +     - '     Default: C(thick) thick disk, no eagerzero.'
```suggestion

```

2019-08-14 08:37 UTC, gen2kes commented
Hi @Akasurde , 
I've uploaded the tests for the modified module vmware_guest_disk as requested. Please check it if you wish.
Regards

2019-08-26 17:24 UTC, goneri commented
Hi @gen2kes, The PR looks good to me, I'm ok to merge it when the CI issue get resolved, (do you need help with that?). And thanks for the functional test! :+1:

2019-08-27 13:59 UTC, goneri approved these changes

2019-09-04 17:47 UTC, jillr approved these changes
rebuild_merge

2019-09-05 15:52 UTC, merged