[WIP] Fix Gitlab module deprecation warning
ansible/ansible pull request #60425
Opened 2019-08-12 15:05 UTC by Lunik

##### SUMMARY

Fix and enchance deprecation warning for gitlab modules

Fixes #59976 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

gitlab_runner
gitlab_user
gitlab_project
gitlab_group
gitlab_hook
gitlab_deploy_key

##### ADDITIONAL INFORMATION

```paste below

```

2019-08-29 09:04 UTC, Lunik commented
shipit

2019-09-10 17:45 UTC, gundalow commented
So sounds like we need to merge and backport this (before 2.9.0 is released) then we can merge https://github.com/ansible/ansible/pull/61912 into devel (for release in 2.10)

I've triggered a rerun of CI. Could anyone please help review this GitLab PR, looks fairly straight forward, though review from someone that knows the area better would help. Thanks in advance.

2019-10-02 08:40 UTC, Shaps commented
Since this has taken longer than the 2.9 release, I'd rather start removing the parameters directly so we can get it done by the time 2.10 is released!

2019-10-08 11:05 UTC, Shaps requested changes
@Lunik Since we'll be printing 1 deprecation per alias, I think it makes more sense to change `Aliases` with `Alias`. Looks good otherwise

2019-10-08 11:05 UTC, Shaps commented on lib/ansible/modules/source_control/gitlab_deploy_key.py
> +            module.deprecate("Aliases \'{aliase}\' is deprecated".format(aliase=aliase), "2.10")
```suggestion
            module.deprecate("Alias \'{aliase}\' is deprecated".format(aliase=aliase), "2.10")
```

2019-10-08 11:05 UTC, Shaps commented on lib/ansible/modules/source_control/gitlab_group.py
> +            module.deprecate("Aliases \'{aliase}\' is deprecated".format(aliase=aliase), "2.10")
```suggestion
            module.deprecate("Alias \'{aliase}\' is deprecated".format(aliase=aliase), "2.10")
```

2019-10-08 11:05 UTC, Shaps commented on lib/ansible/modules/source_control/gitlab_hook.py
> +            module.deprecate("Aliases \'{aliase}\' is deprecated".format(aliase=aliase), "2.10")
```suggestion
            module.deprecate("Alias \'{aliase}\' is deprecated".format(aliase=aliase), "2.10")
```

2019-10-08 11:05 UTC, Shaps commented on lib/ansible/modules/source_control/gitlab_project.py
> +            module.deprecate("Aliases \'{aliase}\' is deprecated".format(aliase=aliase), "2.10")
```suggestion
            module.deprecate("Alias \'{aliase}\' is deprecated".format(aliase=aliase), "2.10")
```

2019-10-08 11:05 UTC, Shaps commented on lib/ansible/modules/source_control/gitlab_runner.py
> +            module.deprecate("Aliases \'{aliase}\' is deprecated".format(aliase=aliase), "2.10")
```suggestion
            module.deprecate("Alias \'{aliase}\' is deprecated".format(aliase=aliase), "2.10")
```

2019-10-08 11:05 UTC, Shaps commented on lib/ansible/modules/source_control/gitlab_user.py
> +            module.deprecate("Aliases \'{aliase}\' is deprecated".format(aliase=aliase), "2.10")
```suggestion
            module.deprecate("Alias \'{aliase}\' is deprecated".format(aliase=aliase), "2.10")
```

2019-10-08 11:31 UTC, Lunik commented
Thank's for the review @Shaps. It should be fine now

2019-10-14 12:47 UTC, Lunik commented
ready_for_review

2019-10-14 19:53 UTC, Shaps commented
shipit

2019-10-14 19:58 UTC, merged