New options to Interface
ansible/ansible pull request #60499
Opened 2019-08-13 16:12 UTC by carchi8py

##### SUMMARY
New Options for Interface 

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME
- na_ontap_interface.py 

##### ADDITIONAL INFORMATION

```paste below

```

2019-08-19 16:35 UTC, carchi8py commented
@thedoubl3j how do we force ansibot to return this?

2019-08-20 17:50 UTC, thedoubl3j reviewed
docs look clear, just need CI fixed.

2019-08-20 17:52 UTC, lonico commented on lib/ansible/modules/storage/netapp/na_ontap_interface.py
> +            options['listen-for-dns-query'] = str(parameters['listen_for_dns_query'])
Is it enough to use str, or do we need to convert to lowercase?

Look also at line 296.  Should we use teh same construct?

2019-08-20 17:54 UTC, lonico requested changes

2019-08-20 17:54 UTC, lonico commented on lib/ansible/modules/storage/netapp/na_ontap_interface.py
> +            if interface_attributes.get_child_by_name('dns-domain-name') is not 'none':
should be   != 'none'

is not None is correct.  is not 'none' is not correct.

2019-08-23 17:48 UTC, lonico commented on lib/ansible/modules/storage/netapp/na_ontap_interface.py
> +            options['listen-for-dns-query'] = str(parameters['listen_for_dns_query'])
I confirmed the ZAPI accepts both False and false, or True and true, so this is OK as is.

It's only when making comparisons with returned values (get), that we need to be case sensitive.

2019-08-26 13:56 UTC, thedoubl3j commented
@carchi8py @lonico still waiting on fixes for this one

2019-08-26 16:55 UTC, lonico approved these changes
shipit

2019-08-28 15:44 UTC, thedoubl3j approved these changes
lgtm, tests updated with new features. shipit

2019-08-28 15:45 UTC, merged