update ce_bgp to fix bugs
ansible/ansible pull request #60573
Opened 2019-08-14 13:41 UTC by yanzhangi

##### SUMMARY

Modify an error: When the vrf_name parameter is in the module and the configuration is repeatedly sent to the device, the module displays change = True

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

ansible/modules/network/cloudengine/ce_bgp.py
##### ADDITIONAL INFORMATION

```paste below

```

2019-08-14 15:21 UTC, yuandongx requested changes

2019-08-14 15:21 UTC, xuxiaowei0512 commented on lib/ansible/modules/network/cloudengine/ce_bgp.py
> +            if vrfName == "_public_":
vrfName ?

2019-09-18 01:36 UTC, hwDCN commented
LGMT

2019-09-18 01:40 UTC, hwDCN commented
+1

2019-09-18 01:45 UTC, yuandongx approved these changes
+1

2019-09-18 01:46 UTC, merged