Resource module for ios_lag_interfaces
ansible/ansible pull request #60672
Opened 2019-08-16 08:37 UTC by justjais

##### SUMMARY

Resource module for `ios_lag_interfaces`, with supported operations and respective integration tests.
(ref model: [ios_lag_interfaces](https://github.com/ansible-network/resource_module_models/pull/24/files) model)

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

ios_lag_interfaces
##### ADDITIONAL INFORMATION

```paste below

```

2019-08-16 13:58 UTC, justjais commented
recheck

2019-08-16 14:33 UTC, Qalthos requested changes

2019-08-16 14:33 UTC, Qalthos commented on lib/ansible/module_utils/network/ios/facts/lag_interfaces/lag_interfaces.py
> +        if connection:  # just for linting purposes, remove
You can remove this

2019-08-16 14:33 UTC, Qalthos commented on lib/ansible/modules/network/ios/ios_lag_interfaces.py
> +  sample: ['interface GigabitEthernet0/1', 'command 2', 'command 3']
Should probably replace `command 2` and `command 3` with something that the module might actually emit, too

2019-08-19 09:22 UTC, danielmellado requested changes
Hi, Sumit, some comments there.

2019-08-19 09:22 UTC, danielmellado commented on lib/ansible/modules/network/ios/ios_lag_interfaces.py
> +config:
This needs to be indented, otherwise validate-modules will thing that options is empty. Please change it so config is indented under options.

2019-08-19 09:22 UTC, danielmellado commented on lib/ansible/modules/network/ios/ios_lag_interfaces.py
> +      type: int
are you sure that this is an int?, this is defined as str on your argspec `'name': {'required': True, 'type': 'str'},`

2019-08-19 09:22 UTC, danielmellado commented on lib/ansible/modules/network/ios/ios_lag_interfaces.py
> +      - Interface options for the link aggregation group.
missing type

2019-08-19 09:22 UTC, danielmellado commented on lib/ansible/modules/network/ios/ios_lag_interfaces.py
> +          - auto
please surround all this with quotes as in 'auto', 'on', and so, otherwise validate-modules gets confused.

2019-08-19 10:22 UTC, ganeshrn commented on lib/ansible/module_utils/network/ios/config/lag_interfaces/lag_interfaces.py
> +        existing_interfaces_facts = self.get_interfaces_facts()
The name as per conventions can be `existing_lag_interfaces_facts` and `get_lag_interfaces_facts`

2019-08-19 10:22 UTC, ganeshrn commented on lib/ansible/module_utils/network/ios/config/lag_interfaces/lag_interfaces.py
> +        commands.extend(self.set_config(existing_interfaces_facts))
Same as above and applicable at other places as well

2019-08-19 11:21 UTC, ganeshrn commented on lib/ansible/module_utils/network/ios/config/lag_interfaces/lag_interfaces.py
> +        interfaces_facts = facts['ansible_network_resources'].get('lag_interfaces')
Name as per convention can be  `lag_itnerfaces_facts`

2019-08-19 11:21 UTC, ganeshrn commented on lib/ansible/module_utils/network/ios/config/lag_interfaces/lag_interfaces.py
> +        changed_interfaces_facts = self.get_lag_interfaces_facts()
same as above

2019-08-19 11:21 UTC, ganeshrn commented on lib/ansible/module_utils/network/ios/config/lag_interfaces/lag_interfaces.py
> +            result['after'] = changed_interfaces_facts
same as above

2019-08-19 11:21 UTC, ganeshrn approved these changes

2019-08-19 11:54 UTC, danielmellado approved these changes
LGTM, let's wait for Zuul and merge ;)

2019-08-19 12:57 UTC, justjais commented
recheck

2019-08-19 15:11 UTC, merged