Online: rename _facts -> _info
ansible/ansible pull request #61091
Opened 2019-08-22 05:36 UTC by felixfontein

##### SUMMARY
Fixes #60517.

##### ISSUE TYPE
- Bugfix Pull Request
- New Module Pull Request

##### COMPONENT NAME
online_server_facts
online_user_facts

2019-08-22 07:28 UTC, felixfontein commented
ready_for_review

2019-08-25 20:22 UTC, felixfontein commented
Rebased to resolve conflict in porting guide.

2019-08-26 15:53 UTC, felixfontein commented
CC @sieben (module author)

2019-08-27 17:47 UTC, s-hertel requested changes
A couple little things, but looks good besides that.

2019-08-27 17:47 UTC, s-hertel commented on lib/ansible/modules/cloud/online/online_server_info.py
> +  online_server_facts:
```suggestion
  online_server_info:
```

2019-08-27 17:47 UTC, s-hertel commented on test/legacy/roles/online_server_facts/tasks/main.yml
> -# ONLINE_TOKEN='XXX' ansible-playbook ./test/legacy/online.yml --tags test_online_server_facts
Also need to rename the directories test/legacy/roles/online_server_facts and test/legacy/roles/online_user_facts so the roles in test/legacy/online.yml work.

2019-08-27 18:46 UTC, felixfontein commented on test/legacy/roles/online_server_facts/tasks/main.yml
> -# ONLINE_TOKEN='XXX' ansible-playbook ./test/legacy/online.yml --tags test_online_server_facts
Looks like I didn't notice when editing the file... Should have also run `find | grep xxx` here... Thanks!

2019-08-27 18:46 UTC, felixfontein commented on lib/ansible/modules/cloud/online/online_server_info.py
> +  online_server_facts:
Thanks!

2019-08-27 20:33 UTC, s-hertel approved these changes

2019-08-27 20:36 UTC, merged

2019-08-27 20:50 UTC, felixfontein commented
@s-hertel thanks a lot for reviewing this one, too!