Add nxos_l2_interfaces resource module
ansible/ansible pull request #61120
Opened 2019-08-22 10:32 UTC by trishnaguha

Signed-off-by: Trishna Guha <trishnaguha17@gmail.com>

##### SUMMARY

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

modules/network/nxos/nxos_l2_interfaces.py

2019-08-22 11:38 UTC, danielmellado requested changes
Some minor typos there, thanks Trishna!

2019-08-22 11:38 UTC, danielmellado commented on lib/ansible/modules/network/nxos/nxos_l2_interfaces.py
> +	  allowed_vlans: 2,4,15
There's some mixed spaces and tabs here, please remove the tabs and use spaces only.

2019-08-22 11:38 UTC, danielmellado commented on lib/ansible/modules/network/nxos/nxos_l2_interfaces.py
> +	  vlan: 30
same here

2019-08-22 11:38 UTC, danielmellado commented on lib/ansible/modules/network/nxos/nxos_l2_interfaces.py
> +	  native_vlan: 20
ditto

2019-08-22 11:38 UTC, danielmellado commented on lib/ansible/modules/network/nxos/nxos_l2_interfaces.py
> +	  trunk_vlans: 5-10, 15
ditto

2019-08-22 11:38 UTC, danielmellado commented on lib/ansible/modules/network/nxos/nxos_l2_interfaces.py
> +	  vlan: 30
ditto

2019-08-22 18:48 UTC, samccann reviewed
no other docs comments other than the spacing comments from the other reviewer

2019-08-23 09:35 UTC, trishnaguha commented
@danielmellado fixed the spacing.

2019-08-26 11:15 UTC, danielmellado approved these changes
LGTM now, thanks trishna!

2019-08-26 11:16 UTC, merged