azure: fixed conflict caused by outdated azure-cli-core
ansible/ansible pull request #61238
Opened 2019-08-23 16:59 UTC by ssbarnea

##### SUMMARY
The pinned version of azure-cli-core caused installation conflicts due
to requesting wrong versions of tabulate, creating conflicts with
ansible molecule.

The newer version of azure-cli-core fixed this issue.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
azure

##### ADDITIONAL INFORMATION

```paste below
Collecting tabulate<=0.8.2,>=0.7.7 (from azure-cli-core==2.0.35->ansible[azure])
...
ERROR: molecule 2.23.dev8+gabf4956c has requirement tabulate>=0.8.3, but you'll have tabulate 0.8.2 which is incompatible.
```

2019-09-03 15:27 UTC, gundalow commented
@haroldwongms @nitzmahone @yuwzho @yungezz @zikalino would welcome your thoughts on this, thanks in advance.

2019-09-04 05:35 UTC, Fred-sun commented
review_need

2019-09-04 17:17 UTC, nitzmahone commented
This will never be fixed permanently- Azure CLI and random users of the Azure SDK (eg Ansible) need to be in separate venvs (which is why all OS packaged versions of Azure CLI install to a dedicated venv). The Azure CLI requirements change almost daily, so trying to keep these in sync will be an endless game of whack-a-mole (ask the Tower team, they tried for over a year and finally gave up in disgust). Strongly recommend this PR be closed and that `az` be used from a dedicated venv one way or another.

2019-09-04 17:19 UTC, nitzmahone requested changes
Recommend close; only update the requirements file when the code actually needs it, or it'll be updated daily...

2019-09-18 08:36 UTC, Fred-sun commented
ping to closed

2019-09-18 09:01 UTC, yungezz commented
close_it

2019-09-18 09:13 UTC, closed without merging