Add support for reset_connection in persistent connection
ansible/ansible pull request #61317
Opened 2019-08-26 13:21 UTC by ganeshrn

##### SUMMARY

*  Implement `reset()` method for persistent connections
   (network_cli/netconf/httpapi) to support
   meta: reset_connection

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

ansible/plugins/connection/__init__.py
ansible/plugins/connection/httpapi.py
ansible/plugins/connection/netconf.py
ansible/plugins/connection/network_cli.py

##### ADDITIONAL INFORMATION

```paste below

```

2019-08-27 03:09 UTC, ganeshrn commented
recheck

2019-08-29 13:35 UTC, Qalthos requested changes

2019-08-29 13:35 UTC, Qalthos commented on lib/ansible/plugins/connection/network_cli.py
> +    def reset(self):
This method is already in `NetworkConnectionBase`, why are we adding it to the subclasses too?
And why does this implementation differ from the others?

2019-08-29 13:35 UTC, Qalthos commented on lib/ansible/plugins/connection/__init__.py
> +                        setattr(self.connection, '_socket_path', None)
Am I missing something? What is `self.connection` in this context?

2019-08-29 14:49 UTC, ganeshrn commented on lib/ansible/plugins/connection/network_cli.py
> +    def reset(self):
`reset` needs to be implemented in the individual connection class as invloking `close()` in the parent class will call `close` method defined either in the same class or it's parent and  not that of the child class (eg: the one defined in `network_cli`)

2019-08-29 14:50 UTC, ganeshrn commented on lib/ansible/plugins/connection/__init__.py
> +                        setattr(self.connection, '_socket_path', None)
copy/paste error. Fixed now

2019-08-29 15:11 UTC, Qalthos commented on lib/ansible/plugins/connection/network_cli.py
> +    def reset(self):
> invloking close() in the parent class will call close method defined either in the same class or it's parent and not that of the child class

That is not true. If it were, none of this would work. We rely on the fact that overridden methods get called properly despite being called in parent classes all the time.

As it is implemented presently, `reset_connection` works fine for the _transport_ connection, it just doesn't do anything about the persistent connection socket. And... I'm really not sure it should? At least, I'm open to being convinced that the persistent connection process is worth being able to be reset like this, but I'm not sure what the need is.

2019-08-29 15:20 UTC, Qalthos commented on lib/ansible/plugins/connection/__init__.py
> +                        self._connected = False
This line is executed in `NetworkConnectionBase.close()` (and, is in fact the _only_ thing that method does) which is universally called immediately after shutdown.

I don't think it belongs in a `finally` block
(I don't think a `finally` block even makes sense after a no-op Pokemon exception)
I also don't think it belongs inside the conditional

You now call `shutdown` in every implementing plugin's `close` method, so why not move this code into `NetworkConnectionBase.close` (or at least call `shutdown` in `NetworkConnectionBase.close`) Is there some reason to keep the two separate?

2019-08-30 15:53 UTC, ganeshrn commented
Closing this PR as it will be fixed by https://github.com/ansible/ansible/pull/61591

2019-08-30 15:54 UTC, closed without merging