new module netapp csv pools for aws
ansible/ansible pull request #61340
Opened 2019-08-26 20:19 UTC by carchi8py

##### SUMMARY
New Module: netapp CSV pools for aws

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME
- aws_netapp_cvs_pool.py 

##### ADDITIONAL INFORMATION

```paste below

```

2019-08-27 21:02 UTC, lonico commented on test/units/modules/cloud/amazon/test_aws_netapp_cvs_pool.py
> +    @patch('ansible.module_utils.netapp.AwsCvsRestAPI.post')
post needs to be changed to delete here.

2019-08-27 22:16 UTC, lonico requested changes

2019-08-27 22:16 UTC, lonico commented on lib/ansible/modules/cloud/amazon/aws_netapp_cvs_pool.py
> +            new_name=dict(required=False, type='str'),
don't use new_name.   It should be from_name to maintain idempotency

2019-08-28 15:52 UTC, lonico approved these changes
shipit

2019-08-28 20:24 UTC, lonico approved these changes
shipit

2019-08-29 00:32 UTC, anshulbehl commented
All looks good, shipit

2019-08-29 03:16 UTC, thedoubl3j approved these changes
everything looks good, docs fragment in plac and tests added. shipit.

2019-08-29 03:30 UTC, merged