new module: Cloud Volume for AWS FileSystems
ansible/ansible pull request #61343
Opened 2019-08-26 20:41 UTC by carchi8py

##### SUMMARY
new module: Cloud Volume for AWS FileSystems

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME
- aws_netapp_cvs_FileSystems.py

##### ADDITIONAL INFORMATION

```paste below

```

2019-08-27 14:30 UTC, thedoubl3j commented
bot_status

2019-08-28 12:36 UTC, thedoubl3j commented
@carchi8py CI still failing

2019-08-28 16:21 UTC, lonico requested changes
The logic around cd_action needs to be revisited.

2019-08-28 16:21 UTC, lonico commented on lib/ansible/modules/cloud/amazon/aws_netapp_cvs_FileSystems.py
> +        list_filesystem, error = self.restApi.get('FileSystems')
since we are only interested in the creationToken field, is it possible to scope the query to only return this field?

I'm concerned this can generate a lot of traffic if all attributes are returned.

Can be delayed.

2019-08-28 16:21 UTC, lonico commented on lib/ansible/modules/cloud/amazon/aws_netapp_cvs_FileSystems.py
> +                    return response
not used by the caller.

The error processing is weak.  What if we are getting something different than done?  

We'll to validate how much is reported in 'error', and whether we need to support async and sync operations.

(I confirmed there are sync operations, we are waiting for the command to complete)

2019-08-28 16:21 UTC, lonico commented on lib/ansible/modules/cloud/amazon/aws_netapp_cvs_FileSystems.py
> +        cd_action = self.na_helper.get_cd_action(fileSystem, self.parameters)
fileSystem is not set yet, so cd_action always believes the fileSystem does not exist.

I confirmed this prevents 'delete' to work correctly.

2019-08-28 20:26 UTC, lonico approved these changes
shipit

2019-08-28 23:35 UTC, thedoubl3j approved these changes
CI is green, docs look good and tests included. lgtm. shipit.

2019-08-29 03:02 UTC, merged