Removing jmighion as maintainer of aruba and aireos modules.
ansible/ansible pull request #61469
Opened 2019-08-28 16:20 UTC by jmighion

##### SUMMARY

I no longer have access to those network devices and don't really have enough time to be a good maintainer.

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2019-08-28 16:25 UTC, jmighion commented
Not sure if I did that correctly. The docs say to put "ansible" when removing a maintainer, but the file appeared to use `$team_ansible` which was an empty array. Might need a doc change to https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/community/maintainers.rst#adding-and-removing-maintainers.

2019-08-29 11:30 UTC, gundalow requested changes
@jmighion Thank you for everything you've done so far.

If you wrote any of the modules you need to add `ignore: jmighion`

I've assigned this to myself and will review the docs (most likely after Fest)

So let's leave this PR open (and assigned to me) and I'll tidy it up

2019-08-29 14:59 UTC, jmighion commented
Thanks @gundalow !

2019-11-05 16:20 UTC, merged

2019-11-06 04:44 UTC, Akasurde commented
@jmighion Thanks for the contribution. It is sad to see you go as a maintainer, hope to see you again. Thanks.