Adding support for --group to inventory tool
ansible/ansible pull request #61487
Opened 2019-08-28 20:04 UTC by Daemoen

##### SUMMARY
By default, we have no way of doing an inventory usable format for listing group data.  We can use 'host', but that is limited to a *single* host literal.  This way we can now include groups.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
ansible-inventory

2019-08-28 21:46 UTC, sivel commented on lib/ansible/cli/inventory.py
> +            top = self._get_group(context.CLIARGS['group'])
This breaks `--list`, as you inserted a new `elif` before code that ran in `--list`.  I'm not convinced that `--group` is needed.  We could make `--limit` work, and use it in place of `all` in the above `_get_group` call.

At minimum, if we accepted `--group`, it should have a default of `'all'`, and that should be used in the existing `self._get_group` call instead of adding another branch.

2019-08-28 22:39 UTC, Daemoen commented
I definitely agree that having --limit would be a good thing, but its still only a start for the reason illustrated below --

ansible -i ec2_dynamic.yml 'some_group_with_hosts' -- limit 'other_group'  allows you to do an intersection where the hosts you are working on must be in both groups.

You can do this with both ansible -i and ansible-playbook -i. --  there is no way of doing this currently with ansible-inventory.  --group would at least allow for part of this, though ultimately it might be better, as you said, to modify the list so that it supports default 'all' and also allows group support, and combine that with --limit, which would make the behavior similar to ansible/-playbook

2019-08-30 14:34 UTC, bcoca commented
this used to work for --graph, you could pass a group name:

```
#>ansible-inventory -i ~/work/inventories/test.ini --graph testing
@testing:
  |--mailer1
  |--oi_test
```
but now this fails in 2.9 (it works up to 2.8)

2019-08-30 17:13 UTC, Daemoen commented
@bcoca Right, but there is a distinct difference between graph and list -- One is usable as an actual inventory source, the  other is not, which is why its a bit of a bummer, since it makes  it difficult to 'play at' inventory testing.

2019-08-30 19:58 UTC, bcoca commented
`--limit` should be the way to do this

2021-04-01 18:48 UTC, bcoca requested changes
as in comment above, we don't need new option, just implementing limit

2022-02-11 07:50 UTC, closed without merging