Nagios module: minor change, added "start" parameter
ansible/ansible pull request #61562
Opened 2019-08-29 16:03 UTC by dramaley

##### SUMMARY
Add a "start" parameter to the nagios module, allowing the user to specify when a scheduled outage in Nagios begins.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
nagios.py

##### ADDITIONAL INFORMATION
This PR finishes the "start" parameter of the nagios module, allowing the user to set when a Nagios downtime should begin. The backend functions within the module already supported a start parameter; this change just exposes that. If the new parameter is not provided, it defaults to the current time. This preserves compability with existing playbooks.

2019-08-29 16:32 UTC, dramaley commented
Closing and reopening to force CI, per the notes on the "needs_ci" and "stale_ci" labels.

2019-08-29 16:47 UTC, dramaley commented
bot_status

2019-09-10 15:02 UTC, goneri commented
I'm not sure what happened with the CI here, it seems to be running this time.

2019-10-18 14:34 UTC, dramaley commented
Hello. This has been sitting here awhile. Is there any way to get a pull request looked at and accepted? Thank you!

2019-10-24 16:12 UTC, dramaley commented
Closing and reopening to force CI, per the notes on the "stale_ci" label.

2019-11-22 21:08 UTC, dramaley commented
Closing and reopening to force CI.

2019-12-05 16:58 UTC, goneri requested changes
A little comment, otherwise the code looks good.

2019-12-05 16:58 UTC, goneri commented on lib/ansible/modules/monitoring/nagios.py
> +            start=dict(default=int(time.time())),
I think it's better to set `start` to `None` by default. In this case `_fmt_dt_str()` with initialize it to `now()` anyway. And this avoid the case where the same variable can be initialized at two different locations in the code.

2019-12-06 17:23 UTC, merged

2019-12-06 17:23 UTC, goneri commented
Thanks for the contribution @dramaley :-)

2019-12-06 17:24 UTC, dramaley commented
Thank you for much @goneri for committing this!