Fixes IOS L3 intermittent zuul failure
ansible/ansible pull request #61682
Opened 2019-09-02 11:30 UTC by justjais

##### SUMMARY

Fixes IOS L3 intermittent zuul failure raised in bug #61305. Also, updated the tests IP to use documentation IPs instead of random.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

ios_l3_interfaces

##### ADDITIONAL INFORMATION

```paste below

```

2019-09-02 13:11 UTC, justjais commented
recheck

2019-09-02 13:26 UTC, danielmellado approved these changes
Besides a minor comment on a test, it LGTM!

2019-09-02 13:26 UTC, danielmellado commented on lib/ansible/module_utils/network/ios/config/l3_interfaces/l3_interfaces.py
> +        Check the IPV4 difference again when secondary IP is configured,
Could we rephrase this? I think it's a little bit confusing. IIUC when there's a difference in order there'd be a mismatch on the set? Too much difference on the comment ;)

2019-09-02 18:03 UTC, pabelanger commented
recheck

2019-09-02 19:32 UTC, pabelanger commented
recheck

2019-09-02 19:37 UTC, pabelanger commented
@justjais I've created an issue for the ios_file failure, so we can work on a fix:

https://github.com/ansible/ansible/issues/61694

2019-09-02 21:20 UTC, pabelanger requested changes
It looks like we still have an intermittent issue, you can see the last test failing:

  https://object-storage-ca-ymq-1.vexxhost.net/v1/a0b4156a37f9453eb4ec7db5422272df/ansible_82/61682/0b0550fc96f7fe814d6d39328993a79aa1cab1b0/third-party-check/ansible-test-network-integration-ios-python35/62fb746/controller/ara-report/

That happened because of:

  ios_l3_interfaces : Merge provided configuration with device configuration (IDEMPOTENT)

changing.

2019-09-03 08:24 UTC, justjais commented
recheck

2019-09-03 08:49 UTC, danielmellado approved these changes
Looks like latest change got rid of the intermittent issue

2019-09-03 22:22 UTC, pabelanger commented
recheck

2019-09-03 23:28 UTC, pabelanger commented
recheck

2019-09-04 01:35 UTC, pabelanger commented
recheck

2019-09-04 03:17 UTC, pabelanger commented
recheck

2019-09-04 04:54 UTC, justjais commented
recheck

2019-09-04 06:05 UTC, justjais commented
recheck

2019-09-04 07:24 UTC, justjais commented
recheck

2019-09-04 10:19 UTC, danielmellado approved these changes
Zuul seems happy after serveral rechecks, let's get this in!

2019-09-04 10:21 UTC, merged