Added Exos vlan resource module
ansible/ansible pull request #61865
Opened 2019-09-05 15:30 UTC by JayalakshmiV

##### SUMMARY

Resource module for exos_vlan, with supported operations and integration tests.

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

exos_vlan

##### ADDITIONAL INFORMATION

```paste below

```

2019-09-05 18:52 UTC, ujwalkomarla commented on lib/ansible/modules/network/exos/exos_vlans.py
> +version_added: 2.9
2.10

2019-09-05 19:05 UTC, ujwalkomarla commented on lib/ansible/modules/network/exos/exos_vlans.py
> +commands:
Please replace `commands` section with this:
```
requests:
  description: The set of requests pushed to the remote device.
  returned: always
  type: list
  sample: [{"data": "...", "method": "...", "path": "..."}, {"data": "...", "method": "...", "path": "..."}, {"data": "...", "method": "...", "path": "..."}]
```

2019-09-05 19:07 UTC, ujwalkomarla commented on test/integration/targets/exos_vlan/defaults/main.yaml
> +---
Please move the 'exos_vlan' target folder to 'exos_vlans' folder.

2019-09-06 05:53 UTC, ujwalkomarla requested changes

2019-09-06 05:53 UTC, ujwalkomarla commented on test/integration/targets/exos_vlans/tests/httpapi/merged.yaml
> +        - name: vlan_30
Add some vlans whose state will be suspended in the merged, overridden, replaced tests.

2019-09-06 05:53 UTC, ujwalkomarla commented on lib/ansible/module_utils/network/exos/facts/vlans/vlans.py
> +                "path": "/rest/restconf/data/openconfig-vlan:vlans/",
Limit the restconf GET by specifying the depth parameter with value 5 : `/rest/restconf/data/openconfig-vlan:vlans?depth=5`

2019-09-06 05:53 UTC, ujwalkomarla commented on lib/ansible/module_utils/network/exos/config/vlans/vlans.py
> +                request_delete = deepcopy(self.VLAN_DELETE)
Move this line after 250.
You won't need to deepcopy unless you are actually creating a request.

2019-09-06 05:53 UTC, ujwalkomarla commented on lib/ansible/module_utils/network/exos/config/vlans/vlans.py
> +                request_delete = deepcopy(self.VLAN_DELETE)
Move this line after 261.
You won't need to deepcopy unless you are actually creating a request.

2019-09-06 05:53 UTC, ujwalkomarla commented on lib/ansible/module_utils/network/exos/argspec/vlans/vlans.py
> +                    'choices': ['active', 'suspended'],
Choices are 'active' and 'suspend'.

2019-09-06 05:53 UTC, ujwalkomarla commented on lib/ansible/module_utils/network/exos/config/vlans/vlans.py
> +                    continue
If the VLAN exists, you should check the name and state to make sure they are same as requested.

2019-09-06 05:53 UTC, ujwalkomarla commented on lib/ansible/module_utils/network/exos/config/vlans/vlans.py
> +            request_delete = deepcopy(self.VLAN_DELETE)
deepcopy only if required, move it inside the conditional.

2019-09-06 05:53 UTC, ujwalkomarla commented on lib/ansible/module_utils/network/exos/config/vlans/vlans.py
> +                    request_post = deepcopy(self.VLAN_POST)
You have identical code on lines 159-163, 193-197, 228-232... Move it into a function.

2019-09-07 00:01 UTC, ujwalkomarla reviewed
Otherwise LGTM

2019-09-07 00:01 UTC, ujwalkomarla commented on lib/ansible/module_utils/network/exos/facts/vlans/vlans.py
> +        else:
You can simplify with 
`config["state"] = "suspend" if conf["status"] == "SUSPENDED" else conf["status"].lower()

2019-09-07 00:01 UTC, ujwalkomarla commented on lib/ansible/module_utils/network/exos/config/vlans/vlans.py
> +        :returns: the commands necessary to migrate the current configuration
If you could replace 'commands' with 'requests' in the comments that would be good.

2019-09-07 23:26 UTC, ujwalkomarla commented
shipit

2019-09-07 23:27 UTC, ujwalkomarla commented on lib/ansible/module_utils/network/exos/config/vlans/vlans.py
> +        :returns: the commands necessary to migrate the current configuration
Thanks for the changes!
Looks good.

2019-09-07 23:28 UTC, ujwalkomarla approved these changes
shipit

2019-10-09 14:27 UTC, ganeshrn approved these changes
Thank you!

2019-10-09 14:27 UTC, ganeshrn commented
rebuild_merge

2019-10-10 10:50 UTC, merged