test_cp_mgmt_network_facts module
ansible/ansible pull request #61880
Opened 2019-09-05 18:21 UTC by chkp-amiads

##### SUMMARY

Checkpoint test_cp_mgmt_network_facts module

##### ISSUE TYPE

- New Test Module Pull Request

##### COMPONENT NAME

checkpoint
##### ADDITIONAL INFORMATION

```paste below

```

2019-09-11 09:32 UTC, danielmellado requested changes

2019-09-11 09:32 UTC, danielmellado commented on test/units/modules/network/check_point/test_cp_mgmt_network_facts.py
> +from units.modules.utils import set_module_args, exit_json, fail_json, AnsibleFailJson, AnsibleExitJson
AnsibleFailJson is not used and shouldn't be imported

2019-09-11 09:32 UTC, danielmellado commented on test/units/modules/network/check_point/test_cp_mgmt_network_facts.py
> +from ansible.module_utils.network.checkpoint.checkpoint import api_call_facts
This is not used and shouldn't be imported

2019-09-11 09:32 UTC, danielmellado commented on test/units/modules/network/check_point/test_cp_mgmt_network_facts.py
> +        result = self._run_module(SHOW_SINGLE_PAYLOAD)
I'd be expecting some assertion here, like in the follow-up test, otherwise you're just assigning result but never using it.

2020-06-29 12:25 UTC, Akasurde commented
Hi @chkp-amiads, Thank you very much for your interest in Ansible. This plugin/module is no longer maintained in this repository and has been migrated to https://github.com/CheckPointSW/CheckPointAnsibleMgmtCollection<br><br>If you have further questions please stop by IRC or the mailing list:<br><br>* IRC: #ansible on irc.freenode.net<br>* mailing list: https://groups.google.com/forum/#!forum/ansible-project<br>

2020-06-29 12:25 UTC, closed without merging