Fix #60119
ansible/ansible pull request #62060
Opened 2019-09-10 12:34 UTC by cjbrowne

##### SUMMARY
Fixes #60119 by adding a `persist` flag (False by default) and using it to choose between GLOBAL or PERSIST keywords in the MySQL query.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
mysql_variables

##### ADDITIONAL INFORMATION

2019-09-10 12:59 UTC, cjbrowne commented
I'll come back to this.  It only works in MySQL >= version 8.0 so needs a fact check and a fallback mechanism for adding persistent variables in MySQL <= 5.7.

2019-09-11 01:47 UTC, Akasurde commented
cc @Andersson007 @pratikgadiya12 Could you please review this ? Thanks.

2019-09-11 06:47 UTC, Andersson007 commented
@cjbrowne thank you for adding this option @Akasurde i'll try to take a look till the end of this week, thank you for mentioning!

2019-09-12 18:42 UTC, Andersson007 commented
@cjbrowne  hey, could you please add ci tests for this case, it should cover at least 2 points:
1.  you could set a variable, then restart mysql server and check that the variable became wrong
2. then you could set the variable with the suggested flag, after that, respectively, restart the server again and check that the variable has the right value
3. maybe anything else

The existent tests are there test/integration/targets/mysql_variables/ , you could add yours to them.
If you have any questions about integration tests, feel free to ask us any time here or directly by aaklychkov at mail dot ru.
Thank you for fixing this! waiting for your feedback.

p.s. unfortunately i will not look at the code at least before next week but the integration tests would be a good starting point (IMO they are necessary for all prs except simple cases like fixing typos, etc.)

2019-09-12 18:56 UTC, Andersson007 requested changes
https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_documenting.html#documentation-block see the "Linking within module documentation" section

2019-09-12 18:56 UTC, Andersson007 commented on lib/ansible/modules/database/mysql/mysql_variables.py
> +            - If true, sets variable persistently (will survive mysql restarts)
```suggestion
            - If C(true), sets variable persistently (will survive mysql restarts). Supported from MySQL 8.0.
```
about version, needs to be checked

2019-09-12 19:03 UTC, Andersson007 requested changes

2019-09-12 19:03 UTC, Andersson007 commented on lib/ansible/modules/database/mysql/mysql_variables.py
> +    persist: yes
```suggestion
    mode: persist
```
regarding the [documentation](https://dev.mysql.com/doc/refman/8.0/en/set-variable.html) maybe we could change ```persist``` option to something like:
```
mode:
  description: ...
  type: str
  choices: ['global', 'persist', 'persist_only']
  default: 'global'
```
(i guess 'session' support does not make sense)

2019-09-12 19:08 UTC, Andersson007 requested changes

2019-09-12 19:08 UTC, Andersson007 commented on lib/ansible/modules/database/mysql/mysql_variables.py
> +    persist_keyword = "PERSIST" if persist else "GLOBAL"
```
    persist_keyword = "PERSIST" if persist else "GLOBAL"
```
also persist_only support regarding that i suggested above

2019-09-12 19:12 UTC, Andersson007 commented
The idea looks good to me in general.
@bmalynovytch what do you think about this?

2019-09-12 19:14 UTC, highwaycoder commented on lib/ansible/modules/database/mysql/mysql_variables.py
> +    persist: yes
because of how it all works, session support doesn't currently make sense, but would in theory be cool if you could somehow re-use the same mysql session for a later task, so you could set session variables for an ansible play this way

2019-09-12 19:15 UTC, highwaycoder commented
Not sure when I'll get around to writing the CI tests but it's on my to-do list now, will try to get to it ASAP :)

2019-09-12 19:25 UTC, Andersson007 commented
@cjbrowne In general ci tests are just common playbooks. See the directory's content test/integration/targets/mysql_variables/

About this particular case:
i guess the current ci tests are based on the version that's lower than 8.0, so it is impossible to make them right now without MySQL 8.0 installation during the tests.

if we look at test/integration/targets/setup_mysql_db/tasks/main.yml, it installs the latest version from repos (it can be not 8.0), we need to have 8.0. Please, check

Ok, that's it for today, see you next week!

2019-10-11 11:17 UTC, Andersson007 commented
@cjbrowne how are you? :)

2019-10-16 08:13 UTC, Andersson007 commented
because there is no feedback it could be closed via https://github.com/ansible/ansible/pull/63547

2019-10-16 09:04 UTC, closed without merging

2019-11-06 10:41 UTC, cjbrowne commented
Ah! Sorry, this slipped off my radar briefly, it looks like it has been added now anyway so that's great.  :+1:

2019-11-06 11:07 UTC, Andersson007 commented
@cjbrowne , thanks for pointing this out and implementing the initial solution!