allow groups, append with local user
ansible/ansible pull request #62134
Opened 2019-09-11 12:56 UTC by utoddl

##### SUMMARY
This change to the user module handles groups for local users.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
user module

##### ADDITIONAL INFORMATION
The "append" and "groups" parameters were recently made mutually exclusive with the "local" parameter because lusermod and luseradd can't achieve the desired state. However, with the additional use of lgroupmod, the desired state is quite easily reached when "local" is true.

This change adds lgroupmod to the mix when local is true, and removes the now-unnecessary incompatibility with the append and groups parameters.

2020-02-05 17:49 UTC, samdoran requested changes
Change looks good. Please create a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment). See [this fragment](https://github.com/ansible/ansible/blob/c2f528b7686c9573aa8493357219e0bbe4416dd3/changelogs/fragments/reboot-change-default-boot-command.yaml) as an example.

2020-02-05 17:49 UTC, samdoran commented
You'll also need to rebase to fix the merge conflict in the test file. Hopefully that won't be too much of a pain.

2020-02-06 15:43 UTC, utoddl commented
@samdoran Requested changes and rebase are done, checks passed.

2020-02-06 17:32 UTC, samdoran approved these changes

2020-02-06 17:32 UTC, merged