[WIP] Raw Device Mapping
ansible/ansible pull request #62394
Opened 2019-09-17 07:19 UTC by sandrich

##### SUMMARY
This is work in progress for raw device mapping which should tackle #24837

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
vmware_guest_disk

##### ADDITIONAL INFORMATION
The enhancement allows to map raw devices into the VM. The current implementation is working but is missing some tests and code cleanup. Also currently only physicalMode compatibility mode is supported.

Also thanks to @radudd for his contributions

```paste below

```

2019-09-17 14:09 UTC, sandrich commented
I was wondering how to write tests for raw device mapping. The test esx environment would require some additional disks I could use. Any help would be appreciated.

2019-11-10 13:42 UTC, sandrich commented
ready_for_review

2020-01-21 04:36 UTC, Akasurde requested changes
Could you please rebase this PR? Thanks for the contribution.

2020-01-21 04:36 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_guest_disk.py
>                                            " 'disk_type' value from ['thin', 'thick', 'eagerzeroedthick']." % disk_index)
```suggestion
                                          " 'disk_type' value from ['thin', 'thick', 'eagerzeroedthick', 'raw']." % disk_index)
```

2020-01-21 07:59 UTC, sandrich commented
Screwed this one up. Will recreate

2020-01-21 07:59 UTC, closed without merging