ovirt_host update force doc
ansible/ansible pull request #62491
Opened 2019-09-18 10:27 UTC by mnecas

##### SUMMARY

ovirt_host update force doc

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1719271
##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

ovirt
##### ADDITIONAL INFORMATION

```paste below

```

2019-09-18 11:27 UTC, mwperina requested changes

2019-09-18 11:27 UTC, mwperina commented on lib/ansible/modules/cloud/ovirt/ovirt_host.py
> +            - "It don't forcibly remove host if it's being removed already."
I'd rephrase:
 "WARNING: It doesn't forcibly remove the host if another host related operation is being executed on the host at the same time."

2019-09-24 14:54 UTC, machacekondra commented
shipit

2019-09-24 15:05 UTC, mwperina approved these changes
shipit

2019-09-24 15:06 UTC, merged