new module: lbu
ansible/ansible pull request #62584
Opened 2019-09-19 11:05 UTC by kunkku

Alpine Linux Local Backup Utility

##### SUMMARY
Module for Alpine Linux Local Backup Utility

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
lbu

2019-09-20 06:29 UTC, Akasurde requested changes
Thanks for the contribution.

2019-09-20 06:29 UTC, Akasurde commented on lib/ansible/modules/system/lbu.py
> +short_description: Local Backup Utility
```suggestion
short_description: Local Backup Utility for Alpine Linux
```

2019-09-20 06:29 UTC, Akasurde commented on lib/ansible/modules/system/lbu.py
> +- Alpine Linux Local Backup Utility
```suggestion
- Manage Alpine Linux Local Backup Utility while Alpine Linux is in a run-from-RAM configuration mode.
```

2019-09-20 06:29 UTC, Akasurde commented on lib/ansible/modules/system/lbu.py
> +    - Control whether to commit changed files
```suggestion
    - Control whether to commit changed files.
```

2019-09-20 06:29 UTC, Akasurde commented on lib/ansible/modules/system/lbu.py
> +    - List of paths to exclude
```suggestion
    - List of paths to exclude.
```

2019-09-20 06:29 UTC, Akasurde commented on lib/ansible/modules/system/lbu.py
> +    - List of paths to include
```suggestion
    - List of paths to include.
```

2019-09-20 06:29 UTC, Akasurde commented on lib/ansible/modules/system/lbu.py
> +    def run_lbu(*args):
```suggestion
    def run_lbu(*args):
        lbu_path = module.get_bin_path('lbu', required=True)
```

2019-09-20 06:29 UTC, Akasurde commented on lib/ansible/modules/system/lbu.py
> +        code, stdout, stderr = module.run_command(['lbu'] + list(args))
```suggestion
        code, stdout, stderr = module.run_command([lbu_path] + list(args))
```

2019-10-10 07:06 UTC, Akasurde approved these changes

2019-11-30 18:17 UTC, tdtrask commented
shipit

2019-12-02 13:30 UTC, merged