VMware: vmware_cluster_ha example mentions enable_vsan
ansible/ansible pull request #62616
Opened 2019-09-19 18:39 UTC by mariolenz

##### SUMMARY
There is a C&P error in the example section of the documentation: `enable_vsan` isn't a valid parameter.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
vmware_cluster_ha

2019-09-19 19:39 UTC, goneri requested changes
Thanks for the cleanup @mariolenz ! Could you please add a changelog entry, this way the backport of the patch will be easier.

2019-09-19 20:01 UTC, mariolenz commented
> Thanks for the cleanup @mariolenz ! Could you please add a changelog entry, this way the backport of the patch will be easier.

As far as I can see, you don't have a category for documentation fixes. Should I use `bugfixes` or `minor_changes` in the changelog fragment? (Both feel wrong to me, somehow. But all other options are even worse.)

2019-09-20 01:47 UTC, goneri commented
Good question, I would go for `minor_changes`. See: Creating a changelog fragment

2019-09-20 06:33 UTC, merged

2019-09-20 06:34 UTC, Akasurde commented
@mariolenz Could you please create a back port for this change ? You can find the documentation about creating back port [here](https://docs.ansible.com/ansible/latest/community/development_process.html#backporting-merged-prs). Thanks in advance.

2019-09-20 18:01 UTC, mariolenz commented
> @mariolenz Could you please create a back port for this change ? You can find the documentation about creating back port [here](https://docs.ansible.com/ansible/latest/community/development_process.html#backporting-merged-prs). Thanks in advance.

PR #62671