Ec2 metric alarm boto3 and treat missing data
ansible/ansible pull request #62669
Opened 2019-09-20 16:33 UTC by ezmac

##### SUMMARY

Converted the ec2_metric_alarm module to boto3. Added support for the Treat Missing Data option.

Based on the work in PR  #23407.  

I think this also obsoletes 38034 and 33086, which were closed due to inactivity

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

ec2_metric_alarm

##### ADDITIONAL INFORMATION

Test case steals setup from other ec2 module and uses aws cli because there's currently no module to fetch this info.  Tests are basic, but if you want more, let me know.  

```paste below

```

2019-09-20 18:49 UTC, ezmac commented
Current fail is aws permissions.  I'll get back to this PR later, but if anyone knows a fix, please let me know.

2019-09-21 07:01 UTC, tremble requested changes
Permissions are managed through https://github.com/mattclay/aws-terminator however there might not be support for cleaning up the alarms in aws-terminator yet so we may need to make this 'unsupported' for now.

I've not had chance to run the test suite yet, but you may also need to update the testing policies (for devs rather than shippable) : https://github.com/ansible/ansible/tree/devel/hacking/aws_config/testing_policies

2019-09-21 07:01 UTC, tremble commented on lib/ansible/modules/cloud/amazon/ec2_metric_alarm.py
> +    HAS_BOTO3 = False
```suggestion
    pass  # Handled by AnsibleAWSModule
```

2019-09-21 07:01 UTC, tremble commented on lib/ansible/modules/cloud/amazon/ec2_metric_alarm.py
> +    HAS_BOTO3 = True
Not needed

2019-09-21 07:01 UTC, tremble commented on test/integration/targets/ec2_metric_alarm/defaults/main.yml
> +ec2_ami_image:
Rather than having a hard coded list you can use ec2_ami_info  (name can be wildcarded)

```
    - name: Find AMI to use 
      ec2_ami_info:
        owners: 'amazon'
        filters:
          name: '{{ ec2_ami_name }}'
      register: ec2_amis
    - set_fact:
        ec2_ami_image: '{{ ec2_amis.images[0].image_id }}'
```

2019-09-21 07:01 UTC, tremble commented on test/integration/targets/ec2_metric_alarm/tasks/main.yml
> +    - name: set up aws connection info
Rather than this fact block I'd recommend using 
```
module_defaults:
  group/aws:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      security_token: "{{ security_token | default(omit) }}"
      region: "{{ aws_region }}"
```

It behaves better when security_token isn't set, and it helps catch issues where the group hasn't been properly updated.  You also only need to define it at this top level rather than in all of your includes too.

2019-09-21 07:01 UTC, tremble commented on lib/ansible/modules/cloud/amazon/ec2_metric_alarm.py
> +    region, ec2_url, aws_connect_params = get_aws_connection_info(module, boto3=True)
You can make use of some of the helpers in AnsibleAWSModule
```suggestion
    connection = module.client('cloudwatch')
```

This then moots the pieces below.

2019-09-21 07:01 UTC, tremble commented on lib/ansible/modules/cloud/amazon/ec2_metric_alarm.py
> +            comparison=dict(type='str', choices=['LessThanOrEqualToThreshold', 'LessThanThreshold', 'GreaterThanThreshold',
Having migrated to AnsibleAWSModule you shouldn't need ec2_argument_spec any more, it's automatically added

2019-09-23 15:14 UTC, tremble requested changes
Looking better, still some minor issues.

2019-09-23 15:14 UTC, tremble commented on test/integration/targets/ec2_metric_alarm/tasks/env_setup.yml
> +  set_fact:
Not needed now you're using module_defaults in main.yml

2019-09-23 15:14 UTC, tremble commented on test/integration/targets/ec2_metric_alarm/tasks/env_cleanup.yml
> +  set_fact:
Not needed now you're using module_defaults

2019-09-23 15:14 UTC, tremble commented on lib/ansible/modules/cloud/amazon/ec2_metric_alarm.py
>          dict(
Looks like an extra dict

2019-09-23 16:51 UTC, ezmac commented
@tremble 
Thanks for the reviews and sorry for the back and forth.  It's been a while since I looked at ansible from this side.  If all the tests run with the same iam policy created by aws_config/testing_policies, then it should be enough to add cloudwatch:DeleteAlarms to the container-policy, but that seems like it's not the correct place.  Please let me know if there's something I need to be doing with policies.

2019-10-15 22:18 UTC, jillr reviewed
Thanks very much for picking this up @ezmac, it will be good to get this refactor merged. I'll take a look at the policy change again this week too (I generally go through that queue in batches since they have to be deployed to the CI environment to be tested).

2019-10-15 22:18 UTC, jillr commented on lib/ansible/modules/cloud/amazon/ec2_metric_alarm.py
> +          - '>'
Can you please note these options as deprecated here in the docs as well?

2019-10-15 22:18 UTC, jillr commented on lib/ansible/modules/cloud/amazon/ec2_metric_alarm.py
> +        warnings.append('Using the <=, <, > and >= operators for comparison has been deprecated. Please use LessThanOrEqualToThreshold, '
This should use `module.deprecate`, there's a good example in https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/aws_kms.py#L954:L956

2019-10-15 22:18 UTC, jillr commented on lib/ansible/modules/cloud/amazon/ec2_metric_alarm.py
> +          - 'GreaterThanOrEqualToThreshold'
Should this also have 'LessThanLowerOrGreaterThanUpperThreshold', 'LessThanLowerThreshold', and 'GreaterThanUpperThreshold'?

2019-10-15 22:18 UTC, jillr commented on lib/ansible/modules/cloud/amazon/ec2_metric_alarm.py
> +            module.fail_json(msg=str(e))
Use module.fail_json_aws(e), which will handle calling ansible.module_utils._text.to_native() on e for you.

2019-10-15 22:18 UTC, jillr commented on lib/ansible/modules/cloud/amazon/ec2_metric_alarm.py
> +        except ClientError as e:
This one was here originally, but would you be able to also update this to use module.fail_json_aws(e)?  The to_native() call that uses does a better job of handling py2/3 type conversions and is all-around preferred.

2019-10-15 22:18 UTC, jillr commented on lib/ansible/modules/cloud/amazon/ec2_metric_alarm.py
> +        except (ClientError) as e:
And here as well.

2019-10-15 22:18 UTC, jillr commented on test/integration/targets/ec2_metric_alarm/tasks/main.yml
> +
Can you please add idempotency tests? So for example here you would repeat the test from line 48 as:
`- name: create ec2 metric alarm on ec2 instance (idempotent)`
And assert that the result did not change.

2019-10-16 15:26 UTC, ezmac commented on lib/ansible/modules/cloud/amazon/ec2_metric_alarm.py
> +          - 'GreaterThanOrEqualToThreshold'
It looks like yes.  They were added fairly recently (botocore 1.12.185) so I'll add some error checking around that.  Is this the way that kind of tests should be written? https://github.com/ansible/ansible/blob/devel/test/integration/targets/ecs_cluster/tasks/main.yml

2019-10-16 17:26 UTC, jillr commented on lib/ansible/modules/cloud/amazon/ec2_metric_alarm.py
> +          - 'GreaterThanOrEqualToThreshold'
Yes, thanks

2019-10-17 20:40 UTC, ezmac commented on lib/ansible/modules/cloud/amazon/ec2_metric_alarm.py
> +          - 'GreaterThanOrEqualToThreshold'
This looks much more involved than I originally thought.  

From https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cloudwatch.html#CloudWatch.Client.put_metric_alarm, "The values LessThanLowerOrGreaterThanUpperThreshold , LessThanLowerThreshold , and GreaterThanUpperThreshold are used only for alarms based on anomaly detection models." 

From https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/using-metric-math.html#metric-math-syntax, anomaly detection looks like it's part of metric math equations.

2019-10-17 20:54 UTC, jillr commented on lib/ansible/modules/cloud/amazon/ec2_metric_alarm.py
> +          - 'GreaterThanOrEqualToThreshold'
Thanks for looking into that, it would make a good feature if someone wants to work on it but sounds like it exceeds the scope of this change.

2019-10-17 23:33 UTC, jillr commented
New policies have been deployed to the CI environment.

2019-10-22 13:57 UTC, ezmac commented on lib/ansible/modules/cloud/amazon/ec2_metric_alarm.py
> +          - '>'
I've noted that symbolic comparison operators are deprecated in the doc block around line 69.

2019-10-22 13:58 UTC, ezmac commented on lib/ansible/modules/cloud/amazon/ec2_metric_alarm.py
> +            module.fail_json(msg=str(e))
This and the other three have been changed to fail_json_aws as requested.

2019-10-22 15:49 UTC, ezmac commented on test/integration/targets/ec2_metric_alarm/tasks/main.yml
> +
Idempotency test has been added.  It should test both the changed property as well as the properties returned from the api call.

2019-10-22 18:13 UTC, jillr approved these changes
LGTM, thanks very much @ezmac!
shipit

2019-12-12 21:09 UTC, merged