Update vmware ansible modules requirements section
ansible/ansible pull request #62797
Opened 2019-09-24 15:30 UTC by jobingeo

##### SUMMARY
Some of the recent vmware modules like content library, tagging is using vsphere automation sdk. 
All the new features(APIs) from vsphere 6.0 are available only in vSphere Automation SDKs.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
Documentation Update

##### ADDITIONAL INFORMATION
Added a documentation section as below:

```
Ansible VMware modules leveraging latest vSphere(6.0+) features are using vSphere Automation Python SDK. The vSphere Automation Python SDK also have client libraries, documentation and sample code for VMware Cloud on AWS Console APIs, NSX VMware Cloud on AWS integration APIs, VMware Cloud on AWS site recovery APIs and NSX-T APIs. You can install vSphere Automation Python SDK using pip:

$ pip install --upgrade git+https://github.com/vmware/vsphere-automation-sdk-python.git
Note:
Installing vSphere Automation Python SDK also installs pyvmomi. A separate installation of pyvmomi is not required.

```

2019-09-25 08:05 UTC, pgbidkar requested changes

2019-09-25 08:05 UTC, pgbidkar commented on docs/docsite/rst/scenario_guides/vmware_scenarios/vmware_intro.rst
> +Ansible VMware modules leveraging latest vSphere(6.0+) features are using `vSphere Automation Python SDK <https://github.com/vmware/vsphere-automation-sdk-python>`__. The vSphere Automation Python SD
Change The vSphere Automation Python SDK also have to The vSphere Automation Python SDK also **has**

Change documentation and to documentation,

2019-09-26 14:45 UTC, samccann commented on docs/docsite/rst/scenario_guides/vmware_scenarios/vmware_intro.rst
> +Ansible VMware modules leveraging latest vSphere(6.0+) features are using `vSphere Automation Python SDK <https://github.com/vmware/vsphere-automation-sdk-python>`__. The vSphere Automation Python SD
```suggestion
Ansible VMware modules leveraging latest vSphere(6.0+) features are using `vSphere Automation Python SDK <https://github.com/vmware/vsphere-automation-sdk-python>`__. The vSphere Automation Python SDK also has client libraries, documentation, and sample code for VMware Cloud on AWS Console APIs, NSX VMware Cloud on AWS integration APIs, VMware Cloud on AWS site recovery APIs, and NSX-T APIs. You can install vSphere Automation Python SDK using pip:
```

2019-10-17 08:58 UTC, pgbidkar approved these changes
LGTM

2019-10-18 06:04 UTC, merged