add update_cache_allow_releaseinfo_change option
ansible/ansible pull request #62824
Opened 2019-09-25 09:12 UTC by agix

##### SUMMARY
This add an option to pass `--allow-releaseinfo-change` to `update_cache`

It should fixes https://github.com/ansible/ansible/issues/30754

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
Change in apt module

2019-10-03 19:26 UTC, bcoca requested changes

2019-10-03 19:26 UTC, bcoca commented on lib/ansible/modules/packaging/os/apt.py
> +    description:
remove update_cache from name and add to the description 'this option is only used if update_cache is yes/truye'

2020-07-13 18:33 UTC, mkosobucki commented
any update on this?

2020-11-21 22:00 UTC, asper-ru commented
No any movement yet, eh?
Do we wait for review from @bcoca ?

2021-02-23 00:10 UTC, bcoca commented
needs a change log ... i would also like to add tests but not sure how to do that without possibly breaking the apt based images

2021-08-16 09:34 UTC, freeyoung commented
Since Debian `bullseye` was released the day before yesterday, I guess there would be more Ansible users wishing this to be merged earlier.

2022-02-28 17:54 UTC, mds-lord approved these changes
this option is truly missing and should be added to apt module.

2022-04-11 10:37 UTC, tagirb commented
Came across this issue just today. Any news as to when this PR will be merged?

2022-05-24 12:22 UTC, johnbui423 commented
@agix - are you still planning to address the missing changelog comment? That seems to be the only review comment holding this back? See https://docs.ansible.com/ansible/latest/community/development_process.html#community-changelogs for more info on how to do this.
Thanks!

2022-05-24 13:30 UTC, agix commented
Few years I didn't work with ansible.
If you want to do it, please do.

I may take a look this week otherwise.

2022-09-14 19:43 UTC, nitzmahone commented
Closing for inactivity- feel free to reopen if anyone wants to run this one to completion

2022-09-14 19:43 UTC, closed without merging