fix os_user_role for groups in multidomain context
ansible/ansible pull request #62858
Opened 2019-09-26 08:11 UTC by bverschueren

##### SUMMARY
In a multidomain context, if the same group name exists in multiple domains, the module fails with `"msg": "Multiple matches found for %s"`.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
os_user_role

##### ADDITIONAL INFORMATION
Steps to reproduce:

Create a group & project in 2 separate domains and assign a role to the group on the project:

```
---
- hosts: localhost
  gather_facts: no

  tasks:
    - os_keystone_domain:
        cloud: test-cloud
        state: present
        name: "{{ item }}"
      with_items:
        - "domain_1"
        - "domain_2"
      register: domains

    - os_group:
        cloud: test-cloud
        name: group_1
        domain_id: "{{ item.id }}"
      with_items: "{{ domains.results }}"

    - os_project:
        cloud: test-cloud
        name: project_1
        domain_id: "{{ item.id }}"
      with_items: "{{ domains.results }}"

    - os_user_role:
        cloud: test-cloud
        role: admin
        group: group_1
        project: project_1
        domain: "{{ item.id }}"
      with_items: "{{ domains.results }}"
```

Before change:
```paste below
failed: [localhost] (item={'changed': False, <...>  "msg": "Multiple matches found for group_1"}
failed: [localhost] (item={'changed': False, <...>  "msg": "Multiple matches found for group_1"}                                
```
After change:
```paste below                                                           
changed: [localhost] => (item={<...> => {"ansible_loop_var": "item", "changed": true, <...> }
changed: [localhost] => (item={<...> => {"ansible_loop_var": "item", "changed": true, <...> }
```

2020-01-07 22:56 UTC, cloudnull approved these changes
shipit

2020-01-20 13:48 UTC, sshnaidm commented
Thanks for submitting patch for Openstack Ansible modules!
We moved Openstack Ansible modules to Openstack repositories.
Next patches should be submitted not with Ansible Github but with
Openstack Gerrit: https://review.opendev.org/#/q/project:openstack/ansible-collections-openstack
Please submit your code there from now.
Thanks for your contribution and sorry for inconvienience.

2020-01-21 08:12 UTC, sshnaidm requested changes
Because we moved Openstack Ansible modules to Openstack repositories, please submit all changes from openstack modules to Openstack Gerrit: https://review.opendev.org/#/q/project:openstack/ansible-collections-openstack Thanks for your contribution and sorry for inconvienience.

2020-01-23 07:28 UTC, bverschueren commented
duplicated this to https://review.opendev.org/703930

2020-01-23 07:28 UTC, closed without merging