Doc updates to openssl_certificate and ecs_certificate
ansible/ansible pull request #63006
Opened 2019-10-01 13:12 UTC by ctrufan

##### SUMMARY
Some minor fixes to the language and syntax used in the entrust specific certificate modules.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
openssl_certificate
ecs_certificate

2019-10-02 11:39 UTC, felixfontein requested changes
Besides the one option, looks good!

2019-10-02 11:39 UTC, felixfontein commented on lib/ansible/modules/crypto/entrust/ecs_certificate.py
> +            - The destination path for a backup of the certificate in I(path).
```suggestion
            - Whether a backup should be made for the certificate in I(path).
```
After all, it's a boolean option, and not the return value (which will contain the path) :)

2019-10-02 14:02 UTC, felixfontein approved these changes

2019-10-02 21:06 UTC, merged

2019-10-02 21:07 UTC, felixfontein commented
@ctrufan thanks for caring about the docs! :)

Do you want to create a backport PR for `stable-2.9`?

2019-10-02 22:41 UTC, ctrufan commented
I wasn't sure if it was too late, I'll create a backport tomorrow!

2019-10-03 04:15 UTC, felixfontein commented
It could very well be too late for 2.9.0, but should definitely make it for 2.9.1. And docs changes are sometimes also merged between releases, so it could show up even earlier than 2.9.1.

2019-10-03 15:52 UTC, ctrufan commented
@felixfontein 
Thanks for the review and merge!