skip adding aliases to argument_spec #62315
ansible/ansible pull request #63017
Opened 2019-10-01 16:04 UTC by artbycrunk

##### SUMMARY

Based on the issue reported by @sndv([62315](https://github.com/ansible/ansible/issues/62315)) 

Fix suggested by @sivel, thanks

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

module_utils/basic.py

##### ADDITIONAL INFORMATION

More information about how to reproduce this issue is described in the issue [62315](https://github.com/ansible/ansible/issues/62315)

RESULTS AFTER FIX 
```paste below
TASK [Gathering Facts] ***********************************************************************************************************[0/3864]
ok: [localhost]

TASK [blockinfile] ***********************************************************************************************************************
--- before: /tmp/blockinfile-test-block (content)
+++ after: /tmp/blockinfile-test-block (content)
@@ -0,0 +1,3 @@
+# BEGIN ANSIBLE MANAGED BLOCK
+some content
+# END ANSIBLE MANAGED BLOCK

changed: [localhost]

TASK [blockinfile] ***********************************************************************************************************************
--- before: /tmp/blockinfile-test-content (content)
+++ after: /tmp/blockinfile-test-content (content)
@@ -0,0 +1,3 @@
+# BEGIN ANSIBLE MANAGED BLOCK
+some content
+# END ANSIBLE MANAGED BLOCK

changed: [localhost]

PLAY RECAP *******************************************************************************************************************************
localhost                  : ok=3    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

```

2019-10-10 19:35 UTC, sivel requested changes
Not a full review, only just this print. Because I provided the original diff, I probably should not review this in it's entirety.

2019-10-10 19:35 UTC, sivel commented on lib/ansible/module_utils/basic.py
> +            print("add_file_common_args", add_file_common_args)
This print needs removed.

2020-08-27 00:27 UTC, terencehonles commented
Would it help to rebase an open a new PR? Not sure what the next steps for this PR are.

2020-08-31 05:02 UTC, Akasurde commented
@artbycrunk Are you still working on this? If yes, please rebase this branch, remove `print` statement, add a changelog entry, and add a test for this change. Thanks.

needs_info

2020-09-01 01:40 UTC, terencehonles commented
> @artbycrunk Are you still working on this? If yes, please rebase this branch, remove `print` statement, add a changelog entry, and add a test for this change. Thanks.
> 
> needs_info

@Akasurde it looks like this has already been fixed on devel. I opened #71555 to show so (I was trying to write a test after rebasing this change).

2020-09-01 06:12 UTC, terencehonles commented
> > @artbycrunk Are you still working on this? If yes, please rebase this branch, remove `print` statement, add a changelog entry, and add a test for this change. Thanks.
> > needs_info
> 
> @Akasurde it looks like this has already been fixed on devel. I opened #71555 to show so (I was trying to write a test after rebasing this change).

I replaced #71555 with #71557 because I realized the change that @sivel suggested is probably something that still should be added.

2020-11-04 07:16 UTC, closed without merging