ios_bgp :  Fix for bug #59083
ansible/ansible pull request #63055
Opened 2019-10-02 14:58 UTC by GomathiselviS

SUMMARY
Added fix to handle idempotentency issue when using networks on classful boundaries

Fixes #59083

ISSUE TYPE
Bugfix Pull Request

COMPONENT NAME
lib/ansible/module_utils/network/ios/providers/cli/config/bgp/process.py

2019-10-02 17:45 UTC, GomathiselviS commented
recheck

2019-10-02 19:25 UTC, Qalthos requested changes

2019-10-02 19:25 UTC, Qalthos commented on test/integration/targets/ios_bgp/tests/cli/basic.yaml
> +
You've got extra spaces here that I'd rather not see, but otherwise looks fine

2019-10-04 05:25 UTC, NilashishC approved these changes
Looks good to me +1

2019-10-04 14:55 UTC, Qalthos approved these changes

2019-10-04 14:56 UTC, merged