support syslog module
ansible/ansible pull request #63177
Opened 2019-10-06 13:12 UTC by anas-shami

support syslog module to config. logging levels and priorities 

You can configure: 
- local level 
- trap 
- format 
- monitor facility and override class
- enable receive logging 
- change fraction digits or whole digits in the seconds field

2019-10-24 15:32 UTC, samerd requested changes
Thanks @anas-shami 
please fix according to the comments

2019-10-24 15:32 UTC, samerd commented on lib/ansible/modules/network/onyx/onyx_syslog.py
> +        choices: ['alert', 'crit', 'debug', 'emerg', 'err', 'info', 'none', 'notice', 'warning']
please sort this list from least severe to most severe

2019-10-24 15:32 UTC, samerd commented on lib/ansible/modules/network/onyx/onyx_syslog.py
> +                choices: ['alert', 'crit', 'debug', 'emerg', 'err', 'info', 'none', 'notice', 'warning']
use sorted list.
please use the sorted list in all relevant places

2019-10-24 15:32 UTC, samerd commented on lib/ansible/modules/network/onyx/onyx_syslog.py
> +        current_config['received'] = True if current_config.get('received') == 'yes' else False
```python
current_config['received'] = (current_config.get('received') == 'yes')
```

2019-10-24 15:32 UTC, samerd commented on lib/ansible/modules/network/onyx/onyx_syslog.py
> +                if match:
```python
if match:
    current_config['format_welf_host'] = match.group(1)
    continue
```
no need to proceed to other checks when you find a match
do it for all match check

2019-10-27 14:16 UTC, anas-shami commented
@samerd  please review

2019-10-28 17:22 UTC, samerd approved these changes
looks great
thanks @anas-shami

2019-10-28 17:23 UTC, samerd commented
@ganeshrn 
could you please review and approve this PR if it is ok?

2020-08-20 08:38 UTC, Akasurde commented
Hi @anas-shami, Thank you very much for your interest in Ansible. This plugin/module is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/mellanox.onyx<br><br>If you have further questions please stop by IRC or the mailing list:<br><br>* IRC: #ansible on irc.freenode.net<br>* mailing list: https://groups.google.com/forum/#!forum/ansible-project<br><br>needs_info<br>

2020-08-20 08:38 UTC, closed without merging