lineinfile: bugfix 58923, 58946
ansible/ansible pull request #63194
Opened 2019-10-07 11:23 UTC by Andersson007

##### SUMMARY
Fixes #58923
A part of fixes got from https://github.com/ansible/ansible/pull/58946

The doc, particularly, says
```
If regular expressions are passed to both regexp and
insertafter, insertafter is only honored if no match for regexp is found.
```
Therefore:
```
When regular expressions are passed to both regexp and insertafter, then:
1. regexp was found -> ignore insertafter, replace the founded line
2. regexp was not found -> insert the line after 'insertafter' line
```

##### ISSUE TYPE

- Bugfix Pull Request

2019-10-07 11:39 UTC, Andersson007 commented
@mutt13y , samdoran , ffloimair 
would be cool if you all took a look at this, try, then confirm it solves these problems or doesn't

ready_for_review

2019-10-07 11:41 UTC, Andersson007 commented
@samdoran i took some fixes from your fix #58946

2019-10-07 20:40 UTC, samdoran requested changes
Code changes look good and I have tested it and it seems to match the documented and discussed behavior. Thank you for working on this.

I would like to revamp the tests a bit mainly to reset the test file before each group of tests and group test assertions at the end of test.

I made [a gist](https://gist.github.com/samdoran/5b1bdbdfc361dfa413ba5308b125a54a) with the patch. It's possible I have missed a test scenario with the refactoring. I'm not sure we test when the line is present in the file but not in the before/after spot but it _does_ match the regexp (which was one of the problems with my original fix).

2019-10-08 06:19 UTC, Andersson007 commented
@samdoran thank you for helping!
And thank you for sharing this way of assertion, much more clear to compare the results by that.
The patch has been applied, PTAL

2019-10-08 06:35 UTC, Andersson007 commented
@samdoran,
About testing - i think this PR, at least, makes the code corresponding to the documentation and the tests covers these scenarios:
0. All of existent tests were passed
1. Using firstmatch with insertafter and ensure multiple lines are not inserted (your initial part from line 824)
2. insertafter + regexp: when regexp is not presented, the module inserts a line after 'insertafter' line
3. insertafter + regexp: try again - nothing has been changed
4. insertafter without regexp (the file was recreated  previously):  the line was inserted after 'insertafter' line
5. did the same again - nothing has been changed
6. did all steps for insertbefore - all was as expected

2019-10-08 14:00 UTC, samdoran approved these changes

2019-10-08 14:01 UTC, merged

2019-10-08 14:03 UTC, samdoran commented
Please create a [backport PR](https://docs.ansible.com/ansible/latest/community/development_process.html#backporting-merged-prs) for this to be included in previous versions. We haven't released 2.9 yet and we plan to do one last release of 2.8, so please open backports against `stable-2.9` and `stable-2.8`. Thank you!

2019-10-08 14:05 UTC, Andersson007 commented
@samdoran , sure!
Thank you for the code, rewinding, and merging!