Added Unit tests to eos_logging
ansible/ansible pull request #63248
Opened 2019-10-08 19:44 UTC by GomathiselviS

SUMMARY

Added Unit Testcases to eos_logging module

ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME
test/units/modules/network/eos/test_eos_logging.py

2019-10-09 15:48 UTC, GomathiselviS commented
recheck

2019-10-23 20:49 UTC, Qalthos requested changes
Again with commands that aren't asserted. You could probably at least do something with `load_config.assert_called_once_with(...)` if you really wanted to, but that's probably overkill

2019-10-23 20:49 UTC, Qalthos commented on test/units/modules/network/eos/test_eos_logging.py
> +        commands = ['logging host 175.16.0.10']
```suggestion
```

2019-10-23 20:49 UTC, Qalthos commented on test/units/modules/network/eos/test_eos_logging.py
> +        commands = ['logging buffered 5']
```suggestion
```

2019-10-25 15:15 UTC, GomathiselviS commented
recheck

2019-10-31 18:34 UTC, GomathiselviS commented on test/units/modules/network/eos/test_eos_logging.py
> +        commands = ['logging buffered 5']
Done!

2019-11-04 14:03 UTC, Qalthos approved these changes

2019-11-05 12:50 UTC, merged