Add new module ce_lldp to manage Link Layer Discovery Protocol(LLDP)
ansible/ansible pull request #63395
Opened 2019-10-11 14:32 UTC by xuxiaowei0512

##### SUMMARY

A new module ce_lldp to manage Link Layer Discovery Protocol(LLDP)

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

lib/ansible/modules/network/cloudengine/ce_lldp.py
##### ADDITIONAL INFORMATION

sample:

```paste below
```

2019-10-12 00:55 UTC, hwDCN commented
LGTM

2019-10-18 09:22 UTC, hwDCN commented
shipit

2019-10-18 10:04 UTC, zhongjun2 commented
LGTM

2019-10-18 10:31 UTC, Andersson007 requested changes

2019-10-18 10:31 UTC, Andersson007 commented on lib/ansible/modules/network/cloudengine/ce_lldp.py
> +    description: k/v pairs of existing global LLDP configration
```suggestion
    description: k/v pairs of existing global LLDP configuration
```

2019-10-18 10:31 UTC, Andersson007 commented on lib/ansible/modules/network/cloudengine/ce_lldp.py
> +    description: k/v pairs of global LLDP configration after module execution
```suggestion
    description: k/v pairs of global LLDP configuration after module execution
```

2019-10-18 10:31 UTC, Andersson007 commented on lib/ansible/modules/network/cloudengine/ce_lldp.py
> +    """Manage global lldp enable configration"""
```suggestion
    """Manage global lldp enable configuration"""
```

2019-10-18 10:31 UTC, Andersson007 commented on lib/ansible/modules/network/cloudengine/ce_lldp.py
> +                    msg='Error: Bind_name length is beetween 1 and 63.')
```suggestion
                    msg='Error: Bind_name length is between 1 and 63.')
```

2019-10-18 10:31 UTC, Andersson007 commented on lib/ansible/modules/network/cloudengine/ce_lldp.py
> +        """Excute task"""
```suggestion
        """Execute task"""
```

2019-10-18 11:02 UTC, xuxiaowei0512 commented on lib/ansible/modules/network/cloudengine/ce_lldp.py
> +                    msg='Error: Bind_name length is beetween 1 and 63.')
Done.

2019-10-18 11:02 UTC, xuxiaowei0512 commented on lib/ansible/modules/network/cloudengine/ce_lldp.py
> +    description: k/v pairs of global LLDP configration after module execution
Done.

2019-10-18 11:03 UTC, xuxiaowei0512 commented on lib/ansible/modules/network/cloudengine/ce_lldp.py
> +    description: k/v pairs of existing global LLDP configration
Done.

2019-10-18 11:06 UTC, xuxiaowei0512 commented
@Andersson007  Done, it is so good for me.
Thank you so much.

2019-10-18 11:15 UTC, xuxiaowei0512 commented
read_for_review

2019-10-18 11:17 UTC, yuandongxx approved these changes
LGTM

2019-10-18 11:23 UTC, gundalow commented
bot_status

2019-10-18 11:26 UTC, hwDCN commented
shipit

2019-10-18 11:27 UTC, hwDCN commented
bot_status

2019-10-18 11:40 UTC, hwDCN commented
+1

2019-10-18 11:41 UTC, hwDCN commented
LGTM

2019-10-18 11:43 UTC, xuxiaowei0512 commented
bot_status

2019-10-18 11:51 UTC, Andersson007 commented
!needs_revision

2019-10-18 11:56 UTC, Andersson007 approved these changes
The changes I requested were done correctly. I cannot comment on anything else.
(and i am far from the topic)

2019-10-18 12:15 UTC, merged

2019-10-18 13:38 UTC, xuxiaowei0512 commented
@Andersson007 @gundalow  @zhongjun2 
Thank you for your help.