Add unit testcases to eos_vlans
ansible/ansible pull request #63404
Opened 2019-10-11 16:58 UTC by GomathiselviS

##### SUMMARY

Added Unit testcases for the resource module eos_vlans

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME
/home/gosriniv/ansible/test/units/modules/network/eos/test_eos_vlans.py

2019-10-23 20:47 UTC, Qalthos requested changes
You don't need to specify commands if you're not going to assert them with `execute_module`.

Is the vlan issue fixed? If not, what is the issue #? I prefer not to commit commented tests without good reason

2019-10-23 20:47 UTC, Qalthos commented on test/units/modules/network/eos/test_eos_vlans.py
> +        #       file_cmd_dict = {file_cmd[i]: file_cmd[i + 1] for i in range(0, len(file_cmd), 2)}
Yeah, we still can't use dict comprehensions until 2.6 is formally dropped, sorry.

2019-10-23 20:47 UTC, Qalthos commented on test/units/modules/network/eos/test_eos_vlans.py
> +        commands = ['vlan 10', 'name ten']
```suggestion
```

2019-10-23 20:47 UTC, Qalthos commented on test/units/modules/network/eos/test_eos_vlans.py
> +        commands = ['vlan 10', 'name ten']
```suggestion
```

2019-10-23 20:47 UTC, Qalthos commented on test/units/modules/network/eos/test_eos_vlans.py
> +        commands = ['vlan 30', 'state 10']
```suggestion
```

2019-10-23 20:47 UTC, Qalthos commented on test/units/modules/network/eos/test_eos_vlans.py
> +    #        commands = ['vlan outofrange']
```suggestion
```

2019-10-23 20:47 UTC, Qalthos commented on test/units/modules/network/eos/test_eos_vlans.py
> +        commands = ['vlan thirty']
```suggestion
```

2019-10-23 20:47 UTC, Qalthos commented on test/units/modules/network/eos/test_eos_vlans.py
> +        commands = ['vlan 10', 'name ten']
```suggestion
```

2019-10-23 20:47 UTC, Qalthos commented on test/units/modules/network/eos/test_eos_vlans.py
> +        commands = ['vlan 10', 'name ten']
```suggestion
```

2019-10-30 16:37 UTC, GomathiselviS commented on test/units/modules/network/eos/test_eos_vlans.py
> +        #       file_cmd_dict = {file_cmd[i]: file_cmd[i + 1] for i in range(0, len(file_cmd), 2)}
Addressed the review comments

2019-10-31 13:34 UTC, Qalthos commented on test/units/modules/network/eos/test_eos_vlans.py
> +        #       file_cmd_dict = {file_cmd[i]: file_cmd[i + 1] for i in range(0, len(file_cmd), 2)}
Can you remove the commented comprehensions? It is unfortunate that dict comprehensions aren't available, but having commented code floating around is rarely helpful.

2019-10-31 15:02 UTC, GomathiselviS commented on test/units/modules/network/eos/test_eos_vlans.py
> +        #       file_cmd_dict = {file_cmd[i]: file_cmd[i + 1] for i in range(0, len(file_cmd), 2)}
Done!

2019-11-04 14:00 UTC, Qalthos approved these changes

2019-11-05 12:55 UTC, merged