Update cache plugin documentation
ansible/ansible pull request #63635
Opened 2019-10-17 15:11 UTC by s-hertel

##### SUMMARY
Fixes #63616

Since 2.8 cache plugins using BaseCacheModule and BaseFileCacheModule as the base class can be used for inventory.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
docs/docsite/rst/plugins/cache.rst

2019-10-19 15:57 UTC, Akasurde commented on docs/docsite/rst/plugins/cache.rst
> +Prior to Ansible 2.8, inventory plugins that support caching could use file-based cache plugins, such as jsonfile, pickle, and yaml. For Ansible 2.8 and later all cache plugins shipped with Ansible a
```suggestion
Prior to Ansible 2.8, inventory plugins that support caching could use file-based cache plugins, such as jsonfile, pickle, and yaml. For Ansible 2.8 and later all cache plugins shipped with Ansible are supported. Check the specific inventory plugin to see if it supports caching. To cache inventory with a custom plugin in your plugin path, take a look at the `developer's guide for cache plugins <https://docs.ansible.com/ansible/latest/dev_guide/developing_plugins.html#cache-plugins>`_. Cache plugins inside a collection are not supported for caching inventory.
```

2019-10-22 09:08 UTC, s-hertel commented on docs/docsite/rst/plugins/cache.rst
> +Prior to Ansible 2.8, inventory plugins that support caching could use file-based cache plugins, such as jsonfile, pickle, and yaml. For Ansible 2.8 and later all cache plugins shipped with Ansible a
Thanks :)

2019-10-22 09:24 UTC, Akasurde approved these changes
LGTM

2019-10-25 10:16 UTC, gundalow requested changes

2019-10-25 10:16 UTC, gundalow commented on docs/docsite/rst/plugins/cache.rst
> +Prior to Ansible 2.8, inventory plugins that support caching could use file-based cache plugins, such as jsonfile, pickle, and yaml. For Ansible 2.8 and later all cache plugins shipped with Ansible a
```suggestion
Prior to Ansible 2.8, inventory plugins that support caching could use file-based cache plugins, such as jsonfile, pickle, and yaml. For Ansible 2.8 and later all cache plugins shipped with Ansible are supported. Check the specific inventory plugin to see if it supports caching. To cache inventory with a custom plugin in your plugin path, take a look at the :ref:`developer guide on cache plugins<developing_cache_plugins>`. Cache plugins inside a collection are not supported for caching inventory.
```

2019-10-28 15:39 UTC, s-hertel commented on docs/docsite/rst/plugins/cache.rst
> +Prior to Ansible 2.8, inventory plugins that support caching could use file-based cache plugins, such as jsonfile, pickle, and yaml. For Ansible 2.8 and later all cache plugins shipped with Ansible a
Thanks, links are difficult :-)

2019-10-31 08:00 UTC, gundalow approved these changes

2019-11-01 19:39 UTC, s-hertel commented
Thanks for the reviews. @acozine let me know at the beginning of this week "I might make a few changes on top of your changes" in regard to this PR, so this is just waiting on that.

2019-11-18 22:00 UTC, merged