add a new module to confiure isis on interface.
ansible/ansible pull request #63717
Opened 2019-10-20 09:16 UTC by xuxiaowei0512

##### SUMMARY

##### ISSUE TYPE

- Bugfix Pull Request
##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2019-10-21 01:14 UTC, xuxiaowei0512 commented
-label bug

2019-10-27 06:26 UTC, yuandongxx requested changes

2019-10-27 06:26 UTC, hwDCN commented on lib/ansible/modules/network/cloudengine/ce_is_is_interface.py
> +    - Manages  isis process id, creates a isis instance id or deletes a process id
Manages  isis process id --->  Manages isis process id

2019-10-27 06:26 UTC, hwDCN commented on lib/ansible/modules/network/cloudengine/ce_is_is_interface.py
> +    required: false
required: false is default behavior.

2019-10-27 06:26 UTC, hwDCN commented on lib/ansible/modules/network/cloudengine/ce_is_is_interface.py
> +    required: false
Same....

2019-10-27 06:26 UTC, hwDCN commented on lib/ansible/modules/network/cloudengine/ce_is_is_interface.py
> +    required: false
Same....

2019-10-27 06:26 UTC, hwDCN commented on lib/ansible/modules/network/cloudengine/ce_is_is_interface.py
> +    required: false
same

2019-10-27 06:26 UTC, hwDCN commented on lib/ansible/modules/network/cloudengine/ce_is_is_interface.py
> +    required: false
same

2019-10-27 06:26 UTC, hwDCN commented on lib/ansible/modules/network/cloudengine/ce_is_is_interface.py
> +    required: false
same

2019-10-27 06:26 UTC, hwDCN commented on lib/ansible/modules/network/cloudengine/ce_is_is_interface.py
> +    required: false
same

2019-10-27 06:26 UTC, hwDCN commented on lib/ansible/modules/network/cloudengine/ce_is_is_interface.py
> +    required: false
same

2019-10-27 06:26 UTC, hwDCN commented on lib/ansible/modules/network/cloudengine/ce_is_is_interface.py
> +    required: false
same

2019-10-27 06:26 UTC, hwDCN commented on lib/ansible/modules/network/cloudengine/ce_is_is_interface.py
> +    required: false
same

2019-10-27 06:26 UTC, hwDCN commented on lib/ansible/modules/network/cloudengine/ce_is_is_interface.py
> +    required: false
same

2019-10-27 06:26 UTC, hwDCN commented on lib/ansible/modules/network/cloudengine/ce_is_is_interface.py
> +    required: false
same

2019-10-27 07:18 UTC, xuxiaowei0512 commented on lib/ansible/modules/network/cloudengine/ce_is_is_interface.py
> +    - Manages  isis process id, creates a isis instance id or deletes a process id
Done

2019-10-27 07:18 UTC, xuxiaowei0512 commented on lib/ansible/modules/network/cloudengine/ce_is_is_interface.py
> +    required: false
Done

2019-10-27 07:18 UTC, xuxiaowei0512 commented on lib/ansible/modules/network/cloudengine/ce_is_is_interface.py
> +    required: false
Done

2019-10-27 07:18 UTC, xuxiaowei0512 commented on lib/ansible/modules/network/cloudengine/ce_is_is_interface.py
> +    required: false
Done

2019-10-27 07:19 UTC, xuxiaowei0512 commented on lib/ansible/modules/network/cloudengine/ce_is_is_interface.py
> +    required: false
Done

2019-10-27 07:19 UTC, xuxiaowei0512 commented on lib/ansible/modules/network/cloudengine/ce_is_is_interface.py
> +    required: false
Done

2019-10-27 07:20 UTC, xuxiaowei0512 commented
ready_for_review

2019-10-27 08:25 UTC, hwDCN commented
shipit

2019-10-27 08:26 UTC, yuandongxx approved these changes

2019-11-01 16:52 UTC, hwDCN commented
shipit

2019-11-01 16:52 UTC, hwDCN commented
+1

2019-11-25 01:11 UTC, hwDCN commented
shipit

2019-11-26 11:12 UTC, merged