add a new module to create isis instance.
ansible/ansible pull request #63716
Opened 2019-10-20 09:07 UTC by xuxiaowei0512

##### SUMMARY

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2019-10-27 06:20 UTC, yuandongxx requested changes

2019-10-27 06:20 UTC, hwDCN commented on lib/ansible/modules/network/cloudengine/ce_is_is_instance.py
> +RETURN = '''
r'''

2019-10-27 06:20 UTC, hwDCN commented on lib/ansible/modules/network/cloudengine/ce_is_is_instance.py
> +      - VPN Instance, Associate the VPN instance with the corresponding IS-IS process.
Associate -> associate

2019-10-27 06:20 UTC, hwDCN commented on lib/ansible/modules/network/cloudengine/ce_is_is_instance.py
> +    required: false
required: false is default behavior.

2019-10-27 06:20 UTC, hwDCN commented on lib/ansible/modules/network/cloudengine/ce_is_is_instance.py
> +    required: false
required: false is default behavior.

2019-10-27 07:04 UTC, xuxiaowei0512 commented on lib/ansible/modules/network/cloudengine/ce_is_is_instance.py
> +    required: false
Done

2019-10-27 07:04 UTC, xuxiaowei0512 commented on lib/ansible/modules/network/cloudengine/ce_is_is_instance.py
> +    required: false
Done

2019-10-27 07:04 UTC, xuxiaowei0512 commented on lib/ansible/modules/network/cloudengine/ce_is_is_instance.py
> +      - VPN Instance, Associate the VPN instance with the corresponding IS-IS process.
Done

2019-10-27 07:05 UTC, xuxiaowei0512 commented on lib/ansible/modules/network/cloudengine/ce_is_is_instance.py
> +RETURN = '''
Done

2019-10-27 07:20 UTC, xuxiaowei0512 commented
ready_for_review

2019-10-27 08:25 UTC, hwDCN commented
shipit

2019-10-27 08:25 UTC, yuandongxx approved these changes

2019-11-01 17:13 UTC, hwDCN commented
shipit

2019-11-26 11:23 UTC, merged