add a new module to configure isis on isis-view.
ansible/ansible pull request #63720
Opened 2019-10-20 12:16 UTC by xuxiaowei0512

##### SUMMARY

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2019-10-21 01:14 UTC, xuxiaowei0512 commented
-label bug

2019-10-27 06:32 UTC, yuandongxx requested changes

2019-10-27 06:32 UTC, hwDCN commented on lib/ansible/modules/network/cloudengine/ce_is_is_view.py
> +    - Manages  isis process id, creates a isis instance id or deletes a process id
Manages isis process id

2019-10-27 06:58 UTC, xuxiaowei0512 commented on lib/ansible/modules/network/cloudengine/ce_is_is_view.py
> +    - Manages  isis process id, creates a isis instance id or deletes a process id
Done

2019-10-27 07:11 UTC, xuxiaowei0512 commented
read_for_review

2019-10-27 07:18 UTC, xuxiaowei0512 commented
ready_for_review

2019-10-27 08:24 UTC, hwDCN commented
shipit

2019-11-01 17:28 UTC, hwDCN commented
shipit

2019-11-01 17:28 UTC, hwDCN commented
+1

2019-11-01 17:28 UTC, hwDCN commented
lgtm

2019-11-20 14:18 UTC, gundalow commented
rebuild_merge

2019-11-20 14:37 UTC, merged

2019-11-21 00:57 UTC, xuxiaowei0512 commented
@gundalow  Thank you very much!