add a new module to configure multicast global.
ansible/ansible pull request #63745
Opened 2019-10-21 12:21 UTC by xuxiaowei0512

##### SUMMARY

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2019-10-27 06:36 UTC, yuandongxx requested changes

2019-10-27 06:36 UTC, hwDCN commented on lib/ansible/modules/network/cloudengine/ce_multicast_global.py
> +                # self.multicast_global_info['multicast_global'] has not value
unused code?
```suggestion
                # multicast_global_info has no multicast_global value.
```

2019-10-27 06:36 UTC, hwDCN commented on lib/ansible/modules/network/cloudengine/ce_multicast_global.py
> +                # self.multicast_global_info['multicast_global'] has value
```suggestion
                # multicast_global_info has no multicast_global value
```

2019-10-27 06:36 UTC, hwDCN commented on lib/ansible/modules/network/cloudengine/ce_multicast_global.py
> +                # mcast_enable_key = {vrfName:11,addressFamily:'xx'}
```suggestion
                # i.e. mcast_enable_key = {vrfName:11,addressFamily:'xx'}
```

2019-10-27 06:57 UTC, xuxiaowei0512 commented on lib/ansible/modules/network/cloudengine/ce_multicast_global.py
> +                # mcast_enable_key = {vrfName:11,addressFamily:'xx'}
Done

2019-10-27 06:57 UTC, xuxiaowei0512 commented on lib/ansible/modules/network/cloudengine/ce_multicast_global.py
> +                # self.multicast_global_info['multicast_global'] has value
Done

2019-10-27 06:57 UTC, xuxiaowei0512 commented on lib/ansible/modules/network/cloudengine/ce_multicast_global.py
> +                # self.multicast_global_info['multicast_global'] has not value
Done

2019-10-27 07:07 UTC, xuxiaowei0512 commented
ready_for_review

2019-10-27 08:24 UTC, hwDCN commented
shipit

2019-10-27 08:26 UTC, yuandongxx approved these changes

2019-11-01 17:12 UTC, hwDCN commented
shipit

2019-11-26 11:22 UTC, merged