add a new module to configure multicast igmp and enable it.
ansible/ansible pull request #63746
Opened 2019-10-21 12:32 UTC by xuxiaowei0512

##### SUMMARY

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

lib/ansible/modules/network/cloudengine/ce_multicast_igmp_enable.py
##### ADDITIONAL INFORMATION

```paste below

```

2019-10-27 06:40 UTC, yuandongxx requested changes

2019-10-27 06:40 UTC, hwDCN commented on lib/ansible/modules/network/cloudengine/ce_multicast_igmp_enable.py
> +    required: false
required: false 
```suggestion
```

2019-10-27 06:40 UTC, hwDCN commented on lib/ansible/modules/network/cloudengine/ce_multicast_igmp_enable.py
> +    required: false
The same

2019-10-27 06:40 UTC, hwDCN commented on lib/ansible/modules/network/cloudengine/ce_multicast_igmp_enable.py
> +    required: false
the same

2019-10-27 06:40 UTC, hwDCN commented on lib/ansible/modules/network/cloudengine/ce_multicast_igmp_enable.py
> +    required: false
the same

2019-10-27 06:40 UTC, hwDCN commented on lib/ansible/modules/network/cloudengine/ce_multicast_igmp_enable.py
> +    required: false
the same

2019-10-27 06:40 UTC, hwDCN commented on lib/ansible/modules/network/cloudengine/ce_multicast_igmp_enable.py
> +  - name: config global igmp enable
```suggestion
  - name: configure global igmp enable
```

2019-10-27 06:40 UTC, hwDCN commented on lib/ansible/modules/network/cloudengine/ce_multicast_igmp_enable.py
> +  - name: config global igmp disable
```suggestion
  - name: configure global igmp disable
```

2019-10-27 06:40 UTC, hwDCN commented on lib/ansible/modules/network/cloudengine/ce_multicast_igmp_enable.py
> +  - name: config vlan igmp enable
```suggestion
  - name: configure vlan igmp enable
```

2019-10-27 06:40 UTC, hwDCN commented on lib/ansible/modules/network/cloudengine/ce_multicast_igmp_enable.py
> +    description: check to see if a change was made on the device
```suggestion
    description: check if a change was made on the device
```

2019-10-27 06:40 UTC, hwDCN commented on lib/ansible/modules/network/cloudengine/ce_multicast_igmp_enable.py
> +                    # self.igmp_info_data["igmp_info"] has not value
```suggestion
                    # igmp_info_data has not igmp_info value.
```

2019-10-27 06:40 UTC, hwDCN commented on lib/ansible/modules/network/cloudengine/ce_multicast_igmp_enable.py
> +                    # self.igmp_info_data["igmp_info"] has value
```suggestion
                    # self.igmp_info_data has no igmp_info value
```

2019-10-27 06:47 UTC, xuxiaowei0512 commented on lib/ansible/modules/network/cloudengine/ce_multicast_igmp_enable.py
> +    required: false
Done

2019-10-27 06:47 UTC, xuxiaowei0512 commented on lib/ansible/modules/network/cloudengine/ce_multicast_igmp_enable.py
> +    required: false
Done

2019-10-27 06:47 UTC, xuxiaowei0512 commented on lib/ansible/modules/network/cloudengine/ce_multicast_igmp_enable.py
> +    required: false
Done

2019-10-27 06:47 UTC, xuxiaowei0512 commented on lib/ansible/modules/network/cloudengine/ce_multicast_igmp_enable.py
> +    required: false
Done

2019-10-27 06:49 UTC, xuxiaowei0512 commented on lib/ansible/modules/network/cloudengine/ce_multicast_igmp_enable.py
> +  - name: config vlan igmp enable
Done

2019-10-27 06:49 UTC, xuxiaowei0512 commented on lib/ansible/modules/network/cloudengine/ce_multicast_igmp_enable.py
> +    description: check to see if a change was made on the device
Done

2019-10-27 06:50 UTC, xuxiaowei0512 commented on lib/ansible/modules/network/cloudengine/ce_multicast_igmp_enable.py
> +                    # self.igmp_info_data["igmp_info"] has not value
Done

2019-10-27 06:50 UTC, xuxiaowei0512 commented on lib/ansible/modules/network/cloudengine/ce_multicast_igmp_enable.py
> +                    # self.igmp_info_data["igmp_info"] has value
Done

2019-10-27 07:06 UTC, xuxiaowei0512 commented
ready_for_review

2019-10-27 08:23 UTC, yuandongxx approved these changes

2019-10-27 08:24 UTC, hwDCN commented
shipit

2019-11-01 17:11 UTC, hwDCN commented
shipit

2019-11-26 11:38 UTC, merged