Add ansible cli options --ask-vault-password and --vault-pass-file
ansible/ansible pull request #63782
Opened 2019-10-22 11:51 UTC by ivog74

##### SUMMARY
The ansible-playbook command provides 2 options to specify a vault password:
--ask-vault-pass
--vault-password-file

One option use 'pass', the other uses 'password'. I propose to use either pass or password for both option. For now I added the following options:
-- ask-vault-password
--vault-pass-file

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
ansible cli

##### ADDITIONAL INFORMATION

before:
```bash
ansible-playbook --ask-vault-pass ....
ansible-playbook --vault-password-file=<filename> ....
```

after:
```bash
ansible-playbook --ask-vault-password ....
ansible-playbook --vault-password-file=<filename> ....
```

or

```bash
ansible-playbook --ask-vault-pass ....
ansible-playbook --vault-pass-file=<filename> ....
```

2019-10-22 16:07 UTC, samdoran requested changes
Rather than adding additional calls to `add_argument()`, just add additional parameters to the existing `add_argument()` calls.

Also, please create a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment) and add integration tests to `test/integration/targets/vault`. See [this fragment](https://github.com/ansible/ansible/blob/c2f528b7686c9573aa8493357219e0bbe4416dd3/changelogs/fragments/reboot-change-default-boot-command.yaml) as an example.

2019-10-22 16:07 UTC, samdoran commented on lib/ansible/cli/arguments/option_helpers.py
>      base_group.add_argument('--ask-vault-pass', default=C.DEFAULT_ASK_VAULT_PASS, dest='ask_vault_pass', action='store_true',
```suggestion
     base_group.add_argument('--ask-vault-pass', '--ask-vault-password' default=C.DEFAULT_ASK_VAULT_PASS, dest='ask_vault_pass', action='store_true',
```

2019-10-22 16:07 UTC, samdoran commented on lib/ansible/cli/arguments/option_helpers.py
>      base_group.add_argument('--vault-password-file', default=[], dest='vault_password_files',
```suggestion
     base_group.add_argument('--vault-pass-file', '--vault-password-file', default=[], dest='vault_password_files',
```

2019-10-23 14:58 UTC, bcoca approved these changes

2019-10-23 20:41 UTC, samdoran requested changes
Please add integration tests.

2019-12-10 05:44 UTC, Akasurde commented
@ivog74 Are you still working on this? Thanks.

2019-12-10 12:59 UTC, ivog74 commented
> @ivog74 Are you still working on this? Thanks.

Hi @Akasurde, as far as I'm concerned this PR is finished. Do I still need to add something to the PR ?

2019-12-10 13:31 UTC, Akasurde commented
> Hi @Akasurde, as far as I'm concerned this PR is finished. Do I still need to add something to the PR ?
Could you please add integration test for this change [here](https://github.com/ansible/ansible/blob/devel/test/integration/targets/vault/runme.sh)?

2019-12-19 17:06 UTC, samdoran approved these changes

2019-12-19 17:07 UTC, merged