add option to use first 'HW' network interface IP address as ansible_…
ansible/ansible pull request #63875
Opened 2019-10-23 20:09 UTC by pito111

##### SUMMARY
Often, in case there is a virtual interface (e.g. from docker), vmware will assign IP address of that interface as default usually rendering the VM unaccessible. This is a simple workaround using first IP of first "physical" interface detected from VM configuration and filtered using MAC address. Additional IP network/address filter could be applied.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
vmware_inventory

2019-11-19 21:23 UTC, goneri requested changes
Hi @pito111 and thank you for the contribution. I put a couple of comments. It would also be great if you can update the functional test of the module. If you need help, please don't hesitate to ping us on IRC :-).

2019-11-19 21:23 UTC, goneri commented on contrib/inventory/vmware_inventory.py
> +            # minimum of 4 required for 'use_hw_if_as_host' to work. It will default to 4 in that case if set lower.
You should move this comment on top of the `use_hw_if_as_host` key.

2019-11-19 21:23 UTC, goneri commented on contrib/inventory/vmware_inventory.py
> +            # requires 'max_object_level': 4 (minimum) will check and set automatically if this is enabled.
The convention is to put the comment above the key.

2019-11-19 21:23 UTC, goneri commented on contrib/inventory/vmware_inventory.py
> +            # filter string to filter (start of) ip addresses for 'use_hw_if_as_host'
The same, please put the comment on top of the key.

2019-11-19 21:23 UTC, goneri commented on contrib/inventory/vmware_inventory.py
> +        # maxlevel >= 4 required for 'use_hw_if_as_host' to work
We don't need the comment again.

2019-11-19 21:23 UTC, goneri commented on contrib/inventory/vmware_inventory.py
> +        if config.get('vmware', 'use_hw_if_as_host').lower() == 'true' and self.maxlevel < 4:
I would prefer you just raise an error if `use_hw_if_as_host` is `true` and maxlevel < 4.

2019-11-19 21:23 UTC, goneri commented on contrib/inventory/vmware_inventory.py
> +    def create_host_mapping(self, inventory, pattern, use_hw_if='False', ip_filter="", dtype='string'):
This function is too complex. Could you please factor and avoid:
- more than 2 level of condition
- inner loop.
You can probably break down the function in several small functions.

2019-11-19 21:23 UTC, goneri commented on contrib/inventory/vmware_inventory.py
> +            'hw_if_ip_filter': '',
You should be more explicit here. How does this filter work? Does it exclude or include the IP? Does it filter IP or IF name?

2020-01-22 18:59 UTC, pito111 commented
Unfortunately I changed work and no longer have VMWare accessible to test this on so I would not feel confident the refactored code works. Does some sort of development version of vSphere exists?

2020-06-30 08:10 UTC, Akasurde commented
The inventory script is superseded by the inventory plugin. Please use [`vmware_vm_inventory`](https://github.com/ansible-collections/vmware/blob/master/plugins/inventory/vmware_vm_inventory.py) inventory plugin instead of `vmware_inventory`.

2020-06-30 08:10 UTC, closed without merging