Removes an obsolete fallback for Python 2.6 in wait_for.
ansible/ansible pull request #63988
Opened 2019-10-27 19:00 UTC by atombrella

##### SUMMARY

Removing some dead code due to Python 2.6 being the minimum.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
core

##### ADDITIONAL INFORMATION

2019-10-29 15:25 UTC, samdoran commented
Please create a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment). See [this fragment](https://github.com/ansible/ansible/blob/c2f528b7686c9573aa8493357219e0bbe4416dd3/changelogs/fragments/reboot-change-default-boot-command.yaml) as an example.

2019-10-29 18:54 UTC, atombrella commented
@samdoran Done. My branch is open if you want to re-phrase it.

2019-11-04 15:01 UTC, samdoran requested changes

2019-11-04 15:01 UTC, samdoran commented on changelogs/fragments/63988-removes-python_compat_fallback.yml
> +  - code - removes some Python compatibility code for dealing with socket timeouts in wait_for .
```suggestion
  - code - removes some Python compatibility code for dealing with socket timeouts in ``wait_for``
```

2019-11-04 15:01 UTC, samdoran commented on lib/ansible/modules/utilities/logic/wait_for.py
> +    return socket.create_connection((host, port), connect_timeout)
This function can be removed altogether. Change calls to `_create_connection()` to call `socket.create_connection()` directly.

2019-11-04 16:03 UTC, atombrella commented
@samdoran Thanks. Done :)

2019-11-04 16:38 UTC, samdoran approved these changes

2019-11-04 16:39 UTC, merged