Supporting SNMP Hosts Configurations in Ansible
ansible/ansible pull request #63983
Opened 2019-10-27 14:02 UTC by Sara-Touqan

##### SUMMARY

Supporting SNMP Hosts Configurations in Ansible

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

onyx_snmp_hosts
##### ADDITIONAL INFORMATION

```paste below
```
This module supports snmp configurations that are related to hosts.

2019-10-28 17:40 UTC, samerd requested changes
thanks @Sara-Touqan 
added some comments, please fix

2019-10-28 17:40 UTC, samerd commented on lib/ansible/modules/network/onyx/onyx_snmp_hosts.py
> +                         privacy_password=dict(type='str'),
add no_log=True to hide passwords

2019-10-28 17:40 UTC, samerd commented on lib/ansible/modules/network/onyx/onyx_snmp_hosts.py
> +    def generate_commands(self):
function is too complex.
try to split to smaller functions

2019-11-20 15:02 UTC, samerd approved these changes
Thanks @Sara-Touqan 
great job

2020-01-08 16:27 UTC, Qalthos commented
rebuild_merge

2020-01-08 16:51 UTC, merged