make sure current_pass_hash is a string before using it in comparison
ansible/ansible pull request #64059
Opened 2019-10-29 12:25 UTC by reduzent

##### SUMMARY
Fixes idempotency problem with mysql_user in python 3.7 that always reports changed even when nothing has actually changed.

Fixes #60567

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
mysql_user

##### ADDITIONAL INFORMATION
Playbook used for testing:
```
---
- hosts:
    - db1test
  tasks:
    - name: install mysql user
      mysql_user:
        name: testi
        password: testi
        host: localhost
        state: present
        update_password: always
```

Current output:
```
TASK [install mysql user] ******************************************
changed: [db1test] => {
    "changed": true,
    "user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
}

MSG:

Password updated (old style)
```

Output after the fix:
```
TASK [install mysql user] ***************************************
ok: [db1test] => {
    "changed": false,
    "user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
}

MSG:

User unchanged
```

2019-10-29 14:37 UTC, bmalynovytch commented
LGTM

+label needs_ci

2019-11-14 15:17 UTC, gundalow commented
@reduzent Thank you for this PR, your first to Ansible.
I was wondering if you could possible add a `changelog/fragment`, see https://docs.ansible.com/ansible/latest/community/development_process.html#making-your-pr-merge-worthy

2019-12-24 10:06 UTC, Andersson007 requested changes
hey, thanks for fixing this!

in general, we usually need:
1. CI tests. Add your own to test/integration/targets/mysql_user/tasks
2. A changelog fragment, see [here](https://docs.ansible.com/ansible/latest/community/development_process.html#changelogs) how to do it

then ping me for review
thanks!
needs_info

2020-01-14 14:21 UTC, reduzent commented
@gundalow: I just add added a changelogs/fragments file, as requested.

2020-01-24 10:56 UTC, Andersson007 commented
@reduzent , please close and reopen this to rerun CI tests (now labeled as ``stale_ci``)

2020-01-24 11:23 UTC, Andersson007 commented
if the tests are passed well, i think, we could merge this without CI
@bmalynovytch what do you think?

2020-01-24 12:20 UTC, reduzent commented
I temporarily close it.

2020-01-24 12:21 UTC, reduzent commented
I re-open it again.

2020-01-24 15:50 UTC, bmalynovytch commented
> if the tests are passed well, i think, we could merge this without CI
> @bmalynovytch what do you think?

LGTM 👍

2020-01-24 15:50 UTC, bmalynovytch approved these changes

2020-01-24 15:51 UTC, bmalynovytch commented
shipit

2020-01-24 17:43 UTC, Andersson007 commented
shipit

2020-01-24 17:44 UTC, Andersson007 approved these changes

2020-01-24 18:32 UTC, merged