clc_aa_policy: deprecate unused 'wait' parameter
ansible/ansible pull request #64367
Opened 2019-11-03 20:30 UTC by pilou-

##### SUMMARY

`clc_aa_policy`: deprecate unused `wait` parameter

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
clc_aa_policy

##### ADDITIONAL INFORMATION

```paste below

```

2019-11-08 11:27 UTC, tremble requested changes
Quick look at the code and its history seems to show it was never used.  Please add a porting_guide entry

2019-11-08 11:27 UTC, tremble commented on changelogs/fragments/clc_aa_policy-remove-unused-wait-parameter.yaml
> +  - "clc_aa_policy - The ``wait`` option had no effect and will be removed in Ansible 2.14"
Also needs an entry in the porting guide

2019-11-08 12:26 UTC, tremble approved these changes

2019-11-08 21:14 UTC, samccann approved these changes
docs portion LGTM

2019-11-18 22:26 UTC, acozine commented
rebuild_merge

2019-11-19 07:53 UTC, pilou- commented
@acozine PR rebased & updated (exception removed from `test/sanity/ignore.txt`)

2019-12-21 04:05 UTC, acozine commented
rebuild_merge

2019-12-21 04:46 UTC, merged