nxos_linkagg: removing unsupported parameter "provider" and "timeout" from sanity test
ansible/ansible pull request #64370
Opened 2019-11-04 03:39 UTC by nkshrishail

##### SUMMARY
Removing unsupported parameter "provider" and "timeout" from the sanity test for nxos_linkagg test module.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2019-11-04 13:17 UTC, chrisvanheuveln commented
shipit

2019-11-13 14:42 UTC, NilashishC requested changes
@nkshrishail removing `provider` would break integration tests, because we are still running against `ansible_connection=local` [here](https://github.com/ansible/ansible/blob/devel/test/integration/targets/nxos_linkagg/tasks/nxapi.yaml#L30).

2019-11-19 13:13 UTC, nkshrishail commented
@NilashishC , right, there is another PR coming in soon which will remove the support for local nxapi plugin and will also remove any references of local and also of provider. This one can be merged after the upcoming PR gets merged.

2019-11-21 19:42 UTC, mikewiebe commented
@nkshrishail Is this PR still valid since you have the larger PR that removes provider for all tests?  If it is still valid you need to make sure to remove the nxapi local block under `tasks/nxapi.yaml` for this test.

2019-11-21 19:55 UTC, nkshrishail commented
@mikewiebe yeah, it is, I have actually left out these files in the larger PR.

2020-01-08 08:14 UTC, NilashishC approved these changes

2020-01-08 08:15 UTC, merged