eos_l3interfaces: Add unit testcases to eos_l3_interfaces
ansible/ansible pull request #64400
Opened 2019-11-04 17:20 UTC by GomathiselviS

##### SUMMARY
Added unit testcases to eos_l3_interfaces

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME
test/units/modules/network/eos/fixtures/eos_l3_interfaces_config.cfg

2019-11-13 09:32 UTC, rohitthakur2590 commented on test/units/modules/network/eos/test_eos_l3_interfaces.py
> +        super(TestEosL2InterfacesModule, self).setUp()
L2  or L3 ?

2020-01-17 15:13 UTC, Qalthos requested changes

2020-01-17 15:13 UTC, Qalthos commented on test/units/modules/network/eos/test_eos_l3_interfaces.py
> +        super(TestEosL2InterfacesModule, self).setUp()
Should be L3, yeah

2020-08-20 08:38 UTC, Akasurde commented
Hi @GomathiselviS, Thank you very much for your interest in Ansible. This plugin/module is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/arista.eos<br><br>If you have further questions please stop by IRC or the mailing list:<br><br>* IRC: #ansible on irc.freenode.net<br>* mailing list: https://groups.google.com/forum/#!forum/ansible-project<br><br>needs_info<br>

2020-08-20 08:38 UTC, closed without merging

2020-08-20 08:39 UTC, Akasurde commented
Hi @GomathiselviS, Thank you very much for your interest in Ansible. This plugin/module is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/arista.eos<br><br>If you have further questions please stop by IRC or the mailing list:<br><br>* IRC: #ansible on irc.freenode.net<br>* mailing list: https://groups.google.com/forum/#!forum/ansible-project<br><br>needs_info<br>