Support static route commands
ansible/ansible pull request #64516
Opened 2019-11-06 14:11 UTC by anas-shami

Support static route commands:
- ip route
- ip route vrf
- ip routing
- ip routing vrf
- ip map-hostname
- ip host hostname
- ip mroute
- ip mroute vrf
- ip multicast-routing
- ip multicast-routing vrf

2019-11-20 16:10 UTC, anas-shami commented
@samerd please review

2019-11-20 17:53 UTC, samerd requested changes
Thanks @anas-shami 
please fix according to the comments

2019-11-20 17:53 UTC, samerd commented on lib/ansible/modules/network/onyx/onyx_static_route.py
> +            required_str = network_prefix + ' ' + netmask + ' ' + nexthop
```python
required_str = ' '.join((network_prefix, netmask, nexthop))
```

2019-11-20 17:53 UTC, samerd commented on lib/ansible/modules/network/onyx/onyx_static_route.py
> +                required_str = required_str + ' ' + str(route_distance)
use join or print formatting, much efficient than addition:
```python
required_str = '%s %s' % (required_str, route_distance)
```

2019-11-20 17:53 UTC, samerd commented on lib/ansible/modules/network/onyx/onyx_static_route.py
> +                required_str = required_str + ' ' + str(mroute_preference)
see above

2019-11-20 17:53 UTC, samerd commented on lib/ansible/modules/network/onyx/onyx_static_route.py
> +            - Assign multicast route prefernce (1-255)
add validation in the code

2019-11-20 17:53 UTC, samerd commented on lib/ansible/modules/network/onyx/onyx_static_route.py
> +    route_distance:
add distance range 1-255 and add validation in code

2019-12-15 14:24 UTC, anas-shami commented
@samerd  could you please check ?

2019-12-16 18:44 UTC, samerd approved these changes
Thanks @anas-shami 
looks great

2020-08-20 08:37 UTC, Akasurde commented
Hi @anas-shami, Thank you very much for your interest in Ansible. This plugin/module is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/mellanox.onyx<br><br>If you have further questions please stop by IRC or the mailing list:<br><br>* IRC: #ansible on irc.freenode.net<br>* mailing list: https://groups.google.com/forum/#!forum/ansible-project<br><br>needs_info<br>

2020-08-20 08:37 UTC, closed without merging