Don't return module error when mysql_connect fails (#64560)
ansible/ansible pull request #64585
Opened 2019-11-08 06:37 UTC by juergenhoetzel

mysql_user expects an Exception when using check_implicit_admin.

##### SUMMARY

Fixes ##64560

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME

- mysql_user module
- mysql_utils

##### ADDITIONAL INFORMATION

Fixes regression bug #64560 introduced with #55434 (which raises `module.fail_json` in utility function `mysql_connect`)

2019-11-08 07:24 UTC, Andersson007 requested changes
hello, @juergenhoetzel , thanks for fixing this
1. In the PR's title the ```postgresql_user``` module is mentioned but in the PR you changed ```mysql_info```
2. We need integration tests for this case which try to reproduce the situation when the wrong behavior occurs and check that all is ok after

2019-12-05 20:40 UTC, juergenhoetzel commented
> 
> 1. In the PR's title the `postgresql_user` module is mentioned but in the PR you changed `mysql_info`

Cant confirm that: title is about mysql  :thinking: 
> 2. We need integration tests for this case which try to reproduce the situation when the wrong behavior occurs and check that all is ok after

I just added a test and rebased.

2019-12-05 20:48 UTC, Andersson007 approved these changes
LGTM, thanks!
shipit

2019-12-05 20:53 UTC, nerijus commented
Please apply to 2.9 branch too, as it worked with 2.8.

2019-12-05 20:56 UTC, Andersson007 commented
@nerijus , wanted to mention it, you were faster :) thanks!
@juergenhoetzel see [here](https://docs.ansible.com/ansible/latest/community/development_process.html#backporting-merged-prs) how to do it. If you can't/have no time, let me know, i'll backport it

2019-12-05 21:03 UTC, Andersson007 commented
if they won't merge it today, i'll ping somebody directly tomorrow morning

2019-12-05 21:12 UTC, juergenhoetzel commented
> if they don't merge it today, i'll ping somebody directly tomorrow morning

I'm not mad at you for doing this :smile:  I am already half asleep.

2019-12-05 21:23 UTC, Andersson007 commented
ok, sorry for the late conversation) they said we need a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment) in order to merge it

2019-12-06 05:52 UTC, merged

2019-12-06 06:15 UTC, Andersson007 commented
added the changelog fragment https://github.com/ansible/ansible/pull/65594

2019-12-06 06:51 UTC, Andersson007 commented
@juergenhoetzel morning! i made the backport https://github.com/ansible/ansible/pull/65596.
So you don't need to do anything else for solving this, thank you!
Thank you guys all!

2019-12-06 07:39 UTC, juergenhoetzel commented
> @juergenhoetzel morning! i made the backport #65596.
> So you don't need to do anything else for solving this, thank you!
> Thank you guys all!

@Andersson007 Thank you so much for taking care of it.

I wasn't aware of the extra stable branch process.

You must have had a short night :fearful:

2019-12-06 09:39 UTC, Andersson007 commented
@julienstroheker just i tried to make the night shorter, the ansible development is really suitable for that :)

2019-12-06 11:53 UTC, misterunknown commented
Thank you guys @juergenhoetzel @Andersson007 for the fast fix! Saved me a lot of work :heart_eyes: