Improved message for unarchive.
ansible/ansible pull request #64594
Opened 2019-11-08 10:35 UTC by sbulage

Signed-off-by: Satyajit Bulage <sbulage@redhat.com>

##### SUMMARY

Added more verbose message to unarchive, trying to unarchive empty file.

##### ISSUE TYPE

- Bugfix Pull Request
Fixes: #44340
##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2019-11-08 11:24 UTC, Akasurde requested changes
cc @samccann @acozine Can you help here for more user friendly message ? Thanks.

2019-11-08 11:24 UTC, Akasurde commented on lib/ansible/modules/files/unarchive.py
> +        return False, 'Command "%s" could not unacrhive, archive file may be empty.' % self.cmd_path
```suggestion
        return False, 'Command "%s" found no files in archive. Empty archive files are not supported' % self.cmd_path
```

2019-11-08 12:40 UTC, sbulage commented on lib/ansible/modules/files/unarchive.py
> +        return False, 'Command "%s" could not unacrhive, archive file may be empty.' % self.cmd_path
okay

2019-11-09 04:28 UTC, Akasurde requested changes

2019-11-09 04:28 UTC, Akasurde commented on lib/ansible/modules/files/unarchive.py
> +        return False, 'Command "%s" found no files in archive. Empty archive files are not supported' % self.cmd_path
```suggestion
        return False, 'Command "%s" found no files in archive. Empty archive files are not supported.' % self.cmd_path
```

2019-11-09 06:23 UTC, sbulage commented on lib/ansible/modules/files/unarchive.py
> +        return False, 'Command "%s" found no files in archive. Empty archive files are not supported' % self.cmd_path
added/updated.

2019-11-10 04:22 UTC, sbulage commented
@Akasurde @ansibot CI failures are not related with the changes made in this PR.

2019-11-10 06:57 UTC, sbulage commented
@ansibot remove needs_revision

2019-11-12 20:12 UTC, samccann approved these changes
updated error message LGTM.

2019-11-14 14:47 UTC, gundalow commented
rebuild_merge

2019-11-15 07:22 UTC, Akasurde commented
CI failures are irrelevant to change. Merging.

2019-11-15 07:22 UTC, merged

2019-11-15 07:23 UTC, Akasurde commented
@sbulage Thanks for the contribution. @gundalow @samccann Thanks for the review.