eos_lag_interfaces : Add unit testcases to eos_lag_interfaces
ansible/ansible pull request #64616
Opened 2019-11-08 17:42 UTC by GomathiselviS

##### SUMMARY
Added unit testcases to eos_lag_interfaces

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME
lib/ansible/module_utils/network/eos/facts/lag_interfaces/lag_interfaces.py

2019-11-10 19:19 UTC, pabelanger commented
recheck

2020-01-17 18:00 UTC, Qalthos requested changes

2020-01-17 18:00 UTC, Qalthos commented on test/units/modules/network/eos/test_eos_lag_interfaces.py
> +    #    commands=['interface Ethernet1', 'no channel-group']
```suggestion
```

2020-01-17 18:00 UTC, Qalthos commented on test/units/modules/network/eos/test_eos_lag_interfaces.py
> +    # Bug #64615
Is this still applicable?

2020-08-20 08:38 UTC, Akasurde commented
Hi @GomathiselviS, Thank you very much for your interest in Ansible. This plugin/module is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/arista.eos<br><br>If you have further questions please stop by IRC or the mailing list:<br><br>* IRC: #ansible on irc.freenode.net<br>* mailing list: https://groups.google.com/forum/#!forum/ansible-project<br><br>needs_info<br>

2020-08-20 08:38 UTC, closed without merging