[WIP] Add mccabe complexity testing
ansible/ansible pull request #64623
Opened 2019-11-08 21:19 UTC by sivel

##### SUMMARY
Add mccabe complexity testing

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
test/

##### ADDITIONAL INFORMATION

```paste below

```

2019-11-11 14:55 UTC, sivel commented
When I merged the ignore.txt changes, and re-sorted the file it resulted in a lot of sorting based changes. It looks like only 509 new lines are actually added.

2019-11-11 15:47 UTC, mattclay commented
It may be a good idea to first merge a separate PR to sort the ignore file, so lines only need to be added in this PR.

2019-11-11 17:14 UTC, mattclay commented
One potential issue with enabling this test is that code which is almost over the limit is likely to either require a refactor (or an added ignore) when minor changes or bug fixes are applied, if those changes push the code over the limit.

2019-11-11 17:17 UTC, sivel commented
I don't think there is really anyway around that though. I'm not against adding an ignore in those cases if refactoring is outside the scope. The biggest problem I see is that our ignores are per file, unless it's done in code, rather than `ignore.txt`.

2019-11-11 17:19 UTC, mattclay commented
Yeah, there really isn't a way around it. I just wanted to point out one of the downsides to enabling this. I still think it's a good idea to add it.

2019-12-21 18:28 UTC, felixfontein commented
@sivel @mattclay how about having a sanity check which enforces that `ignore.txt` is sorted (in a canonical way)? Every time I work on a PR which involves updating `ignore.txt`, and I sort it after adding new entries, there are several changes which are only because of sorting. Also, I suspect that since sorting depends on locale and the sorting program used, different people sorting `ignore.txt` get different orders, which makes the problem worse. So having one canonical and enforced order should be helpful for everyone.

2019-12-23 09:04 UTC, tremble approved these changes
FWIW I like the addition of this test.  It certainly seems to be complaining about some pretty gnarly code in modules/cloud/amazon/.

In my opinion it would be helpful to have a way to manually *lower* the limit during things like initial reviews and reviews of "significant" code rewrites/refactors, this would reduce the risk of a minor change needing significant surgery to avoid an ignore.txt error.  My mind's heading in the direction of "ansible-test sanity --strict ....." which could do things like drop the complexity limit to 15 and testing for unused imports, where gating on them will likely result in more spam in ignore.txt than it's worth, but a human can use that added bit of judgement.

2019-12-23 17:14 UTC, sivel commented
> Also, I suspect that since sorting depends on locale and the sorting program used, different people sorting `ignore.txt` get different orders, which makes the problem worse

FWIW, I used python to sort the file, and it seems that python does not use the locale when sorting.  So a helper script, or something exposed through `ansible-test` might be useful.

2019-12-23 17:26 UTC, sivel commented
> In my opinion it would be helpful to have a way to manually _lower_ the limit during things like initial reviews

We might be expose an argument of `--max-complexity` when using `sanity` I suppose.

2020-01-07 22:13 UTC, mattclay commented
After reviewing some of the files that fail the new test, and thinking more about how this would get used, I'm not sure this is something we should be including in the standard sanity tests.

Up until this point we've done a good job of limiting sanity tests to very low false positives. There is very rarely a reason to add an ignore for a sanity test when adding new code or making changes. For the most part the tests are simply pass/fail and rarely report a fail when they should not.

The mccabe test is different since it provides a score for which there is no correct threshold. This will guarantee the need for ignore entries for valid code that should not, or in some cases, cannot be reasonably refactored to satisfy the test.

This kind of testing seems like it should be purely advisory, and only applied during code review, rather than a hard threshold that must be met or explicitly ignored.

2020-01-09 16:07 UTC, sivel commented
> The mccabe test is different since it provides a score for which there is no correct threshold

I suppose this is where it becomes subjective, like many other coding standard tests.  The best you can do is define a sane threshold, just like any other rule used in ensuring a quality of code.

The overall goal with complexity scoring is to add an indicator that the unit of code is too complex to be reliably tested.  Additionally, overly complex code can make it harder to read and reason about.  I know from experience what a high complexity level can do on writing tests, when working with something like `open_url` which weighs in at 31 right now.  I'd argue that they aren't false positives, and are in fact things that can be improved. They should not remain as ignores forever, although I cannot state that someone will ever go back and work on any old ignore.

If we don't have this run and report during CI, no one will ever run it, and we gain nothing.  I'll likely be one the few who ever looks at it, just as I am now.

2020-03-26 19:16 UTC, mattclay commented
This may be a good candidate for opt-in sanity test codes as proposed here: https://github.com/ansible/ansible/pull/66920#discussion_r398817968

2020-06-09 20:12 UTC, sivel commented
I've updated this PR to make `too-complex` an optional error.  The next commend will be hidden but will include the output, when using `--enable-optional-errors`.

2020-06-09 20:12 UTC, sivel commented
```
ERROR: Found 200 pylint issue(s) which need to be resolved:
ERROR: hacking/build_library/build_ansible/command_plugins/plugin_formatter.py:435:0: too-complex: 'process_plugins' is too complex. The McCabe rating is 29
ERROR: lib/ansible/cli/doc.py:144:4: too-complex: 'run' is too complex. The McCabe rating is 30
ERROR: lib/ansible/cli/doc.py:506:4: too-complex: 'add_fields' is too complex. The McCabe rating is 27
ERROR: lib/ansible/cli/doc.py:587:4: too-complex: 'get_man_text' is too complex. The McCabe rating is 23
ERROR: lib/ansible/cli/galaxy.py:499:4: too-complex: '_parse_requirements_file' is too complex. The McCabe rating is 21
ERROR: lib/ansible/cli/playbook.py:68:4: too-complex: 'run' is too complex. The McCabe rating is 24
ERROR: lib/ansible/cli/pull.py:151:4: too-complex: 'run' is too complex. The McCabe rating is 40
ERROR: lib/ansible/cli/scripts/ansible_cli_stub.py:57:0: too-complex: This 'if' is too complex. The McCabe rating is 26
ERROR: lib/ansible/config/manager.py:55:0: too-complex: 'ensure_type' is too complex. The McCabe rating is 28
ERROR: lib/ansible/config/manager.py:425:4: too-complex: 'get_config_value_and_origin' is too complex. The McCabe rating is 27
ERROR: lib/ansible/executor/interpreter_discovery.py:38:0: too-complex: 'discover_interpreter' is too complex. The McCabe rating is 21
ERROR: lib/ansible/executor/module_common.py:696:0: too-complex: 'recursive_finder' is too complex. The McCabe rating is 36
ERROR: lib/ansible/executor/module_common.py:989:0: too-complex: '_find_module_utils' is too complex. The McCabe rating is 31
ERROR: lib/ansible/executor/play_iterator.py:257:4: too-complex: '_get_next_task_from_state' is too complex. The McCabe rating is 36
ERROR: lib/ansible/executor/playbook_executor.py:75:4: too-complex: 'run' is too complex. The McCabe rating is 29
ERROR: lib/ansible/executor/task_executor.py:101:4: too-complex: 'run' is too complex. The McCabe rating is 31
ERROR: lib/ansible/executor/task_executor.py:278:4: too-complex: '_run_loop' is too complex. The McCabe rating is 25
ERROR: lib/ansible/executor/task_executor.py:519:4: too-complex: '_execute' is too complex. The McCabe rating is 60
ERROR: lib/ansible/galaxy/role.py:214:4: too-complex: 'install' is too complex. The McCabe rating is 43
ERROR: lib/ansible/module_utils/basic.py:310:0: too-complex: '_remove_values_conditions' is too complex. The McCabe rating is 21
ERROR: lib/ansible/module_utils/basic.py:1035:4: too-complex: 'set_mode_if_different' is too complex. The McCabe rating is 24
ERROR: lib/ansible/module_utils/basic.py:2194:4: too-complex: 'atomic_move' is too complex. The McCabe rating is 37
ERROR: lib/ansible/module_utils/basic.py:2383:4: too-complex: 'run_command' is too complex. The McCabe rating is 53
ERROR: lib/ansible/module_utils/compat/_selectors2.py:83:0: too-complex: This 'if' is too complex. The McCabe rating is 22
ERROR: lib/ansible/module_utils/compat/_selectors2.py:550:0: too-complex: This 'if' is too complex. The McCabe rating is 23
ERROR: lib/ansible/module_utils/facts/hardware/linux.py:159:4: too-complex: 'get_cpu_facts' is too complex. The McCabe rating is 39
ERROR: lib/ansible/module_utils/facts/hardware/linux.py:642:4: too-complex: 'get_device_facts' is too complex. The McCabe rating is 34
ERROR: lib/ansible/module_utils/facts/network/aix.py:53:4: too-complex: 'get_interfaces_info' is too complex. The McCabe rating is 27
ERROR: lib/ansible/module_utils/facts/network/linux.py:99:4: too-complex: 'get_interfaces_info' is too complex. The McCabe rating is 44
ERROR: lib/ansible/module_utils/facts/system/service_mgr.py:65:4: too-complex: 'collect' is too complex. The McCabe rating is 21
ERROR: lib/ansible/module_utils/facts/virtual/linux.py:36:4: too-complex: 'get_virtual_facts' is too complex. The McCabe rating is 59
ERROR: lib/ansible/module_utils/facts/virtual/sunos.py:33:4: too-complex: 'get_virtual_facts' is too complex. The McCabe rating is 28
ERROR: lib/ansible/module_utils/six/__init__.py:752:0: too-complex: This 'if' is too complex. The McCabe rating is 23
ERROR: lib/ansible/module_utils/urls.py:178:0: too-complex: This 'if' is too complex. The McCabe rating is 40
ERROR: lib/ansible/module_utils/urls.py:414:0: too-complex: This 'if' is too complex. The McCabe rating is 23
ERROR: lib/ansible/module_utils/urls.py:807:4: too-complex: 'get_ca_certs' is too complex. The McCabe rating is 23
ERROR: lib/ansible/module_utils/urls.py:1096:4: too-complex: 'open' is too complex. The McCabe rating is 31
ERROR: lib/ansible/modules/apt.py:438:0: too-complex: 'package_status' is too complex. The McCabe rating is 24
ERROR: lib/ansible/modules/apt.py:1014:0: too-complex: 'main' is too complex. The McCabe rating is 41
ERROR: lib/ansible/modules/blockinfile.py:193:0: too-complex: 'main' is too complex. The McCabe rating is 34
ERROR: lib/ansible/modules/copy.py:332:0: too-complex: 'chown_recursive' is too complex. The McCabe rating is 29
ERROR: lib/ansible/modules/copy.py:492:0: too-complex: 'main' is too complex. The McCabe rating is 72
ERROR: lib/ansible/modules/cron.py:535:0: too-complex: 'main' is too complex. The McCabe rating is 43
ERROR: lib/ansible/modules/dnf.py:879:4: too-complex: 'ensure' is too complex. The McCabe rating is 95
ERROR: lib/ansible/modules/file.py:662:0: too-complex: 'ensure_symlink' is too complex. The McCabe rating is 22
ERROR: lib/ansible/modules/file.py:765:0: too-complex: 'ensure_hardlink' is too complex. The McCabe rating is 28
ERROR: lib/ansible/modules/find.py:355:0: too-complex: 'main' is too complex. The McCabe rating is 25
ERROR: lib/ansible/modules/get_url.py:422:0: too-complex: 'main' is too complex. The McCabe rating is 43
ERROR: lib/ansible/modules/git.py:1043:0: too-complex: 'main' is too complex. The McCabe rating is 40
ERROR: lib/ansible/modules/lineinfile.py:253:0: too-complex: 'present' is too complex. The McCabe rating is 48
ERROR: lib/ansible/modules/pip.py:584:0: too-complex: 'main' is too complex. The McCabe rating is 39
ERROR: lib/ansible/modules/service.py:435:4: too-complex: 'get_service_tools' is too complex. The McCabe rating is 27
ERROR: lib/ansible/modules/service.py:669:4: too-complex: 'service_enable' is too complex. The McCabe rating is 56
ERROR: lib/ansible/modules/service.py:1163:4: too-complex: 'service_enable' is too complex. The McCabe rating is 23
ERROR: lib/ansible/modules/service_facts.py:95:4: too-complex: 'gather_services' is too complex. The McCabe rating is 23
ERROR: lib/ansible/modules/stat.py:432:0: too-complex: 'main' is too complex. The McCabe rating is 24
ERROR: lib/ansible/modules/systemd.py:321:0: too-complex: 'main' is too complex. The McCabe rating is 45
ERROR: lib/ansible/modules/sysvinit.py:117:0: too-complex: 'main' is too complex. The McCabe rating is 51
ERROR: lib/ansible/modules/unarchive.py:293:4: too-complex: 'is_unarchived' is too complex. The McCabe rating is 72
ERROR: lib/ansible/modules/uri.py:586:0: too-complex: 'main' is too complex. The McCabe rating is 38
ERROR: lib/ansible/modules/user.py:578:4: too-complex: 'create_user_useradd' is too complex. The McCabe rating is 28
ERROR: lib/ansible/modules/user.py:713:4: too-complex: 'modify_user_usermod' is too complex. The McCabe rating is 36
ERROR: lib/ansible/modules/user.py:989:4: too-complex: 'ssh_key_gen' is too complex. The McCabe rating is 21
ERROR: lib/ansible/modules/user.py:1260:4: too-complex: 'modify_user' is too complex. The McCabe rating is 35
ERROR: lib/ansible/modules/user.py:1488:4: too-complex: 'modify_user' is too complex. The McCabe rating is 26
ERROR: lib/ansible/modules/user.py:1661:4: too-complex: 'modify_user' is too complex. The McCabe rating is 24
ERROR: lib/ansible/modules/user.py:1796:4: too-complex: 'create_user' is too complex. The McCabe rating is 30
ERROR: lib/ansible/modules/user.py:1897:4: too-complex: 'modify_user_usermod' is too complex. The McCabe rating is 31
ERROR: lib/ansible/modules/user.py:2649:4: too-complex: 'modify_user' is too complex. The McCabe rating [...]

2020-06-10 17:47 UTC, mattclay commented on test/lib/ansible_test/_data/requirements/sanity.txt
> +mccabe
The sanity test files are now split up by sanity test, so this belongs here now:

https://github.com/ansible/ansible/blob/devel/test/lib/ansible_test/_data/requirements/sanity.pylint.txt

2020-06-10 17:52 UTC, sivel commented on test/lib/ansible_test/_data/requirements/sanity.txt
> +mccabe
done.

2020-06-11 18:16 UTC, mattclay approved these changes

2020-06-11 18:18 UTC, mattclay requested changes
Needs a changelog fragment. I'd also freeze the plugin version in the constraints file.

Other than that, it looks ready to merge.

2020-06-11 19:21 UTC, mattclay commented
CI failure are unrelated to changes.

2020-06-11 20:01 UTC, mattclay approved these changes

2020-06-11 20:02 UTC, merged