Supporting AAA Authentication configs in Ansible.
ansible/ansible pull request #64663
Opened 2019-11-11 09:41 UTC by Sara-Touqan

##### SUMMARY

Supporting AAA Authentication configs in Ansible.

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

onyx_aaa_authentication
##### ADDITIONAL INFORMATION

```paste below
This module supports the config params for aaa authentication.
```

2019-11-13 19:37 UTC, samerd requested changes
thanks @Sara-Touqan 
please see my review

2019-11-13 19:37 UTC, samerd commented on lib/ansible/modules/network/onyx/onyx_aaa_authentication.py
> +  auth_login_method1:
auth_login_methods should be an array (length 1 to 4)

2019-11-13 19:37 UTC, samerd commented on lib/ansible/modules/network/onyx/onyx_aaa_authentication.py
> +            auth_login_method1=dict(type='str', choices=['local', 'ldap', 'radius', 'tacacs+']),
define login methods constants

2019-11-13 19:37 UTC, samerd commented on lib/ansible/modules/network/onyx/onyx_aaa_authentication.py
> +            reset_for=dict(type='str', choices=['all', 'user']),
add relations between the reset parameter.
user_name is mandatory when reset_for is user

2019-11-13 19:37 UTC, samerd commented on lib/ansible/modules/network/onyx/onyx_aaa_authentication.py
> +    def validate_auth_params(self):
this validation can be done using spec relationships

2019-11-13 19:37 UTC, samerd commented on lib/ansible/modules/network/onyx/onyx_aaa_authentication.py
> +        if 'aaa authentication attempts track downcase' in curr_config_arr:
no need for another loop
you can check this in the previous loop

2019-11-13 19:37 UTC, samerd commented on lib/ansible/modules/network/onyx/onyx_aaa_authentication.py
> +            if auth_login_method4 is not None:
see above suggestion to use array of auth methods

2020-08-20 08:37 UTC, Akasurde commented
Hi @Sara-Touqan, Thank you very much for your interest in Ansible. This plugin/module is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/mellanox.onyx<br><br>If you have further questions please stop by IRC or the mailing list:<br><br>* IRC: #ansible on irc.freenode.net<br>* mailing list: https://groups.google.com/forum/#!forum/ansible-project<br><br>needs_info<br>

2020-08-20 08:37 UTC, closed without merging