parted: support fs_type
ansible/ansible pull request #64983
Opened 2019-11-18 09:16 UTC by rmunn

This is a rebase of #47879 to be based on the current state of the `devel` branch, since the original author of that PR hasn't rebased it in a while. If #47879 is merged, this PR can be safely closed.

2019-11-19 10:16 UTC, Akasurde requested changes

2019-11-19 10:16 UTC, Akasurde commented on lib/ansible/modules/system/parted.py
> +    version_added: '2.8'
```suggestion
    version_added: '2.10'
```

2019-11-19 10:17 UTC, Akasurde commented on lib/ansible/modules/system/parted.py
> +            'fs_type': {'default': 'ext4', 'type': 'str'},
```suggestion
            fs_type=dict(default='ext4', type='str'),
```

2019-11-19 10:18 UTC, Akasurde commented
!component =lib/ansible/modules/system/parted.py

2020-02-18 02:39 UTC, rmunn commented
@Akasurde Thanks for the review. Before I implement those changes, would you like to take a look at https://github.com/ansible/ansible/pull/47879? That's the original PR that I was simply rebasing; I'd rather see that one merged so that its author, not me, gets the credit. (He's since rebased it, and it appears to be ready to merge, including all the fixes that you requested here.)

2020-08-20 09:27 UTC, Akasurde commented
Hi @rmunn, Thank you very much for your interest in Ansible. This plugin/module is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.general<br><br>If you have further questions please stop by IRC or the mailing list:<br><br>* IRC: #ansible on irc.freenode.net<br>* mailing list: https://groups.google.com/forum/#!forum/ansible-project<br><br>needs_info<br>

2020-08-20 09:27 UTC, closed without merging