vmware_guest: Cloned machine's hostname is no longer updated
ansible/ansible pull request #65037
Opened 2019-11-19 07:17 UTC by ngp-star

##### SUMMARY
include fix for the issue https://github.com/ansible/ansible/issues/57873
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME
vmware_guest.py
##### ADDITIONAL INFORMATION
code changes done for bug raised under the issuehttps://github.com/ansible/ansible/issues/57873

2019-11-19 11:24 UTC, pgbidkar requested changes

2019-11-19 11:24 UTC, pgbidkar commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +                if key == 'type' and nw['type'] == 'dhcp':
Add this check inside if key not in ('device_type', 'mac', 'name', 'vlan', 'type', 'start_connected'): condition. Dont make it separate if block

2019-11-19 11:45 UTC, pgbidkar commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +                if key == 'type' and nw['type'] == 'dhcp':
Sorry, I misread the logic. Look good to me.

2019-11-19 11:45 UTC, pgbidkar commented
Hi @Akasurde , @goneri , Please review this change

Thanks

2019-11-19 19:31 UTC, goneri approved these changes

2019-11-21 11:34 UTC, ngp-star commented
@Akasurde @goneri  is there any update?

2019-11-25 06:13 UTC, ngp-star commented
@Akasurde 
can you just review this fix?

2019-11-28 11:13 UTC, merged