fix module that it reports the correct status of a change
ansible/ansible pull request #65098
Opened 2019-11-20 09:39 UTC by tcraxs

(cherry picked from commit 2028734ac334323aff4b9ac7289857e5f74bef53)

##### SUMMARY
`postgresql_privs` now reports the correct status of a change when using `type=default_privs`

"Fixes #64371 "

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
postgresql_privs

2019-11-20 21:27 UTC, samdoran commented
Hold off on merging this until we get #65125 merged in `devel`.

2019-11-20 23:27 UTC, samdoran commented
We need to add 426e37ea92 to this PR.

2019-11-21 04:32 UTC, Akasurde requested changes
Could you please include change https://github.com/ansible/ansible/commit/426e37ea92db037fe9367a6daa4d17622b1faf1d ? Thanks.

2019-11-21 09:03 UTC, tcraxs commented
@samdoran thanks for the info, I will include it :)

2019-11-21 09:52 UTC, Akasurde approved these changes
LGTM

2019-11-22 05:16 UTC, Andersson007 approved these changes
good job!
shipit

2019-11-25 10:50 UTC, Andersson007 commented
cc @nitzmahone @mattclay

2019-12-02 15:28 UTC, tcraxs commented
@samdoran @Akasurde can someone merge it please?

2019-12-02 15:53 UTC, Akasurde commented
> @samdoran @Akasurde can someone merge it please?

Since this is a backport PR, it will merged by release manager.

2019-12-03 23:46 UTC, mattclay commented
Why are there two backports this PR? It's much easier for RMs to review backports that have a 1:1 relationship with the original devel PR.

2019-12-04 02:11 UTC, merged

2019-12-10 13:55 UTC, tsacha commented
Hey, I had this error on Ansible 2.9.2 (it works on 2.9.1). Is this related?

`
{"attempts": 3, "changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/usr/lib/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_postgresql_privs_payload_gsems1r4/ansible_postgresql_privs_payload.zip/ansible/modules/database/postgresql/postgresql_privs.py\", line 1057, in <module>\n  File \"/tmp/ansible_postgresql_privs_payload_gsems1r4/ansible_postgresql_privs_payload.zip/ansible/modules/database/postgresql/postgresql_privs.py\", line 1038, in main\n  File \"/tmp/ansible_postgresql_privs_payload_gsems1r4/ansible_postgresql_privs_payload.zip/ansible/modules/database/postgresql/postgresql_privs.py\", line 752, in manipulate_privs\nTypeError: '<' not supported between instances of 'NoneType' and 'NoneType'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
`

Task:

```
    - name: Create permissions for {{ client }}
      postgresql_privs:
        db: '{{ client }}'
        roles: '{{ client }}'
        privs: ALL
        objs: ALL_IN_SCHEMA
      register: result
      retries: 3
      delay: 10
      until: result is not failed
      become: true
      become_user: postgres
```

2019-12-12 10:42 UTC, Andersson007 commented
@tsacha hey, probably yes and we need conditions there with .sort()
```
        executed_queries.append(query)
        self.cursor.execute(query)
        status_after = get_status(objs)
        status_before.sort()
        status_after.sort()
        return status_before != status_after
```
will see

2019-12-12 10:54 UTC, Andersson007 commented
@tsacha thanks for reporting this!
I created an issue https://github.com/ansible/ansible/issues/65761
If you can add anything else important, please, do it there, maybe any other ditailes which could be important to clerify the whole situation, see the issue's sections in desctiption as a hint.

2019-12-17 10:08 UTC, Andersson007 commented
https://github.com/ansible/ansible/pull/65903