import_tasks: Raise an error when applying notify
ansible/ansible pull request #65103
Opened 2019-11-20 11:18 UTC by Akasurde

##### SUMMARY

notify is not valid import_tasks attribute. Raise an error
when user specifies it.

Fixes: #64935

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE 
- Bugfix Pull Request

##### COMPONENT NAME
changelogs/fragments/64935_import_tasks.yml
lib/ansible/playbook/task_include.py

2019-11-26 16:16 UTC, s-hertel commented on lib/ansible/playbook/task_include.py
> +        if ds['action'] in ('import_tasks') and 'notify' in ds:
`register` is another keyword which is ignored for import_tasks.

2019-12-11 16:04 UTC, s-hertel reviewed
I took a more thorough look at this, and I kind of feel like we ought to go with a acceptlist like include_tasks and include_role because there are actually a lot of invalid keywords that just get ignored currently. Here are the valid keywords I found (you may want to double-check me):
* action
* any_errors_fatal
* args
* become
* become_exe
* become_flags
* become_method
* become_user
* check_mode
* collections
* connection
* debugger
* delegate_facts
* delegate_to
* diff
* environment
* ignore_errors
* ignore_unreachable
* module_defaults
* name
* no_log
* run_once
* tags
* throttle
* timeout
* vars
* when
* remote_user

Alternatively, we could go with a rejectlist in case there are keywords I missed that are valid (but this won't account for new keywords added that don't work with imports). Here are the invalid keywords I found (again, may want to double-check):
* async
* changed_when
* delay
* failed_when
* loop
* loop_args
* loop_control
* notify
* poll
* port
* register
* retries
* until

2020-04-22 06:27 UTC, rbellamy commented
@s-hertel greate comment, that should really be added to the `import_tasks` documentation.

2020-04-23 00:59 UTC, bcoca commented
we need similar lists for includes,  meta and 'other' tasks (debug, add_host, prompt, etc)

2020-07-13 16:04 UTC, Akasurde commented
@s-hertel Could you please take a look? I updated the logic and tested these combinations.

2020-07-13 21:18 UTC, s-hertel requested changes
Looks good. I went back over the lists of possible valid/invalid task level keywords and retested.

2020-07-13 21:18 UTC, s-hertel commented on lib/ansible/playbook/task_include.py
> +    VALID_IMPORT_KEYWORDS = VALID_KEYWORDS.union(frozenset(('become', 'check_mode', 'delegate_to', 'delegate_facts',
The other become-related options should be here too, right?

2020-07-13 21:18 UTC, s-hertel commented on lib/ansible/playbook/task_include.py
> +                                                            'remote_user')))
`any_errors_fatal`, `connection`, `throttle`, and `timeout` also seem valid for import_tasks

2020-07-14 14:55 UTC, bcoca commented
@Akasurde  actually, i think this needs to be a generic feature for all actions, not a bunch of hardcoded lists.

so first, this should be reflected in the docs:
https://github.com/ansible/proposals/issues/68

2nd, we should use this 'per action' list to warn the user.

2021-02-11 19:53 UTC, bcoca commented on lib/ansible/playbook/task_include.py
> +    VALID_IMPORT_KEYWORDS = VALID_KEYWORDS.union(frozenset(('become', 'check_mode', 'delegate_to', 'delegate_facts',
instead of keeping track manually, we should just query 'block' class for allowed keywords.

2021-05-26 14:03 UTC, closed without merging