find_file_in_search_path: early return if absolute path provided
ansible/ansible pull request #65172
Opened 2019-11-22 08:44 UTC by cjeanner

##### SUMMARY
This small change allows to get an early return without the need to
actually search for the file.

It still performs a search in case of a non-existing file, in order
to stay compliant with the current way things are running.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME

lookup

2019-11-28 09:09 UTC, cjeanner commented
hmm, failure isn't due to the patch apparently:
```
"Curl error (28): Timeout was reached for https://download.docker.com/linux/fedora/docker-ce.repo [Operation timed out after 30001 milliseconds with 0 out of 0 bytes received]",
```

2019-12-05 19:21 UTC, jborean93 requested changes
Are you able to add a changelog fragment with `minor_changes` as documented at https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment.

Also having a test will ensure this functionality is not removed in the future.

2021-05-30 13:05 UTC, Akasurde commented
@cjeanner Are you still working on this, let us know? Thanks,

needs_info

2021-06-01 12:23 UTC, cjeanner commented
hey @Akasurde - sorry for the (long...) delay - I was side-tracked on other things.
I still think this change is needed - so I'll try to find some time this week in order to rebase it, and push the needed changes (release note + tests).

2021-06-01 14:44 UTC, bcoca commented
same shortcut already exists in path_dwim_relative_stack, this just saves us 1 if so i didn't consider adding it at the time.

2021-06-01 14:47 UTC, cjeanner commented
> same shortcut already exists in path_dwim_relative_stack, this just saves us 1 if so i didn't consider adding it at the time.

does it means this patch is irrelevant then, @bcoca ? If it saves only one recursion or search, it's probably not worth the effort.

2021-06-01 14:53 UTC, bcoca commented
i would not say completely irrelevant, but ... close

2021-06-02 05:59 UTC, cjeanner commented
'k, so if such a shortcut exists, guess we can just close this patch. Probably not worth the whole thing.

2021-06-02 05:59 UTC, closed without merging