Fix to  - eos_lag_interfaces: Port-channel getting removed
ansible/ansible pull request #65210
Opened 2019-11-22 23:11 UTC by GomathiselviS

##### SUMMARY
Fix to #64615

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
lag_interfaces.py

2019-11-23 01:35 UTC, GomathiselviS commented
recheck

2020-01-14 16:21 UTC, Qalthos requested changes

2020-01-14 16:21 UTC, Qalthos commented on test/integration/targets/eos_lag_interfaces/tests/cli/deleted.yaml
> +      - "ansible_facts.network_resources.lag_interfaces|symmetric_difference(expected_config)|length == 0"
```suggestion
      - "ansible_facts.network_resources.lag_interfaces|symmetric_difference(expected_config) == []"
```

2020-01-14 16:21 UTC, Qalthos commented on test/integration/targets/eos_lag_interfaces/tests/cli/overridden.yaml
> +      - "ansible_facts.network_resources.lag_interfaces|symmetric_difference(expected_config)|length == 0"
```suggestion
      - "ansible_facts.network_resources.lag_interfaces|symmetric_difference(expected_config) == []"
```

2020-01-14 16:21 UTC, Qalthos commented on test/integration/targets/eos_lag_interfaces/tests/cli/deleted.yaml
> +- include_tasks: _reset_config.yml
I'm confused by what's going on here... you've added a file named `reset_config.yaml`, but including `_reset_config.yml`?

2020-01-14 16:21 UTC, Qalthos commented on test/integration/targets/eos_lag_interfaces/tests/cli/reset_config.yaml
> +      - "ansible_facts.network_resources.lag_interfaces|symmetric_difference(expected_config)|length == 0"
```suggestion
      - "ansible_facts.network_resources.lag_interfaces|symmetric_difference(expected_config) == []"
```

2020-06-17 14:12 UTC, GomathiselviS commented
This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/arista.eos


IRC: #ansible-network on irc.freenode.net
mailing list: https://groups.google.com/forum/#!forum/ansible-project

2020-06-17 14:12 UTC, closed without merging