Flip p=/u= marker data
ansible/ansible pull request #65218
Opened 2019-11-23 17:44 UTC by msaladna

##### SUMMARY

PR #56311 standardizes logging per Python best practices. The changes implemented flipped user/pid data for u= and p= markers, which breaks context-specific pattern matches in the logfile. This PR restores the context associations prior to a7837edcf26e1e8542109952a9117e145c4cba1d.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

`lib/ansible/utils/display.py`

##### ADDITIONAL INFORMATION

```paste below
env ANSIBLE_LOG_PATH=/tmp/ansible-log.txt ansible -m debug -a msg=Hello localhost
cat /tmp/ansible-log.txt
```
**Incorrect logging format**:
```
2019-11-23 12:39:12,543 p=root u=10058 | localhost | SUCCESS => {
    "msg": "Hello"
}
```

**Corrected logging format**:
```
2019-11-23 12:42:44,342 p=10349 u=root | localhost | SUCCESS => {
    "msg": "Hello"
}
```

2019-12-03 19:57 UTC, chilicheech commented on lib/ansible/utils/display.py
> +        logging.basicConfig(filename=path, level=logging.INFO, format='%(asctime)s p=%(process)d u=%(user)s | %(message)s')
Where do you get `%(user)s`? According to the documentation that key doesn't exist: https://docs.python.org/3/library/logging.html#logrecord-attributes

Using `%(user)s` gives me the following error:
```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 580, in format
    s = self.formatMessage(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 549, in formatMessage
    return self._style.format(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 391, in format
    return self._fmt % record.__dict__
KeyError: 'user'
```

2019-12-05 19:30 UTC, jborean93 requested changes
Can you add a changelog fragment to this as documented at https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment. This will help other users see what has changed in newer versions.

Also please ping us in IRC once done so we don't loose track of this.

2019-12-05 23:57 UTC, jborean93 commented
Just an FYI, I did the same swap in another PR which is meant to fix up another bug in https://github.com/ansible/ansible/pull/65582. I was working on the code at the same time and thought it best to just do it in 1 go.

2019-12-06 19:28 UTC, msaladna commented
You got it. Submitted a changelog 👍

2019-12-06 19:38 UTC, sivel commented
Superseded by https://github.com/ansible/ansible/pull/65582

2019-12-06 19:38 UTC, closed without merging