Added required parameter to document DOC-string to produce Documentation.
ansible/ansible pull request #65230
Opened 2019-11-24 10:56 UTC by sbulage

Signed-off-by: Satyajit Bulage <sbulage@redhat.com>

##### SUMMARY

Fixes #64654

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

template and win_template

2019-11-24 11:02 UTC, sbulage commented
cc @acozine

2019-12-01 20:22 UTC, jborean93 requested changes

2019-12-01 20:22 UTC, jborean93 commented on lib/ansible/modules/windows/win_template.py
> +short_description: Create file from template or Backup given file.
Should just be what was on the original `short_description` in the template_common file.

2019-12-01 20:22 UTC, jborean93 commented on lib/ansible/modules/files/template.py
> +short_description: Create a files and directories by using templates.
SHould just be what was on the original `short_description` in the template_common file.

2019-12-01 20:22 UTC, jborean93 commented on lib/ansible/plugins/doc_fragments/template_common.py
> +- Template a file out to a remote server.
I don't think this is needed, seems like we just need to remove `short_description` here and just duplicate it across to `template.py` and `win_template.py`.

2019-12-04 19:52 UTC, jborean93 approved these changes

2019-12-04 20:09 UTC, jborean93 commented
I've pushed the requested changes so we can merge this in and get the issue fixed.

2019-12-04 20:23 UTC, merged

2019-12-04 20:25 UTC, jborean93 commented
Backport PR to stable-2.9 https://github.com/ansible/ansible/pull/65518