Add PVLAN support - fixes #47649
ansible/ansible pull request #65256
Opened 2019-11-25 16:17 UTC by OnceUponALoop

##### SUMMARY
Adds support for pvlan assignment to portgroups.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
vmware_dvs_portgroup

##### ADDITIONAL INFORMATION
I added the flag `vlan_pvlan` to mimic the existing `vlan_trunk` flag.

A better fix would be to create a `vlan_type` flag and allow it to be either `trunk` or `pvlan` but that would break existing configuration and I didn't want to make that decision

2019-11-25 18:14 UTC, mariolenz commented
Thanks for this contribution! At first glance it looks good to me. Just two things:

1) You should check if `vlan_pvlan` differs from the current configuration which is done in the method `check_dvspg_state`. This will allow people to change from a non-private VLAN to a private one and vice versa.
2) I think you can't have a private VLAN trunk so you should probably define `vlan_pvlan` and `vlan_trunk` as `mutually_exclusive`. Just grep for this in the VMware modules and you should find an example how this can be done.

Oh, and I guess the ansible team will want to have a [changelog fragment](https://docs.ansible.com/ansible/2.9/community/development_process.html#changelogs-how-to). I think something like this would be a `minor_changes`.

2019-11-26 03:51 UTC, OnceUponALoop commented
@mariolenz 
Thanks for the assist - I rushed the PR and should've considered both suggestions - good to go now, added them as suggested, added the changelog fragment, and tested.

2019-12-06 20:54 UTC, goneri requested changes
Thanks @OnceUponALoop for the contribution. Could you extend the functional test to cover the new feature? The test playbook is here: https://github.com/ansible/ansible/blob/devel/test/integration/targets/vmware_dvs_portgroup/tasks/main.yml

Thanks :-)

2020-01-23 10:16 UTC, Akasurde commented
@OnceUponALoop Could you please add a test case for this change? Thanks.

needs_info

2020-02-07 17:37 UTC, mariolenz commented
@OnceUponALoop maybe you can join forces with @axarriola who issued the similar PR #67205.

2020-03-26 18:47 UTC, closed without merging