cloud/openstactack: adds qos_policy and qos_policy_rule for OpenStack
ansible/ansible pull request #65292
Opened 2019-11-26 17:39 UTC by DSpeichert

##### SUMMARY
These two modules allow for the management of QoS policies and their rules in OpenStack (Neutron).

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
openstack
os_qos_policy
os_qos_policy_rule

##### ADDITIONAL INFORMATION
Like other OpenStack modules in Ansible, it uses `openstacksdk` dependency and typical "boilerplate" conventions from other modules. I used existing `os_subnet` as an example to structure this module.

It works to the best of my knowledge. I haven't found tests in Ansible for other OpenStack modules (besides simple os_server unit test). I'm not sure if it's feasible and required for these modules to write something.

I am also unclear on what the Copyright headers should be. I kept the ones from the files I copied as example. I've noticed that other modules in `cloud/openstack` have different "Author" in `DOCUMENTATION` and different Copyright headers.

2019-12-23 06:29 UTC, tremble requested changes

2019-12-23 06:29 UTC, tremble commented on test/sanity/ignore.txt
> +lib/ansible/modules/cloud/openstack/os_qos_policy.py validate-modules:undocumented-parameter
You accept 'availability_zone' as a parameter (it comes from openstack_full_argument_spec) so it should be documented.

I'm surprised it's not included in the fragment ( ./lib/ansible/plugins/doc_fragments/openstack.py ).  But this certainly shouldn't be grounds for an entry in ignore.txt

2020-01-20 13:47 UTC, sshnaidm commented
Thanks for submitting patch for Openstack Ansible modules!
We moved Openstack Ansible modules to Openstack repositories.
Next patches should be submitted not with Ansible Github but with
Openstack Gerrit: https://review.opendev.org/#/q/project:openstack/ansible-collections-openstack
Please submit your code there from now.
Thanks for your contribution and sorry for inconvienience.

2020-01-21 08:11 UTC, sshnaidm requested changes
Because we moved Openstack Ansible modules to Openstack repositories, please submit all changes from openstack modules to Openstack Gerrit: https://review.opendev.org/#/q/project:openstack/ansible-collections-openstack Thanks for your contribution and sorry for inconvienience.

2020-08-19 10:31 UTC, Akasurde commented
@DSpeichert Thanks for the contribution. Closing as per above.

2020-08-19 10:31 UTC, closed without merging