Adds ipa_pwpolicy module
ansible/ansible pull request #65321
Opened 2019-11-27 10:49 UTC by b1czu

##### SUMMARY

This PR adds an ipa_pwpolicy module which allows to manage IPA Password Policies.

Fixes #65319 
##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

We did not have a ipa_pwpolicy module, so here's one! Borrowed a lot from @fxfitz's work (thanks! made it much easier).

2019-12-11 11:09 UTC, b1czu commented
ready_for_review

2020-01-03 06:26 UTC, Akasurde requested changes
Rest LGTM

2020-01-03 06:26 UTC, Akasurde commented on lib/ansible/modules/identity/ipa/ipa_pwpolicy.py
> +- Add, delete and modify an IPA Password Policies using IPA API. Ommited values are not changed during module execution.
```suggestion
- Add, delete and modify an IPA Password Policies using IPA API.
- Omitted values are not changed during module execution.
```

2020-01-03 06:26 UTC, Akasurde commented on lib/ansible/modules/identity/ipa/ipa_pwpolicy.py
> +    description: Priority of the policy (higher number means lower priority). Ignored if group=global_policy
```suggestion
    description:
    - The priority of the policy (higher number means lower priority).
    - Ignored if C(group=global_policy).
```

2020-01-03 06:26 UTC, Akasurde commented on lib/ansible/modules/identity/ipa/ipa_pwpolicy.py
> +    description: State to ensure
```suggestion
    description: State to ensure.
```

2020-01-03 06:26 UTC, Akasurde commented on lib/ansible/modules/identity/ipa/ipa_pwpolicy.py
> +  type: dict
add a sample here - 

```
sample: {
	...
}
``

2020-01-05 04:51 UTC, Akasurde commented
> ```
> lib/ansible/modules/identity/ipa/ipa_pwpolicy.py:0:0: doc-required-mismatch: Argument 'ipa_pass' in argument_spec is not required, but is documented as being required
> ```

Fixed in https://github.com/ansible/ansible/pull/66194

2020-01-14 10:29 UTC, b1czu commented
ready_for_review

2020-02-23 21:47 UTC, b1czu commented
bot_status

2020-08-16 00:01 UTC, closed without merging