VMware: new module vmware_network_protocol_profile
ansible/ansible pull request #65327
Opened 2019-11-27 15:30 UTC by vishvarath

this library help adding and removing network protocol profile from vcenter.

##### SUMMARY

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2019-12-06 20:45 UTC, goneri requested changes
Thank you for your patch @vishvarath and welcome in the community :-). It looks pretty good to me. However, we cannot accept a new module without any functional test.

Please see: https://docs.ansible.com/ansible/latest/dev_guide/platforms /vmware_guidelines.html#functional-tests

If you have any question, you can also ask on #ansible-vmware.

2019-12-06 20:45 UTC, goneri commented on lib/ansible/modules/cloud/vmware/vmware_network_protocol_profile.py
> +    - "python >= 2.6"
Please bump it to 2.7. This is the oldest version of Python supported by Pyvmomi.

2020-01-20 06:25 UTC, Akasurde requested changes
Could you please add an integration test for this change? Thanks.

2020-01-20 06:25 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_network_protocol_profile.py
> +# Copyright: (c) 2019, Vishvarath Nayak vishvarath@gmail.com
```suggestion
# Copyright: (c) 2019, Vishvarath Nayak <vishvarath@gmail.com>
```

2020-01-20 06:25 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_network_protocol_profile.py
> +#from typing import Optional, Any
Remove this line if not required.

2020-01-20 06:25 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_network_protocol_profile.py
> +short_description: create/remove network_protocol_profile to/from vCenter
```suggestion
short_description: create, remove network_protocol_profile to and from vCenter
```

2020-01-20 06:25 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_network_protocol_profile.py
> +    - This module can be used to add/remove an IP Pool to/from vCenter
```suggestion
    - This module can be used to add or remove an IP Pool to and from vCenter
```

2020-01-20 06:25 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_network_protocol_profile.py
> +- Vishvarath Nayak
```suggestion
- Vishvarath Nayak (@vishvarath)
```

2020-01-20 06:25 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_network_protocol_profile.py
> +instance:
Use an informative key instead of `instance` for example `network_protocol_profile_info`

2020-01-20 06:25 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_network_protocol_profile.py
> +    sample: None
It would be great to see an example rather than just None

2020-01-20 06:25 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_network_protocol_profile.py
> +class vmware_network_protocol_profile(object):
```suggestion
class vmware_network_protocol_profile(Pyvmomi):
```

2020-01-20 06:25 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_network_protocol_profile.py
> +from ansible.module_utils.vmware import get_all_objs, connect_to_api, vmware_argument_spec, find_datacenter_by_name, find_dvs_by_name, find_dvspg_by_name
```suggestion
from ansible.module_utils.vmware import PyVmomi, get_all_objs, vmware_argument_spec, find_datacenter_by_name, find_dvs_by_name, find_dvspg_by_name
```

2020-01-20 06:25 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_network_protocol_profile.py
> +        self.content = connect_to_api(module)
Use `Pyvmomi` class, just like other Vmware modules.

2020-01-20 06:25 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_network_protocol_profile.py
> +    def get_obj(self, vimtype, name, return_all=False):
Use existing methods from `module_utils/vmware.py`

2020-01-20 06:25 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_network_protocol_profile.py
> +            ippool_states = {
Dict can be defined outside try block

2020-01-20 06:25 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_network_protocol_profile.py
> +            self.module.fail_json(msg=str(e))
```suggestion
            self.module.fail_json(msg=to_native(e))
```

2020-01-20 06:25 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_network_protocol_profile.py
> +        result = None
```suggestion

```

2020-01-20 06:25 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_network_protocol_profile.py
> +        IpPool_assoc = vim.vApp.IpPool.Association()
```suggestion
        ip_pool_assoc = vim.vApp.IpPool.Association()
```

2020-01-20 06:25 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_network_protocol_profile.py
> +        IpPool_data = vim.vApp.IpPool()
```suggestion
        ip_pool_data = vim.vApp.IpPool()
```

2020-01-20 06:25 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_network_protocol_profile.py
> +                self.ip_pool_obj = i
What happens if we have multiple IP pool with same name. In the past, we have seen a lot of issues due to the same name objects.

2020-01-20 06:25 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_network_protocol_profile.py
> +	validate_certs=dict(required=False, type='bool'),
Mix tab and spaces in identation.

2020-01-20 06:25 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_network_protocol_profile.py
> +    - PyVmomi
Could you please add documentation for all the parameters, their description, use, datatypes etc.?

2020-08-16 00:01 UTC, closed without merging