Suppress warning for user directory(~)
ansible/ansible pull request #65344
Opened 2019-11-28 06:12 UTC by sbulage

Signed-off-by: Satyajit Bulage <sbulage@redhat.com>

##### SUMMARY

Warning is given when `(~)` user directory is used `--playbook-dir` path.
Fixed #65262 
##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

loader
##### ADDITIONAL INFORMATION

```paste below
ansible-inventory -i inventory --list --export --playbook-dir=~/invet_dir/
{
    "_meta": {
        "hostvars": {
            "192.168.122.139": {
                "ansible_ssh_user": "root"
            }
        }
    }, 
    "all": {
        "children": [
            "ungrouped"
        ]
    }, 
    "ungrouped": {
        "hosts": [
            "192.168.122.139"
        ]
    }
}

```

2019-11-28 06:14 UTC, sbulage commented
Please review the fix. @AlanCoding @Akasurde

2019-11-28 09:13 UTC, Akasurde requested changes

2019-11-28 09:13 UTC, Akasurde commented on lib/ansible/plugins/loader.py
>      b_path = to_bytes(path, errors='surrogate_or_strict')
```suggestion
     b_path = os.path.expanduser(to_bytes(path, errors='surrogate_or_strict'))
```

2019-11-28 09:13 UTC, Akasurde commented on lib/ansible/plugins/loader.py
>      b_path = to_bytes(path, errors='surrogate_or_strict')
Could you please add a changelog entry for this change? Also, test for this change would be good to have.

2019-12-02 13:38 UTC, AlanCoding commented
👍 removes the warning as I reported in the issue, comparing `devel` branch to running same command after checking out this branch.

2019-12-25 15:46 UTC, Akasurde commented
@sbulage ping.

2019-12-26 04:28 UTC, sbulage commented
Yes @akasurde

2020-07-02 12:51 UTC, Akasurde commented
rebuild_merge

2020-07-02 20:22 UTC, merged