On OpenBSD, use the actual number of online CPUs for facts
ansible/ansible pull request #65370
Opened 2019-11-29 15:19 UTC by jasperla

This switches to use hw.ncpuonline instead of hw.ncpu when
showing the number of cpus/cores in the system

##### SUMMARY

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
`setup` module

##### ADDITIONAL INFORMATION
In OpenBSD it's possible to disable SMT since release 6.4 as such the number of detected physical CPUs/cores with `hw.ncpu` may not actually be the number of CPUs/cores which are in use. The `hw.ncpuonline` sysctl value does correctly reflect that.

I think it makes sense to switch to using this value instead of `hw.ncpu`.

2019-12-13 22:02 UTC, samdoran requested changes
This seems like a reasonable change. I tested on OpenBSD 6.6 and it works.

Please create a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment). See [this fragment](https://github.com/ansible/ansible/blob/c2f528b7686c9573aa8493357219e0bbe4416dd3/changelogs/fragments/reboot-change-default-boot-command.yaml) as an example.

We do not have any unit tests for `openbsd.by` currently. Would you be able to write unit tests to at cover this method?

2019-12-13 22:05 UTC, samdoran commented
I am not a BSD user, so one thing I'm wondering is if changing this will result in any surprises or if it will be ok since it's correcting an inaccurate count. Should we leave the the current `processor_cores` and `processor_count` untouched and add new fields such as `enabled_cores` and `enabled_count`, or does it just make sense to change this to only reflect the enabled count?

2019-12-13 22:39 UTC, grayed commented
@samdoran, I'm not a Linux user (no kidding). Looks like the 'process_cores' is filled from '# processors' line in /proc/cpuinfo. Does the '# processors' change upon disabling hyperthreading? If yes then (I suppose) on OpenBSD it should change, too; if not then not. Same logic applies for 'processor_count'.

2019-12-16 16:02 UTC, samdoran commented
@grayed On Linux, disabling hyperthreading does not reduce the physical core count but does reduce the number of CPUs

Comparison of `lscpu`
```
with-ht.txt
CPU(s):                40
Thread(s) per core:    2
Core(s) per socket:    10

without-ht.txt
CPU(s):                20
Thread(s) per core:    1
Core(s) per socket:    10
```

Comparison of facts
```
with-ht-facts.txt
        "ansible_processor_cores": 10,
        "ansible_processor_count": 2,
        "ansible_processor_vcpus": 40

without-ht-facts.txt
        "ansible_processor_cores": 10,
        "ansible_processor_count": 2,
        "ansible_processor_vcpus": 20
```

2022-05-04 15:10 UTC, bcoca commented
waiting_on_contributor

2023-05-17 12:55 UTC, closed without merging