Add FileStorage and BlockBlobStorage for kind
ansible/ansible pull request #65535
Opened 2019-12-05 03:34 UTC by Fred-sun

##### SUMMARY

Add FileStorage and BlockBlobStorage account for kind option. try to fix #65481 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

azure_rm_storageaccount
##### ADDITIONAL INFORMATION

```paste below

```

2019-12-05 05:01 UTC, Fred-sun commented
ready_for_review

2019-12-17 15:30 UTC, Ackak12 requested changes
Can we make it conditional so that if account type is Premium_LRS then only the FileStorage and BlockBlobStorage options can be selected else it will throw error from API?

2019-12-18 02:55 UTC, Fred-sun commented
> Can we make it conditional so that if account type is Premium_LRS then only the FileStorage and BlockBlobStorage options can be selected else it will throw error from API?

@Ackak12 Thanks for your comments! Do you mean the errors are as follows?

```e.g.
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Parameter error: storage account BlockBlobStorage require account type is Premium_LRS"}

2019-12-23 16:51 UTC, Ackak12 commented
> > Can we make it conditional so that if account type is Premium_LRS then only the FileStorage and BlockBlobStorage options can be selected else it will throw error from API?
> 
> @Ackak12 Thanks for your comments! Do you mean the errors are as follows?
> 
> ```
> fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Parameter error: storage account BlockBlobStorage require account type is Premium_LRS"}
> ```

Hi @Fred-sun, You are correct. Please add this to the code and try to merge it to Master. We need this in our latest project.

2020-01-17 02:10 UTC, Fred-sun commented
ready_for_review

2020-01-17 07:38 UTC, Ackak12 approved these changes

2020-01-17 09:16 UTC, Ackak12 commented
Hi,
Could someone approve and help to merge this PR?

2020-02-05 08:37 UTC, Fred-sun commented
@gavinfish @haiyuazhang

2020-02-06 07:44 UTC, gavinfish commented on lib/ansible/modules/cloud/azure/azure_rm_storageaccount.py
> +    - name: create an account with kind of FileStorage
This sample misses the `kind` property for FileStorage.

2020-02-06 07:44 UTC, gavinfish commented on lib/ansible/modules/cloud/azure/azure_rm_storageaccount.py
> +            self.fail("Parameter error: storage account {0} require account type is Premium_LRS".format(self.kind))
```suggestion
            self.fail("Parameter error: storage account with {0} kind requires account type is Premium_LRS".format(self.kind))
```

2020-02-06 08:58 UTC, gavinfish approved these changes
shipit

2020-03-10 02:03 UTC, Fred-sun commented
ping to merge!

2020-03-16 03:48 UTC, Fred-sun commented
This PR has been migrated to [#71](https://github.com/ansible-collections/azure/pull/71) .

2020-03-16 03:48 UTC, closed without merging