Adds ipa_automountkey module
ansible/ansible pull request #65720
Opened 2019-12-11 10:10 UTC by b1czu

##### SUMMARY

This PR adds an ipa_automountkey module which allows to manage IPA Automount Keys.

Fixes #65719
##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

We did not have an ipa_automountkey module, so here's one!

2019-12-11 12:42 UTC, b1czu commented
@Akasurde @Nosmoht @fxfitz can you help me with this failing documentation test? I've submitted  IPA module with similar documentation before and it passed OK. Now, for this one, it complains about ipa_pass argument but it is not in argument_spec or documentation part of my `ipa_automountkey.py` file.

Also local tests run with `ansible-test sanity -v --junit --coverage-check --docker-keep-git --base-branch origin/devel --allow-disabled --require lib/ansible/modules/identity/ipa/ipa_automountkey.py --docker default
` do not throw this error.

Any help in fixing this would be appreciated.

2020-01-09 13:01 UTC, Akasurde requested changes
Rest LGTM

2020-01-09 13:01 UTC, Akasurde commented on lib/ansible/modules/identity/ipa/ipa_automountkey.py
> +    choices: ["present", "absent"]
```suggestion
    choices: ["absent", "present"]
```

2020-01-09 13:01 UTC, Akasurde commented on lib/ansible/modules/identity/ipa/ipa_automountkey.py
> +# Ensure that /exports/nas key in auto.direct map is present
```suggestion
- name: Ensure that /exports/nas key in auto.direct map is present
  ipa_automountkey:
```

2020-01-09 13:01 UTC, Akasurde commented on lib/ansible/modules/identity/ipa/ipa_automountkey.py
> +# Ensure that /exports/nas key in auto.direct map is absent
```suggestion
- name: Ensure that /exports/nas key in auto.direct map is absent
  ipa_automountkey:
```

2020-01-09 13:01 UTC, Akasurde commented on lib/ansible/modules/identity/ipa/ipa_automountkey.py
> +  type: dict
Add a sample over here how this dict will look like.

2020-01-09 13:01 UTC, Akasurde commented
I re-triggered the CI and fixed the issue for above CI failure.

2020-01-14 10:51 UTC, b1czu commented
ready_for_review

2020-02-23 21:43 UTC, b1czu commented
bot_status

2020-08-16 00:00 UTC, closed without merging