Fix problem with multidomain environments in os_user_role
ansible/ansible pull request #65743
Opened 2019-12-11 20:19 UTC by dkt26111

##### SUMMARY
Fixes #57099 by using domain when getting group

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
cloud/openstack/os_user_role.py

##### ADDITIONAL INFORMATION
Look up groups by domain if specified.

2020-01-03 17:01 UTC, cloudnull approved these changes
shipit

2020-01-20 13:46 UTC, sshnaidm commented
Thanks for submitting patch for Openstack Ansible modules!
We moved Openstack Ansible modules to Openstack repositories.
Next patches should be submitted not with Ansible Github but with
Openstack Gerrit: https://review.opendev.org/#/q/project:openstack/ansible-collections-openstack
Please submit your code there from now.
Thanks for your contribution and sorry for inconvienience.

2020-01-21 08:11 UTC, sshnaidm requested changes
Because we moved Openstack Ansible modules to Openstack repositories, please submit all changes from openstack modules to Openstack Gerrit: https://review.opendev.org/#/q/project:openstack/ansible-collections-openstack Thanks for your contribution and sorry for inconvienience.

2020-08-19 10:30 UTC, Akasurde commented
@dkt26111 Thanks for the contribution. Closing as per above.

2020-08-19 10:30 UTC, closed without merging