Fix #63077
ansible/ansible pull request #65750
Opened 2019-12-12 00:55 UTC by agowa338

If the package is already installed the stdout is not as expected by this function. Either remove `--needed` or just noop if we detect pacman returning. We cannot match the stdout string, as that is most likely localized.

```
[root@archBook user]# /usr/bin/pacman --upgrade --noconfirm --noprogressbar --needed  /srv/aur/src/i3cat-git/i3cat-git-r38.c6d29dd-1-x86_64.pkg.tar.xz
loading packages...
warning: i3cat-git-r38.c6d29dd-1 is up to date -- skipping
 there is nothing to do
```

##### SUMMARY

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2019-12-22 10:00 UTC, tchernomax requested changes
I don't think it solve the problem if we try to install two packages.
For me the solution would be to merge https://github.com/ansible/ansible/pull/65238 and to exclude the `warning` lines from the output.

2019-12-23 21:21 UTC, agowa338 commented
@tchernomax: That issue #65238 seam to be about localization issues when parsing.
This pr is about the case **where all packages we ask pacman to install are already installed**, in that case currently there is an IndexError, because the output is shorter than expected. Therefore we need to check the length of the result.

2020-01-04 19:08 UTC, tchernomax commented
@agowa338 I didn't see that "there is nothing to do" is in stderr.
Can you add a comment explaining in the code in which case `len(stdout.split('\n'))` could be < 3 ?
Else LGTM

2020-01-04 19:09 UTC, tchernomax approved these changes

2020-01-05 17:13 UTC, tchernomax approved these changes
LGTM

2020-01-30 20:11 UTC, felixfontein commented
I tested the module a bit; it doesn't break anything for me at least. Since the PR fixed the problem for @bobsaintcool (https://github.com/ansible/ansible/issues/63077#issuecomment-569040991), I'm inclined to merge this once tests pass.

2020-01-30 20:11 UTC, felixfontein commented
(I added a changelog fragment since that was missing.)

2020-01-30 20:54 UTC, felixfontein commented
If nobody disagrees, I'll merge this over the weekend and create a backport PR.

2020-02-01 13:37 UTC, merged

2020-02-01 13:38 UTC, felixfontein commented
@agowa338 thanks for fixing this!
@tchernomax thanks for reviewing!