mysql_db does not support --no-create-db flag
ansible/ansible pull request #65773
Opened 2019-12-12 19:20 UTC by kitsushadow

…o-create-db flag

##### SUMMARY

The mysql_db module does not provide the ability to include the --no-create-db flag when performing a dump. This PR includes this functionality. We have tested this within the scope of our project.

##### ISSUE TYPE

- Docs Pull Request
- Feature Pull Request

##### COMPONENT NAME

mysql_db

##### ADDITIONAL INFORMATION

Issue can be seen in detail here. I am not the author.
https://stackoverflow.com/questions/59216939/database-specificity-in-sql-dump-file-generated-using-ansible-mysql-db-module 

```paste below
--no-create-db
```

2019-12-12 19:54 UTC, kitsushadow commented
02:43 ERROR: lib/ansible/modules/database/mysql/mysql_db.py:0:0: module-invalid-version-added-number: version_added for new option (create_new) is not a valid version number: '2.X' (75%)

Should I not update the documentation?

02:43 ERROR: lib/ansible/modules/database/mysql/mysql_db.py:0:0: nonexistent-parameter-documented: Argument 'create_new' is listed in DOCUMENTATION.options, but not accepted by the module argument_spec (75%)

What format do you wish to have for argument names?

2019-12-18 16:27 UTC, kitsushadow commented
Any updates or actions I need to take to move this forward?

2019-12-19 07:55 UTC, bmalynovytch commented
Hi @kitsushadow !
Thank you for your contrib !

You need to change the `version_added` to `2.10` (which will remove the first error)
You must also declare your new parameter in the `argument_spec` dictionary.

When you'll be done with it, errors will be gone.

Could you also add a CI test that dumps to check that your parameter does the jobs it's meant to ?

2019-12-19 08:26 UTC, Andersson007 requested changes

2019-12-19 08:26 UTC, Andersson007 commented on lib/ansible/modules/database/mysql/mysql_db.py
> +            encoding=None, force=False, create_new=None):
```suggestion
            encoding=None, force=False, no_create_db=False):
```

2019-12-19 08:26 UTC, Andersson007 commented on lib/ansible/modules/database/mysql/mysql_db.py
> +  create_new:
```suggestion
  no_create_db:
```

2019-12-19 08:26 UTC, Andersson007 commented on lib/ansible/modules/database/mysql/mysql_db.py
> +    version_added: "2.X"
```suggestion
    version_added: '2.10'
```

2019-12-19 08:26 UTC, Andersson007 commented on lib/ansible/modules/database/mysql/mysql_db.py
> +    if create_new:
```suggestion
    if no_create_db:
```

2019-12-19 08:28 UTC, Andersson007 commented
Hello, thanks for the contribution!
Please,
1. change ```create_new``` to ```no_create_db``` because it sounds closer to the key ```--no-create-db```, so IMO is more clear
2. add a changelog fragment
3. add CI tests

2019-12-19 20:22 UTC, kitsushadow commented
> Hello, thanks for the contribution!
> Please,
> 
> 1. change `create_new` to `no_create_db` because it sounds closer to the key `--no-create-db`, so IMO is more clear
> 2. add a changelog fragment
> 3. add CI tests
> 4. `You must also declare your new parameter in the argument_spec dictionary.` @bmalynovytch thanks you
> 5. You also don't pass your option anywhere to the function, so it won't work in this implementation

Thanks for the reply and the assistance. Can I have  

Where can I add a changelog fragment?
Where can I found the CI tests for the mysql_db.py ?

2019-12-20 06:51 UTC, Andersson007 requested changes

2019-12-20 06:51 UTC, Andersson007 commented on lib/ansible/modules/database/mysql/mysql_db.py
> +    no_create_db = module.params["no_create_db"]
you also need to pass the flag to the mysql_dump function where it's invoked in the code

2019-12-20 06:52 UTC, Andersson007 commented
1. changelog fragments [here](https://docs.ansible.com/ansible/latest/community/development_process.html#changelogs)
2. CI tests ```test/integration/targets/mysql_db/```

2019-12-20 06:57 UTC, Andersson007 requested changes

2019-12-20 06:57 UTC, Andersson007 commented on lib/ansible/modules/database/mysql/mysql_db.py
> +      - Option used to exclude CREATE DATABASE and USE commands
```suggestion
      - Option used to exclude CREATE DATABASE and USE commands. Used only with I(state=export).
```
Please, determine explicitly with what this option can be used (i'm not sure that it is only state=export, needs to be rechecked)

2020-01-14 13:50 UTC, kitsushadow commented
What's remaining for this to be merged?

2020-01-15 06:07 UTC, Andersson007 requested changes
2. CI tests ```test/integration/targets/mysql_db/``` (don't change existing, write tests for your case separately please)

2020-01-15 06:07 UTC, Andersson007 commented on changelogs/fragments/65773-add-no-create-db-flag.yml
> +
```suggestion
```

2020-01-15 06:07 UTC, Andersson007 commented on lib/ansible/modules/database/mysql/mysql_db.py
> +    no_create_db = module.params["no_create_db"]
you also need to pass the flag to the mysql_dump function where it's invoked in the code

2020-01-22 20:56 UTC, apapsch commented
Supporting the many options found in mysqldump results in a flurry of PRs all similar to this one, with little advantage for the module. It looks somewhat independent of mysqldump and adding many options breaks the abstraction. I propose, instead of adding many options in a trickle, just add an args argument that serves as the single loophole out of the abstraction. PR #66252 adds the args argument.

2020-01-22 21:10 UTC, Andersson007 commented
@apapsch i absolutely agree with you! this situation happened historically i guess.
will see

2020-04-10 10:10 UTC, Andersson007 commented
close_me

2020-04-10 10:12 UTC, Andersson007 commented
@kitsushadow thanks for the pr
it's fixed by https://github.com/ansible/ansible/pull/67747 i think.
if not, feel free to create a new pr in the new repo for community stuff https://github.com/ansible-collections/community.general

2020-04-10 10:20 UTC, closed without merging