Testing: Add support for AIX/IBMi platform
ansible/ansible pull request #65802
Opened 2019-12-13 11:53 UTC by Spredzy

##### SUMMARY

Enabling testing on AIX platform

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

  - testing

##### ADDITIONAL INFORMATION

  - N/A

2020-01-24 18:34 UTC, jctanner commented
!waffling core_review

2020-01-29 04:02 UTC, mattclay requested changes

2020-01-29 04:02 UTC, mattclay commented on test/integration/targets/acl/aliases
> +skip/ibmi
Since we're adding the `skip/ibmi` aliases now, we should include `ibmi` in `shippable.yml` and `remote.txt`.

2020-01-29 04:02 UTC, mattclay commented on test/lib/ansible_test/_data/setup/remote.sh
> +    chfs -a size=10G /opt
Looking at the default volume sizes, and the values currently in this script, it appears there are both undersized and oversized volumes. In the brief testing I did the following resulted in a more even distribution of the percentage of free space:

```
    chfs -a size=1G /
    chfs -a size=5G /usr
    chfs -a size=1G /var
    chfs -a size=1G /tmp
    chfs -a size=5G /opt
```

2020-01-29 04:02 UTC, mattclay commented on test/lib/ansible_test/_internal/core_ci.py
> +                self.max_threshold = 6
Instead of using the threshold to trigger additional retry cycles, define a new `self.retries` value near the top of this function and override it here. Use it as the value for `tries` in `_start_at_threshold` instead of the hard-coded value.

Also include a comment here explaining that the additional retries are needed to accommodate images transitioning to the active state.

2020-01-29 04:02 UTC, mattclay commented on test/lib/ansible_test/_internal/delegation.py
> +                # AIX cp and GNU cp provide different options, no way could be found to have a commen
```suggestion
                # AIX cp and GNU cp provide different options, no way could be found to have a common
```

2020-01-29 04:02 UTC, mattclay commented on test/lib/ansible_test/_internal/delegation.py
> +                # patttern and achieve the same goal
```suggestion
                # pattern and achieve the same goal
```

2020-01-29 04:02 UTC, mattclay commented on test/lib/ansible_test/_internal/executor.py
> +    if _platform.system() != 'AIX':
There is a new option `pip-check=disabled` that can be used in `remote.txt` instead of a new conditional here.

2020-01-29 04:02 UTC, mattclay commented on test/lib/ansible_test/_internal/executor.py
> +    elif _platform.system() == 'AIX':
There is a new `httptester=disabled` option in `remote.txt` that can be used instead of a conditional here.

2020-01-29 04:02 UTC, mattclay commented on test/lib/ansible_test/_internal/manage_ci.py
> +        command = command if self.core_ci.platform in ['aix', 'ibmi'] else cmd_quote(command)
It looks like this should be conditional on `self.become` rather than the platform:

```suggestion
        command = cmd_quote(command) if self.become else command
```

2020-01-29 04:02 UTC, mattclay commented on test/utils/shippable/platform.sh
> +#!/usr/bin/env bash
I've added a new `remote.sh` file which can be linked to instead of adding this file. The only difference between the two is the use of the `--no-temp-unicode` option. Instead of putting that option here, there is a new setting `temp-unicode=disabled` that can be used in the `remote.txt` file.

2020-01-29 04:02 UTC, mattclay commented on test/lib/ansible_test/_internal/manage_ci.py
> +                'rm -rf ~/ansible && mkdir ~/ansible && cd ~/ansible && gunzip %s && tar oxf %s' %
Pipe the gunzip output to tar instead of reading and writing an intermediary file on disk.

We should also be removing the temp file after extracting it. That's not a new problem with this PR, but this is a good time to fix it since we're making changes here.

2020-01-29 04:02 UTC, mattclay commented on test/lib/ansible_test/_data/setup/remote.sh
> +if [ "${platform}" != "aix" ]; then
I've fixed the SSH setup logic, so this conditional should no longer be needed.

2020-01-29 04:02 UTC, mattclay commented on test/lib/ansible_test/_internal/executor.py
> +import platform as _platform  # the platform string is already used as variables name
No longer needed.

2020-01-29 04:02 UTC, mattclay commented on test/lib/ansible_test/_data/completion/remote.txt
> +aix/7.2 python=2.7
```suggestion
aix/7.2 python=2.7 httptester=disabled temp-unicode=disabled pip-check=disabled
```

2020-01-29 17:01 UTC, mattclay requested changes

2020-01-29 17:01 UTC, mattclay commented on test/lib/ansible_test/_data/setup/remote.sh
> +        pip install --quiet virtualenv \
```suggestion
        pip install --disable-pip-version-check --quiet \
```

2020-01-29 17:03 UTC, mattclay commented
Also needs a changelog entry.

2020-01-29 19:24 UTC, mattclay approved these changes

2020-01-29 23:56 UTC, merged