[WIP]  new module ecs_tag
ansible/ansible pull request #65924
Opened 2019-12-17 17:52 UTC by mpechner

##### SUMMARYwrapper around boto3  ecs tag_resource() and untag_resource()
 

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

ecs_tag()  will tag ecs resources
##### ADDITIONAL INFORMATION

```paste below

```
Started with ec2_tag module code.

2019-12-17 17:53 UTC, mpechner commented
Just looking for comments on API.  Will write and check in tests  once I receive feedback.

2019-12-18 08:33 UTC, mpechner commented
I'll work on tests this weekend.  I wanted this to be reviewed, get feed back on the API I proposed. I am using a version locally  that only handles tagging the cluster resource.

2019-12-22 19:35 UTC, mpechner commented
How do I get someone to tag a look? next steps?  Do you want the Ansible playbooks I used to test placed somewhere?

 Made tags optional if state is list
    For remove tags, list of keys has to be a list or tupel
    
    Tested:
    all 3 states for cluster, service and task_defintion.
    No Ansible info for tasks and cluster_instances - or did I miss something. So these resources types have not been tested.

2019-12-27 14:43 UTC, ezmac commented
Ansibot should have mentioned IRC a few times.  If you want to talk to someone about this PR, that's the best place to go.  irc.freenode.net #ansible-aws Tests will help but from what I've seen, you'll need to talk to others on IRC.  Sometimes it can take a while for them to get the time to look.
I'm "on holiday" until jan-6, but I've been watching the original issue for a while.  I'm just community, but I'll try to take a look when I get back.

2019-12-27 15:36 UTC, mpechner commented
Thanks.  Posted a message on #ansible-aws and joined ansible-devel and ansible

--------------------------------------------
Michael Pechner  NE6RD

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
On Friday, December 27, 2019 6:43 AM, Tad Merchant <notifications@github.com> wrote:

> Ansibot should have mentioned IRC a few times. If you want to talk to someone about this PR, that's the best place to go. irc.freenode.net #ansible-aws Tests will help but from what I've seen, you'll need to talk to others on IRC. Sometimes it can take a while for them to get the time to look.
> I'm "on holiday" until jan-6, but I've been watching the original issue for a while. I'm just community, but I'll try to take a look when I get back.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, [view it on GitHub](https://github.com/ansible/ansible/pull/65924?email_source=notifications&email_token=AABTQSCVYXW2SY4KN2CENNLQ2YIB5A5CNFSM4J37IEJKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHXJGLA#issuecomment-569283372), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AABTQSH67DKYWAY4NDF23T3Q2YIB5ANCNFSM4J37IEJA).

2019-12-27 19:17 UTC, tremble requested changes
Hi,

Thanks for your contribution.  Mostly little niggles, I know you lifted a lot of the work from ec2_tag but we're trying to raise the quality of our code so you're going to get a little more scrutiny than the original code faced.  (We are going back and cleaning things up, but this takes time)

In addition to my other comments, running the code through pylint (with complexity testing enabled) is picking up on the main function getting a little 'complex':  "The McCabe rating is 27 (too-complex)".  While this doesn't generate a sanity error today there is work underway to add complexity testing to the sanity tests.  ( #64623 )

I'd suggest pulling the code for finding the ARN out into a dedicated function.  Additionally, rather than the mass of ``if len(...):`` clauses you can just directly do the resource_arn assignments and catch Index/Key errors (just after catching the Boto errors) if no resource was returned.

```
    try:
        if resource_type == 'cluster':
            description = ecs.describe_clusters(clusters=[resource])
            resource_arn = description['clusters'][0]['clusterArn']
        elif resource_type == 'task':
...
    except (IndexError, KeyError):
        module.fail_json(msg='Failed to find {0} {1}'.format(resource_type, resource))
```

Also, as mentioned on IRC, please add some integration tests and update lib/ansible/config/module_defaults.yml

2019-12-27 19:17 UTC, tremble commented on lib/ansible/modules/cloud/amazon/ecs_tag.py
> +    required: false
```suggestion
```

By convention we don't add ``required: false`` (it's implied) See also
https://docs.ansible.com/ansible/devel/dev_guide/developing_modules_documenting.html#documentation-block

2019-12-27 19:17 UTC, tremble commented on lib/ansible/modules/cloud/amazon/ecs_tag.py
> +      - If the value provided for a tag is null and C(state) is I(absent), the tag will be removed regardless of its current value.
```suggestion
      - If the value provided for a tag is null and I(state=absent), the tag will be removed regardless of its current value.
```

C is for values I is for parameters (and can be used for param=) there are some bad examples around.

2019-12-27 19:17 UTC, tremble commented on lib/ansible/modules/cloud/amazon/ecs_tag.py
> +      - "Note that when combined with C(state: absent), specified tags with non-matching values are not purged."
```suggestion
      - Note that when combined with I(state=absent), specified tags with non-matching values are not purged.
```

2019-12-27 19:17 UTC, tremble commented on lib/ansible/modules/cloud/amazon/ecs_tag.py
> +    default: no
```suggestion
    default: false
```

2019-12-27 19:17 UTC, tremble commented on lib/ansible/modules/cloud/amazon/ecs_tag.py
> +short_description: create and remove tags on ecs clusters.
```suggestion
short_description: create and remove tags on Amazon ECS resources
```

a) short_description shouldn't end in a '.'
b) ECS is an acronym and product name.  In the documentation we should try to refer to it as 'ECS' rather than 'ecs' as an accuracy thing.
c) If I'm reading the module correctly it doesn't just tag clusters...

2019-12-27 19:17 UTC, tremble commented on lib/ansible/modules/cloud/amazon/ecs_tag.py
> +    - Creates, removes and lists tags for an ecs_cluster.
```suggestion
    - Creates, removes and lists tags for Amazon ECS resources.
```

2019-12-27 19:17 UTC, tremble commented on lib/ansible/modules/cloud/amazon/ecs_tag.py
> +       The resource is referenced by its cluster name.  It is designed to be used with complex args (tags), see the examples.
```suggestion
     - Resources are referenced by their cluster name.
```

I wouldn't bother with the comment about 'complex args', the parameters and examples do this for you.

2019-12-27 19:17 UTC, tremble commented on lib/ansible/modules/cloud/amazon/ecs_tag.py
> +author:
@acozine : This is based on the ec2_tags module written by @lwade and @flowerysong.  It feels 'wrong' adding them as authors here since this will start spamming them for ecs_tags issues/PRs.

Is there any 'standard' approach here?  Put a note below the copyright notice?

2019-12-27 19:17 UTC, tremble commented on lib/ansible/modules/cloud/amazon/ecs_tag.py
> +      - The name of the cluster who's resources we are tagging
```suggestion
      - The name of the cluster who's resources we are tagging.
```

While short_description entries shouldn't have a '.' at the end, description entries should...

2019-12-27 19:17 UTC, tremble commented on lib/ansible/modules/cloud/amazon/ecs_tag.py
> +except Exception:
```suggestion
except ImportError:
```

It's generally considered a 'bad' thing to catch 'Exception'.  This is normally done by catching ImportError...

2019-12-27 19:17 UTC, tremble commented on lib/ansible/modules/cloud/amazon/ecs_tag.py
> +    required_if = [('state', 'present', ['tags']), ('state', 'absent', ['tags'])]
I think the code below is going to spit out an ugly exception if resource_type is task/service/task_definition/container and resource is undefined.

It's probably better to require resource be set if resource_type is one of those values...

```suggestion
    required_if = [
        ('state', 'present', ['tags']),
        ('state', 'absent', ['tags']),
        ('resource_type', 'task', ['resource']),
        ('resource_type', 'service', ['resource']),
        ('resource_type', 'task_definition', ['resource']),
        ('resource_type', 'container', ['resource']),
    ]
```

(note: I've not double checked the spacing here, so it'll possibly generate a lint warning)

2019-12-27 20:48 UTC, mpechner commented
I should have time to get this done this weekend. Thanks for the feedback.

--------------------------------------------
Michael Pechner  NE6RD

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
On Friday, December 27, 2019 11:17 AM, Mark Chappell <notifications@github.com> wrote:

> @tremble requested changes on this pull request.
>
> Hi,
>
> Thanks for your contribution. Mostly little niggles, I know you lifted a lot of the work from ec2_tag but we're trying to raise the quality of our code so you're going to get a little more scrutiny than the original code faced. (We are going back and cleaning things up, but this takes time)
>
> In addition to my other comments, running the code through pylint (with complexity testing enabled) is picking up on the main function getting a little 'complex': "The McCabe rating is 27 (too-complex)". While this doesn't generate a sanity error today there is work underway to add complexity testing to the sanity tests. ( [#64623](https://github.com/ansible/ansible/pull/64623) )
>
> I'd suggest pulling the code for finding the ARN out into a dedicated function. Additionally, rather than the mass of if len(...): clauses you can just directly do the resource_arn assignments and catch Index/Key errors (just after catching the Boto errors) if no resource was returned.
>
> except (IndexError, KeyError) as e:
>         module.fail_json(msg='Failed to find {0} {1}'.format(resource_type, resource))
>
> ---------------------------------------------------------------
>
> In [lib/ansible/modules/cloud/amazon/ecs_tag.py](https://github.com/ansible/ansible/pull/65924#discussion_r361710166):
>
>> +version_added: '2.10'
> +author:
> +  - Lester Wade (@lwade)
> +  - Paul Arthur (@flowerysong)
> +  - Michael Pechner (@mpechner)
> +requirements: [ boto3, botocore ]
> +options:
> +  cluster_name:
> +    description:
> +      - The name of the cluster who's resources we are tagging
> +    required: true
> +    type: str
> +  resource:
> +    description:
> +      - The ecs resource name. Can be none only if resource_type is cluster.
> +    required: false
>
> ⬇️ Suggested change
>
> -    required: false
>
> By convention we don't add required: false (it's implied) See also
> https://docs.ansible.com/ansible/devel/dev_guide/developing_modules_documenting.html#documentation-block
>
> ---------------------------------------------------------------
>
> In [lib/ansible/modules/cloud/amazon/ecs_tag.py](https://github.com/ansible/ansible/pull/65924#discussion_r361710959):
>
>> +  resource_type:
> +    description:
> +      - The type of resource
> +    default: cluster
> +    choices: ['cluster', 'task', 'service', 'task_definition', 'container']
> +    type: str
> +  state:
> +    description:
> +      - Whether the tags should be present or absent on the resource. Use list to interrogate the tags of a ecs resource.
> +    default: present
> +    choices: ['present', 'absent', 'list']
> +    type: str
> +  tags:
> +    description:
> +      - A dictionary of tags to add or remove from the resource.
> +      - If the value provided for a tag is null and C(state) is I(absent), the tag will be removed regardless of its current value.
>
> ⬇️ Suggested change
>
> -      - If the value provided for a tag is null and C(state) is I(absent), the tag will be removed regardless of its current value.
> +      - If the value provided for a tag is null and I(state=absent), the tag will be removed regardless of its current value.
>
> C is for values I is for parameters (and can be used for param=) there are some bad examples around.
>
> ---------------------------------------------------------------
>
> In [lib/ansible/modules/cloud/amazon/ecs_tag.py](https://github.com/ansible/ansible/pull/65924#discussion_r361711227):
>
>> +    type: str
> +  state:
> +    description:
> +      - Whether the tags should be present or absent on the resource. Use list to interrogate the tags of a ecs resource.
> +    default: present
> +    choices: ['present', 'absent', 'list']
> +    type: str
> +  tags:
> +    description:
> +      - A dictionary of tags to add or remove from the resource.
> +      - If the value provided for a tag is null and C(state) is I(absent), the tag will be removed regardless of its current value.
> +    type: dict
> +  purge_tags:
> +    description:
> +      - Whether unspecified tags should be removed from the resource.
> +      - "Note that when combined with C(state: absent), specified tags with non-matching values are not purged."
>
> ⬇️ Suggested change
>
> -      - "Note that when combined with C(state: absent), specified tags with non-matching values are not purged."
> +      - Note that when combined with I(state=absent), specified tags with non-matching values are not purged.
>
> ---------------------------------------------------------------
>
> In [lib/ansible/modules/cloud/amazon/ecs_tag.py](https://github.com/ansible/ansible/pull/65924#discussion_r361711277):
>
>> +    description:
> +      - Whether the tags should be present or absent on the resource. Use list to interrogate the tags of a ecs resource.
> +    default: present
> +    choices: ['present', 'absent', 'list']
> +    type: str
> +  tags:
> +    description:
> +      - A dictionary of tags to add or remove from the resource.
> +      - If the value provided for a tag is null and C(state) is I(absent), the tag will be removed regardless of its current value.
> +    type: dict
> +  purge_tags:
> +    description:
> +      - Whether unspecified tags should be removed from the resource.
> +      - "Note that when combined with C(state: absent), specified tags with non-matching values are not purged."
> +    type: bool
> +    default: no
>
> ⬇️ Suggested change
>
> -    default: no
> +    default: false
>
> ---------------------------------------------------------------
>
> In [lib/ansible/modules/cloud/amazon/ecs_tag.py](https://github.com/ansible/ansible/pull/65924#discussion_r361714488):
>
>> @@ -0,0 +1,238 @@
> +#!/usr/bin/python
> +# -*- coding: utf-8 -*-
> +# Copyright: (c) 2019, Michael Pechner <mikey@mikey.com>
> +# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
> +from __future__ import absolute_import, division, print_function
> +ANSIBLE_METADATA = {'metadata_version': '1.1',
> +                    'status': ['preview'],
> +                    'supported_by': 'community'}
> +
> +
> +DOCUMENTATION = r'''
> +---
> +module: ecs_tag
> +short_description: create and remove tags on ecs clusters.
>
> ⬇️ Suggested change
>
> -short_description: create and remove tags on ecs clusters.
> +short_description: create and remove tags on Amazon ECS resources
>
> a) short_description shouldn't end in a '.'
> b) ECS is an acronym and product name. In the documentation we should try to refer to it as 'ECS' rather than 'ecs' as an accuracy thing.
> c) If I'm reading the module correctly it doesn't just tag clusters...
>
> ---------------------------------------------------------------
>
> In [lib/ansible/modules/cloud/amazon/ecs_tag.py](https://github.com/ansible/ansible/pull/65924#discussion_r361714746):
>
>> +# Copyright: (c) 2019, Michael Pechner <mikey@mikey.com>
> +# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
> +from __future__ import absolute_import, division, print_function
> +ANSIBLE_METADATA = {'metadata_version': '1.1',
> +                    'status': ['preview'],
> +                    'supported_by': 'community'}
> +
> +
> +DOCUMENTATION = r'''
> +---
> +module: ecs_tag
> +short_description: create and remove tags on ecs clusters.
> +notes:
> +    - none
> +description:
> +    - Creates, removes and lists tags for an ecs_cluster.
>
> ⬇️ Suggested change
>
> -    - Creates, removes and lists tags for an ecs_cluster.
> +    - Creates, removes and lists tags for Amazon ECS resources.
>
> ----------------------------------------------------- [...]

2019-12-28 15:56 UTC, tremble requested changes
Some more minor documentation tweaks.

2019-12-28 15:56 UTC, tremble commented on lib/ansible/modules/cloud/amazon/ecs_tag.py
> +      - The ecs resource name. Can be none only if resource_type is cluster.
```suggestion
      - The ECS resource name.
      - Required unless I(resource_type=cluster).
```

2019-12-28 15:56 UTC, tremble commented on lib/ansible/modules/cloud/amazon/ecs_tag.py
> +     - Resources are referenced by their cluster name.
```suggestion
    - Resources are referenced by their cluster name.
```

2019-12-28 15:56 UTC, tremble commented on lib/ansible/modules/cloud/amazon/ecs_tag.py
> +      - The type of resource
```suggestion
      - The type of resource.
```

2019-12-28 15:56 UTC, tremble commented on lib/ansible/modules/cloud/amazon/ecs_tag.py
> +      - Whether the tags should be present or absent on the resource. Use list to interrogate the tags of a ecs resource.
```suggestion
      - Whether the tags should be present or absent on the resource.
      - Use C(list) to interrogate the tags of an ECS resource.
```

2019-12-28 15:56 UTC, tremble commented on lib/ansible/modules/cloud/amazon/ecs_tag.py
> +      - The name of the cluster who's resources we are tagging.
```suggestion
      - The name of the cluster whose resources we are tagging.
```

2019-12-29 23:52 UTC, mpechner commented
When  a rebase does not work, stop and try again.

2019-12-29 23:52 UTC, closed without merging