New magic var: `ansible_config_file`
ansible/ansible pull request #66085
Opened 2019-12-27 07:46 UTC by stawii

##### SUMMARY

There are many magic variables ie. ansible_diff_mode, ansible_forks, playbook_dir or ansible_playbook_python.
In some cases it is good to know real path of Ansible config file, check if right one was applied, to read it again manually or just to know its presence.
Therefore I suggest to add new magic variable `ansible_config_file` which keeps path to config or null if none is found.
Overall system impact is unnoticeable, just another var lying around - don't need? don't touch :)

##### ISSUE TYPE

- Feature Pull Request

2020-01-03 16:06 UTC, bcoca submitted a review, later dismissed
lgtm, i would just add a changelog with 'minor feature'

2020-01-09 19:52 UTC, samdoran requested changes
Please add this new magic variable to the docs. https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/reference_appendices/special_variables.rst

2020-01-21 18:16 UTC, samdoran approved these changes

2020-01-21 18:16 UTC, samdoran commented
rebuild_merge

2020-02-11 20:04 UTC, acozine commented
rebuild_merge

2020-02-11 20:49 UTC, merged