FreeIPA: Fix documentation
ansible/ansible pull request #66194
Opened 2020-01-05 04:49 UTC by Akasurde

##### SUMMARY

* Add datatype whereever it is missing
* Fix documentation

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE 
- Bugfix Pull Request

##### COMPONENT NAME
changelogs/fragments/fix_ipa_module_doc_type.yml
lib/ansible/modules/identity/ipa/ipa_config.py
lib/ansible/modules/identity/ipa/ipa_dnsrecord.py
lib/ansible/modules/identity/ipa/ipa_dnszone.py
lib/ansible/modules/identity/ipa/ipa_group.py
lib/ansible/modules/identity/ipa/ipa_hbacrule.py
lib/ansible/modules/identity/ipa/ipa_host.py
lib/ansible/modules/identity/ipa/ipa_hostgroup.py
lib/ansible/modules/identity/ipa/ipa_role.py
lib/ansible/modules/identity/ipa/ipa_service.py
lib/ansible/modules/identity/ipa/ipa_subca.py
lib/ansible/modules/identity/ipa/ipa_sudocmd.py
lib/ansible/modules/identity/ipa/ipa_sudocmdgroup.py
lib/ansible/modules/identity/ipa/ipa_sudorule.py
lib/ansible/modules/identity/ipa/ipa_user.py
lib/ansible/modules/identity/ipa/ipa_vault.py
lib/ansible/plugins/doc_fragments/ipa.py
test/sanity/ignore.txt

2020-01-05 04:50 UTC, Akasurde commented
cc @felixfontein @Andersson007

2020-01-05 10:29 UTC, felixfontein reviewed
Looks reasonable, though I have no way to verify that the types for `elements` are correct.

(This probably doesn't need a changelog fragment.)

2020-01-06 04:26 UTC, Akasurde commented
> (This probably doesn't need a changelog fragment.)

Removed.

Will wait for @Andersson007 confirmation.

2020-01-06 07:48 UTC, Andersson007 requested changes
@Akasurde thanks for tidying up the documentation!
A few cosmetic suggestions for most of the files:
1.  ```DOCUMENTATION = '''``` -> ```DOCUMENTATION = r'''``` , the same for the EXAMPLE and RETURN sections
2. Would be cool to see ```- name: description``` in the EXAMPLE section instead of using comments

2020-01-06 07:48 UTC, Andersson007 commented on lib/ansible/modules/identity/ipa/ipa_dnsrecord.py
>      choices: ['A', 'AAAA', 'A6', 'CNAME', 'DNAME', 'PTR', 'TXT', 'SRV', 'MX']
```suggestion
    choices: ['A', 'AAAA', 'A6', 'CNAME', 'DNAME', 'PTR', 'TXT', 'SRV', 'MX']
```
i'd put them alphabetically too

2020-01-06 07:48 UTC, Andersson007 commented on lib/ansible/modules/identity/ipa/ipa_service.py
> +    - Principal of the service
```suggestion
    - Principal of the service.
```

2020-01-06 07:48 UTC, Andersson007 commented on lib/ansible/modules/identity/ipa/ipa_subca.py
>      - The Sub Certificate Authority's Subject. e.g., 'CN=SampleSubCA1,O=testrelm.test'
```suggestion
    - The Sub Certificate Authority's Subject. e.g., 'CN=SampleSubCA1,O=testrelm.test'.
```

2020-01-06 07:48 UTC, Andersson007 commented on lib/ansible/modules/identity/ipa/ipa_sudocmd.py
>      - Sudo Command.
```suggestion
    - Sudo command.
```

2020-01-06 07:48 UTC, Andersson007 commented on lib/ansible/modules/identity/ipa/ipa_user.py
> +    - Will not be set for an existing user unless C(update_password) is set to C(always), which is the default.
```suggestion
    - Will not be set for an existing user unless C(update_password) is set to C(always), which is the default.
```
good job to split bunches of text to separate lines ! Easier to read the documentation

2020-01-07 08:46 UTC, tremble commented on lib/ansible/modules/identity/ipa/ipa_user.py
> +    - Will not be set for an existing user unless C(update_password) is set to C(always), which is the default.
```suggestion
    - Will not be set for an existing user unless I(update_password) is set to C(always), which is the default.
```

(or ``I(update_password=always)``)

2020-01-09 09:52 UTC, Andersson007 approved these changes
shipit

2020-01-09 10:02 UTC, merged

2020-01-09 10:02 UTC, Akasurde commented
@felixfontein @Andersson007 Thanks for the review.

2020-01-09 12:11 UTC, Akasurde commented
@tremble Thanks for the review.