Update user module to support no_log=False.
ansible/ansible pull request #66219
Opened 2020-01-06 18:43 UTC by kaorihinata

##### SUMMARY

Updates the user module to support pull request #64733. Neither the update_password or password_lock field contains sensitive information, so mark them as such.

Supports #64733.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

lib/ansible/modules/system/user.py 

##### ADDITIONAL INFORMATION

The current testing method for the user module requires that no warnings be emitted during testing. As such, changes to the user module must be submitted first, then pull request #64733 in order to pass testing, and not break CI.

I'm not too familiar with GitHub's tools yet, so please let me know if I need to recreate this pull request.

2020-01-06 20:02 UTC, samdoran requested changes
Please add a changelog fragment.

2020-01-06 20:35 UTC, kaorihinata commented
Changelog fragment added. Let me know if there's an alternative format I should be using embed the PR link.

2020-01-07 16:26 UTC, samdoran approved these changes

2020-01-07 16:26 UTC, merged

2020-01-07 16:27 UTC, samdoran commented
Please create a [backport PR](https://docs.ansible.com/ansible/latest/community/development_process.html#backporting-merged-prs) for this to be included in previous versions. This only needs to be backported to `stable-2.9` since it is not a critical fix.