Add cacert param for self signed spacewalk usage
ansible/ansible pull request #66353
Opened 2020-01-10 14:55 UTC by gali0

##### SUMMARY

rhn_channel raise a CERTIFICATE_VERIFY_FAILED error when use with self signed certificate

Fixes  #29649

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

rhn_channel

##### ADDITIONAL INFORMATION

Error raised before change:
```paste below
TASK [RHN_CHANNEL_configure : Configure Channel on Satellite] ******************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
```

2020-01-14 04:48 UTC, jamescassell requested changes
See https://github.com/ansible/ansible/issues/52506

2020-01-14 04:48 UTC, jamescassell commented on lib/ansible/modules/packaging/os/rhn_channel.py
> +    cacert:
```suggestion
    ca_cert:
```

2020-01-14 08:55 UTC, gali0 commented
> 
> 
> See #52506

You're right, thanks

2020-02-15 23:21 UTC, felixfontein reviewed
You need a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#changelogs-how-to).

2020-02-15 23:21 UTC, felixfontein commented on lib/ansible/modules/packaging/os/rhn_channel.py
> +        if sys.version_info < (2, 7, 9):
```suggestion
        if module.params['ca_cert'] and sys.version_info < (2, 7, 9):
```

2020-02-15 23:21 UTC, felixfontein commented on lib/ansible/modules/packaging/os/rhn_channel.py
> +    if module.params['ca_cert'] is not None and sys.version_info > (2, 7, 9):
If your claim below is correct, you need:
```suggestion
    if module.params['ca_cert'] is not None and sys.version_info >= (2, 7, 9):
```

2020-03-02 13:53 UTC, gali0 commented
> 
> 
> You need a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#changelogs-how-to).

Done

Thanks.

2020-03-02 16:08 UTC, felixfontein approved these changes

2020-03-24 09:03 UTC, yakhatape commented
any update about this PR ? I'm interested on it too :)

2020-03-24 09:37 UTC, gali0 commented
bot_status

2020-03-24 12:51 UTC, gali0 commented
> 
> 
> any update about this PR ? I'm interested on it too :)

All community plugins have moved to another repos, but I can't find any infomations on how to move this PR to this new repo, but I'm still working on getting it accepted :)

2020-03-24 14:08 UTC, felixfontein commented
Most current info is on https://github.com/ansible-collections/overview/, but please note that currently everything is still in flux and community.general (where this has been moved) is still not completely ready yet.

2020-03-24 14:16 UTC, gali0 commented
> 
> 
> Most current info is on https://github.com/ansible-collections/overview/, but please note that currently everything is still in flux and community.general (where this has been moved) is still not completely ready yet.

Okay, thanks for your answer, so I'll wait until you're ready.

2020-03-24 17:16 UTC, yakhatape commented
many thanks for your update @gali0 @felixfontein  ;)

2020-08-15 16:37 UTC, closed without merging