Added extra logic to match security group rules existing rules
ansible/ansible pull request #66351
Opened 2020-01-10 14:34 UTC by Thulium-Drake

Added extra logic to correct module input parameters when matching rules with protocol 'any'

##### SUMMARY

Fixes #66350 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

os_security_group_rule
##### ADDITIONAL INFORMATION

See the linked issue.

```paste below

```

2020-01-14 04:53 UTC, jamescassell requested changes
Wouldn't it be better to just make protocol required? (It's in every example.)

2020-01-14 10:40 UTC, Thulium-Drake commented
From what I've seen in the code the protocol is already a mandatory argument. But the problem is not there.

The problem is that the module wants/needs to match ports. Protocol 'any' does not match ports (that's a fix I wrote earlier to be able to remove rules with 'any' protocol, see #59055).

However, I missed something while testing this. When you want to create a rule, it works just fine, until you run the module for the second time. Then the API returns an error the rule already exists, the issue again is that the module wants to match ports (which is _still_ valid for all TCP/UDP rules).

Being as there are multiple valid ways to define 'all ports' for a security rule:

1. port_min: -1  / port_max: -1
2. port_min: 0  / port_max: 65535
3. port_min: None / port_max: None (basically, leave undefined)

And the API returns the 2nd method, I wrote the fix that if the user supplied protocol 'any' to correct the input to something that will actually match the output.

OT: Maybe the Openstack set of modules could use a complete redesign, but I am not equipped to do so. I have limited time to work on this, which I'd like to focus on fixing the issues I run into :slightly_smiling_face:

2020-01-14 12:04 UTC, jamescassell approved these changes
The change is good, but perhaps make the default protocol explicitly 'any' and remove references to None in the docs.

2020-01-20 13:46 UTC, sshnaidm commented
Thanks for submitting patch for Openstack Ansible modules!
We moved Openstack Ansible modules to Openstack repositories.
Next patches should be submitted not with Ansible Github but with
Openstack Gerrit: https://review.opendev.org/#/q/project:openstack/ansible-collections-openstack
Please submit your code there from now.
Thanks for your contribution and sorry for inconvienience.

2020-01-21 08:10 UTC, sshnaidm requested changes
Because we moved Openstack Ansible modules to Openstack repositories, please submit all changes from openstack modules to Openstack Gerrit: https://review.opendev.org/#/q/project:openstack/ansible-collections-openstack Thanks for your contribution and sorry for inconvienience.

2020-01-21 09:45 UTC, Thulium-Drake commented
Hi Sergey,

Thanks for the feedback, I'll prepare to republish the changes I have outstanding in the coming days.

PS: can I sign in with my Github account on Opendev?

2020-01-21 09:51 UTC, sshnaidm commented
@Thulium-Drake unfortunately you can't use Github account for Opendev, the required steps are: https://docs.openstack.org/contributors/common/accounts.html
Thanks!

2020-08-19 10:30 UTC, Akasurde commented
@Thulium-Drake Thanks for the contribution. Closing as per above.

2020-08-19 10:30 UTC, closed without merging