Added additional error handling inside the hcloud.py inventory plugin…
ansible/ansible pull request #66381
Opened 2020-01-11 13:40 UTC by sternze

…. Otherwise, errors may happen, if the HCloud API is not able to correctly identify the server image.

##### SUMMARY

During a test run of the plugin with my HCloud, I recognized errors inside the inventory code. By adding additional checks for "None" Objects, those errors could be fixed and I was able to get the information from the Inventory Plugin.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

HCloud Inventory Plugin

##### ADDITIONAL INFORMATION

Error before the change:
```paste below
daniel@ubuntu:~/ansible_test$ HCLOUD_TOKEN=<TOKEN> ansible-inventory -i hcloud.yml --list -vvvv
ansible-inventory 2.9.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/daniel/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/daniel/.local/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible-inventory
  python version = 3.6.8 (default, Oct  7 2019, 12:59:55) [GCC 8.3.0]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /home/daniel/ansible_test/hcloud.yml as it did not pass its verify_file() method
script declined parsing /home/daniel/ansible_test/hcloud.yml as it did not pass its verify_file() method
toml declined parsing /home/daniel/ansible_test/hcloud.yml as it did not pass its verify_file() method
[WARNING]:  * Failed to parse /home/daniel/ansible_test/hcloud.yml with auto plugin: 'NoneType' object has no attribute 'id'

  File "/home/daniel/.local/lib/python3.6/site-packages/ansible/inventory/manager.py", line 280, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/home/daniel/.local/lib/python3.6/site-packages/ansible/plugins/inventory/auto.py", line 58, in parse
    plugin.parse(inventory, loader, path, cache=cache)
  File "/home/daniel/.local/lib/python3.6/site-packages/ansible/plugins/inventory/hcloud.py", line 208, in parse
    self._set_server_attributes(server)
  File "/home/daniel/.local/lib/python3.6/site-packages/ansible/plugins/inventory/hcloud.py", line 181, in _set_server_attributes
    self.inventory.set_variable(server.name, "image_id", to_native(server.image.id))

[WARNING]:  * Failed to parse /home/daniel/ansible_test/hcloud.yml with yaml plugin: Plugin configuration YAML file, not YAML inventory

  File "/home/daniel/.local/lib/python3.6/site-packages/ansible/inventory/manager.py", line 280, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/home/daniel/.local/lib/python3.6/site-packages/ansible/plugins/inventory/yaml.py", line 112, in parse
    raise AnsibleParserError('Plugin configuration YAML file, not YAML inventory')

[WARNING]:  * Failed to parse /home/daniel/ansible_test/hcloud.yml with ini plugin: Invalid host pattern 'plugin:' supplied, ending in ':' is not allowed, this character is reserved to provide a port.

  File "/home/daniel/.local/lib/python3.6/site-packages/ansible/inventory/manager.py", line 280, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/home/daniel/.local/lib/python3.6/site-packages/ansible/plugins/inventory/ini.py", line 138, in parse
    raise AnsibleParserError(e)

[WARNING]: Unable to parse /home/daniel/ansible_test/hcloud.yml as an inventory source

[WARNING]: No inventory was parsed, only implicit localhost is available

{
    "_meta": {
        "hostvars": {}
    },
    "all": {
        "children": [
            "ungrouped"
        ]
    }
}

```

Corrected after the change (I removed server names/IPs/IDs):
```paste below
daniel@ubuntu:~/ansible_test$ HCLOUD_TOKEN=<TOKEN> ansible-inventory -i hcloud.yml --list -vvvv
ansible-inventory 2.9.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/daniel/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/daniel/.local/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible-inventory
  python version = 3.6.8 (default, Oct  7 2019, 12:59:55) [GCC 8.3.0]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /home/daniel/ansible_test/hcloud.yml as it did not pass its verify_file() method
script declined parsing /home/daniel/ansible_test/hcloud.yml as it did not pass its verify_file() method
Parsed /home/daniel/ansible_test/hcloud.yml inventory source with auto plugin
{
    "_meta": {
        "hostvars": {
            "Server1": {
                "ansible_host": "<Correct-IP>",
                "datacenter": "nbg1-dc3",
                "id": "1233",
                "image_id": "2",
                "image_name": "debian-9",
                "image_os_flavor": "debian",
                "ipv4": "<Correct-IP>",
                "ipv6_network": "<Correct-IP>",
                "ipv6_network_mask": "64",
                "labels": {},
                "location": "nbg1",
                "name": "Server1",
                "server_type": "debian-9",
                "status": "running",
                "type": "cx31"
            },
            "Server2": {
                "ansible_host": "<Correct-IP>",
                "datacenter": "fsn1-dc14",
                "id": "1234",
                "image_id": "11331244",
                "image_name": "No Image Name found",
                "image_os_flavor": "debian",
                "ipv4": "<Correct-IP>",
                "ipv6_network": "<Correct-IP>",
                "ipv6_network_mask": "64",
                "labels": {},
                "location": "fsn1",
                "name": "Server2",
                "server_type": "No Image name found.",
                "status": "running",
                "type": "cx21"
            },
            ...
        }
    },
    "all": {
        "children": [
            "hcloud",
            "ungrouped"
        ]
    },
    "hcloud": {
        "hosts": [
            "Server1",
            "Server2"
        ]
    }
}

```

2020-01-14 11:16 UTC, LKaemmerling approved these changes

2020-01-14 11:20 UTC, LKaemmerling requested changes
Looks good, thank you! I have some things which should be changed.

2020-01-14 11:20 UTC, LKaemmerling commented on lib/ansible/plugins/inventory/hcloud.py
> +            if server.image.id is not None:
If an image is set, the ID can never be None.

2020-01-14 11:20 UTC, LKaemmerling commented on lib/ansible/plugins/inventory/hcloud.py
> +                self.inventory.set_variable(server.name, "image_name", to_native(server.image.name))
The name of an image can be None, if the name is None you should go on the non unique description.

Images with names are only our system images. Without names are backups or snapshots.

2020-01-14 11:20 UTC, LKaemmerling commented on lib/ansible/plugins/inventory/hcloud.py
> +            if server.image.os_flavor is not None:
os_flavor is always set it can't be None

2020-01-14 11:50 UTC, LKaemmerling approved these changes

2020-01-14 11:50 UTC, LKaemmerling commented
shipit

2020-02-15 14:48 UTC, gundalow commented
rebuild_merge

@sternze  Your first Ansible PR, MERGED :tada:  . Welcome to the Ansible Community

@LKaemmerling Thank you for the review

If you'd like to see this fixed in Ansible 2.9 please raise a backport PR including a changelog/fragment
https://docs.ansible.com/ansible/latest/community/development_process.html#making-your-pr-merge-worthy

2020-02-15 16:09 UTC, merged