zabbix_template - fixing errors on empty linked templates
ansible/ansible pull request #66463
Opened 2020-01-14 08:32 UTC by rockaut

##### SUMMARY
fixes #66417

Line 409 fixes KeyError if existing template has no linked templates - as Zabbix API isn't returning an empty array either.
Line 417 is needed to mark as changed if new/modified template has no linked but existing one has.
Line 442 is needed to actually update even if link_templates was None.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
zabbix_template

##### ADDITIONAL INFORMATION
Tested against Zabbix 4.4.4 with Ansible 2.9.2 and python 3.6.9

2020-01-17 14:17 UTC, D3DeFi approved these changes
Thank you @rockaut for identifying these issues and fixing them. I've tested your patch against zbx 3.0, 4.0 and 4.4 and it seems to be working for me. 

This was testing [playbook](https://github.com/D3DeFi/zbx-ansible-dev/blob/master/test_zabbix_template.yml). Only problem was with task 'Create multiple templates from XML (existing)' where module was not idempotent. It still imported all of the templates form a single XML file, but reported `changed=True` every time. I am closing my eyes before that one as `check_template_changed` was never tailored to work with more than one template in the first place.

Now only needs [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#changelogs-how-to) and is good to go if @sky-joker agrees.

2020-01-19 15:24 UTC, sky-joker commented
Looks good to me :)
(tested on zabbix 3.0/3.2/3.4/4.0/4.2/4.4/5.0)

Can you please add fragment file to this PR.

2020-01-20 12:28 UTC, D3DeFi requested changes

2020-01-20 12:28 UTC, D3DeFi commented on changelogs/fragments/66463-zabbix_template-fix-error-linktemplate-and-importdump.yml
> +  - zabbix_template fix for error on linked templates and their removal
```suggestion
  - zabbix_template - fixed error when providing empty linked templates to the module (see https://github.com/ansible/ansible/issues/66417)
```

2020-01-20 12:28 UTC, D3DeFi commented on changelogs/fragments/66463-zabbix_template-fix-error-linktemplate-and-importdump.yml
> +  - zabbix_template fix for error on dump/import of templates
```suggestion
  - zabbix_template - fixed invalid (non-importable) output provided by exporting XML (see https://github.com/ansible/ansible/issues/66466)
```

2020-01-23 04:30 UTC, D3DeFi approved these changes
Thank you for implementing our recommendations! This is good to go now.

shipit

2020-01-23 13:17 UTC, sky-joker commented
Thank you @rockaut :)

shipit

2020-01-23 13:19 UTC, rockaut commented
Hm... I think this still doesn't work fully as expected. If you dump a template, then change the linked templates and then import the file again, the changes to the linked templates aren't saved.

Partly thats because the linked templates of the loaded xml/json file are never processed. So acutally it's more a new issue then! The fixes here now are working.

2020-01-23 13:22 UTC, merged