VMware: Match state param in vmware_guest and vmware_guest_powerstate
ansible/ansible pull request #66706
Opened 2020-01-23 07:30 UTC by Akasurde

##### SUMMARY

Added 'powered-on', 'powered-off', 'shutdown-guest', 'reboot-guest' state
values in vmware_guest module in order to match vmware_guest_powerstate module.

Fixes: #55653

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE 
- Bugfix Pull Request

##### COMPONENT NAME
changelogs/fragments/55653-vmware_guest_powerstate.yml
lib/ansible/modules/cloud/vmware/vmware_guest.py
test/integration/targets/vmware_guest/tasks/check_mode.yml

2020-01-23 19:18 UTC, samccann reviewed
one little nit...

2020-01-23 19:18 UTC, samccann commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +      C(present), C(restarted), C(suspended) and virtual machine does not exists, virtual machine is deployed with the given parameters.'
```suggestion
      C(present), C(restarted), C(suspended) and virtual machine does not exist, virtual machine is deployed with the given parameters.'
```

2020-01-24 19:26 UTC, mariolenz commented
I think it's a good idea to have consistent values for the (power) state of a VM. But if you prefer- for example- `powered-off` over `poweredoff`, I think we should deprecate the latter and remove it in the future.

Btw: According to the documentation, vmware_guest_info returns `poweredOff`. Maybe this should be changed, too, for the sake of consistency.

2020-01-29 08:35 UTC, Andersson007 commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +    - 'Powerstate C(powered-on) and C(powered-off) is added in version 2.10.'
```suggestion
    - 'Powerstate C(powered-on) and C(powered-off) is added in version 2.10.'
    -
```
I think to add the same for ```shutdown-guest``` and ```reboot-guest``` would be good

2020-02-03 18:47 UTC, goneri requested changes
Looks good to me, just a minor comment.

2020-02-03 18:47 UTC, goneri commented on lib/ansible/modules/cloud/vmware/vmware_guest.py
> +    - 'If C(state) is set to C(poweredon) or C(powered-on) and virtual machine exists with powerstate other than powered on,
In order to keep things simple and short, I would prefer to just mention the new state names, and add a comment to list the aliases. e.g: `poweredoff` is an alias for `powered-off`.
I also would like to see a deprecation warning when the old state are used. This way, we won't have to keep all the state names for decades.

2020-03-02 20:37 UTC, goneri commented
Hi!

Thank you for your PR. Since March 2, 2020, the Ansible team does not accept any new changes on the VMware modules on the core `ansible/ansible` repository.
The development continue but in the new VMware collection repository: https://github.com/ansible-collections/vmware
Could you please reopen the PR there?

Links:
- https://groups.google.com/forum/#!msg/ansible-devel/6UAfogEDtG8/wMTgxBGWCgAJ
- https://github.com/ansible-collections/overview/blob/master/README.rst

2020-03-02 21:56 UTC, goneri commented
I've manually migrated the PR to the new collection repository: https://github.com/ansible-collections/vmware/pull/11

I close this one.

2020-03-02 21:56 UTC, closed without merging