Update CentOS test images
ansible/ansible pull request #66771
Opened 2020-01-24 19:25 UTC by samdoran

##### SUMMARY

The test images have the following changes:
- CentOS 8.1
- remove MySQL and MariaDB packages since the tests install them
- remove i18n files (and a few other things) to pare down the image sizes somewhat

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

`test/lib/ansible_test/_data/completion/docker.txt`

2020-01-24 20:12 UTC, mattclay commented
It's probably time to update to the new container version for all of the containers, not just centos.

2020-01-24 20:48 UTC, samdoran commented
Ok, I was wondering about that.

2020-01-24 22:36 UTC, samdoran commented
I have some test failures to investigate.

2020-06-03 23:30 UTC, mattclay requested changes
Changelog entry needed.

2020-06-08 20:03 UTC, mattclay approved these changes

2020-06-09 14:08 UTC, merged