Update vmware_guest_disk_info.py
ansible/ansible pull request #67127
Opened 2020-02-05 15:05 UTC by yuramat

For  returning value: "backing_diskmode"

##### SUMMARY

For returning value: "backing_diskmode".

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2020-02-05 17:43 UTC, goneri commented
recheck

2020-02-06 07:08 UTC, yuramat commented
recheck

2020-02-07 01:00 UTC, goneri commented
recheck

2020-02-07 14:06 UTC, yuramat commented
recheck

2020-02-07 19:55 UTC, goneri approved these changes

2020-02-07 19:58 UTC, goneri commented
Looks good to me, thanks @yuramat for the contribution. Could you please just add a changelog entry:
https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#changelogs

2020-02-20 07:04 UTC, Akasurde requested changes

2020-02-20 07:04 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_guest_disk_info.py
> +                    disks_info[disk_index]['backing_diskmode'] = disk.backing.diskMode
```suggestion
                    disks_info[disk_index]['backing_diskmode'] = disk.backing.diskMode
                    disks_info[disk_index]['backing_disk_mode'] = disk.backing.diskMode
```

For backward compatability.

2020-02-20 07:06 UTC, Akasurde commented on lib/ansible/modules/cloud/vmware/vmware_guest_disk_info.py
> +                    disks_info[disk_index]['backing_diskmode'] = disk.backing.diskMode
This change is required due to https://github.com/ansible/ansible/commit/34868f07d5b32083d03cc4954287355b3b2f647e#commitcomment-35271563

2020-02-20 07:07 UTC, Akasurde commented
Add a change log entry for this change [here](https://github.com/ansible/ansible/tree/devel/changelogs/fragments)

2020-03-02 20:35 UTC, goneri commented
Hi!

Thank you for your PR. Since March 2, 2020, the Ansible team does not accept any new changes on the VMware modules on the core `ansible/ansible` repository.
The development continue but in the new VMware collection repository: https://github.com/ansible-collections/vmware
Could you please reopen the PR there?

Links:
- https://groups.google.com/forum/#!msg/ansible-devel/6UAfogEDtG8/wMTgxBGWCgAJ
- https://github.com/ansible-collections/overview/blob/master/README.rst

2020-03-02 22:13 UTC, goneri commented
I've manually migrated your PR here, feel free to take it over: https://github.com/ansible-collections/vmware/pull/15

I close this one since it will never be merged.

2020-03-02 22:13 UTC, closed without merging