Add the section RETURN to the module lineinfile
ansible/ansible pull request #67224
Opened 2020-02-07 22:01 UTC by it-praktyk

##### SUMMARY
The section RETURN was added to a documentation of the lineinfile module

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
lineinfile

2020-02-09 21:13 UTC, it-praktyk commented
I've tried to debug the error locally. I can't figured out if/what is it wrong with my PR.

My results.
```
<user_name>% ansible-test sanity --test docs-build
WARNING: PyYAML will be slow due to installation without libyaml support for interpreter: /home/<user_name>/<virtualev_name>/bin/python
Running sanity test 'docs-build' with Python 3.6
ERROR: Found 11 docs-build issue(s) which need to be resolved:
ERROR: docs/docsite/rst/index.rst:30:0: literal-block-lex-error: Could not lex literal_block as "guess". Highlighting skipped.
ERROR: docs/docsite/rst/index.rst:47:0: literal-block-lex-error: Could not lex literal_block as "guess". Highlighting skipped.
ERROR: docs/docsite/rst/index.rst:56:0: literal-block-lex-error: Could not lex literal_block as "guess". Highlighting skipped.
ERROR: docs/docsite/rst/index.rst:72:0: literal-block-lex-error: Could not lex literal_block as "guess". Highlighting skipped.
ERROR: docs/docsite/rst/index.rst:188:0: literal-block-lex-error: Could not lex literal_block as "guess". Highlighting skipped.
ERROR: docs/docsite/rst/index.rst:201:0: literal-block-lex-error: Could not lex literal_block as "guess". Highlighting skipped.
ERROR: docs/docsite/rst/index.rst:211:0: literal-block-lex-error: Could not lex literal_block as "guess". Highlighting skipped.
ERROR: docs/docsite/rst/index.rst:266:0: literal-block-lex-error: Could not lex literal_block as "guess". Highlighting skipped.
ERROR: docs/docsite/rst/index.rst:298:0: literal-block-lex-error: Could not lex literal_block as "guess". Highlighting skipped.
ERROR: docs/docsite/rst/index.rst:308:0: literal-block-lex-error: Could not lex literal_block as "guess". Highlighting skipped.
ERROR: docs/docsite/rst/index.rst:322:0: literal-block-lex-error: Could not lex literal_block as "guess". Highlighting skipped.
See documentation for help: https://docs.ansible.com/ansible/devel/dev_guide/testing/sanity/docs-build.html
ERROR: The 1 sanity test(s) listed below (out of 1) failed. See error output above for details.
docs-build
```

```
<user_name>% cd docs/docsite
<user_name>% make singlehtmldocs
PYTHONPATH=../../lib ../../hacking/build-ansible.py collection-meta --template-file=../templates/collections_galaxy_meta.rst.j2 --output-dir=rst/dev_guide/ ../../lib/ansible/galaxy/data/collections_galaxy_meta.yml
PYTHONPATH=../../lib ../../hacking/build-ansible.py document-config --template-file=../templates/config.rst.j2 --output-dir=rst/reference_appendices/ ../../lib/ansible/config/base.yml
mkdir -p rst/cli
PYTHONPATH=../../lib ../../hacking/build-ansible.py generate-man --template-file=../templates/cli_rst.j2 --output-dir=rst/cli/ --output-format rst ../../lib/ansible/cli/*.py
PYTHONPATH=../../lib ../../hacking/build-ansible.py document-keywords --template-dir=../templates --output-dir=rst/reference_appendices/ ./keyword_desc.yml
PYTHONPATH=../../lib ../../hacking/build-ansible.py document-plugins -t rst --template-dir=../templates --module-dir=../../lib/ansible/modules -o rst/modules/
Evaluating module files...
../../lib/ansible/modules/cloud/amazon/cloudwatchlogs_log_group_metric_filter.py:cloudwatchlogs_log_group_metric_filter:yaml error:'NoneType' object does not support item assignment:returndocs=
metric_filters:
    description: Return the origin response value
    returned: success
    type: list
    contains:
        creation_time:
        filter_name:
        filter_pattern:
        log_group_name:
        metric_filter_count:

rendering: iam_server_certificate_info
../../lib/ansible/modules/network/netconf/netconf_rpc.py:netconf_rpc:yaml error:list indices must be integers or slices, not str:returndocs=
stdout:
  description: The raw XML string containing configuration or state data
               received from the underlying ncclient library.
  returned: always apart from low-level errors (such as action plugin)
  type: str
  sample: '...'
stdout_lines:
  description: The value of stdout split into a list
  returned: always apart from low-level errors (such as action plugin)
  type: list
  sample: ['...', '...']
output:
  description: Based on the value of display option will return either the set of
               transformed XML to JSON format from the RPC response with type dict
               or pretty XML string response (human-readable) or response with
               namespace removed from XML string.
  returned: when the display format is selected as JSON it is returned as dict type, if the
            display format is xml or pretty pretty it is returned as a string apart from low-level
            errors (such as action plugin).
  type: complex
  contains:
    formatted_output:
      - Contains formatted response received from remote host as per the value in display format.

../../lib/ansible/modules/network/netconf/netconf_get.py:netconf_get:yaml error:list indices must be integers or slices, not str:returndocs=
stdout:
  description: The raw XML string containing configuration or state data
               received from the underlying ncclient library.
  returned: always apart from low-level errors (such as action plugin)
  type: str
  sample: '...'
stdout_lines:
  description: The value of stdout split into a list
  returned: always apart from low-level errors (such as action plugin)
  type: list
  sample: ['...', '...']
output:
  description: Based on the value of display option will return either the set of
               transformed XML to JSON format from the RPC response with type dict
               or pretty XML string response (human-readable) or response with
               namespace removed from XML string.
  returned: when the display format is selected as JSON it is returned as dict type, if the
            display format is xml or pretty pretty it is returned as a string apart from low-level
            errors (such as action plugin).
  type: complex
  contains:
    formatted_output:
      - Contains formatted response received from remote host as per the value in display format.

*** recording category all in list_of_all_modules.rst ***
*** recording category cloud in list_of_cloud_modules.rst ***
*** recording category clustering in list_of_clustering_modules.rst ***
*** recording category commands in list_of_commands_modules.rst ***
*** recording category crypto in list_of_crypto_modules.rst ***
*** recording category database in list_of_database_modules.rst ***
*** recording category files in list_of_files_modules.rst ***
*** recording category identity in list_of_identity_modules.rst ***
*** recording category inventory in list_of_inventory_modules.rst ***
*** recording category messaging in list_of_messaging_modules.rst ***
*** recording category monitoring in list_of_monitoring_modules.rst ***
*** recording category net_tools in list_of_net_tools_modules.rst ***
*** recording category network in list_of_network_modules.rst ***
*** recording category notification in list_of_notification_modules.rst ***
*** recording category packaging in list_of_packaging_modules.rst ***
*** recording category remote_management in list_of_remote_management_modules.rst ***
*** recording category source_control in list_of_source_control_modules.rst ***
*** recording category storage in list_of_storage_modules.rst ***
*** recording category system in list_of_system_modules.rst ***
*** recording category utilities in list_of_utilities_modules.rst ***
*** recording category web_infrastructure in list_of_web_infrastructure_modules.rst ***
*** recording category windows in list_of_windows_modules.rst ***
looping over doc plugins
for plugin in become cache callback cliconf connection httpapi inventory lookup netconf shell strategy vars; \
do \
	PYTHONPATH=../../lib ../../hacking/build-ansible.py document-plugins -t rst --plugin-type $plugin --template-dir=../templates --module-dir=../../lib/ansible/plugins/$plugin -o rst ; \
done
Evaluating become files...
Evaluating cache files...
Evaluating callback files...
Evaluating cliconf files...
Evaluating connection files...
Ev [...]

2020-02-11 17:35 UTC, acozine commented
@it-praktyk thanks for doing the work of adding these return values.

To fix the test error, I think you need to remove the `-`s under `contains`. For the syntax, take a look at https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/aws_eks_cluster.py. 

Also, it looks like you have two sets of values for `after` - should one of them have a different name?

Finally, you may need to rebase this branch, because I just merged a change to the lineinfile examples.

Feel free to hop on the ansible-docs channel on freenode IRC to chat about this. I hope to get this change passing CI and merged soon!

2020-02-11 18:56 UTC, it-praktyk commented
@acozine, thank you for your review.

Unfortunately, the output from the `lineinfile` module looks like I describe in the proposed change. I provide the example below. 

That means that the diff key contains the list of two dictionaries. Keys of both dictionaries can be the same :-/ 

```yaml
{
    "backup": "",
    "changed": false,
    "diff": [
        {
            "after": "",
            "after_header": "/etc/services (content)",
            "before": "",
            "before_header": "/etc/services (content)"
        },
        {
            "after_header": "/etc/services (file attributes)",
            "before_header": "/etc/services (file attributes)"
        }
    ],
    "invocation": {
        "module_args": {
            "attributes": null,
            "backrefs": false,
            "backup": true,
            "create": false,
            "firstmatch": false,
            "group": "vagrant",
            "insertafter": null,
            "insertbefore": "^www.*80/tcp",
            "line": "# default port used for http",
            "mode": null,
            "owner": null,
            "path": "/etc/services",
            "regexp": "^# port for http",
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "state": "present",
            "unsafe_writes": null,
            "validate": null
        }
    },
    "msg": ""
}
```
So for now I propose to consider add an exception for the CI role which fails. I observed - under local rendering HTML help - that only the first element of the list under the diff key is added to the document. 

From my side, I can open the issue to discuss with the `lineinfile` module authors and the Ansible maintainers team changing of returned output.

What do you think?

CC: @dhozac, @ahtik

2020-02-11 21:45 UTC, acozine commented
@it-praktyk thanks for the response. I do see the problem, but I'm not sure what's the best solution. Keep me posted on the conversation with the module authors.

2020-02-24 18:23 UTC, samdoran requested changes

2020-02-24 18:23 UTC, samdoran commented on lib/ansible/modules/files/lineinfile.py
> +changed:
Common return values such as `changed`, `failed`, `msg`, etc.  do not need to be documented explicitly by the module.

2020-02-24 18:23 UTC, samdoran commented on lib/ansible/modules/files/lineinfile.py
> +  returned: When changed a status message otherwise an empty string.
If you do want to document `msg`, then it should also be mentioned that the `msg` will contain error information in the event of failure.

2020-02-24 18:23 UTC, samdoran commented on lib/ansible/modules/files/lineinfile.py
> +  type: complex
This should be `type: list` with `elements: dict` since it contains a list of two dictionaries. The first dictionary in the list contains the file content difference and the second contains file attribute differences.

2020-02-24 18:23 UTC, samdoran commented on lib/ansible/modules/files/lineinfile.py
> +        returned: When the parameter `--diff` is used otherwise empty string is returned.
Module doc strings are restructured text format, so double backticks are needed for inline code snippets.
```suggestion
        returned: When the parameter ``--diff`` is used otherwise empty string is returned.
```

2020-02-24 18:23 UTC, samdoran commented on lib/ansible/modules/files/lineinfile.py
> +        returned: When the parameter `--diff` is used otherwise empty string is returned.
```suggestion
        returned: When the parameter ``--diff`` is used otherwise empty string is returned.
```

2020-02-24 18:23 UTC, samdoran commented on lib/ansible/modules/files/lineinfile.py
> +  type: complex
The contents section is meant to describe the value of each key in dictionary elements in list, not the content of each key for each specific element in the list, which is why the schema validation is failing.

In this case, I can see how it makes sense to want to describe item 0 and item 1 separately since they same keys mean different things depending on position. This would require changing the validation schema to allow for a list of dicts in `contains`.

Another option would be to just describe the terms more generically instead of trying to enumerate the specific values at a position in the list.

2020-03-04 04:23 UTC, jamescassell approved these changes

2021-02-19 15:04 UTC, s-hertel commented on lib/ansible/modules/files/lineinfile.py
> +    - after:
This is failing the sanity test because `elements` is a dict, but this is a list. Just document the 4 keys and use sample at the same level as `elements` to display the diff array.

2022-03-23 19:51 UTC, nitzmahone commented
Closing for inactivity- please open a new rebased PR if this documentation is still desired

2022-03-23 19:51 UTC, closed without merging