add module cloudformation_exports
ansible/ansible pull request #67349
Opened 2020-02-12 18:06 UTC by mmoyle

##### SUMMARY
New module to read CloudFormation Exports

##### COMPONENT NAME
cloudformation_exports

2020-02-19 01:32 UTC, jillr reviewed
Thanks for this new module!
Could you please add the module name to `lib/ansible/config/module_defaults.yml` as part of "group/aws", and `cloudformation:ListExports` to `hacking/aws_config/testing_policies/devops-policy.json`?  I'll try to give these tests a run through later this week.

2020-02-19 01:32 UTC, jillr commented on test/integration/targets/cloudformation_exports/tasks/main.yml
> +    - debug:
Please remove the debug task here

2020-02-19 01:32 UTC, jillr commented on test/integration/targets/cloudformation_exports/tasks/main.yml
> +          - export_value is defined
We should try to assert some additional things about the export_value, like `export_value['Name'] is "Set By CF Exports"` and the length/number of exports.

2020-02-19 01:32 UTC, jillr commented on lib/ansible/modules/cloud/amazon/cloudformation_exports.py
> +- debug: var=cf_exports
```suggestion
- debug: 
    msg: "{{ cf_exports }}"
```
We generally prefer this syntax.

2020-02-19 01:32 UTC, jillr commented on lib/ansible/modules/cloud/amazon/cloudformation_exports.py
> +    import botocore
Please just import the exceptions that you need rather than the full library.

2020-02-19 01:32 UTC, jillr commented on lib/ansible/modules/cloud/amazon/cloudformation_exports.py
> +    result['original_message'] = module.params
```suggestion
```
We don't need to return the credentials back out in the result.

2020-02-19 01:32 UTC, jillr commented on lib/ansible/modules/cloud/amazon/cloudformation_exports.py
> +        message=''
```suggestion
```
Nothing ever gets added to message, if the key isn't used it doesn't need to be returned.

2020-02-19 14:08 UTC, tremble commented
@mmoyle When the tests finish ansibot's going to get grumpy about the 'merge' commit.  Please **rebase** rather than merging devel into your branch.

2020-02-19 14:09 UTC, mmoyle commented
Hi @jillr ! 

Thank you for the review! I am still getting the testing error

```
01:35     "msg": "Unable to locate credentials", 
01:35     "resource_actions": [
01:35         "cloudformation:ListExports"
01:35     ]
```

2020-02-19 14:18 UTC, tremble requested changes

2020-02-19 14:18 UTC, tremble commented on test/integration/targets/cloudformation_exports/tasks/main.yml
> +          - "{{ export_items | length }}" == 1
```suggestion
          - export_items | length == 1
```

"that" is kinda like "when" you don't need the wrapping '{{ }}'

2020-02-19 18:38 UTC, jillr commented
Thanks @mmoyle, I haven't deployed your policy changes to aws-terminator yet, when I do that I'll merge that PR and rerun the tests here (it's a straightforward change, looks like it should be fine as-is).  I generally do these once a week on Thursdays.

2020-02-20 09:36 UTC, mmoyle commented
> @mmoyle When the tests finish ansibot's going to get grumpy about the 'merge' commit. Please **rebase** rather than merging devel into your branch.

Thank you for the info. I hopefully cleanly removed the merge. I will leave it alone unless we see a merge conflict with devel.

2020-02-20 22:33 UTC, jillr reviewed
A couple of notes from testing, this is coming along well!

2020-02-20 22:33 UTC, jillr commented on test/integration/targets/cloudformation_exports/tasks/main.yml
> +          - export_items['cf-exports-param'] is defined
This is actually `cf-export-cf-exports-param`, due to https://github.com/ansible/ansible/blob/a4a4c4817d0c8d33ddf8edfd6a0f82c4a746c63d/test/integration/targets/cloudformation_exports/files/test_stack.yml#L24.

2020-02-20 22:33 UTC, jillr commented on test/integration/targets/cloudformation_exports/tasks/main.yml
> +        export_items: "{{ exports_result['export_items']['cf-exports-param'] }}"
```suggestion
        export_items: "{{ exports_result['export_items'] }}"
```
I think here you just want export_items, to match up to the assertions being made.

2020-02-21 12:01 UTC, mmoyle commented
btw @jillr, I just got the integration tests to run locally. But I had to place `cloud-config-aws.ini` in two places. In addition, ansible-test could not find the file if I created a `cloud-config-aws.yml`.

I placed the files in
```
./test/integration/cloud-config-aws.ini
./test/lib/ansible_test/config/cloud-config-aws.ini
```
I ran it as 
```
$ ansible-test integration --docker -v cloudformation_exports
```

2020-02-21 20:23 UTC, tremble requested changes
The code looks good, but I'm going to be annoying and point out that this module should probably be cloudformation_exports_info (or even just an addition to cloudformation_info)

2020-02-21 20:31 UTC, jillr commented
tremble is entirely correct about the module naming - my apologies for the oversight @mmoyle.  I've deployed the CI changes so we should be good after this one last thing.

2020-02-24 20:29 UTC, jillr commented
This looks ready to go - I'm going to hold off on merging it for a couple days however as there's some additional work I will need to do in another repo at the time it merges due to our upcoming migration to [collections](https://github.com/ansible-collections/overview/blob/master/README.rst) and we have a few other open PRs for new modules I would like to do all at the same time. So this is all set, you're just waiting on me to hit the merge button now.  Thanks!

2020-02-27 18:40 UTC, merged