lib/ansible/plugins/inventory: added space between lines for ini error
ansible/ansible pull request #67361
Opened 2020-02-12 21:26 UTC by falcon78921

##### SUMMARY

Added space between lines for error output.

BEFORE:
~~~
[WARNING]:  * Failed to parse /opt/bogus_inv with ini plugin: /opt/bogus_inv:1: Invalid section entry: '[Bogus Copy]'. Please make sure that there are no spacesin the section entry, and that there are no
other invalid characters
~~~

AFTER:
~~~
[WARNING]:  * Failed to parse /opt/bogus_inv with ini plugin: /opt/bogus_inv:1: Invalid section entry: '%s'. Please make sure that there are no spaces in the section entry, and that there are no other
invalid characters
~~~ 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

lib/ansible/plugins/inventory/ini.py

2020-02-19 17:57 UTC, falcon78921 commented
ready_for_review

2020-02-20 20:10 UTC, s-hertel requested changes

2020-02-20 20:10 UTC, s-hertel commented on lib/ansible/plugins/inventory/ini.py
> +                self._raise_error("Invalid section entry: '%s'. Please make sure that there are no spaces" + " " +
```suggestion
                self._raise_error("Invalid section entry: '%s'. Please make sure that there are no spaces" % line + " " +
```

2020-02-24 14:26 UTC, s-hertel approved these changes

2020-02-24 14:26 UTC, merged

2020-02-24 14:27 UTC, s-hertel commented
thanks @falcon78921