s3_bucket: accept NetApp StorageGRID create_bucket response.
ansible/ansible pull request #67462
Opened 2020-02-17 10:04 UTC by r0ckpine

##### SUMMARY

Support StorageGRID S3 API
Fixes #67459 

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

s3_bucket

##### ADDITIONAL INFORMATION

```paste below

```

2020-02-17 11:24 UTC, tremble requested changes
Other than the sanity/linting issue, this PR looks reasonable and it doesn't seem to break the existing s3_bucket integration tests.

NetApp docs are https://docs.netapp.com/sgws-110/index.jsp?topic=%2Fcom.netapp.doc.sg-s3%2FGUID-6E737B19-441A-495F-A35C-9BDC8BA1A4A2.html and seem to imply that XNotImplemented is what it will throw for unsupported functions.

2020-02-17 11:24 UTC, tremble commented on lib/ansible/modules/cloud/amazon/s3_bucket.py
> +        if exp.response['Error']['Code']  not in ('NotImplemented', 'XNotImplemented') or requester_pays:
```suggestion
        if exp.response['Error']['Code'] not in ('NotImplemented', 'XNotImplemented') or requester_pays:
```

2020-02-21 06:15 UTC, r0ckpine commented
ready_for_review

2020-02-21 07:52 UTC, tremble commented
LGTM

Sorry about the s3_bucket test flakes, I've been investigating them.  They seem to be related to our use of us-east-1 for our CI.  (50 runs in us-west-2 and I couldn't trigger it, test in us-east-1 and I get a 15+% failure rate)

2020-02-21 15:58 UTC, tremble commented
bot_status

2020-02-21 16:12 UTC, jillr commented
Thanks @r0ckpine, this looks great but could you please add a [changelog](https://docs.ansible.com/ansible/latest/community/development_process.html#changelogs-how-to) noting the bugfix?

2020-02-24 02:18 UTC, r0ckpine commented
ready_for_review

2020-02-24 20:00 UTC, jillr approved these changes

2020-02-24 20:00 UTC, merged