Update installp.py
ansible/ansible pull request #67676
Opened 2020-02-23 05:34 UTC by roxyland

##### SUMMARY

##### ISSUE TYPE
- Docs Pull Request

+label: docsite_pr

##### SUMMARY

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2020-02-24 04:38 UTC, Akasurde requested changes
@roxyland Thanks for the PR. Could you please add a change log entry [here](https://github.com/ansible/ansible/tree/devel/changelogs/fragments)?

2020-02-24 19:27 UTC, samccann approved these changes

2020-02-24 19:28 UTC, merged

2020-02-24 19:28 UTC, samccann commented
Thanks @roxyland for the Ansible documentation fix!  @Akasurde - we don't typically ask for changelogs for minor docs fixes.

2020-02-25 03:31 UTC, Akasurde commented
@samccann Got it. Thanks for the info. @roxyland Thanks for the contribution.