Fix for #67423 ansible issue
ansible/ansible pull request #67849
Opened 2020-02-28 09:59 UTC by Vaishnavi-infoblox

##### SUMMARY

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2020-02-28 10:00 UTC, Vaishnavi-infoblox commented
Fix for #67423

2020-02-28 15:28 UTC, megabreit commented
@Vaishnavi-infoblox You added only 5 number options but there are 8 name options. Just want to make sure this is no typo...

2020-02-28 15:41 UTC, Akasurde commented on lib/ansible/modules/net_tools/nios/nios_fixed_address.py
> +    special_num =  [3, 6 , 15, 28, 51]
```suggestion
    special_num =  [3, 6, 15, 28, 51]
```

2020-02-28 15:43 UTC, Akasurde commented on lib/ansible/modules/net_tools/nios/nios_fixed_address.py
> +        if 'name' in opt:
```suggestion
        if 'name' in opt and opt['name'] not in special_options:
```

2020-02-28 15:43 UTC, Akasurde commented on lib/ansible/modules/net_tools/nios/nios_fixed_address.py
> +        if 'num' in opt:
```suggestion
        if 'num' in opt and opt['num'] not in special_num:
```

2020-02-28 15:46 UTC, Akasurde requested changes
Please add correct title and description so that it will convey why this change is made in first place.

2020-03-02 10:45 UTC, Vaishnavi-infoblox commented
> @Vaishnavi-infoblox You added only 5 number options but there are 8 name options. Just want to make sure this is no typo...

options-router-templates, broadcast-address-offset, dhcp6.name-servers don't have any associated number

2020-03-02 10:45 UTC, closed without merging