Allow list of filters for the setup module
ansible/ansible pull request #68551
Opened 2020-03-30 10:00 UTC by fatpat

##### SUMMARY
The setup module can now filter out multiple pattern by providing a list to the filter parameter instead of just a string. The default behavior and single string filtering still work as before. But instead of calling the setup module multiple times to filter out multiple facts, it can now be called only once with multiple filtering with an important speed improvement. 

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
- modules/system/setup
- module_utils/facts/ansible_collector

##### ADDITIONAL INFORMATION
In a task, when only some facts must be gathered (and cached) the only solution was to use the `setup` module with the `filter` parameter  called multiple times (with a `loop`) like below:
```
tasks:
  - setup:
      filter: "{{ item }}"
    loop:
      - 'ansible_machine_id'
      - 'ansible_distribution'
```

It implies that the setup modules is called several times doing the same work and only filtering out the one element that needs to be selected. This is a waste of time and can quickly get painfull with a large number of hosts and of filters.

This patch allow to pass a list of filters to the setup module. This way, the setup module is called only once and the filtering is done once also for each filters. See below:
```
tasks:
  - setup:
      filter: 
        - 'ansible_machine_id'
        - 'ansible_distribution'
```

2020-04-09 19:14 UTC, sivel requested changes
Please provide a changelog in `changelogs/fragments` for this change.

2020-04-10 05:00 UTC, fatpat commented
> Please provide a changelog in `changelogs/fragments` for this change.

done

2020-06-24 12:52 UTC, fatpat commented
tag v2.10.0b1 has been released and yet this simple PR has not been merge. It's been 3 month.

can someone please merge this ?

2020-09-09 16:10 UTC, sivel commented
rebuild_merge

2020-09-09 18:40 UTC, merged