Update BOTMETA
ansible/ansible pull request #68639
Opened 2020-04-02 14:00 UTC by NilashishC

Signed-off-by: NilashishC <nilashishchakraborty8@gmail.com>

##### SUMMARY
- Update BOTMETA with new changes

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
.github/BOTMETA.yml

2020-04-02 16:08 UTC, justjais requested changes

2020-04-02 16:08 UTC, justjais commented on .github/BOTMETA.yml
> -  team_asa: NilashishC ogenstad
@NilashishC u can add my username under asa

2020-04-03 05:31 UTC, NilashishC commented on .github/BOTMETA.yml
> -  team_asa: NilashishC ogenstad
Done.

2020-04-03 05:35 UTC, justjais approved these changes

2020-04-03 13:40 UTC, gundalow reviewed
You'll need to make these changes in `community.network` once that repo is live.

2020-04-06 09:51 UTC, NilashishC commented
> You'll need to make these changes in `community.network` once that repo is live.

@gundalow ack.

2020-04-06 09:52 UTC, merged

2020-04-08 06:33 UTC, gundalow commented
@NilashishC can you please make these changes in community.network as well. Thanks.