Replace the use of the function string.replace with the method str.replace
ansible/ansible pull request #68793
Opened 2020-04-09 02:19 UTC by lparkes

##### SUMMARY
Python 3 no longer has the module function `string.replace`, but it still shares the `str` method `replace` with Python 2. This PR replaces both uses of `string.replace()` in the Ansible source code with `str.replace()`. 

I also fixed a typo in a nearby comment.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
service

##### ADDITIONAL INFORMATION
A couple of bits of code for managing BSD rc.conf style service configuration files still used the obsolete `string.replace()` function.

I have successfully tested this with the following trivial playbook
```
- hosts: fog
  tasks:
  - name: NTP service
    service:
      name: ntpd
      enabled: yes
```

2020-04-09 15:18 UTC, sivel requested changes
`import string` can also be removed.  Additionally, this should include a changelog fragment in `changelogs/fragments`

2020-04-09 21:38 UTC, lparkes commented
Changes made.

2020-05-11 14:37 UTC, sivel approved these changes

2020-08-08 03:28 UTC, lparkes commented
Well, that rebase didn't work. The diff looked fine, so I'll dig into what git-fu I'm missing.

2020-08-10 11:08 UTC, Akasurde commented
@lparkes Could you please rebase this branch? You can use this guide - https://docs.ansible.com/ansible/latest/dev_guide/developing_rebasing.html

2020-08-10 22:52 UTC, lparkes commented
Thanks for pointing me at the documentation for the Github magic. This rebase has one fewer parents in the revision history and Github is sure to be happier with that. Please hold on while I double check that I have got all the Python 2 out of service.py. I (re)discovered another one in service.py over the weekend and I need double check that I've included it. It would be anoying to have to create another PR for the same sort of problem in the same source file.

2020-08-10 23:10 UTC, lparkes commented
I added in a string to bytes conversion to keep os.write() happy. I would like to write a test for this, but a quick look shows me that this will require quite a bit of reading on my part.

2020-08-10 23:16 UTC, lparkes commented
I don't know of any remaining Python 2 code in the rcconf service support, so I'm happy for this to be merged.

2020-12-27 00:13 UTC, lparkes commented
I've rebased the PR again in order to trigger new CI tests.

2021-01-05 16:20 UTC, merged

2021-01-05 16:21 UTC, bcoca commented
@Iparkes  this is a good candidate for backporting, if you are interested https://docs.ansible.com/ansible/latest/community/development_process.html#backporting-merged-prs-in-ansible-base