Add support for regex section names in ini lookup
ansible/ansible pull request #69048
Opened 2020-04-20 17:45 UTC by RomFouq

##### SUMMARY
Add support for regex section names in ini lookup.
Useful when the section name cannot be entirely predicted.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
plugins/lookup/ini.py

2020-09-01 15:46 UTC, bcoca commented
add tests and changelog

2020-09-02 14:26 UTC, Shrews requested changes

2020-09-02 14:26 UTC, Shrews commented on lib/ansible/plugins/lookup/ini.py
> +          - Requires the C(re) flag to be set to C(True).
Why are you going to require `re` to be `True`? I feel like that restricts this usefulness of this feature. For example, I could see someone wanting to do something similar to this:

```
    - debug:
        msg: "{{ item }}"
      with_ini:
        - 'user section=da* file=users.ini re_section=True'
```

I think that should be supported.

2021-05-30 15:43 UTC, Akasurde commented
@RomFouq Could you please rebase and create a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment)? See [this fragment](https://github.com/ansible/ansible/blob/c2f528b7686c9573aa8493357219e0bbe4416dd3/changelogs/fragments/reboot-change-default-boot-command.yaml) as an example. Also, add tests for this change.

needs_info

2021-08-02 17:15 UTC, closed without merging