Update to fix #64031
ansible/ansible pull request #69163
Opened 2020-04-25 00:11 UTC by coolnothing

##### SUMMARY
1, Add python path for OS400 platform
2, Add a new collector to collect system info about OS400 platform

Fixes #64031
##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME

gather_facts or setup

2020-06-09 01:49 UTC, coolnothing commented
Could you help to merge this PR?
Since we can not put this in collections, If this PR is not merged, our customer can not use the collections either.

2020-07-07 17:51 UTC, kadler requested changes
AFAICT, we should _not_ be using itoolkit at all here. As I intend to remove the SQL interfaces in a future version of itoolkit, I would recommend against adding more dependencies to them, especially when it's completely pointless as we already have an SQL interface with ibm_db.

2020-07-07 17:51 UTC, kadler commented on lib/ansible/module_utils/facts/virtual/ibmi.py
> +            sql = "SELECT SYSTEM_VALUE_NAME,CURRENT_NUMERIC_VALUE,CURRENT_CHARACTER_VALUE FROM QSYS2.SYSTEM_VALUE_INFO"
Why are we calling SQL through itoolkit over a database connection instead of just passing the SQL through the database connection itself?

2020-07-07 17:51 UTC, kadler commented on lib/ansible/module_utils/facts/virtual/ibmi.py
> +    HAS_IBM_DB = False
This is never checked anywhere

2022-04-04 15:15 UTC, ThePrez commented
@coolnothing , are you able to clean up the code per @kadler's comments? I find the lack of python interpreter issue ( #77458 is very pervasive for IBM i users)

2022-08-24 19:09 UTC, nitzmahone commented
This really belongs in an IBM i specific collection- we're not generally adding support for new platforms to the core facts modules since they can be configured and invoked automatically via inventory when gather_facts or the `setup` module is run (eg, `ansible_facts_modules=yourns.yourcoll.yourfactmodule`).

2022-08-24 19:09 UTC, closed without merging