Preserve file premissions of file used in known_hosts module
ansible/ansible pull request #69231
Opened 2020-04-29 07:08 UTC by Akasurde

##### SUMMARY

Due to known issue in ssh-keygen, file permissions are lost.
known_hosts module uses ssh-keygen and ultimately changes the file
permission advertenly. This PR restores the given permissions for the
file used.

Fixes: #68795

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
changelogs/fragments/68795_known_hosts.yml
lib/ansible/modules/system/known_hosts.py
test/integration/targets/known_hosts/tasks/main.yml

2020-04-29 09:24 UTC, Akasurde commented
Fixes: https://github.com/ansible/ansible/issues/29331

2020-04-29 19:30 UTC, bcoca commented on lib/ansible/modules/system/known_hosts.py
> +    prev_mode = os.stat(path)
i would add if os.path.exists check, then default to a 'safe/secure' default on else

2020-04-30 22:36 UTC, mattclay commented on lib/ansible/modules/system/known_hosts.py
> +    prev_mode = 33188
Setting the default is not needed since it's always overwritten before use.

2020-06-26 16:24 UTC, mattclay requested changes

2020-06-26 16:24 UTC, mattclay commented on lib/ansible/modules/known_hosts.py
> +        module.fail_json(msg="Failed to find file %s" % path)
This check appears unnecessary, since the `stat` call below will also provide a user-friendly error message if the file does not exist.

2021-01-20 12:59 UTC, Akasurde commented
recheck

2021-01-22 15:56 UTC, s-hertel commented
This should probably done in common code rather than special-casing/reinventing the wheel for known_hosts. See the copy module as an example of using preserve permissions with standard functions.

2021-01-22 15:56 UTC, closed without merging