Updated CLI help for 'ansible-galaxy' for 'collection' subcommand
ansible/ansible pull request #69458
Opened 2020-05-12 16:28 UTC by biradarganesh25

##### SUMMARY

On giving an invalid subcommand to ansible-galaxy, the argparse help output for ansible-galaxy (the same as running `ansible-galaxy --help`) is also displayed along with the error displayed by argparse.

Fixes #69009 
##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

ansible-galaxy
##### ADDITIONAL INFORMATION

Before this change giving an invalid subcommand to ansible-galaxy would result in:
```
(venv) ganeshb@LAPTOP-QANFFN26:~/Documents/ansible$ ansible-galaxy doesnotexist
[WARNING]: You are running the development version of Ansible. You should only run Ansible from "devel" if you are modifying the Ansible engine, or trying out features under development.
This is a rapidly changing source of code and can become unstable at any point.
usage: ansible-galaxy role [-h] ROLE_ACTION ...
ansible-galaxy role: error: argument ROLE_ACTION: invalid choice: 'doesnotexist' (choose from 'init', 'remove', 'delete', 'list', 'search', 'import', 'setup', 'login', 'info', 'install')
```
Here the help shown does not include help for collection subcommand. This might lead to some confusion. After the change, the output is:
```
(venv) ganeshb@LAPTOP-QANFFN26:~/Documents/ansible$ ansible-galaxy doesnotexist                                                                                                            
[WARNING]: You are running the development version of Ansible. You should only run Ansible from "devel" if you are modifying the Ansible engine, or trying out features under development. 
This is a rapidly changing source of code and can become unstable at any point.                                                                                                            
usage: ansible-galaxy role [-h] ROLE_ACTION ...                                                                                                                                            
ansible-galaxy role: error: argument ROLE_ACTION: invalid choice: 'doesnotexist' (choose from 'init', 'remove', 'delete', 'list', 'search', 'import', 'setup', 'login', 'info', 'install') 
                                                                                                                                                                                           
usage: ansible-galaxy [-h] [--version] [-v] TYPE ...                                                                                                                                       
                                                                                                                                                                                           
Perform various Role and Collection related operations.                                                                                                                                    
                                                                                                                                                                                           
positional arguments:                                                                                                                                                                      
  TYPE                                                                                                                                                                                     
    collection   Manage an Ansible Galaxy collection.                                                                                                                                      
    role         Manage an Ansible Galaxy role.                                                                                                                                            
                                                                                                                                                                                           
optional arguments:                                                                                                                                                                        
  --version      show program's version number, config file location,                                                                                                                      
                 configured module search path, module location, executable                                                                                                                
                 location and exit                                                                                                                                                         
  -h, --help     show this help message and exit                                                                                                                                           
  -v, --verbose  verbose mode (-vvv for more, -vvvv to enable connection                                                                                                                   
                 debugging)                                                                                                                                                                
```
Here the additional help is also displayed. This makes it much more clearer. I have attached the sanity test output here. 
[test.txt](https://github.com/ansible/ansible/files/4616956/test.txt)
tldr of tests:

```
ERROR: The 2 sanity test(s) listed below (out of 54) failed. See error output above for details.
pylint
rstcheck
```
The reason for their failure is not due to this particular change.

2020-05-14 19:33 UTC, Shrews requested changes
Can we get a changelog for this?

2020-05-15 05:39 UTC, biradarganesh25 commented
Sure, I'll work on it

2020-05-16 06:49 UTC, biradarganesh25 commented
I've added the changelog, but the shippable tests are failing... I do not think it's due to the new changes (I verified changelog is correct by running the changelog sanity test). Should I try to run shippable again or is this fine?

2020-05-16 13:47 UTC, biradarganesh25 commented
All right it seems to have been a temporary error.

2020-05-28 14:20 UTC, biradarganesh25 commented
@Shrews Should I do something else here? Or will it be merged later?

2020-05-28 14:30 UTC, Shrews approved these changes

2020-05-28 14:38 UTC, samdoran approved these changes

2020-05-28 14:38 UTC, merged