docs: Proposal: list playbook keywords with "Applies to" flags
ansible/ansible pull request #69656
Opened 2020-05-21 20:23 UTC by moreati

##### SUMMARY
The [playbook keywords reference](https://docs.ansible.com/ansible/devel/reference_appendices/playbooks_keywords.html) is currently organised by category, then applicable keywords.

I propose reorganising this, to list all keywords at the top level, each with an "Applies to" block. The PR shows a demonstrator. It isn't intended to as a polished, styled final design. 

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION
The motivations for this proposed reorganisation are

- Make it easy to link to one canonical reference for a given keyword
- Make it easier to see what categories/levels a given keyword applies to
- Reduce repetition of keyword descriptions on the page

I hope the following table and screenshot illustrate the concept

<table>
<tr>
<th>Current organisation
<th>Proposed organisation
<tr>
<td>

**Play**

any_errors_fatal
&nbsp;&nbsp;    [description]

become
&nbsp;&nbsp;    [description]

...

**Role**

any_errors_fatal
&nbsp;&nbsp;    [description]

become
&nbsp;&nbsp;    [description]

...

<td>

**action**

Applies to: ✗ Play ✗ Role ✗ Block ✓ Task

[description]

**always**

Applies to: ✗ Play ✗ Role ✓ Block ✗ Task

[description]

...
</table>

![image](https://user-images.githubusercontent.com/174450/82602518-1dcd6600-9ba9-11ea-807b-0ea7f972e797.png)

2020-06-16 18:35 UTC, acozine commented
This is an interesting enhancement, thanks @moreati. We are in the midst of changing our docs pipeline to work with collections, so it may take us some time to get to this.

2020-06-17 15:12 UTC, bcoca requested changes
some people prefer to look at it by the object, I would prefer to not replace the existing page but compliment it and have each link to each other.

2020-06-17 17:43 UTC, moreati commented
> compliment it and have each link to each other

I'll iterate the prototype on that basis

2024-09-15 09:33 UTC, moreati commented
I didn't iterate, and now the docs have moved to https://github.com/ansible/ansible-documentation/. As a rough and ready one off, I've generated a table https://gist.github.com/moreati/d7cb1573e8f00dd320d6569bb35b5f61. I may revisit this in a new PR to the migrated repo.

2024-09-15 09:33 UTC, closed without merging