Add seed parameter to password lookup
ansible/ansible pull request #69775
Opened 2020-05-30 13:40 UTC by s-hamann

##### SUMMARY
This PR adds a `seed` parameter to the `password` lookup plugin. This allows for idempotently generating random passwords, in particular when not saving them to a local file. This matches the `random`, `shuffle` and `random_mac` filters.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
password

##### ADDITIONAL INFORMATION
Usage example:
```
- set_fact:
    password: "{{ lookup('password', '/dev/null seed=inventory_hostname }}"
```

Obviously, I guessed at the `version_added` part of the documentation. Please tell me if I was too optimistic or just change it yourself :)

2020-06-01 11:08 UTC, Akasurde commented on lib/ansible/plugins/lookup/password.py
> +        version_added: "2.11"
```suggestion
        version_added: "2.10"
```

2020-06-01 11:09 UTC, Akasurde commented on lib/ansible/plugins/lookup/password.py
> +        description: A seed to initialize the random number generator. Identical seeds will yield identical passwords. Use this for random-but-idempotent password generation.
```suggestion
        description:
        - A seed to initialize the random number generator.
        - Identical seeds will yield identical passwords.
        - Use this parameter for random but idempotent password generation.
```

2020-06-01 11:20 UTC, s-hamann commented
Thank you @Akasurde, changed as suggested.

2020-06-01 12:53 UTC, Akasurde commented on test/units/plugins/lookup/test_password.py
> +        params=dict(length=password.DEFAULT_LENGTH, encrypt=None, chars=DEFAULT_CHARS, seed=1),
```suggestion
        params=dict(length=password.DEFAULT_LENGTH, encrypt=None, chars=DEFAULT_CHARS, seed='1'),
```

2020-06-01 12:53 UTC, Akasurde commented on test/units/plugins/lookup/test_password.py
> +        params=dict(length=password.DEFAULT_LENGTH, encrypt=None, chars=DEFAULT_CHARS, seed=1),
This will fix the testcase.

2020-07-20 18:57 UTC, bmillemathias-1a commented
/rebuild_failed

2021-03-17 19:32 UTC, samdoran commented
/azp run

2021-05-27 15:48 UTC, Akasurde commented
@samdoran Could you please review this? I updated the code and tests. LGTM.

2021-06-02 16:20 UTC, samdoran requested changes

2021-06-02 16:20 UTC, samdoran commented on lib/ansible/plugins/lookup/password.py
> +    password: "{{ lookup('password', '/dev/null seed=inventory_hostname') }}"
This won't do what you think. `'/dev/null seed=inventory_hostname'` is passed in to the lookup as a literal string. `inventory_hostname` is not interpolated.

The lookup system [recently moved](https://github.com/ansible/ansible/commit/84e473a26ea95afec207409c42ba872c009fe6b6) to accepting kwargs rather than a single string. Using kwargs, the value of `inventory_hostname` would be passed in as the seed. `lookup('password', '/dev/null', seed=inventory_hostname)`.

However, this particular plugin was missed in the move to kwargs. I'll open a separate PR to get that fixed. Otherwise this example would need to change in order to use the inventory_hostname as the seed. 😱 

```
lookup('password', '/dev/null seed=' ~ inventory_hostname)
```

2021-06-02 16:20 UTC, samdoran commented on lib/ansible/plugins/lookup/password.py
> +          - Use this for random-but-idempotent password generation.
```suggestion
          - Use this for random-but-consistent password generation.
```

2021-06-02 16:20 UTC, samdoran commented on test/units/plugins/lookup/test_password.py
> +                    chars=sorted([u'abcdefghijklmnop', u',', u'digits']), seed=None),
This does not need to be wrapped.

2021-06-02 16:20 UTC, samdoran commented on test/units/plugins/lookup/test_password.py
> +                    chars=[u','], seed=None),
This does not need to be wrapped.

2021-06-02 16:20 UTC, samdoran commented on test/units/plugins/lookup/test_password.py
> +                    chars=sorted([u'digits', u'=', u',']), seed=None),
This does not need to be wrapped.

2021-06-02 16:20 UTC, samdoran commented on test/units/plugins/lookup/test_password.py
>          candidate_chars=u'abc=def0123456789',
This does not need to be wrapped.

2021-06-02 16:20 UTC, samdoran commented on test/units/plugins/lookup/test_password.py
> +                    chars=sorted([u'digits', u'くらとみ', u',']), seed=None),
This does not need to be wrapped.

2021-06-02 16:20 UTC, samdoran commented on test/units/plugins/lookup/test_password.py
> +                    chars=sorted([u'くらとみ']), seed=None),
This does not need to be wrapped.

2021-06-02 16:20 UTC, samdoran commented on test/units/plugins/lookup/test_password.py
> +                    chars=sorted([u'ascii_letters', u'digits']), seed=None),
This does not need to be wrapped.

2021-06-02 16:20 UTC, samdoran commented on test/units/plugins/lookup/test_password.py
> +                    chars=sorted([u'digits', u'abc', u'def']), seed=None),
This does not need to be wrapped.

2021-06-02 21:03 UTC, s-hamann commented on lib/ansible/plugins/lookup/password.py
> +          - Use this for random-but-idempotent password generation.
Not that I'm opposed to your suggestion, but Ansible's documentation on filters uses the term 'random-but-idempotent' to describe the `seed` parameter for `random` and `random_mac`. I think it's more consistent to stick with that.

2021-06-02 21:16 UTC, s-hamann commented on lib/ansible/plugins/lookup/password.py
> +    password: "{{ lookup('password', '/dev/null seed=inventory_hostname') }}"
Thank you for pointing that out. Now that I think about it, it seems obvious...
I changed the example to use the kwargs format and trust that your PR get merged quickly enough :wink:
The other examples do not use the kwargs format, so this looks slightly out-of-place to me. But that's a topic for another pull request.

2021-06-02 21:19 UTC, s-hamann commented on test/units/plugins/lookup/test_password.py
> +                    chars=sorted([u'abcdefghijklmnop', u',', u'digits']), seed=None),
@Akasurde formatted it like this, so I'll leave it to you two to sort out the preferred style :wink:

2021-06-03 05:37 UTC, Akasurde commented on test/units/plugins/lookup/test_password.py
> +                    chars=sorted([u'abcdefghijklmnop', u',', u'digits']), seed=None),
I blame my `black` setting.

2021-06-03 05:38 UTC, Akasurde commented on test/units/plugins/lookup/test_password.py
> +                    chars=sorted([u'digits', u'abc', u'def']), seed=None),
Blame my `black` settings.

2021-06-03 19:00 UTC, samdoran commented on lib/ansible/plugins/lookup/password.py
> +    password: "{{ lookup('password', '/dev/null seed=inventory_hostname') }}"
Yeah, I will cleanup the examples in my PR to add kwargs support.

2021-06-03 19:01 UTC, samdoran commented on lib/ansible/plugins/lookup/password.py
> +          - Use this for random-but-idempotent password generation.
I'm not a fan of the "I" word because it's quite jargon-y. But I'll yield to consistency for the time being.

2021-06-04 16:20 UTC, samdoran approved these changes

2021-06-04 16:20 UTC, merged