ansible-doc: properly handle suboptions
ansible/ansible pull request #69795
Opened 2020-06-01 08:51 UTC by felixfontein

##### SUMMARY
Right now, suboptions for module/plugin options are simply dumped as YAML (excerpt from `ansible-doc docker_container`):
```
- device_read_bps
        List of device path and read rate (bytes per second) from device.
        [Default: (null)]
        elements: dict
        suboptions:
          path:
            description:
            - Device path in the container.
            required: true
            type: str
          rate:
            description:
            - Device read limit in format `<number>[<unit>]'.
            - Number is a positive integer. Unit can be one of `B' (byte), `K' (kibibyte,
              1024B), `M' (mebibyte), `G' (gibibyte), `T' (tebibyte), or `P' (pebibyte).
            - Omitting the unit defaults to bytes.
            required: true
            type: str
        
        type: list
```
This PR adjusts it so they are pretty-printed like top-level options:
```
- device_read_bps
        List of device path and read rate (bytes per second) from device.
        [Default: (null)]
        elements: dict
        type: list

        SUBOPTIONS:

        = path
            Device path in the container.

            type: str

        = rate
            Device read limit in format `<number>[<unit>]'.
            Number is a positive integer. Unit can be one of `B' (byte), `K' (kibibyte, 1024B), `M' (mebibyte), `G'
            (gibibyte), `T' (tebibyte), or `P' (pebibyte).
            Omitting the unit defaults to bytes.

            type: str
```

##### ISSUE TYPE
- Docs Pull Request
- Feature Pull Request

##### COMPONENT NAME
ansible-doc

2020-06-02 15:42 UTC, samdoran requested changes
Can you please add tests for this change?

2020-06-07 13:23 UTC, felixfontein commented
/rebuild_failed

2020-06-08 15:24 UTC, samdoran approved these changes

2020-06-08 15:51 UTC, merged

2020-06-08 15:53 UTC, felixfontein commented
@samdoran @bcoca thanks for reviewing and merging!