Use fqcr from command module invocation using shell module
ansible/ansible pull request #69790
Opened 2020-06-01 06:59 UTC by ganeshrn

##### SUMMARY

Fixes https://github.com/ansible/ansible/issues/69788

Use fully qualified collection reference while invoking
command module from shell module

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

shell
##### ADDITIONAL INFORMATION

```paste below

```

2020-06-01 16:07 UTC, nitzmahone commented
IMO this is the "right thing" anywhere we call a module/action internally, though we've sorta allowed people to replace the builtins in the past with local `library/` (etc) versions. I think the original issue is caused by something this doesn't address though: these internal redirections, even if we want to continue to allow non-collections overrides, should *never* be using the collections search path to find things. But, it looks like they are, since it found something outside the core routing metadata- I'll look into that.

2020-06-02 16:53 UTC, bcoca requested changes
As already mentioned, this breaks backwards compatibility.

2020-06-02 22:57 UTC, nitzmahone commented
Hrm, looking at that closer, it's not even passing `collection_list` to `PluginLoader.get()`, so it shouldn't be possible for it to find that override... @ganeshrn are you sure you don't have an ansible-base routing entry for a command action/module, or a local library `command` module somewhere?

I'm not seeing how this could hit the behavior you're describing, and if it is, there's a nastier bug lurking...

For these internal cases, we might want to consider deprecating the local override capability (eg overriding `normal` on action- if you want to do that, use your own action).

2020-06-03 23:33 UTC, nitzmahone commented
As I mentioned over on #69788 - I think the actual "right thing" to do here is to change this ref to `ansible.legacy.command`- that will do the legacy library search, followed by a fallback search to `ansible.builtin`, which is exactly the behavior you want here to preserve the legacy local override capability (and the reason `ansible.legacy` exists).

2020-06-04 02:17 UTC, bcoca commented
this is still patching the bug for a single plugin while leaving it existing for the rest, while im not against merging this AFTER we fix the actual bug, it is not a full fix.

2020-06-04 02:17 UTC, bcoca requested changes

2020-06-04 02:17 UTC, bcoca commented on lib/ansible/plugins/action/shell.py
> +        command_action = self._shared_loader_obj.action_loader.get('ansible.builtin.command',
s/ansible.builtin/ansible.legacy/

2020-06-04 05:05 UTC, ganeshrn commented on lib/ansible/plugins/action/shell.py
> +        command_action = self._shared_loader_obj.action_loader.get('ansible.builtin.command',
Fixed

2020-06-04 17:00 UTC, merged