better porting entry for key bool fix
ansible/ansible pull request #69948
Opened 2020-06-08 15:03 UTC by bcoca

alt fixes #69786

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

playbook

2020-06-08 16:59 UTC, samdoran requested changes
RST is hard.

Also, I dug through this a bit more and it does seem the fields _do_ get templated here: https://github.com/ansible/ansible/blob/f23498440f9628f69d0323ab5c42035e8ab34668/lib/ansible/playbook/base.py#L431

Which is called from here `post_validate()` https://github.com/ansible/ansible/blob/f23498440f9628f69d0323ab5c42035e8ab34668/lib/ansible/executor/task_executor.py#L540-L540

I found that if the _entire_ field is a valid Jinja expression, it will get a templated value that will later satisfy the `boolean()` test.

` diff: "{{ not dont_show_diff }}`

If only the variable is wrapped, it does get templated properly but later fails the `boolean()` test:
`diff: not {{ dont_show_diff }}`

```
 0.5s template(<ansible.template.Templar object>, 'not {{ dont_show_diff }}')
 0.5s   template(<ansible.template.Templar object>, True)
 0.5s   -> True
 0.5s -> 'not True'
```

That's a long way of asking whether or not we should include an example/recommendation to have the entire field value be written in a such a way that the templated result evaluates to a value that will satisfy the `boolean()` test.

2020-06-08 16:59 UTC, samdoran commented on docs/docsite/rst/porting_guides/porting_guide_2.10.rst
> +  Some playbooks would have seemed to be working as random strings would evaluate as `True`.
```suggestion
  Some playbooks would have seemed to be working as random strings would evaluate as ``True``.
```

2020-06-08 16:59 UTC, samdoran commented on docs/docsite/rst/porting_guides/porting_guide_2.10.rst
> +  This looked like the value was being templated, but this was not the case. It evaluated to `True` not because the expression `not dont_show_diff` would be so in Jinja, instead it was due to a 'non
```suggestion
  This looked like the value was being templated, but this was not the case. It evaluated to ``True`` not because the expression ``not dont_show_diff`` was evaluated by Jinja, but instead due to a 'non-empty string', which is 'truthy' in Python and Jinja.  The expression ``diff: dont_show_diff`` would also be ``True`` previously.
```

2020-06-08 16:59 UTC, samdoran commented on docs/docsite/rst/porting_guides/porting_guide_2.10.rst
> +    When there is an error templating with `no_log` it defaults to `True`, to be on the safe side, so this might obscure the issue is due to this change.
```suggestion
    When there is an error templating with ``no_log`` it defaults to ``True`` to be on the safe side, so this might obscure that real the issue is due to this change.
```

2020-06-08 16:59 UTC, samdoran commented on docs/docsite/rst/porting_guides/porting_guide_2.10.rst
> +  This applies for every keyword that would take a boolean as a value (check_mode, no_log, become, run_once, ...), but not conditionals (`*when:`).
```suggestion
  This applies for every keyword that would take a boolean as a value (check_mode, no_log, become, run_once, ...), but not conditionals (``*when:``).
```

2020-06-08 19:10 UTC, bcoca commented
@samdoran yes, it got sent to templating, but it would look like a string and return a string not a templated result.

2020-06-08 20:26 UTC, samdoran commented
From a simple porting guide perspective, I think it would be helpful to have an example of "this used to work, but now you have to do this". Now that I understand what's happening in the code, it's obvious that the entire field value needs to be a valid boolean value, but that's probably not obvious to most playbook authors who may think all fields get templated more or less the same.

Maybe @willthames could chime in with his perspective.

2020-06-08 20:53 UTC, bcoca commented
well, the issue is that it DIDN'T work .. just appeared to do so for 'truth' values as all strings are true, which i do show an example of. adding 'correct' example anyways.

2020-06-08 23:53 UTC, willthames commented
@bcoca this explanation doesn't seem entirely satisfactory to me. It's not that my code wasn't working in 2.9 but I just thought that it was - I could change `unsafe_show_logs` between true and false in my playbook in 2.9 and have the desired effect:

```
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    unsafe_show_logs: yes

  tasks:
    - name: can we control no log?
      debug:
        msg: top secret
      no_log: not (unsafe_show_logs | bool)
```

logs as expected (i.e. the value of `no_log` is being evaluated to `False`)

so as such I don't believe this porting note is entirely correct - the behaviour isn't entirely due to a changing of whether a string is truthy or not

2020-06-09 01:26 UTC, bcoca commented
@willtahmes I added tests for this behaviour, but not specifically for no_log, i'll try looking at that since we do treat is 'special' in many cases (as note implies), but this was a generic fix for the 'boolean' type keywords and it does work as I stated for the subset we do test.

2020-06-11 13:55 UTC, bcoca commented
```
- hosts: localhost
  gather_facts: no
  tasks:
    - name: can we control no log?
      debug:
        msg: top secret
      no_log: not (unsafe_show_logs | bool)
      ignore_errors: true
      vars:
        unsafe_show_logs: no
    - name: can we control no log?
      debug:
        msg: top secret
      no_log: not (unsafe_show_logs | bool)
      vars:
        unsafe_show_logs: yes
```

in 2.9 there is no difference as it is incorrectly evaluated:
```
PLAY [localhost] **********************************************************************************************************************************************************************************

TASK [can we control no log?] *********************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "top secret"
}

TASK [can we control no log?] *********************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "top secret"
}

PLAY RECAP ****************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

in devel, also no difference, but for different reason:
```

PLAY [localhost] **********************************************************************************************************************************************************************************

TASK [can we control no log?] *********************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result"}
...ignoring

TASK [can we control no log?] *********************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result"}

PLAY RECAP ****************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=1
```

Aside from the PR referenced above changing the nature of 'boolean keyword evaluation', no_log had also been updated to default to `True` on any error on templating the value.

2020-06-11 14:32 UTC, willthames commented on docs/docsite/rst/porting_guides/porting_guide_2.10.rst
> +* The ``no_log`` keyword has been modified to act in a more secure manner, if there is a value assigned and a templating or type conversion error happens, it defaults to ``True`` instead of it' snorm
typo: `it' snormal`

2022-05-26 18:05 UTC, samccann commented
@bcoca 2.10 is EOL at this point so I'm inclined to close this PR. Let me know if you or anyone else feels differently...

2022-06-16 18:26 UTC, closed without merging