'groups' is a list, update examples to suit
ansible/ansible pull request #70035
Opened 2020-06-12 06:38 UTC by ad8-bdl

##### SUMMARY
`groups` is documented as a list, the current example could be improved to show it as such.

Also, the current example raises a "Incorrect type. Expected "array"." warning from RedHat's VSCode YAML extension.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
user module

##### ADDITIONAL INFORMATION
n/a

2020-06-15 15:52 UTC, bcoca commented
example is correct, 'comma separated string' is valid in list fields

2020-06-16 00:48 UTC, ad8-bdl commented
As someone new to Ansible, it seems correct to me that when the documentation says a key is a list, it ought to look list(array)-like. I was actually wondering why it wasn't a "list" before the linter highlighted it.

I'm no YAML expert, but this page and others I've tried tells me that a comma-separated string of words is not a list: https://yaml-online-parser.appspot.com/?yaml=k1%3A+a%2Cb%2Cc%0Ak2%3A+%5Ba%2Cb%2Cc%5D&type=json

From what I can tell from the code, the comma-separated string is an artefact of the previous specification.

FWIW https://docs.ansible.com/ansible/latest/modules/python_requirements_info_module.html#python-requirements-info-module has a similarly defined list, as an array.

2020-06-16 01:47 UTC, bcoca commented
Ansible does not require a user to be a programmer, for most a list is `a,b,c`, no need to know it requires bracket notation in most languages. You can probably find many examples both ways, both are valid.

2020-06-16 01:48 UTC, bcoca requested changes
no need to change, existing examples are correct

2020-06-16 15:07 UTC, samdoran commented
Closing per above. We have no plans to disallow comma separated strings in list fields. That is a a feature not a bug.

2020-06-16 15:07 UTC, closed without merging