[WIP] botmeta: exoscale migrated to ngine_io.exoscale
ansible/ansible pull request #70095
Opened 2020-06-16 14:19 UTC by resmo

##### SUMMARY
exoscale related modules migrated to dedicated collection. 

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME
exoscale

##### ADDITIONAL INFORMATION

```paste below

```

2020-06-24 13:29 UTC, gundalow approved these changes

2020-06-24 13:39 UTC, gundalow requested changes

2020-06-24 13:39 UTC, gundalow commented on lib/ansible/config/ansible_builtin_runtime.yml
>      dnsmadeeasy:
Missing module_utils from here

2020-06-26 11:54 UTC, felixfontein commented on lib/ansible/config/ansible_builtin_runtime.yml
>      dnsmadeeasy:
Also doc_fragments.

2020-07-02 21:46 UTC, resmo commented
ready_for_review

2020-07-02 22:01 UTC, felixfontein commented on lib/ansible/config/ansible_builtin_runtime.yml
> +      redirect: ngine.io.exoscale.exoscale
```suggestion
      redirect: ngine_io.exoscale.exoscale
```

2020-07-02 22:07 UTC, resmo commented
@felixfontein good catch. Thanks

2020-07-02 22:13 UTC, felixfontein approved these changes

2020-07-03 06:28 UTC, gundalow approved these changes

2020-07-03 06:39 UTC, gundalow commented
rebuild_merge

2020-07-03 08:37 UTC, felixfontein commented
/rebuild_failed

2020-07-03 09:15 UTC, merged