[get_url] permit to have a checksum only file
ansible/ansible pull request #70349
Opened 2020-06-28 14:54 UTC by bmillemathias

##### SUMMARY
checksum parameter can also accept a checksum only file (no filename beside the checksum).
fixes #54390

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
get_url

##### ADDITIONAL INFORMATION
Code is from @sivel and it cover a part of the patch done by @Zype76 in #68869

2020-08-12 15:52 UTC, bmillemathias commented
@Akasurde the PR is waiting review from you, is there something blocking ?

best

2020-11-26 08:20 UTC, bmillemathias commented
/rebuild_failed

2020-12-23 06:00 UTC, Akasurde approved these changes
LGTM

2020-12-23 06:15 UTC, Akasurde requested changes
Some tests are failing for me.

2020-12-23 07:47 UTC, felixfontein commented on changelogs/fragments/get_url-accept-file-for-checksum.yml
> +- get_url - permit to pass to parameter ``checksum`` an url pointing to a file containing only a checksum (https://github.com/ansible/ansible/issues/54390).
```suggestion
- get_url - permit to pass to parameter ``checksum`` an URL pointing to a file containing only a checksum (https://github.com/ansible/ansible/issues/54390).
```

2020-12-23 07:47 UTC, felixfontein commented on lib/ansible/modules/get_url.py
> +                # filename checksum
```suggestion
                # checksum filename
```

2021-07-09 15:33 UTC, s-hertel commented
@bmillemathias Can you rebase this please?

2022-06-01 18:22 UTC, s-hertel commented
@bmillemathias This came up in ansible-core's backlog meeting again today and we still wanted to include it. I wasn't sure if you'd mind me force pushing to your branch, so I opened a new PR with your rebased commit: #77948. Thank you for working on this and adding tests.

2022-06-01 18:27 UTC, bmillemathias commented
> @bmillemathias This came up in ansible-core's backlog meeting again today and we still wanted to include it. I wasn't sure if you'd mind me force pushing to your branch, so I opened a new PR with your rebased commit: #77948. Thank you for working on this and adding tests.

sure, happy that helps

2022-06-02 19:19 UTC, closed without merging