[2.9] Fix issue with MongoDB 4.0.20
ansible/ansible pull request #71393
Opened 2020-08-21 10:28 UTC by rhysmeister

##### SUMMARY
Update to module and tests to fix https://github.com/ansible-collections/community.mongodb/issues/136

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
mongodb_replicaset & tests for mongodb_replicaset and mongodb_shard

2020-08-21 15:45 UTC, relrod commented
@rhysmeister Since you said (in the other ticket) that this changes module behavior, we probably at least need a changelog here stating the changes.

2020-08-21 19:04 UTC, nitzmahone requested changes
One minor structural question, and needs a changelog entry, but otherwise this should be fine.

2020-08-21 19:04 UTC, nitzmahone commented on lib/ansible/modules/database/mongodb/mongodb_replicaset.py
> +        module.fail_json(msg='Unable to connect to database: %s' % to_native(e))
This is an awfully big exception handler with a really specific failure message- any unhandled exception through most of the module body will fail with "Unable to connect to database". The smaller sub-operation try/except blocks mitigate that somewhat, but it should probably just be limited to the connection bits as it was previously (so any future additions inside the try block won't fail with a misleading error).

2020-08-22 11:20 UTC, rhysmeister commented on lib/ansible/modules/database/mongodb/mongodb_replicaset.py
> +        module.fail_json(msg='Unable to connect to database: %s' % to_native(e))
Noted and modified.

2020-08-25 23:37 UTC, nitzmahone approved these changes

2020-08-25 23:39 UTC, nitzmahone commented
@rhysmeister looks great. I truncated the changelog text a bit and added the module name to the front (usually just need the affected component, a terse description, and link to the issue). We'll get this merged for the next 2.9 update. Thanks!

2020-08-27 17:13 UTC, merged