do not add colliding aliases to argument_spec #62315
ansible/ansible pull request #71557
Opened 2020-09-01 06:11 UTC by terencehonles

##### SUMMARY

This is a refreshed PR based on #63017. While #62315 is already fixed on `devel` and I had opened #71555 to just incorporate the test in `test/integration/targets/blockinfile/tasks/main.yml` (which is also included in this PR) I realized this was still a bug to have the `FILE_COMMON_ARGUMENTS` stomping on module aliases, and I opened this PR to address that.

As mentioned in #71555 the issue #62315 was fixed with #66389, and that will go out with the next stable release.

While I have already closed #71555, I do want to call out my comment on that PR, that figuring out how to write a test for Ansible was rather difficult and I struggled with trying to even start the test runner. Eventually I stumbled upon the `--venv` option, and I **really** think that should be much more front and center because it is very likely the option you want to be running with (that or possibly `--docker`). As an initial contributor I don't want to worry about how the packages are installed and I don't want the test system to install packages globally on my system. I'm calling this out because I'm an advanced Python user and I am also very stubborn and wanted to get this fix in. I don't know if this is something you can count on from your average developer. Just my two cents, and I mean what I'm saying as constructively as possible.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
module_utils (all modules)

2020-09-02 21:44 UTC, terencehonles commented
Looking at the tests it looks like moving the `FILE_COMMON_ARGUMENTS` registration to after the aliases are resolved breaks the aliases coming from `FILE_COMMON_ARGUMENTS`. I'll see about updating that when I can.

2020-10-07 20:37 UTC, terencehonles commented
I think this may fix the issue exposed by the tests, but I'm just going to let the CI build this since I didn't uncover this issue when I had tested locally.

2022-08-17 15:25 UTC, s-hertel requested changes

2022-08-17 15:25 UTC, s-hertel commented on lib/ansible/module_utils/basic.py
> +                            for a in file_common_aliases)):
This would be more readable by setting some intermediate variables.

2023-03-08 19:37 UTC, nitzmahone commented
We think the underlying issue was mostly fixed with the stuff that closed #66389, and that specific cases that remain should probably be handled by more careful inheritance of args. Another possibility would be to just raise an error on multiply-defined copies of the arg, but trying to merge it this way would likely just sweep a problem under the rug that module authors should be aware of.

Closing for now- feel free to discuss if you've got another idea. Thanks!

2023-03-08 19:37 UTC, closed without merging