add_host/group_by: fix using changed_when in a loop v2
ansible/ansible pull request #71719
Opened 2020-09-11 12:26 UTC by mkrizek

##### SUMMARY

Second attempt to fix #71627

Fixes #71627

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

`lib/ansible/playbook/task.py`
`lib/ansible/plugins/strategy/__init__.py`

2020-09-16 13:00 UTC, AlanCoding commented on test/integration/targets/add_host/tasks/main.yml
> +      - add_host_loop_res.results[2] is not changed
looks like a pretty robust test 👍

2020-12-09 15:11 UTC, AlanCoding commented
bump - it would be good to get some resolution to the fact that this produces tracebacks with the `changed_when` syntax, so workarounds aren't really sensible.

2021-01-20 15:26 UTC, mkrizek commented
Note: the issue with this PR as is is that it doesn't amend the `changed` in the overall task result after the loop ended, just the per iteration results.

2022-02-03 17:32 UTC, bcoca approved these changes

2022-02-03 17:32 UTC, bcoca requested changes

2022-02-03 17:32 UTC, bcoca commented on lib/ansible/executor/task_executor.py
> +                if self._task.action not in ('add_host', 'group_by'):
actually, add the 'fqcn' function and probably move this tuple to lib/ansible/constants.py

2022-02-03 20:06 UTC, bcoca approved these changes

2022-02-04 11:35 UTC, merged