Make sure that none is not accepted for required module options
ansible/ansible pull request #72248
Opened 2020-10-18 22:15 UTC by felixfontein

##### SUMMARY
If a value that is required (by required, required_if, required_together, required_one_of, required_by) is specified as `none`/`null`/`~`/empty, it is only accepted when the option explicitly declares `allow_none_value=True`.

Fixes #69190 more closely to https://meetbot.fedoraproject.org/ansible-meeting/2020-05-05/ansible_core_public_irc_meeting.2020-05-05-19.05.log.html than #72243.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/module_utils/basic.py
lib/ansible/module_utils/common/validation.py

2020-10-19 08:22 UTC, tremble requested changes
I don't see any tests for the `allow_none_value=True` behaviour. Given that this was the original behaviour there should probably be some tests that it's possible to go back to the old behaviour.

Similarly I may have missed it but I don't see any update to the arg_spec sanity tests to ensure its use doesn't trigger a sanity warning.

2020-10-19 12:07 UTC, felixfontein commented
@treble that's kind of expected, since I only stayed up to long to finish the main part of the PR before I forgot my plans for it ;)

2020-10-19 17:30 UTC, felixfontein commented
/rebuild_failed

2020-10-20 20:28 UTC, felixfontein commented
TODO:
 - warn for 2.11
 - change to deprecation warning for 2.12
 - switch default for `accept_none_value` from `True` to `False` in 2.16
 - convert class method to function

2020-10-22 19:14 UTC, felixfontein commented
(Rebase after merge of #72245. Nothing else changed.)

2020-10-24 13:38 UTC, felixfontein commented
/rebuild_failed

2020-10-24 14:10 UTC, felixfontein commented
/rebuild_failed

2020-11-04 21:37 UTC, felixfontein commented
@bcoca tests passed.

2020-12-03 18:13 UTC, samdoran commented
!waffling core_review

2020-12-03 20:35 UTC, mkrizek commented
!waffling core_review

2020-12-03 20:35 UTC, mkrizek commented
!waffling needs_revision

2021-03-20 20:45 UTC, felixfontein commented
This needs a complete rewrite since the argument spec handling was rewritten / completely refactored.

2023-09-02 07:56 UTC, closed without merging