[WIP] import sanity test for plugins
ansible/ansible pull request #72497
Opened 2020-11-05 13:34 UTC by felixfontein

##### SUMMARY
Right now the import sanity test only supports modules. Tries to see whether it can be extended to plugins as well.

First version works, but fails for all plugins as `jinja2` cannot be found. I guess the minimal venv is not the best place for this :)

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
ansible-test sanity

2020-11-06 08:14 UTC, felixfontein commented
I guess the plugin import tests need to run in a less minimal venv, where ansible's requirements are installed, to avoid https://app.shippable.com/github/ansible/ansible/runs/176079/1/tests I didn't look into how to achieve that yet.

2020-11-13 08:44 UTC, felixfontein commented
I'm getting some strange errors on Python 2.7:
```
lib/ansible/plugins/action/add_host.py:0:0: traceback: AttributeError: 'NoneType' object has no attribute 'ImpImporter' (at lib/ansible/utils/collection_loader/_collection_finder.py:252:0)
lib/ansible/plugins/action/assemble.py:0:0: traceback: TypeError: 'NoneType' object is not callable (at lib/ansible/utils/collection_loader/_collection_finder.py:111:0)
```
The full tracebacks are:
```
Traceback (most recent call last):
  File "/root/ansible_collections/community/docker/tests/output/.tmp/sanity/import/minimal-py27-requirements-None/bin/importer.py", line 261, in test_python_module
    import_module(name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/root/ansible/lib/ansible/utils/collection_loader/_collection_finder.py", line 368, in load_module
    exec(code_obj, module.__dict__)
  File "/root/ansible_collections/community/docker/plugins/inventory/docker_machine.py", line 90, in <module>
    from ansible.plugins.inventory import BaseInventoryPlugin, Constructable, Cacheable
  File "/usr/lib/python2.7/pkgutil.py", line 243, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/root/ansible/lib/ansible/plugins/__init__.py", line 30, in <module>
    from ansible.utils.display import Display
  File "/root/ansible/lib/ansible/utils/collection_loader/_collection_finder.py", line 252, in find_module
    return pkgutil.ImpImporter(self._pathctx).find_module(fullname)
AttributeError: 'NoneType' object has no attribute 'ImpImporter'
```
and
```
Traceback (most recent call last):
  File "/root/ansible_collections/community/docker/tests/output/.tmp/sanity/import/minimal-py27-requirements-None/bin/importer.py", line 261, in test_python_module
    import_module(name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/root/ansible/lib/ansible/utils/collection_loader/_collection_finder.py", line 368, in load_module
    exec(code_obj, module.__dict__)
  File "/root/ansible_collections/community/docker/plugins/inventory/docker_swarm.py", line 141, in <module>
    from ansible.errors import AnsibleError
  File "/root/ansible/lib/ansible/utils/collection_loader/_collection_finder.py", line 180, in find_module
    return _AnsibleInternalRedirectLoader(fullname=fullname, path_list=path)
  File "/root/ansible/lib/ansible/utils/collection_loader/_collection_finder.py", line 645, in __init__
    builtin_meta = _get_collection_metadata('ansible.builtin')
  File "/root/ansible/lib/ansible/utils/collection_loader/_collection_finder.py", line 1019, in _get_collection_metadata
    collection_pkg = import_module('ansible_collections.' + collection_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/root/ansible/lib/ansible/utils/collection_loader/_collection_finder.py", line 513, in load_module
    ansible_pkg_path = os.path.dirname(import_module('ansible').__file__)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/root/ansible/lib/ansible/utils/collection_loader/_collection_finder.py", line 111, in _ansible_collection_path_hook
    path = to_native(path)
TypeError: 'NoneType' object is not callable
```

2020-11-14 11:46 UTC, felixfontein commented
Interestingly, the first file processed always works. The second file gets `AttributeError: 'NoneType' object has no attribute 'ImpImporter'`, and the third and all others `TypeError: 'NoneType' object is not callable`.

2020-11-14 13:04 UTC, felixfontein commented
I think this now works as expected.

It successfully found some easy to fix errors in community.general and community.network, and pointed out some more serious problems with some plugins in community.network (broken cross-collection dependencies).

ready_for_review

2020-12-17 07:09 UTC, felixfontein commented
The new error is:
```
2020-12-17T06:36:04.9856593Z 04:14 ERROR: Found 1 import issue(s) on python 3.6 which need to be resolved:
2020-12-17T06:36:04.9858239Z 04:14 ERROR: plugins/filter/check_pylint.py:16:0: traceback: KeyError: None
```

2020-12-17 08:35 UTC, mattclay commented
The issue in `test/integration/targets/ansible-test/ansible_collections/ns/col/plugins/filter/check_pylint.py` can be fixed by making `None` a valid key:

```python
result = {None: None}[{}.get('something')]
```

It should be done in a separate PR so it can be backported, ideally as part of https://github.com/ansible/ansible/pull/72997.

2020-12-17 09:37 UTC, felixfontein commented
/rebuild_failed

2020-12-17 11:06 UTC, felixfontein commented
/rebuild_failed

2020-12-18 02:25 UTC, mattclay commented
@felixfontein This refactor should provide what you need to install cryptography: https://github.com/ansible/ansible/pull/73017

Just call the install_cryptography function with the venv python and pip.

2020-12-21 16:24 UTC, felixfontein commented
/rebuild_failed

2020-12-21 18:31 UTC, felixfontein commented
/rebuild_failed

2020-12-21 19:30 UTC, felixfontein commented
@mattclay thanks, it worked!

2021-01-04 06:11 UTC, mkrizek commented
!waffling core_review

2021-01-07 17:15 UTC, felixfontein commented
Rebased after #73017 has been merged.

ready_for_review

2021-02-12 18:09 UTC, mattclay requested changes
@felixfontein Thanks for working on this. I'm sorry it took me so long to review. Overall it looks really good. It ended up being much easier to review than I expected.

When you push your next changes, please include a changelog fragment.

2021-02-12 18:09 UTC, mattclay commented on lib/ansible/plugins/action/pause.py
> +    except (curses.error, TypeError, io.UnsupportedOperation):
If these changes are needed, they should be in a separate PR with a changelog fragment and ideally some tests.

2021-02-12 18:09 UTC, mattclay commented on test/lib/ansible_test/_data/requirements/sanity.import-plugins.txt
> +packaging
This file needs to be updated include the new resolvelib requirement.

2021-02-12 18:09 UTC, mattclay commented on test/sanity/code-smell/ansible-requirements.py
> +        if requirements_1 != requirements_2:
```suggestion
    original_requirements = read_file(ORIGINAL_FILE)
    vendored_requirements = read_file(VENDORED_COPY)

    if original_requirements is not None and vendored_requirements is not None:
        if original_requirements != vendored_requirements:
```

2021-02-12 18:09 UTC, mattclay commented on test/sanity/code-smell/ansible-requirements.py
> +            print('%s:%d:%d: Not identical to %s' % (VENDORED_COPY, 0, 0, ORIGINAL_FILE))
```suggestion
            print('%s:%d:%d: must be identical to %s' % (VENDORED_COPY, 0, 0, ORIGINAL_FILE))
```

2021-02-12 18:09 UTC, mattclay commented on test/sanity/code-smell/ansible-requirements.py
> +            sys.exit()
```suggestion
```

2021-02-12 18:09 UTC, mattclay commented on test/sanity/code-smell/ansible-requirements.py
> +        print('%s:%d:%d: Reading file failed: %s' % (path, 0, 0, re.sub(r'\s+', ' ', str(ex))))
```suggestion
        print('%s:%d:%d: unable to read required file %s' % (path, 0, 0, re.sub(r'\s+', ' ', str(ex))))
```

2021-02-12 18:09 UTC, mattclay commented on test/lib/ansible_test/_internal/executor.py
> +        return get_hash(path)
Remove the entire static method and call `get_hash` directly.

2021-02-12 18:09 UTC, mattclay commented on test/lib/ansible_test/_data/sanity/import/importer.py
> +        pass
Use an environment variable to pass additional arguments to this script, by adding it here:

https://github.com/ansible/ansible/blob/ea2f37d2536300b2cf00366e730ca04e9252d45d/test/lib/ansible_test/_data/sanity/import/importer.py#L26-L29

2021-02-12 18:09 UTC, mattclay commented on test/lib/ansible_test/_data/sanity/import/importer.py
> +    def run(args):
```suggestion
    def run(restrict_to_module_paths):
```

2021-02-12 18:09 UTC, mattclay commented on test/lib/ansible_test/_data/sanity/import/importer.py
> +            sys.exit(1)
This can be simplified:

```suggestion
        for path in args or sys.stdin.read().splitlines():
            name = convert_relative_path_to_name(path)
            test_python_module(path, name, base_dir, messages, restrict_to_module_paths)
```

The extra error logic shouldn't be needed since this is only called internally by ansible-test.

2021-02-12 18:09 UTC, mattclay commented on test/lib/ansible_test/_data/sanity/import/importer.py
> +    run(args)
```suggestion
    run(import_type == 'module')
```

2021-02-12 18:09 UTC, mattclay commented on test/lib/ansible_test/_data/sanity/import/importer.py
> +                    "ignore", "Python 3.5 support will be dropped in the next release of cryptography. Please upgrade your Python.")
Purely cosmetic, but easier to read and consistent with the previous entries:

```suggestion
                warnings.filterwarnings(
                    "ignore", 
                    "Python 3.5 support will be dropped in the next release ofcryptography. Please upgrade your Python.")
                warnings.filterwarnings(
                    "ignore", 
                    "Python 3.5 support will be dropped in the next release of cryptography. Please upgrade your Python.")
```

2021-02-12 18:09 UTC, mattclay commented on test/lib/ansible_test/_data/sanity/import/importer.py
> +
Why is this needed?

2021-02-12 18:09 UTC, mattclay commented on test/lib/ansible_test/_internal/sanity/import.py
> +    module_path = data_context().content.module_path
Add a doc string and PEP 484 type hints for this function.

2021-02-12 18:09 UTC, mattclay commented on test/lib/ansible_test/_internal/sanity/import.py
> +            if import_type == 'plugin' and python_version.startswith('2.6'):
```suggestion
            if import_type == 'plugin' and python_version in REMOTE_ONLY_PYTHON_VERSIONS:
```

Also, as a side-note, we're going to need something more complex to handle collections which have controller-only modules and module_utils -- but that's not something we should try to address in this PR.

2021-02-12 18:09 UTC, mattclay commented on test/lib/ansible_test/_internal/sanity/import.py
> +            cmd = ['importer.py', '--type', import_type]
Pass `import_type` using an environment variable instead.

```suggestion
            cmd = ['importer.py']
```

2021-02-12 18:09 UTC, mattclay commented on test/lib/ansible_test/_internal/sanity/import.py
> +                this_results = parse_to_list_of_dict(pattern, ex.stdout)
```suggestion
                parsed = parse_to_list_of_dict(pattern, ex.stdout)
```

2021-02-12 18:09 UTC, mattclay commented on test/lib/ansible_test/_internal/sanity/import.py
> +                this_results = [SanityMessage(
```suggestion
                messages += [SanityMessage(
```

You could also use `extend` instead of `+=`.

2021-02-12 18:09 UTC, mattclay commented on test/lib/ansible_test/_internal/sanity/import.py
> +                ) for r in this_results]
```suggestion
                ) for r in parsed]
```

2021-02-12 18:09 UTC, mattclay commented on test/lib/ansible_test/_internal/sanity/import.py
> +            results.extend(settings.process_errors(this_results, paths))
Move this outside the loop:

```suggestion
        results = settings.process_errors(messages, paths)
```

2021-02-12 18:09 UTC, mattclay commented on test/lib/ansible_test/_internal/sanity/import.py
> +            this_results = []
```suggestion
            messages = []
```

2021-02-12 19:23 UTC, felixfontein commented on test/lib/ansible_test/_data/requirements/sanity.import-plugins.txt
> +packaging
Done. I rebased the PR so that both files are identical both in AZP and locally.

2021-02-12 19:32 UTC, samdoran commented
!waffling needs_revision

2021-02-12 19:40 UTC, felixfontein commented on test/lib/ansible_test/_internal/executor.py
> +        return get_hash(path)
Implemented in cb7558ad9cc040045e830d28268091345af1abc6.

2021-02-12 19:40 UTC, felixfontein commented on test/lib/ansible_test/_data/sanity/import/importer.py
> +        pass
Implemented in cb7558ad9cc040045e830d28268091345af1abc6.

2021-02-12 19:40 UTC, felixfontein commented on test/lib/ansible_test/_internal/sanity/import.py
> +            cmd = ['importer.py', '--type', import_type]
Implemented in cb7558ad9cc040045e830d28268091345af1abc6.

2021-02-12 19:49 UTC, felixfontein commented on test/lib/ansible_test/_data/sanity/import/importer.py
> +
The plugin loader inserts itself at the beginning of `sys.meta_path`, which causes the importer test to report `report_message(path, 0, 0, 'metapath', 'changes to sys.meta_path[0] are not permitted', messages)` (three lines below). The `_remove()` call makes the collection loader clean up (and remove itself from `sys.meta_path`).

2021-02-12 19:50 UTC, felixfontein commented on test/lib/ansible_test/_internal/sanity/import.py
> +            if import_type == 'plugin' and python_version.startswith('2.6'):
Implemented in 0a631981cd731f62acf0eb33fd68eb3e41c7b482.

2021-02-12 19:50 UTC, felixfontein commented on test/lib/ansible_test/_internal/sanity/import.py
> +    module_path = data_context().content.module_path
Implemented in 0a631981cd731f62acf0eb33fd68eb3e41c7b482.

2021-02-12 20:06 UTC, felixfontein commented on test/lib/ansible_test/_data/sanity/import/importer.py
> +
Without the above, the following will happen:
```
ERROR: lib/ansible/plugins/action/__init__.py:0:0: metapath: changes to sys.meta_path[0] are not permitted
ERROR: lib/ansible/plugins/action/add_host.py:0:0: traceback: ValueError: unable to locate collection ansible.builtin (at lib/ansible/utils/collection_loader/_collection_finder.py:1054:0)
ERROR: lib/ansible/plugins/action/assemble.py:0:0: traceback: ValueError: unable to locate collection ansible.builtin (at lib/ansible/utils/collection_loader/_collection_finder.py:1054:0)
ERROR: lib/ansible/plugins/action/assert.py:0:0: traceback: ValueError: unable to locate collection ansible.builtin (at lib/ansible/utils/collection_loader/_collection_finder.py:1054:0)
ERROR: lib/ansible/plugins/action/async_status.py:0:0: traceback: ValueError: unable to locate collection ansible.builtin (at lib/ansible/utils/collection_loader/_collection_finder.py:1054:0)
ERROR: lib/ansible/plugins/action/command.py:0:0: traceback: ValueError: unable to locate collection ansible.builtin (at lib/ansible/utils/collection_loader/_collection_finder.py:1054:0)
ERROR: lib/ansible/plugins/action/copy.py:0:0: traceback: ValueError: unable to locate collection ansible.builtin (at lib/ansible/utils/collection_loader/_collection_finder.py:1054:0)
```
(repeats for every file processed afterwards)

2021-02-12 20:08 UTC, felixfontein commented on lib/ansible/plugins/action/pause.py
> +    except (curses.error, TypeError, io.UnsupportedOperation):
Without this change, I get:
```
ERROR: lib/ansible/plugins/action/pause.py:47:0: traceback: UnsupportedOperation: fileno
```

2021-02-12 20:18 UTC, felixfontein commented on lib/ansible/plugins/action/pause.py
> +    except (curses.error, TypeError, io.UnsupportedOperation):
I moved this change to #73588; will rebase once that's merged.

I have no idea how to test this, I haven't managed to reproduce this outside of this PR.

2021-02-12 21:12 UTC, felixfontein commented
@mattclay I rebased after #73588 has been merged. I think I have addressed all your review comments, and hopefully the tests now pass as well.

2021-02-12 22:09 UTC, mattclay approved these changes

2021-02-12 22:09 UTC, merged

2021-02-12 22:13 UTC, mattclay commented
@felixfontein As a follow-up to this, I realized we need to update the list of plugin types known to ansible-test:

https://github.com/ansible/ansible/blob/1f3a90270b5b718ad1456e6bb11097724cd3d8ab/test/lib/ansible_test/_internal/provider/layout/__init__.py#L176-L196

We'll also need to update the code that uses `REMOTE_ONLY_PYTHON_VERSIONS` to recognize that `plugin_utils` is not for remote usage. That should be just the unit tests and the updated import sanity test.

Are you up for making those changes?

2021-02-12 22:41 UTC, mattclay commented
I'm working on an announcement to cover these changes.

2021-02-13 06:41 UTC, felixfontein commented
@mattclay thanks for reviewing and merging!

I'll take a look over the weekend at updating that.

2021-02-13 20:17 UTC, felixfontein commented
@mattclay

> We'll also need to update the code that uses `REMOTE_ONLY_PYTHON_VERSIONS` to recognize that `plugin_utils` is not for remote usage. That should be just the unit tests and the updated import sanity test.

No change is needed for that, since the code only considers entries in `modules` and `module_utils` for `REMOTE_ONLY_PYTHON_VERSIONS`:
https://github.com/ansible/ansible/blob/d092356fc510069fe59258230c94871f32995c61/test/lib/ansible_test/_internal/sanity/import.py#L69-L73
https://github.com/ansible/ansible/blob/d092356fc510069fe59258230c94871f32995c61/test/lib/ansible_test/_internal/units/__init__.py#L65-L67