Add sles to INTERPRETER_PYTHON_DISTRO_MAP
ansible/ansible pull request #72498
Opened 2020-11-05 15:25 UTC by tongpu

Since SLES 15 SUSE recommends to use the Python 3 interpreter.

##### SUMMARY
Extend INTERPRETER_PYTHON_DISTRO_MAP with a default value for SLES 15 to ease transition to Ansible v2.10.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
config

##### ADDITIONAL INFORMATION
This change ensures that when running Ansible against SUSE Linux Enterprise Server 15 machines the correct Python interpreter is being used.

2020-11-05 20:11 UTC, mattclay requested changes
Please add a changelog fragment for this change.

2020-11-05 20:43 UTC, tongpu commented
> Please add a changelog fragment for this change.

I've added the changelog fragement. Hope it is sufficient and correct.

2020-11-05 21:33 UTC, mattclay approved these changes

2020-12-16 22:22 UTC, mattclay commented
/azp run

2021-05-22 14:13 UTC, Akasurde commented
cc @nitzmahone

2021-05-24 16:19 UTC, nitzmahone commented
Historically, only distros that need a very specific and well-known Python version for basic bootstrapping functionality to work have gotten an entry in the mapping table (eg, the package management modules for yum/dnf/apt with their OS-packaged Python libs). With the recent advent of optional module_utils and module_respawn, the mapping table has become even less important for its original purpose. We've always been concerned about the amount of ongoing maintenance and potential for trouble that the mapping table could be if we started adding many distros to it, which is why the config values have remained fixed and private.

Now that Python 2.x is pretty well dead, we're considering addressing this in a different way by changing the order of the Python fallback list to favor 3.x Python versions. That will certainly break some folks, eg, those that are managing old distros with unsupported Python 3 versions. One way we could address that as well might be to allow the fallback list to be configurable by both inventory and config to allow for more specific customization when our defaults don't work well.

2021-05-24 18:09 UTC, tongpu commented
@nitzmahone No issue if this change is not accepted, because I know myself that it's not 100% complete (e.g. openSUSE should be added too).

One argument for inclusion of SLES and openSUSE would be that Python 3 includes the XML module required to install packages using zypper, but Python 2 doesn't, which was the reason I started the change in the first place.

If you want this change to be included I would extend it to also support openSUSE.

2021-05-24 20:53 UTC, nitzmahone commented
The interpreter map is a somewhat ham-fisted approach to the problem, now that we have module respawn. If I'd done that  back in 2.8, we might not even have needed the interpreter map. 

It might be better to update the zypper modules to try and locate a workable Python with the necessary deps, then module respawn  under that Python (take a look at yum/dnf/apt in devel/2.11 to see how we do that). Since we backported optional module_utils, it should be possible to have the updated modules work from the latest 2.9->devel and beyond (though the respawn magic itself would only work on 2.11+).

2021-07-26 20:25 UTC, samdoran commented
When #75049 is merged, Python 3 will be preferred and `INTERPRETER_PYTHON_DISTRO_MAP` will be configurable using config or an inventory variable. That is the best solution for reasons outlined above.

2021-07-27 04:34 UTC, tongpu commented
Thanks for that. I guess I'm going to close this PR then, because it's not providing any benefits anymore.

2021-07-27 04:34 UTC, closed without merging