Allow using galaxy.yml as a requirements file
ansible/ansible pull request #72637
Opened 2020-11-16 17:03 UTC by sivel

##### SUMMARY
Allow using galaxy.yml as a requirements file

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
lib/ansible/cli/galaxy.py

##### ADDITIONAL INFORMATION
We had discussed this previously, but didn't pursue it.  This may be useful for https://github.com/ansible/ansible/issues/72634 whether ansible-test supports it natively or not.

Just a potential option.

2020-11-16 19:02 UTC, webknjaz commented on lib/ansible/cli/galaxy.py
> +
Note to myself: this is going to conflict with #72591.

2020-12-03 19:19 UTC, mattclay commented
/azp run

2022-02-16 15:10 UTC, bcoca commented
requires changelogs and tests

2022-02-16 15:11 UTC, bcoca requested changes
clog and tests

2022-11-23 00:32 UTC, webknjaz commented
/azp run

2024-01-08 20:54 UTC, webknjaz commented
/azp run

2024-01-08 20:56 UTC, webknjaz commented
This needs a rebase.

2025-01-28 16:35 UTC, closed without merging