add fragments to return
ansible/ansible pull request #72635
Opened 2020-11-16 16:01 UTC by bcoca

also minor refactor in getting docstrings from import
  making it easier to reuse

##### ISSUE TYPE

- Docs Pull Request
- Feature Pull Request

##### COMPONENT NAME

ansible-doc

2021-01-18 19:03 UTC, felixfontein requested changes

2021-01-18 19:03 UTC, felixfontein commented on lib/ansible/utils/plugin_docs.py
> +            add_fragments(dstring, path, fragment_loader=floader, section=s)
This call is not passing `is_module`, which is required to know whether this is for a module or another plugin type.

2021-01-18 19:03 UTC, felixfontein commented on lib/ansible/utils/plugin_docs.py
> +                add_collection_to_versions_and_dates(data[key], collection_name, is_module=is_module)
This needs to pass `return_docs=True` for return docs.

2021-01-18 19:03 UTC, felixfontein commented on lib/ansible/utils/plugin_docs.py
> -        if 'options' not in fragment:
The `add_collection_to_versions_and_dates` call in line 173 needs `return_docs=True` passed if this is a return value fragment.

2021-01-18 20:27 UTC, bcoca commented on lib/ansible/utils/plugin_docs.py
> +            add_fragments(dstring, path, fragment_loader=floader, section=s)
not needed, since there is no difference in this case.

2021-01-18 20:33 UTC, felixfontein commented on lib/ansible/utils/plugin_docs.py
> +            add_fragments(dstring, path, fragment_loader=floader, section=s)
It is needed, since doc fragments for plugins can also contain option deprecations.

2025-08-03 15:48 UTC, felixfontein commented on lib/ansible/utils/plugin_docs.py
> +                    doc['seealso'].extend(seealso)
While you're touching these lines, how about factoring out common code, similarly as `options` and `attributes` are handled together further below:
```suggestion
            for doc_key in ['notes', 'seealso']:
                if doc_key in fragment:
                    entries = fragment.pop(doc_key)
                    if entries:
                        if doc_key not in doc:
                            doc[doc_key] = []
                        doc[doc_key].extend(entries)
```

2025-08-03 15:48 UTC, felixfontein commented on lib/ansible/utils/plugin_docs.py
> +        add_fragments(data['returndocs'], filename, fragment_loader=fragment_loader, is_module=is_module, section='RETURN')
I'm a bit worried that this will lead to sudden rejection of modules/plugins which have a return value called `extends_documentation_fragment` (while that would be quite surprising, it's technically allowed). How about doing something like:
```suggestion
        if not isinstance(data['returndocs'].get('extends_documentation_fragment'), Mapping):
            add_fragments(data['returndocs'], filename, fragment_loader=fragment_loader, is_module=is_module, section='RETURN')
```
Maybe with some warning/deprecation if `extends_documentation_fragment` turns out to be a mapping?

2025-08-03 15:48 UTC, felixfontein commented on lib/ansible/utils/plugin_docs.py
>          add_collection_to_versions_and_dates(fragment, real_collection_name, is_module=is_module)
```suggestion
        add_collection_to_versions_and_dates(fragment, real_collection_name, is_module=is_module, return_docs=(section == 'RETURN'))
```

2025-08-03 16:08 UTC, felixfontein commented
I really like this, it's a rather simple mechanism (similar to doc fragments for DOCUMENTATION) that solves some common problems:
1. Avoiding repeating similar return values in related modules (for example `community.crypto.openssl_csr` and `community.crypto.openssl_csr_pipe` have most return values in common, except `filename` and `backup_file` for `openssl_csr` that do not make sense for the other - all duplicate RVs can now be moved to a single place! similarly for `openssl_privatekey` and `openssl_privatekey_pipe`).
2. The problem described here: https://forum.ansible.com/t/how-should-presence-of-common-return-values-in-modules-be-documented/44155 - how to document common return values like `cmd`, `rc`, `stdout`, `stdout_lines`, etc., without having to explicitly write out all these definitions in every single module? With this feature, I can add a doc fragment like `community.general.common_return_values` so I can pick what I need for a module, like `community.general.common_return_values.cmd`, `community.general.common_return_values.rc`, `community.general.common_return_values.stdout` (which would include both `stdout` and `stdout_lines`), etc.

Something that this feature does not solve is repetition like between the `openssl_certificate_info` module and the `openssl_certificate_info` filter. Basically the big return value definition is identical, **except** that the return values for the filter are wrapped into a dict key `_value`. That might be possible to solve, **but** there's also a difference in markup, since return values mentioned with `RV()` now have the `_value` as part of the name. For this, a more generic solution is needed - maybe some templating done by a script inside the collection's repo. (I'd say this is very much out of scope for a mechanism to be included in ansible-doc.)

I'm looking forward to see this merged (with some compatibility shim backported so that older versions of ansible-core won't choke on a list `extends_documentation_fragment` in the return values - their ansible-doc might not show all return values then, but at least it will show some and not bail out before showing any docs :) )!

2025-08-04 19:57 UTC, felixfontein approved these changes

2025-08-04 20:58 UTC, merged

2025-08-10 14:23 UTC, felixfontein commented
I created https://github.com/ansible/ansible/pull/85638 to fix the failing sanity tests in ansible-core devel.