Document that *become* vars not put into play context
ansible/ansible pull request #72870
Opened 2020-12-05 03:36 UTC by bsolomon1124

##### SUMMARY

Fixes #72740

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

become

2020-12-08 15:25 UTC, mkrizek commented
Play context is an implementation detail and probably should not be mentioned in the user guide.

2020-12-08 15:26 UTC, samdoran commented
It would be less confusing to simply state that become variables are not available for templating.

2020-12-13 17:43 UTC, bsolomon1124 commented
Addressed feedback on wording.

2020-12-14 15:04 UTC, samdoran approved these changes

2020-12-14 15:04 UTC, samdoran commented
Awaiting approval from docs team.

2020-12-14 16:16 UTC, bcoca commented
I think you are mixing issues, the `ansible_become_` vars  are not magic vars, they are never populated automatically, they are there for the user to define, in which case they WILL be available.

2020-12-14 16:53 UTC, bsolomon1124 commented
@bcoca I may have concepts mixed up here including definition of magic vars.

At the end of the day this PR arose from the following observation:

```bash
$ mkdir ansible-72870
$ cd ansible-72870
$ python3 -m pip install -U 'ansible==2.9.*'
$ cat << EOF > pb.yaml
- name: test
  hosts: localhost
  connection: local
  tasks:
    - debug: var=ansible_ssh_user
    - debug: var=ansible_ssh_timeout
    - debug: var=ansible_ssh_pass
    - debug: var=ansible_become
    - debug: var=ansible_become_pass
EOF
```

Given the above setup, command-line flags associated with `*become*` variables are conspicuously absent from playbook context:

```bash
$ ANSIBLE_STDOUT_CALLBACK=yaml ansible-playbook --timeout 13 -kK --become pb.yaml 
SSH password: 
BECOME password[defaults to SSH password]: 
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [test] ****************************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************
ok: [localhost]

TASK [debug] ***************************************************************************************************************************************************
ok: [localhost] => 
  ansible_ssh_user: bsolomon

TASK [debug] ***************************************************************************************************************************************************
ok: [localhost] => 
  ansible_ssh_timeout: 13

TASK [debug] ***************************************************************************************************************************************************
ok: [localhost] => 
  ansible_ssh_pass: '12345test'

TASK [debug] ***************************************************************************************************************************************************
ok: [localhost] => 
  ansible_become: VARIABLE IS NOT DEFINED!

TASK [debug] ***************************************************************************************************************************************************
ok: [localhost] => 
  ansible_become_pass: VARIABLE IS NOT DEFINED!
```

As mentioned in https://github.com/ansible/ansible/issues/72740 it seems like these are deliberately excluded from being set in `play_context.py`, a behavior that seemed worth documenting.

2020-12-14 17:09 UTC, bcoca commented
@bsolomon1124 you hit a kind of 'legacy' that is also misleading, most of those vars get 'updated' but not with the final value. 

This value can change PER loop iteration, yet the update you see is before loops get processed, this is also not well documented and we specifically purged 'become' values since they were a disclosure issue (I would argue `ansilbe_ssh_pass` is also a problem) that had been created with specific hardcoded connection variables (mostly ssh related) but not for all connection/become plugins, this is also something I'm planning on removing in the future, while looking at a more accurate reporting method that users could opt in to get most of this info (sans secrets of course).

2021-01-18 20:29 UTC, samccann commented on docs/docsite/rst/user_guide/become.rst
> +As a security precaution, Ansible ``*become*`` magic variables such as
```suggestion
As a security precaution, Ansible ``*become*``  variables such as
```

2021-01-18 20:30 UTC, samccann approved these changes

2021-01-18 20:37 UTC, bcoca commented
the text is still not correct, the 'ansible_become_*' vars are not AUTOMATICALLY populated, but if you set them in any way vars can be set (not the same as using cli options, keywords or configuration) they are still there
```
#> ansible -m debug -a 'msg={{ansible_become_password}}' -e ansible_become_password=test2 localhost

localhost | SUCCESS => {
    "msg": "test2"
}
```

2021-12-15 20:46 UTC, samccann reviewed
@bcoca Do the suggested edits correctly address your prior comment?

(And sorry for the delay here!)

2021-12-15 20:46 UTC, samccann commented on docs/docsite/rst/user_guide/become.rst
> +Become variables not available for templating
```suggestion
Become variables and templating
```

2021-12-15 20:46 UTC, samccann commented on docs/docsite/rst/user_guide/become.rst
> +``ansible_become_pass`` are *not* available for templating. For instance, even
```suggestion
``ansible_become_pass`` are *not* available for templating if set with the CLI, keywords, or configuration. For instance, 
```

2021-12-15 20:46 UTC, samccann commented on docs/docsite/rst/user_guide/become.rst
> +
```suggestion
You can access these variables in template strings if you set the variable in other ways.

.. code-block:: text

    ansible -m debug -a 'msg={{ansible_become_password}}' -e ansible_become_password=test2 localhost

```

2021-12-16 15:19 UTC, bcoca requested changes

2021-12-16 15:19 UTC, bcoca commented on docs/docsite/rst/user_guide/become.rst
> +As a security precaution, Ansible ``*become*``  variables such as
This is still incorrect, also it assumes tha tthe CLI/keywords or configuration set ansible_become variables, they DO NOT and never did.

We sometimes populate those variables based on the 'resolved value' but are trying to avoid it going forward for security reasons . This does not mean the variables are removed from being templatable, it only means we avoid defining them in certain cases, if the variable is defined, it is available for templating.  

The variable itself is ONE way of defining the value to be used, at some points it was hijacked to also 'reflect' the resolved value but this creates 2 problems, one is security, the other is 'rentrant values' which would bring the incorrect 'resolved value' as the variable itself has high precedence and changes meant to change the value would be incorrectly overridden. 

For example, you use the `--become-user` option to set it to `foo`, if we set the `ansible_become_user` variable to `foo` then a play that then uses the keyword `become_user` to override the value to `bar` would not work (since variable has greater precedence then keyword) which would not be what the play author expected (since keyword has greater precedence than CLI)

2022-02-23 19:46 UTC, bcoca commented
closing as per above and lack of activity

2022-02-23 19:46 UTC, closed without merging