Improve a documentation of the first_found lookup plugin
ansible/ansible pull request #73080
Opened 2020-12-30 09:44 UTC by it-praktyk

##### SUMMARY
Added an example usage of the `skip` argument - indentation of that is not obvious
Made a notation more consistent across all examples

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
plugins/lookup/first_found

##### ADDITIONAL INFORMATION

The correct indentation of the `skip` parameter is not obvious - I've found - and tested the solution - at [stack overflow](https://stackoverflow.com/questions/39542085/how-to-use-skip-true-with-with-first-found).

2021-02-19 00:39 UTC, tadeboro reviewed
Thank you, @it-praktyk, for your contribution. Unfortunately, the whole block of examples is inconsistent and would really benefit from a bit more thorough cleanup.

Things that need unification are:

 1. `"` vs `'` usage. I would suggest that we use `"`  where quoting is needed and reserve `'` for lookup parameters.
 2. Spaces inside mustaches. Currently, some examples properly use the `{{ expression }}` format, while others omit the spaces after `{{` and before `}}`.

Would you be interested in making those modifications? Thank you in advance!

2021-04-27 07:45 UTC, Akasurde commented
@it-praktyk Are you still working on this? Thanks

needs_info

2021-04-27 07:47 UTC, Akasurde requested changes

2021-04-27 07:47 UTC, Akasurde commented on lib/ansible/plugins/lookup/first_found.py
> +    msg: "{{lookup('first_found', findme, errors='ignore')}}"
```suggestion
    msg: "{{ lookup('first_found', findme, errors='ignore') }}"
```

2021-04-27 07:47 UTC, Akasurde commented on lib/ansible/plugins/lookup/first_found.py
> +    src: "{{lookup('first_found', findme)}}"
```suggestion
    src: "{{ lookup('first_found', findme) }}"
```

2021-04-27 07:47 UTC, Akasurde commented on lib/ansible/plugins/lookup/first_found.py
> +    src: "{{lookup('first_found', params)}}"
```suggestion
    src: "{{ lookup('first_found', params) }}"
```

2021-04-28 19:23 UTC, it-praktyk commented on lib/ansible/plugins/lookup/first_found.py
> +    msg: "{{lookup('first_found', findme, errors='ignore')}}"
Included in the post-review commit.

2021-04-28 19:24 UTC, it-praktyk commented on lib/ansible/plugins/lookup/first_found.py
> +    src: "{{lookup('first_found', findme)}}"
Included in the post-review commit.

2021-04-28 19:24 UTC, it-praktyk commented on lib/ansible/plugins/lookup/first_found.py
> +    src: "{{lookup('first_found', params)}}"
Included in the post-review commit.

2021-04-28 19:51 UTC, it-praktyk commented
@Akasurde,  I've changed those you requested, but I see that most of the changes is covered now by https://github.com/ansible/ansible/pull/70502/commits.

2021-04-29 04:32 UTC, merged

2021-04-29 04:32 UTC, Akasurde commented
@it-praktyk Thanks for the contribution.

2021-04-29 04:32 UTC, Akasurde commented
@tadeboro Thanks for the review.