Do not pretend expression is filename in compile() Python built-in call
ansible/ansible pull request #73113
Opened 2021-01-04 22:37 UTC by oldium

##### SUMMARY

When calling `compile()`, the `filename` argument should be either a real file name or an angle-bracketed string. According to Python docs, most commonly used string is `'<string>'`. Keep the current behaviour (encapsulate the actual expression), but enclose it into angle brackets.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
Ansible package `ansible.template.safe_eval`

##### ADDITIONAL INFORMATION

The expression instead of file name problem was discovered while debugging execution of ansible-playbook with VisualStudio Code. The expression used in `filename` argument of `compile()` caused VisualStudio Code Python integration to throw exceptions when trying to handle the filename as a real file.

2021-01-04 23:00 UTC, bcoca commented
The docs don't require it:
`The filename argument should give the file from which the code was read; pass some recognizable value if it wasn’t read from a file ('<string>' is commonly used).`

2021-01-04 23:06 UTC, oldium commented
> The docs don't require it:
> `The filename argument should give the file from which the code was read; pass some recognizable value if it wasn’t read from a file ('<string>' is commonly used).`

Yes, correct. I read it in a way that the angle-bracket string is a usual form when not dealing with real file name. Actually it is used on multiple places in ansible in the form `<stdin>` or `<unknown>`.

2021-01-04 23:12 UTC, oldium commented
The actual issue is that the `filename` argument actually gets into the Python's stack as `frame.f_code.co_filename`, so the only way to distinguish it from the file is angle-bracket convention.

2021-01-12 15:09 UTC, samdoran requested changes
Please create a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment). See [this fragment](https://github.com/ansible/ansible/blob/c2f528b7686c9573aa8493357219e0bbe4416dd3/changelogs/fragments/reboot-change-default-boot-command.yaml) as an example.

2021-01-12 15:43 UTC, oldium commented
Fragment added. Done.

2021-01-13 21:14 UTC, samdoran approved these changes
Just want to get some others to approve this before merging. I believe this is correct because the use of `compile()` here won't ever be a filename based on the existing calls in our code today.

2021-01-19 17:20 UTC, merged