validate_modules: fails with .id attribute not found
ansible/ansible pull request #73322
Opened 2021-01-21 19:01 UTC by goneri

This patch addresses a problem in the `found_try_except_import` test.

This module tries to identify lines like:

`HAS_FOO = True`

In this case, the target (`HAS_FOO`) is of type `ast.Name` and has a
`id` attribute which provide the name.

In my case, I've a line that set a module attribute`. In this case, the
target (`module.var`) has the type `ast.Attribute` and no `id`
attribute. The code trigger an `AttributeError` exception.

This patch ensures we compare a `ast.Name`.

2021-01-21 19:46 UTC, s-hertel commented
Can you provide a complete example of how to trigger this? Thanks.

2021-01-22 13:56 UTC, goneri commented
> Can you provide a complete example of how to trigger this? Thanks.

Hi @s-hertel,

This line triggers the exception.
https://github.com/goneri/vmware.vmware_rest/blob/bump-auto-generated-modules_22976/plugins/modules/vcenter_cluster_info.py#L150

2021-02-02 19:47 UTC, goneri commented
Can we land that?

2021-02-02 20:09 UTC, mattclay commented
@goneri I'll look at this today.

2021-02-02 20:30 UTC, mattclay requested changes

2021-02-02 20:30 UTC, mattclay commented on test/lib/ansible_test/_data/sanity/validate-modules/validate_modules/main.py
> +                            if not hasattr(target, 'id'):
```suggestion
                            if not isinstance(target, ast.Name):
```

2021-02-02 20:44 UTC, mattclay requested changes

2021-02-02 20:44 UTC, mattclay commented on changelogs/fragments/validate-modules_found_try_except_import_fails_module_attribute.yaml
> +- validate-modules - do not raise an ``AttributeError`` is a value is assigned to a module attribute in a try/except block.
```suggestion
- validate-modules - do not raise an ``AttributeError`` if a value is assigned to a module attribute in a try/except block.
```

2021-02-02 20:44 UTC, mattclay commented on changelogs/fragments/validate-modules_found_try_except_import_fails_module_attribute.yaml
> +- validate-modules - do not raise an ``AttributeError`` is a value is assigned to a module attribute in a try/except block.
Sorry I didn't catch this in the initial review.

2021-02-02 21:08 UTC, mattclay approved these changes

2021-02-02 21:29 UTC, merged

2021-02-02 21:34 UTC, goneri commented
Thank you @mattclay