Fixed/improved regular expresssion for collection names
ansible/ansible pull request #73577
Opened 2021-02-11 22:54 UTC by russoz

##### SUMMARY
The regexp to determine a collection name in `schema.py`:
```python
COLLECTION_NAME_RE = re.compile('^([^.]+.[^.]+)$')
```
has two bugs: a) it does not protect the dot between names, allowing things like `community#general` or `community%general` or even `communitygeneral` to be validated, when they shouldn't, and b) it fails to validate namespaces with _deeper_ directory structures.

While investigating this, simplified a regexp in `lib/ansible/utils/collection_loader/_collection_finder.py` as well

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/utils/collection_loader/_collection_finder.py
test/lib/ansible_test/_data/sanity/validate-modules/validate_modules/schema.py

2021-02-11 23:02 UTC, sivel commented
Related https://github.com/ansible/ansible/pull/73279

2021-02-17 15:06 UTC, samdoran requested changes
This change looks correct at first glance, but it needs tests and a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment). See [this fragment](https://github.com/ansible/ansible/blob/c2f528b7686c9573aa8493357219e0bbe4416dd3/changelogs/fragments/reboot-change-default-boot-command.yaml) as an example.

2021-02-21 19:22 UTC, russoz commented
@samdoran changelog fragment added.

2021-02-22 16:03 UTC, samdoran requested changes
The changelog looks good. Can you please add some more tests cases to the existing unit tests? https://github.com/ansible/ansible/blob/f327e65d11bb905ed9f15996024f857a95592629/test/units/utils/collection_loader/test_collection_loader.py#L743-L745

2021-02-28 07:50 UTC, russoz commented
I love the smell of rebase in the morning

2021-03-01 00:07 UTC, russoz commented
@samdoran added a couple of lines to the test data - not a big change so not much to add there.

2021-03-01 15:40 UTC, samdoran approved these changes

2021-03-01 15:40 UTC, merged