Fixes #67257
ansible/ansible pull request #73682
Opened 2021-02-22 09:33 UTC by Saurabh-Thakre

##### SUMMARY

Fixes "skipping: no hosts matched" even when output is disabled #67257

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2021-02-23 15:32 UTC, samdoran commented
This fix is incorrect. The fix for the linked issue should be to add a feature to not display output on skipped tasks, not removing the skipped host message.

2021-02-23 16:10 UTC, bcoca commented
The setting used is specifically for avoiding extra output on a TASK for a skipped host, due to a conditional on the task itself.

You are applying it to an 'end of PLAY' message which does not run any tasks due to the host selection not matching anything in inventory. 

These are not the same thing, the same setting should not be used for both. (also clog and tests are missing)

2021-02-23 16:11 UTC, bcoca requested changes
The setting used is specifically for avoiding extra output on a TASK for a skipped host, due to a conditional on the task itself.

You are applying it to an 'end of PLAY' message which does not run any tasks due to the host selection not matching anything in inventory.

These are not the same thing, the same setting should not be used for both. (also clog and tests are missing)

2022-05-04 15:25 UTC, bcoca commented
closing as per above, this is not how the feature is supposed to work

2022-05-04 15:25 UTC, closed without merging