ansible-test: add Zuul CI provider
ansible/ansible pull request #73826
Opened 2021-03-08 15:38 UTC by goneri

Add a Zuul CI provider driver based on the Local one. The difference
is that we build the prefix with a md5 checksum to keep the final string
length under control.

2021-03-08 19:22 UTC, mattclay requested changes
I don't think this is the correct way to solve this problem. This allows the tests to pass, but only under Zuul. If the tests are run in other environments, they can still fail due to length issues.

The tests should be updated to limit the amount of the resource prefix they use, if needed, so they're not dependent on the environment to pass.

2021-03-08 20:30 UTC, goneri commented
Hi @mattclay, thank you for your feedback.

I would prefer to stick with a prefix below 64 characters. This was the current situation by convention. It happens we go above now because of uncommon the size of the nodes.

Since I expose a md5 instead of an hostname, I decided to add a new CIProvider to avoid any potential side-effect. 
As an alternative, I can submit something like that where we keep only the 32 first char of the hostname:

```path
diff --git a/test/lib/ansible_test/_internal/ci/local.py b/test/lib/ansible_test/_internal/ci/local.py
index 83ebb9d81d..d87e1596d2 100644
--- a/test/lib/ansible_test/_internal/ci/local.py
+++ b/test/lib/ansible_test/_internal/ci/local.py
@@ -60,7 +60,7 @@ class Local(CIProvider):
         """Return a resource prefix specific to this CI provider."""
         node = re.sub(r'[^a-zA-Z0-9]+', '-', platform.node().split('.')[0]).lower()
 
-        prefix = 'ansible-test-%s-%d' % (node, random.randint(10000000, 99999999))
+        prefix = 'ansible-test-%s-%d' % (node[:32], random.randint(10000000, 99999999))
 
         return prefix

```

What do you think?

2021-03-10 03:45 UTC, mattclay commented
@goneri Does https://github.com/ansible/ansible/pull/73844 solve the issue for you? It provides a consistent format and length limit for `resource_prefix` regardless of CI provider.

2021-03-10 15:34 UTC, goneri commented
> @goneri Does #73844 solve the issue for you? It provides a consistent format and length limit for `resource_prefix` regardless of CI provider.

Yes it looks good to me. Thank you @mattclay.

2021-03-10 15:35 UTC, goneri commented
Superseded by https://github.com/ansible/ansible/pull/73844

2021-03-10 15:35 UTC, closed without merging