Fix expected float and got str
ansible/ansible pull request #73860
Opened 2021-03-11 11:09 UTC by guillermomolina

##### SUMMARY
This is a bug and a fix, the service module fails in Solaris, the way the comparison of the version is implemented in lib/ansible/modules/service.py:

`    def svcadm_supports_sync(self):
        # Support for synchronous restart/refresh is only supported on
        # Oracle Solaris >= 11.2
        for line in open('/etc/release', 'r').readlines():
            m = re.match(r'\s+Oracle Solaris (\d+\.\d+).*', line.rstrip())
            if m and m.groups()[0] >= 11.2:
                return True
`

It compares the string "11.X" with the float 11.2 raising an exception.
I propose to convert it to a float and guard it for exception with:

`    def svcadm_supports_sync(self):
        # Support for synchronous restart/refresh is only supported on
        # Oracle Solaris >= 11.2
        for line in open('/etc/release', 'r').readlines():
            m = re.match(r'\s+Oracle Solaris (\d+\.\d+).*', line.rstrip())
            try:
                if m and float(m.groups()[0]) >= 11.2:
                    return True
            except:
                pass
`

This new code is tested ok in Solaris 11.4

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
service

##### ADDITIONAL INFORMATION

2021-03-11 20:05 UTC, mattclay requested changes
Several changes are needed here:

1) Use LooseVersion to compare versions.
2) Add tests.
3) Add a changelog.

2021-03-15 10:30 UTC, Akasurde commented on lib/ansible/modules/service.py
> +                if m and float(m.groups()[0]) >= 11.2:
```suggestion
                if m and LooseVersion(m.groups()[0]) >= LooseVersion('11.2'):
```

2021-03-16 18:55 UTC, bcoca requested changes
still needs changelog

2021-03-17 05:37 UTC, guillermomolina commented
> still needs changelog and tests

What do you mean by changelog? do you want me to add a file at ansible/changelogs/fragments ?

Could you point me where this the service module is tested to insert a test there

Thanks

2021-03-17 06:13 UTC, Akasurde commented
@guillermomolina Every PR requires a changelog. You can create it [here](https://github.com/ansible/ansible/tree/devel/changelogs/fragments). Take a look at the existing changelog entry to get an idea.

You can write tests [here](https://github.com/ansible/ansible/tree/devel/test/units/modules/)

2021-03-17 06:15 UTC, Akasurde commented on lib/ansible/modules/service.py
> +            try:
I think this try...except is not necessary.

2021-03-17 11:11 UTC, Akasurde commented on changelogs/fragments/73860-solaris-correct-version-check-in-svcadm_supports_sync
> +  - Solaris: Correct version check in svcadm_supports_sync (https://github.com/ansible/ansible/pull/73860).
```suggestion
  - Solaris - correct version check in svcadm_supports_sync (https://github.com/ansible/ansible/pull/73860).
```

2021-03-17 11:12 UTC, Akasurde commented on changelogs/fragments/73860-solaris-correct-version-check-in-svcadm_supports_sync
> +  - Solaris: Correct version check in svcadm_supports_sync (https://github.com/ansible/ansible/pull/73860).
Add '.yml' extension to this file.

2021-03-17 11:12 UTC, Akasurde commented on test/units/modules/test_sunos_service_sync.py
> +# Copyright (c) 2020 Ansible Project
```suggestion
# Copyright (c) 2021 Ansible Project
```

2021-03-17 11:12 UTC, Akasurde commented on test/units/modules/test_sunos_service_sync.py
> +# Copyright (c) 2020 Ansible Project
Rename this file to module name specific like `test_service.py`

2021-03-19 10:25 UTC, Akasurde commented
```
ERROR: test/units/modules/test_service.py:14:1: E302: expected 2 blank lines, found 1 (100%)
```

2021-03-23 08:17 UTC, guillermomolina commented
Please give me hints on how to create the module test, everything I tried didn't work.

2021-03-23 09:28 UTC, Akasurde commented
> Please give me hints on how to create the module test, everything I tried didn't work.

Give me some time I will try something and let you know. Thanks.

2021-03-25 08:05 UTC, Akasurde commented
@guillermomolina Could you please take a look at the test and let me know? Thanks.

2021-03-25 08:32 UTC, guillermomolina commented
> @guillermomolina Could you please take a look at the test and let me know? Thanks.

@Akasurde Perfect, very well done, thanks.

2021-04-09 10:12 UTC, Akasurde commented
@bcoca @mattclay Can you please review this? Thanks in advance.

2021-04-09 15:00 UTC, bcoca approved these changes

2021-04-09 15:09 UTC, Akasurde commented
recheck

2021-04-09 15:12 UTC, Akasurde commented
/azp run

2021-04-10 02:32 UTC, merged

2021-04-12 03:59 UTC, Akasurde commented
@guillermomolina Thanks for the contribution.

2021-04-12 04:08 UTC, guillermomolina commented
@Akasurde you are welcome

2021-04-22 07:25 UTC, froebela commented
Hello,

we've just installed the new quarterly Solaris 11.4 SRU patchset 32. As part of that, Solaris has changed the standard Python interpreter /usr/bin/python from Python 2 to Python 3. As a result we now also face this issue with our Ansible version 2.9 running on Debian 10 and we assume many more Solaris customers will follow. Therefore we'd kindly request a backport for this fix to Ansible 2.9 and 2.10 as soon as possible.

Thanks and kind regards,

Andre Fröbel!

2021-04-22 07:43 UTC, Akasurde commented
@froebela Can you confirm if this fix works with 2.10? 

FYI, Ansible 2.9 is only accepting security fixes.

2021-04-23 10:21 UTC, froebela commented
@Akasurde We're a little bit afraid of getting newer Ansible major versions in an uncontrolled way, therefore we pin it. I'm in discussion with my colleagues in order to roll out version 2.10. After that we could test the fix.