Detect Homebrew on Mac M1(Apple Silicon).
ansible/ansible pull request #73896
Opened 2021-03-14 06:29 UTC by kimata

##### SUMMARY

Detect Homebew on Mac M1(Apple Silicon).

Fixes #73887

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

facts

##### ADDITIONAL INFORMATION

Homebew on Mac M1 is installed to /opt/homebrew/bin/brew.
So, PKG_MGRS should include that path.

2021-03-15 10:02 UTC, Akasurde requested changes

2021-03-15 10:02 UTC, Akasurde commented on lib/ansible/module_utils/facts/system/pkg_mgr.py
> +            {'path': '/opt/homebrew/bin/brew', 'name': 'homebrew'},
Could you please add a changelog entry for this change and tests?

2021-04-18 22:44 UTC, fernandoacorreia commented
@Akasurde I'm having the same issue and I'm willing to help getting this PR over the finish line.

Can you give some pointers about the kind of test that you have in mind? Is there an existing test for `pkg_mgr.py` that can be updated?

2021-04-19 05:03 UTC, Akasurde commented
@fernandoacorreia You are absolutely right. Write a unit test under `test/units/module_utils/facts/system/`. Let me know if you need any help.

2021-04-22 05:28 UTC, fernandoacorreia commented
@Akasurde I have a candidate PR: #74378

2021-04-22 19:24 UTC, bcoca commented
closing in favor of more complete #74378

2021-04-22 19:24 UTC, closed without merging