Cumulus: support for 4-value Cumulus release versions
ansible/ansible pull request #73973
Opened 2021-03-19 22:51 UTC by quentinzil

##### SUMMARY

For internal releases and special releases, Cumulus uses a X.Y.Z.x format in the version numbers.
Ex: 3.7.14.1 or 3.7.13~16.d223

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

Use the reboot module on an internal or special Cumulus release.

Before change:
```
ansible -b mux01 -m reboot -i ./hosts_ssim
mux01 | FAILED! => {
    "msg": "Failed to get distribution information. Missing \"ansible_distribution\" in output."
}
```
After change:
```
ansible -b mux01 -m reboot -i ./hosts_ssim                                                                                                                         
mux01 | CHANGED => {
    "changed": true,
    "elapsed": 36,
    "rebooted": true
}
```

2021-03-22 04:48 UTC, Akasurde requested changes

2021-03-22 04:48 UTC, Akasurde commented on lib/ansible/module_utils/facts/system/distribution.py
> +                    debian_facts['distribution_%s_version' % name] = val
There are no facts as `distribution_maintenance_version` and `distribution_special_version`. So need to remove them. 

Also, please add a changelog entry [here](https://github.com/ansible/ansible/tree/devel/changelogs/fragments) and test case for this change just like [this](https://github.com/ansible/ansible/blob/devel/test/units/module_utils/facts/system/distribution/fixtures/cumulus_linux_2.5.4.json).

2021-05-31 06:48 UTC, Akasurde commented
@quentinzil Are you still working on this? Thanks


needs_info

2021-06-03 04:30 UTC, quentinzil commented
Hey @Akasurde, haven't had the chance to get back to this yet but I will work on it.

2022-05-11 20:03 UTC, bcoca commented
waiting_on_contributor

2023-05-17 09:21 UTC, closed without merging