Just clarifying that lists can be used for servicenames
ansible/ansible pull request #74087
Opened 2021-03-31 18:38 UTC by kvegh

Just like with the systemd module, the service module doesn't take a list of names for services to be managed, one has to loop through them. Just clarifying this, since I ran into this, probably happens to others too.

##### SUMMARY

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- Test Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2021-04-01 19:41 UTC, acozine reviewed
@kvegh Thank you for taking the time to share what you learned from experience with the rest of the Ansible community through the documentation! We appreciate your interest, your generosity, and your persistence.

I'm not sure about this change, though. The `name` option here is correctly documented as a string (`type: str`). Options that accept lists are documented as `type: list` with `elements: str` or `elements: dict` to document the type of the individual elements within the list.

The note you added is accurate. However, it could apply to every option of `type: str` throughout the documentation. I don't think we want to add it everywhere, and unless we do that, how do we decide which options in which modules should or should not get an extra note about using loops?

I'll leave this open for a while to allow others to comment, but I'm leaning against merging this.

2021-04-02 01:51 UTC, kindlehl commented
I agree that the extra level of detail here is not needed because it would have to be applied everywhere. The default/implied semantic is that one module invocation is matched to one resource/action on the target, with a few exceptions like package management modules. I think that it makes sense to only document the exceptions to this line of thought.

2021-04-06 15:16 UTC, bcoca requested changes

2021-04-06 15:16 UTC, bcoca commented on lib/ansible/modules/service.py
> +          one service to work with.
this is not needed, all 'type: str' do not accept lists.

2021-04-20 17:20 UTC, acozine commented
Closing per discussions above.

2021-04-20 17:20 UTC, closed without merging