Adding DigitalOcean cloud support to ansible-test
ansible/ansible pull request #74222
Opened 2021-04-10 18:41 UTC by mamercad

##### SUMMARY

Adding support to `ansible-test` for the DigitalOcean cloud. Working with folks in #ansible-digitalocean on this.

##### ISSUE TYPE

- Test Pull Request

##### COMPONENT NAME

* `ansible-test`

##### ADDITIONAL INFORMATION

2021-04-17 03:12 UTC, mattclay requested changes
The cloud plugins have undergone some recent changes. Please update this plugin using https://github.com/ansible/ansible/blob/devel/test/lib/ansible_test/_internal/cloud/vultr.py as a starting point. You should be able to copy the body of `get_environment_config` into a copy of that plugin, then update the docstring and class names.

2021-04-19 21:58 UTC, mattclay requested changes
Looks good overall. There's one minor change that could be made. It also needs a changelog fragment.

2021-04-19 21:58 UTC, mattclay commented on test/lib/ansible_test/_internal/cloud/digitalocean.py
> +            digitalocean_resource_prefix=self.resource_prefix,
This can be shorter, since it doesn't need to be unique across test plugins:

```suggestion
            resource_prefix=self.resource_prefix,
```

2021-04-20 01:55 UTC, mamercad commented
> Looks good overall. There's one minor change that could be made. It also needs a changelog fragment.

Thanks, both of these should be done now.

2021-04-20 03:40 UTC, mattclay approved these changes

2021-05-06 22:46 UTC, mattclay requested changes
These plugins have moved, and are now in: 

`test/lib/ansible_test/_internal/commands/integration/cloud/`

You should be able to rebase your PR and relocate the file to the new location.

2021-05-07 20:06 UTC, samdoran requested changes
The relative imports need adjusting due to the new file structure.

2021-05-07 20:06 UTC, samdoran commented on test/lib/ansible_test/_internal/commands/integration/cloud/digitalocean.py
> +from ..config import (
```suggestion
from ....config import (
```

2021-05-07 20:06 UTC, samdoran commented on test/lib/ansible_test/_internal/commands/integration/cloud/digitalocean.py
> +from ..util import (
```suggestion
from ....util import (
```

2021-05-07 21:03 UTC, mamercad commented on test/lib/ansible_test/_internal/commands/integration/cloud/digitalocean.py
> +from ..config import (
Ah, thank you, will fix.

2021-05-12 21:47 UTC, samdoran approved these changes

2021-05-12 21:48 UTC, samdoran commented
rebuild_merge

2021-05-12 23:06 UTC, mattclay approved these changes

2021-05-12 23:07 UTC, merged