fix module schema
ansible/ansible pull request #74295
Opened 2021-04-15 18:20 UTC by bcoca

no out of date hardcoded list anymore, uses 'current + 4' to
  set valid deprecation targets

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

test/schema

2021-04-19 22:40 UTC, mattclay requested changes

2021-04-19 22:40 UTC, mattclay commented on test/lib/ansible_test/_data/sanity/validate-modules/validate_modules/schema.py
> +    return Any(*[str(current + x / 100) for x in range(0, 5)])
This avoids using floats/division and uses `"""` for docstrings (follows PEP 8 style).

```suggestion
def deprecation_versions():
    """Create a list of valid version for deprecation entries, current+4"""
    major, minor = [int(version) for version in __version__.split('.')[0:2]]
    return Any(*['{0}.{1}'.format(major, minor + increment) for increment in range(0, 5)])
```

The use of floats/division can yield incorrect results:

```
'2.12' -> 2.12 -> ['2.12', '2.13', '2.14', '2.15', '2.16']
'2.13' -> ['2.13', '2.1399999999999997', '2.15', '2.1599999999999997', '2.17']
```

2021-04-19 22:40 UTC, mattclay commented on test/lib/ansible_test/_data/sanity/validate-modules/validate_modules/schema.py
> +        version_schema = {Required('removed_in'): version(for_collection)}
I'd keep the original style here:

```suggestion
        version_schema = {
            Required('removed_in'): version(for_collection),
        }
```

2021-04-19 22:40 UTC, mattclay commented on test/lib/ansible_test/_data/sanity/validate-modules/validate_modules/schema.py
> +
I'd keep the original style here:

```suggestion
        version_schema = {
            Required('removed_in'): deprecation_versions(),
        }
```

2021-04-19 22:46 UTC, mattclay approved these changes

2021-04-20 12:29 UTC, webknjaz commented on test/lib/ansible_test/_data/sanity/validate-modules/validate_modules/schema.py
> +    return Any(*['{0}.{1}'.format(major, minor + increment) for increment in range(0, 5)])
How about 
```python
from decimal import Decimal
```
and then
```suggestion
    ver = Decimal('.'.join(ansible.__version__.split('.')[:2]))
    return Any(*[str(ver + _ * Decimal('0.01')) for _ in range(5)])
```

2021-04-20 12:36 UTC, webknjaz approved these changes

2021-04-20 14:02 UTC, merged