Fix world readable setting
ansible/ansible pull request #74324
Opened 2021-04-16 22:34 UTC by bcoca

now uses shell option in all cases, the old constant still exists
    as 'documentation' but it not settable.
   also fix the docsite link in warnings/errors

alternative to #74207

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

action base

2021-04-16 22:38 UTC, Nothing4You requested changes
typo in the doclink method name

2021-04-16 22:38 UTC, Nothing4You commented on lib/ansible/plugins/action/__init__.py
> +from ansible.utils.plugin_docs import get_versioned_docklink
`s/dock/doc/`

2021-04-16 22:38 UTC, Nothing4You commented on lib/ansible/plugins/action/__init__.py
> +        become_link = get_versioned_docklink('user_guide/become.html')
`s/dock/doc/`

2021-04-16 22:42 UTC, Nothing4You commented on lib/ansible/plugins/action/__init__.py
>                  # user that something might go weirdly here.
you removed half the comment here

2021-04-16 22:45 UTC, Nothing4You commented on lib/ansible/plugins/action/__init__.py
>                  # user that something might go weirdly here.
i guess i can't mark this as resolved myself :/

2021-04-16 22:48 UTC, Nothing4You commented on lib/ansible/plugins/action/__init__.py
> +        if self.get_shell_option('world_readable_temp')
`s/$/:/`

2021-04-19 16:18 UTC, sivel commented
Related 8ef54759ec80b6bdecb58fb0d0262bc47c963f3d

2021-04-19 16:23 UTC, sivel commented
Only thing that comes to mind here, is whether we could test for this.  Maybe a `find` task that locates itself/its tmpdir.

2021-04-26 16:49 UTC, merged