[POC] PlayIterator: use enums for states
ansible/ansible pull request #74511
Opened 2021-04-30 15:20 UTC by mkrizek

##### SUMMARY

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
`lib/ansible/executor/play_iterator.py`
`lib/ansible/plugins/strategy/__init__.py`
`lib/ansible/plugins/strategy/linear.py`

2021-10-21 21:10 UTC, nitzmahone requested changes
+1000 for this change- it's bugged me for years that these couldn't be enums... Just a couple of nits on the compatibility/deprecation stuff.

2021-10-21 21:10 UTC, nitzmahone commented on lib/ansible/executor/play_iterator.py
> +class FailedStates(IntEnum):
If preserving the exact string representation of a multi-valued `FailedStates` isn't important, this should probably be `IntFlag`- that way we can ditch the custom multi-valued formatting code below...

2021-10-21 21:10 UTC, nitzmahone commented on lib/ansible/executor/play_iterator.py
> +__all__ = ['PlayIterator', 'IteratingStates', 'FailedStates']
Any reason not to just ditch this nowadays?

2021-10-21 21:10 UTC, nitzmahone commented on lib/ansible/executor/play_iterator.py
> +            if n == FailedStates.NONE:
Making `FailedStates` derive from `IntFlag` would allow us to ditch this conversion function entirely, I think?

2021-10-21 21:10 UTC, nitzmahone commented on lib/ansible/executor/play_iterator.py
> +    def __getattribute__(cls, name):
This is arguably a pretty expensive way to get this behavior, since now all PI attribute lookups are doing extra string prefix checks "just in case". Would be much cheaper to dynamically install the relevant values as class properties that fire the deprecation warnings. Still needs a metaclass to do so, since class properties aren't really a thing, but would still make the overall dispatch effectively free vs routing everything through a custom prefix-based getattribute intercept.

2021-10-21 21:21 UTC, nitzmahone commented on lib/ansible/executor/play_iterator.py
> +    def __getattribute__(cls, name):
Actually I think you can get away with read-only properties on the class object without using a metaclass at all, which should probably be fine in this case.

2021-10-21 23:53 UTC, nitzmahone commented on lib/ansible/executor/play_iterator.py
> +    def __getattribute__(cls, name):
Thinking about this even more- I guess it's less of a performance problem since the early-access `__getattribute__` is only overridden on the metaclass (ie, it's only all the class attribute lookups that are going through that). So the only sticky part there is that the metaclass `__getattribute__` impl technically should delegate to the base impl `__getattribute__` on `AttributeError`, otherwise any class attribute lookup that the overridden one doesn't know about will fail (eg, `PlayContext.SomeOtherClassAttribute`). I don't know that there are any right now, but could be nasty trip hazard "WTF?!" thing if anyone were to ever add one. :laughing:

2021-10-25 11:57 UTC, mkrizek commented on lib/ansible/executor/play_iterator.py
> +class FailedStates(IntEnum):
Nice, I didn't realize `IntFlag` existed. Done.

2021-10-25 11:58 UTC, mkrizek commented on lib/ansible/executor/play_iterator.py
> +__all__ = ['PlayIterator', 'IteratingStates', 'FailedStates']
Likely not. I am fine either way.

2021-10-25 11:59 UTC, mkrizek commented on lib/ansible/executor/play_iterator.py
> +    def __getattribute__(cls, name):
> So the only sticky part there is that the metaclass __getattribute__ impl technically should delegate to the base impl __getattribute__ on AttributeError, otherwise any class attribute lookup that the overridden one doesn't know about will fail (eg, PlayContext.SomeOtherClassAttribute).

Good point, fixed.

2021-10-25 12:00 UTC, mkrizek commented on lib/ansible/executor/play_iterator.py
> +    def __getattribute__(cls, name):
(Though I still think my original assumption that no one will touch PlayIterator and add class attributes is rock solid :trollface:)

2021-10-25 17:46 UTC, nitzmahone commented on lib/ansible/executor/play_iterator.py
> +    def __getattribute__(cls, name):
lol, agreed ;)

2021-10-25 17:51 UTC, nitzmahone approved these changes
Code changes look good; *probably* could use a changelog, but I could go either way.

2021-10-25 18:50 UTC, sivel approved these changes

2021-10-26 08:16 UTC, merged