Become: Change use of "yes" to "true" to promote ansible-lint compliance
ansible/ansible pull request #74531
Opened 2021-05-01 18:51 UTC by ChristopherJHart

##### SUMMARY
The [ansible-lint project](https://github.com/ansible-community/ansible-lint) leverages [yamllint](https://github.com/adrienverge/yamllint) rules by default. Yamllint has a [truthy rule](https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.truthy), which will alert on the `become: yes` statement that is used heavily in Ansible documentation. This PR changes `become: yes` to `become: true`, which is `ansible-lint` compliant.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
"Become" chapter in Ansible User Guide

##### ADDITIONAL INFORMATION
Other sections of the Ansible documentation contain similar `ansible-lint` compliance issues. It may be worth analyzing popular core documentation for non-compliance and correcting those documents first, then propagating similar changes to downstream modules.

2021-05-02 21:13 UTC, imjoseangel reviewed
LGTM

2021-05-03 13:29 UTC, sivel commented
We explicitly prefer `yes`/`no` in our documentation instead of `true`/`false`.

2021-05-03 13:31 UTC, bcoca requested changes
Many of us disagre with the opinion(s) in ansible-lint, 'yes/no' is preferred as a more user friendly approach.

2021-05-03 13:44 UTC, ChristopherJHart commented
@sivel @bcoca Is this preference documented in the [Ansible Style Guide](https://docs.ansible.com/ansible/latest/dev_guide/style_guide/index.html)? I reviewed that document as well as the [Contributing to the Ansible Documentation](https://docs.ansible.com/ansible/latest/community/documentation_contributions.html) document for guidance on whether there was a preference between `yes`/`no` and `true`/`false`, but wasn't able to find one. As a result, I assumed that the root of this "issue" was in Ansible's documentation, not ansible-lint's rules.

If we can get this documented, we might be able ask ansible-lint to justify ignoring yamllint's opinion on `yes`/`no` vs. `true`/`false`.

2021-05-03 14:23 UTC, imjoseangel commented
Probably good to open a change request under [ansible-lint](https://github.com/ansible-community/ansible-lint) project.

2021-05-03 14:24 UTC, bcoca commented
our preferences on how we document and explain usage is not the same as something we want to force onto users, otherwise it is something we could have restricted in the code.

2021-05-04 15:20 UTC, samdoran commented
Closing per above.

2021-05-04 15:20 UTC, closed without merging

2021-05-04 15:23 UTC, ChristopherJHart commented
@bcoca I appreciate your insight on the documentation's style guide! I'll reference this issue in the ansible-lint project to see if we can disable/ignore this rule.

Thank you!