fix: action _fixup_perms2 macos +a remote_paths in list() as it can be a tuple
ansible/ansible pull request #74613
Opened 2021-05-07 07:15 UTC by shane-axiom

##### SUMMARY
in `lib/ansible/plugin/action/__init__.py`'s `_fixup_perms2`, `remote_paths` can be a list or tuple. however, the macos specific attempt to use chmod +a attempts to concatenate `remote_paths` with a list, which will fail if it is a tuple. wrapping `remote_paths` in `list()` fixes this error.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/plugins/action

##### ADDITIONAL INFORMATION
Traceback before fix:

```
The full traceback is:
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/ansible-keryx-2-11/lib/python3.8/site-packages/ansible/executor/task_executor.py", line 159, in run
    res = self._execute()
  File "/home/user/miniconda3/envs/ansible-keryx-2-11/lib/python3.8/site-packages/ansible/executor/task_executor.py", line 583, in _execute
    result = self._handler.run(task_vars=variables)
  File "/home/user/miniconda3/envs/ansible-keryx-2-11/lib/python3.8/site-packages/ansible/plugins/action/template.py", line 186, in run
    result.update(copy_action.run(task_vars=task_vars))
  File "/home/user/miniconda3/envs/ansible-keryx-2-11/lib/python3.8/site-packages/ansible/plugins/action/copy.py", line 519, in run
    module_return = self._copy_file(source_full, source_rel, content, content_tempfile, dest, task_vars, follow)
  File "/home/user/miniconda3/envs/ansible-keryx-2-11/lib/python3.8/site-packages/ansible/plugins/action/copy.py", line 316, in _copy_file
    self._fixup_perms2((self._connection._shell.tmpdir, remote_path))
  File "/home/user/miniconda3/envs/ansible-keryx-2-11/lib/python3.8/site-packages/ansible/plugins/action/__init__.py", line 627, in _fixup_perms2
    res = self._remote_chmod([chmod_acl_mode] + remote_paths, '+a')
TypeError: can only concatenate list (not "tuple") to list

```

2021-05-07 07:16 UTC, shane-axiom commented
@relrod

2021-05-07 07:53 UTC, mkrizek requested changes
This needs a changelog, see https://docs.ansible.com/ansible/latest/community/development_process.html#changelogs, and likely a test.

2021-05-10 07:43 UTC, srstsavage commented
@mkrizek Added a changelog fragment. I took a look at the [test case](https://github.com/ansible/ansible/blob/devel/test/units/plugins/action/test_action.py#L457-L459) but couldn't yet figure out how this could be tested as the test case also does the list + `remote_paths` concatenation and assumes that `remote_paths` is a list.

2021-05-10 21:59 UTC, relrod commented on changelogs/fragments/74613-actionfixup_perms2_macos_remote_paths_ensure_list.yml
> +  - "In lib/ansible/plugin/action/__init__.py's _fixup_perms2, wrap ``remote_paths`` in ``list()`` before appending it to another list as it can be a list or tuple (https://github.com/ansible/ansible
```suggestion
  - "remote tmpdir permissions - fix type error in macOS chmod ACL fallback (https://github.com/ansible/ansible/pull/74613)."
```

2021-05-10 22:00 UTC, relrod approved these changes

2021-05-11 15:08 UTC, merged