[2.10]: Fix checksum binary validation
ansible/ansible pull request #74674
Opened 2021-05-12 06:27 UTC by resmo

##### SUMMARY
backport of #74502 and #71435 ( /cc @Akasurde )

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

get_url

##### ADDITIONAL INFORMATION

```paste below

```

2021-05-17 03:05 UTC, relrod commented
needs_info (failing CI)

2021-06-18 05:17 UTC, resmo commented
rebased

2021-06-18 05:41 UTC, Akasurde requested changes

2021-06-18 05:41 UTC, Akasurde commented on test/integration/targets/get_url/tasks/main.yml
> +  register: stat_result_sha256_with_file_scheme
`get_url` does not have support for `file://` in Stable-2.10 which was added via https://github.com/ansible/ansible/pull/71205

2021-06-18 05:41 UTC, Akasurde commented on test/integration/targets/get_url/tasks/main.yml
> +
Same as above.

2021-06-18 05:47 UTC, Akasurde commented on test/integration/targets/get_url/tasks/main.yml
> +  register: stat_result_sha256_with_file_scheme
Added backport via https://github.com/ansible/ansible/pull/75052

2021-07-12 05:40 UTC, relrod commented
This needs another rebase and to see if it passes tests now that #75052 was merged.

needs_info

2021-07-12 11:02 UTC, resmo commented
rebased but zuul is not happy.

I don't see why and how to make zuul happy.

2021-07-12 18:25 UTC, samdoran commented
recheck

2021-07-12 18:42 UTC, samdoran commented
The Zuul check was enabled by mistake and can be ignored.

2021-07-12 18:48 UTC, merged