WIP: Moves the AWS Scenario Guide out of the main docs
ansible/ansible pull request #74704
Opened 2021-05-14 15:06 UTC by acozine

##### SUMMARY

The Scenario Guides belong with the modules and other collection-based resources they describe. This PR removes them from the core repo. https://github.com/ansible-community/antsibull/pull/255 allows publication of .rst files from collections to docs.ansible.com. https://github.com/ansible-collections/amazon.aws/pull/362 adds this content to the amazon.aws collection. 

We'll need to merge the other two PRs first, so we can uncomment and test the link to the AWS Scenario Guide in its new location. 

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
docs.ansible.com

2021-05-14 16:36 UTC, felixfontein commented
Shouldn't we replace docs/docsite/rst/scenario_guides/guide_aws.rst by a stub which has a ref to `ansible_collections.amazon.aws.docsite.aws_intro`?

2021-05-14 19:50 UTC, acozine commented
Ah, good point @felixfontein, I forgot about that.

2021-05-17 18:33 UTC, felixfontein approved these changes

2021-06-24 15:53 UTC, acozine commented
/azp run

2021-07-06 15:38 UTC, acozine commented
rebuld_merge

2021-07-06 16:49 UTC, acozine commented
Whoops, typo. Trying again to kick CI without merging.

/azp run

2021-08-06 06:19 UTC, felixfontein commented
Needs a rebase due to #75375.

2021-08-11 19:42 UTC, acozine commented
Rebased. Still need a release of ansible.aws before we can merge this PR and remove the Guide.

2021-09-23 18:02 UTC, felixfontein commented
@samccann @ariordan-redhat now that amazon.aws 2.0.0 has been released with this guide (it's available at https://docs.ansible.com/ansible/devel/collections/amazon/aws/docsite/guide_aws.html), I think it's time to complete this PR!

2021-10-06 17:03 UTC, tremble approved these changes
LGTM

2021-10-06 17:06 UTC, tremble requested changes

2021-10-06 17:06 UTC, tremble commented on docs/docsite/rst/scenario_guides/cloud_guides.rst
> +:ref:`ansible_collections.amazon.aws.docsite.aws_intro`
Actually, I'm failing to see this file in the Amazon.AWS collection

2021-10-06 17:07 UTC, tremble commented on docs/docsite/rst/scenario_guides/cloud_guides.rst
> +:ref:`ansible_collections.amazon.aws.docsite.aws_intro`
Am I looking in the right place?   https://github.com/ansible-collections/amazon.aws/tree/main/docs/docsite

2021-10-06 17:15 UTC, felixfontein commented on docs/docsite/rst/scenario_guides/cloud_guides.rst
> +:ref:`ansible_collections.amazon.aws.docsite.aws_intro`
See the label: https://raw.githubusercontent.com/ansible-collections/amazon.aws/main/docs/docsite/rst/guide_aws.rst

2021-10-06 17:18 UTC, ariordan-redhat commented on docs/docsite/rst/scenario_guides/cloud_guides.rst
> +:ref:`ansible_collections.amazon.aws.docsite.aws_intro`
@tremble
It's here: 
https://raw.githubusercontent.com/ansible-collections/amazon.aws/main/docs/docsite/rst/guide_aws.rst

2021-10-06 18:03 UTC, tremble approved these changes

2021-10-06 18:03 UTC, tremble commented on docs/docsite/rst/scenario_guides/cloud_guides.rst
> +:ref:`ansible_collections.amazon.aws.docsite.aws_intro`
Ah the label right up at the top!

2021-10-06 19:34 UTC, ariordan-redhat approved these changes
Looks good to me

2021-10-06 19:34 UTC, merged