Document real plugin directory names
ansible/ansible pull request #74729
Opened 2021-05-17 11:43 UTC by 0mp

##### SUMMARY

The way plugin directory names were documented was a bit confusing. Plugin
directory names do not end with "_plugin". Adjust the documentation
accordingly.

##### ISSUE TYPE
- Docs Pull Request

+label: docsite_pr

2021-05-17 13:03 UTC, mkrizek commented
This does not appear to be correct change. Can you be a more specific?

```
% cat ../ansible-issues/74729.yml
- hosts: localhost
  gather_facts: no
  tasks:
    - debug:
        msg: "{{ 'hello' | custom_filter }}"
```

```
% cat ../ansible-issues/filter_plugins/custom_filter.py
class FilterModule:
    def filters(self):
        return {
            'custom_filter': lambda x: '"%s" was custom filtered!' % x,
        }
```

```
% ansible-playbook ../ansible-issues/74729.yml

PLAY [localhost] **********************************************************************************************************************************************

TASK [debug] **************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "\"hello\" was custom filtered!"
}

PLAY RECAP ****************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

2021-05-17 13:33 UTC, 0mp commented
Hmmm, I see now where my confusion is.

The documentation says that plugin directories must end with `_plugins` as documented here: https://github.com/ansible/ansible/blame/fd430c688fa529b416ccb32df4ba5362a3539eba/docs/docsite/rst/dev_guide/developing_locally.rst#L74-L84

However, in the same document the suggested directories for modules are without the `_plugins` suffix, e.g., `~/.ansible/plugins/callback`: https://github.com/ansible/ansible/blame/fd430c688fa529b416ccb32df4ba5362a3539eba/docs/docsite/rst/dev_guide/developing_locally.rst#L93-L94

Later on, the documentation mentions some examples for directories with the `_plugins` suffix: https://github.com/ansible/ansible/blame/fd430c688fa529b416ccb32df4ba5362a3539eba/docs/docsite/rst/dev_guide/developing_locally.rst#L104-L105

The confusing part is that the plugin types are never listed without the `_plugins` suffix.

I am not sure if I know how to improve this document to be less confusing to new users. Thanks for reviewing my patch neverthless, @mkrizek. :)

2021-05-17 13:45 UTC, mkrizek commented
@0mp Thanks for bringing this up, this indeed looks like something that should be improved.

2021-05-17 14:14 UTC, bcoca commented
Those names are for 'adjacent' directories vs 'configured', the adjacent to play or inside a role do follow that naming scheme. When it comes to 'configured paths' it does not matter since we don't need to 'auto detect' the directories.

2021-05-17 15:51 UTC, acozine commented
In the past, modules were treated as "special" plugins, so the directory for them is not named `module_plugins` - instead it is just named `modules`. The current documentation is correct, though you're right that we don't have a list of all the plugin types separate from the list of plugin directories. The closest we have is in https://docs.ansible.com/ansible/latest/dev_guide/developing_plugins.html#developing-particular-plugin-types. We should for sure be linking between those two pages.

2021-05-17 16:02 UTC, acozine commented
Ah, we do link to the developing plugins page here: https://github.com/ansible/ansible/pull/74729/files#diff-f86624f19b3c2b63c00584651a666437a3abc75fdda23ba8ed56129435d72e49R10. Maybe we should also link to 

The other place we list all the plugin types is in the User Guide:https://docs.ansible.com/ansible/latest/plugins/plugins.html. Maybe we should link from this page to that one as well . . .

2021-05-17 16:03 UTC, acozine requested changes
@0mp thanks for the PR and the discussion - the current change isn't the right fix for the problem. 

Can you open an issue with a little more detail? What was your goal when you came to the documentation? What did you expect? What confused you? Something like, "I searched for 'Ansible add plugin' and got to this page. I was looking for information on creating a custom plugin, and the list of directories was confusing. I couldn't find a list of all the plugin types anywhere." That would help us figure out ways to address the problem. 

Add a "related to" note with a link back to this PR from the Issue.

2021-06-25 16:55 UTC, acozine commented
Superseded by #75050. 

@0mp if the changes from the PR above didn't help, feel free to open a ticket with more information. You can also join the #ansible-docs channel on [Libera Chat IRC](https://libera.chat/) to discuss this informally, or add it to the [agenda](https://github.com/ansible/community/issues/579) for the [Docs Working Group](https://github.com/ansible/community/wiki/Docs). 

Thanks for taking the time to help us improve the Ansible documentation!

2021-06-25 16:55 UTC, closed without merging