Update infoblox scenario guide
ansible/ansible pull request #74727
Opened 2021-05-17 09:25 UTC by Akasurde

##### SUMMARY

Replaced Dynamic inventory script details with
Dynamic Inventory plugin details in Infoblox scenario guide.

Fixes: #73675

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
docs/docsite/rst/scenario_guides/guide_infoblox.rst

2021-05-17 09:27 UTC, Akasurde commented
cc @justjais Could you please review this? Thanks in advance.

2021-05-17 11:06 UTC, felixfontein commented on docs/docsite/rst/scenario_guides/guide_infoblox.rst
> +Ansible provides a dynamic inventory plugin for Infoblox.
Ansible does not do that. The Infoblox collection does. As long as infoblox.nios_modules is not included in Ansible, this is an important distinction :)

2021-05-20 06:15 UTC, justjais approved these changes

2021-05-21 15:41 UTC, samccann requested changes
Putting this on hold, please don't merge yet.
The infoblox collection is not in Ansible the package and that is what we document right now on docs.ansible.com.  I'll need to request advice from The Powers That Be on what to do here.

2021-06-01 17:04 UTC, samccann commented
The Powers that Be came back with a decision. We've written up a 'generic' comment reply that I'll post below and then close this issue. Using the generic comment to get your feedback @Akasurde to see if it's clear enough or needs more detail, for when we hit this situation with another PR from the community.  Thanks for your patience and helping us through this!

2021-06-01 17:05 UTC, samccann commented
Thanks @Akasurde for the PR. This content refers to functionality in a collection, and does not belong in the ansible/ansible repository. Can you please move this scenario guide to your collection /docs/ folder? You have two options:

1. Add it as .rst to the docs/docsite/rst sub-folder in the collection repo. This will keep the document with the collection. The reStructuredText content will be published on docs.ansible.com if the collection is included in a future version of Ansible.
2. Convert it to .md and add it directly to the collection /docs folder. The markdown content will appear in Automation Hub if the collection achieves Red Hat certification.

You can do either or both of these and then please open a PR in ansible/ansible to remove the old scenario guide.

2021-06-01 17:05 UTC, closed without merging