Doc: Update plugin page
ansible/ansible pull request #74769
Opened 2021-05-19 16:37 UTC by Akasurde

##### SUMMARY

* Added Doc Fragment Plugin documentation
* Fix links

Fixes: #73327

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
docs/docsite/rst/dev_guide/developing_collections_shared.rst
docs/docsite/rst/dev_guide/developing_modules_documenting.rst
docs/docsite/rst/dev_guide/developing_program_flow_modules.rst
docs/docsite/rst/dev_guide/platforms/aws_guidelines.rst
docs/docsite/rst/plugins/plugins.rst
docs/docsite/rst/user_guide/playbooks_doc_fragments.rst

2021-05-19 16:40 UTC, Akasurde commented
@acozine @samccann @lmalivert @abadger @felixfontein @Andersson007  I tried to cover all the requirements in https://github.com/ansible/ansible/issues/73327. Could you please help me out here? Thanks.

2021-06-16 15:35 UTC, Akasurde commented
cc @samccann @acozine @lmalivert

2021-06-16 16:17 UTC, samccann reviewed
Hey sorry for the delay in getting to this one!

So I think there is an easier way to do all of this... see the comments included.  Also, from the issue, I don't know if we have a terminal plugins page? I can't find one...

Looks like there was one other suggestion to move rejecting_modules down to the seealso section. I would also add links to the following in seealso as well to cover what the issue suggests: 
 modules (use the working_with_modules anchor)
- module_utils (use the developing_module_utilities anchor)

2021-06-16 16:17 UTC, samccann commented on docs/docsite/rst/user_guide/playbooks_doc_fragments.rst
> +
I'm unclear why it was necessary to move this section to its own page?  I also don't see this page included anywhere in an index file.  I'm guessing you moved it so you could get a page to link to, but the <../user_guide/foo> approach for linking is an outdated approach. We prefer :ref:`title<anchor>` as that ensures if we do decide to move the section somewhere else, all the old anchors will still work.  So for example, if you had to move this section for other reasons, if you had kept the anchor the same as the old section `.. _module_doc_fragments`, you wouldn't need to update that wherever it was used.

2021-06-16 16:17 UTC, samccann commented on docs/docsite/rst/plugins/plugins.rst
> +   Filter Plugins <../user_guide/playbooks_filters>
```suggestion
   :ref:`Filter Plugins<playbooks_filters>`
```

2021-06-16 16:17 UTC, samccann commented on docs/docsite/rst/plugins/plugins.rst
> +   Test Plugins <../user_guide/playbooks_tests>
```suggestion
   :ref:`Test Plugins<playbooks_tests>`
```

2021-06-16 16:17 UTC, samccann commented on docs/docsite/rst/plugins/plugins.rst
> +   Doc Fragments Plugins <../user_guide/playbooks_doc_fragments>
Rather than move that section to its own page, this can be handled with the following :
:ref:`Doc Fragments Plugins<module_docs_fragments>`

Then you can keep the doc fragments section where it is and link directly to it (and also keep the old references in place to that anchor (module_docs_fragments).

2021-06-16 16:17 UTC, samccann commented on docs/docsite/rst/dev_guide/developing_collections_shared.rst
> +:ref:`playbooks_doc_fragments` covers the basics for documentation fragments. The `kubernetes.core <https://github.com/ansible-collections/kubernetes.core>`_ collection includes a complete example.
please leave the old anchor as is.  This will make sense when you read later comments...

2021-06-16 16:17 UTC, samccann commented on docs/docsite/rst/dev_guide/developing_modules_documenting.rst
> -.. _module_docs_fragments:
please leave this section as is.  This will make sense when you see later comments.

2021-06-16 16:17 UTC, samccann commented on docs/docsite/rst/dev_guide/developing_program_flow_modules.rst
> +You can find `a list of all file options here <https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/doc_fragments/files.py>`_. It is recommended that you make your ``DOCUMENTATION`` exte
Please leave this anchor as is.  Will make sense later, I promise :-)

2021-06-16 16:17 UTC, samccann commented on docs/docsite/rst/dev_guide/platforms/aws_guidelines.rst
> +There are two :ref:`common documentation fragments <playbooks_doc_fragments>`
Please leave the old anchor as is.

2021-06-17 12:54 UTC, acozine requested changes
@Akasurde thanks for the PR and for raising the profile of this issue! The instructions for using docs fragments shouldn't move to the User Guide, since users don't need to know about them. I'm going to do some work on this issue - I'll leave this PR open for now, and either update it or open another PR in the next couple of days.

2021-06-17 21:36 UTC, acozine commented
Superseded by #75050.

2021-06-17 21:36 UTC, closed without merging