maleable verbosity
ansible/ansible pull request #74888
Opened 2021-06-02 15:27 UTC by bcoca

Adds 'verbosity' keyword to plays

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

playbook

2021-06-02 19:04 UTC, briantist commented
I like this

2021-06-03 14:01 UTC, s-hertel requested changes

2021-06-03 14:01 UTC, s-hertel commented on lib/ansible/executor/task_executor.py
> +        display.verbosity = self._task.verbosity
At first I assumed this might fix https://github.com/ansible/ansible/issues/24215 + supersede https://github.com/ansible/ansible/pull/41621. But it doesn't expand verbosity of a single task result, just connection info. I'd prefer if the FA was moved to Play instead of Base (or that this would increase verbosity for the whole task process).

2021-06-03 14:06 UTC, bcoca commented on lib/ansible/executor/task_executor.py
> +        display.verbosity = self._task.verbosity
FA being in base already affects play, but finding the right place to increase verbosity is tricky, i just added it after the full task was post_validated, but we can move before that as long as we ensure we template verbosity at that point (for one i was missing the task file path)

2021-06-03 14:10 UTC, s-hertel commented on lib/ansible/executor/task_executor.py
> +        display.verbosity = self._task.verbosity
Yes. The point of moving it from Base to Play was to not support it for Task until it seems more complete.

2021-06-03 15:01 UTC, bcoca commented on lib/ansible/executor/task_executor.py
> +        display.verbosity = self._task.verbosity
updated code to handle this in strategy, it should be what most require (problem before is we only affected display in subproc, so callbacks were ignoring change).

2021-06-03 15:29 UTC, bcoca commented
right now, thinking this is not possible per task if you want to get all the task info, since that has to happen in main proc and affects 'other tasks in parallel', this is not much of an issue in linear strategy (only at task start/end boundries) but for free .. this won't work at all.

2021-06-03 15:31 UTC, bcoca commented
Another approach is to restore back to task executor and have callbacks check 'task.verbosity' over display.verbosity

2021-06-21 21:13 UTC, closed without merging