WIP: Update plugin docs
ansible/ansible pull request #75050
Opened 2021-06-17 21:25 UTC by acozine

##### SUMMARY
Closes #73327
Supersedes #74769 

Adds a page for every plugin type, adds cross-linking to multiple related topics, edits existing plugin pages for style, etc.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
docs.ansible.com

2021-06-18 04:21 UTC, Akasurde commented on docs/docsite/rst/plugins/callback.rst
> +Callback plugins enable adding new behaviors to Ansible when responding to events. By default, callback plugins control most of the output you see when running the command line programs, but can also
```suggestion
Callback plugins enable adding new behaviors to Ansible when responding to events. By default, callback plugins control most of the output you see when running the command-line programs, but can also be used to add additional output, integrate with other tools, and marshall the events to a storage backend. If necessary, you can :ref:`create custom callback plugins <developing_callbacks>`.
```

2021-06-18 15:27 UTC, acozine commented on docs/docsite/rst/plugins/callback.rst
> +Callback plugins enable adding new behaviors to Ansible when responding to events. By default, callback plugins control most of the output you see when running the command line programs, but can also
Good catch, thanks @Akasurde.

2021-06-20 16:08 UTC, tadeboro requested changes
I found a few Freenode references in the docs, but apart from that, things do look OK from my side.

2021-06-20 16:08 UTC, tadeboro commented on docs/docsite/rst/plugins/docs_fragment.rst
> +   `irc.freenode.net <http://irc.freenode.net>`_
This should point to Libera.

2021-06-20 16:08 UTC, tadeboro commented on docs/docsite/rst/plugins/filter.rst
> +   `irc.freenode.net <http://irc.freenode.net>`_
Should point to Libera.

2021-06-20 16:08 UTC, tadeboro commented on docs/docsite/rst/plugins/module_util.rst
> +   `irc.freenode.net <http://irc.freenode.net>`_
Libera.

2021-06-20 16:08 UTC, tadeboro commented on docs/docsite/rst/plugins/module_util.rst
> +Module utilities contain shared code used by multiple modules. You can write :ref:`custom module utilities <developing_module_utilities>`.
Code from the `module_utils` directory can (and often is) also used by other plugin kinds, not only modules.

2021-06-20 16:08 UTC, tadeboro commented on docs/docsite/rst/plugins/terminal.rst
> +   `irc.freenode.net <http://irc.freenode.net>`_
Libera.

2021-06-20 16:08 UTC, tadeboro commented on docs/docsite/rst/plugins/test.rst
> +   `irc.freenode.net <http://irc.freenode.net>`_
Libera.

2021-06-20 16:08 UTC, tadeboro commented on docs/docsite/rst/plugins/action.rst
> +Action plugins act in conjunction with :ref:`modules <working_with_modules>` to execute the actions required by playbook tasks. They usually execute automatically in the background doing prerequisite
Maybe we should add something along the lines of "action plugin is the control node part of a module"? This should help explain why action plugins share their documentation with the module.

2021-06-21 16:03 UTC, acozine commented on docs/docsite/rst/plugins/module_util.rst
> +Module utilities contain shared code used by multiple modules. You can write :ref:`custom module utilities <developing_module_utilities>`.
ah, good catch, thanks

2021-06-21 16:04 UTC, acozine commented on docs/docsite/rst/plugins/docs_fragment.rst
> +   `irc.freenode.net <http://irc.freenode.net>`_
well spotted! I've fixed those in 6f2b1c71c73aa833220fc996bb108ef5a520f63f

2021-06-21 19:45 UTC, samccann reviewed
one nit

2021-06-21 19:45 UTC, samccann commented on docs/docsite/rst/plugins/callback.rst
> +Callback plugins enable adding new behaviors to Ansible when responding to events. By default, callback plugins control most of the output you see when running the command line programs, but can also
```suggestion
Callback plugins enable adding new behaviors to Ansible when responding to events. By default, callback plugins control most of the output you see when running the command line programs, but can also be used to add additional output, integrate with other tools and marshal the events to a storage backend. If necessary, you can :ref:`create custom callback plugins <developing_callbacks>`.
```

2021-06-21 19:50 UTC, tadeboro approved these changes
Thank you, @acozine, for preparing this PR.

2021-06-21 20:07 UTC, merged