dnf - properly ignore packages to uninstall not installed (#75021)
ansible/ansible pull request #75277
Opened 2021-07-16 19:39 UTC by ssato

dnf - properly ignore packages to uninstall not installed (#75021)

##### SUMMARY

dnf module tries to detect errors to uninstall packages by matching the error messages from dnf with the expected messages in _sanitize_dnf_error_msg_remove but it does not succeed because the error messages should vary depends on the locale configuration.

This change fixes this issue by catching an exception dnf.exceptions.PackagesNotInstalledError raised from dnf in such cases properly instead of matching with messages.

Fixes #75021

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

dnf

##### ADDITIONAL INFORMATION

There is another PR  to fix the same issue but I believe this PR is much better to fix this specific issue.

And it works as expected as far as I tested in my environment like below.

```
$ locale                                                  ~
LANG=ja_JP.UTF-8
LC_CTYPE="ja_JP.UTF-8"
LC_NUMERIC="ja_JP.UTF-8"
LC_TIME="ja_JP.UTF-8"
LC_COLLATE="ja_JP.UTF-8"
LC_MONETARY="ja_JP.UTF-8"
LC_MESSAGES="ja_JP.UTF-8"
LC_PAPER="ja_JP.UTF-8"
LC_NAME="ja_JP.UTF-8"
LC_ADDRESS="ja_JP.UTF-8"
LC_TELEPHONE="ja_JP.UTF-8"
LC_MEASUREMENT="ja_JP.UTF-8"
LC_IDENTIFICATION="ja_JP.UTF-8"
LC_ALL=
$
```

2021-07-19 07:31 UTC, mkrizek requested changes
While this might fix the specific issue (https://github.com/ansible/ansible/issues/75021) it does not cover all cases and introduces a change in behavior that potentially _might_ not be desired.

Currently when installing and removing packages we catch a base generic exception `MarkingError` and then we look for a match in that exception's message for a couple of hardcoded messages that we do not consider a failure and do not treat them as such if we find a match.

I believe the reasons for this implementation are, at least, that 1) the hardcoded messages can actually come from different types of exceptions (that are based on `MarkingError`), 2) to allow for different version of DNF API be used which might throw different types of exceptions depending on the version. While it might not be as elegant as catching specific exceptions it is a robust and safe solution.

So as to this specific change:
* it will treat _all_ `PackageNotInstalledError` exceptions as non-failure as opposed to just those that `_sanitize_dnf_error_msg_remove` filters, this is a change in behavior that would need to be investigated,
* we would also need to investigate if DNF API is consistent in throwing `PackageNotInstalledError` in this specific scenario across versions,
* we would still need https://github.com/ansible/ansible/pull/75264 because we would still scrape the messages and https://github.com/ansible/ansible/pull/75264 covers all possible cases where we might see a failure in non-english environments,
* due to all of the above I would be hesitant to consider backporting this change to older releases.

Having said that I am not opposed to working towards using the specific exceptions and away from scraping the messages but we need to carefully go through the (multiple versions of) DNF API code and make sure we catch the right exceptions.

2021-07-20 15:35 UTC, s-hertel commented
Closing in favor of #75264.

2021-07-20 15:35 UTC, closed without merging

2021-07-20 18:13 UTC, ssato commented
>  it does not cover all
So? What's the problem you intended to focus on? From the beginning, I stated that that change fixes the specific problem.

> it will treat all PackageNotInstalledError exceptions ....

> we would also need to investigate if DNF API is consistent in throwing PackageNotInstalledError...
>  dnf: ensure we use the correct locale for dnf API #75264 covers all possible cases

The issue may be  that developers too naively consider that the messages from DNF are stable, looks static-const regardless of the user"s environments, which is actually NOT TRUE. I don't understand why you guys are not trying to resolve this exact problem instead of making hacks may hiding the real issues instead.

AFAIK, the exception PackageNotInstalledError looks *very* stable since it was introduced  in the early days of DNF which was derived from YUM as far as I researched with the git's log of DNF (https://github.com/rpm-software-management/dnf/commit/5ee682b7c14d70842215585a1c1042a437732b2a ) 8 years ago before RHEL 7 was born. That is, we might be able to think they are safe to use and ignore distributions of which DNF does not have its definition in fact, I think.

Excuse me but your logic that 'exceptions are NOT stable and depends on versions (it's NOT actually true AFAIK) and capturing messages which must  vary depends on users' environments (locale) is better than that' feels *very* strange for me.

2021-07-20 18:40 UTC, bcoca commented
@ssato why we normally force the locale on most package manager modules, dnf was an exception to this (fix currently on the way #75264).

In the case of dnf API the meaning and 'permanence' of the exceptions has varied over time and in this case the same exception applies to packages that once contrasted with other info, are not an error, which is what the `_sanatize_` function tries to emulate from the dnf CLI behaviour.

2021-07-21 07:03 UTC, ssato commented
> @ssato why we normally force the locale on most package manager modules, dnf was an exception to this (fix currently on the way #75264).
> 
> In the case of dnf API the meaning and 'permanence' of the exceptions has varied over time and in this case the same exception applies to packages that once contrasted with other info, are not an error, which is what the `_sanatize_` function tries to emulate from the dnf CLI behaviour.
> 
> Sadly we have found it common that the English/C messages are a lot more reliable than using the internal APIs.

I have understood. I didn't know APIs have such issues. Thanks for your clear explanation.