Call initialize_locale() automatically if it hasn't run.
ansible/ansible pull request #75317
Opened 2021-07-23 22:43 UTC by xavierholt

##### SUMMARY
This attempts to call `initialize_locale()` when necessary, rather than simply printing an error message.

It should deal with the warning I keep seeing when running Ansible from Python on a Raspberry Pi 4 via `ansible-runner`:
```
[WARNING]: ansible.utils.display.initialize_locale has not been called, this
may result in incorrectly calculated text widths that can cause Display to
print incorrect line lengths
```

##### ISSUE TYPE
- Bugfix/Feature (?) Pull Request

##### COMPONENT NAME
utils

##### ADDITIONAL INFORMATION
This changes the meaning of the `_LOCALE_INITIALIZED` variable slightly.  In the old version, it was set to true only if the `initialize_locale()` call succeeded; it's now set to true whenever the call is _attempted_ and the presence of `_LOCALE_INITIALIZATION_ERR` indicates that the call failed.

2021-07-27 15:27 UTC, sivel commented
We need the locale set as early as programmatically possible, otherwise this can have adverse side effects on other code.  Waiting until it's needed will be too late and can cause issues.

Since this represents itself via `ansible-runner` only, it would seem to indicate an issue in `ansible-runner` where the CLI entry points are not being invoked.

Can you provide a reproducer using ansible-runner that causes this issue?  Such as the `ansible-runner` command that is being executed?

2021-07-27 15:53 UTC, sivel requested changes
This looks like an issue with runner, and should be addressed there.  We'll need more info, and to work with the runner team.

2021-07-27 18:46 UTC, xavierholt commented
I did some more testing, and I'm seeing the warning exactly when:
- I invoke the `ansible-playbook` command (plain `ansible` is fine), and...
- ...at least one of `stdin`, `stdout`, or `stderr` is non-interactive.

If calling `initialize_locale()` on demand isn't viable you should close this PR, and I'll open a bug instead.  I don't think it's an `ansible-runner` problem, though - I think runner is just exposing the underlying problem by running `ansible-playbook` as a subprocess with I/O redirection.

2021-07-27 18:55 UTC, bcoca commented
I cannot reproduce what you are stating, it also makes no sense, both `ansible` and `ansible-playbook` do it the same way (its actually same code) at the start of it's invocation. 

If it is an issue with stdin (not sure how that is a factor) ... then why is it not an issue with your change, that just does it later in the same invocation?.

2021-07-27 18:59 UTC, sivel commented
Please provide a reproducer where we can see this behavior, preferably a reproducer using `ansible-runner`.

2021-07-28 00:41 UTC, xavierholt commented
I dug a bit deeper and figured it out - it was ultimately a configuration problem on my end.  I had installed Ansible 2.7.7 via APT, and then Pip had installed Ansible 2.11.3 as a dependency of `ansible-runner`.  The problem was with where things ended up on their respective paths:  The Ansible CLI script from 2.7.7 (with no `initialize_locale()`) was the first on my shell's path, but Ansible 2.11.3 (which expects `initialize_locale()`) was the first on Python's library path.  So I would end up running the old CLI but importing the new library, which complained.

The error never showed up when running plain `ansible` because the check only runs when printing `*`-padded screen-width "banners", which (as far as I can tell) only show up in the output of `ansible-playbook`.

Sorry for the noise!

2021-07-28 00:41 UTC, closed without merging