ansible-test - add RHEL 8.4 as a remote
ansible/ansible pull request #75362
Opened 2021-07-29 20:56 UTC by s-hertel

##### SUMMARY
Adds rhel/8.4 as a remote

##### ISSUE TYPE
- Test Pull Request

2021-07-29 21:38 UTC, mattclay requested changes

2021-07-29 21:38 UTC, mattclay commented on .azure-pipelines/azure-pipelines.yml
> +              test: rhel/8.4@3.8
Replace the existing 8.3 tests with 8.4 in our test matrix instead of adding new entries.

2021-07-29 21:47 UTC, mattclay commented on .azure-pipelines/azure-pipelines.yml
> +              test: rhel/8.4@3.8
There's another set of 8.3 entries to update under `Remote` (these are `Incidental Remote`).

2021-07-30 01:10 UTC, mattclay approved these changes

2021-07-30 05:35 UTC, Andersson007 commented
https://github.com/ansible-collections/overview/issues/45#issuecomment-889538991 (i almost did the same)

2021-07-30 15:19 UTC, merged