Fixing #75556 BUG
ansible/ansible pull request #75557
Opened 2021-08-24 11:51 UTC by MassimilianoPasquini97

Fixing #75556 BUG

##### SUMMARY
Fixing  #75556  BUG

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
module builtin subversion

2021-08-24 12:06 UTC, mkrizek requested changes
`--trust-server-cert-failures` was added in svn 1.9 ( https://subversion.apache.org/docs/release-notes/1.9.html#svn-trust) which means that this will make `validate_certs: no` unusable on machines with older svn versions.

The documentation above also states:
> If at all possible, fixing a certificate problem is preferable to using this option.

2021-08-24 13:47 UTC, MassimilianoPasquini97 commented
@mkrizek  The problem is that now the default value for validate_certs is 'no'. If the module is run on svn 1.9 and above, and the values is not changed to 'yes', the module goes on error because is append --trust-server-cert that is not supported anymore. In my opinion mast be changed to 'yes' by default and added an other parameter for permit user to append --trust-server-cert-failures.

2021-08-24 14:05 UTC, mkrizek commented
On subversion `1.10.2` which is available on Centos 8 the help says:
>   --trust-server-cert      : deprecated; same as --trust-server-cert-failures=unknown-ca

So it appears that the way forward here is to use `--trust-server-cert-failures=unknown-ca` but still fall back to `--trust-server-cert` to account for older versions.

2021-08-24 14:13 UTC, MassimilianoPasquini97 commented
I'm using Debian 10 with svn 1.10.4 and with this version ignore completely --trust-server-cert. We can use --trust-server-cert for older version and --trust-server-cert-failures=unknown-ca,cn-mismatch,other for version 1.9 and above

2021-08-24 14:20 UTC, mkrizek commented
> I'm using Debian 10 with svn 1.10.4 and with this version ignore completely --trust-server-cert. We can use --trust-server-cert for older version and --trust-server-cert-failures=unknown-ca,cn-mismatch,other for version 1.9 and above

I am not sure `--trust-server-cert-failures=unknown-ca,cn-mismatch,other` is correct since that would change behavior, `svn help checkout` suggests that `--trust-server-cert` is same as `--trust-server-cert-failures=unknown-ca`. So it seems that for other failures, the certificate should be fixed.

2021-08-24 14:26 UTC, mkrizek commented
Looking at subversion `1.14.1` on Debian 11, the option is still available:
>   --trust-server-cert      : deprecated; same as
>                             --trust-server-cert-failures=unknown-ca

So it is not the option that is the issue on your system, it is the certificate that does not passes `--trust-server-cert-failures=unknown-ca`, that is why using `--trust-server-cert-failures=unknown-ca,cn-mismatch,other` fixes your issue.

2021-08-24 14:30 UTC, MassimilianoPasquini97 commented
Debian10, svn help checkout on 1.10.4
```
--trust-server-cert      : deprecated; same as
                             --trust-server-cert-failures=unknown-ca
  --trust-server-cert-failures ARG : with --non-interactive, accept SSL server
                             certificates with failures; ARG is comma-separated
                             list of 'unknown-ca' (Unknown Authority),
                             'cn-mismatch' (Hostname mismatch), 'expired'
                             (Expired certificate), 'not-yet-valid' (Not yet
                             valid certificate) and 'other' (all other not
                             separately classified certificate errors).
```
macOS 11.5.2, svn help checkout  1.14.1 `--trust-server-cert` and `--trust-server-cert-failures` completely gone

2021-08-24 14:33 UTC, MassimilianoPasquini97 commented
We can use `--trust-server-cert-failures=unknown-ca,cn-mismatch,other` for 1.9 and above and `--trust-server-cert` for older version. We can consider to switch validate-certs value to 'yes' by default.

2021-08-24 14:51 UTC, mkrizek commented
> macOS 11.5.2, svn help checkout 1.14.1 --trust-server-cert and --trust-server-cert-failures completely gone

I had to add `-v` to see the global options, so `svn help checkout -v` to see that `--trust-server-cert` is still there.

2021-08-24 15:56 UTC, MassimilianoPasquini97 commented
> > macOS 11.5.2, svn help checkout 1.14.1 --trust-server-cert and --trust-server-cert-failures completely gone
> 
> I had to add `-v` to see the global options, so `svn help checkout -v` to see that `--trust-server-cert` is still there.

Sorry, with `svn help checkout -v` on macOS svn 1.14.1 I can see `--trust-server-cert` and `--trust-server-cert-failures`
```
--trust-server-cert      : deprecated; same as
                             --trust-server-cert-failures=unknown-ca
  --trust-server-cert-failures ARG : with --non-interactive, accept SSL server
                             certificates with failures; ARG is comma-separated
                             list of 'unknown-ca' (Unknown Authority),
                             'cn-mismatch' (Hostname mismatch), 'expired'
                             (Expired certificate), 'not-yet-valid' (Not yet
                             valid certificate) and 'other' (all other not
                             separately classified certificate errors).
```

I'm not the only person with this problem https://stackoverflow.com/questions/62144479/ansible-how-to-trust-certificates.
We can fix this problem using `--trust-server-cert` for svn version before 1.9 and `--trust-server-cert-failures=unknown-ca,cn-mismatch,other` for 1.9 and later version. I suggest to set `validate_certs` to `yes` as a default value in case this option become deprecated in the future. If you agree I can start to code the changes.

2021-08-25 07:48 UTC, mkrizek commented
I am still confused by this change. The bug report that this PR aims to fix claims:

> In subversion module validate_certs parameter append '--trust-server-cert' instead of '--trust-server-cert-failures=unknown-ca,cn-mismatch,other' causing module error with latest svn version.

We showed that `--trust-server-cert` is still available on all released `subversion` versions so no change is needed on the `subversion` Ansible module side right now.

I see two possible intents of this PR:

1. Since `--trust-server-cert` is deprecated, prepare `subversion` module for removal of the option by using `--trust-server-cert-failures=unknown-ca` (because that is the equivalent of `--trust-server-cert` according to `svn help checkout -v`) and fall back to `--trust-server-cert` when the new option is not available.

or

2. Extend the list of SSL server certificate errors that are accepted when `validate_certs: no` is used. 

    - This would be a change in behavior so the PR would need to be re-classified to a feature pull request.
    - We also need to make sure that this is done for all `subversion` versions, or at least properly document behavior if that is not possible - and according to [docs](https://subversion.apache.org/docs/release-notes/1.9.html#svn-trust) it is not possible: `Previous versions of Subversion in non-interactive mode could only ignore certificates with an unknown certificate authority, but expired or otherwise invalid SSL certificates could not be accepted.`.
    - If we were to take this route we would probably need to investigate it from the security point of view, is it acceptable to ignore all SSL certificate errors? [Docs](https://subversion.apache.org/docs/release-notes/1.9.html#svn-trust) also mention `If at all possible, fixing a certificate problem is preferable to using this option.`

Effectively the current PR as-is makes the `subversion` module behavior dependant on the `subversion` version being installed on the system because for `1.9` and higher it accepts `unknown-ca,cn-mismatch,other` certificates errors while on `1.8` and lower it only accepts `unknown-ca`.

cc'ing @relrod since he is the original author of `validate_certs` in the `subversion` module (https://github.com/ansible/ansible/pull/70890).

2021-08-25 08:15 UTC, MassimilianoPasquini97 commented
The problem is that with newer version of svn `--trust-server-cert-failures=unknown-ca` don't cover all certificate error so I prefer to use `--trust-server-cert-failures=unknown-ca,cn-mismatch,other` that cover all certificate error. Last modification I made cover the first solution, using `--trust-server-cert-failures=unknown-ca,cn-mismatch,other` for svn 1.9 or later and `--trust-server-cert` for older version. Like mention before I'm not the only person with this problem https://stackoverflow.com/questions/62144479/ansible-how-to-trust-certificates.

2022-05-31 18:00 UTC, closed without merging