added ansible_delegated_host
ansible/ansible pull request #75578
Opened 2021-08-26 17:59 UTC by bcoca

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

magic vars

2021-08-27 04:49 UTC, timway requested changes
I think it's just a simple spelling error.

2021-08-27 04:49 UTC, timway commented on docs/docsite/rst/user_guide/playbooks_vars_facts.rst
> +``ansible_delegatd_host`` is a sting, containing the ``inventory_hostname`` of the host you are delegating to in the task, only defined if doing delegation. ``inventory_hostname`` always reflects the
... is a _string_, containing the ... #nit

2021-08-27 07:50 UTC, qermit commented
@bcoca have you considered name `ansible_effective_host`  and have it and always have it available?

2021-08-27 14:32 UTC, bcoca commented
@qermit i initially wrote `ansible_connection_host` but it seemed less confusing to do it this way, that said, I'm open to hear arguments for/against.

2021-09-01 20:01 UTC, samccann commented on docs/docsite/rst/user_guide/playbooks_vars_facts.rst
> +``ansible_delegatd_host`` is a sting, containing the ``inventory_hostname`` of the host you are delegating to in the task, only defined if doing delegation. ``inventory_hostname`` always reflects the
```suggestion
``ansible_delegated_host`` is a string, containing the ``inventory_hostname`` of the host you are delegating to in the task. This is only defined if you are doing delegation.  The ``inventory_hostname`` always reflects the original host the task targeted.
```

2021-09-01 20:01 UTC, samccann commented on docs/docsite/rst/user_guide/playbooks_vars_facts.rst
> +``ansible_delegatd_host`` is a sting, containing the ``inventory_hostname`` of the host you are delegating to in the task, only defined if doing delegation. ``inventory_hostname`` always reflects the
something that confuses me here - I don't think it ever overwrites ``inventory_hostname``, right? If so then it should be ...is a string containing the hostname of the host you are delegating to ... (as in don't use inventory_hostname there).

2021-09-01 20:03 UTC, samccann commented
Coming at this as a noob - ``ansible_delegated_hostname`` makes sense to me if the task is using ``delegated_to`` etc.

2021-09-01 21:13 UTC, bcoca commented on docs/docsite/rst/user_guide/playbooks_vars_facts.rst
> +``ansible_delegatd_host`` is a sting, containing the ``inventory_hostname`` of the host you are delegating to in the task, only defined if doing delegation. ``inventory_hostname`` always reflects the
inventory_hostname is explicitly overwritten  in the delegated vars to the 'original host', if that is what you are asking

2021-09-01 21:13 UTC, bcoca commented
yeah, i was just lazy and wanted to save myself a name, have not decided 100% on variable name yet and open to bikeshed

2021-09-08 11:11 UTC, samccann approved these changes
Docs portion LGTM

2021-10-05 13:53 UTC, bcoca commented
rebuild_merge

2021-10-05 14:31 UTC, closed without merging