Support podman-remote in ansible-test
ansible/ansible pull request #75753
Opened 2021-09-21 21:30 UTC by sivel

##### SUMMARY
Support podman-remote in ansible-test

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
test/lib/ansible_test/_internal

##### ADDITIONAL INFORMATION

```paste below

```

2021-09-21 21:33 UTC, sivel commented on test/lib/ansible_test/_internal/docker_util.py
> +        stdout = raw_command(['podman', 'system', 'connection', 'list', '--format=json'], capture=True)[0]
Just a note here, `--format` doesn't exist in all versions.  Locally I have 3.3.1 and it exists there.  On a CentOS8 box I have 3.0.2 and it's missing there.

2021-09-21 21:36 UTC, sivel commented on test/lib/ansible_test/_internal/docker_util.py
> +        if connection['Name'][-1] == '*':
The trailing asterisk seems to be the only way the default is identified.

2021-09-23 21:33 UTC, sivel commented
Another note here, is that the `podman-remote` binary for macos is distributed as just `podman`, but on a system with full podman support, you need to either run `podman --remote ...` or `podman-remote ...`.

This change would need to probably need a way to specify that the user wants to use `podman-remote`, and add `--remote` in the podman commands.  `podman --remote` works on macos too.

Or maybe the existence of `CONTAINER_HOST` toggles this?

2022-03-09 16:14 UTC, sivel commented
/azp run

2022-03-09 16:50 UTC, mattclay commented on test/lib/ansible_test/_internal/docker_util.py
> +        stdout = raw_command(['podman', 'system', 'connection', 'list', '--format=json'], capture=True)[0]
It would be helpful to include this information in a comment for future reference.

2022-03-09 17:08 UTC, mattclay requested changes
A changelog entry is also needed.

2022-03-09 17:08 UTC, mattclay commented on test/lib/ansible_test/_internal/containers.py
> -    get_host_ip,
This function is no longer used and should be removed from `util.py`.

2022-03-09 17:31 UTC, mattclay approved these changes

2022-03-09 21:59 UTC, merged