Add `v2_runner_item_on_start` callback to callback plugins.
ansible/ansible pull request #75903
Opened 2021-10-06 15:37 UTC by x-t

##### SUMMARY

This PR adds the `v2_runner_item_on_start` callback that will execute on an item starting execution. I have also added default behaviour for this callback, including a new option `show_per_item_start` which is inspired by the `v2_runner_on_start` callback and its adjacent option `show_per_host_start`.

Implements #75874

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
callback

##### ADDITIONAL INFORMATION
Here's how the change looks:
```
$ cat test.yml
---
  - name: Test
    hosts: localhost
    tasks:
      - name: Test task
        command: "{{ item }}"
        with_items:
          - echo "hello"
          - echo "world"
          
$ ANSIBLE_SHOW_PER_ITEM_START=0 ansible-playbook test.yml

PLAY [Test] *******************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************
ok: [localhost]

TASK [Test task] **************************************************************************************************************
changed: [localhost] => (item=echo "hello")
changed: [localhost] => (item=echo "world")

PLAY RECAP ********************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

$ ANSIBLE_SHOW_PER_ITEM_START=1 ansible-playbook test.yml

PLAY [Test] *******************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************
ok: [localhost]

TASK [Test task] **************************************************************************************************************
 [started item "echo "hello"" in TASK: Test task]
changed: [localhost] => (item=echo "hello")
 [started item "echo "world"" in TASK: Test task]
changed: [localhost] => (item=echo "world")

PLAY RECAP ********************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

$
```

2021-10-06 15:43 UTC, sivel commented on lib/ansible/executor/task_executor.py
> +            self._final_q.send_callback('v2_runner_item_on_start', self._task, item)
I think it probably makes sense to move this after `loop_pause` block.  It should more closely indicate when the action actually starts processing.

2021-10-06 17:52 UTC, bcoca approved these changes

2021-10-07 19:32 UTC, sivel requested changes

2021-10-07 19:32 UTC, sivel commented on lib/ansible/executor/task_executor.py
> +            self._final_q.send_callback('v2_runner_item_on_start', self._task, item)
This is actually going to cause some performance problems. We prevent sending back a task object whenever possible, because serializing the object is very expensive.  This should probably send back `self._task._uuid` like we do for the `TaskResult`s.

However, the code that consumes the queue, only deals with fixing this in `TaskResult` objects.  We'd need to extend `ansible.plugins.strategy::results_thread_main` in some manner that can handle this.  The only problem, is that it's just a string, and we can't just try to convert every string to a task or host.  And we shouldn't special case callback names.  It'll need to be more generic, and likely require some new wrapper objects.

Additionally, all of these callbacks are per host when coming from the `TaskExecutor`, so they also will need to include `self._host` as well, which carries the same concern as the task object, and should use `self._host.name`.

I don't have an answer on how to handle this off the top of my head yet.

Another concern, regardless of the serialization, is that simply sending more items over the queue is expensive.

Let's assume we have 100 hosts, with 100 loop items.  We're going to be sending 10,000 more callbacks over the queue, which in itself could cause performance degradations.  So the performance aspect of this may ultimately outweigh the feature itself.

This PR, while simple on the surface, is likely going to require hours to days of investigation and work.

2021-10-21 07:15 UTC, x-t commented
Honestly, yeah. The performance concerns make perfect sense.

2021-10-21 07:15 UTC, closed without merging