code-block wrapping for user_guide/playbooks_filters.rst
ansible/ansible pull request #75953
Opened 2021-10-07 19:37 UTC by ferminhg

##### SUMMARY
Fixex #75896

Wraps code examples in code-block sections.

##### ISSUE TYPE

- Docs Pull Request

##### ADDITIONAL INFORMATION

- All instances of code examples changed:

```
grep -rn "^[[:blank:]]*[^[:blank:]\.\.].*::$" ./playbooks_filters.rst
```

- Manual testing: [generated the docs manually as described in the Contributor guide](https://docs.ansible.com/ansible/latest/dev_guide/testing/sanity/docs-build.html) and had a look at the generated HTML.

2021-10-12 06:10 UTC, Akasurde requested changes
rest LGTM

2021-10-12 06:10 UTC, Akasurde commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat requested changes
@ferminhg 
Thank you for creating this PR.

I added suggestions to change the `jinja` lexer to `yaml+jinja`. 
`jinja` would be more accurate, but it it is not an [allowed value](https://docs.ansible.com/ansible/latest/dev_guide/style_guide/index.html#syntax-highlighting-pygments) in the Ansible documentation.

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 10:30 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: jinja
```suggestion
.. code-block:: yaml+jinja
```

2021-10-14 12:55 UTC, ferminhg commented
@ariordan-redhat, I updated the code-block to use `yaml+jinja`  

I can fix this doc to avoid this mistake again:

https://github.com/ansible/ansible/blame/fd346565d3f681844e6223b93930b8039db59e95/docs/docsite/rst/user_guide/playbooks_vars_facts.rst#L522 

PD: I couldn't apply all your suggestions, GitHub raised errors in the frontend 🤣

2021-10-14 13:52 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: yaml+jinja
```suggestion
.. code-block:: text
```

2021-10-14 14:07 UTC, ariordan-redhat commented
> @ariordan-redhat, I updated the code-block to use `yaml+jinja`
> 
> I can fix this doc to avoid this mistake again: https://github.com/ansible/ansible/blame/fd346565d3f681844e6223b93930b8039db59e95/docs/docsite/rst/user_guide/playbooks_vars_facts.rst#L522
> 
> PD: I couldn't apply all your suggestions, GitHub raised errors in the frontend 🤣

@ferminhg I'll create a separate issue to fix `playbooks_vars_facts.rst`.

It looks like all my suggestions were applied in the end. 

I added one suggestion: a block with single `{` had a lexer tag. 

Could you rebase your  branch against devel, please?

2021-10-14 14:13 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +.. code-block:: yaml+jinja
```suggestion
.. code-block:: ini
```

2021-10-14 15:08 UTC, ariordan-redhat approved these changes
Looks good to me

2021-10-14 15:11 UTC, merged

2021-10-14 15:11 UTC, ariordan-redhat commented
@ferminhg 
Many thanks for your work on this issue.

2021-10-14 16:00 UTC, ariordan-redhat commented
@ferminhg 
I'm creating an issue to fix the lexers in [user_guide/playbooks_vars_facts.rst](https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/user_guide/playbooks_vars_facts.rst).

Do you want me to tag you in the issue? 
No pressure if you don't want to, but if you'd like to work on another hacktoberfest PR, leave a comment here.

2021-10-19 09:58 UTC, ferminhg commented
Hi @ariordan-redhat , yes !!!