Feat/add mising code block elements to playbooks strategies.rst
ansible/ansible pull request #75969
Opened 2021-10-08 04:57 UTC by hereje

##### SUMMARY
    feat: (docs): Add missing code-block elements on playbooks_strategies.rst
    
    ** add code-block elements on user guide/playbooks_strategies.rst file
    so that translation processes keep code as is
    
    - hacktoberfest 2021
    
    Fixes: #75911

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
user guide/ playbooks_strategies.rst

##### ADDITIONAL INFORMATION
```
There is no need of additional information
```

2021-10-08 05:02 UTC, Akasurde commented on docs/docsite/rst/user_guide/playbooks_startnstep.rst
> +To start executing your playbook at a particular task (usually the task that failed on the previous run), use the ``--start-at-task`` option:
Please remove this file as this is already modified here - https://github.com/ansible/ansible/pull/75967

2021-10-08 05:02 UTC, Akasurde requested changes
Please remove this file as this is already modified here - https://github.com/ansible/ansible/pull/75967

2021-10-08 05:47 UTC, hereje commented on docs/docsite/rst/user_guide/playbooks_startnstep.rst
> +To start executing your playbook at a particular task (usually the task that failed on the previous run), use the ``--start-at-task`` option:
Done. File does not belong to this change

2021-10-11 21:52 UTC, ariordan-redhat commented
Closing this PR: Issue 75911 has already been resolved with a merged PR.

@hereje Thank you for taking the time to contribute.

2021-10-11 21:53 UTC, closed without merging