docs - Use code-block to format code examples in user_guide/playbooks_vars_facts.rst
ansible/ansible pull request #75961
Opened 2021-10-08 00:54 UTC by Overflow0xFFFF

##### SUMMARY
Format all code blocks in `user_guide/playbooks_strategies.rst` with syntax highlighting.

Fixes ansible#75912.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
docs/docsite/rst/user_guide/playbooks_vars_facts.rst

##### ADDITIONAL INFORMATION
None.

2021-10-08 05:16 UTC, Akasurde requested changes

2021-10-08 05:16 UTC, Akasurde commented on docs/docsite/rst/user_guide/playbooks_vars_facts.rst
> +.. code-block:: none
```suggestion
.. code-block:: shell
```

2021-10-08 05:16 UTC, Akasurde commented on docs/docsite/rst/user_guide/playbooks_vars_facts.rst
> +.. code-block:: none
```suggestion
.. code-block:: shell
```

2021-10-08 05:16 UTC, Akasurde commented on docs/docsite/rst/user_guide/playbooks_vars_facts.rst
> +.. code-block:: json-object
```suggestion
.. code-block:: json
```

To match other occurances.

2021-10-08 05:16 UTC, Akasurde commented on docs/docsite/rst/user_guide/playbooks_vars_facts.rst
> +.. code-block:: json-object
```suggestion
.. code-block:: json
```

To match other occurrences in the existing documentation

2021-10-08 11:34 UTC, Overflow0xFFFF commented on docs/docsite/rst/user_guide/playbooks_vars_facts.rst
> +.. code-block:: json-object
I will gladly make the change requested! These were initially `json`, but didn't pass rstcheck. It'll require a little more doc change than just adding in code blocks.

2021-10-08 11:40 UTC, Overflow0xFFFF commented
Thank you for the feedback, @Akasurde! Changes have been amended to the commit and pushed up. Let me know what you think!

2021-10-11 20:27 UTC, ariordan-redhat approved these changes
Docs changes approved

2021-10-11 20:28 UTC, merged

2021-10-11 20:29 UTC, ariordan-redhat commented
@Overflow0xFFFF 
Thank you for contributing to the Ansible docs!

2021-10-11 20:29 UTC, ariordan-redhat commented
@Akasurde Thanks for doing a review !