Add default value for lvm_facts when lvm or lvm2 is not installed or …
ansible/ansible pull request #75989
Opened 2021-10-09 09:37 UTC by maheshbr

…there are no lvm facts

##### SUMMARY

- Adds a default value to `lvm_facts` as suggested [here](https://github.com/ansible/ansible/issues/17393#issuecomment-834570561)

Fixes: #17393
##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

- setup module for linux
##### ADDITIONAL INFORMATION

```paste below
N/A
```

2021-10-11 05:15 UTC, Akasurde requested changes

2021-10-11 05:15 UTC, Akasurde commented on lib/ansible/module_utils/facts/hardware/linux.py
> +        lvm_facts = {'lvm': 'N/A'}
Please create a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment). See [this fragment](https://github.com/ansible/ansible/blob/c2f528b7686c9573aa8493357219e0bbe4416dd3/changelogs/fragments/reboot-change-default-boot-command.yaml) as an example.

2021-10-11 08:07 UTC, maheshbr commented on lib/ansible/module_utils/facts/hardware/linux.py
> +        lvm_facts = {'lvm': 'N/A'}
Done, the changelog fragment has been added 👍🏾

2021-10-11 14:01 UTC, bcoca commented on lib/ansible/module_utils/facts/hardware/linux.py
> +        lvm_facts = {'lvm': 'N/A'}
I was thinking of standardizing on the work i did in  #74714 as a way to resolve 'unable to get facts' behaviour normalized

2021-10-11 20:18 UTC, maheshbr commented on lib/ansible/module_utils/facts/hardware/linux.py
> +        lvm_facts = {'lvm': 'N/A'}
I will leave it up to @Akasurde and @samdoiron to decide  🙌🏾

2022-01-26 21:17 UTC, williamhanseneric commented
Is there an initiative somewhere to allow us to see the facts via a become-like behavior?  I'd like to be able to sudo here and control lvm volumes, but if you can't see them... and your org doesn't permit login as root...

2022-01-27 14:41 UTC, bcoca commented
@williamhanseneric  like?
```
- setup:
  become: true
```

2022-01-27 22:52 UTC, williamhanseneric commented
If that works, I like yes

On Thu, Jan 27, 2022, 8:41 AM Brian Coca ***@***.***> wrote:

> @williamhanseneric <https://github.com/williamhanseneric> like?
>
> - gather_facts:
>   become: true
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ansible/ansible/pull/75989#issuecomment-1023280204>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AD3OIDGUFCLKKMNS7N4RV63UYFKSBANCNFSM5FVDJ3MA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-01-28 14:10 UTC, williamhanseneric commented
That does not work, you actually have to be root to get these facts...you
cannot use become

On Thu, Jan 27, 2022, 4:52 PM Eric Hansen ***@***.***>
wrote:

> If that works, I like yes
>
> On Thu, Jan 27, 2022, 8:41 AM Brian Coca ***@***.***> wrote:
>
>> @williamhanseneric <https://github.com/williamhanseneric> like?
>>
>> - gather_facts:
>>   become: true
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/ansible/ansible/pull/75989#issuecomment-1023280204>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AD3OIDGUFCLKKMNS7N4RV63UYFKSBANCNFSM5FVDJ3MA>
>> .
>> Triage notifications on the go with GitHub Mobile for iOS
>> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
>> or Android
>> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>>
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>

2022-01-28 14:14 UTC, williamhanseneric commented
My ansible version is 2.9.27 running Tower 3.8.4, if it matters

On Fri, Jan 28, 2022, 8:10 AM Eric Hansen ***@***.***>
wrote:

> That does not work, you actually have to be root to get these facts...you
> cannot use become
>
> On Thu, Jan 27, 2022, 4:52 PM Eric Hansen ***@***.***>
> wrote:
>
>> If that works, I like yes
>>
>> On Thu, Jan 27, 2022, 8:41 AM Brian Coca ***@***.***>
>> wrote:
>>
>>> @williamhanseneric <https://github.com/williamhanseneric> like?
>>>
>>> - gather_facts:
>>>   become: true
>>>
>>> —
>>> Reply to this email directly, view it on GitHub
>>> <https://github.com/ansible/ansible/pull/75989#issuecomment-1023280204>,
>>> or unsubscribe
>>> <https://github.com/notifications/unsubscribe-auth/AD3OIDGUFCLKKMNS7N4RV63UYFKSBANCNFSM5FVDJ3MA>
>>> .
>>> Triage notifications on the go with GitHub Mobile for iOS
>>> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
>>> or Android
>>> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>>>
>>> You are receiving this because you were mentioned.Message ID:
>>> ***@***.***>
>>>
>>

2022-01-28 18:04 UTC, williamhanseneric commented
There is only one place in the entirety of module_utils where they do this check to see if you are root (id==0)... the question I have would be why?  What is so special about this lvm data, I assert nothing.

[root@xxx module_utils]# grep -ri "os.getuid"
facts/system/user.py:        user_facts['real_user_id'] = os.getuid()
facts/hardware/linux.py:        if os.getuid() == 0 and self.module.get_bin_path('vgs'):
[root@xxx module_utils]#

2022-07-13 19:30 UTC, merged