update code-block formatting changes for playbook_variables.rst
ansible/ansible pull request #75985
Opened 2021-10-08 18:12 UTC by Accoustium

formatting updates for https://github.com/ansible/ansible/issues/75899

2021-10-11 22:44 UTC, ariordan-redhat requested changes
Adding suggestions for code-block lexers

2021-10-11 22:44 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_variables.rst
> +.. code-block:: yaml
```suggestion
.. code-block:: yaml+jinja
```

2021-10-11 22:44 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_variables.rst
> +.. code-block:: yaml
```suggestion
.. code-block:: yaml+jinja
```

2021-10-11 22:44 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_variables.rst
> +.. code-block:: yaml
```suggestion
.. code-block:: yaml+jinja
```

2021-10-11 22:44 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_variables.rst
> +.. code-block:: yaml
```suggestion
.. code-block:: yaml+jinja
```

2021-10-11 22:44 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_variables.rst
> +.. code-block:: yaml
```suggestion
.. code-block:: yaml+jinja
```

2021-10-11 22:44 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_variables.rst
> +.. code-block:: yaml
```suggestion
.. code-block:: yaml+jinja
```

2021-10-11 22:44 UTC, ariordan-redhat commented on docs/docsite/rst/user_guide/playbooks_variables.rst
> +.. code-block:: text
```suggestion
.. code-block:: shell
```

2021-10-11 22:46 UTC, ariordan-redhat commented
@Accoustium 
Thanks for creating the PR.
I made suggestions for some lexer values.

2021-10-12 00:23 UTC, Accoustium commented on docs/docsite/rst/user_guide/playbooks_variables.rst
> +.. code-block:: yaml
Updated with suggested change

2021-10-12 00:23 UTC, Accoustium commented on docs/docsite/rst/user_guide/playbooks_variables.rst
> +.. code-block:: yaml
Updated with suggested change

2021-10-12 00:23 UTC, Accoustium commented on docs/docsite/rst/user_guide/playbooks_variables.rst
> +.. code-block:: yaml
Updated with suggested change

2021-10-12 00:23 UTC, Accoustium commented on docs/docsite/rst/user_guide/playbooks_variables.rst
> +.. code-block:: yaml
Updated with suggested change

2021-10-12 00:23 UTC, Accoustium commented on docs/docsite/rst/user_guide/playbooks_variables.rst
> +.. code-block:: yaml
Updated with suggested change

2021-10-12 00:23 UTC, Accoustium commented on docs/docsite/rst/user_guide/playbooks_variables.rst
> +.. code-block:: yaml
Updated with suggested change

2021-10-12 00:23 UTC, Accoustium commented on docs/docsite/rst/user_guide/playbooks_variables.rst
> +.. code-block:: yaml
Updated with suggested change

2021-10-12 00:24 UTC, Accoustium commented
Thank you for the suggestions.  I did notice they were Jinja formats, but was unsure if you wanted jinja to be referenced or just the standard file type additions.

2021-10-12 10:07 UTC, ariordan-redhat commented
@Accoustium The main purpose of this issue is to prevent the translation of code by adding the `code-block::`.   
I requested the `yaml+jinja` lexer in this topic because it's useful to distinguish variable definition from variable reference.   Thanks for making the changes.

2021-10-12 10:09 UTC, merged

2021-10-12 10:09 UTC, ariordan-redhat commented
@Accoustium Thank you for contributing to the Ansible docs!