add missing space to `--playbook-dir` help string
ansible/ansible pull request #76062
Opened 2021-10-17 12:00 UTC by jbpratt

##### SUMMARY
fixes missing space in optional argument help string
```
  --playbook-dir BASEDIR
                        Since this tool does not use playbooks, use this as a substitute playbook directory.This
                        sets the relative path for many features including roles/ group_vars/ etc.
```

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
cli

2021-10-18 14:02 UTC, sivel requested changes

2021-10-18 14:02 UTC, sivel commented on lib/ansible/cli/arguments/option_helpers.py
> +                             " This sets the relative path for many features including roles/ group_vars/ etc.",
Please move the space to the preceding line, instead of starting the new line with a space.

2021-10-18 14:06 UTC, jbpratt commented on lib/ansible/cli/arguments/option_helpers.py
> +                             " This sets the relative path for many features including roles/ group_vars/ etc.",
Fixed, I mimicked the code right below it for what its worth :)  https://github.com/ansible/ansible/blob/606d0a8729fd6621776bf3f76ec2357ad68460fd/lib/ansible/cli/arguments/option_helpers.py#L239-L240

2021-10-19 15:17 UTC, mkrizek approved these changes

2021-10-19 15:17 UTC, merged