Docsite/dev_guide: add note about ansible-test utility installation ways
ansible/ansible pull request #76128
Opened 2021-10-25 09:53 UTC by Andersson007

##### SUMMARY
As there are questions like "How can I get / install ansible-test" https://github.com/ansible-collections/community.general/pull/3562#issuecomment-945415386 , this needs to be clarified.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
docs/docsite/rst/dev_guide/testing_running_locally.rst
docs/docsite/rst/dev_guide/developing_collections_testing.rst (I added the link to `testing_running_locally.rst` because ansible-test is described better there than in `:ref:developing_testing` - where's no explanation, only examples, BTW)

2021-10-25 09:55 UTC, Andersson007 commented
cc @mattclay @felixfontein @samccann

2021-10-25 14:32 UTC, samccann commented on docs/docsite/rst/dev_guide/testing_running_locally.rst
>  Requirements
Unfortunately, this is an orphan page, which means it isn't anywhere in the left-hand navigation. While that's not a 'show stopper' so to speak, if you look at the full file, it has some problems.  The first is the title isn't unique. I can't make suggested edits since that section isn't part of this PR but what I recommend:
 - change the title to "Testing Ansible locally with ``ansible-test``"
 - Remove bullet list below the title and just say 'This section describes how to run tests locally using ``ansible-test``.  (I don't know what Extend was supposed to talk about but I don't see it in the file so lets remove it)
 - Get a full review of the entire file by 'someone in the know.'. Most of the file hasn't been touched in 2-5 years so if we are now going to expose it to readers, we need to be sure the information is still accurate.

(Back story on orphan pages - sometimes they are fully supported docs that are deep in the details and would clutter up the left-hand navigation. Other times, like this one, might have been orphaned because they were no longer correct or needed, or were not completed and then, just... forgotten about.)

2021-10-26 06:06 UTC, Andersson007 commented on docs/docsite/rst/dev_guide/testing_running_locally.rst
>  Requirements
@samccann thanks, done points 1 and 2.

@mattclay could you please take a look at the doc and say if it's fully relevant or not?

2021-10-26 18:54 UTC, mattclay requested changes
The `testing_running_locally` page is so light on details I'm not sure if we should be linking to it or not. At the very least it should mention that it's incomplete and instruct the user to reference the built-in help in `ansible-test` for commands and options.

2021-10-26 18:54 UTC, mattclay commented on docs/docsite/rst/dev_guide/testing_running_locally.rst
> +
I don't think we should repeat this information here. The documentation already covers how to use the `devel` branch in several other places.

```suggestion
```

2021-10-26 18:54 UTC, mattclay commented on docs/docsite/rst/dev_guide/testing_running_locally.rst
>  The ``argparse`` package is required for Python 2.6.
This is no longer correct, since Ansible now requires 3.8+ on the controller.

I don't know if we need something else here or can just omit it entirely.

```suggestion
```

2021-10-26 18:54 UTC, mattclay commented on docs/docsite/rst/dev_guide/testing_running_locally.rst
>  The requirements for each ``ansible-test`` command are covered later.
Where is this documented? There doesn't seem to be any value in having this without a link to the details.

2021-11-23 07:51 UTC, Andersson007 commented
@mattclay @samccann as the goal of the PR isn't making the orphaned page reachable again, i excluded it and have put what is (imo) worth mentioning to the other page. The question if we should remove `docs/docsite/rst/dev_guide/testing_running_locally.rst` at all as it brings no much value is for another PR.
ready_for_review

2021-11-30 22:05 UTC, mattclay approved these changes

2021-12-03 13:17 UTC, Andersson007 commented
cc @samccann

2021-12-07 07:45 UTC, Andersson007 commented
cc @ariordan-redhat

2021-12-07 11:15 UTC, ariordan-redhat approved these changes

2021-12-07 11:18 UTC, merged

2021-12-07 11:37 UTC, Andersson007 commented
@samccann @mattclay @ariordan-redhat thanks for reviewing and merging!