Changing check mode behavior for some tasks which don't support it.
ansible/ansible pull request #76147
Opened 2021-10-26 20:46 UTC by itayporezky

##### SUMMARY
Fixing [#76127](https://github.com/ansible/ansible/issues/76127#issue-1034868052)

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
copy
raw
fetch
reboot
script
wait_for_connection
win_copy

##### ADDITIONAL INFORMATION
[#76127](https://github.com/ansible/ansible/issues/76127#issue-1034868052)

Sorry for mistakes, first pull request.

2021-10-26 21:29 UTC, bcoca requested changes

2021-10-26 21:29 UTC, bcoca commented on lib/ansible/plugins/action/copy.py
> +                raise AnsibleActionSkip('Check mode is not supported for this task.')
This is incorrect, it should be
```
raise AnsibleActionDone(changed=True)
```

2021-10-26 21:29 UTC, bcoca commented on lib/ansible/plugins/action/raw.py
> +
this is not needed as the 'super' already would trigger this from the base class, this is actually dead code and should be removed

2021-10-26 21:29 UTC, bcoca commented on lib/ansible/plugins/action/reboot.py
> +            raise AnsibleActionSkip('Check mode is not supported for this task.')
not skip

```
raise AnsibleActionDone(changed=True, elapsed=0, rebooted=True)
```

2021-10-26 21:29 UTC, bcoca commented on lib/ansible/plugins/action/script.py
> +                raise AnsibleActionSkip('Check mode is not supported for this task.')
```
raise AnsibleActionDone(changed=True)
```

2021-10-26 21:29 UTC, bcoca commented on lib/ansible/plugins/action/wait_for_connection.py
> +
can be removed, the call to 'supper' below already takes care of this

2021-10-26 21:29 UTC, bcoca commented on test/support/windows-integration/plugins/action/win_copy.py
> +            raise AnsibleActionSkip('Check mode is not supported for this task.')
these 2 are also wrong as it bypasses the logic on the caller that still does things with the resulting dictionary

2021-10-27 15:55 UTC, itayporezky commented
@bcoca , I've made the changes based on what Sivel [commented](https://github.com/ansible/ansible/issues/76127#issuecomment-952045617)

2021-10-27 16:19 UTC, bcoca commented
@itayporezky i believe that is incorrect, since what we want to reflect is an esitmate of what would happen IF the action ran fully, that is what 'check_mode' means, otherwise you would just use `when: false` to skip actions

2021-10-27 16:33 UTC, itayporezky commented
Sorry, I also don't see it in that way, at current state, if a task has `check_mode: yes` and you run it in production, you will see `changed=1` (for some modules) and would have no idea why your application breaks when the "`changed`" step says it changed but it didn't actually do anything.

A middle ground for this would be showing the task as `changed=1` as you want but also displaying a message in some way saying that it was actually skipped - whats your opinion on this?

btw, thanks for your review.

2021-10-27 16:57 UTC, bcoca commented
you already have a way of doing that, see `check_mode_markers`, i even linked you the docs in previous response

2021-11-01 14:39 UTC, s-hertel commented on lib/ansible/plugins/action/copy.py
> +                raise AnsibleActionSkip('Check mode is not supported for this task.')
Isn't this just removing check mode support? The only time skipping makes sense to me (sorta; I think 'skipped' is overloaded) is if changed is unknown (such as for `script`), and here we know changed=True.

2021-11-01 14:39 UTC, s-hertel commented on lib/ansible/plugins/action/reboot.py
> +            raise AnsibleActionSkip('Check mode is not supported for this task.')
We know reboot will always make a change so there's no need to disable check mode support. It's accurately reporting a change would occur. You can even see the intention a few lines above: `self._supports_check_mode = True`.

2022-07-13 19:50 UTC, mattclay commented
Closing due to inactivity.

2022-07-13 19:50 UTC, closed without merging