Stop using "checksumming" instead of "encrypting" in the docs
ansible/ansible pull request #76168
Opened 2021-10-28 07:21 UTC by vice

All encryption systems have a formal inverse function to decrypt
A hash is a one way function without inverse by definition

##### SUMMARY
Change title in template filter documentation that says encrypting when hashing is described

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
Template hashing and checksum filters

2021-10-28 11:19 UTC, webknjaz requested changes
Thanks for your contribution, I reviewed it and discovered that below the hashing examples in this documentation section, there are also examples of encryption with `vault`/`unvault` at the bottom. So it sounds like there's both encryption and hashing present. Note that the title also mentions "checksumming" — I believe that this part is what refers to hashing in the examples. Would you agree with this judgement?

2021-10-28 12:09 UTC, vice commented
You are right that now there is content about vault storage and that is encrypted storage. This content have been added in commit 90518d8bb5b82827829e364696c326e31c6b3c74 on September 1th 2021 and I haven't read it in https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#encrypting-and-checksumming-strings-and-passwords.

Preparing this pull request I noticed the vault part but thought that it would be another section.

So this title was wrong all this time but could be correct thanks to this recent addition.

2021-10-28 12:25 UTC, vice commented
I agree that cryptographically strong hash code could be a good checksum. But Checksums and hashes have different uses and requirements.

See introductions from wikipedia:
https://en.wikipedia.org/wiki/Checksum
https://en.wikipedia.org/wiki/Hash_function

2021-10-28 12:31 UTC, webknjaz commented
Well, it is there now: https://docs.ansible.com/ansible-core/devel/user_guide/playbooks_filters.html#encrypting-and-checksumming-strings-and-passwords.

2021-11-01 19:03 UTC, samccann commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +Hashing and checksumming strings and passwords
```suggestion
Hashing and encrypting strings and passwords
```

2021-11-01 19:03 UTC, samccann commented on docs/docsite/rst/user_guide/playbooks_filters.rst
> +Hashing and checksumming strings and passwords
Most of what is on that page is hashing, with one checksum example, and the new encrypting section so I think this title covers it well enough.

2021-11-04 14:24 UTC, samccann commented
@webknjaz what do you think of the updated heading now?

2021-11-04 18:59 UTC, webknjaz approved these changes
LGTM

2021-11-04 19:06 UTC, merged