Update attributes of files that are links without specifying link target
ansible/ansible pull request #76167
Opened 2021-10-27 20:50 UTC by mdonoughe

##### SUMMARY

When the `file` module is used to modify the permissions or modification time of a file without specifying the `state` parameter, Ansible autodetects the current state of the file and uses that as the desired state. However, if the current state of the file is detected to be "link" or "hard", then Ansible will want `src` to have been specified so it can ensure the correct link target.

This is particularly annoying when dealing with hard links, because essentially all normal files are hard links and the distinction used by Ansible is whether there is more than one link to the backing inode. That means if somebody else hard links to your file, then Ansible will start detecting that your file (the original file) is a hard link, and attempting to modify attributes of the file without specifying the path to the other file in the `src` parameter will fail. Even if you are expecting this, due to the nature of hard links, it's non-trivial (and sometimes impossible) to determine an appropriate value for `src` without creating a new, temporary hard link.

As a workaround, the playbook author can specify `state: file`, which will update the link without treating it as a link.

There were already tests for updating permissions of an existing symlink or hard link, but they specified the target of the link in `src` even though they weren't expecting to change `src`. I've removed `src` from those tests to give coverage to this code path. Tests that verify the link is not changed when specifying the same target should continue to provide coverage for the other code path.

Additionally, I added a check for if the user tries to create a new symlink but does not specify `src`. Previously, a file not found exception would be raised because Ansible would attempt to read the target of the link even if the link did not already exist. In the case where the link does not already exist, Ansible now continues as if `follow: no` was specified, and raises a more appropriate error about requiring `src`.

Fixes #76142

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

file

2022-01-07 19:20 UTC, bcoca requested changes, later dismissed
lgtm, just needs a changelog

2022-01-07 20:43 UTC, mdonoughe commented
Do I write the changelog?

2022-01-10 14:23 UTC, bcoca commented
https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment

2022-02-07 19:09 UTC, mattclay commented
@mdonoughe Can you rebase this PR to trigger a fresh CI run? There's an issue with RHEL 9.0 Beta right now and it's been removed from our test matrix -- but the CI failure can't be resolved without an update to this PR.

2022-03-12 17:10 UTC, mdonoughe commented
This PR is still marked "Changes requested" but I think it should be good to go.

2022-08-10 19:41 UTC, jborean93 commented
/azp run

2022-08-10 20:01 UTC, jborean93 approved these changes
bcoca's review requesting a changelog has been done.

2022-08-10 20:01 UTC, merged