Update `edgeos_config` module docs for 2.9
ansible/ansible pull request #76220
Opened 2021-11-04 04:12 UTC by mddeff

##### SUMMARY

Updates docs to reflect correct `lines` argument `type` of `list` instead of default `string`.  Verified by [the module itself](https://github.com/ansible/ansible/blob/stable-2.9/lib/ansible/modules/network/edgeos/edgeos_config.py#L281)

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

`edgeos_config` module
##### ADDITIONAL INFORMATION
Causes issues with [SchemaStore](https://github.com/SchemaStore/schemastore/) that gets its ansible schema automatically generated from this repo. SchemaStore is used by the [RedHat VScode-yaml plug-in](https://github.com/redhat-developer/vscode-yaml) which, in turn, is used by the [Ansible VScode module](https://github.com/ansible/vscode-ansible).

First time contributor, so if I'm pointing this in the wrong direction, let me know.  Thanks!

2021-11-15 21:03 UTC, samccann commented
@mddeff - Can you begin this by proposing the same fix to the current module? I believe it lives at https://github.com/ansible-collections/community.network/blob/main/plugins/modules/network/edgeos/edgeos_config.py

Once that is merged, ask the 'merger' to review this PR and approve it before we  merge.  Thanks!

2021-11-15 21:04 UTC, samccann requested changes
Requesting the change happens in the collection first before we proceed with this in 2.9.

2021-12-21 20:12 UTC, dericcrago commented
hi @samccann - the equivalent PR has been merged in the `community.network` collection.

2022-01-05 17:54 UTC, samccann approved these changes

2022-05-02 21:33 UTC, sivel commented
Thank you for your interest in Ansible. Ansible 2.9 has reached its end of life, and no more releases are expected. As such, we are no longer accepting changes for the stable-2.9 branch.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible-devel on irc.libera.chat
   * mailing list: https://groups.google.com/forum/#!forum/ansible-devel

2022-05-02 21:33 UTC, closed without merging