dnf: allow enabling of modules without a default profile
ansible/ansible pull request #76277
Opened 2021-11-11 08:33 UTC by evgeni

##### SUMMARY

DNF modules can be shipped without a default profile. In this case
calling 'install module:stream' errors out, as DNF doesn't know
what to install (as this is determined by the profile).

One solution is to explicitly call 'install module:stream/profile'.
However, it can be beneficial to only enable a module, without
installing anything from it. This is useful when the module is just
needed for dependencies, and maybe doesn't ship *any* profiles at all.

Examples for such modules are pki-deps and pki-core in EL8.

Fixes: #56504

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

dnf

##### ADDITIONAL INFORMATION

On EL8, the `pki-core` module can't be *installed*, just *enabled*, as it does not have any profiles.

```paste below
# ansible -m dnf -a 'name=@pki-core:10.6' localhost
localhost | FAILED! => {
    "changed": false,
    "failures": [
        "pki-core:10.6 Problems in request:\nbroken groups or modules: pki-core:10.6"
    ],
    "msg": "Failed to install some of the specified packages",
    "rc": 1,
    "results": []
}

# dnf module install pki-core:10.6
Failed to set locale, defaulting to C.UTF-8
Last metadata expiration check: 19:38:41 ago on Wed Nov 10 12:54:13 2021.
No profiles for module pki-core:10.6
Error: Problems in request:
broken groups or modules: pki-core:10.6

# ansible -m dnf -a 'name=@pki-core:10.6 state=enabled' localhost   
localhost | CHANGED => {
    "changed": true,
    "msg": "",
    "rc": 0,
    "results": [
        "Module pki-core:10.6 enabled."
    ]
}
```

2021-11-11 20:12 UTC, s-hertel requested changes
I see why this felt like a natural extension to the already-existing module support, but I think the initial feature also would have been better as a separate module for maintainability. It seems like there's consensus from https://github.com/ansible/ansible/issues/64852 (including from the active maintainer at the time who added the initial support) is that it should be a separate module. 

Another thing to note is that it would break feature parity with the `yum` module that was added in https://github.com/ansible/ansible/commit/6d95624c22d1c275974db1e7c94dcc171dc1457e.

New modules should generally be opened against a community collection. There are some guidelines here: https://docs.ansible.com/ansible/latest/community/contributing_maintained_collections.html#deciding-where-your-contribution-belongs

2021-11-12 08:54 UTC, evgeni commented
Thanks for the quick review!

> I see why this felt like a natural extension to the already-existing module support, but I think the initial feature also would have been better as a separate module for maintainability. It seems like there's consensus from #64852 (including from the active maintainer at the time who added the initial support) is that it should be a separate module.

I do agree that *all of* modularity support should never have been added to the `dnf` module to begin with, but in an own `dnf_module` module (how often will I write module in this post?). As right now, `dnf` can handle *some* modules, but not others, and this makes users unhappy.

> Another thing to note is that it would break feature parity with the `yum` module that was added in [6d95624](https://github.com/ansible/ansible/commit/6d95624c22d1c275974db1e7c94dcc171dc1457e).

Given the `dnf` module can handle installing/uninstalling modules, and `yum` cannot, makes this argument moot, no? :)

Also, there are gems like
https://github.com/ansible/ansible/blob/382a35323400e841caa0560132779f0ab563ad2e/lib/ansible/modules/dnf.py#L1405-L1408
As `yum` and `dnf` (the tools, not the modules) don't have feature parity anyways.

> New modules should generally be opened against a community collection. There are some guidelines here: https://docs.ansible.com/ansible/latest/community/contributing_maintained_collections.html#deciding-where-your-contribution-belongs

Placing `dnf_module` into a collection, would also mean that users of `ansible-core` (and other Ansible distribututions that don't ship the `community.*` collections) would get the `dnf` module that can do a bit of modularity, but not `dnf_module` which can do the other "half", which sounds wrong to me. I think what I am trying to say is: either all of this needs to be in the `dnf` module, or we need to rip out the current modularity support out of it, and place all into `dnf_module`, thus making it the only one handling modules. Otherwise we end up with terrible UX :(

[this post, without the quotes, includes 16 times the word "module"]

2021-11-12 17:35 UTC, s-hertel commented
> Given the dnf module can handle installing/uninstalling modules, and yum cannot, makes this argument moot, no? :)

Well, the `yum` action plugin may call the `dnf` module...

IMO it would be a good candidate for ansible.posix. But at least from the docs, I'd expect it to start in a community collection (maybe community.general? Probably a question for the community team), and then be promoted, since supported collections should be tried and true content.

Regarding ripping the existing support out, we could perhaps deprecate + eventually remove it. There are many cases of modules that accidentally started doing too much though, and often those are just left alone. For example, the `s3` module used to be the only module for managing AWS S3, and handled objects in buckets and buckets. Then an s3_bucket module was created to better support bucket management rather than continuing to add to the s3 module. Nothing was deprecated from the s3 module though, since in it's limited scope, it works fine and breaking playbooks was unnecessary.

ticket needs moar module :-)

2021-11-16 10:53 UTC, evgeni commented
> > Given the dnf module can handle installing/uninstalling modules, and yum cannot, makes this argument moot, no? :)
> 
> Well, the `yum` action plugin may call the `dnf` module...

Yuck, I forgot about this…

> IMO it would be a good candidate for ansible.posix. But at least from the docs, I'd expect it to start in a community collection (maybe community.general? Probably a question for the community team), and then be promoted, since supported collections should be tried and true content.

Ack, I can work on a `dnf_module` for `community.general` (and later `ansible.posix`), but it seems like a rather long path to get it into the users hands (not your fault, just general grief)

> Regarding ripping the existing support out, we could perhaps deprecate + eventually remove it. There are many cases of modules that accidentally started doing too much though, and often those are just left alone. For example, the `s3` module used to be the only module for managing AWS S3, and handled objects in buckets and buckets. Then an s3_bucket module was created to better support bucket management rather than continuing to add to the s3 module. Nothing was deprecated from the s3 module though, since in its limited scope, it works fine and breaking playbooks was unnecessary.

My main point about ripping it out is that it's incomplete, and users usually will go "oh, there is a builtin module, that's best supported for sure, let's use it" and then it breaks on the second use.

> ticket needs moar module :-)

![](https://i.imgflip.com/5ucpqe.jpg)

SCNR ;-)

2022-07-08 08:24 UTC, Thulium-Drake commented
@evgeni o/

Any update on this? I'm actually running into this problem trying to set up Satellite 6.11 on RHEL8 with Ansible :-(

2023-05-17 15:45 UTC, s-hertel commented
Hi!

Thanks very much for your submission to Ansible.  It means a lot to us that you've taken time to contribute. We discussed this in backlog today, and don't want to add additional top level `state` options. Rather than overloading the existing Ansible module, this would be more manageable as its own module.

However, we're absolutely always up for discussion.
Because this project is very active, we're unlikely to see comments made on closed tickets and we lock them after some time.
If you or anyone else has any further questions, please let us know by using any of the communication methods listed in the page below:

   * https://docs.ansible.com/ansible/latest/community/communication.html

In the future, sometimes starting a discussion on the development list prior to implementing a feature can make getting things included a little easier, but it's not always necessary.

Thank you once again for this and your interest in Ansible!

2023-05-17 15:45 UTC, closed without merging