Update intro_inventory.rst
ansible/ansible pull request #76340
Opened 2021-11-22 16:05 UTC by jmcgill298

I believe the first statement is clear enough, and that the second statement only creates confusion of where additional `group|host_vars` directories should be placed. As I read the second statement, I would expect the `group|host_vars` directories to be placed where the `ansible-playbook` command is issued. In practice, I have found that this is incorrect, and that the `group|host_vars` directories need to be adjance to the playbook that is being executed.

For example, executing `ansible-playbook playbooks/pb.yml` should have the `group|host_vars` directories inside the `playbooks` directories. Per the second statement, I would actually expect `group|host_vars` directories to be placed in the directory that the command is executed from.

##### SUMMARY

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- Test Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2021-11-30 15:26 UTC, bcoca requested changes

2021-11-30 15:26 UTC, bcoca commented on docs/docsite/rst/user_guide/intro_inventory.rst
> +You can also add ``group_vars/`` and ``host_vars/`` directories to your playbook directory. Other Ansible commands (for example, ``ansible``, ``ansible-console``, and so on) will only look for ``grou
It is good to remove that phrase, but I would add ansible-playbook to the previous one:
``` - For ``ansible-playbook`` you can also add ...```

2021-11-30 15:50 UTC, jmcgill298 commented on docs/docsite/rst/user_guide/intro_inventory.rst
> +You can also add ``group_vars/`` and ``host_vars/`` directories to your playbook directory. Other Ansible commands (for example, ``ansible``, ``ansible-console``, and so on) will only look for ``grou
```suggestion
For ``ansible-playbook`` you can also add ``group_vars/`` and ``host_vars/`` directories to your playbook directory. Other Ansible commands (for example, ``ansible``, ``ansible-console``, and so on) will only look for ``group_vars/`` and ``host_vars/`` in the inventory directory. If you want other commands to load group and host variables from a playbook directory, you must provide the ``--playbook-dir`` option on the command line.
```

2021-12-01 19:47 UTC, samdoran commented
/azp run

2021-12-14 21:36 UTC, samccann approved these changes

2021-12-14 21:36 UTC, merged

2021-12-14 21:36 UTC, samccann commented
Thanks @jmcgill298 for the Ansible docs fix!