package_facts: Add pkg_info support for OpenBSD
ansible/ansible pull request #76580
Opened 2021-12-19 13:51 UTC by rgoncalvesse

##### SUMMARY
Add `package_facts` support to OpenBSD via `pkg_info`.

The implementation is mostly copied from the `apk` one.

Tested on  OpenBSD 6.9 and OpenBSD 7.0.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
package_facts

2021-12-29 06:27 UTC, Akasurde commented on lib/ansible/modules/package_facts.py
>        - The 'apk' option was added in version 2.11.
```suggestion
      - The 'apk' option was added in version 2.11.
      - The 'pkg_info' option was added version 2.13.
```

2021-12-29 06:30 UTC, Akasurde commented on lib/ansible/modules/package_facts.py
> +    choices: ['auto', 'rpm', 'apt', 'portage', 'pkg', 'pacman', 'apk', 'pkg_info']
Please create a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment). See [this fragment](https://github.com/ansible/ansible/blob/c2f528b7686c9573aa8493357219e0bbe4416dd3/changelogs/fragments/reboot-change-default-boot-command.yaml) as an example.

2022-01-06 19:39 UTC, bcoca requested changes
The thing is that pkg_info exists fro more than openbsd and the options are not compatible, so we should add OS detection to use the options intelligently.

2022-01-06 20:11 UTC, rgoncalvesse commented
> The thing is that pkg_info exists fro more than openbsd and the options are not compatible, so we should add OS detection to use the options intelligently.

OK, I forgot about that.

I have identified that `pkg_info` is present in OpenBSD, FreeBSD and NetBSD. The `-A` flag is specific to OpenBSD (lists installed and internal packages). However the `-a` flag is common to those three BSD systems for listing installed packages.

I suggest to use the `-a` flag for retrieving package facts for those three systems.

2022-01-07 14:39 UTC, rgoncalvesse commented
Is there any other systems that support the `pkg_info` command? I have tested the latest changes on OpenBSD 7.0 and NetBSD 9.2. Their standard output are exactly the same:

- <name>-<version> <description>

Therefore I don't think OS detection is necessary (as long as the format is similar)

2022-01-07 14:58 UTC, bcoca approved these changes

2022-01-07 14:59 UTC, merged