Add dotall flags to regex functions
ansible/ansible pull request #76886
Opened 2022-01-30 20:55 UTC by BaldFabi

##### SUMMARY
This PR adds an additional flag to the regex functions. `dotall`/`re.S` was missing

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
core

2022-02-01 15:33 UTC, mkrizek requested changes
This needs a changelog fragment https://docs.ansible.com/ansible/devel/community/development_process.html#creating-a-changelog-fragment and mention the new flag in the documentation https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#searching-strings-with-regular-expressions.

2022-02-01 19:45 UTC, BaldFabi commented
Added the missing changes

2022-02-14 19:40 UTC, samccann reviewed
Adding link to pr into the changelog fragment.

2022-02-14 19:40 UTC, samccann commented on changelogs/fragments/76886-add-dotall-flag-to-all-regex-functions.yml
> +  - core - Add dotall flag to all regex functions
```suggestion
  - core - Add dotall flag to all regex functions (https://github.com/ansible/ansible/pull/76886).
```

2022-02-14 19:40 UTC, samccann approved these changes
Docs portion LGTM.

2023-01-11 19:48 UTC, mattclay requested changes
We've discussed this amongst the core team and we're inclined to document the existing functionality in Python which supports setting flags as part of the pattern: https://docs.python.org/3/library/re.html#index-16

This would allow using all flags available to Python, not just the ones we've chosen to implement. This should be documented in a doc fragment so it can be added to each filter plugin using a regular expression.

We're also inclined to deprecate the existing flags arguments for `ignorecase` and `multiline`. If you're interested in doing that as well, we'd accept it in a separate PR.

2023-06-09 16:10 UTC, Akasurde commented
superseded by https://github.com/ansible/ansible/pull/81016

2023-06-09 16:10 UTC, closed without merging