Shebang code-smell skips Role files and templates
ansible/ansible pull request #76881
Opened 2022-01-30 01:10 UTC by lilatomic

##### SUMMARY
Fixes #76612 

Some paths should not be validated by the shebang sanity test, since they do not contain files which will be used by Ansible. For example, Roles' "files" directory contains scripts to deploy to hosts.
This MR adds an early approval for those files.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
sanity/code-smell/shebang.py

##### ADDITIONAL INFORMATION

The first 2 commits are just "extract variable"s and "extract function" so it's testable.

I added some unit tests for the code smell, but it uses some importlib machinery. I'm open to a better way of doing that, but it's difficult because 'code-smell' is not a valid identifier for Python modules. If this is the best way, we should probably formalise it as a util and add some documentation)

2022-06-27 15:19 UTC, webknjaz commented
/azp run

2022-06-30 00:49 UTC, mattclay requested changes
@lilatomic Thanks for working on this. I'd like to see the changes made without refactoring the existing implementation. It should be a fairly minor change.

As for tests, there is now an [integration test](https://github.com/ansible/ansible/tree/devel/test/integration/targets/ansible-test-sanity-shebang) you can extend, so no need for hacks to test with unit tests.

2022-10-26 20:02 UTC, bcoca commented
@lilatomic  can you address the comments?
waiting_on_contributor

2022-12-04 20:26 UTC, lilatomic commented
Sorry folks. I tried getting back into this MR, but I don't have the context for it any more and my dev environment can't seem to run the tests. I don't think I realistically have the energy to move forward on this MR.

2022-12-04 20:26 UTC, closed without merging