[lookup/password] Handle vault encrypted files correctly
ansible/ansible pull request #77072
Opened 2022-02-18 16:15 UTC by fhemberger

##### SUMMARY
Files encrypted with `ansible-vault` and read with the `password` lookup return the **encrypted** content of the file. This commit aligns the behavior with the `copy` module and the `file` lookup plugin.

Ref: https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/lookup/file.py#L76-L77

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
password

##### ADDITIONAL INFORMATION
The current implementation of the password lookup deviates in its behavior from other modules.

Encrypt a file with `ansible-vault`:

- Ansible's `copy` module decrypts the file, writes the decrypted content to the target host.
- The `file` lookup module decrypts the file, returns the decrypted content.
- The `password` lookup module … well, it returns the **encrypted** content of the file.

This causes all kinds of trouble when you use the password plugin to create randomized, low-impact passwords (e.g. for technical `.htaccess` users, cookie secrets, etc.) which are stored encrypted inside the repository.

2022-02-18 16:40 UTC, fhemberger commented
Tried to address the failing test (`test_encrypt_wrapped_crypt_algo`), but ran into an issue:

```
❯ ansible-test units --docker -v test/units/plugins/lookup/test_password.py
WARNING: Skipping unit tests on Python 2.6 because it is only supported by module/module_utils unit tests. No module/module_utils unit tests were selected.
WARNING: Skipping unit tests on Python 2.7 because it is only supported by module/module_utils unit tests. No module/module_utils unit tests were selected.
WARNING: Skipping unit tests on Python 3.5 because it is only supported by module/module_utils unit tests. No module/module_utils unit tests were selected.
WARNING: Skipping unit tests on Python 3.6 because it is only supported by module/module_utils unit tests. No module/module_utils unit tests were selected.
WARNING: Skipping unit tests on Python 3.7 because it is only supported by module/module_utils unit tests. No module/module_utils unit tests were selected.
Run command: docker -v
Detected "docker" container runtime version: Docker version 20.10.11, build dea9396
Starting new "pypi-test-container-kGhlIdr8" container.
Run command: docker image inspect quay.io/ansible/pypi-test-container:1.0.0
Run command: docker run --name pypi-test-container-kGhlIdr8 -d quay.io/ansible/pypi-test-container:1.0.0
Adding "pypi-test-container-kGhlIdr8" to container database.
Run command: docker inspect b5e460abfdc6b95463f731d43548a13beaff3907f3dce6c920a1e8fcf020a4c5
Assuming Docker is available on localhost.
Starting new "ansible-test-controller-kGhlIdr8" container.
Run command: docker image inspect quay.io/ansible/ansible-core-test-container:4.1.1
Run command: docker run --volume /sys/fs/cgroup:/sys/fs/cgroup:ro --privileged=false --security-opt seccomp=unconfined --volume /var/run/docker.sock:/var/run/docker.s ...
Adding "ansible-test-controller-kGhlIdr8" to container database.
Run command: docker inspect dff730a4a321825f2806d9ec647a73561711543a4badc2203054400b9bc11f72
Run command: docker exec -i ansible-test-controller-kGhlIdr8 /bin/sh
Creating a payload archive containing 796 files...
Created a 1298040 byte payload archive containing 796 files in 0 seconds.
Run command: docker exec -i ansible-test-controller-kGhlIdr8 tar oxzf - -C /root
Creating container database.
Run command: docker exec -it ansible-test-controller-kGhlIdr8 mkdir -p /root/ansible/test/results/junit /root/ansible/test/results/coverage
Run command: docker exec -it ansible-test-controller-kGhlIdr8 chmod 777 /root/ansible/test/results/junit /root/ansible/test/results/coverage
Run command: docker exec -it ansible-test-controller-kGhlIdr8 chmod 755 /root
Run command: docker exec -it ansible-test-controller-kGhlIdr8 chmod 644 /root/ansible/test/results/.tmp/metadata-vtnrmvml.json
chmod: cannot access '/root/ansible/test/results/.tmp/metadata-vtnrmvml.json': No such file or directory
ERROR: Command "docker exec -it ansible-test-controller-kGhlIdr8 chmod 644 /root/ansible/test/results/.tmp/metadata-vtnrmvml.json" returned exit status 1.
Run command: docker rm -f ansible-test-controller-kGhlIdr8
Run command: docker rm -f b5e460abfdc6b95463f731d43548a13beaff3907f3dce6c920a1e8fcf020a4c5
```

2022-02-18 17:05 UTC, jpmens commented
I think there’s a changelog snippet missing, but otherwise LGTM. 

shipit

2022-02-18 18:05 UTC, fhemberger commented
Looks like I need a little help with the unit tests … 🙈  Shouldn't be a big issue, probably just adjusting the mock calls. I took the code change from the `file` lookup which doesn't have unit tests. 🤷

2022-02-18 18:13 UTC, fhemberger commented
@jpmens Added the fragment.

2022-02-21 14:20 UTC, bcoca requested changes
code lgtm but, 

a) this is a new feature, not really a bugfix, 'auto vault decrypting' is an opt in that most lookups do not support
b) you might want to add an integration test with a vaulted password file to ensure there is no future regression on this feature

2022-02-22 15:15 UTC, bcoca commented
two other things, 

- there should be the option to vault the file when creating it
- this should be a toggle

waiting_on_contributor

2022-02-22 15:18 UTC, fhemberger commented
> two other things,
> 
> * there should be the option to vault the file when creating it
> * this should be a toggle
> 
> waiting_on_contributor

I'd rather put that into a different PR, at the moment this is about adjusting the behavior of the `password` lookup to match the `file` lookup and the `copy` module.

2022-02-22 15:20 UTC, sivel commented
> I'd rather put that into a different PR, at the moment this is about adjusting the behavior of the `password` lookup to match the `file` lookup and the `copy` module.

I don't agree.  This is implementing a poorly thought out feature.  If you already have to create the file manually, you should be using legit vars files, like in `group_vars` or `host_vars`.

If you want the feature in the lookup plugin, the lookup plugin should be capable of owning.  Otherwise, I vote -1 on accepting this PR.

2022-02-22 16:30 UTC, jpmens commented
It’s sad that a user who has what imo was a good idea should get drawn into providing code they might not actually be able to contribute (think beginners in Python) instead of accepting the idea and putting extensions such as creating vaulted files onto a “futures” queue. 

My opinion.

2022-02-22 16:36 UTC, sivel commented
As mentioned, I see this as a misuse of the plugin in this form.  Use real vars files if you are having to manually create the vaulted file anyway.  There is effectively no benefit in this feature, if the functionality should be handled using more appropriate functionality that already exists.

This PR as it stands would be recommending a workflow that I would not support.

2022-02-22 19:51 UTC, fhemberger commented
> If you already have to create the file manually, you should be using legit vars files, like in `group_vars` or `host_vars`.

I don't create the file manually, if it doesn't exist yet it's created by the password lookup. At the moment, I have to **encrypt** it in a second step (if the file on disk is not already encrypted). I'd love to add this feature to the plugin, if that's what's needed to land this change – but as @jpmens already guessed – I'm quite new to Python and the inner workings of the Ansible codebase, and I'm trying my best here.

I'd really appreciate it if someone could point me to a documentation or code fragment on how to trigger vault's encryption. This would require that a vault password has already been set (e.g. `vault_password_file` config flag), and if the toggle flag is on but no vault password defined, the task should fail.

Would that be sufficient for you, @sivel?

My use case is to create long, random passwords on the fly (e.g. for securing an HTTP endpoint with a htaccess-password for a *technical user* or setting random values for session secrets), where no password is normally shared with a human user (hence no manually defined password "sup3rsecr3t" in `host_vars`), but is has to be stored encrypted somewhere for the next playbook run, without invalidating sessions by setting a new secret each time.

If that still hasn't convinced you that this addition might be useful for some people, please feel free to close this PR.

2022-02-22 20:12 UTC, sivel commented
Sounds like you could achieve that now using the `community.general.random_string` lookup, `copy`/`template` to write an encrypted string of that random value by using the `|vault` filter.  Only doing that when the file doesn't exist, and reading the file with the `file` lookup when it does.  Technically you could just use the `password` lookup still with a `/dev/null` file instead of the `random_string` lookup, but `random_string` doesn't concern itself with storing that string.

We already have `|vault` and `|unvault` filters. Those filters show how to use the vault code from within a plugin.

2022-02-22 20:32 UTC, fhemberger commented
Thanks, I wasn't aware of the `vault` filter, I'll take a closer look. So would you be okay with the PR if I added a toggle in the `password` lookup to save the generated password encrypted with vault?

2022-02-23 00:53 UTC, bcoca commented
With the vault/unvault filters you can encrypt the password and save to a file, but not use the file password creates automatically (but that might be enough for you). 

I still think there is value for password lookup to vault (with toggle) and unvault automatically.

2022-02-23 01:11 UTC, bcoca commented
```diff --git a/lib/ansible/plugins/lookup/password.py b/lib/ansible/plugins/lookup/password.py
index 134b7dec58..f6a323be9e 100644
--- a/lib/ansible/plugins/lookup/password.py
+++ b/lib/ansible/plugins/lookup/password.py
@@ -30,9 +30,8 @@ DOCUMENTATION = """
         description:
            - Which hash scheme to encrypt the returning password, should be one hash scheme from C(passlib.hash; md5_crypt, bcrypt, sha256_crypt, sha512_crypt).
            - If not provided, the password will be returned in plain text.
-           - Note that the password is always stored as plain text, only the returning password is encrypted.
+           - Note that the password is stored as plain text, unless vault is used, only the returning password is encrypted.
            - Encrypt also forces saving the salt value for idempotence.
-           - Note that before 2.6 this option was incorrectly labeled as a boolean for a long time.
       ident:
         description:
           - Specify version of Bcrypt algorithm to be used while using C(encrypt) as C(bcrypt).
@@ -64,10 +63,13 @@ DOCUMENTATION = """
           - Identical seeds will yield identical passwords.
           - Use this for random-but-idempotent password generation.
         type: str
+      vault:
+        version_added: "2.13"
+        description:
+          - Use the vault secret or reference passed to encrypt the file
     notes:
-      - A great alternative to the password lookup plugin,
-        if you don't need to generate random passwords on a per-host basis,
-        would be to use Vault in playbooks.
+      - A vaulted variable or file would be a great alternative to the password lookup plugin,
+        if you don't need to generate random passwords on a per-host basis.
         Read the documentation there and consider using it first,
         it will be more desirable for most applications.
       - If the file already exists, no data will be written to it.
@@ -77,6 +79,7 @@ DOCUMENTATION = """
         the target file must be readable by the playbook user, or, if it does not exist,
         the playbook user must have sufficient privileges to create it.
         (So, for example, attempts to write into areas such as /etc will fail unless the entire playbook is being run as root).'
+      - The plugin will unvault the file automatically if the required secret is present
 """

 EXAMPLES = """
@@ -124,12 +127,12 @@ _raw:
 import os
 import string
 import time
-import shutil
 import hashlib

 from ansible.errors import AnsibleError, AnsibleAssertionError
 from ansible.module_utils._text import to_bytes, to_native, to_text
 from ansible.parsing.splitter import parse_kv
+from ansible.parsing.vault import VaultEditor, VaultLib
 from ansible.plugins.lookup import LookupBase
 from ansible.utils.encrypt import BaseHash, do_encrypt, random_password, random_salt
 from ansible.utils.path import makedirs_safe
@@ -273,14 +276,19 @@ def _format_content(password, salt, encrypt=None, ident=None):
     return u'%s salt=%s' % (password, salt)


-def _write_password_file(b_path, content):
+def _write_password_file(b_path, content, vault):
     b_pathdir = os.path.dirname(b_path)
     makedirs_safe(b_pathdir, mode=0o700)

-    with open(b_path, 'wb') as f:
-        os.chmod(b_path, 0o600)
-        b_content = to_bytes(content, errors='surrogate_or_strict') + b'\n'
-        f.write(b_content)
+    b_content = to_bytes(content, errors='surrogate_or_strict') + b'\n'
+
+    if vault:
+        veditor = VaultEditor(VaultLib(vault))
+        veditor.create_file(b_path, b_content)
+    else:
+        with open(b_path, 'wb') as f:
+            os.chmod(b_path, 0o600)
+            f.write(b_content)


 def _get_lock(b_path):
@@ -364,7 +372,7 @@ class LookupModule(LookupBase):

             if changed and b_path != to_bytes('/dev/null'):
                 content = _format_content(plaintext_password, salt, encrypt=encrypt, ident=ident)
-                _write_password_file(b_path, content)
+                _write_password_file(b_path, content, self.get_option('vault'))

             if first_process:
                 # let other processes continue```

2022-02-24 09:14 UTC, fhemberger commented
@bcoca Thanks, added your changes and changed the PR from `bugfix` to `minor_changes`.
Will try to add tests as well.

2022-03-01 14:43 UTC, fhemberger commented
I wrote an integration test, but running `./bin/ansible-test integration -v lookup_password` required adding packages in `test/integration/targets/lookup_password/runme.sh`:

```diff
-pip install passlib
+pip install passlib cryptography jinja2 PyYAML
```
I' not sure if this is the case because I ran the test in isolation.


@bcoca This doesn't seem to work … 🤔 

```diff
+    if vault:
+        veditor = VaultEditor(VaultLib())
+        veditor.create_file(b_path, b_content)
```

`Error was a <class 'TypeError'>, original message: Can't mix bytes and non-bytes in path components."`, trying to cast `b_path` to string (which was just a wild guess from my side) just results in `Error was a <class 'AttributeError'>, original message: 'str' object has no attribute 'bytes'.`

I'm sorry, seems like I need a litte more help with this. 😩

2022-03-16 18:35 UTC, bcoca commented
what is the full traceback?

2022-03-27 14:07 UTC, fhemberger commented
@bcoca `VaultLib()` expects a dict of secrets as parameter:
https://github.com/ansible/ansible/blob/devel/lib/ansible/cli/vault.py#L171-L175
https://github.com/ansible/ansible/blob/devel/lib/ansible/cli/vault.py#L245

So somehow I need to get [`setup_vault_secrets`](https://github.com/ansible/ansible/blob/devel/lib/ansible/cli/__init__.py#L171) in there as well?

2022-03-28 14:47 UTC, bcoca commented
no, just use loader, it has methods with all of this taken care of already (`get_file_contents`)

2022-03-29 12:49 UTC, fhemberger commented
There is no method for encrypting files in the loader, that's the only part that is missing. Encryption only seems to be in the vault CLI code.

2022-10-23 12:05 UTC, fhemberger commented
I'm sorry, I'm giving up on this one. Implementing the encryption part would require a major internal code rewrite, for which I currently lack the time and expertise. I would have been very happy if this had landed here, maybe someone else will pick it up again at a later date.

If someone is still interested in the **decryption** part, I'm keeping a small [patch](https://github.com/fhemberger/ansible-password-lookup) around for myself.

2022-10-23 12:05 UTC, closed without merging