linux networking facts: Provide IPv4 prefix
ansible/ansible pull request #77193
Opened 2022-03-03 08:10 UTC by tyll

##### SUMMARY
For IPv6 addresses, Ansible already provides the prefix length for IP
addresses in the `prefix` fact. This patch adjusts the facts for IPv4
addresses to also contain the prefix length in the prefix fact. This
makes it easier to use the facts consistently when the CIDR notation is
needed.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME

gather_facts

##### ADDITIONAL INFORMATION

This came up because https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters_ipaddr.html#converting-subnet-masks-to-cidr-notation requires the python netaddr module which is an optional dependency that can be easily avoided with this patch.

2022-03-03 19:11 UTC, jborean93 commented
Is it possible to provide a changelog fragment that documents this new feature, the docs for doing this can be found at https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment.

2022-03-03 19:13 UTC, mattclay requested changes

2022-03-03 19:13 UTC, mattclay commented on lib/ansible/module_utils/facts/network/linux.py
> +                                                         'prefix': netmask_length
```suggestion
                                                         'prefix': netmask_length,
```

2022-03-03 19:13 UTC, mattclay commented on lib/ansible/module_utils/facts/network/linux.py
> +                                'prefix': netmask_length
```suggestion
                                'prefix': netmask_length,
```

2022-03-03 19:13 UTC, mattclay commented on lib/ansible/module_utils/facts/network/linux.py
> +                                    'prefix': netmask_length
```suggestion
                                    'prefix': netmask_length,
```

2022-03-07 18:17 UTC, tyll commented
I added the changelog fragment and the requested commas.

2022-03-09 03:45 UTC, Akasurde commented on changelogs/fragments/77193-linux-networking-facts-Provide-IPv4-prefix.yml
> +  - facts - report prefix length for IPv4 addresses
```suggestion
  - facts - report prefix length for IPv4 addresses while reporting Linux networking facts.
```

2022-03-09 13:13 UTC, tyll commented on changelogs/fragments/77193-linux-networking-facts-Provide-IPv4-prefix.yml
> +  - facts - report prefix length for IPv4 addresses
@Akasurde thank you, I adjusted the changelog.

2022-03-09 17:42 UTC, mattclay approved these changes

2022-03-10 03:28 UTC, Akasurde approved these changes

2022-03-16 14:53 UTC, tyll commented
@mattclay @Akasurde thank you for approving this. Anything else I need to do to get this merged?

2022-03-23 16:26 UTC, tyll commented
Just FYI, I will not be available next week in case you need anything else from me to get his merged.

@jborean93 since @mattclay and @Akasurde approved this, can you merge this?

2022-03-23 18:47 UTC, merged