callback: query strategy whether to cache taskname
ansible/ansible pull request #77303
Opened 2022-03-16 16:32 UTC by bailsman

##### SUMMARY

With the free strategy, the last task name should not be cached. Ref: #43950

However, the same might be true of a strategy plugin, a popular example being
mitogen_free. Otherwise, task names will be incorrect for mitogen_free just
like in #43950

Rather than checking for the name of the strategy in the callback plugin, we
can query the strategy itself whether task names should be cached or not.

Since the strategy is not available directly from the callback, passing a flag
on the play object via v2_playbook_on_play_start. A play has only one strategy.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
default callback / free strategy

##### ADDITIONAL INFORMATION

```paste below

```

2022-03-16 16:36 UTC, bcoca commented
The name is not the only issue, we were thinking more of a 'callback class property' `self.lockstep=true|false` than a function/method and then apply that to the many exceptions we now have for 'free', not just in task_executor but in the default callback and others.

2022-03-16 16:39 UTC, bailsman commented
related: #73483

2022-03-16 16:51 UTC, bailsman commented
What's the best way to pass information from the strategy to the callback?

2022-03-16 18:10 UTC, bcoca commented
that is one thing we are working on, have several PoCs but we have not decided upon a specific one yet.

2022-03-21 17:31 UTC, sivel commented
Ultimately we're going to expose the strategy to the callback, and the strategy will be able to expose functionality it supports.  Unfortunately, we cannot just expose the _full_ strategy to the callback, as that would allow the callback to do really nasty things.

We've begun work on a "restricted object proxy" that would use Python `typing.Protocol` to define the restricted interface.  However, that work has been put on hold for now, and hasn't been prioritized yet for 2.14 either.

I know the current situation isn't great, since we're dealing with just matching names, and not querying actual functionality.

But I cannot see us going the route this PR goes.  Ultimately, we're just going to have to wait until we can prioritize the feature to expose objects in some restricted form without exposing the full functionality of every object.

2022-03-21 21:14 UTC, sivel requested changes
See https://github.com/ansible/ansible/pull/77303#issuecomment-1074207802

2023-09-06 14:31 UTC, webknjaz commented
/azp run

2023-09-11 15:53 UTC, webknjaz commented
The CI can't merge the branches for testing because the PR HEAD is too old.

2023-09-11 16:14 UTC, closed without merging