ASCII Splash PoC
ansible/ansible pull request #77489
Opened 2022-04-07 18:30 UTC by nitzmahone

##### SUMMARY
Add PoC ASCII splash to `--version` outputs when we're on a TTY

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
CLI display

2022-04-07 18:41 UTC, bcoca requested changes
missing cowsay integration

2023-09-12 14:39 UTC, webknjaz commented
/azp run

2023-09-12 19:45 UTC, webknjaz commented
The CI can't make a proper checkout anymore. This needs rebasing.

2024-05-15 19:32 UTC, jborean93 commented
@nitzmahone is there an end date for this PR, was the plan to eventually merge it in or just use it as a fallible POC?

2025-01-21 15:57 UTC, webknjaz commented
/azp run

2025-01-21 16:04 UTC, webknjaz commented
@mattclay @sivel this is an example PR that #84375 / #84402 would've helped with.

2025-02-07 17:10 UTC, closed without merging