add link to deprecation warning
ansible/ansible pull request #77599
Opened 2022-04-21 15:58 UTC by samccann

##### SUMMARY

Fixes #76684

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

lib/ansible/playbook/helpers.py
##### ADDITIONAL INFORMATION

```paste below

```

2022-04-21 16:08 UTC, bcoca commented on lib/ansible/playbook/helpers.py
> +    include_link = get_versioned_doclink('user_guide/playbooks_reuse_includes.html')
move to inside the else, since it is the only place where it is used (avoid doing work when not needed)

2022-04-21 19:22 UTC, bcoca approved these changes

2022-04-21 19:23 UTC, bcoca requested changes
can we also get a changelog?

2022-04-21 20:38 UTC, samccann commented
you want fries with that documentation?  :-)  Yep will do.

2022-04-22 14:59 UTC, samccann commented
/azp run

2022-04-22 16:22 UTC, samccann commented
@bcoca I think this one is ready now...

2022-04-22 23:37 UTC, bcoca commented
@samccann still needs changelog, I had missed that, but it was brought up during triage, since this is candidate to backport

2022-04-25 15:44 UTC, samccann commented
@bcoca doh!  I created the changelog last week but pushed to wrong branch... fixed now, thanks!

2022-04-25 15:44 UTC, bcoca approved these changes

2022-04-25 15:44 UTC, merged

2022-04-25 15:48 UTC, bcoca commented
saw that ... NEVAR happens to me .. no sir .. nope .. much less a dozen times ...