update documentation of 'unarchive'
ansible/ansible pull request #77643
Opened 2022-04-26 10:17 UTC by optica-phoffmann

##### SUMMARY
I want to add valuable information to the documentation of `ansible.builtin.unarchive`. I hope that others see this addition as valuable as well.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
ansible.builtin.unarchive

##### ADDITIONAL INFORMATION

2022-04-26 15:56 UTC, bcoca requested changes

2022-04-26 15:56 UTC, bcoca commented on lib/ansible/modules/unarchive.py
> +      - The given path must exist. Base directory is not created by this module.
I would just change this to ``- Existing remote absolute ....```  no need for full new sentence

2022-04-26 15:56 UTC, bcoca commented on lib/ansible/modules/unarchive.py
> +      - The specified absolute path (file or directory) must be below the base path given with C(dest:).
I'm not sure how/why anyone would think that creation would happens outside of `dest` since that is where we are targeting to create/unarchive the files. I don't think this item is needed.

2022-06-09 18:30 UTC, samccann commented
@bcoca - I'm inclined to agree with the PR. As someone who's never read the module, I initially found the existing descriptions confusing. I thought 'creates' might actually create the base directory. With these additions, it's clear that 'dest' MUST already exist, and 'creates' is adding the subdirectory.  Unless you feel strongly otherwise, I'm inclined to merge as it does make things that little bit clearer to someone new.

2022-06-16 18:33 UTC, samccann approved these changes

2022-06-16 18:34 UTC, merged