[WIP]: Make ignore_unreachable to ignore the task
ansible/ansible pull request #77693
Opened 2022-04-29 11:00 UTC by kristianheljas

##### SUMMARY

**! WORK IN PROGRESS - DO NOT MERGE !**

This PR is demonstrating possible solution for https://github.com/ansible/ansible/issues/77690 (without tests!)

Once this issue is confirmed, I will finalize this PR (or delete if rejected)

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
 
stats

##### ADDITIONAL INFORMATION

If following task would result in unreachable

```yaml
- name: ignored unreachable task
  action: ping
  ignore_unreachable: true
```

then this PR would change the output like so (just as ignore_errors does):

```diff
TASK [ignored unreachable task] ************************************************
fatal: [localhost]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added 'localhost' (ED25519) to the list of known hosts.\r\nnon-existent-user@localhost: Permission denied (publickey,password).", "unreachable": true}
+...ignoring

PLAY RECAP *********************************************************************
-localhost                  : ok=0    changed=0    unreachable=1    failed=0    skipped=1    rescued=0    ignored=0   
+localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=1   
```

2022-04-29 13:26 UTC, bcoca commented
no need to add new arguments that will be backwards incompatible with existing callbacks, task_result already carries a task object, which has the info about `ignore_unreachable`

2022-04-30 07:11 UTC, kristianheljas commented
Good observation, I blindly followed `ignore_errors` pattern.

2022-05-03 15:10 UTC, mkrizek requested changes
Please create a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment).

2022-05-03 17:23 UTC, kristianheljas commented
I added the counting difference as breaking change. I did not include the addition of `..ignoring` as it seemed irrelevant for a changelog.

I also did not add any tests for this since I did not find any existing test for stat counters.

2022-05-03 21:48 UTC, bcoca approved these changes

2022-05-03 22:06 UTC, kristianheljas commented
Fixed a typo in changelog (`ignore_errors` => `ignore_unreachable`)

2022-05-09 15:53 UTC, mkrizek approved these changes

2022-06-01 12:09 UTC, mkrizek commented
/azp run

2022-06-01 14:11 UTC, merged