Supply 'dev' keyword for linux network facts discovery
ansible/ansible pull request #77793
Opened 2022-05-13 13:16 UTC by rmuir

This avoids incorrect results when the device name conflicts with another 'ip' keyword. For example, if the device name is 'primary'.

Fixes #77792

2022-05-17 15:17 UTC, mkrizek requested changes
Please create a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment).

2022-05-18 12:05 UTC, rmuir commented
thanks @mkrizek , i took a stab at adding one.

2022-05-18 14:18 UTC, bcoca approved these changes

2022-05-23 06:58 UTC, mkrizek approved these changes

2022-05-23 06:58 UTC, merged