add more options to random filter so it supports weighted random
ansible/ansible pull request #78078
Opened 2022-06-17 12:14 UTC by jangel97

Hi,

The aim of this PR is to add new default options to the random filter plugin so it supports weights, accumulative weights and k parameter (The number of samples you want from a population). All these new parameters would be optional so the basic functionality of the random filter does not break after merging the new changes.

This would be useful for me because I need to assign tasks to nodes via delegated_to using a random pattern (if weighted could make things more interesting for my use case).

Examples on how to use it:

Example I:
```
$ ansible localhost -m debug -a "msg={{ [1,2,3,4,5,6,7,8,9,10] | list|random }}"
localhost | SUCCESS => {
    "msg": "6"
}
```
Example II:
```
$ ansible localhost -m debug -a "msg={{ [1,2,3,4,5,6,7,8,9,10] | list|random(k=10000)|community.general.counter }}"
localhost | SUCCESS => {
    "msg": {
        "1": 948,
        "2": 1024,
        "3": 999,
        "4": 974,
        "5": 988,
        "6": 1060,
        "7": 970,
        "8": 994,
        "9": 1052,
        "10": 991
    }
}
```
Example III:
```
$ ansible localhost -m debug -a "msg={{ [1,2,3,4,5,6,7,8,9,10] | list|random(weights=[10,10,0,0,0,0,0,0,0,1000],k=10000)|community.general.counter }}"
localhost | SUCCESS => {
    "msg": {
        "1": 115,
        "2": 105,
        "10": 9780
    }
}
```

Let me know if the change makes sense, or if you find any issues.

Thanks in advance!

2022-06-21 15:09 UTC, s-hertel requested changes

2022-06-21 15:09 UTC, s-hertel commented on lib/ansible/plugins/filter/core.py
> +def rand(environment, end, weights=None, cum_weights=None, k=1, start=None, step=None, seed=None):
This needs a [changelog](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment) and test.

new options should be added to the end of the function
```suggestion
def rand(environment, end, start=None, step=None, seed=None, weights=None, cum_weights=None, k=1):
```

2022-07-01 14:14 UTC, jangel97 commented
Hi,

I added a unit test, let me know if it looks good to you.

Thanks,

2022-07-12 14:02 UTC, s-hertel commented
Hi!

Thanks very much for your submission to Ansible.  It means a lot to us that you've taken time to contribute.

Sorry for not getting back to this one more promptly. This needed a little more discussion. Unfortunately, we're not sure if we want this feature in the program, and I don't want this to seem confrontational.
Our reasons for this are:

   * We do not want the ansible.builtin `random` filter to further diverge from the Jinja `random` filter.
   
 Instead:
 
   * This could be added to the Jinja builtin filter. The ansible.builtin `random` filter should be updated to call the Jinja `random` filter (similarly to how we handle the `unique` filter) and accept any options it allows.
   * This could be implemented as a new filter in another collection.

However, we're absolutely always up for discussion.
Because this project is very active, we're unlikely to see comments made on closed tickets and we lock them after some time.
If you or anyone else has any further questions, please let us know by using any of the communication methods listed in the page below:

   * https://docs.ansible.com/ansible/latest/community/communication.html

In the future, sometimes starting a discussion on the development list prior to implementing a feature can make getting things included a little easier, but it's not always necessary.

Thank you once again for this and your interest in Ansible!

2022-07-12 14:02 UTC, closed without merging