systemctl reset-failed feature
ansible/ansible pull request #78100
Opened 2022-06-21 13:41 UTC by vicmunoz

##### SUMMARY
Added reset-failed feature to systemd builtin module

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

systemd_service.py new option - reset_failed
##### ADDITIONAL INFORMATION
n/a

```paste below

```

2022-06-21 15:27 UTC, s-hertel requested changes
This needs a [changelog](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment) and tests.

2022-06-21 15:27 UTC, s-hertel commented on lib/ansible/modules/systemd_service.py
> +    reset_failed: yes
reset_failed should be able to be used in conjunction with other options

2022-06-21 15:32 UTC, bcoca requested changes
This looks like a state/action and does not seem to handle interaction with other options at all, what would you expect from?:

```
systemd:
    state: stopped
    reset_failed: true
```

Aside from that, there is no real feedback or verification from the command, I see little value for adding it to the module vs just using `shell/command` to issue it.

A more useful option would be using `service_facts` to find the failed services and then using the current `state` options of `systemd` we should also be able to cover this case, this at least would give you a record of 'actions needed/taken'.

2022-10-05 15:49 UTC, s-hertel commented
Closing due to inactivity

2022-10-05 15:49 UTC, closed without merging