add note about permission change
ansible/ansible pull request #78128
Opened 2022-06-23 14:53 UTC by samccann

##### SUMMARY

Fixes #25389
##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

lib/ansible/modules/lineinfile.py
lib/ansible/modules/replace.py
##### ADDITIONAL INFORMATION

```paste below

```

2022-06-23 15:03 UTC, bcoca requested changes

2022-06-23 15:03 UTC, bcoca commented on lib/ansible/modules/lineinfile.py
> +    running Ansible, this module will change the owner of the file to the user running Ansible.
This is not complete, as you can specify `owner` and `group` options, probably better to explain what happens when you don't set these in each option. 'When left unspecified it will use the current user(group of the current user) ...' unless you are root, in which case in CAN preserve the previous ownership

2022-06-23 15:05 UTC, bcoca commented on lib/ansible/modules/lineinfile.py
> +    running Ansible, this module will change the owner of the file to the user running Ansible.
also ,this affects all 'file based modules' so updating the common doc fragment at the `owner` and `group` level will 'correct' the information for all of them, not just lineinfile and replace

2022-07-01 18:22 UTC, samccann commented on lib/ansible/modules/lineinfile.py
> +    running Ansible, this module will change the owner of the file to the user running Ansible.
applied the fix @bcoca . Can you take another look?

2022-07-28 17:24 UTC, samccann commented
/azp run

2022-07-28 18:45 UTC, merged