added --allow-change-held-packages for apt remove
ansible/ansible pull request #78203
Opened 2022-07-04 15:48 UTC by inifares23lab

##### SUMMARY

Changed the apt module.
now when using apt remove (i.e. state=absent) it is possible to use the "allow-change-held-packages" parameter

fixes #78131

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

apt

##### ADDITIONAL INFORMATION

```paste below

```

2022-07-05 15:33 UTC, bcoca requested changes
Code lgtm, but requires changelog and tests

2022-07-06 15:16 UTC, inifares23lab commented
Hi

without changing the test code:
- most of the times the integration tests for apt module fail 
- sometimes they complete without errors.
[ansible-test-apt.txt](https://github.com/ansible/ansible/files/9056024/ansible-test-apt.txt)

It's some old tests that fail on build-dep.
maybe is related to issue #38995 which has been closed.

not sure how this affects this or other PRs since the CI tests usually fail
should a new issue be opened?

2022-11-02 15:40 UTC, s-hertel commented
/azp run

2022-11-02 15:41 UTC, bcoca approved these changes

2022-11-02 16:02 UTC, merged

2022-11-02 16:02 UTC, s-hertel commented
@inifares23lab Thanks for adding this!