Documented connection parameters required to enable scp (OpenSSH >=9.0)
ansible/ansible pull request #78745
Opened 2022-09-10 16:37 UTC by wnjuguna

##### SUMMARY

Fixes #78600

Documented extra parameters required to enable scp for OpenSSH >=9.0 

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

lib/ansible/plugins/connection/ssh.py

##### ADDITIONAL INFORMATION

```paste below

```

2022-09-12 13:40 UTC, bcoca approved these changes

2022-09-12 13:41 UTC, bcoca requested changes

2022-09-12 13:41 UTC, bcoca commented on lib/ansible/plugins/connection/ssh.py
> +            - For OpenSSH >=9.0 you must add an additional option to enable scp (ansible_scp_extra_args="-O")
the setting is `scp_extra_args`, there is more than one way to add the -O, not just the variable

2022-09-12 19:44 UTC, wnjuguna commented
ready_for_review

2022-09-13 15:07 UTC, bcoca approved these changes

2022-09-15 15:02 UTC, samccann approved these changes

2022-09-15 15:03 UTC, merged

2022-09-15 15:03 UTC, samccann commented
Thanks @wnjuguna for the Ansible docs fix!