Fixes #78832: Limited write on parent
ansible/ansible pull request #78833
Opened 2022-09-21 11:40 UTC by re-schneider

##### SUMMARY

Fixes #78832:
when dealing with cross-device cases, the copy is the simplest action and equivalent for the move/rename action that is the initial attempt

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
lineinfile and copy (and possibly others)

2022-12-02 15:23 UTC, bcoca requested changes

2022-12-02 15:23 UTC, bcoca commented on lib/ansible/module_utils/basic.py
> +                                   exception=traceback.format_exc())
this copy is both unnecessary and unwanted, it is not an atomic operation when it goes across partitions. 

Also the following code path does a 'copy and move' which does the same but in an atomic manner.

2022-12-02 15:23 UTC, bcoca commented on lib/ansible/modules/copy.py
> +    if not checksum_dest and not os.access(os.path.dirname(b_dest), os.W_OK) and not module.params['unsafe_writes']:
we should already have handled missing file in previous branch, these changes don't seem to be needed either.

2022-12-02 15:24 UTC, bcoca requested changes
Also missing clog and tests, but current code does not seem to handle the intended cases

2023-06-07 15:41 UTC, s-hertel commented
Closing for inactivity. You should be able to handle this with[ `unsafe_writes`](https://github.com/ansible/ansible/issues/78832#issuecomment-1253771537).

2023-06-07 15:41 UTC, closed without merging