[docs] Fixes issue #72389
ansible/ansible pull request #78858
Opened 2022-09-22 11:24 UTC by JaroslavKlech

##### SUMMARY
Adds a suggested note mentioned in https://github.com/ansible/ansible/issues/72389#issuecomment-1234750451 and polishes the `sample_setup.rst` file in general.

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME
docs.ansible.com

##### ADDITIONAL INFORMATION

```paste below

```

2022-09-22 11:49 UTC, tremble requested changes
"These" in the note refers to the examples rather than elements.  I'd leave it to folks more knowledgable than I if the change in voice is desirable.

2022-09-22 11:49 UTC, tremble commented on docs/docsite/rst/tips_tricks/sample_setup.rst
> +You have learned about playbooks, inventory, roles, and variables. This section combines all those elements, and outlines a sample setup for automating a web service. You can find more example playbo
```suggestion
You have learned about playbooks, inventory, roles, and variables. This section combines all those elements, and outlines a sample setup for automating a web service. You can find more example playbooks that illustrate these patterns in our `ansible-examples repository <https://github.com/ansible/ansible-examples>`_. (NOTE: These examples do not use all of the latest features, but are still an excellent reference.).
```

2022-09-22 13:01 UTC, tremble commented
Fixes: https://github.com/ansible/ansible/issues/72389

2022-09-22 18:23 UTC, oraNod approved these changes
@JaroslavKlech Thanks for the changes! I've made some minor suggestions on wording. Feel free to take them, leave them, or modify them. Cheers!

2022-09-22 18:23 UTC, oraNod commented on docs/docsite/rst/tips_tricks/sample_setup.rst
> +With this setup, you can configure your entire infrastructure by running ``site.yml``. Alternatively, to configure just a portion of your infrastructure, run ``webservers.yml``. This is analogous to
```suggestion
With this setup, you can configure your entire infrastructure by running ``site.yml``. Alternatively, to configure just a portion of your infrastructure, run ``webservers.yml``. This is similar to the Ansible ``--limit`` parameter but a little more explicit:
```

2022-09-22 18:23 UTC, oraNod commented on docs/docsite/rst/tips_tricks/sample_setup.rst
> +The sample setup illustrates a typical configuration topology. When you do multi-tier deployments, you will likely need some additional playbooks that hop between tiers to roll out an application. In
```suggestion
The sample setup illustrates a typical configuration topology. When you do multi-tier deployments, you will likely need some additional playbooks that hop between tiers to roll out an application. In this case, you can augment ``site.yml`` with playbooks like ``deploy_exampledotcom.yml``. However, the general concepts still apply. With Ansible you can deploy and configure using the same utility. Therefore, you will probably reuse groups and keep the OS configuration in separate playbooks or roles from the application deployment.
```

2022-09-22 18:23 UTC, oraNod commented on docs/docsite/rst/tips_tricks/sample_setup.rst
> +If a playbook has a :file:`./library` directory relative to its YAML file, you can use this directory to add Ansible modules that will automatically be in the Ansible module path. This is a way to ke
```suggestion
If a playbook has a :file:`./library` directory relative to its YAML file, you can use this directory to add Ansible modules automatically to the module path. This organizes modules with playbooks. For example, see the directory structure at the start of this section.
```

2022-09-23 08:13 UTC, JaroslavKlech commented
@oraNod and @tremble, I committed your suggestions. I think they were valid points.

2022-09-23 08:17 UTC, oraNod commented
@JaroslavKlech Cheers. I'd like to wait for @samccann to have a quick look before we merge. Should be today though. Thanks again!

2022-09-23 14:19 UTC, samccann approved these changes

2022-09-23 14:19 UTC, merged

2022-09-23 14:19 UTC, samccann commented
Thanks @JaroslavKlech for the detailed Ansible docs fix and Welcome to Ansible!

2022-09-23 14:32 UTC, oraNod commented
Thanks @samccann and, yes, welcome @JaroslavKlech ! Great first docs contribution. :tada: