fix Alibaba Cloud Compute Services Guide text
ansible/ansible pull request #78984
Opened 2022-10-02 09:34 UTC by tasoint

##### SUMMARY
In the Alibaba Cloud Compute Services Guide page, What should be written as vars_files is written as vras_file.

page(https://docs.ansible.com/ansible/devel/scenario_guides/guide_alicloud.html)

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME
Noted statements in the Authentication section.

##### ADDITIONAL INFORMATION
Correct vars_file to vars_files.

2022-10-03 03:47 UTC, Akasurde requested changes

2022-10-03 03:47 UTC, Akasurde commented on docs/docsite/rst/scenario_guides/guide_alicloud.rst
> +To store authentication credentials in a vars_files, encrypt them with :ref:`Ansible Vault<vault>` to keep them secure, then list them::
```suggestion
To store authentication credentials in a vars_files, encrypt them with :ref:`Ansible Vault<vault>` to keep them secure, then list them:

.. code-block:: yaml

```

2022-10-03 03:47 UTC, Akasurde commented on docs/docsite/rst/scenario_guides/guide_alicloud.rst
> +Note that if you store your credentials in a vars_files, you need to refer to them in each Alicloud module. For example::
```suggestion
Note that if you store your credentials in a vars_files, you need to refer to them in each Alicloud module. For example:

.. code-block:: yaml
```

2022-10-03 20:45 UTC, samccann commented
Thanks @tasoint for the proposed Ansible docs fix! If you select `commit suggestion` on each of the proposed changes above, we can merge this PR.  
![image](https://user-images.githubusercontent.com/30267855/193679066-b21f1055-7609-4231-aa6f-944623c159b9.png)

2022-10-04 01:45 UTC, Akasurde approved these changes

2022-10-04 09:03 UTC, oraNod approved these changes

2022-10-04 09:19 UTC, merged

2022-10-04 09:21 UTC, oraNod commented
Thanks for the contribution @tasoint! More contributions are welcome and you can grab one of the [Hacktoberfest issues here](https://github.com/ansible/ansible/labels/hacktoberfest).