Removal of add_attribute from collection_integrating_updating.rst file
ansible/ansible pull request #79019
Opened 2022-10-04 08:44 UTC by prayatharth

##### SUMMARY
Removal of `add_attribute:` from `collection_integrating_updating.rst` file  for the one having for `name: Test for new_option, create new user WITHOUT the attribute`   and ` name: Query the database if the user exists but does not have the attribute (it is NULL)`

##### ISSUE TYPE

- Docs Pull Request

2022-10-04 09:39 UTC, oraNod requested changes

2022-10-04 09:39 UTC, oraNod commented on docs/docsite/rst/community/collection_contributors/collection_integration_about.rst
> +    communnity.postgresql.postgresql_user:
```suggestion
    community.postgresql.postgresql_user:
```

2022-10-04 09:39 UTC, oraNod commented on docs/docsite/rst/community/collection_contributors/collection_integration_about.rst
> +    communnity.postgresql.postgresql_query:
```suggestion
    comunnity.postgresql.postgresql_query:
```

2022-10-05 11:38 UTC, closed without merging

2022-10-05 11:39 UTC, Akasurde commented
Changes are already in place. Closing this request.