builtin lookup plugin password: fix example
ansible/ansible pull request #79058
Opened 2022-10-06 08:28 UTC by azrdev

##### SUMMARY

all parameters must be passed space-delimited as part of the single argument string, the last example had this wrong.

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

ansible.builtin.password

##### ADDITIONAL INFORMATION

```paste below

```

2022-10-06 13:23 UTC, bcoca requested changes

2022-10-06 13:23 UTC, bcoca commented on lib/ansible/plugins/lookup/password.py
> +    password: "{{ lookup('ansible.builtin.password', '/dev/null seed=' + inventory_hostname) }}"
this is incorrect, this example is to specifically show the comma separated method of passing arguments

2022-10-06 13:25 UTC, bcoca commented
@azrdev while this was true for password in the past it is not anymore, all lookups now should support the common comma separated argument passing (as functions in most programming languages allow) and will soon deprecate custom parsing of arguments that different lookups implemented.

2022-10-09 14:42 UTC, Akasurde commented
Similar to https://github.com/ansible/ansible/pull/76529

2022-10-10 14:42 UTC, bcoca commented
arghh .. thought i had merged #76551, will get on that right now, in any case, closing this as dupe of #76529

2022-10-10 14:42 UTC, closed without merging