added number of matches to replace parameter
ansible/ansible pull request #79094
Opened 2022-10-10 20:10 UTC by shivamdurgbuns

Signed-off-by: Shivam Durgbuns <shivamdurgbuns@gmail.com>

##### SUMMARY
Added `numberofmatches` parameter to replace functionality to replace the first n number of matches during a replace function, the default is set to 0 i.e all the occurrences will be replaced.

Fixes: https://github.com/ansible/ansible/issues/78866

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
replace

2022-10-11 14:09 UTC, bcoca requested changes
code lgtm, could you add a couple of integration tests to ensure we do  not regress?

2022-10-11 14:15 UTC, shivamdurgbuns commented
> code lgtm, could you add a couple of integration tests to ensure we do  not regress?

Sure will do that @bcoca

2022-10-15 19:59 UTC, anirbandey303 approved these changes

2022-11-25 09:48 UTC, zedr commented on changelogs/fragments/78866-replace-n-number-of-matches.yaml
> +        - added new `numberofmatches` paramter to replace function to replace the first n number of occurances (https://github.com/ansible/ansible/issues/78866)
@shivamdurgbuns typo

2022-11-25 09:51 UTC, zedr commented on lib/ansible/modules/replace.py
> +    numberofmatches: 1
Consider using `count` to reflect the actual keyword parameter that you are using.

2022-11-25 09:59 UTC, zedr commented
@shivamdurgbuns consider adding these tests:

- Test the exact case that was mentioned in the feature request: https://github.com/ansible/ansible/issues/78866#issue-1383403463
- Test that the module behaves exactly the same in these two cases: 1) omitting the `numberofmatches` parameter and 2) providing the default value.

2023-05-24 19:46 UTC, s-hertel commented
Closing for inactivity

2023-05-24 19:46 UTC, closed without merging