fix incorrect ansible_managed formatting
ansible/ansible pull request #79129
Opened 2022-10-13 10:59 UTC by doc-sheet

##### SUMMARY

Ansible breaks configs if file name contains `%` chars.
Especially `%n`_`[ame%]`_ which is a line break pattern according to [strftime (3)](https://manpages.debian.org/bullseye/manpages-dev/strftime.3.en.html)

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

`generate_ansible_template_vars()`

##### ADDITIONAL INFO
default value for `ansible_managed` is
```cfg
ansible_managed = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
```

if you put `{{ansible_managed}}` in jinja template and save in file named like `/etc/whatever/%name%.conf` it will split string to multiple lines and possibly break syntax

Simple test case:
```
>>> a = 'haha %name% haha %Y-%m-%d'
>>> time.strftime(a)
'haha \name% haha 2022-10-13'
```

2022-10-13 19:19 UTC, nitzmahone commented
This is probably mergeable with a changelog fragment and a test

2022-10-15 14:16 UTC, doc-sheet commented
Added changelog and test.
Also fixed config load for #39531 test

2022-10-20 20:26 UTC, doc-sheet commented
ready_for_review

2022-12-05 10:47 UTC, doc-sheet commented
What should I do next?

2023-02-24 13:26 UTC, doc-sheet commented
bot_status

2023-02-24 13:56 UTC, doc-sheet commented
ready_for_review

2023-07-19 15:40 UTC, bcoca requested changes

2023-07-19 15:40 UTC, bcoca commented on lib/ansible/template/__init__.py
> +        file=temp_vars['template_path'].replace('%', '%%'),
This fix only addresses the %, it should escape any/all characters that would cause issues with templating

2023-08-05 18:07 UTC, doc-sheet commented on lib/ansible/template/__init__.py
> +        file=temp_vars['template_path'].replace('%', '%%'),
according [to docs](https://manpages.debian.org/bookworm/manpages-dev/strftime.3.en.html) only percent characters could cause unexpected result. I guess it's enough to replace them in in file path to sanitize input.

2023-08-07 13:21 UTC, bcoca commented on lib/ansible/template/__init__.py
> +        file=temp_vars['template_path'].replace('%', '%%'),
`{{` .. strftime is not the only 'templating' that happens

2023-08-09 00:37 UTC, doc-sheet commented on lib/ansible/template/__init__.py
> +        file=temp_vars['template_path'].replace('%', '%%'),
oh. right

2023-08-09 18:45 UTC, doc-sheet commented on lib/ansible/template/__init__.py
> +        file=temp_vars['template_path'].replace('%', '%%'),
Thank you!
I've updated PR and added test for this.

2023-08-09 19:16 UTC, bcoca approved these changes

2023-08-13 18:39 UTC, doc-sheet commented
ready_for_review

2023-08-14 13:59 UTC, merged