[78461] Deprecation: warn_change: add param to module.deprecate to inform of a change instead of removal.
ansible/ansible pull request #79181
Opened 2022-10-20 20:18 UTC by itxasos23

##### SUMMARY

Fixes #78461.
This PR adds a new param (`warn_change`) to `AnsibleModule.deprecate` to inform the user that a feature is going to change, but no necessarily to be removed.

Before this PR, the deprecation message looked like this.
`This feature will be removed from test.test in version 1.0.0.`

Now, if the method `deprecate` is invoked with `warn_change=True`, the message reads:
`This feature will change in test.test in version 1.0.0.`
The developer is expected to provide context in the deprecation message beforehand.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

Basic

##### ADDITIONAL INFORMATION

Test module
library/my_test.py
```
#!/usr/bin/python
from __future__ import (absolute_import, division, print_function)
__metaclass__ = type
from ansible.module_utils.basic import AnsibleModule

def run_module():
    module_args = dict(warn_changes=dict(type='bool', default=None))
    result = dict(changed=False)
    module = AnsibleModule(argument_spec=module_args)

    if module.params['warn_changes'] is None:
        module.deprecate(
            'Test feature will change in 1.0.0',
            version='1.0.0', collection_name='test.test', warn_change=True)

    module.exit_json(**result)

def main():
    run_module()

if __name__ == '__main__':
    main()

```

invoked with:
```
ANSIBLE_LIBRARY=./library ./ansible/lib/ansible/cli/adhoc.py -m my_test localhost
```

Output:
```
[DEPRECATION WARNING]: Test feature will change in 1.0.0. This feature will 
change in test.test in version 1.0.0. Deprecation warnings can be disabled by 
setting deprecation_warnings=False in ansible.cfg.
localhost | SUCCESS => {
    "changed": false
}

```

See original issue for further discussion.

2022-10-21 08:53 UTC, tremble requested changes
I'm generally +1 to the implementation, a couple of minor things though.

Please would you update the unit tests, to include testing this change:
`test/units/module_utils/common/warnings/test_deprecate.py`

Please add a changelog entry:
https://docs.ansible.com/ansible/latest/community/development_process.html#changelogs-how-to

2022-10-21 08:54 UTC, tremble commented
@itxasos23 Thanks for taking the time to submit this PR.  Much appreciated from my side.

2022-10-21 17:17 UTC, s-hertel reviewed
This looks good, thanks for working on it.

2022-10-21 17:17 UTC, s-hertel commented on lib/ansible/utils/display.py
> +    def get_deprecation_message(self, msg, version=None, removed=False, warn_change=False, date=None, collection_name=None):
In case anything is calling this using positionals, put the new kwarg on the end.

2022-10-23 20:15 UTC, itxasos23 commented on lib/ansible/utils/display.py
> +    def get_deprecation_message(self, msg, version=None, removed=False, warn_change=False, date=None, collection_name=None):
Fair!
Updated, how about now?

2022-10-24 07:51 UTC, tremble requested changes
Minor niggles, but otherwise looking good.

2022-10-24 07:51 UTC, tremble commented on changelogs/fragments/79181-add-deprecate-warn-change.yml
> +  test.test in version 1.0.0.`
```suggestion
  that don't remove features. New wording ``This feature will change in 
  test.test in version 1.0.0.`` (https://github.com/ansible/ansible/pull/79181).
```

2022-10-24 07:51 UTC, tremble commented on lib/ansible/utils/display.py
> +    def deprecated(self, msg, version=None, removed=False, warn_change=False, date=None, collection_name=None):
```suggestion
    def deprecated(self, msg, version=None, removed=False, date=None, collection_name=None, warn_change=False):
```

2022-10-24 07:51 UTC, tremble commented on lib/ansible/utils/display.py
> +        message_text = self.get_deprecation_message(msg, version=version, removed=removed, warn_change=warn_change, date=date, collection_name=collection_name)
```suggestion
        message_text = self.get_deprecation_message(msg, version=version, removed=removed, date=date, collection_name=collection_name, warn_change=warn_change)
```

2022-10-26 13:07 UTC, s-hertel commented
@itxasos23 I assume you're working on this for Hacktoberfest and maybe there is still time to pick something else up, so I just wanted to let you know that I'm not sure it will be merged. When we triaged this yesterday it was basically a 50-50 split. It would have been better to catch this when triaging the feature request itself rather than waste potential-contributors' time. I'm still in favor of merging it (after bikeshedding the parameter name). Sorry and great work.

(also fyi @tremble)

2023-05-17 17:03 UTC, s-hertel commented
@itxasos23 Hi, this came up in backlog today and we discussed the change as a group. Instead of introducing a toggle to handle two different deprecation fragments, we reached a consensus that it would be preferable to make the existing fragment more generic, even if though it is a minor alteration in behavior. If you are still interested and available to work on it, could you please update this pull request?

needs_info

2023-06-18 17:46 UTC, closed without merging