document where to save cloud config files
ansible/ansible pull request #79412
Opened 2022-11-18 08:31 UTC by mdavis-xyz

##### SUMMARY

This fixes part of #79411.
This fixes the comment part.
And the part about the optional `security_token` field.
This does not modify the error message returned by `ansible-test`.

This should help with: https://github.com/ansible-collections/amazon.aws/issues/924

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
config

##### ADDITIONAL INFORMATION

I don't know what most of those files I modified are. I've only tested AWS stuff previously. So I need someone to confirm that the changes to those other files are applicable to those.

I did not modify the cloudscale one, because that's very barebones. I don't know if it's the same situation as the others.

I did not modify the openshift one, because it already had some mention of putting another file next to this one. That sounds possibly not right. Should both files go into `tests/integration` instead?

2023-01-16 23:25 UTC, mattclay requested changes
All of the `cloud-` prefixed templates are handled the same way, so the boilerplate should be updated on all of them.

2023-01-17 21:45 UTC, mdavis-xyz commented
What should the boilerplate say for the openshift one?

I currently says:

> place your kubeconfig file next to this file, with the same name, but without the .template extension.

The point of this change is that you're not supposed to modify these files or put files into the same folders.
So is "next to this file" incorrect?

I don't understand the point of that file. There's nothing in it. Is it just supposed to be some instructions, which are located in the same place as instructions for other modules?

Should it say:

> place your kubeconfig file 
> into the tests/integration directory of the collection you're testing, 
> with the same name as this file, but without the .template extension.

2023-01-17 21:55 UTC, mattclay commented
> Should it say:
> 
> > place your kubeconfig file
> > into the tests/integration directory of the collection you're testing,
> > with the same name as this file, but without the .template extension.

Yes, that should work. The instructions in all of these template files were created when they originally resided in the `test/integration/` directory (before we even had support for collections). The instructions were never updated when the files were moved.

2023-01-18 01:16 UTC, mdavis-xyz commented
Ok, now I've updated all the cloud- files.

2023-01-18 01:40 UTC, mattclay requested changes
Looks good. Just one minor cosmetic change requested.

2023-01-18 01:40 UTC, mattclay commented on test/lib/ansible_test/config/cloud-config-cloudscale.ini.template
> +# fill in the value below and save this file without the .template extension,
A minor cosmetic change:

```suggestion
# Fill in the value below and save this file without the .template extension,
```

2023-01-19 23:25 UTC, mattclay approved these changes

2023-01-19 23:25 UTC, merged

2023-01-19 23:25 UTC, mattclay commented
@mdavis-xyz Thanks for fixing this.