Fix password lookup rewrites file when using encrypt
ansible/ansible pull request #79431
Opened 2022-11-21 15:16 UTC by gaudenz

##### SUMMARY
This fixes a bug where the password file is always rewritten when using the encrypt parameter. The bug was introduced with commit 1bd7dcf339dd8b6c50bc16670be2448a206f4fdb.

Fixes: #79430.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
password lookup

2022-11-21 15:26 UTC, bcoca requested changes
lgtm, just needs a changelog

2022-11-21 17:41 UTC, gaudenz commented
@bcoca thanks for the review. I added a changelog entry, please have another look.

2022-11-21 17:55 UTC, bcoca approved these changes

2022-11-26 21:29 UTC, gaudenz commented
Anything left to do for this to be merged?

2022-11-29 15:26 UTC, mkrizek approved these changes

2022-11-29 15:26 UTC, merged