set_stats, make issues more transparent
ansible/ansible pull request #79559
Opened 2022-12-08 10:50 UTC by NickLohr

##### SUMMARY
That the stat module doesn't throw a warning (or even an error) when the Types are mismatched, is for me dangerous. This makes debugging a lot harder and in general more difficult to find small mistakes. Just returning "None" without any feedback to the user, is not transparent and can lead to dangerous errors, which are nearly impossible to find. 
This change is a small one and just an option. One also could throw an exception, but this could theoretically break some code (bad code in my opinion). With this small edit, no old code would break, but it can help find errors faster. 

##### ISSUE TYPE
Transparency, make Ansible easier to work with (Feature Pull Request I assume)

##### ADDITIONAL INFORMATION
The warning message is just a placeholder and can be changed easily. As long as there is a warning/error or just an info that something went wrong, would improve the Ansible experience.

2022-12-08 11:39 UTC, NickLohr commented on lib/ansible/executor/stats.py
```suggestion


```
Add new line

2022-12-08 14:40 UTC, bcoca requested changes
this would also need a changelog and tests

2022-12-08 14:40 UTC, bcoca commented on lib/ansible/executor/stats.py
> +            display.warning("Mismatching types in stats")
i would add which,what and host information, narrowing down where the mismatch hapened

2022-12-08 19:19 UTC, jborean93 commented
Are you also able to add a changelog fragment to document this bugfix as per https://docs.ansible.com/ansible/latest/community/development_process.html#creating-changelog-fragments.

2023-06-07 15:42 UTC, s-hertel commented
Closing for inactivity

2023-06-07 15:42 UTC, closed without merging