fall back to stderr/stdin for terminal with detection
ansible/ansible pull request #79780
Opened 2023-01-20 19:54 UTC by kristianheljas

##### SUMMARY

this allows to use pipes with grep without truncating the output while keeping compability with #70199 (commit: 45e0f747)

for example: `ansible-doc -l | grep ...`

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

display

##### ADDITIONAL INFORMATION

Before:
```
$ ansible-doc -l | grep deb
ansible.builtin.debconf                                          Configure ...
ansible.builtin.debug                                            Print stat...
```
After:
```
$ ansible-doc -l | grep deb
ansible.builtin.debconf                                          Configure a .deb package                                                                                                                                          
ansible.builtin.debug                                            Print statements during execution 
```

```paste below

```

2023-01-20 22:50 UTC, briantist commented on changelogs/fragments/79780-fix-column-width-detection.yaml
> +  - terminal width detection from stdout now falls back to stderr and stdin, keeping terminal width when piping ansible output (https://github.com/ansible/ansible/pull/79780)
nit
```suggestion
  - terminal width detection from stdout now falls back to stderr and stdin, keeping terminal width when piping ansible output (https://github.com/ansible/ansible/pull/79780).
```

2023-01-20 23:05 UTC, kristianheljas commented on changelogs/fragments/79780-fix-column-width-detection.yaml
> +  - terminal width detection from stdout now falls back to stderr and stdin, keeping terminal width when piping ansible output (https://github.com/ansible/ansible/pull/79780)
Good catch, afaik full sentences are required

2023-01-21 09:35 UTC, kristianheljas commented
CI got some weird [DNS resolution error](https://dev.azure.com/ansible/ansible/_build/results?buildId=66255&view=logs&j=d779b318-e945-5f68-8766-fbe2801e3df5&t=0a5086e0-1ee4-52f3-3f4e-e0e26cb687f5&l=91536).

Lets see if i can restart this.

/rebuild_failed

2023-01-23 22:17 UTC, bcoca commented
i can see the use of size with stdout/stderr .. but why stdin? that size is only for outputs

2023-01-24 15:37 UTC, bcoca requested changes
Not sure why you think using a pipe on stdin is breaking the output and the lack of tests doesn't help. 

I can see divergence between stdout/stder and the need for ttysize should adapt to whichever one we are printing to, but even then, this code does not fix that, just 'finds first descriptor with tty  size defined' and uses that for all.

2023-02-25 07:00 UTC, kristianheljas commented
Hey, the pipe on stdin does not break the output, pipe on stdout does, since pipe is not a tty and ansible-doc will cut out at 79 characters, making it non-usable with grep for example.

I know very little of ttys, but as far a I understand if any of those three are a TTY, it is referring to user terminal.

Stdin is there in case when both stdout and sterr are piped, ie `ansible-playbook ... > playbook.log 2>&1`

I finally have time to look at https://github.com/ansible/ansible/pull/73834 which also helps to resolve this issue, but i still don't like that grepping for documentation is not supported out of the box and would need extra configuration..

Anyway, @bcoca, if you're willing to consider checking only stdout/stderr streams for columns i would be happy with that as well. If not, or I'm talking jibberish about TTYs - close the issue.

2023-07-19 16:02 UTC, bcoca commented
closing as we have redesigned how display works across forks and this function needs a complete rewrite.

2023-07-19 16:02 UTC, closed without merging