ansible-playbook -K breaks when passwords have quotes
ansible/ansible pull request #79837
Opened 2023-01-29 22:34 UTC by msagi

##### SUMMARY
Fixes #79836 ("ansible-playbook -K breaks when passwords have quotes ")

ansible.config.manager.py ensure_type deliberately removes quotes from string and default value types, which causes sudo passwords starts and ends with quotes (" and ') to fail and needs double quoting. Since passwords are to be forwarded to sudo 'as is', I added a 'string_literal' type which does not remove quotes from the value. This enables passwords, like `"hello"` to go through sudo without issue.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
ansible.config.manager
ansible.plugins.become.sudo 

##### ADDITIONAL INFORMATION
If my password is `"hello"` entering it as `'"hello"'` in the become prompt works, entering it plain does not work.

2023-01-30 10:26 UTC, desultory commented
my sudo code doesn't seem to contain that type parameter 
`/usr/lib/python3.10/site-packages/ansible/plugins/become/sudo.py`

```
        become_pass:
            description: Password to pass to sudo
            required: False
            vars:
              - name: ansible_become_password
              - name: ansible_become_pass
              - name: ansible_sudo_pass
            env:
              - name: ANSIBLE_BECOME_PASS
              - name: ANSIBLE_SUDO_PASS
            ini:
              - section: sudo_become_plugin
                key: password
```

I could be looking at the wrong file

2023-02-06 18:25 UTC, bcoca requested changes
`sudo` is not the only become plugin, all others in core should be updated to do the same and we should make note to community and in docs that passwords might require this.

2023-02-06 18:25 UTC, bcoca commented on lib/ansible/config/manager.py
> +            value = to_text(value, errors='surrogate_or_strict')
i would not use to_text here as 'raw' is meant to bypass any conversion at the generic code and leave for plugin to handle

2023-02-06 18:35 UTC, bcoca commented
another option @sivel brought up, only use unquote on string if `origin = 'ini'` since that is the case that created the need to 'unquote'.

2023-02-06 19:16 UTC, sivel commented
Yeah, something like this:

```diff
diff --git a/lib/ansible/config/manager.py b/lib/ansible/config/manager.py
index e1fde1d30a..1396df1f60 100644
--- a/lib/ansible/config/manager.py
+++ b/lib/ansible/config/manager.py
@@ -144,14 +144,17 @@ def ensure_type(value, value_type, origin=None):
 
         elif value_type in ('str', 'string'):
             if isinstance(value, (string_types, AnsibleVaultEncryptedUnicode, bool, int, float, complex)):
-                value = unquote(to_text(value, errors='surrogate_or_strict'))
+                value = to_text(value, errors='surrogate_or_strict')
+                if origin == 'ini':
+                    value = unquote(value)
             else:
                 errmsg = 'string'
 
         # defaults to string type
         elif isinstance(value, (string_types, AnsibleVaultEncryptedUnicode)):
-            value = unquote(to_text(value, errors='surrogate_or_strict'))
-
+            value = to_text(value, errors='surrogate_or_strict')
+            if origin == 'ini':
+                value = unquote(value)
         if errmsg:
             raise ValueError('Invalid type provided for "%s": %s' % (errmsg, to_native(value)))
```

To further explain, the `unquote` exists there because people like to put quotes in the `ansible.cfg` and the ini parser just treats them as literal characters as part of the value.

2023-02-07 20:42 UTC, msagi commented
> 

Hi @sivel and @bcoca , sure, I'll take a look, the `origin = 'ini'` approach seems more straightforward to me. I'd like to do some tests though, as the original issue was related from a password typed in from command line, so perhaps there are other `origins` in addition to 'ini' where we can extend this approach to.

2023-02-07 21:40 UTC, bcoca commented
ini is the only origin that needs 'dequoting' env vars are handled by shell, yaml vars by yaml parser, prompts would pass through here w/o modifying once the `origin == 'ini'` code is in place

2023-02-08 21:30 UTC, msagi commented
> ini is the only origin that needs 'dequoting' env vars are handled by shell, yaml vars by yaml parser, prompts would pass through here w/o modifying once the `origin == 'ini'` code is in place

You are right, thanks for the explanation. I've made the recommended changes.

2023-02-09 16:30 UTC, bcoca commented
now you just need a changelog and tests

2023-02-10 00:56 UTC, msagi commented
> now you just need a changelog and tests

Sure, will do! 🙂

2023-02-10 18:49 UTC, bcoca approved these changes

2023-02-20 16:58 UTC, merged