Fix getting timeout for get mounts facts on Linux
ansible/ansible pull request #79847
Opened 2023-01-30 18:39 UTC by gdoucet

* Fix how to get the gather_timeout setting while getting the
mounts facts on Linux.

Issue: #79844

##### SUMMARY

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- Test Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2023-01-31 15:15 UTC, mkrizek requested changes
Please create a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment).

Also please add a test if at all possible.

2023-02-01 16:39 UTC, gdoucet commented
> Please create a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment).
> 
> Also please add a test if at all possible.

Hi @mkrizek , do you have a pointer how to create a test for this. I see there is already a test https://github.com/ansible/ansible/blob/devel/test/units/module_utils/facts/hardware/test_linux.py#L40 that already setup and teardown the timeout.GATHER_TIMEROUT.

2023-02-02 02:13 UTC, thmai11 commented
I tried to write a unit test for this fix. Unfortunately the value is defined and used within the method. It is never pass as an argument making it impossible to test it by asserting on a mock interaction.

2023-02-06 15:36 UTC, bcoca requested changes
we probably also want to update the timeout module to ignore gather_timeout global

2023-02-06 15:36 UTC, bcoca commented on lib/ansible/module_utils/facts/hardware/linux.py
> -        maxtime = globals().get('GATHER_TIMEOUT') or timeout.DEFAULT_GATHER_TIMEOUT
~we can just remove gather_timeout, this was for backwards compatibility with previous versions of ansible, it should always be using the default_gather_timeout in any 'current' version.~
nvmd, we did update the code so `timeout.GATHER_TIMEOUT` now reflects the parameters passed

2023-03-31 12:43 UTC, gdoucet commented
@bcoca Is there anything I can do in this PR?

2023-03-31 16:59 UTC, bcoca commented
tests

2023-03-31 19:53 UTC, thmai11 commented
@bcoca Its been a while I debugged this but here is what I remember (As I have not debugged it recently)
I already replied about that the value is defined and used within the method. It is never pass as an argument making it impossible to test it by asserting on a mock interaction. The original code call the globals() method. The variable is indeed global but in a different module. It look like that the globals() does not use the updated value which always resolve to None.  When I debugged the module following this documentation (https://docs.ansible.com/ansible/latest/dev_guide/debugging.html#detailed-debugging-steps)  I saw that the default value was resolving to None. When I changed it to the proposed fix (Reading from the module timeout) the value was correct. Such test would be possible to write if it was passed as an argument. There is definitely a problem with this and it require an high volume of filesystem to experience it because usually the default value is perfectly fine. We had to workaround this with a shell module invocation within our playbook.

2023-04-03 13:07 UTC, bcoca commented
/azp run

2023-04-03 13:25 UTC, bcoca approved these changes

2023-04-04 15:00 UTC, mkrizek approved these changes

2023-04-04 15:02 UTC, merged