Update async_status.py
ansible/ansible pull request #79935
Opened 2023-02-07 09:28 UTC by maa

##### SUMMARY
Added extra single qoutes in example, otherwise Ansible treat jid as floating point number.

##### ISSUE TYPE
- Docs Pull Request

+label: docsite_pr

##### SUMMARY

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- Test Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2023-02-07 15:28 UTC, mkrizek commented
Are you using `jinja2_native`?

needs_info

2023-02-08 08:31 UTC, maa commented
[defaults]
force_color = true
inventory = ./inventory
library = ./modules
jinja2_native = true
roles_path = ./roles.galaxy:./roles
bin_ansible_callbacks = true
stdout_callback = yaml
callback_whitelist = profile_tasks
log_path = ./ansible.log

2023-02-08 16:16 UTC, sivel commented
Ok, so as is, this change isn't likely the thing we want to do.  Your change will only work when jinja2 native is enabled, and will break the majority of users who are using the default.

We could potentially document this, or we do have a fix in another PR to handle this specific case, so there is no requirement to mess with the quoting (https://github.com/ansible/ansible/pull/67919/files?diff=unified&w=0#diff-22aefadd7744bdc563fede5e10e7855a92312e31fb6d69434fddc2200be40d1f)

For what it is worth, I believe that you could also work around this issue with using the `|string` filter:

```
jid: '{{ yum_sleeper.ansible_job_id|string }}'
```

At a minimum, instead of simply changing the current example, a new example would need added, and expanded documentation around why double quoting is required.  However, I think I'd prefer to address this as a code fix, and not push this complexity onto playbook authors.

2023-02-08 16:16 UTC, sivel requested changes
See https://github.com/ansible/ansible/pull/79935#issuecomment-1422880345

2023-02-08 18:47 UTC, mkrizek commented
Closing in favor of https://github.com/ansible/ansible/pull/79951.

2023-02-08 18:47 UTC, closed without merging