consistent booleans for page text and code blocks
ansible/ansible pull request #80036
Opened 2023-02-19 15:26 UTC by aasthavar

##### SUMMARY

Fixes #80012

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2023-02-22 00:06 UTC, DesmondSanctity requested changes

2023-02-22 00:06 UTC, DesmondSanctity commented on docs/docsite/rst/playbook_guide/playbooks_checkmode.rst
> +.. note:: Prior to version 2.2 only the equivalent of ``check_mode: n`` existed. The notation for that was ``always_run: yes``.
```suggestion
.. note:: Prior to version 2.2 only the equivalent of ``check_mode: no`` existed. The notation for that was ``always_run: yes``.
```

2023-02-23 14:35 UTC, aasthavar commented on docs/docsite/rst/playbook_guide/playbooks_checkmode.rst
> +.. note:: Prior to version 2.2 only the equivalent of ``check_mode: n`` existed. The notation for that was ``always_run: yes``.
Sorry, I missed it !

2023-02-23 15:22 UTC, samccann approved these changes

2023-02-23 15:24 UTC, merged

2023-02-23 15:25 UTC, samccann commented
Thanks @aasthavar for the Ansible docs fix and welcome to the Ansible project!. And thanks @DesmondSanctity for the review!