modules/dnf: Substitute variables in DNF cache path
ansible/ansible pull request #80094
Opened 2023-02-27 10:32 UTC by BenoitKnecht

##### SUMMARY

The cache directory can be specified with variables that are expanded by DNF, e.g.

```
cachedir=/var/cache/yum/$basearch/$releasever
```

But the `dnf` module would use that path literally, instead of replacing `$basearch` and `$releasever` with their values.

This commit ensures that variables in `cachedir` are properly substituted.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

`dnf`

##### ADDITIONAL INFORMATION

To reproduce the issue, set

```ini
[main]
cachedir=/var/cache/yum/$basearch/$releasever
```

in `/etc/dnf/dnf.conf` and use the `dnf` module to install a package. On the target system, Ansible will create a directory called `/var/cache/yum/$basearch/$releasever`, instead of `/var/cache/yum/x86_64/8` for instance.

```paste below

```

2023-02-27 23:06 UTC, sivel commented on lib/ansible/modules/dnf.py
> +            import libdnf
Up a few lines, you'll need to add a `global libdnf`

2023-02-28 09:07 UTC, BenoitKnecht commented on lib/ansible/modules/dnf.py
> +            import libdnf
Thanks @sivel, added! :slightly_smiling_face:

2023-02-28 09:37 UTC, BenoitKnecht commented
Looks like [`mypy` is unhappy about `libdnf`](https://dev.azure.com/ansible/ansible/_build/results?buildId=69838&view=logs&j=f39c292d-0a23-56d4-e7e5-386951c14ece&t=3af4f6c8-91cf-5ddb-8873-9e1cb9dedca9&l=361) now though:

```
01:08 FATAL: Encountered 1 fatal errors reported by mypy:
01:08 lib/ansible/modules/dnf.py:582:1: import: Cannot find implementation or library stub for module named "libdnf"
```

I'm not sure how to get around that.

2023-02-28 15:28 UTC, BenoitKnecht commented
> Looks like [`mypy` is unhappy about `libdnf`](https://dev.azure.com/ansible/ansible/_build/results?buildId=69838&view=logs&j=f39c292d-0a23-56d4-e7e5-386951c14ece&t=3af4f6c8-91cf-5ddb-8873-9e1cb9dedca9&l=361) now though:
> 
> ```
> 01:08 FATAL: Encountered 1 fatal errors reported by mypy:
> 01:08 lib/ansible/modules/dnf.py:582:1: import: Cannot find implementation or library stub for module named "libdnf"
> ```
> 
> I'm not sure how to get around that.

OK, I managed to work around it with 197e1a6771a16d1ec8459ed96c5d16a1d13f0eee.

2023-07-26 19:42 UTC, jborean93 requested changes
For the changes here we will need a changelog fragment for this PR which is documented here https://docs.ansible.com/ansible/latest/community/development_process.html#creating-changelog-fragments. We would also look at adding some integration tests for this scenario under https://github.com/ansible/ansible/tree/devel/test/integration/targets/dnf. The integration tests might be a bit harder to setup but we can certainly work through them if you have any questions.

2024-04-09 19:19 UTC, Akasurde approved these changes
LGTM

2024-04-09 20:09 UTC, jborean93 approved these changes

2024-04-09 20:11 UTC, merged