Issue #80267: Remove user not found warning
ansible/ansible pull request #80291
Opened 2023-03-23 21:20 UTC by Sebi94nbg

##### SUMMARY

Removes the warning, when `local: true` and the user could not be found.

A note about this warning already exists in the documentation.

Fixes #80267

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

ansible.builtin.user

##### ADDITIONAL INFORMATION

See #80267.

2023-03-28 15:08 UTC, mkrizek requested changes
Please create a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment).

The integration tests need to be changed as well. Probably just remove the assert checking for the warning.

2023-11-06 03:41 UTC, Akasurde commented
@Sebbo94BY Are you still working on this?

2023-11-20 14:04 UTC, Sebbo94BY commented
Sorry for the delay.

I've added the missing changelog fragment.

I couldn't find any assertion / test for this specific code. Which do you mean?

2023-11-23 14:25 UTC, mkrizek approved these changes

2023-11-23 14:25 UTC, merged