WIP: Remove deprecated include
ansible/ansible pull request #80752
Opened 2023-05-10 03:42 UTC by jborean93

##### SUMMARY
Removes the deprecated `include` plugin. Users should use `include_tasks` or `import_tasks` instead.

Fixes: https://github.com/ansible/ansible/issues/80445

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
include

2023-05-11 09:57 UTC, ssbarnea approved these changes

2023-05-17 22:29 UTC, sivel requested changes

2023-05-17 22:29 UTC, sivel commented on lib/ansible/playbook/helpers.py
>                          if action in C._ACTION_IMPORT_TASKS:
I believe this `if` statement can be removed.

2023-05-18 19:18 UTC, sivel approved these changes

2023-05-18 19:49 UTC, merged