ansible-test: remove Ubuntu 20.04 LTS
ansible/ansible pull request #81070
Opened 2023-06-15 15:52 UTC by Akasurde

##### SUMMARY

Fixes: #80853

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
.azure-pipelines/azure-pipelines.yml
changelogs/fragments/ansible-test-remove-ubuntu-2004.yml
test/integration/targets/apt/vars/Ubuntu-20.yml
test/lib/ansible_test/_data/completion/docker.txt

2023-06-15 17:17 UTC, mattclay requested changes

2023-06-15 17:17 UTC, mattclay commented on .azure-pipelines/azure-pipelines.yml
> -              test: ubuntu2004
These lines should not be removed. We only want to remove the Ubuntu 20.04 VM, not containers.

2023-06-15 17:17 UTC, mattclay commented on changelogs/fragments/ansible-test-remove-ubuntu-2004.yml
> +  - ansible-test - Removed Ubuntu 20.04 LTS image from the default completion list.
```suggestion
  - ansible-test - Removed Ubuntu 20.04 LTS image from the `--remote` option.
```

2023-06-15 17:17 UTC, mattclay commented on test/integration/targets/apt/vars/Ubuntu-20.yml
> -multiarch_test_pkg: libunistring2
This file is still needed for integration tests run in a container.

2023-06-15 17:17 UTC, mattclay commented on test/lib/ansible_test/_data/completion/docker.txt
> -ubuntu2004 image=quay.io/ansible/ubuntu2004-test-container:5.0.0 python=3.8
Container support should be retained. The VM completion entry should be removed instead:

https://github.com/ansible/ansible/blob/cde15f3c8158467a96023a9cffcba4bc0a207b0f/test/lib/ansible_test/_data/completion/remote.txt#L17

2023-06-15 20:43 UTC, mattclay approved these changes
Looks good.

CC @felixfontein I noticed you're using this here: https://github.com/ansible-collections/community.crypto/blob/230f0b51f2b4003089beb6767d7c0f7e5348a9cc/.azure-pipelines/azure-pipelines.yml#L205-L206

2023-06-16 04:16 UTC, felixfontein commented
@mattclay thanks for the heads up! I just removed it in https://github.com/ansible-collections/community.crypto/pull/623.

2023-06-20 18:25 UTC, merged