ansible-test: remove alpine 3.17
ansible/ansible pull request #81124
Opened 2023-06-26 14:46 UTC by bcoca

fixes #80418 

##### ISSUE TYPE

- Test Pull Request

##### COMPONENT NAME

ansible-test

2023-06-26 21:06 UTC, mattclay commented
This should be announced before being merged.

For reference, here's the recent announcement for the Fedora change: https://github.com/ansible-collections/news-for-maintainers/issues/50

The tool to generate the announcement checklist has already been updated: https://github.com/ansible/ansible-azp-tools/pull/33

2023-06-26 21:08 UTC, mattclay requested changes

2023-06-26 21:08 UTC, mattclay commented on changelogs/fragments/a_test_rmv_alpine_317.yml
> +  - ansible-test, remove Alpine 3.17 from remotes/CI
We don't include CI changes in the changelog, since they don't make it into the sdist, just the ansible-test changes:

```suggestion
  - ansible-test - remove Alpine 3.17 from remotes
```

2023-06-26 22:10 UTC, mattclay approved these changes

2023-06-26 22:11 UTC, mattclay commented
I converted this to a draft to help avoid accidental merges.

2023-07-10 15:08 UTC, bcoca commented
https://github.com/ansible-collections/news-for-maintainers/issues/52

2023-08-01 18:54 UTC, merged