fix/81553 Add exceptions for illegal names in role
ansible/ansible pull request #81555
Opened 2023-08-21 22:09 UTC by atsalolikhin-spokeo

##### SUMMARY

Fixes #81553

##### ISSUE TYPE

- Bugfix Pull Request
 

##### ADDITIONAL INFORMATION

See #81553

2023-08-21 23:59 UTC, atsalolikhin-spokeo commented
@bcoca Is this something like what you had in mind?  I'm just learning Python so feel free to steer me in the right direction if there is anything off about this PR.  

I didn't test my changes because the README says you install from pip and my changes are not in pip.  I wasn't sure how to install Ansible from the source tree.

However the PR passed the CI test:  78 successful checks.

Thanks!

2023-08-23 15:32 UTC, bcoca commented
I would change those to warnings (`display.warning()`) to keep it backwards compatible, but give users at least a hint why the files were not extracted.

2023-08-23 16:19 UTC, atsalolikhin-spokeo commented
@bcoca Thanks!  I added `display.warning()`.

I'm not sure I correctly understood your comment https://github.com/ansible/galaxy/issues/271#issuecomment-1686846546 saying this should not be an unhandled exception.

I am raising `RuntimeError` with an explanation now rather than letting Python exit with Errno 20 and a cryptic and potentially misleading "Not a directory" error message.

Is that what you had in mind here?

2023-08-23 17:06 UTC, bcoca commented
The 'unexpected exception' message comes from our 'catchall' and is normally indication of a bug, for this one i think we should handle the issue more gracefully and return a more pertinent error message that allows the user to fix/bypass the issue.

Your current code does avoid this but it changes behavior by preventing the install of the role at all vs just skipping the 'bad files', this is why i suggested above you change it into a warning. The ultimate fix for the original error would capture the existing exception and reraise it in an `AnsibleError` with appropriate messaging.

2023-08-23 17:09 UTC, bcoca commented
This is the loop which generates the error reported
https://github.com/ansible/ansible/pull/81555/files#diff-b99ff71e25ad80853389fe308d3e0693231cfb21e28ecaf7f80bd4a3ee23ade1L317

it should either have the same/similar code and skip 'bad members' or handle the exception and either reraise or skip (cause we know why we didnt create the dir).

2023-08-23 17:10 UTC, bcoca requested changes
this will also need a changelog and tests

2023-08-23 17:10 UTC, bcoca commented on lib/ansible/galaxy/role.py
> +                                        raise RuntimeError
remove the raise RuntimeError and just add a continue (next item in loop)

2023-08-23 17:16 UTC, atsalolikhin-spokeo commented
@bcoca Thank you very much. Could you please point me in the right direction for how to install Ansible from source code? I want to be able to test my changes end-to-end.

2023-08-23 17:20 UTC, bcoca commented
https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#installing-for-development
^ personally i use the clone, but any option should work

2023-08-23 21:23 UTC, atsalolikhin-spokeo commented
# Validation

## Before

```
$ ansible-galaxy install -r requirements.yml --force
Starting galaxy role install process
- extracting ansible-galaxy-issue-271 to /home/atsaloli/.ansible/roles/ansible-galaxy-issue-271
[WARNING]: - ansible-galaxy-issue-271 was NOT installed successfully: Could not update files in /home/atsaloli/.ansible/roles/ansible-galaxy-issue-271:
[Errno 20] Not a directory: '/home/atsaloli/.ansible/roles/ansible-galaxy-issue-271/files/udf/CMC_VWAP.class'
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
$
```

## After

```
[/tmp] [py-3.11] $ ansible-galaxy install -r requirements.yaml
[WARNING]: You are running the development version of Ansible. You should only run Ansible from "devel" if you are modifying
the Ansible engine, or trying out features under development. This is a rapidly changing source of code and can become
unstable at any point.
Starting galaxy role install process
- extracting ansible-galaxy-issue-271 to /Users/atsalolikhin/.ansible/roles/ansible-galaxy-issue-271
[WARNING]: Illegal filename 'CMC_VWAP$CMC_VWAP_proc.class': names cannot contain '$'
[WARNING]: - ansible-galaxy-issue-271 was NOT installed successfully: Could not update files in
/Users/atsalolikhin/.ansible/roles/ansible-galaxy-issue-271: [Errno 20] Not a directory:
'/Users/atsalolikhin/.ansible/roles/ansible-galaxy-issue-271/files/udf/CMC_VWAP.class'
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
[/tmp] [py-3.11] $
```

The behavior is exactly the same as before, except it adds a warning to give a hint to the user.

```
[WARNING]: Illegal filename 'CMC_VWAP$CMC_VWAP_proc.class': names cannot contain '$'
```

In both cases, role installation fails halfway through.  

I feel this changeset accomplishes my purpose, which was to add a warning that explains what just happened (why the installation failed), and would be an incremental improvement to the codebase.

@bcoca Thank you for helping me install Ansible from source code. Is there any documentation on how to update the changelog?   I looked at https://docs.ansible.com/ansible/latest/community/contributor_path.html and the dev guide.

Also, I see there is already an integration test for invalid filenames: https://github.com/ansible/ansible/blob/116948cd1468b8a3e34af8e3671f4089e1f7584c/test/integration/targets/ansible-galaxy-role/tasks/main.yml#L28-L31

Do you still expect me to add a test for my changeset?  I'm happy to learn how to do that if so.

2023-08-24 15:49 UTC, bcoca commented
https://docs.ansible.com/ansible/latest/community/development_process.html#creating-changelog-fragments

2023-08-24 16:46 UTC, atsalolikhin-spokeo commented
/rebuild_failed

2023-08-24 17:53 UTC, atsalolikhin-spokeo commented
@bcoca I've added a changelog fragment; and I see we already have a test for invalid filenames: https://github.com/ansible/ansible/blob/116948cd1468b8a3e34af8e3671f4089e1f7584c/test/integration/targets/ansible-galaxy-role/tasks/main.yml#L28-L31

Do you still feel it's necessary to add tests to this PR?  (I'd be happy to do so if needed.)

Otherwise this changeset is ready for re-review, please.

Thanks very much for your help along the way!

2023-08-28 17:57 UTC, atsalolikhin-spokeo commented
@bcoca Do you have any concerns about this changeset as it stands today?   :)  This is my first PR to the project, it's not my intention to make a major rewrite of any part (I saw Alexander's comment in commit 1c83672532330d0d26b63f8a97ee703e7fc697df that the entire module needs a rewrite), I just want to drop the user some breadcrumbs (a hint) about why role installation is failing when the role contains Java inner classes (files with `$` in the filenames).

2023-08-28 18:52 UTC, bcoca approved these changes
while we still need to add code to handle the exception, this is still an improvement and can be merged independantly

2023-08-28 18:54 UTC, merged

2023-08-28 18:57 UTC, atsalolikhin-spokeo commented
Thank you very much @bcoca for orienting me to Ansible development and helping me with my first PR.  :)  Win!

2023-08-28 18:59 UTC, bcoca commented
thank you for your contribution