dnf module can be used to update packages to latest
ansible/ansible pull request #81568
Opened 2023-08-23 18:10 UTC by barbacbd

[Fixes 81376](https://github.com/ansible/ansible/issues/81376).

Allow users to update packages with dnf using:
-- update-only: true
   state: latest

##### SUMMARY

DNF module update_only functionality was altered to allow packages or names of packages to be updated. 

##### ISSUE TYPE

- Bugfix Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

2023-08-24 10:26 UTC, mkrizek requested changes
The integration tests being added in this pull request pass even without the change and do not appear to test the issue the change is trying to fix. Rather they are testing `update_only` functionality which I believe we already have a test for.

The bug in https://github.com/ansible/ansible/issues/81376 manifests itself when `update_only` is used when installing an rpm directly (filesystem/network), not from a repository.

2023-08-24 17:45 UTC, barbacbd commented
> The integration tests being added in this pull request pass even without the change and do not appear to test the issue the change is trying to fix. Rather they are testing `update_only` functionality which I believe we already have a test for.
> 
> The bug in #81376 manifests itself when `update_only` is used when installing an rpm directly (filesystem/network), not from a repository.

The update to tests should be working. Without the changes the same test was failing. With the changes to the dnf module the test passes.

2023-08-25 07:27 UTC, mkrizek commented on changelogs/fragments/dnf-update-only-latest.yml
> +  - update only - packages were failing when update-only was set as well as latest was selected (https://github.com/ansible/ansible/issues/81376).
The following should describe the problem better and mention the module name as well:
```suggestion
  -  dnf - fix a failure when a package from URI was specified and ``update_only`` was set (https://github.com/ansible/ansible/issues/81376).
```

2023-08-28 08:46 UTC, mkrizek approved these changes

2023-08-28 08:48 UTC, merged