Remove deprecated JINJA2_NATIVE_WARNING env var
ansible/ansible pull request #81720
Opened 2023-09-19 06:56 UTC by mkrizek

##### SUMMARY

Fixes #81714

##### ISSUE TYPE

- Feature Pull Request

2023-09-19 14:24 UTC, webknjaz commented
/azp run

2023-09-19 15:32 UTC, bcoca requested changes

2023-09-19 15:32 UTC, bcoca commented on lib/ansible/config/base.yml
> -      deprecated:
this only deprecated the env var, the whole entry should have had a deprecation notice, those using ini, for example would not get notice.

2023-09-19 15:32 UTC, bcoca commented on lib/ansible/config/base.yml
> -      deprecated:
we probalby need to 'redeprecate', but the entire entry now.

2023-09-19 15:40 UTC, sivel commented on lib/ansible/config/base.yml
> -      deprecated:
Well, it wasn't doing anything anyway, we just didn't use it anyway, and having it in the config isn't an error, so it would still be ignored regardless.  I think it should be fine to remove it.

2023-10-02 19:57 UTC, bcoca approved these changes

2023-10-02 19:57 UTC, merged