Throw LockFailedException if apt cmd encounters a lock file
ansible/ansible pull request #81754
Opened 2023-09-21 16:01 UTC by chrispbailey

##### SUMMARY

Fixes https://github.com/ansible/ansible/issues/78658

##### ISSUE TYPE

- Bugfix Pull Request

##### ADDITIONAL INFORMATION

An earlier attempt (https://github.com/ansible/ansible/issues/78658) to fix this issue didn't work for me because because `DPkg::Lock::Timeout` is an `apt` parameter not a `dpkg` one.

The code supports the `lock_timeout` parameter but the problem here is that the when the lock issue is encountered, the code subsequently runs `m.fail_json` which then calls `sys.exit` and this bypasses the `except apt.cache.LockFailedException` handler so the cmd is never re-tried.

I'm sure there are better solutions to this issue but I'm raising this PR here just in case others want to use this solution by overriding apt.py locally.

2024-05-15 19:46 UTC, jborean93 requested changes
Thanks for PR, are you able to create a changelog fragment for this bugfix as per https://docs.ansible.com/ansible/latest/community/development_process.html#creating-changelog-fragments. It would also be great to have an integration test for at least some of the scenarios, it could potentially be done by having an `async` task that locks the file while you then run a normal task that expects the lock to be there and fail after the timeout.

2025-01-21 15:50 UTC, webknjaz commented
/azp run

2025-01-21 15:54 UTC, webknjaz commented
@mattclay @sivel this is an example PR that #84375 / #84402 would've helped with.

2025-10-08 07:30 UTC, mkrizek commented
I am closing this as https://github.com/ansible/ansible/issues/78658 was fixed in https://github.com/ansible/ansible/pull/85219. Thank you for your contribution.

2025-10-08 07:30 UTC, closed without merging