Updated some incomplete docstrings, added missing docstrings
ansible/ansible pull request #81861
Opened 2023-10-03 18:32 UTC by freewayml

##### SUMMARY

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- Test Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

2023-10-03 21:07 UTC, bcoca commented on lib/ansible/executor/playbook_executor.py
> +
?

2023-10-03 21:10 UTC, bcoca requested changes
I think it is good to add most of these, but we should keep using the formatting we use elsewhere instead of changing function documentation standards. https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/common/text/converters.py#L33

2023-10-04 00:18 UTC, freewayml commented
> I think it is good to add most of these, but we should keep using the formatting we use elsewhere instead of changing function documentation standards. https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/common/text/converters.py#L33

I appreciate the feedback. I've updated one file as a test to verify the format is correct before fixing the rest of the files in this PR.  Can you take a look at lib/ansible/playbook/attribute.py and let me know if this file looks good? thanks!

2023-10-04 14:12 UTC, bcoca commented
sample looks good, feel free to continue

2023-10-04 20:53 UTC, freewayml commented
> sample looks good, feel free to continue

Thanks, I've updated the rest of the PR per the repo formatting standard and verified code formatting using black.

2024-05-29 19:43 UTC, Akasurde commented
@freewaydev Could you please rebase this branch and let us know? Thanks,

2025-06-06 02:07 UTC, closed without merging

2025-06-06 02:07 UTC, mattclay commented
Closing due to inactivity.