Remove Python 2 datetime compat fallbacks
ansible/ansible pull request #81874
Opened 2023-10-03 21:10 UTC by webknjaz

##### SUMMARY

$sbj.

##### ISSUE TYPE

- Maintenance Pull Request

##### ADDITIONAL INFORMATION

N/A

2023-10-10 14:01 UTC, webknjaz commented
> The test `ansible-test sanity --test no-get-exception` [[explain](https://docs.ansible.com/ansible-core/devel/dev_guide/testing/sanity/no-get-exception.html)] failed with 1 error:
> 
> ```
> lib/ansible/module_utils/compat/datetime.py:31:10: do not use `get_exception`
> ```

@mattclay apparently that `no-get-exception` test matches `get_exception()` within docstrings. Is it supposed to do that?

2023-10-11 16:47 UTC, webknjaz commented
So the CI failure is
```console
01:24 _____________________ test_deprecate_without_list[stdin0] ______________________
01:24 [gw0] linux -- Python 3.12.0 /usr/bin/python3.12
01:24 
01:24 am = <ansible.module_utils.basic.AnsibleModule object at 0x7fca11c53530>
01:24 capfd = <_pytest.capture.CaptureFixture object at 0x7fca11c2dfd0>
01:24 
01:24     @pytest.mark.parametrize('stdin', [{}], indirect=['stdin'])
01:24     def test_deprecate_without_list(am, capfd):
01:24         with pytest.raises(SystemExit):
01:24             am.exit_json(deprecations='Simple deprecation warning')
01:24     
01:24         out, err = capfd.readouterr()
01:24         output = json.loads(out)
01:24 E         
01:24 E         ...Full output truncated (21 lines hidden), use '-vv' to show
01:24 
01:24 test/units/module_utils/basic/test_deprecate_warn.py:67: AssertionError
```

Which is weird because I cannon reproduce it locally with `--docker`.

2023-10-11 17:22 UTC, webknjaz commented
Aha.. So `while :; do if ! bin/ansible-test units --docker --python 3.12 -vvvvvv --debug -- test/units/module_utils/basic/test_deprecate_warn.py; then break; fi; done` doesn't reproduce the problem, but running much more tests does, like this:
```console
$ while :; do if ! bin/ansible-test units --docker --python 3.12 -vvvvvv --debug -- test/units/module_utils/; then break; fi; done
```

2023-10-11 17:27 UTC, webknjaz commented
Reduced the repro to
```console
$ while :; do if ! bin/ansible-test units --docker --python 3.12 -vvvvvv --debug -- test/units/module_utils/basic/test_deprecate_warn.py test/units/module_utils/compat/test_datetime.py; then break; fi; done
```

2023-10-11 17:38 UTC, webknjaz commented
Apparently, `test/units/module_utils/compat/test_datetime.py` `import`s the deprecated objects `from` the compat module, accessing them at import time, which triggers deprecation warnings that leak into stdout later on.

2023-10-11 18:00 UTC, webknjaz commented
@mattclay should we only deprecate the `UTC` object in this module?

2023-10-12 00:56 UTC, mattclay requested changes, later dismissed
It's too early to deprecate this, since collections may need it for compatibility across multiple non-EOL versions of ansible-core. Instead of deprecating it, add a deprecated comment (detected by pylint) so we can defer deprecation until 2.16 (the first version with this module_util) is the oldest non-EOL version.

2023-10-18 16:36 UTC, webknjaz commented
@mattclay so I wasn't sure about deprecating since most of these aren't exact implementations of what's in stdlib.

2025-02-05 17:07 UTC, mattclay commented
@webknjaz I can review this once the test issues are resolved. Let me know if you need help with the test failures.

2025-02-18 01:32 UTC, mattclay submitted a review, later dismissed
There are 3 Ansible modules that still use `ansible.module_utils.compat.datetime`, which should be updated to use `datetime` directly, while avoiding deprecated methods.

2025-02-18 01:32 UTC, mattclay commented on lib/ansible/module_utils/compat/datetime.py
> +# __all__ = ('UTC', 'utcfromtimestamp', 'utcnow')  # pylint: disable=undefined-all-variable
Is there a reason to leave this comment here?

2025-02-18 01:32 UTC, mattclay commented on lib/ansible/module_utils/compat/datetime.py
> +        version='2.20',
I'd set this to 2.21 instead, for a "normal" short deprecation cycle, given that there appears to be little to no use of these functions.

2025-02-18 01:32 UTC, mattclay commented on lib/ansible/module_utils/facts/system/date_time.py
> +        utcnow = datetime.datetime.utcfromtimestamp(epoch_ts)
This should be updated to not use a deprecated function.

2025-02-19 18:44 UTC, webknjaz commented on lib/ansible/module_utils/compat/datetime.py
> +        version='2.20',
ack

2025-02-19 18:44 UTC, webknjaz commented on lib/ansible/module_utils/compat/datetime.py
> +# __all__ = ('UTC', 'utcfromtimestamp', 'utcnow')  # pylint: disable=undefined-all-variable
I might've missed it. Thanks!

2025-02-19 18:46 UTC, webknjaz commented
Thanks for the hint to check other modules. Recording the findings for history:
```console
$ rg compat\\.datetime
lib/ansible/modules/wait_for.py
241:from ansible.module_utils.compat.datetime import utcnow

lib/ansible/modules/uri.py
446:from ansible.module_utils.compat.datetime import utcnow, utcfromtimestamp

lib/ansible/modules/get_url.py
379:from ansible.module_utils.compat.datetime import utcnow, utcfromtimestamp

lib/ansible/module_utils/compat/datetime.py
49:        msg=f'The `ansible.module_utils.compat.datetime.{importable_name}` '
```

2025-02-20 00:12 UTC, webknjaz commented on lib/ansible/module_utils/facts/system/date_time.py
> +        utcnow = datetime.datetime.utcfromtimestamp(epoch_ts)
Done. Marking as resolved.

2025-02-20 00:12 UTC, webknjaz commented on lib/ansible/module_utils/compat/datetime.py
> +        version='2.20',
Done. Marking as resolved.

2025-02-20 00:12 UTC, webknjaz commented on lib/ansible/module_utils/compat/datetime.py
> +# __all__ = ('UTC', 'utcfromtimestamp', 'utcnow')  # pylint: disable=undefined-all-variable
Fixed. Marking as resolved.

2025-02-20 22:56 UTC, webknjaz commented
@mattclay I think I tracked down everything.

2025-03-11 05:05 UTC, mattclay requested changes, later dismissed
Include a changelog fragment for the deprecation.

2025-03-11 05:05 UTC, mattclay commented on lib/ansible/module_utils/compat/datetime.py
> +        ) from key_err
This more accurately reflects the standard behavior:

```suggestion
        raise AttributeError(f"module {__name__!r} has no attribute {key_err}") from None
```

2025-03-11 14:43 UTC, webknjaz commented on lib/ansible/module_utils/compat/datetime.py
> +        ) from key_err
I suppose… Although, this exception isn't actually surfaced anywhere. The end-users get a regular `ImportError`, I think.

2025-03-11 15:25 UTC, mattclay commented on lib/ansible/module_utils/compat/datetime.py
> +        ) from key_err
The `AttributeError` is exposed when accessing attributes instead of importing them, such as:

```python
from ansible.module_utils.compat import datetime

datetime.something
```

2025-03-11 15:36 UTC, mattclay approved these changes

2025-03-11 16:19 UTC, merged