Infame io/rpm key
ansible/ansible pull request #81929
Opened 2023-10-07 11:50 UTC by infame-io

##### SUMMARY

It would be great if the GPG key could be passed as a string value into the `ansible.builtin.rpm_key` module. This would allow passing the GPG key as an env. variable
```bash
export GPG_KEY="-----BEGIN PGP PUBLIC KEY BLOCK-----

mQGNBGUhLi4BDACrXw5kkEdclg7edHjzs3dCs4GIn7ct/tkyhi0Sw5cmH8txujPi
...
6cy9+l5zdaTzJ+biexvyK7dhXXhyueXWaDF9
=NXmg
-----END PGP PUBLIC KEY BLOCK-----"
```

```yaml
---
- name: Import GPG key
  hosts: sandwich

  tasks:
    - name: Import key (env. var)
      become: true
      ansible.builtin.rpm_key:
        key: '{{ lookup("env", "GPG_KEY" )}}'
        state: present
```

and it could enable passing the GPG key from services like AWS Systems Manager Parameter Store
```yaml
---
- name: Import GPG key
  hosts: sandwich

  tasks:
    - name: Import key (AWS SSM)
      become: true
      ansible.builtin.rpm_key:
        key: '{{ lookup("aws_ssm", "/test/ansible/rpm.key.gpg", region="us-east-1" )}}'
        state: present
```

##### ISSUE TYPE

- Feature Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

2023-10-17 15:26 UTC, bcoca requested changes
also missing a changelog

2023-10-17 15:26 UTC, bcoca commented on lib/ansible/modules/rpm_key.py
> +            keyfile = self.keyfile(bytes(key, 'utf-8'))
use ``to_bytes`` function instead

2023-10-17 15:26 UTC, bcoca commented on lib/ansible/modules/rpm_key.py
> +        tmpfd, tmpname = tempfile.mkstemp()
the module already has a private tmpdir, use that to keep files in a place we guarantee cleanup

2023-10-19 01:27 UTC, infame-io commented on lib/ansible/modules/rpm_key.py
> +            keyfile = self.keyfile(bytes(key, 'utf-8'))
Updated

2023-10-19 01:30 UTC, infame-io commented
Thank you @bcoca. Changelog included

2023-10-19 14:27 UTC, bcoca approved these changes

2023-10-19 14:29 UTC, bcoca requested changes
one thing I missed, the `key:`  option is missing an update, add 'since version 2.17 you can also pass the key as a string'

2024-12-06 20:19 UTC, Akasurde commented
@infame-io Are you still working on this? Thanks.

2025-01-10 20:44 UTC, closed without merging