Fix locale related parsing error in git.py
ansible/ansible pull request #81931
Opened 2023-10-09 12:38 UTC by Migsi

##### SUMMARY

This fixes the issue found at https://github.com/ansible/ansible/issues/77213 which got introduced by changing over to "best parseable locale" approach, but missing out the requirement of locales other than `L` having to have `LANGUAGE` specified as well. For further details, check this post within the issue discussion: https://github.com/ansible/ansible/issues/77213#issuecomment-1446919617

##### ISSUE TYPE

- Bugfix Pull Request

##### ADDITIONAL INFORMATION

See above linked issue report and linked explanation to why this caused an error in the first place.

2023-10-17 15:27 UTC, bcoca requested changes
add a changelog

2023-10-23 14:52 UTC, Migsi commented
> add a changelog

~~Pardon if I ask stupidly: Where? And are there any formatting templates/requirements?~~

Done.

2023-10-25 12:44 UTC, mkrizek approved these changes

2023-10-25 13:39 UTC, bcoca approved these changes

2023-10-25 13:47 UTC, merged