[WIP] Allow multiple documents in the YAML stream for EXAMPLES.
ansible/ansible pull request #82355
Opened 2023-12-05 07:25 UTC by tremble

##### SUMMARY

Fixes: #82353 

EXAMPLES are intended to be copy-and-paste ready.

While most of the documentation is expected to be a single document, it's reasonable to expect that within examples (especially for inventory plugins), there may be multiple documents in there. If only a single document is permitted, then when multiple examples are added for an inventory plugin, attempting to lint the YAML results in key-duplicates errors.

##### ISSUE TYPE

- Feature Pull Request

##### ADDITIONAL INFORMATION

See also https://github.com/ansible/ansible-lint/issues/3860

2023-12-05 13:22 UTC, tremble commented
@ssbarnea how would you feel about this approach as a way to deal with https://github.com/ansible/ansible-lint/issues/3860 ?

ansible-docs handles multiple documents in EXAMPLES fine, as does ansible-lint.

2023-12-05 14:41 UTC, bcoca commented
both the original and the proposed changes are wrong, `EXAMPLES` is a 'free text' field.

2023-12-05 14:53 UTC, tremble commented
> both the original and the proposed changes are wrong, `EXAMPLES` is a 'free text' field.

Thanks for looking at this, the documentation seems to conflict with this statement https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_documenting.html#examples-block

> After the shebang, the UTF-8 coding, the copyright line, the license section, and the DOCUMENTATION block comes the EXAMPLES block. Here you show users how your module works with real-world examples in multi-line plain-text YAML format. The best examples are ready for the user to copy and paste into a playbook. Review and update your examples with every change to your module.

2023-12-05 14:55 UTC, bcoca commented
Yes, someone assumed examples was YAML and ran with it.... does not help that most instances of it ARE YAML.

2023-12-05 15:45 UTC, bcoca commented
adding docs to script inventory plugins so we at least have some example in core #82361

2023-12-05 19:08 UTC, tremble commented
Probably obsoleted by #82361

2023-12-05 19:17 UTC, sivel commented
fwiw, we have a way to dictate that `EXAMPLES` is not YAML.  See:

https://github.com/ansible/ansible/blob/6ebefaceb6cd0d4961776a94d63a71fc1fc28bc0/lib/ansible/plugins/inventory/toml.py#L18

As long as `# fmt: whatever` is specified as the first line, and `whatever` isn't actually `yaml` then it will skip:

https://github.com/ansible/ansible/blob/6ebefaceb6cd0d4961776a94d63a71fc1fc28bc0/test/lib/ansible_test/_util/controller/sanity/yamllint/yamllinter.py#L184-L187

https://github.com/ansible/ansible/blob/6ebefaceb6cd0d4961776a94d63a71fc1fc28bc0/test/lib/ansible_test/_util/controller/sanity/yamllint/yamllinter.py#L120-L123

2023-12-05 19:21 UTC, tremble commented
@sivel In my specific case, it *is* YAML, but ansible-test doesn't currently support YAML multi-documents, so the current ansible-test is still broken

2023-12-06 15:15 UTC, webknjaz commented
/azp run

2023-12-07 19:40 UTC, jborean93 requested changes
Are you able to add some integration tests for this. We should have a sanity test target that allows you to test the working and failure case added here.

2023-12-08 08:56 UTC, tremble commented
@jborean93 Happy to add them, but didn't want to waste time on it if this wasn't a direction the team wanted this to go.

2023-12-08 10:18 UTC, jborean93 commented
The general consensus in triage was that we would like to potentially provide a way to use a different format for things like toml but this doesn't mean we can't support this in the meantime.

2023-12-08 23:50 UTC, jborean93 approved these changes
Looks great thanks for the tests.

2023-12-13 20:18 UTC, merged