Missing Exception Handling in SSH Plugin Fixed Error Verbosity Issue#…
ansible/ansible pull request #82354
Opened 2023-12-05 07:13 UTC by Hacodex

…58133

##### SUMMARY

- Added error verbosity for sshpass errors 1-6 excluding 5
- raised an exception if no_log
- converted erroneous command to text

##### ISSUE TYPE

- Bugfix Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

2023-12-05 17:40 UTC, Hacodex commented
#58133

2023-12-07 19:46 UTC, jborean93 requested changes
Are you able to add a changelog fragement for this change at https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment.

2023-12-07 19:46 UTC, jborean93 commented on lib/ansible/plugins/connection/ssh.py
> +                1: "sshpass: Invalid command line argument. Command given ({})".format(cmd_error),
I would avoid embedding the stderr for this and the next one in case it contains sensitive information that should not be exposed in `no_log`.

2025-01-17 15:20 UTC, Akasurde commented
superseded by https://github.com/ansible/ansible/pull/84539

2025-01-17 15:20 UTC, closed without merging