Rename git module option gpg_whitelist to gpg_allowlist
ansible/ansible pull request #82377
Opened 2023-12-07 12:48 UTC by sedrubal

##### SUMMARY

Rename the `gpg_whitelist` option of git module to `gpg_allowlist` (and add an alias to avoid breaking existing workflows). This is a small step towards a more inclusive tech industry. Using the word "black" with negative connotations and "white" with positive is discouraged. More information can be found in this article:

https://www.businessinsider.com/companies-github-terms-master-slave-blacklist-whitelist-open-source-2020-6?op=1

##### ISSUE TYPE

- Feature Pull Request

2023-12-07 15:04 UTC, bcoca requested changes
Add changelog and note in the description 'gpg_allowlist name was added in 2.17 and we will eventually deprecate the gpg_whitelist alias' or similar

2023-12-07 15:36 UTC, sedrubal commented
Thank you. I added a changelog fragment. I hope, the way I did it is correct :wink:

2024-01-12 16:33 UTC, bcoca approved these changes

2024-03-15 22:43 UTC, Akasurde commented
/azp run

2024-03-15 22:49 UTC, merged