ci: run docs-build checkers from ansible-documentation
ansible/ansible pull request #82405
Opened 2023-12-11 22:25 UTC by gotmax23

##### SUMMARY

Now that ansible-core and documentation are in separate repos, it's
possible for core changes to be merged that break docs, as happened this
past Friday. Docs failures were always a blocker for merging core PRs
(there used be sanity tests in core that do the same thing that
ansible-documentation's docs checkers now do), so it would be nice to
keep that to make everyone's jobs easier.

Relates: https://github.com/ansible/ansible/pull/82361

/cc @samccann oraNod

##### ISSUE TYPE

- Test Pull Request

2023-12-12 15:23 UTC, samccann commented
Thanks for this @gotmax23 !

2023-12-12 15:23 UTC, samccann approved these changes
Can't comment on the code but it's definitely something that will improve the docs workflow, thanks!

2023-12-12 15:31 UTC, sivel commented
Just curious, can you link to whatever failure there was?  I'm curious as to what the failure was caused by.

2023-12-12 15:41 UTC, sivel commented
I also note that this is using GitHub actions which I don't think is going to work for us, due to the restrictions in place within this GH org.  This will likely need to be integrated into a new test target to run within our current CI workflow.  We'll likely not get back to this until January; Just giving a heads up on the probable direction this PR would need to go.

2023-12-12 16:24 UTC, gotmax23 commented
Thanks for the quick response!

> Just curious, can you link to whatever failure there was? I'm curious as to what the failure was caused by.

Doc builds broke after https://github.com/ansible/ansible/pull/82361 was merged. `# fmt: code` was not supported by antsibull-docs, so we had to scramble to fix it, cut a new release, and update the antsibull-docs version used by the docs.


> I also note that this is using GitHub actions which I don't think is going to work for us, due to the restrictions in place within this GH org. This will likely need to be integrated into a new test target to run within our current CI workflow. We'll likely not get back to this until January; Just giving a heads up on the probable direction this PR would need to go.

Fair enough. Github Actions has worked well enough for us in the ansible-documentation repo, but I understand you all may have different requirements. I'm not particularly familiar with core's CI set up, but I can look into it if you can give me a pointer.


> docs/ansible-core-branch.txt:0:0: directory "docs/" is obsolete and should not contain any files

What should I do about this one and the package-data test? Should this marker file be moved somewhere else or should I update the sanity test to exclude this file? If it should be moved, where? Should the file be included in the sdist?

2024-01-02 21:59 UTC, mattclay requested changes
One of the reasons for moving `docs/` out of core was to eliminate the dependency on the docs build. We shouldn't be trying to restore that dependency.

Looking at the underlying issue, this appears to be a gap in our sanity tests around usage of `# fmt:` comments in plugin docs. That's something we should be correcting in validate-modules instead.

2024-01-03 20:31 UTC, felixfontein commented
@mattclay validate-modules couldn't have prevented this, since the break was caused by a missing feature / bug (depends on how you think about it) in antsibull-docs.

IMO it makes sense to have the docs build as a "non-voting" test here so docs folks can be pinged when it fails to figure out what the problem is (preferably *before* the PR is merged and the docs build breaks for `devel`).

2024-01-03 20:58 UTC, mattclay commented
If validate-modules checked `# fmt:` comments for allowed types, then we'd know when changes make use of unsupported values. That would give us an opportunity to revise the list and notify anyone as needed before enabling new types.

Doing that gives us a common specification to work from (in this case, allowed types). That's a more specific test than running checks from an external repository (in this case, ansible-documentation).

2024-01-03 21:04 UTC, felixfontein commented
That's definitely helpful for the future!

2024-01-03 21:08 UTC, felixfontein commented
There's still the issue with *other* unexpected situations that will break the docs build though, with no advance warning if the docs build is not run in ansible-core PRs.

2024-01-03 21:18 UTC, mattclay commented
> There's still the issue with _other_ unexpected situations that will break the docs build though, with no advance warning if the docs build is not run in ansible-core PRs.

That's true for any project that depends on this repository. Rather than running tests (voting or not) from other repositories, we should ensure that the tests in this repository accurately reflect what we've agreed to provide to our users. If there are deficiencies in our tests, we should address those specifically, rather than relying on external tests to fill in those gaps.

2024-01-03 21:35 UTC, bcoca commented
That is what devel and milestone tags are for, it is fine that something breaks temporarily

2024-01-03 21:42 UTC, gotmax23 commented
> That is what devel and milestone tags are for, it is fine that something breaks temporarily

We build docs for all supported core versions, so changes from stable branches can also break docs builds. My goal was to implement this CI job there as well.

2024-01-03 21:46 UTC, bcoca commented
out backports require going through devel, so that should be a very rare issue. The only thing i suggest is that a failed build leaves the site untouched.

2024-01-03 21:59 UTC, samccann commented
Others can correct me here, but I thought what triggered all this was the problem wasn't breaking the publishing, but the actual ansible-documentation CI.  So all PRs failed CI because of this external problem.

2024-01-03 22:04 UTC, bcoca commented
@samccann if that is the case, everything works as intended, that is the right place to find breaking changes with upstream deps

2024-01-30 22:32 UTC, samccann commented
hey folks, as you're probably aware, we had another docs CI breakage after the prettify PR merged (I think that's the one). Anyway, I'm open to suggestions on how we can either prevent or get a heads up that something is going to break.

For any files related to the `ansible-docs` code, could we have a label automagically added to the PR? Then we can keep an eye or something so we can test prior to merging here and have a fix 'ready' so to speak.

Another random idea - is there a 'shorter/simpler/ docs CI we could consider adding to ansible/ansible, or is that notion just off the table entirely?

thanks!

2025-06-04 06:18 UTC, mattclay commented
While we won't be adding ansible-documentation builds to the tests in this repo, we are open to improving our own tests to verify the content in this repo, as noted in https://github.com/ansible/ansible/pull/82405#issuecomment-1875985584.

2025-06-04 06:18 UTC, closed without merging