iptables module: Enable support for pmtu clamp
ansible/ansible pull request #82537
Opened 2024-01-14 15:36 UTC by potvinp

##### SUMMARY

Fixes #82525

iptables has a native option to clamp the MSS within a rule to the path MTU. This patch enables support for this option. An example rule is:
```
iptables -A POSTROUTING -o eth1 -p tcp -m tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
```

##### ISSUE TYPE
- Feature Pull Request

2024-01-15 20:11 UTC, webknjaz commented on test/units/modules/test_iptables.py
> +            '--tcp-flags', 'SYN,RST SYN'
If you don't put a comma between subsequent strings, Python concatenates them implicitly, during parsing:
```suggestion
            '--tcp-flags', 'SYN,RST SYN',
```

2024-01-15 20:13 UTC, webknjaz requested changes
Why is this sent against an old branch? ansible-core 2.13 is EOL and no longer supported. All PRs must be sent against `devel` and then backported to stable branches only if they are bugfixes.

2024-01-16 15:34 UTC, Akasurde commented on lib/ansible/modules/iptables.py
> +    version_added: "2.13"
```suggestion
    version_added: "2.17"
```

2024-01-16 15:34 UTC, Akasurde commented on lib/ansible/modules/iptables.py
> +  clamp_mss_to_pmtu:
Please create a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment). See [this fragment](https://github.com/ansible/ansible/blob/c2f528b7686c9573aa8493357219e0bbe4416dd3/changelogs/fragments/reboot-change-default-boot-command.yaml) as an example.

2024-01-18 17:15 UTC, sivel commented
It looks like this PR was submitted directly against the stable-2.13 branch.  2.13 is now end of life, and not accepting changes.  Independent of that, aall changes need to be merged to devel first, and then based on the release lifecycle, individual changes will be backported to older versions as necessary.  Since this is a new feature, if it were merged to devel now it would appear in the upcoming 2.17 release.

I'm going to proceed with closing this PR.  Please feel free to rebase against devel, and create a new pull request.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible-devel on irc.libera.chat
   * mailing list: https://groups.google.com/forum/#!forum/ansible-devel

2024-01-18 17:15 UTC, closed without merging