Fix Creating user directory using tilde always reports "changed"
ansible/ansible pull request #83113
Opened 2024-04-21 11:47 UTC by yctomwang

##### SUMMARY

Fixes the issue of when Creating user directory using tilde, ansible always reports "changed"(https://github.com/ansible/ansible/issues/82490). along with an integration test to prevent regression. Fixed this issue through changing the spec from 'string' to 'path' for shell. This allowed for auto expansion of the tilde in user provided shell variable.

Fixes #82490 
##### ISSUE TYPE

- Bugfix Pull Request

##### ADDITIONAL INFORMATION

2024-04-22 13:58 UTC, Akasurde requested changes

2024-04-22 13:58 UTC, Akasurde commented on test/integration/targets/user/tasks/test_create_user.yml
> +    shell: ~/custom_shell
```suggestion
  user:
    name: bob
    shell: ~/custom_shell
  register: user_create_result
```

2024-04-22 13:58 UTC, Akasurde commented on test/integration/targets/user/tasks/test_create_user.yml
> +    fail_msg: "Failure: User state was changed, We expect it to be same."
```suggestion
- name: Assert that the user with a tilde in the shell path is created
  assert:
    that:
      - user_creation_result is not changed
      - user_create_result is changed
```

2024-04-22 13:58 UTC, Akasurde commented on lib/ansible/modules/user.py
> +        type: path
Add a note stating the change like this - 

```
- From Ansible 2.18, the type is changed to I(path) from I(str).

2024-04-23 02:37 UTC, yctomwang commented
@Akasurde Hi, thanks for the code review, I have applied changes you have suggested. I am not sure as to why the tests are failing on FreeBSD, I dont have that locally, I will try to look into it on the weekend or something by trying to get a VM with FreeBSD on it and run the ansible tests.

2024-05-08 14:34 UTC, bcoca commented
its failing because the user 'doesnotmatter' already exists, revert back to 'bob'.

2024-05-09 13:15 UTC, yctomwang commented
@bcoca Hi, the reason why i changed to 'doesnotmatter' is because 'bob' was failiing aswell, the playbook was giving back showing that changed is false which is suspicous,so I thought 'bob' might already exist. It still doesnot explain why its failing on the FreeBSD regardless.

2024-06-23 10:29 UTC, yctomwang commented
@Akasurde Hi there, its been a while since I followed up on this PR. I have finally gotten myself a FreeBSD14 so i can run these integration test local and figure out why its failing for FreeBSD, can you please retrigger this pipeline for this PR? Thanks.

2024-07-07 19:19 UTC, Akasurde commented
/azp run

2024-07-07 19:20 UTC, Akasurde approved these changes

2024-07-07 19:26 UTC, merged