Update distro version in __init__.py
ansible/ansible pull request #83114
Opened 2024-04-21 18:08 UTC by mishrahrishikesh

Update the bundled package distro from 1.6.0 to 1.9.0 in __init__.py

##### SUMMARY

Latest package of distro has been released and it has been changed from 1.6.0 to 1.9.0 in __init__.py file.

##### ISSUE TYPE

- Bugfix Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

2024-04-22 13:48 UTC, Akasurde requested changes

2024-04-22 13:48 UTC, Akasurde commented on lib/ansible/module_utils/distro/__init__.py
> +_BUNDLED_METADATA = {"pypi_name": "distro", "version": "1.9.0"}
```suggestion
_BUNDLED_METADATA = {"pypi_name": "distro", "version": "1.8.0"}
```

2024-04-22 13:48 UTC, Akasurde commented on lib/ansible/module_utils/distro/__init__.py
> +_BUNDLED_METADATA = {"pypi_name": "distro", "version": "1.9.0"}
The current version of https://github.com/python-distro/distro is set to 1.8.0.

2024-04-23 15:26 UTC, Akasurde approved these changes

2024-04-23 15:26 UTC, merged

2024-04-23 15:59 UTC, mattclay commented
This was a follow-up to https://github.com/ansible/ansible/pull/81765, which updated `distro` to 1.8.0 without updating `_BUNDLED_METADATA` to match.

2024-04-23 16:06 UTC, Akasurde commented
Thanks @mattclay.