Ensure meta tasks don't disrupt host_pinned host/fork affinity
ansible/ansible pull request #83249
Opened 2024-05-13 22:35 UTC by sivel

##### SUMMARY

Ensure meta tasks don't disrupt host_pinned host/fork affinity

##### ISSUE TYPE

- Bugfix Pull Request

##### ADDITIONAL INFORMATION

Tests to come later

2024-05-14 20:54 UTC, sivel commented
<details>
<summary>Reproducer...</summary>
<p>

```
.
├── ansible.cfg
│   │ [defaults]
│   │ forks = 2
├── hosts
│   │ localhost0
│   │ localhost1
│   │ localhost2
│   │ localhost3
│   │ localhost4
│   │ localhost5
│   │ localhost6
│   │ localhost7
│   │ localhost8
│   │ localhost9
│   │
│   │ [all:vars]
│   │ ansible_connection=local
│   │ ansible_python_interpreter={{ansible_playbook_python}}
├── include_me.yml
│   │ - debug:
│   │     msg: include
│   │
│   │ - meta: noop
└── playbook.yml
    │ - hosts: all
    │   gather_facts: false
    │   strategy: host_pinned
    │   tasks:
    │     - name: start
    │       debug:
    │         msg: start
    │
    │     - wait_for:
    │         timeout: '{{ groups.all.index(inventory_hostname) // 2 }}'
    │
    │     - include_tasks:
    │         file: include_me.yml
    │
    │     - name: end
    │       debug:
    │         msg: end
```

</p>
</details>

2024-05-15 16:28 UTC, sivel commented
This implementation has a shortcoming, in that meta only tasks won't break out of the inner loop.  This can result in an extra non-meta task executing early.

2024-05-15 17:37 UTC, sivel commented
The last commit may fix the previously noted shortcoming

2024-06-18 09:19 UTC, mkrizek requested changes

2024-06-18 09:19 UTC, mkrizek commented on lib/ansible/plugins/strategy/free.py
> +                        task_count += 1
I believe counting tasks is not sufficient. Say there are 3 hosts and 2 forks.

At the top of the inner loop, first iteration: the first host is still executing a long running regular non-meta task from previous iteration and therefore is blocked and skipped: still `workers_free == 1`.

Second iteration, the second host is about to execute a meta task and does so: `workers_free == 1`, `task_count == 1`.

With the state of the counters above the inner loop continues to the third iteration and the third host can queue/execute a task (either regular or meta task) and only then the loop would end (either via `workers_free == 0` or `task_count == 2 == fork_max`... and the fact that there are no more hosts left but we wouldn't get to that check) resulting in 3 hosts executing on 2 forks 💥

Carefully crafted playbook to demonstrate:

```yaml
- hosts: localhost0,localhost1,localhost2
  gather_facts: false
  strategy: host_pinned
  tasks:
    - debug:
        msg: start

    - command: sleep 3
      when: inventory_hostname == "localhost0"

    # e.g. role_complete via include_role
    - meta: noop

    # e.g. flush_handlers
    - meta: noop

    - debug:
        msg: end
```

https://github.com/ansible/ansible/pull/83437 and https://github.com/ansible/ansible/pull/83438 handle this scenario.

2024-08-13 15:40 UTC, closed without merging