Fix file changed detection for get_url in check mode
ansible/ansible pull request #83617
Opened 2024-07-16 09:46 UTC by jorg-vr

##### SUMMARY

This pr revives https://github.com/ansible/ansible/pull/65703 and fixes https://github.com/ansible/ansible/issues/65687

Actually preforming the get request, even in check mode, results in the correct checksums being compared.

I prefer this solution over only checking if the file exists, as for our use case it is also important that the new file has the same content as the file on the remote url.
I can also compromise on making both those options available, depending on a variable. But that will make the code more complex.

##### ISSUE TYPE
- Bugfix Pull Request

##### ADDITIONAL INFORMATION

I have removed the mentions off `HEAD` in the integration tests. The tests themselves did not seem to require a change.

It would be useful to also add a test on the actual issue: should not report changed when dest and source file are already the same. But I wasn't completely sure on how to write that.

```paste below
None
```

2024-07-16 13:30 UTC, webknjaz commented
/azp run

2024-07-23 15:20 UTC, mkrizek requested changes
This is not a fix, this effectively disables `check_mode`. Instead we should document the existing behavior.

2024-07-23 16:46 UTC, bcoca commented
`check_mode` cannot be perfect in all circumstances, specifically in this action it can be very unreliable due to how web servers and clients are implemented, configured and "understand standards differently". It cannot guarantee that the HEAD requests will return the exact same result that a GET would, but doing a GET bypasses the whole point of having a 'light weight' check.

If the `check_mode` for this module does not work well for your case, you can bypass using it, but removing it from the code breaks it for those cases in which it does work, specially when the request itself is costly.

2024-07-29 11:58 UTC, jorg-vr commented
Although I understand that my solution doesn't fit the lightweight philosophy, the current HEAD approach is just odd.

`check_mode` now compares the checksum of the HEAD result with the checksum of the file on disk.

Either this assumes the result of the HEAD request to be the same as the GET request, in which case it wouldn't matter to replace it by a GET request.
Or this check is completely nonsensical, as this will always flag 'changed=true'.

So I don't agree with 'Instead we should document the existing behavior.'

A solution I might agree on is disabling the checksum compare in check_mode (and documenting that) if the lightweightness of the functionality is prioritized.

2024-07-29 14:01 UTC, s-hertel commented
> Either this assumes the result of the HEAD request to be the same as the GET request, in which case it wouldn't matter to replace it by a GET request.

It would matter. A HEAD request retrieves metadata from an object without returning the object body itself. GET can be an expensive operation, so doing it in check mode breaks expectations.

This module has [partial check_mode support](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/get_url_module.html#attribute-check_mode), it could probably be clearer. I don't think we should disable check mode though since `check_mode: false` can be set on tasks to override `--check`.

2024-08-02 07:22 UTC, jorg-vr commented
I don't see the usecase of the partial support. I know the difference between `HEAD` and `GET`, that is why i added:

> Or this check is completely nonsensical, as this will always flag 'changed=true

But I understand that you are happy with the current state. So I will close this pr.
I would suggest also closing the related issue as won't fix. Because the only suggested fix is updating documentation, but the documentation already matches the current implementation in my opinion.

Anyway thanks all for reviewing this pr and for all your work on this project!

2024-08-02 07:23 UTC, closed without merging