remove ignore clauses for module uri
ansible/ansible pull request #83642
Opened 2024-07-20 05:17 UTC by russoz

##### SUMMARY

Remove the cases in `ignore.txt` for the module `uri`.

Case 1: doc-required-mismatch
Add parameter `url` in the module, overriding the one from `url_argument_spec()`.

##### ISSUE TYPE

- Bugfix Pull Request

2024-07-20 16:33 UTC, flowerysong requested changes

2024-07-20 16:33 UTC, flowerysong commented on lib/ansible/modules/uri.py
> +        url=dict(type='str', required=True),
```suggestion
    argument_spec = url_argument_spec()
    argument_spec['url']['required'] = True
    argument_spec.update(
```

2024-07-20 16:33 UTC, flowerysong commented on changelogs/fragments/83642-fix-sanity-ignore-for-uri.yml
> +  - uri - minor refactor (https://github.com/ansible/ansible/pull/83642).
```suggestion
bugfixes:
  - uri - mark ``url`` as required (https://github.com/ansible/ansible/pull/83642).
```

This doesn't change the structure of the code, so it's not a refactor (and it's better to be specific anyway.) This fixes the error returned when the module is called without this required parameter, so it's a bugfix.

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: a bytes-like object is required, not 'str'
fatal: [localhost]: FAILED! =>
    changed: false
    elapsed: 0
    msg: 'Status code was -1 and not [200]: An unknown error occurred: a bytes-like object
        is required, not ''str'''
    redirected: false
    status: -1
    url: null
```
vs.
```
fatal: [localhost]: FAILED! =>
    changed: false
    msg: 'missing required arguments: url'
```

2024-08-20 09:20 UTC, russoz commented
hi @Akasurde m could you please confirm if there is anything else needed in this PR? TIA

2024-11-07 14:43 UTC, Akasurde commented
/azp run

2024-11-07 14:56 UTC, merged