fix: adds color included
ansible/ansible pull request #83711
Opened 2024-08-02 17:04 UTC by akire0ne

##### SUMMARY

Fixes: https://github.com/ansible/ansible/issues/83663

##### ISSUE TYPE

- Bugfix Pull Request

##### ADDITIONAL INFORMATION

Adds a new parameter to set color for Included tasks. Prior to that, the included tasks used the same color as `COLOR_SKIP` parameter. This made differentiating the `included` and `skipped` tasks a bit hard in some occurrence.

2024-08-02 17:08 UTC, akire0ne commented
Not all colors seems to work with this... I will investigate a bit before putting this "Ready for review" ...

with `ANSIBLE_COLOR_INCLUDED=red` , everything OK

![image](https://github.com/user-attachments/assets/636a71a1-9e41-44d8-b6f6-e202e15f6481)

with `ANSIBLE_COLOR_INCLUDED=magenta`, it works but displays a Warning ?

![image](https://github.com/user-attachments/assets/be97d7ba-a295-4bb5-891b-71b7f26c7a03)

2024-08-02 17:13 UTC, bcoca commented
it is not about the color, but the config and it's value. this happens in the 'color to log level' mapping, which does not contain the new color config, https://github.com/ansible/ansible/blob/devel/lib/ansible/utils/display.py#L172

2024-08-02 17:23 UTC, akire0ne commented
Indeed this seems to do the trick @bcoca 
![image](https://github.com/user-attachments/assets/7b2fbacc-be2e-4224-b7da-b5a1a4dbc060)

2024-08-02 17:46 UTC, bcoca commented
related #83712, this should 'fix' the issue also, but keeping color JIC people are using display in 'fun' ways, will incorporate new config from this ticket once merged.

2024-08-08 19:08 UTC, bcoca commented on lib/ansible/config/base.yml
> +  - {key: included, section: colors}
needs version_added

2024-08-08 19:09 UTC, bcoca requested changes
Also this requires a changelog

2024-08-09 10:12 UTC, akire0ne commented on lib/ansible/config/base.yml
> +  - {key: included, section: colors}
All done

2024-08-09 14:25 UTC, bcoca approved these changes

2024-08-09 14:26 UTC, merged