dnf5,apt: add auto_install_module_deps option
ansible/ansible pull request #84292
Opened 2024-11-11 11:32 UTC by mkrizek

##### SUMMARY
Fixes #84206

##### ISSUE TYPE

- Feature Pull Request

2024-11-11 20:30 UTC, webknjaz commented
/azp run

2024-11-19 19:17 UTC, mattclay requested changes

2024-11-19 19:17 UTC, mattclay commented on test/integration/targets/dnf5/playbook.yml
> +        - name: Test the auto_install_module_deps option
Add a task to ensure `python3-libdnf5` is absent before this test, in case it has already been installed in the environment.

2024-11-19 19:22 UTC, nitzmahone reviewed
Agree w/ Matt's comment that it should probably explicitly uninstall the deps as part of the test, but otherwise LGTM.

2024-11-20 17:13 UTC, mattclay approved these changes

2024-11-21 16:05 UTC, sivel approved these changes

2024-11-21 16:06 UTC, merged