Fix integration tests on debian
ansible/ansible pull request #84379
Opened 2024-11-23 12:56 UTC by leegarrett

##### SUMMARY

Couple of fixes to make the integration tests work again on Debian. Currently ansible project CI tests don't run against Debian, but Debian downstream does.

##### ISSUE TYPE

- Test Pull Request

2024-11-25 15:22 UTC, webknjaz commented
/azp run

2025-01-02 22:16 UTC, mattclay commented
/azp run

2025-01-02 22:33 UTC, mattclay commented on test/integration/targets/hostname/tasks/Debian.yml
> +      - "ansible_distribution_release ~ '-bebop.ansible.example.com' in grep_hostname.stdout"
What's the Debian related change here? Or is this just a syntax cleanup?

2025-01-03 09:45 UTC, leegarrett commented on test/integration/targets/hostname/tasks/Debian.yml
> +      - "ansible_distribution_release ~ '-bebop.ansible.example.com' in grep_hostname.stdout"
It's code that likely worked in the past, but throws an error in current ansible releases. It went unnoticed because CI doesn't test against Debian (only Ubuntu).

2025-01-03 18:22 UTC, mattclay commented on test/integration/targets/hostname/tasks/Debian.yml
> +      - "ansible_distribution_release ~ '-bebop.ansible.example.com' in grep_hostname.stdout"
What error do you get without this change?

2025-01-24 16:13 UTC, Akasurde commented
@leegarrett, Could you please paste the error you encountered in Debian and rebase this PR? Thanks.

2025-01-26 18:14 UTC, leegarrett commented on test/integration/targets/hostname/tasks/Debian.yml
> +      - "ansible_distribution_release ~ '-bebop.ansible.example.com' in grep_hostname.stdout"
The error I get is:
```
TASK [hostname : Test DebianStrategy using assertions] *************************
[WARNING]: conditional statements should not include jinja2 templating
delimiters such as {{ }} or {% %}. Found: '{{ ansible_distribution_release
}}-bebop.ansible.example.com' in get_hostname.stdout
fatal: [testhost]: FAILED! => {"msg": "The conditional check ''{{ ansible_distribution_release }}-bebop.ansible.example.com' in get_hostname.stdout' failed. The error was: Conditional is marked as unsafe, and cannot be evaluated."}
```

A small caveat: I get this error in release 2.18.1, not against devel.

2025-01-26 18:15 UTC, leegarrett commented
@Akasurde Sure, did so in the thread. I also rebased it against devel again.

2025-01-26 18:31 UTC, leegarrett commented
Also dropped `fc94f51530 Remove redundant task`, this was a commit not intended for this PR.

2025-01-27 20:12 UTC, leegarrett commented on test/integration/targets/hostname/tasks/Debian.yml
> +      - "ansible_distribution_release ~ '-bebop.ansible.example.com' in grep_hostname.stdout"
I noticed that I only get this error on 2.18.1 and not on devel, so I bisected it. #83922 introduces the regression. I assume it's not failing on devel because there's no data tagging in place yet.

2025-02-17 16:02 UTC, leegarrett commented
Gentle ping. Does this need any action on my side?

2025-02-18 01:45 UTC, mattclay commented
/azp run

2025-02-18 02:03 UTC, mattclay requested changes

2025-02-18 02:03 UTC, mattclay commented on test/integration/targets/service/tasks/main.yml
> +  when: ansible_service_mgr not in ['rc', 'systemd', 'sysv', 'upstart']
This incorrectly skips the tests on FreeBSD because `ansible_service_mgr` is `bsdinit`. Instead of including only systems listed here, it would be safer to exclude systems known not to be supported. That would avoid issues like this, where skipped tests could easily go undetected.

2025-02-18 14:08 UTC, leegarrett commented on test/integration/targets/service/tasks/main.yml
> +  when: ansible_service_mgr not in ['rc', 'systemd', 'sysv', 'upstart']
Indeed. Good point. I've fixed the issue in the last commit.

2025-02-18 21:33 UTC, mattclay approved these changes

2025-02-18 21:33 UTC, merged