`with_dict` type error include value in error message
ansible/ansible pull request #84473
Opened 2024-12-17 18:22 UTC by simonLeary42

##### SUMMARY

I have been struggling with jinja2 and `with_dict`, and to solve it I had to find the error message in the ansible source code, open `plugins/lookup/dict.py` in vscode, make a breakpoint, run `ansible-playbook` with the vscode python debugger with `justmycode: false`, and then I got to see what was the value that my jinja2 expression returned. Ansible should just tell me the value. The `sublements` lookup already does this: https://github.com/ansible/ansible/blob/cae4f90b21bc40c88a00e712d28531ab0261f759/lib/ansible/plugins/lookup/subelements.py#L135

##### ISSUE TYPE

- Feature Pull Request

2024-12-17 20:30 UTC, bcoca commented
Hi,

Thanks for your contribution, but to be complete it should have tests and a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#making-your-pr-merge-worthy).

The full Core contributor guide https://docs.ansible.com/ansible/latest/community/contributions.html

2024-12-18 16:38 UTC, Akasurde approved these changes

2024-12-24 23:57 UTC, flowerysong commented on lib/ansible/plugins/lookup/dict.py
> +                raise AnsibleError(f"with_dict expects a dict, got '{term}' of type {type(term)})")
As long as we're improving things: the lookup is just called `dict`. `with_dict` is one way to use the `dict` lookup, but not the only one.

2025-01-07 15:06 UTC, Akasurde requested changes

2025-01-07 15:06 UTC, Akasurde commented on lib/ansible/plugins/lookup/dict.py
> +                raise AnsibleError(f"with_dict expects a dict, got '{term}' of type {type(term)})")
```suggestion
                raise AnsibleError(f"lookup dict expects a dictionary, got '{term}' of type {type(term)})")
```

2025-01-07 15:18 UTC, Akasurde approved these changes

2025-01-07 16:21 UTC, bcoca commented on lib/ansible/plugins/lookup/dict.py
> +                raise AnsibleError(f"lookup dict expects a dictionary, got '{term}' of type {type(term)})")
To be more explicit `The 'dict' lookup expects ...`

2025-01-14 15:21 UTC, merged